### PR TITLE
fix: persist refresh token for IDP token exchange

### LINKED ISSUE #14644: External IDP tokens are not refreshed automatically for OAuth2 & OIDC IDPs when retrieving the external token
### Describe the bug

We're using Github (specifically a Github app) as an external IDP. We have configured Github to use expiring access tokens (good for 8 hours). When we want to get data from Github on behalf of the user, such as a list of repositories where the Github app is installed, we need a Github [user-to-server access token](https://docs.github.com/en/rest/apps/installations#list-app-installations-accessible-to-the-user-access-token).

We can retrieve these external IDP tokens from keycloak via [this endpoint](https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens).

Unfortunately, if it has been more than 8 hours, then the access token is expired and the request to Github will fail. If I use the refresh token (which is also returned from the endpoint above), to get new tokens from Github, this works _once_. I get a new access and refresh token, and I can make a request to Github with the access token. However, this _expires_ the refresh token that Keycloak has. And there doesn't seem to be a way for me to give Keycloak the new access/refresh tokens that I've retrieved on behalf of the user.

Is this just an oversight? Is there any way to use Github as an external IDP with expiring access tokens?

### Version

19.0.2

### Expected behavior

1. Keycloak refreshes tokens _before_ returning them from `GET /realms/{realm}/broker/{provider_alias}/token` (provided the current `refresh_token` has not expired).

### Actual behavior

Keycloak appears to just return the exact response that it originally receives from Github, which is most likely an expired access token. If the refresh token is still good, it is worthless because using it will expire the one held in Keycloak.

### How to Reproduce?

Use Github as an external IDP with expiring tokens and try to use the endpoint as described above.

### Anything else?

_No response_

### LINKED ISSUE #39502: Refreshed tokens are not persisted for IDP token exchange
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

When exchanging an internal token to an external IDP token, and the token is not persisted when the token is  refreshed.

It is only kept in-memory for the current node, and due to that it is not available to other nodes in the cluster of when the node is restarted.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The refreshed token should be persisted.

### Actual behavior

It is not persisted

### How to Reproduce?

See the test in the connected PR

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by abhishek818**
Closes #39502

Save the newly refreshed token in the database, so that on keycloak restart/session purge scenario, subsequent token refresh exchanges always uses the updated refresh token.

### CODE REVIEW

**Comment by abhishek818** [comment]
@thomasdarimont @pedroigor Putting this for review or please tag relevant SME's for the code review..

**Comment by opiredev** [comment]
The user @abhishek818 has claimed all the rewards in #14644 👀 We've notified the reward creators [here](https://github.com/keycloak/keycloak/issues/14644#issuecomment-2227367068).
@abhishek818 make sure you have your [payment account ready](https://app.opire.dev/settings) to receive the payment for your hard work 💪

**Comment by psardana** [comment]
@thomasdarimont any update on this when this could be reviewed and released?

**Comment by thomasdarimont** [comment]
@abhishek818 Thanks for your contribution! 

Could you please remove the merge commit and just rebase your branch on top of main?

@pedroigor I think this PR is quite useful and contains a working test. I think we should integrate this for Keycloak 26 and additionally add this to the backports (24.x and 25.x) as it resolves a real issue in practice.

**Comment by ahus1** [comment]
Thank you @thomasdarimont for haing a look here. I see that the test case `testRefreshTokenPersistence` which is added in this PR fails. While the test is necessary to show that this works as expected, the test would need to pass before this PR can be merged.

**Comment by abhishek818** [comment]
@thomasdarimont @ahus1 Can you approve the workflows? 
I am able to build the code locally but unable to run the tests. I have tried following steps mentioned here [HOW-TO-RUN.md](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md). Do you recommend any steps/doc or which server mode to focus on (Keycloak on embedded undertow, on Quarkus or an embedded server) ?

**Comment by abhishek818** [comment]
I ran the tests thru github actions in my forked repo, its passing.

**Comment by ahus1** [comment]
@thomasdarimont - tests are green now.

**Comment by psardana** [comment]
@ahus1 this will be released in v26 or before?

**Comment by ahus1** [comment]
@psardana - first we'll need to get this PR ready which will get it into Keycloak 26. Once that is done, we can think about backporting it to Keycloak 25 which is IMHO possible given that the change is not so big.

**Comment by psardana** [comment]
> @psardana - first we'll need to get this PR ready which will get it into Keycloak 26. Once that is done, we can think about backporting it to Keycloak 25 which is IMHO possible given that the change is not so big.

Okay. Thanks for the update

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java [hunk 1]
```diff
@@ -1220,4 +1220,27 @@ public void testSetEmptyAttributeValues() {
             adminClient.realm(realmName).remove();
         }
     }
+
+    @Test
+    public void testRefreshTokenPersistence() {
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java:1225]: This test is not correct as it does not test at all the scenario from the description.

I've tried to copy/paste the test to my fork and it passed even without your change in the `OIDCIdentityProvider` . Which is because the test you added just adds the regular refresh token (without any involvement from identity brokering...)

The correct test is the one, which really tests the scenario you are fixing. So likely should fail without your change and should pass after your change. AFAIK the scenarios related to OIDC identity brokering and token exchange are in `KcOidcBrokerTokenExchangeTest`

**Review by mposolda — COMMENTED** [review]
@abhishek818 Added the comment regarding the test. Can you please check it?

**Comment by rasika** [comment]
Hi everyone, any timelines on when this could be reviewed and released?

File: services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java [hunk 2]
```diff
@@ -240,6 +240,7 @@ protected Response exchangeStoredToken(UriInfo uriInfo, EventBuilder event, Clie
                 }
                 model.setToken(response);
                 tokenResponse = newResponse;
+                session.users().updateFederatedIdentity(authorizedClient.getRealm(), tokenSubject, model);
             } else if (exp != null) {
```
Comment (Parvezkhan0) [inline services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java:244]: Consider adding null checks for model and authorizedClient to avoid potential runtime issues when persisting the federated identity. This will ensure robustness in cases where these objects might unexpectedly be null.

**Review by Parvezkhan0 — DISMISSED** [review]

**Comment by larsw** [comment]
What's stopping this from being merged and is there anything I can do to help with the impediment(s)?

File: services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java (hunk 2 above)
Comment (larsw) [reply services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java:244]: IMHO this review comment is redundant, since both `authorizedCLient` and `tokenSubject` has already been used on line 196.

**Comment by kneringerjohann** [comment]
can we add another available reviewer in here as @mposolda  seems to be not available? this one is on hold for a while...

**Review by kneringerjohann — APPROVED** [review]

**Comment by larsw** [comment]
What stops this from being merged?

**Comment by kneringerjohann** [comment]
> What stops this from being merged?

i guess @mposolda approval. can someone else review this?

**Comment by ahus1** [comment]
I started to look into this PR, and I found that the test case doesn't address the code changes. An updated test case is in the works. 

While the changes in this PR are valid, I think they don't address (all) the issue described in the parent issue.

**Comment by ahus1** [comment]
As this PR is unrelated to the originally linked issue, I now liked it to a new issue #39502

**Comment by ahus1** [comment]
@rmartinc / @mposolda - I've added a test case to this change that breaks without the change and is green with the change. So I'd say it is now good to be merged. 

Please review when you have the time. Thanks!

**Comment by ahus1** [comment]
There is now a follow-up PR #39508 which attempts to address #14644

**Review by mposolda — APPROVED** [review]
@ahus1 @abhishek818 LGTM, Thanks!

@ahus1 During the merge, it would be good to make sure that the commits are somehow squashed and updated the message, so the merge does not close also #14644 , which is not solved by this PR per my understanding.
