### PR TITLE
Fix stale client session is present in user session

### LINKED ISSUE #17570: UserSessionEntity can contain stale ClientSession references
When a client session expires and the corresponding user session does not, the loaded user session still contains a reference to the already expired client session.

When a client session is loaded, we check whether it is expired; if not, we return null.

The presence of a stale client session reference can cause an issue in the following scenario:
1. Create a user session and a client session where the client session has lower expiration than the user session
2. Move in time after the client session is expired
3. Create a new client session for the same client as in step 1

In step 3 we detect whether the client session already exists for the client and [remove it](https://github.com/keycloak/keycloak/blob/340025b412d7d14673d55932b87506bc468fabfd/model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java#L123). This is not executed for HotRod because it detects client session is not present in the cache as it expired.

Then we add the newly created client session. This adds another client session reference for the same `clientId`. In this case, when we obtain a client session for the given client we sometimes (depends on the Set::stream order) hit the expired client session and we return `null` client session because the one we hit is expired.

To fix that, we need to remove the stale reference when we encounter it.

### PR DESCRIPTION
**Pull request by mhajas**
Closes #17570

### CODE REVIEW

File: model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java [hunk 1]
```diff
@@ -79,20 +77,33 @@ private MapUserSessionEntity wrapUserSessionEntityToClientSessionAwareDelegate(M
         if (entity == null) return null;
 
         return new MapUserSessionEntityDelegate(new SimpleDelegateProvider<>(entity)) {
+
+            private boolean filterAndRemoveNotExpired(MapAuthenticatedClientSessionEntity clientSession) {
+                if (!clientSessionTransaction.exists(clientSession.getId())) {
+                    // If client session does not exist, remove the reference to it from userSessionEntity loaded in this transaction
+                    entity.removeAuthenticatedClientSession(clientSession.getClientId());
```
Comment (stelewis-redhat) [inline model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java:84]: Is this N possible hits to the database or just one?

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/HotRodUserSessionClientSessionRelationshipTest.java [hunk 2]
```diff
@@ -114,6 +118,38 @@ public void testSessionsAreRemovedOnRealmRemoval() {
...
+        prepareSessions(uSessionId, cSessionId);
+
+        // Move in time when client session should be expired but user session not
+        setTimeOffset(70);
+
+        // Try to create a new client session for the same user session
+        withRealm(realmId, (session, realm) -> {
+            ClientModel client = realm.getClientByClientId(CLIENT0_CLIENT_ID);
+            UserSessionModel uSession = session.sessions().getUserSession(realm, uSessionId.get());
+            assertThat(session.sessions().createClientSession(realm, client, uSession), notNullValue());
```
Comment (martin-kanis) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/session/HotRodUserSessionClientSessionRelationshipTest.java:142]:
```suggestion
            assertThat(uSession.getAuthenticatedClientSessions(), anEmptyMap());
            assertThat(session.sessions().createClientSession(realm, client, uSession), notNullValue());
```

File: model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java [hunk 3]
```diff
@@ -79,20 +77,33 @@ private MapUserSessionEntity wrapUserSessionEntityToClientSessionAwareDelegate(M
         if (entity == null) return null;
 
         return new MapUserSessionEntityDelegate(new SimpleDelegateProvider<>(entity)) {
+
+            private boolean filterAndRemoveNotExpired(MapAuthenticatedClientSessionEntity clientSession) {
+                if (!clientSessionTransaction.exists(clientSession.getId())) {
```
Comment (martin-kanis) [inline model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java:82]: I noticed that `exists` method now defaults to "read by id". Shouldn't we override `exists` method in `NoActionHotRodTransactionWrapper`?

**Review by martin-kanis — COMMENTED** [review]
Thanks Michal for the PR. Please see my two comments.

File: model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java (hunk 1 above)
Comment (mhajas) [reply model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java:84]: @stelewis-redhat thank you for the review. I am not following your question. Could you please elaborate a little bit?

File: model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java (hunk 3 above)
Comment (mhajas) [reply model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java:82]: we should, I created a new issue for that: https://github.com/keycloak/keycloak/issues/19196

**Review by martin-kanis — APPROVED** [review]

File: model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java (hunk 1 above)
Comment (stelewis-redhat) [reply model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java:84]: I think my mental model of the data is wrong, after thinking about this a bit more.

If this gets called in a loop, "removeAuthenticateClientSession" does something like "delete from blah where blah_id=<id>" which is fine. In the SQL world, one could optimize a little by "delete from blah where blah_id in (<id1>, <id2>)" which isn't really possible, since HotRod isn't the SQL world.

In sum: nevermind.

Comment (mhajas) [reply model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java:84]: This is a correct suggestion, however, it is not applicable in current context.

What is happening here is the following:
If we have one user session (U1) that has 3 client sessions (C1, C2, C3). The user session entity contains 3 references to each client sessions. 

In JSON form It would be something like this:
```json
"U1": {
    // ..........
    clientSessions: [C1.id, C2.id, C3.id],
    // ..........
    }
```

Now, when any of the client sessions expire, they are removed from cache. However, the reference in the U1 is still there. Therefore, when Keycloak loads client sessions for U1, we need to check each client session whether it still exists, that is what we are doing on line 82 (this was done also prior to this PR). However, we also need to clean that reference from the U1 (which is added in this PR), otherwise it is still present in Infinispan and can cause some trouble. 

So in this loop we are calling delete for each client session we find out is missing (it is already removed from Infinispan). What  are doing is basically removing ids from the `Set` within U1 and at the end of the transaction we call `replace` on whole U1 entity.

**Review by hmlnarik — APPROVED** [review]
Approving per @martin-kanis 's review
