### PR TITLE
Make sure refresh token expiration is based on the current time when the token is issued

### LINKED ISSUE #27180: Grant type "urn:ietf:params:oauth:grant-type:uma-ticket" openid-connect/token service endpoint is returning refresh token with invalid Expiration
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

When upgraded to version 23 from 21, started experiencing invalid refresh token expiration time for Authorization service with grant type "urn:ietf:params:oauth:grant-type:uma-ticket".
Flow:
Step 1: UI level authentication process calls token service with grant type "grant_type: authorization_code"
Step 2:  Resource Authorization process calls token service with grant type "urn:ietf:params:oauth:grant-type:uma-ticket". With this step, received refresh token expiration time remains unchanged but, issue time gets updated properly.

With version 21, Step2 returns updated expiration and issue time.
In my application, Step 2 gets executed frequently so, eventually it enters into a situation with expiration time is greater than issue time and fails in refresh-token grant.

### Version

23

### Regression

- [ ] The issue is a regressions

### Expected behavior

Resource Authorization token service call with grant type "urn:ietf:params:oauth:grant-type:uma-ticket" should return refresh_token with updated expiration and issue time.  

### Actual behavior

Resource Authorization token service call with grant type "urn:ietf:params:oauth:grant-type:uma-ticket" is returning refresh_token with unchanged expiration time.  

### How to Reproduce?

Attached simple Nodejs script can be used to re-create the issue.
Step 1: npm install
Step 2: Provide keycloak details in the .env file
Step 3: npm run start

Script first Authenticates and then runs Authorization with resource server (grant type "urn:ietf:params:oauth:grant-type:uma-ticket") in a loop of 5 times. Script produces difference between issue and expiration of refresh token and access token.
[keycloak-script.zip](https://github.com/keycloak/keycloak/files/14354140/keycloak-script.zip)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #27180 
Needs #27574

* When issuing tokens, the expiration time for refresh tokens should be based on when the token is being issued and not from the last time the client session was refreshed.

The problem being fixed here is more evident when using the permission grant type because for this grant type we are not creating new user/client sessions on every token request like when doing client credentials (where a new user session is created all the time).

I'm not 100% sure if the fix here is the best because the time stamp from the client session should not be used to set the expiration time for refresh tokens but the time the token response is being created. For this reason, marking it as a draft for now.

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java [hunk 1]
```diff
@@ -1141,24 +1141,25 @@ public AccessTokenResponseBuilder generateRefreshToken(String scope) {
         }
 
         private void generateRefreshToken(boolean offlineTokenRequested) {
+            refreshToken = new RefreshToken(accessToken);
+            refreshToken.id(KeycloakModelUtils.generateId());
+            refreshToken.issuedNow();
+            clientSessionCtx.getClientSession().setTimestamp(Time.currentTime());
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java:1147]: @pedroigor I don't know much about authz but in general refresh token the user and client session timestamps are updated in [refreshAccessToken](https://github.com/keycloak/keycloak/blob/37cdc95bf3cc741b64fc3666233ccc29793444fd/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L431-L433). Probably in the authz execution path that method is not called, but then I think that updating `lastSessionRefresh` in the user session is also needed (check if it's needed or it's done in another place).

Comment (pedroigor) [reply services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java:1147]: We don't and the behavior is that you would need a refresh token so they don't become idle.

But regarding the change, doesn't make more sense to just ise the `iat` to calculate the expiration time? In this method we are creating a refresh token so why use the timestamp from the client session?

Comment (pedroigor) [reply services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java:1147]: Also, whenever we issue a refresh token, the `lastSessionRefresh` should also be updated in the user session, no? 

That is what I'm trying to point out here ... We are actually issuing a new set of tokens so the sessions should not get idle if you are operating in the same (or a new) user/client session.

Comment (rmartinc) [reply services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java:1147]: @pedroigor Yes, if a refresh token is issued both sessions timestamps are updated, but right now for normal refresh is done in the other method [refreshAccessToken](https://github.com/keycloak/keycloak/blob/37cdc95bf3cc741b64fc3666233ccc29793444fd/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L431-L433). I suppose in authz the other method is not executed, right?

In that case I think you also need to update the user session lastSessionRefresh like in the other method.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java]: @rmartinc Just update the PR to make clear what I'm trying to point out. Based on what you are saying, we should update the sessions (both user and client) whenever a refresh token is issued/created.

I've also updated this method https://github.com/keycloak/keycloak/pull/27577/files#diff-cbee120571b12f77f69db4cb51c259afea6d79df968c65b9879ab0b633b3db4fR142 to always take the `iat` as a input for the expiration rather than the "lastRefreshed". AFAIK, that was how the expiration was calculated before (not using the session timestamp) where the current time was used. Does this part make sense for you too?

**Review by rmartinc — APPROVED** [review]
Thanks @pedroigor! Approved!

**Review by mposolda — APPROVED** [review]
@pedroigor Thanks for the PR

Relying on @rmartinc review
