### PR TITLE
Fix TimeUnit function and TimeUnit2 function

### LINKED ISSUE #9488: Setting "24 mins" to timeout, the admin console displays "1 day"
### Describe the bug

In the timeout view, when I set "24 mins" to timeout and click the save button, 
timeunit

the admin console displays "1 day".
timeunit2

### Version

16.1.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by y-tabata**
Closes #9488

I fixed the following behavior.
- When we set multiple of 24 to timeout of minutes, the admin console converts it and displays the timeout of days.

The TimeUnit2 function is for almost all timeouts, and the TimeUnit function is for example for brute force protection.

### CODE REVIEW

File: themes/src/main/resources/theme/base/admin/resources/js/services.js [hunk 1]
```diff
@@ -1589,15 +1589,16 @@ module.factory('TimeUnit', function() {
         if (time % 60 == 0) {
             unit = 'Minutes';
             time  = time / 60;
+            if (time % 60 == 0) {
+                unit = 'Hours';
+                time = time / 60;
+                if (time % 24 == 0) {
+                    unit = 'Days'
+                    time = time / 24;
```
Comment (tnorimat) [inline themes/src/main/resources/theme/base/admin/resources/js/services.js:1597]: Is the line `time = time / 24;` needed?

**Review by tnorimat — COMMENTED** [review]
@y-tabata I've reviewed this PR and added one comment. Could you check it?

File: themes/src/main/resources/theme/base/admin/resources/js/services.js (hunk 1 above)
Comment (y-tabata) [reply themes/src/main/resources/theme/base/admin/resources/js/services.js]: I left it because it existed in the original logic, but I removed it because it is certainly unnecessary.

**Review by tnorimat — APPROVED** [review]
LGTM

**Review by jonkoops — APPROVED** [review]
Not a fan of the level of nesting, but the code does what it needs to do. LGTM :+1:
