### PR TITLE
moved keycloak to context so it can be updated

### LINKED ISSUE #11931: user first name not refreshed in Keycloak V2 theme
### Describe the bug

User's first name was updated and saved. But on the top-right corner, the new info is not updated. It still shows “test“
Screen Shot 2022-05-10 at 1 04 04 PM

### Version

16.1.1

### Expected behavior

Profile info near sign out button to be updated

### Actual behavior

Profile info near sign out button is not updated

### How to Reproduce?

Edit user's first name and click save. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #11931

### CODE REVIEW

File: js/libs/keycloak-masthead/src/util.ts [hunk 1]
```diff
@@ -1,15 +1,18 @@
-import Keycloak from "keycloak-js";
+import { KeycloakTokenParsed } from "keycloak-js";
```
Comment (jonkoops) [inline js/libs/keycloak-masthead/src/util.ts:1]:
```suggestion
import { type KeycloakTokenParsed } from "keycloak-js";
```

File: js/libs/keycloak-masthead/src/KeycloakContext.tsx [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+export const KeycloakProvider = ({
+  keycloak,
+  children,
+}: PropsWithChildren<KeycloakProviderProps>) => {
+  const [token, setToken] = useState(keycloak.tokenParsed);
+  const updateToken = async () => {
+    await keycloak.updateToken(-1);
+    setToken(keycloak.tokenParsed);
+  };
+  console.log("what", keycloak, token, updateToken);
```
Comment (jonkoops) [inline js/libs/keycloak-masthead/src/KeycloakContext.tsx:27]: Stray console log.

File: js/apps/account-ui/src/personal-info/PersonalInfo.tsx [hunk 3]
```diff
@@ -38,6 +39,7 @@ export const fieldName = (name: string) =>
 
 const PersonalInfo = () => {
   const { t } = useTranslation();
+  const context = useKeycloak();
```
Comment (jonkoops) [inline js/apps/account-ui/src/personal-info/PersonalInfo.tsx:42]: Can we name this something other than `context`?
```suggestion
  const keycloak = useKeycloak();
```

File: js/libs/keycloak-masthead/src/KeycloakContext.tsx [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+  return (
+    <KeycloakContext.Provider value={{ keycloak, token, updateToken }}>
```
Comment (jonkoops) [inline js/libs/keycloak-masthead/src/KeycloakContext.tsx:29]: This will always be a new object, so I would recommend wrapping it in a `useMemo()` to prevent re-renders.

File: js/libs/keycloak-masthead/src/KeycloakContext.tsx [hunk 5]
```diff
@@ -0,0 +1,33 @@
+import Keycloak, { KeycloakTokenParsed } from "keycloak-js";
+import { createContext, PropsWithChildren, useContext, useState } from "react";
+
+type KeycloakProps = {
+  keycloak?: Keycloak;
```
Comment (jonkoops) [inline js/libs/keycloak-masthead/src/KeycloakContext.tsx:5]: Under which circumstances would the Keycloak instance not be defined? Perhaps this can be made required?
```suggestion
  keycloak: Keycloak;
```

File: js/libs/keycloak-masthead/src/KeycloakContext.tsx [hunk 6]
```diff
@@ -0,0 +1,33 @@
+import Keycloak, { KeycloakTokenParsed } from "keycloak-js";
```
Comment (jonkoops) [inline js/libs/keycloak-masthead/src/KeycloakContext.tsx:1]:
```suggestion
import type Keycloak, { KeycloakTokenParsed } from "keycloak-js";
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Comment by jonkoops** [comment]
@edewit there are some failing checks, can you take a look?

**Review by jonkoops — APPROVED** [review]
