### PR TITLE
Admin console localizate realm name

### LINKED ISSUE #48084: Admin console localizate realm name
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The realm name in the Admin console takes on some places is localized, so if it matches the messages.properties key, it's translated to that. But it should not. If the display name is set, it should be used. Otherwise, only the plain name should be used. 

Clearly visible here:

https://github.com/user-attachments/assets/21018bb8-c7ab-4191-8806-fb825a033e47

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Realm name is not localized

### Actual behavior

Realm name is localized

### How to Reproduce?

- Create a new realm with the name 'custom'
- Look at the Admin console and you can see the name as "Custom attributes"

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #48084

@ssilvert @edewit Could you please check it? 

Works as expected:

https://github.com/user-attachments/assets/ae1ea24c-c519-4300-b5a5-eea7c2c853f1

### CODE REVIEW

**Review by edewit — CHANGES_REQUESTED** [review]
so I see that you now have introduced 2 ways to not translate the realm display name. Via the `resolveRealmDisplayName` that only translates when there is a "bundle key" and in the ViewHeader where you added a "no translation property". I don't think both of those are needed. You only need `resolveRealmDisplayName`

**Comment by edewit** [comment]
on top of this this is something that is used everywhere also for client names, not just for display name

File: js/apps/admin-ui/src/utils/realm-utils.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { isBundleKey, label } from "@keycloak/keycloak-ui-shared";
+import { TFunction } from "i18next";
+
+export const resolveRealmDisplayName = (
+  t: TFunction,
+  displayName?: string,
+  fallback = "",
+) => {
```
Comment (rmartinc) [inline js/apps/admin-ui/src/utils/realm-utils.ts:8]: As @edewit has commented, I think that this can be re-used for more things like clients in the future. Maybe you can use a generic `resolveDisplayName` and add it to the general `src/util.ts` instead of adding a new utils file.

File: docs/documentation/release_notes/topics/26_7_0.adoc [hunk 2]
```diff
@@ -0,0 +1,10 @@
+// Release notes should contain only headline-worthy new features,
+// assuming that people who migrate will read the upgrading guide anyway.
+
+= Administration
+
+== Realm display name no longer accidentally translated
```
Comment (rmartinc) [inline docs/documentation/release_notes/topics/26_7_0.adoc:6]: I don't know if a release note is really needed. It's just a change in the name of the realm and now it will be OK, previously they can be a non related string, which IMO was a bug. But if you think that it is needed, this can be maintained.

File: js/apps/admin-ui/src/components/view-header/ViewHeader.tsx [hunk 3]
```diff
@@ -100,7 +102,11 @@ export const ViewHeader = ({
                     component="h1"
                     data-testid="view-header"
                   >
-                    {i18n.exists(titleKey) ? t(titleKey) : titleKey}
+                    {noTranslate
+                      ? titleKey
+                      : i18n.exists(titleKey)
+                        ? t(titleKey)
+                        : titleKey}
```
Comment (rmartinc) [inline js/apps/admin-ui/src/components/view-header/ViewHeader.tsx:109]: Just a nitpick but maybe it's better to do an or here:

```suggestion
                    {noTranslate || !i18n.exists(titleKey)
                      ? titleKey
                      : t(titleKey)}
```

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx [hunk 4]
```diff
@@ -123,6 +124,7 @@ const RealmSettingsHeader = ({
       />
       <ViewHeader
         titleKey={realmName}
+        noTranslate
```
Comment (rmartinc) [inline js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx:127]: @edewit I see this OK, I think that @mabartos is trying to not re-translate what it was translated before. Not a lot chances to have it in the i18n but not a bad addition. WDYT?

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @mabartos! LGTM! Just a few comments.

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx (hunk 4 above)
Comment (edewit) [reply js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx:127]: A component either uses a label or a text this now introduces that the text could be a label or the actual text and it's not clear that `noTranslate` means: e.g. do not translate the titleKey. I would rather have it that we rename it to `title` and call it with `title={t('the-key')}` everywhere

File: docs/documentation/release_notes/topics/26_7_0.adoc (hunk 2 above)
Comment (mabartos) [reply docs/documentation/release_notes/topics/26_7_0.adoc]: @rmartinc Yep, we can remove it.

File: js/apps/admin-ui/src/utils/realm-utils.ts (hunk 1 above)
Comment (mabartos) [reply js/apps/admin-ui/src/utils/realm-utils.ts]: @rmartinc Done.

File: docs/documentation/release_notes/topics/26_7_0.adoc (hunk 2 above)
Comment (mabartos) [reply docs/documentation/release_notes/topics/26_7_0.adoc]: @rmartinc Done

File: js/apps/admin-ui/src/components/view-header/ViewHeader.tsx (hunk 3 above)
Comment (mabartos) [reply js/apps/admin-ui/src/components/view-header/ViewHeader.tsx]: @rmartinc Done

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx (hunk 4 above)
Comment (mabartos) [reply js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx:130]: @edewit Ok, created a follow-up spike issue:
- https://github.com/keycloak/keycloak/issues/48496

**Review by edewit — APPROVED** [review]

**Review by rmartinc — APPROVED** [review]
Thanks @mabartos! LGTM now.
