### PR TITLE
Fix typo in consent scope

### LINKED ISSUE #40786: Typo in Consent Scope Representation
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

There's a typo in the response of the `/account/applications` endpoint

Image

### Version

26.2.5

### Regression

- [ ] The issue is a regression

### Expected behavior

It should return `displayText`

### Actual behavior

It returns `displayTest`

### How to Reproduce?

Do a request to the `/account/applications` endpoint

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SferaDev**
Closes #40786

### CODE REVIEW

**Comment by ahus1** [comment]
Adding a "hold" label as this would be a breaking change to the current users of the API

File: core/src/main/java/org/keycloak/representations/account/ConsentScopeRepresentation.java [hunk 1]
```diff
@@ -23,15 +23,22 @@ public class ConsentScopeRepresentation {
 
     private String name;
 
+    /**
+     * @deprecated Use {@link #displayText} instead. This field will be removed in KC 27.0.
+     */
+    @Deprecated
     private String displayTest;
```
Comment (ahus1) [inline core/src/main/java/org/keycloak/representations/account/ConsentScopeRepresentation.java]: Could you please remove this deprecated field, and only keep the new one? Then the old getter/setter would only point to that new field. IMHO this should be enough to create the right JSON, and parse the JSON correctly, assuming people will send one or the other.

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for the PR. See below for one suggested change.

File: core/src/main/java/org/keycloak/representations/account/ConsentScopeRepresentation.java (hunk 1 above)
Comment (SferaDev) [reply core/src/main/java/org/keycloak/representations/account/ConsentScopeRepresentation.java]: You're right, I've double checked and the getter and setter in the representation are enough. Thanks!

image

**Review by ahus1 — APPROVED** [review]
