### PR TITLE
Fix ID token not being sent after expiration for OIDC logout

### LINKED ISSUE #10164: id_token_hint for external IDP not sent after token expiry
### Describe the bug

For external IDPs like Okta, the OIDC logout flow requires the original federated id_token be sent during logout as a id_token_hint query parameter. However, I see that this happens only as long as the original access tokens acquired from the external IDP have not expired. Once they expire, the oidc logout redirect does not contain this id_token_hint parameter.

### Version

16.1.1

### Expected behavior

id_token_hint should be sent in logout url always, irrespective of expiry of tokens

### Actual behavior

id_token_hint is not sent after the external IDP's original access token has expired. It does not matter if I call keycloak's /token endpoint to get updated tokens. For example, if my okta access token expiry is 15 minutes, and my keycloak client's access token expiry is 5 minutes, I am able to logout properly upto 15 minutes only (id_token_hint parameter is being passed). Post that, Okta throws an error like 
`{"errorCode":"invalid_client","errorSummary":"A client_id must be provided in the request.","errorLink":"invalid_client","errorId":"oaeU-8_B1DtRZSPMvZMIV5QCw","errorCauses":[]}`
which essentially is due to id_token_hint not being passed in.

### How to Reproduce?

_No response_

### Anything else?

I'm using Keycloak 16.1.1 docker image, and the keycloak-js npm library from calling logout(). Using Frontchannel logout.
Snippets of the frontend code:
```
import Keycloak from "keycloak-js";

const _kc = new Keycloak({
  url: keycloakUrl,
  realm: realmName,
  clientId: KEYCLOAKCLIENTID,
});

const initKeycloak = (onAuthenticatedCallback) => {
  _kc
    .init({
      onLoad: "login-required",
      pkceMethod: "S256",
      token: localStorage.getItem("access_token"),
      refreshToken: localStorage.getItem("refresh_token"),
      // enableLogging: true
    })
    .then((authenticated) => {
      if (authenticated) {
        saveTokens({
          access_token: _kc.token,
          refresh_token: _kc.refreshToken,
        });
        onAuthenticatedCallback();
      } else {
        doLogin();
      }
    });
};
const logout = () => {
    clearTokens(); // from localStorage, defined elsewhere
    _kc.logout();
};

const updateToken = () =>
  _kc
    .updateToken(60)
    .then((refreshed) => {
      if (refreshed) {
        // Save tokens in localstorage (defined elsewhere) if successfully refreshed
        saveTokens({
          access_token: _kc.token,
          refresh_token: _kc.refreshToken,
        });
        return Promise.resolve();
      } else {
        // Show login screen otherwise.
        doLogin();
      }
    })
    .catch((error) => {
      return Promise.reject(error);
    });
_kc.onTokenExpired = () => updateToken();
```

### PR DESCRIPTION
**Pull request by Szer**
Closes #10164

OIDC spec recommend sending id_token_hint regardless of expiration

https://openid.net/specs/openid-connect-rpinitiated-1_0.html

Quotes:

### id_token_hint
**RECOMMENDED**. ID Token previously issued by the OP to the RP passed to the Logout Endpoint as a hint about the End-User's current authenticated session with the Client. This is used as an indication of the identity of the End-User that the RP is requesting be logged out by the OP.
...
When an id_token_hint parameter is present, the OP MUST validate that it was the issuer of the ID Token. The OP SHOULD accept ID Tokens when the RP identified by the ID Token's aud claim and/or sid claim has a current session or had a recent session at the OP, **even when the exp time has passed**. If the ID Token's sid claim does not correspond to the RP's current session or a recent session at the OP, the OP SHOULD treat the logout request as suspect, and MAY decline to act upon it.

### CODE REVIEW

**Comment by Szer** [comment]
@mposolda any chance you could look at it again?

**Comment by Szer** [comment]
@mposolda sure thing! Thank you for pointing me in the right direction I'll try to add tests asap!

**Comment by Akireken** [comment]
Hello @Szer, thanks for the PR !

I've open a duplicate issue and start to investigate and correct few days ago on the fix. I'm looking for this correction soon so if I can help for testing, I will be glad.

Thanks :)

**Comment by Szer** [comment]
@Akireken @mposolda I'll be honest I feel stuck with the test.

What I want to achieve in the test - assert that `idp_login_hint` is being passed to IDP regardless of expiration
What I did - called IDP login, got `id_token`, fast-forwarded time in future, called login

Now, to the tricky part. How to observe that?
With backchannel logout it is being called [asynchronously through HTTP call](https://github.com/keycloak/keycloak/blob/972ebb96505bf2ac3164ab4a3bf51c62e3324ead/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L143-L161)
I couldn't find a way how to make sure that KC made that call

So I decided to disable backchannel logout for these tests.

Now logout became a [302 redirect](https://github.com/keycloak/keycloak/blob/972ebb96505bf2ac3164ab4a3bf51c62e3324ead/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L182) but WebDriver is so fast with redirects, I couldn't find a way to observe that it happens.

I'm probably missing something as I'm not having the full context of the KC developer here. Do you have some advice on how to make that assertion correctly?

**Comment by mposolda** [comment]
@Szer Thanks, I hope that for example `KcOidcBrokerLogoutTest.logoutAfterBrowserRestart()` can be used for the "inspiration" as that one is doing also some logout with `id_token_hint` ?

I think that after logout, you should be redirected to the `consumer` page. When attempt to click on the `login with IDP` link from `consumer` realm login page, you should be redirected to the `provider` realm login page, which means that previous logout was successful and was propagated for both `consumer` and `provider` realm.

**Comment by Akireken** [comment]
Hello @Szer, since I doesn't have any news seen fews days, I would like to know if your are still on this PR. I need this fix for my project and I don't want to duplicate PRs. If you can't work on it, can you give me access in order to let me try to work on it :) ?

Thanks

**Comment by Akireken** [comment]
@Szer thanks for access !

I submitted a PR on your branch fews days agos but seem it was not obvious. Sorry for lack of communication. Already test it in localhost, and it work for me also ;).

Other than that, I think we need to test behaviors and not implementation at Selenium type test level, so I've came to the same solution than @mposolda : testing logout work for idp even when token expired.

Here are modification I have made :
- I've change back KcOidcBrokerLogoutTest to use original configuration to keep original scope of thoses tests
- I've change assertion to verify user is logout from idp as other test do
- I've add a KcOidcBrokerLogoutFrontChannelTest in order to test logout from idp without backchannel (not tested before)

Fork synchronized and branch rebase

**Comment by Akireken** [comment]
@mposolda is it possible to have a review on the last changes ?

**Comment by Akireken** [comment]
Hello @mposolda , I'm coming back to have news. Is it possible to have a review on last changes please ?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java [hunk 1]
```diff
@@ -1,26 +1,21 @@
...
 
 import static org.junit.Assert.assertEquals;
-import static org.keycloak.testsuite.admin.ApiUtil.createUserWithAdminClient;
-import static org.keycloak.testsuite.admin.ApiUtil.resetUserPassword;
-import static org.keycloak.testsuite.broker.BrokerTestConstants.REALM_CONS_NAME;
-import static org.keycloak.testsuite.broker.BrokerTestConstants.REALM_PROV_NAME;
-import static org.keycloak.testsuite.broker.BrokerTestTools.waitForPage;
-import static org.keycloak.testsuite.broker.BrokerTestTools.getConsumerRoot;
-import static org.keycloak.testsuite.broker.BrokerTestTools.getProviderRoot;
+import static org.keycloak.testsuite.broker.BrokerTestConstants.*;
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java:15]: We try to avoid "stars" in the imports and static imports. Can you please revert to avoid using stars here?

**Review by mposolda — CHANGES_REQUESTED** [review]
@Szer @Akireken Thanks a lot for your joint effort! I've added one very minor comment inline regarding imports in the test. But overally looks good. Hope we're very close to have this in...

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java (hunk 1 above)
Comment (Akireken) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java]: Done

**Review by mposolda — APPROVED** [review]
@Akireken Thanks!

Hope tests are ok

**Comment by mposolda** [comment]
@Akireken @Szer Thanks!

**Comment by Akireken** [comment]
Hey, just see that my name disapear from the keycloak repo. Is it still possible to be credited as co-author ?

**Comment by mposolda** [comment]
@Akireken Looks like a mistake. I guess it can be caused by the fact that you guys collaborated in the branch, from which the PR was originally sent, and you were not mentioned as co-author in the commit https://github.com/keycloak/keycloak/pull/16593/commits/faebf25c3947845575f0acd6813d6c80ad94e9bb where "your PR to the original PR branch" was squashed... Not sure... I should likely doublecheck that you're author during squash, so I am sorry for not doing that :-(

Unfortunately, we cannot change the history as that would have some other side-effects. Hopefully it won't happen in the future.
