### PR TITLE
Optimize querying sub-groups of groups

### LINKED ISSUE #12080: Bad Map storage performance with lots of groups in a realm when evaluating subgroups
### Describe the bug

The current implementation streams all groups from the database to retrieve the parent groups. 

While this is correct, it is not efficient. as all entities are fetched from the realm, wrapped as model elements, and then filtered. 

from: MapGroupAdapter.java
```
    @Override
    public Stream<GroupModel> getSubGroupsStream() {
        return session.groups().getGroupsStream(realm)
                .filter(groupModel -> getId().equals(groupModel.getParentId()));
    }
```

### Version

999-SNAPSHOT

### Expected behavior

The parent groups should be filtered from the database.

### Actual behavior

All entities are fetched from the DB and are de-serialized and wrapped.

### How to Reproduce?

CreateGroups in keycloak-benchmark

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #12080

### CODE REVIEW

**Comment by ahus1** [comment]
I wonder if there should be a new method in the GroupProvider interface, or if that query should be run directly by the MapGroupAdapter once it has the transaction passed in from the constructor. Please let me hear your thoughts.

File: model/map/src/main/java/org/keycloak/models/map/group/MapGroupAdapter.java [hunk 1]
```diff
@@ -101,8 +102,8 @@ public String getParentId() {
 
     @Override
     public Stream<GroupModel> getSubGroupsStream() {
-        return session.groups().getGroupsStream(realm)
-                .filter(groupModel -> getId().equals(groupModel.getParentId()));
+        // TODO: make this a proper interface on GroupProvider
+        return ((MapGroupProvider) session.getProvider(GroupProvider.class)).getGroupsByParentId(realm, this.getId());
```
Comment (mhajas) [inline model/map/src/main/java/org/keycloak/models/map/group/MapGroupAdapter.java:106]:
```suggestion
        return ((MapGroupProvider) session.groups()).getGroupsByParentId(realm, this.getId());
```

**Review by mhajas — COMMENTED** [review]
That's not nice. Good catch @ahus1! At the moment, we are not passing the transaction to any adapter and I am not sure we should start doing that. 

In my opinion, the correct thing to do is to introduce a new method to the provider.

File: model/map/src/main/java/org/keycloak/models/map/group/MapGroupAdapter.java (hunk 1 above)
Comment (hmlnarik) [inline model/map/src/main/java/org/keycloak/models/map/group/MapGroupAdapter.java:106]: We need to think of other approach due to following constraints:
- System-wide group provider might not be a map provider originating this group.

Do you recall the trick with anonymous adapter below? Perhaps would be useful in here.
https://github.com/keycloak/keycloak/blob/44cd6cd5fb6811853405e9ba3b6d1624dc280f2e/model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java#L61-L66

Something like this in the `MapGroupProvider`:
```java
    private Function<MapGroupEntity, GroupModel> entityToAdapterFunc(RealmModel realm) {
        // Clone entity before returning back, to avoid giving away a reference to the live object to the caller
        return origEntity -> new MapGroupAdapter(session, realm, origEntity) {
            public Stream<GroupModel> getSubGroupsStream() {
                return getGroupsByParentId(realm, this.getId());
            }
        };
    }
```

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thanks for the PR. Please find the comments inline

File: model/map/src/main/java/org/keycloak/models/map/group/MapGroupAdapter.java (hunk 1 above)
Comment (mhajas) [reply model/map/src/main/java/org/keycloak/models/map/group/MapGroupAdapter.java:106]: This would work. However, I am not quite following what you mean by `System-wide group provider might not be a map provider originating this group.` What other provider could be originating this group?

Comment (hmlnarik) [reply model/map/src/main/java/org/keycloak/models/map/group/MapGroupAdapter.java:106]: Any group provider. We cannot anticipate all the future uses.

Taking an example from current state - today there is `RealmCacheSession` and `JpaRealmProvider` implementing group provider. Could a `GroupAdapter`s originating from `JpaRealmProvider` rely on the fact that its originator is `session.groups()`?

Still in this case, we need to redirect the call to `getSubGroupsStream()` to the same provider's `getGroupsByParentId` - and the only way I can see at this moment is to override it in the anonymous class created in the provider itself.

Comment (mhajas) [reply model/map/src/main/java/org/keycloak/models/map/group/MapGroupAdapter.java:106]: Given other implementations of `GroupProvider` running alongside `MapGroupProvider`, are we sure that only `MapGroupProvider` originating this entity contains its children? 

If we count on this scenario in the future, shouldn't we use `session.groups()` everywhere rather than searching only within `MapGroupProvider`?

**Comment by ahus1** [comment]
I pushed a change that includes the update as @hmlnarik suggested. It also adds a missing index. 

When reading the code, I found the comment "Clone entity before returning back, to avoid giving away a reference to the live object to the caller" in MapGroupProvider, and also in other place. 

Looking at the code, it seems to me that that comment is no obsolete as I don't see any cloning happening there. I'd therefore remove it here and in all other places (or open a new issue as this is not relevant for this issue)

**Review by mhajas — APPROVED** [review]
Thank you @ahus1, the PR LGTM. 

I think you are right with the obsolete comment. Transactions should be responsible for cloning the entity before returning it. I don't know whether it should be removed here or in a separate issue, but I don't think not removing it blocks this PR so I am approving.

**Comment by hmlnarik** [comment]
> I don't know whether it should be removed here or in a separate issue [...]

Let's treat it in a separate issue.

**Review by hmlnarik — APPROVED** [review]
Thanks for the PR!
