### PR TITLE
Register custom functions via FunctionContributor

### LINKED ISSUE #16336: Hibernate 6 upgrade: JSON functions need to be registered using new APIs
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

In Hibernate 6, custom functions have to be registered using new APIs. There seems to be a hook in the dialects (PostgresDialect and CockroachDialect) via the `initializeFunctionRegistry` method, but the preferred way seems to be via `MetadataBuilderContributor`.

I've attempted to use the contributor as it is already used to register the custom `JsonbType`, and apparently was able to register the `->>` function (test of an actual query that uses this function was not yet done, but hibernate stopped complaining about unrecognized function).

We need to check if this is being done correctly and also register the `->` and `@>` functions. One tricky thing about `->` is that it has a `JsonbType` return type, and we need to check how exactly to map that when registering the function.

### Version

quarkus3 branch

### Expected behavior

All JSON functions used in map storage should be properly registered/tested with Hibernate 6

### Actual behavior

Only `->>` function is registered and we're not sure the approach taken is the correct one for that.

### How to Reproduce?

User quarkus3 branch.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vramik**
Closes #16336

Creating draft as https://github.com/keycloak/keycloak/issues/16496 might be a prerequisite for this one as there is `JsonbPostgreSQL95Dialect` removed within this PR.

### CODE REVIEW

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/contributor/JpaMapFunctionContributor.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+    }
+
+    private void contributeDbSpecificFunctions(FunctionContributions fc) {
+        Dialect dialect = getDialect(fc);
+        if (dialect instanceof PostgreSQLDialect) {
+            fc.getFunctionRegistry().registerPattern("kc_hash", "sha256(?1::bytea)", getBasicType(fc, StandardBasicTypes.BINARY));
+        } else if (dialect instanceof CockroachDialect) {
+            fc.getFunctionRegistry().registerPattern("kc_hash", "sha256(?1)", getBasicType(fc, StandardBasicTypes.STRING));
+        } else {
+            throw new UnsupportedOperationException("not supported");
```
Comment (hmlnarik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/contributor/JpaMapFunctionContributor.java:64]: This should log a warning that a dialect is not recognized instead. If an exception is thrown, it will not be possible to extend this functionality for other databases using extensions which would register their `FunctionContributor` implementations.

**Review by hmlnarik — COMMENTED** [review]
LGTM up to one thing, thank you @vramik!

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/contributor/JpaMapFunctionContributor.java (hunk 1 above)
Comment (vramik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/contributor/JpaMapFunctionContributor.java:64]: Thanks. I will update it. I wanted to go with fail-fast approach for now, but I agree with the argument.

**Comment by hmlnarik** [comment]
@vramik Could you please rebase?

**Comment by vramik** [comment]
> @vramik Could you please rebase?

Rebased.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/contributor/JpaMapFunctionContributor.java [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    }
+
+    private void contributeDbSpecificFunctions(FunctionContributions fc) {
+        Dialect dialect = getDialect(fc);
+        if (dialect instanceof PostgreSQLDialect) {
+            fc.getFunctionRegistry().registerPattern("kc_hash", "sha256(?1::bytea)", getBasicType(fc, StandardBasicTypes.BINARY));
+        } else if (dialect instanceof CockroachDialect) {
+            fc.getFunctionRegistry().registerPattern("kc_hash", "sha256(?1)", getBasicType(fc, StandardBasicTypes.STRING));
+        } else {
+            LOG.warnf("Dialect % not recognized.", dialect);
```
Comment (hmlnarik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/contributor/JpaMapFunctionContributor.java:68]:
```suggestion
            LOG.warnf("Dialect %s not recognized.", dialect);
```

**Review by hmlnarik — APPROVED** [review]
