### PR TITLE
Fix embedded theme-resources lookup in Keycloak.X

### LINKED ISSUE #9653: Keycloak.X cannot lookup embedded theme-resources from extension jars
### Describe the bug

The Wildfly based Keycloak distribution supports accessing embedded templates from `theme-resources` folder in extension jars. 

The Keycloak.X distribution fails to resolve templates form `theme-resources`. 
During  boostrap the `ProviderManager` is configures a `KeycloakDeploymentInfo` with [service lookups enabled but without `themes-resource` support](https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L438). Therefore no `ClasspathThemeResourceProviderFactory` is configured and therefore nested theme-resource lookups are not supported.

In the Wildfly based Keycloak distribution the `ClasspathThemeResourceProviderFactory` is registered via the [DefaultProviderLoader](https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/services/src/main/java/org/keycloak/provider/DefaultProviderLoader.java#L65)

### Version

Keycloak.X 16.1.0

### Expected behavior

Keycloak.X should support nested theme-resource lookup as the Wildfly based Keycloak distribution does.

### Actual behavior

Nested theme-resources lookups do not work.

### How to Reproduce?

1) Create an extension (authenticator) with embedded resources
2) Deploy the extension with Keycloak.X.
3) Try to access the authenticator
4) The server console will contain a strack-trace indicating that the theme template could not be found.

### Anything else?

A naive fix could be to change the line:
https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L438

to
```java
ProviderManager pm = new ProviderManager(KeycloakDeploymentInfo.create().services().themes().themeResources(), classLoader);
```

As a workaround we explicitly register the `ClasspathThemeResourceProviderFactory` with a custom implementation:
```java
package com.github.thomasdarimont.keycloakx.themes;

import com.google.auto.service.AutoService;
import org.keycloak.theme.ClasspathThemeResourceProviderFactory;
import org.keycloak.theme.ThemeResourceProviderFactory;

/**
 * Workaround for missing {@link ClasspathThemeResourceProviderFactory} in Keycloak.X to support theme-resources in extension jars.
 */
@AutoService(ThemeResourceProviderFactory.class)
public class CustomClasspathThemeResourceProviderFactory extends ClasspathThemeResourceProviderFactory {

    private static final String ID = "custom-classpath-themeresource-provider";

    public CustomClasspathThemeResourceProviderFactory() {
        super(ID, Thread.currentThread().getContextClassLoader());
    }

    @Override
    public String getId() {
        return ID;
    }
}

```

### PR DESCRIPTION
**Pull request by thomasdarimont**
Previously lookups for embedded theme-resources did not work for Keycloak.X because of a missing
`ClasspathThemeResourceProvider` registration.

This PR ensures that a `ClasspathThemeResourceProvider` will be registered in Keycloak.X based deployments.

Fixes #9653

### CODE REVIEW

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 1]
```diff
@@ -421,7 +422,14 @@ void configureDevMode(BuildProducer<HotDeploymentWatchedFileBuildItem> hotFiles)
             Map<String, ProviderFactory> preConfiguredProviders) {
         Config.init(new MicroProfileConfigProvider());
         ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
-        ProviderManager pm = new ProviderManager(KeycloakDeploymentInfo.create().services(), classLoader);
+
+        KeycloakDeploymentInfo keycloakDeploymentInfo = KeycloakDeploymentInfo.create()
+                .name("classpath")
```
Comment (thomasdarimont) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:427]: I needed to provide a name for the deployment unit here, using "classpath" since we only scan things from classpath.

**Comment by thomasdarimont** [comment]
This currently failes with:
```
$ KEYCLOAK_ADMIN_USERNAME=admin KEYCLOAK_ADMIN_PASSWORD=admin bin/kc.sh start-dev --http-relative-path=auth       
Updating the configuration and installing your custom providers, if any. Please wait.
2022-01-20 21:06:36,936 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 3741ms
2022-01-20 21:06:39,266 INFO  [org.key.qua.run.hos.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>
ERROR: Failed to start server using profile (dev)
ERROR: java.lang.NoSuchMethodException: org.keycloak.theme.ClasspathThemeProviderFactory.<init>()
ERROR: org.keycloak.theme.ClasspathThemeProviderFactory.<init>()
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

File: services/src/main/java/org/keycloak/theme/ClasspathThemeProviderFactory.java [hunk 2]
```diff
@@ -36,6 +36,10 @@
 
     private String id;
 
+    public ClasspathThemeProviderFactory() {
```
Comment (thomasdarimont) [inline services/src/main/java/org/keycloak/theme/ClasspathThemeProviderFactory.java:39]: This ctor seems to be necessary for quarkus to avoid:
```
RROR: Failed to start server using profile (dev)
ERROR: java.lang.NoSuchMethodException: org.keycloak.theme.ClasspathThemeProviderFactory.<init>()
ERROR: org.keycloak.theme.ClasspathThemeProviderFactory.<init>()
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

File: services/src/main/java/org/keycloak/theme/ClasspathThemeResourceProviderFactory.java [hunk 3]
```diff
@@ -22,6 +22,10 @@
     private final String id;
     private final ClassLoader classLoader;
 
+    public ClasspathThemeResourceProviderFactory() {
```
Comment (thomasdarimont) [inline services/src/main/java/org/keycloak/theme/ClasspathThemeResourceProviderFactory.java:25]: Same as above

**Comment by thomasdarimont** [comment]
I tested this manually with an extension.jar with an embedded themes-resources copied into the `providers` folder.
I also tested this with the `keycloak-example-themes.jar` from the `examples/themes` module copied to the `providers` folder.

Both work fine with the fix.

**Review by pedroigor — APPROVED** [review]
@thomasdarimont Thanks.
