### PR TITLE
changed to use serverBaseUrl instead

### LINKED ISSUE #32205: Endpoint configurations shows hostname_admin
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We are using a dedicated hostname-admin URL.
The URL in the realm's endpoint configuration contains the admin url and not the frontend url.

This affects both:
- OpenID Endpoint Configuration 
- SAML 2.0 Identity Provider Metadata 

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Frontend/Backend URL should be used to expose URLs and not the Administration URL.

### Actual behavior

The URL contains the admin url and not the frontend url.

#### Running keycloak `25.0.2`
```yaml
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HOSTNAME: http://localhost:8081
      KC_HOSTNAME_ADMIN: http://localhost:8082
    ports:
      - 8081:8080
      - 8082:8080
```
- browse to `http://localhost:8082` <- the admin console URL
- Go to `Realm settings` (bottom left main menu)
- Observe the Endpoint URL (bottom of the page):
(shows the **admin** hostname)

### Anything else?

Related (regression?): https://github.com/keycloak/keycloak/issues/31244

### PR DESCRIPTION
**Pull request by edewit**
fixes: #32205
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]

**Comment by ssilvert** [comment]
@edewit Looks like the test failure is legit.  Need to update the test?

File: js/apps/admin-ui/src/realm-settings/GeneralTab.tsx [hunk 1]
```diff
@@ -95,7 +95,9 @@ function RealmSettingsGeneralTabForm({
   save,
   userProfileConfig,
 }: RealmSettingsGeneralTabFormProps) {
-  const { adminClient } = useAdminClient();
+  const {
+    environment: { serverBaseUrl },
+  } = useEnvironment();
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/GeneralTab.tsx:100]: Why does this need to use the `useEnvironment()` hook? The environment passed into it is the same environment that can be statically referenced from `environment.ts`.

Comment (edewit) [reply js/apps/admin-ui/src/realm-settings/GeneralTab.tsx:100]: you need to be able to change the environment when you use this screen to build your own admin ui

**Review by ssilvert — APPROVED** [review]
