### PR TITLE
fix: simplify / refine validation methods

### LINKED ISSUE #32455: Refine option validation via PropertyMapper builder
The creation / processing of validation can be improved.

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/pull/32346#discussion_r1734503003_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #32455

For a single option this accumulates, rather than emitting the first exception. This is true for lists as well. If this seems unnecessary, it can be toned down to just the first exception.

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java [hunk 1]
```diff
@@ -349,16 +352,30 @@ public Builder<T> isEnabled(BooleanSupplier isEnabled) {
         /**
          * Set the validator, overwriting the current one.
          */
-        public Builder<T> validator(BiConsumer<PropertyMapper<T>, ConfigValue> validator) {
-            this.validator = validator;
+        public Builder<T> validator(Consumer<String> validator) {
+            this.validator = (mapper, value) -> mapper.validateExpectedValues(value,
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:356]:
```suggestion
            this.validator = (mapper, value) -> mapper.validateValues(value,
```
I've always found the `validateExpectedValues` a little bit confusing as it might reference the `expectedValues` attr of the Option. Wouldn't be better to rename it to sth else? Like this?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java [hunk 2]
```diff
@@ -349,16 +352,30 @@ public Builder<T> isEnabled(BooleanSupplier isEnabled) {
...
+                    (c, v) -> validator.accept(v));
+            if (!Objects.equals(this.description, this.option.getDescription())) {
+                throw new AssertionError("appendValidateEnabled was already called");
+            }
             return this;
         }
         
         public Builder<T> appendValidator(BiConsumer<PropertyMapper<T>, ConfigValue> validator) {
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:364]: Are we actually using somewhere the `PropertyMapper` for validations? Probably not and only the ConfigValue might be sufficient? => IMHO, it should have the same signature as `validator()`.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java [hunk 3]
```diff
@@ -349,16 +352,30 @@ public Builder<T> isEnabled(BooleanSupplier isEnabled) {
...
          * Set the validator, overwriting the current one.
          */
-        public Builder<T> validator(BiConsumer<PropertyMapper<T>, ConfigValue> validator) {
-            this.validator = validator;
+        public Builder<T> validator(Consumer<String> validator) {
+            this.validator = (mapper, value) -> mapper.validateExpectedValues(value,
+                    (c, v) -> validator.accept(v));
+            if (!Objects.equals(this.description, this.option.getDescription())) {
+                throw new AssertionError("appendValidateEnabled was already called");
+            }
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:360]: Might seem confusing for the `validator()` method, comparing some descriptions and having an unclear relationship with the `appendValidateEnabled`. 

I'm not a big fan of the `appendValidateEnabled` either as I find it confusing as well - like having the same functionality as `isEnabled()` except the aspect the prop will be shown in help. I'd still rather extend the `isEnabled()` signature about some flag for showing it in help and removing the `appendValidateEnabled` at all. 

@shawkins WDYT?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java [hunk 4]
```diff
@@ -400,14 +417,30 @@ public void validateExpectedValues(ConfigValue configValue, BiConsumer<ConfigVal
...
+                result.append("Invalid value for multivalued option " + getOptionAndSourceMessage(configValue)
                         + ": list value '" + v + "' should not have leading nor trailing whitespace");
+                continue;
             }
-            singleValidator.accept(configValue, v);
+            try {
+                singleValidator.accept(configValue, v);
+            } catch (PropertyException e) {
+                if (!result.isEmpty()) {
+                    result.append(". ");
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:436]: I like the validation errors accumulating. Very nice stuff. 

What I'd like more is how these errors will be displayed for users.

Instead of having them on a single line delimited by dot, I'd rather have them displayed as a list where each error will be on the new line (if there is more).

Sth like (example):
```
There are multiple validation errors:
* Invalid value for option '--users': invalid. Expected values are: skip, realm_file, same_file, different_files
* Property '--users' can be used only when exporting to a directory, or value set to 'same_file' when exporting to a file.
* Something else...
```

**Review by mabartos — COMMENTED** [review]
@shawkins Very nice stuff! Good job!

I've just put some comments to improve it even a little bit more. Let me know what you think.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:356]: Sure, it can be renamed.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:364]: > Are we actually using somewhere the PropertyMapper for validations? 

Yes with appendValidateEnabled. However it is currently only using the option, which could also be obtained from the builder itself.

> IMHO, it should have the same signature as validator().

While that's possible with a tweak based upon the above, it doesn't really offer much simplication based upon current usage, and it will make it more difficult to do anything more advanced later.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 3 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:360]: > Might seem confusing for the validator() method, comparing some descriptions and having an unclear relationship with the appendValidateEnabled.

The message can be exanded to reference the description if you like.

> @shawkins WDYT?

I disagree. There's a good bit of complexity with how the isEnabled logic is consumed and it won't help to add another check for an additional flag. Keeping this as stictly validation related encapsulates the complexity to the PropertyMapper / builder. And if you end up setting a validator based upon an additional flag you'll have the same issue of interdependency between calls.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 4 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:436]: > Instead of having them on a single line delimited by dot, I'd rather have them displayed as a list where each error will be on the new line (if there is more).

Sure, separate lines with a header is good.

And it's probably good to note that this is per option. We are not yet aggregating across options.

Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:436]: > And it's probably good to note that this is per option. We are not yet aggregating across options.

Yes, I was thinking about it as well, but... In that case, we should edit the validator messages so as not to duplicate the property name again. However, if there's only one error, there will not be any header, and the message will not contain the property name. 

So it should be handled somehow - but yes, it's possible, probably not a big deal.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 2 above)
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:364]: > While that's possible with a tweak based upon the above, it doesn't really offer much simplication based upon current usage, and it will make it more difficult to do anything more advanced later.

Yep, agree that might be handy for future advanced usage. Like that might be the case even for the `validator()`, right? 

What about providing both signatures with overloading: 
```
validator(Consumer<String> ...)
validator(BiConsumer<PropertyMapper,String> ...)
```
(or `ConfigValue` instead of strings?)

The same for `appendValidator`. I think it will not introduce any additional complexity as it would be very trivial and useful.

WDYT?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 3 above)
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:360]: > The message can be exanded to reference the description if you like.

Would be great - like when the `AssertionError` is thrown with the `appendValidateEnabled was already called` msg, I don't know what's the problem. "I'm not able to call appendValidateEnabled more times? Was the validator() called twice? Does the order of the builder method matter? ...."

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:364]: > (or ConfigValue instead of strings?)

For list item validation that would implie creating ConfigValue wrappers for each item, which I would like to avoid.

> WDYT?

My approach is to start with the minimum and let additional signatures be added as needed. It doesn't bother me that appendValidator has a different signature - as is it's used internally once, and externally once (which doesn't depend on any of the arguments). So it can easily be changed later if desired.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 3 above)
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:360]: > I disagree. There's a good bit of complexity with how the isEnabled logic is consumed and it won't help to add another check for an additional flag. Keeping this as stictly validation related encapsulates the complexity to the PropertyMapper / builder. And if you end up setting a validator based upon an additional flag you'll have the same issue of interdependency between calls.

As we're discussing more DevEx as users are not affected by this, it might be sufficient to improve the error message as the Javadoc for the `appendValidateEnabled` should be sufficient. 

So, ok, not a big deal for me :)

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 2 above)
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:364]: > For list item validation that would implie creating ConfigValue wrappers for each item, which I would like to avoid.

+1 

> My approach is to start with the minimum and let additional signatures be added as needed. It doesn't bother me that appendValidator has a different signature - as is it's used internally once, and externally once (which doesn't depend on any of the arguments). So it can easily be changed later if desired.

Got it. I'm just trying to make a good DevEx for the prop mappers and options, as we're not alone who's creating the options and possibly adding the validators, etc.

But the extension of it might be done later as it'd be a straightforward task. 

So, ok.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 4 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java]: Switched to newline delimited. The header would be nice, but may not be worth it at this point. Alternatively how the exceptions are collected / emitted could change - a validator could just as easily be a List<String> supplier which would make it easy for the top level validate method to emit a message with a header. I would leave that to a follow-up.

**Review by mabartos — COMMENTED** [review]
@shawkins Great, thanks for these changes! 

- The renaming of these methods makes much more sense to me right now
- Also the description of the assertion error is better
- Agree to not introducing the header for exceptions for now
- good to have the PropertyMapper test

Consideration for the test - _could be even good to leverage the functionality for some dist tests where we check only the error messages, etc. as we might test only the SmallRye Config error messages to save some test exec time._

Please resolve the conflicts. Otherwise LGTM, nice job!

**Comment by shawkins** [comment]
> Consideration for the test - could be even good to leverage the functionality for some dist tests where we check only the error messages, etc. as we might test only the SmallRye Config error messages to save some test exec time.

Yes, I'm a big fan of unit tests where possible. Some of the failing tests in particular could be unit tests - there will be some that also need something like the ConfigurationTest setup as the mappers directly reference the Configuration. I'd vote for a follow-on issue for this.

**Comment by mabartos** [comment]
> Yes, I'm a big fan of unit tests where possible. Some of the failing tests in particular could be unit tests - there will be some that also need something like the ConfigurationTest setup as the mappers directly reference the Configuration. I'd vote for a follow-on issue for this.

@shawkins Definitely something that we should look at. There might be many occurrences of the "failing" dist tests -> yep, follow-up issue.

**Comment by shawkins** [comment]
It has been rebased.

**Review by mabartos — APPROVED** [review]
@shawkins LGTM, thanks!
