### PR TITLE
fix: preventing args to service commands

### LINKED ISSUE #44975: tools completion accepts any arguments
### Description

For example `./kc.sh tools completion --foo=dev-mem` does not produce an error. The command should actually not accept any property mapper / spi arguments, let alone someing completely invalid like --foo.

Also relates to new commands being added for windows services - they similarly don't need to accept any arguments not defined on the command.

See  https://github.com/keycloak/keycloak/pull/44496#discussion_r2627649298

### PR DESCRIPTION
**Pull request by shawkins**
also outputting all commands for help files

closes #44975

### CODE REVIEW

**Comment by shawkins** [comment]
@Pepo48 this reestablishes the replacement logic, but I see that more is still needed to enable the tests on windows.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java [hunk 1]
```diff
@@ -36,21 +39,24 @@
...
-import org.approvaltests.core.Options;
-import org.approvaltests.core.VerifyResult;
 import org.hamcrest.MatcherAssert;
 import org.hamcrest.Matchers;
+import org.junit.jupiter.api.Tag;
 import org.junit.jupiter.api.Test;
 
 import static org.keycloak.quarkus.runtime.cli.command.AbstractAutoBuildCommand.OPTIMIZED_BUILD_OPTION_LONG;
 
+@WithEnvVars({"KEYCLOAK_ALL_COMMANDS", "true"})
```
Comment (vmuzikar) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java]: With this approach, we won't know the hiding of the OS-specific cocmmands actually works.

Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java]: Sorry, I meant to add a Linux specific test showing that these commands won't work there.

The main thought here is that we don't need helpcommanddisttest to be OS dependent.

I'd also be fine to extend this approach to a way to set the OS for picocli, rather than just relying upon the Environment method.

**Comment by Pepo48** [comment]
> @Pepo48 this reestablishes the replacement logic, but I see that more is still needed to enable the tests on windows.

@shawkins correct, as I mentioned in the Windows service PR, this issue most likely has nothing to do with the changes introduced by the service feature. If the test had been enabled, it probably would have failed a long time ago. It’s a tricky one, because I couldn’t reproduce it locally. The raw GitHub logs show just a single trailing space (you can try searching the logs for "Usage: "), and I can’t directly download the received .txt files to check whether there’s anything more.

I tried to implement a [scrubber](https://github.com/approvals/ApprovalTests.Java/blob/master/approvaltests/docs/Scrubbers.md) using various regexes, but again - what worked locally didn’t work in CI. Therefore, I suspect there must be something else at play, possibly an environmental difference or a Picocli discrepancy.

As a result, simply adding the tag did not resolve the issue for me either, and it requires deeper analysis.

I’m now wondering whether someone noticed this a long time ago and whether this was the actual reason the tests were never enabled on Windows runners. 😄.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java (hunk 1 above)
Comment (vmuzikar) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java]: > The main thought here is that we don't need helpcommanddisttest to be OS dependent.

Not sure about that. How do we know the OS dependent logic for hiding/removing commands also works correctly for the help command?

Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java]: @vmuzikar updated the branch to show this more completely. We also have the option of moving the helpdisttest entirely out of the integration tests if we don't want to expose an environment variable for testing purposes.

Comment (vmuzikar) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java]: @shawkins Thanks for the update. I understand the reasoning and the push for unit test-like approach. It's alright, I think we can keep this approach for the helpdisttest. Still, I'd like to include at least a small integration smoke test that would verify our logic for excluding commands work on unsupported OSs. I'd feel better when merging if we had something like that here. :)

**Comment by shawkins** [comment]
> I'd feel better when merging if we had something like that here. :)

Added a non-windows test to make sure that the command is not recognized.

> I’m now wondering whether someone noticed this a long time ago and whether this was the actual reason the tests were never enabled on Windows runners.

Right, I'm giving up on that aspect for this test. There isn't an obvious difference in the log with these changes to the help dist test, so maybe it can be reexamined under the other issue.

**Review by vmuzikar — APPROVED** [review]
Looks good, thanks @shawkins!

**Comment by vmuzikar** [comment]
> so maybe it can be reexamined under the other issue.

+1, it'd be good to have the helpdisttest running on Windows but it's a separate issue.

**Comment by shawkins** [comment]
@Pepo48 do you want to give a final review?

**Review by Pepo48 — APPROVED** [review]
LGTM, thanks @shawkins!
