### PR TITLE
Fix for issue #24035

### LINKED ISSUE #24035: Admin UI: Group details page is not updated by group list dropdown actions
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When deleting a group from the groups list and being on the details view of that group, the ui does not jump back to the groups overview like it does for the Action -> Delete dropdown: 

image
image

Additionally when renaming the group via the left menu the group name on the details also is not updated automatically.
image
image
image

### Version

22.0.4

### Expected behavior

When deleting a group that is currently opened the UI should always switch to the overview again. 
When renaming a group the name should automatically be updated in the details view of that group.

### Actual behavior

The UI stays at the details view of the deleted group.
The name stays the same.

### How to Reproduce?

Group delete:
1. Create a group
2. Go to the details view of that group
3. Delete the group with the delete dropdown of the group list (NOT Action -> Delete which is working fine)

Group renaming:
1. Create a group
2. Go to the details view of that group
3. Rename the group with the rename dropdown of the group list (NOT Action -> Rename which is working fine)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by himanshi1099**
Added 'navigate(toGroups({ realm }));' to 'DeleteGroup' component and rename 'GroupsModal' component in GroupTree.tsx

Closes #24035

### CODE REVIEW

**Comment by himanshi1099** [comment]
@ssilvert @edewit @jonkoops I have raised PR for issue #24035. Can you please check. Thanks in Advance

**Comment by jonkoops** [comment]
@himanshi1099 please do not @ team members as it causes more notifications and noise for us. We will get to your PR when we can.

**Comment by ssilvert** [comment]
@himanshi1099 Please work with @edewit on this.

Also, I have updated your initial comment on this PR as per our [contribution guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking).

File: js/apps/admin-ui/src/groups/components/GroupTree.tsx [hunk 1]
```diff
@@ -60,6 +62,7 @@ const GroupTreeContextMenu = ({
           id={group.id}
           rename={group}
           refresh={() => {
+            navigate(toGroups({ realm }));
             refresh();
```
Comment (edewit) [inline js/apps/admin-ui/src/groups/components/GroupTree.tsx:66]: The original `refresh` no longer makes sense when we navigate away before.

**Review by edewit — CHANGES_REQUESTED** [review]
I think it would be better to change the refresh in `GroupsSection` instead

**Review by edewit — APPROVED** [review]
