### PR TITLE
RemoteUserSessionProvider remote query calls must not use negative values for offsets and maxResults

### LINKED ISSUE #43769: RemoteUserSessionProvider remote query calls must not use negative values for offsets and maxResults
### Description

Since Infinispan 16.0, the use of a negative offset with remote queries results in the query failing with the following server-side exception:

```
14:04:20,381 ERROR () [org.infinispan.SERVER] ISPN005003: Exception reportedjava.lang.IllegalArgumentException: ISPN014824: startOffset cannot
 be less than 0
        at org.infinispan.commons.query.BaseQuery.startOffset(BaseQuery.java:175)
        at org.infinispan.commons.query.BaseQuery.startOffset(BaseQuery.java:21)
        at org.infinispan.server.core.query.impl.ObjectRemoteQueryEngine.makeQuery(ObjectRemoteQueryEngine.java:30)
        at org.infinispan.server.core.query.impl.BaseRemoteQueryManager.localQuery(BaseRemoteQueryManager.java:90)
        at org.infinispan.server.core.query.impl.ProtobufRemoteQueryManager.localQuery(ProtobufRemoteQueryManager.java:23)
        at org.infinispan.server.core.query.impl.BaseRemoteQueryManager.executeQuery(BaseRemoteQueryManager.java:71)
        at org.infinispan.server.core.query.impl.ProtobufRemoteQueryManager.executeQuery(ProtobufRemoteQueryManager.java:23)
        at org.infinispan.server.core.query.impl.QueryFacadeImpl.query(QueryFacadeImpl.java:45)
        at org.infinispan.server.hotrod.HotRodServer.query(HotRodServer.java:161)
        at org.infinispan.server.hotrod.CacheRequestProcessor.queryInternal(CacheRequestProcessor.java:610)
        at org.infinispan.server.hotrod.CacheRequestProcessor.lambda$query$0(CacheRequestProcessor.java:605)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```

See infinispan/infinispan#15962

We should transform negative calls to `Query#startOffset` and `Query#maxResults` in `RemoteUserSessionProvider#streamUserSessionByClientId` as the calling API `UserSessionProvider#getUserSessionsStream` explicitly allows negative values.

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #43769

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java [hunk 1]
```diff
@@ -446,10 +446,10 @@ private Stream<UserSessionModel> streamUserSessionByBrokerUserId(RealmModel real
 
     private Stream<UserSessionModel> streamUserSessionByClientId(RealmModel realm, String clientId, boolean offline, Integer offset, Integer maxResults) {
         var userSessionIdQuery = ClientSessionQueries.fetchUserSessionIdForClientId(getClientSessionTransaction(offline).getCache(), realm.getId(), clientId);
-        if (offset != null) {
+        if (offset != null && offset > -1) {
             userSessionIdQuery.startOffset(offset);
         }
-        userSessionIdQuery.maxResults(maxResults == null ? Integer.MAX_VALUE : maxResults);
+        userSessionIdQuery.maxResults(maxResults == null || maxResults == -1 ? Integer.MAX_VALUE : maxResults);
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java:452]: We probably need the same logic as above.
```java
        if (maxResults != null && maxResults > -1) {
            userSessionIdQuery.maxResults(maxResults);
        }
```
This could have been merged in `main` IMO.

Comment (ryanemerson) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java:452]: What's wrong with passing MAX_VALUE in this case?

> This could have been merged in `main` IMO.

This isn't a bug with Infinispan 15.x.y. It will make it to `main` eventually, but this way I don't have to create two PRs :slightly_smiling_face:

Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java:452]: > What's wrong with passing MAX_VALUE in this case?

Currently, nothing, and we are forced to use `MAX_VALUE` as indexed queries only returns 100 hits by default. Hybrid queries may break if `offset > 0` as it sums the `maxResults` with the `offset`. 

https://github.com/infinispan/infinispan/blob/1e095d400033299d02fbdb3e8fd375e5170bc7dc/query-core/src/main/java/org/infinispan/query/core/impl/HybridQuery.java#L71

> this way I don't have to create two PRs 

Isn't this branch being rebased on top of main?

Comment (ryanemerson) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java:452]: > Isn't this branch being rebased on top of main?

It will eventually, but it's currently 120 commits behind and I wanted the fix in ASAP for testing.
