### PR TITLE
fix: adding filtering to ignore anything runtime during a build

### LINKED ISSUE #25166: config keystore runtime properties are validated during re-augmentation
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Picocli.hasConfigChanges triggers the resolution of all properties, so a runtime property like config-keystore gets validation with kc.sh build - but that is not expected.

### Version

23

### Expected behavior

Runtime properties should not be validated until runtime.

### Actual behavior

Validation failure during build time.

### How to Reproduce?

export KC_CONFIG_KEYSTORE=invalid
./kc.sh build

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
We can more pervasively exclude anything runtime from consideration during build time or the auto-build check with some additional filtering on the interceptor.  However it does seem to show that https-client-auth needs to be a build time property - it is in quarkus https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.ssl.client-auth

@vmuzikar @pedroigor @Pepo48 let me know if this approach seems viable, and I'll add a test and some docs.

closes: #25166

### CODE REVIEW

**Comment by vmuzikar** [comment]
I'm ok in general with this approach but it'd be good  to get @pedroigor's and @mabartos' perspective as well.

**Comment by vmuzikar** [comment]
> However it does seem to show that https-client-auth needs to be a build time property - it is in quarkus

Hmmm, seems like an oversight in Keycloak that it was runtime. Not much of a choice we have here. We just need to make sure we reflect that in the upgrading guide.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java [hunk 1]
```diff
@@ -38,6 +46,57 @@
...
+            @Override
+            public T next() {
+                if (next == null && !isNull && !hasNext()) {
+                    throw new NoSuchElementException();
+                }
+                T value = next;
+                next = null;
+                isNull = false;
+                return value;
+            }
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java:81]: Could be simplified as below, right? I don't really like the conditions `next == null && !isNull` as it may seem confusing. Is there any specific case you considered with the functionality?

```suggestion
            T next;

            @Override
            public boolean hasNext() {
                while (next == null) {
                    if (!iter.hasNext()) {
                        return false;
                    }
                    T value = iter.next();
                    if (isRuntime(nameFunc.apply(value))) continue;
                    next = value;
                }
                return true;
            }

            @Override
            public T next() {
                if (next == null && !hasNext()) {
                    throw new NoSuchElementException();
                }
                T value = next;
                next = null;
                return value;
            }
```

File: quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt [hunk 2]
```diff
@@ -109,6 +113,15 @@ HTTP(S):
...
 
+Config:
+
+--config-keystore <config-keystore>
+                     Specifies a path to the KeyStore Configuration Source.
+--config-keystore-password <config-keystore-password>
+                     Specifies a password to the KeyStore Configuration Source.
+--config-keystore-type <config-keystore-type>
+                     Specifies a type of the KeyStore Configuration Source. Default: PKCS12.
+
```
Comment (mabartos) [inline quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt:124]: Why these changes were provided? Only the `--https-client-auth` should be changed, right?

**Review by mabartos — COMMENTED** [review]
@shawkins I've added some comments below. Mostly nitpicks.

File: quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt (hunk 2 above)
Comment (shawkins) [reply quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt:124]: The windows files are not well maintained, I have a utility to just accept the actual so it will pick up any changes that are still needed. I have filtered those out for a couple of prs, but it makes more sense to just have everything up to date.

Comment (mabartos) [reply quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt:124]: Ok, works for me. What kind of utility do you use for it?

Comment (shawkins) [reply quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt:124]: Just a java class that I run from the ide after the test. It would be better to check in something that can run from maven. However the treatment of the windows files isn't completely correct - replacing kc.sh with kc.bat can cause the line length to change and multiple lines need then need to be reformatted.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java (hunk 1 above)
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java:81]: > There were two reasons for that, the first is that it's not documented whether null is allowed in the iterators - logically it should not be, but it's best not to make assumptions.

+1; once we get null value from the inherited iterator, we should take it into account and not "throw it away". 

> Most of the smallrye logic internally simply creates and accumulates a new collection, rather than filtering over the iterator. However I do see quite a few traversals during build, so it seemed better to filter. But we can certainly just make the logic read like the other interceptors and it will be simpler still.

I like rather filtering it out in the iterator.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java [hunk 3]
```diff
@@ -38,6 +46,57 @@
...
+                        return false;
+                    }
+                    T value = iter.next();
+                    if (!isRuntime(nameFunc.apply(value))) {
+                        next = value;
+                        isNull = next == null;
+                    }
+                }
+                return true;
+            }
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java:70]: @shawkins What about this? We'd remove the isNull var and the functionality would be the same, right? 
When the runtime option is present, it just ignores it. If the build option, or null, is present, it returns true.
WDYT?

```suggestion
            @Override
            public boolean hasNext() {
                while (iter.hasNext()) {
                    T value = iter.next();
                    if (isRuntime(nameFunc.apply(value))) continue;
                    next = value;
                    return true;
                }
                return false;
            }
```

**Review by mabartos — APPROVED** [review]
@shawkins LGTM

**Comment by mabartos** [comment]
Rebased via the GitHub UI. Commits will be squashed afterward.

**Review by mhajas — APPROVED** [review]
Approving based on the review from @mabartos
