### PR TITLE
Ignore unknown realms when migrating sessions

### LINKED ISSUE #29802: Flaky test: org.keycloak.testsuite.model.session.UserSessionPersisterProviderTest#testMigrateSession
## org.keycloak.testsuite.model.session.UserSessionPersisterProviderTest#testMigrateSession
[Keycloak CI - Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/9200221159/job/25306687681)

```
java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
...
```

### PR DESCRIPTION
**Pull request by ahus1**
Closes #29802

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java [hunk 1]
```diff
@@ -1030,8 +1031,18 @@ public void migrateNonPersistentSessionsToPersistentSessions() {
         AtomicInteger currentBatch = new AtomicInteger(0);
         var persistence = ComponentRegistry.componentOf(sessionCache, PersistenceManager.class);
         if (persistence != null && !persistence.getStoresAsString().isEmpty()) {
+            ArrayList<Throwable> errors = new ArrayList<>();
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:1034]: you don't need an array list since it will only have, at most, a single exception.

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:1034]: What Java container do you suggest? I need something that's valid within a lambda...

Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:1034]: we have `org.infinispan.commons.util.ByRef` in Infinispan for this type of case :)

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java]: ok, let's use that. PR updated.

**Comment by ahus1** [comment]
@pruivo / @mhajas - please review when you have the time. Thanks!

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java [hunk 2]
```diff
@@ -75,6 +76,7 @@
 import org.keycloak.models.utils.UserModelDelegate;
 
 import java.nio.charset.StandardCharsets;
+import java.util.ArrayList;
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:79]: nitpicking: probably unused import

**Review by pruivo — APPROVED** [review]

**Comment by ahus1** [comment]
@pruivo - well spotted, removed the unused import.

**Review by mhajas — APPROVED** [review]
Thank you @ahus1, LGTM
