### PR TITLE
solve issues 9376. Add flow to generate secret length based on signature algorithm

### LINKED ISSUE #9376: Client secret length should be adjusted based on select signature algorithm
### Describe the bug

Client secret length should be changed based on Mac Algorithm if secret-jwt is used as Client Authenticator.

image

Currently, Keycloak generates client secret with 32 characters which is only good for HS256 (32 x 8 = 256). 

However if user wants to use HS384 or HS512, secret length should be changed based on selected signature algorithm as client secret is used to sign the JWT.

For HS384, secret length should be 48 (384 / 8 = 48). And For HS512, secret length should be 64 (512 / 8 = 64).

### Version

16.1.0

### Expected behavior

Secret length should be changed based on selected signature algorithm.

### Actual behavior

Secret length is always 32 characters which can only work with HS256 signature algorithm.

### How to Reproduce?

- Select `Signed Jwt with Client Secret` as client authenticator for OIDC client
- Select HS512 as signature algorithm
- Regenerate the secret and we can see it is only 32 characters long

```java
//Reference: org.keycloak.models.utils.KeycloakModelUtils#generateSecret
public static String generateSecret(ClientModel client) {
        String secret = SecretGenerator.getInstance().randomString();
        client.setSecret(secret);
        return secret;
}
```

### PR DESCRIPTION
**Pull request by marcelomrwin**
Resolve #9376

### CODE REVIEW

File: server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java [hunk 1]
```diff
@@ -775,4 +786,20 @@ public static boolean isRealmProviderJpa(KeycloakSession session) {
         return providerIds != null && providerIds.size() == 1 && providerIds.iterator().next().equals("jpa");
     }
 
+    /**
+     * @param clientAuthenticatorType
+     * @return secret size based on authentication type
+     */
+    public static int getSecretLengthByAuthenticationType(String clientAuthenticatorType, String signingAlg) {
+        String sanitizedClientAuthType = clientAuthenticatorType.replaceAll("[^a-zA-Z0-9]",""); //FIXME some locations are referenced with "_" while others with "-"
```
Comment (mposolda) [inline server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java:794]: This is a bit strange. I see that `JWTClientSecretAuthenticator.PROVIDER_ID` is `client-secret-jwt` and that is how is the factory selected in various places in the code (For example in `ClientManager.getClientCredentialsAdapterConfig` method).

I hope this workaround is not needed. If there are any places in the code or any failing tests without this workaround, it rather worth to investigate why the `_` is needed instead of `-` .

**Review by mposolda — CHANGES_REQUESTED** [review]
@marcelomrwin Thanks for this PR! It looks good to me, but added one inline comment.

Besides that, it looks that the test failures can be caused by these changes? Like for example `FineGrainAdminUnitTest` and maybe others. Can you please doublecheck?

File: server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java (hunk 1 above)
Comment (marcelomrwin) [reply server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java]: Workaround removed. Let's just treat it as client-secret-jwt. Fixed bug in base tests

**Review by mposolda — APPROVED** [review]
@marcelomrwin Thanks!
