### PR TITLE
Fixing UserFederationLdapConnectionTest,LDAPUserLoginTest to work with FIPS

### LINKED ISSUE #14965: FIPS: Failures related to LDAP tests with ldaps connection to ApacheDS
When running testsuite with Keycloak on Quarkus distribution with FIPS support and BCFIPS security providers (after #14886), there are failures like those below. This is probably related to issues with `ldaps` connection to ApacheDS not working due the fact that truststore does not work as expected (might be related to the WARNING at server startup related to truststore):

```
[ERROR]   UserFederationLdapConnectionTest.testLdapConnectionsSsl:97->assertStatus:129 expected:<204> but was:<400>

[ERROR]   LDAPUserLoginTest>AbstractKeycloakTest.beforeAbstractKeycloakTest:188->AbstractLDAPTest.importTestRealms:89->afterImportTestRealm:124 » Runtime java.lang.ClassNotFoundException: org.bouncycastle.tls.TlsFatalAlert
[ERROR]   LDAPUserLoginTest>AbstractKeycloakTest.beforeAbstractKeycloakTest:188->AbstractLDAPTest.importTestRealms:89->afterImportTestRealm:124 » Runtime java.lang.ClassNotFoundException: org.bouncycastle.tls.TlsFatalAlert
[ERROR]   LDAPUserLoginTest>AbstractKeycloakTest.beforeAbstractKeycloakTest:188->AbstractLDAPTest.importTestRealms:89->afterImportTestRealm:124 » Runtime java.lang.ClassNotFoundException: org.bouncycastle.tls.TlsFatalAlert
[ERROR]   LDAPUserLoginTest>AbstractKeycloakTest.beforeAbstractKeycloakTest:188->AbstractLDAPTest.importTestRealms:89->afterImportTestRealm:124 » Runtime java.lang.ClassNotFoundException: org.bouncycastle.tls.TlsFatalAlert
```

### PR DESCRIPTION
**Pull request by mposolda**
closes #14965

This PR fixes the tests where FIPS based Keycloak server connects to LDAP with usage of SSL or startTLS.

Summary of changes:

- The `org.keycloak.truststore.SSLSocketFactory` used when connecting to LDAP (with the truststore based on Keycloak Truststore SPI) is updated to allow the JDK factory to be decorated with the SSLSocketFactory provided by underlying CryptoProvider implementation. In case of BCFIPS, it needs to use custom SSLSocketFactory in order to use the correct hostname of the LDAP host when verifying certificate. More details in https://downloads.bouncycastle.org/fips-java/BC-FJA-(D)TLSUserGuide-1.0.9.pdf - Section 3.5.2 (Endpoint identification)

- Updated keycloak-fips.truststore.pkcs12 to remove the invalid certificate signed by not-FIPS compliant algorithm

- Small update in `FileTruststoreProviderFactory` to continue parsing truststore if there is single invalid certificate signed by unsupported algorithm

### CODE REVIEW

File: crypto/fips1402/src/main/java/org/keycloak/crypto/fips/FIPS1402Provider.java [hunk 1]
```diff
@@ -209,4 +218,39 @@ public Signature getSignature(String sigAlgName) throws NoSuchAlgorithmException
...
+                    SSLSocket ssl = (SSLSocket)s;
+                    String hostname = hostnameSupplier.get();
+                    SNIHostName sniHostName = getSNIHostName(hostname);
+                    if (sniHostName != null) {
+                        SSLParameters sslParameters = new SSLParameters();
+                        sslParameters.setServerNames(Collections.singletonList(sniHostName));
+                        ssl.setSSLParameters(sslParameters);
+                    }
+                }
+                return s;
```
Comment (stianst) [inline crypto/fips1402/src/main/java/org/keycloak/crypto/fips/FIPS1402Provider.java:240]: What happens if it's null (for whatever reason, for example hostnameSupplier isn't set properly or something)? Does it fail checks, or just it silently ignore hostname checks?

File: services/src/main/java/org/keycloak/truststore/SSLSocketFactory.java [hunk 2]
```diff
@@ -58,7 +65,17 @@ private SSLSocketFactory() {
...
+        Supplier<String> hostnameProvider = () -> {
+            KeycloakSession session = Resteasy.getProvider().getContextData(KeycloakSession.class);
+            if (session == null) {
+                log.tracef("Not found keycloakSession in the resteasy context when trying to retrieve hostname attribute from it");
+                return null;
+            }
+            String hostname = session.getAttribute(Constants.SSL_SERVER_HOST_ATTR, String.class);
+            log.tracef("Found hostname '%s' to be used by SSLSocketFactory", hostname);
+            return hostname;
+        };
```
Comment (stianst) [inline services/src/main/java/org/keycloak/truststore/SSLSocketFactory.java:77]: Since it's only the FIPS1402Provider that needs this, could this be moved to the provider itself and removed from here?

File: crypto/fips1402/src/main/java/org/keycloak/crypto/fips/FIPS1402Provider.java (hunk 1 above)
Comment (mposolda) [reply crypto/fips1402/src/main/java/org/keycloak/crypto/fips/FIPS1402Provider.java:240]: It will fail checks (that is the reason why the tests were failing before this change).

For more details, it will try to verify against the hostname from IP address, rather than hostname. But if the certificate doesn't have the reference to IP address like `127.0.0.1` (instead of hostname like `localhost`) in the subject name or subject alternative name, it will fail.

Some more details why this is needed for BC providers and not for sun providers: https://downloads.bouncycastle.org/fips-java/BC-FJA-(D)TLSUserGuide-1.0.9.pdf section 3.5.2

File: services/src/main/java/org/keycloak/truststore/SSLSocketFactory.java (hunk 2 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/truststore/SSLSocketFactory.java:77]: The reason is, that this code uses stuff from `keycloak-services`, but `keycloak-crypto-fips1402` doesn't have dependency on `keycloak-services`.

However I think it should work to add dependency on `keycloak-services` into `keycloak-crypto-fips1402` - especially since we have only quarkus distribution and don't need to deal with WF modules etc. So I can change it that way.

**Comment by mposolda** [comment]
@stianst Updated to move the code for hostname retrieve to FIPS1402Provider as you suggested. It means dependency of `keycloak-crypto-fips1402`, as I've pointed in the inline comment.

Could you please re-review? I've used separate commit for easier review just so you can see the latest changes, but we can squash before merge.

**Review by stianst — APPROVED** [review]

**Comment by mposolda** [comment]
@stianst Thanks!
