### PR TITLE
Fix for When editing JS policy, the text area with "Code" should be read-only

### LINKED ISSUE #19532: When editing JS policy, the text area with "Code" should be read-only
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I enable "Authorization" for some confidential OIDC client.

Then go to: My client  -> Authorization -> Policies -> Default Policy

Now I should not be able to update `Code` text area as the JS script is supposed to be read-only. However as an administrator, it appears that I am able to edit the `Code` in the script as shown in this screenshot

Screenshot from 2023-04-04 17-14-33

When I click `Save`, it looks like my script was saved. In reality, the script was not saved as server-side works correctly and does not allow to save the script. When I go to some other screens in the admin console and then return back here, I can see that script was not really updated.

So only confusing thing is, that text area, which should be read-only, is editable and administrator may have impression that he can edit this (even if he cannot).

### Version

21.0.2

### Expected behavior

Text area with `Code` should be read-only. It will be nice if administrator can view it and be able to copy/paste from it, however he should not be able to edit it.

### Actual behavior

Text-area `Code` is not read-only. Administrator can write something into it. He cannot really save his changes to server-side (which is correct behaviour). So this is only UI issue.

### How to Reproduce?

See above

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaustubh-rh**
Made The the text area with "Code" should be read-only and disabled to "Save" button

Closes [#19532](https://github.com/keycloak/keycloak/issues/19532)

### CODE REVIEW

**Review by ssilvert — DISMISSED** [review]
LGTM

**Comment by kaustubh-rh** [comment]
The changes through the UI will be disabled only for the Default Policy. However, the user will have the possibility to create new policies.

**Review by ssilvert — DISMISSED** [review]

**Review by jonkoops — CHANGES_REQUESTED** [review]
Looks like there are some linting issues, please fix them and rebase your PR with `main`.

**Comment by kaustubh-rh** [comment]
Hi @jonkoops , fixed linting issues .

File: js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx [hunk 1]
```diff
@@ -101,6 +104,11 @@ export default function PolicyDetails() {
     ({ policy, policies }) => {
       reset({ ...policy, policies });
       setPolicy(policy);
+      if (policy !== undefined) {
+        if (policy.name === "Default Policy") {
+          setIsDisabled(true);
+        }
+      }
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:111]: Since this is the only place that `setIsDisabled` is set and the state is derived from the value of `policy` this doesn't actually have to be a state. Instead the value could be derived from the value of policy:

```ts
const [policy, setPolicy] = useState<PolicyRepresentation>();
const isDisabled = policy?.name === "Default Policy";
```

File: js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx [hunk 2]
```diff
@@ -101,6 +104,11 @@ export default function PolicyDetails() {
     ({ policy, policies }) => {
       reset({ ...policy, policies });
       setPolicy(policy);
+      if (policy !== undefined) {
+        if (policy.name === "Default Policy") {
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:108]: Is there no better way to detect the default policy? Using the human-readable name seems like an error prone approach. I am worried that this might not work under different locales.

@ssilvert WDYT?

File: js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx [hunk 3]
```diff
@@ -164,9 +172,12 @@ export default function PolicyDetails() {
...
 
-  const ComponentType = isValidComponentType(policyType)
-    ? COMPONENTS[policyType]
-    : COMPONENTS["js"];
+  let ComponentType = COMPONENTS["js-disabled"];
+  if (!IsDisabled) {
+    ComponentType = isValidComponentType(policyType)
+      ? COMPONENTS[policyType]
+      : COMPONENTS["js"];
+  }
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:180]: This seems to be getting a bit messy, perhaps we can extract this into a separate function so we can use an eager return pattern? For example:

```ts
function getComponentType(policyType: string, isDisabled: boolean) {
  if (isDisabled) {
    return COMPONENTS["js-disabled"];
  }

  return isValidComponentType(policyType)
    ? COMPONENTS[policyType]
    : COMPONENTS["js"];
}
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Comment by kaustubh-rh** [comment]
Hi @jonkoops @ssilvert updated the PolicyDetails.tsx as per the prior suggestions. I tested the same on to my local system and it's working fine. Do review the latest changes. Thanks

**Comment by kaustubh-rh** [comment]
Hi @jonkoops @ssilvert  fixed the linting issues. Thanks

**Review by jonkoops — DISMISSED** [review]
I think the work here is probably fine, but I'd like the other team members to take a look at this as well.

@ssilvert @edewit

File: js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx (hunk 2 above)
Comment (ssilvert) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx]: I don't think the default policy name is localizable.  But I would need to look at the back end to know for sure.

Comment (kaustubh-rh) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx]: I think it originates from [ResourceServerService.java] (https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authorization/admin/ResourceServerService.java#L181) 

As it's hardcoded, I think, it should not be an issue.

Comment (jonkoops) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx]: Nice, thanks for checking that. I think I would prefer if the API returned a proper field for it (like `isReadOnly` or somthing). But I think that kind of change is out of scope for this issue.

File: js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx [hunk 4]
```diff
@@ -164,9 +167,17 @@ export default function PolicyDetails() {
     return <KeycloakSpinner />;
   }
 
-  const ComponentType = isValidComponentType(policyType)
-    ? COMPONENTS[policyType]
-    : COMPONENTS["js"];
+  function getComponentType() {
+    if (isDisabled) {
+      return COMPONENTS["js-disabled"];
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:172]: I was thinking, rather than handling `js-disable` as an edge case like this. Perhaps we should add a `isDisabled` prop to the `COMPONENTS`? That way we can re-use the existing `JavaScript` component.

Comment (kaustubh-rh) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:172]: Hi @jonkoops , we are just checking the above edge case in the `getComponentType() `function to assign a ComponentType . For other components like `NameDescription`,`LogicSelector` and `Button` we are passing `isDisabled` as a prop.

Comment (jonkoops) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:172]: I believe that @ssilvert mentioned to me that the JS one should always be disabled. But I do not recall the fine details.

Comment (kaustubh-rh) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:172]: @jonkoops @ssilvert If we disable the JS component, then the user will not have the possibility to create a new JS based policy as the input box will always be disabled. As of `js` points to the `JavaScript` component and `js-disabled` points to the `JavaScriptDisabled` component which it seems to be working fine.

Comment (ssilvert) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:172]: I have verified this now.  Awhile back, we decided that javascript should never be "uploadable".   Furthermore, you should not be able to create a javascript policy from the UI.

Comment (jonkoops) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:172]: In that case I think we can make the default `js` read only, that should be enough. It also removes the need to explicitly check the name of the default policy.

Comment (kaustubh-rh) [reply js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx:172]: @jonkoops @ssilvert ack , thanks for the confirmation

**Comment by kaustubh-rh** [comment]
@jonkoops @ssilvert made `js` read only  . Thanks

**Review by jonkoops — APPROVED** [review]
