### PR TITLE
Encode realm name in console URIs

### LINKED ISSUE #25807: Space in realm name breaks initial console uris
### Area

dist/quarkus

### Describe the bug

Realm names can include spaces, but doing so will create a realm with broken console clients.

The console client uris (including the redirect uris) will contain the unencoded realm name, but they need to include the encoded realm name as the redirect uris will break otherwise.

### Version

23.0.3

### Expected behavior

console clients should be created with valid client uris.

### Actual behavior

The generated redirect uris need to be fixed manually to include the encoded realm name.

### How to Reproduce?

1. Create Realm called "Test Realm"
2. The `account` client has the redirect uri `/realms/Test Realm/account/*`
3. The `account-console` client has the redirect uri `/realms/Test Realm/account/*`
4. The `security-admin-console` client has the redirect uri `/admin/Test Realm/console/*`

### Anything else?

_No response_

### LINKED ISSUE #26108: Realm improper input sanitization
### Description

Unsanitized user input values that can contain special characters can be saved as the Realm ID and name. This can be done through the Keycloak admin console UI or though the Keycloak Admin REST API.

### Version
\>= 23.0.4

### Impact

Unexpected behavior that affects the realm functionality and their related components.

### Recommendations

* Database ID field should be a randomly generated uuid and not a user controlled input value
* A unified sanitization and validation strategy should be implemented on all user input values to ensure only valid values are accepted and saved.

### References
- https://issues.redhat.com/browse/RHSSO-2689
- https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #25807

This probably also closes #26108. I'll take a look but I think that with this the realm is properly checked in name and id.

The PR encodes the URLs generated when a realm is created. It also decodes the issuer to obtain the realm that was previously encoded. Tests added.

Maybe there are more issues about spaces in realms but the idea is managing them one by one. With this PR at least the realm is created and it's functional with the admin console. I'm going to file a new bug for the account console. The v2 one worked OK but v3 is failing.

### CODE REVIEW

**Comment by rmartinc** [comment]
I have fixed also the account v3. It was just a decode in the path of the router. Please @keycloak/ui take a look just in case.

File: js/apps/account-ui/src/routes.tsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ export const PersonalInfoRoute: IndexRouteObject = {
 };
 
 export const RootRoute: RouteObject = {
-  path: new URL(environment.baseUrl).pathname,
+  path: decodeURI(new URL(environment.baseUrl).pathname),
```
Comment (jonkoops) [inline js/apps/account-ui/src/routes.tsx:62]: There should be no need to decode this I think, as `URL` should already take care of it. But if you do you want to likely go for [`decodeURIComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent) since this is not decoding a whole URL, but only the path, there are [some differences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI#decodeuri_vs._decodeuricomponent).

File: services/src/main/java/org/keycloak/services/managers/RealmManager.java [hunk 2]
```diff
@@ -178,7 +179,8 @@ protected void setupAdminConsole(RealmModel realm) {
         adminConsole.setName("${client_" + Constants.ADMIN_CONSOLE_CLIENT_ID + "}");
 
         adminConsole.setRootUrl(Constants.AUTH_ADMIN_URL_PROP);
-        String baseUrl = "/admin/" + realm.getName() + "/console/";
+
+        String baseUrl = UriBuilder.fromPath("/admin/{realmName}/console/").build(realm.getName()).toString();
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/services/managers/RealmManager.java:183]: Don't we have some kind of URL builder or constant for this? E.g.

```suggestion
        String baseUrl = session.getContext().getUri(UrlType.ADMIN).build(realm.getName()).toString();
```

File: services/src/main/java/org/keycloak/services/managers/RealmManager.java [hunk 3]
```diff
@@ -424,7 +426,8 @@ private void setupAccountManagement(RealmModel realm) {
             accountClient.setFullScopeAllowed(false);
 
             accountClient.setRootUrl(Constants.AUTH_BASE_URL_PROP);
-            String baseUrl = "/realms/" + realm.getName() + "/account/";
+
+            String baseUrl = UriBuilder.fromPath("/realms/{realmName}/account/").build(realm.getName()).toString();
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/services/managers/RealmManager.java:430]: Same here, seems something we repeat often enough for the path to be stored as a constant somewhere.

**Review by jonkoops — DISMISSED** [review]
LGTM, just wondering if the URLs could be done with less repetition.

File: js/apps/account-ui/src/routes.tsx (hunk 1 above)
Comment (rmartinc) [reply js/apps/account-ui/src/routes.tsx:62]: The decode is necessary, if not I have an error 404 with route (I detected this today, previously account v2 worked flawlessly). It seems that the router uses a decoded path. I  will change `decodeURI` with `decodeURIComponent`.

File: services/src/main/java/org/keycloak/services/managers/RealmManager.java (hunk 2 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/services/managers/RealmManager.java:183]: @jonkoops This creation method is sometimes executed with no valid resteasy context (for example initial creation for the master realm at first boot). If you want I can do something simpler and more similar to what we had before:

```java
String baseUrl = "/admin/" + Encode.encodePathSegment(realm.getName()) + "/console/";
```

WDYT?

File: js/apps/account-ui/src/routes.tsx (hunk 1 above)
Comment (rmartinc) [reply js/apps/account-ui/src/routes.tsx]: Done now!

File: services/src/main/java/org/keycloak/services/managers/RealmManager.java (hunk 2 above)
Comment (jonkoops) [reply services/src/main/java/org/keycloak/services/managers/RealmManager.java]: Sounds fine to me, we should find a long term solution at some point to centralize this kind of logic.

File: services/src/main/java/org/keycloak/services/managers/RealmManager.java (hunk 3 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/services/managers/RealmManager.java]: Same, I did string concatenation but with the realm name encoded.

**Review by jonkoops — APPROVED** [review]
LGTM!

**Review by mposolda — APPROVED** [review]
@rmartinc @jonkoops Thanks!
