### PR TITLE
Fix `DefaultHostnameTest` on Undertow

### LINKED ISSUE #14270: Unstable DefaultHostnameTest with auth-server-undertow
### Description

The issue is briefly described in [Fix jspath for old admin console and frontend url PR](https://github.com/keycloak/keycloak/pull/13730). The test failure console output can be found [here](https://github.com/keycloak/keycloak/runs/8243281972?check_suite_focus=true#step:9:2083).

The failure can be reproduced locally:
* build the distribution first via:
```
mvn clean install -Pdistribution -DskipTests -DincludeWildFly
```
* run the test via:
```
mvn -f testsuite/integration-arquillian/pom.xml clean install -Dtest=DefaultHostnameTest
```

Note:
If the tests are separately one by one, e.g.: `-Dtest=DefaultHostnameTest#fixedFrontendUrlOldAdminPage` they seem to be stable. The instability appears only when the whole test class is executed.
With `-Pauth-server-wildfly` everything works as expected and the failure is not present.

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #14270

### CODE REVIEW

File: services/src/main/java/org/keycloak/theme/DefaultThemeSelectorProvider.java [hunk 1]
```diff
@@ -50,9 +48,9 @@ public String getThemeName(Theme.Type type) {
 
         if (name == null || name.isEmpty()) {
             name = Config.scope("theme").get("default", Version.NAME.toLowerCase());
-            if ((type == Theme.Type.ACCOUNT) && isAccount2Enabled) {
+            if ((type == Theme.Type.ACCOUNT) && Profile.isFeatureEnabled(Profile.Feature.ACCOUNT2)) {
                 name = name.concat(".v2");
-            } else if ((type == Theme.Type.ADMIN) && isAdmin2Enabled) {
+            } else if ((type == Theme.Type.ADMIN) && Profile.isFeatureEnabled(Profile.Feature.ADMIN2)) {
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/theme/DefaultThemeSelectorProvider.java:53]: This is necessary for Undertow as it shares the same JVM with tests and the static fields previously were not re-instantiated on server restart (or disabled features update).

Although updating server code to fix tests is not ideal, I believe this change actually aligns the use of `Profile.isFeatureEnabled()` with other parts of Keycloak – we usually don't store the result `Profile.isFeatureEnabled()` of in a constant.

**Review by Pepo48 — APPROVED** [review]
I just tested the proposed changes, I ran all the tests at once and then even separately one by one on both Undertow and WildFly (just to be completely sure). The previously affected tests were stable in all the scenarions Moreover, as we we were discussing it continuously I totally agree with the fix and thus I'm approving the PR.

Thanks @vmuzikar for your time, the effort and the guidance!

**Review by pedroigor — APPROVED** [review]
