### PR TITLE
lazy populate the treeview for groups

### LINKED ISSUE #19954: Admin UI hangs with many subgroups
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

This was reported internally by Engin Atick from Claudia's team.  He has groups with thousands of subgroups.  When he tries to open the group section, the UI hangs and then errors out.

I have reproduced this using partial import of a group with 10,000 subgroups.  The old UI seems to handle it better.  With the old UI, the response is slow but it does work.

Here is a json you can import to create the groups:
[groups-10000-in-subgroup.zip](https://github.com/keycloak/keycloak/files/11326066/groups-10000-in-subgroup.zip)

### Version

main

### Expected behavior

Groups display

### Actual behavior

Freeze and crash

### How to Reproduce?

Use attached json to do partial import.  Then open groups section.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
Fetching of the subgroups is now paginates in the tree and the detail view

subgroup pagination in the treeview
image

tree is now lazy populated on select

fixes: #19954

### CODE REVIEW

File: js/apps/admin-ui/src/groups/GroupsSection.tsx [hunk 1]
```diff
@@ -53,6 +56,9 @@ export default function GroupsSection() {
   const location = useLocation();
   const id = getLastId(location.pathname);
 
+  const [searchParams] = useSearchParams();
+  const lazy = searchParams.get("lazy") || "false";
```
Comment (ssilvert) [inline js/apps/admin-ui/src/groups/GroupsSection.tsx:60]: Shouldn't this be a boolean instead of a String?

Something like, 
```suggestion
  const lazy = searchParams.has("lazy") || false;
```

File: js/apps/admin-ui/src/groups/GroupsSection.tsx [hunk 2]
```diff
@@ -53,6 +56,9 @@ export default function GroupsSection() {
...
+  const [open, toggle] = useToggle(lazy === "false");
```
Comment (ssilvert) [inline js/apps/admin-ui/src/groups/GroupsSection.tsx:61]:
```suggestion
  const [open, toggle] = useToggle(lazy);
```

**Review by ssilvert — COMMENTED** [review]
Looks good.  I'm going to try it out later.

File: js/apps/admin-ui/src/groups/GroupsSection.tsx (hunk 1 above)
Comment (edewit) [reply js/apps/admin-ui/src/groups/GroupsSection.tsx:60]: right if we use `has` the value doesn't matter so it will be `?lazy` then it will hide the tree view initially and it will only show the root and search

**Review by ssilvert — CHANGES_REQUESTED** [review]
This doesn't fix the problem for me.   Did you try to partial import the json attached to the issue?  Import works fine (you just have to let it finish).  But then I try to go to the Groups section and it hangs.

On a more minor note, the show/hide works well, but I think the "show" icon should be a right arrow instead of a hamburger menu.

**Review by ssilvert — COMMENTED** [review]
I've tested the latest revision on this PR and it works great.  Still needs code review.

**Comment by jonkoops** [comment]
@ssilvert I think the tests are still failing on this one, but I will do quick rebase to make sure.

**Comment by jonkoops** [comment]
Looks like it has to do with the changes introduced by Erik, we'll have to wait until he's back next week.

**Comment by Redhat-Alice** [comment]
We have been working on the same idea with a slightly different direction by expanding out the storage implementations and then updating the surrounding utility and resource classes to account for pagination. It isn't in a final state yet but since comments mention issue not being solved curious if it would be welcome here: https://github.com/keycloak/keycloak/compare/main...Redhat-Alice:keycloak:subgroup-model-expansion

**Comment by zwitter1** [comment]
Just a heads up. I had a few issues in testing this branch. The pagination on the left side wasn't working when I'd switch the count to 10 per page. 

I also don't get the caret on the dropdowns for groups with subgroups until I click on the group.

**Comment by ssilvert** [comment]
> We have been working on the same idea with a slightly different direction by expanding out the storage implementations and then updating the surrounding utility and resource classes to account for pagination. It isn't in a final state yet but since comments mention issue not being solved curious if it would be welcome here: [main...Redhat-Alice:keycloak:subgroup-model-expansion](https://github.com/keycloak/keycloak/compare/main...Redhat-Alice:keycloak:subgroup-model-expansion)

I believe this is solved now and we intend to merge the PR soon.  If you want to suggest an improvement, go ahead and create an enhancement request or discussion.

**Review by ssilvert — APPROVED** [review]
