### PR TITLE
ConcurrentModificationException in KeycloakProcessor#configureProfile

### LINKED ISSUE #45501: ConcurrentModificationException in KeycloakProcessor#configureProfile
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

There is an exception in the CI which seems leads to random failures:

> [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureProfile threw an exception: java.util.ConcurrentModificationException

```
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) ERROR: Failed to run 'start-dev' command.
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: -15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureProfile threw an exception: java.util.ConcurrentModificationException
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at io.smallrye.config.SmallRyeConfig$ConfigSources$PropertyNames$Names$1.next(SmallRyeConfig.java:2217)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at io.smallrye.config.SmallRyeConfig$ConfigSources$PropertyNames$Names$1.next(SmallRyeConfig.java:2198)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.keycloak.quarkus.runtime.QuarkusSingleProfileConfigResolver.getQuarkusFeatureState(QuarkusSingleProfileConfigResolver.java:24)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.keycloak.quarkus.runtime.QuarkusSingleProfileConfigResolver.<init>(QuarkusSingleProfileConfigResolver.java:17)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.keycloak.quarkus.runtime.Environment.getCurrentOrCreateFeatureProfile(Environment.java:206)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureProfile(KeycloakProcessor.java:260)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:872)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1694)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at java.base/java.lang.Thread.run(Thread.java:1583)
2026-01-15 23:07:37,749 ERROR [managed.keycloak] (pool-33-thread-1) 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Start should not fail

### Actual behavior

It fails randomly

### How to Reproduce?

https://github.com/keycloak/keycloak/actions/runs/21048881157/job/60530559255?pr=45490
https://github.com/keycloak/keycloak/actions/runs/21060684793/job/60566425044?pr=45499

### Anything else?

Might be a regression in latest Quarkus updates?

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #45501

I was not able to reproduce the issue on my local machine, so this might be considered rather as an educated guess.

The `ConcurrentModificationException` for the `Configuration.getPropertyNames()` happens in the `QuarkusSingleProfileConfigResolver` during initializing profile. However, the iterator/stream over all the property streams seems to be modified somewhere. The property names object is an aggregated store of property names from individual config sources, which should be immutable. That may mean that we call the iterator when the runtime config is not fully initialized yet -> **We just wait for the runtime config completion on the Quarkus side.** But not sure why it started to fail now as recent changes do not uncover anything suspicious. 

Alternative issue -> AFAIK, the `SmallRyeConfig.getPropertyNames()` calls the interceptor chain via `iterateNames()` including our config interceptors. On the SmallRye side, they claim going over the property names should be thread safe and can be done concurrently. However, there might be some issues in our config interceptors that might provoke the CoModEx. 

@shawkins WDYT?

### CODE REVIEW

**Comment by mabartos** [comment]
Store IT tests failures are not related, and the rest of tests passed. 

I'll try to run the whole CI again to have it verified.

**Comment by shawkins** [comment]
@mabartos I vaguely remember seeing something like this before, but it was only happening with embedded. Is that the case here?

**Comment by mabartos** [comment]
@shawkins It happens even for the distribution (remote), and not only embedded: https://github.com/keycloak/keycloak/actions/runs/21060684793/job/60566425044?pr=45499

**Comment by mabartos** [comment]
Test failure not related: https://github.com/keycloak/keycloak/issues/45522

**Comment by mabartos** [comment]
I've run the full CI 2x, and I haven't seen the failure. Hopefully, it helped to solve the issue. 

cc: @ahus1

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 1]
```diff
@@ -243,6 +244,7 @@ FeatureBuildItem getFeature() {
 
     @Record(ExecutionTime.STATIC_INIT)
     @BuildStep
+    @Consume(RuntimeConfigSetupCompleteBuildItem.class)
```
Comment (ahus1) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:254]: Maybe adding a line comment of why this is Consumed would help our future selves to understand why it was added.

Comment (mabartos) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:254]: @ahus1 Agree; added.

**Review by ahus1 — APPROVED** [review]
Looks good to me. Will wait for someone else from the CND team to review it as well.

**Review by Pepo48 — APPROVED** [review]
LGTM. Thanks @mabartos.
