### PR TITLE
Ensure correct options are displayed for 'Archive format'

### LINKED ISSUE #17514: SAML2 Client Signing Keys Config does not accept PEM import
### Before reporting an issue

- [x] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I want to create a new SAML2 client in Keycloak and I want to require client signatures, I can click `Regenerate` and receive a private key. The conceptual problem is that
a) keycloak should never know the private key
b) I don't want to transfer the private key to my client. 
Private keys are private. They should be generated on the client and remain on the client. What I actually want to do is to import the client's public certificate as trusted.
This behaviour is broken since the Admin-UI redesign.
image

When I click on `Import Key` the dropdown seems to be broken:
image
I want either .crt or .pem import, but the only options available are JKS and PKCS12.

I can create a PKCS12 file on my client without a private key:
````
└─$ openssl pkcs12 -export -nokeys -in public.crt -name foo -out foo.p12                                         1 ⨯
Enter Export Password:
Verifying - Enter Export Password:
````
But if I import this in keycloak I get the following error:
image

What am I missing here? Keycloak does not need the client's private key, so why is this new dialog forcing me to give it one?

### Version

21.0.1

### Expected behavior

I can import a trusted cert from the client

### Actual behavior

I have to provide a private key or use the private key which keycloak generates, which does not make sense from a security perspective

### How to Reproduce?

1. Start fresh keycloak (e.g. use the getting-started-docker guide)
2. Create new Realm
3. Create new SAML2 client
4. Go to `Keys` Tab of the client configuration
5. Try to import a .pem or .crt public certificate from the client

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #17514

### CODE REVIEW

File: js/apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx [hunk 1]
```diff
@@ -99,6 +99,7 @@ export const KeyForm = ({
               variant={SelectVariant.single}
               aria-label={t("archiveFormat")}
               isOpen={openArchiveFormat}
+              menuAppendTo="parent"
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx:102]: The options in the dropdown were clipping on the bounds of the modal dialog, this helps prevent that.

**Review by agagancarczyk — APPROVED** [review]
