### PR TITLE
fix: adds additional info / warnings to hostname v2

### LINKED ISSUE #24815: Hostname config check on welcome page
### Description

When running Keycloak behind a loadbalancer / reverse proxy, Keycloak needs to know the hostname and schema of the loadbalancer for users to be able to log in for all the redirects. 

A lot of example explain how to set the hostname. Users then fail to log in as the loadbalancer is https, and Keycloak is running without https (which is shouldn't for security reasons). All they see is a blank screen, and only the browser console reveals some details.

It would be good to have a self-check as part of Keycloak's welcome screen which would check that the hostname and schema of the welcome screen match the settings in Keycloak. If they don't match, a descriptive error message should be shown, and logging in to the admin console should be disabled.

### Discussion

_No response_

### Motivation

Make it simpler for users to spot mis-configurations.

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #24815

### CODE REVIEW

**Review by Pepo48 — DISMISSED** [review]

**Comment by shawkins** [comment]
Added some refinements to #33209 on this pr as well - it can be done as a separate one if desired.

File: services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java [hunk 1]
```diff
@@ -41,16 +47,23 @@ public class HostnameV2ProviderFactory implements HostnameProviderFactory, Envir
...
         if (strictMode && hostnameRaw == null) {
             throw new IllegalArgumentException("hostname is not configured; either configure hostname, or set hostname-strict to false");
         } else if (hostnameRaw != null && !strictMode) {
             // We might not need this validation as it doesn't matter in this case if strict is true or false. It's just for consistency – hostname XOR !strict.
 //            throw new IllegalArgumentException("hostname is configured, hostname-strict must be set to true");
+            LOGGER.info("If hostanme is specified, hostname-strict is effectively ignored");
         }
-
+        
+        List<String> inUse = REMOVED_OPTIONS.stream().filter(s -> config.get(s) != null).toList();
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java:61]: @shawkins I believe this won't work as the config provider here has a scope that only contains options starting with `kc.spi-hostname-v2-`. The old options [had a prefix of `kc.spi-hostname-default-`](https://github.com/keycloak/keycloak/blob/25.0.6/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV1PropertyMappers.java#L21).

Since we don't have access to all config options through the SmallRye Config here, we have move it somewhere to quarkus module I'm afraid.

**Review by vmuzikar — CHANGES_REQUESTED** [review]

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 2]
```diff
@@ -28,5 +35,13 @@ public static PropertyMapper<?>[] getHostnamePropertyMappers() {
         .map(b -> b.isEnabled(() -> Profile.isFeatureEnabled(Profile.Feature.HOSTNAME_V2), "hostname:v2 feature is enabled").build())
         .toArray(s -> new PropertyMapper<?>[s]);
     }
+    
+    public static void validateConfig() {
+        List<String> inUse = REMOVED_OPTIONS.stream().filter(s -> Configuration.getOptionalKcValue(s).isPresent()).toList();
+        
+        if (!inUse.isEmpty()) {
+            LOGGER.errorf("Hostname v1 options %s are still in use, please review your configuruation", inUse);
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:43]:
```suggestion
            LOGGER.errorf("Hostname v1 options %s are still in use, please review your configuration", inUse);
```

**Review by vmuzikar — DISMISSED** [review]
LGTM, thanks!

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java [hunk 3]
```diff
@@ -42,6 +44,7 @@ public void run() {
         doBeforeRun();
         CommandLine cmd = spec.commandLine();
         HttpPropertyMappers.validateConfig();
+        HostnameV2PropertyMappers.validateConfig();
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java:47]: out-of-scope: We really need some abstraction over our property mappers and have the ability to add validators for the whole category mappers. As the validation for particular mappers should not be here (as shown above).

But it's out of scope of this PR - just sth to consider.

File: docs/guides/server/hostname.adoc [hunk 4]
```diff
@@ -48,7 +48,7 @@ The result of this configuration is that you can continue to access {project_nam
 
 == Using a reverse proxy
 
-When a proxy is in use, the `proxy-headers` should be set. Depending on the hostname settings, some or all of the URL, may be dynamically determined.
+When a proxy is in use for edge, reencrypt, or http passthrough, the `proxy-headers` should be set. Depending on the hostname settings, some or all of the URL, may be dynamically determined.
```
Comment (mabartos) [inline docs/guides/server/hostname.adoc:51]:
```suggestion
When a proxy is in use for edge, reencrypt, or https passthrough, the `proxy-headers` should be set. Depending on the hostname settings, some or all of the URL, may be dynamically determined.
```

**Review by mabartos — COMMENTED** [review]
@shawkins Just some typos. I don't want to block this PR due to these nitpicks, so merge it manually if necessary.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java (hunk 3 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java:47]: #27025 remains open to cover this.

File: docs/guides/server/hostname.adoc (hunk 4 above)
Comment (shawkins) [reply docs/guides/server/hostname.adoc:51]: I do mean http, not https, here. But calling it http passthrough is probably confusing.

Comment (shawkins) [inline docs/guides/server/hostname.adoc:51]:
```suggestion
When a proxy is in use for http, edge TLS, or reencrypt TLS, the `proxy-headers` should be set. Depending on the hostname settings, some or all of the URL, may be dynamically determined.
```

**Review by mabartos — APPROVED** [review]
@shawkins Looks better now, thanks!

cc @vmuzikar - just to be aware of the latest changes

**Review by vmuzikar — APPROVED** [review]
