### PR TITLE
Correct isValidScope method of TokenManager for Dynamic scopes

### LINKED ISSUE #13158: Correct isValidScope method of TokenManager for Dynamic scopes ( case scope ="openid")
### Describe the bug

When scope ="openid", method isValidScope return false beacause authorizationRequestContext.getAuthorizationDetailEntries is null or empty.
This method need to firstly remove "openid" scope from scope list and after check for  authorizationRequestContext.getAuthorizationDetailEntries is null or empty together with non empty scope list.

### Version

18.0.0

### Expected behavior

When scope ="openid", isValidScope method of TokenManager returns always true.

### Actual behavior

When scope ="openid", isValidScope method of TokenManager returns false.

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
Closes #13158

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@cgeorgilakis Looks good, Thanks for the PR!

Is it also possible to have some automated test for this?

**Comment by cgeorgilakis** [comment]
I do not know how to add tests for it. 
This PR together with [another PR](https://github.com/keycloak/keycloak/pull/13163), help us overcome tests failure and problems occured in account console when DYNAMIC_SCOPES is enabled.

Make DYNAMIC_SCOPES default feature and run all tests. You will see tests failures.
See also tests running in [this github actions](https://github.com/eosc-kc/keycloak/actions/runs/2825460909). The branch consists the two bug fixes together with DYNAMIC_SCOPES as default feature.
However, I do not think that any of them is appropriate test cases for this PR.

**Comment by mposolda** [comment]
@cgeorgilakis Sorry for the late reply. The GH action run https://github.com/eosc-kc/keycloak/actions/runs/2825460909 shows only test failures related to unit tests (which is due you added DYNAMIC_SCOPES feature). And I suppose that WebAuthn test failures are not related to your change, or are they? Could you please point which test is failing with DYNAMIC_SCOPES feature enabled by default?

One related note: if you are aware that some test is failing with the DYNAMIC_SCOPES feature enabled, then possibly you can create another test method, which will re-run existing test with the DYNAMIC_SCOPES feature enabled. For example if there is test like `testFooBar()`, which is OK without DYNAMIC_SCOPES, but it fails with DYNAMIC_SCOPES (before your change), then you can possibly do automated test just with something like this:

```
 // TODO remove this once DYNAMIC_SCOPES feature is enabled by default
@Test
@EnableFeature(value = Profile.Feature.DYNAMIC_SCOPES, skipRestart = true)
public void testFooBarWithDynamicScopesEnabled() {
    // Just use existing test with DYNAMIC_SCOPES feature enabled as it was failing with DYNAMIC_SCOPES
    testFooBar();
}
```

Will this work?

**Comment by cgeorgilakis** [comment]
Unit tests failed due to enabled dynamic scope feature. 
WebAuthn test failures are related with chrome driver problem. I do not know why. However, this PR WebAuthn tests are passing.
WebAuthn test failure exception: 
`Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
--   (unknown error: DevToolsActivePort file doesn't exist)
--   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)`

**Comment by mabartos** [comment]
@cgeorgilakis In the latest upstream, the WebAuthn tests are now ignored within GH Actions as we're aware of those failures.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java [hunk 1]
```diff
@@ -264,6 +266,34 @@ public void testWithClientBrowserOverride() throws Exception {
         events.expectLogin().client("test-app-flow").detail(Details.USERNAME, "test-user@localhost").assertEvent();
     }
 
+    // TODO remove this once DYNAMIC_SCOPES feature is enabled by default
+    @Test
+    @EnableFeature(value = Profile.Feature.DYNAMIC_SCOPES, skipRestart = true)
+    public void testWithClientBrowserOverrideWithDynamicScope() throws Exception {
+        // Just use existing test with DYNAMIC_SCOPES feature enabled as it was failing with DYNAMIC_SCOPES
+        oauth.clientId(TEST_APP_FLOW);
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java:274]: Thanks for this update.

One note: Is it possible to just directly call method `testWithClientBrowserOverride()` instead of copy/pasting the whole content of this method? It may be slightly better for the maintenance to avoid unecessary code duplicities.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java [hunk 2]
```diff
@@ -531,6 +561,52 @@ public void testClientOverrideFlowUsingBrowserHttpChallenge() {
         events.clear();
     }
 
+    // TODO remove this once DYNAMIC_SCOPES feature is enabled by default
+    @Test
+    @EnableFeature(value = Profile.Feature.DYNAMIC_SCOPES, skipRestart = true)
+    public void testClientOverrideFlowUsingBrowserHttpChallengeWithDynamicScope() {
+        // Just use existing test with DYNAMIC_SCOPES feature enabled as it was failing with DYNAMIC_SCOPES
+        Client httpClient = AdminClientUtil.createResteasyClient();
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java:569]: Same comment as above. It seems it is possibly to just invoke `testClientOverrideFlowUsingBrowserHttpChallenge()` method from here directly?

**Review by mposolda — CHANGES_REQUESTED** [review]
@cgeorgilakis Thanks for the automated tests. I've added some inline comments.

**Comment by cgeorgilakis** [comment]
Tests failures are ChallengeFlowTest.testChallengeFlow, FlowOverrideTest methods testClientOverrideFlowUsingBrowserHttpChallenge, testRestInterface, testWithClientBrowserOverride and RequiredActionUpdateProfileWithUserProfileTest ( enabled DECLARATIVE_USER_PROFILE feature).

I have added test method testClientOverrideFlowUsingBrowserHttpChallenge and testWithClientBrowserOverride with dynamic scopes enabled. I do recommented changes.

**Comment by mposolda** [comment]
@cgeorgilakis Thanks!

**Review by mposolda — APPROVED** [review]
