### PR TITLE
set the standardcharset to UTF-8 instead of relying on system charset…

### LINKED ISSUE #10462: v17/Quarkus Charset issue with LinkedIn IdP
### Describe the bug

I'm running LinkedIn IdP on Keycloak v17/Quarkus on a staging environment, and v16.1.1/WildFly on a production environment, with same configurations.

Everything is working fine on v16.1.1/WildFly, but on v17/Quarkus my first name which contains a `é` accent is not properly synched.

### Version

v17.0.0/v17.0.1

### Expected behavior

User data grabbed from LinkedIn response should be properly encoded.

### Actual behavior

First name is wrong

linkedin-charset-issue

### How to Reproduce?

- Create a linkedin account with a special character like `é` in the first name.
- Configure LinkedIn broker in Keycloak Quarkus v17.
- Login with LinkedIn in Keycloak.
- Check the created user in admin UI.
- First name has invalid characters instead of the special one.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DGuhr**
… in SimpleHttp

...as the system charset may cause problems when its non-UTF-8, e.g. when linking Identity Providers like Azure AD, Linkedin (see issue)

Closes #10462

### CODE REVIEW

File: server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java [hunk 1]
```diff
@@ -345,7 +346,7 @@ private void readResponse() throws IOException {
                             }
                         }
 
-                        try (InputStreamReader reader = charset == null ? new InputStreamReader(is) :
+                        try (InputStreamReader reader = charset == null ? new InputStreamReader(is, StandardCharsets.UTF_8) :
```
Comment (DGuhr) [inline server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java:349]: I'd like to leave this also as we shouldn't rely anywhere on system environment, especially when this leads to errors, but instead it's good practice to specify the charset.

**Review by pedroigor — APPROVED** [review]
