### PR TITLE
Register event not triggered on external to internal token exchange

### LINKED ISSUE #9684: Register event not triggered on token exchange
### Describe the bug

If a user is created when using [external token to internal token exchange](https://www.keycloak.org/docs/latest/securing_apps/#external-token-to-internal-token-exchange) no `EventType.REGISTER` is triggered

### Version

15

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #9684

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

File: services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java [hunk 1]
```diff
@@ -603,6 +604,13 @@ protected UserModel importUserFromExternalIdentity(BrokeredIdentityContext conte
                 logger.debugf("Email verified automatically after registration of user '%s' through Identity provider '%s' ", user.getUsername(), context.getIdpConfig().getAlias());
                 user.setEmailVerified(true);
             }
+
+            event.clone()
+                    .event(EventType.REGISTER)
+                    .user(user.getId())
+                    .detail(Details.REGISTER_METHOD, "token-exchange")
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java:611]: @douglaspalmer What about adding the broker alias as a detail? It should help to better recognize the broker from which the user originated.

**Review by pedroigor — APPROVED** [review]
