### PR TITLE
fix: adds hostname:v1

### LINKED ISSUE #25336: Add a hostname:v1 feature
### Description

To support #24252 the existing hostname options that will become deprecated should be associated with a v1 feature that will initially be enabled by default.  The new options for the hostname will be introduced under hostname:v2.  

Ideally this issue will also address associating options to features, so that validation / cli parsing is conditional on the usage of the feature.  This seems straight-forward with a sequence such as:

./kc.sh build --features=hostname:v1 ...
./kc.sh start ... - expects hostname v1 options

However auto builds may not straight-forward to do directly in picocli - but we can address expectations in the adjunct Picocli.validateConfig method.

cc @mabartos

### PR DESCRIPTION
**Pull request by shawkins**
closes: #25336

### CODE REVIEW

**Comment by shawkins** [comment]
@vmuzikar @mabartos I think this roughly covers adding a v1 hostname option. Some things to review:
- do we want the essential feature designation? It does allow for some better / earlier error messages. If not, then the logic in the DefaultHostnameProvider could be a catch all.
- What, if any, documentation is needed at this point - since this will always be enabled, and can't be disabled, that should probably wait until we're adding v2.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java [hunk 1]
```diff
@@ -17,218 +17,16 @@
...
-
-        return realmUrl;
-    }
 
-    @Override
-    public void close() {
+public final class DefaultHostnameProvider implements HostnameProviderFactory {
 
-    }
+    HostnameProvider provider;
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java:29]: Do we really want to have it package-private and accessible from the outside?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java [hunk 2]
```diff
@@ -237,121 +35,16 @@ public String getId() {
...
-            throw new RuntimeException("Strict hostname resolution configured but no hostname setting provided");
-        }
-
-        hostnameEnabled = (frontEndHostName != null || frontEndBaseUri != null);
-
-        if (frontEndBaseUri == null) {
-            strictHttps = hostnameEnabled && config.getBoolean("strict-https", false);
+    public void init(Scope config) {
+        if (Profile.isFeatureEnabled(Feature.HOSTNAME_V1)) {
+            this.provider = new V1HostnameProvider().init(config);
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java:44]: IMHO, this approach feels a bit odd, TBH. Each implementation of an SPI should have its own factory. Maybe we could rather use `EnvironmentDependentProviderFactory`? I think we don't need the explicit exception for when no hostname provider is enable. That should not normally happen as we don't allow disabling this feature.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@shawkins Thanks for the PR!

**Review by mabartos — COMMENTED** [review]
@shawkins LGTM in general. Just a few small suggestions. 

----------------------------
> do we want the essential feature designation? It does allow for some better / earlier error messages. If not, then the logic in the DefaultHostnameProvider could be a catch all.

In theory, what's the purpose of these features? To be able to enable/disable specific behavior, or some sort of add-ons, right? :) The Hostname feature is the first essential feature in Keycloak (in deep dive, we might argue if it's really essential, but it is rn) introduced due to requirements to have it versioned. My point is that this feature differs from the other ones, which are only additional features of the system.

But I'm ok to provide the first essential feature with the inability to disable it completely. I'd like to see a more verbose message, when it happens.
Something like:
```
Cannot disable '<some-feature>' feature as it is essential for the application. One of these features must be enabled: <some-feature1>, <some-feature2>.
```
_Probably quite long, but don't mind the wording._ 

It makes sense to me to catch it earlier than in the specific hostname factory. 

------------------------
> What, if any, documentation is needed at this point - since this will always be enabled, and can't be disabled, that should probably wait until we're adding v2.

IMO, agree that we can wait with it.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java [hunk 3]
```diff
@@ -17,218 +17,16 @@
...
-                }
-            }
-        }
-
-        return realmUrl;
-    }
 
-    @Override
-    public void close() {
+public final class DefaultHostnameProvider implements HostnameProviderFactory {
```
[the remark this answers is not in the document]
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java:27]: What @vmuzikar suggested would be better. See https://github.com/keycloak/keycloak/pull/26003#discussion_r1448703394

[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java:27]: It wouldn't compile - we're still resticting in maven to 1.8 for some reason.

File: common/src/main/java/org/keycloak/common/Profile.java [hunk 4]
```diff
@@ -192,6 +200,8 @@ public String getLabel() {
         }
     }
 
+    private static final Set<String> ESSENTIAL_FEATURES = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(Feature.HOSTNAME_V1.getUnversionedKey())));
```
[the remark this answers is not in the document]
Comment (vmuzikar) [reply common/src/main/java/org/keycloak/common/Profile.java:203]: Oh, right... :( IIRC, it's because of adapters that use this module...

**Comment by vmuzikar** [comment]
> I'd like to see a more verbose message, when it happens.

@mabartos Not sure we really need it. Currently you simply can't disable an essential feature, the config option doesn't allow it. IMHO that might be sufficient for now.

**Comment by shawkins** [comment]
@vmuzikar updated to the EnvironmentDependent interface. We can rename the DefaultHostnameProvider to V1, or just leave it as is since it looks like the plan is to eventually remove it. 

It also doesn't work very well to have isSupported() as deprecated, but not default - you end up having to implement both it and the other method signature. So I've changed it to have a default impl instead (alternatively isSupported(scope) could have been done through a new interface) - but if that doesn't seem necessary, it can be reverted.

File: server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java [hunk 5]
```diff
@@ -31,7 +31,10 @@ public interface EnvironmentDependentProviderFactory {
      * @return <code>true</code> if the provider is supported and should be available, <code>false</code> otherwise
      * @deprecated Prefer overriding/using the {@link #isSupported(Config.Scope)} method.
      */
-    boolean isSupported();
+    @Deprecated
+    default boolean isSupported() {
+        return false;
+    }
```
Comment (mabartos) [inline server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: I wouldn't change it. When some factory implements this interface, the assumption behind it is that there's really a need to check the environment setup and enable the factory based on specific conditions. I'd require to override the method.

I understand your input as both methods should be overridden when the Config.Scope is needed. However, AFAIK, there are only 2 cases (out of >70) when the scope is needed, otherwise the plain `isSupported()` is used. 
The JavaDoc is IMHO little bit misleading as I wouldn't consider it as a method, that should be deprecated. I think it should only emphasize the preference with the `isSupported(Config.Scope ...)` over the no-args method. 

@shawkins Does it work for you?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java [hunk 6]
```diff
@@ -354,4 +357,9 @@ private <T> T fromBaseUriOrDefault(Function<URI, T> resolver, URI baseUri, T def
 
         return defaultValue;
     }
+
+    @Override
+    public boolean isSupported() {
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java:362]: Should we rather implement the new non-deprecated `isSupported(Config.Scope config)`?

File: server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java (hunk 5 above)
Comment (vmuzikar) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: @mabartos I think this is not about which use cases need `Config.Scope` and which don't. The interface is defined in a way that `isSupported()` is deprecated and shouldn't be use in new implementations. Problem is, you must use it as it has no default value.

Comment (shawkins) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: Here's what I'm comfortable doing in this pr (as it's a small change):

- remove the deprecation
- change the deprecated method to have a default implementation

Or I can back the change out and we can log an issue for:

- removing the legacy method, which touches quite a few classes and I assume would hit the community as a breaking change as well
- introduce a new interface with the desired signature, so that the old interface can be deprecated - this will lead to a proper deprecation path where users can switch to the new interface to resolve the deprecation prior to the old interface being removed.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java (hunk 6 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java:362]: This was due to me waffling between the first two options listed in https://github.com/keycloak/keycloak/pull/26003#discussion_r1450346314 - let's make sure we agree on the approach and then I'll fix this method to match.

File: server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java (hunk 5 above)
Comment (vmuzikar) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: Removing the deprecation seems a bit out of scope of this PR given it's used at many places. I'd do that as a separate follow-up (we'll also need to involve the core team for that). For now we can just add a default impl for the deprecated method.

@mabartos Would that work for you?

Comment (mabartos) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: Yep, removing the deprecation requires explicit approval from the core team.  

> removing the legacy method, which touches quite a few classes and I assume would hit the community as a breaking change as well

Even when the deprecation is present there for some time, removing the method will not bring any additional value, quite the opposite. IMHO, the UX would be worse for the custom impls as I can imagine for the majority of cases, the scope is not needed at all - introduce such breaking change does not seem right to me. But it's for a different discussion. 

> @mabartos Would that work for you?

@vmuzikar @shawkins Yes, I prefer to add the default impl for the no-args method.

Comment (shawkins) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: > Removing the deprecation seems a bit out of scope of this PR given it's used at many places. I'd do that as a separate follow-up (we'll also need to involve the core team for that). For now we can just add a default impl for the deprecated method.

To clarify I mean that we should do one of these, not both. If we leave the method with a default impl and deprecated for a major release, then I'm fine with it being removed later.

But if you're thinking there doesn't seem to be any need to every remove it, then I'm also fine with opening another issue on removing the deprecation.

Comment (vmuzikar) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: I think we definitely should remove the deprecated method at some point, just maybe not in this PR. So I'm ok with just adding the default impl to it for now.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java (hunk 6 above)
Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java:362]: > Based upon the above it sounds like we'll leave the default and have the method still be deprecated, so I'll change this to the other signature.

Makes sense to me.

File: server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java (hunk 5 above)
Comment (shawkins) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: Correct, I'm not suggesting removing the deprecated method in this pr. 

The only consideration I'm raising about that could be in the scope of this pr is removing the deprecation - that is leave the method but not as deprecated and just assume we won't get around to ever removing it.

Comment (vmuzikar) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: > The only consideration I'm raising about that could be in the scope of this pr is removing the deprecation - that is leave the method but not as deprecated and just assume we won't get around to ever removing it.

Seems it was deprecated for a reason, not sure we should simply un-deprecate it. :)

Comment (shawkins) [reply server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java:37]: I can understand the intent behind why it was deprecated - but unfortunately that isn't the right way to do it. Without the default impl, it still needs to be implemented. Then even if deprecated you generally won't know it as a developer - the IDE will typically only show deprecated usage (instance.isSupported() - which here is not directly called by the implementor), nor will it be by default in the compile deprecation warnings when you run maven / javac. 

So the deprecation isn't really helpful. The only way to make that work as expected would be to introduce another interface and deprecate the old interface.

**Review by vmuzikar — DISMISSED** [review]
@shawkins LGTM, could you please rebase to resolve conflicts?

@mabartos Do you want to make a final review too?

I think we should also create a follow-up for the removal of the deprecated `supported` method. WDYT?

**Comment by shawkins** [comment]
> @shawkins LGTM, could you please rebase to resolve conflicts?

Sure - those pesky help tests strike again.

> I think we should also create a follow-up for the removal of the deprecated `supported` method. WDYT?

I'd also consider just making it not deprecated - https://github.com/keycloak/keycloak/pull/26003#discussion_r1452632466

**Comment by vmuzikar** [comment]
> I'd also consider just making it not deprecated

IMHO including config as a parameter makes sense. And just removing the parameter-less version of that method would clean the interface. So I'd vote for eventually removing the deprecated method. :)

**Review by vmuzikar — APPROVED** [review]

**Review by mabartos — APPROVED** [review]
LGTM; works for me like this.

**Comment by mabartos** [comment]
@vmuzikar Sorry that I merged it; it touches places out of CN responsibilities. Was it required approval from the core team?
