### PR TITLE
File storage: Fix path traversal

### LINKED ISSUE #17029: File store path traversal
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

The file storage basis from #16001 has postponed path traversal prevention. Fix it.

### Version

main

### Expected behavior

Path traversal not possible

### Actual behavior

Path traversal possible

### How to Reproduce?

Send request for object with specially crafted ID.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hmlnarik**
Fixes: #17029

### CODE REVIEW

File: model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java [hunk 1]
```diff
@@ -149,79 +153,77 @@ public Crud(Class<V> entityClass, Function<String, Path> dataDirectoryFunc, Func
...
-            return getPathForSanitizedId(Path.of(sanitizedId));
+            String[] escapedIdArray = ID_COMPONENT_SEPARATOR_PATTERN.split(escapedId);
+            return getPathForEscapedId(escapedIdArray);
         }
 
-        protected String sanitizeId(String id) {
-            Objects.requireNonNull(id, "ID must be non-null");
+        // Percent sign + Unix (/) and https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file reserved characters
+        private static final Pattern RESERVED_CHARACTERS = Pattern.compile("[%<:>\"/\\\\|?*=]");
+        private static final String ID_COMPONENT_SEPARATOR = ":";
```
Comment (hmlnarik) [inline model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java:182]: This is needed for React admin console to work as it does not handle slash and percent characters. See keycloak/keycloak-ui#4288.

File: model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java [hunk 2]
```diff
@@ -149,79 +153,77 @@ public Crud(Class<V> entityClass, Function<String, Path> dataDirectoryFunc, Func
...
             }
 
-            return getPathForSanitizedId(Path.of(sanitizedId));
+            String[] escapedIdArray = ID_COMPONENT_SEPARATOR_PATTERN.split(escapedId);
+            return getPathForEscapedId(escapedIdArray);
         }
 
-        protected String sanitizeId(String id) {
-            Objects.requireNonNull(id, "ID must be non-null");
+        // Percent sign + Unix (/) and https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file reserved characters
```
Comment (ahus1) [inline model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java:180]: The reserved chars listed here are only a subset of those reserved characters listed at the given URL. 

* Integer value zero, sometimes referred to as the ASCII NUL character.
* Characters whose integer representations are in the range from 1 through 31

I assume that the creation of such a file will fail, and there will be no harm done. As those file names would also be strange on Linux systems, I'd suggest to treat those characters as illegal and not even escape those. 

The docs also list LPT1 and other file names which shouldn't be used. I gave it a try on a recent Windows machine:  I was able to create those files with ported *nix tools on the file system, but wasn't able to retrieve the files with *OS/*indows tools, so the results are kind of mixed. I am not sure if harm can be done here, so I'd suggest to avoid those names on Windows file systems.

As those items are not necessarily related to the path traversal issue, feel free to consider them for a future issue.

**Review by ahus1 — CHANGES_REQUESTED** [review]
Hi @hmlnarik - I had a look and my tests showed that it fixes the original path traversal issue.

It also adds a workaround for the URI path problem in the UI, which doesn't fix all problems with the UI path. For example a client name "#" still leads to problems. There is `ReservedCharValidator` which contains additional characters which should not appear in URIs, and therefore shouldn't be part of IDs. As this PR started to handle the UI problems, I would consider this in-scope for this PR to complete this. If not, please create a new issue.

Looking at the `ReservedCharValidator` and how it is being used, a `/` character might actually not be a valid character in IDs, so the issue filed against the UI might be invalid.

See below for more comments.

File: model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java (hunk 2 above)
Comment (hmlnarik) [reply model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java:180]: > I assume that the creation of such a file will fail, and there will be no harm done

That is correct, and thus is not a concern too. I do not see the need of fixing those, since even in windows, they can be used inside a .zip archive which is one of the future paths for the file store.

**Comment by hmlnarik** [comment]
> Hi @hmlnarik - I had a look and my tests showed that it fixes the original path traversal issue.
> 
> It also adds a workaround for the URI path problem in the UI, which doesn't fix all problems with the UI path. For example a client name "#" still leads to problems. There is `ReservedCharValidator` which contains additional characters which should not appear in URIs, and therefore shouldn't be part of IDs. As this PR started to handle the UI problems, I would consider this in-scope for this PR to complete this. If not, please create a new issue.

This is not only a workaround for the UI but also fixes `/` vs `\` directory separator issue which would have to be dealt anyway. Fixing it for the React routes is a side-effect and has positive impact on the file store.

Neither URL nor `ReservedCharValidator` is a driving format of IDs of any store.

> Looking at the `ReservedCharValidator` and how it is being used, a `/` character might actually not be a valid character in IDs, so the issue filed against the UI might be invalid.

This is not a concern, please see above.

**Review by ahus1 — APPROVED** [review]
Thanks for providing some more context. I'm approving this.
