### PR TITLE
Convert the wizard to create client in progressive to validate every step

### LINKED ISSUE #42971: create clients without required value
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-js

### Describe the bug

In manage -> clients -> create clients, I can press 3. login setting button to jump to last setting page and save client without client id filled, which is required value. The new client doesn't have client id and I can't get in it's setting page to do anything.

### Version

26.3.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Create client page should stop me from jumping to last setting page or creating an invalid client.

### Actual behavior

I can create a client without client id

### How to Reproduce?

manage -> clients:
1. press create clients
2. press 3. login setting
3. press save

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #42971

Just adding the `isProgressive` to the client wizard. This option does not show the future step links in the left side, only the already completed ones (you can go back but cannot go forward). This way, the administrator needs to pass through the three steps and ensures that all the required fields are filled. I don't see any test failing, so I suppose the links were never tested.

### CODE REVIEW

**Comment by rmartinc** [comment]
@jonkoops @ssilvert This is the PR. It's just a one-liner. :smiley:

File: js/apps/admin-ui/src/clients/add/NewClientForm.tsx [hunk 1]
```diff
@@ -107,6 +107,7 @@ export default function NewClientForm() {
             onClose={() => navigate(toClients({ realm }))}
             navAriaLabel={`${title} steps`}
             onSave={save}
+            isProgressive={true}
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/add/NewClientForm.tsx]: Code style nit; boolean properties that are `true` can omit their value.
```suggestion
            isProgressive
```

**Review by jonkoops — APPROVED** [review]

File: js/apps/admin-ui/src/clients/add/NewClientForm.tsx (hunk 1 above)
Comment (rmartinc) [reply js/apps/admin-ui/src/clients/add/NewClientForm.tsx]: One line and it can be improved :facepalm:. Done now!

**Review by jonkoops — APPROVED** [review]

File: js/apps/admin-ui/src/clients/add/NewClientForm.tsx (hunk 1 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/clients/add/NewClientForm.tsx]: To be fair, this is something the linter should have picked up and fixed :P

**Review by mposolda — APPROVED** [review]
@rmartinc @jonkoops Thanks!
