### PR TITLE
Upgrade liquibase version to avoid a bug where a changeset is execute…

### LINKED ISSUE #23220: Update to Keycloak 22.0.3 fails: Migration failed for change set META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak
### Before reporting an issue

- [X] I have searched existing issues
- [x] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Update from 8.0.1 to 22.0.3 fails.

### Version

22.0.3

### Expected behavior

Update from older Keycloak to newer should work

### Actual behavior

During first start of Keycloak 22.0.3, Liquibase migration fails:

```
2023-09-13 22:10:38,059 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2023-09-13 22:10:38,059 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2023-09-13 22:10:38,059 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-13
.0.0.xml::default-roles::keycloak:
     Reason: liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "UK_J3RWUVD56ONTGSUHOGM184WW2-2"
  Detail: Key (name, client_realm_constraint)=(default-roles-default, 457fced9-8955-4979-951e-3e5507355372) already exists. [Failed SQL: (0) INSERT INTO keycloak.keycloak_role (ID, CLIENT_REALM_CONSTRAINT, C
LIENT_ROLE, DESCRIPTION, NAME, REALM_ID, REALM) VALUES ('380e0a09-9f4b-4214-8fd6-b9c4ea4253f3', '457fced9-8955-4979-951e-3e5507355372', FALSE, '${role_default-roles-default}', 'default-roles-default', '457fc
ed9-8955-4979-951e-3e5507355372', '457fced9-8955-4979-951e-3e5507355372')]
2023-09-13 22:10:38,059 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak:
     Reason: liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "UK_J3RWUVD56ONTGSUHOGM184WW2-2"
  Detail: Key (name, client_realm_constraint)=(default-roles-default, 457fced9-8955-4979-951e-3e5507355372) already exists. [Failed SQL: (0) INSERT INTO keycloak.keycloak_role (ID, CLIENT_REALM_CONSTRAINT, C
LIENT_ROLE, DESCRIPTION, NAME, REALM_ID, REALM) VALUES ('380e0a09-9f4b-4214-8fd6-b9c4ea4253f3', '457fced9-8955-4979-951e-3e5507355372', FALSE, '${role_default-roles-default}', 'default-roles-default', '457fc
ed9-8955-4979-951e-3e5507355372', '457fced9-8955-4979-951e-3e5507355372')]
2023-09-13 22:10:38,059 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: duplicate key value violates unique constraint "UK_J3RWUVD56ONTGSUHOGM184WW2-2"
  Detail: Key (name, client_realm_constraint)=(default-roles-default, 457fced9-8955-4979-951e-3e5507355372) already exists. [Failed SQL: (0) INSERT INTO keycloak.keycloak_role (ID, CLIENT_REALM_CONSTRAINT, C
LIENT_ROLE, DESCRIPTION, NAME, REALM_ID, REALM) VALUES ('380e0a09-9f4b-4214-8fd6-b9c4ea4253f3', '457fced9-8955-4979-951e-3e5507355372', FALSE, '${role_default-roles-default}', 'default-roles-default', '457fc
ed9-8955-4979-951e-3e5507355372', '457fced9-8955-4979-951e-3e5507355372')]
2023-09-13 22:10:38,060 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: duplicate key value violates unique constraint "UK_J3RWUVD56ONTGSUHOGM184WW2-2"
  Detail: Key (name, client_realm_constraint)=(default-roles-default, 457fced9-8955-4979-951e-3e5507355372) already exists.
2023-09-13 22:10:38,060 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the de
tails about the usage of the particular command.
```

### How to Reproduce?

Attempt to update Keycloak 8.0.1 to 22.0.3.
It worked to 21.*

### Anything else?

Multiple people in the discussion https://github.com/keycloak/keycloak/issues/9886 confirm that the problem started to occur again in 22.*.

### PR DESCRIPTION
**Pull request by vramik**
…d twice

Closes https://github.com/keycloak/keycloak/issues/23220

NOTE: the liquibase 4.23.2 is present in quarkus since 3.4.1: https://github.com/quarkusio/quarkus/blob/6c6c3b972b34268a34d5ca8f55858d494742ac0e/bom/application/pom.xml#L172

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java [hunk 1]
```diff
@@ -74,7 +74,7 @@ public SqlStatement[] generateStatements(Database database) {
         }
         try {
             // To check that the table already exists or not on which the index will be created.
-            if (!SnapshotGeneratorFactory.getInstance()
+            if (getTableName() == null || !SnapshotGeneratorFactory.getInstance()
```
Comment (vramik) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java:77]: It may happen that table is not yet set in scenario when [`generateStatements`](https://github.com/keycloak/keycloak/blob/58131f1dccb7113cb708407d6cf90842216c8d00/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java#L60) method is called from [`AbstractChange.supports`](https://github.com/liquibase/liquibase/blob/ae4f651d241c45f2d09d4c23d6da8a56446a6f17/liquibase-standard/src/main/java/liquibase/change/AbstractChange.java#L387) which is the case since this [change](https://github.com/liquibase/liquibase/pull/4476/files#diff-402d22cfe1bfa96a8a1ef2bc2210864d96082666359af99c266575781f40da89R109).

**Review by sguilhen — APPROVED** [review]
Thanks for the fix, @vramik ! LGTM!

**Review by ahus1 — APPROVED** [review]
Approving as of @sguilhen's review.

**Comment by lrozenblyum** [comment]
Thanks for the fix @vramik, @ahus1!
Is it planned to be ported to the 22.* release (as it's part of the 22.0.5 milestone)?

**Comment by ahus1** [comment]
@lrozenblyum - it is being considered for a backport. The major version bumb of Liquibase is something we usually want to avoid in a patch release, so that is why we are not sure yet.

**Comment by lrozenblyum** [comment]
I see and understand your concern @ahus1.
Anyway hoping for the backport to be able directly upgrading the legacy Keycloak to 22.*.
(NOTE: The bug affected multiple users as we saw in the recent discussion in https://github.com/keycloak/keycloak/issues/9886 and the workaround of 2-hop update is not applicable well for everyone).
