### PR TITLE
ResetPasswordTest.resetPasswordExpiredCode Error -> AbstractKeycloakTest.deleteAllCookiesForRealm:297

### LINKED ISSUE #33940: ResetPasswordTest.resetPasswordExpiredCode Error -> AbstractKeycloakTest.deleteAllCookiesForRealm:297
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Run - error: https://github.com/keycloak/keycloak/actions/runs/11336943763/job/31527876496

ResetPasswordTest>AbstractTestRealmKeycloakTest.beforeAbstractKeycloakTest:82->AbstractTestRealmKeycloakTest.deleteCookies:87->AbstractKeycloakTest.deleteAllCookiesForRealm:297 » Timeout timeout: Timed out receiving message from renderer: 10.000

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

clean cookies action should pass

### Actual behavior

clean cookies action timeouts 

### How to Reproduce?

Run particular GH action (Forms IT) with a predefined test case ResetPasswordTest.resetPasswordExpiredCode.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #33940

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/WaitUtils.java [hunk 1]
```diff
@@ -48,7 +48,7 @@ public final class WaitUtils {
 
     public static final String PAGELOAD_TIMEOUT_PROP = "pageload.timeout";
 
-    public static final Integer PAGELOAD_TIMEOUT_MILLIS = Integer.parseInt(System.getProperty(PAGELOAD_TIMEOUT_PROP, "10000"));
+    public static final Integer PAGELOAD_TIMEOUT_MILLIS = Integer.parseInt(System.getProperty(PAGELOAD_TIMEOUT_PROP, "60000"));
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/WaitUtils.java:51]: This seems to me a bit strange to change this. Increasing this timeout can have more side-effects on other places.

It looks to me that root cause of the issue is somewhere else. Are you able to reproduce this manually?

Comment (douglaspalmer) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/WaitUtils.java]: I revisited this. I can't reproduce locally. I did find in the logs that one test from ResetPasswordTest passes before all of the rest fail. Changing the click() calls to clickLink() calls in the Pages used by the passing test seems to fix the timeout issue.

**Review by mposolda — APPROVED** [review]
@douglaspalmer Ok, Thanks!
