### PR TITLE
Synchronize Maven surefire plugin with Quarkus

### LINKED ISSUE #41488: Synchronize Maven surefire plugin with Quarkus
### Description

We've seen some issues in the `quarkus-next` branch with the maven surefire as it causes some kind of instability for the windows agent: f.e. https://github.com/keycloak/keycloak/issues/41468

As stated even in our parent `pom.xml`, we should have aligned Surefire plugin with Quarkus:
```pom.xml
<!-- Needs to be aligned with Quarkus, see e.g. https://github.com/quarkusio/quarkus-quickstarts/blob/2.13.5.Final/getting-started-async/pom.xml#L14 -->
<surefire-plugin.version>3.0.0-M7</surefire-plugin.version>
```

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### LINKED ISSUE #41491: ExternalLinks are broken in documentation
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The documentation checks are not executed very often and when they're finally executed, they contains some wrong links. 

We should also find some way on how to at least test it on a nightly basis. EDIT: It is tested on a nightly basis, but no tests executed - see below.

```
Error:  Failures: 
Error:    ExternalLinksTest.checkExternalLinks:41 Broken links (3) in guide 'release_notes': 
		- file:/home/runner/work/keycloak/keycloak/docs/documentation/server_admin/target/generated-docs/index.html#_recovery-codes (invalid anchor _recovery-codes)
		- https://www.wildfly.org/news/2021/12/16/WildFly26-Final-Released/ (invalid redirect to )
		- https://www.wildfly.org/news/2021/10/05/WildFly25-Final-Released/ (invalid redirect to )
Error:    ExternalLinksTest.checkExternalLinks:41 Broken links (1) in guide 'server_admin': 
		- https://jwt.io/ (invalid redirect to https://www.jwt.io/)
Error:    ExternalLinksTest.checkExternalLinks:41 Broken links (2) in guide 'upgrading': 
		- file:/home/runner/work/keycloak/keycloak/docs/documentation/server_admin/target/generated-docs/index.html#_recovery-codes (invalid anchor _recovery-codes)
		- https://www.wildfly.org/news/2021/10/05/WildFly25-Final-Released/ (invalid redirect to )
```

It seems these tests are completely broken:
https://github.com/keycloak/keycloak/actions/runs/16545359256/job/46792168455
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Jul 28, 2025 12:25:39 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
org.junit.platform.commons.JUnitException: OutputDirectoryProvider not available; probably due to unaligned versions of the junit-platform-engine and junit-platform-launcher jars on the classpath/module path.
	at org.junit.platform.engine.EngineDiscoveryRequest.getOutputDirectoryProvider(EngineDiscoveryRequest.java:94)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:68)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:120)
	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:102)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:143)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

We need to include the enhancement for the maven surefire plugin: https://github.com/keycloak/keycloak/issues/41488

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests pass

### Actual behavior

Tests fail

### How to Reproduce?

Run the test

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #41488
- Closes #41491
- Blocked by and blocks: https://github.com/keycloak/keycloak/issues/41491

The version of the surefire was changed automatically by executing script:
```bash
./set-quarkus-version.sh 3.24.5
```

@Pepo48 @shawkins Could you please check it as you made changes to the script?

I expect that we might add some version overrides from the Quarkus parent pom.xml in the future

### CODE REVIEW

File: quarkus/set-quarkus-version.sh [hunk 1]
```diff
@@ -47,19 +47,36 @@ if [ "$QUARKUS_BRANCH" == "$DEFAULT_QUARKUS_VERSION" ]; then
 fi
 
 QUARKUS_BOM_URL="https://raw.githubusercontent.com/quarkusio/quarkus/$QUARKUS_BRANCH/bom/application/pom.xml"
+QUARKUS_PARENT_POM_URL="https://raw.githubusercontent.com/quarkusio/quarkus/$QUARKUS_BRANCH/independent-projects/parent/pom.xml"
+
+VERSIONS_FROM_QUARKUS_PARENT=(
+    "version.surefire.plugin"
+)
```
Comment (mabartos) [inline quarkus/set-quarkus-version.sh:54]: JFYI - IMO it's better approach to keep a list of versions that should be obtained from the Quarkus parent pom.xml than to update only the surefire for now. We'd need to fetch the parent pom.xml anyway.

**Comment by mabartos** [comment]
Failures in documentation caused by: https://github.com/keycloak/keycloak/issues/41491

File: quarkus/set-quarkus-version.sh [hunk 2]
```diff
@@ -47,19 +47,36 @@ if [ "$QUARKUS_BRANCH" == "$DEFAULT_QUARKUS_VERSION" ]; then
...
 QUARKUS_BOM=$(curl -f -s "$QUARKUS_BOM_URL")
+QUARKUS_PARENT_POM=$(curl -f -s "$QUARKUS_PARENT_POM_URL")
 
 echo "Setting Quarkus version: $QUARKUS_VERSION"
 
 $SCRIPT_DIR/../mvnw -B versions:set-property -f $SCRIPT_DIR/../pom.xml -Dproperty=quarkus.version -DnewVersion="$QUARKUS_VERSION" 1> /dev/null
 $SCRIPT_DIR/../mvnw -B versions:set-property -f $SCRIPT_DIR/../pom.xml -Dproperty=quarkus.build.version -DnewVersion="$QUARKUS_VERSION" 1> /dev/null
 
+for dependency in "${VERSIONS_FROM_QUARKUS_PARENT[@]}"; do
+    VERSION=$(grep -oP "(?<=<$dependency>).*(?=</$dependency)" <<< "$QUARKUS_PARENT_POM")
```
Comment (Pepo48) [inline quarkus/set-quarkus-version.sh]:
```suggestion
    VERSION=$(grep -oP "(?<=<$dependency>)[^<]*(?=</$dependency>)" <<< "$QUARKUS_PARENT_POM")
```

This should make it a little bit more strict, just to be on a safe side. Other than that LGTM. Thanks @mabartos!

Comment (mabartos) [reply quarkus/set-quarkus-version.sh]: Looks good, thanks!

**Comment by mabartos** [comment]
@Pepo48 We'd need to unfortunatelly add even the fix for Documentation. Otherwise the CI will not pass. 

They blocking each other as when we provide only the surefire upgrade, the documentation CI fail. If we provide only the fix for external links, we don't fully verify it's working in CI. Thus, I suggest to include them both to this PR.

@ahus1 Could you please check the second commit for fixing the ExternalLinks test? Thanks

**Comment by mabartos** [comment]
Docs tests passed:
https://github.com/keycloak/keycloak/actions/runs/16593799982/job/46935564791?pr=41489
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.keycloak.documentation.test.ExternalLinksTest
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.91 s -- in org.keycloak.documentation.test.ExternalLinksTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
```

**Comment by mabartos** [comment]
@Pepo48 @shawkins @ahus1 Ready for review. Thanks

**Review by ahus1 — APPROVED** [review]
I'm ok with the changes to the documentation.

**Review by Pepo48 — APPROVED** [review]
