### PR TITLE
Cors modifications for UserInfo endpoint

### LINKED ISSUE #26782: Accessing userinfo fails with CORS when token is expired or session is deleted
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I use [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/fetch) to access userinfo endpoint (http://localhost:8180/realms/hawtio/protocol/openid-connect/userinfo) and test various issues related to invalid token.

After successful public-client grant, I get a code (first stage) and access+refresh+id tokens (second stage). Using the access token I can access the userinfo endpoint.

Preflight `OPTIONS` request:
```
OPTIONS /realms/hawtio/protocol/openid-connect/userinfo HTTP/1.1
Host: localhost:8180
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0
Accept: */*
...
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization
...
Origin: http://localhost:3000
...
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
...
```

`OPTIONS` response:
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, DPoP, Authorization
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Max-Age: 3600
...
```

`GET` request:
```
GET /realms/hawtio/protocol/openid-connect/userinfo HTTP/1.1
Host: localhost:8180
...
authorization: Bearer <access token>
Origin: http://localhost:3000
...
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
...
```

`GET` response:
```
HTTP/1.1 200 OK
content-length: 98
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Expose-Headers: Access-Control-Allow-Methods
Content-Type: application/json
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
```

However there are two problems I found

1. Deleting KC session while the token is still valid (`nbf` and `exp` claims)

Preflight response is fine:
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, DPoP, Authorization
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Max-Age: 3600
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
content-length: 0
```

However the response misses all the CORS headers:
```
HTTP/1.1 401 Unauthorized
content-length: 0
Content-Type: text/plain;charset=utf-8
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
WWW-Authenticate: Bearer realm="hawtio", error="invalid_token", error_description="User session not found or doesn't have client attached on it"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```

And the browser shows:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8180/realms/hawtio/protocol/openid-connect/userinfo. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 401.
```

I can only detect 401, but it'd be nice to get the content of `WWW-Authenticate` header. See next point

2. Accessing user info endpoint after the token has expired

Preflight response is fine:
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, DPoP, Authorization
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Max-Age: 3600
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
content-length: 0
```

However the response itself is not quite fine:
```
HTTP/1.1 401 Unauthorized
content-length: 0
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Expose-Headers: Access-Control-Allow-Methods
Content-Type: text/plain;charset=utf-8
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
WWW-Authenticate: Bearer realm="hawtio", error="invalid_token", error_description="Token verification failed"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```

While 401 and `WWW-Authenticate: Bearer realm="hawtio", error="invalid_token", error_description="Token verification failed"` are expected, I'm getting only `Access-Control-Expose-Headers: Access-Control-Allow-Methods` header which mean the JavaScript can't access the information contained in `WWW-Authenticate`.

I can't call:
```javascript
response.headers.get('www-authenticate')
```

I would get it (checked under debugger) if I got `Access-Control-Expose-Headers: Access-Control-Allow-Methods, WWW-Authenticate`

### Version

23.0.5

### Expected behavior

Getting CORS headers also for failed requests.

### Actual behavior

Missing or insufficient CORS headers in case of token errors.

### How to Reproduce?

Use JavaScript client in browser and 1) remove the session at KC side, 2) wait till the token is expired without refreshing it.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #26782

CORS are not added in user-info endpoint if the session is not found. The www-authenticate header is also added to the exposed headers if returned. Tests added.

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/cors/DefaultCors.java [hunk 1]
```diff
@@ -117,7 +117,10 @@ public Cors allowedMethods(String... allowedMethods) {
 
     @Override
     public Cors exposedHeaders(String... exposedHeaders) {
-        this.exposedHeaders = new HashSet<>(Arrays.asList(exposedHeaders));
+        if (this.exposedHeaders == null) {
+            this.exposedHeaders = new HashSet<>();
+        }
+        this.exposedHeaders.addAll(Arrays.asList(exposedHeaders));
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/cors/DefaultCors.java:123]: This changes the behaviour a bit to add `exposedHeaders` to `this.exposedHeaders` instead of overriding it how it was before. This is also not compatible with other methods like `allowedMethods` etc.

Can we perhaps either:
- Add new method like `addExposedHeaders` to both `Cores` and `DefaultCors`
- Rename the existing method to something like `addExposedHeaders` .

I prefer the first option, but second is fine if you prefer it for some reason

Comment (rmartinc) [reply services/src/main/java/org/keycloak/services/cors/DefaultCors.java]: Option 1 done! Let's see the tests!

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks!
