### PR TITLE
Enforcing expiration and issued for claims when validating ID tokens as claim tokens

### LINKED ISSUE #46717: UMA permission grant accepts ID token issued to a different client
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When a client is calling the UMA endpoint with its client credentials and and ID token, Keycloak does not check that the token presented is connected to the client calling the API.

This is a similar problem like #46716

### Version

26.5.2

### Regression

- [ ] The issue is a regression

### Expected behavior

If the `azp` in the call doesn't match the client, the call should be rejected. 

(I'm assuming for an ID token the `azp` and the `aud` are the same)

### Actual behavior

The token is accepted.

### How to Reproduce?

* Call the UMA RPT with the ID Token issued for the admin user to the admin-cli client 

### Anything else?

This has been assessed as a hardening issue as the attacker needs the client credentials.

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #46717
Closes #46716

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java [hunk 1]
```diff
@@ -193,7 +193,7 @@ protected List<String> getArgs(Map<String, String> env) {
         }
 
         if (System.getProperty("auth.server.host") != null) {
-            commands.add("-Dauth.server.host=" + System.getProperty("auth.server.host"));
+//            commands.add("-Dauth.server.host=" + System.getProperty("auth.server.host"));
```
Comment (sguilhen) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java]: Do these need to be commented out? Can't we just remove these lines?

Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java]: Not related ... Removed.

**Review by sguilhen — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
