### PR TITLE
Fix totp manual link for proxy mode

### LINKED ISSUE #11774: Configure Otp with manual url is not generating the url correctly when keycloak is behind a reverse proxy on an url like http://www.host.com/auth
### Describe the bug

We have a keycloak that is running on an url like http://www.host.com/auth

There is a reverse proxy that is redirecting every request on http://ip:another_port/auth on a docker that expose keycloak on http://ip:port/

The TotpBean is getting an uriBuilder in its contructor. This UriBuilder corresponds to the UriInfo where the request is arriving, it's not based on the keycloak configuration that is defining the correct host and path

### Version

17.0.0

### Expected behavior

The request generated by the TotpBean for the manual url should be http://www.host.com/auth/manualUrl

### Actual behavior

The request generated by the TotpBean for the manual url is http://host.com/manualUrl

### How to Reproduce?

1 - Use a reverse proxy like apache or nginx
2 - Make Your keycloak run on ip:port/
3 - Reverse proxy the url on ip:another_port/auth on your keycloak that is running ip:port/
4 - Go to the OTP configuration page
5 - Try to switch on manual URL, the url is pointing on /manualUrl and not on /auth/manualUrl

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by RobYed**
This PR fixes the totp manual mode url when using keycloak behind a reverse proxy.

Unfortunately I haven't been able to write a test for this very special case. However, I have manually tested my implementation responsibly. Please let me know if you have any ideas on how to simulate a reverse proxy within the tests.

Closes #11774

### CODE REVIEW

**Comment by stianst** [comment]
This change shouldn't be needed as uriInfo should already be the front-end url. Have you properly configured the hostname for Keycloak? I.e. take a look at the openid connect well-known endpoints and make sure they have the correct URLs.

**Review by stianst — CHANGES_REQUESTED** [review]
I think this is down to invalid hostname configuration and should be fixed by properly configuring the hostname/proxy settings for Keycloak.

**Comment by RobYed** [comment]
As already pointed out in #11774 I do not think this is a configuration issue. 

Why would `uriInfo.getBaseUriBuilder()`[FreeMarkerLoginFormsProvider.java](https://github.com/keycloak/keycloak/pull/13485/commits/ba9b3a19a2834fbb30f133fb371dbebfa937c1da#diff-907f2f4ebf2325e60f99d994c49f56c8c5b7da4794b29cbb64e20ababba381df) return the correct URL in case the hostname is configured improperly? 

I might be wrong. I don't know every implementation detail of Keycloak. I just wonder why everything works fine expect that single link of the OTP form.

**Review by stianst — DISMISSED** [review]

**Comment by stianst** [comment]
@RobYed you're right, I've had a second look at this, and as it currently is it does indeed bypass the whole hostname provider, which is basically what you've fixed here, so this PR should be all good. Thanks.

**Comment by stianst** [comment]
PR itself looks good to me, but there's one related test that is failing:
RequiredActionTotpSetupTest.setupTotpModifiedPolicy:315 » NoSuchElement Unable to locate element with ID: kc-totp-type

**Comment by RobYed** [comment]
@stianst Nice to see the PR approved. Thanks! As I am on vacation I will not be able to work on this for the next two weeks. I will have a look into it then.

**Comment by RobYed** [comment]
@stianst I tried to reproduce the [test errors of former workflows](https://github.com/keycloak/keycloak/actions/runs/3192544556/jobs/5210303050) locally in order to finish this PR - without success.

I followed the guidelines in `/testsuite/integration-arquillian/HOW-TO-RUN.md`. I first built the project and then executed the previously failing tests with:
`mvn -f testsuite/integration-arquillian/pom.xml clean install -Dtest=AppInitiatedActionTotpSetupTest` and
`mvn -f testsuite/integration-arquillian/pom.xml clean install -Dtest=RequiredActionTotpSetupTest`

Could you please execute the workflow again with the latest code changes from main? Maybe the tests got somehow magically fixed in the meantime.

**Comment by RobYed** [comment]
I really would love to see this PR merged. What should I do to reproduce the failing tests locally?

**Comment by pedroigor** [comment]
@RobYed Looks like the failures are related. Could you please try running the failing tests locally?

**Comment by RobYed** [comment]
@pedroigor That's exactly what I did. Please see [my comment above](https://github.com/keycloak/keycloak/pull/13485#issuecomment-1323216019).

File: services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java [hunk 1]
```diff
@@ -305,6 +305,18 @@ private boolean isDynamicUserProfile() {
...
 
+    /**
+     * Get sure that correct hostname and path is used for totp form.
+     * Relevant when running in proxy mode.
+     *
+     * @return UriBuilder with configured hostname and path set
+     */
+    private UriBuilder getTotpUriBuilder() {
+        return uriInfo.getBaseUriBuilder()
+                .path(uriInfo.getRequestUri().getPath())
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java:316]: Try changing to `replacePath`. Otherwise, the resulting URL would include two occurrences of `/auth`.

**Review by pedroigor — CHANGES_REQUESTED** [review]
Hi @RobYed, sorry for the delay.

I've run your branch locally and the issues seem to be related to an additional `/auth` path in URLs.

File: services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java (hunk 1 above)
Comment (RobYed) [reply services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java:316]: Thanks @pedroigor. I am going to try this.

Comment (RobYed) [reply services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java]: @pedroigor I applied your suggested change. Seems to work as expected :)

**Comment by RobYed** [comment]
Looks like a progress 👍 
What can we do about the flaky cypress tests?

**Review by pedroigor — APPROVED** [review]
