### PR TITLE
Instead of an InputStream that doesn't know about its encoding, use a String

### LINKED ISSUE #20916: DefaultHttpClientFactory should handle the encoding of the response
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

As a follow-up to #20897, the response should respect the returned content type and its charset when handling the response in `DefaultHttpClientFactory`. 

### Version

main

### Expected behavior

A response is decoded using the correct charset.

### Actual behavior

An `InputStream` is returned and the callers will decode it later using the JVM's default charset.

### How to Reproduce?

(by code review)

### Anything else?

In the different places where this is being called, it would be better to return a readily decoded String instead of using an InputStream with an unknown encoding.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #20916

### CODE REVIEW

**Comment by ahus1** [comment]
@rmartinc - some time I ago I stumbled about the situation that the HTTP client fetches resources, and then passes around an `InputStream` without handling the encoding of the contents. 

This PR changes this, with some corner cases still existing when a file is uploaded. 

As you have been touching this code lately, I'd be happy if you could give it a review when you have the time. Thanks!

File: services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java [hunk 1]
```diff
@@ -107,20 +108,14 @@ public int postText(String uri, String text) throws IOException {
...
                 HttpGet request = new HttpGet(uri);
                 HttpResponse response = httpClient.execute(request);
-                int statusCode = response.getStatusLine().getStatusCode();
-                HttpEntity entity = response.getEntity();
-                if (statusCode < 200 || statusCode >= 300) {
-                    EntityUtils.consumeQuietly(entity);
-                    throw new IOException("Unexpected HTTP status code " + response.getStatusLine().getStatusCode() + " when expecting 2xx");
-                }
-                if (entity == null) {
+                String body = responseHandler.handleResponse(response);
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:114]: I would have preferred to use `EntityUtils.toString(response.getEntity())` which is what this handler is doing in the end. Just because it would be easier to be changed in the future. But just nitpicking. It's approved anyway.

**Review by rmartinc — APPROVED** [review]
@ahus1 LGTM! Just a nitpicking comment but approved anyway!

Two things to consider. They can be followups.

1. The class Response class in [SimpleHttp](https://github.com/keycloak/keycloak/blob/24.0.1/server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java#L353-L389) is doing something similar. Maybe we can change to use `BasicResponseHandler` or `EntityUtils` apache http-client classes like you are doing here.
2. There is a weakness issue #27293 which maybe we can consider now for 25.0.0 as we are reading strings. The httpcllient5 added a variant for [EntityUtils.toString](https://github.com/apache/httpcomponents-core/blob/master/httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/EntityUtils.java#L369) with max length parameter in 5.2. But I suppose the upgrade is complicated.

File: services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java (hunk 1 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:114]: I didn't want the error handling to be duplicated which is already present in the `AbstractResponseHandler`. Still I agree it is a matter of how much changes we would expect here in the future.

**Comment by ahus1** [comment]
@rmartinc - thank you for approving. I'd be +1 for handling the other items as follow-ups.

File: server-spi-private/src/main/java/org/keycloak/connections/httpclient/HttpClientProvider.java [hunk 2]
```diff
@@ -53,8 +52,8 @@ public interface HttpClientProvider extends Provider {
      * Helper method
      *
      * @param uri
-     * @return response stream, you must close this stream or leaks will happen
+     * @return Body of the response
      * @throws IOException On network errors, no content being returned or a non-2xx HTTP status code
      */
-    public InputStream get(String uri) throws IOException;
+    public String get(String uri) throws IOException;
```
Comment (hmlnarik) [inline server-spi-private/src/main/java/org/keycloak/connections/httpclient/HttpClientProvider.java:58]: This means that every HTTP response returns a `String`. Is this really the case? Considering extensions that use this (unsupported) API, I'd suggest considering addition of a new method (e.g. `getAsString`, perhaps with a default implementation) rather than changing existing method.

**Review by hmlnarik — COMMENTED** [review]
While automatic handling of `String` responses is a good addition for dev UX, I wonder if it covers all the cases. Please see inline

File: server-spi-private/src/main/java/org/keycloak/connections/httpclient/HttpClientProvider.java (hunk 2 above)
Comment (ahus1) [reply server-spi-private/src/main/java/org/keycloak/connections/httpclient/HttpClientProvider.java:58]: All occurrences I found in the code fetch either JSON or XML from a remote source. As stated in the original issue, and handling of encoding is lost in those cases. 

Extensions can still use `getHttpClient()` if they want to go beyond this. As it is an internal API, I'd rather keep its surface small. 

If that doesn't convince you, I'd go for two methods `getString()` and `getInputStream()` with JavaDoc explaining when to use one or the other.

Comment (hmlnarik) [reply server-spi-private/src/main/java/org/keycloak/connections/httpclient/HttpClientProvider.java:58]: I like the new way where the encoding is correctly handled, so the `getString` method is a valuable addition.

Since this provider can be used to retrieve binary data in simple use cases (e.g. retrieve image in a mapper), a `HttpClient` reference is viable but adds unnecesary complexity. Thus the two methods would be my preferred option.

**Review by hmlnarik — APPROVED** [review]
Thank you for the change!
