### PR TITLE
making the update reason and recreate annotations stable

### LINKED ISSUE #38487: [Keycloak Operator CI] - Test remote (slow) - UpdateTest.testExplicitStrategy
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 763.939 s <<< FAILURE! - in org.keycloak.operator.testsuite.integration.UpdateTest
Error:  org.keycloak.operator.testsuite.integration.UpdateTest.testExplicitStrategy  Time elapsed: 166.643 s  <<< FAILURE!
java.lang.AssertionError: java.util.concurrent.TimeoutException
	at org.keycloak.operator.testsuite.integration.UpdateTest.await(UpdateTest.java:255)
	at org.keycloak.operator.testsuite.integration.UpdateTest.testExplicitStrategy(UpdateTest.java:194)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:960)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:810)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.keycloak.operator.testsuite.integration.UpdateTest.await(UpdateTest.java:253)
	... 6 more
```

https://github.com/keycloak/keycloak/actions/runs/14096028509/job/39484001270

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #38487

The second commit shows what this test looks like against just the api server - that can be left off of this commit if desired as it has the obvious drawback of needing to emulate a statefulset controller. @pruivo @vmuzikar @mabartos what do you think?

The core fix is that we want to preserve the new annotations when possible from the existing deployment - they are still relevant on the current status even when the rolling or recreate has completed.

### CODE REVIEW

**Comment by shawkins** [comment]
The test failure in the first run is due to a weakness in our testing assumptions - and similarly causes some of the other tests be flakey as well.

Here we're checking for Ready=False with a particular reason, but that is an ephemeral state. Even with using informers to pick up all status changes does not guarentee that we'll see that state - for two reasons:
1. the informer can reconnect to the api server in such a way as to restart the watch, so we skip over intermediate events - this is not very likely given that bookmarks are in use, but it can still happen.
2. the event(s) that would have ultimately resulted in the update of the Keycloak status into the desired ephemeral state, were interrupted in some way - most likely a 409 error updating something - such that by the time we retry, we're in a different state.

**Comment by vmuzikar** [comment]
> The second commit shows what this test looks like against just the api server - that can be left off of this commit if desired as it has the obvious drawback of needing to emulate a statefulset controller. @pruivo @vmuzikar @mabartos what do you think?

I would rather stick to integration test in this case, feels too "artificial" to mock statefulset controller.

**Comment by shawkins** [comment]
> I would rather stick to integration test in this case, feels too "artificial" to mock statefulset controller.

There are of course tradeoffs. The reason the mocking here is so complete is to ensure that we generate intermediate states for the statefulset to match our test expectations looking for things like Ready=False - as explained above those are actually a little problematic in any case.

We could simplify the assertions and the mock logic instead of simulating up / down handling could just make the new statefulset seem immediately available.

In the end it's about the amount of coverage for how long the test takes. As written, the api server version of the test runs in less than 20 seconds. The integration test currently takes 1-2 minutes. I can tweak the integration test to instead disable probes (we don't really need the server to come up for this test), but it will still take nearly twice as long as the apiserver test - without any additional increase in coverage from the perspective of the operator.

Another benefit of the apiserver testing locally is that it's faster to restart testing - there's no namespace to cleanup / setup, and no database needed.

The last thought is that these testing approaches don't have to be mutually exclusive. The test logic here is the same whether it's being run against the apiserver only or a full kubernetes - if we're sufficiently clever, then we could have a single definition of a test, but three testing modes local, remote, and apiserver.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java [hunk 1]
```diff
@@ -147,23 +146,33 @@ public StatefulSet desired(Keycloak primary, Context<Keycloak> context) {
...
 
-        var existingDeployment = ContextUtils.getCurrentStatefulSet(context).orElseThrow();
-
         // version 22 changed the match labels, account for older versions
         if (!existingDeployment.isMarkedForDeletion() && !hasExpectedMatchLabels(existingDeployment, primary)) {
             context.getClient().resource(existingDeployment).lockResourceVersion().delete();
             Log.info("Existing Deployment found with old label selector, it will be recreated");
         }
 
+        baseDeployment.getMetadata().getAnnotations().put(Constants.KEYCLOAK_UPDATE_REASON_ANNOTATION, ContextUtils.getUpdateReason(context));
```
Comment (pruivo) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:174]: Is updating the metadata safe without using the "builder" classes?

File: operator/src/test/java/org/keycloak/operator/testsuite/apiserver/UpdateTest.java [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+    public void testExplicitStrategy() throws InterruptedException, ExecutionException, TimeoutException {
+        var operator = BaseOperatorTest.createOperator(k8sclient);
+        operator.start();
+
+        var kc = createInitialDeployment(UpdateStrategy.EXPLICIT);
+
+        var updateCondition = assertUnknownUpdateTypeStatus(kc);
+
+        // fake statefulset controller
+        k8sclient.apps().statefulSets().withName(KeycloakDeploymentDependentResource.getName(kc))
```
Comment (pruivo) [inline operator/src/test/java/org/keycloak/operator/testsuite/apiserver/UpdateTest.java:83]: `close()` is never invoked on the informer. Does it matter?

File: operator/src/test/java/org/keycloak/operator/testsuite/apiserver/UpdateTest.java [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+                int replicas = obj.getSpec().getReplicas();
+                String revision = String.valueOf(Math.abs(obj.getSpec().hashCode()));
+                if (!Objects.equals(Optional.ofNullable(obj.getStatus().getReplicas()).orElse(0), replicas)
+                        || !Objects.equals(revision, obj.getStatus().getUpdateRevision())
+                        || !Objects.equals(obj.getStatus().getCurrentRevision(), obj.getStatus().getUpdateRevision())) {
+                    // generate intermediate rolling events
+                    int actualReplicas;
+                    if (!Objects.equals(revision, obj.getStatus().getUpdateRevision())) {
+                        actualReplicas = 0;
+                    } else if (replicas == 0) {
```
Comment (pruivo) [inline operator/src/test/java/org/keycloak/operator/testsuite/apiserver/UpdateTest.java:101]: Can this branch be removed? 
If the replicas < status.replicas then you decrement the number of replicas, otherwise you increment.

Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/apiserver/UpdateTest.java:101]: If the revision doesn't match the updateRevision, then we are rolling in another spec change. Setting the replicas to 0 represents taking everything offline, then we let subsequent events handle the roll up. Hybrid of serial and parallel handling.

You don't have to have a replica change with a spec change, so the other handling with incrementing / decrementing won't do anything if the replicas are left the same in the CR.

Comment (pruivo) [reply operator/src/test/java/org/keycloak/operator/testsuite/apiserver/UpdateTest.java:101]: Right! forgot about the rolling update :facepalm:

**Review by pruivo — APPROVED** [review]
LGTM

**Comment by shawkins** [comment]
To keep this pr moving quickly, I've pulled out the apiserver test approach - I'll refine that and bring it back in another pr.

**Review by ahus1 — APPROVED** [review]
Approving based on @pruivo's review. Thank you for this change,  @shawkins, you're going to amazing depth with the Operator SDK here.
