### PR TITLE
Handle HTTP response codes when retrieving data from remote endpoints

### LINKED ISSUE #20895: Keycloak's default http client doesn't check HTTP response code
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

When retrieving information via HTTP like for example information from a discovery endpoint like in #20802, Keycloak will not check the HTTP response code. 

This leads to a situation that data is processed when it shouldn't, as the caller is assuming it is a successful call. 
While `HttpClientProvider#get()` can return null, no caller ever checks that, leading to NPEs.

### Version

main

### Expected behavior

On non-2xx-responses, an error should be logged and the response shouldn't be processed any futher.

### Actual behavior

Non-2xx-responses are processed.

### How to Reproduce?

* Start Keycloak locally on port 8080 (Quarkus default in start-dev)
* Go to *Identity Providers* and create a new one
* Use `http://localhost:8080/realms/master/.well-known/missing` as a URL that returns 404 to retrieve the settings

### Anything else?

While this issue is about handling the response code, a follow-up issue should revisit the interface again to ensure that the response is processed with the right encoding/content type. At the moment the input streams are read using Keycloak's encoding, while they should be parsed using the encoding returned by the called server.

This follow-up issue should be tackled once this issue has been resolved.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #20895

### CODE REVIEW

File: services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java [hunk 1]
```diff
@@ -110,8 +110,15 @@ public int postText(String uri, String text) throws IOException {
             public InputStream get(String uri) throws IOException {
                 HttpGet request = new HttpGet(uri);
                 HttpResponse response = httpClient.execute(request);
+                int statusCode = response.getStatusLine().getStatusCode();
                 HttpEntity entity = response.getEntity();
-                if (entity == null) return null;
+                if (statusCode < 200 || statusCode >= 300) {
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:115]: Interesting that you have to check this range manually. Isn't there a [`Response.ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) equivalent here?

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
As you mentioned before, we should be more strict about the request and response media types. As well as make sure the client code is properly handling response errors in order to provide a better message or fallbacks.

For now, LGTM.

File: services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java (hunk 1 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:115]: The closest I found is a `BasicResponseHandler` which would return a `String`, but not an `InputStream`. For the next refactoring where we rework the returned media types, we'd change this code to probably use a `BasicResponseHandler`.

**Comment by ahus1** [comment]
@pedroigor - thank you for the review. I opened a follow-up issue #20916 for this.

File: services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java (hunk 1 above)
Comment (mposolda) [inline services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:115]: One note: This won't handle redirections. Is it on purpose? Or is it any issue with switching the latter part to `statusCode >= 400)` ?

I wonder about scenario like:
- Well-known endpoint configured for some IDP to `https://my-idp-public-endpoint`
- This will redirect to something like `https://my-real-endpoint` 

On the other hand, HttpClient should do some redirections automatically, so maybe this is not an issue?

Comment (ahus1) [reply services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:115]: @mposolda - HttpClient will already to an automatic redirect on GET, see https://hc.apache.org/httpcomponents-client-4.5.x/current/httpclient/apidocs/org/apache/http/impl/client/DefaultRedirectStrategy.html. If we would end up with a 301 here, the body would be empty anyway, and the current code can't continue. 

The code I added here is similar to https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/impl/client/AbstractResponseHandler.java#L64-L74 which I'll use in a follow-up PR listed above.

Comment (jonkoops) [reply services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:115]: Yeah, `BasicResponseHandler` seems like a good solution. Was just wondering :)

Comment (mposolda) [reply services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:115]: @ahus1 Yes, That's what I though (about httpClient doing automatic redirection) , but wasn't 100% sure. Thanks for answer this!
