### PR TITLE
fix: include debug logging for init

### LINKED ISSUE #33109: Infinite loop when accessing account management console
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Hello,

We set up Keycloak with docker-compose and Apache proxy.
The admin console is accessible and working fine.
We are able to connect to Nextcloud or Wordpress thanks to Keyloaker.
But when we try to go to https://\<url\>/realms/master/account, the page is infinitly loading (see screenshot).

image

When i open the console, it says this : 

image

--------------------------------

Docker compose config :

keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    env_file: .env
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db:5432/$KC_DB_NAME
      - KC_DB_USERNAME=$KC_DB_USER
      - KC_DB_PASSWORD=$KC_DB_PASS
      - KC_HOSTNAME=https://\<url\>
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_LEVEL=info
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=$ADMIN_NAME
      - KEYCLOAK_ADMIN_PASSWORD=$ADMIN_PASS
    command: start-dev
    depends_on:
      - keycloak_db
    ports:
      - 19830:8080
    networks:
      - xxx

--------------------------------

Apache config :  

\<VirtualHost *\:80\>
    ServerName \<url\>
    Redirect permanent / https://\<url\>
\<\/VirtualHost\>

\<VirtualHost *:443\>
    ServerName \<url\>

    Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"

    SSLEngine ON
    SSLProtocol all -SSLv2 -SSLv3
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
    SSLCertificateFile /etc/letsencrypt/live/<url>/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/<url>/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/<url>/chain.pem

    ProxyRequests Off
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:19830/ connectiontimeout=60 timeout=60 retry=1 Keepalive=On
    ProxyPassReverse / http://127.0.0.1:19830/

    # Logs
    CustomLog "/var/log/apache2/wordpress/access" common
    ErrorLog "/var/log/apache2/wordpress/error"
\<\/VirtualHost\>

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Access the Account Management Console.

### Actual behavior

Infinite loop when accessing the Account Management Console.

### How to Reproduce?

Go to https://\<url\>/realms/master/account

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
Since we have seen several similar issues, it might be helpful to users to see additional debugging.

closes: #33109

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java [hunk 1]
```diff
@@ -60,12 +63,21 @@ public Response preCheck(@QueryParam("client_id") String clientId, @QueryParam("
...
                 if (validWebOrigins.contains("*") || validWebOrigins.contains(origin)) {
                     return Response.noContent().build();
                 }
+                if (logger.isDebugEnabled()) {
+                    logger.debugf("client %s does not allow origin=%s for requestOrigin=%s (as determined by hostname settings), init will return a 403", clientId, origin, requestOrigin);
+                }
+            } else {
+                if (logger.isDebugEnabled()) {
+                    logger.debugf("client %s does not exist or not enabled, init will return a 403", clientId);
+                }
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java:77]: Unrelated to this implementation, but does `debugf()` itself not check if debugging is enabled? Also, why is this not needed for the `logger.debug()` call below?

Comment (shawkins) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java]: > Unrelated to this implementation, but does debugf() itself not check if debugging is enabled?

It does, and it is checked prior to the formatting of the string, so it is unnecessary here.

> Also, why is this not needed for the logger.debug() call below?

Because it is an exceptional case, so I don't think there's any concern about it being on a critical path for performance.

Updated so that none of them use an explicit check.

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by ahus1 — APPROVED** [review]
