### PR TITLE
Force login in reset-credentials to federated users

### LINKED ISSUE #37207: Change default value for force-login option in reset-credential-email
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Follow-up of #36844. After talking with the team we decided to change the default value for the new `force-login` option in the `reset-credential-email` authenticator. This should be secure by default. Two possible solutions:

* Change the default to true to always login again.
* Add a third option similar to `only-federated` that only force the login for federated users and make it default. This way the behavior is only changed for federated users and internal DB users work in the same way.

### Version

26.1.1

### Regression

- [ ] The issue is a regression

### Expected behavior

N/A

### Actual behavior

N/A

### How to Reproduce?

N/A

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #37207

The PR implements the second option commented in the issue. The first option makes sense to me too. But this option changes the default behavior only for the problematic federated users. So the PR is taking the approach that is secure by default, breaks less the compatibility, but adds more complexity in the configuration. Let me know what you prefer.

### CODE REVIEW

**Comment by rmartinc** [comment]
Converting to draft because we need to change version to 26.1.3 as 26.1.2 was released. I will update the notes when we decided if this is the option to follow.

File: services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java [hunk 1]
```diff
@@ -237,4 +242,16 @@ public void postInit(KeycloakSessionFactory factory) {
...
+    private boolean forceLogin(AuthenticatorConfigModel config, UserModel user) {
+        final String forceLogin = config != null? config.getConfig().get(FORCE_LOGIN) : null;
+        if (Boolean.parseBoolean(forceLogin)) {
+            return Boolean.TRUE;
+        } else if (Boolean.FALSE.toString().equalsIgnoreCase(forceLogin)) {
+            return Boolean.FALSE;
+        } else {
+            // default is only-federated
+            return !StorageId.isLocalStorage(user.getId()) || user.getFederationLink() != null;
+        }
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java:255]: Could we be strict here to only allow the three values "true", "false", "only-federated", and throw an error if something else appears? It would make the logic simpler to grasp IMHO.

File: docs/documentation/server_admin/topics/login-settings/forgot-password.adoc [hunk 2]
```diff
@@ -27,9 +27,9 @@ image:images/forgot-password-page.png[Forgot Password Page]
 
 The text sent in the email is configurable. See link:{developerguide_link}[{developerguide_name}] for more information.
 
-When users click the email link, {project_name} asks them to update their password, and if they have set up an OTP generator, {project_name} asks them to reconfigure the OTP generator. By default, the flow maintains the user who is logged in if the same authentication session (same browser) was used. Depending on the security requirements of your organization, you may not want users to reset their OTP generator through email or you may want to force them to login again after the process.
+When users click the email link, {project_name} asks them to update their password, and if they have set up an OTP generator, {project_name} asks them to reconfigure the OTP generator. For security reasons, the flow forces federated users to login again after the reset credentials and maintains internal DB users logged in if the same authentication session (same browser) is used. Depending on the security requirements of your organization, you may want to change both default behaviors.
```
Comment (ahus1) [inline docs/documentation/server_admin/topics/login-settings/forgot-password.adoc:30]:
```suggestion
When users click the email link, {project_name} asks them to update their password, and if they have set up an OTP generator, {project_name} asks them to reconfigure the OTP generator. For security reasons, the flow forces federated users to login again after the reset credentials and keeps internal database users logged in if the same authentication session (same browser) is used. Depending on the security requirements of your organization, you can change the default behavior.
```

File: services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java [hunk 3]
```diff
@@ -205,10 +207,13 @@ public List<ProviderConfigProperty> getConfigProperties() {
                         If this property is true, the user needs to login again after the reset credentials.
                         If this property is false, the user will be automatically logged in after the succesful
                         reset credentials when the same authentication session is used.
+                        If this property is only-federated (default), only federated users will be forced to login again,
+                        internal DB users will be logged in if using the same authentication session.
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java:211]:
```suggestion
                        users stored in the internal database will be logged in if using the same authentication session.
```

File: docs/documentation/upgrading/topics/changes/changes-26_1_2.adoc [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+
+Previously the reset credentials flow (*forgot password* feature) maintained the user logged in after the reset credentials if the same authentication session (same browser) was used. For federated user providers this behavior can be a security issue. Imagine a provider implementation that detects the user as *enabled*, performs the password change successfully but the validation of the user password fails for some reason. In this scenario the reset credentials flow allowed a user to be logged in after the successful password change that would have not been allowed to login using the normal browser flow. This scenario is not a common case but should be avoided by default.
+
+For this reason now the authenticator `reset-credential-email` (*Send Reset Email*) has a new configuration option called `force-login` (*Force login after reset*) with values `true` (always force the login), `false` (previous behavior that maintains the user logged in if the same authentication session is used), and `only-federated` (default value that forces federated users to authenticate again and maintains previous behavior for internal DB users).
```
Comment (ahus1) [inline docs/documentation/upgrading/topics/changes/changes-26_1_2.adoc:9]:
```suggestion
For this reason now the authenticator `reset-credential-email` (*Send Reset Email*) has a new configuration option called `force-login` (*Force login after reset*) with values `true` (always force the login), `false` (previous behavior that maintains the user logged in if the same authentication session is used), and `only-federated` (default value that forces federated users to authenticate again and maintains previous behavior for users stored in {project_name}'s internal database).
```

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for this PR, IMHO it aligns with that we discussed. 

See below for some minor remarks. The "internal DB users" sounded a bit like database credentials, so I tried something different. Please have a look if this needs additional changes. 

I strongly suggest to make the parsing of the configuration strict to avoid having strange configurations possibly due to typos that lead to unexpected behaviors.

File: services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java (hunk 1 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java]: Yes, I know this is a bit convoluted. I have changed this a bit but using `equalsIgnoreCase`, I think that admins are using any case for `true` in the configurations. Let's see if it's clearer now.

**Comment by rmartinc** [comment]
I have done the changes and updated to version 26.1.3. @ahus1 just check if the method is clearer now. :smile:

**Review by ahus1 — APPROVED** [review]
Thank you for this change, this and the check is now more clear. While it is ready-to-be merged and I approve it, I assume the Admin UI frontend might not be case sensitive when showing the values. Given that, it might be ok to be case sensitive in the backend Java code as well.

File: docs/documentation/server_admin/images/reset-credential-email-config.png
Comment (jonkoops) [inline docs/documentation/server_admin/images/reset-credential-email-config.png:1]: From UX perspective I would expect that this dialog would have 'Yes' and 'No' as options for the force login, not a boolean value. But this is a small nit.

**Review by jonkoops — APPROVED** [review]
LGTM

File: docs/documentation/server_admin/images/reset-credential-email-config.png
Comment (rmartinc) [reply docs/documentation/server_admin/images/reset-credential-email-config.png:1]: Yes, agree, or something like always, never,... But the problem is that we are coming from a boolean so the previous values (true/false) should work. I thought the multi-list type can have values and labels but it's not. Maybe we can improve that in the future.
