### PR TITLE
[OID4VCI] Fix OID4VCI credential requests to restrict Default client scopes

### LINKED ISSUE #44737: CredentialRequest requires that client scope is assigned as 'Optional'
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

Let's assume that I send credential request for the client scope requesting credential related to the client scope `sd-jwt-credential` . As long as client scope is assigned to the client as "Optional" client scope, this works OK. However if the client scope is assigned to the client as "Default" client scope, it doesn't work.

Hint: As of today, there are some places in the `OID4VCIssuerEndpoint` class calling something like : `ClientScopeModel clientScope = clientModel.getClientScopes(false)...` 

This considers only "optional" client scopes, but not "default" client scopes assigned to the client.

### Version

nightly (from 2025-12-08)

### Regression

- [ ] The issue is a regression

### Expected behavior

All client scopes assigned to the client should be considered during credentialRequest

### Actual behavior

Only "optional" client scopes assigned to the client are considered during credentialRequest

### How to Reproduce?

See details.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Awambeng**
This PR implements backend validation to restrict OID4VCI client scope assignments as default:

Changes:
- OID4VCI scopes can only be assigned as Optional scopes (not Default)
- OID4VCI scopes cannot be assigned when the Verifiable Credentials feature is disabled at the realm level
- The pre-created `oid4vc_natural_person` scope is now assigned as Optional by default

Closes #44737

### CODE REVIEW

**Review by Captain-P-Goldfish — APPROVED** [review]
LGTM

**Comment by mposolda** [comment]
@Awambeng Sorry for late response. Added comment on the related issue https://github.com/keycloak/keycloak/issues/44737#issuecomment-3777664371 . Is it OK for you to update this PR according to that?

**Comment by Awambeng** [comment]
> @Awambeng Sorry for late response. Added comment on the related issue [#44737 (comment)](https://github.com/keycloak/keycloak/issues/44737#issuecomment-3777664371) . Is it OK for you to update this PR according to that?

@mposolda It's fine. I'll take a look.

**Comment by Awambeng** [comment]
@mposolda @Captain-P-Goldfish I've reworked the implementation taking into consideration the discussions in #44737. Could you please have a look when you get a chance?

File: services/src/main/java/org/keycloak/protocol/oid4vc/OID4VCLoginProtocolFactory.java [hunk 1]
```diff
@@ -137,7 +137,7 @@ public void createDefaultClientScopes(RealmModel newRealm, boolean addScopesToEx
             naturalPersonScope.addProtocolMapper(builtins.get(FIRST_NAME_MAPPER));
             naturalPersonScope.addProtocolMapper(builtins.get(LAST_NAME_MAPPER));
             addClientScopeDefaults(naturalPersonScope);
-            newRealm.addDefaultClientScope(naturalPersonScope, true);
+            newRealm.addDefaultClientScope(naturalPersonScope, false);
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oid4vc/OID4VCLoginProtocolFactory.java:140]: Probably better to not assign this at all and just keep this example client scope as "none" and make sure that administrator assign this to clients when they need. But this is not a blocker for this PR as there is other PR https://github.com/keycloak/keycloak/pull/44840 related to this.

Also it seems that "Realm optional client scopes" of OID4VCI protocol are not assigned as "optional" to newly created clients (both OIDC clients and OID4VCI clients). But this is separate issue (maybe not issue at all and is intended to work like this...?). Anyway, not blocker for this PR IMO.

**Review by mposolda — APPROVED** [review]
@Awambeng Thanks! I've tested this and works nice IMO.

Added one comment inline, but not a blocker for this PR.

@Captain-P-Goldfish Do you want to re-review as well?

File: services/src/main/java/org/keycloak/protocol/oid4vc/OID4VCLoginProtocolFactory.java (hunk 1 above)
Comment (Awambeng) [reply services/src/main/java/org/keycloak/protocol/oid4vc/OID4VCLoginProtocolFactory.java:140]: > Probably better to not assign this at all and just keep this example client scope as "none" and make sure that administrator assign this to clients when they need. But this is not a blocker for this PR as there is other PR #44840 related to this.
> 
You’re right, at the moment `oid4vc_natural_person` is created and assigned as Optional to behave like a “default” scope and make the OID4VCI setup work out of the box. I’m fine changing this to leave the scope unassigned (type `none`) so that administrators explicitly attach it to clients when needed. I can either do that here or we can align it with the changes in PR #44840.

> Also it seems that "Realm optional client scopes" of OID4VCI protocol are not assigned as "optional" to newly created clients (both OIDC clients and OID4VCI clients). But this is separate issue (maybe not issue at all and is intended to work like this...?). Anyway, not blocker for this PR IMO.
>
I don’t see this as a major issue, as admins should explicitly decide which scopes to assign per client. I’d prefer to stick with the current approach.

**Comment by Captain-P-Goldfish** [comment]
> @Awambeng Thanks! I've tested this and works nice IMO.
> 
> Added one comment inline, but not a blocker for this PR.
> 
> @Captain-P-Goldfish Do you want to re-review as well?

I will check if I find some time soon. Currently it is pretty difficult to find open slots.

**Review by Captain-P-Goldfish — APPROVED** [review]
LGTM

**Comment by Awambeng** [comment]
@mposolda I’ve rebased on the latest main. Could you please review and merge?

**Review by mposolda — APPROVED** [review]
@Awambeng @Captain-P-Goldfish Thanks!
