### PR TITLE
Keep time units upon time entry

### LINKED ISSUE #26549: Mysterious settings changes due to Keycloak cluster changes
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The other day we had an issue with our Keycloak cluster. We're running 3 nodes hosted in Azure App Service. At one point one of the nodes was recycled and a new node was started to replace it. During the shutdown/startup we can see from the logs that there were some issues with the Infinispan cache (`java.lang.IllegalStateException: Read commands must ignore leavers` and timeouts).

But, as it seems the nodes were back in normal operation soon after, as expected. What follows is not as expected though. Suddenly we're seeing an increased number of expired refresh tokens and consequently 401s.

By more or less coincidence we saw that the `Offline Session Idle` setting was configured to 42 minutes and not 42 days as we had configured it. Changing this value back to days (not minutes) immediately resolved the expired refresh token issue.

So to us it seems like this setting was changed somehow due to the recycling of the node and/or the Infinispan issues. 

### Version

22.0.1

### Expected behavior

The `Offline Session Idle` setting (and all other settings) should not be affected by changes to the Keycloak cluster.

### Actual behavior

Seems like the the `Offline Session Idle` setting was changed due changes in the Keycloak cluster.

### How to Reproduce?

N/A.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hmlnarik**
Fixes: #26549

### CODE REVIEW

File: js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx [hunk 1]
```diff
@@ -60,6 +60,10 @@ export const TimeSelector = ({
 }: TimeSelectorProps) => {
   const { t } = useTranslation();
 
+  const [lastMultiplier, setLastMultiplier] = useState<number | undefined>(
+    undefined,
+  );
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx:65]: If no default value is provided to `useState()` it will assume the default is `undefined` and overload the generic passed into it with this, so this code can be reduced to:
```suggestion
  const [lastMultiplier, setLastMultiplier] = useState<number>();
```

File: js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx [hunk 2]
```diff
@@ -88,9 +92,11 @@ export const TimeSelector = ({
     if (value) {
       setMultiplier(multiplier);
       setTimeValue(value / multiplier);
+      setLastMultiplier(multiplier);
     } else {
       setTimeValue(value || "");
-      setMultiplier(defaultMultiplier);
+      setMultiplier(lastMultiplier || defaultMultiplier);
+      setLastMultiplier(lastMultiplier || defaultMultiplier);
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx:99]: Note that `||` will also fall back to `defaultMultiplier` if `lastMultiplier` is `0`. This is probably intentional, as that is an invalid multiplier, but if you'd like to only fall back if `lastMultiplier` is `undefined` you can use the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) (`??`).

```suggestion
      setMultiplier(lastMultiplier ?? defaultMultiplier);
      setLastMultiplier(lastMultiplier ?? defaultMultiplier);
```

Again, not sure if this suggestion applies here, feel free to do what you like.

**Review by jonkoops — DISMISSED** [review]
LGTM, just some general feedback.

**Review by jonkoops — APPROVED** [review]
LGTM
