### PR TITLE
Fix disableDefaultIngress CR field of the operator

### LINKED ISSUE #11577: `disableDefaultIngress` of the Keycloak CR doesn't work
### Describe the bug

The operator crashes trying to deserialize the field `disableDefaultIngress` when set

### Version

18.0.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**
Resolves #11577

### CODE REVIEW

File: operator/src/test/java/org/keycloak/operator/CRSerializationTest.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+import org.junit.jupiter.api.Test;
+import org.keycloak.operator.v2alpha1.crds.Keycloak;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertTrue;
+
+public class CRSerializationTest {
+
+    @Test
+    public void testDeserialization() {
```
Comment (andreaTP) [inline operator/src/test/java/org/keycloak/operator/CRSerializationTest.java:13]: left this unit tests as it actually spots the underlying issue:
  - use a yaml source file
  - deserialize it
this is not explicitly tested by the current E2E

**Review by DGuhr — APPROVED** [review]
LGTM

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

**Review by abstractj — APPROVED** [review]
