### PR TITLE
Deprecate for removal Instagram Identity Broker

### LINKED ISSUE #36562: Social login - Instagram Login test fails, API changed
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Test fails with response: https://www.instagram.com/oauth/authorize/third_party/error/?message=Invalid%20Request%3A%20Request%20parameters%20are%20invalid%3A%20Invalid%20scope%3A%20user_profile

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Successful login throw api

### Actual behavior

Request fails due to recent changes on the Instagram Basic Display API. https://developers.facebook.com/docs/instagram-platform

### How to Reproduce?

1. Set up the Instagram application according to the documentation: https://www.keycloak.org/docs/latest/server_admin/#instagram
2.  Prepare social.properties file containing the required variables (e.g., Client ID, Client Secret, ...)
3. Run the testsuite with following command with your custom social.properties file
```
$ mvn -f testsuite/integration-arquillian/pom.xml clean install \
      -Dtest=SocialLoginTest#instagramLogin \
      -Dsocial.config=path\to\social.properties \
      -Dbrowser=chrome
```

### Anything else?

_No response_

### LINKED ISSUE #37967: Deprecate for removal the Instagram social broker
### Description

We are considering deprecating the Instagram social provider and eventually removing it in a future release. For that, we want to first create a discussion to share the decision with the community and depending on how things goes, move forward with deprecating it and updating the release / upgrade guides.

The reasons for that are:

* Instagram is a social network and a product owned by Meta and looking at their documentation they are pushing people to use Facebook authentication instead. Because of that, we assume that the support for Facebook login is enough for those that want to authenticate to Meta and use Instagram APIs [1]. At the very least, I find this documentation a bit confusing and hard to follow.

* Instagram login [2] went through changes that make it really hard to set up a client application to configure a social broker in Keycloak. We might be missing something but we could not figure out how to have one.

* There is no issue in the community about Instagram not working but a single one [3] from our QE team. We are missing justifications to keep this social broker given its cost for testing and supporting it. The issues we have closed does not justify either having this social broker.

* We have no access and no control over the credentials and applications currently being used to configure the Instagram broker tests. That is a big problem because today we are not even able to obtain verification codes when the IdP is asking for a 2nd factor during the authentication process. This is not a problem specific to Instagram though and we should probably consider reviewing our social broker test configuration to rely on e-mail accounts from the [redhat.com](http://redhat.com/) domain or some other way that allows people from our team continuous access to user accounts across the different (social) brokers we support 

That being said, is there any objection to deprecate and remove the Instagram social provider?

[1] https://developers.facebook.com/docs/instagram-platform/instagram-api-with-facebook-login/
[2] https://developers.facebook.com/blog/post/2024/09/04/update-on-instagram-basic-display-api/
[3] https://github.com/keycloak/keycloak/issues/36562

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #37967
Closes #36562

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java [hunk 1]
```diff
@@ -351,6 +352,7 @@ public void facebookLoginWithEnhancedScope() throws InterruptedException {
     }
 
     @Test
+    @Ignore
```
Comment (miquelsi) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java:355]: Why not just deleting the test?

**Review by abstractj — COMMENTED** [review]
@pedroigor I'd suggest to update the following docs:

1) docs/documentation/server_admin/topics/identity-broker/social/instagram.adoc and add ==== Instagram (Deprecated).
2) docs/guides/server/features.adoc and add instagram as part of == Deprecated features section.

**Review by miquelsi — APPROVED** [review]

**Comment by abstractj** [comment]
@pedroigor there are some conflicts, but after solving them, please ping me and I can approve.

**Comment by pedroigor** [comment]
@abstractj Rebased

**Review by ahus1 — APPROVED** [review]
