### PR TITLE
Sanitize logs in JBossLoggingEventListenerProvider

### LINKED ISSUE #25078: Log Injection during WebAuthn authentication/registration
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

Errors in browser client during setup/auth with "Security Key login" (WebAuthn) are written into the form, send to Keycloak and written to log without escaping. Any content could be send with this request and therefore allows log injection.

### Version

22.0.5

### Expected behavior

Message from user input are escaped to prevent (log) injection attacks.

### Actual behavior

Request data is written to in log without escaping and allows log injection.

### How to Reproduce?

- Start login with a user, who is required to setup a second auth factor
- Configure "Security-Token"
- Get form URL (`<FORM_URL>`) from page source code
- Run command in terminal:

```shell
curl '<FORM_URL>' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Cookie: AUTH_SESSION_ID=9249c14d-1baa-43ba-a110-bbcdff689e9e.19d58cc8a8cf-28439; AUTH_SESSION_ID_LEGACY=9249c14d-1baa-43ba-a110-bbcdff689e9e.19d58cc8a8cf-28439; KC_STATE_CHECKER=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3NzQ1OTFkOC1hNGNlLTQ5MjUtODFlZS01NWQ5ZmM0YjhlZTgifQ.eyJta3kiOiJpbnZhbGlkQ29kZU1lc3NhZ2UiLCJtdHkiOiJFUlJPUiIsIm1wYXIiOltdLCJzdGF0Ijo0MDAsInN0MiI6ImY0NGE4NDU1LTU5MWYtNGNjYi1hZWZiLTIxYmQwMzE5OTRjYiJ9.AruNFsHMyHt1SF31TaRsN875qquIMSKhxp-dwfE4zts; KC_RESTART=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3NzQ1OTFkOC1hNGNlLTQ5MjUtODFlZS01NWQ5ZmM0YjhlZTgifQ.eyJjaWQiOiJhY2NvdW50LWNvbnNvbGUiLCJwdHkiOiJvcGVuaWQtY29ubmVjdCIsInJ1cmkiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvYzEtczEtaTEvYWNjb3VudC8jLyIsImFjdCI6IkFVVEhFTlRJQ0FURSIsIm5vdGVzIjp7InNjb3BlIjoib3BlbmlkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL2MxLXMxLWkxIiwicmVzcG9uc2VfdHlwZSI6ImNvZGUiLCJjb2RlX2NoYWxsZW5nZV9tZXRob2QiOiJTMjU2IiwicmVkaXJlY3RfdXJpIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL2MxLXMxLWkxL2FjY291bnQvIy8iLCJzdGF0ZSI6IjNjNDUzMWJkLTYxNTMtNDRiYS05MDc1LWE1NzcyY2Y4MTA5ZSIsIm5vbmNlIjoiZjQ4MDUzNDktZDIxMi00Mzc3LThmODMtYTBjOGZjZDQxY2UzIiwiY29kZV9jaGFsbGVuZ2UiOiJOa1RxTHFWUl9jWjJFVEd1VGZxOHJTYVpHdzdCd1BXdUdSVFVHa29oSjlzIiwicmVzcG9uc2VfbW9kZSI6ImZyYWdtZW50In19.U2_FfhLkAzJILgHfVYVL1-4dE4B7oEULDtRTl5XpgBw; __snackbar=IjZmMjA3NGFiZTg4MDUxZGQi.3USigr8kqbvE758yaKF5QkElgCUgieTfik%2FewsWYuhw; __session=ImE4ZTFmZTRhMTUzZmNlZjIi.MsiBCXKE1XZZHwcBe2lbTQ2RwnoTNplIR5sByOMB97Q' \
  --data-raw 'clientDataJSON=&attestationObject=&publicKeyCredentialId=&authenticatorLabel=&transports=&error=invalid%5Fuser%5Fcredentials%2C%20credential%5Ftype%3Dwebauthn%2C%20auth%5Fmethod%3Dopenid%2Dconnect%2C%20web%5Fauthn%5Fregistration%5Ferror%5Fdetail%3D%27NotAllowedError%3A%20The%20operation%20either%20timed%20out%20or%20was%20not%20allowed%2E%20See%3A%20https%3A%2F%2Fwww%2Ew3%2Eorg%2FTR%2Fwebauthn%2D2%2F%23sctn%2Dprivacy%2Dconsiderations%2Dclient%2E%27%2C%20custom%5Frequired%5Faction%3Dwebauthn%2Dregister%2C%20response%5Ftype%3Dcode%2C%20web%5Fauthn%5Fregistration%5Ferror%3Dwebauthn%2Derror%2Dregister%2Dverification%2C%20redirect%5Furi%3Dhttp%3A%2F%2Flocalhost%3A8080%2Fauth%2Frealms%2Fc1%2Ds1%2Di1%2Faccount%2F%23%2F%2C%20remember%5Fme%3Dfalse%2C%20code%5Fid%3D9249c14d%2D1baa%2D43ba%2Da110%2Dbbcdff689e9e%2C%20response%5Fmode%3Dfragment%2C%20username%3Da%27%0A2023%2D11%2D03%2009%3A32%3A33%2C614%20WARN%20%20%5Borg%2Ekeycloak%2Eevents%5D%20%28executor%2Dthread%2D14%29%20type%3DCUSTOM%5FREQUIRED%5FACTION%5FERROR%2C%20realmId%3Dinst%2D001%2D001%2D001%2C%20clientId%3Daccount%2Dconsole%2C%20userId%3Dd5410969%2D4a04%2D4f35%2D87d3%2D76b9343119b2%2C%20ipAddress%3D172%2E18%2E0%2E1%2C%20error%3Dthe%20admin%20did%20something%20very%20evil%21%21%21%2C%20remember%5Fme%3Dfalse%2C%20code%5Fid%3D9249c14d%2D1baa%2D43ba%2Da110%2Dbbcdff689e9e%2C%20response%5Fmode%3Dfragment%2C%20username%3Dadmin'
```

The decoded error part contains manipulated log entries:

```
invalid_user_credentials, credential_type=webauthn, auth_method=openid-connect, web_authn_registration_error_detail='NotAllowedError: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.', custom_required_action=webauthn-register, response_type=code, web_authn_registration_error=webauthn-error-register-verification, redirect_uri=http://localhost:8080/auth/realms/c1-s1-i1/account/#/, remember_me=false, code_id=9249c14d-1baa-43ba-a110-bbcdff689e9e, response_mode=fragment, username=a'
2023-11-03 09:32:33,614 WARN  [org.keycloak.events] (executor-thread-14) type=CUSTOM_REQUIRED_ACTION_ERROR, realmId=inst-001-001-001, clientId=account-console, userId=d5410969-4a04-4f35-87d3-76b9343119b2, ipAddress=172.18.0.1, error=the admin did something very evil!!!, remember_me=false, code_id=9249c14d-1baa-43ba-a110-bbcdff689e9e, response_mode=fragment, username=admin
```

- after sending that, the log contains the following entries:

```
keycloak-base-keycloak-1    | 2023-11-03 10:14:01,861 WARN  [org.keycloak.authentication.requiredactions.WebAuthnRegister] (executor-thread-52) WebAuthn API .create() response validation failure. invalid_user_credentials, credential_type=webauthn, auth_method=openid-connect, web_authn_registration_error_detail='NotAllowedError: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.', custom_required_action=webauthn-register, response_type=code, web_authn_registration_error=webauthn-error-register-verification, redirect_uri=http://localhost:8080/auth/realms/c1-s1-i1/account/#/, remember_me=false, code_id=9249c14d-1baa-43ba-a110-bbcdff689e9e, response_mode=fragment, username=a'
keycloak-base-keycloak-1    | 2023-11-03 09:32:33,614 WARN  [org.keycloak.events] (executor-thread-14) type=CUSTOM_REQUIRED_ACTION_ERROR, realmId=inst-001-001-001, clientId=account-console, userId=d5410969-4a04-4f35-87d3-76b9343119b2, ipAddress=172.18.0.1, error=the admin did something very evil!!!, remember_me=false, code_id=9249c14d-1baa-43ba-a110-bbcdff689e9e, response_mode=fragment, username=admin
keycloak-base-keycloak-1    | 2023-11-03 10:14:01,870 WARN  [org.keycloak.events] (executor-thread-52) type=CUSTOM_REQUIRED_ACTION_ERROR, realmId=inst-001-001-001, clientId=account-console, userId=d5410969-4a04-4f35-87d3-76b9343119b2, ipAddress=172.18.0.1, error=invalid_user_credentials, credential_type=webauthn, auth_method=openid-connect, web_authn_registration_error_detail='invalid_user_credentials, credential_type=webauthn, auth_method=openid-connect, web_authn_registration_error_detail='NotAllowedError: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.', custom_required_action=webauthn-register, response_type=code, web_authn_registration_error=webauthn-error-register-verification, redirect_uri=http://localhost:8080/auth/realms/c1-s1-i1/account/#/, remember_me=false, code_id=9249c14d-1baa-43ba-a110-bbcdff689e9e, response_mode=fragment, username=a'
keycloak-base-keycloak-1    | 2023-11-03 09:32:33,614 WARN  [org.keycloak.events] (executor-thread-14) type=CUSTOM_REQUIRED_ACTION_ERROR, realmId=inst-001-001-001, clientId=account-console, userId=d5410969-4a04-4f35-87d3-76b9343119b2, ipAddress=172.18.0.1, error=the admin did something very evil!!!, remember_me=false, code_id=9249c14d-1baa-43ba-a110-bbcdff689e9e, response_mode=fragment, username=admin', custom_required_action=webauthn-register, response_type=code, web_authn_registration_error=webauthn-error-register-verification, redirect_uri=http://localhost:8080/auth/realms/c1-s1-i1/account/#/, remember_me=false, code_id=9249c14d-1baa-43ba-a110-bbcdff689e9e, response_mode=fragment, username=a
```

This is only a poc, more sophisticated log manipulation is certainly possible.

### Anything else?

This has been reported as a vulnerability, but was considered a security hardening issue.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #25078

I have followed the recommendation of [owasp](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html#event-collection) and perform some sanity to the values logged. Any whitespace (CR, LF, TAB,...)  is changed for common space (character 20) and quotes are escaped to mark the value is not finished. So now the log is different an the values are `name="value"` instead of `name=value`. I have added two more config properties in the factory to allow log as before: `sanitize` defaults to true and `quotes` defaults to `"`. I suppose we need a little upgrading notes to comment the change, but first I wanted to share the PR to see your reaction (maybe we don't want to change it this way). :smile:

### CODE REVIEW

File: server-spi/src/main/java/org/keycloak/utils/StringUtil.java [hunk 1]
```diff
@@ -56,4 +56,41 @@ public static String joinValuesWithLogicalCondition(String conditionText, Collec
...
+     * Utility method that substitutes any isWhitespace char to common space ' ' or character 20.
+     * The idea is removing any weird space character in the string like \t, \n, \r.
+     * If quotes character is passed the quotes char is escaped to mark is not the end
+     * of the value (for example escaped \" if quotes char " is found in the string).
+     *
+     * @param str The string to normalize
+     * @param quotes The quotes to escape (for example " or '). It can be null.
+     * @return The string without weird whitespaces and quotes escaped
+     */
+    public static String sanitizeSpacesAndQuotes(String str, Character quotes) {
```
Comment (mhajas) [inline server-spi/src/main/java/org/keycloak/utils/StringUtil.java:69]: Is there some library providing implementation of similar method? If it is OWASP recommendation there could be something like that.

File: services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java [hunk 2]
```diff
@@ -88,6 +97,18 @@ public List<ProviderConfigProperty> getConfigMetadata() {
                 .options(logLevels)
                 .defaultValue("warn")
                 .add()
+                .property()
+                .name("sanitize")
+                .type("boolean")
+                .helpText("If true the log messages are sanitized to avoid line breaks. If false messages are not sanitized.")
+                .defaultValue("true")
```
Comment (mhajas) [inline services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java:104]: Should we mention this in release notes since it is changing default behavior?

**Review by mhajas — COMMENTED** [review]
Thank you @rmartinc. This is a great idea. Could you please check my comments?

File: services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java (hunk 2 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java:104]: Yes, for sure, I wanted to add some notes in the upgrading notes. But I wanted to first share the PR to see if it was in the right direction for everybody.

File: server-spi/src/main/java/org/keycloak/utils/StringUtil.java (hunk 1 above)
Comment (rmartinc) [reply server-spi/src/main/java/org/keycloak/utils/StringUtil.java:69]: I spent some time yesterday and I didn't find anything, so I think there is nothing commonly used. The most closer method was the [normalizeSpace](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#normalizeSpace-java.lang.String-) from commons lang. But I also decided to escape quotes to also cover that part. So I (more or less) reuse the idea to implement the method.

File: services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java (hunk 2 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java:104]: I have added the upgrading point explaining the changes. :smiley:

**Comment by rmartinc** [comment]
@mhajas Added the upgrading doc point, rebased and tuned a bit more. I have not seen any general owasp implementation to sanitize messages (just the description linked before as general practices). As commented, I based my implementation in the [normalizeSpace](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#normalizeSpace-java.lang.String-) of the commons-lang library.

If anybody found some owasp implementation (or any other from a trusted source) please just let me know.

File: docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc [hunk 3]
```diff
@@ -114,4 +114,14 @@ By using separate templates for each flow, a more clear distinction exist as to
 and potentially introduce unexpected changes and behavior that should only affect pages for a specific flow.
 
 If you have customizations to the `login-update-profile.ftl` template to customize how users update their profiles when authenticating through a broker, make sure to move your changes
-to the new template.
\ No newline at end of file
+to the new template.
+
+= Changes in jboss-logging event messages
```
Comment (mposolda) [inline docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc:119]: If we are going to backport this (which I assume that yest), then it should rather use file `changes-23_0_5.adoc` to add this release note?

**Review by mposolda — COMMENTED** [review]
@rmartinc Thanks! I've added only one note inline as I think that we will be backporting this to Keycloak 23.X and hence the better `changes-*.adoc` file should be used.

@andymunro Could you please review the documentation for this PR?

File: docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc [hunk 4]
```diff
@@ -114,4 +114,14 @@ By using separate templates for each flow, a more clear distinction exist as to
...
+
+Because of issue https://github.com/keycloak/keycloak/issues/25078[#25078], the `jboss-logging` message values are now quoted (character `"` by default) and sanitized to prevent any line break. There are two new options in the provider (`spi-events-listener-jboss-logging-sanitize` and `spi-events-listener-jboss-logging-quotes`) that allow to customize the new behavior. For example, to avoid both, sanitization and quoting, the server can be started like this:
+
+```
+./kc.sh start --spi-events-listener-jboss-logging-sanitize=false --spi-events-listener-jboss-logging-quotes=none ...
+```
+
+More information about the options in the https://www.keycloak.org/server/all-provider-config#_jboss_logging[all provider configuration guide].
```
Comment (andymunro) [inline docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc:127]:
```suggestion
For more information about the options, see the https://www.keycloak.org/server/all-provider-config#_jboss_logging[all provider configuration guide].
```

**Review by andymunro — CHANGES_REQUESTED** [review]
A few changes to suggest, @rmartinc

File: docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc [hunk 5]
```diff
@@ -114,4 +114,14 @@ By using separate templates for each flow, a more clear distinction exist as to
 and potentially introduce unexpected changes and behavior that should only affect pages for a specific flow.
 
 If you have customizations to the `login-update-profile.ftl` template to customize how users update their profiles when authenticating through a broker, make sure to move your changes
-to the new template.
\ No newline at end of file
+to the new template.
+
+= Changes in jboss-logging event messages
+
+Because of issue https://github.com/keycloak/keycloak/issues/25078[#25078], the `jboss-logging` message values are now quoted (character `"` by default) and sanitized to prevent any line break. There are two new options in the provider (`spi-events-listener-jboss-logging-sanitize` and `spi-events-listener-jboss-logging-quotes`) that allow to customize the new behavior. For example, to avoid both, sanitization and quoting, the server can be started like this:
```
[the remark this answers is not in the document]
Comment (rmartinc) [reply docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc]: Done!

**Review by mposolda — APPROVED** [review]
@rmartinc @andymunro Thanks!
