### PR TITLE
OID4VCI: allow credential_configuration_id without authorization_details

### LINKED ISSUE #46639: [OID4VCI] Broken issuance due to errnoeous credential_identifier check
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

I just tested the credential issuance with Valera using the current development state from **26.02.2026**.
The issuance process is now aborting with the following error message:

```
Missing credential_identifier in credential request. Per OID4VCI specification, 
credential_identifier must be used when authorization_details are present
```

I have sent this authorization request:

```
https://govntb647:6090/realms/id-mercury/protocol/openid-connect/auth?scope=openid urn:eudi:pid:1&response_type=code&client_id=goldfish&redirect_uri=https%3A%2F%2Fgovntb647%3A9543%2Fauthcode&state=9f1e6e4f-2f78-4bf0-810a-c0ba32b2afc7
```

The scope `urn:eudi:pid:1` is my credential.

The token endpoint then returns the following Access Token:

Image

As shown in the screenshot, there is **no `authorization_details`** present in the Access Token response.

The following code snippet is responsible for the failure:

```java
String credentialIdentifier = credentialRequestVO.getCredentialIdentifier();

// credential_identifier is required
if (credentialIdentifier == null) {
    String errorMessage = "Missing credential_identifier in credential request. " +
            "Per OID4VCI specification, credential_identifier must be used when authorization_details are present.";
    LOGGER.debugf(errorMessage);
    eventBuilder.detail(Details.REASON, errorMessage).error(Errors.INVALID_REQUEST);
    throw new BadRequestException(getErrorResponse(ErrorType.INVALID_CREDENTIAL_REQUEST, errorMessage));
}
```

This snippet only checks whether the credential request contains `credential_identifier`, but it does **not** check whether the Access Token response originally contained `authorization_details` (with `credential_identifiers`) in the first place.

As a result, the logic currently enforces `credential_identifier` unconditionally, even though the error message and requirement are explicitly tied to the presence of `authorization_details`.

### Version

999.0.0-SNAPSHOT

### Regression

- [x] The issue is a regression

### Expected behavior

The credential-request should accept the `credential_configuration_id` parameter instead of the `credential_identifier`

### Actual behavior

The credential-request should does not accept `credential_configuration_id` parameter anymore

### How to Reproduce?

see above

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Oluwatobi-Mustapha**
Fix #46639

- In `OID4VCIssuerEndpoint.requestCredential`, accept `credential_configuration_id` only when the access token has no `authorization_details`.

- Preserve strict `credential_identifier` enforcement and offer-state/token `authorization_details` matching when `authorization_details` are present.

- Keep missing-input behavior as `INVALID_CREDENTIAL_REQUEST` for compatibility.

- Add regression coverage for authz-code flow without `authorization_details` and align unknown-configuration error expectation for that path.

Tests:
- `./mvnw -pl testsuite/integration-arquillian/tests/base -Dtest=OID4VCJWTIssuerEndpointTest -DfailIfNoTests=false test`

- `./mvnw -pl testsuite/integration-arquillian/tests/base -Dtest=OID4VCJwtAuthorizationCodeFlowTest#testCredentialRequestWithConfigurationIdWhenTokenHasNoAuthorizationDetails -DfailIfNoTests=false test`

### CODE REVIEW

**Comment by mposolda** [comment]
@Oluwatobi-Mustapha Thanks for the PR!

The problem with this approach is, that it does not correlate the access-token returned from the token-response with the credential. It will be good to make sure that only access token returned from the token-response, which actually requested the `scope` for OID4VCI credential was used in the credential request. If we allow the change from this PR, it would mean that any arbitrary access-token can be used in the credential request, which is not the desired behaviour and has security challenges.


I think that in the `OID4VCAuthorizationDetailsProcessor.handleMissingAuthorizationDetails` should be updated in a way that it will read the client scopes from the current request rather than from the clientSession note.

```
List<String> credentialConfigIds = clientSessionCtx.getClientScopesStream()
        .filter(clientScope -> OID4VCLoginProtocolFactory.PROTOCOL_ID.equals(clientScope.getProtocol()))
        .map(clientScope -> clientScope.getAttribute(CredentialScopeModel.VC_CONFIGURATION_ID))
        .filter(Objects::nonNull)
        .toList();
```

Also the method `generateAuthorizationDetailsFromCredentialOffer` of that class should be updated accordingly. This will make sure that `authorization_Details` would be added to both access-token and token response and OID4VCISsuerEndpoint will not need any changes and can work the same as before.

Finally, I think that the note `OID4VCIssuerEndpoint.CREDENTIAL_CONFIGURATION_IDS_NOTE` can be removed entirely (as even when the credential-offer is used, the client session where credential-offer was created can be the different one than the client session used in this request).

**Comment by Oluwatobi-Mustapha** [comment]
@mposolda 

Thanks for the review. I’ve reworked the implementation to follow your guidance exactly.

- `OID4VCAuthorizationDetailsProcessor.handleMissingAuthorizationDetails` now derives credential configuration IDs from `clientSessionCtx.getClientScopesStream()` (OID4VC protocol scopes + `CredentialScopeModel.VC_CONFIGURATION_ID`), not client-session notes.

- `generateAuthorizationDetailsFromCredentialOffer` was updated to use the same request-scope-based source.

- `OID4VCIssuerEndpoint.CREDENTIAL_CONFIGURATION_IDS_NOTE` was removed entirely, along with note-based reads/writes.

- `PreAuthorizedCodeGrantType` now builds the scope parameter from credential-offer configuration IDs by resolving mapped client scopes and validating they are assigned to the client before creating `ClientSessionContext`.

- Fallback generation is limited to pre-authorized flow, so non-preauthorized grants do not receive synthetic credential identifiers.

This keeps `authorization_details` in token response/access token strictly tied to scopes requested for that token, and prevents credential requests from being authorized by unrelated bearer tokens.

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java [hunk 1]
```diff
@@ -343,39 +345,27 @@ private List<OID4VCAuthorizationDetail> generateAuthorizationDetailsFromCredenti
...
-                logger.debugf("Successfully parsed credential configuration IDs: %s", configIds);
-                return configIds;
-            } catch (Exception e) {
-                logger.warnf("Failed to parse credential configuration IDs from predictable location: %s", e.getMessage());
-            }
-        }
-
-        logger.debugf("No credential_configuration_ids found in predictable location");
-        return null;
+    private List<String> extractCredentialConfigurationIds(ClientSessionContext clientSessionCtx) {
```
Comment (IngridPuppet) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java]: Minor suggestion. I would recommend renaming "extract" to "derive". The method is now implementing some reasoning.

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java [hunk 2]
```diff
@@ -343,39 +345,27 @@ private List<OID4VCAuthorizationDetail> generateAuthorizationDetailsFromCredenti
...
-        // 2. There's a credential offer note in the client session (indicating this is a credential offer flow)
-        // This prevents generating authorization_details for regular SSO logins that don't request OID4VCI - Not 100% sure the check for CREDENTIAL_CONFIGURATION_IDS_NOTE is needed and sufficient
-        if (clientSessionCtx.getClientSession().getNote(OID4VCIssuerEndpoint.CREDENTIAL_CONFIGURATION_IDS_NOTE) != null) {
-            AuthenticatedClientSessionModel clientSession = clientSessionCtx.getClientSession();
-            return generateAuthorizationDetailsFromCredentialOffer(clientSession);
-        } else {
+        // Fallback generation is only intended for pre-authorized code flow.
+        // Other grant types should not get synthetic credential identifiers.
+        String vcIssuanceFlow = clientSessionCtx.getClientSession().getNote(PreAuthorizedCodeGrantType.VC_ISSUANCE_FLOW);
+        if (!PreAuthorizedCodeGrantTypeFactory.GRANT_TYPE.equals(vcIssuanceFlow)) {
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java]: I am missing why this should be limited only to pre-authorized code grant? The issue description #46639 is about authorization-code grant. If this is limited only to pre-authorized code grant, then the issue in question will not be fixed per my understanding?

My understanding is that:

- When authorization-code grant request with `scope=urn:eudi:pid:1` is sent, then the `handleMissingAuthorizationDetails` should be called for authorization-code grant as well and in case that some OID4VCI scope was used (which is scope `urn:eudi:pid:1` in this scenario), then the `authorization_details` should be generated in the access-token as well as in the token response. This should make sure that in the credential-request, Valera wallet should be able to use `credential identifier` from the `authorization_details`, which were returned in the token response. It can be nice if you write the automated test for this scenario (slightly modified version of the test you added in the first commit of this PR, but test should be able to test that `authorization_details` were returned in the token-response and credential-request works with the use of credential-identifier from that token response).

**Review by mposolda — COMMENTED** [review]
@Oluwatobi-Mustapha Thanks for the updates. I've added the comment inline.

File: services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java [hunk 3]
```diff
@@ -149,12 +150,11 @@ public Response process(Context context) {
                 null, UserSessionModel.SessionPersistenceState.TRANSIENT);
 
         AuthenticatedClientSessionModel clientSession = session.sessions().createClientSession(realm, clientModel, userSession);
-        String credentialConfigurationIds = JsonSerialization.valueAsString(credOffer.getCredentialConfigurationIds());
-        clientSession.setNote(OID4VCIssuerEndpoint.CREDENTIAL_CONFIGURATION_IDS_NOTE, credentialConfigurationIds);
         clientSession.setNote(OIDCLoginProtocol.ISSUER, credOffer.getCredentialIssuer());
         clientSession.setNote(VC_ISSUANCE_FLOW, PreAuthorizedCodeGrantTypeFactory.GRANT_TYPE);
 
-        ClientSessionContext sessionContext = fromClientSessionAndScopeParameter(clientSession, OAuth2Constants.SCOPE_OPENID, session);
+        String scopeParam = getScopeParamForCredentialOffer(clientModel, credOffer.getCredentialConfigurationIds());
```
Comment (IngridPuppet) [inline services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java]: This appears to run a heavy logic for the only purpose of recovering the very same credentialConfigurationIds eventually in `handleMissingAuthorizationDetails`. I would argue it makes sense to keep the session note in this flow and update the `handleMissingAuthorizationDetails` to work with both sources: the session note and then the client scopes. WDYT? @Oluwatobi-Mustapha @mposolda

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java (hunk 2 above)
Comment (IngridPuppet) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java]: Same point with Marek. As described in the issue description, the Authorization Code flow is actually the buggy one for two reasons:

- It can be started without receiving an offer, so no fixed credentialConfigurationIds;
- It can be run with a scope, instead of authorization details, which would have embedded credentialConfigurationIds.

We must ensure that we can successfully run the Authorization Code flow under those combined conditions.

**Review by IngridPuppet — COMMENTED** [review]
Hello @Oluwatobi-Mustapha - Thank you for the PR. I reviewed the changes and left some comments. Please could you check?

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java (hunk 2 above)
Comment (Oluwatobi-Mustapha) [reply services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java]: Thank you, sir. 

I have removed the pre-authorized-only restriction in `handleMissingAuthorizationDetails`.

The fallback now runs for authorization-code flow as well, derives `credential_configuration_id` from current request client scopes, and generates `authorization_details` that are returned in both access token and token response via the existing token flow path.

I also updated the integration test (`testCredentialIssuanceWithAuthZCodeWithScopeMatched`) to assert:
1) `authorization_details` is present in token response, and
2) credential request succeeds using the `credential_identifier` returned from that token response.

@mposolda

Comment (Oluwatobi-Mustapha) [reply services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java]: I also agreed with this, and addressed it in my latest commit.

`handleMissingAuthorizationDetails` now applies to authorization-code flow, so auth-code + OID4VC scope without explicit `authorization_details` is handled correctly.

I validated this with integration tests covering:

- auth-code + matching scope (success path with returned credential_identifier),
- auth-code + unmatched scope (rejected),
- auth-code + no scope (rejected),
- pre-authorized control path (still passing).

@IngridPuppet

File: services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java (hunk 3 above)
Comment (Oluwatobi-Mustapha) [reply services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java]: I considered the dual-source fallback, but I intentionally did not keep the session-note path.

Reason: as Marek noted yesterday, the client session that created the credential-offer can differ from the client session used in the token request, so `CREDENTIAL_CONFIGURATION_IDS_NOTE` is not a reliable binding source. 

Keeping note-first fallback can de-correlate `authorization_details` from the actual scope of the issued access token.

In this update I made current request scopes the single source of truth:

- pre-authorized flow maps offer `credential_configuration_ids` -> effective scope parameter in `getScopeParamForCredentialOffer(...)` (with scope existence + client-assignment checks),

- `handleMissingAuthorizationDetails(...)` derives only from `clientSessionCtx.getClientScopesStream()`.

This keeps auth-code and pre-authorized behavior aligned and keeps `authorization_details` in token response/access token strictly tied to the request context of that token.

174F88E6-1E20-470B-94D0-4F81EA46312E_1_201_a

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java [hunk 4]
```diff
@@ -524,44 +524,31 @@ public void testCredentialIssuance() throws Exception {
     @Test
     public void testCredentialIssuanceWithAuthZCodeWithScopeMatched() throws Exception {
         String scopeName = jwtTypeCredentialClientScope.getName();
-        String credConfigId = jwtTypeCredentialClientScope.getAttributes().get(CredentialScopeModel.CONFIGURATION_ID);
+        String credentialConfigurationId = jwtTypeCredentialClientScope.getAttributes().get(CredentialScopeModel.CONFIGURATION_ID);
```
Comment (IngridPuppet) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java]: The added test covers the buggy scenario this PR aims to fix. However, I don't think you should overwrite this previous test. It covered a distinct scenario, which I believe is valid and should remain supported:

- Request authz code with scope
- But send auth details in Token Request

The spec does not seem to oppose this. https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-request-credential-issuance

File: services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java (hunk 3 above)
Comment (IngridPuppet) [reply services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java]: It's fine for me. Thank you for the clarification.

**Review by IngridPuppet — APPROVED** [review]
Thank you for the update. LGTM.

File: services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java (hunk 3 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java]: @IngridPuppet Yes, I see your point here. Was thinking about the same for the pre-authorized code grant and whether this new method `getScopeParamForCredentialOffer` is really needed.

At the same time, it helps with the fact that pre-authorized code grant is now processed with the correct `scope`, which correlates with the credentials used in the credential-offer. Which is likely an advantage (even if in the `scope` of the token-response from pre-authorized code grant, we return just the single scope related to the credential-config-id). So I consider this approach OK.

**Review by mposolda — DISMISSED** [review]
@Oluwatobi-Mustapha @IngridPuppet Thanks for the updates and PR review!

**Comment by Oluwatobi-Mustapha** [comment]
@keycloak-bot 

I have reviewed and resolved the issues.

**Review by mposolda — APPROVED** [review]
@Oluwatobi-Mustapha Thanks!
