### PR TITLE
Block shutdown if the Infinispan cluster is not stable

### LINKED ISSUE #44620: Possible data loss when scaling Keycloak StatefulSet down (on Kubernetes)
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

When testing Keycloak scaling down capabilities (within https://github.com/defenseunicorns/uds-core/issues/2003), I discovered that the node properly leaves the cluster but it doesn't take ongoing rebalance into account. As a result, Keycloak scales down very rapidly (going from 5 to 1 instance in a matter of second) which can lead to the data loss when caches contain logs of data. 

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

When scaling down, during the shutdown hook, Infinispan should block until an ongoing rebalance completes and data segments are reshuffled. 

### Actual behavior

Infinispan seems to properly leave the cluster but doesn't take the ongoing rebalance into consideration.

### How to Reproduce?

1. Get a healthy cluster of 5 nodes up and running.
2. Scale the StatefulSet from 5 to 1
3. Observe the rapid scale down

### Anything else?

I successfully verified that:

* The StatefulSet controller behaves correctly and the deletion order is correct:

```
$ kubectl get events -n keycloak --sort-by=.lastTimestamp | grep keycloak
15m         Normal    SuccessfulDelete               statefulset/keycloak          delete Pod keycloak-4 in StatefulSet keycloak successful
15m         Normal    SuccessfulDelete               statefulset/keycloak          delete Pod keycloak-3 in StatefulSet keycloak successful
15m         Normal    Killing                        pod/keycloak-3                Stopping container keycloak
15m         Normal    SuccessfulDelete               statefulset/keycloak          delete Pod keycloak-2 in StatefulSet keycloak successful
15m         Normal    Killing                        pod/keycloak-2                Stopping container keycloak
15m         Normal    Killing                        pod/keycloak-1                Stopping container keycloak
15m         Normal    SuccessfulDelete               statefulset/keycloak          delete Pod keycloak-1 in StatefulSet keycloak successful
```

* JGroups properly installs new view and then FD Protocols note the member being down. This order of events suggests a proper implementation of the graceful leave, so I guess shutdown hooks work correctly. 

* I checked the code `DefaultInfinispanConnectionProviderFactory#close` code and indeed it seems to call `CacheManager#stop` properly. 

* I don't have the code at hand right now but I think it used to work correctly with the Golang Operator.

### PR DESCRIPTION
**Pull request by pruivo**
Prevent NullPointerException in DefaultInfinispanConnectionProviderFactory

Closes #44620

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java [hunk 1]
```diff
@@ -139,7 +140,8 @@ public static void runWithWriteLockOnCacheManager(Runnable task) {
     @Override
     public void close() {
         logger.debug("Closing provider");
-        shutdownManager.onShutdown();
+        Optional.ofNullable(shutdownManager).ifPresent(ShutdownManager::onShutdown);
+        shutdownManager = null;
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java]: Nitpick, but I think being consistent with the rest of the logic in this method would help readability:

```java
        if (shutdownManager != null) {
            shutdownManager.onShutdown();
            shutdownManager = null;
        }
```

**Review by ahus1 — APPROVED** [review]
