### PR TITLE
fix: aligns our dev http-host default behavior with that of quarkus

### LINKED ISSUE #42876: dev mode should bind only to localhost if possible
### Description

We should follow the default quarkus behavior such that dev mode binds to localhost only when possible.

### Discussion

_No response_

### Motivation

 To prevent inadvertant exposure of dev instances.

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #42876

Matches the quarkus behavior for dev mode binding to localhost. To further prevent this from being seen as breaking, it also checks if kc_run_in_container is true - however I wasn't sure if this needs mentioning in the doc notes.

### CODE REVIEW

**Review by mabartos — COMMENTED** [review]
@shawkins In general, LGTM.

But I'm still able to access the dev instance from the other instance.

I started Keycloak in dev mode with your changes. 

Image

And when I access the 192.168.0.181:8080 on my phone, I can see the Keycloak login page. 

Are these Quarkus changes in the release that we currently use, or will it be available after the 3.31.0?

**Review by mabartos — CHANGES_REQUESTED** [review]
The check on the Quarkus side is probably needed.

**Comment by shawkins** [comment]
> The check on the Quarkus side is probably needed.

Yes, I had launched the Keycloak class and saw that it appropriately picked up the localhost default - but we're not when using start-dev from the cli. The likely problem is that for the latter quarkus doesn't think that is actually a test / dev launch.

**Comment by shawkins** [comment]
@mabartos should be better now. Unfortunately it makes this leakier into our code than I would have liked, but it's a much bigger change to have start-dev actually be in the quarkus dev or test launch mode.

**Comment by vmuzikar** [comment]
@Pepo48 Could you please review for the Windows bits?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java [hunk 1]
```diff
@@ -66,6 +89,13 @@ public List<PropertyMapper<?>> getPropertyMappers() {
                         .build(),
                 fromOption(HttpOptions.HTTP_HOST)
                         .to("quarkus.http.host")
+                        .mapFrom(new OptionBuilder<>("run-in-container", Boolean.class).build(), (v, c) -> {
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java]: Can't we simply check for the `KC_RUN_IN_CONTAINER` env var in the transformer?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java [hunk 2]
```diff
@@ -56,6 +58,27 @@ private static void setCustomExceptionTransformer() {
         });
     }
 
+    // taken from VertxConfigBuilder
+    private static boolean isWSL() {
+        var sysEnv = System.getenv();
+        return sysEnv.containsKey("IS_WSL") || sysEnv.containsKey("WSL_DISTRO_NAME");
+    }
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:64]: Why this doesn't work in WSL?

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thanks for the PR. It'd be good to have more tests for  this, though.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java]: Right, that would be simplier :)

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:64]: That's a limitation documented from quarkus - it's probably like starting in a container with localhost only.

**Review by vmuzikar — DISMISSED** [review]
LGTM, thank you.

@Pepo48 Do you want to check this too?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java (hunk 2 above)
Comment (Pepo48) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:64]: Afaik, binding to 0.0.0.0 is necessary for WSL networking.

Comment (Pepo48) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:64]: Yes, indeed. See: https://learn.microsoft.com/en-us/windows/wsl/networking#connecting-via-remote-ip-addresses

**Review by Pepo48 — APPROVED** [review]
Sorry for the late review. I tested this on Windows (native), worked as expected. Thanks Steve, LGTM.

**Comment by shawkins** [comment]
> Sorry for the late review. I tested this on Windows (native), worked as expected. Thanks Steve, LGTM.

Thank you for checking.

**Review by mabartos — APPROVED** [review]
LGTM, thanks!

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java (hunk 2 above)
Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:64]: @shawkins Maybe it'd be good to add that link to a comment here for future references.

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:64]: I assumed it was sufficient to reference VertxConfigBuilder

**Review by vmuzikar — APPROVED** [review]
