### PR TITLE
Fix errors when code, clientId, or tabId are null

### LINKED ISSUE #33232: 400 error logged as 500
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

When a request with missing `code`, `clientId`, or `tabId` is sent to `GET .../{provider_alias}/login`, Keycloak logs two error messages. Moreover, the second logged message suggests that a 500 internal server error has occurred, which isn't the case.
```
Sep 19, 2024 1:40:53 PM org.keycloak.services.resources.IdentityBrokerService fireErrorEvent
ERROR: invalidRequestMessage
Sep 19, 2024 1:40:53 PM org.keycloak.services.resources.IdentityBrokerService fireErrorEvent
ERROR: unexpectedErrorHandlingRequestMessage: org.keycloak.services.ErrorPageException: HTTP 500 Internal Server Error
```

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Only a 400 error should be logged.

### Actual behavior

Two errors are logged, with one misleadingly indicating a 500 internal server error.

### How to Reproduce?

Send a request to `GET .../{provider_alias}/login` without `code`.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kszafran**
Closes https://github.com/keycloak/keycloak/issues/33232

Calling `parseSessionCode` inside the try-catch would result in `ErrorPageException` thrown by `redirectToErrorPage` being caught and re-reported, resulting in one log entry with `invalidRequestMessage` and another one with `unexpectedErrorHandlingRequestMessage`:
```
Sep 19, 2024 1:40:53 PM org.keycloak.services.resources.IdentityBrokerService fireErrorEvent
ERROR: invalidRequestMessage
Sep 19, 2024 1:40:53 PM org.keycloak.services.resources.IdentityBrokerService fireErrorEvent
ERROR: unexpectedErrorHandlingRequestMessage: org.keycloak.services.ErrorPageException: HTTP 500 Internal Server Error
```

Additionally, two of `ErrorPageException` constructors didn't pass the status to `super()`, resulting in the logger error message being "HTTP 500 Internal Server Error" even though the status was actually something else, like 400. I noticed that `ErrorPageException` can be simplified by just passing the response to `super()`, which is one way of fixing the problem.

### CODE REVIEW

**Comment by ahus1** [comment]
To track bugs and enhancements in our workflows, we require that you create a GitHub issue for each bug an enhancement. 

Please create a bug issue for this PR, then update the description and the commit message to reference it as outlined in the CONTRIBUTING.md in this repository. Thanks!

**Comment by kszafran** [comment]
@ahus1 I created and linked an issue.

**Comment by martin-kanis** [comment]
@ahus1 Can you please enable workflows for the PR? Thanks

**Comment by jonkoops** [comment]
Running them now.

**Comment by martin-kanis** [comment]
@kszafran Thanks for the PR. Changes looks good to me, however we have failed tests.
```
testAuthenticationExpiredWithMoreBrowserTabs_clickIdpLoginInTab1AfterExpiration
testAuthenticationExpiredWithMoreBrowserTabs_loginExpiredInBothConsumerAndProvider
```  
Weird thing is that those tests fail for me locally even with `main` branch, but I didn't find those failures in GHA in different runs, other than this PR.

**Comment by kszafran** [comment]
@martin-kanis Will you check why those tests are failing? It'll take me some time to figure out how to run these tests locally.

File: services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java [hunk 1]
```diff
@@ -376,9 +376,9 @@ public Response performLogin(@PathParam("provider_alias") String providerAlias,
             logger.debugf("Sending authentication request to identity provider [%s].", providerAlias);
         }
 
-        try {
-            AuthenticationSessionModel authSession = parseSessionCode(code, clientId, tabId, clientData);
+        AuthenticationSessionModel authSession = parseSessionCode(code, clientId, tabId, clientData);
```
Comment (martin-kanis) [inline services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java:379]: Issues in the tests are caused by this change. One option how to fix it, is to put the line back into the `try` block and the following `catch`:
```java
} catch (WebApplicationException e) {
    return e.getResponse();
}
```

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Hi @kszafran,
sorry for the late reply. I found the cause of the failing tests, see bellow. Will you have a chance to update the PR?

File: services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java (hunk 1 above)
Comment (kszafran) [reply services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java:379]: Interesting. How come in all the other endpoints that use `parseSessionCode(...)` the call isn't inside a try-catch? Maybe we have the same problem in the other endpoints, but it's not detected by tests?

Comment (martin-kanis) [reply services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java:379]: When this exception is thrown in an endpoint where it is not caught, it returns "400 Bad request" with some HTML. Maybe it's not ideal but don't see it as a big problem. Feel free to update just the original scope of this PR/issue you filled so the tests are green.

Comment (kszafran) [reply services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java]: Done and rebased on top of latest main.

**Review by martin-kanis — APPROVED** [review]
@kszafran thanks! LGTM

**Review by pedroigor — APPROVED** [review]
