### PR TITLE
Localization > Effective message bundles tab improvements

### LINKED ISSUE #26132: Localization: Effective message bundles subtab
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

As described in https://github.com/keycloak/keycloak/issues/26060

### Effective message bundles subtab
- We need a heading for this tab as well.  It needs to describe what an effective message bundle is.  I suggest text such as, "An effective message bundle is the set of translations for a given language, theme, and theme type.  It also takes into account any realm overrides, which will take precedence."  Suggest we remove the help icon.
- In the search, Theme, Theme Type, and Language should be required fields.  Maybe the simplest way to deal with this is for each of these values to have a reasonable default.  Language would have the default language as the default selection.  The others could just default to the first value in the dropdown.
- In the search, `Theme` and `Theme Type` are backwards.  The dropdown for `Theme` is showing the values for `Theme Type`, and vice versa.
- We are not supporting the `common` theme with respect to message bundles.  So `common` should not show up in the dropdown.
- `Has words` only searches the values.  It would be nice if it were also searching the keys.  That way if I know the key I am looking for I can find it quickly.
- In the search dialog, the tab key closes the dialog.  Instead, I should be able to tab through the fields.
- We need a refresh button.  If I go to the `Realm overrides` tab and create a new override for a translation, I will not see it in the `Effective message bundles` tab.  I should be able to do a refresh so I can view my change in the effective message bundle.
- By default, translations should be sorted by key in alphabetical order.

### Version

22.0.5

### Expected behavior

As described in https://github.com/keycloak/keycloak/issues/26060

### Actual behavior

As described in https://github.com/keycloak/keycloak/issues/26060

### How to Reproduce?

As described in https://github.com/keycloak/keycloak/issues/26060

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/26132

### CODE REVIEW

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx [hunk 1]
```diff
@@ -63,9 +66,12 @@ export const EffectiveMessageBundles = ({
...
-    ? Object.keys(themes).sort((a, b) => a.localeCompare(b))
+    ? Object.keys(themes)
+        .filter((key) => key !== "common")
+        .sort((a, b) => a.localeCompare(b))
     : [];
-  const themeTypes = Object.values(themes!)
+
+  const themesList = Object.values(themes!)
     .flatMap((theme) => theme.map((item) => item.name))
     .filter((value, index, self) => self.indexOf(value) === index)
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:76]: Why are we filtering out duplicates? Are there cases where there are multiple themes of the same name?

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx [hunk 2]
```diff
@@ -101,11 +107,20 @@ export const EffectiveMessageBundles = ({
...
+        filter.hasWords.length > 0
+          ? messages.filter((m) =>
+              filter.hasWords.some(
+                (f) => m.value.includes(f) || m.key.includes(f),
+              ),
+            )
+          : messages;
+
+      const sortedMessages = [...filteredMessages].sort((a, b) =>
+        a.key.localeCompare(b.key, undefined, { sensitivity: "base" }),
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:120]: This should `useLocaleSort()` as well.

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx [hunk 3]
```diff
@@ -101,11 +107,20 @@ export const EffectiveMessageBundles = ({
         },
       );
 
-      return filter.hasWords.length > 0
-        ? messages.filter((m) =>
-            filter.hasWords.some((f) => m.value.includes(f)),
-          )
-        : messages;
+      const filteredMessages =
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:110]: It's not possible to do this kind of filtering on the API? @edewit

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties [hunk 4]
```diff
@@ -2985,4 +2985,5 @@ readBlog=Read blog
 customValue=Custom value
 termsAndConditionsUserAttribute=Terms and conditions accepted timestamp
 realmOverridesDescription= Realm overrides allow you to specify translations that will take effect for the entire realm. These translations will override any translation specified by a theme.
-addTranslation=Add translation
\ No newline at end of file
+addTranslation=Add translation
+=An effective message bundle is the set of translations for a given language, theme, and theme type. It also takes into account any realm overrides, which will take precedence.
```
[the remark this answers is not in the document]
Comment (agagancarczyk) [reply js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties:2989]: yes, sorry, don't know what happened there

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx (hunk 1 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:76]: Thanks @jonkoops I'm filtering out duplicates because I'm using `  const themes = serverInfo.themes;` which returns this obj:

Screenshot 2024-01-18 at 13 19 53

I can just create a hardcoded obj with {base, keycloak, keycloak.v2, keycloak.v3} and not use themes. WDYT?

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx (hunk 3 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:110]: thanks @jonkoops this implementation was suggested by @edewit

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx (hunk 1 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:76]: Ahhh, yes this makes sense! Just wanted to understand better, thanks!

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx (hunk 3 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:110]: Then I will assume it's not possible, thanks :+1:

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx [hunk 5]
```diff
@@ -62,15 +67,21 @@ export const EffectiveMessageBundles = ({
...
   >({});
   const themes = serverInfo.themes;
-  const themeKeys = themes
-    ? Object.keys(themes).sort((a, b) => a.localeCompare(b))
+  const themeTypes = themes
+    ? localeSort(
+        Object.keys(themes).filter((key) => key !== "common"),
+        (key) => key,
+      )
+    : [];
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:75]: Forgot to add this in my original review, but it seems to me that this might be a potentially expensive operation to do on each render. This component likely will re-render a couple of times due to the different types of state in it getting manipulated, so it might be worth it to memoize these values.

```suggestion
  const themeTypes = useMemo(() => {
    if (!themes) {
      return [];
    }
  
    return localeSort(
      Object.keys(themes).filter((key) => key !== "common"),
      (key) => key,
    );
  }, [themes]);
```

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx [hunk 6]
```diff
@@ -62,15 +67,21 @@ export const EffectiveMessageBundles = ({
...
+  const themeNames = themes
+    ? localeSort(
+        Object.values(themes)
+          .flatMap((theme) => theme.map((item) => item.name))
+          .filter((value, index, self) => self.indexOf(value) === index),
+        (name) => name,
+      )
     : [];
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:83]: Likewise here.
```suggestion
  const themeNames = useMemo(() => {
    if (!themes) {
      return [];
    }
  
    return localeSort(
      Object.values(themes)
        .flatMap((theme) => theme.map((item) => item.name))
        .filter((value, index, self) => self.indexOf(value) === index),
      (name) => name,
    );
  }, [themes]);
```

**Review by jonkoops — DISMISSED** [review]
LGTM

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx (hunk 5 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx]: Thanks @jonkoops you're 100% right!

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx (hunk 6 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx]: Thanks @jonkoops you're 100% right here!

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx [hunk 7]
```diff
@@ -61,15 +66,32 @@ export const EffectiveMessageBundles = ({
...
   const [key, setKey] = useState(0);
+  const themes = serverInfo.themes;
+
+  const themeTypes = useMemo(() => {
+    if (!themes) {
+      return [];
+    }
+
+    return localeSort(
+      Object.keys(themes).filter((key) => key !== "common"),
```
Comment (ssilvert) [inline js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx:78]: Actually, I think I was wrong about this.  Let's remove this filter.  It won't hurt anything.

**Review by ssilvert — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx (hunk 7 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx]: Thanks @ssilvert this is done now.

**Review by jonkoops — APPROVED** [review]
LGTM!

**Review by ssilvert — APPROVED** [review]
