### PR TITLE
[#10894] SAML Adapters tests start failing in recent versions of EAP/wildfly

### LINKED ISSUE #10894: SAML Adapters tests start failing in recent versions of EAP/wildfly
### Describe the bug

[ELYWEB-163](https://issues.redhat.com/browse/ELYWEB-163) fixed a bug in elytron-web that re-encodes (twice) the query parameters. It seems that OIDC/SAML did a workaround to fix this just re-decoding the values also two times ([here](https://github.com/keycloak/keycloak/blob/15.0.2/adapters/oidc/wildfly-elytron/src/main/java/org/keycloak/adapters/elytron/ElytronHttpFacade.java#L200-L218), first `getQuery` do one decoding and after that the code perform the second one). My feeling that this was not even a workaround, it just worked and no one thought about being doing a first decoding calling `getQuery` (`getRawQuery` in URI returns the query string without deconding, but calling `getQuery` it is decoded).

After the fix the double decoding makes the signature parameter in SAML REDIRECT binding fail (it is wrong after the second decoding).

More info: https://issues.redhat.com/browse/RHSSO-1943

### Version

17.0.0 15.0.2

### Expected behavior

It's weird but probably we need to make it work in both situations (with and without the fix). Because if not the adapters will fail when installed in a version without ELYWEB-163 applied.

### Actual behavior

```
[org.keycloak.adapters.saml.profile.webbrowsersso.WebBrowserSsoAuthenticationHandler] (default task-1) null: java.security.SignatureException: Signature length not correct: got 126 but was expecting 128
 at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:211)
 at java.security.Signature$Delegate.engineVerify(Signature.java:1394)
 at java.security.Signature.verify(Signature.java:771)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.validateRedirectBindingSignatureForKey(AbstractSamlAuthenticationHandler.java:744)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.validateRedirectBindingSignature(AbstractSamlAuthenticationHandler.java:695)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.verifyRedirectBindingSignature(AbstractSamlAuthenticationHandler.java:678)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.validateSamlSignature(AbstractSamlAuthenticationHandler.java:317)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.handleSamlResponse(AbstractSamlAuthenticationHandler.java:248)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.doHandle(AbstractSamlAuthenticationHandler.java:148)
 at org.keycloak.adapters.saml.profile.webbrowsersso.WebBrowserSsoAuthenticationHandler.handle(WebBrowserSsoAuthenticationHandler.java:51)
 at org.keycloak.adapters.saml.SamlAuthenticator.authenticate(SamlAuthenticator.java:48)
 at org.keycloak.adapters.saml.elytron.KeycloakHttpServerAuthenticationMechanism.evaluateRequest(KeycloakHttpServerAuthenticationMechanism.java:102)
 at org.wildfly.security.http.util.SetMechanismInformationMechanismFactory$1.evaluateRequest(SetMechanismInformationMechanismFactory.java:119)
 at org.wildfly.security.http.util.SocketAddressCallbackServerMechanismFactory$1.evaluateRequest(SocketAddressCallbackServerMechanismFactory.java:82)
 at org.wildfly.security.auth.server.SecurityIdentityServerMechanismFactory$1.evaluateRequest(SecurityIdentityServerMechanismFactory.java:85)
 at org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.authenticate(HttpAuthenticator.java:326)
 at org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.access$800(HttpAuthenticator.java:301)
 at org.wildfly.security.http.HttpAuthenticator.authenticate(HttpAuthenticator.java:94)
 at org.wildfly.elytron.web.undertow.server.SecurityContextImpl.authenticate(SecurityContextImpl.java:107)
 at org.wildfly.elytron.web.undertow.server.servlet.ServletSecurityContextImpl.authenticate(ServletSecurityContextImpl.java:115)
 at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
 at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
 at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
 at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
 at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
 at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
 at org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
 at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
 at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
 at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
 at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
 at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
 at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
 at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
 at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
 at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
 at java.lang.Thread.run(Thread.java:748) &amp#27;[0m&amp#27;[32m04:38:17,662 DEBUG [org.keycloak.adapters.saml.profile.webbrowsersso.WebBrowserSsoAuthenticationHandler] (default task-1) Verification failed: %s: java.security.SignatureException: Signature length not correct: got 126 but was expecting 128
 at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:211)
 at java.security.Signature$Delegate.engineVerify(Signature.java:1394)
 at java.security.Signature.verify(Signature.java:771)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.validateRedirectBindingSignatureForKey(AbstractSamlAuthenticationHandler.java:744)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.validateRedirectBindingSignature(AbstractSamlAuthenticationHandler.java:711)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.verifyRedirectBindingSignature(AbstractSamlAuthenticationHandler.java:678)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.validateSamlSignature(AbstractSamlAuthenticationHandler.java:317)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.handleSamlResponse(AbstractSamlAuthenticationHandler.java:248)
 at org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.doHandle(AbstractSamlAuthenticationHandler.java:148)
 at org.keycloak.adapters.saml.profile.webbrowsersso.WebBrowserSsoAuthenticationHandler.handle(WebBrowserSsoAuthenticationHandler.java:51)
 at org.keycloak.adapters.saml.SamlAuthenticator.authenticate(SamlAuthenticator.java:48)
 at org.keycloak.adapters.saml.elytron.KeycloakHttpServerAuthenticationMechanism.evaluateRequest(KeycloakHttpServerAuthenticationMechanism.java:102)
 at org.wildfly.security.http.util.SetMechanismInformationMechanismFactory$1.evaluateRequest(SetMechanismInformationMechanismFactory.java:119)
 at org.wildfly.security.http.util.SocketAddressCallbackServerMechanismFactory$1.evaluateRequest(SocketAddressCallbackServerMechanismFactory.java:82)
 at org.wildfly.security.auth.server.SecurityIdentityServerMechanismFactory$1.evaluateRequest(SecurityIdentityServerMechanismFactory.java:85)
 at org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.authenticate(HttpAuthenticator.java:326)
 at org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.access$800(HttpAuthenticator.java:301)
 at org.wildfly.security.http.HttpAuthenticator.authenticate(HttpAuthenticator.java:94)
 at org.wildfly.elytron.web.undertow.server.SecurityContextImpl.authenticate(SecurityContextImpl.java:107)
 at org.wildfly.elytron.web.undertow.server.servlet.ServletSecurityContextImpl.authenticate(ServletSecurityContextImpl.java:115)
 at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
 at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
 at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
 at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
 at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
 at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
 at org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
 at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
 at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
 at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
 at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
 at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
 at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
 at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
 at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
 at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
 at java.lang.Thread.run(Thread.java:748)
```

### How to Reproduce?

* Change `eap.version` in `pom.xml` to `7.4.3.GA-redhat-00002`.
* And execute:
```bash
mvn clean install -DskipTests
cd distribution
mvn clean install
cd ..
mvn -f testsuite/integration-arquillian/servers/pom.xml clean install -Papp-server-eap (*)
cd testsuite/integration-arquillian/tests/base/
mvn clean test -Papp-server-eap -Dtest=org.keycloak.testsuite.adapter.servlet.SAMLServletAdapterTest
```
(*) You need a repo with the eap 7.4.3 distribution (`org.jboss.eap:wildfly-ee-dist` artifact).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Fixes #10894.

This one is a bit tricky. The problem is that the adapters should manage fixed and not fixed wildfly/EAP versions. So we need a detection to know if the EAP in which the bundle is installed has ELYWEB-163 or not. And there is no detection except looking into the version of the elytron-web module (we don't know if the parameter is double encoded or just has very strange characters). :smile: 

Changes:

* There is a system property to force the usage of the previous bogus behavior: `-Dorg.keycloak.adapters.elytronweb.forceBogus=true` (or false to forcibly not using it).
* By default the affected class in elytron-web is loaded and the implementation version checked. If the version is less than 1.9.2 or 1.10.1 (fixed ones) the bogus version is used. Otherwise the new correct code is used.
* The default is false (no bug) if not detected.
* Both adapters need to include `elytron-web` module (included as optional just in case) to load the class.

If someone has a better idea just let me know. But this is a generic query parameter getter so a parameter can be very strange with weird characters.

### CODE REVIEW

File: adapters/oidc/wildfly-elytron/src/main/java/org/keycloak/adapters/elytron/ElytronHttpFacade.java [hunk 1]
```diff
@@ -77,6 +83,30 @@
...
+
+    static {
+        boolean bogus = false;
+        String prop = System.getProperty("org.keycloak.adapters.elytronweb.forceBogus");
+        if (prop != null) {
+            bogus = Boolean.parseBoolean(prop);
+            log.tracef("Forcing value for bogus version of elytron-web %b", bogus);
+        } else {
+            try {
+                Class clazz = ElytronHttpFacade.class.getClassLoader().loadClass("org.wildfly.elytron.web.undertow.server.ElytronHttpExchange");
```
Comment (mabartos) [inline adapters/oidc/wildfly-elytron/src/main/java/org/keycloak/adapters/elytron/ElytronHttpFacade.java:96]: @rmartinc Just out of curiosity. What's the intention behind the using this instead of `ElytronHttpExchange.class.getPackage().getImplementationVersion();` ?

Comment (rmartinc) [reply adapters/oidc/wildfly-elytron/src/main/java/org/keycloak/adapters/elytron/ElytronHttpFacade.java:96]: Not depending in the elytron-web module. If for whatever reason the module or class disappear we set the bogus property to false. I declared the module optional too in the module.xml.

**Comment by mabartos** [comment]
At this moment, it's not possible to execute the adapter tests due to the build pipeline is not working. However, I tried to execute a few SAML Adapter tests on my local machine and everything works as expected. (Tested with EAP 7.4.3.GA, EAP 7.4.2.GA and WildFly version included in the latest upstream main branch).

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thank you for the PR. While functionality might be fixed, there are couple of other items to fix:

- The changes to this regression on Wildfly / EAP side should only be done to the respective adapters code *only*
- Changes in this patch to `common` module are not in line with that and have to be moved to inside adapters
- `org.keycloak.adapters.elytronweb.forceBogus` is misleading and should be renamed to a more suitable name that encapsulates the problematic issue, like `org.keycloak.adapters.elytronweb.ELY-163.workaround`
- This applies to all variables that are named "bogus" - the names are misleading for the future (which one of "boguses" will that be in a year?) and thus need to be named with maintenance in mind

**Comment by rmartinc** [comment]
@hmlnarik OK to all except the common one... I placed the class there because I see no other package that is common to saml and oidc wildfly-elytron adapters. It's just a utility static class. Do I duplicate the code in both saml and oidc better?

**Comment by mabartos** [comment]
@hmlnarik I'm quite lean towards the @rmartinc's argument with the 'common' module. AFAIK, the module is always present for all SAML and OIDC adapters, and additional duplication, IMHO, would bring more significant maintainability effort and risk of unintentional inconsistency in the future. For some time, we use a few static util classes from the 'common' module (i.e. `UriUtils`,...) and we didn't encounter any problems with that, therefore I wouldn't consider it as the need for change.

@hmlnarik Could you please elaborate your concern a little bit more?

**Comment by hmlnarik** [comment]
> @hmlnarik OK to all except the common one... I placed the class there because I see no other package that is common to saml and oidc wildfly-elytron adapters. It's just a utility static class. Do I duplicate the code in both saml and oidc better?

Yes please. Long term we might remove adapters from main keycloak repository, and this change does is not used in keycloak server.

**Comment by sguilhen** [comment]
> * `org.keycloak.adapters.elytronweb.forceBogus` is misleading and should be renamed to a more suitable name that encapsulates the problematic issue, like `org.keycloak.adapters.elytronweb.ELY-163.workaround`

I was going to comment something very similar to that, so +1 to change that into something more meaningful

**Review by sguilhen — DISMISSED** [review]
LGTM

**Review by hmlnarik — COMMENTED** [review]
Changes look good to me now, thanks @rmartinc! I would like to see adapter pipeline passing before approving though. @mabartos , could you please check it?

**Comment by mabartos** [comment]
The build pipeline is available again, so I'll let you know about the results then.

**Comment by mabartos** [comment]
The execution of adapter pipeline tests is finished. However, there's some issue with EAP6, so I need to verify if it's related or not.
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/933/

```
&amp#27;[31m04:36:57,058 ERROR [org.apache.catalina.connector] (http-127.0.0.1:8280-1) JBWEB001018: An exception or error occurred in the container during the request processing: java.lang.NoClassDefFoundError: Could not initialize class org.keycloak.adapters.jbossweb.JBossWebPrincipalFactory
	at org.keycloak.adapters.saml.jbossweb.SamlAuthenticatorValve.createPrincipalFactory(SamlAuthenticatorValve.java:73) [keycloak-saml-as7-adapter-999-SNAPSHOT-pr-10895-20220325-064941.jar:999-SNAPSHOT-pr-10895-20220325-064941]
	at org.keycloak.adapters.saml.AbstractSamlAuthenticatorValve.createSessionStore(AbstractSamlAuthenticatorValve.java:288) [keycloak-saml-tomcat-adapter-core-999-SNAPSHOT-pr-10895-20220325-064941.jar:999-SNAPSHOT-pr-10895-20220325-064941]
	at org.keycloak.adapters.saml.AbstractSamlAuthenticatorValve.getSessionStore(AbstractSamlAuthenticatorValve.java:280) [keycloak-saml-tomcat-adapter-core-999-SNAPSHOT-pr-10895-20220325-064941.jar:999-SNAPSHOT-pr-10895-20220325-064941]
	at org.keycloak.adapters.saml.AbstractSamlAuthenticatorValve.invoke(AbstractSamlAuthenticatorValve.java:182) [keycloak-saml-tomcat-adapter-core-999-SNAPSHOT-pr-10895-20220325-064941.jar:999-SNAPSHOT-pr-10895-20220325-064941]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.21.Final-redhat-1.jar:7.5.21.Final-redhat-1]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:151) [jbossweb-7.5.29.Final-redhat-1.jar:7.5.29.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.29.Final-redhat-1.jar:7.5.29.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.29.Final-redhat-1.jar:7.5.29.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [jbossweb-7.5.29.Final-redhat-1.jar:7.5.29.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.5.29.Final-redhat-1.jar:7.5.29.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:656) [jbossweb-7.5.29.Final-redhat-1.jar:7.5.29.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.29.Final-redhat-1.jar:7.5.29.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
```

**Comment by mabartos** [comment]
@rmartinc Unfortunately, the test failures for EAP6 seem to be related to this PR. I compared the results with our nightly builds and didn't find any of the present failures. I'll try to find out, what should be done in order to fix it.

**Comment by rmartinc** [comment]
@mabartos I think that is very strange that it is related because now the changes are only in elytron projects which should be unrelated to EAP6 as far as I can understand. But I didn't test anything with EAP6, that is true.

File: distribution/feature-packs/adapter-feature-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-wildfly-elytron-oidc-adapter/main/module.xml [hunk 2]
```diff
@@ -45,6 +45,7 @@
         <module name="org.keycloak.keycloak-core"/>
         <module name="org.keycloak.keycloak-common"/>
         <module name="org.wildfly.security.elytron" optional="true"/>
+        <module name="org.wildfly.security.elytron-web.undertow-server" optional="true"/>
```
Comment (mabartos) [inline distribution/feature-packs/adapter-feature-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-wildfly-elytron-oidc-adapter/main/module.xml:48]: @rmartinc It seems the failures for EAP6 are caused by this.

**Comment by mabartos** [comment]
@rmartinc I'll try to execute those tests once again, but I don't think it'll help. We'll see.

File: distribution/feature-packs/adapter-feature-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-wildfly-elytron-oidc-adapter/main/module.xml (hunk 2 above)
Comment (mabartos) [reply distribution/feature-packs/adapter-feature-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-wildfly-elytron-oidc-adapter/main/module.xml:48]: It seems not.

**Comment by mabartos** [comment]
Next update: It's failing only with JDK7. With JDK8, everything works as expected.

**Comment by rmartinc** [comment]
@mabartos I rebased the PR to include [this commit](https://github.com/keycloak/keycloak/commit/fb92b95c33a6d036c0f9ee00aaa8a999d6410aff).

**Review by mabartos — APPROVED** [review]
@hmlnarik The pipeline tests passed. (the present failures are not related to this PR)

All adapters: https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/933/
EAP adapters: https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/937/

@rmartinc Thank you very much for the fix!

**Review by sguilhen — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]
Approving per @sguilhen 's and @mabartos 's approval. Thanks @rmartinc!
