### PR TITLE
Switching to Resteasy Reactive

### LINKED ISSUE #10713: Update the server to use RESTEasy Reactive
### Description

Accordingly, to @geoand, applications using `quarkus-resteasy-reactive` should still benefit from a better startup time, runtime performance, and memory footprint, even though not using reactive style/semantics. Most importantly, applications using RESTEasy Classic should be able to move to `quarkus-resteasy-reactive` without any changes to code if they are relying on JAX-RS API.

We should evaluate how much it would take to change the server to use `quarkus-resteasy-reactive`.

### Discussion

_No response_

### Motivation

Benefit from the improvements brought by `quarkus-resteasy-reactive` and keep the server aligned with Quarkus goals.

### Details

_No response_

### LINKED ISSUE #20451: User search returns invalid JSON if request caused error
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

In case of LDAP User Federation if there is an backend error while fetching users, response returned by Keycloak is not a valid JSON.  Response from the server is : 

[]{"error":"unknown_error"}

Depending on the setup array can sometimes contains user objects.

### Version

21.1.1

### Expected behavior

KC should return valid JSON for example : {"error":"unknown_error"}, without user array

### Actual behavior

KC returns array of user objects (empty or not) which is not valid JSON. Here are two responses that I am getting on two different versions and installations:

url: https://localhost:8086/auth/admin/realms/myrealm/users?briefRepresentation=true&first=0&max=20&search=*
response: []{"error":"unknown_error"}

or 

url: http://localhost:8080/admin/realms/master/ui-ext/brute-force-user?briefRepresentation=true&first=0&max=11&search=*
response: [{"id":"53111570-de45-4dbd-81f3-02923e446686","createdTimestamp":1684474467833,"username":"admin","enabled":true,"emailVerified":false,"access":{"manageGroupMembership":true,"view":true,"mapRoles":true,"impersonate":true,"manage":true},"bruteForceStatus":{"numFailures":0,"disabled":false,"lastIPFailure":"n/a","lastFailure":0}}]{"error":"unknown_error"}

### How to Reproduce?

1) Install Keycloak
2) Add LDAP/ User Federation but provide invalid connection URL
3) go to users
4) search for * 
5) check response

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes https://github.com/keycloak/keycloak/issues/10713
Closes #20451

### CODE REVIEW

**Comment by vmuzikar** [comment]
@pedroigor Since 21 is now released, maybe we can continue with this?

**Comment by pedroigor** [comment]
@vmuzikar I Rebased again and marked it as ready for review.

**Comment by pedroigor** [comment]
Rebased again.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+import org.keycloak.http.FormPartValue;
+import org.keycloak.http.HttpRequest;
+import org.keycloak.quarkus.runtime.integration.jaxrs.EmptyMultivaluedMap;
+import org.keycloak.services.FormPartValueImpl;
+
+import io.vertx.ext.web.RoutingContext;
+
+public final class QuarkusHttpRequest implements HttpRequest {
+
+    private static final MultivaluedMap<String, String> EMPTY_FORM_PARAM = new EmptyMultivaluedMap<>();
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java:44]: Do we really need to create our implementation of empty MultivaluedMap? What's the intention behind this?

What about use `javax.ws.rs.core.MultivaluedHashMap`?
```suggestion
    private static final MultivaluedMap<String, String> EMPTY_FORM_PARAM = new MultivaluedHashMap<>();
```

File: services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java [hunk 2]
```diff
@@ -109,7 +108,7 @@ public KeycloakApplication() {
             classes.add(KcUnrecognizedPropertyExceptionHandler.class);
 
             singletons.add(new ObjectMapperResolver());
```
Comment (mabartos) [inline services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java:110]: Why this `ObjectMapperResolver` is represented as a singleton? Would probably be better to use the same approach as for the WelcomeResource, right? Add it here to classes, and in QuarkusKeycloakApplication remove it. The instantiation of this object is done here and for Quarkus not used at all. 

WDYT?

**Review by mabartos — COMMENTED** [review]
@pedroigor I've just briefly looked at it and have some comments. Code in general looks good to me, but I'm a little bit concerned about the benchmarking. I'm just wondering what we could do more in this context. But of course, it can be done in some follow-up tasks.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java (hunk 1 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java:44]: Because we don't want callers writing to it as it should hold no data. If you try to add something to it you get an exception.

File: services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java (hunk 2 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java:110]: I would prefer to avoid changing `KeycloakApplication` in this PR. It is still used by Undertow and in Quarkus we do it right.

Comment (mabartos) [reply services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java:110]: Yeah, I understand, but why are the other singletons changed here in KeycloakApplication? It's only a nitpick, but would be good to have it unified, and I'd like to find out if there's some special intention behind it :))

**Comment by tkyjovsk** [comment]
Hello, recent _keycloak-benchmark_ test runs on this branch (vs nightly) show **+50% increase in response times for the login operation with JPA map store** , and **+80% increase with JPA legacy store**, both with PostgreSQL.

With Jaeger tracing I was able to narrow it down to method: `org.keycloak.services.resources.LoginActionsService.authenticateForm`.

Test runs for Client Credentials show **no increase in response times.** Neither do `admin.CreateDelete*` scenarios. 

There is **no increase in KC server startup time,** and the memory footprint 2-3 minutes after start looks the same as for the nightly version. There is about **+10% increase in augmentation time.**

These results are valid for revision: `6fe74cd`. I wanted to rerun with the more recent revision but I'm not able to build the container image for some reason.

File: services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java (hunk 2 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java:110]: I remember facing some errors when doing it. I need to change and check again.

**Comment by geoand** [comment]
> Hello, recent keycloak-benchmark test runs on this branch (vs nightly) show +50% increase in response times for the login operation with JPA map store , and +80% increase with JPA legacy store, both with PostgreSQL.

Hi,

How do I reproduce this? I am interested in seeing why the RESTEasy Reactive port is slower

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 3]
```diff
@@ -615,15 +594,22 @@ void disableHealthEndpoint(BuildProducer<RouteBuildItem> routes, BuildProducer<B
...
     @BuildStep
-    void configureResteasy(BuildProducer<ResteasyDeploymentCustomizerBuildItem> deploymentCustomizerProducer) {
-        deploymentCustomizerProducer.produce(new ResteasyDeploymentCustomizerBuildItem(new Consumer<ResteasyDeployment>() {
+    void configureResteasy(CombinedIndexBuildItem index,
+            BuildProducer<BuildTimeConditionBuildItem> buildTimeConditionBuildItemBuildProducer,
+            BuildProducer<MethodScannerBuildItem> scanner) {
+        buildTimeConditionBuildItemBuildProducer.produce(new BuildTimeConditionBuildItem(index.getIndex().getClassByName(DotName.createSimple(
+                KeycloakApplication.class.getName())), false));
+
+        // TODO: remove when https://github.com/quarkusio/quarkus/issues/29575 is available
```
Comment (geoand) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:603]: Should this now be removed?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java [hunk 4]
```diff
@@ -53,16 +68,24 @@ protected void loadConfig() {
...
+    public Set<Class<?>> getClasses() {
+        Set<Class<?>> classes = new HashSet<>(super.getClasses());
+
+        classes.remove(WelcomeResource.class);
+        classes.add(QuarkusWelcomeResource.class);
 
-        singletons.add(new QuarkusWelcomeResource());
+        classes.add(QuarkusObjectMapperResolver.class);
+        classes.add(CloseSessionHandler.class);
+        classes.add(StreamingOutputMessageBodyWriter.class);
```
Comment (geoand) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:83]: I think this was added to Quarkus as well

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java (hunk 3 above)
Comment (pedroigor) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:603]: Probably, I'll remove it and update the branch.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java (hunk 4 above)
Comment (geoand) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:83]: Yeah, I am thinking of https://github.com/quarkusio/quarkus/pull/30945

Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java]: Seems to work fine without it. Branch updated.

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java (hunk 3 above)
Comment (pedroigor) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java]: Seems to work fine after removing the workaround. Branch updated.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java [hunk 5]
```diff
@@ -250,12 +250,12 @@ public void jsonProcessingException() throws IOException {
             try (CloseableHttpResponse response = client.execute(post)) {
                 assertEquals(Response.Status.BAD_REQUEST.getStatusCode(), response.getStatusLine().getStatusCode());
 
-                Header header = response.getFirstHeader("Content-Type");
-                assertThat(header, notNullValue());
-                assertEquals(MediaType.APPLICATION_JSON, header.getValue());
-
-                OAuth2ErrorRepresentation error = JsonSerialization.readValue(response.getEntity().getContent(), OAuth2ErrorRepresentation.class);
-                assertEquals("unknown_error", error.getError());
+//                Header header = response.getFirstHeader("Content-Type");
```
Comment (pedroigor) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java:253]: For some reason, our `ExceptionMapper` is not being invoked when this test is forcing a deserialization issue (sending an JSON array whereas the endpoint expects a single JSON object).

@geoand Not a blocker for the benchmark work so I'm adding this comment to investigate this in more detail.

**Comment by geoand** [comment]
> Hello, recent _keycloak-benchmark_ test runs on this branch (vs nightly) show **+50% increase in response times for the login operation with JPA map store** , and **+80% increase with JPA legacy store**, both with PostgreSQL.
> 

What configuration was used to run the benchmark? 
I am asking because I cannot replicate these results locally - the two branches effectively perform the same for the load configurations I tested.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java (hunk 5 above)
Comment (geoand) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java:253]: Which `ExceptionMapper` is meant to be called?

Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java:253]: The https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java is our main mapper.

There is another one (https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/error/KcUnrecognizedPropertyExceptionHandler.java) but I don't think it is related to the test failure.

Both are registered here https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java.

Comment (geoand) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java:253]: Hm... IIRC, we don't really support registering providers that way...

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java (hunk 4 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:83]: @geoand When removing the custom `MessageBodyWriter` we have failures in a test.

For some reason, without the custom `MessageBodyWriter` our exception mapper is not invoked to properly handle exceptions thrown during the deserialization of methods parameters. For instance, we expect our exception mapper setting a proper content type and response payload. See https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java#L253.

Comment (geoand) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:83]: I'll have to try it tomorrow

Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java]: I did something wrong here.

The difference is actually in how our exception mappers are mapped to exceptions at runtime. I had to add a new `KeycloakMismatchedInputExceptionHandler` to override the default instance set by Resteasy Reactive when mapping exceptions of type `com.fasterxml.jackson.databind.exc.MismatchedInputException`. See https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/ResteasyReactiveJacksonProcessor.java#L112.

We have a generic exception mapper (`org.keycloak.services.error.KeycloakErrorHandler`) to handle `Throwable`. It seems the `DefaultMismatchedInputException` is taking precedence (even though it is not a user-defined mapper) because it is specific for `MismatchedInputException`. Is this behavior expected or Resteasy should run the custom mapper instead?

Comment (geoand) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java]: So is there still anything I should look at WRT this?

**Comment by tkyjovsk** [comment]
On 2023-06-12 (about a month ago) I rerun the performance comparison of this branch vs main and I was NOT ABLE TO REPRODUCE the performance difference anymore. I've run the test on 3 different types of HW to be sure. (Sorry for the delayed response. I already provided this feedback via other means but forgot to post an update here.)

@pedroigor I see that there have been some changes on this branch since then. Would it make sense to retest again? Or do you plan to make some additional changes here?

**Comment by pedroigor** [comment]
@tkyjovsk Not sure if we need it because changes were basically polishing the code. They should not impact the runtime so much.

**Comment by mabartos** [comment]
@pedroigor We can continue around this initiative, right? Is there anything you'd like to add?

**Comment by vmuzikar** [comment]
We need a rebase. :)

**Comment by pedroigor** [comment]
@vmuzikar I'm marking the PR as a draft because I'm expecting failures related to the hostname debug capability. With Resteasy Reactive, the JAX-RS application is built ahead of time and we can't dynamically enable the debug endpoint dynamically. We can either mark the `hostname-debug` as a built-time option or change how the endpoint is enabled at runtime.

I'll try out some solutions to keep the current behavior and let you know.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java (hunk 4 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java]: @geoand It should be fine from your side. Thanks for all your help!

Comment (geoand) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java]: 🙏

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 6]
```diff
@@ -614,15 +589,19 @@ void disableHealthEndpoint(BuildProducer<RouteBuildItem> routes, BuildProducer<B
     }
 
     @BuildStep
-    void configureResteasy(BuildProducer<ResteasyDeploymentCustomizerBuildItem> deploymentCustomizerProducer) {
-        deploymentCustomizerProducer.produce(new ResteasyDeploymentCustomizerBuildItem(new Consumer<ResteasyDeployment>() {
+    void configureResteasy(CombinedIndexBuildItem index,
+            BuildProducer<BuildTimeConditionBuildItem> buildTimeConditionBuildItemBuildProducer,
+            BuildProducer<MethodScannerBuildItem> scanner) {
+        buildTimeConditionBuildItemBuildProducer.produce(new BuildTimeConditionBuildItem(index.getIndex().getClassByName(DotName.createSimple(
+                KeycloakApplication.class.getName())), false));
```
Comment (mabartos) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:596]: Just out of curiosity, what exactly is this change for? What does the `BuildTimeConditionBuildItem` do? I haven't found any docs for it.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java [hunk 7]
```diff
@@ -44,6 +44,7 @@
 import org.keycloak.quarkus.runtime.cli.Picocli;
 import org.keycloak.common.Version;
 import org.keycloak.quarkus.runtime.cli.command.Start;
+import org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory;
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java:47]: Nitpick; unused import.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java [hunk 8]
```diff
@@ -0,0 +1,152 @@
...
+    }
+
+    @Override
+    public HttpHeaders getHttpHeaders() {
+        return context.getHttpHeaders();
+    }
+
+    @Override
+    public X509Certificate[] getClientCertificateChain() {
+        Instance<RoutingContext> instances = CDI.current().select(RoutingContext.class);
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java:127]: Can't we directly leverage Arc[1] when it's related directly to Quarkus? Or you wanted to achieve more abstraction via CDI? 

[1] `Arc.container().instance(...`

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java [hunk 9]
```diff
@@ -53,16 +67,21 @@ protected void loadConfig() {
 
     @Override
     public Set<Object> getSingletons() {
-        Set<Object> singletons = super.getSingletons().stream()
-                .filter(QuarkusKeycloakApplication::filterSingletons)
-                .collect(Collectors.toSet());
+        return Set.of();
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:70]: Can we remove the `ObjectMapperResolver` singleton as we already have the extended version `QuarkusObjectMapperResolver` in classes? Or should the singleton exist?

**Review by mabartos — COMMENTED** [review]
@pedroigor Fantastic work! I've just added some comments below. 

These are only nitpicks and rather questions as I'd like to fully understand it. I don't see any blocker for this PR, just need to wait for the performance results. 

Thanks!

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java (hunk 6 above)
Comment (pedroigor) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:596]: Removes the given type from Arc index. As we don't want `KeycloakApplication` available we disable it.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java (hunk 9 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:70]: This is how it is working already, isn't it? I mean, the `ObjectMapperResolver` should not be registered as an extension at runtime.

**Comment by pedroigor** [comment]
@mabartos Rebased

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java (hunk 8 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java:127]: Yes, we can. If not a blocker I would leave it as is.

**Review by mabartos — APPROVED** [review]
@pedroigor Thanks for the clarification. LGTM

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java [hunk 10]
```diff
@@ -1,175 +0,0 @@
...
-            // See https://github.com/quarkusio/quarkus/issues/34998 for a discussion.
-            context.vertx().executeBlocking(ctx -> {
-                try {
-                    runBlockingCode(context);
-                    ctx.complete();
-                } catch (Throwable ex) {
-                    ctx.fail(ex);
-                }
-            }, false, null);
-            if (loadSheddingActive) {
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:89]: I believe this PR broke the load shedding. See also #21962. We should've had probably tests for it.

CC @ahus1

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@pedroigor Thanks, very nice work!

Added one comment. Apart from that LGTM but I'm not super familiar with the low-level RESTEasy stuff.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java (hunk 10 above)
Comment (ahus1) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:89]: Load shedding is not officially support as of now. If this PR breaks it, just continue with this PR and we'll fix it (and officially support it) afterwards.

**Review by vmuzikar — APPROVED** [review]
Approving based on @ahus1's feedback as my only concern is now resolved.
