### PR TITLE
Use AWS JDBC Wrapper in CI tests. Resolves #27123

### LINKED ISSUE #27123: Use AWS JDBC Wrapper in CI tests
### Description

The [Amazon Web Services (AWS) JDBC Driver](https://github.com/awslabs/aws-advanced-jdbc-wrapper)  is the recommended driver for users to connect to Aurora Postgres instances. Therefore, we should update the testsuite so that all Aurora tests are executed using said driver.

### LINKED ISSUE #27133: Workflow failure: Keycloak CI - Store IT (aurora-postgres)
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Recently during the weekend this stage started to fail with following message, occurred in 3 runs leading into the same result on each run.
```
The error appears to be in '/home/runner/work/keycloak/keycloak/.github/scripts/ansible/roles/mvn_ec2_runner/tasks/run.yml': line 15, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Run mvn command on the remote hosts
  ^ here
Error: Process completed with exit code 4.
``` 

job1: https://github.com/keycloak/keycloak/actions/runs/7937743626/job/21675720361
job2: https://github.com/keycloak/keycloak/actions/runs/7945178083/job/21691732542
job3: https://github.com/keycloak/keycloak/actions/runs/7952710409/job/21707852026

### Version

latest

### Regression

- [ ] The issue is a regressions

### Expected behavior

n/a

### Actual behavior

n/a

### How to Reproduce?

n/a

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ryanemerson**
Resolves #27123
Fixes #27133

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/StoreProvider.java [hunk 1]
```diff
@@ -31,25 +31,39 @@ public enum StoreProvider {
     JPA("jpa") {
         @Override
         public void addStoreOptions(List<String> commands) {
-            getDbVendor().ifPresent(vendor -> commands.add("--db=" + vendor));
+            getDbVendor().ifPresent(vendor -> {
```
Comment (ahus1) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/StoreProvider.java:34]: This switch seems to appear twice, so I wonder if it can be extracted.

The refactoring to a switch delivers IMHO the correct results, but switch statements without a `break` after each case are difficult to maintain, so I'd rather avoid them.

**Review by ahus1 — DISMISSED** [review]
Thank you for this PR. While the changes look quite good (let's wait for test results), I'd like you to change the switch statement for better readability. 

My rule of thumb: Never use switch cases without break.

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/StoreProvider.java (hunk 1 above)
Comment (ryanemerson) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/StoreProvider.java]: Updated.

Comment (ahus1) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/StoreProvider.java]: Thanks. Let me know once there is a green build in your branch and then I'll review the PR again.

**Comment by ryanemerson** [comment]
Green run with Aurora tests passing on my fork: https://github.com/ryanemerson/keycloak/actions/runs/7961605755

**Review by ahus1 — APPROVED** [review]
Thank you for this PR fixing the problem I introduces
