### PR TITLE
removes the termination grace period override

### LINKED ISSUE #22160: Occasional operator test failures
### Description

Recent prs seem to be related to some failed startup / migration https://github.com/keycloak/keycloak/actions/runs/5726457904/job/15517348959?pr=22152#step:8:2561 and https://github.com/keycloak/keycloak/actions/runs/5726457904/job/15517348959?pr=22152#step:8:2699 - this does not happen consistently, but once it does it seems to inhibit that keycloak instance from coming up.  Presumably this has to do with sharing the database instance for all tests in a test class.

The root exception message is 
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "user_setup_allowed" of relation "authentication_execution" does not exist
```

This may have become more prevelent by changes to speed up the tests - the immediate termination of pods and not waiting for instances to become ready could cause a prior test to corrupt some expection of the database state.  However I'm not familar enough to know why it should even be entering migration logic.

cc @vmuzikar

### PR DESCRIPTION
**Pull request by shawkins**
It does appear that non-graceful termination makes it more possible to put the database in a bad state.

This does leave in place the tweak to remove the probes for some of the tests, that seems to account for about 4 seconds per pod start of improvement, or somewhere around 1-2 minutes over the entire test suite run.  There are two options there:
1. just remove this optimization also
2. allow it to be enabled or disabled by a flag so that at least the CI remote test run would run with probes enabled.

Closes #22160

### CODE REVIEW

**Comment by vmuzikar** [comment]
@shawkins Thanks for the fix. Do we have some batch run (at least 10 CI runs or so) to check if this fully fixed https://github.com/keycloak/keycloak/issues/22160? If so, I'm ok with keeping removing the probes in tests.

**Comment by shawkins** [comment]
> Do we have some batch run (at least 10 CI runs or so) to check if this fully fixed https://github.com/keycloak/keycloak/issues/22160?

@vmuzikar what mechanism exists for this?  I don't seem to have rights to even manually retrigger GHA workflows.

**Comment by vmuzikar** [comment]
> @vmuzikar what mechanism exists for this? I don't seem to have rights to even manually retrigger GHA workflows.

See e.g. https://github.com/vmuzikar/keycloak/blob/8564dacbc96533b109b7fc99d803ecca1c022933/.github/workflows/ci.yml#L68

**Comment by shawkins** [comment]
@vmuzikar looks good with 20 test runs https://github.com/shawkins/keycloak/actions/runs/5751557199

**Review by vmuzikar — DISMISSED** [review]
@shawkins Thanks!

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java [hunk 1]
```diff
@@ -265,7 +265,7 @@ public void afterEach(QuarkusTestMethodContext context) {
           return;
       }
       try {
-          if (!context.getTestStatus().isTestFailed() && !(context.getTestStatus().getTestErrorCause() instanceof TestAbortedException)) {
+          if (!context.getTestStatus().isTestFailed() || context.getTestStatus().getTestErrorCause() instanceof TestAbortedException) {
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:268]: Ah, good catch! Missed that during the review.

**Review by vmuzikar — APPROVED** [review]

**Comment by vmuzikar** [comment]
CI is acting weird (which prevents me from merging). Closing and reopening.
