### PR TITLE
Client Types - Client Update/Create Validations

### LINKED ISSUE #28528: API Validation of Clients associated with a Client Type
### Description

Report failures with client update and creation requests, when the client is associated with a client type.

API should respond with bad request and with all of the parameters that failed validation.

Part of #22262

### PR DESCRIPTION
**Pull request by patrickjennings**
Closes #28528.

Improves validation of client creation and update requests, by returning the full list of fields that failed due to being non-applicable or read-only and a value being specified by the request.

Respond with 400 bad request response and all failures are provided in the params response field.

### CODE REVIEW

**Review by vickeybrown — APPROVED** [review]
LGTM!

File: services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java [hunk 1]
```diff
@@ -81,47 +84,84 @@ public <T> T getDefaultValue(String optionName, Class<T> optionType) {
...
+
+        if (!propertyConfig.getApplicable() || propertyConfig.getDefaultValue() == null) {
+            return;
+        }
+
+        if (clientRepresentationProperties.containsKey(propertyName)) {
+            // Java property on client representation
+            Method setter = clientRepresentationProperties.get(propertyName).getWriteMethod();
+            try {
+                setter.invoke(client, propertyConfig.getDefaultValue());
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java:154]: Looks good. 

FYI. from the long term perspective, I can think about avoid using reflection and instead rely on something like:

```
Map<String, BiConsumer<ClientModel, Object>> properties;

properties.put("standardFlowEnabled", (clientModel, standardFlowModel) -> client.setStandardFlowEnabled(standardFlowEnabled));
```

And then in `setClientProperty` something like:

```
BiConsumer invoker = properties.get(propertyName);
invoker.accept(client, propertyConfig.getDefaultValue());
```

This can hopefully work for "compound" properties as wel (like clientScopes or protocolaMappers). But that is something for the future...

One question here is, if we need to set properties at all during client create/update as if properties are provided by clientType itself, we can rely on the properties returned by the clientType (done in `TypeAwareClientModelDelegate`) instead of rely on the properties returned by the client?

But those are all open questions for future discussions, rather than something specific to this PR :-)

File: services/src/main/java/org/keycloak/services/clienttype/DefaultClientTypeManager.java [hunk 2]
```diff
@@ -109,8 +109,14 @@ public ClientModel augmentClient(ClientModel client) throws ClientTypeException
...
         } else {
-            ClientType clientType = getClientType(client.getRealm(), client.getType());
-            return new TypeAwareClientModelDelegate(clientType, () -> client);
+            try {
+                ClientType clientType = getClientType(client.getRealm(), client.getType());
+                return new TypeAwareClientModelDelegate(clientType, () -> client);
+            } catch(ClientTypeException cte) {
+                logger.errorf("Could not augment client, %s, due to client type exception: %s",
+                        client, cte);
+                return client;
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/clienttype/DefaultClientTypeManager.java:118]:
```suggestion
                throw cte;
```

I am not sure about returning client in this case. If something is bad with clientType, it is rather better to propagate exception rather than just log it and return client IMO. Returned "unaugmented" client can have side-effects like for instance administrator being able to edit client properties, which he is not supposed to edit etc.

Comment (patrickjennings) [reply services/src/main/java/org/keycloak/services/clienttype/DefaultClientTypeManager.java]: Yeah that is likely the safer option. Reverted so it will propagate the exception as well as log as an error message.

This might affect loading of other clients, as well. For instance through the admin UI, the listing of clients will fail to load if this exception is thrown. The admin will have to fix the issue with the client type to proceed.

File: services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java (hunk 1 above)
Comment (patrickjennings) [reply services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java:154]: Agreed! Having a consistent way of augmenting the client model / representation would be a good idea.

**Review by mposolda — APPROVED** [review]
@patrickjennings Thanks for the updates
