### PR TITLE
Enhance error logs and error events during UserInfo endpoint and Toke…

### LINKED ISSUE #24344: Enhance error logs and error events during UserInfo endpoint and Token Introspection failure
### Description

When a UserInfo Endpoint returns error and Token Introspection returns _{"valid":"false"}_ , no useful information is logged and from login events you could not specify why UserInfo endpoint or Token Introspection are failed.
For some cases, users open issue for such errors. Most of the times, we could not respond for the failing reason with debugging. Debugging can not be done in production instance.

So, we believe that we should enhance logs and USER_INFO_REQUEST_ERROR and iNTROSPECT_TOKEN_ERROR events.

No user secure information like access token, passwords must be saved.

### Discussion

_No response_

### Motivation

When a UserInfo Endpoint returns error and Token Introspection returns _{"valid":"false"}_ , logs and USER_INFO_REQUEST_ERROR and iNTROSPECT_TOKEN_ERROR events should be sufficient for recognize error reason.

### Details

We plan to open a PR to enhance error logs and error events during UserInfo endpoint and Token Introspection failure.
We could discuss there appropriate logging.

### PR DESCRIPTION
**Pull request by cgeorgilakis**
…n Introspection failure

Closes #24344

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java [hunk 1]
```diff
@@ -306,7 +310,10 @@ public boolean checkTokenValidForIntrospection(KeycloakSession session, RealmMod
             if (realm.isRevokeRefreshToken()
                 && (tokenType.equals(TokenUtil.TOKEN_TYPE_REFRESH) || tokenType.equals(TokenUtil.TOKEN_TYPE_OFFLINE))
                 && !validateTokenReuseForIntrospection(session, realm, token)) {
-                return false;
+                 logger.warn("Introspection access token for "+token.getIssuedFor() +" client: failed to validate Token reuse for introspection");
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java:313]: Is it possible to debug instead of warn?

File: services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java [hunk 2]
```diff
@@ -316,8 +323,12 @@ public boolean checkTokenValidForIntrospection(KeycloakSession session, RealmMod
                     clientSession.setTimestamp(currentTime);
                 }
             }
+            eventBuilder.detail("Token valid for introspection", String.valueOf(valid));
+            
         }
 
+        if (!valid)
+            logger.warn("Introspection access token: Failed to valid access token for introspection");
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java:331]: Is it possible to debug instead of warn and possibly add more context data?

**Review by mposolda — COMMENTED** [review]
@cgeorgilakis Thanks! Is it possible to rebase to latest Keycloak main? Hopefully it will help to fix the build, which failed in GH actions.

Also I would suggest to avoid using `warn` level in the introspection endpoint as introspection is pretty often operation and `warn` is mostly dedicated for server-wide issues instead of issues with client/users invoking HTTP requests in often-used endpoints.

Also it can be nice to add more context informations to debug messages and/or avoid adding them at all - as with added event error, the information is available anyway from the event details (which is logged by default anyway by JBOssLoggingEventListenerProvider)? I marked some of them in the inline comments, but it applies to pretty much all the warnings you introduced.

File: services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java [hunk 3]
```diff
@@ -199,7 +199,7 @@ public TokenValidation validateToken(KeycloakSession session, UriInfo uriInfo, C
         }
 
         if (oldToken.isIssuedBeforeSessionStart(clientSession.getStarted())) {
-            logger.debug("refresh token issued before the client session started");
+            logger.warn("refresh token issued before the client session started");
```
[the remark this answers is not in the document]
Comment (cgeorgilakis) [reply services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java:202]: I will keep previous code. This is changed by mistake. This is for refresh token validation.

File: services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java (hunk 2 above)
Comment (cgeorgilakis) [reply services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java]: > Is it possible to debug instead of warn and possibly add more context data?

I have created appropriate debug logs and event deails for all possible cases of valid = false.

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis Thanks! Is it possible to rebase to latest Keycloak main? Hopefully it will help to fix the build, which failed in GH actions.
> 
> Also I would suggest to avoid using `warn` level in the introspection endpoint as introspection is pretty often operation and `warn` is mostly dedicated for server-wide issues instead of issues with client/users invoking HTTP requests in often-used endpoints.
> 
> Also it can be nice to add more context informations to debug messages and/or avoid adding them at all - as with added event error, the information is available anyway from the event details (which is logged by default anyway by JBOssLoggingEventListenerProvider)? I marked some of them in the inline comments, but it applies to pretty much all the warnings you introduced.

I have corrected GH-actions related errors, have made all loggers as debug and have enhanced information (logger and event details) based mainly on your suggestions.
Could you review it again?

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis Thanks! Looks much better.
> 
> I have still one thing (not sure if you added it in your latest changes, or if it was already present. I am sorry if it was already present and I did not noticed in the previous review): You are using event details in the way like this:
> 
> ```
> eventBuilder.detail("Valid user session not found", String.format("Could not find valid user session for session_state = %s", token.getSessionState()));
> ```
> 
> Here I can add that the key of the event detail is supposed to be the "simple key" like thing, so it can be easily filtered by various event listeners etc. This key is not supposed to be random string like `Valid user session not found` . You can take a look at the class `org.keycloak.events.Details` for the inspiration and how the details are used in various other events in Keycloak. I think that in the most cases for this PR, you can use the event detail with key `REASON`, which is used in various places in Keycloak for add the error details to the event? So for instance for the case above something like:
> 
> ```
> eventBuilder.detail(Details.REASON, String.format("Could not find valid user session for session_state = %s", token.getSessionState()));
> ```
> 
> Similar probably can be used for some other occurences of the `eventBuilder.detail` in your PR. Can you please update like that?

I agree with you. All (or almost all -need investigation) event details must be under REASON tag.
This set must be happen once, in false token introspection. I will investigate possible errors, make appropriate changes and inform you.

General exception catch in token introspection must only log unexpected errors.

**Comment by cgeorgilakis** [comment]
I have maid changes related to Detail.REASON. @mposolda review them?

**Review by mposolda — APPROVED** [review]
@cgeorgilakis Thanks!
