### PR TITLE
fix: replace aesh with picocli

### LINKED ISSUE #27388: Migrate kcadm from aesh to picocli
### Description

For consistency and a better user experience we should migrate off of aesh. This will also help with issues like #27322

### PR DESCRIPTION
**Pull request by shawkins**
closes: #27388

A similar effort would be needed for kcreg, but it looks like there should also be a common module created to remove duplication between the two.

This is a minimal porting - it doesn't really rely on the picocli help system. The existing help / usage messages are re-used, but there are some small difference, which are consistent with kc.sh.

### CODE REVIEW

**Comment by shawkins** [comment]
@vmuzikar @mabartos this is to more fully address some of the recent issues we have seen aesh - the need for internal quoting (the change was made to kcadm, but not kcreg), and the odd parsing / message when specifying the wrong option (again applied to kcadm, but not kcreg). I also locally have the changes to kcreg, and would follow up with an additional issue to refactor to remove overlap between the two.

**Comment by shawkins** [comment]
> Just a question - should we use this as an opportunity to improve the [Server Administration docs](https://www.keycloak.org/docs/latest/server_admin/index.html)? I have in mind one specific https://github.com/keycloak/keycloak/issues/9948#issuecomment-1743615454, where users got confused by --realm and -r/--target-realm usage (and I can see the reason). I remember that when we were discussing it we agreed that all the options could be at least documented (in case we want to avoid any option name changes; right now the docs contains just specific examples).

Sounds good to get this documented. At least from a cli perspective the picocli default help / exception messages are pretty informative, but a replaced by the existing short message for continuity with the existing implemenation. We could aslo consider using more of the picocli help system. I'd capture these as separate issues though.

**Review by pedroigor — DISMISSED** [review]
LGTM.

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java [hunk 1]
```diff
@@ -103,100 +104,57 @@ public abstract class AbstractRequestCmd extends AbstractAuthOptionsCmd {
 
     String httpVerb;
 
-    Headers headers = new Headers();
+    @Option(names = {"-h", "--headers"}, description = "Set request header NAME to VALUE")
```
Comment (mabartos) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java:107]:
```suggestion
    @Option(names = {"-h", "--header"}, description = "Set request header NAME to VALUE")
```
I think it should be like this in order to reflect the old behavior.

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCmd.java [hunk 2]
```diff
@@ -16,66 +16,35 @@
...
-                        args.remove(0);
-                        ConfigTruststoreCmd command = new ConfigTruststoreCmd();
-                        command.initFromParent(this);
-                        return command.execute(commandInvocation);
-                    }
-                    default: {
-                        if (printHelp()) {
-                            return help ? CommandResult.SUCCESS : CommandResult.FAILURE;
-                        }
-                        throw new IllegalArgumentException("Unknown sub-command: " + cmd + suggestHelp());
```
Comment (mabartos) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCmd.java:59]: The current error message is not as pretty as the old one:

Execute command with a typo:
```
./kcadm.sh config truststores
```

Error message:
```
Unmatched argument at index 1: 'truststores'
```

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/NewObjectCmd.java [hunk 3]
```diff
@@ -51,59 +49,24 @@
...
 
-    @Option(shortName = 'c', name = "compressed", description = "Don't pretty print the output", hasValue = false)
+    @Option(names = {"-c", "--compressed"}, description = "Don't pretty print the output")
     boolean compressed;
 
-    //@OptionGroup(shortName = 's', name = "set", description = "Set attribute to the specified value")
-    //Map<String, String> attributes = new LinkedHashMap<>();
-
+    @Option(names = {"-s", "--set"}, description = "Set a specific attribute NAME to a specified value VALUE")
+    List<String> values = new ArrayList<>();
```
Comment (mabartos) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/NewObjectCmd.java:62]: @shawkins Do you know why it was ignored? 

I mean, from my POV +1, but I'm curious about the reason in the old version.

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/IoUtil.java [hunk 4]
```diff
@@ -81,43 +73,14 @@ public static void waitFor(long millis) {
...
+        char[] passwd;
+        if ((cons = System.console()) != null &&
+            (passwd = cons.readPassword("%s", prompt)) != null) {
+            return new String(passwd);
         }
-         */
-        // Windows hack - get rid of any \n
-        result = result.replaceAll("\\n", "");
-        return result;
+        throw new RuntimeException("Console is not active, or no password provided");
```
Comment (mabartos) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/IoUtil.java:83]: nit: I'd prefer to separate these errors as it's more clear to the user what's going on. So, one for not active console, and the other one for no password. @shawkins wdyt?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java [hunk 5]
```diff
@@ -34,8 +34,8 @@ public void testBadCommand() {
          */
         KcAdmExec exe = execute("nonexistent");
 
-        assertExitCodeAndStreamSizes(exe, 1, 0, 1);
-        Assert.assertEquals("stderr first line", "Unknown command: nonexistent", exe.stderrLines().get(0));
+        assertExitCodeAndStreamSizes(exe, 2, 0, 3);
+        Assert.assertEquals("stderr first line", "Unmatched argument at index 0: 'nonexistent'", exe.stderrLines().get(0));
```
Comment (mabartos) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java:38]: As I mentioned above. There should not be any big effort required to reflect the old error message, right? Or probably print sth like "Unknown argument"?

**Review by mabartos — COMMENTED** [review]
@shawkins Great job! In general LGTM.

I've just added a few comments. Most of them are nitpicks, and I don't want to block this PR, but I think a small effort is needed to polish it.

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/NewObjectCmd.java (hunk 3 above)
Comment (shawkins) [reply integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/NewObjectCmd.java:62]: It wasn't ignored, just processed in a different spot. However the help about the new command was not correct.

**Comment by mabartos** [comment]
@shawkins One thing to confirm. AFAIK, end users should not be affected by these changes (except for some minor changes in messages), so we will not need any migration guide or release notes, right?

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCmd.java (hunk 2 above)
Comment (shawkins) [reply integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCmd.java:59]: I'd argue that it doesn't seem worth introducing additional parsing logic for this case since it will be clear from the help what is needed. I think this also may be a case where the default picocli error is probably better than the short one we are producing.

**Comment by shawkins** [comment]
> One thing to confirm. AFAIK, end users should not be affected by these changes (except for some minor changes in messages), so we will not need any migration guide or release notes, right?

Thank you for the review @mabartos  

I am not sure what may need a release not here. The biggest change that could affect users I think would be using exit code 2 instead of 1 to indicate a usage error (which is what kc.sh does).

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java (hunk 5 above)
Comment (shawkins) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java:38]: The full output with this pr is:

```
Unmatched argument at index 0: 'nonexistent'
Try 'kcadm.sh --help' for more information on the available options.
```

kc.sh will print these errors like "Unknown option: 'foo'" if for example you enter ./kc.sh tools foo - that's because the kc.sh short error message isn't making any distinction between an option and an argument, which isn't quite right either.

The default handling would produce:
```
Unmatched argument at index 0: 'nonexistent'
Keycloak - Open Source Identity and Access Management

Find more information at: https://www.keycloak.org/docs/latest
Usage: kcadm.sh [-x] [--help] [COMMAND]

COMMAND [ARGUMENTS]
      --help   Print command specific help
  -x           Print full stack trace when exiting with error
Commands:
  help          This Help
  config        COMMAND [ARGUMENTS]
  new-object    Command to create new JSON objects locally
  create        Command to create new resources
  get           [ARGUMENTS]
  update        CLIENT_ID [ARGUMENTS]
  delete        CLIENT [GLOBAL_OPTIONS]
  add-roles     [ARGUMENTS]
  remove-roles  [ARGUMENTS]
  get-roles     [ARGUMENTS]
  set-password  [ARGUMENTS]
```
Where the error message is color coded red, and the help is color coded to highlight arguments and options.

The logic current logic (or the default) will make suggestions, but nonexistent is not sufficiently like the valid values for that to happen. For example with the default logic, or the overriden exception handling you see:

```
Unmatched argument at index 0: 'creative'
Did you mean: kcadm.sh create or kcadm.sh remove-roles or kcadm.sh update?
```

Then with our override we'll tack on "Try 'kcadm.sh --help' for more information on the available options."

If you want it to omit the index, that can be done. I suppose that is being done because command chaining could cause an argument to appear multiple times.

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/IoUtil.java (hunk 4 above)
Comment (shawkins) [reply integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/IoUtil.java]: Ok, separated the cases.

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCmd.java (hunk 2 above)
Comment (mabartos) [reply integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCmd.java:59]: Ok, works for me.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java (hunk 5 above)
Comment (mabartos) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java:38]: Yep, the index is not very user-friendly, but at least it can provide more info to the user. 

As I've mentioned above, it works for me to keep it as is.

**Comment by mabartos** [comment]
@shawkins Thanks for addressing these comments. 

> I am not sure what may need a release not here. The biggest change that could affect users I think would be using exit code 2 instead of 1 to indicate a usage error (which is what kc.sh does).

I'd opt for providing at least some small release notes + a migration guide, as the CLI provider for KC admin has changed from aesh to picocli, and users may notice some small changes. The exit code might be for some users important, as they can use some custom scripts where they rely on the exit code. Those are only my assumptions, but I think brief notes are better than none :P 

@shawkins Or wdyt? 
@vmuzikar Maybe you could have some input on the docs.

**Review by Pepo48 — DISMISSED** [review]
LGTM. @shawkins thanks for taking care of this. I specifically appreciate that we got rid of all the escaping workarounds within KcAdmMain.

I don't have a strong opinion about adding a release note (I don't see that many occasions where this change could potentially cause an issue).

**Comment by mabartos** [comment]
@Pepo48 Thanks for your feedback. 

I'd still be glad to have some brief notes for the docs (will not be polluted much). We prevent any issues customers may face and provide these changes in a safer manner :))  

@shawkins Could you please squash these commits and sign them?

**Comment by shawkins** [comment]
> Could you please squash these commits and sign them?

Yes, that will happen with the auto-merge once we're ready for that.

File: docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc [hunk 6]
```diff
@@ -61,6 +61,10 @@ The module `org.keycloak:keycloak-model-legacy` module was deprecated in a previ
 
 The old behavior to preload offline sessions at startup is now removed after it has been deprecated in the previous release.
 
+= kcadm Changes
+
+How kcadm parses and handles options and parameters has changed. Error messages from usage errors, the wronge option or parameter, may be slightly different than previous versions. Also usage errors will have an exit code of 2 instead of 1.
```
Comment (mabartos) [inline docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc:66]:
```suggestion
How kcadm parses and handles options and parameters has changed. Error messages from usage errors, the wrong option or parameter, may be slightly different than previous versions. Also usage errors will have an exit code of 2 instead of 1.
```
@shawkins I believe it's a typo, right?

Comment (shawkins) [reply docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc:66]: Correct

**Review by mabartos — APPROVED** [review]
@shawkins Thanks, LGTM!

**Review by vmuzikar — APPROVED** [review]
@shawkins Thanks, nice job! Since @mabartos, @Pepo48 and @pedroigor already reviewed, I did only a high level review and LGTM. From users perspective looks not much has changed so that's what matter most.
