### PR TITLE
Do not store RealmModel in CachedOrganizationIds 

### LINKED ISSUE #33331: Performance drop in cpuUsageForLoginsTest since 19.09.2024
### Describe the bug

A performance decrease is spotted in `cpuUsageForLoginsTest` run since 19.09.2024. 

From the attached screenshot of KCB daily runs statistics  in Horreum, you can see that the value of `userLoginsPerSecPer1vCpuPerPod` has decreased from average 110 to 82.

horreum_perf_decrease_spot

The same you can see on Horreum change detection graph for that metric:

image

I have checked the KCB commits, and the only change that was merged on 18.09 was Healthcheck related changes to github workflow, but there was nothing from my point of view that could harm the performance this way. 

### Version

nightly run

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mhajas**
Closes #33331

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java [hunk 1]
```diff
@@ -338,7 +338,7 @@ protected UserModel validateCache(RealmModel realm, CachedUser cached) {
     protected UserModel cacheUser(RealmModel realm, UserModel delegate, Long revision) {
         int notBefore = getDelegate().getNotBeforeOfUser(realm, delegate);
 
-        if (Profile.isFeatureEnabled(Profile.Feature.ORGANIZATION)) {
+        if (Profile.isFeatureEnabled(Profile.Feature.ORGANIZATION) && realm.isOrganizationsEnabled()) {
```
Comment (pedroigor) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:341]: We can't check it here because the user will be readonly when orgs is disabled and the user is a "managed" user (a user that was created in the context of an org).

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java [hunk 2]
```diff
@@ -28,21 +28,28 @@
...
+    private final String realmId;
+    private final List<String> orgIds;
 
-    public CachedOrganizationIds(Long revision, String id, RealmModel realm, Stream<OrganizationModel> organizations) {
+    public CachedOrganizationIds(Long revision, String id, RealmModel realm, OrganizationModel model) {
         super(revision, id);
-        this.realm = realm;
-        organizations.map(OrganizationModel::getId).forEach(orgIds::add);
+        this.realmId = realm.getId();
+        orgIds = List.of(model.getId());
```
Comment (pedroigor) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java:37]: The reason why it is a set is because we don't want duplicates even though very unlikely to happen. Or is there any other reason to change to a list?

Comment (mhajas) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java:37]: This change was made by @pruivo. He mentioned lists are more effective. We can change to set and then to list to make sure there are not duplicates.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java (hunk 1 above)
Comment (mhajas) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:341]: Hmm, but this method is checking whether the organization itself is disabled, not organizations in general.

It seems this method is not checking realm config, only org config or am I missing something?
https://github.com/keycloak/keycloak/blob/8d314a69a01f0909cc94ebbf5d04ecab8de69674/model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L936-L943

Comment (pedroigor) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:341]: Behind the scenes, the call to `organizationProvider.isEnabled` is checking if org is enabled at the realm level.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java (hunk 2 above)
Comment (pedroigor) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java:38]: No problem. Let's keep as is.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java (hunk 1 above)
Comment (mhajas) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:341]: Ok. Can we then change it something like the following? It would avoid looking members by id if orgProvider is disabled. 
```
private boolean isOrganizationDisabled(KeycloakSession session, UserModel delegate) {
        // check if provider is enabled and user is managed member of a disabled organization OR provider is disabled and user is managed member
        OrganizationProvider organizationProvider = session.getProvider(OrganizationProvider.class);

        if (!organizationProvider.isEnabled()) {
            return true;
        }
 
        return organizationProvider.getByMember(delegate)
                .anyMatch((org) -> (organizationProvider.isEnabled() && org.isManaged(delegate) && !org.isEnabled()) ||
                        (!organizationProvider.isEnabled() && org.isManaged(delegate)));
    }
```

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java (hunk 2 above)
Comment (mhajas) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java:38]: I changed it to convert to set and only then to list to make sure there are no duplicates. @pruivo does it make sense to you?

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java (hunk 1 above)
Comment (pedroigor) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:341]: I don't think so. As I said, if org is disabled (at the realm) and the user is a managed member, we need to return false.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java (hunk 2 above)
Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganizationIds.java:38]: `List` is more memory efficient than `Set`; we are not invoking `contains()` and only iterating. We can use  `distinct()` in the stream if you want to remove duplicates. 
I'm ok to use `Set` if you prefer :+1:

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java (hunk 1 above)
Comment (sguilhen) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:341]: We could at least avoid fetching users to check for memberships if there are no orgs in the realm.. so in addition to checking if the feature is enabled, we could do 
```
OrganizationProvider organizationProvider = session.getProvider(OrganizationProvider.class);
if(Profile.isFeatureEnabled(Profile.Feature.ORGANIZATION) && organizationProvider.count > 0) {
 ....
 }
```

**Review by pedroigor — APPROVED** [review]
