### PR TITLE
Test flaky due to dual certificates

### LINKED ISSUE #41823: Test flaky due to dual certificates
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

This test is flaky:
test\clients\saml.spec.ts:136:3 › Clients SAML tests › should enable Encryption keys config 

The problem is that the test should be expecting two certificates on the page.  The way it is written, the test waits for one certificate.  Sometimes the second certificate has not been rendered yet and the test will pass.  Instead it should be waiting for the second certificate to be rendered.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Test always passes

### Actual behavior

Test sometimes fails

### How to Reproduce?

Run test several times locally

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ssilvert**
Fixes #41823

The problem was that the test should be expecting two certificates on the page. The way it was written, the test waits for one certificate. Sometimes the second certificate has not been rendered yet and the test would erroneously pass.  Instead it should be waiting for the second certificate to be rendered so it is checking the correct assertion.

### CODE REVIEW

File: js/apps/admin-ui/test/clients/saml.ts [hunk 1]
```diff
@@ -81,7 +87,7 @@ export async function clickOffEncryptionAssertions(page: Page) {
 export async function clickGenerate(page: Page) {
   const responsePromise = page.waitForResponse(
     (res) => res.url().includes("/generate") && res.status() === 200,
-    { timeout: 10000 },
+    { timeout: 60000 },
```
Comment (jonkoops) [inline js/apps/admin-ui/test/clients/saml.ts:90]: Perhaps the default of 30 seconds is enough here?
```suggestion
(res) => res.url().includes("/generate") && res.status() === 200,
```

**Review by jonkoops — APPROVED** [review]
LGTM

File: js/apps/admin-ui/test/clients/saml.ts (hunk 1 above)
Comment (ssilvert) [reply js/apps/admin-ui/test/clients/saml.ts:90]: > Perhaps the default of 30 seconds is enough here?

Hard to say.  I just decided better safe than sorry.
