### PR TITLE
Simplifying the CORS SPI and the default implementation

### LINKED ISSUE #27646: Account Console REST API for /linked-accounts Returns Multiple Access-Control-Allow-Origin Headers
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

In version 23.0.7, if I send a GET request to realms/[realm]/account/linked-accounts with Origin set, I get two Access-Control-Allow-Origin in the response.

Example:
GET  realms/[realm]/account/linked-accounts
Authentication: Bearer e...
Origin: http://localhost:4200

In the response I get the following access control headers:
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true

Chrome (and probably other browsers) reject this due to CORS violations:
Access to fetch at 'https://.../realms/[realm]/account/linked-accounts' from origin 'http://localhost:4200' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:4200, http://localhost:4200', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This prevents cross-origin access to the linked-accounts endpoint. This is mostly relevant for local development of the account console theme. But could also effect other users of the account API.

I looked into the code but could not directly find the cause for this. I suspect multiple places colling "addHeader.accept(ACCESS_CONTROL_ALLOW_ORIGIN, origin);" to add the origin.

### Version

23.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

Only one access control header is returned, so that API is callable from a frontend application.

### Actual behavior

Two access control headers are returned.

### How to Reproduce?

Set the Web Origin for the account-console client to http://localhost:4200.
Call the /linked-accounts API with an Origin header set to http://localhost:4200.
Observe two Access-Control-Allow-Origin headers in the response.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #27646

* Make sure CORS headers are only set once as per #27646 and https://fetch.spec.whatwg.org/.
* Removes unnecessary/boilerplate code when building CORS responses
* Creating a CORS response is now about creating a `Cors` instance from the `Cors#builder` method and adding CORS headers by invoking the `Cors#add` to add the headers to the underlying `HttpResponse`. There is no need to pass the `HttpRequest` when creating a `Cors` instance. We probably want to avoid using the `Resteasy` utility class to resolve the session when creating `Cors` instances but I think we can do that in a follow-up.
* Makes more explicit that CORS headers are added to the underlying `HttpResponse` and not the `Response` instance returned from JAX-RS resources. The convenient method to return a `Response` was kept but as a default method in the `Cors` interface.

### CODE REVIEW

File: server-spi-private/src/main/java/org/keycloak/services/cors/Cors.java [hunk 1]
```diff
@@ -36,59 +33,67 @@
...
-    public Cors allowedMethods(String... allowedMethods);
+    Cors exposedHeaders(String... exposedHeaders);
 
-    public Cors exposedHeaders(String... exposedHeaders);
+    /**
+     * Add the CORS headers to the current {@link org.keycloak.http.HttpResponse}.
+     */
+    void add();
 
-    public Cors addExposedHeaders(String... exposedHeaders);
```
Comment (pedroigor) [inline server-spi-private/src/main/java/org/keycloak/services/cors/Cors.java:86]: @rmartinc This is related to #26782 and I'm removing the method here as it is used from a single place. Now the `epxosedHeaders` is doing the same thing and adding additional "exposed" headers. 

The test should pass.

Comment (rmartinc) [reply server-spi-private/src/main/java/org/keycloak/services/cors/Cors.java:86]: @pedroigor Sorry for not answering before. I did exactly the same as you in the previous PR but @mposolda recommended to add the `addExposedHeaders` because it was a change of behavior. You can see Marek's comments in the [PR](https://github.com/keycloak/keycloak/pull/27015). I'm OK with it as I did the same as the first option. :smile:

**Review by stianst — DISMISSED** [review]

**Review by stianst — APPROVED** [review]
