### PR TITLE
Fixes a NullPointerException after import validation

### LINKED ISSUE #20150: NPE after import validation in UserStorageManager::getUserByEmail
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

If an import validation returns null, indicating that the user entity should be removed from local storage, during UserStorageManager::getUserByEmail a NullPointerException is raised due to an email equality check is performed without checking if the returned `UserModel` is null.

### Version

21.1.1

### Expected behavior

To not get a NullPointerException and that the federated user is removed from local storage.

### Actual behavior

A NullPointerException is thrown.

### How to Reproduce?

Add a custom user federation provider that implements `ImportedUserValidation` which always returns null:
```java
public UserModel validate(RealmModel realmModel, UserModel userModel) {
    return null;
}
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by havarnov**
If the import validation (when getting a user by email) returns null, indicating that the user entity should be removed from local storage, an email equality check results in a NullPointerException.

This commit fixes this issue by explicitly checking for null.

Closes #20150

### CODE REVIEW

File: model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java [hunk 1]
```diff
@@ -340,7 +340,7 @@ public UserModel getUserByEmail(RealmModel realm, String email) {
         if (user != null) {
             user = importValidation(realm, user);
             // Case when email was changed directly in the userStorage and doesn't correspond anymore to the email from local DB
-            if (email.equalsIgnoreCase(user.getEmail())) {
+            if (user != null && email.equalsIgnoreCase(user.getEmail())) {
```
Comment (havarnov) [inline model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java:343]: Maybe it would be correct to return `null` here, if `importValidation()` returns `null`?

**Review by mhajas — CHANGES_REQUESTED** [review]
Thank you for the PR @havarnov! Can you please also create some tests for this? I believe the best class to place this is: https://github.com/keycloak/keycloak/blob/main/testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserSyncTest.java

What we need is:
1. Create a user in LDAP
2. Load the user by email (imports user to KC database)
3. Remove the user from LDAP only
4. Assert no exception is thrown and no user was returned

**Comment by martin-kanis** [comment]
@havarnov Thank you for the PR. Will you be able to add the missing test anytime soon? I can offer more guidance if needed.

**Comment by havarnov** [comment]
@martin-kanis sry, I've been busy with other stuff. I'll see if I can make it this week!

I do have one comment I'd like some feedback on, though: https://github.com/keycloak/keycloak/pull/20151/files#r1184988078

**Comment by havarnov** [comment]
I'm having issues running the tests locally. Is there some kind of setup I'm missing maybe?

```
org.junit.AssumptionViolatedException: Some required providers not found: got: <[interface org.keycloak.models.UserProvider, interface org.keycloak.cluster.ClusterProvider, interface org.keycloak.models.RealmProvider, interface org.keycloak.storage.UserStorageProvider]>, expected: an empty collection
```

File: model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java (hunk 1 above)
Comment (mhajas) [reply model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java:343]: Sorry, I missed this question before. I don't think we want to return `null` in that case. If `importValidation` returns `null` it means the user from Keycloak database is invalid and was removed. Returning `null` in that situation would mean we say Keycloak does not know the user by this email, however, this is not true and it can be still present in an external provider. We need to query the user again.

**Comment by mhajas** [comment]
> Is there any dependencies I'm missing, e.g. start a specific container or something?

No, it should work out of the box. It seems you are doing the correct thing. Have you done any changes to the `UserSyncTest` class? If yes, can you push the changes so I can give it a try?

**Comment by havarnov** [comment]
No changes to `UserSyncTest`. I just did a rebase against main, so I get this error on [bugfix/import-validation-null-pointer-bug](https://github.com/havarnov/keycloak/tree/bugfix/import-validation-null-pointer-bug) without any changes.

**Comment by mhajas** [comment]
@havarnov I created a PR for fixing the failing test. You can try whether the code I added works for you:
https://github.com/keycloak/keycloak/pull/22603

**Comment by havarnov** [comment]
@mhajas thanks both the work-around and your PR worked for me :D

**Comment by havarnov** [comment]
@mhajas I've now added a test that fails if the fix is _not_ applied. But, I'm not totally sure why I need the two calls to `UserStorageSyncManager.syncAllUsers()` to get this to work. Shouldn't `LDAPTestUtils.addLDAPUser()` also add the user to the `localStorage`?

File: model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java (hunk 1 above)
Comment (mhajas) [reply model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java:378]: As I wrote, we DO NOT want to return `null` when validation fails, because some provider may still contain the user.

For example:
1. Some provider contains `user1` and it is synced to KC DB
2. The `user1` is changed in that provider (Keycloak DB is not updated). 
3. If we query this user by email, the validation will fail because the user was changed
4. Returning `null` in that case would be wrong because the provider still contains the user. We need to reload the user from the provider (or any other provider knowing user by that email).

**Comment by mhajas** [comment]
@mkrueger92 We probably don't need to do synchronization at all in this test. I updated the test a little bit. Could you please have a look at whether it makes sense?

**Review by mhajas — APPROVED** [review]
Thanks for the contribution @havarnov
