### PR TITLE
Fix json editor scroll behavior

### LINKED ISSUE #36985: Admin console: unable to edit user profile attribute either on the form or the JSON editor.
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Hi,

I go to admin console, select a realm, realm settings, user profile.

Then select first name. 

Uncheck "who can edit/ user" checkbox then hit save. 

Nothing happens. 

Same with other edits.

The browser's js console displays:

> react-dom.production.min.js:10 Th: Table headers must have an accessible name. If the Th is intended to be visually empty, pass in screenReaderText. If the Th contains only non-text, interactive content such as a checkbox or expand toggle, pass in an aria-label.

**Workaround:** Scroll up to the "display name" field and hit the "add translations" icon. Do nothing in the form and hit "cancel".
Then, try again to uncheck "who can edit/ user" checkbox, followed by "save" button. This time it works.

Until I found the workaround, I tried to use the JSON editor. Well, I was unable to use that interface. I could only edit the first part of the visible JSON and when I tried to scroll and edit the firstName and lastName part, my keystrokes did not show any effect on the screen. Unable to put the caret anywhere in the json file. Clicking save shows a message with invalid JSON or something.

### Version

26.1.0

### Regression

- [x] The issue is a regression

### Expected behavior

The "save" button in user profile attribute form should save the modifications on the selected attribute.

### Actual behavior

Clicking "save" on attribute editor does nothing.

Impossible to use the JSON editor form. The editor field simply not works.

### How to Reproduce?

Already written in the bug description paragraph. 

### Anything else?

If any incidence on the bug, the realm has activated localization with several languages.
I'm on Google Chrome.

### PR DESCRIPTION
**Pull request by koplas**
This allows to edit the text that is outside the scroll area.

Closes #36985

### CODE REVIEW

File: js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx [hunk 1]
```diff
@@ -34,15 +34,16 @@ export const ScriptComponent = ({
         defaultValue={defaultValue}
         control={control}
         render={({ field }) => (
-          <CodeEditor
-            id={name!}
-            data-testid={name}
-            readOnly={isDisabled}
-            onChange={field.onChange}
-            value={Array.isArray(field.value) ? field.value[0] : field.value}
-            style={{ height: "600px", overflow: "scroll" }}
```
Comment (edewit) [inline js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx:43]: it already had these styles applied why would this change be needed?

**Review by edewit — COMMENTED** [review]
Seems some of the instances don't have the styles needed, but moving it to a div that surrounds the editor seems like not the right solution tbh

File: js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx (hunk 1 above)
Comment (koplas) [reply js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx:43]: The `div` container is needed to work around these issues: https://github.com/react-simple-code-editor/react-simple-code-editor/issues/63 and https://github.com/react-simple-code-editor/react-simple-code-editor/issues/32. 
I am open for other solutions, but this seems to be the one that works. Without the `div` container the invisible `textarea` won't work after scrolling.

**Review by edewit — APPROVED** [review]
