### PR TITLE
[OID4VCI] Fix deprecated realm-scoped well-known endpoint access

### LINKED ISSUE #44033: [OID4VCI] Fix deprecated realm-scoped well-known endpoint access
### Description

Various oid4vci test cases use a deprecated metadata url 

Related to #41589

### PR DESCRIPTION
**Pull request by tdiesler**
closes #44033

### CODE REVIEW

**Comment by mposolda** [comment]
@tdiesler Thanks for the PR!

I did re-run the tests as it seems those are not related to your updates, but was just flaky test. Hopefully that helps with the test failures.

Also see this comment (as it applies to this PR as well) : https://github.com/keycloak/keycloak/pull/44029#issuecomment-3503478289

**Review by Captain-P-Goldfish — APPROVED** [review]
LGTM

**Review by tnorimat — APPROVED** [review]
LGTM.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java [hunk 1]
```diff
@@ -527,7 +521,11 @@ protected String getBasePath(String realm) {
     }
 
     protected String getRealmPath(String realm) {
-        return suiteContext.getAuthServerInfo().getContextRoot().toString() + "/auth/realms/" + realm;
+        return suiteContext.getAuthServerInfo().getContextRoot() + "/auth/realms/" + realm;
+    }
+
+    protected String getRealmMetadataPath(String realm) {
+        return suiteContext.getAuthServerInfo().getContextRoot() + "/auth/.well-known/openid-credential-issuer/realms/" + realm;
     }
```
Comment (IngridPuppet) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java]: We should agree that this URL is still not fully compliant with the latest requirements to have ".well-known/" even before "/auth". The SIG is aware of the limitation imposed by the current testing infrastructure regarding this issue. Could you add a comment here to report the limitation to future readers?

File: services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialsOffer.java [hunk 2]
```diff
@@ -52,6 +53,18 @@ public CredentialsOffer setCredentialIssuer(String credentialIssuer) {
         return this;
     }
 
+    @Transient
+    public String getIssuerMetadataUrl() {
+        var metadataUrl = credentialIssuer + "/.well-known/openid-credential-issuer";
```
Comment (IngridPuppet) [inline services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialsOffer.java]: - Could we play it safe and use the UriBuilder for building URLs?
- I also suggest we reuse constant `WELL_KNOWN_OPENID_CREDENTIAL_ISSUER`.

**Review by IngridPuppet — COMMENTED** [review]
Hello @tdiesler - Thank you for the cleanup. I checked the PR and left a few minor comments. Please could you check?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java (hunk 1 above)
Comment (tdiesler) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java]: There are many cases like, which I tried to address in #44037
Perhaps we can get that (cosmetic) PR merged first?

File: services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialsOffer.java (hunk 2 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialsOffer.java]: This is also addressed by #44037

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java (hunk 1 above)
Comment (tdiesler) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java]: done

**Review by IngridPuppet — APPROVED** [review]
Thank you for the update. However, did you mean to reference another PR in your response? #44037 loops back to this PR.

**Comment by tdiesler** [comment]
I meant this one - perhaps I got mixed up by similar change requests on a different PR.

**Review by mposolda — APPROVED** [review]
@tdiesler @Captain-P-Goldfish @tnorimat @IngridPuppet Thanks for the updates and for the review of this PR!
