### PR TITLE
fix: mapping mtls enabled to a runtime option

### LINKED ISSUE #47750: cache-embedded-mtls-enabled maps to a build time property, but is a runtime option
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

cache-embedded-mtls-enabled maps to kc.spi-jgroups-mtls--default--enabled which is a build time option for enabling / disabling a provider.

However the option is marked as runtime. This can lead to confusing errors if we make changes to how we expose runtime options to quarkus such as https://github.com/keycloak/keycloak/actions/runs/23953775981/job/69867750818?pr=47748#step:5:1852

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The option looks like it is supposed to be a runtime configuration, so it should not overlap with a build time option.

### Actual behavior

The option is effectively both build time and runtime.

### How to Reproduce?

https://github.com/keycloak/keycloak/actions/runs/23953775981/job/69867750818?pr=47748#step:5:1852

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #47750

We also don't want to advertise spi options that we already have first-class options for.

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/jgroups/certificates/DefaultJGroupsCertificateProviderFactory.java [hunk 1]
```diff
@@ -46,8 +43,11 @@ public class DefaultJGroupsCertificateProviderFactory implements JGroupsCertific
 
     public static final String PROVIDER_ID = "default";
 
-    // config
+    // for metadata compatibility
     public static final String ENABLED = "enabled";
+
+    // config
+    public static final String ACTIVATED = "activated";
```
Comment (vmuzikar) [inline model/infinispan/src/main/java/org/keycloak/jgroups/certificates/DefaultJGroupsCertificateProviderFactory.java:50]: Why we're renaming `spi-jgroups-mtls--default--enabled` to `spi-jgroups-mtls--default--activated`?

Comment (shawkins) [reply model/infinispan/src/main/java/org/keycloak/jgroups/certificates/DefaultJGroupsCertificateProviderFactory.java:50]: --enabled is already reserved for controlling whether the provider is enabled - it should not have been used as a runtime option.

Comment (vmuzikar) [reply model/infinispan/src/main/java/org/keycloak/jgroups/certificates/DefaultJGroupsCertificateProviderFactory.java:50]: Sorry, right, that's the gist of the whole issue – that `-enabled` made it implicitly a build time option. 🙈

**Review by vmuzikar — DISMISSED** [review]
LGTM, thanks.

**Comment by vmuzikar** [comment]
@shawkins Can you please rebase?

**Comment by shawkins** [comment]
> @shawkins Can you please rebase?

Updated.

**Review by ahus1 — COMMENTED** [review]
I'm ok with this change for as much as I understand it. I'll leave it to others to fully approve it due to my lack of knowledge in the Quarkus side of things. 

It definitely makes sense to have this a runtime option, and not a build time option.

**Review by vmuzikar — APPROVED** [review]
