### PR TITLE
Fix tests in CI when running with a proper browser

### LINKED ISSUE #37682: [Keycloak CI] - Cookies Tests
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
2025-02-26 23:47:25  -- [ERROR] Failures: 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.broker.KcOidcBrokerTokenExchangeFederatedTest.testExternalInternalTokenExchangeUsingIssuer
2025-02-26 23:47:25  -- [ERROR]   Run 1: KcOidcBrokerTokenExchangeFederatedTest>KcOidcBrokerTokenExchangeTest.testExternalInternalTokenExchangeUsingIssuer:91->KcOidcBrokerTokenExchangeTest.assertExternalToInternalExchange:151 
2025-02-26 23:47:25  -- Expected: <200>
2025-02-26 23:47:25  --      but: was <400>
2025-02-26 23:47:25  -- [ERROR]   Run 2: KcOidcBrokerTokenExchangeFederatedTest>KcOidcBrokerTokenExchangeTest.testExternalInternalTokenExchangeUsingIssuer:91->KcOidcBrokerTokenExchangeTest.assertExternalToInternalExchange:151 
2025-02-26 23:47:25  -- Expected: <200>
2025-02-26 23:47:25  --      but: was <400>
2025-02-26 23:47:25  -- [ERROR]   Run 3: KcOidcBrokerTokenExchangeFederatedTest>KcOidcBrokerTokenExchangeTest.testExternalInternalTokenExchangeUsingIssuer:91->KcOidcBrokerTokenExchangeTest.assertExternalToInternalExchange:151 
2025-02-26 23:47:25  -- Expected: <200>
2025-02-26 23:47:25  --      but: was <400>
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.broker.KcOidcBrokerTokenExchangeV1Test.testExternalInternalTokenExchangeUsingIssuer
2025-02-26 23:47:25  -- [ERROR]   Run 1: KcOidcBrokerTokenExchangeV1Test>KcOidcBrokerTokenExchangeTest.testExternalInternalTokenExchangeUsingIssuer:91->KcOidcBrokerTokenExchangeTest.assertExternalToInternalExchange:151 
2025-02-26 23:47:25  -- Expected: <200>
2025-02-26 23:47:25  --      but: was <400>
2025-02-26 23:47:25  -- [ERROR]   Run 2: KcOidcBrokerTokenExchangeV1Test>KcOidcBrokerTokenExchangeTest.testExternalInternalTokenExchangeUsingIssuer:91->KcOidcBrokerTokenExchangeTest.assertExternalToInternalExchange:151 
2025-02-26 23:47:25  -- Expected: <200>
2025-02-26 23:47:25  --      but: was <400>
2025-02-26 23:47:25  -- [ERROR]   Run 3: KcOidcBrokerTokenExchangeV1Test>KcOidcBrokerTokenExchangeTest.testExternalInternalTokenExchangeUsingIssuer:91->KcOidcBrokerTokenExchangeTest.assertExternalToInternalExchange:151 
2025-02-26 23:47:25  -- Expected: <200>
2025-02-26 23:47:25  --      but: was <400>
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.organization.broker.OrganizationOIDCBrokerSelfRegistrationTest.testRememberOrganizationWhenReloadingLoginPage
2025-02-26 23:47:25  -- [ERROR]   Run 1: OrganizationOIDCBrokerSelfRegistrationTest>AbstractBrokerSelfRegistrationTest.testRememberOrganizationWhenReloadingLoginPage:748
2025-02-26 23:47:25  -- [ERROR]   Run 2: OrganizationOIDCBrokerSelfRegistrationTest>AbstractBrokerSelfRegistrationTest.testRememberOrganizationWhenReloadingLoginPage:748
2025-02-26 23:47:25  -- [ERROR]   Run 3: OrganizationOIDCBrokerSelfRegistrationTest>AbstractBrokerSelfRegistrationTest.testRememberOrganizationWhenReloadingLoginPage:748
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.organization.broker.OrganizationSAMLBrokerSelfRegistrationTest.testRememberOrganizationWhenReloadingLoginPage
2025-02-26 23:47:25  -- [ERROR]   Run 1: OrganizationSAMLBrokerSelfRegistrationTest>AbstractBrokerSelfRegistrationTest.testRememberOrganizationWhenReloadingLoginPage:748
2025-02-26 23:47:25  -- [ERROR]   Run 2: OrganizationSAMLBrokerSelfRegistrationTest>AbstractBrokerSelfRegistrationTest.testRememberOrganizationWhenReloadingLoginPage:748
2025-02-26 23:47:25  -- [ERROR]   Run 3: OrganizationSAMLBrokerSelfRegistrationTest>AbstractBrokerSelfRegistrationTest.testRememberOrganizationWhenReloadingLoginPage:748
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] Errors: 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.broker.KcOidcBrokerTransientSessionsTest.offlineTokenBrowserFlow
2025-02-26 23:47:25  -- [ERROR]   Run 1: KcOidcBrokerTransientSessionsTest.offlineTokenBrowserFlow:604->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [ERROR]   Run 2: KcOidcBrokerTransientSessionsTest.offlineTokenBrowserFlow:604->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [ERROR]   Run 3: KcOidcBrokerTransientSessionsTest.offlineTokenBrowserFlow:604->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.broker.KcOidcBrokerTransientSessionsTest.testSingleSignOn
2025-02-26 23:47:25  -- [ERROR]   Run 1: KcOidcBrokerTransientSessionsTest.testSingleSignOn:476->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [ERROR]   Run 2: KcOidcBrokerTransientSessionsTest.testSingleSignOn:476->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [ERROR]   Run 3: KcOidcBrokerTransientSessionsTest.testSingleSignOn:476->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.broker.KcOidcBrokerTransientSessionsTest.testUserInfoEndpoint
2025-02-26 23:47:25  -- [ERROR]   Run 1: KcOidcBrokerTransientSessionsTest.testUserInfoEndpoint:553->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [ERROR]   Run 2: KcOidcBrokerTransientSessionsTest.testUserInfoEndpoint:553->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [ERROR]   Run 3: KcOidcBrokerTransientSessionsTest.testUserInfoEndpoint:553->loginWithBrokerUsingOAuthClient:579 » IllegalArgument Keys to send should be a not null CharSequence
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.broker.OidcClaimToUserSessionNoteMapperTest.claimIsNotPropagatedWhenNameDoesNotMatch
2025-02-26 23:47:25  -- [ERROR]   Run 1: OidcClaimToUserSessionNoteMapperTest.claimIsNotPropagatedWhenNameDoesNotMatch:129->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
2025-02-26 23:47:25  -- [ERROR]   Run 2: OidcClaimToUserSessionNoteMapperTest.claimIsNotPropagatedWhenNameDoesNotMatch:129->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
2025-02-26 23:47:25  -- [ERROR]   Run 3: OidcClaimToUserSessionNoteMapperTest.claimIsNotPropagatedWhenNameDoesNotMatch:129->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.broker.OidcClaimToUserSessionNoteMapperTest.claimIsPropagatedOnAllLoginsWhenNameMatchesAndSyncModeIsForce
2025-02-26 23:47:25  -- [ERROR]   Run 1: OidcClaimToUserSessionNoteMapperTest.claimIsPropagatedOnAllLoginsWhenNameMatchesAndSyncModeIsForce:110->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
2025-02-26 23:47:25  -- [ERROR]   Run 2: OidcClaimToUserSessionNoteMapperTest.claimIsPropagatedOnAllLoginsWhenNameMatchesAndSyncModeIsForce:110->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
2025-02-26 23:47:25  -- [ERROR]   Run 3: OidcClaimToUserSessionNoteMapperTest.claimIsPropagatedOnAllLoginsWhenNameMatchesAndSyncModeIsForce:110->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
2025-02-26 23:47:25  -- [INFO] 
2025-02-26 23:47:25  -- [ERROR] org.keycloak.testsuite.broker.OidcClaimToUserSessionNoteMapperTest.claimIsPropagatedOnFirstLoginOnlyWhenNameMatchesAndSyncModeIsImport
2025-02-26 23:47:25  -- [ERROR]   Run 1: OidcClaimToUserSessionNoteMapperTest.claimIsPropagatedOnFirstLoginOnlyWhenNameMatchesAndSyncModeIsImport:93->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
2025-02-26 23:47:25  -- [ERROR]   Run 2: OidcClaimToUserSessionNoteMapperTest.claimIsPropagatedOnFirstLoginOnlyWhenNameMatchesAndSyncModeIsImport:93->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
2025-02-26 23:47:25  -- [ERROR]   Run 3: OidcClaimToUserSessionNoteMapperTest.claimIsPropagatedOnFirstLoginOnlyWhenNameMatchesAndSyncModeIsImport:93->login:144 » NullPointer Cannot invoke "java.util.Map.get(Object)" because "this.params" is null
```

https://keycloak-jenkins/view/Keycloak/job/keycloak-continuous-testing/160/execution/node/777/log/

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes #37682

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java [hunk 1]
```diff
@@ -785,9 +785,9 @@ public void testRememberOrganizationWhenReloadingLoginPage() {
         assertFalse(loginPage.isSocialButtonPresent(realmIdp.getAlias()));
 
         driver.navigate().back();
-        // only org idp, back button won't reset the flow and the organization is the same
```
Comment (martin-kanis) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java:788]: @pedroigor why clicking back should not return us back and restart the flow? It is the case in firefox and chrome web drivers, only htmlUnit doing weird things here.

**Review by sguilhen — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]
