### PR TITLE
Fix test LDAP connection with multiple ldap connection urls (#31267)

### LINKED ISSUE #31267: multiple ldap url's not working on one realm
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I have a realm where I connect to one ldap instance. There, I configured to url's for redundancy.
The thing is that whenever I test the connection, it gives me this error on gui:

Screenshot 2024-07-13 at 07 33 56

Individually, both url's work fine.
I see nothing at all on the logs.
When I save it, I can still search users. But if the first url is down, it doesn't retrieve users using the second url

In a brand new realm, I can do this normally, and I got no error whatsoever. So something might be broken underneath.

### Version

25.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

Get a successful test connection when using multiple ldap url's.
Getting redundancy by setting up two url's.

### Actual behavior

I get an error when testing two otherwise working ldap urls when configuring ldap user storage to use them.
I don't get the second url to work. When the first url is down, no search is made on the second.

### How to Reproduce?

I don't know. I can't reproduce this on another realm.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thomasdarimont**
Previously, the given connection string was check with URI.create(..) which failed when multiple space separated LDAP URLs were given.

Fixes #31267

### CODE REVIEW

File: federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java [hunk 1]
```diff
@@ -94,6 +95,29 @@ public static LDAPConfig buildLDAPConfig(TestLdapConnectionRepresentation config
...
+     * @param ldapConfig
+     * @return
+     * @throws ModelValidationException if an invalid URL is provided
+     */
+    private static boolean checkLdapConnectionUrl(TestLdapConnectionRepresentation config, LDAPConfig ldapConfig) {
+        // There could be multiple connection URIs separated via spaces.
+        String[] configConnectionUrls = config.getConnectionUrl().split(" ");
+        String[] ldapConfigConnectionUrls = ldapConfig.getConnectionUrl().split(" ");
+        if (configConnectionUrls.length != ldapConfigConnectionUrls.length) {
+            throw new ModelValidationException("invalid ldap url");
```
Comment (jonkoops) [inline federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java:112]: Perhaps a little more information can be provided here as to why this URL is invalid?

File: federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java [hunk 2]
```diff
@@ -94,6 +95,29 @@ public static LDAPConfig buildLDAPConfig(TestLdapConnectionRepresentation config
...
+     * See: https://docs.oracle.com/javase/jndi/tutorial/ldap/misc/url.html
+     * @param config
+     * @param ldapConfig
+     * @return
+     * @throws ModelValidationException if an invalid URL is provided
+     */
+    private static boolean checkLdapConnectionUrl(TestLdapConnectionRepresentation config, LDAPConfig ldapConfig) {
+        // There could be multiple connection URIs separated via spaces.
+        String[] configConnectionUrls = config.getConnectionUrl().split(" ");
+        String[] ldapConfigConnectionUrls = ldapConfig.getConnectionUrl().split(" ");
```
Comment (jonkoops) [inline federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java:110]: Might be worth it to trim off any leading and trailing white-space before splitting this, WDYT?
```suggestion
        String[] configConnectionUrls = config.getConnectionUrl().trim().split(" ");
        String[] ldapConfigConnectionUrls = ldapConfig.getConnectionUrl().trim().split(" ");
```

**Review by jonkoops — DISMISSED** [review]
LGTM, just some optional feedback

**Comment by thomasdarimont** [comment]
With the changes, we can now test ldap connections with space separated LDAP server urls.
image

**Review by jonkoops — DISMISSED** [review]
LGTM. @thomasdarimont would it be possible to write a test to cover this? Looks like we already have a `UserFederationLdapConnectionTest` test that might bbe extendable.

**Comment by thomasdarimont** [comment]
For some reason the existing tests in `org.keycloak.testsuite.admin.UserFederationLdapConnectionTest#testLdapConnections` don't trigger the issue but I can clearly reproduce it through the UI.

**Comment by thomasdarimont** [comment]
@jonkoops added additional test. The issue was that the problem only occured when the testLDAPConnection was used in combination with a stored LDAP federation provider model.

**Comment by ahus1** [comment]
@rmartinc - could you please review as well? Thanks!

File: federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java [hunk 3]
```diff
@@ -94,6 +95,29 @@ public static LDAPConfig buildLDAPConfig(TestLdapConnectionRepresentation config
...
+     * @param ldapConfig
+     * @return
+     * @throws ModelValidationException if an invalid URL is provided
+     */
+    private static boolean checkLdapConnectionUrl(TestLdapConnectionRepresentation config, LDAPConfig ldapConfig) {
+        // There could be multiple connection URIs separated via spaces.
+        String[] configConnectionUrls = config.getConnectionUrl().trim().split(" ");
+        String[] ldapConfigConnectionUrls = ldapConfig.getConnectionUrl().trim().split(" ");
+        if (configConnectionUrls.length != ldapConfigConnectionUrls.length) {
+            throw new ModelValidationException("LDAP Connection URL mismatch. Number of provided URLs does not match stored URLs.");
```
Comment (rmartinc) [inline federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java:112]: Why don't return `false` instead of the exception?

**Review by rmartinc — CHANGES_REQUESTED** [review]
Just a minor change, I think you just need to return `false` and not throw an exception following the same idea. And thanks for the PR!

File: federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java (hunk 3 above)
Comment (thomasdarimont) [reply federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java]: I'm fine with either. I just checked the code to return false instead of throwing an exception.

**Comment by thomasdarimont** [comment]
thanks for the review @rmartinc ! I adapted the code accordingly.

**Review by rmartinc — APPROVED** [review]
Thanks @thomasdarimont!

**Review by ahus1 — APPROVED** [review]
Approving based on @rmartinc's review.

**Comment by nodje** [comment]
Maybe not the right place, but:

there should be a minimal documentation on this.
I couldn't find anything in the doc about it. 

I was actually configuring multiple LDAP provider to implement failover.
Since stumbling upon this issue, I realize I have to use one unique provider and fill in multiple LDAP URLs.
Hovering over ? icon on Connection URL disaplys only `Connection URL to your LDAP server` even in KC 26.3.4

Only https://www.keycloak.org/docs/latest/server_admin/index.html#dealing-with-provider-failures makes clear that mulitple provider conf isn't going to failover, but doesn't say multiple URL for a provider is possible.

**Comment by nodje** [comment]
Food for thoughts:

This is how it's implemented in LDAP itself:

```
          **uri "ldap://host/ ldap://backup-host/"**

          The URI list is space- or comma-separated.  Whenever the server that responds is not the first one in the list, the list is rearranged and the responsive server  is  moved to the head, so that it will be first contacted the next time a connection needs to be created.
```
That seems clever to me, is it how it works in KC when multiple URLs are provided?

**Comment by jonkoops** [comment]
@nodje comments left here are likely to fall on deaf ears, I would recommend logging a new issue referencing this one.

**Comment by nodje** [comment]
thx, will do
