### PR TITLE
Fix for Log handler specific log levels support only lower-case levels

### LINKED ISSUE #34817: Log handler specific log levels support only lower-case levels
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Log handler specific log levels support only lower-case levels (`info` for example), while the global level supports upper case (INFO or info).

This is a bit confusing as the syntax differs between the two, and also the [documented log levels](https://www.keycloak.org/server/logging#_log_levels) are all in upper case.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Both `--log-syslog-level=INFO` and `--log-syslog-level=info` should work just like for `--log-level`.

### Actual behavior

The following error message is displayed:
```
Invalid value for option '--log-syslog-level': INFO. Expected values are: off, fatal, error, warn, info, debug, trace, all
```

### How to Reproduce?

`kc.sh start-dev --log-syslog-level=INFO`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaustubh-rh**
Closes https://github.com/keycloak/keycloak/issues/34817

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java [hunk 1]
```diff
@@ -525,6 +525,9 @@ public static boolean isEnvOption(ConfigValue configValue) {
     }
 
     void validateExpectedValues(ConfigValue configValue, String v) {
+        if (configValue.getName().equals("kc.log-syslog-level")) {
```
[the remark this answers is not in the document]
Comment (kaustubh-rh) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:528]: @shawkins  thanks for the update, will add the suggested changes.

[the remark this answers is not in the document]
Comment (kaustubh-rh) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java]: Hi @shawkins , thanks added the same to LOG_FILE_LEVEL and LOG_CONSOLE_LEVEL

[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java]: Thanks, but you'll have to use a new method as validateLogLevel allows values that should not be accepted for these currently.

[the remark this answers is not in the document]
Comment (kaustubh-rh) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java]: @shawkins , did the changes .

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java [hunk 2]
```diff
@@ -192,6 +197,15 @@ private static void setCategoryLevel(String category, String level) {
 
     record CategoryLevel(String category, String levelName) {}
 
+    private static void validateLogParameters(String level) {
+        try {
+            toLevel(level);
+        } catch (IllegalArgumentException iae) {
+            throw new PropertyException(
+                    String.format("Invalid parameter: %s", level));
```
Comment (shawkins) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java:205]: This is not descriptive enough. It should mimic the previous error message and possibly mention the level is not case-sensitive.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java]: Thank you, added another comment.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java (hunk 2 above)
Comment (kaustubh-rh) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java:205]: Hi @shawkins ,yes, but in the function validateLogParameters , we are unable to get the option paramas like `--log-console-level` . Also, do you want me to hardcode these options `off, fatal, error, warn, info, debug, trace, all` ?

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java:205]: > we are unable to get the option params like --log-console-level

That is accessible via addValidator - but since that is additive, you'd first have to call validator with something that does nothing. Alternatively, you can have a method that returns a function:

```
private static Consumer<String> validateLogParameters(String param, String level) {
   ...
```

> Also, do you want me to hardcode these options

No, use Stream.of(Level.values()).collect(Collectors.joining(", "))

Comment (kaustubh-rh) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java]: Hi @shawkins , yes I have implemented the suggested changes, thanks !

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java [hunk 3]
```diff
@@ -192,6 +199,15 @@ private static void setCategoryLevel(String category, String level) {
 
     record CategoryLevel(String category, String levelName) {}
 
+    private static void validateLogParameters(Option<LoggingOptions.Level> option, String level) {
+        try {
+            toLevel(level);
+        } catch (IllegalArgumentException iae) {
+            String expectedValues = Stream.of(option.getExpectedValues()).map(Object::toString).collect(Collectors.joining(", ")).replace("[","").replace("]","");
```
Comment (shawkins) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java:206]: One final thought - we could create PropertyMapper.validateExpectedValues could be refactored so that a common method supports both the default validation and this one:

```
void validateExpectedValues(ConfigValue configValue, String v, Predicate<String> test)
```

Where the default test is "!expectedValues.isEmpty() && !expectedValues.contains(v) && getOption().isStrictExpectedValues()"

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java:206]: To elaborate, on PropertyMappers this would look like:

```
    void validateExpectedValues(ConfigValue configValue, String v) {
        if (getOption().isStrictExpectedValues()) {
            validateExpectedValues(configValue, v, (expectedValues) -> !expectedValues.isEmpty() && expectedValues.contains(v));
        }
    }

    void validateExpectedValues(ConfigValue configValue, String v, Function<Collection<String>, Boolean> test) {
        List<String> expectedValues = getExpectedValues();
        if (test.apply(expectedValues)) {
            throw new PropertyException(
                    String.format("Invalid value for option %s: %s.%s", getOptionAndSourceMessage(configValue), v,
                            ShortErrorMessageHandler.getExpectedValuesMessage(expectedValues)));
        }
    }
```

Then you would call it on the logging proeprty mappers:

```
                fromOption(LoggingOptions.LOG_SYSLOG_LEVEL)
                        .isEnabled(LoggingPropertyMappers::isSyslogEnabled, SYSLOG_ENABLED_MSG)
                        .validator(ignored -> {})
                        .addValidator((mapper, configValue) -> mapper.validateExpectedValues(configValue,
                                configValue.getValue(),
                                (expectedValues) -> expectedValues.contains(configValue.getValue().toLowerCase())))
```

That will make the exception handling logic the same.

The other possiblities here are:
- declaratively mark the option as case-insensitive, so that the validateExpectedValues does the lower-casing automatically (similar to the isStrictExpectedValues check) and we don't have to directly mess with the validators on the logging property mappers.
- add another builder validator method so we don't need to call both validator and addValidator

Comment (kaustubh-rh) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java]: Hi @shawkins , I tried to incorporate the changes (Updated the PR) . The build is successful but i still get `ERROR: The LogManager accessed before the "java.util.logging.manager" system property was set to "org.jboss.logmanager.LogManager". Results may be unexpected.`
Screenshot 2024-11-13 at 7 43 57 PM

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java]: That error likely indicates an uncaught exception that is trigger some logging at another point in the code. You'll have to debug to see what is happening.

**Comment by shawkins** [comment]
Should be ready for review.

**Comment by kaustubh-rh** [comment]
hi @mabartos @shawkins , it looks like we passed all the test cases :)

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 4]
```diff
@@ -788,7 +788,8 @@ private static String getDecoratedOptionDescription(PropertyMapper<?> mapper) {
             }).toList();
 
             var isStrictExpectedValues = mapper.getOption().isStrictExpectedValues();
-            var printableValues = String.join(", ", decoratedExpectedValues) + (!isStrictExpectedValues ? ", or a custom one" : "");
+            var isCaseSensitiveExpectedValues = mapper.getOption().isCaseInsensitiveExpectedValues();
+            var printableValues = String.join(", ", decoratedExpectedValues) + (!isStrictExpectedValues ? ", or a custom one" : (isCaseSensitiveExpectedValues ? " (case insensitive)" : ""));
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:792]: IMO, case sensitivity should not be associated with the strictness of expected values. It means when we allow specifying some custom values, we can also say whether we accept case-insensitive values.

I would rather add the info about case sensitivity before the list of expected values. See a suggestion below.

cc @shawkins

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 5]
```diff
@@ -788,7 +788,8 @@ private static String getDecoratedOptionDescription(PropertyMapper<?> mapper) {
...
 
             transformedDesc.append(String.format(" Possible values are: %s.", printableValues));
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:794]:
```suggestion
            transformedDesc.append(String.format(" Possible values are%s: %s.",
                    isCaseInsensitiveExpectedValues ? " (case insensitive)" : "",
                    printableValues)
            );
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 6]
```diff
@@ -788,7 +788,8 @@ private static String getDecoratedOptionDescription(PropertyMapper<?> mapper) {
             }).toList();
 
             var isStrictExpectedValues = mapper.getOption().isStrictExpectedValues();
-            var printableValues = String.join(", ", decoratedExpectedValues) + (!isStrictExpectedValues ? ", or a custom one" : "");
+            var isCaseSensitiveExpectedValues = mapper.getOption().isCaseInsensitiveExpectedValues();
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:791]:
```suggestion
            var isCaseInsensitiveExpectedValues = mapper.getOption().isCaseInsensitiveExpectedValues();
```

**Review by mabartos — COMMENTED** [review]
@kaustubh-rh Thanks for this PR!

I've just added some comments below, please check them (cc @shawkins ).

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 7]
```diff
@@ -788,9 +788,13 @@ private static String getDecoratedOptionDescription(PropertyMapper<?> mapper) {
             }).toList();
 
             var isStrictExpectedValues = mapper.getOption().isStrictExpectedValues();
-            var printableValues = String.join(", ", decoratedExpectedValues) + (!isStrictExpectedValues ? ", or a custom one" : "");
+            var isCaseInsensitiveExpectedValues = mapper.getOption().isCaseInsensitiveExpectedValues();
+            var printableValues = String.join(", ", decoratedExpectedValues) + (!isStrictExpectedValues ? ", or a custom one" : (isCaseSensitiveExpectedValues ? " (case insensitive)" : ""));
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:792]:
```suggestion
            var printableValues = String.join(", ", decoratedExpectedValues) + (!isStrictExpectedValues ? ", or a custom one" : "");
```
@shawkins I think this should be removed as well.

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:792]: See the latest changes. The reason I initially went with appending case sensitive is because it adds complexity to the short error message. Things are aligned now, but we'll have even more code to handle this situation.

**Review by mabartos — APPROVED** [review]
LGTM
