### PR TITLE
Fix "Duplicate" group function

### LINKED ISSUE #46775: "Duplicate" function does not work correctly for organization groups
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

Several issues with duplicating organization groups:
  - Members are copied using the realm group API (`users.addToGroup`) instead of the organization group API, causing failures
  - Role mappings and permissions are copied even though organization groups do not support them
  - The user-entered name for the duplicate is ignored — the duplicate always uses "Copy of {original name}"
  - Server returns 500 because the `addSubGroup` endpoint in `OrganizationGroupResource` does not set the `Location` header on 201 responses

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

see description

### Actual behavior

see description

### How to Reproduce?

see description

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vramik**
Closes #46775

Org groups does not support role mapping as well as FGAP. Therefore when duplicating an org group it should be skipped.

### CODE REVIEW

File: js/apps/admin-ui/src/groups/GroupsModal.tsx [hunk 1]
```diff
@@ -231,7 +244,12 @@ export const GroupsModal = ({
 
     try {
       if (duplicateId && duplicateGroupDetails) {
-        await duplicateGroup(duplicateGroupDetails);
+        await duplicateGroup(
+          duplicateGroupDetails,
+          undefined,
+          false,
+          group.name,
```
Comment (edewit) [inline js/apps/admin-ui/src/groups/GroupsModal.tsx]: this is not necessary, because this are the defaults

**Review by pedroigor — APPROVED** [review]
@edewit I'm assuming @vramik applied your suggestions. Thanks.
