### PR TITLE
fix: fully sanitizing mappers and changing duplicated log to trace

### LINKED ISSUE #38438: Avoid 'duplicated mappers' message
### Description

After upgrading KC 22.0.5 to 26.1.4 we see suspucious DEBUG messages during boot

```
2025-03-26 13:02:16,675 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
2025-03-26 13:02:16,678 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
2025-03-26 13:02:16,679 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
2025-03-26 13:02:16,680 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
2025-03-26 13:02:16,682 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
```

Check if possible to avoid them

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
Scaled back replacement for #41886 - it turns out that I need these changes first to further refine picocli performance.

closes: #38438

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java [hunk 1]
```diff
@@ -52,10 +52,12 @@ public List<PropertyMapper<?>> getPropertyMappers() {
                 fromOption(ExportOptions.FILE)
                         .to("kc.spi-export--single-file--file")
                         .paramLabel("file")
+                        .isEnabled(c -> c instanceof Export)
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java:55]: So, when there's some duplication, we'd need to explicitly enable/disable the mapper, right? 

Why we should remove the check of the `command.getOptionCategories()`? It was quite nice approach(idea) on how to eliminate the mapper from "denied" category - so, no explicit check of the command. 

Would it be possible to have it checked based on the used optionCategories? And if there are some duplicated mappers in 2 or more categories, require to add some explicit check. 

I could imagine even have the default value for the `isEnabled` the check of the comman categories. So, every mapper with the associated option in the denied category would be disabled. 

@shawkins WDYT?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java [hunk 2]
```diff
@@ -152,26 +150,22 @@ public static String maskValue(String value, String configSourceName, PropertyMa
...
         final var mappers = new ArrayList<>(MAPPERS.getOrDefault(property, Collections.emptyList()));
         if (category != null) {
             mappers.removeIf(m -> !m.getCategory().equals(category));
         }
 
         return switch (mappers.size()) {
-            case 0 -> defaultMapper;
+            case 0 -> null;
             case 1 -> mappers.get(0);
             default -> {
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java:162]: So, is it now even possible that we find 1+ mapper here? 

Is it related to the help-all?

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java [hunk 3]
```diff
@@ -106,13 +106,6 @@ void testHttpEnabled(CLIResult cliResult) {
         cliResult.assertStarted();
     }
 
-    @DryRun
-    @Test
-    @Launch({ "-v", "start", "--db=dev-mem", OPTIMIZED_BUILD_OPTION_LONG})
-    void failBuildPropertyNotAvailable(CLIResult cliResult) {
-        cliResult.assertError("Build time option: '--db' not usable with pre-built image and --optimized");
```
Comment (mabartos) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java:113]: It still should be valid, right?

**Review by mabartos — COMMENTED** [review]
@shawkins Thanks for the PR! Just a few comments.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java (hunk 3 above)
Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java:113]: It is redundant with other tests.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java:162]: Before sanitizing it is still possible to have more than 1. However there was no usage of the default concept, so that was removed.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java:55]: > So, when there's some duplication, we'd need to explicitly enable/disable the mapper, right?

Yes. The import / export property mappers are really a pretty special case. They overlap and are valid only for their respective commands. Honestly I'm not sure we even want someone putting file=... into the keycloak.conf as it's not clear that should represent both the import and export location. We've also talked about having the keycloak.conf more easily scoped per command, but that's an even bigger change.

> Why we should remove the check of the command.getOptionCategories()? It was quite nice approach(idea) on how to eliminate the mapper from "denied" category - so, no explicit check of the command.

I would like to further refine the option categories handling in other prs. The problem is that it's not a great abstraction - it is ultimiately about hidding options and it's behavior can be different between build and runtime options.

Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java:55]: > Yes. The import / export property mappers are really a pretty special case. They overlap and are valid only for their respective commands. Honestly I'm not sure we even want someone putting file=... into the keycloak.conf as it's not clear that should represent both the import and export location. We've also talked about having the keycloak.conf more easily scoped per command, but that's an even bigger change.

@shawkins In the context of CLI and putting the command with the `--file`, the scenario is nice as you don't have to specify sth like `--import-file`, or `--export-file`. However, yes, totally unusable in the keycloak.conf as having the `file=` there. 

> I would like to further refine the option categories handling in other prs. The problem is that it's not a great abstraction - it is ultimiately about hidding options and it's behavior can be different between build and runtime options.

Ok, works to me.

**Review by mabartos — COMMENTED** [review]
@shawkins Sorry for the late response. 

LGTM in general.

It'd be good if you could rebase this to comply with the spotless checks.

**Review by mabartos — APPROVED** [review]
