### PR TITLE
Persist kid for java keystore key providers

### LINKED ISSUE #47495: JavaKeystoreKeyProvider generates a new random KID for symmetric keys (HMAC) on every restart or config change
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

When using the java-keystore provider with symmetric keys (e.g., HS512, HS256), the KID (Key ID) is not stable. If the Keycloak server restarts or the java key provider config changes, the provider generates a new random KID.

In JavaKeystoreKeyProvider.java, the createKeyWrapper method initializes the KeyWrapper:
`keyWrapper.setKid(model.get(Attributes.KID_KEY, KeycloakModelUtils.generateId()));`

The logic checks if Attributes.KID_KEY exists in the component model. For symmetric key keystore configurations, this attribute is not persisted or explicitly set during the initial setup of the java-keystore provider. ConsequentlykeyWrapper.setKid(model.get(Attributes.KID_KEY, KeycloakModelUtils.generateId()));, it falls back to KeycloakModelUtils.generateId(), which creates a new UUID every time the provider is instantiated.

This causes all previously issued tokens signed with that secret to fail validation, as the ServerMacSignatureVerifierContext cannot find a matching KID in the current realm keys.

### Version

26.4.7 but it also same in latest version

### Regression

- [ ] The issue is a regression

### Expected behavior

The KID should be stable. It should ideally be derived from the alias name in the keystore or be persisted in the component configuration (KID_KEY attribute) upon the first load so that it remains identical across server restarts.

### Actual behavior

A new random KID is generated on every provider initialization, breaking token transition and validation.

### How to Reproduce?

- Create a Java Keystore (JKS) containing a SecretKey (for HS512).
- In Keycloak, go to Realm Settings -> Keys -> Providers.
- Add a java-keystore provider pointing to your JKS.
- Observe the KID of the HS512 key in the Active keys tab.
- Restart the Keycloak server or update the java-keystore provider configuration.
- Observe the KID again. It will have changed.
- Any tokens issued before the restart will now result in a VerificationException: Key not found during validation.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #47495

### CODE REVIEW

File: tests/base/src/test/java/org/keycloak/tests/keys/JavaKeystoreKeyProviderTest.java [hunk 1]
```diff
@@ -151,6 +154,29 @@ public void createHMAC() throws Exception {
         createSuccess(cryptoHelper.isFips() ? KeystoreUtil.KeystoreFormat.BCFKS : KeystoreUtil.KeystoreFormat.PKCS12, AlgorithmType.HMAC, Algorithm.HS256, true);
     }
 
+    @Test
+    public void testKidDoesNotChangeOnComponentUpdate() throws Exception {
+        KeystoreUtil.KeystoreFormat keystoreType = cryptoHelper.keystore().getPreferredKeystoreType();
```
Comment (rmartinc) [inline tests/base/src/test/java/org/keycloak/tests/keys/JavaKeystoreKeyProviderTest.java]: @pedroigor The FIPS execution is failing, I remember there was a problem storing HMAC in bc-fips. Try doing as it is done in the previous method:

```java
KeystoreUtil.KeystoreFormat keystoreType = cryptoHelper.isFips() ? KeystoreUtil.KeystoreFormat.BCFKS : KeystoreUtil.KeystoreFormat.PKCS12
```

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @pedroigor! LGTM, but the test is failing in FIPS, I remember there were limitations between fips, non-fips and store types. So try doing as the `createHMAC` method is doing.

File: tests/base/src/test/java/org/keycloak/tests/keys/JavaKeystoreKeyProviderTest.java (hunk 1 above)
Comment (pedroigor) [reply tests/base/src/test/java/org/keycloak/tests/keys/JavaKeystoreKeyProviderTest.java]: Thanks, @rmartinc. Applied your suggestion, and it is passing locally. Let us check CI ...

**Review by rmartinc — APPROVED** [review]
Thanks @pedroigor!

**Review by ahus1 — APPROVED** [review]
