### PR TITLE
removed need to query all groups

### LINKED ISSUE #20489: Admin UI - unable to load user's groups when large number of groups defined for the realm
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I have a Keycloak instance with ~18k defined groups in flat structure - every group on the same root level.  
When I go to security admin console (admin UI) -> Users -> select sample user and go to "Groups" tab, only "loading" circle is displayed and no groups at all.  

image

Looking at network requests - I can see two requests:  
image

1. https://mydomain/auth/admin/realms/myrealm/users/12345679/groups?first=0&max=11
2. https://mydomain/auth/admin/realms/myrealm/groups

The second requests takes "forever" to complete (~5 minutes in my case), seems to be performance problem with getting all realm groups. Anyway this request seems to be pointless because "Groups" tab displays only first 10 groups by default and results are paginated.

### Version

21.1.1

### Expected behavior

User's groups in admin UI should be displayed in acceptable time, independently from groups count for whole realm.
Probably: API request to get all realm groups should not be executed on User's groups tab.

### Actual behavior

User's groups in Admin UI are not displayed, because UI calls API to get all realm's groups. Request finished after ~5 minutes when there are ~18k groups defined.

### How to Reproduce?

Fill any Keycloak instance (version 21.1.1) with 18k groups on root level (optional).
Go to security admin console -> Users -> select any user and go to "Groups" tab. Open browser's developer tools (F12) and open Network tab. Refresh page, you'll see there are two requests for user's group: one with max=11 parameter, and second request getting all realm groups.
When you have ~18k groups in the realm then no user's groups will be displayed at all because UI waits till requests for all groups finish.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #20489

### CODE REVIEW

File: js/apps/admin-ui/src/user/UserGroups.tsx [hunk 1]
```diff
@@ -63,111 +62,32 @@ export const UserGroups = ({ user }: UserGroupsProps) => {
...
-        index === self.findIndex((t) => t.name === thing.name)
-    );
-
-    if (!isDirectMembership) {
-      return alphabetize(filterDupesfromGroups);
-    }
+    setDirectMembershipList([...joinedUserGroups]);
+
+    if (!isDirectMembership)
+      joinedUserGroups.map((g) => {
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserGroups.tsx:75]: This value is mapped, but not assigned to anything, looks like this could just be a `for...of` loop?

File: js/apps/admin-ui/src/user/UserGroups.tsx [hunk 2]
```diff
@@ -63,111 +62,32 @@ export const UserGroups = ({ user }: UserGroupsProps) => {
...
+        if (g.path?.substring(1).includes("/")) {
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserGroups.tsx:76]: You could also build up the paths beforehand and check the length of the result. Also adding a `slice()` will allow you to remove the `pop()` instruction.
```ts
const paths = g.path
  ?.substring(1)
  ?.split("/")
  ?.slice(0, -1)
  ?? [];
  
if (paths.length > 0) {
  ...
}
```

File: js/apps/admin-ui/src/user/UserGroups.tsx [hunk 3]
```diff
@@ -208,20 +128,20 @@ export const UserGroups = ({ user }: UserGroupsProps) => {
...
+    try {
+      await Promise.all(
+        groups.map((group) =>
+          adminClient.users.addToGroup({
+            id: user.id!,
+            groupId: group.id!,
+          })
+        )
+      );
+      refresh();
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserGroups.tsx:140]: Some of these Promises could resolve successfully and mutate the data. Should we perhaps always call `refresh()`?

File: js/apps/admin-ui/src/user/UserGroups.tsx [hunk 4]
```diff
@@ -237,10 +157,9 @@ export const UserGroups = ({ user }: UserGroupsProps) => {
           }}
           canBrowse={isManager}
           onClose={() => setOpen(false)}
-          onConfirm={(groups) => {
-            addGroups(groups || []);
+          onConfirm={async (groups) => {
+            await addGroups(groups || []);
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserGroups.tsx:161]: You could add a default here instead.
```suggestion
          onConfirm={async (groups = []) => {
            await addGroups(groups);
```

**Review by jonkoops — DISMISSED** [review]
Got a few comments, but nothing blocking.

**Review by jonkoops — APPROVED** [review]
