### PR TITLE
fix: allow ignored artifacts to find the default

### LINKED ISSUE #37128: Customized quarkus.properties for MySQL cause "Unable to find the JDBC driver (org.h2.Driver)"，The server fails to start.
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

I try to create a user storage provider following [user-storage-jpa](https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/user-storage-jpa#user-storage-jpa-user-storage-provider-with-jpa), but I changed quarkus.properties to use MySQL
```
quarkus.datasource.user-store.db-kind=mysql
quarkus.datasource.user-store.username=root
quarkus.datasource.user-store.password=123456
quarkus.datasource.user-store.jdbc.url=jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false
quarkus.datasource.user-store.jdbc.transactions=xa
```

Then I copy the above quarkus.properties to the conf directory of the server distribution (I do not copy any other artifacts).

Then I run `bin\kc start-dev`. 

On keycloak-26.0.8, the server is started up properly.

But on keycloak-26.1.1/keycloak-26.1.0, I got the following error messages:
```
Updating the configuration and installing your custom providers, if any. Please wait.
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#checkJdbcDriver threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find the JDBC driver (org.h2.Driver). You need to install it.
        at org.keycloak.quarkus.deployment.KeycloakProcessor.throwConfigError(KeycloakProcessor.java:327)
        at org.keycloak.quarkus.deployment.KeycloakProcessor.checkJdbcDriver(KeycloakProcessor.java:299)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:842)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

ERROR: Build failure: Build failed due to errors
        [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#checkJdbcDriver threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find the JDBC driver (org.h2.Driver). You need to install it.
        at org.keycloak.quarkus.deployment.KeycloakProcessor.throwConfigError(KeycloakProcessor.java:327)
        at org.keycloak.quarkus.deployment.KeycloakProcessor.checkJdbcDriver(KeycloakProcessor.java:299)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:842)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

ERROR: Unable to find the JDBC driver (org.h2.Driver). You need to install it.
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

Is this a bug, or Keycloark has changed the configuration settings starting from 26.1.0?

I run it on JDK 17, Windows 10.

### Version

Keycloak 26.1.1, 26.1.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The Keycloak  server 26.1.1/26.1.0 should start up properly.

### Actual behavior

The Keycloak  serverIt fails to start.

### How to Reproduce?

Just copy quarkus.properties to conf directory, then run it by `bin\kc start-dev`.

quarkus.properties
```
quarkus.datasource.user-store.db-kind=mysql
quarkus.datasource.user-store.username=root
quarkus.datasource.user-store.password=123456
quarkus.datasource.user-store.jdbc.url=jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false
quarkus.datasource.user-store.jdbc.transactions=xa
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #37128

I'll follow-up with another pr with a more general approach to the names provided by the PropertyMapperInterceptor.

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java [hunk 1]
```diff
@@ -131,9 +129,10 @@ private static Set<String> jdbcDrivers() {
             }
         });
 
-        if (vendorsOfAllDatasources.isEmpty()) {
-            vendorsOfAllDatasources.add(Database.Vendor.H2);
-        }
+        // since the default may not be a known property name, look for it explicitly
+        Configuration.getOptionalValue("quarkus.datasource.db-kind")
+            .flatMap(Database::getVendor)
+            .ifPresent(vendorsOfAllDatasources::add);
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java:135]:
```suggestion
        vendorsOfAllDatasources.add(Configuration.getOptionalValue("quarkus.datasource.db-kind")
                .flatMap(Database::getVendor)
                .orElse(Database.Vendor.H2)
        );
```
@shawkins Wouldn't be better to explicitly add the H2 there if we can't get the vendor for the default datasource? Cause in most cases, it'll default to `dev-file`(default value for the KC `--db` option). If there's some unknown DB vendor, validation will fail.

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java:135]: quarkus.datasource.db-kind currently has a default value, so it will always resolve to a value. My next changes will remove this case entirely.

**Review by mabartos — APPROVED** [review]
