### PR TITLE
Clear local caches on split-brain heal

### LINKED ISSUE #25837: Infinispan Cache(embedded) data is not being updated during mergeView event
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

We have a Quarkus keycloak(version) statefulset with 2 replicas. We intentionally set the num_discovery_runs=1 to simulate network partitions. By setting num_discovery_runs to such a low value for kubernetes based Jgroups Discovery protocol, we can simulate both the replicas initially considered themself as master. Later due to merge protocol of Jgroups these instances able to view eachother and the view reconciles. 
 
We update the master realm header only in one of the replica, before the view reconciled. We are updating the realm header via following rest call 

`curl -g -X PUT "https://${POD1_IP}:${KC_HTTPS_PORT}${KEYCLOAK_PATH}/admin/realms/master/" -H "Authorization: Bearer ${TKN}" -H "Content-Type: application/json" -d '{"displayName":"My Custom Realm displayName", "displayNameHtml": "<div class=\"kc-logo-text\"><span>My Custom Realm displayName</span></div>"}'`

We are observing that only one instance of keycloak is getting updated with this change and other instance is not getting updated ever in the lifetime of that keycloak cluster. 
We check the change in the displayName with below rest call. 

`curl -vk https://${POD2_IP}:${KC_HTTPS_PORT}${KEYCLOAK_PATH}/admin/realms/master/ -H "Authorization: Bearer $TKN" | jq -r '.displayName'`

We think Realm caches are not getting synced after the rebalance of membership. Although we have simulated this for the realm cache but we think the same issue is applicable for any other local or distributed cache if keycloak server does not explicitly handle the network partitions scenario. Refer - http://www.jgroups.org/manual5/index.html#HandlingNetworkPartitions 

We are using the default Infinispan cache configuration for kubernetes. 

### Version

22.0.5

### Expected behavior

Once the views are merged after network partitions. Data in the caches should refresh there content from database where applicable or merge there contents(e.g. Authorization tokens)

### Actual behavior

Data in the caches are becoming divergent after network partitions, even though the views were merged at the Infinispan level. 

### How to Reproduce?

Please refer the description.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #25837

I've added a new class PartitionManager which should make it simpler for new split-brain related test cases to be added to the testsuite in the future. This class is a modified version of the logic found in Infinispan's [BasePartitionHandlingTest](https://github.com/infinispan/infinispan/blob/main/core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java)

### CODE REVIEW

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/SplitBrainTest.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+import org.keycloak.models.session.UserSessionPersisterProvider;
+import org.keycloak.testsuite.model.KeycloakModelTest;
+import org.keycloak.testsuite.model.RequireProvider;
+
+@RequireProvider(CacheRealmProvider.class)
+@RequireProvider(InfinispanConnectionProvider.class)
+@RequireProvider(RealmProvider.class)
+@RequireProvider(UserSessionPersisterProvider.class)
+@RequireProvider(UserSessionProvider.class)
+@RequireProvider(UserProvider.class)
```
Comment (ryanemerson) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/SplitBrainTest.java:31]: Maybe all of these are overkill? I wasn't really sure what the consequences were of adding/omitting Providers here.

Comment (ahus1) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/SplitBrainTest.java:31]: The tests are run for different configuration mutations as listed in the different profiles which lead to differently configured setups which are based on KeycloakModelParameters. Nowadays, all profiles are based on JPA of some kind, which provides for example the RealmProvider. Still, not all profiles include Infinispan, so the first two are definitely relevant.

File: testsuite/model/pom.xml [hunk 2]
```diff
@@ -102,6 +102,12 @@
             <groupId>org.infinispan</groupId>
             <artifactId>infinispan-core</artifactId>
         </dependency>
+        <dependency>
+            <groupId>org.infinispan</groupId>
+            <artifactId>infinispan-core</artifactId>
+            <type>test-jar</type>
+            <version>${infinispan.version}</version>
+        </dependency>
```
Comment (ahus1) [inline testsuite/model/pom.xml:110]: Please add this to the dependency management in the root `pom.xml` together with the other Infinispan dependencies. I'd like to have those in one central place.

File: model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java [hunk 3]
```diff
@@ -195,6 +198,17 @@ public boolean isSupported(Config.Scope config) {
     @Listener
     public class ViewChangeListener {
 
+        @Merged
+        public void mergeEvent(MergeEvent event) {
+           localExecutor.execute(() -> {
+              var cm = workCache.getCacheManager();
+              cm.getAccessibleCacheNames().stream()
+                    .map(cm::getCache)
+                    .filter(c -> c.getCacheConfiguration().clustering().cacheMode() == CacheMode.LOCAL)
```
Comment (ahus1) [inline model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java:207]: Iterating over all local caches is good for a default configuration that Keycloak ships. 

Still I can see problems where people add their own additional caches to the Infinispan configuration.

Or they choose to switch a cache to local where it is by default distributed (for example, if they use sticky sessions and don't care a lot for their authentication sessions, they might configure it to be a local cache). 

So I'd rather iterate over all those caches which depend on the work cache's invalidations. There is a constant `InfinispanConnectionProvider.LOCAL_CACHE_NAMES` which contains those cache names. Despite its name, it should be read as "caches that a by default local where users shouldn't have a reason to configure them differently". And those implicitly depend on the work cache.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/SplitBrainTest.java [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+public class SplitBrainTest extends KeycloakModelTest {
```
Comment (ahus1) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/SplitBrainTest.java:32]: Please provide a bit more context what kind of split brains we consider here, and what the expected behavior of Keycloak should be. Put this as JavaDoc either on the class or the method, or split it between the two.

File: model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java [hunk 5]
```diff
@@ -195,6 +198,17 @@ public boolean isSupported(Config.Scope config) {
     @Listener
     public class ViewChangeListener {
 
+        @Merged
+        public void mergeEvent(MergeEvent event) {
```
Comment (ahus1) [inline model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java:202]: Please add more context here why we do this. When looking at the code in this method, people would see what we are doing, but not why. Thanks!

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for this PR. While I don't insights to best test a split brain with Infinispan, I've looked at the other changes including how you used the test suite. LGTM, still some comments below.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/SplitBrainTest.java (hunk 4 above)
Comment (ryanemerson) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/SplitBrainTest.java]: I've add some Javadocs and renamed the test to `InfinispanEmbeddedSplitBrainTest` to make the purpose more explicit.

**Review by ahus1 — APPROVED** [review]
LGTM, thank you for the changes. 

@pruivo - may I ask you to comment on the `PartitionManager` part of this? Thanks!

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/PartitionManager.java [hunk 6]
```diff
@@ -0,0 +1,261 @@
...
+            STABLE stable = c.getProtocolStack().findProtocol(STABLE.class);
+            stable.gc();
+         }
+         try {
+            Thread.sleep(10);
+         } catch (InterruptedException e) {
+            e.printStackTrace();
+         }
+
+         MergeView mv = new MergeView(view1.get(0).getAddress(), viewId.incrementAndGet(), allAddresses, allViews);
```
Comment (pruivo) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/PartitionManager.java:165]: The view id should be the highest view id +1

https://github.com/belaban/JGroups/blob/1f6da1af5fffda1f5b7e52a9f96575e08f5dd693/src/org/jgroups/protocols/pbcast/Merger.java#L716-L717

**Review by pruivo — COMMENTED** [review]
LGTM, just a small comment :+1:

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/PartitionManager.java (hunk 6 above)
Comment (ryanemerson) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/PartitionManager.java:165]: I think that will be the case as we're calling `viewId.incrementAndGet` each time when we do:

```java
         View v1 = toView(view1);
         View v2 = toView(view2); 
```

This is the same code that's in BasePartitionHandlingTest, so if there's an issue we need to fix there as well.

Comment (pruivo) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/PartitionManager.java:165]: ah, that sounds good to me then.

**Review by pruivo — APPROVED** [review]
