### PR TITLE
Convert ClientSessionIdleTimeout from seconds to milliseconds before …

### LINKED ISSUE #13046: UserSession expiration computation is wrong
### Describe the bug

After changing the expiration field from seconds to milliseconds for the new storage, there is a bug causing the wrong expiration time computation when clientSessionIdle timeout is set. The code is wrongly treating seconds as milliseconds on this line:

https://github.com/keycloak/keycloak/blob/240de2aeb0fef64b050838aa3c3dfb9ef380aa2b/model/map/src/main/java/org/keycloak/models/map/userSession/SessionExpiration.java#L147

### Version

18.0.2

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mhajas**
…using it

Closes #13046

### CODE REVIEW

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionExpirationTest.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+import org.junit.Test;
+import org.keycloak.common.util.Time;
+import org.keycloak.models.Constants;
+import org.keycloak.models.KeycloakSession;
+import org.keycloak.models.RealmModel;
+import org.keycloak.models.RealmProvider;
+import org.keycloak.models.UserSessionProvider;
+import org.keycloak.testsuite.model.KeycloakModelTest;
+import org.keycloak.testsuite.model.RequireProvider;
+import org.keycloak.testsuite.model.infinispan.InfinispanTestUtil;
```
Comment (martin-kanis) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionExpirationTest.java:29]: Following two imports can be removed.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionExpirationTest.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+import org.keycloak.timer.TimerProvider;
+
+import static org.hamcrest.CoreMatchers.notNullValue;
+import static org.hamcrest.CoreMatchers.nullValue;
+import static org.hamcrest.MatcherAssert.assertThat;
+
+@RequireProvider(value = UserSessionProvider.class, only = "map")
```
Comment (martin-kanis) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionExpirationTest.java:36]: Nitpick: Consider using static property for consistency with existing classes. 
```suggestion
@RequireProvider(value = UserSessionProvider.class, only = MapUserSessionProviderFactory.PROVIDER_ID)
```

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Thanks @mhajas for the PR. It looks good, just see two minor things.

**Review by martin-kanis — APPROVED** [review]
