### PR TITLE
Fix declarative UI page change with signaled data table loading

### LINKED ISSUE #48284: UiPageProvider components not refreshed on page change
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When clicking between different UiPageProvider component pages in the admin UI, the component listing does not refresh.

### Version

26.6.1

### Regression

- [ ] The issue is a regression

### Expected behavior

When clicking between UiPageProvider implementation pages in the admin UI, the component listing should be refreshed to contain components for the respective implementation provider ID.

### Actual behavior

When clicking between UiPageProvider implementation pages in the admin UI, the component listing maintains components for the initially clicked implementation provider ID.

### How to Reproduce?

Augment a Keycloak server with two UiPageProvider implementations, add at least one component for one of them, and click between the pages in the admin UI.

### Anything else?

This is a follow up to the work done in https://github.com/keycloak/keycloak/issues/45877.

### PR DESCRIPTION
**Pull request by jonathancgt**
Closes https://github.com/keycloak/keycloak/issues/48284

### CODE REVIEW

**Comment by ahus1** [comment]
@edewit - can you please have a look as you would have probably the best knowledge in this area?

File: js/apps/admin-ui/src/page/PageList.tsx [hunk 1]
```diff
@@ -58,13 +58,16 @@ export default function PageList() {
...
 
-  const loader = async () => {
-    const params: ComponentQuery = {
-      parent: realm?.id,
-      type: PAGE_PROVIDER,
-      providerId,
-    };
-    return await adminClient.components.find({ ...params });
+  const loader = {
+    signal: { providerId },
```
Comment (mckoon) [inline js/apps/admin-ui/src/page/PageList.tsx:62]: This is an elegant way to notify `KeycloakDataTable` that the route changed, so the `useFetch` dependencies will trigger it to run again.

**Review by mckoon — APPROVED** [review]

**Review by edewit — APPROVED** [review]
right, I like it, after merge we should have a look at some other places where we could use this

**Review by edewit — APPROVED** [review]

**Review by mposolda — APPROVED** [review]
@jonathancgt @edewit Thanks for the PR and review!
