### PR TITLE
fixed style of clickable card

### LINKED ISSUE #28519: Cards in IDP and User federation are not shown to be clicable
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Cards should have the styles to show that they are clickable like pointer style "hand" and some shadow see: https://www.patternfly.org/components/card#clickable

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

These styles should be applied: 
image

### Actual behavior

They are not

### How to Reproduce?

Hover over the cards with your mouse and see no styles are applied

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #28519
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

File: js/apps/admin-ui/src/components/keycloak-card/ClickableCard.tsx [hunk 1]
```diff
@@ -1,13 +1,15 @@
...
+import { Card, CardHeader, CardProps } from "@patternfly/react-core";
 
 type ClickableCardProps = Omit<CardProps, "onClick"> & {
+  id: string;
   onClick: () => void;
 };
 
 export const ClickableCard = ({
-  children,
+  id,
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/keycloak-card/ClickableCard.tsx:10]: Instead of passing the `id` as a prop this could be handled internally by using the [`useId()`](https://react.dev/reference/react/useId) hook.

```ts
const id = useId();
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by jonkoops — APPROVED** [review]

**Review by agagancarczyk — APPROVED** [review]
