### PR TITLE
Return a user friendly message when a group name already exists on the same level

### LINKED ISSUE #16888: Getting notification with unknown error when trying to create duplicated sub group.
### Describe the bug

Getting error: "Could not create group unknown_error" while attempt to create sub group with duplicated name

### Version

Keycloak 999-SNAPSHOT on JVM (powered by Quarkus 2.7.5.Final)

### Expected behavior

Should show notification message "duplicated group could not be created" or similar.

### Actual behavior

 "Could not create group unknown_error"

### How to Reproduce?

1. Go to Groups
2. Create parent group
3. Navigate to parent group details, child groups tab
4. Create a sub group
5. Again create the sub group with same name as previous.
6. Masthead notification show wrong text.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by klajdipaja**
Closes #16888

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java [hunk 1]
```diff
@@ -31,13 +31,7 @@
...
 import org.keycloak.models.Constants;
 import org.keycloak.representations.AccessToken;
-import org.keycloak.representations.idm.ClientRepresentation;
-import org.keycloak.representations.idm.CredentialRepresentation;
-import org.keycloak.representations.idm.GroupRepresentation;
-import org.keycloak.representations.idm.MappingsRepresentation;
-import org.keycloak.representations.idm.RealmRepresentation;
-import org.keycloak.representations.idm.RoleRepresentation;
-import org.keycloak.representations.idm.UserRepresentation;
+import org.keycloak.representations.idm.*;
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java:34]: Can you please remove star imports and update imports as was before? We try to avoid star imports in Keycloak project.

**Review by mposolda — CHANGES_REQUESTED** [review]
@klajdipaja Thanks for the PR! It looks good to me, I've just added one minor comment inline.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java (hunk 1 above)
Comment (klajdipaja) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java]: Fixed it and squashed the commits, thanks @mposolda!

**Review by mposolda — DISMISSED** [review]
@klajdipaja Thanks!

**Review by mposolda — DISMISSED** [review]

**Review by mposolda — APPROVED** [review]
