### PR TITLE
fix: consistently resetting the configuration

### LINKED ISSUE #47869: Configuration reset isn't always complete
### Description

I noticed there was an inconsistency because of running our quarkus unit tests in the ide and getting a failure on a health check test.

Configuration.reset should always call KeycloakConfigSourceProvider.reload() because otherwise the existing config sources will get reused and it's possible they contain stale state.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #47869

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 1]
```diff
@@ -109,7 +108,6 @@ public void start() {
 
         @Override
         public void initConfig(AbstractCommand command) {
-            KeycloakConfigSourceProvider.reload();
```
Comment (vmuzikar) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:112]: We're not calling `Configuration.resetConfig()` somewhere here, are we?

Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:112]: That call was a workaround for missing it somewhere else when resetting the config. Now that we do it consistently we don't need this one off.

**Review by vmuzikar — APPROVED** [review]
