### PR TITLE
Test framework validations and error messages

### LINKED ISSUE #38163: Framework validations and error messages
At this point, the framework allows some stuff that's not fully valid. We should investigate which are these issues and resolve them. Some of them are:

- annotations used for a wrong resource
    ```java
    @TestRealm
    ClientResource clientResource
    ```
- Injecting the same resource multiple times. Should the following be valid? Should an exception be thrown or a warning be raised? (`realm1` == `realm2`, `realm3` == `realm4`)
    ```java
    @TestRealm
    RealmResource realm1;

    @TestRealm
    RealmResource realm2;

    @TestRealm(ref="my-realm")
    RealmResource realm3;

    @TestRealm(ref="my-realm")
    RealmResource realm4;
    ```

### PR DESCRIPTION
**Pull request by vaceksimon**
Closes #38163

### CODE REVIEW

**Comment by vaceksimon** [comment]
For now, all validation errors throw exceptions to make testing easier.

Here are examples what happens if you run tests that fail the validation

```java
@InjectRealm
ManagedUser user;
```
throws:
```
2026-01-29 18:30:10,003 INFO  [testinfo] (main) ----------------------------------------------------------------
2026-01-29 18:30:10,008 INFO  [testinfo] (main)    RUNNING - org.keycloak.test.examples.ValidationsTest
2026-01-29 18:30:10,118 ERROR [testinfo] (main)     FAILED - org.keycloak.test.examples.ValidationsTest / thisTestWillFail

org.keycloak.testframework.TestFrameworkException: @InjectRealm requires ManagedRealm but field has type ManagedUser

	at org.keycloak.testframework.TestFrameworkException.typeMismatch(TestFrameworkException.java:18)
	at org.keycloak.testframework.injection.Registry.createRequestedInstance(Registry.java:282)
...
```
<strike>

---
```java
@InjectRealm(ref = "test")
ManagedRealm realm1;

@InjectRealm(ref = "test")
ManagedRealm realm2;
```
throws:
```
2026-01-29 18:27:17,579 INFO  [testinfo] (main) ----------------------------------------------------------------
2026-01-29 18:27:17,593 INFO  [testinfo] (main)    RUNNING - org.keycloak.test.examples.ValidationsTest
2026-01-29 18:27:17,727 ERROR [testinfo] (main)     FAILED - org.keycloak.test.examples.ValidationsTest / thisTestWillFail

org.keycloak.testframework.TestFrameworkException: A ManagedRealm with ref="test" requested more than once. Second request was for field:

@InjectRealm(ref="test")
ManagedRealm realm2

	at org.keycloak.testframework.TestFrameworkException.instanceAlreadyRequested(TestFrameworkException.java:28)
	at org.keycloak.testframework.injection.Registry.findRequestedInstances(Registry.java:172)
```
---
```java
@InjectRealm
ManagedRealm realm1;

@InjectRealm
ManagedRealm realm2;
```
throws:
```
2026-01-29 18:28:03,483 INFO  [testinfo] (main) ----------------------------------------------------------------
2026-01-29 18:28:03,487 INFO  [testinfo] (main)    RUNNING - org.keycloak.test.examples.ValidationsTest
2026-01-29 18:28:03,595 ERROR [testinfo] (main)     FAILED - org.keycloak.test.examples.ValidationsTest / thisTestWillFail

org.keycloak.testframework.TestFrameworkException: A ManagedRealm with ref="" requested more than once. Second request was for field:

@InjectRealm(ref="")
ManagedRealm realm2

	at org.keycloak.testframework.TestFrameworkException.instanceAlreadyRequested(TestFrameworkException.java:28)
	at org.keycloak.testframework.injection.Registry.findRequestedInstances(Registry.java:172)
...
```
</strike>

EDIT: Only the first scenario is forbidden. Others don't constitute a validation error

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java [hunk 1]
```diff
@@ -23,7 +24,7 @@
 import org.junit.jupiter.api.extension.ReflectiveInvocationContext;
 
 @SuppressWarnings({"rawtypes", "unchecked"})
-public class Registry implements ExtensionContext.Store.CloseableResource {
+public class Registry implements AutoCloseable {
```
Comment (vaceksimon) [inline test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java:31]: Sneaked this in to fix the warning we've been seeing for some time:

```
2026-01-29 18:37:54,792 WARNING [org.junit.jupiter.engine.descriptor.AbstractExtensionContext] (main) Type implements CloseableResource but not AutoCloseable: org.keycloak.testframework.injection.Registry
```

Comment (stianst) [reply test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java:31]: Please send this as a separate fix

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java [hunk 2]
```diff
@@ -167,6 +168,9 @@ private void findRequestedInstances(Object testInstance, Method testMethod) {
         for (Field f : ReflectionUtils.listFields(testClass)) {
             RequestedInstance requestedInstance = createRequestedInstance(f.getAnnotations(), f.getType());
             if (requestedInstance != null) {
+                if (requestedInstances.stream().anyMatch(i -> i.getValueType().equals(requestedInstance.getValueType()) && Objects.equals(i.getRef(), requestedInstance.getRef()))) {
```
Comment (stianst) [inline test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java]: Use `RequestedInstancePredicates.matches`

**Review by stianst — COMMENTED** [review]
One problem with this I'm pretty sure about is if I have a test class with multiple test methods each test will still try to run, and I'll get multiple repeats of the same failure.

Wonder if it's possible to somehow stop JUnit from running more tests if the test class is broken.

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java (hunk 1 above)
Comment (vaceksimon) [reply test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java:31]: Opened a PR https://github.com/keycloak/keycloak/pull/45887

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java (hunk 2 above)
Comment (vaceksimon) [reply test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java]: Updated

**Comment by vaceksimon** [comment]
> One problem with this I'm pretty sure about is if I have a test class with multiple test methods each test will still try to run, and I'll get multiple repeats of the same failure.
> 
> Wonder if it's possible to somehow stop JUnit from running more tests if the test class is broken.

@stianst Added a simple check for that to `Registry#beforeEach()`

Here's an example of what it looks like:
```java
@KeycloakIntegrationTest
public class FailTest {

    @InjectRealm
    ManagedUser mismatched;

    @Test
    public void thisTestWillFail1() {    }

    @Test
    public void thisTestWillFail2() {    }
}
```
outputs:
```
2026-01-30 17:25:31,058 INFO  [testinfo] (main) ----------------------------------------------------------------
2026-01-30 17:25:31,058 INFO  [testinfo] (main)    RUNNING - org.keycloak.test.examples.FailTest
2026-01-30 17:25:31,066 ERROR [testinfo] (main)    ABORTED - org.keycloak.test.examples.FailTest / thisTestWillFail1

org.opentest4j.TestAbortedException: Skipping test method due to test class setup failure


	at org.keycloak.testframework.injection.Registry.skipTestMethod(Registry.java:383)
	at org.keycloak.testframework.injection.Registry.beforeEach(Registry.java:127)
	at org.keycloak.testframework.KeycloakIntegrationTestExtension.beforeEach(KeycloakIntegrationTestExtension.java:32)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

2026-01-30 17:25:31,075 ERROR [testinfo] (main)    ABORTED - org.keycloak.test.examples.FailTest / thisTestWillFail2

org.opentest4j.TestAbortedException: Skipping test method due to test class setup failure


	at org.keycloak.testframework.injection.Registry.skipTestMethod(Registry.java:383)
	at org.keycloak.testframework.injection.Registry.beforeEach(Registry.java:120)
	at org.keycloak.testframework.KeycloakIntegrationTestExtension.beforeEach(KeycloakIntegrationTestExtension.java:32)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


org.keycloak.testframework.TestFrameworkException: @InjectRealm requires ManagedRealm (or its subclass) but field has type ManagedUser

	at org.keycloak.testframework.TestFrameworkException.typeMismatch(TestFrameworkException.java:18)
	at org.keycloak.testframework.injection.Registry.createRequestedInstance(Registry.java:301)
	at org.keycloak.testframework.injection.Registry.findRequestedInstances(Registry.java:181)
	at org.keycloak.testframework.injection.Registry.beforeEach(Registry.java:123)
	at org.keycloak.testframework.KeycloakIntegrationTestExtension.beforeEach(KeycloakIntegrationTestExtension.java:32)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

```

File: test-framework/core/src/main/java/org/keycloak/testframework/TestFrameworkException.java
Comment (stianst) [inline test-framework/core/src/main/java/org/keycloak/testframework/TestFrameworkException.java:1]: I'd rename this to something like `FatalTestClassException`. We can use it for other things as well in the future. Maybe even throw it from tests themselves.

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java [hunk 3]
```diff
@@ -31,6 +33,7 @@ public class Registry implements AutoCloseable {
     private final Extensions extensions;
     private final List<InstanceContext<?, ?>> deployedInstances = new LinkedList<>();
     private final List<RequestedInstance<?, ?>> requestedInstances = new LinkedList<>();
+    private TestFrameworkException testClassSetupFailure;
```
Comment (stianst) [inline test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java]: Maybe rename to:
```suggestion
    private TestFrameworkException fatalTestClassException;
```

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java [hunk 4]
```diff
@@ -113,14 +116,28 @@ private <T> T getRequestedDependency(Class<T> typeClass, String ref, InstanceCon
     }
 
     public void beforeEach(Object testInstance, Method testMethod) {
-        findRequestedInstances(testInstance, testMethod);
+        if (testClassSetupFailure != null) {
+            skipTestMethod();
+        }
+
+        try {
```
Comment (stianst) [inline test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java:128]: Maybe we should wrap everything? Then anything can throw a fatal test class exception? Including suppliers (for example server if it detects invalid config or port is busy)

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java [hunk 5]
```diff
@@ -113,14 +116,28 @@ private <T> T getRequestedDependency(Class<T> typeClass, String ref, InstanceCon
...
+        }
         destroyIncompatibleInstances();
         matchDeployedInstancesWithRequestedInstances();
         deployRequestedInstances();
         injectFields(testInstance);
         invokeBeforeEachOnSuppliers();
     }
 
+    private void skipTestMethod() {
+        Assumptions.abort("Skipping test method due to test class setup failure");
```
Comment (stianst) [inline test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java]:
```suggestion
        Assumptions.abort("Skipping test method due to fatal test class error");
```

File: test-framework/core/src/main/java/org/keycloak/testframework/TestFrameworkException.java [hunk 6]
```diff
@@ -1,9 +1,24 @@
...
+import java.lang.annotation.Annotation;
+
+
 public class TestFrameworkException extends RuntimeException {
 
     public TestFrameworkException(String message) {
         super(message);
     }
 
+    public static TestFrameworkException typeMismatch(
```
Comment (stianst) [inline test-framework/core/src/main/java/org/keycloak/testframework/TestFrameworkException.java]: If we make this a generic fatal test error exception then maybe this should be moved elsewhere?

File: test-framework/core/src/test/java/org/keycloak/testframework/injection/RegistryTest.java [hunk 7]
```diff
@@ -18,6 +19,7 @@
 import org.junit.jupiter.api.Assertions;
 import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
+import org.opentest4j.TestAbortedException;
```
Comment (lhanusov) [inline test-framework/core/src/test/java/org/keycloak/testframework/injection/RegistryTest.java:24]: @vaceksimon do you know if there is something similar per JUnit6? It introduces a new dependency, which is not a good idea.

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java [hunk 8]
```diff
@@ -113,14 +116,28 @@ private <T> T getRequestedDependency(Class<T> typeClass, String ref, InstanceCon
...
 
     public void beforeEach(Object testInstance, Method testMethod) {
-        findRequestedInstances(testInstance, testMethod);
+        if (testClassSetupFailure != null) {
+            skipTestMethod();
+        }
+
+        try {
+            findRequestedInstances(testInstance, testMethod);
+        } catch (TestFrameworkException e) {
```
Comment (lhanusov) [inline test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java]: you are catching only RuntimeException, do we plan to catch some mismatch?

**Review by lhanusov — CHANGES_REQUESTED** [review]

File: test-framework/core/src/test/java/org/keycloak/testframework/injection/RegistryTest.java (hunk 7 above)
Comment (vaceksimon) [reply test-framework/core/src/test/java/org/keycloak/testframework/injection/RegistryTest.java:24]: This exception is used in JUnit6. It is thrown by the [`Assumptions#abort(String message)`](https://docs.junit.org/6.0.2/api/org.junit.jupiter.api/org/junit/jupiter/api/Assumptions.html#abort(java.lang.String)) in the `Registry`.

From what I read, using this class is the preferred way to stop a junit test execution.

File: test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java (hunk 8 above)
Comment (vaceksimon) [reply test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java]: I'm not sure what you mean. The `TestFrameworkException` here is caught and stored to be thrown again after all test methods are aborted.

**Review by stianst — APPROVED** [review]
