### PR TITLE
Declarative User Profile export

### LINKED ISSUE #12062: Declarative User Profile export
### Description

The realm export via admin console, should include the defined declarative user profile.

### Discussion

https://github.com/keycloak/keycloak/discussions/11541

### Motivation

The declarative user profile is a really nice feature, but migrating a realm from one stage to another will require more manual effort without this feature.

### Details

The UserProfileProvider is correctly exported with `declarative-user-profile` but the config is empty:

```
"org.keycloak.userprofile.UserProfileProvider": [
      {
        "id": "88cef18c-bcd8-40d2-9e7d-d257298317f2",
        "providerId": "declarative-user-profile",
        "subComponents": {},
        "config": {}
      }
    ],
```
I would expect that the config would contain the defined user attributes.

### LINKED ISSUE #20885: Key length is limited to 4000 characters
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I am trying to add an RSA certificate which is 5517 characters long in it's PEM presentation, using either Terraform's keycloak_realm_keystore_rsa provider or GUI: Realm settings -> Keys -> Providers -> Add provider -> rsa -> Enter a 5517 character long PEM into field 'X509 Certificate'.

This fails with an unexpected error. Terraform says '500 Internal Server Error. Response body: {"error":"unknown_error"}'

### Version

20.0.5

### Expected behavior

Long rsa certificates should work, just like certificates shorter than 4000 characters in their PEM format

### Actual behavior

This fails with an unexpected error. Terraform says '500 Internal Server Error. Response body: {"error":"unknown_error"}'

Keycloak log says:
`Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(4000)`

### How to Reproduce?

- Have an RSA certificate and its private key in PEM format. The certificate should be longer than 4000 characters
- In GUI: Go to your realm -> Realm settings -> Keys -> Providers -> Add provider -> rsa -> Enter the PEM into field 'X509 Certificate', also fill the other required fields
- Click 'Save'

### Anything else?

This is clearly a problem with the 4000 character limit on the database schema:

On psql, logged in as the keycloak database user:
```
keycloak=> \d component_config
                     Table "public.component_config"
    Column    |          Type           | Collation | Nullable | Default 
--------------+-------------------------+-----------+----------+---------
 id           | character varying(36)   |           | not null | 
 component_id | character varying(36)   |           | not null | 
 name         | character varying(255)  |           | not null | 
 value        | character varying(4000) |           |          | 
Indexes:
    "constr_component_config_pk" PRIMARY KEY, btree (id)
    "idx_compo_config_compo" btree (component_id)
Foreign-key constraints:
    "fk_component_config" FOREIGN KEY (component_id) REFERENCES component(id)
```
I tripled the character limit:
```
keycloak=> alter table component_config alter column value type character varying(12000);
ALTER TABLE

keycloak=> \d component_config
                     Table "public.component_config"
    Column    |           Type           | Collation | Nullable | Default 
--------------+--------------------------+-----------+----------+---------
 id           | character varying(36)    |           | not null | 
 component_id | character varying(36)    |           | not null | 
 name         | character varying(255)   |           | not null | 
 value        | character varying(12000) |           |          | 
Indexes:
    "constr_component_config_pk" PRIMARY KEY, btree (id)
    "idx_compo_config_compo" btree (component_id)
Foreign-key constraints:
    "fk_component_config" FOREIGN KEY (component_id) REFERENCES component(id)
```
... and the problem is gone. I can now add my rsa certificate.

### PR DESCRIPTION
**Pull request by vramik**
Closes https://github.com/keycloak/keycloak/issues/12062
Resolves https://github.com/keycloak/keycloak/issues/20885

### CODE REVIEW

**Review by douglaspalmer — APPROVED** [review]
I wonder if the changes for #12062 can be separated from those for #20885 ?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java [hunk 1]
```diff
@@ -262,6 +271,45 @@ public void testImportWithNullAuthenticatorConfigAndNoDefaultBrowserFlow() {
         Assert.assertTrue("Imported realm hasn't been found!", isRealmPresent("cez"));
     }
 
+    @Test
+    @EnableFeature(value = Profile.Feature.DECLARATIVE_USER_PROFILE)
```
Comment (ahus1) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java:275]: I had a look why this test fails, and I found that once you add the `@EnableFeature` annotation on a method, it will restart the Quarkus instance with the new configuration. 

https://github.com/keycloak/keycloak/blob/82269f789ab0a336ea33788216a94b2b08002744/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakContainerFeaturesController.java#L147-L150

Once that happens, the referenced in `AbstractKeycloakTest` is now stale.

I found that the test works as expected without that annotation. 

I would be ok to remove this annotation, and open a follow-up issue to re-think the `adminClient` in `AbstractKeycloakTest`. Maybe it would be better to get rid of the attribute `adminClient` and to only keep the method `getAdminClient()` and make it retrieve the latest instance from `testContext` instead. There are a lot of references that need to be updated, therefore it should be a different issue.

**Review by ahus1 — COMMENTED** [review]
Hi @vramik - thank you for this change, it looks good to me. I had a look why the test case fails. See below for a suggestion.

**Comment by ahus1** [comment]
> I wonder if the changes for #12062 can be separated from those for #20885 ?

@vramik / @douglaspalmer - One could argue that #20885 is handled more as a side effect of a change that we're making to fix the export of the user profile, and I wouldn't object. 

If Vlasta decided to separate them, I'd suggest to keep all changes in this PR, and have two commits in it referencing the two different issues as it makes sense to test them together and this PR has progressed already quite far. The maintainer merging this PR would make sure to use rebase, and not squash them.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java (hunk 1 above)
Comment (vramik) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java:275]: Thank you, your findings are inline with mine. I was experimenting with `skipRestart` flag: `@EnableFeature(value = Profile.Feature.DECLARATIVE_USER_PROFILE, skipRestart = true)` and it also resolves the test failure.

I was digging a little bit and found out that the reason why the test is passing without the annotation is the fact the rest endpoints in the `UserProfileResource` are not guarded by feature flag. I've discussed it with @pedroigor and it turned out there is no plan to add such a guard there since the User Profle will be supported soon and that "it does not expose anything critical/sensitive to when declarative is not used". Therefore I decided to follow your suggestion to remove the annotation.

I think it makes a lot of sense to open the issue to re-think the `adminClient` concept, maybe it might make sense to restrict the access to the field altogether and access it via a method only in whole testsuite. I'll create an issue for it.

**Comment by vramik** [comment]
> > I wonder if the changes for #12062 can be separated from those for #20885 ?
> 
> @vramik / @douglaspalmer - One could argue that #20885 is handled more as a side effect of a change that we're making to fix the export of the user profile, and I wouldn't object.

+1
 
> If Vlasta decided to separate them, I'd suggest to keep all changes in this PR, and have two commits in it referencing the two different issues as it makes sense to test them together and this PR has progressed already quite far. The maintainer merging this PR would make sure to use rebase, and not squash them.

Currently I plan to keep the changes in one commit.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java (hunk 1 above)
Comment (vramik) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java]: https://github.com/keycloak/keycloak/issues/24190

**Review by ahus1 — APPROVED** [review]
Thank you for preparing this PR. I tested it locally, both import/export, migration on import and migration on upgrade worked for me. Therefore I'm approving and merging it.
