### PR TITLE
fix: adding the jgroups bind address for ipv6 support

### LINKED ISSUE #36383: Operator tests failing on IPV6 environment
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Some operator tests are failing on the IPV6 environment

[https://jenkins.com/view/OpenShift/job/rhbk-operator-test-pipeline/1108/](https://jenkins-csb-keycloak-qe-master.dno.corp.redhat.com/view/OpenShift/job/rhbk-operator-test-pipeline/1108/)

org.keycloak.operator.testsuite.integration.KeycloakNetworkPolicyTest.testJGroupsConnectivity org.keycloak.operator.testsuite.integration.KeycloakNetworkPolicyTest.testHttpAndHttps org.keycloak.operator.testsuite.integration.KeycloakNetworkPolicyTest.testServiceConnectivity org.keycloak.operator.testsuite.integration.KeycloakNetworkPolicyTest.testUpdate

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Pass

### Actual behavior

6 failures

### How to Reproduce?

Run a build of the job with the IPV6 parameters

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
The understanding from the kube docs is that in ipv4 or dual stack environments this will supply a ipv4 address. In ipv6 only environments it will be ipv6.

closes: #36383

### CODE REVIEW

**Comment by shawkins** [comment]
Tried this on an ipv6 cluster, in the log it shows:

2025-01-15 19:52:15,690 INFO [org.jgroups.JChannel] (ForkJoinPool.commonPool-worker-1) local_addr: 4624b5f7-a8b3-40e0-b397-bc3576332fcc, ...

And the KeycloakNetworkPolicyTests pass.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java [hunk 1]
```diff
@@ -296,6 +298,7 @@ private StatefulSet createBaseDeployment(Keycloak keycloakCR, Context<Keycloak>
                         && (customImage.isPresent() || operatorConfig.keycloak().startOptimized())) {
             containerBuilder.addToArgs(OPTIMIZED_ARG);
         }
+        containerBuilder.addToArgs(0, "-Djgroups.bind.address=$(%s)".formatted(POD_IP));
```
Comment (ahus1) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:301]: Nitpick: Add a comment stating why we do this.

```suggestion
        // Set bind address as this is required for JGroups to form a cluster in IPv6 envionments
        containerBuilder.addToArgs(0, "-Djgroups.bind.address=$(%s)".formatted(POD_IP));
```

**Review by ahus1 — COMMENTED** [review]
Thank you for the change, great to hear that it in a test cluster. 
One nit-pick below.

**Review by ahus1 — APPROVED** [review]
Thank you for this change!

**Review by pruivo — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]
@shawkins Thanks for the fix!

Changes as such LGTM. I cannot verify it solves the IPv6 related issue as reported in https://github.com/keycloak/keycloak/issues/36383 but based on the comments there it appears so.
