### PR TITLE
When asserting a URL, allow for some time for any redirect to complete.

### LINKED ISSUE #12446: Flaky test SessionServletAdapterTest.testSessionInvalidatedAfterFailedRefresh
### Describe the bug

The test failed with the following error: 

> SessionServletAdapterTest.testSessionInvalidatedAfterFailedRefresh:163->loginAndCheckSession:227 Expected URL: http://localhost:8280/session-portal/ ; actual: http://localhost:8280/session-portal/?state=6e6b0539-f3be-4a89-b293-40c6f13ebd2a&session_state=a4870775-14f3-4d4f-84e7-6ce103330ce0&code=d17d9065-fa8c-4d9f-8c82-4d09bbb5e9be.a4870775-14f3-4d4f-84e7-6ce103330ce0.0bc75b15-4b30-4369-b95f-45d8b14a4fb3

Apparently the redirect didn't complete when the test checked the URL. 

### Version

999-SNAPSHOT

### Expected behavior

Test should be stable

### Actual behavior

Test is unstable, at least with undertow-map-hot-rod

### PR DESCRIPTION
**Pull request by ahus1**
Closes #12446

### CODE REVIEW

**Comment by ahus1** [comment]
This ensure that the tests run stable even when we switch the storage for a database that might be slower than a concurrent hash map. 

The CI will not run these tests for the JPA map store as the code changes don't touch a map store. I ran them locally and they passed. The tests still pass (as before) for the concurrent hash map that is part of the CI. Even for JPA map they will only fail sometimes (and probably never locally on a fast machine) as it is about a timing issue. 

Ready for review. Thanks!

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/URLAssert.java [hunk 1]
```diff
@@ -87,31 +92,33 @@ public static void assertCurrentUrlStartsWith(final AbstractPage page) {
...
     public static void assertCurrentUrlDoesntStartWith(final AbstractPage page, WebDriver driver) {
         assertCurrentUrlDoesntStartWith(page.toString(), driver);
     }
 
     public static void assertCurrentUrlDoesntStartWith(final String url, WebDriver driver) {
-        DroneUtils.addWebDriver(driver);
-        assertCurrentUrlDoesntStartWith(url);
-        DroneUtils.removeWebDriver();
+        awaitUntilAsserted(() -> {
+            DroneUtils.addWebDriver(driver);
```
Comment (mhajas) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/URLAssert.java:107]: I think this can be outside of `awaitUntilAsserted`

**Review by mhajas — DISMISSED** [review]
Thanks @ahus1, I added one nitpick comment but I don't think it is a blocking issue so I am leaving this up to you whether you want to fix it or not. Approving

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/URLAssert.java (hunk 1 above)
Comment (ahus1) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/URLAssert.java]: Thanks for the review, updated the code. CI is now running.

**Review by mhajas — APPROVED** [review]
Thanks @ahus1 LGTM. Wondering if we want someone from QA to have a look. Maybe @mabartos?

**Review by mabartos — APPROVED** [review]
@ahus1 LGTM.

**Review by hmlnarik — APPROVED** [review]
Approving per @mhajas and @mabartos 's approvals
