### PR TITLE
DefaultBruteForceProtector leverages a single thread to write success /failed events

### LINKED ISSUE #14084: DefaultBruteForceProtector leverages a single thread to write success/failed events
### Describe the bug

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java uses a single thread/queue to update the database for success/failed login attempts.

The idea behind it is to prevent multiple concurrent writes to overwrite each-other. The problem with that though is most installation of Keycloak is leveraging a cluster with multiple nodes, which means this doesn't really do anything other than introduce a bottleneck. 

This is a follow-up to https://github.com/keycloak/keycloak/pull/7748, where it was observed that during both success and failed login attempts a wait of up to 5 seconds is introduced waiting for the queue to process the event. It can be questioned if this is a good idea or not for failed login attempts, but it certainly isn't a good idea to do this for successful logins. 

### Version

main

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #14084

### CODE REVIEW

**Comment by mposolda** [comment]
@rmartinc Could you please review this PR?

File: services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java [hunk 1]
```diff
@@ -261,125 +151,61 @@ protected void sendEvent(KeycloakSession session, RealmModel realm, UserLoginFai
...
         logger.trace("sent success event");
     }
 
+    private void processLogin(RealmModel realm, UserModel user, ClientConnection clientConnection, boolean success) {
+        KeycloakSession session = factory.create();
+        ExecutorsProvider provider = session.getProvider(ExecutorsProvider.class);
+        ExecutorService executor = provider.getExecutor("bruteforce");
+        executor.execute(() -> {
+            try {
+                session.getTransactionManager().begin();
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:188]: This is new thread and as such, it should probably also use dedicated `KeycloakSession` instance. Using same `KeycloakSession` within many threads can have bad side-effects as this is supposed to be per-thread object.

I think something like this should work (this will make sure to use dedicated KeycloakSession together with dedicated transaction and also automatically handles transaction rollbacks as well:)

```
executor.execute(() -> {
    KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(), () -> {
        if(success) {
            success(session, realm, user.getId());
        } else {
            failure(session, realm, user.getId(), clientConnection.getRemoteAddr(), Time.currentTimeMillis());
        }
    });
});
```

**Review by mposolda — COMMENTED** [review]
@douglaspalmer @rmartinc Agree that this version looks much simpler. Thanks for the update!

Added one comment inline.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java [hunk 2]
```diff
@@ -88,7 +88,9 @@ public long getLastFailure() {
     }
 
     public void setLastFailure(long lastFailure) {
-        this.lastFailure = lastFailure;
+        if(lastFailure>this.lastFailure) {
+            this.lastFailure = lastFailure;
+        }
```
Comment (rmartinc) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java:93]: @douglaspalmer Probably we need something similar in `failedLoginNotBefore`.

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @douglaspalmer! Just a minor comment.

File: services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java (hunk 1 above)
Comment (douglaspalmer) [reply services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java]: Done

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java (hunk 2 above)
Comment (douglaspalmer) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java:95]: Done

**Review by mposolda — APPROVED** [review]

File: services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java [hunk 3]
```diff
@@ -261,125 +152,54 @@ protected void sendEvent(KeycloakSession session, RealmModel realm, UserLoginFai
...
-            // cannot flood with failed logins and overwhelm the queue and not have notBefore updated to block next requests
-            // todo failure HTTP responses should be queued via async HTTP
-            event.latch.await(5, TimeUnit.SECONDS);
-        } catch (InterruptedException e) {
-        }
+        processLogin(realm, user, clientConnection, false);
+        // wait a minimum of seconds for type to process so that a hacker
+        // cannot flood with failed logins and overwhelm the queue and not have notBefore updated to block next requests
+        // todo failure HTTP responses should be queued via async HTTP
+        //event.latch.await(5, TimeUnit.SECONDS);
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:173]: Maybe we should delete these comments. My feeling this was important in the past because maybe the success/failure was executed in the same thread and not off-thread like it is now. But this is a minor thing. Approving anyway.

**Review by rmartinc — APPROVED** [review]
Thanks @douglaspalmer! Approving. I did a comment because there is a comment which I think it's outdated but it's a minor thing.

File: services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java (hunk 3 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:173]: +1, but yeah, likely does not worth to wait even more for this PR just because of it.

Maybe we can delete during some next PR, which need to do any changes in brute-force protector.
