### PR TITLE
When using the token revocation endpoint with refresh-token, only par…

### LINKED ISSUE #35486: When using the token revocation endpoint with refresh-token, all sessions from the user+client are terminated
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Currently token revocation does this:

- For access token, it revokes only the particular access token (OK)
- When invoked with the refresh token of client `client-a` and user `user-a` with the token created with user session `session1`, it:
  - Deletes the consent granted by the `user-a` to `client-a`
  - Deletes all client sessions of client `client-a` of all user sessions for user `user-a` . So it deletes also the client sessions, which are unrelated to the particular session `session1`, but possibly also to other user sessions

The behaviour is not compliant with the specification as the specs mention to only invalidate refresh-token and related access-tokens issued during same authorization grant, which effectively means droping just this particular client session (See https://datatracker.ietf.org/doc/html/rfc7009#section-2.1) . Also misleading for the users as can be seen in the discussion https://github.com/keycloak/keycloak/discussions/27815 and some other report by our customer.

AFAIK the reasoning behind deleting of all client sessions of all user sessions might be the fact, that we are dropping also the granted consent. During refresh-token request, we are checking that granted consent is still valid (for clients with `Consent Required` enabled). So if we drop only single session `session1`, the other refresh tokens would be effectively invalid as well.

If we want to update the behaviour, our options are:
1) Don't delete the granted consent. Revoke only client session for particular user session `session1`, which was referenced in the refresh-token
2) Still delete the granted consent. Revoke only client session for particular user session `session1`, which was referenced in the refresh-token.

The option (2) means that for clients with `Consent Required`, the other client sessions will be effectively revoked as well (due the fact that refresh-token request checks if consent is still granted). So this would be still a bit buggy behaviour IMO.

IMO, we should do the option (1) and document in the upgrading guide about this. If there is someone, who want the old behaviour, we can handle that with client-policy-executor as a follow-up (if there is a request for this).

### Version

nightly (from 2024-12-02)

### Regression

- [ ] The issue is a regression

### Expected behavior

Only one session is invalidated. The granted consent should be probably kept (See description for more details)

### Actual behavior

All sessions are invalidated.

### How to Reproduce?

1. Create a session with a test user

```
    curl -d "client_id=<test client id>" \
    -d "client_secret=<test client secret>" \
    -d "grant_type=password" \
    -d "username=<test user name>" \
    -d "password=<test user password>" \
    -d "scope=openid" \
    "http://<domain>/auth/realms/<realm name>/protocol/openid-connect/token" | jq .refresh_token
```

2. Create another session with the same user

```
    curl -d "client_id=<test client id>" \
    -d "client_secret=<test client secret>" \
    -d "grant_type=password" \
    -d "username=<test user name>" \
    -d "password=<test user password>" \
    -d "scope=openid" \
    "http://<domain>/auth/realms/<realm name>/protocol/openid-connect/token"
```

3. Check the two sessions are created in the admin console

4. Revoke the session created in step 1

```
    curl -d "client_id=<test client id>" \
    -d "client_secret=<test client secret>" \
    -d "token_type_hint=refresh_token" \
    -d "token=<refresh token>" \
    "http://<domain>/auth/realms/<realm name>/protocol/openid-connect/revoke"
```

For <refresh_token>, use the refresh token issued in step1.

5. Check the sessions in the admin console
It is expected that the session created in step2 still exists, but actually, both sessions are revoked.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
…ticular clientSession related to given refresh token should be terminated

closes #35486

Pretty much option (1) from #35486 as discussed on the issue with @sschu and with my team. It adds some additional details to the event like sessionId (now possible to add since it applies to single session), refreshTokenType (whether offline or refresh) and refreshTokenId.

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java [hunk 1]
```diff
@@ -242,26 +243,24 @@ private void checkParameterDuplicated(MultivaluedMap<String, String> formParams)
...
-        UserConsentManager.revokeConsentForClient(session, realm, user, client.getId());
+    private void revokeClientSession() {
         if (TokenUtil.TOKEN_TYPE_OFFLINE.equals(token.getType())) {
-            new UserSessionManager(session).revokeOfflineToken(user, client);
+            UserSessionModel userSession = session.sessions().getOfflineUserSession(realm, token.getSessionId());
+            if (userSession != null) {
+                new UserSessionManager(session).removeClientFromOfflineUserSession(realm, userSession, client, user);
+            }
+        }
+        UserSessionModel userSession = session.sessions().getUserSession(realm, token.getSessionId());
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java:253]: This should be an else, if it's an offline token we don't want to remove the online session. Or am I missing something?

**Review by rmartinc — COMMENTED** [review]
@mposolda LGTM! Just one question because I don't understand that part.

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java (hunk 1 above)
Comment (douglaspalmer) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java:253]: Can an offline session and an online session share the same session ID? If not userSession will be null so this will function just like an else. An else would make it more readable though.

**Review by graziang — APPROVED** [review]
@mposolda Thanks, LGTM!

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java (hunk 1 above)
Comment (graziang) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java:253]: I think a regular user session is still being created

**Review by douglaspalmer — APPROVED** [review]
LGTM assuming the session ID can't be shared between online and offline sessions.

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java (hunk 1 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java]: @rmartinc @douglaspalmer @graziang Thanks for the feedback. The online and offline session can share the same ID. I've originally did not updated this part due the previously there was not `else` as well. On the other hand, it will makes sense to add "else" due the:
- Previously the consent was revoked, which effectively revoked both offline and online sessions. But now consent is not revoked and hence makes sense to revoke only one of them
- Revoking only offline session in case that offline-token is provided is more aligned with the recent changes done by @rmartinc regarding offline sessions

So I've added `else` as suggested by @rmartinc to make sure that if offline-token is provided, only related offline-session is revoked, but "online" session is not touched.

**Review by rmartinc — APPROVED** [review]
Thanks @mposolda! LGTM!

**Comment by mposolda** [comment]
@rmartinc @graziang @douglaspalmer Thanks everyone!
