### PR TITLE
use subGroupCount to render subGroups

### LINKED ISSUE #28080: Paging issue in groups via user view
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Paging doesn't work for groups in user view.

### Version

23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Paging works, going back and forth between pages is possible

### Actual behavior

Paging doesn't work. It is only possible to go to the second page.

### How to Reproduce?

1. Go to Users
2. Select a user
3. Go to Groups Tab
4. Click 'Join Group'
5. Go to the next page
6. Following is displayed instead of correct pages:
image
7. It is impossible to go back to previous page

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #28080
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

File: js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx [hunk 1]
```diff
@@ -93,14 +93,13 @@ export const GroupPickerDialog = ({
...
-            first: first,
-            max: max + 1,
-            parentId: group.id,
-          };
-          groups = await adminClient.groups.listSubGroups(args);
-        }
+
+        const args: SubGroupQuery = {
+          first: first,
+          max: max + 1,
```
Comment (bodograumann) [inline js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx:99]: Without the slice below, all `max + 1` subgroups will now be shown. Maybe this should just be `max`?

Comment (edewit) [reply js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx]: right, we still need the slice for the root groups

**Review by agagancarczyk — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]
