### PR TITLE
Client 'admin-permissions' doesn't have protocol set.

### LINKED ISSUE #38765: Client 'admin-permissions' doesn't have protocol set.
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

There is a warning in logs:

```
Client 'admin-permissions' doesn't have protocol set. Fallback to openid-connect. Please fix client configuration
```

We should set the OIDC protocol as the protocol for this client.

### Version

999.0.0-SNAPSHOT

### Regression

- [ ] The issue is a regression

### Expected behavior

Protocol set to the admin permission client

### Actual behavior

Protocol not set to the admin permission client

### How to Reproduce?

Run multiple evaluations and you'll see eventually this message in logs

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vramik**
Closes #38765

### CODE REVIEW

File: server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java [hunk 1]
```diff
@@ -281,6 +281,7 @@ public void init(KeycloakSession session, RealmModel realm) {
         }
 
         client = clients.addClient(realm, Constants.ADMIN_PERMISSIONS_CLIENT_ID);
+        client.setProtocol("openid-connect");
```
Comment (pedroigor) [inline server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java:284]:
```suggestion
        client.setProtocol(org.keycloak.protocol.oidc.OIDCLoginProtocol.LOGIN_PROTOCOL);
```

**Review by pedroigor — APPROVED** [review]
