### PR TITLE
fix: adding imagePullSecret to update job

### LINKED ISSUE #39015: Keycloak operator with update strategy to Auto: missing imagePullSecrets
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

# `imagePullSecrets` not used in k8s Job for automatic rolling updates

## Description

I’m trying to use the new [automatic rolling updates](https://www.keycloak.org/operator/rolling-updates) feature introduced in the Keycloak Operator.

However, it seems that the `imagePullSecrets` defined in the `Keycloak` custom resource is **not** applied to the Kubernetes Job used by the operator to detect whether a rolling or recreate update is needed.

This leads to the detection Job failing with an image pull error when using a private image registry:

```
Failed to pull image "harbor.imio.be/common/keycloak:26.2.0-imio-0": failed to pull and unpack image "harbor.imio.be/common/keycloak:26.2.0-imio-0": failed to resolve reference "harbor.imio.be/common/keycloak:26.2.0-imio-0": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials
```

### Version

26.2.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The Job created by the operator to evaluate the rolling update strategy should inherit or use the same `imagePullSecrets` as defined in the `Keycloak` CR, to allow access to private registries.

### Actual behavior

The k8s Job failing with an image pull error when using a private image registry

### How to Reproduce?

The keycloak tenant YAML file I used:

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: staging-kc-apps
spec:
  instances: 1
  image: harbor.imio.be/common/keycloak:26.2.0-imio-0
  imagePullSecrets:
    - name: harbor-secret
  update:
    strategy: Auto 
  db:
    usernameSecret:
      name: keycloak-apps-secret
      key: db_username
    passwordSecret:
      name: keycloak-apps-secret
      key: db_password
    port: 5432
    database: common_keycloak_apps
    host: 10.7.121.7
    vendor: postgres
  hostname:
    hostname: https://keycloak-apps.cloud.imio-test.be
    admin: https://admin.keycloak-apps.cloud.imio-test.be
  ingress:
    enabled: false
  http:
    httpEnabled: true
    tlsSecret: keycloak-apps-secret-tls
  additionalOptions:
    - name: metrics-enabled 
      value: 'true'
  features:
    enabled:
      - preview
  resources:
    requests:
      cpu: 500m
      memory: 1700Mi
    limits:
      cpu: 1000m
      memory: 2000Mi
```

### Anything else?

Let me know if you need any additional information or testing on my side.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #39015

@ahus1 @pruivo @vmuzikar I believe that we have quite a few corner cases yet to address with the auto job logic, not just to address image pull secrets. I tried to add TODOs where there are additional concerns.

At a high level:

- usage of the unsupported pod template could cause things to fail or be inaccurate in several ways.

- starting with the desired state pod spec will copy over additional settings like the imagePullSecrets, but we still end up needing merge logic to the existing state, so it doesn't actually save us that much effort. We only have merge logic for the imagePullSecrets and volumes. We may have to review if anything else seems applicable - or what we may need to do to keep the logic in sync with what the main deployment logic is doing.

- having the auto strategy work with start-dev is problematic because of the profile change - we can account for that, or probably just fail / recreate if someone is using start-dev

### CODE REVIEW

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java [hunk 1]
```diff
@@ -127,56 +123,66 @@ private void addPodSpecTemplate(JobSpecFluent<?> builder, Keycloak keycloak, Con
...
-        addInitContainer(builder, context, allVolumes.keySet(), requiredVolumes);
-        addContainer(builder, context, allVolumes.keySet(), requiredVolumes);
+
+        // remove things we don't want
+
+        // TODO: this may actually not be correct - via the unsupported PodTemplate someone could make configuration dependent upon an init container
+        builder.withInitContainers();
+        builder.withContainers();
+
+        // TODO: should the scheduling fields be tweaked
```
Comment (ahus1) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:139]: I'd say it would be usually safe to keep them as is. Some people would want to run Keycloak only on specific nodes, and could for example also ensure that it runs only on ARM architecture nodes. 

As an alternative, we might eventually add some separate scheduling to the upgrade part of the CR. Until then, I think we're good to keep it as is.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java [hunk 2]
```diff
@@ -127,56 +123,66 @@ private void addPodSpecTemplate(JobSpecFluent<?> builder, Keycloak keycloak, Con
...
+
+        // mix in the existing state
+        var currentSecrets = builder.buildImagePullSecrets();
+        current.getSpec().getTemplate().getSpec().getImagePullSecrets().stream().filter(s -> !currentSecrets.contains(s)).forEach(builder::addToImagePullSecrets);
+        // TODO: if the name is the same, but the volume has changed the behavior will be inconsistent
```
Comment (ahus1) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:144]: I'd say if we would make the volume name a bit more specific we should be good for now. 

See above for a suggestion.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java [hunk 3]
```diff
@@ -41,17 +45,12 @@
...
-import org.keycloak.operator.Utils;
-import org.keycloak.operator.crds.v2alpha1.CRDUtils;
-import org.keycloak.operator.crds.v2alpha1.deployment.Keycloak;
 
 @ApplicationScoped
 public class KeycloakUpdateJobDependentResource extends CRUDKubernetesDependentResource<Job, Keycloak> {
 
     // shared volume configuration
-    private static final String WORK_DIR_VOLUME_NAME = "workdir";
+    private static final String WORK_DIR_VOLUME_NAME = "workdir"; // TODO: could conflict with an existing volume name
```
Comment (ahus1) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:53]: Let's try to make it unique. Alternatively we could make it non-static and add a random suffix. 

```suggestion
    private static final String WORK_DIR_VOLUME_NAME = "update-job-temporary-workdir";
```

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java [hunk 4]
```diff
@@ -194,24 +200,11 @@ private static void configureContainer(ContainerFluent<?> containerBuilder, Stri
...
-        return currentArgs.stream().
-                <String>mapMulti((arg, downstream) -> {
-            if (START_ARGS.contains(arg)) {
-                updateArgs.forEach(downstream);
-                return;
-            }
-            downstream.accept(arg);
-        }).toList();
+        // TODO: reuse ConfigArgConfigSource parsing
+        // also start-dev is problematic - at the very least --profile=dev should be added
```
Comment (ahus1) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:205]: I wonder how a `start-dev` would end up here ... again via a `podTemplate`? I'd say this is not supported when using the Operator?

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java [hunk 5]
```diff
@@ -127,56 +123,66 @@ private void addPodSpecTemplate(JobSpecFluent<?> builder, Keycloak keycloak, Con
...
+        // start off with the desired statefulset state
+        var builder = desired.getSpec().getTemplate().getSpec().edit();
         builder.withRestartPolicy("Never");
-        addInitContainer(builder, context, allVolumes.keySet(), requiredVolumes);
-        addContainer(builder, context, allVolumes.keySet(), requiredVolumes);
+
+        // remove things we don't want
+
+        // TODO: this may actually not be correct - via the unsupported PodTemplate someone could make configuration dependent upon an init container
+        builder.withInitContainers();
```
Comment (ahus1) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:136]: Copying over init containers might be a good thing. But as PodTemplate is not supported, might do a best effort here. 

Reading up on init containers, it seems that they run sequentially. So we could then add ours at the end.

**Review by ahus1 — COMMENTED** [review]
Thank you for looking into this issue and creating both the PR and the list of TODOs.

With the imagePullSecret fixed, I'd say once we make the name of the workdir volume a bit more specific to avoid clashes, I consider this PR ready to be merged.

Optional: Copying over init containers could be part of this PR if we think this is a low-hanging fruit, or a follow-up. AFAIK the init containers run sequentially, and we could add ours at the end which should be fine. 

There was a new comment in the parent issue about the imagePullPolicy, not sure if this is really not picked up and where this would be missing. 

I don't really understand how a start-dev would end up in here. If it is via a `podTemplate`, I'd say it is not supported. If there is no simple way to handle it beyond also replacing `start-dev` or adding a profile, I'd say failing and then recreate is fine. I would assume that it is failing today already, as the init container wouldn't create the JSON, and then the second one wouldn't be able to read it.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java (hunk 4 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:205]: Yes, the podTemplate is the only way to use start-dev.

If we are ok with letting the job fail to start, then I can just minimize this comment and move on - this in general is a misconfiguration because you'd have to go to great lengths to cluster in dev mode.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java (hunk 2 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:144]: This concerns is about a difference between the desired and existing state. Lets say in the existing state you have a volume name config pointed at configmap X, and in the desired state you a volume also named config pointed at configmap Y - we are not accounting for that possibility.

This could happen with more than just via the unsupported podTemplate, such as via the cache config configmap.

If we want to account for this we'll need to do a name remapping as part of the merge.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java (hunk 1 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:139]: > Until then, I think we're good to keep it as is.

I'm fine with that, just wanted to highlight a behavioral difference between what the logic was doing and will now do. Let's just expand the comment to explain why keeping the scheduling is ok.

**Comment by shawkins** [comment]
> There was a new comment in the parent issue about the imagePullPolicy, not sure if this is really not picked up and where this would be missing.

I don't believe the comment is correct. imagePullPolicy is inherited at the container level. I believe they are just seeing the same issue with imagePullSecrets.

> I don't really understand how a start-dev would end up in here. If it is via a `podTemplate`, I'd say it is not supported. If there is no simple way to handle it beyond also replacing `start-dev` or adding a profile, I'd say failing and then recreate is fine. I would assume that it is failing today already, as the init container wouldn't create the JSON, and then the second one wouldn't be able to read it.

Yes, hopefully we can just let it fail rather than adding more logic to gracefully handle an unsupported situation.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java (hunk 1 above)
Comment (ahus1) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:139]: agreed, lease expand the comment.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java (hunk 2 above)
Comment (ahus1) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:144]: Thank you, I now see your point. I'd say this is in the unsupported space, and within the margin of error when we accept it as-is now.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java (hunk 4 above)
Comment (ahus1) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java:205]: I'm ok with letting it fail to start.

**Comment by shawkins** [comment]
> Are we ready to wrap the low-hanging and obvious items (renaming the workdir, extending the comment) in this PR?

As long as you are good with not accounting for volume changes, like a change in cache config configmap, then I can wrap this up.

**Comment by shawkins** [comment]
The comments and volume / mount names have been updated, should be ready for review.

**Review by ahus1 — DISMISSED** [review]

**Comment by ahus1** [comment]
Follow-up issue for the docs: https://github.com/keycloak/keycloak/issues/39059

**Review by ahus1 — APPROVED** [review]
