### PR TITLE
Provide an option to force login after reset credentials

### LINKED ISSUE #36844: Provide an option to force login after reset credentials
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Provide an option for the [forget link (reset credentials)](https://www.keycloak.org/docs/latest/server_admin/#enabling-forgot-password) flow to force re-login after resetting the password with the email link. Currently the user remains logged in if the same auth session (same browser) is used. The main reason is that the reset credentials link is using an [action token](https://www.keycloak.org/docs/latest/server_development/#_action_token_handler_spi). This is not a problem with keycloak but maybe there are external storages that allow the password change and not the login for the same user.

### Version

26.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The user should re-login after the reset credentials.

### Actual behavior

N/A

### How to Reproduce?

N/A

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #36844

Just adding the option in the `Send Reset Email`. Default behavior without the configuration is the same one used today to maintain compatibility. Tests added.

I have not added a release note because this is a minor change. But if you think it is needed just let me know about it and I'll add a little one.

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]

File: services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java [hunk 1]
```diff
@@ -33,7 +33,9 @@
 import org.keycloak.models.*;
```
Comment (graziang) [inline services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java:33]: not introduced by this PR, but this import with * caught my eye. This could be a good opportunity to replace it with single imports.

**Review by graziang — APPROVED** [review]
LGTM @rmartinc, added just a minor comment.

File: services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java (hunk 1 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java:33]: okis, I'll change to use the imports individually...

Comment (rmartinc) [reply services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java]: Done!

**Review by mposolda — DISMISSED** [review]

File: docs/documentation/release_notes/topics/26_1_1.adoc [hunk 2]
```diff
@@ -3,3 +3,9 @@
...
 
 The value `false` is maintained for compatibility with the previous behavior. Note that existing configurations will not have the new option and will act as if this option was set to `false`, but the Admin Console will add the default value `true` on edit.
+
+= New option in Send Reset Email to force a login after reset credentials
+
+The `reset-credential-email` (*Send Reset Email*) is the authenticator used in the *reset credentials* flow (*forgot password* feature) for sending the email to the user with the reset credentials token link. This authenticator now has a new option `force-login` (*Force login after reset*) which, when set to `true`, terminates the session and forces a new login after the password change.
```
Comment (andymunro) [inline docs/documentation/release_notes/topics/26_1_1.adoc:9]:
```suggestion
The `reset-credential-email` (*Send Reset Email*) is the authenticator used in the *reset credentials* flow (*forgot password* feature) for sending the email to the user with the reset credentials token link. This authenticator now has a new option `force-login` (*Force login after reset*). When this option is set to `true`, the authenticator terminates the session and forces a password change before a new login.
```

File: docs/documentation/server_admin/topics/login-settings/forgot-password.adoc [hunk 3]
```diff
@@ -27,7 +27,7 @@ image:images/forgot-password-page.png[Forgot Password Page]
 
 The text sent in the email is configurable. See link:{developerguide_link}[{developerguide_name}] for more information.
 
-When users click the email link, {project_name} asks them to update their password, and if they have set up an OTP generator, {project_name} asks them to reconfigure the OTP generator.  Depending on security requirements of your organization, you may not want users to reset their OTP generator through email. 
+When users click the email link, {project_name} asks them to update their password, and if they have set up an OTP generator, {project_name} asks them to reconfigure the OTP generator. By default the flow maintains the user logged in if the same authentication session (same browser) was used. Depending on security requirements of your organization, you may not want users to reset their OTP generator through email and/or you may want to force them to re-login after the process.
```
Comment (andymunro) [inline docs/documentation/server_admin/topics/login-settings/forgot-password.adoc:30]:
```suggestion
When users click the email link, {project_name} asks them to update their password, and if they have set up an OTP generator, {project_name} asks them to reconfigure the OTP generator. By default, the flow maintains the user who is logged in if the same authentication session (same browser) was used. Depending on the security requirements of your organization, you may not want users to reset their OTP generator through email or you may want to force them to login again after the process.
```

File: docs/documentation/server_admin/topics/login-settings/forgot-password.adoc [hunk 4]
```diff
@@ -40,6 +40,11 @@ To change this behavior, perform these steps:
 image:images/reset-credentials-flow.png[Reset Credentials Flow]
 +
 If you do not want to reset the OTP, set the `Reset - Conditional OTP` sub-flow requirement to *Disabled*.
++
+.Send Reset Email Configuration
+image:images/reset-credential-email-config.png[Send Reset Email Configuration]
++
+If the user needs to re-login after the password change, click *Send Reset Email* settings icon in the flow, define an *Alias* and set *Force login after reset* to *On*.
```
Comment (andymunro) [inline docs/documentation/server_admin/topics/login-settings/forgot-password.adoc:47]:
```suggestion
If the user needs to login again after the password change, click the *Send Reset Email* settings icon in the flow, define an *Alias*, and enable *Force login after reset*.
```

**Review by andymunro — CHANGES_REQUESTED** [review]
@rmartinc looks good with a few suggestions.

File: docs/documentation/release_notes/topics/26_1_1.adoc (hunk 2 above)
Comment (andymunro) [reply docs/documentation/release_notes/topics/26_1_1.adoc:9]: Okay, that works. Thanks.

**Review by andymunro — APPROVED** [review]
Approved with the changes recommended.

**Review by mposolda — APPROVED** [review]
