### PR TITLE
Better caching for federated users

### LINKED ISSUE #35637: Inconsistency when returning user attributes when executing a seach or fetching users by ID from external user storage providers
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

The user attributes are fetched differently when executing searches and fetching users by their identifiers.

When running a search, the external user storage provider is called and eventually returns a `UserModel` that fetches the user attributes from their storage.

However, when querying users by their identifiers where the user is already cached the user attributes will have their values fetched from the cache, which can be different than the value from the external user storage. This is especially true when the user storage provider is updated directly without necessarily going through the server.

This issue is mainly impacting the LDAP user storage provider, for now. But it should apply to any other user storage provider (including custom ones). The LDAP mappers that support the setting `Always read value from LDAP` will not work as expected because values won't be (always) read from LDAP if the user is already cached.

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The user attribute values are the same when fetching users using a search and when querying by their identifier.

### Actual behavior

The user attribute values are not the same when fetching users using a search and when querying by their identifier.

### How to Reproduce?

* Create an LDAP provider and make sure the mapper corresponding to the `firstName` has the `Always read value from LDAP` enabled
* Import a user from LDAP
* Change the value of the `firstName` attribute in LDAP
* Go to `Users` to list all realm users and see the `firstName` attribute set with the value from LDAP
* Try to edit the user and see the `firstName` attribute with a different value

### Anything else?

See https://github.com/keycloak/keycloak/issues/34954#issuecomment-2515431058.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #35637

The PR performs mainly two changes in the infinispan caching to make it consistent with user federation providers (like ldap):

1. The local `UserStorageManager` (used in ldap when import users is ON) does not enforce the validation if the returned user is cached. The cached user will be valid for the configured cache time and will be validated from ldap when it needs to be refreshed (cache time is expired). The users were already cached (not validated) for other methods like `getUserById` or `getUserByUsername` so I think it's OK.
2. The infinispan impl also adds the users returned by the `searchForUserStream` methods into the cache. The DB implementation already performs this, so we are already doing this in general. This point makes a little change in the `addRevisioned` method in `CacheManager` (`put` is used instead of `putForExternalRead`, because the latter only adds the user if not present like  `putIfAbsent`). This change is to cache the new user refreshed from the external storage (we can also return the cached one, but I think that this makes more sense, the user is refreshed from the provider so it's up to date). As this cache is always a local cache, I think it's OK and it's not a performance drawback. 

The change (in theory) improves the search for users in ldap in two ways. When importing into the DB, the search for users does not validate the cached users (avoiding the ldap access for each user if cached). When not importing, the search in the ldap caches the returned users from ldap for other operations. It can have a performance drawback too, because there are some minor changes. So probably we need to test ldap performance in general. Is there some tests/CI we can check for this?

It's a draft because I don't know if we want to follow this path.

@mposolda @pedroigor @sguilhen WDYT?

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java [hunk 1]
```diff
@@ -589,29 +589,37 @@ public int getUsersCount(RealmModel realm, Map<String, String> params, Set<Strin
...
+            // just return if the entry is an already cached entry of this provider
+            return delegate;
+        }
+        return cacheUser(realm, delegate, cache.getCurrentRevision(delegate.getId()));
+    }
+
     @Override
     public Stream<UserModel> searchForUserStream(RealmModel realm, String search) {
-        return getDelegate().searchForUserStream(realm, search);
+        return getDelegate().searchForUserStream(realm, search).map(u -> updateCache(realm, u));
```
Comment (mposolda) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:602]: I have a little bit of fear of the scenario, when user storage provider returns some way of "lightweight" user from the "search" operations.

For example some user-storage implementation `myUserStorageProvider` where method `searchForUserStream` returns `UserModel` instances with only filled `id` and `username`. As it is an assumption that if admin is interested about particular user `john`, he will then call subsequent call `getUserById`, which is then supposed to return "full" user with all the attributes filled.

If we do the change in this PR, it means that "lightweight" users will be added to the cache, which could then cause issues as subsequent `getUserById` will then also returns this "lightweight" user...

Could this be an issue?

If it could be an issue, the alternative might be to invalidate the users from cache, which are returned by the `search` operations? This will fix the "inconsistency" problem . At the same time, it will have performance impact (the "search" operations are probably not called very often as those are "admin" operations AFAIK, so not sure how much bad is the performance impact...)

Comment (rmartinc) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:602]: Yes, that could be an issue. In that case maybe we should just return the cached user instead of the returned user in the store. Not caching anything in searches.

Comment (mposolda) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java:602]: Yes, that is also an option. And IMO it is better than current behaviour with "inconsistent" results returned from `search` operations and from operations like `getUserById` . So my vote is to go that path (if @pedroigor and @sguilhen are fine with that).

Comment (rmartinc) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java]: Modified `searchForUserStream` to return the cached entry if present and not cache new entries.

**Review by sguilhen — APPROVED** [review]
Tested the PR locally and it fixes the inconsistency when searching users that are already cached.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java (hunk 1 above)
Comment (rmartinc) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java]: @mposolda @sguilhen I'm moving this draft to normal PR as we decided that this is just a bug and no upgrading notes are needed. :smile:

**Review by mposolda — APPROVED** [review]
Changes LGTM

@pedroigor Assigning PR to you, so you can merge if you are OK with the changes (As it is more a core-iam area).
