### PR TITLE
Show length validations in the admin UI

### LINKED ISSUE #42178: Integer validation error not shown for user profile fields
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

When I create a field in the user profile and add a length min/max validation to it, the error message doesn't show in the admin UI, the user is not saved, and an exception is shown in the console.  

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The validation error should be shown.

### Actual behavior

No validation error is shown

### How to Reproduce?

Create a new field and add a length validation to it

Image

Image

### Anything else?

The problem is that the length validation error adds integer parameters, while front end only expects strings.  

I'll provide a fix.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #42178

### CODE REVIEW

**Comment by ahus1** [comment]
@keycloak/ui - happy to get your feedback on this change, and if additional tests would be needed. Thanks!

File: js/libs/ui-shared/src/user-profile/utils.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ export type UserFormFields = Omit<
 type FieldError = {
   field: string;
   errorMessage: string;
-  params?: string[];
+  params?: any[];
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/utils.ts]: Instead of `any`, a better type would be `unknown`, which will force the compiler to error unless the type of the value is checked at runtime (e.g. `typeof params === 'string'`).
```suggestion
  params?: unknown[];
```

File: js/libs/ui-shared/src/user-profile/utils.ts [hunk 2]
```diff
@@ -24,7 +24,11 @@ export type UserProfileError = {
   responseData: ErrorArray | FieldError;
 };
 
-const isBundleKey = (displayName?: string) => displayName?.includes("${");
+const isBundleKey = (displayName?: any) => {
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/utils.ts]: Same here, can be `unknown`, you might even drop the optionality here, as `null` and `undefined` should also be covered by the `unknown` type.
```suggestion
const isBundleKey = (displayName?: unknown) => {
```

Or possibly:
```suggestion
const isBundleKey = (displayName: unknown) => {
```

**Comment by ahus1** [comment]
@jonkoops - please re-review. Thanks!

**Review by jonkoops — APPROVED** [review]
