### PR TITLE
change the realm selector into a section

### LINKED ISSUE #38112: Worse UX with new realm selector
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The newly introduced realm selector has some usability concerns, and honestly doesn't look very polished either.

Some issues I've identified:

* Placement on the top menu is not ideal at least not for my usual flows; my usual flow is to focus on the left hand menu, and with the old placement in the left menu it was quicker to glance at what realm was active, and change the realm is needed. Now I need to focus both my eyes and the mouse on a different place in the UI
* There's a lot of noise as there is now 3 elements (label + dropdown + create realm), this makes it look rather unpolished
* It's very close to and distracts from the Keycloak logo, which visually isn't very pleasing
* With less than 10 realms the drop-down has "Current realm", "Recently used", and the rest. This means I need to look two places when switching to a realm. First looking in recently used, then it all the rest. I don't think there should be recently used at all when there is 10 realms or less, just list the current realm, then the rest
* The dropdown has entries that are multi lines if a realm has display name set. This makes the dropdown awkward as the size of the elements differ. I would rather just show the display name if there is one, otherwise realm name. Alternatively some way of showing both on a single line would be okay
* The dropdown is very narrow if there is no realms with a long display name or realm name; would be good to have a minimum-width set
* Create realm isn't something that is used super frequently; while now it takes up pretty much the most valuable real estate on the UI

### Version

main

### Regression

- [x] The issue is a regression

### Expected behavior

Better UX

### Actual behavior

Worse UX

### How to Reproduce?

Open the admin UI ;)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #38112

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

make realms a section and remove realm selector

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

File: js/apps/admin-ui/src/realm/RealmSection.tsx [hunk 1]
```diff
@@ -0,0 +1,268 @@
...
+    titleKey: t("deleteConfirmRealm", {
+      count: selected.length,
+      name: selected[0]?.name,
+    }),
+    messageKey: "deleteConfirmRealmSetting",
+    continueButtonLabel: "delete",
+    onConfirm: async () => {
+      try {
+        if (selected.filter(({ name }) => name === "master").length > 0) {
+          addAlert(t("cantDeleteMasterRealm"), AlertVariant.warning);
```
Comment (ssilvert) [inline js/apps/admin-ui/src/realm/RealmSection.tsx:164]: I think `cantDeleteMasterRealm` is missing?

**Review by ssilvert — CHANGES_REQUESTED** [review]

**Review by ssilvert — CHANGES_REQUESTED** [review]
It would be helpful if the search also searched on description as well as realm name.  I've seen customers that use cryptic realm names where searching on the realm name would not be helpful.

**Comment by edewit** [comment]
We can't search on description as it's a realm attribute that can also be translated if we really want to make that, it would mean migrating the display name into a actual property

**Review by ssilvert — APPROVED** [review]
Looks good.
