### PR TITLE
Make group filter case-insensitive

### LINKED ISSUE #32419: Joining group with text filter does not show all results even if backend returned them
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In Users -> Groups page, joining group and entering a text filter, e.g. "pro" in my case, there should be three results ("Intranet - Project Coordinator", "Intranet - Project Manager" and "project-test") 
They are correctly represented in record number in bottom right, also in the backend response 
(groups?first=0&max=11&search=pro)

[
    {
        "id": "65ccda8c-d10d-4891-a3c6-0ff4466b16e0",
        "name": "Intranet - Project Coordinator",
        "path": "/Intranet - Project Coordinator",
        "subGroupCount": 0,
        "subGroups": [],
        "access": {
            "view": true,
            "viewMembers": true,
            "manageMembers": true,
            "manage": true,
            "manageMembership": true
        }
    },
    {
        "id": "d9c7ba25-aa85-4664-a296-4d69deec401a",
        "name": "Intranet - Project Manager",
        "path": "/Intranet - Project Manager",
        "subGroupCount": 0,
        "subGroups": [],
        "access": {
            "view": true,
            "viewMembers": true,
            "manageMembers": true,
            "manage": true,
            "manageMembership": true
        }
    },
    {
        "id": "9de53528-3008-4507-8ca7-dafff4ff4bcd",
        "name": "project-test",
        "path": "/project-test",
        "subGroupCount": 0,
        "subGroups": [],
        "access": {
            "view": true,
            "viewMembers": true,
            "manageMembers": true,
            "manage": true,
            "manageMembership": true
        }
    }
]

But only one result is shown in the frontend page:

image

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Three results should also be shown in the frontend page

### Actual behavior

Only one result is shown in the frontend tab, even if record number and backend response contain three results.

### How to Reproduce?

1. Create following groups: "Intranet - Project Coordinator", "Intranet - Project Manager", "project-test"
2. Try to join group by searching "pro" in text filter
3. Only project-test is shown

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ssilvert**
Fixes #32419

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Review by agagancarczyk — APPROVED** [review]

File: js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx [hunk 1]
```diff
@@ -224,7 +224,10 @@ export const GroupPickerDialog = ({
         <DataList aria-label={t("groups")} isCompact>
           {groups.slice(0, max).map((group: SelectableGroup) => (
             <Fragment key={group.id}>
-              {(!isSearching || group.name?.includes(filter)) && (
+              {(!isSearching ||
+                group.name
+                  ?.toLocaleUpperCase()
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx:229]: Why use `.toLocaleUpperCase()` over `.toUpperCase()`? No locale is explicitly passed, nor would it change the amount of resulting matches.

Comment (ssilvert) [reply js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx:229]: I assumed that .toLocaleUpperCase() might be able to detect the preferred locale (maybe from the browser?).  But I'm not sure if that's true.  It seems that if there is no other mechanism to detecting locale than passing a param then the no-arg version of the method should not be allowed, or at least detected by the linter.

Anyway, it doesn't make any difference.  Merging.
