### PR TITLE
Accept deprecated Hibernate datasource settings property

### LINKED ISSUE #37656: [Keycloak Integration CI] - Extension - Start keycloak failed
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
ERROR: Failed to start server in (development) mode
ERROR: Cannot invoke "Object.getClass()" because "val1" is null
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
Error: Process completed with exit code 4.
```
https://github.com/keycloak/keycloak-quickstarts/actions/runs/13536244746/job/37828366581#step:7:453

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Fixes #37656 

@shawkins Could you please check it? Thanks!

### CODE REVIEW

**Review by shawkins — DISMISSED** [review]
LGTM, is there already a migration guide entry for this?

**Comment by mabartos** [comment]
> LGTM, is there already a migration guide entry for this?

Right, I'll create one.

**Comment by mposolda** [comment]
@mabartos Do you have a plan to update this PR before Keycloak 26.2? Just checking as we have quickstarts PR waiting for this (quickstarts PR are failing now): https://github.com/keycloak/keycloak-quickstarts/pull/663 . So wondering if we should use deprecated property or wait for this one (CC @rmartinc ).

**Comment by mabartos** [comment]
@mposolda I'll use the deprecated option for now and update this PR. Thanks for bringing this up.

**Review by shawkins — DISMISSED** [review]
LGTM, thanks @mabartos

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java [hunk 1]
```diff
@@ -179,7 +179,7 @@ AgroalDataSource.class, new DataSource() {
                                 return name;
                             }
                         })) {
-                    propertyCollector.accept(AvailableSettings.JAKARTA_JTA_DATASOURCE, instance.get());
+                    propertyCollector.accept(isJta ? AvailableSettings.JAKARTA_JTA_DATASOURCE : AvailableSettings.JAKARTA_NON_JTA_DATASOURCE, instance.get());
```
Comment (rmartinc) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java:182]:
```suggestion
                    propertyCollector.accept(AvailableSettings.DATASOURCE, instance.get());
```

@mabartos This needs to use the old property because if not I receive this error:

```
Error details:
jakarta.persistence.PersistenceException: [PersistenceUnit: user-store] Unable to build Hibernate SessionFactory
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:129)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:89)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:163)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.connections.spi.ConnectionProvider] due to: A Datasource was configured as Connection Pool, but it's not the Agroal connection pool. In Quarkus, you need to use Agroal.
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:276)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:434)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:305)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:129)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:81)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:52)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
	at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:290)
	at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:72)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
	... 6 more
Caused by: org.hibernate.HibernateException: A Datasource was configured as Connection Pool, but it's not the Agroal connection pool. In Quarkus, you need to use Agroal.
	at io.quarkus.hibernate.orm.runtime.service.QuarkusConnectionProviderInitiator.initiateService(QuarkusConnectionProviderInitiator.java:41)
	at io.quarkus.hibernate.orm.runtime.service.QuarkusConnectionProviderInitiator.initiateService(QuarkusConnectionProviderInitiator.java:16)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	... 26 more
```
I think this error is more on the quarkus/hibernate side. They have changed the property to use the new externally but not internally, and the old one is used to create the datasource (the new one does not work). Then you can to remove the `isJta` parameter and be back to the previous method signature.

Tested the extension tests with old and new property.

**Review by rmartinc — CHANGES_REQUESTED** [review]
@mabartos The PR does not work with the quickstarts. In the creation part you need to still use the deprecated property. If not there is an exception. As commented this is more in quarkus/hibernate side.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java (hunk 1 above)
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java:182]: Thanks for checking this. In that case, to be safe, it'd be good to revert these changes and use the deprecated values for now.

The thing is that Quarkus does prefer using Quarkus props for the persistence unit settings and stuff related to that. They want to move on from the `persistence.xml`, but we still support it.

I'll try to push more on the Quarkus side and provide the functionality there.

@rmartinc Thanks for the review and test!

**Review by shawkins — APPROVED** [review]
I'm fine going back to what was already supported. Seems like we'll need to get the wildcard stuff fully staightened out before tackling the additional persistence related options as well.

**Review by rmartinc — APPROVED** [review]
Thanks @mabartos! This also works with the quickstarts. Approved!

**Comment by mabartos** [comment]
@shawkins @rmartinc Thanks for the review!
