### PR TITLE
Fix how the admin ui obtains its logo

### LINKED ISSUE #45733: Admin UI theme logo not displaying from theme properties
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The admin UI theming system does not properly display custom logos configured in theme properties, unlike the login and account themes which work correctly.

When setting a custom logo in the admin console theme settings, the logo does not appear in the admin UI header. The issue occurs because the PageHeader.tsx component incorrectly prioritizes empty preview logos over the actual theme logo from `environment.logo`.

### Version

26.5.2

### Regression

- [ ] The issue is a regression

### Expected behavior

- Admin UI should display the logo specified in theme.properties - Should behave consistently with login and account themes
- Preview functionality should still work during theme editing

### Actual behavior

- Admin theme logos from theme.properties are ignored
- Empty `customLogo` values override the theme logo
- Login and account themes work correctly with the same theme configuration

### How to Reproduce?

1. Create a custom theme with `logo=img/logo.png` in admin theme.properties
2. Deploy the theme to Keycloak
3. Set admin console theme to the custom theme
4. Observe that the custom logo does not appear in the admin header

### Anything else?

The issue is in js/apps/admin-ui/src/PageHeader.tsx line 116 where the logic uses `customLogo || joinPath(environment.resourceUrl, logo)`. The `customLogo` from LogoContext is often an empty string, which overrides the valid theme logo from `environment.logo`.

### PR DESCRIPTION
**Pull request by martwana**
## Description
Fixes the admin UI theming bug where custom logos from theme properties were not being displayed, making admin theming inconsistent with login and account themes.
## Problem
The PageHeader.tsx component was incorrectly prioritizing empty preview logos over actual theme logos. The logic `customLogo || joinPath(environment.resourceUrl, logo)` meant that even empty strings from the LogoContext would override the valid theme logo from `environment.logo`.
## Solution
Updated the logo source logic to only use custom logo when it has a meaningful value:
```typescript
src: (customLogo && customLogo.trim()) ? customLogo : joinPath(environment.resourceUrl, logo)
```

Fixes #45733

### CODE REVIEW

File: js/apps/admin-ui/src/PageHeader.tsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ const ServerInfoDropdownItem = () => {
   return (
     <DropdownItem
       key="server info"
-      component={(props) => <Link {...props} to={toDashboard({ realm })} />}
+      component={(props: React.ComponentProps<typeof Link>) => <Link {...props} to={toDashboard({ realm })} />}
```
Comment (ssilvert) [inline js/apps/admin-ui/src/PageHeader.tsx]: Is the type really needed here?

**Review by ssilvert — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/PageHeader.tsx (hunk 1 above)
Comment (martwana) [reply js/apps/admin-ui/src/PageHeader.tsx]: No, thats fair. Thinking about it, it doesn't add any safety and just adds bloat to the code. 

Removed.

**Review by ssilvert — DISMISSED** [review]

**Comment by ssilvert** [comment]
@martwana Looks like we have some linting errors to fix before this can be merged.

**Review by ssilvert — APPROVED** [review]
