### PR TITLE
Doublecheck if we need to override properties in java.security

### LINKED ISSUE #16702: Doublecheck if we need to override properties in java.security
So far, we have few properties overriden when running with `kc.java.security` file in our testsuite. But it is possible that we don't need to override almost anything and we can still achieve everything working. This issue is about doublecheck the overriden properties in `kc.java.security` and eventually skip overriding most of the properties in this file and also make sure that people don't need to override most of the properties in their own custom manually `java.security` properties file.

Right now, the `kc.java.security` file from testsuite override those:

1) It adds `XMLDSig` security provider, which is needed for SAML. This needs to be present right now and there is separate task for it #16326 . Due to this, we would still need to have custom `kc.java.security` property files, but possibly with all the other properties removed/commented in this file with the exception of this one (See below).
 
2) The properties:
```
keystore.type=PKCS12
fips.keystore.type=PKCS12

ssl.TrustManagerFactory.algorithm=PKIX
fips.ssl.TrustManagerFactory.algorithm=PKIX
```
already have same values like the default `JAVA_HOME/conf/security/java.security` from OpenJDK17 on FIPS enabled RHEL VM. So hopefully we can just comment those properties in our `kc.java.security` ?

3) The property:
```
ssl.KeyManagerFactory.algorithm=PKIX
fips.ssl.KeyManagerFactory.algorithm=PKIX
```
has different value than default `JAVA_HOME/conf/security/java.security`. When this property is removed from the `kc.java.security` file, then some X.509 tests and authorization-adapter tests are failing (see my comment below).

So this task is mostly down to the investigation of the last property (3).

Can we just manually set this property programatically somewhere in `FIPS1402Provider` initialization with `Security.setProperty("ssl.KeyManagerFactory.algorithm", "PKIX");` ? Or would it have any bad side-effect if we do this? It will be good to doublecheck why the `X.509` tests and authorization-adapter tests are failing when this property is not overriden. Could this be related to the fact that the other party is using older algorithms for it's keys during SSL handshake? Or some completely different reason?

### LINKED ISSUE #17106: FIPS tests marked in GH actions as passing even if they are failing
For example see this PR https://github.com/keycloak/keycloak/pull/16876 and then click to `FIPS IT (non-strict)` from the list of GH actions tests and then click to `Run base tests` when you have underlying PR opened.

There are 2 issues:
- FIPS tests are marked as passing even if they are failing. This needs to be changed to actually make sure that GH actions are failing when any FIPS test failing. Looks like the issue is, that docker command returns `0` even if testsuite failing? Hopefully we can figure it

- Fix testsuite failures itself. Looks like some of the failures are caused by the `KeycloakFipsSecurityProvider.isSystemFipsEnabled` doesn't properly work in GH actions fips environment. As step1, we can possibly just comment calling of `KeycloakFipsSecurityProvider.isFipsEnabled` ? Then we can try to make it working as a follow-up though?

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/16702

Changing our `kc.java.security` to be again default `ssl.KeyManagerFactory.algorithm=SunX509`. The `FIPS1402Provider` now forces implementations for `KeyManagerFactory` and `TrustManagerFactory` if the default one is missing when inserting the BCJSSE provider.

Setting `--add-opens=java.base/java.security=ALL-UNNAMED` to the scripts after https://github.com/keycloak/keycloak/issues/12428 to enable the FIPS detection in RH JDK 17. Changing warn message to debug too because JDK-17 tests fail with non RH JDKs (temurin for example with `KcAdmTest` or `KcRegTest`, the warn message interferes with the output and the tests fail). I have also added `set -o pipefail` to the IT script because the pipe make it return 0 with failed maven. So this also closes #17106 and #17108.

With this one the only addition needed is `fips.provider.7=XMLDSig` which is pending in [openjdk](https://bugzilla.redhat.com/show_bug.cgi?id=1940064).

### CODE REVIEW

File: testsuite/integration-arquillian/servers/auth-server/common/fips/kc.java.security [hunk 1]
```diff
@@ -40,11 +40,8 @@ fips.keystore.type=PKCS12
 # This is needed especially if we cannot add security provider "com.sun.net.ssl.internal.ssl.Provider BCFIPS" as a security provider.
 # OpenJDK has "SunX509" as default algorithm, but that one is not supported by BCJSSE. So adding the Sun provider delegating to BCFIPS is needed (as above)
 # or changing default algorithm as described here
-ssl.KeyManagerFactory.algorithm=PKIX
-fips.ssl.KeyManagerFactory.algorithm=PKIX
-
+ssl.KeyManagerFactory.algorithm=SunX509
```
Comment (mposolda) [inline testsuite/integration-arquillian/servers/auth-server/common/fips/kc.java.security:43]: Minor: the value is not aligned with what is mentioned above in the comment. IMO it can be better to just comment those options?

But this is not a blocker for this PR IMO (I can change in the follow-up though...)

**Review by mposolda — DISMISSED** [review]
@rmartinc Thanks! Added one comment inline, but not a blocker for this PR IMO.

File: testsuite/integration-arquillian/servers/auth-server/common/fips/kc.java.security (hunk 1 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/servers/auth-server/common/fips/kc.java.security]: You are right, I have modified `kc.java.security` to just contain the XMLDSig line. Let's see the tests...

**Review by mposolda — APPROVED** [review]
