### PR TITLE
Use an original domain name of Kerberos Principal in UserModel attrib…

### LINKED ISSUE #20045: Use an original domain name of Kerberos Principal in UserModel attribute instead of configured value of Kerberos realm in User federation
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

There are 2 Active Directory domains (EXAMPLE1.COM and EXAMPLE2.COM) which have mutual trust.
Configuring User Federation of kerberos against one of them (EXAMPLE**1**.COM), RH-SSO/Keycloak can authenticate user1@EXAMPLE**2**.COM against the domains.
However, the "KERBEROS_PRINCIPAL" attribute in UserModel is "user1@EXAMPLE**1**.COM". It should be "user1@EXAMPLE**2**.COM".

### Version

21.0.2/upstream

### Expected behavior

It should be "user1@EXAMPLE**2**.COM".

### Actual behavior

"user1@EXAMPLE**1**.COM".

### How to Reproduce?

1. Setup AD domains of EXAMPLE1.COM and EXAMPLE2.COM then make mutual trust between them
2. configure Keycloak User federation so that it authenticates users agaist EXAMPLE1.COM
3. log in Keycloak as user1@EXAMPLE2.COM

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
…ute instead of configured value of Kerberos realm in User federation

closes #20045

This PR addresses issue when single LDAP/Kerberos provider allows to authenticate users from multiple kerberos realms (which are in trust among each other). It does somehow what is mentioned here https://github.com/keycloak/keycloak/issues/20045#issuecomment-1554268105 . Despite the last point with the fallback between multiple LDAP storage providers, which is different issue and handled in the PR https://github.com/keycloak/keycloak/pull/22531 (Both are related to trust scenarios, but that one is multiple LDAP providers to single kerberos realm when this one is possibly single LDAP provider to multiple Kerberos realms). 

The `SPNEGOAuthenticator` returns whole authenticated kerberos principal without cutting realm from it, so LDAP provider is able to lookup proper user based on the kerberos principal. The LDAP attribute where Kerberos principal is saved unfortunately differs among LDAP servers, so added configuration option `Kerberos principal attribute` to have some flexibility here.

The `KerberosFederationProvider` uses whole authenticated principal instead of just username chained with configured realm, which ensures that correct realm is used.

For backwards compatibility, when the attribute is left empty, it sticks to the previous behaviour and tries to find the LDAP user with same username as the prefix of kerberos principal without realm. This might be needed as it is possible that some LDAP servers don't support specific attribute with kerberos principal name (however looks that all LDAP servers we support have this).

@ahus1 Could you please review from the store team or delegate to someone?
@ssilvert Could you please review the UI related changes or delegate to someone from the UI team?
@andymunro  Could you please review documentation changes?
@miquelsi  Adding you as reviewer too as this can be needed to be tested with our LDAP pipeline though to make sure it works with all our LDAP servers. It's possible that some new things would need to be added to the properties files, which we use in LDAP pipeline. For MSAD, the property file might need:
```
idm.test.kerberos.principal.ldap.attribute=userPrincipalName
```

And for RHDS/FreeIPA maybe something like this (not 100% sure about the attribute name in RHDS, just tried FreeIPA):
```
idm.test.kerberos.principal.ldap.attribute=krbPrincipalName
```

### CODE REVIEW

File: common/src/main/java/org/keycloak/common/constants/KerberosConstants.java [hunk 1]
```diff
@@ -71,6 +71,11 @@ public class KerberosConstants {
     public static final String SERVER_PRINCIPAL = "serverPrincipal";
     public static final String KEYTAB = "keyTab";
     public static final String DEBUG = "debug";
+    public static final String KERBEROS_PRINCIPAL_ATTRIBUTE = "krbPrincipalAttribute";
+    public static final String KERBEROS_PRINCIPAL_LDAP_ATTRIBUTE_KRB5_PRINCIPAL_NAME = "krb5PrincipalName"; // Used for instance in ApacheDS
```
Comment (pedroigor) [inline common/src/main/java/org/keycloak/common/constants/KerberosConstants.java:75]: @mposolda Isn't possible to infer the LDAP attribute name based on the vendor? Wondering if it helps to avoid forcing admins to save typing when creating the provider for well-known vendors.

**Review by jonkoops — DISMISSED** [review]
Changes on the client side look good to me.

**Review by sguilhen — APPROVED** [review]
From a storage perspective, the changes also look good to me

**Comment by mposolda** [comment]
@sguilhen @jonkoops Thanks for the review!

File: common/src/main/java/org/keycloak/common/constants/KerberosConstants.java (hunk 1 above)
Comment (mposolda) [reply common/src/main/java/org/keycloak/common/constants/KerberosConstants.java:75]: Yes, that's good idea and I've already did that at the admin console level. Admin console "suggests" the attribute based on the vendor, which is selected by administrator.

But now I've updated it to also add the attribute on server-side when creating new LDAP provider, so that it is applied also for the cases when LDAP provider is created directly by REST API for example. That's what we're doing for some other LDAP settings as well.

**Review by mposolda — COMMENTED** [review]
@pedroigor I've rebased the PR and also updated per your suggestion. Could you please review again?

**Review by pedroigor — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving as of @sguilhen's review

**Comment by jonkoops** [comment]
Looks like this PR has enough approval to be merged. Are we still waiting on a specific reviewer?

**Comment by mposolda** [comment]
Thanks everyone for the review!

@ahus1 I agree that documentation can be addressed in a follow-up if needed. Regarding testing, I've tested with our LDAP pipeline and created the PR to our LDAP configuration (will send the details offline).
