### PR TITLE
Check if fine grained is enabled

### LINKED ISSUE #36518: Duplicate groups needs fine grained authorisation
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I use the duplicate group function I get the following error in the server log:

```
2025-01-16 09:10:20,493 WARN  [org.keycloak.events] (executor-thread-287) type="REFRESH_TOKEN_ERROR", realmId="b8acab53-7d16-45d8-a0fd-abce69d045f6", realmName="master", clientId="security-admin-console", userId="null", ipAddress="0:0:0:0:0:0:0:1", error="invalid_token", reason="Token is not active", grant_type="refresh_token", client_auth_method="client-secret"
2025-01-16 09:12:01,115 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-296) Uncaught server error: jakarta.ws.rs.WebApplicationException: Feature not enabled
	at org.keycloak.utils.ProfileHelper.requireFeature(ProfileHelper.java:32)
	at org.keycloak.services.resources.admin.GroupResource.getManagementPermissions(GroupResource.java:323)
	at org.keycloak.services.resources.admin.GroupResource$quarkusrestinvoker$getManagementPermissions_3b85618d68db8fe7ad2afa0963ccc2dc07a4bf70.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2025-01-16 09:12:54,458 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-297) Uncaught server error: jakarta.ws.rs.WebApplicationException: Feature not enabled
	at org.keycloak.utils.ProfileHelper.requireFeature(ProfileHelper.java:32)
	at org.keycloak.services.resources.admin.GroupResource.getManagementPermissions(GroupResource.java:323)
	at org.keycloak.services.resources.admin.GroupResource$quarkusrestinvoker$getManagementPermissions_3b85618d68db8fe7ad2afa0963ccc2dc07a4bf70.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Using it without needing to add `--features=admin-fine-grained-authz` at startup

### Actual behavior

It only works when I enable the feature

### How to Reproduce?

* Start the server with no feature enabled
* Create a group
* from the kebab of the created group select: "duplicate"
* see the error in the console and on the UI

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #36518
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

File: js/apps/admin-ui/src/groups/GroupsModal.tsx [hunk 1]
```diff
@@ -132,15 +134,17 @@ export const GroupsModal = ({
         });
       }
 
-      const permissions = await adminClient.groups.listPermissions({
-        id: sourceGroup.id!,
-      });
+      if (isFeatureEnabled(Feature.AdminFineGrainedAuthzV2)) {
```
Comment (vramik) [inline js/apps/admin-ui/src/groups/GroupsModal.tsx:137]: I believe it should be guarded against V1:
```suggestion
      if (isFeatureEnabled(Feature.AdminFineGrainedAuthz)) {
```

**Review by ssilvert — APPROVED** [review]
