### PR TITLE
Bugfix: "User Profile" attributes not available for Users Attribute search

### LINKED ISSUE #27536: "User Profile" attributes not available for Users Attribute search and Attribute selection, if no view or manage realm realm-management role added
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Realm Admin users, having "realm-management" role/permissions only to "manage-users" and "query-users", cannot make Search using the Attribute or to add attribute for example for Locale.
Having "view-realm" or of course "manage-realm" is fixing it, but then the Realm Admin users are also able to see the Realm Settings, which might be not desired as it contains sensitive information.

Please note that the "User Profile" attributes are available normally, as the User Profile "groups" and "attributes" are localized when the User is opened

### Version

24.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

The User Profile Attributes are available for User Attribute search without the need of "view-realm" or "manage-realm" realm-management Client Role to be assigned:
User attribute search:
image
Locale attribute selection:
image

### Actual behavior

The User Attribute Search is not usable, as User Profile attributes are not available in case "view-realm" or "manage-realm" realm-management Client Role is not assigned:
User attribute search:
image
User Attribute select:
image

### How to Reproduce?

1. Create User Profile attributes, also some with multiselect, like for Locale selection
2. Create user with user/credentials (or use Identity Provider if available)
3. Assign "manage-users" and "query-users" realm-management Client roles to an user
4. Sign in with the security-admin-console client with 
5. Go to the User menu:
image
6. Try to make Attribute Search:
image
or to assign some Attribute for the user

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by danielFesenmeyer**
... when admin user does not have view- or manage-realm realm-management role

Closes #27536

### CODE REVIEW

**Comment by edewit** [comment]
@pedroigor what do you think about this?

**Review by pedroigor — DISMISSED** [review]

File: js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx [hunk 1]
```diff
@@ -188,7 +188,10 @@ export function UserDataTableAttributeSearchForm({
   };
 
   return (
-    <Form className="user-attribute-search-form">
+    <Form
+      className="user-attribute-search-form"
+      data-testid={"user-attribute-search-form"}
```
Comment (edewit) [inline js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx:193]:
```suggestion
      data-testid="user-attribute-search-form"
```

File: js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx [hunk 2]
```diff
@@ -231,6 +234,7 @@ export function UserDataTableAttributeSearchForm({
           </InputGroupItem>
           <InputGroupItem>
             <Button
+              data-testid={"user-attribute-search-add-filter-button"}
```
Comment (edewit) [inline js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx:237]:
```suggestion
              data-testid="user-attribute-search-add-filter-button"
```

File: js/apps/admin-ui/src/components/users/UserDataTable.tsx [hunk 3]
```diff
@@ -238,6 +233,7 @@ export function UserDataTable() {
               return (
                 <ChipGroup
                   className="pf-v5-u-mt-md pf-v5-u-mr-md"
+                  data-testid={"user-attribute-search-chips-group"}
```
Comment (edewit) [inline js/apps/admin-ui/src/components/users/UserDataTable.tsx:236]:
```suggestion
                  data-testid="user-attribute-search-chips-group"
```

**Review by edewit — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx (hunk 1 above)
Comment (danielFesenmeyer) [reply js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx]: Adjusted.

**Comment by danielFesenmeyer** [comment]
@edewit I've applied your simplifications, thanks for those suggestions.

If tests are still passing, the PR can be merged from my POV.

**Review by sguilhen — APPROVED** [review]
LGTM

**Review by edewit — APPROVED** [review]

**Review by mposolda — APPROVED** [review]

**Comment by danielFesenmeyer** [comment]
Thanks guys for the review and merge :smiley:

File: js/apps/admin-ui/src/components/users/UserDataTable.tsx [hunk 4]
```diff
@@ -216,12 +211,12 @@ export function UserDataTable() {
 
   const goToCreate = () => navigate(toAddUser({ realm: realmName }));
 
-  if (!userStorage || !realm) {
+  if (!uiRealmInfo || !realm) {
```
Comment (fvales) [inline js/apps/admin-ui/src/components/users/UserDataTable.tsx:214]: Shouldn't this be 
```
if (uiRealmInfo.userProfileProvidersEnabled === undefined || !realm) {
  return <KeycloakSpinner />;
}
``` 
as uiRealmInfo is initialized as empty object?
API call to fetch users is made even if user federation is enabled because `userProfileProvidersEnabled` is undefined and `listUsers` is true.
However, when the user clicks on next page and since `userProfileProvidersEnabled ` is available API call isn't made and user federation enabled info message is displayed.

Comment (ahus1) [reply js/apps/admin-ui/src/components/users/UserDataTable.tsx:214]: @fvales - if you think this is a bug, please create a new issue, possibly describing the expected vs. actual behavior.
