### PR TITLE
Relax checking of messages

### LINKED ISSUE #28911: clients_saml_test.spec.ts fails in main
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

clients_saml_test.spec.ts often fails

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

clients_saml_test.spec.ts always passes

### Actual behavior

clients_saml_test.spec.ts sometimes fails

### How to Reproduce?

Run clients_saml_test.spec.ts

### Anything else?

https://github.com/keycloak/keycloak/actions/runs/8749261524/job/24011145819
https://github.com/keycloak/keycloak/actions/runs/8746367004/job/24003206842
https://github.com/keycloak/keycloak/actions/runs/8746121067/job/24002475929

### PR DESCRIPTION
**Pull request by hmlnarik**
Related to: #28873
Fixes: #28911

### CODE REVIEW

File: js/apps/admin-ui/cypress/support/pages/admin-ui/Masthead.ts [hunk 1]
```diff
@@ -94,16 +94,27 @@ export default class Masthead extends CommonElements {
...
       this.#getAlertsContainer()
-        .find(`button[title="` + message.replaceAll('"', '\\"') + `"]`)
-        .last()
-        .click({ force: true });
+        .find(this.#alertMessage)
+        .invoke("text")
+        .should("match", message);
+
+      if (closeNotification) {
+        this.#getAlertsContainer().find("button").last().click({ force: true });
```
Comment (jonkoops) [inline js/apps/admin-ui/cypress/support/pages/admin-ui/Masthead.ts:116]: This looks like it might close an unrelated alert, but probably fine,

**Review by jonkoops — APPROVED** [review]
