### PR TITLE
iso-date validator for the user-profile

### LINKED ISSUE #11757: Declarative User Profile: local-date validation and html5-date clash
### Describe the bug

When creating a user profile with a birthday attribute which should be displayed with a date picker in the registration dialogue this input will always fail validation when using local-date-validation.

### Version

18.0.0

### Expected behavior

The user is created and has the attribute birthday set as iso 8601 date.

### Actual behavior

The birthday field is flagged as invalid.

image

Another interesting sidenote: The date format in the date picker didn't change with a localization change.

In the form data I can see it being sent as:
```
birthday: 2022-01-01
```

### How to Reproduce?

In a realm with declarative user profile with the following configuration:

```
{
  "attributes": [
    {
      "name": "username",
      "displayName": "${username}",
      "validations": {
        "length": {
          "min": 3,
          "max": 255
        },
        "username-prohibited-characters": {}
      }
    },
    {
      "name": "email",
      "displayName": "${email}",
      "validations": {
        "email": {},
        "length": {
          "max": 255
        }
      }
    },
    {
      "selector": {
        "scopes": []
      },
      "permissions": {
        "view": [
          "user",
          "admin"
        ],
        "edit": [
          "user",
          "admin"
        ]
      },
      "name": "birthday",
      "displayName": "Birthday",
      "required": {
        "roles": [],
        "scopes": []
      },
      "validations": {
        "local-date": {}
      },
      "annotations": {
        "inputType": "html5-date"
      }
    }
  ]
}
```

Then try to register a new account.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ThoreKr**
Adds a new validator in order to be able to validate user-model fields which should be modified/supplied by a datepicker.

I did try to create a shared date validator class, which handles parsingwith a provided datetimeformatter. In that attempt I also migrated the local-date validator to a datetimeformatter. However, this had the effect that for the english locale `12/13/2021` would no longer be acepted. Only `12/13/21` was considered as valid.
For that reason I removed the shared parsing logic.

Closes #11757

### CODE REVIEW

File: server-spi-private/src/main/java/org/keycloak/validate/BuiltinValidators.java [hunk 1]
```diff
@@ -19,17 +19,7 @@
...
-import org.keycloak.validate.validators.IntegerValidator;
-import org.keycloak.validate.validators.LengthValidator;
-import org.keycloak.validate.validators.LocalDateValidator;
-import org.keycloak.validate.validators.NotBlankValidator;
-import org.keycloak.validate.validators.NotEmptyValidator;
-import org.keycloak.validate.validators.OptionsValidator;
-import org.keycloak.validate.validators.PatternValidator;
-import org.keycloak.validate.validators.UriValidator;
-import org.keycloak.validate.validators.ValidatorConfigValidator;
+import org.keycloak.validate.validators.*;
```
Comment (pedroigor) [inline server-spi-private/src/main/java/org/keycloak/validate/BuiltinValidators.java:22]: Can you please revert this change?

**Review by pedroigor — CHANGES_REQUESTED** [review]
@ThoreKr Thanks for this one and sorry for the nitpick but we need to revert that change.

Otherwise, LGTM.

File: server-spi-private/src/main/java/org/keycloak/validate/BuiltinValidators.java (hunk 1 above)
Comment (ThoreKr) [reply server-spi-private/src/main/java/org/keycloak/validate/BuiltinValidators.java]: Sure, that was just the auto-optimize.

Just curious, are there specific benefits with the explicit imports?

Comment (pedroigor) [reply server-spi-private/src/main/java/org/keycloak/validate/BuiltinValidators.java]: Not really it is more about making more explicit the dependencies you have. We avoid using wildcards even though we don't have any automation to enforce a coding style.

**Review by pedroigor — APPROVED** [review]
