### PR TITLE
no longer use subgroup cache

### LINKED ISSUE #21693: New Admin UI: Group Attribute UI does not refresh, shows stale values
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I want to change an attribute value on a group:
1. I click on "Groups" in the left main menu
2. I choose the group I want to change in the "search groups" panel
3. I click on tab "Attributes", change the value of the attribute and click on Save
4. I click on the group again in the "search groups" panel
5. The old values are shown
6. Same happens if I click on other tabs in the group UI and switch back to attributes
7. I have to reload the whole page or click on "Groups" in the breadcrumps to load the changed value

image

### Version

21.0.1/21.1.1

### Expected behavior

I want to change an attribute value on a group:
1. I click on "Groups" in the left main menu
2. I choose the group I want to change in the "search groups" panel
3. I click on tab "Attributes", change the value of the attribute and click on Save
4. A HTTP GET is called to updated the cached values and the new value is always shown.

### Actual behavior

see Bug Description.

### How to Reproduce?

1. Start nightly with "kc.sh start-dev"
2. Follow the steps above

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #21693

### CODE REVIEW

File: js/apps/admin-ui/src/groups/GroupAttributes.tsx [hunk 1]
```diff
@@ -29,27 +27,24 @@ export const GroupAttributes = () => {
...
+      setCurrentGroup(group);
+    },
+    [],
+  );
 
   const save = async (attributeForm: AttributeForm) => {
     try {
-      const group = currentGroup();
-      const attributes = keyValueToArray(attributeForm.attributes!);
+      const group = currentGroup;
```
Comment (jonkoops) [inline js/apps/admin-ui/src/groups/GroupAttributes.tsx:44]: If `currentGroup` no longer needs to be called, perhaps we can remove this alias and just use it directly?

**Review by jonkoops — DISMISSED** [review]

**Review by jonkoops — DISMISSED** [review]
LGTM

**Review by jonkoops — DISMISSED** [review]

**Review by ssilvert — APPROVED** [review]
