### PR TITLE
Fix #14173, should not hide IDP from login page

### LINKED ISSUE #14173: IDP Provider is hidden from the login form after the back button is pressed
### Describe the bug

When there's an IDP in the KeyCloak realm (eg.: Google or Facebook) AND in the _First Broker Login_ authentication flow the _Review Profile_ is set then I can hide the given IDP from the login page.

### Version

19.0.1-legacy

### Expected behavior

After the following steps below the IPD should not disappear from the login page.

### Actual behavior

After the following steps below the IPD is filtered out by [LoginFormsUtil::63](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java#L63-L67). 

### How to Reproduce?

Steps required:
 - open a keycloak login page (for example we have one here: fiok.bkk.hu)
 - click on the _New user? Register_ button to open the registration screen
 - do not fill the registration form, but click on the _Already have an account? Log in!_ button to go back to the login screen
 - click on any IDP you like (eg.: click on the Google login option)
 - on the _Please provide your email address_ do not provide your e-mail address but click the back button in your browser. Go back to the login screen
 - the IDP disappeared from the login screen

### Anything else?

I think the LoginFormsUtil should not filter out based on the `existingIdp` if there's no user in the context.

### PR DESCRIPTION
**Pull request by vilmosnagy**
Closes #14173

See in the issue, to my understanding we should not filter
the users in the given method if there is no logged in
user.

### CODE REVIEW

**Comment by vilmosnagy** [comment]
@mposolda as fas as I see you were the last / main editor of this file. Could you review this for me please?

File: services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java [hunk 1]
```diff
@@ -63,6 +63,7 @@ public static List<IdentityProviderModel> filterIdentityProviders(Stream<Identit
             return providers
                     .filter(p -> { // Filter current IDP during first-broker-login flow. Re-authentication with the "linked" broker should not be possible
                         if (existingIdp == null) return true;
+                        if (context.getUser() == null) return true;
```
Comment (zak905) [inline services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java:66]: If you look carefully at the next filter there is a check for:
```
if (federatedIdentities == null) return true;
``` 
federatedIdentities will only be `null` if the `context.getUser()` is null as you can see from the check in line 55. Your change here has no effect.

Comment (zak905) [reply services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java:66]: Also, based on the comment: `Re-authentication with the "linked" broker should not be possible`

I think this was the intended behavior

Comment (vilmosnagy) [reply services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java:66]: But those providers will be filtered _out_ in this step, they won't even reach the lines below.

'cause the:
 - `Objects.equals(p.getAlias(), existingIdp.getAlias())` will be true (the alias of the cached-but-not-used provider will be one of the aliases of the available providers)
 -  and we negate this expression here
 - so the cached-but-not-used provider will be filtered out by this filter and never reach the next one

My fix is an early-exit, so if there's no user logged in then we can reach the filter below.

Comment (vilmosnagy) [reply services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java:66]: > I think this was the intended behavior

Please, check the video I've attached to the issue :slightly_smiling_face: 

I do not finish the authentication flow, so there's no user authenticated. No user linked with the Identity Provider at all.

Comment (zak905) [reply services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java:66]: I saw the video. Are you sure when you get the review profile step the user is not yet created / authenticated ? In this case, how does keycloak knows which user is modifying their profile

Comment (zak905) [reply services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java:66]: > No user created, so there's no-one linked with the Identity Provider with the given ID after the steps.

Ok that answers the question. I think it makes sens but maybe the solution could be just modifying the `First Broker` Flow by either:
- making the `Review profile` step after the user creating/linking => which is the natural order of things
- making the review profile `Update profile on first login` value to `missing` instead of `on`.

Comment (vilmosnagy) [reply services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java:66]: >  Are you sure when you get the review profile step the user is not yet created / authenticated ? In this case, how does keycloak knows which user is modifying their profile

Yeah, I'm pretty sure about that. You can test on a keycloak instance, that no user is created if you press the back button on the review page.

No user can be created, 'cause there's a step for that it the First Broker Login flow:

image

The user is created in the _create user if unique_ authenticator. (See the code here: [IdpCreateUserIfUniqueAuthenticator::75](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpCreateUserIfUniqueAuthenticator.java#L75)) And no user is created when there's a duplication AND the duplicated users are forbidden in the realm settings.

> - making the Review profile step after the user creating/linking => which is the natural order of things
> - making the review profile Update profile on first login value to missing instead of on.

I think you cannot do that. Consider the following example: given User John Doe with the following accounts:
 - Facebook, where he uses his childhood's email address: jhonny9310@aol.net
 - Google, where he has a more formal e-mail address: john.doe@gmail.com
 - And he has an Apple account, where he has the private relay setting on, so the e-mail address Apple gives to keycloak is a randomly generated string 

He registered with his Google account months ago, and when he next visits our site he does not remember which IDP he used. He clicks on the Apple login (he opened the site from an iPhone, so Apple login is a convenient one). Keycloak presents him the following info:
 - this IDP is not yet linked with an account
 - and he can review the e-mail address he'd like to use

So John has the ability to change the e-mail address to his main one: john.doe@gmail.com And from there Keycloak takes care of merging his Apple ID to the pre-existing account. I'm pretty sure this is the expected behavior from the Keycloak team (see the flow, there are multiple verification options, and stuff).

 - If I'd change the First broker login flow in my installation (eg: move the review step after the user creation), then I'd be divert from upstream AND lose this merging functionality
 - If I'd make this change in the upstream keycloak, then the upstream keycloak lose this merging functionality
   - Or if we'd take care of the merging, we'd introduce a lot of fake user creation. There'd be created a user for the apple account in the previous example, AND we should merge the two accounts when John changes the email address in one of the accounts... But what should we do if he changes the e-mail address minutes/months after the registration? What should our clients do? Should _all_ Keycloak clients prepare for merged users?

Imagine a subscription website which uses Keycloak as the authentication. Should this website merge the users' subscriptions after the users had been merged? Who takes care of the refunds, and so on... Huge mess.

I'm pretty sure that we (the Keycloak team and myself) do not want to change how the First Broker login flow works.

And I'm pretty sure it's a bug, even if it's a small one, that the IDP button disappears sometimes.

I've tested it: this change fixes this bug, the only thing I'm not sure of, whether there are security issues with it or not. I'm not _THAT_ familiar with OAuth & Keycloak yet.

**Comment by vilmosnagy** [comment]
@stianst can I ask you a question (I see the added label): is the logic correct here?

My assumption is the following: if the user is not logged in we should show them all of the IDPs. The reasoning is, 'cause the original filter is supposed to filter out the _already-linked_ identity providers. Am I correctly assuming that?

If so, I'll write the tests this week, so you could accept this PR :slightly_smiling_face:

**Comment by vilmosnagy** [comment]
@zak905 @stianst @mposolda I've written some tests for the code, please review.

**Comment by sschu** [comment]
If I am not mistaken, adding mockito won't be accepted. Please have a look at how other tests are written and implement your tests in a similar way.

**Comment by vilmosnagy** [comment]
@sschu could you help me with an example Test? As far as I can see `LoginFormsUtil` needs a fully initialized:
 - `KeycloakSession`
 - `AuthenticationFlowContext`
 - and a realm with the identityProviders

All of the tests in `keycloak-services` module test some _very basic_ function. The closest to my use-case is `PlainTextVaultProviderFactoryTest`, but even from there I cannot see how to create IdentityProviders in the session. The `session.getKeycloakSessionFactory().factoriesMap` is an empty `Map`, so the `serializedCtx.deserialize()` will always throw an Exception.

**Comment by mposolda** [comment]
I can add, that there are some tests for identity brokering in the package `org.keycloak.testsuite.broker` inside the integration testsuite (module `testsuite/integration-arquillian`)

**Comment by vilmosnagy** [comment]
@mposolda @sschu thanks for the feedback, I rewrote the test. It fails without my modification in the `LoginFormsUtil` class, and the test passes with my modification.

Please review :)

**Comment by vilmosnagy** [comment]
@mposolda @stianst could you review please the `missing/tests` label, cause I've added the tests a couple of weeks ago.

thanks, :)

**Review by mposolda — CHANGES_REQUESTED** [review]
@vilmosnagy Thanks. I've removed the label, however there are failing tests, which looks like a regression of your PR ("Model tests" are unrelated to your changes, but the rest failing tests in "Group 2" are probably related)

**Comment by vilmosnagy** [comment]
@mposolda thanks for the clarification.

I've rewritten the PR, and now it has the test for the bug reported in #14173, and all the tests (except the model tests) pass. Could you re-review it please?

**Review by mposolda — APPROVED** [review]
@vilmosnagy Nice, Thanks for the update!
