### PR TITLE
Do not use whitelist/blacklist in the UI

### LINKED ISSUE #45539: Avoid using some blacklist/whitelist wording in UI and docs
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The words blacklist/whitelist are considered not to be inclusive, and the words "allowed" and "denied" are more descriptive.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Do not use blacklist/whitelist in the UI messages

### Actual behavior

There are some occurrences

### How to Reproduce?

Look at the message properties files

### Anything else?

I'll prepare a PR

### PR DESCRIPTION
**Pull request by ahus1**
Closes #45539

### CODE REVIEW

File: misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java [hunk 1]
```diff
@@ -81,6 +82,27 @@ private void verifyNoHtmlEntities() {
         });
     }
 
+    private final static Pattern DISCOURAGED_WORDS = Pattern.compile("(whitelist|blacklist)", Pattern.CASE_INSENSITIVE);
+
+    private void verifyNoDiscouragedWords() {
+        PropertyResourceBundle bundle = getPropertyResourceBundle();
+
+        if (!file.getName().endsWith("_en.properties")) {
```
Comment (pruivo) [inline misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java:90]: Why not all languages?

File: js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties [hunk 2]
```diff
@@ -267,7 +267,7 @@ resourceAttributeHelp=The attributes associated with the resource.
 updateCredentialUserLabelSuccess=The user label has been changed successfully.
 product=Product
 credentialUserLabel=User Label
-passwordPoliciesHelp.passwordBlacklist=Prevents the use of a password that is in a blacklist file.
+passwordPoliciesHelp.passwordBlacklist=Prevents the use of a password that is in a file with passwords that must not be used for example because they are considered to be weak passwords.
```
Comment (pruivo) [inline js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties]: This look a very long sentence. How about:
```suggestion
passwordPoliciesHelp.passwordBlacklist=Restricts the use of passwords identified in a password file.
```

File: misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java (hunk 1 above)
Comment (ahus1) [reply misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java:90]: In other languages it might be translated, I know that it is translated at least in French. At least with Weblate, the translators will be notified that the English text changed, and this will indicate to them that they should review and possibly change their translations.

File: js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties (hunk 2 above)
Comment (ahus1) [reply js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties]: @pruivo - I've updated the entry with a different text. I think it is important for an admin to know that this the file is a server side file. Please have another look.

**Review by pruivo — APPROVED** [review]

**Review by mabartos — APPROVED** [review]

**Review by stianst — APPROVED** [review]
