### PR TITLE
Account UI throws error when opening an unknown path

### LINKED ISSUE #40602: Account UI reports "Something went wrong" when opening an unknown path
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When opening the Account UI with an unknown path, it show the error message "Something went wrong" and the button "try again". 

This happens if you disabled a menu entry for example by re-configuring Keycloak.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

When a menu entry doesn't exist, redirect to the start page of the Account UI. Possibly (but not required) show an error message before redirecting.

### Actual behavior

There is an error message, and pressing "Try again" just reloads the account console. 

### How to Reproduce?

Either use a wrong URL: `http://localhost:8080/realms/test/account/dddd`

Or enabled organizations, go to `http://localhost:8080/realms/test/account/organizations`, then disable organizations, go to the URL again, and see the error.

### Anything else?

As menu entries can also be added and removed by themes using the `content.json` file, this is very annoying, and users might be caught in an endless loop.

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #40602

#### New behavior

https://github.com/user-attachments/assets/bfd3206b-53b6-4437-a9f6-c5ba57887635

@ssilvert @edewit @ahus1 Could you please check it? Thanks!

### CODE REVIEW

File: js/apps/account-ui/src/root/Root.tsx [hunk 1]
```diff
@@ -45,6 +48,19 @@ function mapRoutes(
     .flat();
 }
 
+function CatchAllRedirect() {
+  const { t } = useTranslation();
+  const { addAlert } = useAlerts();
+  const navigate = useNavigate();
+
+  useEffect(() => {
+    addAlert(t("pageNotFound"), AlertVariant.danger);
```
Comment (ssilvert) [inline js/apps/account-ui/src/root/Root.tsx]: Suggest using AlertVariant.warning here.  User hasn't done anything scary.


```suggestion
    addAlert(t("pageNotFound"), AlertVariant.warning);
```

**Review by ssilvert — CHANGES_REQUESTED** [review]
Looks good overall.  Just one suggestion.

**Comment by mabartos** [comment]
@ssilvert Works to me; updated.

File: js/apps/account-ui/src/root/Root.tsx [hunk 2]
```diff
@@ -45,6 +48,19 @@ function mapRoutes(
...
+  const { t } = useTranslation();
+  const { addAlert } = useAlerts();
+  const navigate = useNavigate();
+
+  useEffect(() => {
+    addAlert(t("pageNotFound"), AlertVariant.warning);
+    navigate(".", { replace: true });
+  }, [addAlert, navigate, t]);
+
+  return null;
```
Comment (edewit) [inline js/apps/account-ui/src/root/Root.tsx]: No need to return anything here, it does that by default
```suggestion
```

**Review by edewit — APPROVED** [review]

File: js/apps/account-ui/src/root/Root.tsx (hunk 2 above)
Comment (mabartos) [reply js/apps/account-ui/src/root/Root.tsx]: Not really helped. Added a different approach.

**Comment by mabartos** [comment]
@ssilvert @edewit THanks for your review; updated.

**Review by ssilvert — APPROVED** [review]
