### PR TITLE
fix: updates to create a java admin client build

### LINKED ISSUE #48340: Release a version of the java admin client that supports client admin api v2
### Description

The current client admin api v2 classes are missing from the java admin client build. There are a couple of refinements needs so that the classes are usable.

### PR DESCRIPTION
**Pull request by shawkins**
I see the intent behind the ClientsWrapper class, but I don't think we're ready yet to commit to an api like that as it obsures the versioning and is a different realm paradigm than the existing methods.

For now I'd propose opening up the proxy method, as that won't unnecessarily expose anything that we wish to change later with the understanding that the client v2 interfaces aren't yet considered supported (I'm not sure if / where that needs documented). 

Comparing with the fabric8 logic you have both methods, such as client.apps().statefulsets() - specifically for v1 statefulsetets, or you can also do client.resources(StatefulSets.class) for the general api.

Another set of changes is to set a lower source compatiblity level. The admin client is using 8, but setting the admin api v2 interfaces to v2 to 11 seems sufficient to have things compile, so I'd start there instead.

As noted in other issues, we still have to make it clearer how we're differentiating between admin api v2 (the new url structure) from the resource specific versions clients v2, v3, etc. - or even if the latter is still a good idea :) cc @michalvavrik 

Related to that, our api structuring is not correct. Having a general "ClientsApi clients(String version)" endpoint means that  we'll only ever have things that conform to the ClientsApi (v2) contract. It's not even possible to have a truly breaking change.

After this pr, I have changes for the admin client repo that will add the v2 classes.

closes: #48340

### CODE REVIEW

File: integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java [hunk 1]
```diff
@@ -218,6 +216,17 @@ public <T> T proxy(Class<T> proxyClass, URI absoluteURI) {
         WebTarget register = client.target(absoluteURI).register(newAuthFilter());
         return CLIENT_PROVIDER.targetProxy(register, proxyClass);
     }
+    
+    /**
+     * Create a proxy
+     *
+     * @param proxyClass
```
Comment (michalvavrik) [inline integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java]: I know that this is probably just a c&p of the other `proxy` method, but I still think that these empty `@param` and `@return`  are just a noise, I'd either add some short description or drop them.

File: integration/admin-client/src/main/java/org/keycloak/admin/client/wrapper/Clients.java [hunk 2]
```diff
@@ -1,24 +0,0 @@
-package org.keycloak.admin.client.wrapper;
-
-import jakarta.ws.rs.client.WebTarget;
-
-import org.keycloak.admin.api.AdminRootV2;
-import org.keycloak.admin.api.client.ClientsApi;
```
Comment (michalvavrik) [inline integration/admin-client/src/main/java/org/keycloak/admin/client/wrapper/Clients.java:6]: This means that `keycloak-admin-v2-api` dependency in `integration/admin-client/pom.xml` is not needed anymore. I didn't find a reason to keep it for only enforcing order either, so I'd just drop it and ask anyone who needs it to bring that dependency directly.

**Review by michalvavrik — COMMENTED** [review]
I am fine with changes. One comment regarding a dead dependency in admin-client pom.

File: integration/admin-client/src/main/java/org/keycloak/admin/client/wrapper/Clients.java (hunk 2 above)
Comment (shawkins) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/wrapper/Clients.java:6]: > so I'd just drop it and ask anyone who needs it to bring that dependency directly.

Seems good. This only affects test logic, and to use the v2 stuff you have to have a dependency already on the api.

File: integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java (hunk 1 above)
Comment (shawkins) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java]: No problem, dropped them.

**Review by michalvavrik — APPROVED** [review]

**Review by edewit — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]
This looks good. We can later (when we resolve the issues around Java versions) add a dedicated `clientV2` method (or something like that) to the root of admin client to avoid using the `proxy` method.
