### PR TITLE
use inputOptionsLabels when they exist

### LINKED ISSUE #22432: inputOptionLabels is not used by Admin UI
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the Admin UI the user profile option `inputOptionLabels`, which can be specified to provide translations to select values are not respected. If I specify them I get correctly translated forms in the login process but the keys are not translated in the admin ui.

### Version

22.0.1

### Expected behavior

With `inputOptionLabels` I should be able to provide translated labels for select options in the admin ui.

### Actual behavior

The `inputOptionLabels` option is ignored by admin ui.

### How to Reproduce?

1. Add a custom attribute in the user profile:
```json
{
      "name": "attr",
      "displayName": "${attr}",
      "selector": {
        "scopes": [
          "microprofile-jwt",
          "phone",
          "profile",
          "email",
          "web-origins",
          "roles",
          "offline_access",
          "role_list",
          "address",
          "acr"
        ]
      },
      "permissions": {
        "edit": [
          "user",
          "admin"
        ],
        "view": [
          "user",
          "admin"
        ]
      },
      "annotations": {
        "inputType": "select",
        "inputOptionLabels": {
          "option1": "${option1Label}",
          "option2": "${option2Label}",
        }
      },
      "validations": {
        "options": {
          "options": [
            "option1",
            "option2"
          ]
        }
      },
      "required": {
        "roles": [
          "user"
        ],
        "scopes": [
          "microprofile-jwt",
          "phone",
          "profile",
          "email",
          "web-origins",
          "roles",
          "offline_access",
          "role_list",
          "address",
          "acr"
        ]
      },
      "group": null
    },
```
2. Check the User detail page of a user
3. It says `option1` and `option2` instead of `option1Label` and `option2Label`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #22432

### CODE REVIEW

File: js/apps/admin-ui/src/user/components/SelectComponent.tsx [hunk 1]
```diff
@@ -86,7 +86,13 @@ export const SelectComponent = ({
                 key={option}
                 value={option}
               >
-                {option}
+                {t(
+                  unWrap(
+                    (attribute.annotations?.["inputOptionLabels"] as any)?.[
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/components/SelectComponent.tsx:91]: Why does this need to be converted to `any`?

Comment (edewit) [reply js/apps/admin-ui/src/user/components/SelectComponent.tsx:91]: because annotations can be anything according to the java model

**Review by jonkoops — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]
