### PR TITLE
Skip link only when client is not system when logout

### LINKED ISSUE #24595: Leaving Single Sign Out page open for too long and then confirming logout leads to error page
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We have a logout page that is responsible for logging the user out of all connected services.
If a user goes to this logout page but leaves that page open for about an hour and only then presses the logout button to confirm the logout, the user is redirected to the error page from which there is no knowing what went wrong or how to recover (except navigating manually to the login page again via URL).
In the attached image the two steps are shown: Above is the logout page with the logout button and below the resulting error is shown.
keycloak_error_logout

### Version

19.0.3, 22.0.4

### Expected behavior

As I suspect this issue to be related to some timeout setting, the expected behaviour should probably be to automatically redirect the user to the login page instead of an error page when the session expires while on the logout screen.

### Actual behavior

The user is redirected to an error page upon confirming the logout with the logout button on the logout page.

### How to Reproduce?

I am not sure if the problem is easily reproducible without our setup, but here are the steps I took to consistently reproduce this error on our system:

- From our application, go to the logout page for a logged in user.
- Leave this page open for about an hour.
- Confirm the logout by pressing the logout button.

### Anything else?

When filtering for logout errors in the keycloak admin console UI, the logout error event that is caused by this issue is shown but without any client or user, which probably indicates the session expired and; therefore, the event can not be matched to a logged in user.
keycloak_error_log

Upgrading from keycloak 19.0.3 to 22.0.4 did not solve this issue for us.

### PR DESCRIPTION
**Pull request by lexcao**
Closes #24595

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java [hunk 1]
```diff
@@ -371,7 +371,7 @@ public Response logoutConfirmAction() {
             logger.debugf("Failed verification during logout. logoutSessionId=%s, clientId=%s, tabId=%s",
                     logoutSession != null ? logoutSession.getParentSession().getId() : "unknown", clientId, tabId);
 
-            if (logoutSession == null || logoutSession.getClient().equals(SystemClientUtil.getSystemClient(logoutSession.getRealm()))) {
+            if (logoutSession != null && logoutSession.getClient().equals(SystemClientUtil.getSystemClient(logoutSession.getRealm()))) {
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java:374]: One concern here: In case that logoutSession is expired (so `logoutSession == null`), but logout was triggered with "system" client, than the more correct behaviour might be still to skip showing the link though?

Could we fallback to `clientId` parameter in that case? I guess something like this (not 100% sure code is correct, just for the illustration):
```
String usedClientId = "account";
if (logoutSession != null) {
  usedClientId = logoutSession.getClient().getClientId();
} else if (clientId != null) {
  // fallback to parameter clientId
  usedClientId = clientId;
}
if (usedClientId != null && usedClientId.equals(SystemClientUtil.getSystemClient(logoutSession.getRealm()).getClientId()) {
  // skip link ...
}
```

Will probably require some small adjustements to the test (or maybe new test)?

**Review by mposolda — COMMENTED** [review]
@lexcao Thanks for the PR! I have one comment inline. Could you pleae check it?

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java (hunk 1 above)
Comment (lexcao) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java:374]: Make sense, let me try this.

**Review by mposolda — COMMENTED** [review]
@lexcao Thanks, added one minor nitpick comment. Is it possible to address that one and rebase this PR? Hopefully that will also help with failing tests.

File: server-spi-private/src/main/java/org/keycloak/models/utils/SystemClientUtil.java [hunk 2]
```diff
@@ -57,4 +62,16 @@ public static ClientModel getSystemClient(RealmModel realm) {
 
     }
 
+    /**
+     * Cleanup system client URL to avoid links to account management
+     */
+    public static void skipLink(KeycloakSession session, AuthenticationSessionModel authSession) {
```
[the remark this answers is not in the document]
Comment (lexcao) [reply server-spi-private/src/main/java/org/keycloak/models/utils/SystemClientUtil.java]: Good suggestion, thanks.

**Review by mposolda — APPROVED** [review]
@lexcao Thanks!
