### PR TITLE
Check email and username for duplicated if isLoginWithEmailAllowed

### LINKED ISSUE #27297: Check for duplicated usernames and emails when Login with email option is enabled
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

Currently the user profile validators check for duplicated username and duplicated emails. But when the option `Login with email` is enabled (it's enabled by default) it can happen that the username (if it has an email format) collides with another user email. The duplicated username and duplicated email validators should also check for the other field when that option is enabled to avoid duplicates between them.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

- The validators should check the other field and throw an error because it's duplicated.

### Actual behavior

- The validators allow a user to have the same username than another email user and vice-versa. 

### How to Reproduce?

- In a realm with `login with email` enabled.
- Create a user with username `username1@local.com` and email `username1@local.org`.
- Create a second user with username `username2` and email `username1@local.com` (like the first username).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #27297

Email and username validators check duplicates in the other attribute if `isLoginWithEmailAllowed` is enabled. The duplicated username validator was working incorrectly, fixed now. I decided to add the duplicated validators to the ADMIN_API too. The user endpoints try to return the same errors as before (there are very little differences but more or less the same).  Tests added to two contexts: admin api and update profile action.

### CODE REVIEW

File: services/src/main/java/org/keycloak/userprofile/validator/DuplicateUsernameValidator.java [hunk 1]
```diff
@@ -64,12 +64,21 @@ public ValidationContext validate(Object input, String inputHint, ValidationCont
         KeycloakSession session = context.getSession();
         UserModel existing = session.users().getUserByUsername(session.getContext().getRealm(), value);
         UserModel user = UserProfileAttributeValidationContext.from(context).getAttributeContext().getUser();
+        String valueLowercased = value.toLowerCase();
 
-        if (! KeycloakModelUtils.isUsernameCaseSensitive(session.getContext().getRealm())) value = value.toLowerCase();
+        if (! KeycloakModelUtils.isUsernameCaseSensitive(session.getContext().getRealm())) value = valueLowercased;
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/userprofile/validator/DuplicateUsernameValidator.java:69]: This is different than what we are doing here https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/userprofile/validator/UsernameMutationValidator.java#L69.

If I read that code correctly, only if the realm is not set to use case-sensitive usernames we should lower case the value.

This was added by #14678. @vramik Wdyt?

Comment (rmartinc) [reply services/src/main/java/org/keycloak/userprofile/validator/DuplicateUsernameValidator.java:69]: @pedroigor I think I'm doing the same than before, but just saving the lower-cased value for the email comparison (email is always lower-cased, so we should search for email with the lowercased username).

**Review by pedroigor — APPROVED** [review]

File: services/src/main/java/org/keycloak/userprofile/validator/DuplicateUsernameValidator.java (hunk 1 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/userprofile/validator/DuplicateUsernameValidator.java:69]: You're right. Sorry for the noise.
