### PR TITLE
fix: making the truststore name field optional

### LINKED ISSUE #28012: Keycloak CR Truststore should not have a name
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

There were several design iterations over if/where a truststore should be named. In the final version the name is supposed to be on the map of entries at the spec level, however a name field was also left on the truststore itself.

### Version

24

### Regression

- [ ] The issue is a regression

### Expected behavior

A name should not be required on the truststore stanza.

### Actual behavior

A redundant name is required.

### How to Reproduce?

Add a truststore to a keycloak cr.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
We unfortunately need to leave the field in the crd so this is not a breaking change. We can consider not storing a value in later version, and then completely removing in an even later version - or once we move to a different crd revision.

closes: #28012

### CODE REVIEW

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/Truststore.java [hunk 1]
```diff
@@ -21,12 +21,13 @@
...
 
 import com.fasterxml.jackson.annotation.JsonInclude;
+import com.fasterxml.jackson.annotation.JsonPropertyDescription;
 
 @JsonInclude(JsonInclude.Include.NON_NULL)
 @Buildable(editableEnabled = false, builderPackage = "io.fabric8.kubernetes.api.builder")
 public class Truststore {
 
-    @Required
+    @JsonPropertyDescription("Not used")
```
Comment (mabartos) [inline operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/Truststore.java:30]: @shawkins It would be good to add a little more text with an explanation of why it is not used, right? Or make it somehow deprecated by mentioning that it's gonna be removed in later versions?

**Comment by mabartos** [comment]
One more comment; I've noticed that for the KC 24.0.0 release notes[1], the truststores do not contain the name item, but it's required so far. Is it correct? IMHO, we should edit it there for the website. Probably not a big deal once we have the docs[2], but for better clarity.

[1] https://www.keycloak.org/2024/03/keycloak-2400-released.html#_keycloak_cr_truststores
[2] https://github.com/keycloak/keycloak/pull/28015/

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/Truststore.java (hunk 1 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/Truststore.java]: Added the text about removal.

**Comment by shawkins** [comment]
> IMHO, we should edit it there for the website.

Who can do that? cc @vmuzikar

**Review by mabartos — APPROVED** [review]

**Comment by vmuzikar** [comment]
> Who can do that? cc @vmuzikar

@shawkins AFAIK, these release announce blog posts are generated. Probably we just need to fix the [release notes](https://github.com/keycloak/keycloak/blob/22aba84293944a3ce225007852e0e2c18b5a97ff/docs/documentation/release_notes/topics/24_0_0.adoc?plain=1#L231-L245)?

**Comment by shawkins** [comment]
Probably we just need to fix the [release notes](https://github.com/keycloak/keycloak/blob/22aba84293944a3ce225007852e0e2c18b5a97ff/docs/documentation/release_notes/topics/24_0_0.adoc?plain=1#L231-L245)?

Opened #28097
