### PR TITLE
Cache guide does not properly print cache-stack values

### LINKED ISSUE #31941: Cache guide does not properly print `cache-stack` values
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The [Configuring distributed cache](https://www.keycloak.org/server/caching#_transport_stacks) guide does not properly print out the `cache-stack` values.

It is caused by the different handling of expected values in our Keycloak Options in the Quarkus module as the `cache-stack` also allows some custom values. This requirement might be needed in the future for the other properties (f.e. custom sampler for the tracing,...)

### Version

999

### Regression

- [X] The issue is a regression

### Expected behavior

Items are properly printed:
Screenshot from 2024-08-06 15-55-51

### Actual behavior

Items are not present:

Screenshot from 2024-08-06 15-54-43

### How to Reproduce?

Check out the guide: https://www.keycloak.org/server/caching#_transport_stacks

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Ability to choose expected values strict

Fixes #31941

Docs are properly printed:

image

Non-strict default values:

image

### CODE REVIEW

**Review by shawkins — COMMENTED** [review]
The changes seem fine, but do introduce another construct that may not be needed for any other option.

One alternative is to just update the caching doc to remove the <@opts.expectedValues option="cache-stack"/> and preceeding semi-colon. The cache-stacks are each mentioned below that point in the docs.

**Comment by mabartos** [comment]
> The changes seem fine, but do introduce another construct that may not be needed for any other option.

It is true for now, but I encountered the issue when I was investigating the possibilities of OTel custom samplers (which might be a potential follow-up task in the OTel integration) that some custom values need to be added.

It is used only for the `cache-stack` right now, but I believe there will be more in the near future. This should also remove the workaround made for the property mappers.

File: quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java [hunk 1]
```diff
@@ -128,7 +145,26 @@ public Option<T> build() {
             deprecated();
         }
 
-        return new Option<T>(type, key, category, hidden, build, description, defaultValue, expectedValues, deprecatedMetadata);
+        Class<?> expected = type;
+        if (auxiliaryType != null) {
+            expected = auxiliaryType;
+        }
+
+        if (CollectionUtil.isEmpty(expectedValues)) {
```
Comment (shawkins) [inline quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java:153]: We talked about adding to getExpectedValues javadoc a reference to strict method. There is also some subtle behavior here that should be mentioned - if you call builder.expectedValues() that doesn't mean no expected values, it means infer the default.

**Review by shawkins — COMMENTED** [review]
It should be fine to do it this way - it just might need a couple of javadocs on the builder / propertymapper.

**Comment by mabartos** [comment]
@shawkins I've updated the Javadoc. Let me know if it works for you or not; thanks!

**Review by shawkins — DISMISSED** [review]
LGTM, @mabartos that should be good enough to future proof the usage, thanks

File: quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java [hunk 2]
```diff
@@ -50,9 +50,8 @@ public enum Stack {
 
     public static final Option<Stack> CACHE_STACK = new OptionBuilder<>("cache-stack", Stack.class)
             .category(OptionCategory.CACHE)
-            .expectedValues(List.of())
-            .description("Define the default stack to use for cluster communication and node discovery. This option only takes effect "
-                    + "if 'cache' is set to 'ispn'. Default: udp. Built-in values include: " + Stream.of(Stack.values()).map(Stack::name).collect(Collectors.joining(", ")))
+            .expectedValues(false)
+            .description("Define the default stack to use for cluster communication and node discovery. This option only takes effect if 'cache' is set to 'ispn'. Default: udp.")
```
Comment (vmuzikar) [inline quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java:54]: Should we mark `udp` as the formal default value in the Options instead of just mentioning it in the desc? It'd help with formatting especially in the guide.

**Review by vmuzikar — COMMENTED** [review]
@mabartos Thanks for the PR!

I wonder, should we also add some handling for the non-strict (custom) values to the guides, similarly to what you did for the CLI? Currently, the list doesn't seem to hint that:
Screenshot 2024-08-12 at 13 16 23

File: quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java (hunk 2 above)
Comment (mabartos) [reply quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java:54]: Yep, it'd be better to do it, but there's a bigger issue around defining the default value. When the default value is specified by this, it is not possible to leverage the ability to use the stack specified in the ISPN/JGroups cache file[1]. 

In the doc[1], there are these sentences: 
_"By default, the value set to the cache-stack option has precedence over the transport stack you define in the cache configuration file. If you are defining a custom stack, make sure the cache-stack option is not used for the custom changes to take effect."_

That means, when we specify the default value, the default value will always be present (`udp` in this case), and the custom stack defined in the cache file will not be used.

I think it's not worth providing any comprehensive handling of this case. @vmuzikar WDYT?

Relevant issue: https://github.com/keycloak/keycloak/issues/10052

[1] https://www.keycloak.org/server/caching#_custom_transport_stacks

**Comment by mabartos** [comment]
> I wonder, should we also add some handling for the non-strict (custom) values to the guides, similarly to what you did for the CLI?

@vmuzikar Good point. Added commit: https://github.com/keycloak/keycloak/pull/31943/commits/9ab1a8eda0a180a2d45d6cbfe4687b1bc58a8e30

nitpick: As the doc guides provide formatting for the default values, I'm deciding whether to use the same `, or a custom one.`, or just `, or any.` The 'any' would not be formatted, so users would not consider it as another possible value. Any preference?

Maybe it'd be good to have it unified as in CLI and use the "custom one", right?

File: quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java (hunk 2 above)
Comment (vmuzikar) [reply quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java:54]: Thanks for pointing that out. I agree it's not worth it to over-engineer this. Let's keep as is.

**Comment by vmuzikar** [comment]
> Any preference?

IMHO "or any" works for the text guides better as it's shorter. For CLI is "or a custom one" more suitable as we can't distinguish it by formatting.

File: docs/guides/templates/options.adoc [hunk 3]
```diff
@@ -39,12 +40,12 @@ ${option.deprecated.note!}<#if option.deprecated.newOptionsKeys?has_content><#if
 </#if>
 
 |<#if option.expectedValues?has_content>
-<#list option.expectedValues as value>`+${value!}+`<#if option.defaultValue?has_content && value = option.defaultValue> (default)</#if><#if value?has_next>, </#if></#list>
+<#list option.expectedValues as value>`+${value!}+`<#if option.defaultValue?has_content && value = option.defaultValue> (default)</#if><#if value?has_next>, </#if></#list><#if !option.strictExpectedValues>, or a custom one.</#if>
```
Comment (vmuzikar) [inline docs/guides/templates/options.adoc:43]: Just a nitpick to keep it consistent with strict expected values which don't use a sentence.
```suggestion
<#list option.expectedValues as value>`+${value!}+`<#if option.defaultValue?has_content && value = option.defaultValue> (default)</#if><#if value?has_next>, </#if></#list><#if !option.strictExpectedValues>, or a custom one</#if>
```

**Review by vmuzikar — COMMENTED** [review]
@mabartos Thanks for the update!

**Review by vmuzikar — DISMISSED** [review]

**Comment by vmuzikar** [comment]
@shawkins Do you want to check the changes again as well?

**Review by shawkins — DISMISSED** [review]
LGTM

**Comment by vmuzikar** [comment]
@mabartos Seems some tests failed. Could you please check it?

**Comment by mabartos** [comment]
@shawkins @vmuzikar Oopps, the approved files should be properly updated now. Thanks for the review.

**Review by vmuzikar — APPROVED** [review]
