### PR TITLE
Synchronize workflow scheduled settings using cluster events (#48422)

### LINKED ISSUE #48185: Deleted workflow still attempting to run
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

workflows

### Describe the bug

After testing the [Tracking of user activity and taking actions workflow](https://www.keycloak.org/docs/latest/server_admin/index.html#tracking-user-activity-and-taking-actions-on-inactivity) in the documentation which creates a scheduled task, this workflow was deleted from the UI before being explicitly disabled. 

After deletion, server logs show that the scheduled task associated with the workflow continues to execute and fails because the referenced workflow no longer exists:

`ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task workflow-032b10ae-dfc2-41be-996a-d3dc0e868282: jakarta.ws.rs.BadRequestException: Not a valid workflow resource: 032b10ae-dfc2-41be-996a-d3dc0e868282`

This results in repeated error logs from `ScheduledTaskRunner`.

### Version

26.6.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Deleting a workflow should also unregister or cancel any associated scheduled tasks, or prevent further execution attempts.

### Actual behavior

The scheduled task continues to run and attempts to execute a workflow that has been deleted, resulting in repeated errors.

### How to Reproduce?

Create a workflow as in the example in the documentation, delete without disabling and observe the logs.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
* Synchronize workflow scheduled settings using cluster events

Closes #48185

(cherry picked from commit 33651e42c4d9fb513cde5e4b1da506f8b99a40a2)

### CODE REVIEW

File: services/src/test/java/org/keycloak/compatibility/KeycloakCompatibilityMetadataProviderTest.java [hunk 1]
```diff
@@ -17,17 +17,17 @@ public void testMicroVersionUpgradeWorksWithRollingUpdateV2() {
...
-        assertCompatibility(CompatibilityResult.ExitCode.RECREATE, compatibilityProvider.isCompatible(Map.of(VERSION_KEY, "998.999.998-Final")));
+        assertCompatibility(CompatibilityResult.ExitCode.RECREATE, compatibilityProvider.isCompatible(Map.of(VERSION_KEY, "999.999.1000-Final", "new cluster event", "WorkflowScheduleClusterEvent")));
+        assertCompatibility(CompatibilityResult.ExitCode.RECREATE, compatibilityProvider.isCompatible(Map.of(VERSION_KEY, "999.998.999-Final", "new cluster event", "WorkflowScheduleClusterEvent")));
+        assertCompatibility(CompatibilityResult.ExitCode.RECREATE, compatibilityProvider.isCompatible(Map.of(VERSION_KEY, "998.999.999-Final", "new cluster event", "WorkflowScheduleClusterEvent")));
+        assertCompatibility(CompatibilityResult.ExitCode.RECREATE, compatibilityProvider.isCompatible(Map.of(VERSION_KEY, "999.998.998-Final", "new cluster event", "WorkflowScheduleClusterEvent")));
+        assertCompatibility(CompatibilityResult.ExitCode.RECREATE, compatibilityProvider.isCompatible(Map.of(VERSION_KEY, "998.999.998-Final", "new cluster event", "WorkflowScheduleClusterEvent")));
```
Comment (ryanemerson) [inline services/src/test/java/org/keycloak/compatibility/KeycloakCompatibilityMetadataProviderTest.java:33]: I think we need a test case to represent when we upgrade from 26.6.1 to 26.6.2, i.e. the "new cluster event" K and Value are missing:

```java
assertCompatibility(CompatibilityResult.ExitCode.RECREATE, compatibilityProvider.isCompatible(Map.of(VERSION_KEY, "999.999.999-Final")));
```

Comment (sguilhen) [reply services/src/test/java/org/keycloak/compatibility/KeycloakCompatibilityMetadataProviderTest.java:33]: @ryanemerson I thought that was implicitly covered in `testRollingUpgradeRefusedWithOtherMetadataNotEquals`, but I can add something targetting the versions

Comment (sguilhen) [reply services/src/test/java/org/keycloak/compatibility/KeycloakCompatibilityMetadataProviderTest.java:33]: Done, added the assertion as you've suggested.

**Review by pruivo — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]
