### PR TITLE
OTEL: Add Telemetry options to Keycloak CR

### LINKED ISSUE #45348: OTEL: Add Telemetry options to Keycloak CR
### Description

As we have the `telemetry` options now for the OpenTelemetry integration, we should provide a first-class citizen fields for that parent category for the whole OTel integration (logs, metrics, traces) to simplify setup. 

### Value Proposition

Have the `telemetry-*` options first class citizens in Keycloak CR

### Goals

- Support the `telemetry-*` options in Keycloak CR

### Non-Goals

N/A

### Discussion

_No response_

### Notes

_No response_

### LINKED ISSUE #45623: Avoid unnecessary warning logs during the operator tests execution
### Description

As with the Telemetry and Tracing options enabled, we specify OTLP port where the telemetry data is sent. However as nobody listens on that port, we have multiple warning seen in the logs. 

```
2026-01-20 16:33:21,417 WARNING [io.quarkus.opentelemetry.runtime.exporter.otlp.sender.VertxGrpcSender] (vert.x-eventloop-thread-3) Failed to export TraceRequestMarshaler. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
```

It'll be good to have a separate CR created with the telemetry/tracing settings and not use it as the default for all Operator tests.

### Value Proposition

Avoid unnecessary warning logs in all operator tests

### Goals

- Clean up logs 
- Improve readability

### Non-Goals

N/A

### Discussion

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #45348
- Closes #45623
- Add the support for telemetry options in Keycloak CR
- Deprecate the `tracing.resourceAttributes` and `tracing.serviceName` in Keycloak CR

### CODE REVIEW

**Comment by mabartos** [comment]
@vmuzikar @shawkins Could you please check it? THanks!

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TracingSpec.java [hunk 1]
```diff
@@ -36,7 +37,11 @@ public class TracingSpec {
     @JsonPropertyDescription("OpenTelemetry endpoint to connect to.")
     private String endpoint;
 
-    @JsonPropertyDescription("OpenTelemetry service name. Takes precedence over 'service.name' defined in the 'resourceAttributes' map.")
+    /**
+     * @deprecated Use {@link TelemetrySpec#getServiceName()}
+     */
+    @Deprecated
+    @JsonPropertyDescription("DEPRECATED - use the 'telemetry.serviceName' instead. OpenTelemetry service name. Takes precedence over 'service.name' defined in the 'resourceAttributes' map.")
```
Comment (shawkins) [inline operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TracingSpec.java:44]: I think we have an issue somewhere about emitting a CR warning when a deprecated field is used. Would be nice to have here, but could also just be handled in that follow-up.

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+    public void setResourceAttributes(Map<String, String> resourceAttributes) {
+        this.resourceAttributes = resourceAttributes;
+    }
+
+    /**
+     * Convert resource attributes in format key=val delimited by comma to string
+     */
+    public static String convertResourceAttributesToString(Map<String, String> attributes) {
+        return attributes.entrySet().stream()
+                .map(attr -> String.format("%s=%s", attr.getKey(), attr.getValue()))
```
Comment (shawkins) [inline operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java:73]: Are there any encoding concerns, or is it not possible for keys and values to contain = or ,

File: docs/guides/observability/telemetry.adoc [hunk 3]
```diff
@@ -51,6 +51,29 @@ You can change the protocol via CLI as follows:
...
+
+[source,yaml]
+----
+apiVersion: k8s.keycloak.org/v2alpha1
+kind: Keycloak
+metadata:
+  name: example-kc
+spec:
+  telemetry:
+    endpoint: http://my-telemetry:4317          # default 'http://localhost:4317'
```
Comment (shawkins) [inline docs/guides/observability/telemetry.adoc:65]: Not specifically related to this pr, but I think we're now enabling the telemetry endpoint by default in the operator example kc CR that is the basis for most deployments. The server logs contain warnings that the endpoint is unreachable.

**Review by shawkins — COMMENTED** [review]
This looks good in general, just a couple of thoughts / questions.

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TracingSpec.java (hunk 1 above)
Comment (mabartos) [reply operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TracingSpec.java:44]: I haven't found any existing issue.

- Created: https://github.com/keycloak/keycloak/issues/45567

EDIT: Existing issue: https://github.com/keycloak/keycloak/issues/28600

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java (hunk 2 above)
Comment (mabartos) [reply operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java:73]: There might be no encoding concerns nor usage of '=' and ','. 

This just translates the map of resource attributes directly to the format that Quarkus expects, like: `ATTRIBUTES_ENV='attr1=val1,attr2=val2'` 

We could potentially introduce a wildcard option, but not sure if it's required. 

@shawkins Or what are you referring to?

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java:73]: If an attribute key, or value, contains '=' or ',', then basic concat will not be parsed correctly.

If as you are saying that = and , aren't valid in keys or values in general, then that's not a big concern - more just a user error if they were to try something like that.

File: docs/guides/observability/telemetry.adoc [hunk 4]
```diff
@@ -51,6 +51,29 @@ You can change the protocol via CLI as follows:
...
+    serviceName: my-best-keycloak-telemetry     # default 'keycloak'
+    protocol: http/protobuf                     # default 'grpc'
+    resourceAttributes:
+      service.namespace: keycloak-namespace-telemetry
+----
+
+These fields should reflect 1:1 association with `telemetry-*` options that contain more information.
```
Comment (shawkins) [inline docs/guides/observability/telemetry.adoc]:
```suggestion
These fields should reflect a 1:1 association with `telemetry-*` server options.
```

File: docs/guides/observability/telemetry.adoc [hunk 5]
```diff
@@ -51,6 +51,29 @@ You can change the protocol via CLI as follows:
 
 <@kc.start parameters="--telemetry-protocol=http/protobuf"/>
 
+== Configuration via Keycloak CR (Operator)
+You can change the telemetry configuration via Keycloak CR when using the Operator.
+It will help to simplify telemetry settings in your deployment by using the first-class citizen configuration options.
+
+You can change telemetry configuration via Keycloak CR fields as follows:
```
Comment (shawkins) [inline docs/guides/observability/telemetry.adoc]:
```suggestion
The Keycloak CR has first-class citizen configuration options for telemetry. These may be configured under the spec.telemtry stanza as follows:
```

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java (hunk 2 above)
Comment (mabartos) [reply operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java:73]: > If as you are saying that = and , aren't valid in keys or values in general, then that's not a big concern - more just a user error if they were to try something like that.

@shawkins Yes, the '=' and ',' are not valid for keys and values of resource attributes. I'll try to add some validation of keys/values. Thanks!

File: docs/guides/observability/telemetry.adoc (hunk 3 above)
Comment (mabartos) [reply docs/guides/observability/telemetry.adoc:65]: > Not specifically related to this pr, but I think we're now enabling the telemetry endpoint by default in the operator example kc CR that is the basis for most deployments.

@shawkins But you mean it's enabled by default in tests, right? Or do you think users use that as a basis for their deployments?

Comment (mabartos) [reply docs/guides/observability/telemetry.adoc:65]: @shawkins Or I guess you mean this test CR, right? [test-serialization-keycloak-cr.yml‎](https://github.com/keycloak/keycloak/pull/45397/changes/BASE..218bf0503d7292b0395fe87989bf85aeae6bb701#diff-27689ffed0ac1d16cc0ee50bcb94f46515d74ac6af0354e52df48379e77d146c)

There's also a specified endpoint for tracing, which is also not enabled, so the log should contain the warning as well. We can consider it in a follow-up task.

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java (hunk 2 above)
Comment (mabartos) [reply operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TelemetrySpec.java:73]: @shawkins I added the validation: https://github.com/keycloak/keycloak/pull/45397/changes/27ac0f6fcca9a096adb132cc70356d57fa537064

File: docs/documentation/upgrading/topics/changes/changes-26_6_0.adoc [hunk 6]
```diff
@@ -44,7 +44,10 @@ Specific sensitive information is omitted from the HTTP Access log, such as the
 
 The following sections provide details on deprecated features.
 
-=== <TODO>
+=== Deprecation of specific tracing properties in Keycloak CR
+
+The `tracing.serviceName`, and `tracing.resourceAttributes`, first-class citizens of the Keycloak CR, are now deprecated.
+You should use the new `telemetry.serviceName`, and `telemetry.resourceAttributes` first class citizens that are shared among all OpenTelemetry components - logs, metrics, and traces.
```
Comment (vmuzikar) [inline docs/documentation/upgrading/topics/changes/changes-26_6_0.adoc]:
```suggestion
The `tracing.serviceName`, and `tracing.resourceAttributes`, fields of the Keycloak CR, are now deprecated.
You should use the new `telemetry.serviceName`, and `telemetry.resourceAttributes` fields that are shared among all OpenTelemetry components - logs, metrics, and traces.
```

**Review by vmuzikar — DISMISSED** [review]
@mabartos Thank you for the PR. Looks good, added one nitpick.

File: docs/documentation/upgrading/topics/changes/changes-26_6_0.adoc (hunk 6 above)
Comment (mabartos) [reply docs/documentation/upgrading/topics/changes/changes-26_6_0.adoc]: @vmuzikar Thanks for the review! We can do this in a follow-up if @shawkins does not have any other comments to this (only the CI for docs will run).

Comment (shawkins) [reply docs/documentation/upgrading/topics/changes/changes-26_6_0.adoc]: Nothing more from me.

File: docs/guides/observability/telemetry.adoc (hunk 3 above)
Comment (shawkins) [reply docs/guides/observability/telemetry.adoc:65]: Yes, we have logs like:

```
2026-01-20 16:33:21,417 WARNING [io.quarkus.opentelemetry.runtime.exporter.otlp.sender.VertxGrpcSender] (vert.x-eventloop-thread-3) Failed to export TraceRequestMarshaler. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
```

Comment (mabartos) [reply docs/guides/observability/telemetry.adoc:65]: Created follow-up issue:
- https://github.com/keycloak/keycloak/issues/45623

Comment (mabartos) [reply docs/guides/observability/telemetry.adoc:65]: Solved in commit: https://github.com/keycloak/keycloak/pull/45397/commits/0cd2526662169e9b205d984d465084f40fa19736

**Comment by mabartos** [comment]
@shawkins @vmuzikar Should be ready to review.

Added a commit solving the https://github.com/keycloak/keycloak/issues/45623

File: docs/documentation/upgrading/topics/changes/changes-26_6_0.adoc [hunk 7]
```diff
@@ -39,23 +39,15 @@ This change should prevent deadlocks due to pinned virtual threads.
...
-
 // ------------------------ Deprecated features ------------------------ //
 == Deprecated features
 
 The following sections provide details on deprecated features.
 
-=== <TODO>
+=== Deprecation of specific tracing properties in Keycloak CR
+
+The `tracing.serviceName`, and `tracing.resourceAttributes`, fields of the Keycloak CR, are now deprecated.
```
Comment (vmuzikar) [inline docs/documentation/upgrading/topics/changes/changes-26_6_0.adoc]:
```suggestion
The `tracing.serviceName`, and `tracing.resourceAttributes` fields of the Keycloak CR, are now deprecated.
```

**Review by vmuzikar — DISMISSED** [review]
Looks good to me, thanks. I spotted one extra comma, I'll try to remove it and merge.

**Review by vmuzikar — APPROVED** [review]
