### PR TITLE
Escape $ sign when replacing clientId in the role mappers

### LINKED ISSUE #23692: Genetated access token exception then $ sign in client name
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

If you create a client with a $ sign in its name. Create roles in this client. Assign a client role to a user. Then an exception occurs when requesting a token for this user.
Stacktrace:
```
2023-10-04 11:28:45,249 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-31) Uncaught server error: java.lang.IllegalArgumentException: Illegal group reference
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067)
        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)
        at org.keycloak.protocol.oidc.mappers.AbstractUserRoleMappingMapper.mapClaim(AbstractUserRoleMappingMapper.java:102)
        at org.keycloak.protocol.oidc.mappers.AbstractUserRoleMappingMapper.setClaim(AbstractUserRoleMappingMapper.java:81)
        at org.keycloak.protocol.oidc.mappers.UserClientRoleMappingMapper.setClaim(UserClientRoleMappingMapper.java:129)
        at org.keycloak.protocol.oidc.mappers.AbstractOIDCProtocolMapper.transformAccessToken(AbstractOIDCProtocolMapper.java:82)
        at org.keycloak.protocol.oidc.TokenManager$1.applyMapper(TokenManager.java:756)
        at org.keycloak.protocol.oidc.TokenManager$1.applyMapper(TokenManager.java:753)
        at org.keycloak.protocol.oidc.TokenManager$TokenCollector.lambda$accumulator$3(TokenManager.java:905)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.keycloak.protocol.oidc.TokenManager.transformAccessToken(TokenManager.java:753)
        at org.keycloak.protocol.oidc.TokenManager.createClientAccessToken(TokenManager.java:545)
        at org.keycloak.protocol.oidc.TokenManager$AccessTokenResponseBuilder.generateAccessToken(TokenManager.java:1054)
        at org.keycloak.services.resources.admin.ClientScopeEvaluateResource.lambda$generateExampleAccessToken$5(ClientScopeEvaluateResource.java:235)
        at org.keycloak.services.resources.admin.ClientScopeEvaluateResource.sessionAware(ClientScopeEvaluateResource.java:258)
        at org.keycloak.services.resources.admin.ClientScopeEvaluateResource.generateExampleAccessToken(ClientScopeEvaluateResource.java:231)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Version

22.0.3

### Expected behavior

Control the absence of invalid characters in the names of clients.
Or
Fix the use of regular expressions, for example, CLIENT_ID_PATTERN.matcher(protocolClaim).replaceAll(Matcher.quoteReplacement(clientId))

### Actual behavior

An exception occurs when client roles are inserted into the token and there is a sign $ in the name of clients. 

### How to Reproduce?

1. create a client with a sing $ in the name
2. create a role in the client
3. create a user
4. add client role to the user
5. go to the client card -> Client scopes -> Evaluate
6. choose the user
7. click on "Genetated access token"

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/23692

Minor issue in the role mappers. The `Matcher.replaceAll` uses `$` char to select matching groups. Just using replace in the `clientId` to escape problematic `\`, `.` and `$` characters in the method.

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java [hunk 1]
```diff
@@ -77,9 +77,6 @@ protected static void setClaim(IDToken token, ProtocolMapperModel mappingModel,
 
     private static final Pattern CLIENT_ID_PATTERN = Pattern.compile("\\$\\{client_id\\}");
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java:78]:
```suggestion
    private static final Pattern CLIENT_ID_PATTERN = Pattern.compile(Pattern.quote("${client_id}"));
```

File: services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java [hunk 2]
```diff
@@ -90,11 +87,11 @@ private static void mapClaim(IDToken token, ProtocolMapperModel mappingModel, Ob
...
 
         if (clientId != null) {
-            // case when clientId contains dots
-            clientId = DOT_PATTERN.matcher(clientId).replaceAll(DOT_REPLACEMENT);
             Matcher matcher = CLIENT_ID_PATTERN.matcher(protocolClaim);
             if (matcher.find()) {
-                protocolClaim = matcher.replaceAll(clientId);
+                // case when clientId contains backslash, dot or dollar signs
+                String replacement = clientId.replace("\\", "\\\\\\\\").replace(".", "\\\\.").replace("$", "\\$");
+                protocolClaim = matcher.replaceAll(replacement);
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java:94]:
```suggestion
                protocolClaim = matcher.replaceAll(Matcher.quoteReplacement(clientId));
```

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for preparing this change. Looking at the manual escaping done here, and as regex replacements are quite complex, I suggest to use Java's built-in escapers. 

Note that there are two: one for patterns, one for replacements.

File: services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java (hunk 1 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java]: Good idea! It's done now.

File: services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java (hunk 2 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java]: This one is not so easy, because the `clientId` should escape first dots and backslashes for the claim itself. I added the `quoteReplacement` but it's:

```
protocolClaim = matcher.replaceAll(Matcher.quoteReplacement(clientId.replace("\\", "\\\\").replace(".", "\\.")));
```

Comment (ahus1) [reply services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java]: Thank you for the update. I now know that I still have to learn more about claims. As the test parses it in the response, I approve this. It would still be good if someone else maybe from @keycloak/core would have a look.

**Review by ahus1 — APPROVED** [review]
My comments are resolved. As I found out during the review that I don't know enough about claims, it would still be good if someone else maybe from @keycloak/core would have a look.

**Comment by rmartinc** [comment]
@mposolda @pedroigor WDYT about this?

**Review by mposolda — APPROVED** [review]
Looks good. Hopefully tests are OK
