### PR TITLE
Stops the recreation of managed Keycloak Statefulset Pods when Keycloak Operator restarts occasionally.

### LINKED ISSUE #19725: Operator restarts occasionally result in recreation of managed keycloak Statefulset Pods
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

When the operator container is restarted occasionally the pod template of the keycloak statefulsets managed by the operator changes which leads to a recreation of the keycloak containers managed by the operator.

I noticed the order of environment variables in the pod template changed, which I think is the reason for the recreation.

Pre operator container restart keycloak statefulset spec:
```yaml
spec:
  ...
  template:
    ...
    spec:
      containers:
      - args:
        - start
        env:
        - name: KC_CACHE_STACK
          value: kubernetes
        - name: KC_CACHE
          value: ispn
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_PROXY
          value: edge
      ...
```

Post operator container restart keycloak statefulset spec:
```yaml
spec:
  ...
  template:
    ...
    spec:
      containers:
      - args:
        - start
        env:
        - name: KC_CACHE_STACK
          value: kubernetes
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_CACHE
          value: ispn
        - name: KC_PROXY
          value: edge
      ...
```

### Version

20.0.5

### Expected behavior

Even though the keycloak operator container was restarted, reconciliation should not result in a recreation of the managed keycloak statefulset pods if no configuration was changed.

### Actual behavior

Keycloak Pods are recreated by the operator when it restarts.

### How to Reproduce?

1. Install the keycloak operator in a kubernetes cluster
2. Create a valid Keycloak Resource without specifying the [default configurations](https://github.com/keycloak/keycloak/blob/20.0.5/operator/src/main/java/org/keycloak/operator/Constants.java#L42-L47)
5. Wait until the keycloak StatefulSet is ready and reconciliation of the Keycloak Resource has successfully finished
6. Redeploy the keycloak operator multiple times and notice the order of the environment variables in the Keycloak Statefulset's pod template to change and that keycloak pods are being recreated

### Anything else?

I think the reason for the behavior is that a Map is used for the 
[default configurations](https://github.com/keycloak/keycloak/blob/20.0.5/operator/src/main/java/org/keycloak/operator/Constants.java#L42-L47) 
which does not guarantee order when converted later to a list.
https://github.com/keycloak/keycloak/blob/20.0.5/operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java#L434-L436

### PR DESCRIPTION
**Pull request by andre-nascimento6791**
When the Operator container is restarted occasionally the Pod Template of the Keycloak StatefulSets managed by the Operator changes which leads to a recreation of the Keycloak containers managed by the Operator. This behavior happens because the Map used for the [default configurations] does not guarantee the order when converted later to a list.

This was fixed by sorting the Map of "default configurations" before converting to a List.

Closes #19725

### CODE REVIEW

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java [hunk 1]
```diff
@@ -442,6 +445,7 @@ private List<EnvVar> getEnvVars() {
         // set env vars
         serverConfigSecretsNames = new HashSet<>();
         List<EnvVar> envVars = serverConfig.stream()
+                .sorted((e1, e2) -> e1.getName().compareTo(e2.getName()))
```
Comment (vmuzikar) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java:448]: I don't think we need to sort it here again, do we?

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java [hunk 2]
```diff
@@ -429,7 +429,10 @@ private KeycloakDistConfigurator configureDist() {
 
     private List<EnvVar> getEnvVars() {
         // default config values
-        List<ValueOrSecret> serverConfig = Constants.DEFAULT_DIST_CONFIG.entrySet().stream()
+        List<ValueOrSecret> serverConfig = Constants.DEFAULT_DIST_CONFIG
+                .entrySet()
+                .stream()
+                .sorted((e1, e2) -> e1.getKey().compareTo(e2.getKey()))
```
Comment (vmuzikar) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java:435]: Thanks @andre-nascimento-rh, good catch. As per [documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Map.html), indeed we can't rely on the ordering of immutable maps:
> The iteration order of mappings is unspecified and is subject to change.

I am think whether we should be really sorting the options at each reconciliation loop. Maybe a more optimal approach would be to use a List of `ValueOrSecret` directly in the `DEFAULT_DIST_CONFIG`. That way we'd also optimize the current code avoiding mapping the constant Map to List in each reconciliation loop. Another option would be using an ordered Map, e.g. `LinkedHashMap`. But that might be a bit overkill. WDYT?

**Review by vmuzikar — CHANGES_REQUESTED** [review]

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java (hunk 1 above)
Comment (andre-nascimento-rh) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java]: Removed. 

Thanks.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java (hunk 2 above)
Comment (andre-nascimento-rh) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java]: I went for the first suggestion. Changed.

Thanks.

**Comment by mabartos** [comment]
@vmuzikar @andre-nascimento-rh 
What about leveraging hash-based implementations of collections? As for `HashSet`, hash codes of items are used for determining the position in a table. We don't really care about insertion orders but rather check the presence of changes in the collection, right? IMO, the `HashSet<ValueOrSecret>` would be suitable for this.

WDYT?

**Comment by vmuzikar** [comment]
@mabartos Unfortunately, [it doesn't seem so](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/HashSet.html):
> It makes no guarantees as to the iteration order of the set

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks @andre-nascimento-rh!
