### PR TITLE
Data too long for column 'DETAILS_JSON'

### LINKED ISSUE #17258: Data too long for column 'DETAILS_JSON'
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

When spamming keycloak-javascript-adapter initiated logins by refreshing my frontend many times in a row, I can find the following exception in the Keycloak logs. The user is being redirected to the "500 internal server error" Keycloak website. 

Logs: 

```
2023-02-22 11:27:16,457 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-521) SQL Error: 1406, SQLState: 22001
2023-02-22 11:27:16,457 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-521) Data truncation: Data too long for column 'DETAILS_JSON' at row 1
2023-02-22 11:27:16,458 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (executor-thread-521) HHH000010: On release of batch it still contained JDBC statements
2023-02-22 11:27:16,465 WARN  [com.arjuna.ats.arjuna] (executor-thread-521) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff6443074d:a937:63ea0e5c:1beeac, org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@2f772455 >: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3303)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2438)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:356)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
	at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:76)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:360)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:91)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:105)
	at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:90)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
	at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:64)
	at org.keycloak.quarkus.runtime.integration.jaxrs.TransactionalResponseFilter.filter(TransactionalResponseFilter.java:47)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:367)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.hibernate.exception.DataException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:52)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3375)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3937)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
	... 54 more
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'DETAILS_JSON' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
	at com.mysql.cj.jdbc.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:596)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 66 more
```

### Version

20.0.5

### Expected behavior

The Keycloak server does not get internal server errors when the user attempts to login multiple times in a row

### Actual behavior

Refreshing/requesting the token of the user does end up in a 500 internal server error response

### How to Reproduce?

Use a frontend library to initiate the OIDC login automatically when you open the frontend website.
Refresh the website in your browser in a quick succession after the login was successful using the same session (do not use private windows or clear cookies in-between). 
After some attempts, the abovementioned exception will be thrown. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vramik**
Closes #17258

The PR adds new LOB column into a database `EVENT_ENTITY.DETAILS_JSON_LONG_VALUE`

As requested there is no migration of existing events. the value is stored either in original or new column based on the length of the value.

Options for trimming the events were removed from codebase as well as from documentation. A note in migration guide was added.

### CODE REVIEW

File: model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java [hunk 1]
```diff
@@ -165,40 +160,18 @@ private EventEntity convertEvent(Event event) {
         eventEntity.setIpAddress(event.getIpAddress());
         eventEntity.setError(event.getError());
         try {
-            if (maxDetailLength > 0 && event.getDetails() != null) {
-                Map<String, String> result = new HashMap<>(event.getDetails());
-                result.entrySet().forEach(t -> t.setValue(trimToMaxDetailLength(t.getValue())));
-
-                eventEntity.setDetailsJson(trimToMaxFieldLength(mapper.writeValueAsString(result)));
+            String details = mapper.writeValueAsString(event.getDetails());
+            if (details == null || details.length() <= 2550) { // 2550 is the lenght of the DETAILS_JSON field in EventEntity
```
Comment (martin-kanis) [inline model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java:164]: Can you define the constant as static final variable and use it on second occurrence as well?

File: docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc [hunk 2]
```diff
@@ -135,3 +135,6 @@ Stream<GroupModel> getTopLevelGroupsStream(RealmModel realm,
 
 Endpoint `GET {keycloak server}/realms/{realm}/groups/{group_id}/children` added as a way to get subgroups of specific groups that support pagination
 
+= Removal of the options to trim the event's length
+
+Since this release Keycloak supports long values for both `EventEntity` details and `AdminEventEntity` representation columns. Therefore it no longer supports options for trimming event detail length `--spi-events-store-jpa-max-detail-length` and `--spi-events-store-jpa-max-field-length`.
```
Comment (martin-kanis) [inline docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc:140]: Feels like missing comma to me, but would be great if someone can verify.
```suggestion
Since this release, Keycloak supports long values for both `EventEntity` details and `AdminEventEntity` representation columns. Therefore it no longer supports options for trimming event detail length `--spi-events-store-jpa-max-detail-length` and `--spi-events-store-jpa-max-field-length`.
```

**Review by martin-kanis — CHANGES_REQUESTED** [review]
@vramik Thanks for the PR. It looks good, I have just minor nitpicks.

File: docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc (hunk 2 above)
Comment (martin-kanis) [reply docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc:140]: Also comma after "Therefore"

**Review by ahus1 — CHANGES_REQUESTED** [review]
Hi @vramik - thank you for taking up this issue. 

I reviewed the code, and found the following bits that might need changing: 

* The column REPRESENTATION in ADMIN_EVENT_ENTITY is of type TEXT already. While the Liquibase scripts contain a length, I verified locally on PostgreSQL, MariaDB and OracleDB that this is ignored. So it seems to me that it already allows an arbitrary length. We should only remove the length attribute of the annotation. 
* For the EventEntity, I wonder if we could instead of adding those additional gettes and setters wrap the logic about the length of the field in to EventEntity#getDetailsJson and EventEntity#setDetailsJson. 
* I also wonder if we want to now always write the data to the new column, so that we could in the future have a background process to migrate entity and eventually remove the column. When doing this, we wouldn't need to care about the column length in the code as well. WDYT?

**Review by ahus1 — COMMENTED** [review]
Thank you @vramik - this PR looks good to me, and it is IMHO ready to be merged once it is ready from your side.

One small nitpic: Please add a comment to the old field `detailsJson` explaining that this is the legacy fields which we keep around to be able to read old events without the need to migrate them.

**Comment by vramik** [comment]
Thank you @ahus1 and @martin-kanis for your reviews!

> * The column REPRESENTATION in ADMIN_EVENT_ENTITY is of type TEXT already. While the Liquibase scripts contain a length, I verified locally on PostgreSQL, MariaDB and OracleDB that this is ignored. So it seems to me that it already allows an arbitrary length. We should only remove the length attribute of the annotation.

Annotation removed

> * For the EventEntity, I wonder if we could instead of adding those additional gettes and setters wrap the logic about the length of the field in to EventEntity#getDetailsJson and EventEntity#setDetailsJson.

I was testing this approach and it seems it works fine even with hibernate, where I had my doubts. Thanks for suggestion that.

> * I also wonder if we want to now always write the data to the new column, so that we could in the future have a background process to migrate entity and eventually remove the column. When doing this, we wouldn't need to care about the column length in the code as well. WDYT?

+1 I've incorporated your proposal, thanks

From my POV the PR is ready for another round of review. Thank you.

**Comment by vramik** [comment]
> One small nitpic: Please add a comment to the old field `detailsJson` explaining that this is the legacy fields which we keep around to be able to read old events without the need to migrate them.

Will do, thanks

**Review by ahus1 — APPROVED** [review]
Thank you, this looks great. I also see that you addressed the comments from Martin, so this PR is good to be merged.

**Review by martin-kanis — APPROVED** [review]
Thanks @vramik!
