### PR TITLE
Block shutdown if the Infinispan cluster is not stable

### LINKED ISSUE #44620: Possible data loss when scaling Keycloak StatefulSet down (on Kubernetes)
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

When testing Keycloak scaling down capabilities (within https://github.com/defenseunicorns/uds-core/issues/2003), I discovered that the node properly leaves the cluster but it doesn't take ongoing rebalance into account. As a result, Keycloak scales down very rapidly (going from 5 to 1 instance in a matter of second) which can lead to the data loss when caches contain logs of data. 

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

When scaling down, during the shutdown hook, Infinispan should block until an ongoing rebalance completes and data segments are reshuffled. 

### Actual behavior

Infinispan seems to properly leave the cluster but doesn't take the ongoing rebalance into consideration.

### How to Reproduce?

1. Get a healthy cluster of 5 nodes up and running.
2. Scale the StatefulSet from 5 to 1
3. Observe the rapid scale down

### Anything else?

I successfully verified that:

* The StatefulSet controller behaves correctly and the deletion order is correct:

```
$ kubectl get events -n keycloak --sort-by=.lastTimestamp | grep keycloak
15m         Normal    SuccessfulDelete               statefulset/keycloak          delete Pod keycloak-4 in StatefulSet keycloak successful
15m         Normal    SuccessfulDelete               statefulset/keycloak          delete Pod keycloak-3 in StatefulSet keycloak successful
15m         Normal    Killing                        pod/keycloak-3                Stopping container keycloak
15m         Normal    SuccessfulDelete               statefulset/keycloak          delete Pod keycloak-2 in StatefulSet keycloak successful
15m         Normal    Killing                        pod/keycloak-2                Stopping container keycloak
15m         Normal    Killing                        pod/keycloak-1                Stopping container keycloak
15m         Normal    SuccessfulDelete               statefulset/keycloak          delete Pod keycloak-1 in StatefulSet keycloak successful
```

* JGroups properly installs new view and then FD Protocols note the member being down. This order of events suggests a proper implementation of the graceful leave, so I guess shutdown hooks work correctly. 

* I checked the code `DefaultInfinispanConnectionProviderFactory#close` code and indeed it seems to call `CacheManager#stop` properly. 

* I don't have the code at hand right now but I think it used to work correctly with the Golang Operator.

### PR DESCRIPTION
**Pull request by pruivo**
If a rebalance is in progress, block the shutdown procedure until it finishes or a timeout is reached.

Closes #44620

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java [hunk 1]
```diff
@@ -131,6 +136,7 @@ public static void runWithWriteLockOnCacheManager(Runnable task) {
     @Override
     public void close() {
         logger.debug("Closing provider");
+        shutdownManager.onShutdown();
```
Comment (shawkins) [inline model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:139]: Seems like blocking the other close calls could eventually be an issue as we're serializing the orderly shutdown.

Should we think about allowing for a close method that returns a future or a higher level way to register a shutdown hook? The latter relates to https://github.com/keycloak/keycloak/issues/42670 which proposed adding post start and pre stop events - if that proposal were expanded so that the pre stop event could have shutdown hooks registered. cc @thomasdarimont

Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:142]: > Seems like blocking the other close calls could eventually be an issue as we're serializing the orderly shutdown.

We require this behavior. As a concrete example, the JPA layer **must** be closed after Infinspan/JGroups because we have to clean up some tables from stale data. I can't see how the future or the shutdown hook will help with this case - at the end of the day, order matters. 

Note that this PR is a workaround (and not a good one) until the feature is implemented in Infinispan. The `CacheManager.stop()` will do the blocking that I'm doing manually in this PR. https://github.com/infinispan/infinispan/issues/17016

Comment (shawkins) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:142]: >  I can't see how the future or the shutdown hook will help with this case - at the end of the day, order matters.

Sure, and ordering can easily be preserved with a CompletableFuture. You just need to compose them in the desired order, then wait for everything to complete. I can provide an example of what that could look like if you want.

This also relates to something @ahus1 was looking to do for startup parallelization, which used virtual threads for init - the same principle could be applied to close.

Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:142]: Please check whether the shutdown time is long enough to compensate for the work we need to parallelize everything. It only takes 200ms on my machine.

Comment (shawkins) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:142]: > Please check whether the shutdown time is long enough to compensate for the work we need to parallelize everything. It only takes 200ms on my machine.

If you are certain that it won't block for long, then there's no need to do additional work.

Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:142]: No, it can block for as long as `--shutdown-timeout` at max.

The point that I want to make is that the parallel approach may only be a couple hundreds milliseconds faster than the serial. 

If you have a PoC, we can measure both times to see what the gain is and if it is significant.

Comment (shawkins) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:142]: What I'm roughly describing is like: https://github.com/keycloak/keycloak/compare/main...shawkins:asyncClose?expand=1

With the expectation that factories with long running close methods should override the new method and provide a CompletionStage (or it just a easily be a CompletableFuture).

Alternatively if we don't want to directly expand the api this way, it could be done as a separate interface, or if we assume that it isn't likely that factories could provide a future then there could be annonation like AsyncClose such that the close provider logic would delegate the task to a threadpool to create the future.

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:142]: My discussion on startup time was driven by a customer need to see a fast startup after a failover. The customer chose "4 seconds" as a goal here. 

I don't see a similar need for the shutdown. I addition to that, I consider this out-of-scope for the problem this one is planning to solve.

**Review by ahus1 — DISMISSED** [review]
Thank you for this PR. 

How I understand what is happening here: Keycloak will first wait for running HTTP requests to finish. And then it will wait again for the same period for the Infinispan cluster to stabilize. 

Assuming the value is set to 30 seconds, this then doubles to 60 seconds if both are maxed out. 

From a user's perspective, I want them to set only one timeout.  Can you please check if this is possible?

File: model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java (hunk 1 above)
Comment (shawkins) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:142]: > My discussion on startup time was driven by a customer need to see a fast startup after a failover. The customer chose "4 seconds" as a goal here.

Yes, I understand that it has a different rationale, but there is a symmetry to the problem of long-running blocking operations in our start and shutdown sequences. And I'm not sure if we're trying to account there or here for the possiblity of unknown init / close times from user deployed factories - not just our built-in ones.

> I don't see a similar need for the shutdown. I addition to that, I consider this out-of-scope for the problem this one is planning to solve.

The problem it is trying to solve is highly related to the concern you are bringing up in https://github.com/keycloak/keycloak/pull/48341#pullrequestreview-4160984424 - that is if we have a serial closure of factories, a single long-running closure could consumer the entire timeout and prevent or delay the closure of other factories. 

If at this point in time there is a well-defined ordering of long-running factory closures, then I agree parallizing is out-of-scope.

**Comment by pruivo** [comment]
> Thank you for this PR.
> 
> How I understand what is happening here: Keycloak will first wait for running HTTP requests to finish. And then it will wait again for the same period for the Infinispan cluster to stabilize.
> 
> Assuming the value is set to 30 seconds, this then doubles to 60 seconds if both are maxed out.
> 
> From a user's perspective, I want them to set only one timeout. Can you please check if this is possible?

Isn't this the plan? You want to prevent `CacheManager.stop()` from being invoked if a rebalance is in progress, and Quarkus/Keycloak only invokes it after `delay-timeout` and `shutdown-timeout` have passed.

**Comment by ahus1** [comment]
> You want to prevent CacheManager.stop() from being invoked if a rebalance is in progress

Yes to that ...

> and Quarkus/Keycloak only invokes it after delay-timeout and shutdown-timeout have passed.

... and this is unfortunate. Couldn't one wait inside of the shutdown-timeout while a rebalance is in progress, or would that then be less safe? 

Is there any other way to have it behave like one timeout (like `CacheManager.stop()` using only the remaining time from the shutdown-timeout)? 

Yes, this is all ugly, happy to hear other suggestions to have the one-timeout-rules-all observed behavior.

**Comment by pruivo** [comment]
> Couldn't one wait inside of the shutdown-timeout while a rebalance is in progress, or would that then be less safe?

If there is no rebalance when the shutdown-timeout period starts, there will be no wait. But if a rebalance starts in the middle while already inside the shutdown-timeout period, it won't be detected. 

> like CacheManager.stop() using only the remaining time from the shutdown-timeout

That's easy to do. I'll do the change.

**Comment by ahus1** [comment]
@pruivo - as discussed earlier today, I've updated the shutdown timeout to 10 seconds. 

While I was originally thinking about backporting this to 26.6, I now considered this change too big, at least for now. With that, I've removed the backport label, so it will be in 26.7.

I've also updated the docs to reflect the new behavior. Please review. 

Once you're ok with the changes and the build is green, I'll proceed in merging this one.

**Comment by pruivo** [comment]
> @pruivo - as discussed earlier today, I've updated the shutdown timeout to 10 seconds.
> 
> While I was originally thinking about backporting this to 26.6, I now considered this change too big, at least for now. With that, I've removed the backport label, so it will be in 26.7.
> 
> I've also updated the docs to reflect the new behavior. Please review.
> 
> Once you're ok with the changes and the build is green, I'll proceed in merging this one.

It looks good to me, thanks.

**Review by ahus1 — APPROVED** [review]
