### PR TITLE
Don't keep an old session to avoid a stable object and a memory leak

### LINKED ISSUE #43761: QuarkusKeycloakSession kept in memory for each timer
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When creating a timer, an instance of the KeycloakSession is kept in memory.

The code only needs the sessionFactory, so this should be avoided. 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Don't keep the session, instead keep the sessionFactory

### Actual behavior

A session is kept, and never used. It is also problematic as that session is then later already closed and/or stale.

### How to Reproduce?

Start up Keycloak, and create a heap dump. Look for QuarkusKeycloakSession instances and where they are retained.

### Anything else?

I'll prepare a PR

### PR DESCRIPTION
**Pull request by ahus1**
Closes #43761

### CODE REVIEW

**Comment by ahus1** [comment]
@ryanemerson - please review when have the time and feel familiar enough with the code at hand. Thanks!

File: services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java [hunk 1]
```diff
@@ -37,13 +38,13 @@ public class BasicTimerProvider implements TimerProvider {
...
 
-    private final KeycloakSession session;
+    private final KeycloakSessionFactory sessionFactory;
     private final Timer timer;
     private final int transactionTimeout;
     private final BasicTimerProviderFactory factory;
 
     public BasicTimerProvider(KeycloakSession session, Timer timer, int transactionTimeout, BasicTimerProviderFactory factory) {
-        this.session = session;
+        this.sessionFactory = session.getKeycloakSessionFactory();
```
Comment (ryanemerson) [inline services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java]: Is the `services` module considered API that we can't break?

If not, I would change the ctor to be `BasicTimerProvider(KeycloakSessionFactory sessionFactory, ...)`, otherwise it's probably not worth deprecating the old one and adding a distinct constructor.

Comment (ahus1) [reply services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java]: Thank you for the review. I went the extra mile to deprecate the old timer provider. It is a private API, still as I plan to backport it to a patch release, I want to go the deprecation route.

Comment (shawkins) [reply services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java]: Rather than the session or sessionFactory member variable, you can use KeycloakModelUtils.getKeycloakSession when creating the ScheduledTaskRunner.

**Comment by ryanemerson** [comment]
@ahus1 I pushed a commit to reduce repetition, feel free to disregard if you prefer the more verbose code.

**Review by ryanemerson — DISMISSED** [review]

File: services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java (hunk 1 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java]: @shawkins - let's do that as the next step if you are ok with that.

Comment (shawkins) [reply services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java]: @ahus1 looking at this more, I'm unsure of this change in general. It's a common pattern for providers to hold references to the session as they themselves are session scoped.

What exactly is holding a reference to the BasicTimerProvider in this scenario?

Comment (ahus1) [reply services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java]: There is the inner anonymous class that holds a reference, see this screenshot. I'll rework it to use an inner static class instead. 

image

**Comment by ahus1** [comment]
@ryanemerson  or  @shawkins - please re-review when you have the time. Thanks!

**Review by ryanemerson — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Review by shawkins — APPROVED** [review]
LGTM, thanks @ahus1
