### PR TITLE
fix: converting db-connect-timeout to be used for all datasources

### LINKED ISSUE #48053: Allow db-connect-timeout to be used for all datasources
### Description

Currently db-connect-timeout is only for the primary datasource.

### Value Proposition

For greater consistency of datasource settings and so users don't have to resort to quarkus properties.

### Goals

Allow db-connect-timeout to be used for all datasources.

### Non-Goals

N/A

### Discussion

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #48053

Also consolidates the connect timeout logic.

### CODE REVIEW

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 1]
```diff
@@ -297,7 +297,7 @@ private void assertUnknownOption(NonRunningPicocli nonRunningPicocli) {
...
+                "Possible solutions: --db-url, --db-connect-timeout, --db-url-host, --db-url-database, --db-url-port, --db-url-properties, --db-username, --db-password, --db-schema, --db-pool-initial-size, --db-pool-min-size, --db-pool-max-size, --db-pool-max-lifetime, --db-debug-jpql, --db-log-slow-queries-threshold, --db-tls-mode, --db-tls-trust-store-file, --db-tls-trust-store-type, --db-tls-trust-store-password, --db-driver, --db, --db-url-full-<datasource>, --db-connect-timeout-<datasource>, --db-url-host-<datasource>, --db-url-database-<datasource>, --db-url-port-<datasource>, --db-url-properties-<datasource>, --db-username-<datasource>, --db-password-<datasource>, --db-schema-<datasource>, --db-pool-initial-size-<datasource>, --db-pool-min-size-<datasource>, --db-pool-max-size-<datasource>, --db-debug-jpql-<datasource>, --db-log-slow-queries-threshold-<datasource>, --db-tls-mode-<datasource>, --db-tls-trust-store-file-<datasource>, --db-tls-trust-store-type-<datasource>, --db-tls-trust-store-password-<datasource>, --db-enabled-<datasource>, --db-driver-<datasource>, --db-kind-<datasource>"));
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:300]: Just info: It's getting to be quite messy due to the many options here. Follow-up: maybe would be good to show only not <datasource> options if no datasource is attempted? It means, trying to detect if the user is trying to put the datasource option or not - not sure how challenging it might be.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java [hunk 2]
```diff
@@ -314,49 +292,36 @@ public static boolean isMssqlSendStringParametersAsUnicode() {
...
+                return null;
+            }
 
-        String dbDriver = Configuration.getConfigValue(DatabaseOptions.DB_DRIVER).getValue();
-        if (!Objects.equals(Database.getDriver(db, true).orElse(null), dbDriver) &&
-                !Objects.equals(Database.getDriver(db, false).orElse(null), dbDriver)) {
-            // Custom JDBC driver (e.g. AWS JDBC Wrapper) — do not inject defaults
-            return false;
-        }
+            String dbUrl = Configuration.getConfigValue(DatabaseOptions.DB_URL).getValueOrDefault("");
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java]:
```suggestion
            String dbUrl = findDatabaseUrl(datasource).orElse("");
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java [hunk 3]
```diff
@@ -314,49 +292,36 @@ public static boolean isMssqlSendStringParametersAsUnicode() {
...
+            String dbUrlProperties = Configuration.getKcConfigValue(DatabaseOptions.DB_URL_PROPERTIES.getKey()).getValueOrDefault("");
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java]:
```suggestion
            String dbUrlProperties = getDatasourceOptionValue(DatabaseOptions.DB_URL_PROPERTIES, datasource).orElse("");
```

**Review by mabartos — CHANGES_REQUESTED** [review]
@shawkins Just a few suggestions for the named datasource keys for URL and properties (even as Copilot suggested). Otherwise LGTM, nice! Would be good to update/add tests for this, as it hasn't been caught.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java [hunk 4]
```diff
@@ -314,49 +292,36 @@ public static boolean isMssqlSendStringParametersAsUnicode() {
...
 
-        String dbUrl = Configuration.getConfigValue(DatabaseOptions.DB_URL).getValueOrDefault("");
-        String dbUrlProperties = Configuration.getKcConfigValue(DatabaseOptions.DB_URL_PROPERTIES.getKey()).getValueOrDefault("");
+            // Property already set explicitly by the user — do not override
+            if  (dbUrl.contains(timeoutProperty) || dbUrlProperties.contains(timeoutProperty)) {
+                return null;
```
[the remark this answers is not in the document]
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java]: Relevant - mentioned in the review below.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java [hunk 5]
```diff
@@ -314,49 +292,36 @@ public static boolean isMssqlSendStringParametersAsUnicode() {
...
+            }
 
-    private static boolean isConnectTimeoutEnabled(Database.Vendor expectedVendor, String timeoutProperty) {
-        String db = Configuration.getConfigValue(DB).getValue();
-        Database.Vendor vendor = Database.getVendor(db).orElse(null);
-        if (vendor != expectedVendor) {
-            return false;
-        }
+            String dbDriver = getDatasourceOptionValue(DatabaseOptions.DB_DRIVER, datasource).orElse(null);
+            if (!Objects.equals(Database.getDriver(db, true).orElse(null), dbDriver) &&
```
Comment (pruivo) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java:306]: Should we drop this check? It annoys me that the CLI options only apply to default drivers. cc @ahus1

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:300]: It can be captured as a follow-up, but it could be a little messy as this list is coming directly from picocli.

**Review by mabartos — APPROVED** [review]
@shawkins LGTM, thanks!

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java (hunk 5 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java:306]: @pruivo do you want to address that here or in a follow-up?

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:300]: Captured https://github.com/keycloak/keycloak/issues/48115

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java (hunk 5 above)
Comment (pruivo) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java:306]: @shawkins If you agree with the suggestion, do it here :+1:

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java:306]: My understanding of the concern is that an alternative driver, such as datadirect, may not use the same property key/value semantics as the standard one, so it's better to do nothing than something that may be wrong.

**Review by pruivo — APPROVED** [review]
