### PR TITLE
better unset check

### LINKED ISSUE #32059: Look around window cannot be set to 0
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Since keycloak 24 the `Look around window` configuration option in the OTP policies (Authentication ⟶ Policies ⟶ OTP policy) cannot be configured to 0. That property is the extra time periods (TOTP) or counts (HOTP) the server will take into account just in case the generator and server are out of sync. So the value 0 makes sense (no extra time windows for TOTP and no extra counts for HOTP).

The configuration for OTP is from 0 to any max number with default 1 ([here](https://github.com/keycloak/keycloak/blob/25.0.2/js/apps/admin-ui/src/authentication/policies/OtpPolicy.tsx#L178)). So 0 should be allowed.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Value 0 should be allowed.

### Actual behavior

When you set 0 it converts to default 1.

### How to Reproduce?

Just go to Authentication ⟶ Policies ⟶ OTP policy in your realm. The value for the look around window is 1 by default. Click the minus buttom, it's still 1 and not 0.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #32059
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Comment by rmartinc** [comment]
@edewit I wanted to also change a bit the tooltip of the property. I was working on this [here](https://github.com/rmartinc/keycloak/commit/291698153d6bc4847406f7d2469f17f39b4c8b87). Can you please add the line modified for `lookAroundHelp` tooltip?

**Review by rmartinc — CHANGES_REQUESTED** [review]
@edewit Please add this little change in the tooltip too: https://github.com/rmartinc/keycloak/commit/291698153d6bc4847406f7d2469f17f39b4c8b87#diff-c9ef637a710ad2a1ec0f86584796ce5fff7fa0c7a8702bcd020b29eef4e5af43R2780 (we want to say that the look around window is in token periods for TOTP).

And I would also set the default value if the string is empty or spaces (for example if you remove the value, this PR sets 0). The `Number` returns  0 if `""` or `" "` and IMHO setting the default is better in that case.

```diff
@@ -78,7 +77,12 @@ export const NumberControl = <
               onMinus={() => setValue(value - 1)}
               onChange={(event) => {
                 const newValue = Number(event.currentTarget.value);
-                setValue(!isNaN(newValue) ? newValue : controller.defaultValue);
+                setValue(
+                  isNaN(newValue) ||
+                    (newValue === 0 && event.currentTarget.value.trim() === "")
+                    ? controller.defaultValue
+                    : newValue,
+                );
               }}
             />
           );
```

Although this last part is up to you. You know more than me about this. :smile:

**Review by rmartinc — APPROVED** [review]
Thanks @edewit! LGTM!

File: js/libs/ui-shared/src/controls/NumberControl.tsx [hunk 1]
```diff
@@ -59,9 +60,12 @@ export const NumberControl = <
           const required = !!controller.rules?.required;
           const min = controller.rules?.min;
           const value =
-            field.value === 0 ? controller.defaultValue : field.value;
-          const setValue = (newValue: number) =>
-            field.onChange(min ? Math.max(newValue, Number(min)) : newValue);
+            field.value === undefined ? controller.defaultValue : field.value;
```
Comment (jonkoops) [inline js/libs/ui-shared/src/controls/NumberControl.tsx:63]: Alternatively, the following should do the same:

```ts
const value = field.value ?? controller.defaultValue;
```

File: js/libs/ui-shared/src/controls/NumberControl.tsx [hunk 2]
```diff
@@ -59,9 +60,12 @@ export const NumberControl = <
...
+          const setValue = (newValue: number) => {
+            return field.onChange(
+              min !== undefined ? Math.max(newValue, Number(min)) : newValue,
+            );
+          };
```
Comment (jonkoops) [inline js/libs/ui-shared/src/controls/NumberControl.tsx:68]: This could remain an implicit return
```suggestion
          const setValue = (newValue: number) => field.onChange(
            min !== undefined ? Math.max(newValue, Number(min)) : newValue,
          );
```

**Review by jonkoops — DISMISSED** [review]
LGTM

**Review by rmartinc — APPROVED** [review]

**Review by ssilvert — DISMISSED** [review]

**Review by ssilvert — APPROVED** [review]
