### PR TITLE
always append the resource url

### LINKED ISSUE #38454: Keycloak account console is missing the Keycloak logo
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The account console doesn't show the Keycloak logo in the upper left corner

Image

### Version

nightly

### Regression

- [x] The issue is a regression

### Expected behavior

The logo should show

### Actual behavior

It doesn't show. 

### How to Reproduce?

Start up the nightly image, log in as admin, and change to the account console.

### Anything else?

This probably a blocker for 26.2

Image

### PR DESCRIPTION
**Pull request by edewit**
fixes: #38454
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Review by ssilvert — APPROVED** [review]

File: js/apps/account-ui/src/root/Header.tsx [hunk 1]
```diff
@@ -51,9 +51,7 @@ export const Header = () => {
       features={{ hasManageAccount: false }}
       brand={{
         href: indexHref,
-        src: brandImage.startsWith("/")
-          ? joinPath(environment.resourceUrl, brandImage)
-          : brandImage,
+        src: joinPath(environment.resourceUrl, brandImage),
```
Comment (jonkoops) [inline js/apps/account-ui/src/root/Header.tsx:54]: Would this not break if the image that is loaded is coming from another URL as configured in the theme? E.g. `http://some-other-domain/logo.png`
