### PR TITLE
Change email checkserveridentity prop as angus mail sets it to true by default

### LINKED ISSUE #22395: Email sending fails when SPI truststore is configured and hostnameVerification set to 'ANY'
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

With the current Keycloak version, any mail sending fails for us with the below error, indicating that hostname verification is indeed active, even if no verification is wanted:
```
"exception":{"refId":1,"exceptionType":"jakarta.mail.MessagingException",
    "message":"Could not convert socket to TLS","frames":
    [{"class":"org.eclipse.angus.mail.smtp.SMTPTransport","method":"startTLS","line":2188},
    {"class":"org.eclipse.angus.mail.smtp.SMTPTransport","method":"protocolConnect","line":765},
...
org.keycloak.services.resources.admin.RealmAdminResource: Failed to send email 
jakarta.mail.MessagingException: Could not convert socket to TLS;
nested exception is:
    java.io.IOException: Can't verify identity of server: our-mail-server.com
```

We have Keycloak set up with the following properties setup in keycloak.conf - especially, no hostname verification :)
```yaml
# Truststore
spi-truststore-file-enabled=true
spi-truststore-file-hostname-verification-policy=ANY
spi-truststore-file-password=very-secret
spi-truststore-file-file=/path/to/keycloak/truststore.jks
```

Emails are sent using StartTLS, the realm configuration is as follows:
```json
"smtpServer": {
    "starttls": "true",
    "port": "25",
    "auth": "",
    "host": "our-mail-server.com",
    "from": "we@domain.com",
    "fromDisplayName": "displayName",
    "ssl": ""
  },
```

Cause of this issue is a change in the underlying `angus-mail` implementation, which was updated in Keycloak 22 to Angus-Mail:2.0.1. 
In jakarta.mail:1.6.5 the default for `mail.smtp.ssl.checkserveridentity` is `false`: 
https://github.com/jakartaee/mail-api/blob/1.6.5/mail/src/main/java/com/sun/mail/util/SocketFetcher.java#L608C46-L608C46
...whereas in angus.mail:2.0.1 the default is `true`: 
https://github.com/eclipse-ee4j/angus-mail/blob/master/core/src/main/java/org/eclipse/angus/mail/util/SocketFetcher.java#L634

However, the `DefaultEmailSenderProvider` was not updated to reflect this change. It would need to set this property explicitly for the case of `ANY` hostname verification
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java#L195

For now, I have worked around the issue by providing my own `EmailSenderProvider` and setting this as the default.

### Version

22.0.1

### Expected behavior

Sending emails without hostname verification is possible. The default EmailSenderProvider instructs angus-mail to bypass the verification if so configured.

```java
private void setupTruststore(Properties props) {
        boolean checkServerIdentity = true;

        JSSETruststoreConfigurator configurator = new JSSETruststoreConfigurator(session);

        SSLSocketFactory factory = configurator.getSSLSocketFactory();
        if (factory != null) {
            props.put("mail.smtp.ssl.socketFactory", factory);
            if (configurator.getProvider().getPolicy() == HostnameVerificationPolicy.ANY) {
                props.setProperty("mail.smtp.ssl.trust", "*");
                props.setProperty("mail.smtp.ssl.checkserveridentity", "false"); // this is needed
                checkServerIdentity = false;
            }
        }

        if (checkServerIdentity) { 
            props.put("mail.smtp.ssl.checkserveridentity", "true"); // obsolete w/ angus-mail:2.0.1, but good to be explicit..?
        }
    }
```

### Actual behavior

Sending emails fails with the following error message:
```
"exception":{"refId":1,"exceptionType":"jakarta.mail.MessagingException",
    "message":"Could not convert socket to TLS","frames":
    [{"class":"org.eclipse.angus.mail.smtp.SMTPTransport","method":"startTLS","line":2188},
    {"class":"org.eclipse.angus.mail.smtp.SMTPTransport","method":"protocolConnect","line":765},
...
org.keycloak.services.resources.admin.RealmAdminResource: Failed to send email 
jakarta.mail.MessagingException: Could not convert socket to TLS;
nested exception is:
    java.io.IOException: Can't verify identity of server: our-mail-server.com
```

### How to Reproduce?

Set up keycloak with an SPI Truststore configured and try to send emails using StartTLS. Config example below:

Note.
I am unsure what needs to be configured to actually get an SSLFactory here...
```java
        JSSETruststoreConfigurator configurator = new JSSETruststoreConfigurator(session);

        SSLSocketFactory factory = configurator.getSSLSocketFactory();
```

keycloak.conf
```yaml
# Truststore
spi-truststore-file-enabled=true
spi-truststore-file-hostname-verification-policy=ANY
spi-truststore-file-password=very-secret
spi-truststore-file-file=/path/to/keycloak/truststore.jks
```

realm configuration:
```json
"smtpServer": {
    "starttls": "true",
    "port": "25",
    "auth": "",
    "host": "our-mail-server.com",
    "from": "we@domain.com",
    "fromDisplayName": "displayName",
    "ssl": ""
  },
```

### Anything else?

In jakarta.mail:1.6.5 the default for `mail.smtp.ssl.checkserveridentity` is `false`: 
https://github.com/jakartaee/mail-api/blob/1.6.5/mail/src/main/java/com/sun/mail/util/SocketFetcher.java#L608C46-L608C46
...whereas in angus.mail:2.0.1 the default is `true`: 
https://github.com/eclipse-ee4j/angus-mail/blob/master/core/src/main/java/org/eclipse/angus/mail/util/SocketFetcher.java#L634

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/22395

Just adding the `mail.smtp.ssl.checkserveridentity` to `false` if hostname validation is ANY. Now angus sets that property to true by default (secure by default). Test added to test hostname validation ANY and different name. The `FileTruststoreProvider` constructor was changed to public for testing it (let me know if you prefer a static method in the factory or something different).

### CODE REVIEW

File: services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java [hunk 1]
```diff
@@ -185,22 +185,16 @@ protected String retrieveEmailAddress(UserModel user) {
...
         if (factory != null) {
             props.put("mail.smtp.ssl.socketFactory", factory);
             if (configurator.getProvider().getPolicy() == HostnameVerificationPolicy.ANY) {
                 props.setProperty("mail.smtp.ssl.trust", "*");
-                checkServerIdentity = false;
+                props.put("mail.smtp.ssl.checkserveridentity", Boolean.FALSE.toString());
             }
         }
-
-        if (checkServerIdentity) {
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java:201]: Minor: I would maybe keep the `checkServerIdentity` variable and use here something like `props.put("mail.smtp.ssl.checkserveridentity", String.valueOf(checkServerIdentity);`.

Just in case that "default" changes again in the future, we would have it always overriden based on our settings. But that is minor nitpick and doesn't worth blocking this PR, so approving anyway.

**Review by mposolda — APPROVED** [review]

File: services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java (hunk 1 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java:201]: @mposolda I thought about it, always setting the variable with true or false, but then I decided that this is not probably going to change again. Setting this defaulted to true is the logical option based on secure by default current approach.

**Comment by tondrusk** [comment]
@mposolda, @rmartinc,

I just encountered an issue with these changes in Jenkins. The error says:

`
[ERROR] /C:/Users/hudson/J/workspace/universal-tes---ea900cfa/social_login/keycloak/testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java:[1091,47] FileTruststoreProvider(java.security.KeyStore,org.keycloak.truststore.HostnameVerificationPolicy,java.util.Map<javax.security.auth.x500.X500Principal,java.security.cert.X509Certificate>,java.util.Map<javax.security.auth.x500.X500Principal,java.security.cert.X509Certificate>) is not public in org.keycloak.truststore.FileTruststoreProvider; cannot be accessed from outside package
`

I assume that it is related to the `TestingResourceProviderFactory` class where you on this line

https://github.com/keycloak/keycloak/pull/23483/files#diff-e2647ff767bb935207dfe5a92aa8df1a5fbccb0ffa990fc20d46e79b67b091a2R1090

are getting the `truststoreProvider` from the factory, but the factory itself hast the `truststoreProvider` attribute set to `protected` as you can see here: https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProviderFactory.java#L38.

**Comment by rmartinc** [comment]
I think that line is complaining about the constructor not being public. But my change is also changing that constructor to public:

https://github.com/keycloak/keycloak/pull/23483/files#diff-d843d513411d7a015a18670ec6ecbe2a6efc72401895d7eb64c8d6ed5155cab6R37

Maybe you are testing something that is re-using the JAR with the previous constructor being private. Can you check this?

**Comment by tondrusk** [comment]
I did not re-run the keycloak-build-pipeline so this might be the case. I'll try again tomorrow and let you know.

**Comment by tondrusk** [comment]
@rmartinc, it looks like it was related to what you mentioned. Today it's working fine.
