### PR TITLE
Avoid MRJAR in keycloak-core

### LINKED ISSUE #34630: Avoid multi-release and java16 specific sources in the core module
### Description

There are some issues with the multi-release approach done in the `core` module where is the directory `java16` containing the java files applicable only to java16, which are supposed to override the default files for older java versions.

For example this works:

```
./mvnw -am -pl services install -Dtest=ServerJWKTest
```

but this does not work:
```
./mvnw -am -pl services test -Dtest=ServerJWKTest
```

Can we do something to avoid multi-release and have same sources and decide just in the runtime if EdDSA stuff is available or not?

### Solution ideas

Do we need to have this stuff working only for server or also for client?

If we need to support both on client and server (which I assume), we can possibly have some abstraction and use some reflection mechanism. Something along the lines of:
```
// Make sure that this stuff is executed just once during initialization and not during every invocation
try {
   Class.forName("java.security.spec.EdECPublicKeySpec");
   // EdDSA available. Use implementation, which is able to invoke EdEC operations. Will likely need to use reflection
  // as classes like java.security.spec.EdECPublicKeySpec cannot be directly referenced from sources in compile time
   edEcImpl = new EdEcAwareImpl();
} catch (ClassNotFoundException cnfe) {
   // EdDSA not available. Probably on some old java version. Use impl, which just calls UnsupportedOperationException etc 
   edEcImpl = new EdEcNotAvailableImpl();
}
```

If we need only for server, it is simpler as we can avoid reflection and use some other mechanim and implement some parts for example in `services` module. For example, we can use `ServiceLoader` to make sure that implementation is available in the `services` module, so that when things are executed as part of the server, the `services` module is available and hence the EdDSA stuff is available (server works in Jav17 or newer, so it is not an issue to always assume that `EdDSA` is available).

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #34630

Draft to remove the MR JAR in the keycloak-core. As we need to use release 8 in the library, it is impossible to avoid using a newer java specific sources for at least one class (the one with access to EdEC classes). What I tried in this PR is the following:

* There is a new `EdECUtils.java` class that is only used by the JWK builder and parser if the EdEC classes are detected in the JDK. This way in jdk 8 or 11 the not supported exception is thrown before loading the conflicting class. The util class is not public.
* There is a `EdECUtils.java` in the common source folder to make it compile with source/target/release set to 8. This file is indeed not used at all, just compilation purposes when release set to 8 (default).
* The real `EdEDUtils.java` is compiled later with release set to jdk 15. This way all the classes in the jar are jdk 8 except this one which is jdk 15. This class is not loaded if the EcED classes are not detected in the runtime as commented.
* JDK 15 used instead of 16 because using this method the versions should be aligned with the EdEC support in JDK. EcED support were added in [15](https://bugs.openjdk.org/browse/JDK-8190219).
* I have also changed `JWKBuilder` and `JWKParser` to not have any abstract impl.

I don't know. I still prefer the MR JAR as it's the normal way of doing these things in Java. The issue that test does not work in maven, although it's weird, it makes sense. For me this is a workaround and not very clean, but whatever you prefer. Note that having a class with version jdk 15 is absolutely necessary.

It was tested with this little [class](https://github.com/rmartinc/keycloak-core-tester/blob/main/src/main/java/org/keycloak/sample/Main.java): (using different jdk versions: 8, 11, 14, 15, 16, 17 and 21).

### CODE REVIEW

**Comment by rmartinc** [comment]
I have improved the solution a bit. Instead of a class in java 8 now there is an internal interface. Now the JDK 15+ class implements that interface. I think it's more understandable this way.

File: core/src/main/java/org/keycloak/jose/jwk/JWKBuilder.java [hunk 1]
```diff
@@ -17,14 +17,48 @@
...
+    protected static final EdECUtils EdEC_UTILS;
+
+    static {
+        EdECUtils tmp;
+        try {
+            // check if the impl class for EdEC can be loaded in the runtime
+            tmp = (EdECUtils) Class.forName("org.keycloak.jose.jwk.EdECUtilsImpl")
+                    .getDeclaredConstructor().newInstance();
+        } catch(Throwable e) {
+            tmp = null;
```
Comment (mposolda) [inline core/src/main/java/org/keycloak/jose/jwk/JWKBuilder.java:52]: My personal preference is possibly to use something like:
```
tmp = new EdECUtils() {
    
    @Override
    public JWK okp(Key key, KeyUse keyUse) {
        throw new UnsupportedOperationException("EdDSA algorithms not supported in this JDK version");
    }

   ...
}
```

instead of null checks. But that is maybe just me and it does not matter much IMO (especially since the field is protected anyway). So feel free to keep it as it is unless you strongly prefer to update or there are some more comments...

**Review by mposolda — DISMISSED** [review]
@rmartinc Nice, Thanks!

Tested this and it works fine. I've added one small comment inline, but does not really matter. I can merge once tests are OK and there are not more comments.

File: core/src/main/java/org/keycloak/jose/jwk/JWKBuilder.java (hunk 1 above)
Comment (rmartinc) [reply core/src/main/java/org/keycloak/jose/jwk/JWKBuilder.java:52]: Yep, we can do that. But then we need a `isSupported` method to follow the current behavior. Give me 5 min and I'll send a PR.

Comment (rmartinc) [reply core/src/main/java/org/keycloak/jose/jwk/JWKBuilder.java]: Done! (I have used a separated class file for the unsupported version.)

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks
