### PR TITLE
39546/remove kubernetes stack workarounds 26.2

### LINKED ISSUE #39546: Remove kubernetes stack workarounds after next ISPN 15.0.x release
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

The fix https://github.com/infinispan/infinispan/issues/14725 was added in #39454 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

There should be no workaround

### Actual behavior

There is a workaround

### How to Reproduce?

See #39454 - with the `per-destination` bundler there shouldn't be any errors logged.

### Anything else?

We would need to wait for a productized RHDG release to be able to backport it to 26.2.x

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #39546

### CODE REVIEW

**Comment by ahus1** [comment]
@pruivo - please review when you have the time. Thanks!

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/JGroupsConfigurator.java [hunk 1]
```diff
@@ -107,7 +90,6 @@ public static JGroupsConfigurator create(ConfigurationBuilderHolder holder) {
         var configurator = new ArrayList<JGroupsStackConfigurator>(3);
```
Comment (pruivo) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/JGroupsConfigurator.java]: This may be set back to 2 based on the diff from commit: 

https://github.com/keycloak/keycloak/commit/55998367d899b7eda9fb97752b241ed69240cdba#diff-b928b666e8e3c4cba204462c558ee57541362ac9b9fc5a08135ec33358a2cd6dR107

**Review by pruivo — CHANGES_REQUESTED** [review]
Optional suggestion. LGTM.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/JGroupsConfigurator.java (hunk 1 above)
Comment (ryanemerson) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/JGroupsConfigurator.java]: Good spot, updated.

**Review by pruivo — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving based on previous reviews
