### PR TITLE
Fix ConcurrentLoginTest.concurrentCodeReuseShouldFail on CockroachDB

### LINKED ISSUE #13210: JPA Map Storage with CRDB: ConcurrentLoginTest failures
### Describe the bug

**org.keycloak.testsuite.admin.concurrency.ConcurrentLoginTest**  presents failures/errors with `CockroachDB`:

```
[ERROR]   ConcurrentLoginTest.concurrentLoginSingleUserSingleClient:170->AbstractConcurrencyTest.run:63->AbstractConcurrencyTest.run:122 » Runtime There were failures in threads. Failures count: 2
```

- Required JPA stores to reproduce the failure: **authenticationSessions**

```
[ERROR]   ConcurrentLoginTest.concurrentCodeReuseShouldFail:249->AbstractConcurrencyTest.run:63->AbstractConcurrencyTest.run:122 » Runtime There were failures in threads. Failures count: 2
```

- Required JPA stores to reproduce the failure: **userSessions**

For both tests, logs show the following error:

```
Caused by: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_WRITE_TOO_OLD - WriteTooOld flag converted to WriteTooOldError): "sql txn" meta={id=7af23746 key=/Table/3142/1/"\x9cX4\x9e\xaf\x94F/\xac\xe41~H@\"\x10"/0 pri=0.05982192 epo=0 ts=1658239825.904432104,1 min=1658239825.904379733,0 seq=2} lock=true stat=PENDING rts=1658239825.904379733,0 wto=false gul=1658239826.404379733,0
  Hint: See: https://www.cockroachlabs.com/docs/v21.2/transaction-retry-error-reference.html#retry_write_too_old
```

### Version

main

### Expected behavior

Tests should run without failures or errors

### Actual behavior

_No response_

### How to Reproduce?

1- Setup CockroachDB according to the instructions in https://github.com/keycloak/keycloak/discussions/9596
2- Run the test with the correct parameters, enabling JPA storage for **authenticationSessions**/**userSessions** only:

```
cd testsuite/integration-arquillian

mvn clean install -Pmap-storage -Dpageload.timeout=90000 -Dkeycloak.authSession.map.storage.provider=jpa \
-Dkeycloak.userSession.map.storage.provider=jpa \
-Dkeycloak.map.storage.connectionsJpa.url=jdbc:postgresql://localhost:26257/keycloak \
-Dkeycloak.map.storage.connectionsJpa.user=keycloak -Dkeycloak.map.storage.connectionsJpa.password=pass \
-Dtest=ConcurrentLoginTest
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
- Code to token is executed in a separate retriable transaction.

Partially closes #13210

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java [hunk 1]
```diff
@@ -201,7 +203,22 @@ public Response processGrantRequest() {
 
         switch (action) {
             case AUTHORIZATION_CODE:
-                return codeToToken();
+                Object result = KeycloakModelUtils.runJobInRetriableTransaction(this.session.getKeycloakSessionFactory(), kcSession -> {
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java:206]: It would be nice to have a comment here explaining why this block gets a retry, while the other one doesn't, and why the `WebApplicationException` receives a special treatment (suspected reason: "because WebApplicationException captures final business states that won't change when being retried like an invalid code").

**Review by ahus1 — DISMISSED** [review]
Thanks for preparing this change that gets us one step closer to CockroachDB support! This change keeps the logic of retrying isolated to the TokenEndpoint, which is great.

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java (hunk 1 above)
Comment (sguilhen) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java:209]: Agree.. added some comments that explain what is being done and why.

**Review by ahus1 — DISMISSED** [review]
I've reviewed the changes and they look all good to me. Thanks for preparing this PR!

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java [hunk 2]
```diff
@@ -201,7 +203,28 @@ public Response processGrantRequest() {
...
+                        ClientModel clientModel = realmModel.getClientByClientId(client.getClientId());
+                        kcSession.getContext().setRealm(realmModel);
+                        kcSession.getContext().setClient(clientModel);
+                        return codeToToken(kcSession, realmModel, clientModel);
+                    } catch (WebApplicationException we) {
+                        // WebApplicationException needs to be returned and treated (rethrown) by the calling code because the new transaction
+                        // still needs to be committed when this exception is thrown. It captures final business states that won't change when
+                        // being retried, like an invalid code.
+                        return we;
+                    }
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java:221]: Given the separation proposed in this PR, could the whole code-to-token logic be moved to a private _static_ class within `TokenEndpoint`?

As of now, it is possible to accidentally use `TokenEndpoint.session` field in any method needed in that flow since `codeToToken` method is member method of this class. This is error-prone especially if there would be any change needed in the future. Should any method be shared across `codeToToken` and any other method in this class, it could be declared `static`.

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java [hunk 3]
```diff
@@ -172,14 +175,40 @@ public TokenEndpoint(TokenManager tokenManager, RealmModel realm, EventBuilder e
...
+        // exceptions on DBs with SERIALIZABLE isolation level.
+        Object result = KeycloakModelUtils.runJobInRetriableTransaction(this.session.getKeycloakSessionFactory(), kcSession -> {
+            try {
+                RealmModel realmModel = kcSession.realms().getRealm(realm.getId());
+                kcSession.getContext().setRealm(realmModel);
+                // create another instance of the endpoint that will be run within the new session.
+                Resteasy.pushContext(KeycloakSession.class, kcSession);
+                TokenEndpoint other = new TokenEndpoint(new TokenManager(), realmModel, new EventBuilder(realmModel, kcSession, clientConnection));
+                ResteasyProviderFactory.getInstance().injectProperties(other);
+                return other.processGrantRequestInternal();
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java:188]: I like the idea of creating a new instance. I wonder if the context should be restored afterwards? See below for a (untested) suggestion.

```suggestion
                KeycloakSession oldSession = Resteasy.getContextData(KeycloakSession.class);
                try {
                    Resteasy.pushContext(KeycloakSession.class, kcSession);
                    TokenEndpoint other = new TokenEndpoint(new TokenManager(), realmModel, new EventBuilder(realmModel, kcSession, clientConnection));
                    ResteasyProviderFactory.getInstance().injectProperties(other);
                    return other.processGrantRequestInternal();
                } finally {
                    Resteasy.pushContext(KeycloakSession.class, oldSession);
                }

```

**Review by ahus1 — COMMENTED** [review]
I like the idea. Please see my question below.

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java (hunk 2 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java]: This sounds very well indeed.

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java (hunk 3 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java:188]: Generally this is a good suggestion. Perhaps even better would be to introduce a `Resteasy.popContext` operation.

In this particular case, it is not needed though since the response is not a `Stream`, and the correct session is closed in the request filter. 

Therefore I'm approving this PR as is. Restoring the context can be done as follow-up.

**Review by hmlnarik — APPROVED** [review]
