### PR TITLE
Delete operation does not fire admin event v2

### LINKED ISSUE #46792: Delete operation does not fire admin event v2
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When deleting a client via the Admin API v2, the v2 event is not emitted. There's also no test for that. 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Event v2 is fired

### Actual behavior

No event v2 is fired

### How to Reproduce?

Call the delete op on the Admin API v2 with enabled Admin event v2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #46792

@edewit @vmuzikar Could you please check this straightforward PR? Thanks!

### CODE REVIEW

File: rest/admin-v2/api/src/main/java/org/keycloak/representations/admin/v2/BaseClientRepresentation.java [hunk 1]
```diff
@@ -129,4 +129,20 @@ public boolean equals(Object o) {
     public int hashCode() {
         return Objects.hash(clientId, displayName, description, enabled, appUrl, redirectUris, roles, additionalFields);
     }
+
+    /**
+     * Minimal client representation used for simple identification of client
+     * <p>
+     * Useful to provide as representation in certain Admin events
+     */
+    public static BaseClientRepresentation createMinimalRepresentation(String clientId, String protocol) {
```
Comment (vmuzikar) [inline rest/admin-v2/api/src/main/java/org/keycloak/representations/admin/v2/BaseClientRepresentation.java:138]: This is really not ideal but I assume it's only temporary until we have the new service layer.

**Review by vmuzikar — APPROVED** [review]

File: rest/admin-v2/api/src/main/java/org/keycloak/representations/admin/v2/BaseClientRepresentation.java (hunk 1 above)
Comment (mabartos) [reply rest/admin-v2/api/src/main/java/org/keycloak/representations/admin/v2/BaseClientRepresentation.java:138]: @vmuzikar Depends on what we want to include in the delete operation event. If we want to have there the full representation, or just some minimal that describes the client(as clientId and protocol) - the minimal is also used in the Admin v1 events (containing clientId, client UUID). 

We can improve it in follow-ups to unblock other stuff depending on this. 

Thanks!

Comment (mabartos) [reply rest/admin-v2/api/src/main/java/org/keycloak/representations/admin/v2/BaseClientRepresentation.java:138]: @vmuzikar Created spike:
- https://github.com/keycloak/keycloak/issues/46805
