### PR TITLE
Client cert lookup provider compliant to RFC 9440

### LINKED ISSUE #20761: Support Caddy as a Reverse Proxy Provider for Client Certificate Authentication
### Description

Caddy is a relatively new web server. To support Caddy as a reverse proxy provider for client certificate authentication, the Keycloak team will need to add support for Base64-encoded DER certificates. As of right now, Keycloak only supports PEM files.

### Discussion

_No response_

### Motivation

While Caddy is a new web server, it is not uncommon. Caddy has been used by Cloudflare in their implementation of their MITM protection service; separately, Let's Encrypt considers Caddy's "implementation of [ACME](https://en.wikipedia.org/wiki/Automatic_Certificate_Management_Environment) to be the gold standard of ACME clients," per [Wikipedia](https://en.wikipedia.org/wiki/Caddy_(web_server)). Supporting Caddy would be a great addition to Keycloak as more enterprises consider Caddy for their web server needs.

### Details

Per the [lead developer](https://github.com/caddyserver/caddy/issues/3767#issuecomment-1574294070), Caddy will not support passing PEM-formatted certificates in HTTP headers, and instead only supports B64-encoded DERs; therefore, the standard Apache, Nginx and HAProxy provider options do not work with Caddy. Caddy also does not automatically construct a certificate chain when passing a client certificate, similar to how Nginx currently works (Keycloak documentation mentions this [here](https://www.keycloak.org/server/reverseproxy) under "Configuring the NGINX provider").

My ask is to add Caddy as a reverse proxy provider. This would be nearly identical to the Nginx provider, except Keycloak must accept B64'ed DER certificates. As of right now, if a DER certificate is passed to Keycloak via Caddy, the following error occurs, as the format lacks the expected new line characters:

```
ERROR [org.keycloak.services] (executor-thread-50) org.keycloak.common.util.PemException: org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory$ExCertificateException: parsing issue: 
long form definite-length more than 31 bits: java.security.GeneralSecurityException: org.keycloak.common.util.PemException: org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory$ExCertificateException: parsing issue: long fo
rm definite-length more than 31 bits
```

### PR DESCRIPTION
**Pull request by seiferma**
Closes #20761

This pull request addresses the issue brought up in #20761. I decided to build a certificate lookup provider that is compliant to RFC 9440 instead of just building a caddy-compliant provider. This is the solution that has been suggested in the issue.

Design decisions /  implementation details:
- All configuration options are optional because the RFC already provides reasonable default values
- The length option for certificate chains defines the amount of certificates that are processed and exceeding the limit is treated as an error
- I created unit tests for the actual lookup but none for the factory because I could not find examples of tests for the other providers
- Test data is the data provided in RFC 9440

Checklist from the contribution guidelines:
- [ ] A discussion around the change (https://github.com/keycloak/keycloak/discussions/categories/ideas)
- [x] A GitHub Issue with a good description associated with the PR
- [x] One feature/change per PR
- [x] One commit per PR
- [x] PR rebased on main (git rebase, not git pull)
- [x] [Good descriptive commit message, with link to issue](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking)
- [x] No changes to code not directly related to your PR
- [x] Includes functional/integration test
- [x] Includes documentation

### CODE REVIEW

**Comment by erichayth** [comment]
Hoping this gets implemented soon. Cloudflare can forward a client certificate in DER format only which causes the request to fail on client certificate lookup.

File: services/src/main/java/org/keycloak/services/x509/Rfc9440ClientCertificateLookup.java [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+
+        this.sslCertChainHttpHeader = Optional.ofNullable(sslCertChainHttpHeader)
+                .filter(s -> !s.isBlank())
+                .orElseThrow(() ->  new IllegalArgumentException("sslCertChainHttpHeader"));
+
+        this.certificateChainLength = certificateChainLength;
+    }
+
+    @Override
+    public X509Certificate[] getCertificateChain(HttpRequest httpRequest) throws GeneralSecurityException {
```
Comment (shawkins) [inline services/src/main/java/org/keycloak/services/x509/Rfc9440ClientCertificateLookup.java:74]: This will need to check if the header is trusted - https://github.com/keycloak/keycloak/blob/a72d15b8572926bc460181f9338f7bf65f4ac04c/services/src/main/java/org/keycloak/services/x509/AbstractClientCertificateFromHttpHeadersLookup.java#L120

**Comment by fosple** [comment]
I'm currently deploying Keycloak to production and we use Caddy as a reverse proxy. I was surprised it's not supported yet. Would be awesome to merge this PR to support RFC 9440 and therefore Caddy @mposolda . Thanks a lot :)

**Comment by mposolda** [comment]
@shawkins @vmuzikar Removing myself as an assignee. Discussed with Stian earlier, that this PR is likely more in the area of cloud-native.

Just pointing, that if we add this, it maybe makes sense to wrap this behind feature flag? See `EnvironmentDependentProviderFactory` and it's usage in various providers.

File: services/src/main/java/org/keycloak/services/x509/Rfc9440ClientCertificateLookup.java (hunk 1 above)
Comment (seiferma) [reply services/src/main/java/org/keycloak/services/x509/Rfc9440ClientCertificateLookup.java:74]: I rebased my branch and integrated the check. Thanks for the hint!

File: services/src/main/java/org/keycloak/services/x509/Rfc9440ClientCertificateLookupFactory.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+    protected final static String HTTP_HEADER_CERT_CHAIN_LENGTH = "certificateChainLength";
+    protected final static int HTTP_HEADER_CERT_CHAIN_LENGTH_DEFAULT = 1;
+
+    protected String sslClientCertHttpHeader;
+    protected String sslChainHttpHeader;
+    protected int certificateChainLength;
+
+    @Override
+    public void init(Config.Scope config) {
+        if (config != null) {
```
Comment (shawkins) [inline services/src/main/java/org/keycloak/services/x509/Rfc9440ClientCertificateLookupFactory.java]: Just a nit, a check for a null config is not needed - that should not have been in AbstractClientCertificateFromHttpHeadersLookupFactory

**Comment by shawkins** [comment]
@seiferma sorry for the delay in having more consideration of this pr. My only real concern was addressed.

> which's main purpose is introducing feature flags for the lookup providers?

I don't think we need to have this behind a feature flag. Usage will already be opt-in.

In general there's also https://github.com/keycloak/keycloak/pull/33159 and https://github.com/keycloak/keycloak/issues/33818 - there should be more follow-up about making the x509cert-lookup SPI public cc @mposolda

File: services/src/main/java/org/keycloak/services/x509/Rfc9440ClientCertificateLookupFactory.java (hunk 2 above)
Comment (seiferma) [reply services/src/main/java/org/keycloak/services/x509/Rfc9440ClientCertificateLookupFactory.java]: I removed the null check.

**Comment by seiferma** [comment]
> @seiferma sorry for the delay in having more consideration of this pr. My only real concern was addressed.

No worries @shawkins . I rebased my branch and removed the null check that you mentioned. If there should be more changes, just let me know.

> In general there's also #33159 and #33818 - there should be more follow-up about making the x509cert-lookup SPI public cc @mposolda

That would be nice. My temporary solution was to build the provider separately and integrate it into my keycloak docker image. The warning about using a non-public API sounded pretty dramatic but if the API is fairly stable, it might be worth to remove that restriction.

**Review by vmuzikar — DISMISSED** [review]
@seiferma Thank you for the contribution! I just added some release notes, other than that LGTM. @shawkins Could you please re-review?

**Review by shawkins — DISMISSED** [review]
LGTM, thanks again @seiferma

**Comment by vmuzikar** [comment]
I took the liberty of fixing spotless and rebasing again to make the Operator tests pass.

**Comment by vmuzikar** [comment]
Failing external docs tests are unrelated.

**Review by vmuzikar — APPROVED** [review]
