### PR TITLE
KEYCLOAK-15985 Add Brute Force Detection Lockout Event

### LINKED ISSUE #8769: Add Brute Force Detection Lockout Event
### Description

Trigger an event when the brute force protection detects that the maximum allowed number of login failures is reached for a specific user.

### Discussion

_No response_

### Motivation

We would like to notify users (via e-mail) whenever their account gets locked up due to excessive failed logins.

Our favoured approach consists of implementing an SPI which listens to a USER_LOCKED event. The event is triggered when the brute force protection detects that the maximum allowed number of login failures is reached for a specific user.

### Details

Original Jira ticket [KEYCLOAK-15985](https://issues.redhat.com/browse/KEYCLOAK-15985)

### PR DESCRIPTION
**Pull request by paulbares**
This PR aims to introduce a new event when a user account gets permanently locked up. Test `BruteForceTest#testPermanentLockout` has been updated accordingly. 

Fixes #8769

### CODE REVIEW

**Comment by trixpan** [comment]
@abstractj this PR seem a fairly decent improvement around visibility of lockout events. Would any of the devs be able to review and merge?

**Comment by sgorbaty** [comment]
Bump!

**Comment by abstractj** [comment]
Thanks @trixpan, as soon as the @keycloak/core has some bandwidth to review, they will do.

File: services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java [hunk 1]
```diff
@@ -82,16 +85,58 @@ public ShutdownEvent() {
...
         protected final CountDownLatch latch = new CountDownLatch(1);
 
-        public SuccessfulLogin(String realmId, String userId, String ip) {
-            super(realmId, userId, ip);
+        public SuccessfulLogin(String realmId, String userId, ClientConnection clientConnection) {
+            super(realmId, userId, clientConnection);
+        }
+    }
+
+    protected static class AdaptedClientConnection implements ClientConnection {
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:101]: Could you please elaborate on why we need to copy values from client connection to instances of this class?

Is it related to using it from the background task and making sure the information is kept even though the request has ended?

Perhaps we could just have those fields in the `LoginEvent` itself rather than create a new class to just store them.

**Review by pedroigor — COMMENTED** [review]
@paulbares LGTM. Only a few comments.

File: server-spi-private/src/main/java/org/keycloak/events/EventType.java [hunk 2]
```diff
@@ -149,6 +149,8 @@ public enum EventType {
     DELETE_ACCOUNT(true),
     DELETE_ACCOUNT_ERROR(true),
 
+    USER_DISABLED_BY_PERMANENT_LOCKOUT(true),
```
Comment (pedroigor) [inline server-spi-private/src/main/java/org/keycloak/events/EventType.java:152]: When calling `EventBuilder.error`, you should get an error because the `_ERROR` version of this enum is not available.

I know it does not make much sense to throw an error in this case but I think it is better to add the error enum for the sake of consistency.

Wdyt?

File: services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java (hunk 1 above)
Comment (douglaspalmer) [reply services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:101]: I'm guessing they want the additional data for their SPI to email users. The rest of the PR seems to only read the remote address.

Comment (paulbares) [reply services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:101]: @pedroigor I am not remember exactly why I have done this (it was two years ago :sweat_smile:) but by reading the code, I think it was I need to use the `EventBuilder` to send the event and the only constructor available takes the `ClientConnection` as 3rd args. See usage in `DefaultBruteForceProtector#failure`

```java
...
// Send event
new EventBuilder(realm, session, event.clientConnection)
...
```

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:101]: I see that. But still, not sure if we need a type wrapping the current `ClientConnection` but just pass the instance over.

Even though they are created from the worker thread (as part of the request lifecycle) I don't think we are going to have issues if we use it in the brute force background task.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:101]: @paulbares By the way, I think your work is still valid and helps to improve auditing. Please, don't give up :)

Comment (paulbares) [reply services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:101]: If change 
```java 
        protected LoginEvent(String realmId, String userId, ClientConnection clientConnection) {
            this.realmId = realmId;
            this.userId = userId;
            this.clientConnection = new AdaptedClientConnection(clientConnection);
        }
```
to this (using the same object):
```java 
        protected LoginEvent(String realmId, String userId, ClientConnection clientConnection) {
            this.realmId = realmId;
            this.userId = userId;
            this.clientConnection = clientConnection;
        }
```
All those tests are failing:
image

The assertion errors are different each time.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java:101]: I see. So the fact it is being used in distinct threads is interfering. Please, ignore then.

**Comment by pedroigor** [comment]
@paulbares If you rebase your PR and look at the remaining comment from me, we can the move forward with it.

File: server-spi-private/src/main/java/org/keycloak/events/EventType.java (hunk 2 above)
Comment (paulbares) [reply server-spi-private/src/main/java/org/keycloak/events/EventType.java:152]: @pedroigor I did not get your point. Can you provide more details? Thank you

Comment (paulbares) [reply server-spi-private/src/main/java/org/keycloak/events/EventType.java]: @pedroigor should be ok now.

**Comment by paulbares** [comment]
@pedroigor I have made the changes and rebased my PR.

**Review by pedroigor — APPROVED** [review]
@paulbares Thanks for your time on it.

**Comment by paulbares** [comment]
Great to see it merged, thank you @pedroigor for the review.
