### PR TITLE
Remove duplicated set-cookie header from response when expiring cookies

### LINKED ISSUE #17192: Broken cookies in 20.0.2 (tested in latest realease too 20.0.3)
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

I'm using the keycloak-js (20.0.3)  plugin for javascript and when I upgrade the keycloak to version 20.0.2 or 20.0.3 fails with a 502 after session expired or deleted manually. 
In the brokens keycloak versions I need to every time clear the cookies in the edge browser. 
When I clear the cookies it works again.
The version 20.0.1 it works well when the session expired the cookies are removed automatically KEYCLOAK_SESSION, etc.

image

### Version

20.0.3

### Expected behavior

When the session is expired or deleted for a user in a realm, it shows the login page without error (for example in version 20.0.1)

### Actual behavior

When the session is expired or deleted for a user in a realm it shows a 503 error until manually clear the cookies KEYCLOAK_SESSION, etc.  the login page with an error 503  (for example in version 20.0.3)

### How to Reproduce?

Use de npm package keycloak-js (20.0.3)  in a web-app try to login in a keycloak-20.0.3 it will work well after the session is deleted or expired.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #17192

* Removes `CookieTransaction` in favor of supporting transaction events on the `HttpResponse`.
* Cookie state is shared during the `KeycloakSession` lifetime in order to allow checking for duplicates.
* Introduces a `HttpCookie` type and cookie-related methods to the `HttpResponse` to represent/manage cookies

### CODE REVIEW

**Comment by pedroigor** [comment]
@sguilhen @ahus1 Now we are making sure cookies are not duplicated, I'm wondering if we really need to write cookies only after completion or if we just want to always write cookies after transaction completion (makes more sense to me). I'm not 100% sure about the latter because I don't know if we need cookies sent even though the transaction does not complete successfully.

**Comment by stianst** [comment]
Before this change I see the following for each cookie (:

```
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/
```

That's basically 12 set-cookie headers per cookie.

After the change I see:

```
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/
```

There's still a few improvements that can be made here:

* Get rid of the `_LEGACY` cookies, but that's out of scope for this PR
* Get rid of the legacy path without the '/' at the end. Two ways we can do that, first is just to remove it, second is to only expire cookies that are actually set. I'd say we can just drop the legacy cookies by now?

I also noticed while looking at cookies that I'm getting JSESSIONID cookies. As we don't use HTTP sessions I wonder why this is?

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java [hunk 1]
```diff
@@ -44,6 +56,31 @@ public void setHeader(String name, String value) {
         delegate.getOutputHeaders().putSingle(name, value);
     }
 
+    @Override
+    public void addCookieIfAbsent(HttpCookie cookie) {
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/HttpResponseImpl.java:60]: `addCookieIfAbsent` is a bit confusing name, as I'd say that means add the cookie if not already set in previous requests. Would it be okay to just call it `setCookie`? Or, guess if we want something more explicit `setCookieIfNotSet` or something like that?

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java [hunk 2]
```diff
@@ -44,6 +56,31 @@ public void setHeader(String name, String value) {
...
+        if (cookie == null) {
+            throw new IllegalArgumentException("Cookie is null");
+        }
+
+        if (cookies == null) {
+            cookies = new HashSet<>();
+        }
+
+        if (cookies.add(cookie)) {
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/HttpResponseImpl.java:69]: This relies on hasCode in Cookie:

```
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.name != null ? this.name.hashCode() : 0);
        hash = 97 * hash + (this.value != null ? this.value.hashCode() : 0);
        hash = 97 * hash + this.version;
        hash = 97 * hash + (this.path != null ? this.path.hashCode() : 0);
        hash = 97 * hash + (this.domain != null ? this.domain.hashCode() : 0);
        return hash;
    }
```

So would be possible to have two set-cookie for the same cookie, but with different values. Would it be better to make cookies a list and search for existing cookies by name/path/domain instead?

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java [hunk 3]
```diff
@@ -44,6 +56,31 @@ public void setHeader(String name, String value) {
...
+            if (writeCookiesOnTransactionComplete) {
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/HttpResponseImpl.java:70]: There's a potential problem here if `writeCookiesOnTransactionComplete` is enabled after a cookie is set in the first place, which would result in the cookie being added one more time. Maybe just theoretical though.

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java [hunk 4]
```diff
@@ -44,6 +56,31 @@ public void setHeader(String name, String value) {
...
+                // cookies are written after transaction completes
+                return;
+            }
+
+            addHeader(HttpHeaders.SET_COOKIE, cookie.toHeaderValue());
+        }
+    }
+
+    @Override
+    public void setWriteCookiesOnTransactionComplete() {
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/HttpResponseImpl.java:80]: Looking at where this is used it looks very weird to me that we'd have oidc authentication endpoint basically wrapped in these retriable transactions, seems like a bit of a hack for some corner-cases, which then has implications on all requests resulting in spinning up new tx/objects/etc, when it's not needed 99.9999% of the time.

File: services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java [hunk 5]
```diff
@@ -909,7 +909,6 @@ public static AuthResult authenticateIdentityCookie(KeycloakSession session, Rea
         AuthResult authResult = verifyIdentityToken(session, realm, session.getContext().getUri(), session.getContext().getConnection(), checkActive, false, null, true, tokenString, session.getContext().getRequestHeaders(), VALIDATE_IDENTITY_COOKIE);
         if (authResult == null) {
             expireIdentityCookie(realm, session.getContext().getUri(), session);
-            expireOldIdentityCookie(realm, session.getContext().getUri(), session);
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:912]: I'm still seeing some set-cookie headers for the old paths without the '/' at the end.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:912]: The "old" cookie is set within the `expireIdentityCookie` method. I'm only removing this unnecessary call.

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java (hunk 4 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/HttpResponseImpl.java:80]: We can discuss this in more detail in a separate issue but as you pointed out there is an additional overhead to authorization and login action endpoints.

I can create a follow-up issue to discuss it in more detail with the store team.

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java (hunk 3 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/HttpResponseImpl.java:70]: I mean, this call should always happen at the very beginning of the request. That is why encapsulating this is important to make sure the situation you mentioned does not happen.

It does not make sense to enable this flag after cookies are already set.

**Comment by pedroigor** [comment]
@stianst I'm not seeing any JSESSIONID cookie. Could you share the request/response trace?

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java (hunk 4 above)
Comment (stianst) [reply services/src/main/java/org/keycloak/services/HttpResponseImpl.java:80]: +1 let's do a follow-up around this one

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java (hunk 3 above)
Comment (stianst) [reply services/src/main/java/org/keycloak/services/HttpResponseImpl.java:70]: It's probably fine as it is now, and we can discuss any follow-ups around it in combination with discussing the retry stuff in general.

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java (hunk 2 above)
Comment (stianst) [reply services/src/main/java/org/keycloak/services/HttpResponseImpl.java:69]: Maybe I'm overthinking things a bit, wdyt? just keep as is, or update to compare based on name/path/domain as I suggested?

File: services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java (hunk 5 above)
Comment (stianst) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:912]: I'd vote for removing everything around the old path in this PR, as I think that's perfectly safe since we haven't set a cookie with that old path for years.

**Comment by stianst** [comment]
> @stianst I'm not seeing any JSESSIONID cookie. Could you share the request/response trace?

I deleted that cookie and can't reproduce it, so don't know where it's coming from. Perhaps at some point I've ran something else on http://localhost:8080, which created this cookie. Dunno, but probably not an issue since it's not being created again after I deleted it.

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java (hunk 4 above)
Comment (sguilhen) [reply services/src/main/java/org/keycloak/services/HttpResponseImpl.java:80]: These retriable blocks were introduced to deal with CockroachDB's RETRY exceptions that cause a significant amount of requests to fail in concurrent scenarios. Retrying the transaction is their recommended approach in these cases.

Perhaps a better way to handle this would be to surround the original endpoint method in a try-catch block so we can check if the exception being thrown is a retriable exception and only then use the retry mechanism. That is, the original request is handled by the endpoint normally, and we trigger the retry mechanism only if a retriable exception is caught. This would prevent the creation of extra session/tx/objects, which would not be needed in the majority of scenarios.

We could also discuss if this behavior should be configurable at the realm level. Something like "Retry transactions where possible: yes/no", along with maximum number of retries or maximum time allowed for retrying.

File: services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java (hunk 5 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:912]: I would love to remove it, but we should do it carefully as we might also review any test around it. I'm more in favor of a follow-up, specifically to remove this behavior.

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java (hunk 2 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/HttpResponseImpl.java:69]: I would keep it as is for now and rely on JAX-RS API as much as possible.

File: services/src/main/java/org/keycloak/services/HttpResponseImpl.java (hunk 1 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/HttpResponseImpl.java]: Changed to `setCookieIfNotSet`.

File: server-spi/src/main/java/org/keycloak/http/HttpResponse.java [hunk 6]
```diff
@@ -45,4 +46,20 @@ public interface HttpResponse {
      * @param value the header value
      */
     void setHeader(String name, String value);
+
+    /**
+     * Sets a new cookie only if not yet set.
+     *
+     * @param cookie the cookie
+     */
+    void setCookieIfAbsent(HttpCookie cookie);
```
Comment (mabartos) [inline server-spi/src/main/java/org/keycloak/http/HttpResponse.java:55]: @pedroigor Do we really need to "pollute" the `HttpResponse` interface with the custom class `HttpCookie` only due to the presence of the method converting the cookie props to the Set-Cookie form attribute? We could do it additionally in our implementation of the interface, right? 

Moreover, I'd rather see in this interface some standard structure such as `NewCookie` which should handle the whole process with Set-Cookie stuff.

For inspiration: https://github.com/mabartos/keycloak/commit/89627088421c6c0d2fd60a6a0cade64f8e159a77

Comment (mabartos) [reply server-spi/src/main/java/org/keycloak/http/HttpResponse.java:55]: "`NewCookie`, when sent in the Response, will set a Set-Cookie response header with the cookie information, and `Cookie` will set the Cookie request header with the cookie information. This is per the HTTP spec." [1]

[1] https://stackoverflow.com/a/34055702

Comment (pedroigor) [reply server-spi/src/main/java/org/keycloak/http/HttpResponse.java:55]: How are you handling SameSite cookies in that branch?

Regarding the changes to `HttpResponse` and `HttpCookie`, I'm trying to be a bit conservative here and keep the same behavior when setting cookies. Removing/deprecating code or calls from/to `ServerCookie` should be done carefully as JAX-RS does not provide support for samesite cookies.

Or does it?

File: services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java (hunk 5 above)
Comment (stianst) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:912]: Ok, works for me

**Review by stianst — APPROVED** [review]

File: server-spi/src/main/java/org/keycloak/http/HttpResponse.java (hunk 6 above)
Comment (pedroigor) [reply server-spi/src/main/java/org/keycloak/http/HttpResponse.java:55]: TBH, I prefer having the same representation/type for both request and response cookies.

Comment (mabartos) [reply server-spi/src/main/java/org/keycloak/http/HttpResponse.java:55]: >How are you handling SameSite cookies in that branch?

It's not a complete solution for that yet. I just wanted to mention a particular approach exists. 

>TBH, I prefer having the same representation/type for both request and response cookies.

Not sure if it has some benefits. As the standard way of using cookies is to use `NewCookie` (extension of Cookie) for response and `Cookie` for request; we can easily obtain `Cookie` from `NewCookie`.

However, we can discuss it in different channels and it can be done in some follow-up tasks as this may be slightly out of the scope of this PR and requires some investigation around it. As the next major version of Keycloak is far away, we have some time for that. WDYT?

Comment (pedroigor) [reply server-spi/src/main/java/org/keycloak/http/HttpResponse.java:55]: Works for me, it is an implementation detail we can sort out later. We just need to make sure we can still extend JAX-RS API to add any missing behavior we need (e.g.: same site).

Comment (mabartos) [reply server-spi/src/main/java/org/keycloak/http/HttpResponse.java:55]: @pedroigor +1

**Review by mabartos — APPROVED** [review]
