### PR TITLE
fix: makes the configsources consistent wrt hidden properties

### LINKED ISSUE #37817: internal options are settable in non-cli config sources
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Internal options, such as proxy-forwarded-host, cannot be set via the cli (--proxy-forwarded-host=true). However they are still settable via the other config sources such as using proxy-forwarded-host=true in the keycloak.conf.

### Version

26

### Regression

- [ ] The issue is a regression

### Expected behavior

Only non-internal keycloak options should be directly settable - we expect internal options to be derived.

### Actual behavior

Internal options are settable.

### How to Reproduce?

Use proxy-forwarded-host=true in the keycloak.conf without setting the proxy-headers

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
To make things consistent with hidden / internal properties, they can now be used by the cli as well. I think the rationale for being able to override an undocumented property rests with an existing unit test that allows for override db-dialect, which can't otherwise be set by a quarkus property because the map from will be dominant.

It should have been addressed with property naming refactor, but this also removes handling related to the - separator. We do not want to check for all . forms of kc properties.

closes: #37817

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 1]
```diff
@@ -778,19 +777,20 @@ private static void addMappedOptionsToArgGroups(CommandLine commandLine, Map<Opt
                     name = decorateDuplicitOptionName(name);
                 }
 
-                String description = mapper.getDescription();
-
-                if (description == null || cSpec.optionsMap().containsKey(name) || name.endsWith(OPTION_PART_SEPARATOR) || alreadyPresentArgs.contains(name)) {
+                if (cSpec.optionsMap().containsKey(name) || alreadyPresentArgs.contains(name)) {
                     //when key is already added or has no description, don't add.
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:781]:
```suggestion
                    //when key is already added, don't add.
```

nitpick: might be updated if you potentially make some changes.

**Review by mabartos — COMMENTED** [review]
@shawkins Thanks for this change. LGTM

Could you please add some simple test case? Thanks!

**Comment by shawkins** [comment]
> Could you please add some simple test case? Thanks!

Moved the existing test case from ConfigurationTest to PicocliTest. It would previously have always passed in ConfigurationTest because that was testing below picocli.

**Review by mabartos — APPROVED** [review]
@shawkins I don't see any issues to override them via CLI if users want to. 

But I'd like to hear @vmuzikar's opinion.

**Comment by vmuzikar** [comment]
I plan to review today, or first thing tomorrow.

**Review by vmuzikar — APPROVED** [review]
Changes look good, thanks for the PR. As a follow-up, we might consider logging some warning if the user explicitly uses a hidden option.
