### PR TITLE
23404 improve client role listing

### LINKED ISSUE #23404: Cannot assign client roles to a user when a realm contains more than ~4000 clients
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

One of our realms contains 8754 clients.

On this realm, we are unable to assign a client role to a user.

### Version

22.0.1

### Expected behavior

We should be able to assign client roles to a user even when the database contains many clients.

### Actual behavior

In order to assign a client role to a user, we have to list them. On a realm with many clients, the client selection screen freezes and never loads:

image

The hanging http request is `GET https://keycloak.acme.com/auth/admin/realms/general/ui-ext/available-roles/users/363b9993-ee55-4aff-a415-439ea28396f6?first=0&max=101&search=`

After 5.3 minutes, the http request fails with an internal 500 error and the UI displays an error:

image

Multiple jstack snapshots always show the same stack:
```java
"executor-thread-109" - Thread t@19291
   java.lang.Thread.State: RUNNABLE
        at org.hibernate.persister.entity.AbstractEntityPersister.getPropertyValue(AbstractEntityPersister.java:4227)
        at org.hibernate.persister.entity.EntityPersister.getValue(EntityPersister.java:920)
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:184)
        at org.hibernate.event.internal.AbstractSaveEventListener.cascadeAfterSave(AbstractSaveEventListener.java:490)
        at org.hibernate.event.internal.DefaultPersistEventListener.justCascade(DefaultPersistEventListener.java:161)
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsPersistent(DefaultPersistEventListener.java:154)
        at org.hibernate.event.internal.DefaultPersistEventListener.persist(DefaultPersistEventListener.java:90)
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:77)
        at org.hibernate.internal.SessionImpl$$Lambda$1923/0x00007f687ce38230.applyEventToListener(Unknown Source)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
        at org.hibernate.internal.SessionImpl.persistOnFlush(SessionImpl.java:819)
        at org.hibernate.engine.spi.CascadingActions$8.cascade(CascadingActions.java:333)
        at org.hibernate.engine.spi.CascadingActions$8.cascade(CascadingActions.java:323)
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:513)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:434)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:220)
        at org.hibernate.engine.internal.Cascade.cascadeComponent(Cascade.java:405)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:241)
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:153)
        at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:155)
        at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:145)
        at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:79)
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:48)
        at org.hibernate.internal.SessionImpl$$Lambda$1831/0x00007f687cdb9600.accept(Unknown Source)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1375)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.scroll(JdbcSelectExecutorStandardImpl.java:115)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$1(ConcreteSqmSelectQueryPlan.java:136)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan$$Lambda$1816/0x00007f687cdae3d8.interpret(Unknown Source)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:303)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performScroll(ConcreteSqmSelectQueryPlan.java:252)
        at org.hibernate.query.sqm.internal.QuerySqmImpl.doScroll(QuerySqmImpl.java:629)
        at org.hibernate.query.spi.AbstractSelectionQuery.scroll(AbstractSelectionQuery.java:445)
        at org.hibernate.query.spi.AbstractSelectionQuery.stream(AbstractSelectionQuery.java:457)
        at org.hibernate.query.Query.getResultStream(Query.java:168)
        at org.keycloak.models.jpa.JpaRealmProvider.getClientScopes(JpaRealmProvider.java:986)
        at org.keycloak.storage.ClientStorageManager.getClientScopes(ClientStorageManager.java:212)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientScopes(RealmCacheSession.java:1358)
        at org.keycloak.models.jpa.ClientAdapter.getClientScopes(ClientAdapter.java:366)
        at org.keycloak.models.cache.infinispan.entities.CachedClient.<init>(CachedClient.java:112)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.cacheClient(RealmCacheSession.java:1152)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientById(RealmCacheSession.java:1114)
        at org.keycloak.models.delegate.ClientModelLazyDelegate$WithId.lambda$new$0(ClientModelLazyDelegate.java:53)
        at org.keycloak.models.delegate.ClientModelLazyDelegate$WithId$$Lambda$2700/0x00007f687d16fdd8.get(Unknown Source)
        at org.keycloak.models.delegate.ClientModelLazyDelegate.getDelegate(ClientModelLazyDelegate.java:83)
        at org.keycloak.models.delegate.ClientModelLazyDelegate.getRolesStream(ClientModelLazyDelegate.java:579)
        at org.keycloak.admin.ui.rest.RoleMappingResource$$Lambda$3072/0x00007f687d272b70.apply(Unknown Source)
        at java.base@17.0.8/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base@17.0.8/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@17.0.8/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
        at java.base@17.0.8/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.8/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@17.0.8/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.keycloak.utils.ClosingStream.collect(ClosingStream.java:182)
        at org.keycloak.admin.ui.rest.RoleMappingResource.mapping(RoleMappingResource.java:36)
        at org.keycloak.admin.ui.rest.AvailableRoleMappingResource.listCompositeUserRoleMappings(AvailableRoleMappingResource.java:158)
        at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
        at org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$2361/0x00007f687cfbdcb8.get(Unknown Source)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        - locked <75c69112> (a org.jboss.resteasy.core.interception.jaxrs.PostMatchContainerRequestContext)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
        at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$2359/0x00007f687cfbbf88.run(Unknown Source)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
        at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$2360/0x00007f687cfbc898.get(Unknown Source)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        - locked <3d016fe> (a org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter$$Lambda$2355/0x00007f687cfb1b20.run(Unknown Source)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Follow https://github.com/Cosium/keycloak-issue-21010 , then try to assign a client role to a user.

### Anything else?

This is the same kind of issue as https://github.com/keycloak/keycloak/issues/21010

### PR DESCRIPTION
**Pull request by sschu**
Fixes #23404 

First draft.

### CODE REVIEW

**Comment by sschu** [comment]
First iteration on improving the situation here. I would rather use an iterative approach here rather than having a big bang rewrite also changing the admin API. The PR also tries to improve listing effective roles for a user as this also times out with many clients and it is essentially the same code. In the first iteration:

1. I improved the `RoleMapper.convertToModel()` method to  be O(1) instead of O(#clients) as it essentially made all listing operations O(#clients^2).
2. I improved the listing the effective role mapping to not be O(#clients) but O(#role-mappings).
3. I refactored the code to make it more readable and explicit, also because code sharing between available and effective role mappings won't be possible in the future (the former definitely has to go to the database). But this can be debated.

What is missing is an actual improvement to listing the available role mappings, this is as bad as before. This definitely has to look for roles that can be assigned so it has to somehow iterate over all roles. To make this efficient, this (and pagination) has to happen on the database level. This would be my next step. Other open questions:

1. The fact that only client roles are listed is due to the fact that the same for realm roles is taken from the admin api. For effective role mappings, this could easily include realm roles as well meaning the UI would only have to make one call (currently assigned realm roles are filtered out). This would also be possible for available roles.
2. `listCompositeRealmRoleMappings` doesn't do what it says it just lists subroles of the default role instead of the role provided as parameter. I don't know if this is intended but it looks super odd to me.
3. In the first iteration, I would probably leave everything in `admin-ui-ext`with the option of using it to improve the admin API later.

**Comment by sschu** [comment]
With fine-grained permissions, the most efficient way would be to:
1. collect all roles the user can manage via fine-grained permissions directly
2. collect all roles the user can manage indirectly via fine-grained permissions on a client
3. subtract all roles has directly assigned
Ideally, this would all happen in the database so the database can directly do the pagination. Due to the nature of the user filtering by policies, I fear this won't be possible. So I would probably go for a similar approach to how fine-grained permissions are used when searching for users: add a method `getRolesWithMapPermissions()` to `RolePermissions.java` and use its output as input for a DB query with pagination.

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java [hunk 1]
```diff
@@ -21,23 +22,18 @@ public RoleMappingResource(RealmModel realm, AdminPermissionEvaluator auth) {
...
+        visited.addAll(roles.collect(Collectors.toList()));
+        return Stream.concat(roles, roles.flatMap(r -> addSubRoles(r.getCompositesStream().filter(s -> !visited.contains(s)), visited)));
     }
 
-    protected final List<ClientRole> mapping(Predicate<RoleModel> predicate, long first, long max, final String search) {
-        return mapping(predicate).filter(clientRole -> clientRole.getClient().contains(search) || clientRole.getRole().contains(search))
-                .skip(first).limit(max).collect(Collectors.toList());
+    static Stream<GroupModel> addParents(GroupModel group) {
+        //no cycle check here, I hope that's fine
+        if (group.getParent() == null) return Stream.of(group);
```
Comment (thomasdarimont) [inline rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java:35]:
```suggestion
        if (group.getParent() == null) {
            return Stream.of(group);
        }
```

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/RoleMapper.java [hunk 2]
```diff
@@ -2,14 +2,14 @@
...
 
 public class RoleMapper {
-
-    public static ClientRole convertToModel(RoleModel roleModel, Stream<ClientModel> clients) {
+    public static ClientRole convertToModel(RoleModel roleModel, RealmModel realm) {
         ClientRole clientRole = new ClientRole(roleModel.getId(), roleModel.getName(), roleModel.getDescription());
-        ClientModel clientModel = clients.filter(c -> roleModel.getContainerId().equals(c.getId())).findFirst()
-                .orElseThrow(() -> new IllegalArgumentException("Could not find referenced client"));
+        ClientModel clientModel = realm.getClientById(roleModel.getContainerId());
+        if (clientModel==null) throw new IllegalArgumentException("Could not find referenced client");
```
Comment (thomasdarimont) [inline rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/RoleMapper.java:12]:
```suggestion
        if (clientModel==null) {
            throw new IllegalArgumentException("Could not find referenced client");
        }
```

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java [hunk 3]
```diff
@@ -3,6 +3,8 @@
 import java.util.List;
 import java.util.Objects;
 import java.util.function.Predicate;
+import java.util.stream.Collectors;
+
```
Comment (thomasdarimont) [inline rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java:7]:
```suggestion
```

**Review by thomasdarimont — CHANGES_REQUESTED** [review]
Looks good to me, just a few minor remarks.

**Review by vramik — COMMENTED** [review]
Thank you @sschu for this PR! It looks good to me, just few minor comments.

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/RoleMapper.java [hunk 4]
```diff
@@ -2,14 +2,14 @@
...
 import java.util.stream.Stream;
 import org.keycloak.models.ClientModel;
+import org.keycloak.models.RealmModel;
 import org.keycloak.models.RoleModel;
 
 public class RoleMapper {
-
-    public static ClientRole convertToModel(RoleModel roleModel, Stream<ClientModel> clients) {
+    public static ClientRole convertToModel(RoleModel roleModel, RealmModel realm) {
         ClientRole clientRole = new ClientRole(roleModel.getId(), roleModel.getName(), roleModel.getDescription());
```
[the remark this answers is not in the document]
Comment (sschu) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/RoleMapper.java:10]: Thanks, will fix this.

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java
[the remark this answers is not in the document]
Comment (sschu) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java:1]: I see the reason is that these variables are `private final` and overshadowed in the subclasses. Is there any specific reason for that? Otherwise I would just make them protected in the base class so they can be used in the subclasses.

**Comment by sschu** [comment]
Thanks for the feedback @vramik !
I am currently wondering if `getRolesStream` is actually the best name for the newly introduced method. In other places, methods taking a search string parameter are typically called `searchXyz`. It might even make sense to move the methods to the `RoleLookupProvider` interface (or even introduce a `RoleQueryProvider`? If I look at how it's done for Users, "lookup" typically seems to refer to methods for retrieving individual elements based on various parameters, not for searching for a set of elements).
Also, I am thinking of switching to the Criteria API to not bloat the `RoleEntity.java` with named functions and have some reuse. The search semantics is also not complete as searching for client roles should also include the client IDs, not just the role names.

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java [hunk 5]
```diff
@@ -170,7 +192,11 @@ public final List<ClientRole> listCompositeUsersRoleMappings(@PathParam("id") St
     public final List<ClientRole> listCompositeRealmRoleMappings() {
         auth.roles().requireList(realm);
         final RoleModel defaultRole = this.realm.getDefaultRole();
-        return mapping(o -> o.hasRole(defaultRole)).collect(Collectors.toList());
+        //this definitely does not return what the descriptions says
```
Comment (sschu) [inline rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java:195]: @vramik What do you think about this endpoint here? It definitely does not do what the description says (also before my change).

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java
[the remark this answers is not in the document]
Comment (vramik) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java:1]: yes, that's the second option. Both options works for me, I leave it up to to decide what you prefer.

**Comment by vramik** [comment]
Thank you @sschu!

> I am currently wondering if `getRolesStream` is actually the best name for the newly introduced method. In other places, methods taking a search string parameter are typically called `searchXyz`. It might even make sense to move the methods to the `RoleLookupProvider` interface (or even introduce a `RoleQueryProvider`? If I look at how it's done for Users, "lookup" typically seems to refer to methods for retrieving individual elements based on various parameters, not for searching for a set of elements). 

Good point, I think it makes sense to rename the method to `searchXzy` and move it to `RoleLookupProvider`. I wouldn't create new interface `RoleQueryProvider` for this.

> Also, I am thinking of switching to the Criteria API to not bloat the `RoleEntity.java` with named functions and have some reuse. 

Currently the jpa storage layer is not consistent in using queries. Whether it's named queries, criteria API or even native queries at some places. If you find it convenient, e.g. to have some reuse there, then go for it. I wouldn't mind the current approach with named queries as well.

> The search semantics is also not complete as searching for client roles should also include the client IDs, not just the role names. 

Would be the searching by client IDs required by / useful for by admin UI? Or do you mention it in sake of completeness?

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java (hunk 5 above)
Comment (vramik) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java:195]: I agree the description looks a bit suspicious. Thanks for spotting this. I was trying to find out whether the description or the implementation is off, but I wasn't able to locate correct place from where the endpoint is called from UI.

@edewit could you please comment this one?

**Comment by sschu** [comment]
It's just the existing behaviour to search in client id and role name when searching for client roles, see https://github.com/keycloak/keycloak/blob/6736f319524ad268bd265cace7a27d67466453bb/rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java#L35.

**Comment by sschu** [comment]
I updated the implementation so listing effective role mappings sorts correctly and available role mappings are listed using the new function from the `RoleLookupProvider` for the case that fine-grained permissions are disabled.  Next step is to implement listing available role mappings with fine-grained permissions enabled.
Some open questions for me:
- I added the new search method as a default method so alternative `RoleLookupProviders` still compile. However, they will encounter a runtime exception if they don't implement the method so this might not be ideal.
- Searching for available client roles in the `RoleLookupProvider` searches for matches and role name and client name because that's what the current API is doing to list available client roles. However, it is not consistent with what the other search functions are doing, they search in role name and role description.
- Listing effective role mappings doesn't offer pagination (it was like that before) but the admin console actually sends a request with pagination, at least when listing roles for a user.
- Listing effective role mappings could probably be more efficient by going to the DB directly similar to available role mappings. But it might not be that important considering that the amount of assigned roles should not be that big.

WDYT? @vramik  @danielFesenmeyer  @thomasdarimont

**Comment by sschu** [comment]
I finished the implementation to also work with fine-grained permissions. There are still some open issues but I would rather handle them in a separate issue:

1. The existing endpoints to show role mappings don't sort. When listing user role assignments hiding inherited roles, realm roles come first and then client roles, both are not sorted. When listing user roles including inherited roles, client roles come first and are sorted, then realm roles follow and are not sorted.
2. The existing endpoints to show role mappings don't respect fine-grained permissions. Hiding inherited roles shows all directly assigned roles (also without map-role permissions), showing inherited roles only shows client roles with map-role permission but still shows all realm roles.
3. The code around fine-grained permissions could really use a refactoring, there is a lot of code duplication in there.

All of this already exists in main and is not introduced by the changes here. The question is also, which behaviour is intended i.e. needing map-role permission to see a role as available definitely makes sense but I am not sure it should also be necessary to see a role that is assigned.

@vramik Can you please have a look?

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java [hunk 6]
```diff
@@ -176,8 +212,35 @@ public final List<ClientRole> listCompositeUserRoleMappings(@PathParam("id") Str
...
+    private Set<String> getRoleIdsWithPermissions(String roleResourceScope, String clientResourceScope) {
+        Set<String> roleIds = this.auth.roles().getRolesWithPermission(roleResourceScope);
+        Set<String> clientIds = this.auth.clients().getClientsWithPermission(clientResourceScope);
+        //TODO: this might be pretty inefficient, directly joining client IDs with role IDs in one query would be better
+        clientIds.stream().flatMap(cid -> realm.getClientById(cid).getRolesStream()).forEach(role -> roleIds.add(role.getId()));
+        return roleIds;
+    }
+
+    private List<ClientRole> searchForClientRolesByIds(RealmModel realm, Stream<String> includedIDs, String search, long first, long max) {
+        //TODO: not really sure about that casting of longs to ints here but I did not want to change the API sinature
```
Comment (ahus1) [inline rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java:236]: Feel free to change  `listAvailableRoleMappings()` to have Integers to be consistent with `UserResource` (see below) to avoid the casting. This would resolve this and the following TODO.

```
 @QueryParam("first") Integer firstResult, @QueryParam("max") Integer maxResults,
```

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java [hunk 7]
```diff
@@ -176,8 +212,35 @@ public final List<ClientRole> listCompositeUserRoleMappings(@PathParam("id") Str
...
+            Set<String> roleIds = getRoleIdsWithPermissions(MAP_ROLE_COMPOSITE_SCOPE, MAP_ROLES_COMPOSITE_SCOPE);
+            roleIds.remove(id);
+            return searchForClientRolesByIds(realm, roleIds.stream(), search, first, max);
+        }
+    }
+
+    private Set<String> getRoleIdsWithPermissions(String roleResourceScope, String clientResourceScope) {
+        Set<String> roleIds = this.auth.roles().getRolesWithPermission(roleResourceScope);
+        Set<String> clientIds = this.auth.clients().getClientsWithPermission(clientResourceScope);
+        //TODO: this might be pretty inefficient, directly joining client IDs with role IDs in one query would be better
```
Comment (ahus1) [inline rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java:230]: Please describe if you think this something you want to implement as part of this PR, or if it is good enough / as good as before, and you want handle this in a future issue/PR. 

Either way, there shouldn't be a TODO in the code for this. 

If you choose to have another issue for that, you can even reference the issue here to point to a discussion there.

**Review by ahus1 — COMMENTED** [review]
@sschu - thank you for this PR. I commented on some TODOs, I hope this helps until @vramik has a final look at the PR early next week if time permits.

In general I agree to keep PRs as small as possible, and move work to future PRs if the PR as is is an improvement.

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java (hunk 5 above)
Comment (edewit) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java:181]: Sorry, for missing this ping. Yes it is used in the UI

Comment (sschu) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java:181]: @edewit But what is it used for? The descriptions says, it returns all client subroles for a realm role with a given id, the implementation actually returns all client subroles of the default realm role and the given id is not used at all.

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java (hunk 7 above)
Comment (sschu) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java]: Thanks. I'll keep it as it is for now. The current code also populates the caches which has is upsides. I would revisit this should it turn out to be an issue in practice.

**Comment by sschu** [comment]
Thanks for the comments @ahus1 ! Waiting for @vramik (no pressure) ;)

**Review by edewit — DISMISSED** [review]

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java (hunk 5 above)
Comment (edewit) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java:181]: Right the unused ID is because that way we can make the UI always send one also when no ID is needed it's just to make this a more general implementation.

**Review by vramik — CHANGES_REQUESTED** [review]
Thank you @sschu! The PR looks great. I've several comments.

> * I added the new search method as a default method so alternative `RoleLookupProviders` still compile. However, they will encounter a runtime exception if they don't implement the method so this might not be ideal.

I agree this is not ideal and I believe we could leave it without default implementation. @ahus1 wdyt? If it turns out we have to have a default implementation, I'd advise to return either `null` or `Stream.empty()`, but from my POV the best would be to not have default implementation there.

> * Searching for available client roles in the `RoleLookupProvider` searches for matches in role name and client name because that's what the current API is doing to list available client roles. However, it is not consistent with what the other search functions are doing, they search in role name and role description.

True, @edewit is this desired behavior from UI point of view?

> * Listing effective role mappings doesn't offer pagination (it was like that before) but the admin console actually sends a request with pagination, at least when listing roles for a user.

Interesting, could you please link here a place in code from where the admin console sends the request? I'd say this is something we should look at, probably within follow up issue, could you please create one?

> * Listing effective role mappings could probably be more efficient by going to the DB directly similar to available role mappings. But it might not be that important considering that the amount of assigned roles should not be that big.

I agree, if you'd consider to make this more efficient, please do it within follow-up issue and PR.

> * The way this is currently going I see a lot of code duplication searching for realm/client/all roles. I am wondering if it would be better to just have an RoleQueryType enum with values CLIENT_ROLES,REALM_ROLES,ALL since inside the code differences are minimal.

You're right, we may want to refactor / improve the code in future, would you like to create `enhancement` issue for it?

**Comment by ahus1** [comment]
> from my POV the best would be to not have default implementation there.

I agree that a default implementation only makes sense if it returns a meaningful default, and returning an exception is no meaningful default IMHO. If there is no meaningful default implementation, don't provide one as @vramik suggested.

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java [hunk 8]
```diff
@@ -2,42 +2,26 @@
 
 import static org.keycloak.admin.ui.rest.model.RoleMapper.convertToModel;
 
+import java.util.HashSet;
```
[the remark this answers is not in the document]
Comment (sschu) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java]: I deleted them.

**Comment by sschu** [comment]
@vramik @ahus1 Thanks for the feedback! I included all remarks so from my perspective the PR is good to go if CI is green.

**Comment by sschu** [comment]
@vramik With regards to the admin UI using pagination of listing effective role assignments: I assume this is the code but not sure, frontend isn´t my area:
https://github.com/keycloak/keycloak/blob/153d1a98418c4f9c6dce006cdf99f14fd6f48254/js/apps/admin-ui/src/components/role-mapping/resource.ts#L30-L42

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java (hunk 5 above)
Comment (sschu) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java:181]: Alright, thanks!

**Comment by edewit** [comment]
@sschu yep that is correct

**Comment by sschu** [comment]
@vramik I don't think the test failure is created. I also created the follow-up issues you asked for.

**Review by vramik — APPROVED** [review]
Thank you @sschu!

**Review by ahus1 — APPROVED** [review]
Approving as of @vramik's review. Thank you to everyone involved in this PR to make this performance improvement happen!

**Comment by ahus1** [comment]
@edewit - could you please re-approve this PR for the UI team, as your last review is now stale after the lasted rework from the author. For the one GHA that failed due to flakiness I triggered a rerun.

Thanks!

**Review by edewit — APPROVED** [review]

**Comment by sschu** [comment]
Cool, thanks a lot everybody!
