### PR TITLE
fix: further refining when profile info is logged

### LINKED ISSUE #42334: Experimental features enabled warning shown multiple times
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Enabling experimental features results in the same log statement shown 4 times:

```
2025-09-04 09:03:24,734 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: spiffe:v1
2025-09-04 09:03:25,578 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: spiffe:v1
2025-09-04 09:03:29,245 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 3953ms
Running the server in development mode. DO NOT use this configuration in production.
2025-09-04 09:03:29,763 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: spiffe:v1
2025-09-04 09:03:29,892 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: spiffe:v1
```

With an optimized start it is shown twice instead of 4 times.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

`Experimental features enabled` warning should be shown once

### Actual behavior

`Experimental features enabled` warning is shown 4 or 2 times

### How to Reproduce?

Run:
```
kcw nightly start-dev --features client-auth-federated
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #42334

@mabartos I'd propose this as an alternative to #42334

The intention behind having the logging in KeycloakApplication is for it to be shown even for our non-quarkus usage. The problem with having the log in the constructor is that resteasy annotation scanning is also causing the the constructor to be used.

On the quarkus / picocli side we then should only log any time we aren't going to start quarkus - which we can elevate the shouldStart method to check. This is a more complete check than was being done before, so we'll see the warnings even with the update-compatibility commands.

### CODE REVIEW

**Review by mabartos — DISMISSED** [review]
LGTM.

However, the CI failures might be related to this.

**Comment by shawkins** [comment]
The test failure was due to what is noted by the comment - deferred logging is suppressed.

**Review by mabartos — APPROVED** [review]

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java [hunk 1]
```diff
@@ -58,12 +60,12 @@ public void testEnablePreviewFeatures(CLIResult cliResult) {
...
-    // Should enable "fips" together with all other "preview" features
+    // Should enable "docker" together with all other "preview" features
     @Test
-    @Launch({StartDev.NAME, "--features=preview,fips"})
-    public void testEnablePreviewFeaturesAndFips(CLIResult cliResult) {
+    @Launch({StartDev.NAME, "--features=preview,docker"})
+    public void testEnablePreviewFeaturesAndDocker(CLIResult cliResult) {
+        cliResult.assertStartedDevMode();
         assertPreviewFeaturesEnabled(cliResult);
-        cliResult.assertError("Failed to configure FIPS.");
```
Comment (vmuzikar) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java:66]: Just out of curiosity, why was this change needed?

Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java:66]: Having an error causes the deferred logging output to be lost.

Comment (vmuzikar) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java:66]: Ok, thanks for elaborating.

**Review by vmuzikar — APPROVED** [review]
