### PR TITLE
If application has no URL, render text only

### LINKED ISSUE #25124: If a client does not have a URL the applications page in the account console links to about:blank
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

In the applications view of the account console, clients without a URL to link to are still links, they just point nowhere.

image

If you click on the link, a new tab is opened at "about:blank"

### Version

22.0.5

### Expected behavior

They should probably just not be links.

### Actual behavior

They are links, that are broken.

### How to Reproduce?

Add a client without an endpoint url and go to the applications page in the account console

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ssilvert**
Fixes #25124

### CODE REVIEW

File: js/apps/account-ui/src/applications/Applications.tsx [hunk 1]
```diff
@@ -128,15 +128,22 @@ const Applications = () => {
...
+                        className="pf-u-pl-0 title-case"
+                        component="a"
+                        variant="link"
+                        onClick={() => window.open(application.effectiveUrl)}
+                      >
+                        {application.clientName || application.clientId}{" "}
+                        <ExternalLinkAltIcon />
+                      </Button>
+                    )}
+                    {!application.effectiveUrl && (
```
Comment (jonkoops) [inline js/apps/account-ui/src/applications/Applications.tsx:142]: Rather than inverting the condition here, you could use a ternary:

```tsx
{application.effectiveUrl ? (<Button></Button>) : (<span></span>);
```

File: js/apps/account-ui/src/applications/Applications.tsx [hunk 2]
```diff
@@ -128,15 +128,22 @@ const Applications = () => {
...
-                    >
-                      {application.clientName || application.clientId}{" "}
-                      <ExternalLinkAltIcon />
-                    </Button>
+                    {application.effectiveUrl && (
+                      <Button
+                        className="pf-u-pl-0 title-case"
+                        component="a"
+                        variant="link"
+                        onClick={() => window.open(application.effectiveUrl)}
```
Comment (jonkoops) [inline js/apps/account-ui/src/applications/Applications.tsx:136]: Although his code was was already there it can be slightly improved by passing a `href` and `target` prop instead. 
```suggestion
                        href={application.effectiveUrl}
                        target="_blank"
                        rel="noopener"
```

**Review by jonkoops — DISMISSED** [review]
My PR comments are nits, so approving this regardless.

File: js/apps/account-ui/src/applications/Applications.tsx (hunk 1 above)
Comment (ssilvert) [reply js/apps/account-ui/src/applications/Applications.tsx:142]: I personally find that the ternary operator can make it hard to read, especially when large blocks of code are involved.

**Review by jonkoops — APPROVED** [review]
