### PR TITLE
userprofile shared

### LINKED ISSUE #22818: inputOptionLabels is not used by Account UI v3
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Continuing the work in https://github.com/keycloak/keycloak/issues/22432 and the corresponding PR https://github.com/keycloak/keycloak/pull/22451. The `inputOptionLabels` user profile option, which can be used to specify translatable fields for a select, is not respected in the Account UI.

### Version

22

### Expected behavior

With inputOptionLabels I should be able to provide translated labels for select options in the account ui.

### Actual behavior

The inputOptionLabels option is ignored by account ui.

### How to Reproduce?

1. Add a custom attribute in the user profile:
```json
{
      "name": "attr",
      "displayName": "${attr}",
      "selector": {
        "scopes": [
          "microprofile-jwt",
          "phone",
          "profile",
          "email",
          "web-origins",
          "roles",
          "offline_access",
          "role_list",
          "address",
          "acr"
        ]
      },
      "permissions": {
        "edit": [
          "user",
          "admin"
        ],
        "view": [
          "user",
          "admin"
        ]
      },
      "annotations": {
        "inputType": "select",
        "inputOptionLabels": {
          "option1": "${option1Label}",
          "option2": "${option2Label}",
        }
      },
      "validations": {
        "options": {
          "options": [
            "option1",
            "option2"
          ]
        }
      },
      "required": {
        "roles": [
          "user"
        ],
        "scopes": [
          "microprofile-jwt",
          "phone",
          "profile",
          "email",
          "web-origins",
          "roles",
          "offline_access",
          "role_list",
          "address",
          "acr"
        ]
      },
      "group": null
    },
```
2. Check the account console for a user
3. It says `option1` and `option2` instead of `option1Label` and `option2Label`

### Anything else?

The corresponding source file https://github.com/keycloak/keycloak/blob/main/js/apps/account-ui/src/personal-info/components/SelectComponent.tsx#L53:
```tsx
<Select
  toggleId={attribute.name}
  onToggle={(b) => setOpen(b)}
  onSelect={(_, value) => {
    const option = value.toString();
    if (Array.isArray(field.value)) {
      if (field.value.includes(option)) {
        field.onChange(
          field.value.filter((item: string) => item !== option),
        );
      } else {
        field.onChange([...field.value, option]);
      }
    } else {
      field.onChange(option);
      setOpen(false);
    }
  }}
  selections={field.value ? field.value : t("choose")}
  variant={Array.isArray(field.value) ? "typeaheadmulti" : "single"}
  aria-label={t("selectOne")}
  isOpen={open}
>
  {options.map((option) => (
    <SelectOption
      selected={field.value === option}
      key={option}
      value={option}
    >
      {option}
    </SelectOption>
  ))}
</Select>
```

### PR DESCRIPTION
**Pull request by edewit**
- move account ui user profile to shared
- use ui-shared on admin same error handling

fixes: #22818

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
@edewit LGTM.

**Comment by pedroigor** [comment]
Test failure seems related to a message not being resolved. Will fix it.

**Comment by jonkoops** [comment]
Let's hold on merging this in until we land #23537

**Comment by edewit** [comment]
this also fixes: #22818

**Comment by ssilvert** [comment]
> Let's hold on merging this in until we land #23537

That is done.  

@edewit @jonkoops Can we move forward with this one now?

**Comment by jonkoops** [comment]
Sure, I will try to get a review in, but it looks like there are still some failures on CI that need to be addressed.

**Review by jonkoops — DISMISSED** [review]
LGTM, but some of the CI jobs are still failing.

File: js/libs/ui-shared/src/user-profile/UserProfileFields.tsx [hunk 1]
```diff
@@ -199,19 +217,12 @@ function determineInputType(
 
   const inputType = attribute.annotations?.inputType;
 
-  // If the attribute has no valid input type, fall back to a default input type.
-  // Depending on the length of the value, we either use a 'multi-input' or a 'text' input type so all values are always visible.
+  // If the attribute has no valid input type, it is always multi-valued.
   if (!isValidInputType(inputType)) {
-    return Array.isArray(value) && value.length > 1 ? "multi-input" : "text";
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/UserProfileFields.tsx:205]: This fixes a bug, so that the multi and text values are handled correctly in the absence of an input type. This should probably be restored.

File: js/libs/ui-shared/src/user-profile/userProfileConfig.d.ts
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/userProfileConfig.d.ts:1]: Should this not be part of the Admin Client? Or at least part of it? Or are these custom types we only use internally?

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/libs/ui-shared/src/user-profile/UserProfileFields.tsx (hunk 1 above)
Comment (edewit) [reply js/libs/ui-shared/src/user-profile/UserProfileFields.tsx:205]: right I have the same fallback just optimised it a bit

File: js/libs/ui-shared/src/user-profile/userProfileConfig.d.ts
Comment (edewit) [reply js/libs/ui-shared/src/user-profile/userProfileConfig.d.ts:1]: yes that would be good

Comment (edewit) [reply js/libs/ui-shared/src/user-profile/userProfileConfig.d.ts:1]: but that would make that our ui-shared is depended on admin client

File: js/apps/account-ui/src/api/representations.ts [hunk 2]
```diff
@@ -87,16 +88,9 @@ export interface UserProfileMetadata {
...
 }
 
-export interface UserRepresentation {
-  id: string;
-  username: string;
-  firstName: string;
-  lastName: string;
-  email: string;
-  emailVerified: boolean;
+export type UserRepresentation = UserFormFields & {
```
Comment (jonkoops) [inline js/apps/account-ui/src/api/representations.ts:91]: `UserFormFields` is a different type than `UserRepresentation`, if we need a `UserRepresentation` we should use the one exported by the Admin Client directly.

File: js/apps/account-ui/src/personal-info/PersonalInfo.tsx [hunk 3]
```diff
@@ -6,87 +6,104 @@ import {
...
+                variant="link"
+                onClick={() =>
+                  keycloak?.keycloak.login({ action: "UPDATE_EMAIL" })
+                }
+                icon={<ExternalLinkSquareAltIcon />}
+                iconPosition="right"
+              >
+                {t("updateEmail")}
+              </Button>
+            ) : undefined
```
Comment (jonkoops) [inline js/apps/account-ui/src/personal-info/PersonalInfo.tsx:104]: I think this could use an AND operator here since the else condition doesn't render anything.

```tsx
(!isRegistrationEmailAsUsername || isEditUserNameAllowed) && (
  <Button></Button>
)
```

File: js/libs/keycloak-admin-client/src/defs/userProfileMetadata.ts [hunk 4]
```diff
@@ -1,10 +1,37 @@
-// See: https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/idm/UserProfileMetadata.java
-export interface UserProfileMetadata {
-  attributes?: UserProfileAttributeMetadata[];
-  groups?: UserProfileAttributeGroupMetadata[];
+export default interface UserProfileConfig {
```
Comment (jonkoops) [inline js/libs/keycloak-admin-client/src/defs/userProfileMetadata.ts:1]: The `UserProfileConfig` is a different type of REST API response than `UserProfileMetadata`, and should be contained in in it's own file. I don't recall the exact details, but I believe that  `UserProfileMetadata` is supposed be used generically, whereas `UserProfileConfig` is exclusively used for administration purposes.

@pedroigor is the above correct?

File: js/libs/ui-shared/src/user-profile/MultiInputComponent.tsx [hunk 5]
```diff
@@ -0,0 +1,150 @@
...
+  </UserProfileGroup>
+);
+
+function stringToMultiline(value?: string): string[] {
+  return typeof value === "string" ? value.split("##") : [];
+}
+
+function toStringValue(formValue: string[]): string {
+  return formValue.join("##");
+}
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/MultiInputComponent.tsx:40]: Does this still apply for user profile? This should already be covered by the multi-value attribute right?

File: js/libs/ui-shared/src/user-profile/MultiInputComponent.tsx [hunk 6]
```diff
@@ -0,0 +1,150 @@
...
+  ...rest
+}: MultiLineInputProps) => {
+  const { register, setValue, control } = form;
+  const value = useWatch({
+    name,
+    control,
+    defaultValue: defaultValue || "",
+  });
+
+  const fields = useMemo<string[]>(() => {
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/MultiInputComponent.tsx:70]: Same here, I do believe we no longer handle multi-value with string delimiters when user profile is enabled.

File: js/libs/ui-shared/src/user-profile/UserProfileFields.tsx [hunk 7]
```diff
@@ -199,25 +224,22 @@ function determineInputType(
 
   const inputType = attribute.annotations?.inputType;
 
-  // If the attribute has no valid input type, fall back to a default input type.
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/UserProfileFields.tsx:202]: Can we restore some of the implementation from #24359 here? Especially the comments on the code that explain the reasoning, as this has a topic of a lot of debate and changes, and I'd really like to be able to get back to this in the future and be able to explain the reasoning should questions inevitably arise.

**Review by jonkoops — CHANGES_REQUESTED** [review]
Looks like there are still a couple of failures on CI.

File: js/apps/account-ui/src/api/representations.ts (hunk 2 above)
Comment (edewit) [reply js/apps/account-ui/src/api/representations.ts:91]: atm account-ui has it's own "client" and it doesn't need or use the admin rest endpoints, seems wrong to make it dependent on that just to share a domain model representation

Comment (jonkoops) [reply js/apps/account-ui/src/api/representations.ts:91]: I think it's fine to import the types from the Admin Client, they will get compiled away during bundling anyways.

File: js/libs/keycloak-admin-client/src/defs/userProfileMetadata.ts (hunk 4 above)
Comment (edewit) [reply js/libs/keycloak-admin-client/src/defs/userProfileMetadata.ts:1]: I don't see how / why the filename matters I could rename it to `userProfile.ts`, to me it makes sense to have it all in one file

Comment (jonkoops) [reply js/libs/keycloak-admin-client/src/defs/userProfileMetadata.ts:1]: Mostly because they are two separate representations that are meant for different purposes, and should not be used interchangeably. Putting them in the same file can lead people touching this file in the future to believe they might be the same thing.

File: js/libs/ui-shared/src/user-profile/UserProfileFields.tsx (hunk 7 above)
Comment (jonkoops) [reply js/libs/ui-shared/src/user-profile/UserProfileFields.tsx:202]: Talked to @edewit about this, and we'll keep this the way it is. Consider this resolved.

**Review by jonkoops — DISMISSED** [review]

**Review by jonkoops — DISMISSED** [review]

**Review by jonkoops — DISMISSED** [review]

**Review by jonkoops — DISMISSED** [review]

**Review by ssilvert — DISMISSED** [review]

**Review by pedroigor — DISMISSED** [review]

**Review by hmlnarik — DISMISSED** [review]
Approving Java part

**Review by ahus1 — DISMISSED** [review]
Approving as of @hmlnarik's review for the store code ownership

**Comment by ahus1** [comment]
@jonkoops /  @ssilvert - AFAIK now only a review from @keycloak/ui-maintainers is needed.

File: services/src/main/java/org/keycloak/services/resources/admin/AdminMessageFormatter.java [hunk 8]
```diff
@@ -1,65 +0,0 @@
-/*
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/services/resources/admin/AdminMessageFormatter.java:1]: Ah, so we already had a way to format messages in a localized manner on the API side. Sigh, I really wish we were using this instead of returning arbitrary keys.

**Review by jonkoops — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]
