### PR TITLE
User listing broken because of missing is_temporary_admin attribute

### LINKED ISSUE #39720: User listing broken because of missing `is_temporary_admin` attribute
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

This change https://github.com/keycloak/keycloak/pull/39598 introduced a bug in the user listing page because the attribute `is_temporary_admin` is not always available from the user attributes and that breaks the UI.

### Version

999.0.0-SNAPSHOT

### Regression

- [x] The issue is a regression

### Expected behavior

Able to list users 

### Actual behavior

Not able to list users 

### How to Reproduce?

Try to list users in a realm

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #39720

### CODE REVIEW

File: js/apps/admin-ui/src/components/users/UserDataTable.tsx [hunk 1]
```diff
@@ -65,14 +65,15 @@ const UserDetailLink = (user: BruteUser) => {
...
-      {user.attributes?.["is_temporary_admin"][0] === "true" && (
-        <Tooltip content={t("temporaryAdmin")}>
-          <WarningTriangleIcon
-            className="pf-v5-u-ml-sm"
-            id="temporary-admin-label"
-          />
-        </Tooltip>
-      )}
+      {user.attributes?.["is_temporary_admin"] &&
+        user.attributes?.["is_temporary_admin"][0] === "true" && (
```
Comment (edewit) [inline js/apps/admin-ui/src/components/users/UserDataTable.tsx:69]:
```suggestion
      {user.attributes?.["is_temporary_admin"]?.[0] === "true" && (
```

Comment (pedroigor) [reply js/apps/admin-ui/src/components/users/UserDataTable.tsx]: Tested here, thanks!

**Review by edewit — DISMISSED** [review]

**Review by edewit — APPROVED** [review]
