### PR TITLE
Use correct path to account console

### LINKED ISSUE #27709: Account console does not work with `--http-relative-path`
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The router defined in account console assumes fixed pathname /realms/_realm_/account, however when using `--http-relative-path`, this changes significantly. For example, the testsuite uses `/auth` prefix, and the account console only displays error when navigating to `/auth/realms/master/account/`.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Account console is displayed

### Actual behavior

Account console is not loaded

### How to Reproduce?

Run keycloak with `--http-relative-path=/auth` and navigate to http://localhost:8080/auth/realms/master/account/

### Anything else?

Caused by #22192, the fix #27604 was assuming only default locations.

### PR DESCRIPTION
**Pull request by hmlnarik**
Fixes: #27709

### CODE REVIEW

File: js/apps/account-ui/src/root/PageNav.tsx [hunk 1]
```diff
@@ -134,9 +132,7 @@ export const NavLink = ({
   isActive,
   children,
 }: PropsWithChildren<NavLinkProps>) => {
-  const { realm } = useParams();
-
-  const menuItemPath = `${getRootPath(realm)}/${to}`;
```
Comment (jonkoops) [inline js/apps/account-ui/src/root/PageNav.tsx:139]: I think this is the only place `getRootPath()` was used in the actual code that gets bundled. So perhaps we should move this utility out of `src`? Or perhaps even better, we could re-write `getRootPath()` to return `new URL(environment.baseUrl).pathname`.

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/account-ui/src/root/PageNav.tsx (hunk 1 above)
Comment (hmlnarik) [reply js/apps/account-ui/src/root/PageNav.tsx:139]: TL;DR: This particular issue is a release blocker since it renders `--http-relative-path` option unusable. The `getRootPath` removal which was present in the first version of this PR turned out not really straightforward failing the tests. So I'd prefer this refactor be done separately.

Longer version:
The `getRootPath` is parameterized with realm name, and this parameterization is used in linked accounts tests. Hence it cannot be easily exchanged with the `baseUrl` which contains already realm name hardcoded. Also `getRootPath` turned out to be called from several other places and the account console tests failed.

Comment (hmlnarik) [reply js/apps/account-ui/src/root/PageNav.tsx:139]: Introduced #27716 so that this refactor is not forgotten.

**Review by jonkoops — APPROVED** [review]

**Review by abstractj — APPROVED** [review]
