### PR TITLE
Fixed persisting translations for attribute groups and improved errors for empty translations on attribute/attribute groups save

### LINKED ISSUE #33531: Previously entered translations should persist in the translation dialog for the attribute groups
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Previously entered translations should persist in the translation dialog for the attribute groups

### Version

main

### Regression

- [x] The issue is a regression

### Expected behavior

Previously entered translations should persist in the translation dialog for the attribute groups

### Actual behavior

Previously entered translations don't persist in the translation dialog for the attribute groups, causing an error to display when saving an attribute group without making any changes

### How to Reproduce?

Go to the previously created attribute group (with previously added translations). Open the translation dialogs individually and observe that the translation values are empty

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/33531

I have also found some use cases for improving the errors when saving attributes/attribute groups without translations or with empty translations and decided to address them in this PR as well.

Test cases
Screenshot 2024-10-17 at 10 07 41

### CODE REVIEW

File: js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx [hunk 1]
```diff
@@ -1,3 +1,5 @@
+/* eslint-disable @typescript-eslint/no-unused-vars */
+/* eslint-disable @typescript-eslint/no-empty-function */
```
Comment (edewit) [inline js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx:2]: can't we do without this?

File: js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx [hunk 2]
```diff
@@ -293,11 +307,13 @@ export default function NewAttributeSettings() {
               },
               translation.value,
             );
-          } catch {
-            console.error(`Error saving translation for ${translation.locale}`);
+          } catch (error) {
+            console.error(
+              `Error saving translation for ${translation.locale}: ${error}`,
+            );
```
Comment (edewit) [inline js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx:313]: don't we want to put this into an alert?

**Review by edewit — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx [hunk 3]
```diff
@@ -221,17 +229,22 @@ export default function NewAttributeSettings() {
...
+      });
+      form.setValue(
+        "translations",
+        translationsToSave.flatMap(
+          (translationData: any) => translationData.translations,
+        ),
+      );
     },
-    [combinedLocales],
+    () => {},
```
Comment (edewit) [inline js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx:246]: This is wrong you don't do anything with the fetched result

File: js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx [hunk 4]
```diff
@@ -221,17 +229,22 @@ export default function NewAttributeSettings() {
...
+          (translationData: any) => translationData.translations,
         ),
-      }));
+      });
+      form.setValue(
+        "translations",
+        translationsToSave.flatMap(
+          (translationData: any) => translationData.translations,
+        ),
+      );
```
Comment (edewit) [inline js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx:244]: you can put this in the empty closure

File: js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx [hunk 5]
```diff
@@ -173,6 +176,7 @@ export default function NewAttributeSettings() {
   useFetch(
     async () => {
       const translationsToSave: any[] = [];
```
Comment (edewit) [inline js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx:178]: This should be an array of type `Translations`

**Review by edewit — APPROVED** [review]
