### PR TITLE
fix: reviewed hidden options for what can be removed

### LINKED ISSUE #48003: Follow-up to adding a synthetic option
### Description

After introducing a synthetic option #47399 there are a couple of additional follow-ups:

1. Review and remove unnecessary hidden options 
2. Allow connection timeout to work for all datasources - split to #48053 
3. Expose hidden management options - #48098

### PR DESCRIPTION
**Pull request by shawkins**
~also converted db-connect-timeout to an option for all datasources~

~and exposed more management options~

closes: #48003

The only remaining hidden options once this and the related prs are merged will be those that we either explicitly rely on as an intermediate value, or possible need (db-dialect, several header options).

### CODE REVIEW

**Comment by shawkins** [comment]
Actually I'll tease this apart into separate prs.

edit: done

This pr just changes hidden to synthetic and does not expand what options are exposed.

**Comment by shawkins** [comment]
@mabartos should be ready for a review. This refined the synthetic concept so that it's still possible to do a get of the from / kc key and get the derived value when possible so that the existing usage of the logging and header related options could remain. The mapping logic still won't look for the direct setting of the value, so there's no concern about it being set in an unexpected way.

**Comment by shawkins** [comment]
Addressed the review comments.

**Comment by shawkins** [comment]
> This refined the synthetic concept so that it's still possible to do a get of the from / kc key and get the derived value when possible so that the existing usage of the logging and header related options could remain.

This isn't true yet for synthetic wildcards - you cannot get the value using the from (https://github.com/keycloak/keycloak/blob/760c170367483645a03f8c07a29e0b6dec427847/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/WildcardPropertyMapper.java#L114). I can either try to expand the logic in this PR, or capture a follow up and in general think about speading up the matching routine as our number of wildcards has continued to grow.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

Not merging yet to wait for @mabartos re-review.

File: quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java [hunk 1]
```diff
@@ -20,32 +20,6 @@ public enum Headers {
...
-    public static final Option<Boolean> PROXY_X_FORWARDED_PREFIX_HEADER_ENABLED = new OptionBuilder<>("proxy-allow-x-forwarded-prefix-header", Boolean.class)
-            .category(OptionCategory.PROXY)
-            .defaultValue(Boolean.FALSE)
-            .build();
-
-    public static final Option<Boolean> PROXY_TRUSTED_HEADER_ENABLED = new OptionBuilder<>("proxy-trusted-header-enabled", Boolean.class)
-            .category(OptionCategory.PROXY)
-            .defaultValue(Boolean.FALSE)
-            .hidden()
-            .build();
```
Comment (mabartos) [inline quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java:47]: @shawkins Some of them are not marked as hidden. However, they don't contain the description; does it mean they were some kind of pseudo-hidden? Not shown in help, not shown on website, not shown in CLI suggestions?

Comment (mabartos) [reply quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java:47]: Ahh, see it here: 
https://github.com/keycloak/keycloak/pull/48020/changes#diff-f681a3f8320c0f85b1bf524f7f503e205b9cade1cede83a5b1d38a0a5519c2ddL259

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java [hunk 2]
```diff
@@ -36,7 +36,7 @@ public List<PropertyMapper<?>> getPropertyMappers() {
                         .validator(value -> validateDuration(TransactionOptions.TRANSACTION_SETUP_TIMEOUT, value))
                         .paramLabel("timeout")
                         .build(),
-                fromOption(TransactionOptions.DB_LOCK_TIMEOUT)
+                fromOption(TransactionOptions.TRANSACTION_SETUP_TIMEOUT)
                         .mapFrom(TransactionOptions.TRANSACTION_SETUP_TIMEOUT)
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java:40]: @shawkins Does it work correctly? If I call the Configuration.getConf(TRANSACTION_SETUP_TIMEOUT), how does it know which property mapper should be used? Isn't it required to create a synthetic version of the option here? `fromOption(TransactionOptions.TRANSACTION_SETUP_TIMEOUT)`

**Review by mabartos — APPROVED** [review]
@shawkins LGTM, nice work!

Just having one question, but as tests passed, it's probably ok.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java:40]: @mabartos In the pr that introduced synthetic options, this was added as implicit behavior. If the from and mapFrom as the same, the PropertyMapper builder will implicitly create a synthetic option.

The intention with the initial changes was to make so most of the time an explicit synthetic option was not needed.

The changes in this pr relax that, but not completely: https://github.com/keycloak/keycloak/pull/48020#issuecomment-4260711909
