### PR TITLE
running mappers during account linking

### LINKED ISSUE #11195: Sync user attributes on identity provider account linking
### Describe the bug

Currently, user attributes do not seem to sync when using account linking from an identity provider, despite mappers being set up for the identity provider.

I can see a PR open that seems to address the issue (though no issue open on Github as far as I can see), could this be reviewed?

https://github.com/keycloak/keycloak/pull/8139

### Version

17.0.1

### Expected behavior

When a user has their account linked from an identity provider and attribute mappers are set up for the provider, the attributes are created for the Keycloak user using their identity provider account.

### Actual behavior

A user can successfully link to an identity provider account but no attributes are created for the user.

### How to Reproduce?

Enable account linking only for an identity provider and mappers for some attributes.

### Anything else?

PR seems to be open here:
https://github.com/keycloak/keycloak/pull/8139

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #11195

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java [hunk 1]
```diff
@@ -950,7 +950,11 @@ private Response performAccountLinking(AuthenticationSessionModel authSession, U
             }
         } else {
             this.session.users().addFederatedIdentity(this.realmModel, authenticatedUser, newModel);
+            federatedUser = session.users().getUserByFederatedIdentity(realmModel, newModel);
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java:953]:
```suggestion
            federatedUser = authenticatedUser;
```

Note that it should be same user (See line 927). So we can save some DB queries by not searching for this user again?

**Review by mposolda — COMMENTED** [review]
@pedroigor Added one suggestion inline. WDYT?

**Review by mposolda — APPROVED** [review]
