### PR TITLE
fix: ensure that kc.config.args is omitted from show-config

### LINKED ISSUE #34460: kc.config.args exposed in show-config
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

kc.config.args exposed in show-config - this was due to the removal of the ignored property with #34156

### Version

latest

### Regression

- [X] The issue is a regression

### Expected behavior

kc.config.args should not be exposed

### Actual behavior

kc.config.args is exposed - any sensitive info from the cli (which we recommend against) will be displayed in show-config

### How to Reproduce?

./kc.sh show-config --spi-foo-password=mypassword

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #34460

Change the logic to be opt-in, rather than opt-out for system properties shown in show-config. It's not expected that users will directly use -Dkc.something=value, so it seems fine to ignore that case.

### CODE REVIEW

File: quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java
Comment (vmuzikar) [inline quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:1]: Should we also specifically test  that sys props no longer appear in show-config?

Comment (shawkins) [reply quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:1]: Sure I can also set an arbitrary kc. system property and make sure it doesn't appear.

Comment (vmuzikar) [reply quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:1]: > Sure I can also set an arbitrary kc. system property and make sure it doesn't appear.

Sounds good.

Comment (shawkins) [reply quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:1]: Should be good now.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java [hunk 1]
```diff
@@ -100,28 +97,6 @@ private static Map<String, Set<String>> getPropertiesByGroup() {
...
-                })
-                .filter(ShowConfig::filterByGroup)
-                .collect(Collectors.groupingBy(ShowConfig::groupProperties, Collectors.toSet()))
-                .forEach(new BiConsumer<String, Set<String>>() {
-                    @Override
-                    public void accept(String group, Set<String> propertyNames) {
-                        properties.computeIfAbsent(group, name -> new HashSet<>()).addAll(propertyNames);
-                    }
-                });
-
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java:124]: Just out of curiosity - what was the purpose of this before? It seems all property names were already added to the map, right? And we don't need to check if it was persisted, or not. Is it correct?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java [hunk 2]
```diff
@@ -144,7 +119,11 @@ private void printProperty(String property) {
 
         PropertyMapper<?> mapper = PropertyMappers.getMapper(property);
 
-        if (mapper != null && mapper.isRunTime()) {
+        if (mapper == null) {
+            if (configValue.getSourceName().equals("SysPropConfigSource") && !allowedSystemPropertyKeys.contains(property)) {
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java:123]: There are a couple of issues with that - the ordinal is configurable based upon a system property. Also it's currently below our file sources - which may be confusing and that we may want to adjust it (or our file sources). We can log a quarkus enhancement about exposing the name as well.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java:124]: That was my read - we're iterating over the same set of names either way. Adding filtering won't expand what is included.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java [hunk 3]
```diff
@@ -154,10 +133,6 @@ private void printProperty(String property) {
     }
 
     private static String groupProperties(String property) {
-        if (property.startsWith("%")) {
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java:157]: @shawkins Just out of curiosity - What was the purpose of using '%'? And why it's gonna be removed now? It should mark a profile for the config property, right?

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java:157]: In this instance % properties aren't emited in any case by the surrounding logic - only those properly prefixed by quarkus. or keycloak.

More generally there are a couple of places where we handling profile based property names - however the current behavior of smallrye makes me think that is highly dependent on how you are accessing the configuration. From a top-level you never see those names - they will have already been resolved against the profile.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

**Review by mabartos — APPROVED** [review]
