### PR TITLE
fix: remove the reliance on allowed classes

### LINKED ISSUE #25038: ServerRequestFilter / ServerResponseFilter not being picked up
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

We have a LoggingFilter similar to the one described in the Resteasy Documentation (https://quarkus.io/guides/resteasy-reactive#the-jakarta-rest-way) included in Keycloak. This filter used to work up until Keycloak 22.0.5 but is not being picked up or logging in Keycloak 23.0.0.

The Release Notes for Keycloak 23.0.0 mention a change from Resteasy Classic to Resteasy Reactive (https://www.keycloak.org/docs/23.0.0/upgrading/#resteeasy-reactive). Howver, the filter itself does not use any Reasteasy dependency. I did find some similar filters inside the Keycloak code base itself, namely `CloseSessionHandler` and `KeycloakSecurityHeadersFilter` that are directly registered as part of the `getClasses` method of the `Application` class. I did not find an extension hook for registering our filter, however. 

### Version

23.0.0

### Expected behavior

`ServerRequestFilter` and `ServerResponseFilter` classes are picked up and run.

### Actual behavior

`ServerRequestFilter` and `ServerResponseFilter` classes are not running.

### How to Reproduce?

1. Build a simple Logging Filter like this https://quarkus.io/guides/resteasy-reactive#the-jakarta-rest-way
2. Package it into a jar file.
3. Copy jar file to Keycloak Providers directory
4. Start Keycloak and request a resource.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #25038

cc @geoand @vmuzikar this seems to fix our issue, but requires quarkus to not use the Application.getClasses and instead rely upon the Provider annotation.

I don't see any existing tests covering the usage of provider based Container*Filters - do we want to add something for this case?

Also this logic can be cleaned up a little further if we do #27242

### CODE REVIEW

**Comment by geoand** [comment]
Seems reasonable to me!

**Comment by shawkins** [comment]
Updated to include an integration test to make sure a filter is picked up.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java [hunk 1]
```diff
@@ -69,13 +66,6 @@ public Set<Object> getSingletons() {
...
     public Set<Class<?>> getClasses() {
-        Set<Class<?>> classes = new HashSet<>(super.getClasses());
-
-        classes.add(QuarkusObjectMapperResolver.class);
-        classes.add(CloseSessionHandler.class);
-
-        classes.add(DebugHostnameSettingsResource.class);
-
-        return classes;
+        return Set.of();
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:69]: This approach seems clear and elegant but I can see one major drawback to it: duplicated logic for provider classes. `KeycloakApplication` uses `getClasses` while `QuarkusKeycloakApplication` uses annotations and filters out the classes in `KeycloakProcessor`. AFAIK `KeycloakApplication` serves now just for the Undertow auth server, i.e. just for dev purposes. I wonder if Undertow can't use at least the jax-rs annotations as well.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    @TestProvider(TestFilterTestProvider.class)
+    public void requestFilterTest(KeycloakDistribution dist) {
+        CLIResult cliResult = dist.run("start-dev");
+
+        cliResult.assertStartedDevMode();
+
+        assertEquals(200, when().get("/").getStatusCode());
+
+        Awaitility.await().atMost(5, TimeUnit.SECONDS).untilAsserted(
+                () -> cliResult.assertMessage("Request GET / has context request true has keycloaksession false"));
```
Comment (vmuzikar) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java:48]: Shouldn't keycloaksession be true as well?

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thanks for the PR! Added some comments.

Also we need a review from @keycloak/core.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:69]: The issue is with the conditional inclusion of resources. See #27242 - we'll be able at that point to remove the classes / singletons from KeycloakApplication entirely.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java (hunk 2 above)
Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java:48]: That's the behavior I'm seen with the live server as well - hitting just the landing page seems to happen before the handler chain is invoked and the session is associated. There's a related issue with this in that when you use prematching and resteasy reactive filters the session is always null.

Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java:48]: To expand on this, with the filter annotated with PreMatching we see:

```
Request GET /realms/master/ has context request true has keycloaksession false
Request GET / has context request true has keycloaksession false
```

Without PreMatching, /realms/master/ now has a session:
```
Request GET /realms/master/ has context request true has keycloaksession true
Request GET / has context request true has keycloaksession false
```

This mimicks the behavior seen when using resteasy reactive filters from https://github.com/keycloak/keycloak/issues/25038#issuecomment-1966464394

The user indicated the PreMatching in prior releases of Keycloak still provided access to the session, so it does appear to be a difference with resteasy reactive - namely that the session is created via a customized handler chain, and the PreMatching filter must be running before this. cc @geoand 

My guess was this is something that at the very least we'd have to document with #27057 (I've added a note about this there), but if it seems like a regression then let's open another issue. 

The / resource must have different handling still (I think we just issue a redirect), so perhaps a session shouldn't be expected there.

Comment (geoand) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java:48]: > The user indicated the PreMatching in prior releases of Keycloak still provided access to the session, so it does appear to be a difference with resteasy reactive - namely that the session is created via a customized handler chain, and the PreMatching filter must be running before this. cc @geoand

I can't say I fully understand the problem, but if this is an issue, we can look into it further together

Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java:48]: @geoand keycloaksession creation happens here: https://github.com/keycloak/keycloak/blob/77c4cee4d0ea84b17f9ef46fa70638fa16a46c87/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/CreateSessionHandler.java#L42

Which is controlled by https://github.com/keycloak/keycloak/blob/77c4cee4d0ea84b17f9ef46fa70638fa16a46c87/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/KeycloakHandlerChainCustomizer.java#L62

When a request filter is annotated with PreMatching, what we see is that it the filter will get invoked before the CreateSessionHandler runs.

The user indicates that in prior releases of Keycloak, using just the resteasy classic stack, that a PreMatching filter still had access to the session. 

In the prior releases the keycloaksession creation was handled by QuarkusRequestFilter https://github.com/keycloak/keycloak/commit/217a09ce46bac48b7492a881e2ca5fbeef9dfd6d#diff-80ef3a628be94a94774a6f6e71af1c5d29cfb9dedf6c1e88c39ceb5664662239L134 which was installed via https://github.com/keycloak/keycloak/commit/217a09ce46bac48b7492a881e2ca5fbeef9dfd6d#diff-6ebe7f8db3e4dea9dbefd50eed883b8aac997e6c01127e283631e92e9d022835L614 - which at first glance does appear like it would have priority to run before anything else.

Comment (geoand) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java:48]: I have no idea what the implications would be for Keycloak, but I assume we could the Keycloak handler run before the pre match handler

Comment (vmuzikar) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java:48]: Technically we could create the session at the `BEFORE_PRE_MATCH` phase in the KeycloakHandlerChainCustomizer but I've got no clue why we're not doing it already. Perhaps @pedroigor remembers the reasoning.

**Review by vmuzikar — APPROVED** [review]
LGTM, if we'll get rid of the duplicated logic for adding resources in https://github.com/keycloak/keycloak/pull/27387.

The PreMatching issue will be handled separately in https://github.com/keycloak/keycloak/issues/27446

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java (hunk 2 above)
Comment (pedroigor) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java:48]: @vmuzikar I think only because it is the closest method before invoking resources so that we don't have state being held for more time than needed to execute a method in a resource.
