### PR TITLE
Decoupling legacy and dynamic user profiles and exposing metadata from admin api

### LINKED ISSUE #22532: Decoupling legacy and dynamic user profiles and exposing metadata from admin api
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

The legacy and dynamic user profile should be decoupled in order to avoid one impacting the other when managing user attributes.

In the 22 release, this coupling is causing:

* Username and e-mail fields are not properly managed depending on how the registration as username and edit username settings are set to a realm (using the different combinations of both)
* E-mail not properly managed and shown in UI when the update email feature is enabled
* Admin UI not properly rendering attributes when the user profile is enabled
* Admin API failing to update username/email depending on how the registration as username and edit username settings are set to a realm

### Version

22

### Expected behavior

Username and email are properly managed depending on how the registration as username and edit username settings are set to a realm.

Changes to legacy should not directly affect the dynamic user profile behavior, and vice-versa.

### Actual behavior

Username and email are not properly managed depending on how the registration as username and edit username settings are set to a realm.

Changes to legacy is affected by the dynamic user profile behavior, and vice-versa.

### How to Reproduce?

N/A

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #22532

* Adding more test coverage to user management when registration as username and edit username settings are set
* Adding more test coverage to user management through account and user APIs
* Adding more test coverage to attribute validation and how they are managed through user profile

### CODE REVIEW

File: js/apps/admin-ui/src/user/components/SelectComponent.tsx
Comment (jonkoops) [inline js/apps/admin-ui/src/user/components/SelectComponent.tsx:1]: The attribute permissions are also being [referenced here](https://github.com/keycloak/keycloak/blob/339ee6c1b7bcee49f2bca3bcc187e7de6debd32c/js/apps/admin-ui/src/user/UserProfileFields.tsx#L98), should that code also be refactored?

File: js/apps/admin-ui/src/user/UserForm.tsx [hunk 1]
```diff
@@ -224,7 +224,7 @@ export const UserForm = ({
         </FormGroup>
       )}
       {isUserProfileEnabled ? (
-        <UserProfileFields />
+        <UserProfileFields config={user?.userProfileMetadata!} />
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserForm.tsx:227]: Since the model defines `userProfileMetadata` as optional, I would prefer if we don't use the non-null assertion operator, as it can lead to errors around nullability, even if in this case the response might always be defined.

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/user/UserForm.tsx (hunk 1 above)
Comment (edewit) [reply js/apps/admin-ui/src/user/UserForm.tsx:227]: it must be defined at this point because `isUserProfileEnabled` is true

**Review by mposolda — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]
