### PR TITLE
Fixed removing attributes from a user

### LINKED ISSUE #22570: Unable to remove user attributes
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When removing all attributes from a user and then saving the user, the attributes are not removed.

### Version

nighly

### Expected behavior

All of the attributes are removed.

### Actual behavior

None of the attributes are removed.

### How to Reproduce?

1. Go to the 'Attributes' tab of any user.
2. Add an attribute of any kind.
3. Save the user.
4. Remove the previously added attribute.
5. Save the user.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/22570

### CODE REVIEW

File: js/apps/admin-ui/src/user/EditUser.tsx [hunk 1]
```diff
@@ -152,7 +152,7 @@ const EditUserForm = ({ user, bruteForced, refresh }: EditUserFormProps) => {
     const attributes =
       "key" in (formUser.attributes?.[0] || [])
         ? keyValueToArray(formUser.attributes as KeyValueType[])
-        : user.attributes;
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/EditUser.tsx:155]: I feel like this has been added with some intent to fix a bug, but I could be wrong. Just to be sure, have you tried the following:

- Add a couple of attributes to a user and save.
- Reload the page and change some other field, leaving the attributes, then save the user.
- Reload the page again and save the attributes.

I feel like perhaps if the attributes are left untouched their value in the form might be left empty, hence the fallback to the initial value of the user attributes.

**Review by jonkoops — APPROVED** [review]
LGTM, but let's make sure to test this thoroughly.

**Review by edewit — APPROVED** [review]

File: js/apps/admin-ui/src/user/EditUser.tsx (hunk 1 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/EditUser.tsx:155]: Perfect, thanks for verifying this!
