### PR TITLE
fix: detecting provider changes when running start optimized

### LINKED ISSUE #34665: Add a check when using --optimized for changed providers
### Description

As a follow up to #34260 it makes sense to add a check that providers have changed even for a --optimized start. This could either be a warning or an error (we now do that for changed build time options).

### PR DESCRIPTION
**Pull request by shawkins**
~~also using the optimized mixin rather than scanning the args~~ - this cannot be done based upon the mixin because we are testing for --optimized prior to picocli parsing.

closes: #34665

### CODE REVIEW

**Comment by shawkins** [comment]
This should be ready. The message format will mention that something with the kc.provider.file. prefix has changed. Alternatively we could reuse auto-build option changed logic showing the old and new values - but we'd probably need to mask quarkus. values.

Using a single check for all persisted build state does make things more stringent - the operator was trying to unilaterally turn off health-enabled via an env var, but use an optimized image that would no longer work. If we consider something like that a breaking change for optimized non-server commands, then this will need to be reworked.

cc @mabartos @vmuzikar @Pepo48

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java [hunk 1]
```diff
@@ -147,7 +145,7 @@ private void buildKeycloakJobContainer(Container keycloakContainer, KeycloakReal
 
         var override = "--override=false";
 
-        var runBuild = !keycloakContainer.getArgs().contains(KeycloakDeploymentDependentResource.OPTIMIZED_ARG) ? "/opt/keycloak/bin/kc.sh --verbose build && " : "";
```
Comment (vmuzikar) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java:150]: I'm probably doing something wrong but even if I do something like this with the current main:
```
kc.sh build --db=postgres
kc.sh start --http-enabled=true --hostname-strict=false --optimized
```
I get an error. So not sure why it worked like that in the Operator before.

**Review by vmuzikar — CHANGES_REQUESTED** [review]

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 2]
```diff
@@ -900,34 +911,21 @@ private static void checkChangesInBuildOptionsDuringAutoBuild(PrintWriter out) {
...
-            );
-        }
     }
 
     private static void optionChanged(StringBuilder options, String key, String oldValue, String newValue) {
         // the assumption here is that no build time options need mask handling
         boolean isIgnored = !key.startsWith(MicroProfileConfigProvider.NS_KEYCLOAK_PREFIX)
-                || key.startsWith(KC_PROVIDER_FILE_PREFIX) || key.equals(Configuration.KC_OPTIMIZED)
-                || key.equals(org.keycloak.common.util.Environment.PROFILE);
+                || key.startsWith(KC_PROVIDER_FILE_PREFIX) || isIgnoredPersistedOption(key);
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:928]: For the purposes of showing what has changing with autobuild we're omitting quarkus and kc.provider.file properties. For the build check we want to include both of those.

So we could move that check, but it would at least require creating yet another condition in the build check - one already exists for the kc.provider.file keys, so another one would be needed for quarkus keys.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java (hunk 1 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java:150]: Do you mean if you then do an import with the env setting for health-enabled after that it errors?

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 3]
```diff
@@ -444,5 +452,41 @@ public void warnDBRequired() {
...
+    
+    @Test
+    public void providerChanged() {
+        build("build", "--db=dev-file");
+
+        addPersistedConfigValues(Map.of(Picocli.KC_PROVIDER_FILE_PREFIX + "fake", "value"));
+
+        NonRunningPicocli nonRunningPicocli = pseudoLaunch("start", "--optimized");
+        assertEquals(CommandLine.ExitCode.USAGE, nonRunningPicocli.exitCode);
+        assertTrue(nonRunningPicocli.getErrString().contains("The following build time options have values that differ from what is persisted - the new values will NOT be used until another build is run: kc.provider.file.fake"));
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java]: Ok added a general message about the a provider jar changing.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java [hunk 4]
```diff
@@ -180,7 +179,7 @@ private List<EnvVar> assertWorkingRealmImport(Keycloak kc) {
         assertThat(container).isNotNull();
         var envvars = container.getEnv();
         assertThat(envvars.stream().filter(e -> e.getName().equals(getKeycloakOptionEnvVarName("cache"))).findAny().get().getValue()).isEqualTo("local");
-        assertThat(envvars.stream().filter(e -> e.getName().equals(getKeycloakOptionEnvVarName("health-enabled"))).findAny().get().getValue()).isEqualTo("false");
+        assertThat(envvars.stream().filter(e -> e.getName().equals(getKeycloakOptionEnvVarName("health-enabled"))).findAny().isEmpty());
```
[the remark this answers is not in the document]
Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java:182]: Added.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java (hunk 1 above)
Comment (vmuzikar) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java:150]: Never mind, I think I just got confused here. 🙈

However, I do still wonder what is the benefit of disabling health in import. It doesn't help perf too much.

**Review by vmuzikar — DISMISSED** [review]
Sorry for the late response.

LGTM. Added one minor question but approving regardless.

I'm also gonna rebase to see if tests still pass.

**Comment by vmuzikar** [comment]
@shawkins Rebase here complains about conflict. Can you please rebase manually?

**Comment by shawkins** [comment]
> @shawkins Rebase here complains about conflict. Can you please rebase manually?

Should be up-to-date now.

File: services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java [hunk 5]
```diff
@@ -130,4 +130,5 @@ public List<ProviderConfigProperty> getConfigProperties() {
         properties.addAll(super.getConfigProperties());
         return properties;
     }
+
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java:133]: Just a nitpick. This seems like an unintentional change caused by the rebase.

Comment (shawkins) [reply services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java]: Indeed, removed.

**Review by vmuzikar — APPROVED** [review]
Thank you, LGTM.
