### PR TITLE
fix: provide better error messages for list options

### LINKED ISSUE #25235: Unable to start after updating Docker container
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After updating the Docker container, Keycloak will no longer start only showing a completely useless message.

```
Changes detected in configuration. Updating the server image.

Invalid value for option 'kc.features': account-api, account2, account3, admin-api, admin-fine-grained-authz, admin2, authorization, ciba, client-policies, client-secret-rotation, declarative-user-profile, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, js-adapter, kerberos, linkedin-oauth, map-storage, par, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn. Expected values are: account-api, account2, account3, admin-api, admin-fine-grained-authz, admin2, authorization, ciba, client-policies, client-secret-rotation, declarative-user-profile, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, js-adapter, kerberos, linkedin-oauth, map-storage, par, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn. From ConfigSource KcEnvVarConfigSource
```

The list of features is exactly like documented in https://www.keycloak.org/server/containers
Also the "invalid value"exactly matches the "expected values".

Also nothing has changed in the configuration when updating.

### Version

quay.io/keycloak/keycloak@sha256:42c6c6cf9e7c4c06ff0fd5c0ad7293f0ca76cbb0a3439835b9f940cc1aa4e10f

### Expected behavior

Keycloak starts and is usable

### Actual behavior

Keycloak refuses to start with an error message that is neither true nor useful.

### How to Reproduce?

Run Keycloak as a Docker Stack:

```
version: "3"

volumes:
  database:
    driver: local

services:
  server:
    image: quay.io/keycloak/keycloak
    restart: always
    command: 'start --hostname-port=8070'
    ports:
      - 8070:8080
    environment:
      - TZ=Europe/Zurich
      - KC_HOSTNAME_ADMIN=sso.example.com
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpw
      - KC_HEALTH_ENABLED=false
      - KC_METRICS_ENABLED=false
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://database:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=secret
      - KC_PROXY=edge
      - KC_HOSTNAME_URL=https://sso.example.com/
      - KC_FIPS_MODE=disabled
      - KC_HTTP_ENABLED=true
      - KC_FEATURES=account-api, account2, account3, admin-api, admin-fine-grained-authz, admin2, authorization, ciba, client-policies, client-secret-rotation, declarative-user-profile, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, js-adapter, kerberos, linkedin-oauth, map-storage, par, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn

  database:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secretrootpw
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=keycloak
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u", "keycloak", "--password=secret"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/mysql
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
Clarifies the expectation of whitespace in list properties - that it's not expected. 

Attempted to consolidate the validation logic around all list options - did not try to tackle the spi logic yet. The biggest nuance is this requires all of the existing logic that simply converts the default to string, to use a special purpose function instead. Converting a list directly to string [x, y] is not compatible with the option format x,y.

Also removed the multioption - it's usage was not correct for features, we don't need the type conversion by picocli, and it's not needed for the other handling as the expected values are set (and even it's needed in the future, it can be done via expectedValues(enum class)).

closes: #25235

### CODE REVIEW

**Comment by shawkins** [comment]
I don't see how these changes are causing the failure, ShowConfigCommandTest is failing in such a way that the build flag is still set when show-config runs:
```
but 2024-01-08T22:04:04.6987326Z ShowConfigCommandTest ++ 	quarkus.launch.rebuild =  true (SysPropConfigSource)
```
when that happens show-config is omitting runtime properties - because that happens always now with the logic that's in the PropertyMappingInterceptor.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/ShowConfigCommandTest.java [hunk 1]
```diff
@@ -17,12 +17,12 @@
...
 
+import io.quarkus.test.junit.main.Launch;
+import io.quarkus.test.junit.main.LaunchResult;
+
 import org.junit.jupiter.api.Assertions;
 import org.junit.jupiter.api.Test;
 import org.keycloak.it.junit5.extension.CLITest;
-
-import io.quarkus.test.junit.main.Launch;
-import io.quarkus.test.junit.main.LaunchResult;
```
Comment (vmuzikar) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/ShowConfigCommandTest.java:25]: This change should not be needed but it's ok to keep as is from my PoV.

**Review by vmuzikar — DISMISSED** [review]
LGTM, seems like a nice improvement. Thanks @shawkins!

@mabartos @pedroigor Do you want to review too?

**Comment by vmuzikar** [comment]
Do we know which release has broken the list with spaces behaviour? We possibly should add some note to upgrading guide for that version.

**Comment by shawkins** [comment]
> Do we know which release has broken the list with spaces behaviour? We possibly should add some note to upgrading guide for that version.

I'm not sure. The user indicated some prior release did accept values with space, but I don't think that would have worked completely for some time - the PropertyMapperParameterConsumer since #9706 used a simple split. Likewise the profile logic has been using a simple split for features for years.

**Comment by vmuzikar** [comment]
@shawkins Right, ok, nothing to document then.

File: quarkus/config-api/src/main/java/org/keycloak/config/Option.java [hunk 2]
```diff
@@ -24,7 +25,7 @@ public Option(Class<T> type, String key, OptionCategory category, boolean hidden
         this.buildTime = buildTime;
         this.description = getDescriptionByCategorySupportLevel(description, category);
         this.defaultValue = defaultValue;
-        this.expectedValues = expectedValues;
+        this.expectedValues = expectedValues.get();
```
Comment (mabartos) [inline quarkus/config-api/src/main/java/org/keycloak/config/Option.java:28]: I'd choose only one approach, how to specify the expected values. AFAIK, the Supplier for the expected values was intended to use for lazy evaluation of the values based on environment/configuration; dynamic values. In this case, it doesn't have any effect as it's resolved in the constructor.

AFAIK, for all options we have in Keycloak, we use only static not changeable values. I think we can remove the Supplier as there's no need for it now.

@shawkins WDYT?

File: quarkus/config-api/src/main/java/org/keycloak/config/Option.java [hunk 3]
```diff
@@ -90,4 +91,14 @@ private static String getDescriptionByCategorySupportLevel(String description, O
 
         return description;
     }
+
+    public static String getDefaultValueString(Object value) {
```
Comment (mabartos) [inline quarkus/config-api/src/main/java/org/keycloak/config/Option.java:95]: Why does it have to be static and compute it always for these options? Most of the time, we have the PropertyMapper present, so we can avoid doing this:
```
Option.getDefaultValueString(mapper.getDefaultValue().orElse(null))
````
and do this instead:
```
mapper.getDefaultValueString()
```
Right?

@shawkins So we could have one class method for things where it's needed and one instance method, WDYT?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java [hunk 4]
```diff
@@ -296,15 +292,38 @@ public void validate(ConfigValue value) {
...
 
-    public void validateExpectedValues(ConfigValue value) {
-        if (PropertyMapperParameterConsumer.isExpectedValue(getExpectedValues(), value.getValue())) {
-            return;
+    public void validateExpectedValues(ConfigValue configValue, BiConsumer<ConfigValue, String> singleValidator) {
+        String value = configValue.getValue();
+
+        boolean multiValued = getOption().getType() == java.util.List.class;
+
+        for (String v : multiValued ? value.split(",") : new String[] { value }) {
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:300]: nit: I'd prefer to create separate field `var values=multiValued ? value.split(",") : new String[] { value }` and then only using `for (String v : values) {`. But it's only a matter of preferences, keep it as is if you want :))

**Review by mabartos — COMMENTED** [review]
@shawkins In general, LGTM. I've just added some comments below. Most of them are nitpicks and I don't want to block this PR because of them. They don't have to be resolved when we agree on it :))

File: quarkus/config-api/src/main/java/org/keycloak/config/Option.java (hunk 2 above)
Comment (shawkins) [reply quarkus/config-api/src/main/java/org/keycloak/config/Option.java:28]: > the Supplier for the expected values was intended to use for lazy evaluation

But the Supplier was typically backed by an innner class that held the list of items. The only case where that was not true was with the list of features.

> AFAIK, for all options we have in Keycloak, we use only static not changeable values. I think we can remove the Supplier as there's no need for it now.

I'm fine with that too, was just trying to minimize changes.

File: quarkus/config-api/src/main/java/org/keycloak/config/Option.java (hunk 3 above)
Comment (shawkins) [reply quarkus/config-api/src/main/java/org/keycloak/config/Option.java:95]: > @shawkins So we could have one class method for things where it's needed and one instance method, WDYT?

It's possible of course, this static method is for continuity with how the stringification happens currently and so that we don't end up with instance methods on both PropertyMapper and Option. I don't have a strong opinion though as an instance method was what I started with as well.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 4 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java]: Added the intermediate variable.

**Comment by shawkins** [comment]
@vmuzikar @mabartos made some updates based upon the reviews. The change to not use a supplier "only" touched two more classes, so I added that for now - it can be backed out if desired.

**Review by mabartos — APPROVED** [review]
@shawkins LGTM

I've just rerun Operator CI jobs as the failure was caused by an infra issue.

**Review by vmuzikar — APPROVED** [review]
@shawkins Thanks, LGTM!

**Comment by camilovietnam** [comment]
> Contributor

Not sure if this is relevant anymore after 6+ months, but the version that appears to broke the list is version 23.0.0. Here is my Dockerfile image built on 22.0.5: 

22 0 5 works

And it fails when I switch the base image to 23.0.0:

23 0 0 fails

**Comment by shawkins** [comment]
> Not sure if this is relevant anymore after 6+ months, but the version that appears to have broken the list is version 23.0.0. Here is my Dockerfile image built on 22.0.5:

It's not broken - it wasn't working correctly in versions older than 23 where the feature list was split on just "," so anything with a leading / trailing space did not match. This fix refined the version 23 behavior to provide an even clearer error message.
