### PR TITLE
Clear entries in remote caches and force events on the remote site

### LINKED ISSUE #29592: Remote caches and other site's caches might get out-of-sync when persistent sessions are used
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

With persistent sessions enabled, not all entries are in the embedded cache any more. The remote store can also have only a subset of the sessions in the embedded.

In some places we need to ensure that entries are removed from the remote store successfully, and that they are removed from the other site's caches as well. 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

No stale user sessions after for example a log out, or an updated session. 

### Actual behavior

A stale entry might be left in the other site's embedded cache or the other site's remote cache.

There might also be the possibility to have stale sessions in the remote cache when we're removing all sessions for a realm, or remove the sessions for a removed realm.

### How to Reproduce?

Functional test pending.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #29592

Handles the following cases: 

* When removing the sessions for a realm, and an entry is not in the current site's local cache cache, but in the current site's remote cache: 
  * We're iterating over all entries in the external cache and remove the external ones as well. 
* When removing the sessions for a realm, and an entry is in the other site's local cache or the other site's external cache:
  * We're sending an event to all cluster sites and run the cleanup commands there as well.  
* When removing or updating a single session, but that session isn't present in the external cache, so there wouldn't be an event to be observed on the other site: 
  * We're adding a dummy entry and then removing it to force an event on the other site to trigger a clear on the other site's caches (both external and internal)

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java [hunk 1]
```diff
@@ -537,40 +535,43 @@ public void removeLocalUserSessions(String realmId, boolean offline) {
 
         final AtomicInteger userSessionsSize = new AtomicInteger();
 
-        localCacheStoreIgnore
+        removeEntriesByRealm(realmId, localCacheStoreIgnore, userSessionsSize, localCache, localClientSessionCache);
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:538]: hopefully, realms are not removed very often :)

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java [hunk 2]
```diff
@@ -108,7 +114,24 @@ private <K, V extends SessionEntity> void runOnRemoteCache(TopologyInfo topology
 
         switch (operation) {
             case REMOVE:
-                remoteCache.remove(key);
+                if (Profile.isFeatureEnabled(Profile.Feature.PERSISTENT_USER_SESSIONS) &&
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java:117]: It is not required since removal is always replicated to the remote site.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java [hunk 3]
```diff
@@ -146,6 +169,18 @@ private <K, V extends SessionEntity> void replace(TopologyInfo topology, RemoteC
 
             VersionedValue<SessionEntityWrapper<V>> versioned = remoteCache.getWithMetadata(key);
             if (versioned == null) {
+                if (Profile.isFeatureEnabled(Profile.Feature.PERSISTENT_USER_SESSIONS) &&
+                    (remoteCache.getName().equals(USER_SESSION_CACHE_NAME)
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java:173]: You don't have to check the cache name and invoke remove in all the scenarios.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java [hunk 4]
```diff
@@ -146,6 +169,18 @@ private <K, V extends SessionEntity> void replace(TopologyInfo topology, RemoteC
...
+                     || remoteCache.getName().equals(CLIENT_SESSION_CACHE_NAME)
+                     || remoteCache.getName().equals(OFFLINE_USER_SESSION_CACHE_NAME)
+                     || remoteCache.getName().equals(OFFLINE_CLIENT_SESSION_CACHE_NAME))) {
+                    logger.debugf("No existing entry for %s in the remote cache to remove, might have been evicted.", key);
+                    // force a remove to trigger an event on the remote DC to clear those
+                    remoteCache.put(key, new SessionEntityWrapper<>(null));
+                    if (remoteCache.withFlags(Flag.FORCE_RETURN_VALUE).remove(key) != null) {
+                        logger.warnf("Unable to trigger the remove in the remote cache %s for key %s", remoteCache.getName(), key);
+                    };
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java:182]: `remoteCache.remove` is enough.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionListener.java [hunk 5]
```diff
@@ -130,6 +130,10 @@ protected void createRemoteEntityInCache(K key) {
 
 
         V remoteSession = remoteSessionVersioned.getValue().getEntity();
+        if (remoteSession == null) {
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionListener.java:133]: Not required anymore.

**Review by pruivo — CHANGES_REQUESTED** [review]
There is another place: `org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction#replace()`
If the `computeIfPresent` returns `null`, you should invoke `remove` to ensure the backup owners do not keep any stale value.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java (hunk 2 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java:117]: Resolved in next commit

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java (hunk 3 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java:173]: IMHO I need to check the cache name, as this is also used for login failures.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java (hunk 4 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java:182]: resolved in next commit

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionListener.java (hunk 5 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionListener.java:133]: resolved in next commit

**Comment by ahus1** [comment]
@pruivo - pushed one commit to solve some of your comments.

I'm not sure that `InfinispanChangelogBasedTransaction#replace()` is needed: You describe that I should call `remove()` to clear the entries of backup owners. 

First, this is all about the embedded caches.

This code is used in the non-persistent sessions only, and for those there should always be all entries in memory, until they eventually expire. 

For persistent sessions, we only have one owner as ensured by the CacheManagerFactory, and therefore it won't be an issue IMHO. 

Let me know if I missed something. Thanks!

**Comment by pruivo** [comment]
> @pruivo - pushed one commit to solve some of your comments.
> 
> I'm not sure that `InfinispanChangelogBasedTransaction#replace()` is needed: You describe that I should call `remove()` to clear the entries of backup owners.
> 
> First, this is all about the embedded caches.
> 
> This code is used in the non-persistent sessions only, and for those there should always be all entries in memory, until they eventually expire.
> 
> For persistent sessions, we only have one owner as ensured by the CacheManagerFactory, and therefore it won't be an issue IMHO.
> 
> Let me know if I missed something. Thanks!

@ahus1 you're right. I forgot we are setting `owners=1`.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java (hunk 1 above)
Comment (mhajas) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:538]: I am not following why we iterate over entries in `localCacheStoreIgnore` but remove from `localCache`. Since each KC node is doing it, wouldn't it be enough to iterate over `localCache` only?

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java [hunk 6]
```diff
@@ -537,40 +535,43 @@ public void removeLocalUserSessions(String realmId, boolean offline) {
...
+
+        // iterate over the remote entries as well to ensure they are purged
+        removeEntriesByRealm(realmId, getCache(offline), userSessionsSize, getCache(offline), getClientSessionCache(offline));
```
Comment (mhajas) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:541]: The previous line removes all sessions from the local caches for the realm. This line attempts to remove also remote sessions. 

Would it make sense to use `RemoteCache` directly for remote store removal instead of using `getCache()`. Also, should we add `SKIP_LISTENER_NOTIFICATION` flag to avoid processing of removals by each Keycloak node again? We know the local caches are already clean of sessions for the realm so we don't need to distribute these events. 

If I remember correctly `SKIP_LISTENER_NOTIFICATION` still sends the notification to the other site in case of CrossDC setups but it would still make the number of sent events lower.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java (hunk 1 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:538]: I suppose it is trying to do the following: 

* Get me all entries, but don't ask the remote store for the entries as it would be expensive
* If I then remote items, remove them als from the store which is remote cache

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java (hunk 6 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java]: I've pushed one more commit with the changes you suggested. As the local caches and the remote caches have different interfaces, I needed to duplicate the method to make it work. Please have a look if it now looks better to you.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java (hunk 1 above)
Comment (mhajas) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:538]: > Get me all entries, but don't ask the remote store for the entries as it would be expensive

Yes that is correct, however, the event is processed by each Keycloak node and this means that each ID is processed also by nodes that do not own the entry which results in 3 removals of the same ID (in 3 KC node cluster). Then we use `localCache.removeAsync` which succeeds only on nodes that own the entry as we use the flag `CACHE_MODE_LOCAL` all other nodes do nothing.

I just realized the reason why we are doing it this way may be that we need to remove also client sessions which is making things a little complicated as client sessions may be owned by other nodes than user sessions and we also use `CACHE_MODE_LOCAL` for removal. I am thinking about a few things here:
1. What happens if some n1 owns `clientSession1` and n2 owns `userSession1`. Is it possible that n2 removes `userSession1`, without removing `clientSession1` before n1 iterates over `userSession1` which would mean `n1` never get to `userSession1` and hence never removes `clientSession1`?
2. I am not sure it makes sense to use `CACHE_MODE_LOCAL` for client sessions. Maybe we can use `SKIP_CACHE_STORE` and we can execute the removal only on primary owners for a user session.
3. Also, maybe we don't need to be afraid of keeping client sessions in there since they will be evicted eventually and they cannot be used without the corresponding user session. WDYT? 

> If I then remove items, remove them als from the store which is remote cache

If we talk only about this line, without the line 541, I don't see where we remove also from the remote cache. We are using `CACHE_MODE_LOCAL` for all removals which remove only from the current node if I am not mistaken.

Comment (mhajas) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java:538]: We discussed this in a meeting and we decided not to act on this comment at the moment as it would be just a performance optimization. The important part of this PR is to fix the possible issue when the remote store contains a different set of user sessions which is addressed by iterating also over the remote store. 

We can continue with the performance optimization with a lower priority later.

**Review by mhajas — APPROVED** [review]
Thank you for the fix @ahus1
