### PR TITLE
User Profile: If required roles ('user') and reqired scopes are set, …

### LINKED ISSUE #25475: User Profile: If required roles ("user") and reqired scopes are set, the required scopes have no effect
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

In the following user profile configuration for firstName, a required scope "nameScope" was added.

Required action "Verify Profile" is enabled.

Then the attribute is requested to be filled as required on login, without nameScope being present:

The Bug applies to firstName and lastName or any additional custom attributes.

### Version

22.0.5 and nightly

### Expected behavior

The attribute should be optional, not required. It should become required only, of the configured scope is requested.

### Actual behavior

The attribute is marked required. User can't proceed without providing a value.

### How to Reproduce?

* Enable required action Verify Profile
* Enable User Profile
* Add a required scope for firstName or lastName

User Profile snippet for firstName, with required.roles and required.scopes set:
```
...
    {
      "name": "firstName",
      "displayName": "${firstName}",
      "validations": {
        "person-name-prohibited-characters": {},
        "length": {
          "min": "0",
          "max": "255"
        }
      },
      "annotations": {},
      "required": {
        "roles": [
          "admin",
          "user"
        ],
        "scopes": [
          "nameScope"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      }
    },
...
```

### Anything else?

It should be documented, that required required role "User" AND configured required scope must be present for the filed to become required. With this Bug, the field becomes required as soon as the role "User" is matching.

The expected behaviour can only be achieved when removing required roles in the JSON editor:
```
      "required": {
        "roles": [],
        "scopes": [
          "nameScope"
        ]
      },
```
Then a missing nameScope results in an optional firstName field as expected.
But then required role and required scope can't be combined.

This workaround can't be  achieved in the UI, which displays the state like this:

Additional suggestion for the UI: The required roles should be represented by two checkboxes one for "Required by admin" and one for "Required by user". This way the UI represents what is also configurable at the JSON editor level.

### PR DESCRIPTION
**Pull request by mposolda**
…the required scopes have no effect

closes #25475

Description of the change:
 - When setting `Required when` is selected as `Always`, then only the "role" presence is sufficient to make this attribute REQUIRED
 - When setting `Required when` is selected as `Scopes are requested` with some scopes being present, then the "scope" is required together with "role" to this attribute being required. This effectively means that for the contexts without scopes (admin console, account console), the specified attribute won't be required as the requested scopes are not present
 - In relation to this, I've added validation that if some required scopes are configured, then also role `user` should be configured. Otherwise the attributes will never be required as when role `user` is not used, the `scopes` selector is never applied. So this is just some prevention against misconfiguration

### CODE REVIEW

**Comment by sschu** [comment]
Thanks a lot for this @mposolda ! Can we also have this backported to KC23? It is currently a blocker for us for rolling out KC23.

**Comment by mposolda** [comment]
> Thanks a lot for this @mposolda ! Can we also have this backported to KC23? It is currently a blocker for us for rolling out KC23.

Yes, we discussed it with @pedroigor to possibly backport to Keycloak 23

File: services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java [hunk 1]
```diff
@@ -192,8 +192,15 @@ private static void validateAttribute(KeycloakSession session, UPAttribute attri
...
         if (attributeConfig.getRequired() != null) {
-            validateRoles(attributeConfig.getRequired().getRoles(), "required.roles", errors, attributeName);
-            validateScopes(attributeConfig.getRequired().getScopes(), "required.scopes", attributeName, errors, session);
+            Set<String> roles = attributeConfig.getRequired().getRoles();
+            Set<String> scopes = attributeConfig.getRequired().getScopes();
+            validateRoles(roles, "required.roles", errors, attributeName);
+            validateScopes(scopes, "required.scopes", attributeName, errors, session);
+
+            // Role "user" required when some scopes are configured
+            if (scopes != null && !scopes.isEmpty() && (roles == null || !roles.contains(ROLE_USER))) {
```
Comment (jbman) [inline services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java:201]: Configuration validation is nice, but will make configurations with empty roles but scopes invalid while this was the combination which worked before.
Migration instructions then need a note to update from 
"required-scopes": [] 
to 
"required-scopes": ["user]

**Comment by mposolda** [comment]
@pedroigor @jbman @sschu Updated the behaviour to be compatible with previous version. So:

- In case that `required` attribute is configured without anything (JSON configuration like `required: {}`), then attribute is always required. Same behaviour like before. Note it is not possible to configure this in the admin console UI, as UI always require to select some role or both.

- In case that only some "roles" are configured, but not "scopes", then only roles are used to detect requirement. Same behaviour like before.

- If only `scopes` are configured, but not roles, then only scopes are used to detect requirement. Same behaviour like before this PR.

- If both `roles` and `scopes` are configured, it is the only case when there is the change in behaviour in this PR. Now it works like:
  - For auth flows contexts (everything with the exception of admin console and account console), the `scope` parameter can be evaluated. Hence it is both `roles` and `scopes` evaluted and both must match.
  - For scope-less contexts (contexts where `scope` parameter is not available), it works like:
    - For admin console, the `scope` requirement is ignored and hence attribute is REQUIRED as long as `admin` role is presented in the configuration. This allows user-profile configuration to always require some attribute for administrators, but for regular users, make the attribute REQUIRED based on the `scope` present. I am not 100% sure about this one as `scope` requirement is not met strictly speaking, so wonder if we should always mark attribute as non-required for administrators?
    - For account console, the attribute is never required as scope requirement is never met here. Was thinking about ignoring `scope` requirement as well, but did not made much sense to me. As for example when attribute `test` is configured with required scope `phone`, but this scope is not present during authentication, then registration screen or update-profile screen will show attribute `test` as not required, but account console will show `test` as always required. So here just assuming that account console will never require attributes when scopes are configured.

**Comment by pedroigor** [comment]
@mposolda I think what we are missing is taking into account the authenticated client session (not only the authentication session) when selecting an attribute or checking if it should be required.

For instance, in your case when accessing the account console we should make the attribute required whenever the `phone` scope is available from the authentication or client session notes. Together with the selector, which should also take into account both authentication and client session notes, we can even hide/show the attribute depending on the scopes granted to a particular client session.

Perhaps this makes more clear the usage of the required and the selector settings.

Wdyt?

**Comment by mposolda** [comment]
@pedroigor Yeah, we can. Was also thinking about something like this. However it raises some additional questions/concerns:

- Do we want to evaluate with client session scopes for both account console (context `ACCOUNT`) and admin console (context `USER_API`) ? IMO evaluate both is fine?

- This would mean that our account console (or admin console) will effectively use only "default" client scopes of clients `account-console` (or `security-admin-console`). As when you login to our account console (or admin console), there is no easy way to add additional optional client scopes. The only option is to manually edit `scope` parameter in the browser URL once the request to OIDC authentication is sent, but that's not very good for UX. But perhaps this behaviour is ok?

- Do we want to update behaviour for both "enabled scopes" and for "required scopes" ? Currently scopes evaluation is ignored for "enabled scopes" and both admin console and account console always show all attributes even if it doesn't match the `enabled scopes` filter. IMO this behaviour is fine typically you want to see all attributes in account console (or admin console)? So not 100% sure if change the behaviour just for "required scopes" ?

**Comment by jbman** [comment]
The main use case of our customers have for `required.scopes` configuration is that clients are are in control which additional data is  requested from the user after login.

@pedroigor:
Applying the required scope settings also to the admin console seems like not so useful. As @mposolda said, you then need to add client scopes to the security-admin-console for the main use case above, if you want the attribute as required for an admin, too.

I also don't see how it would solve the "premium" scope use case. To support this case, I would like to suggest a different configuration feature. An attribute should be only visible or required if the viewing admin user has a specific role. In the attribute definition you would specify `enabled.adminRoles` and `required.adminRoles`. 

For this fix I think it is fine that `required.scopes` are only evaluated in the context of a user not in context of an admin.

**Comment by pedroigor** [comment]
@jbman Yeah, and we have an issue tracking how attributes should behave based on the roles and groups set to users. Please, see the issues from this epic https://github.com/keycloak/keycloak/issues/25542.

I also agree it perhaps does not make sense much for the admin console, at least for now. However, I think it makes sense for the account console so that when the client is asking for a scope to access the account (even though it has a UX issue) making sure the scope is also resolved from the client session (previously granted) will make the attribute in the account console more aligned with your settings so that it would be required in both update profile and the account console itself.

But yeah, this is not a blocker for the fix we are doing here.

**Comment by mposolda** [comment]
Updated PR per the discussion with @pedroigor .

Now required scopes are evaluted during authentication flow. For the contexts without scope (So admin console and account console), the attributes are not required in case they have scope based selector.

It is definitely not perfect behaviour, but hopefully sufficient for now. We have follow-up issues for more flexibility:
- Configuration based on user's roles or groups as pointed by @pedroigor
- Context based configuration - https://github.com/keycloak/keycloak/issues/25575 . This may allow lots of flexibility. Like for example specify that attribute `foo` should be always required in the "admin" context and always required during "registration" context, but during "update-profile" context required just with scope `foo` present etc.
- Scopes evaluated from client session, which means that also "admin console" and "account console" will be able to more properly rely on scope based selectors. Perhaps another follow-up issue, which we don't yet have, but can consider for the future.

**Review by pedroigor — APPROVED** [review]
