### PR TITLE
Stabilizing the FipsDistTest

### LINKED ISSUE #26374: Workflow failure: Quarkus IT - FipsDistTest#testUnsupportedHttpsPkcs12KeyStoreInStrictMode
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

[Quarkus IT (ubuntu-latest, zip)](https://github.com/keycloak/keycloak/actions/runs/7581549792/job/20649723076#logs)

`2024-01-19 09:25:26,452 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to //realms/master/ failed, error id: ff61811e-0fa3-4159-a6af-85130a71b2a8-93: java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.instance(java.lang.Class, java.lang.annotation.Annotation[])" because the return value of "io.quarkus.arc.Arc.container()" is null`

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Pepo48**
* increased the timeout to let Keycloak stop

Closes #26374

### CODE REVIEW

**Review by miquelsi — APPROVED** [review]

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java [hunk 1]
```diff
@@ -340,7 +340,7 @@ private void threadDump() {
         try {
             ProcessBuilder builder = new ProcessBuilder("kill", "-3", String.valueOf(keycloak.pid()));
             Process p = builder.start();
-            p.onExit().get(getStartTimeout(), TimeUnit.MILLISECONDS);
+            p.onExit().get(3, TimeUnit.MINUTES);
```
Comment (ahus1) [inline quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java:343]: This is IMHO missing a comment why you whose 3 minutes here. Otherwise people will wonder in the future why this is here. 

Looking at `application.properties`, the transaction timeout is 300 seconds, which is 5 minutes. 

Waiting for 3 minutes here, and (given your comment in the issue) waiting for 2 minutes at another place, would add up to 5 minutes, which matches the 300 seconds. Maybe it would be good to add one more minute to he on the safe side. Whatever your reasoning is here, state the "why" for those minutes you choose here in a comment.

**Review by ahus1 — DISMISSED** [review]
I'd like to see a comment in the code how the 3 minutes are determined.

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java (hunk 1 above)
Comment (Pepo48) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]: Here I wrongly increased the timeout on the kill command while we actually need to increase the stop command. The reason is the mentioned Narayana bug, which makes the process hang longer. I already made the change, I also added a comment that the timeout can be reverted once the bug is addressed.

Speaking about the timeout length, 180 seconds should be just enough. From the perspective of other tests, the used .waitFor() will continue as soon as the process terminates. This way the other tests shouldn't be influenced.

Comment (ahus1) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]: @Pepo48 - I see that the code has changed, but I'd still like to see a comment in the code detailing the "why" you chose 180 seconds so our future selfs and other will know. 

I someone wants to comment why such a comment is not necessary, I'm open to hear that.

Comment (vmuzikar) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]: This is in any case just a workaround that should go away once https://github.com/jbosstm/narayana/pull/2201 is resolved.

Couldn't find an issue to remove the workaround. @shawkins Did we create one, I'm not sure. :)

Comment (shawkins) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]: > Couldn't find an issue to remove the workaround. @shawkins Did we create one, I'm not sure. :)

Not yet, just the comments in the code about the upstream issue.

Comment (vmuzikar) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]: Created #26454

**Review by shawkins — APPROVED** [review]
Looks good to me. If test runtimes become an issue we can put in more proactive destroyForcibly calls.

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java (hunk 1 above)
Comment (vmuzikar) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]: @ahus1 As far as I understand, the 180 seconds is just an "educated guess" (as with anything when dealing with async stuff in testsuite). Do you want to add a comment with that? :)

**Review by vmuzikar — APPROVED** [review]

**Review by ahus1 — COMMENTED** [review]
Going "neutral" after previous discussion.

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java (hunk 1 above)
Comment (ahus1) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]: I was hoping something different than an educated guess, let's leave it as is.
