### PR TITLE
Check for non-ascii local part on emails depending on SMTP configuration

### LINKED ISSUE #41994: Check for non-ascii local part on emails depending on SMTP configuration
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

This is a follow-up for #41023. With the changes done for that issue now the SMTP configuration rejects sending emails to addresses that have non-ascii in the local part if the SMTP configuration does not allow UTF-8. This is OK because we are preventing sending messages to incorrect addresses but we have decided to add this validation to the built-in UP email validator. This way the server will also reject the registration of emails that cannot be used by the SMTP server.

We have managed two ideas:

1. Just use the SMTP configuration to control the email and allow non-ascii if SMTP is not configured or allows UTF-8.
2. Add an option in the validator. This option is independent to the SMTP configuration in the realm.

For the moment I will use the option 1 for the PR but this can change after reviews.

### Version

999

### Regression

- [ ] The issue is a regression

### Expected behavior

The email with non-ascii chars in the local part should be rejected if the SMTP server configuration does not allow sending them.

### Actual behavior

The email is accepted.

### How to Reproduce?

See description.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #41994

Adding the checking for non-ascii in the email local part if the realm is configured to send emails to an SMTP without `allowutf8`. Finally it was talked to use the direct option with no option in the validator. 

@ahus1 @pedroigor @mposolda @stianst For your information.

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

File: server-spi-private/src/main/java/org/keycloak/validate/validators/EmailValidator.java [hunk 1]
```diff
@@ -61,6 +64,29 @@ protected void doValidate(String value, String inputHint, ValidationContext cont
...
+        }
+
+        final KeycloakSession session = context.getSession();
+        if (session == null) {
+            return;
+        }
+
+        final RealmModel realm = session.getContext().getRealm();
+        if (realm == null || realm.getSmtpConfig() == null || realm.getSmtpConfig().isEmpty()
+                || "true".equals(realm.getSmtpConfig().get("allowutf8"))) {
```
Comment (ahus1) [inline server-spi-private/src/main/java/org/keycloak/validate/validators/EmailValidator.java]: Please introduce a constant for `allowutf8` in all places.

File: themes/src/main/resources/theme/base/account/messages/messages_en.properties [hunk 2]
```diff
@@ -386,3 +386,4 @@ error-invalid-date=Invalid date.
 error-user-attribute-read-only=The field {0} is read only.
 error-username-invalid-character=Username contains invalid character.
 error-person-name-invalid-character=Name contains invalid character.
+error-non-ascii-local-part-email=Local part of the address ''{1}'' must contain only ASCII characters.
```
Comment (ahus1) [inline themes/src/main/resources/theme/base/account/messages/messages_en.properties]: In the past there have been attacks to reflect user input in the error messages, which lead to XSS problems. While I'm sure we're encoding the output correctly, I'd rather remove repeating the user input in the error message. This would then apply to the message and also where we add the message parameter.

```suggestion
error-non-ascii-local-part-email=Local part of the address must contain only ASCII characters.
```

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for the pull request. See below for some suggested changes.

File: server-spi-private/src/main/java/org/keycloak/validate/validators/EmailValidator.java (hunk 1 above)
Comment (rmartinc) [reply server-spi-private/src/main/java/org/keycloak/validate/validators/EmailValidator.java]: I created the constant in the `EmailSenderProvider` class.

File: themes/src/main/resources/theme/base/account/messages/messages_en.properties (hunk 2 above)
Comment (rmartinc) [reply themes/src/main/resources/theme/base/account/messages/messages_en.properties]: Done!

**Review by ahus1 — APPROVED** [review]
