### PR TITLE
fix: deprecating the default db value in production mode

### LINKED ISSUE #23805: H2 Database should be opt-in and well-documented
### Description

Keycloak includes an H2 in-memory database for development purposes. The Keycloak image with either no configurations or improperly configured will default to the H2 database. There is little documentation on the behavior of Keycloak on H2, aside from the cryptic warning not to use the default configuration in production.

This becomes problematic as a scan of open ports on the Keycloak image image will reveal constantly opened ports in the 30000+ range. This behavior exists in version `quay.io/keycloak/keycloak:18.0.2` and `quay.io/keycloak/keycloak:22.0.1`.  

The following is naive scan from a security pipeline:
```
73[✓] Discovered port 41801: open
74[•] Service: unknown (confidence level 3/10)
75[•] Server type: unknown (version unknown)
76[✓] 0 web service(s) identified for scanning
77[!] 1 warning(s) for port 41801
78 ‣  Port is NOT exposed by Dockerfile but has state: open
```
As you can imagine, this raised major red flags, and it was with a lot of effort that we were able to track down the source. Searching the usual channels and asking in Slack leads to nowhere about this behavior. 

In the end, the documentation about using H2 in Keycloak is all over the place. The main takeaway we've gotten is that H2 is unsupported and is only meant for dev purposes. It is not clear this the default unless the container is restarted and the in-memory database is wiped, and it is correctly deduced that H2 was in use.

So as a part of docs, there is an need for detailed and consolidated documentation that outlines the behavior of Keycloak when employing the H2 in-memory database. This should include specifics on port usage, potential security implications, and the consequences of using H2 in a production environment. If H2 is truly intended solely for development and unsupported in production, it should not be the default behavior. Users should be explicitly informed about this default setting and the risks associated with it, ensuring they are not inadvertently deploying insecure configurations.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #23805

This keeps the changes from https://github.com/keycloak/keycloak/pull/33760 but switches to using a deprecation instead.

### CODE REVIEW

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 1]
```diff
@@ -88,6 +91,20 @@ public void start() {
...
+            config = createConfig();
+        }
+
+        @Override
+        public void validateConfig(List<String> cliArgs, AbstractCommand abstractCommand) {
+            if (abstractCommand.getName().equals(Build.NAME)) {
+                //PersistedConfigSource.getInstance().getConfigValueProperties().clear();
+            }
+            super.validateConfig(cliArgs, abstractCommand);
+        }
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:106]: What do you want to do here?

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 2]
```diff
@@ -325,20 +342,29 @@ public void testReaugFromProdToDevExport() {
...
     }
 
+    @Test
+    public void testDBRequiredAutoBuild() {
+        build("build", "--db=dev-file");
+
+        Environment.setRebuildCheck(); // will be reset by the system properties logic
+        NonRunningPicocli nonRunningPicocli = pseudoLaunch("export", "--file=file");
+        assertEquals(CommandLine.ExitCode.OK, nonRunningPicocli.exitCode);
+    }
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:360]: What's the purpose of this test case?

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java [hunk 3]
```diff
@@ -139,15 +139,25 @@ void failIfOptimizedUsedForFirstStartup(CLIResult cliResult) {
...
     @Test
-    @Launch({ "start", "--http-enabled=true" })
+    @Launch({ "start", "--db=dev-file", "--http-enabled=true" })
     void failNoHostnameNotSet(CLIResult cliResult) {
         assertTrue(cliResult.getErrorOutput().contains("ERROR: hostname is not configured; either configure hostname, or set hostname-strict to false"),
                 () -> "The Output:\n" + cliResult.getOutput() + "doesn't contains the expected string.");
     }
 
+    @RawDistOnly(reason = "Containers are immutable")
+    void testFastStartOptimized(KeycloakDistribution dist) {
```
Comment (mabartos) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java:149]: Missing `@Test` annotation.

We don't have tests for fast optimized start? Or is it really necessary to have it here?

**Review by mabartos — COMMENTED** [review]
@shawkins Thanks for this PR. In general, LGTM and I like this approach more to have some "migration" time for users and not strictly requiring the `--db` option.

I created a PR to your solution a small typo fix and some minor improvements. Include it there if it suits to you - https://github.com/shawkins/keycloak/pull/16

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:360]: It's no longer valid for the deprecation scenario.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java (hunk 3 above)
Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java:149]: It's no longer necessary here, there's coverage in PicocliTest - there were other refactorings so we now exercise fast start in a unit testable manner.

**Comment by shawkins** [comment]
> @shawkins Thanks for this PR. In general, LGTM and I like this approach more to have some "migration" time for users and not strictly requiring the `--db` option.
> 
> I created a PR to your solution a small typo fix and some minor improvements. Include it there if it suits to you - [shawkins#16](https://github.com/shawkins/keycloak/pull/16)

Thanks @mabartos 

This pr has unfortunatelybeen around for so long that there's been an accumulation of unnecessary changes. I've incorporated you pr and will make additional updates based upon your review comments.

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:106]: That's no longer necessary, I had first placed some changes there but then realized the Build command should not be running validation with the persisted config source - that means it will use any persisted values effectively as defaults.

**Review by mabartos — DISMISSED** [review]
@shawkins Thanks, nice job! 

@vmuzikar Do you wanna look at it as well? Do you agree with the deprecation for the prod profile?

**Comment by vmuzikar** [comment]
I'll try to take a look today.

File: docs/documentation/upgrading/topics/changes/changes-26_1_0.adoc [hunk 4]
```diff
@@ -24,6 +24,10 @@ Previously, the three mappers (`Client Id`, `Client Host` and `Client IP Address
 
 This lists functionality that continues to work as before in this release, but will be removed in a future major release.
 
+=== Default `db` option for production deprecated.
+
+The default value for the `db` option (`dev-file`) is now deprecated in production profiles. For `build` or non-optimized `start` and non-server commands `import`, `export`, or `bootstrap-admin` in the production profile, a value should be explicitly supplied. This is to prevent the unintentional usage of the `dev-file` (H2) database in a production environment, which is typically indicative of a misconfiguration.
```
Comment (vmuzikar) [inline docs/documentation/upgrading/topics/changes/changes-26_1_0.adoc:29]: Maybe we could make it a bit more explicit what the intentions here are.
```suggestion
In previous releases, the `db` option defaulted to `dev-file` both in production (`start`) and development (`start-dev`) modes while `dev-file` has never been supported in the production mode. In this release, we have deprecated this behaviour and in some future release the `db` option won't default to `dev-file` in production mode. For `build` or non-optimized `start` and non-server commands `import`, `export`, or `bootstrap-admin` in the production profile, a value should be explicitly supplied. This is to prevent the unintentional usage of the `dev-file` (H2) database in a production environment, which is typically indicative of a misconfiguration.
```

File: quarkus/runtime/src/main/resources/META-INF/keycloak.conf [hunk 5]
```diff
@@ -1,5 +1,5 @@
 # Default and non-production grade database vendor
-db=dev-file
+%dev.db=dev-file
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/resources/META-INF/keycloak.conf:2]: We do need to make this change now, do we? We're not changing the behaviour yet.

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 6]
```diff
@@ -325,20 +335,30 @@ public void testReaugFromProdToDevExport() {
...
+        build("build", "--db=dev-file");
 
         Environment.setRebuildCheck(); // will be reset by the system properties logic
-        NonRunningPicocli nonRunningPicocli = pseudoLaunch("export", "--file=file");
+        NonRunningPicocli nonRunningPicocli = pseudoLaunch("export", "--db=dev-file", "--file=file");
         assertEquals(CommandLine.ExitCode.OK, nonRunningPicocli.exitCode);
         assertFalse(nonRunningPicocli.reaug);
     }
 
+    @Ignore("Not valid until db is required for production")
```
Comment (vmuzikar) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:346]: Can you please mention a GHI that tracks the breaking change we'll do in 27?

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 7]
```diff
@@ -386,4 +406,18 @@ public void fastStartOptimizedSucceeds() {
         assertEquals(Integer.MAX_VALUE, nonRunningPicocli.exitCode); // "running" state
     }
 
+    @Test
+    public void warnDBRequired() {
+        // dev profile has a default
+        NonRunningPicocli nonRunningPicocli = pseudoLaunch("start-dev");
+        assertEquals(CommandLine.ExitCode.OK, nonRunningPicocli.exitCode);
```
Comment (vmuzikar) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:413]: Should we also assert the warning is not present in this case?

**Comment by vmuzikar** [comment]
@shawkins Overall LGTM. Could you please create a follow-up to make the breaking change in 27. Might  be good to add some pointers to the code base what exactly needs to be done (like unignoring the new test).

File: quarkus/runtime/src/main/resources/META-INF/keycloak.conf (hunk 5 above)
Comment (shawkins) [reply quarkus/runtime/src/main/resources/META-INF/keycloak.conf:2]: We don't have to make this change, but it's effectively redundant to have db=dev-file here and as the default on the option. Since we're making other changes in preparation for the breaking change, I would make this one as well - that will leave just updating the option later.

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 6 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:346]: Captured https://github.com/keycloak/keycloak/issues/35816 - put it as initially targetting 27.

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 7 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:413]: Yes, added now.

File: quarkus/runtime/src/main/resources/META-INF/keycloak.conf (hunk 5 above)
Comment (vmuzikar) [reply quarkus/runtime/src/main/resources/META-INF/keycloak.conf:2]: Ok, let's keep it then.

**Comment by mabartos** [comment]
After the polishing, I'm ok with these changes.

**Review by mabartos — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks!
