### PR TITLE
Fix error handling for duplicate group names and CSS selector update

### LINKED ISSUE #34605: Error on testsuite "group_test" on Cypress
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

There is an error on the test "Duplicate group" on the "group_test" testsuite

https://github.com/keycloak/keycloak/actions/runs/11655914950/job/32451389621
https://github.com/keycloak/keycloak/actions/runs/11638165707/job/32412651345
https://github.com/keycloak/keycloak/actions/runs/11621918237/job/32366664637

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Pass

### Actual behavior

Fails

### How to Reproduce?

Seems flaky

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by charley-geoffroy**
CI was failing because of the error handling for duplicate group names. This PR fixes the error handling and updates the CSS selector for the group name input field.

## How to test it : 

Once you have a Keycloack UP run : 

```bash 
pnpm cypress run --spec "cypress/e2e/group_test.spec.ts"
```

You should see this result:

duplicatedGroup

Closes #34605

### CODE REVIEW

**Review by edewit — DISMISSED** [review]

**Comment by charley04310** [comment]
Hi @edewit ,

I wanted to check in and see if you’re still expecting any changes from me on this PR. I'm new to open source and noticed that the CI failed, but it doesn’t seem to be related to my changes. Please let me know if there's anything else you’d like me to update!

Thank you!

**Comment by edewit** [comment]
@charley04310 nope, all good just restarted the CI it sometimes needs a nudge unfortunately

File: js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default class ListingPage extends CommonElements {
   #deleteUserButton = "delete-user-btn";
   #emptyListImg = '[role="tabpanel"]:not([hidden]) [data-testid="empty-state"]';
   #emptyState = "empty-state";
-  #itemRowDrpDwn = ".pf-v5-c-table__action button";
+  #itemRowDrpDwn = ".pf-v5-c-menu-toggle";
```
Comment (edewit) [inline js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts:36]: This change makes the client_scope test fail

**Review by edewit — APPROVED** [review]
