### PR TITLE
[14210] BouncyCastleProvider: Tests failing due to cast error

### LINKED ISSUE #14210: EAP Adapter tests failing in Test Pipelines with ClassCastException in BCProvider
### Describe the bug

Currently EAP Adaptertests  [org.keycloak.testsuite.adapter.servlet.DemoFilterServletAdapterTest] are failing in the testpipelines with error message: 

https://test-pipeline/job/universal-test-pipeline-adapters/1267/testReport

### Version

999-Snapshot

### Expected behavior

Tests should run without any error 

### Actual behavior

`22:05:41,335 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /customer-portal/: java.util.ServiceConfigurationError: org.keycloak.common.crypto.CryptoProvider: Provider org.keycloak.crypto.def.DefaultCryptoProvider could not be instantiated
`

`Caused by: java.lang.ClassCastException: class org.bouncycastle.jce.provider.BouncyCastleProvider cannot be cast to class org.bouncycastle.jce.provider.BouncyCastleProvider (org.bouncycastle.jce.provider.BouncyCastleProvider is in unnamed module of loader 'deployment.token-min-ttl.war' @4fc03346; org.bouncycastle.jce.provider.BouncyCastleProvider is in unnamed module of loader 'deployment.customer-portal.war' @52038a4a)`

### How to Reproduce?

mvn -f keycloak/testsuite/integration-arquillian/tests/base/pom.xml clean install -Djs.browser=chrome -B -Pauth-server-quarkus -Dkeycloak.logging.level=DEBUG  -Papp-server-eap -Dfuse63.version=6.3.0.redhat-495 -Dapp.server.java.home=/qa/tools/opt/amd64/jdk11_last -Dtest=DemoServletsAdapterTest#testCallURLWithAccessToken

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nehachopra27**
Closes #14210 

Adapter Tests are failing due to following cast error

`Caused by: java.lang.ClassCastException: class org.bouncycastle.jce.provider.BouncyCastleProvider cannot be cast to class org.bouncycastle.jce.provider.BouncyCastleProvider (org.bouncycastle.jce.provider.BouncyCastleProvider is in unnamed module of loader 'deployment.token-min-ttl.war' @4fc03346; org.bouncycastle.jce.provider.BouncyCastleProvider is in unnamed module of loader 'deployment.customer-portal.war' @52038a4a)
`

### CODE REVIEW

File: crypto/default/src/main/java/org/keycloak/crypto/def/DefaultCryptoProvider.java [hunk 1]
```diff
@@ -22,13 +22,14 @@
...
-    private final BouncyCastleProvider bcProvider;
+    private final Provider bcProvider;
 
     private Map<String, Object> providers = new ConcurrentHashMap<>();
 
     public DefaultCryptoProvider() {
         // Make sure to instantiate this only once due it is expensive. And skip registration if already available in Java security providers (EG. due explicitly configured in java security file)
-        BouncyCastleProvider existingBc = (BouncyCastleProvider) Security.getProvider(CryptoConstants.BC_PROVIDER_ID);
+        Provider existingBc = Security.getProvider(CryptoConstants.BC_PROVIDER_ID);
+        System.out.println("Updating BC_Provider");
```
Comment (mposolda) [inline crypto/default/src/main/java/org/keycloak/crypto/def/DefaultCryptoProvider.java:32]: Minor note: Is it possible to either remove this line with `System.out.println` or replace with `logger.trace` call? See for example class `KeycloakFipsSecurityProvider` (or many other classes of Keycloak project) on how to add jboss logging to some class.

**Review by mposolda — CHANGES_REQUESTED** [review]
@nchopra27 Thanks for the PR!

I've added one minor note.

Please let me know when this PR is ready and switch it from the "draft" to "regular PR" and I can merge it. Do we have GH issue created for this?

**Review by mposolda — APPROVED** [review]
@nehachopra27 Thanks! I am approving. I can merge once tests are ok.
