### PR TITLE
Review how all resource type permissions are evaluated

### LINKED ISSUE #37081: Review how all resource type permissions are evaluated
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

The code to evaluate permissions for all resource types is not correct and failing to properly enforce access to resources.

### Version

999-SNAPSHOT

### Regression

- [ ] The issue is a regression

### Expected behavior

Allow access to all resources if no specific permission is set.

### Actual behavior

Not allowing access to all resources if no specific permission is set.

### How to Reproduce?

N/A

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #37081

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionsV2.java [hunk 1]
```diff
@@ -118,10 +118,11 @@ private boolean hasPermission(UserModel user, EvaluationContext context, String.
 
         if (resource == null) {
             // check if there is permission for "all-users". If so, load its resource and proceed with evaluation
-            if (policyStore.findByName(server, AdminPermissionsSchema.USERS_RESOURCE_TYPE) == null) {
+            resource = AdminPermissionsSchema.SCHEMA.getResourceTypeResource(session, server, AdminPermissionsSchema.USERS_RESOURCE_TYPE);
+
+            if (policyStore.findByResource(server, resource).isEmpty()) {
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionsV2.java:123]: This query might be slow depending on how many permissions you have for the resource type. For now, it is OK, I think, and we can evaluate it later once we run some benchmarks before the release.

File: model/jpa/src/main/java/org/keycloak/models/jpa/JpaClientProviderFactory.java [hunk 2]
```diff
@@ -70,9 +70,6 @@ public void postInit(KeycloakSessionFactory factory) {
                     if (Objects.equals(attrUpdateEvent.getAttributeName(), RealmAttributes.ADMIN_PERMISSIONS_ENABLED) && Boolean.parseBoolean(attrUpdateEvent.getAttributeValue())) {
                         KeycloakSession keycloakSession = attrUpdateEvent.getKeycloakSession();
                         RealmModel realm = attrUpdateEvent.getRealm();
-
-                        if (realm.getAdminPermissionsClient() != null) return;
```
Comment (pedroigor) [inline model/jpa/src/main/java/org/keycloak/models/jpa/JpaClientProviderFactory.java:74]: Better handle how the feature is initialized within the `AdminPermissionSchema`. We may eventually change the behavior when disabling/enabling to re-create the authorization model. It should also keep all related code in a single place.

File: server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java [hunk 3]
```diff
@@ -1460,12 +1460,7 @@ private static void updateResources(Set<String> resourceIds, Policy policy, Auth
                 }
 
                 if (!hasResource) {
-                    // for admin permissions remove resource in the FGAP context (if resource is becoming on orphan, we remove the resource from DB)
-                    if (AdminPermissionsSchema.SCHEMA.isAdminPermissionClient(authorization.getRealm(), resourceServer.getId())) {
-                        AdminPermissionsSchema.SCHEMA.removeResource(resourceModel, policy, authorization);
-                    } else {
-                        policy.removeResource(resourceModel);
-                    }
+                    AdminPermissionsSchema.SCHEMA.removeResource(resourceModel, policy, authorization);
```
Comment (pedroigor) [inline server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java:1463]: Keeping the logic to remove resources within the schema object.

Comment (vramik) [reply server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java:1463]: I see, I have no problem to put everything into schema object. Just please note that we are hiding the removal for non-fgap use-cases there.

If you take a look at the code here https://github.com/keycloak/keycloak/blob/ce09061264fed1109a97f8c9a362029fc9e2c050/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L1465-L1467

it is now "hidden" inside the schema.

File: server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java [hunk 4]
```diff
@@ -183,7 +202,15 @@ public Scope getScope(KeycloakSession session, ResourceServer resourceServer, St
     }
 
     public void init(KeycloakSession session, RealmModel realm) {
-        ClientModel client = session.clients().addClient(realm, Constants.ADMIN_PERMISSIONS_CLIENT_ID);
+        ClientProvider clients = session.clients();
+        ClientModel client = clients.getClientByClientId(realm, Constants.ADMIN_PERMISSIONS_CLIENT_ID);
```
Comment (vramik) [inline server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java:206]: just a nitpick, IMO it improve readability.
```suggestion
        ClientModel client = realm.getAdminPermissionsClient();
```

**Review by vramik — APPROVED** [review]
Thanks for the fix. I added two comment, nothing what prevents it from merging.

File: server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java (hunk 4 above)
Comment (pedroigor) [reply server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java:206]: I'm updating it.

File: server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java (hunk 3 above)
Comment (vramik) [reply server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java:1463]: let's keep it as is

**Review by ahus1 — APPROVED** [review]
Approving based on @vramik's review. Thank you for the PR!
