### PR TITLE
Validate auth time when max_age is sent to brokered OPs

### LINKED ISSUE #14146: Validate auth time when max_age is sent to brokered OPs
### Describe the bug

After https://github.com/keycloak/keycloak/pull/8183, it should be possible to propagate the `max_age` param to brokered OPs.

However, the `auth_time` claim from the ID Token is not validated to make sure that re-authentication happened.

### Version

999-SNAPSHOT

### Expected behavior

Fail broker authentication if `max_age` is set but the brokered OP does not re-authenticate the user.

### Actual behavior

The broker authentication is successful even though re-authentication did not happen as per `max_age` parameter.

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #14146

### CODE REVIEW

**Review by ehsantashkhisi — COMMENTED** [review]
Thanks, @pedroigor for the quick response and changes. I can not comment on the code as it is already clean and to me, the problem is conceptual and not in this code. Just because I have been struggling with this re-authentication topic recently and I find this PR the best place to talk about my concerns I'll try to describe them, please correct me if I'm mistaken.

The only way that the client can understand that the re-authentication has taken place in IDP is by checking the value in the `auth_time` claim.  Usually for sensitive action (that requires the user to be authenticated recently) client should check the value for the `auth_time` claim, if that value is not present or the value shows that the user hasn't been authenticated recently, they should redirect the user for re-authentication and after re-authentication, they should redirect the user to the current sensitive action, this time because the user is recently authenticated all those checks will be passed and sensitive action would be done. In credential flow, everything would be fine but upstream IDP raises some problems.

- Now in your code you do not let the user clear the value in the `max_age` param and throw an exception in that case, but the problem is that Keycloak set this `auth_time` claim to the current time each time the user uses IDP so if the user logout from the Keycloak and log in again using IDP(without re-authentication and just using their current session in upstream IDP), this claim will be updated to the current time. Now they can do the sensitive action because from the client’s perspective user has been authenticated recently(they should only check `auth_time` claim to make sure that the user has been authenticated recently). So a hacker can do the sensitive action without providing the credential and just by logging out from Keycloak and logging in again using IDP with the current user session in IDP.

- This has been my question for so long, should Keycloak consider authentication time in upstream IDP when the user is being authenticated with Google or Microsoft? right now when the user is authenticated with Google and Microsoft the `auth_time` claim will be set to the current time even if this is not the `auth_time` in IDP, the user is just logged in to Keycloak based on their current session with those IDP and they have not really provided their credential to those IDP to be authenticated at that time. I am just referring to this part of the [code](https://github.com/keycloak/keycloak/blob/43623ea9d0bae8497889fac9fe902fbf6c4becd9/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L951:L963) in Keycloak.


- The other thing is that some IDPs like Google said that they do not support re-authentication and they will never provide value for `auth_time` in the claim,  you can find the discussion they had [here](https://lists.openid.net/pipermail/openid-specs-ab/Week-of-Mon-20150323/005445.html). So if Keycloak wants to set `auth_time` to the `auth_time` in upstream IDP, for Google it should be `null` in every case because they do not provide this value, even if we pass the `max_age` param. They admit that they are out of protocol in that sense in the discussion.

**Comment by mposolda** [comment]
@ehsan-tashkhisi @pedroigor Thanks for the pointers. To me, it makes sense that in case that `Pass Max Age` is set to ON, then Keycloak should possibly also "inherit" the `auth_time` from the IDP ID Token and set the same `auth_time` in it's own ID Token, which will be sent back to the client after authentication.

In case of Google (and similar IDP): Since they do not provide `auth_time` claim, then they likely don't provider also support for the `max_age` parameter. Hence it probably makes sense to configure `Pass Max Age` to OFF when you use Google IDP (or similar IDP). In this case, we cannot rely on the `auth_time` sent from Google and hence we still use the current behaviour (update `auth_time` during authentication). WDYT about the behaviour like this?

**Comment by mposolda** [comment]
@pedroigor Current PR impl looks good to me. But will be good if we come to some conclusion regarding the behaviour regarding propagating `auth_time` as discussed above and possibly update the PR according to that. So not approving for now until we agree on that.

**Comment by pedroigor** [comment]
@ehsan-tashkhisi Thanks, it is more clear now.

@mposolda Works for me. I'm going to update the impl to respect the auth_time. W.r.t. to the config, the max age option is not available for social providers yet. We can do a follow-up to add the option individually, if that makes sense.

**Comment by ehsan-tashkhisi** [comment]
> @ehsan-tashkhisi @pedroigor Thanks for the pointers. To me, it makes sense that in case that `Pass Max Age` is set to ON, then Keycloak should possibly also "inherit" the `auth_time` from the IDP ID Token and set the same `auth_time` in it's own ID Token, which will be sent back to the client after authentication.

Thanks for considering these edge cases, I agree with you, the only thing that should be considered is that Keycloak sends the `auth_time` in all cases( even if you do not pass `max_age`). It should also not pass the updated `auth_time` when the `max_age` is not passed, because this is the value that clients rely on to make sure about the time that the user has been authenticated. Right now when the user logs in to Keycloak (without using the `max_age` param) using upstream IDP, no matter whether the authentication has taken place in upstream IDP or not, the value for `auth_time` is updated.

> In case of Google (and similar IDP): Since they do not provide `auth_time` claim, then they likely don't provider also support for the `max_age` parameter. Hence it probably makes sense to configure `Pass Max Age` to OFF when you use Google IDP (or similar IDP). In this case, we cannot rely on the `auth_time` sent from Google and hence we still use the current behaviour (update `auth_time` during authentication). WDYT about the behaviour like this?

Yes, I agree, the admin should keep this` pass max_age` param disabled when they are using IDP that does not support `max_age`.

This is somehow unrelated to this PR, but I mentioned it because in our company we are using different IDPs and we want to reauthenticate users for sensitive action, but because Google does not support this I can define a mapper and inform the client that reauthentication is not supported so the client can let the user do the sensitive action in that case even when `auth_time` is not updated.

**Comment by pedroigor** [comment]
@mposolda @ehsan-tashkhisi Does it make sense to assume that clients always expect the `auth_time` from the IDP or we can make this configurable?

For some clients, the expected `auth_time` might be the time when the authentication is completed in Keycloak. That is why I'm asking.

**Comment by mposolda** [comment]
@pedroigor I was wondering if we can just re-use this new switch `Pass Max Age`? In case that it is ON, Keycloak will need to do all 3 of:
1) pass max age to IDP (already done in this PR)
2) Verify auth_time sent from IDP after authentication (already done in this PR)
3) Re-sent auth_time to client (not yet done)

However it is the question if the 3rd should be rather separate switch? Or do you think that someone wants to pass `max_age` and verify `auth_time`, but skip sending `auth_time` back to the client? I hope that rather not, but not 100% sure. Maybe we can start with single switch and eventually introduce another one just if required?

**Comment by ehsan-tashkhisi** [comment]
@pedroigor @mposolda I agree that using a single switch will solve the problem, when they want to pass `max_age` it means that they want to have the `auth_time` in upstream IDP.

**Comment by pedroigor** [comment]
@mposolda @ehsan-tashkhisi PR Updated. 

Testing is tricky because `auth_time` is read-only and can not be set using a mapper so that we can force a specific auth_time at the brokered IDP.

File: services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java [hunk 1]
```diff
@@ -956,7 +960,7 @@ public static Response redirectAfterSuccessfulFlow(KeycloakSession session, Real
             clientSession.setNote(SSO_AUTH, "true");
             authSession.removeAuthNote(SSO_AUTH);
         } else {
-            int authTime = Time.currentTime();
+            int authTime = Optional.ofNullable(authSession.getClientNote(AUTH_TIME_BROKER)).map(Integer::parseInt).orElse(Time.currentTime());
             userSession.setNote(AUTH_TIME, String.valueOf(authTime));
```
Comment (ehsan-tashkhisi) [inline services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:964]: Here when the `Pass Max Age` is enabled but `max_age` is not passed( this is especially the case when the user logout from Keycloak and log in again) the value for  `auth_time` will be updated, I think it should not happen, let's see how clients do the checks for sensitive action:

```
public boolean isSensitiveActionAllowed() {
  long authTime = Optional.ofNullable(oidcHelper.getAuthTime()).orElse(0);
  long now = Time.currentTime();
  return now - authTime < sensitiveActionConfig.getSensitiveActionAllowedDuration();
}

public void sensitiveAction() {
  if (isSensitiveActionAllowed())
  // Do the sensitive action
  else
  // redirect the user for reauthentication and then retry this action.
}

```

The literal description of this sample code:

> When the user tries to do the sensitive action and the `auth_time` is not present in the token, or it is old, the client redirects the user for re-authentication, otherwise, they let the user do the sensitive action.

Now imagine the `auth_time` is old and the user should not be able to do the sensitive action. But Instead of re-authentication, a hacker just logs out from the Keycloak, and logs in again(without going through the natural flow of re-authentication), when they log in again they will have updated `auth_time` and they can do the sensitive action.

I understand that this is complex but if the user can do the sensitive action without reauthentication all this effort would be useless.

Solutions:

* Not to pass `auth_time` to the client when the `Pass Max Age` is enabled and Keycloak does not know the authentication time in IDP(since the `max_age` param is not passed to Keycloak) it might not be backward compatible because Keycloak always passed `auth_time` in the token up to now(But protocol said that it is only required when `max_age` is passed)

*  Return `0` for `auth_time` when Keycloak does not know authentication time in IDP(When `Pass Max Age` is ON and `max_age` is not passed)

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:964]: > Now imagine the auth_time is old and the user should not be able to do the sensitive action. But Instead of re-authentication, a hacker just logs out from the Keycloak, and logs in again(without going through the natural flow of re-authentication), when they log in again they will have updated auth_time and they can do the sensitive action.

You are assuming here that the account is compromised, right? If so, there are many other things like completely stealing the account.

I think what you want to do here is make sure re-authentication happens after logout. In this case, we could perhaps consider a specific claim within the token to indicate that authentication happened at the IdP.

W.r.t. to the proposed solutions:

1) The `auth_time` is an optional claim and I think it makes sense to include it even though you are not using `max_age`.
2) Looks like we are overusing the claim
3) For that we would need to persist the `auth_time` so they can survive session expiration and server restarts. Not sure if we want that.

If it makes sense for you, I would keep the scope of this PR to only include the validation of `auth_time` and the latest change to propagate the time from the OP. We can then create a follow-up issue and discuss the requirements you are proposing.

Comment (ehsan-tashkhisi) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:964]: First of all thanks for the effort in this PR, I thought about it for a long time and I know how complex it is.

> You are assuming here that the account is compromised, right? If so, there are many other things like completely stealing the account.

No, in this scenario, the account is not compromised. Just another malicious user uses our user device and does the sensitive action.  The goal of re-authentication is that the user who is doing the action has the `username` and `password` and thereby he is the identified user. if someone else is using the same device and do not have the username and password should not be able to do the sensitive action.

Please Consider UserA as the owner of the account, and UserB as a malicious user who finds out that UserA is not at his desk and wants to use UserA device and UserA account to do some malicious action.

Here is the scenario for reauthentication that is implemented in this PR.

* UserA wants to do sensitive actions.
*  Client checks the `auth_time` and based on that redirects the user to Keycloak for reauthentication.
*  User clicks on the IDP button.
* Keycloak redirects the user to IDP for reauthentication.
*  User provides its credential(Maybe username and password). 
* User redirects back to Keycloak -> user redirects back to the client.
*  client checks the `auth_time` and lets the sensitive action.

Here is the scenario in which UserB gets at the UserA desk and wants to do some sensitive action, so considering this all the following actions are done with userA device and using userA session with Keycloak and upstream IDP.

* UserB wants to do sensitive action.
* Client checks the `auth_time` and redirects the user for re-authentication.
* At this point, UserB logout from Keycloak(He only logs out from Keycloak, and he is still logged in upstream IDP like Azure AD).
*  Then he login again to Keycloak.
*  He clicks on IDP button. 
*  He will be redirected to IDP.
* **IDP redirects userB back to Keycloak(Note that this time UserB does not need to provide userA credentials,  and  IDP does not ask for the username and password because the UserA session with upstream IDP is still open and the `max_age` param is not provided).**
*  Keycloak redirects back the user to the client with updated `auth_time`.
*  UserB goes back to the sensitive action and does that action, this time he can do that action because he has updated `auth_time` from the client's perspective.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:964]: Thanks. It is clear now the attack scenario you are considering.

I'm not sure how others OPs deal with both `acr` and `amr` claims. This is also somewhat related to step-up. My point is, a `acr==0` might indicate that the authentication was done based on long-lived cookies and as such your client could deny the sensitive operation.

I don't max-age alone will solve this but perhaps a mix of checking `acr`, conditionally forcing `prompt=login`, etc.

There is also the possibility to store tokens when doing brokering. We can also think about comparing the stored token with the new token issued by the OP.

Comment (ehsan-tashkhisi) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:964]: Thank you so much for the answer, it would be also appreciated if you can create an issue to discuss it.

I also thought about step-up authentication but the question that might be raised there is that:

When we are using upstream IDP like azure AD, is that OK to use second-factor authentication in Keycloak, or when the user is being authenticated using upstream IDP all the things that are related to authentication should be done in upstream IDP?

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:964]: Hard to say because it depends on your requirements. If the OP is not enough for you in terms of proof of identity or if you want to also enable users to authenticate through your OP, the it makes sense.

But I think your use case is more related to step-up and how brokering integrates with this capability so that LoAs are properly set when authentication happens at the brokered OP.

Comment (mposolda) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:964]: I agree that it is a complex problem and we can possibly address as a follow-up.

In general, it seems non-trivial to decide what should be proper `auth_time` sent to the client. It is quite clear that in case Keycloak shows interactive screens to the user during auth (EG. username/password, TOTP, WebAuthn), the `auth_time` should be updated. But it is not clear if/how it should be set in case of non-interactive authenticators like Kerberos or X509. And for brokering, where Keycloak delegates authentication to IDP, it is also not clear.

I wonder that we can possibly have `auth_time` protocol mapper? This will allow to configure if:
- The `auth_time` should be set just if interactive authentication was triggered (It is possible to detect interactive authenticators as the authenticators like Password, OTP or WebAuthn implements `CredentialValidator` interface. And the info about authenticators used in finished authentication flow is saved in the authenticationSession)
- The `auth_time` should be set by any authenticator (with the exception of SSO Cookie authenticator)
- The `auth_time` should be set based on some note from authentication session. So the note can be set by the IDP (like done in this PR) or by some authenticator (or by authentication policy in the future)
- Maybe more options (or combinations of the options above).

This may allow to set that for example if authentication happened through Kerberos OR if authentication happened through IDP and IDP did not returned `auth_time`, then the `auth_time` should not be sent at all in the ID Token etc.

Until we have, I am not sure if we should skip sending `auth_time` to client (or set `auth_time` to 0). So I will likely rather keep as it is in this PR.

So +1 to discuss as a follow-up.

**Review by mposolda — APPROVED** [review]
I am approving and leaving to you guys if something more needed or if it can be merged as is.

**Comment by brunomedeirosdedalus** [comment]
@pedroigor 

Hi, just a small remark regarding this line:
 
`if (authTimeInt + maxAgeInt < Time.currentTime())`
 
doesn't this mean that if someone passes max_age=0 (to tell the IdP to force authentication), then we only have 1 second between the time that the IDP reauthenticated and the time that the previous line of code is executed?

That seems semantically incorrect, because the user did re-authenticate.

Shouldn't we instead, check the timestamp of when we send the request to the IdP and then compare that time against the 
authTimeInt + maxAgeInt  and if it is lower, store that information and then check afterwards that indeed an authentication has happend?

Or maybe we could add the 'Allowed clock skew'  as part of the checking?
