### PR TITLE
KEYCLOAK_SESSION not working for some user federation setups when use…

### LINKED ISSUE #14354: KEYCLOAK_SESSION not working for some user federation setups
### Describe the bug

In some cases with user federation, the ID of the user can contain some special characters. For example when configured LDAP provider with "Import Users" set to OFF and with "UUID LDAP Attribute" set to "uid" . Then when you have some user with special character in the "uid", this is in turn used as the ID of the user. And this is saved in the KEYCLOAK_SESSION cookie:
```
KEYCLOAK_SESSION=**:spécial.char/**; 
KEYCLOAK_SESSION_LEGACY=***; 
```
The character "é" is present in the cookie name, which is not allowed by the undertow server. In the log is this (likely when accessing Keycloak from some Javascript application when the particular user with special character is logged):
```
ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to /auth/realms/defence-intra/protocol
/openid-connect/login-status-iframe.html: java.lang.IllegalArgumentException: UT000173: An invalid control character [233] was 
present in the cookie value or attribute
```

### Version

19.0.1

### Anything else?

For the fix, it is probably easiest to Base64Url encode the cookie `KEYCLOAK_SESSION` (and maybe some other related cookies, not yet sure for which of them is this applicable) to make sure that there are not special characters in these cookies.

### PR DESCRIPTION
**Pull request by mposolda**
…r ID has special chars

closes #14354

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java [hunk 1]
```diff
@@ -784,7 +785,8 @@ public static void createLoginCookie(KeycloakSession keycloakSession, RealmModel
         CookieHelper.addCookie(KEYCLOAK_IDENTITY_COOKIE, encoded, cookiePath, null, null, maxAge, secureOnly, true, SameSiteAttributeValue.NONE);
         //builder.cookie(new NewCookie(cookieName, encoded, cookiePath, null, null, maxAge, secureOnly));// todo httponly , true);
 
-        String sessionCookieValue = realm.getName() + "/" + user.getId();
+        // With user-storage providers, user ID can contain special characters, which need to be encoded
+        String sessionCookieValue = realm.getName() + "/" + Encode.urlEncode(user.getId());
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:789]: Curious why the session cookie has the realm name, and user-id. Session iframe only needs the session-id afaik.

Comment (mposolda) [reply services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java:789]: I also don't know. Especially realm is in the cookie path and user-id does not seem to be needed for anything.

On the other hand, if we change it, we break compatibility with the keycloak-js adapter and we break zero-downtime upgrade in z-stream, right?  For example case when login is served by cluster node1, who will use cookie with only session-id, but admin console is served on cluster node2, which still expects old iframe format, then login to the admin console might not work as expected etc.

Hence should we do this one for z-stream and then have follow-up issue, which will change cookie to only session-id? That one will need to change iframe as well and will require migration instructions though. WDYT?

**Review by stianst — APPROVED** [review]
