### PR TITLE
Ensure that the EncryptedKey is passed to the DecryptionKeyLocator for SAML

### LINKED ISSUE #22974: NullpointerException when using encrypted SAML assertions
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

saml

### Describe the bug

When setting up an Identity provider of type SAMLv2.0 and enabling `Want Assertions encrypted`, a NullpointerException is thrown. 

Stacktrace from latest nightly release:
```
2023-09-05 08:57:48,673 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-13) Uncaught server error: org.keycloak.broker.provider.IdentityBrokerException: Could not process response from SAML identity provider.
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:596)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleSamlResponse(SAMLEndpoint.java:679)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.execute(SAMLEndpoint.java:278)
	at org.keycloak.broker.saml.SAMLEndpoint.postBinding(SAMLEndpoint.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.runBlockingCode(QuarkusRequestFilter.java:121)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$handle$0(QuarkusRequestFilter.java:83)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.protocol.saml.SAMLDecryptionKeysLocator.getKeys(SAMLDecryptionKeysLocator.java:164)
	at org.keycloak.saml.processing.core.util.XMLEncryptionUtil.decryptElementInDocument(XMLEncryptionUtil.java:285)
	at org.keycloak.saml.processing.core.saml.v2.util.AssertionUtil.decryptAssertion(AssertionUtil.java:612)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:449)
	... 50 more
```

### Version

21.1.2, where we observed this after upgrading from 20.0.5

### Expected behavior

No exception, instead, usage of the right key.
This worked in Keycloak v20.1.5 before introducing separate keys for signing and encryption.

### Actual behavior

Unable to login with the configured SAML v2.0 identity provider.

### How to Reproduce?

1. Configure a SAML v2.0 identity provider
2. enable `Want Assertions encrypted`
3. Configure the chosen identity provider to encrypt assertions with the key provided in serviceProviderConfig document via link `SAML 2.0 Service Provider Metadata`
4. try to login and get 
image

### Anything else?

Here a patch to fix this:
```
Subject: [PATCH] Ensure only wrapped keys intended for public key cryptography are used for SAML decryption

Otherwise, symmetric keys are selected as well and forcing a NullPointerException
when reading private key while mapping the keyStream.
---
Index: core/src/main/java/org/keycloak/crypto/KeyWrapper.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/main/java/org/keycloak/crypto/KeyWrapper.java b/core/src/main/java/org/keycloak/crypto/KeyWrapper.java
--- a/core/src/main/java/org/keycloak/crypto/KeyWrapper.java	(revision 8286b8b31fcfe9822b5f6f7693e76547b1960d87)
+++ b/core/src/main/java/org/keycloak/crypto/KeyWrapper.java	(date 1693901491498)
@@ -195,4 +195,8 @@
         key.isDefaultClientCertificate = this.isDefaultClientCertificate;
         return key;
     }
+
+    public boolean isForPublicKeyCryptography() {
+        return publicKey != null && privateKey != null;
+    }
 }
Index: services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java b/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java
--- a/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java	(revision 8286b8b31fcfe9822b5f6f7693e76547b1960d87)
+++ b/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java	(date 1693901046818)
@@ -152,6 +152,7 @@
 
         // Map keys to PrivateKey
         return keysStream
+                .filter(KeyWrapper::isForPublicKeyCryptography) // required to get encoded private key safely
                 .map(KeyWrapper::getPrivateKey)
                 .map(Key::getEncoded)
                 .map(encoded -> {
```

I also found that setting `encryptionAlgorithm` config parameter to `RSA-OAEP` (the algorithm from the used key) via Rest-API (note: there is no possibility to set this via UI!) on IdentityProviderRepresentation avoids SamlEndpoint.handleLoginResponse throwing an NPE. But the check (in the patch) is a good defensive strategy for avoiding the NPE.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/22974

Two little issues in SAML decryption of elements:

* The `EncyptedKey` sometimes is outside the `EncryptedData` (next sibling). And it was not passed to the `SAMLDecryptionKeysLocator`. So the locator couldn't filter by the encryption alg set in the response. This threw a NPE iterating the keys. Code also changed to not decode the `EncyptedKey` twice (if it was already inside the data) and to avoid keys without private key.
* Besides the admin console is showing/hiding the encryption algorithm property if the `wantAuthnRequestsSigned` is ON. That makes no sense, the encryption alg is only used to force the alg in decrypting the received elements, not when we sign the requests. I have moved it to show/hide when `wantAssertionsEncrypted` is ON. (I think that there is no lint or test errors, but I'm never sure. :smile: )

The combination of the two problems threw the NPE in the related issue. The alg was not forced (because the box was hidden and the user didn't see how to force it) and then the `EncryptedKey` was outside the `EncrypedData` in okta. Test added to modify the XML and be similar to the one produced by okta.

### CODE REVIEW

File: js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx [hunk 1]
```diff
@@ -462,6 +432,45 @@ const Fields = ({ readOnly }: DescriptorSettingsProps) => {
...
         isReadOnly={readOnly}
       />
+
+      {wantAssertionsEncrypted === "true" && (
+        <FormGroup
+          label={t("encryptionAlgorithm")}
+          labelIcon={
+            <HelpItem
+              helpText={th("encryptionAlgorithm")}
+              fieldLabelId="identity-provider:encryptionAlgorithm"
```
Comment (jonkoops) [inline js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx:442]: We recently made some changes to the way labels are handled, so the namespace can now be omitted.
```suggestion
              fieldLabelId="encryptionAlgorithm"
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx (hunk 1 above)
Comment (rmartinc) [reply js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx]: @jonkoops I had just moved it! :smile: Done now!

But one question, modifying this I saw that the help message was not OK. I needed to also change the `helpText={th("encryptionAlgorithmHelp")}` (adding suffix `Help`) in the `HelpItem`. I see a all the `HelpItem` (a least in the saml provider) are not showing the proper help message. I just modified the one that I was moving.

**Review by jonkoops — DISMISSED** [review]

File: js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx (hunk 1 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx]: Could you log a separate issue for that one? I think this might be because of the recent changes made to the labels. ping @edewit

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by pedroigor — DISMISSED** [review]

**Comment by rmartinc** [comment]
I give up today, something is failing today. Tomorrow I will rebase and try again.

**Comment by rmartinc** [comment]
@jonkoops It seems that the Account UI E2E is failing consistently. And I see it happens in other PRs (for example https://github.com/keycloak/keycloak/pull/23271). I have not changed anything in account so I think I'm not guilty here. :smile: 
The other failure seems to be spureous because something with node not being executable at themes.

**Comment by jonkoops** [comment]
> It seems that the Account UI E2E is failing consistently.

This should be fixed now, could you rebase your PR on `main` and see if everything passes?

**Review by jonkoops — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]

**Comment by rmartinc** [comment]
OK! All CI passed now. Thanks @jonkoops! @pedroigor ready to merge now if you don't see anything more.

**Review by mposolda — APPROVED** [review]
@rmartinc @jonkoops @pedroigor Thanks everyone for the work on this and the review
