### PR TITLE
EventBuilder fixes to copy the store and session context

### LINKED ISSUE #20105: Unable to template emails in EventListenerProvider (No realm in provided KeycloakSession)
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I have a custom EventListenerProvider which instanciate a FreeMarkerEmailTemplateProvider() to send a email with keycloak.

My implementation works well with the keycloak version 21.0.1. but no longer works in  21.1.x.

When I debug Keycloak, I see that there is no realm in the context of the KeycloakSession given to EventListenerProviderFactory in order to instanciate my EventListenerProvider.

I have this error : 
Cannot invoke "org.keycloak.models.RealmModel.getEmailTheme()" because the return value of "org.keycloak.models.KeycloakContext.getRealm()" is null

Example of my code : 
```
public class BlockLoginEventListenerProviderFactory extends EventListenerProviderFactory {

    @Override
    public BlockLoginEventListenerProvider create(KeycloakSession keycloakSession) {
        return new BlockLoginEventListenerProvider(keycloakSession);
    }

    @Override
    public String getId() {
        return "gzl-block-login";
    }
}
```

```
public class BlockLoginEventListenerProvider extends EventListenerProvider {

   KeycloakSession keycloakSession;

    public BlockLoginEventListenerProvider(KeycloakSession keycloakSession) {
       this.keycloakSession = keycloakSession;
    }

    @Override
    public void onEvent(Event event) {
          MyUserModelAdapter myUserModelAdapter = (MyUserModelAdapter) this.getKeycloakSession().users().getUserById(keycloakSession.getContext().getRealm(), event.getUserId());
          ...
          try {
              // Create email template
              EmailTemplateProvider emailTemplateProvider = new FreeMarkerEmailTemplateProvider(this.keycloakSession)
                      .setRealm(keycloakSession.getContext().getRealm())
                      .setUser(myUserModelAdapter);
              // Send email
              emailTemplateProvider.send("xxx", "email-blocked.ftl", attributes);
         } catch (EmailException e) {
              log.warn("Mail not sent");
         }
    }
}
```

### Version

21.1.0 & 21.1.1

### Expected behavior

When I log in throught account client (https:/xxx/auth/realms/myRealm/account/), i want to send an email to notify the user if it account is disabled. For this I use an specific implementation of EventListenerProvider and EventListenerProviderFactory.

Example of KeycloakSession provided to create an instance of EventListenerProvider when it works : 
image

### Actual behavior

Unable to instanciate a FreeMarkerEmailTemplateProvider to send an email in the onEvent() method of my custom EventListenerProvider implementation.

The KeycloakSession provided in the create() method of the factory doesn't contains the RealmModel. A realm is required to retrieve the email templates.

Example of bad KeycloakSession provided to create an instance of EventListenerProvider : 
image

Note that this create() method is called 3 times during the connection attempt. The first two times, the KeycloakSession provided contains the realm but the third time it is no longer the case

### How to Reproduce?

Implement an EventListenerProvider and an EventListenerProviderFactory which instanciate a FreeMarkerEmailTemplateProvider in the onEvent() method. Try to log in to an user account (/realms/myRealm/account). An exception should be thrown.

### Anything else?

_No response_

### LINKED ISSUE #20757: SEND_RESET_PASSWORD event is not stored
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

SEND_RESET_PASSWORD event is not stored

### Version

21.1.1

### Expected behavior

SEND_RESET_PASSWORD event is stored. This event was stored in the 21.0.2 version.

### Actual behavior

SEND_RESET_PASSWORD event is not stored in the database, it is not visible on the admin UI

### How to Reproduce?

- Run Keycloak `21.1.1` locally using docker compose (in my case I have SQL Server database, but it could be any supported database)
image
- Create realm `test-realm`
- Configure Login section:
image
- Configure smtp (please use valid smtp configuration) 
image
- Enable UserEvents, make sure that `SEND_RESET_PASSWORD` is in the list
image
- Create test user
image
- Open client and click to Sign In, then click to Forgot password: http://localhost:8091/realms/test-realm/account/
image
- Use valid test user email address and click Submit
image
- Open user events, they are empty
image

### Anything else?

Please see exported realm json file in zip archive below:
[test-realm.zip](https://github.com/keycloak/keycloak/files/11637895/test-realm.zip)

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/20757
Closes https://github.com/keycloak/keycloak/issues/20105

The `store` property was not cloned and it made the cloned builder not save the event to the store provider. This was triggered by this [commit](https://github.com/keycloak/keycloak/pull/19488/commits/097638a37a29272488e2b80f5bca750dc50b37ff#diff-6c641fd553097eb7d3a340bc4d676ff2c435bac772f3d57e343665c4bf867b6eL86-L87).

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/AbstractEventsTest.java [hunk 1]
```diff
@@ -23,14 +23,15 @@
...
+import java.io.Serializable;
 import java.util.ArrayList;
 import java.util.List;
 
 /**
  *
  * @author Stan Silvert ssilvert@redhat.com (C) 2016 Red Hat Inc.
  */
-public abstract class AbstractEventsTest extends AbstractKeycloakTest {
+public abstract class AbstractEventsTest extends AbstractKeycloakTest implements Serializable {
```
Comment (hmlnarik) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/AbstractEventsTest.java:34]: Why is this change here?

**Review by hmlnarik — COMMENTED** [review]
Thanks for the fix. LGTM apart from one question re the test, please see inline.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/AbstractEventsTest.java (hunk 1 above)
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/AbstractEventsTest.java:34]: Is it needed to use `Serializable` here? It is quite strange to me as none of our other tests need this...

I guess it is because of `testingClient.server(REALM_NAME1).run` block? In that case it can be possibility to:
- Use the real operations (to simulate real events) instead of "faking" them with testingClient
- Use the `final` local variable. Something like for example this should work AFAIK (based on some other classes):
```
final String localRealmId = this.realmId;
        testingClient.server(REALM_NAME_1).run(session -> {
            RealmModel realm = session.realms().getRealm(myRealmId);
```

WDYT?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventStoreProviderTest.java [hunk 2]
```diff
@@ -171,6 +174,32 @@ public void query() {
...
+    @Test
+    public void testEventBuilder() {
+        testingClient.server(REALM_NAME_1).run(session -> {
+            RealmModel realm = session.realms().getRealm(realmId);
+
+            EventBuilder event = new EventBuilder(realm, session)
+                    .event(EventType.LOGIN)
+                    .user("user1")
+                    .client("client1");
+            event.error(Errors.USER_NOT_FOUND);
```
[the remark this answers is not in the document]
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventStoreProviderTest.java:186]: @hmlnarik Yes, the test was done this way on purpose, to test the two different scenarios. The `error` uses a new transaction with `storeImmediately` to true, and the `success` uses false. The latter is the one really testing the issue fixed here, but I added the `error` part to test the other code path too.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventStoreProviderTest.java [hunk 3]
```diff
@@ -171,6 +174,32 @@ public void query() {
...
+
+            event.clone().event(EventType.LOGIN).success();
```
[the remark this answers is not in the document]
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventStoreProviderTest.java:188]: Yep, same answer, I decided to test both ways of storing the event (success and error).

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/AbstractEventsTest.java (hunk 1 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/AbstractEventsTest.java]: It was needed because I used the `realmId` property in the test. But I have changed it to get the realm from `session.getContext()` now. I removed these changes now..

Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/AbstractEventsTest.java]: I changed to use `session.getContext().getRealm()` and removed the `Serializable`. Thanks!

**Comment by pedroigor** [comment]
Also related https://github.com/keycloak/keycloak/issues/20105#issuecomment-1572964464.

**Comment by rmartinc** [comment]
> Also related [#20105 (comment)](https://github.com/keycloak/keycloak/issues/20105#issuecomment-1572964464).

@pedroigor Then, do you want that I set the realm to the context in this PR? But probably I should do the same with client and authentication session, maybe other events need those too... Right?

**Comment by rmartinc** [comment]
OK, I have added the propagation of the session context too. The idea is that now the `runJobInTransaction` has a new variant that you can pass the `KeycloakContext` and all the sets are executed before executing the task. Maybe I have gone too far with the test but I preferred to also test the realm is OK in the event.

Let's see the tests.

**Review by pedroigor — APPROVED** [review]

**Review by hmlnarik — COMMENTED** [review]
@rmartinc @pedroigor This has introduced blocker #20855.

**Comment by rmartinc** [comment]
@hmlnarik upps! Sorry! Happy to see you have catch this up very quick! Thanks a lot! (I'll try to not forget to not mix objects from different sessions...)
