### PR TITLE
fix: relaxes the admin root redirect check

### LINKED ISSUE #39085: Redirects to admin endpoint 404s on hostname-admin / request scheme mismatch
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When a https url is configured for `hostname-admin` and requests are http (e.g. from a edge proxy server terminating TLS) requests to `/admin/` return a 404.

This was introduced with https://github.com/keycloak/keycloak/issues/38463. The logic comparing `requestUrl` and `adminUrl` should be relaxed.

### Version

26.2.0

### Regression

- [x] The issue is a regression

### Expected behavior

Redirect to Admin Console is performed when `/admin` is accessed via the Admin Hostname - a mismatch in schemes http/https should be allowed.

### Actual behavior

404 response when request is http, and  `hostname-admin` is https.

### How to Reproduce?

I'm seeing the issue with only the hostname configured - maybe this is internally setting admin to `hostname + "/admin"`?

```
./bin/kc.sh start-dev \
--hostname=https://banana.russdev
```

Access `/admin/` with a host header configured - and on http.  Observe a 404.

```
$ curl -v --header 'Host: banana.russdev'  localhost:8080/admin/
< HTTP/1.1 404 Not Found
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #39085

@vmuzikar @russau this relaxes the check in two ways 
- if there is no separate hostname-admin configured, then we'll always redirect. 
- the local admin check was exanded to any secure context localhost host - that will continue to allow dev scenarios using not just localhost, but 127.0.0.1, etc.

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java [hunk 1]
```diff
@@ -94,19 +94,31 @@ public static UriBuilder adminBaseUrl(UriBuilder base) {
...
+            return false;
+        }
+        KeycloakUriInfo frontEndUriInfo = session.getContext().getUri();
+        String frontEndUrl = frontEndUriInfo.getBaseUri().toString();
         String adminUrl = adminUriInfo.getBaseUri().toString();
-        String localAdminUrl = session.getContext().getUri(UrlType.LOCAL_ADMIN).getBaseUri().toString();
 
-        if (!isAdminConsoleEnabled() || (!requestUrl.startsWith(adminUrl) && !requestUrl.startsWith(localAdminUrl))) {
-            return Response.status(Response.Status.NOT_FOUND).build();
+        if (adminUrl.equals(frontEndUrl)) {
```
Comment (russau) [inline services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java:115]: This makes sense to me - the issue I reported would enter here, my frontend and admin are the same.

Comment (russau) [reply services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java:115]: I built a new `keycloak-999.0.0-SNAPSHOT.zip` and tested my edge case.

```
$ ./bin/kc.sh start-dev \
--hostname=https://banana.russdev
```

In another window I curled the `/admin/` endpoint and saw the results I was expecting

```
$ curl -v http://banana.russdev:8080/admin/
< HTTP/1.1 302 Found
< Location: https://banana.russdev/admin/master/console/
```

LGTM!

**Comment by shawkins** [comment]
Discussed offline that the local admin concept is a bit odd, but we should stick with it in this pr for now and just note that the original pr introduced a small breaking change that any localhost host or address other than localhost will no longer work for admin redirects. A separate issue can be opened to remove the local admin concept from the hostname providers.

**Review by vmuzikar — COMMENTED** [review]
I was thinking about it more too. It indeed seems like an unnecessary weakness to use LOCAL_ADMIN at the welcome page. +1 for just removing the link and having there just a statement that local address needs to be used.

LOCAL_ADMIN was supposed to be useful for crafting localhost address but as you say it's very problematic if edge (or reencrypt) proxy without proxy headers is involved.

For the admin redirect, let's use the approach in this PR and let's deprecate LOCAL_ADMIN.

File: services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java [hunk 2]
```diff
@@ -94,19 +94,31 @@ public static UriBuilder adminBaseUrl(UriBuilder base) {
...
+            return true; // admin is the same as front-end, we're not leaking information
         }
+        String requestUrl = frontEndUriInfo.getRequestUri().toString();
 
-        RealmModel master = new RealmManager(session).getKeycloakAdminstrationRealm();
-        return Response.status(302).location(
-                adminUriInfo.getBaseUriBuilder().path(AdminRoot.class).path(AdminRoot.class, "getAdminConsole").path("/").build(master.getName())
-        ).build();
+        return requestUrl.startsWith(adminUrl)
+                || SecureContextResolver.isLocalHost(frontEndUriInfo.getRequestUri().getHost());
```
[the remark this answers is not in the document]
Comment (shawkins) [reply services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java:121]: There is one here https://github.com/keycloak/keycloak/pull/39095/files#diff-a1eab9f59881fa83e27b009337ed8645e53009e5c224d0ec9e55c910a99a11e9R48

File: services/src/main/java/org/keycloak/services/resources/WelcomeResource.java [hunk 3]
```diff
@@ -269,15 +269,15 @@ private boolean shouldBootstrap() {
         return shouldBootstrap.get();
     }
 
-    private boolean isLocal() {
+    public static boolean isLocal(KeycloakSession session) {
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/services/resources/WelcomeResource.java:272]: Should this rather be in `SecureContextResolver` if it's public and meant to be used beyond the Welcome page scope?

File: docs/documentation/upgrading/topics/changes/changes-26_2_2.adoc [hunk 4]
```diff
@@ -0,0 +1,7 @@
+== Notable changes
+
+Notable changes where an internal behavior changed to prevent common misconfigurations, fix bugs or simplify running {project_name}.
+
+=== local admin deprecation
+
+`UrlType.LOCAL_ADMIN` and the corresponding welcome theme variable `localAdminUrl` have been deprecated for eventual removal. The default welcome resource will now simply mention localhost rather than providing a URL when an admin user has yet to be created.
```
Comment (vmuzikar) [inline docs/documentation/upgrading/topics/changes/changes-26_2_2.adoc:7]: Despite the deprecation not being a breaking change, I believe we can't do it in a patch release. I'd suggest handling the deprecation in a separate PR for 26.3.

Comment (shawkins) [reply docs/documentation/upgrading/topics/changes/changes-26_2_2.adoc:7]: > Despite the deprecation not being a breaking change, I believe we can't do it in a patch release.

It seems like we can't avoid having some kind of notice in 26.2.2. If you are worried about the case of having a custom hostname provider customize LOCAL_ADMIN, they would need to know that it is no longer used by the default welcome resource.

**Comment by shawkins** [comment]
> @vmuzikar changed the pr to use the same method for the local check in the AdminRoot and the WelcomeResource, deprecated admin local, and removed the link from the welcome page. An upgrade note was added for 26.2.2 presuming this will be quickly backported, or if you want I can open that pr first.

However as you can see, this makes the non-redirect case harder to test - we'll need to access the server via a non-localhost connection.

File: docs/documentation/upgrading/topics/changes/changes-26_2_2.adoc (hunk 4 above)
Comment (shawkins) [reply docs/documentation/upgrading/topics/changes/changes-26_2_2.adoc:7]: My belief is that it would still be a good idea to let users know that LOCAL_ADMIN is not used by default anymore, and that if they are providing their own LOCAL_ADMIN that it should be hardened. If this can't be done via a deprecation because it's a patch release, then I'd still want some change note.

cc @mabartos @abstractj @stianst

File: services/src/main/java/org/keycloak/services/resources/WelcomeResource.java (hunk 3 above)
Comment (vmuzikar) [reply services/src/main/java/org/keycloak/services/resources/WelcomeResource.java:272]: Ok, let's leave as is. The admin root redirect is kinda related to the welcome page, so let's keep the logic there.

File: tests/base/src/test/java/org/keycloak/tests/admin/AdminRootTest.java [hunk 5]
```diff
@@ -63,7 +63,9 @@ public void testRedirect(String hostname) throws Exception {
 
     @Test
     public void testNoRedirectWithFrontendUrl() throws Exception {
-        HttpResponse response = client.execute(new HttpGet(HOSTNAME + "/admin"));
+        HttpGet request = new HttpGet(HOSTNAME + "/admin");
+        request.addHeader("Forwarded", "for=192.0.2.60");
```
Comment (vmuzikar) [inline tests/base/src/test/java/org/keycloak/tests/admin/AdminRootTest.java:67]: It'd be good to have some comment here that we're adding an arbitrary Forwarded header to make the `WelcomeResource.isLocal` check fail.

**Comment by vmuzikar** [comment]
> @vmuzikar are you okay with changing the test to make it seem like the request is coming from a proxy so that it fails the isLocal check?

That's IMHO fine.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

If others agree we will have the deprecation in 26.3 to be consistent that no deprecations are made in patch releases, we can merge.

File: docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc [hunk 6]
```diff
@@ -2,6 +2,10 @@
 
 Breaking changes are identified as requiring changes from existing users to their configurations.
 
+=== local admin deprecated for removal
```
[the remark this answers is not in the document]
Comment (shawkins) [reply docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc:5]: It's both the enum and the template variable that are being deprecated.

**Review by pedroigor — APPROVED** [review]
