### PR TITLE
User session lookup optimization and fixes

### LINKED ISSUE #37662: Optimize session lookup
### Description

When the access-token is sent to some Keycloak endpoints (EG. introspection endpoint, user-info endpoint admin/account REST API), we currently verify if user-session, which is linked to that token, exists (unless token comes from client-credentials grant, which does not use user sessions).

The issue is, that we don't know if token is coming from offline session or "online" session. So currently we try to lookup "online" and then fallback to offline just if "online" not found. This can be optimized and made more secure if we know session type. In that case, we can lookup only the correct session type and lookup either only "online" or only "offline" .

The info about session-type would be available in the token after https://github.com/keycloak/keycloak/issues/37118, so this issue is probably the follow-up after that one.

Related code where the sessions are looked-up:
- `UserSessionUtil.findValidSession` - used by introspection endpoint and user-info endpoint
- `AuthenticationManager.verifyIdentityToken` - used by account REST and admin REST APIs (used maybe by more token types, not just access token. So should be doublechecked and maybe dedicated signature used to optimize session lookup just when used with the access-token. But not sure as the type UNKNOWN, so when token ID is just UUID, it would work as well even if won't be so optimal...)

Related note: `RefreshTokenIntrospectionProvider` might probably override some method for session lookup, so session lookup would be optimized as well. With #37118, the session-type is not encoded to refresh-token as that issue is specific to access-tokens only. However it is not needed for refresh-token as refresh-token has the `type` claim with the value `Refresh` or `Offline`, so for refresh-token it is already clear if it should lookup "online" session or offline session. The optimized lookup is used during refresh-token request where it lookups only proper session type. We can do similar in `RefreshTokenIntrospectionProvider` as well, so it does not need to "fallback" and lookup both online and offline.

### PR DESCRIPTION
**Pull request by mposolda**
closes #37662

I've started to do the refactoring as mentioned in the issue. The aim was to optimize lookup of user session and during token verification, avoid trying to lookup "online" session whe the token is coming from "offline" session etc. Also I've tried to re-use the same code for more places (introspection endpoint, user-info, admin/account REST API verifications) to avoid having the same/similar code for user session lookup and verification on multiple places. So I've made `AuthenticationManager.verifyIdentityToken` to re-use the `UserSessionUtil.findValidSession` for lookup of user-session and all the relevant checks.

I've ended with bigger PR than expected as I found also some bugs during the refactoring (when looking into the code and thinking about various broken scenarios...).

Here some details about the bugs

### Bug 1

Admin/account REST API invoked with the token of disabled user, which comes from offline login. Scenario like:
- User authenticates and gets some token
- Admin disables the user
- When admin REST (or account REST) API is called with the access-token of the user, request is rejected due the disabled user. Which is correct. However when the token is coming from offline session, request is still allowed.

**Cause:** Looks like missing a check in `AuthenticationManager.verifyIdentityToken`. There were quite a lot of if/else branches with various combinations and this combinations was likely missed.

### Bug 2

Events for introspection are a bit buggy.
- When there is error during token introspection request, the error event is called 3 times. Expected would be to call only 1 error event for a request
- The introspection error is always generic error `token_introspection_failed` instead of some more concrete error like what he had in other events (EG. `invalid_token`, `client_not_found`, `session_expired` etc).
- Finally the introspection successful event does not contain some relevant informations. For example user is not in the event.

### Bug 3

The token-exchange scenario like this:
- Login with offline access. Offline user session created
- Token exchange with the `subject_token` from the previous login and with `requested_token_type=access token`. Login is allowed
- Offline user session from previous step is logged-out
- Introspection endpoint called with exchanged token. Now I would expect exchanged token to be invalid (Similarly like we're doing for "online" session). However the exchanged access token is still valid.

**Cause:** The exchanged token does not have `sid` claim filled at all when it is exchanged from subject_token of some offline user session. So it is not linked to any session at all (In case of "online" the sessionType is `TRANSIENT` , but `sid` claim was set)

### Bug 4

The token-exchange scenario like this:
- Login by browser with client `subject_client`
- Doing token exchange with the `subject_token` for client `requester-client` and access token as `requested_token_type` -> SUCCESS
- After some time (EG. 10 seconds) , do SSO login in the browser to `requester-client`. At this moment, the clientSession is created for `requester-client` inside userSession (previous token-exchange did not created client session)
- Do token introspection with the access token from previous step. Introspection should be OK, but it fails (just because of SSO login and the fact that clientSession was created)
 
**Cause:** The fact that clientSession startup time of `requester-client` is newer than access-token startup time)

## Fixes and relevant changes

1) The `AuthenticationManager.verifyIdentityToken` was refactored a bit to move all the session related code and verifications in `UserSessionUtil.findUserSession` like introspection, user-info etc. Hopefully it is less error-prone in general right now with all the logic of session lookup/validation moved to single place.
**Test added:** `AdminClientTest.adminAuthUserDisabled()` (Testing scenario with disabled user for both online and offline session. Online session already rejected request before (correct), but offline session did not rejected request before changes (incorrect IMO)

2) Did some refactoring of introspection provider in general. Moved the introspection checks from `TokenManager` to introspection provider itself, so it can be overriden in `RefreshTokenIntrospectionProvider` (As refresh-token does not have context info in the token ID). Added some event assertions to `TokenIntrospectionTest` for this.

3) Added some new `AccessTokenContext.SessionType` types `ONLINE_TRANSIENT_CLIENT` and `OFFLINE_TRANSIENT_CLIENT` . They are used just during token-exchange right now. The `ONLINE_TRANSIENT_CLIENT` is used when token comes from "online" session, but there is not client session created (like during token-exchange for `requested_token_type` as access token). The `OFFLINE_TRANSIENT_CLIENT` is when token exchange is called with the `subject_token` coming from offline user session. Previously the access token session-type was `TRANSIENT`. With the new types, there is some more context as token-verification knows that it should lookup user session (either "online" or "offline"), but does not need to check it's client session.
**Test added:** `StandardTokenExchangeV2Test.testTransientOfflineSessionForRequester()` (We had similar test already for "online" user session)

4) With my changes, the exchanged token type is `ONLINE_TRANSIENT_CLIENT` . In this case, there is no verification of startup time of client-session compared with the access token.
**Test added:** `StandardTokenExchangeV2Test.testIntrospectionWithExchangedTokenAfterSSOLoginOfRequesterClient()`

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminClientTest.java [hunk 1]
```diff
@@ -213,6 +217,38 @@ public void adminAuthClientDisabled() throws Exception {
...
+                Assert.fail("Not expected to successfully get realm");
+            } catch (NotAuthorizedException nae) {
+                // Expected
+            }
+            try {
+                realm = adminClientOffline.realm(realmName).toRepresentation();
+                Assert.fail("Not expected to successfully get realm");
+            } catch (NotAuthorizedException nae) {
+                // Expected
+            }
```
Comment (rmartinc) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminClientTest.java:246]: I prefer to use `Assert.assertThrows` for this but it's just a nit-pick. :smile:

**Review by rmartinc — APPROVED** [review]
@mposolda LGTM! I never thought that it was necessary to know if the transient session was created from offline or online. Using the same code to retrieve the session is really nice.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminClientTest.java (hunk 1 above)
Comment (mposolda) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminClientTest.java:246]: Ah, ok. Will try to use it for the next time.
