### PR TITLE
Do not send attributes when unlocking the user

### LINKED ISSUE #31165: Re-enabling a temporarily locked user (brute-force) deletes all user properties and attributes
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When re-enabling a due to brute-force temporarily locked user, all the user attributes and properties are being deleted, only the username remains.

### Version

25.x / nightly

### Regression

- [X] The issue is a regression

### Expected behavior

User will be unlocked again, all attributes and properties are preserved.

### Actual behavior

User is unlocked again (expected), but all attributes and properties are deleted.

### How to Reproduce?

- create a fresh realm
- create a user with default properties and some additional attributes, assign a password
- enable brute-force-protection in the realm with temporary lockout
- try to authenticate with the created user, but with invalid password, until the max login failures are reached and the user is temporarily locked, e.g. with the account console
- in admin-ui, go to the user details, user is temporarily locked
- hit the switch to unlock the user -> two change requests are being sent to the server
- reload the browser to get a new, fresh set of user data, now the email, firstname and lastname on the first page are empty and all the other attributes are also gone!

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #31165

* Also removes the additional `DELETE` request because the `PUT` request that enables the user is already clearing the login failures for the user
* As the additional call to `brute-force/users/{user_id}` was removed the change is also firing an admin event to indicate when the user is unlocked
* There is one potential improvement here to how we handle updates when the account is temporarily disabled. It applies to the current state and the new changes herein introduced. When the user is temporarily disabled, the `enabled` field is set to `false`. If the administrator clicks the `Save` button it will end up disabling the user instead of keep the user enabled (in the database) so that when the temporary lockout is removed the user can log in again. Not changing this now and not sure if makes sense to fix that.

### CODE REVIEW

File: js/apps/admin-ui/src/user/UserForm.tsx [hunk 1]
```diff
@@ -93,12 +95,9 @@ export const UserForm = ({
   }, [user, setValue]);
 
   const unLockUser = async () => {
-    try {
-      await adminClient.attackDetection.del({ id: user!.id! });
-      addAlert(t("unlockSuccess"), AlertVariant.success);
-    } catch (error) {
-      addError("unlockError", error);
-    }
+    await adminClient.users.update({ id: user!.id! }, { enabled: true });
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserForm.tsx:98]: Should probably wrap this in a `try` `catch` to handle any errors.

File: js/apps/admin-ui/src/user/UserForm.tsx [hunk 2]
```diff
@@ -52,6 +52,7 @@ export type UserFormProps = {
   bruteForce?: BruteForced;
   userProfileMetadata?: UserProfileMetadata;
   save: (user: UserFormFields) => void;
+  refresh?: any;
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserForm.tsx:55]: Best to give this a proper type
```suggestion
  refresh?: () => void;
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/user/UserForm.tsx (hunk 2 above)
Comment (pedroigor) [reply js/apps/admin-ui/src/user/UserForm.tsx]: I had to add a check to make sure the `refresh` prop is defined before calling it. Hope it is OK.

File: services/src/main/java/org/keycloak/services/resources/admin/UserResource.java [hunk 3]
```diff
@@ -188,7 +188,11 @@ public Response updateUser(final UserRepresentation rep) {
             if (rep.isEnabled() != null && rep.isEnabled()) {
                 UserLoginFailureModel failureModel = session.loginFailures().getUserLoginFailure(realm, user.getId());
                 if (failureModel != null) {
-                    failureModel.clearFailures();
+                    session.loginFailures().removeUserLoginFailure(realm, user.getId());
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/UserResource.java:191]: Previously, we were issuing an update to clear the login failure state. Changing now to remove it from the cache. I can't see why we have two distinct operations to unlock users when brute force is enabled so I'm changing here to actually remove the entry from the cache.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/resources/admin/UserResource.java:191]: @ahus1 Do you have any idea or anything against about changing to remove the entry from the cache rather than just update it?

Comment (ahus1) [reply services/src/main/java/org/keycloak/services/resources/admin/UserResource.java]: On the Infinispan level, with ISPN 15 a remove should be safe as it will propagate to the remote site even if there is no entry in the remote cache. This wasn't the case with ISPN 14.

On the functional level, the old code didn't clear numFailures and failedLoginNotBefore, not sure how much a difference that makes.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/resources/admin/UserResource.java]: I mean https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java#L111. The values are set to `0`, that is why I don't see any difference when just removing the entry.

**Review by douglaspalmer — APPROVED** [review]
LGTM

File: js/apps/admin-ui/src/user/UserForm.tsx [hunk 4]
```diff
@@ -94,8 +96,11 @@ export const UserForm = ({
 
   const unLockUser = async () => {
     try {
-      await adminClient.attackDetection.del({ id: user!.id! });
+      await adminClient.users.update({ id: user!.id! }, { enabled: true });
       addAlert(t("unlockSuccess"), AlertVariant.success);
+      if (refresh) {
+        refresh();
+      }
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserForm.tsx:103]: If you need to call this method optionally you can use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
```suggestion
      refresh?.();
```

**Review by jonkoops — APPROVED** [review]

File: js/apps/admin-ui/src/user/UserForm.tsx (hunk 2 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/UserForm.tsx]: No problem!

**Review by mposolda — APPROVED** [review]
Approving and merging on behalf of @douglaspalmer and @jonkoops reviews and approvals.
