### PR TITLE
Sorting the chapters of the HA guide

### LINKED ISSUE #38721: Obsolete pinned guides and wrong ordering in downstream
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The pinned-guides contain obsolete entries. Also there missing hidden items lead to a wrong ordering of chapters in downstream.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

All hidden guides should be listed in the pinned guides.

### Actual behavior

Obsolete entries, and missing entries.

### How to Reproduce?

Look at pinned-guides

### Anything else?

I'll create a pull request

### PR DESCRIPTION
**Pull request by ahus1**
Closes #38721

### CODE REVIEW

**Comment by ahus1** [comment]
@ryanemerson - please review this PR when you have the time. It cleans up some old pinned guides, and adds checks so that this is detected earlier in the future. Thanks!

File: docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Context.java [hunk 1]
```diff
@@ -31,16 +32,30 @@ public Context(File srcDir) throws IOException {
...
+                if (Objects.equals(guide.getTileVisible(), Boolean.FALSE) && guide.getPriority() == Integer.MAX_VALUE) {
+                    throw new RuntimeException("Invisible tiles should be pinned or have an explicit priority: " + f.getName());
+                }
+
                 guides.add(guide);
             }
         }
 
+        if (guidePriorities != null && !guidePriorities.isEmpty()) {
+            throw new RuntimeException("File pinned-guides contained files that do no longer exist or are mis-spelled: " + guidePriorities.keySet());
```
Comment (ryanemerson) [inline docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Context.java:56]: There's a few typos here, maybe: `"File 'pinned-guides' contains files that no longer exist or are misspelled: " + ...`

File: docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Guide.java [hunk 2]
```diff
@@ -47,4 +48,12 @@ public int getPriority() {
     public void setPriority(int priority) {
         this.priority = priority;
     }
+
+    public Boolean getTileVisible() {
```
Comment (ryanemerson) [inline docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Guide.java:52]: Any reason why we're not using `boolean`? From the current usage it seems that we don't need the boxing. We can then just do `if (!guide.getTileVisible() && guide.getPriority() == Integer.MAX_VALUE) ...` in `Context.java`

Comment (ahus1) [reply docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Guide.java]: I thought I might need a tri-state value, but you are right that this can be simplified to a `boolean` after setting its default value to `true`. 

Changes applied in next commit.

**Comment by ahus1** [comment]
@ryanemerson - thank you for the comments, they should now be addressed. Please re-review when you have the time. Thanks!

**Review by ryanemerson — APPROVED** [review]

**Comment by ryanemerson** [comment]
LGTM, thanks!

**Review by pedroigor — APPROVED** [review]
