### PR TITLE
Fix requesting tokens with multiple organization scopes

### LINKED ISSUE #45900: Support multiple organization scopes in OIDC token requests
## Problem

Currently it is not possible to request a token for a specific subset of organizations. The only options are:
- `organization` scope - returns all organizations the user is a member of
- `organization:alias` scope - returns only one organization

There is no way to request tokens for more than one specific organization (e.g., `organization:Org1 organization:Org2`). When multiple organization scopes are sent, only the last one is processed.

## Solution

1. Modified `TokenManager` to collect all organization scopes into a `Set<String>`
2. Updated `OrganizationScope` to accept a collection of organization aliases

Now clients can request tokens with any combination of specific organizations.

## Testing

Integration test added to verify that multiple organization scopes are correctly processed.

### PR DESCRIPTION
**Pull request by vramik**
Closes #45900

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java [hunk 1]
```diff
@@ -777,10 +777,22 @@ public static boolean isValidScope(KeycloakSession session, String scopes, Autho
...
         if (Profile.isFeatureEnabled(Feature.ORGANIZATION)) {
-            if (rawScopes.stream().filter(scope -> scope.startsWith(ORGANIZATION)).count() > 1) {
-                return false;
+            List<String> orgScopes = rawScopes.stream()
+                    .filter(scope -> scope.equals(ORGANIZATION) || scope.startsWith(ORGANIZATION + ":"))
+                    .toList();
+
+            if (orgScopes.size() > 1) {
+                // multiple organization scopes - only allow if all are specific organizations (not ANY or ALL)
+                boolean hasAnyScope = orgScopes.stream().anyMatch(ORGANIZATION::equals);
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java]: We cannot assume the scope name is `organization` because you can have a client scope using a different name and the organization protocol mapper.

There is a method `org.keycloak.organization.protocol.mappers.oidc.OrganizationScope#resolveClientScope` that recognizes any scope as a "organization" scope if it is bound with a `org.keycloak.organization.protocol.mappers.oidc.OrganizationMembershipMapper`.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java]: FTR, org.keycloak.testsuite.organization.mapper.OrganizationOIDCProtocolMapperTest#testCustomOrganizationScopeName.

**Review by pedroigor — APPROVED** [review]
