### PR TITLE
Commit delete and insert statements together when updating jgroups-jd…

### LINKED ISSUE #38550: Cluster is not correctly formed with JDBC_PING2
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

When running clustering tests it intermittently (very rarely ~1/200 runs) happens that Keycloak nodes are not correctly clustered resulting in a split-brain which means invalidation messages are not delivered.

This seems to be an issue in JDBC_PING2, see [JGRP-2870](https://issues.redhat.com/browse/JGRP-2870) for more details.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Cluster must be formed with no excuses 🤣 

### Actual behavior

Cluster is sometimes not formed

### How to Reproduce?

Add a test like this to cluster tests:
```
    @Test
    public void testClusterFormed() {

        for (int i = 0; i < 100; i++) {
            log.infof("Iteration %d start", i);
            log.info("---------- Killing node");
            failure();
            log.info("---------- Node killed");
            WaitUtils.pause(100);
            log.info("---------- Starting node");
            failback();
            log.info("---------- Node started");
            WaitUtils.pause(100);

            for (ContainerInfo node : suiteContext.getAuthServerBackendsInfo()) {
                KeycloakTestingClient testingClientFor = getTestingClientFor(node);

                testingClientFor.server().run(CheckClusterSize::clusterSize);
            }
            log.infof("Iteration %d end", i);
        }
    }
```

and run workflow like this:
```
name: Stability - Clustering

on:
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"
  SUREFIRE_RERUN_FAILING_COUNT: 0
  SUREFIRE_RETRY: "-Dsurefire.rerunFailingTestsCount=0"

defaults:
  run:
    shell: bash

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

  clustering-integration-tests:
    name: Clustering IT
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 35
    env:
      MAVEN_OPTS: -Xmx1024m
    strategy:
      matrix:
        group1: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ]
        group2: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - id: integration-test-setup
        name: Integration test setup
        uses: ./.github/actions/integration-test-setup

      - name: Run cluster tests
        run: |
          ./mvnw test ${{ env.SUREFIRE_RETRY }} -Pauth-server-cluster-quarkus,db-postgres "-Dwebdriver.chrome.driver=$CHROMEWEBDRIVER/chromedriver" -Dsession.cache.owners=2 -Dtest=RoleInvalidationClusterTest#testClusterFormed -pl testsuite/integration-arquillian/tests/base
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mhajas**
…bc-ping table

Closes #38550
Signed-off-by: Michal Hajas <mhajas@redhat.com>

### CODE REVIEW

**Comment by ahus1** [comment]
@mhajas - looks good to me. Added a commit with a rollback on SQL Exceptions. The jobs have been failing due to some JBoss Maven Repository glitches. Let's see if they complete now.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/impl/KEYCLOAK_JDBC_PING2.java [hunk 1]
```diff
@@ -6,22 +6,35 @@
...
-                    if (isAutocommit) connection.setAutoCommit(false);
+                    if (isAutocommit) {
+                        // Always use a transaction for the delete+insert to make it atomic
+                        // to avoid the short moment where there is no entry in the table.
+                        connection.setAutoCommit(false);
+                    }
                     delete(connection, clustername, data.getAddress());
                     insert(connection, data, clustername);
-                    if (isAutocommit) connection.commit();
+                    connection.commit();
```
Comment (mhajas) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/impl/KEYCLOAK_JDBC_PING2.java:31]: Should we add `if (isAutocommit)` here as well? My reasoning here was that if we have a connection that was  set to `automcommit == false` by someone else the commit is called somewhere else too.

Comment (ahus1) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/impl/KEYCLOAK_JDBC_PING2.java:31]: OK, I follow you on this one. I'll push one more commit.

**Comment by belaban** [comment]
Ooops, didn't see the other commits. Tell me when you're done, then I'll apply these change to JDBC_PING2 again!

**Comment by belaban** [comment]
@ahus1 Yes, I'm going to add this to the codebase (master and 5.3.17).
No, `writeToDB()` is the only method that benefits from this. Note that stored procedures would do the same, but at the expense of not being portable.

**Comment by belaban** [comment]
Done. Do you need a 5.3.17 release?

**Review by ahus1 — APPROVED** [review]
Great work! This came a long way!

**Comment by belaban** [comment]
FYI, I just released 5.3.17

**Comment by ahus1** [comment]
@mhajas - please track that this is updated in upstream ISPN for the 15.0.x branch. Thanks!
