### PR TITLE
Stabilize Infinispan container startup and client connecting to server

### LINKED ISSUE #31972: Unstable test ExternalInfinispanTest
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

The test is unstable, and sometimes the LB check doesn't return 503.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Test should succeed

### Actual behavior

```
2024-08-07 12:27:27,815 INFO  [org.infinispan.HOTROD] (ForkJoinPool.commonPool-worker-2) ISPN004108: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
2024-08-07 12:27:27,984 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2024-08-07 12:27:28,073 INFO  [org.infinispan.HOTROD] (ForkJoinPool.commonPool-worker-2) ISPN004021: Infinispan version: Infinispan 'I'm Still Standing' 15.0.5.Final
2024-08-07 12:27:28,300 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-2) ISPN004006: Server sent new topology view (id=56528015, age=0) containing 1 addresses: [127.0.0.1/<unresolved>:11222]
2024-08-07 12:27:28,303 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-2) ISPN004014: New server added(127.0.0.1/<unresolved>:11222), adding to the pool.
2024-08-07 12:27:28,304 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-2) ISPN004016: Server not in cluster anymore(localhost/<unresolved>:11222), removing from the pool.
2024-08-07 12:27:28,345 WARN  [org.infinispan.client.hotrod.impl.RemoteCacheImpl] (ForkJoinPool.commonPool-worker-2) ISPN004116: Client cannot marshall the server's key media type ('application/x-java-object'). This could cause poor performance.
2024-08-07 12:27:28,433 INFO  [org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory] (ForkJoinPool.commonPool-worker-2) Infinispan Protostream schema uploaded for the first time.
2024-08-07 12:27:28,497 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-6) ISPN004006: Server sent new topology view (id=965700979, age=0) containing 1 addresses: [127.0.0.1/<unresolved>:11222]
2024-08-07 12:27:28,498 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-6) ISPN004014: New server added(127.0.0.1/<unresolved>:11222), adding to the pool.
2024-08-07 12:27:28,498 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-6) ISPN004016: Server not in cluster anymore(localhost/<unresolved>:11222), removing from the pool.
2024-08-07 12:27:28,554 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-7) ISPN004006: Server sent new topology view (id=965700979, age=0) containing 1 addresses: [127.0.0.1/<unresolved>:11222]
2024-08-07 12:27:28,555 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-7) ISPN004014: New server added(127.0.0.1/<unresolved>:11222), adding to the pool.
2024-08-07 12:27:28,555 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-7) ISPN004016: Server not in cluster anymore(localhost/<unresolved>:11222), removing from the pool.
2024-08-07 12:27:28,573 ERROR [org.infinispan.HOTROD] (HotRod-client-async-pool-1-11) ISPN004007: Exception encountered. Retry 3 out of 3: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/[0:0:0:0:0:0:0:1]:11222
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:715)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:692)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:491)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Tests randomly fail, see https://github.com/keycloak/keycloak/actions/runs/10265585450/job/28405547785?pr=31678

### Anything else?

I'll create a PR

### PR DESCRIPTION
**Pull request by ahus1**
Closes #31972

### CODE REVIEW

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/InfinispanContainer.java [hunk 1]
```diff
@@ -51,10 +58,29 @@ public InfinispanContainer() {
             withImagePullPolicy(PullPolicy.alwaysPull());
         }
 
-
-        //order of waitingFor and withStartupTimeout matters as the latter sets the timeout for WaitStrategy set by waitingFor
-        waitingFor(Wait.forLogMessage(".*Infinispan Server.*started in.*", 1));
-        withStartupTimeout(Duration.ofMinutes(5));
+        // Waiting for the port to become available as waiting for the log was sometimes unreliable and seems to miss log messages at the beginning.
+        waitingFor(new AbstractWaitStrategy() {
```
Comment (ahus1) [inline quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/InfinispanContainer.java:62]: I tried to wait for a port binding and an open port, but that didn't work well as it conflicts with the `host` networking used here.

**Comment by pruivo** [comment]
It would take a step further and use the Infinispan provider implementation:
https://github.com/infinispan/infinispan/blob/aaccf153e5406e05d7463e23023123f47f2713c5/server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanContainer.java
The logic to create the caches can be in `org.keycloak.it.junit5.extension.CLITestExtension` class.

**Comment by ahus1** [comment]
@ryanemerson / @pruivo - I've adopted the advice to pick up the Infinispan class. I also found a way to avoid the host network type. I'd like to avoid much more rework in the testsuite though. 

If one of you could review this PR, that would be great. Thanks.

**Review by pruivo — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]
