### PR TITLE
Fix authenticatorConfig for javascript providers

### LINKED ISSUE #20005: JavaScript Authenticator Providers not updated automatically on build and SQL error when removing/adding in flow
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

If you package a Javascript provider and deploy it to a jar, add the scripts to a flow, and then edit and redeploy the script, re build the server and start, the scripts is still in the old versions

Workaround : Remove the scripts from the flow and add it again is the only fix I found.

Edit : Actually this workaround worked the first time but now it's even worst

If I remove the Script from the flow and if I add it again I got the error

```
2023-04-27 20:11:36,510 WARN  [org.mariadb.jdbc.message.server.ErrorPacket] (executor-thread-4) Error: 1062-23000: Duplicate entry 'script-role-based-access.js' for key 'PRIMARY'
2023-04-27 20:11:36,511 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-4) SQL Error: 1062, SQLState: 23000
2023-04-27 20:11:36,511 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-4) (conn=542) Duplicate entry 'script-role-based-access.js' for key 'PRIMARY'
```

`script-role-based-access.js' is the name of my scripts here

### Version

21.1.1

### Expected behavior

Should update the script

### Actual behavior

Script already in the flow are not updated

### How to Reproduce?

- Install a Javascript providers (in my case an authenticator)
- Start the server and the script to a flow (in my case Browser flow copy)
- edit the content of the script, rebuild the jar `my-scripts.jar`
- update`providers/my-scripts.jar` and rebuild `bin/kc.sh build --features=scripts`then start

Now if you go in your flow and display the preview of your script, you still see the previous content

I tried to remove/rename the jar without success

Only fix for me was to remove the script from the flow and add it again (which is an easy workaround) but this doesn't always works second time I had

```
2023-04-27 20:11:36,510 WARN  [org.mariadb.jdbc.message.server.ErrorPacket] (executor-thread-4) Error: 1062-23000: Duplicate entry 'script-role-based-access.js' for key 'PRIMARY'
2023-04-27 20:11:36,511 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-4) SQL Error: 1062, SQLState: 23000
2023-04-27 20:11:36,511 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-4) (conn=542) Duplicate entry 'script-role-based-access.js' for key 'PRIMARY'
```

Fix was 

`DELETE FROM AUTHENTICATOR_CONFIG_ENTRY WHERE AUTHENTICATOR_ID='script-role-based-access.js';`
`DELETE FROM AUTHENTICATOR_CONFIG WHERE ID='script-role-based-access.js';`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
Closes #20005

Few fixes for authenticatorConfig of javascript providers. The first 2 issues reported in #20005. Fixed the other 2 things as a side-effect when looking at this:

1) It was not possible to create same script execution in multiple realms. Or even in multiple authentication flows of same realm.
2) It was not possible to copy authentication flow with some script execution

3) Endpoint `Response addExecution(AuthenticationExecutionRepresentation model)` did not create default configuration for script execution. It worked correctly only for other endpoint `void addExecution(@PathParam("flowAlias") String flowAlias, Map<String, String> data);`, which is used by admin console

4) It was possible to update authentication configuration of javascript execution and update it in the DB (it was even possible to update the script itself in the DB). The `DeployedScriptAuthenticatorFactory` uses hardcoded config from the deployment, but still, it was strange that config is possible to be updated.

Now all javascript executions uses "shared" authenticator config, which is fine as this config should not be updateable at all as it should be based on the deployed javascript. Also make sure that it is read-only and it is not possible to update such config with the hand-written javascript.

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java [hunk 1]
```diff
@@ -419,15 +420,21 @@ public static void copy(RealmModel realm, String newName, AuthenticationFlowMode
                     throw new IllegalStateException("Authentication execution configuration not found");
                 }
 
-                config.setId(null);
+                ProviderFactory pf = getProviderFactory(session, to, execution.getAuthenticator());
+                if (pf instanceof ConfiguredProvider && ((ConfiguredProvider) pf).getConfig() != null) {
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java:424]: @mposolda Wouldn't be good to check READ_ONLY_CONFIGURATION here too?

File: services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java [hunk 2]
```diff
@@ -560,15 +583,17 @@ public Response addExecutionToFlow(@Parameter(description = "Alias of parent flo
                 // useful for internal providers that already provide a built-in configuration
                 AuthenticatorConfigRepresentation configRepresentation = ModelToRepresentation.toRepresentation(
                         config);
-                newExecutionConfig(execution.getId(), configRepresentation).close();
+
+                if (config.getId() != null && realm.getAuthenticatorConfigById(config.getId()) != null) {
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java:587]: And same here? Just reuse config if READ_ONLY_CONFIGURATION? I don't know if there are cases when there is a default config, but it can be modified to have two different configs later...

**Review by rmartinc — COMMENTED** [review]
Just one question, not sure if it's really an issue though. Can be possible to have a default config but it can be modified later?

**Comment by mposolda** [comment]
@rmartinc Updated this, so that `AuthenticatorConfigModel` of deployed providers are not saved into DB at all. This is most proper approach as it avoids the situation, when the config from DB is out-of-sync from the deployed config. Previous approach with stuff saved in the DB might cause some issues, like for instance when the script is re-deployed with slightly different javascript code, the DB would still contain the previous (now outdated) javascript code etc.

Instead I've added `DeployedConfigurationsProvider` in this PR, which allows to "register" such `AuthenticatorConfigModel` at runtime (during server startup) . When there is lookup for `AuthenticatorConfigModel` it will use the "deployed" config instead of the config from the DB.

**Review by rmartinc — APPROVED** [review]
@mposolda LGTM now!

**Comment by mposolda** [comment]
@rmartinc Thanks!
