### PR TITLE
[OID4VCI]: Cannot issue vc of type oid4vc_natural_person

### LINKED ISSUE #43832: Cannot issue vc of type oid4vc_natural_person
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

oid4vc_natural_person has no attributes at all. It is however still included in oid4vc metadata.

```
client_scope_id=$(kcadm get "realms/${realm}/client-scopes" 2>/dev/null | jq -r ".[] | select(.name==\"${credential_id}\") | .id")
kcadm get "realms/${realm}/client-scopes/${client_scope_id}" 2>/dev/null | jq .
{
  "id": "39206d9e-1e2f-4a5f-a0e0-341200405421",
  "name": "oid4vc_natural_person",
  "description": "OIDC$VP Scope, that adds all properties required for a natural person.",
  "protocol": "oid4vc",
  "attributes": {},
  "protocolMappers": [
    {
      "id": "db27723f-2533-4302-9ac5-a178de509399",
      "name": "first-name",
      "protocol": "oid4vc",
      "protocolMapper": "oid4vc-user-attribute-mapper",
      "consentRequired": false,
      "config": {
        "claim.name": "firstName",
        "userAttribute": "firstName",
        "aggregateAttributes": "false"
      }
    },
    {
      "id": "dfcf9152-cb3b-442b-8e2d-1ad02d29ee6a",
      "name": "last-name",
      "protocol": "oid4vc",
      "protocolMapper": "oid4vc-user-attribute-mapper",
      "consentRequired": false,
      "config": {
        "claim.name": "familyName",
        "userAttribute": "lastName",
        "aggregateAttributes": "false"
      }
    },
    {
      "id": "e86f3c29-a6e2-4086-a26b-beb93a14aac4",
      "name": "email",
      "protocol": "oid4vc",
      "protocolMapper": "oid4vc-user-attribute-mapper",
      "consentRequired": false,
      "config": {
        "claim.name": "email",
        "userAttribute": "email",
        "aggregateAttributes": "false"
      }
    },
    {
      "id": "815c0dcd-2573-4e84-af32-dbebd48a5331",
      "name": "subject id",
      "protocol": "oid4vc",
      "protocolMapper": "oid4vc-subject-id-mapper",
      "consentRequired": false,
      "config": {
        "claim.name": "id"
      }
    }
  ]
}
```

Attempted issuance of this type fails with 

```
CredentialRequest: {"credential_configuration_id":"oid4vc_natural_person","proofs":{"jwt":["eyJ0eXAiOiJvcGVuaWQ0dmNpLXByb29mK2p3dCIsImFsZyI6IkVTMjU2IiwiandrIjp7Imt0eSI6IkVDIiwidXNlIjoic2lnIiwiY3J2IjoiUC0yNTYiLCJraWQiOiJ1QkhuRkszdktIWXBsNnllYUhSSC05ZUc4elJocGtxYmJCLUhJTWhmeVFNIiwieCI6Ikg0QjlaSFFJU1BSeTdKRTM5S0JLS3RjY0x0M054a3V3VXZISnhIdHdESzgiLCJ5IjoiUVhwWHFXX2JrVlJNQk5lRmwwRTJLc1ZtR3ZTYzFsN0tzVUJhbWtjS2FNQSIsImFsZyI6IkVTMjU2In19.eyJhdWQiOiJodHRwczovL29hdXRoLmxvY2FsdGVzdC5tZS9yZWFsbXMvb2lkNHZjaSIsImV4cCI6MTc2MTc0ODM1OCwiaWF0IjoxNzYxNzQ4MDU4LCJub25jZSI6ImV5SmhiR2NpT2lKRlV6STFOaUlzSW10cFpDSWdPaUFpYVhwRGNHSjRRa1J1WVc5aFdsbHZWell4VEZRM2JTMVhWRFpGUm1aMWNFWXdZMHR4ZW5OU016UnlUU0o5LmV5SmxlSEFpT2pFM05qRTNORGd4TVRjc0ltbHpjeUk2SW1oMGRIQnpPaTh2YjJGMWRHZ3ViRzlqWVd4MFpYTjBMbTFsTDNKbFlXeHRjeTl2YVdRMGRtTnBJaXdpWVhWa0lqb2lhSFIwY0hNNkx5OXZZWFYwYUM1c2IyTmhiSFJsYzNRdWJXVXZjbVZoYkcxekwyOXBaRFIyWTJrdmNISnZkRzlqYjJ3dmIybGtOSFpqTDJOeVpXUmxiblJwWVd3aUxDSnpZV3gwSWpvaWMyNVliQ3MzVm1kMk5uSlZabTFqZGpSS01sWk9PRFI0Y2tVemRVRnViV3czWWtvMmVWZE9TRkZXV2pCS1dYTm5ObEpZUldOVE0wd3JUME4xUTFrMEt6QjBhVk1pTENKemIzVnlZMlZmWlc1a2NHOXBiblFpT2lKb2RIUndjem92TDI5aGRYUm9MbXh2WTJGc2RHVnpkQzV0WlM5eVpXRnNiWE12YjJsa05IWmphUzl3Y205MGIyTnZiQzl2YVdRMGRtTXZibTl1WTJVaWZRLjM5aDJENl9YUVFZYUpMM1FfekdnVU9heEZCT2RrY0U0T0dKVlZ2MW9lTjY3bTZ6bFlLX3pWNTNZWHdJR194QUZyZnhFdktDVTlSdW5HSVFGM3VuQ2xRIn0.b7gXHM7aIZ1Kg5wOD0TRyWNwRmckc3gQ4nmry0-Fc9sYaIIN3rENpaCblrS-m_I1gXTCs-dIe7KaIQmG0hAeRg"]}}

Unexpected response status: 400  {"error":"UNKNOWN_CREDENTIAL_CONFIGURATION"}
``` 

### Version

26.4.2

### Regression

- [ ] The issue is a regression

### Expected behavior

oid4vc_natural_person should have its attributes initialized with sensible defaults.
Note, these default attributes are present when a new client scope is created through kcadm

### Actual behavior

see above

### How to Reproduce?

Introspect the client scope as above

### Anything else?

CrossRef: https://github.com/tdiesler/nessus-identity/issues/330

### PR DESCRIPTION
**Pull request by tdiesler**
closes #43832

### CODE REVIEW

**Comment by mposolda** [comment]
@Awambeng @forkimenjeckayang @IngridPuppet @francis-pouatcha @tnorimat Anyone available to review the PR please?

**Comment by tnorimat** [comment]
@tdiesler Hello, according to [Contributing to Keycloak - Developer's Certificate of Origin](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#developers-certificate-of-origin), could you add sign-off the commit?

**Review by tnorimat — CHANGES_REQUESTED** [review]
Hello, it seems that this PR lacks the integration test for that modification of the codes. Could you add that?

According to [Contributing to Keycloak](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#contributing-to-keycloak), a contributor of a PR need to add its integration test like:
https://github.com/keycloak/keycloak/pull/34992/files#diff-aa14f84282bde1e574a48da6c46b8929cafe5615e25726bcb33c34af520dd350

**Comment by tnorimat** [comment]
@Awambeng @forkimenjeckayang @IngridPuppet @francis-pouatcha Hello, you are more familiar with the topic of the PR than me. So I would appreciate it if you could review the PR.

**Comment by tdiesler** [comment]
Added some test coverage and signed-off

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.keycloak.testsuite.oid4vc.issuance.signing;
+
+import org.junit.Test;
+import org.keycloak.protocol.oid4vc.issuance.OID4VCIssuerWellKnownProvider;
+import org.keycloak.protocol.oid4vc.model.*;
+import org.slf4j.Logger;
```
Comment (Awambeng) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java]: This import doesn’t seem to be used. Could you please remove it?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+import org.slf4j.LoggerFactory;
+
+import java.util.Map;
```
Comment (Awambeng) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java]: same here.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+                        Claim claim = jwtVcClaims.get("firstName");
+                        assertEquals("firstName", claim.getPath().get(0));
+                        assertFalse(claim.isMandatory());
+                        assertNull(claim.getDisplay());
+                    }
+                    {
+                        Claim claim = jwtVcClaims.get("familyName");
+                        assertEquals("familyName", claim.getPath().get(0));
+                        assertFalse(claim.isMandatory());
+                        assertNull(claim.getDisplay());
```
Comment (Awambeng) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java:91]: Instead of repeating four nearly identical blocks for each claim, consider extracting a small helper method to make the test more concise and maintainable:

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+import org.keycloak.protocol.oid4vc.issuance.OID4VCIssuerWellKnownProvider;
+import org.keycloak.protocol.oid4vc.model.*;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import java.util.Map;
+import java.util.function.Function;
+import java.util.stream.Collectors;
+
+import static org.junit.Assert.*;
```
Comment (Awambeng) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java]: use explicit static imports for better readability.

**Review by Awambeng — CHANGES_REQUESTED** [review]
@tdiesler Thank you very much for the PR! I left a few minor comments. Could you please check them?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java (hunk 3 above)
Comment (tdiesler) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java:91]: If you don't mind, I prefer it that way - analogous to OID4VCSdJwtIssuingEndpointTest.testGetSdJwtConfigFromMetadata

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java (hunk 4 above)
Comment (tdiesler) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java]: done

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java (hunk 3 above)
Comment (Awambeng) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtPreInstalledNaturalPersonTest.java:91]: > If you don't mind, I prefer it that way - analogous to OID4VCSdJwtIssuingEndpointTest.testGetSdJwtConfigFromMetadata

Sure, that’s fine. It makes sense

**Review by Awambeng — APPROVED** [review]
LGTM

**Review by tnorimat — APPROVED** [review]
LGTM

**Review by mposolda — APPROVED** [review]
@tdiesler @tnorimat @Awambeng Thanks for the updates and review!
