### PR TITLE
Fixed dropdown form in clients authorization policies tab

### LINKED ISSUE #26363: Search dialog for authorization policy is wrong?
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

The "search" dialog for authorization policies appears to be wrong. 
Firstly the search field is called "search for permissions". Then the content appears wrong, it has entry fields for permission and scope. I suspect that this is a copy and paste error from the "permissions" list, where those are probably correct.

image

### Version

23.0.4

### Expected behavior

A more appropriate search dialog

### Actual behavior

A confusing search dialog

### How to Reproduce?

Create a client and enable authorization. On the "Authorization" tab select the nested "Policies" tab. Look at the search button and press.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/26363

### CODE REVIEW

File: js/apps/admin-ui/src/clients/authorization/SearchDropdown.tsx [hunk 1]
```diff
@@ -33,13 +33,17 @@ type SearchDropdownProps = {
   search: SearchForm;
   onSearch: (form: SearchForm) => void;
   isResource?: boolean;
+  isPolicies?: boolean;
+  isPermissions?: boolean;
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/authorization/SearchDropdown.tsx:37]: Rather than having a bunch of separate booleans, perhaps it would make sense to have a single 'type' field? This reduces the complexity of conditions in this component. 
```suggestion
  type:  'resource' | 'policy' | 'permission';
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/clients/authorization/SearchDropdown.tsx (hunk 1 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/clients/authorization/SearchDropdown.tsx]: yeah, sounds good to me!

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by edewit — APPROVED** [review]
