### PR TITLE
Use encryption keys rather than sig for crypto in SAML

### LINKED ISSUE #13606: Keycloak uses incorrect encryption keys as SAML identity brokers in SPSSODescriptor
### Describe the bug

Keycloak should send a SPSSODescriptor with a signature and an encryption key to a SAML identity provider. Instead of using a realm signature key for <md:KeyDescriptor use="signing"> and a realm encryption key for <md:KeyDescriptor use="encryption">, realm signing keys are used for signing AND encryption. Realm encryption keys are not considered at all.
I believe that the error is related to the following code location: 
https://github.com/keycloak/keycloak/blob/17.0.1/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
```
session.keys().getKeysStream(realm, KeyUse.SIG, Algorithm.RS256)
                    .filter(Objects::nonNull)
                    .filter(key -> key.getCertificate() != null)
                    .sorted(SamlService::compareKeys)
                    .forEach(key -> {
                        try {
                            Element element = SPMetadataDescriptor
                                    .buildKeyInfoElement(key.getKid(), PemUtils.encodeCertificate(key.getCertificate()));
                            signingKeys.add(element);

                            if (key.getStatus() == KeyStatus.ACTIVE) {
                                encryptionKeys.add(element);
                            }
                        } catch (ParserConfigurationException e) {
                            logger.warn("Failed to export SAML SP Metadata!", e);
                            throw new RuntimeException(e);
                        }
                    });
```
Instead of KeyUse.SIG probably KeyUse.ENC should be used.

### Version

19.0.1

### Expected behavior

Realm signing keys are used in the SPSSODescriptor only under KeyDescriptor use="signing" and realm encryption keys under KeyDescriptor use="encryption".

### Actual behavior

Currently in the SPSSODescriptor realm signing keys are used for signing AND encryption while realm encryption keys are not used at all.

### How to Reproduce?

Create an active realm rsa key for signing and another one for encryption. 
Add a SAML identity provider and call the SPSSODescriptor of this identity provider:
<host>/auth/realms/<realm-name>/broker/<identity-provider>/endpoint/descriptor

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mhajas**
This PR intends to replace PR #8330 

The code is slightly refactored to not add new methods to `KeyManager` API.

It also provides a backward compatibility mode which can be enabled using environment variables and provides the behaviour that was present prior to fixing this issue. The mode would be present only for a limited amount of time and allows users to smoothly migrate to new encryption keys. The mode is expected to be removed with Keycloak 24.

if we agree this PR is the way to go I will create a documentation PR and also an issue for KC 24 to remove the mode.

### CODE REVIEW

File: services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java [hunk 1]
```diff
@@ -362,25 +366,30 @@ public Response export(UriInfo uriInfo, RealmModel realm, String format) {
...
-                            if (key.getStatus() == KeyStatus.ACTIVE) {
-                                encryptionKeys.add(element);
-                            }
+                            return SPMetadataDescriptor.buildKeyInfoElement(key.getKid(), PemUtils.encodeCertificate(key.getCertificate()));
+                        } catch (ParserConfigurationException e) {
+                            logger.warn("Failed to export SAML SP Metadata!", e);
+                            throw new RuntimeException(e);
+                        }
+                    }).forEach(signingKeys::add);
+            session.keys().getKeysStream(realm, KeyUse.ENC, JWEConstants.RSA_OAEP)
```
Comment (stianst) [inline services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:381]: A bit odd to use `JWEConstants` here. Perhaps we should add `RSA-OAEP` to `Algorithm` instead?

File: server-spi-private/src/main/java/org/keycloak/models/utils/DefaultKeyProviders.java [hunk 2]
```diff
@@ -131,6 +132,25 @@ public static void createProviders(RealmModel realm, String privateKeyPem, Strin
...
+            configEnc.putSingle("priority", "100");
+            configEnc.putSingle("privateKey", privateKeyPem);
+            if (certificatePem != null) {
+                configEnc.putSingle("certificate", certificatePem);
+            }
+            rsaEnc.setConfig(configEnc);
+
+            realm.addComponentModel(rsaEnc);
+        }
+
```
Comment (stianst) [inline server-spi-private/src/main/java/org/keycloak/models/utils/DefaultKeyProviders.java:153]: I'm thinking we shouldn't do this, as it puts the server into an non-recommended setup where the same keys are used for signing and encryption.

In the backwards compatibility mode we just use the signature keys as previously, and we should just document how folks can create the proper encryption keys required using the component model in the realm representation, or through the UI.

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java [hunk 3]
```diff
@@ -404,6 +412,17 @@ private String getEntityId(UriInfo uriInfo, RealmModel realm) {
...
         }
 
+        private List<KeyWrapper> getEncryptionKeys() {
+            if (Boolean.getBoolean("keycloak.saml.backward.compatible.encryption")) {
+                KeyManager.ActiveRsaKey keys = session.keys().getActiveRsaKey(realm);
+            }
+            return session.keys()
+                    .getKeysStream(realm, KeyUse.ENC, JWEConstants.RSA_OAEP)
+                    // Sort keys so the active key is the first one
+                    .sorted(SamlService::compareKeys)
```
Comment (stianst) [inline services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:422]: If for some reason multiple keys are marked as active we use priority to pick the best one. Is this considered here?

Is this method only used to decrypt assertions? If this is also used to encrypt assertions this would result in passive keys potentially being used to encrypt assertions.

I would suggest renaming this to getDecryptionKeys perhaps?

**Comment by stianst** [comment]
@mhajas would be good to get someone that knows the SAML code-base better than me to also do a review here. Perhaps @sguilhen or @hmlnarik could help?

File: server-spi-private/src/main/java/org/keycloak/models/utils/DefaultKeyProviders.java (hunk 2 above)
Comment (mhajas) [reply server-spi-private/src/main/java/org/keycloak/models/utils/DefaultKeyProviders.java:153]: This code is used only with the deprecated [RealmRepresentation fields](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java#L101-L106). Removing this would mean we need to migrate all testsuite representations to use the new way of defining keys (using ComponentModel) or somehow hack the importing to double the keys before. 

I would probably prefer to leave this as is. Maybe we can mark this code as deprecated to make sure we remove it as part of the future issue I plan to create for removing the fields I mentioned above.

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java (hunk 3 above)
Comment (mhajas) [reply services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:422]: For SAML we never encrypt using realm keys. We encrypt by a key provided by the client/SP.

**Comment by cgeorgilakis** [comment]
I am member of the team done [the previous PR](https://github.com/keycloak/keycloak/pull/8330) that you want this PR to replace it.

@mhajas I have an important question. I see that you have replaced the search for encryption keys with KeyType.RSA with encryption keys with algorithm RSA-OAEP. Is these correct? Why not having RSA keys with different algorithm? Fe we have encryption keys with algorithm RSA-OAEP-256.

Otherwise, this PR looks good to me in the part of SAML encryption keys. For testing it, do we need any extra configuration in Keycloak? How Keycloak will know if we use encryption keys for crypto in SAML or we use previous Keycloak behaviour?

**Comment by mhajas** [comment]
Thank you for your comment @cgeorgilakis. Our aim in Keycloak is to have one key per algorithm. The problem with obtaining keys based on type is that it can provide a KeyPair intended to be used with signature algorithm `RS256` for encryption which is something we want to avoid. Therefore we want to always specify the algorithm when obtaining keys.

Your point is correct though, with the current implementation it is not possible to use `RSA-OAEP-256` here. What we need here is to obtain the `Algorithm` attribute of `EncryptionMethod` element we are trying to decrypt and load the key based on it. I will work on this to include this option in this PR.

**Comment by cgeorgilakis** [comment]
@mhajas I agree with your response.

**Review by sguilhen — COMMENTED** [review]
From a SAML perspective the changes proposed here look fine. My only comment would be about possibilities to use algorithms other than RSA_OAEP, but this has already been adressed in the discussion between @mhajas and @cgeorgilakis

**Comment by dpulrichth** [comment]
So excited to see this being actively worked on 👍 Thanks to everyone involved. Any chance this will be released as part of Keycloak 21?

**Comment by mhajas** [comment]
@cgeorgilakis I was looking into using `RSA-OAEP-256` but I found out xmlenc spec specifies only two algorithms for key transport: https://www.w3.org/TR/2002/REC-xmlenc-core-20021210/Overview.html#rsa-1_5 and https://www.w3.org/TR/2002/REC-xmlenc-core-20021210/Overview.html#rsa-oaep-mgf1p. Can you please provide more details on how you use `RSA-OAEP-256`?

**Comment by cgeorgilakis** [comment]
@mhajas I do not know if using RSA-OAEP-256 is against SAML key transport protocols.

Keycloak gives the ability to use RSA-OAEP-256 algorithm for java-keystore keys without extension between OIDC and SAML. Maybe 2 keys with different priority will be a solution. RSA-OAEP-256 is a secure algorithm. So we have used RSA-OAEP-256 algorithm for SAML encryption for over 5000 SAML IdPs from [EGI](https://www.egi.eu/) - mainly European Academical IdPs - without any problem in production. We use version 18 plus [our PR](https://github.com/keycloak/keycloak/pull/8330).
I propose to be able to use RSA-OAEP-256 algorithm.

**Comment by mhajas** [comment]
@cgeorgilakis Maybe I misunderstood something, but that is the wrong thing about the PR you proposed, you are using keys generated for usage with the  `RSA-OAEP-256` algorithm, but SAML code then uses the algorithm based on the `EncryptionMethod` element inside the resulting document and it is not guaranteed there is `RSA-OAEP-256` used. Would it be possible to intercept a document generated by your IDP and share the value of the Algorithm attribute in `EncryptionMethod` element? For example, what we use in our testsuite is something like this:
```xml
<ds:KeyInfo>
    <xenc:EncryptedKey>
        <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p"/>
        <xenc:CipherData>
            <xenc:CipherValue>....</xenc:CipherValue>
        </xenc:CipherData>
    </xenc:EncryptedKey>
</ds:KeyInfo>
```

**Comment by cgeorgilakis** [comment]
@mhajas our IdPs send the same algorithm as in your example.
So Keycloak must check also that the algorithm used from the SAML IdP to be the same as the SP metadata algorithm?
To be honest, we proposed this PR because SAML IdPs do not accept same keys for signing and encryption for SP metadata configured.

Proceed with needed changes. Could you only describe in the issue the final changes from upstream behavior?

**Comment by mhajas** [comment]
Thank you for more details @cgeorgilakis! Keycloak must use the same decryption algorithm as the IDP when encrypting the key. I will proceed with the changes and then ask for a review.

**Comment by mhajas** [comment]
### Summary of changes

The latest state contain the following changes:
- When searching for a decryption key we search for keys based on `EncryptionMethod`, [we load the algorithm from the encrypted element and search for keys only for that specific algorithm](https://github.com/keycloak/keycloak/pull/15985/files#diff-99dfac8a86033275f8efa3756d84557fb488d37cbf0527dbfa6e051b852132d6R138-R150). (the link contains also an example of an encrypted message)
- Currently, we support only [two algorithms](https://github.com/keycloak/keycloak/pull/15985/files#diff-4c0955a01df391adbdfd38f240b552ebdc7e0a63dfe5717d80ae1140f90e0878R33-R34) for key decryption (if other algorithms will be necessary we can add those as enhancement)
- When generating SP metadata we never export keys for different algorithms than the supported two mentioned in the previous item. Also, within `KeyDescriptor` we add `EncryptionMethod` so IDP knows which algorithm to use with the exported key. [Here](https://gist.github.com/mhajas/9b57577a012c831e6fcf927ce24291fa) is an example of generated metadata (it contains 3 encryption keys: 2 for [RSA-OAEP](http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p) and 1 for [RSA1.5](http://www.w3.org/2001/04/xmlenc#rsa-1_5)). Keycloak will export all enabled keys generated for supported algorithms unless SP configuration requests a specific algorithm, see the following item
- Recently, it is possible to choose [what algorithm IDP -> SP communication uses](https://github.com/keycloak/keycloak/issues/16324) within SP config, this PR follows up on this and enforces the desired algorithm in the metadata generator and also when searching for keys for decrypting
- By default Keycloak never uses signing keys for decryption, to restore the previous behaviour there is a backward compatibility switch [`keycloak.saml.deprecated.encryption`](https://github.com/keycloak/keycloak/pull/15985/files#diff-372f29884b6defbcc22974ca30286c5bc06a7257600f7a9b7b5e44441520dcd8R153). This switch will change Keycloak to use only active signing key for key decryption. It will not change the behaviour of the metadata generator, if this is necessary please let me know and I will update PR accordingly. 

@cgeorgilakis could you please have a look at the above ^ and the code changes and let me know whether this will address your concerns?

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java [hunk 4]
```diff
@@ -433,11 +436,21 @@ protected Response handleLoginResponse(String samlResponse, SAMLDocumentHolder h
...
+                        /* This code is deprecated and will be removed in Keycloak 24 */
+                        if (DEPRECATED_ENCRYPTION) {
+                            KeyManager.ActiveRsaKey keys = session.keys().getActiveRsaKey(realm);
+                            assertionElement = AssertionUtil.decryptAssertion(responseType, keys.getPrivateKey());
+                        } else {
+                        /* End of deprecated code */
+                            assertionElement = AssertionUtil.decryptAssertion(responseType, new SAMLIDPDecryptionKeysLocator(session, realm, config));
+                        }
+                    } catch (ProcessingException ex) {
+                        throw new WebApplicationException(ex, Response.Status.BAD_REQUEST);
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:452]: Is it possible to display some useful error message to the server.log for this case?

I guess that people migrating from previous version and relying on previous behaviour may have issues and may not know why things not working. I can imagine some warning like `Not possible to decrypt SAML assertion. Please check realm keys of usage ENC in the realm 'foo' and make sure there is a key able to decrypt the assertion encrypted by identity provider 'my-saml-idp'` . WDYT?

Feel free to ignore this comment if you think that error message is already useful, but my guess is that not (actually not 100% sure if `WebApplicationException` displays something to the server.log at all...)

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java [hunk 5]
```diff
@@ -477,9 +490,19 @@ protected Response handleLoginResponse(String samlResponse, SAMLDocumentHolder h
...
+                        /* This code is deprecated and will be removed in Keycloak 24 */
+                        if (DEPRECATED_ENCRYPTION) {
+                            KeyManager.ActiveRsaKey keys = session.keys().getActiveRsaKey(realm);
+                            AssertionUtil.decryptId(responseType, data -> Collections.singletonList(keys.getPrivateKey()));
+                        } else {
+                            /* End of deprecated code */
+                            AssertionUtil.decryptId(responseType, new SAMLIDPDecryptionKeysLocator(session, realm, config));
+                        }
+                    } catch (ProcessingException ex) {
+                        throw new WebApplicationException(ex, Response.Status.BAD_REQUEST);
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:504]: Same comment like above

File: services/src/main/java/org/keycloak/protocol/saml/SamlProtocolUtils.java [hunk 6]
```diff
@@ -132,22 +132,6 @@ public static PublicKey getEncryptionKey(ClientModel client) throws Verification
         return getPublicKey(client, SamlConfigAttributes.SAML_ENCRYPTION_CERTIFICATE_ATTRIBUTE);
     }
 
-    /**
-     * Returns private key used to decrypt SAML assertions encrypted by 3rd party SAML IDP
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/saml/SamlProtocolUtils.java:136]: Minor: Probably some java "imports" can be removed from this class once this method is removed?

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/admin/ApiUtil.java [hunk 7]
```diff
@@ -270,22 +276,49 @@ public static AuthorizationResource findAuthorizationSettings(RealmResource real
...
-                return rep;
-            }
-        }
-        return null;
+        return findRealmKeys(realm, rep -> rep.getPublicKey() != null && KeyStatus.valueOf(rep.getStatus()).isActive() && KeyUse.SIG.equals(rep.getUse()) && alg.equals(rep.getAlgorithm()))
+                .findFirst()
+                .orElse(null);
+    }
+
+    public static KeysMetadataRepresentation.KeyMetadataRepresentation findActiveEncryptingKey(RealmResource realm) {
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/admin/ApiUtil.java:290]: It seems there is exactly same method already present in the testsuite class `org.keycloak.testsuite.util.KeyUtils`. Same applies for method `findActiveSigningKey`. How about to remove one or the other and make the utilities to be present just on the single place?

My vote would be to remove all the "keys" related stuff from ApiUtil and keep in KeyUtils.

**Review by mposolda — CHANGES_REQUESTED** [review]
@mhajas Thanks! I found few things mostly minor.

Besides that, will it be good to slightly change the `saml-encryption-algorithm.tooltip` in the `admin-messages_en.properties`  as the semantics changed a bit?
How about `Encryption algorithm, which is used by SAML IDP for encryption of SAML documents, assertions or IDs. The corresponding decryption key for decrypt SAML document parts will be chosen based on this configured algorithm and should be available in realm keys for the encryption (ENC) usage. If algorithm is not configured, then any supported algorithm is allowed and decryption key will be chosen based on the algorithm configured in SAML document itself` ?

Also will be good to add docs (I've added missing/docs label).

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java (hunk 4 above)
Comment (cgeorgilakis) [reply services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:452]: I agree. Not only for previous false use case. Logs should show what is wrong with keys (fe false key configuration).

File: services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java [hunk 8]
```diff
@@ -363,23 +365,46 @@ public Response export(UriInfo uriInfo, RealmModel realm, String format) {
             String nameIDPolicyFormat = getConfig().getNameIDPolicyFormat();
 
 
-            List<Element> signingKeys = streamForExport(session.keys().getKeysStream(realm, KeyUse.SIG, Algorithm.RS256), false)
+            List<KeyDescriptorType> signingKeys = session.keys().getKeysStream(realm, KeyUse.SIG, Algorithm.RS256)
+                    .filter(key -> key.getCertificate() != null)
```
Comment (cgeorgilakis) [inline services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:369]: Is there any reason for not filtering active keys for signing as we do for encrypted keys?

File: services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java [hunk 9]
```diff
@@ -363,23 +365,46 @@ public Response export(UriInfo uriInfo, RealmModel realm, String format) {
...
             String encAlg = getConfig().getEncryptionAlgorithm();
-            Stream<KeyWrapper> encryptionKeyWrappers = (encAlg != null && !encAlg.trim().isEmpty())
-                    ? session.keys().getKeysStream(realm, KeyUse.ENC, encAlg)
-                    : session.keys().getKeysStream(realm, KeyUse.SIG, Algorithm.RS256);
-            List<Element> encryptionKeys = streamForExport(encryptionKeyWrappers, true)
+            List<KeyDescriptorType> encryptionKeys = session.keys().getKeysStream(realm)
+                    .filter(key -> key.getStatus().isEnabled() && KeyUse.ENC.equals(key.getUse()))
+                    .filter(key -> encAlg == null || Objects.equals(encAlg, key.getAlgorithmOrDefault()))
+                    .filter(key -> SAMLEncryptionAlgorithms.forKeycloakIdentifier(key.getAlgorithm()) != null)
+                    .filter(key -> key.getCertificate() != null)
```
Comment (cgeorgilakis) [inline services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:387]: Why not making one filter with &&? 
It will have better performance.

File: services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java (hunk 8 above)
Comment (mhajas) [reply services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:369]: Where do we filter active keys for encrypted keys?

Comment (mhajas) [reply services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:369]: I see what you mean now. Enabled and active are not the same thing.

We do not filter enabled for signing keys because method `Stream<KeyWrapper> getKeysStream(RealmModel realm, KeyUse use, String algorithm)` does this already, while method `Stream<KeyWrapper> getKeysStream(RealmModel realm)` does not. 

This is something that could be fixed, however, it would require going through all usages and making it consistent which I think should not be part of this PR as it is already quite big.

On the other hand, exporting only active keys could also make sense, but I am not sure what problems  it can cause as at the moment we export both active and passive. @mposolda @stianst Should we export also passive keys as part of SP metadata or there should be only active ones?

**Comment by cgeorgilakis** [comment]
@mhajas @mposolda I think that PR with latest commits is generally ok. It is difficult to be tested now. You could proceed with it.

Only one question related to [choose what algorithm IDP -> SP communication uses](https://github.com/keycloak/keycloak/pull/16370). It will be mandatory to choose an algorithm for SAML Identity provider in the ui? Why not making it optional and by default choose supported SAML algorithms for encryption? We have many SAML Identity Providers that use the same realm encrypted key. Any change in realm key will need change in all SAML Identity Providers.

**Comment by mhajas** [comment]
@cgeorgilakis It is not mandatory to choose any algorithm in the IDP config. When not set Keycloak will consider all keys with the supported algorithm.

**Comment by cgeorgilakis** [comment]
Ok. Thank you.

File: services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java (hunk 8 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:367]: @mhajas @cgeorgilakis Good question. I think it is correct that export for "sig" returns also passive keys, but for "enc" it returns just active keys.

Few more details:
it works in a way that Keycloak always has 1 active key per algorithm. So for example in OIDC, there can be this scenario related to key rotation:
1) Keycloak signs token with active key `abc` and send to javascript client "foo"
2) Keycloak administrator rotates keys and sets the new key `def` for algorithm `RS256` as new active. The key `abc` is still kept as "passive" key
3) At some point (EG. after 10 seconds), javascript client sends the token from step1 to REST service to access some data
4) The REST service wants to verify token, which was signed in step 1 by key `abc`. It want to download realm keys to be able to verify signature. The key `abc` needs to be still present even if it is not "active" as the token was signed with that before

I guess that for SAML IDP, this is likely not so important as Keycloak signs just SAMLRequest sent to the SAML IDP, (or SAMLResponse for some rare cases like logout) AFAIK? Still if we return only "active" keys, I can imagine something like this:
1) Keycloak sends SAMLRequest to IDP signed by key `abc`
2) In the meantime, key is rotated in Keycloak and active key is `abc`
3) SAML IDP wants to verify signature and hence it downloads the keys from SP metadata endpoint. It won't see key key with `abc` and hence it won't be able to verify signature on SAMLRequest and hence it will throw an error -> KO.

So it is likely more proper approach to return also "passive" keys for signing, so the key `abc` is returned from SP metadata and SAML IDP is able to verify signature.

Regarding encryption/decryption, we should likely return only "active" keys as this is what SAML IDP needs to use for "encrypt" SAML assertion. But during verification, we should use also "passive" keys due the rotation. For example scenario like:
1) Key `abc` is exported in SP metadata
2) Based on that, SAML Identity provider will encrypt the assertion with key `abc`
3) In the meantime, keys are rotated in Keycloak and `abc` becomes "passive" key
4) Keycloak won't be able to decrypt the assertion with key `abc` because it is not active -> KO

Could the last scenario happen? It seems to me that not as SAMLDecryptionKeysLocator introduced in this PR considers also "passive" keys for SAML assertion decryption, which is correct.

So we should be good with the changes in this PR.

**Review by mposolda — DISMISSED** [review]
@mhajas LGTM, Thanks for the updates!

**Comment by mposolda** [comment]
@mhajas During docs PR, please consider also updating the option "Encryption key" of SAML IDP in similar way as tooltip in this PR :-) Thanks!

File: services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java (hunk 8 above)
Comment (mhajas) [reply services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:367]: Thanks for the detailed response @mposolda. Based on your response I believe we should change this PR as currently we include also passive encryption keys in SP metadata and I agree with you that it makes sense to include only active ones. 

I will update the PR.

Comment (mposolda) [reply services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:369]: Ok, Thanks for the updates and doublecheck the codebase and for additional comments in the code!

**Review by mposolda — DISMISSED** [review]

**Comment by mhajas** [comment]
Thanks for the reviews @mposolda and @cgeorgilakis, I will work on docs now.

**Comment by mhajas** [comment]
I was finally able to open a PR against `keycloak-documentation`. See https://github.com/keycloak/keycloak-documentation/pull/1760

**Comment by mhajas** [comment]
With the documentation PR in place, I am opening the PR for final reviews. 

Also, I created a task https://github.com/keycloak/keycloak/issues/16726 to remove the backward compatibility mode we introduced in this PR and assigned it to 24.0.0 milestone so we don't forget about it.

**Review by mposolda — DISMISSED** [review]

**Review by mposolda — APPROVED** [review]
