### PR TITLE
Avoid removing static path config from cache

### LINKED ISSUE #9855: PolicyEnforcer sometimes looses provided adapterconfig while executing resource matching
### Describe the bug

We use Keycloak policy enforcement in Quarkus microservices. Some resources we disable for policy enforcement using the `application.properties`. Sample:

```
quarkus.keycloak.policy-enforcer.paths.health.name=Health Check
quarkus.keycloak.policy-enforcer.paths.health.path=${quarkus.http.root-path}/q/health/*
quarkus.keycloak.policy-enforcer.paths.health.enforcement-mode=DISABLED
```

It seems that those configurations sometimes is lost. This seems to be the case because we sometimes experience 401/403 errors based on those resources even though they are explicitly excluded. It is not reproducible. While debugging the issue and checking the code I found the following which I assume could result in the problem which we are facing and hope you can help me analyzing further or maybe come up with a fix.

I think the logic in the `matches` method of the `PathConfigMatcher` could lead to the above described situation. There are a few things which seem like possible causes:

*1. Removing entries from `paths` variable in*

https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java#L276

My understanding of that section is that in case a cache entry expires it will be removed from the paths instance variable. That variable actually contains the initial list of entries which have been provided in the adapterConfig (from application.properties). I can't think of any situation in which this should happen. So I think this could be the reason for the behaviour which we are observing.

*2. Different behaviour depending on `*` being in the path of the configuration or not*

https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java#L270

If we provide a configuration in the `application.properties` it can happen that this configuration is being overriden by a resource in Keycloak. This is the case when the path contains a `*`. It will go into the section because there is `*` in the path and then retrieve the resouce from Keycloak. If something is found there that takes precedence over the configuration in the `paths` instance variable. In the case if the original configuration in `application.properties` would not contain a `*` in the path no request to Keycloak would be issued and therefore the entry in `application.properties` takes precedence. And in this case also the entry would never be removed from the `paths` variable since the removal is within the if statement.

*3. Potentially a multithreading issue*

https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java#L263

In the case that there is no entry in the cache when line 261 is being executed in thread A, but then in a different thread something is put into the cache with that key and now context switches again to thread A while executing line 263 the containsKey check will be true and null will be returned.

### Version

15.0.2 (but is same in current version)

### Expected behavior

Entries in the adapaterConfig which are provided to PolicyEnforcer should always be present and never get lost. Entries in adapterConfig should always take precedence over Keycloak resources.

### Actual behavior

Entries in the adapaterConfig which are provided to PolicyEnforcer are being removed in certain circumstances. Entries in adapterConfig with a `*` can be overriden by Keycloak resources.

### How to Reproduce?

I do not have a reproducing sample. The above description is based on my understanding of the code which might be wrong. I think to make it happen in real world it is some kind of multithreading issue which I was not able to reproduce. But it happens every now and then in our application and I hope you can help to identify the root cause even if above description and understanding of the code is not accurate.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #9855

### CODE REVIEW

File: adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java [hunk 1]
```diff
@@ -282,11 +286,13 @@ public PathConfig matches(String targetUri) {
                             PolicyEnforcerConfig.EnforcementMode enforcementMode = PolicyEnforcerConfig.EnforcementMode.ENFORCING;
                             ResourceRepresentation targetResource = matchingResources.get(0);
                             List<PolicyEnforcerConfig.MethodConfig> methodConfig = null;
+                            boolean isStatic = false;
```
Comment (mhajas) [inline adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java:289]: @pedroigor I am not following the changes below this line. Why is this needed? 

Usecase where it doesn't make sense to me:
1. In `application.properties` file I have some static `pathConfig` that contains `*`  
2. Then for all requests that match the `pathConfig` I will set the `isStatic` to `true` even though the config is lazy loaded from server which means that probably should not be static. Am I missing something?  

Also, if I am not mistaken the reported issue in point 1. (from report #9855) should be fixed by change on line 200-202.

**Review by mhajas — COMMENTED** [review]
Thank you for the fix @pedroigor, I added one question into the code.

File: adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java (hunk 1 above)
Comment (pedroigor) [reply adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java:289]: A `static` path is a path that you explicitly associated with a resource. For those paths, the PEP is not going to invalidate the cache in order to sync changes in your resources (e.g.: changing the URI).

When you set `*` the server will first try to resolve the best match (exact or partial) otherwise use the path configuration you defined in the configuration.

The issue is about removing entries when they are marked as disabled (what should mark a path as `static` and avoid removing it from the paths) and not respecting the `static` marker when paths are configured as such. If you can elaborate more about the fix to line 200-202, I appreciate it. So I can see if I'm missing something.

Comment (mhajas) [reply adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java:289]: What I meant by `200-202` is this part: https://github.com/keycloak/keycloak/pull/13737/files#diff-0db76367dca5a7a87f67bf3a27f7e961e885b2361a1e768c44c1fa554a9b8036R200-R202

If I am not mistaken it solves the issue where disabled pathConfigs are removed from the cache itself.  What I don't understand is what is the purpose of the other changes in the `PolicyEnforcer` class.

This is a scenario I have on my mind when I see the other changes and I am not sure it is correct:
1. PolicyEnforcer config contains some path that is statically bound (P1)
2. There is a request that partially matches P1 therefore it is taken from the cache on this line
https://github.com/keycloak/keycloak/blob/e1fed2c95ca275aeee057a7fc0838ebc14324930/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java#L271
3. It is only a partial match, this means we will search Keycloak server for better matches and let's say we have found some resource (R1)
4. We create pathConfig based on R1:
https://github.com/keycloak/keycloak/blob/e1fed2c95ca275aeee057a7fc0838ebc14324930/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java#L306
5. And then set static flag based on P1
https://github.com/keycloak/keycloak/blob/e1fed2c95ca275aeee057a7fc0838ebc14324930/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java#L316
6. And then cache it and never removed because it is static
https://github.com/keycloak/keycloak/blob/e1fed2c95ca275aeee057a7fc0838ebc14324930/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java#L326

Is this correct? Or Am I missing something?

Comment (pedroigor) [reply adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java:289]: As discussed, behavior expected.

**Review by mhajas — APPROVED** [review]
Thanks @pedroigor, LGTM

**Review by abstractj — APPROVED** [review]
