### PR TITLE
Fix refresh token scope in refresh token flow with scope request para…

### LINKED ISSUE #28463: Error in refresh flow with scope parameter
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

With [my PR](https://github.com/keycloak/keycloak/pull/12043), Keycloak now supports [scope parameter in the refresh flow ](https://github.com/keycloak/keycloak/issues/12009).
However, I have not added a fix that I have found after committed my PR.

Refresh token scopes (if it must be returned) and client session scopes must not be changed.
From [Section 6 in OAuth2 RFC](https://www.ietf.org/rfc/rfc6749.txt)

> If a
   new refresh token is issued, the refresh token scope MUST be
   identical to that of the refresh token included by the client in the
   request.

This bug in accepted PR leads to issues like [https://github.com/keycloak/keycloak/issues/27878](https://github.com/keycloak/keycloak/issues/27878).

However, the [accepted PR](https://github.com/keycloak/keycloak/pull/28093) for fixing previous issue brings the specification!
Although offline_access scope is not in scope parameter, it returns it in access scope!
Together with the fact that this PR does not guarantee same refresh token scopes.

I will commit a new PR for fixing the bug.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

1. Refresh token scopes must be equal to old refresh token scopes during refresh token flow.
2. offline_access must not returned in access scope during a refresh token scope with offline_access existing in refresh flow and not existing in scope parameter

### Actual behavior

1. Refresh token scopes is not equal to old refresh token scopes during refresh token flow when scope parameter with less scope is requested.
2. offline_access is returned in access scope during a refresh token scope with offline_access existing in refresh flow and not existing in scope parameter

### How to Reproduce?

Do a refresh flow with offline_access exists in refresh token scope and not exists in r=scope parameter.
Client must return refresh token

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
…meter

Closes #28463

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java [hunk 1]
```diff
@@ -1050,10 +1050,6 @@ private void offlineTokenRequestWithScopeParameter(String expectedRefreshAlg, St
 
         Assert.assertEquals(TokenUtil.TOKEN_TYPE_OFFLINE, offlineToken.getType());
         Assert.assertEquals(0, offlineToken.getExpiration());
-
-        //refresh token without sending offline_access scope
```
Comment (pedroigor) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java:1054]: Why you are removing this check? The `offline_access` scope should be there as it was request in the first token request, no?

Comment (cgeorgilakis) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java:1054]: > Why you are removing this check? The `offline_access` scope should be there as it was request in the first token request, no?

This test has been changed in previous [false accepted PR ](https://github.com/keycloak/keycloak/pull/28093).
Refresh flow is offline access and scope parameter is '_phone_'. So, access token must not contain _offline_access_ and refresh access token must contain _offline_access_.

So, we need to revert back changes in _testRefreshWithOfflineToken_ in order to take into account if scope parameter will contain _offline_access_.
However, this test part is same as test method _offlineTokenRefreshWithoutOfflineAccessScope_. So, I have enchanced method _offlineTokenRefreshWithoutOfflineAccessScope_. I believe it is enough.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@cgeorgilakis Thanks.
