### PR TITLE
Translate user profile attribute group label

### LINKED ISSUE #24431: Admin UI: User Profile Attribute Group Displayname not translated in Create/Update User Screens
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

The displayName of a User Profile Attribute group is not being translated on the create or update user screens: 

image

It seems like the group display name is not passed through the translate function.

### Version

22.0.5

### Expected behavior

The displayName of a User Profile Attribute Group should be translated like the displayName of the attributes themselves.

### Actual behavior

The displayName of a User Profile Attribute Group is not translated.

### How to Reproduce?

1. Create a realm
2. Enable user profile
3. Add a user profile attribute group and give it a translateable displayname, e.g. "${personalInfo}"
4. Add a user profile attribute and assign it to the group
5. Go to user create/details screen, seeing that the ${...} around the label is not removed indicates that is not running through the translate function

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by antikalk**
Fixes #24431

### CODE REVIEW

**Comment by antikalk** [comment]
Should the `group.displayDescription` also be put through the translation process? It is translated on the Login Theme at least...

File: js/apps/admin-ui/src/user/utils.ts [hunk 1]
```diff
@@ -10,6 +14,14 @@ export const label = (attribute: UserProfileAttributeMetadata, t: TFunction) =>
     ? t(unWrap(attribute.displayName!))
     : attribute.displayName) || attribute.name;
 
+export const attributeGroupLabel = (
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/utils.ts:17]: Since this function is only used once, I think it would be preferential to co-locate it in the place it is used.

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Comment by jonkoops** [comment]
> Should the `group.displayDescription` also be put through the translation process? It is translated on the Login Theme at least...

If it is translated there, we should do so here as well. Feel free to add this code as you see fit.

**Comment by antikalk** [comment]
> > Should the `group.displayDescription` also be put through the translation process? It is translated on the Login Theme at least...
> 
> If it is translated there, we should do so here as well. Feel free to add this code as you see fit.

Additionally, I am a little confused where to put the translation for the user profile attributes. For the login theme it is enough to put the translations in the Realm-Settings -> Localization. Putting it there is not respected by the admin-ui for the user screens though... I think there should only be one place to store/manage the localizations.

**Comment by jonkoops** [comment]
> Additionally, I am a little confused where to put the translation for the user profile attributes. For the login theme it is enough to put the translations in the Realm-Settings -> Localization. Putting it there is not respected by the admin-ui for the user screens though...

Putting it under 'Realm Settings' :arrow_right: 'Localization' should work, if it does not that should be considered a bug, feel free to report it as such.

> I think there should only be one place to store/manage the localizations.

Yes, I completely agree. And I think that our system for localization is fundamentally broken. Ideally localized content would be stored inside of the resource itself (in this case a User Profile attribute). Instead we are doing some 'magic' interpolation based on what comes out of the realm settings.

However, I have not been able to convince the rest of the Keycloak team this is a good idea. If you want to engage or follow this discussion check out https://github.com/keycloak/keycloak/discussions/16882#discussioncomment-6815338.

**Comment by antikalk** [comment]
> > Additionally, I am a little confused where to put the translation for the user profile attributes. For the login theme it is enough to put the translations in the Realm-Settings -> Localization. Putting it there is not respected by the admin-ui for the user screens though...
> 
> Putting it under 'Realm Settings' ➡️ 'Localization' should work, if it does not that should be considered a bug, feel free to report it as such.

Done: https://github.com/keycloak/keycloak/issues/24472

File: js/apps/admin-ui/src/user/UserProfileFields.tsx [hunk 2]
```diff
@@ -221,3 +224,19 @@ function determineInputType(
...
+    ? t(unWrap(group.displayHeader!))
+    : group.displayHeader) || group.name;
+
+const attributeGroupDescriptionLabel = (
+  group: UserProfileAttributeGroupMetadata,
+  t: TFunction,
+) =>
+  isBundleKey(group.displayDescription)
+    ? t(unWrap(group.displayDescription!))
+    : group.displayDescription;
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserProfileFields.tsx:242]: This code looks the same between these functions, aside from the field they operate on. Perhaps this can be done generically? I am also seeing a [similar function](https://github.com/keycloak/keycloak/blob/fe0a9459dd5ae4f400abb17c6b48184a37e98293/js/apps/account-ui/src/personal-info/utils.ts#L9-L12) in the utils that can get the same treatment.

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by ssilvert — COMMENTED** [review]
It looks like this is only dealing with attribute groups?  The issue indicated that this wasn't working with regular attributes either.

**Comment by antikalk** [comment]
> It looks like this is only dealing with attribute groups? The issue indicated that this wasn't working with regular attributes either.

The issue I created for the Realm Settings -> Localization Settings (https://github.com/keycloak/keycloak/issues/24472) also applies to Attribute Labels. This PR here only enables the JS translate function being called for the Attribute Group displayName and description. Even with this PR they would face the same issue as the attributes, but at least the behavior would be the same.
