### PR TITLE
fix: refining arg handling

### LINKED ISSUE #44578: Further refine argument handling
### Description

We are manipulating the command line args in quite a few places. This should be minimized so that it's done in as few places as possible. It should also be based upon the picocli parsing, so that we're not attempting to duplicate the rules / handling in another place.

### PR DESCRIPTION
**Pull request by shawkins**
relying on picocli parsing as much as possible

Also changes the message about ensuring a build is used to just adding --optimized.

closes: #44578

### CODE REVIEW

**Comment by shawkins** [comment]
Let me know if you want this broken up more.

I believe these changes also open up the possibility to reusing reaugmentations across Keycloak and CLITest invocations should we want to refine the logic more - cc @pedroigor 

The only non-distribution CLITests left are under org.keycloak.it.storage.database - most of the distribution related annotatations are not applicable, thus the change to the oracle test. Do we even want to keep these tests as they are, or could we create a follow-up to remove this style (either going full distribution, or moving over to the new test suite).

Another follow-up change: https://github.com/keycloak/keycloak/discussions/38894#discussioncomment-15124256

**Comment by shawkins** [comment]
Marked with a hold as this is not needed for 26.5

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSourceTest.java [hunk 1]
```diff
@@ -30,23 +30,23 @@ public class ConfigArgsConfigSourceTest {
     @Test
     public void testParseArgs() {
         List<String> values = new ArrayList<>();
-        ConfigArgsConfigSource.parseConfigArgs(Arrays.asList("--key=value", "-cf", "file", "command", "arg", "--db", "value"), (key, value) -> values.add(key+'='+value), values::add);
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSourceTest.java:33]: Does it mean that using the `-cf` is not possible?

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java [hunk 2]
```diff
@@ -108,7 +108,7 @@ void testConfigSourceNames(KeycloakDistribution distribution) {
         distribution.setEnvVar("KC_LOG", "file");
         distribution.copyOrReplaceFile(Paths.get("src/test/resources/ShowConfigCommandTest/quarkus.properties"), Path.of("conf", "quarkus.properties"));
 
-        result = distribution.run(String.format("%s=%s", CONFIG_FILE_LONG_NAME, Paths.get("src/test/resources/ShowConfigCommandTest/keycloak-keystore.conf").toAbsolutePath().normalize()), ShowConfig.NAME, "all");
```
Comment (mabartos) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java:111]: Is this change necessary?

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 3]
```diff
@@ -1017,11 +1017,6 @@ public void duplicatedCliOptions() {
         assertThat(nonRunningPicocli.getErrString(), containsString("Unknown option: '--non-existing'"));
         onAfter();
 
-        nonRunningPicocli = pseudoLaunch("start-dev", "-Dsome.property=123", "-Dsome.property=456");
-        assertEquals(CommandLine.ExitCode.OK, nonRunningPicocli.exitCode);
-        assertThat(nonRunningPicocli.getOutString(), containsString("WARNING: Duplicated options present in CLI: -Dsome.property"));
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:1022]: So, we are not warned about system props duplications on CLI?

**Review by mabartos — COMMENTED** [review]
@shawkins Nice work! Just a few questions.

**Comment by mabartos** [comment]
> The only non-distribution CLITests left are under org.keycloak.it.storage.database - most of the distribution related annotatations are not applicable, thus the change to the oracle test. Do we even want to keep these tests as they are, or could we create a follow-up to remove this style (either going full distribution, or moving over to the new test suite).

@shawkins IMHO, It'd better to move them to the new testsuite as it's more prepared for the additional dependencies.

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 3 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:1022]: System properties won't make it to that point in the code. They are not passed as program arguments, and are consumed by the java launch.

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSourceTest.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSourceTest.java:33]: As an argument to parseConfigArgs, yes. That routine is now only for --kc.prop=value options.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java (hunk 2 above)
Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java:111]: It is so the assertion about finding a cli property still works.

**Review by mabartos — APPROVED** [review]
LGTM

**Comment by mabartos** [comment]
@vmuzikar @Pepo48 @pedroigor Anyone else want to review as you're in the list?

**Review by Pepo48 — APPROVED** [review]
LGTM. Thanks, Steve!
