### PR TITLE
Remove the attempt in brute force when the off-thread finishes

### LINKED ISSUE #31881: Flaky test: org.keycloak.testsuite.forms.BruteForceTest#testRaceAttackPermanentLockout
## org.keycloak.testsuite.forms.BruteForceTest#testRaceAttackPermanentLockout
[Keycloak CI - Forms IT (firefox)](https://github.com/keycloak/keycloak/actions/runs/10223619000/job/28290359909)

```
java.lang.AssertionError: Invalid count should be less than or equal 2 but was: 3
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.forms.BruteForceTest.raceAttack(BruteForceTest.java:820)
	at org.keycloak.testsuite.forms.BruteForceTest.testRaceAttackPermanentLockout(BruteForceTest.java:790)
...
```

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #31881

The PR removes the user attempt ensuring the off-thread for brute-force has also been executed. Previously it was removed when the request finished and, as the brute force is working off-thread, there can be a race again in that last part (less probably but it can happen). With this change I could execute the test [30 times](https://github.com/rmartinc/keycloak/actions/runs/10269655254/job/28415828112) in the CI and 50 times locally without issues.

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]

File: services/src/main/java/org/keycloak/services/managers/DefaultBlockingBruteForceProtector.java [hunk 1]
```diff
@@ -73,46 +76,80 @@ private boolean isLoginInProgress(KeycloakSession session, UserModel user) {
...
     private String getThreadName() {
         return Thread.currentThread().getName();
     }
+
+    private void enlistRemoval(KeycloakSession session, String userId) {
+        session.getTransactionManager().enlistAfterCompletion(new AbstractKeycloakTransaction() {
+            @Override
+            protected void commitImpl() {
+                // remove or wait the main thread to finish
+                loginAttempts.computeIfPresent(userId, (k, v) -> v.isEmpty()? null : v.substring(0, v.length() - OFF_THREAD_STARTED.length()));
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/services/managers/DefaultBlockingBruteForceProtector.java:125]: If you prefer:

```java
v.endsWith(OFF_THREAD_STARTED)? v.substring(0, v.length() - OFF_THREAD_STARTED.length()) : null
```

Just let me know. It should be the same but maybe it's more clear.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/managers/DefaultBlockingBruteForceProtector.java:125]: It might happen to not have the suffix appended to the value? If not, works for me.

Comment (rmartinc) [reply services/src/main/java/org/keycloak/services/managers/DefaultBlockingBruteForceProtector.java:125]: No, or it has the suffix appended (off-thread is finishing first) or it is empty (main thread finished first). I think it's the same.
