### PR TITLE
[OID4VCI] TokenResponse requires credential_identifiers in authorization_details

### LINKED ISSUE #47386: [OID4VCI] TokenResponse requires credential_identifiers in authorization_details
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

Currently, we always generate `authorization_details` and return that with the AccessToken Response and include it in the AccessToken JWT

[Section 6.2](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-6.2) of the spec says ...

> authorization_details: REQUIRED when the authorization_details parameter, as defined in [Section 5.1.1](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#authorization-details), is used in either the [Authorization Request](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#credential-authz-request) or [Token Request](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#token-request). OPTIONAL when scope parameter was used to request issuance of a Credential of a certain Credential Configuration. It is a non-empty array of objects, as defined in Section 7 of [[RFC9396](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#RFC9396)]. In addition to the parameters defined in [Section 5.1.1](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#authorization-details), this specification defines the following parameter to be used with the authorization details type openid_credential in the Token Response:
>
> credential_identifiers: REQUIRED. A non-empty array of strings, each uniquely identifying a Credential Dataset that can be issued using the Access Token returned in this response. Each of these Credential Datasets corresponds to the Credential Configuration referenced in the credential_configuration_id parameter. The Wallet MUST use these identifiers together with an Access Token in subsequent Credential Requests. See [Section 3.3.4](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#identifying_credential) for the summary of the options how requested Credential(s) are identified throughout the Issuance flow.

Our `authorization_details` always contains the required `credential_configuration_id` and optionally `credential_identifiers` when configured on the credential scope.

`VCICreateCredentialRequest` in OpenID Conformance test `oid4vci-1_0-issuer-happy-flow` verifies that `credential_identifiers` are present (i.e. not optional) when there are `authorization_details` in the AccessToken Response.

CrossRef: https://gitlab.com/openid/conformance-suite/-/work_items/1724

### Expected behavior

Only return `authorization_details` when ...

* present in Authorization Request
* present in AccessToken Request
* credential identifiers configured on the scope 

When `authorization_details` are returned they must contain (possibly generated) `credential_identifiers`

Dependency of #47316

### PR DESCRIPTION
**Pull request by tdiesler**
closes #47386

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java
Comment (forkimenjeckayang) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java:1]: `checkAuthorizationDetails()` and `validateAuthorizationDetail()` apply different rules to request-time `credential_identifiers` (authorization rejects any presence, while the token path rejects only non-empty arrays), which can lead to divergent behavior (e.g., `[]`).  

Per Section 5.1.1, additional fields for `openid_credential` should not invalidate the authorization details type. Could we unify both paths by accepting this field on input and ignoring/clearing it, while ensuring token responses still emit server-authoritative `credential_identifiers` as defined in Section 6.2?

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java [hunk 1]
```diff
@@ -228,6 +236,34 @@ public void checkOIDCRequest() {
...
+    public void checkAuthorizationDetails() throws AuthorizationCheckException {
+        String authDetailsParam = request.getAdditionalReqParams().get(AUTHORIZATION_DETAILS);
+        if (authDetailsParam != null) {
+            AuthorizationDetailsJSONRepresentation[] authDetails;
+            try {
+                authDetails = JsonSerialization.readValue(authDetailsParam, AuthorizationDetailsJSONRepresentation[].class);
+            } catch (IOException e) {
+                ServicesLogger.LOGGER.warn("Cannot parse authorization_details: " + authDetailsParam);
+                return;
+            }
```
Comment (forkimenjeckayang) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java]: On parse failure, `checkAuthorizationDetails()` logs and returns. Should malformed `authorization_details` instead cause the authorization request to fail with `invalid_request`, ensuring deterministic errors at the authorization endpoint?

**Review by forkimenjeckayang — CHANGES_REQUESTED** [review]
A few concerns @tdiesler 
Please take a look when you can

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java
Comment (tdiesler) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java:1]: Yes, additional fields should not invalidate the authorization details. However, this is a field not totally unknown to the spec - it's a known field used in the wrong context. 

On that basis, I suggest we align like this ...

```
        if (credentialIdentifiers != null) {
            // we also reject an empty array of credential identifiers
            logger.warnf("Property credential_identifiers not allowed in authorization_details");
            throw getInvalidRequestException("credential_identifiers not allowed");
        }
```

It is unlikely that the conformance tests want to see the empty array pass.

WDYT?

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java (hunk 1 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java]: yes, this also aligns with other parser errors

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java [hunk 2]
```diff
@@ -228,6 +236,38 @@ public void checkOIDCRequest() {
...
+        if (authDetailsParam != null) {
+            AuthorizationDetailsJSONRepresentation[] authDetails;
+            try {
+                authDetails = JsonSerialization.readValue(authDetailsParam, AuthorizationDetailsJSONRepresentation[].class);
+            } catch (Exception e) {
+                event.error(Errors.INVALID_REQUEST);
+                throw new AuthorizationCheckException(Response.Status.BAD_REQUEST, Errors.INVALID_REQUEST,
+                        "Cannot parse authorization_details: " + authDetailsParam);
+            }
+            for (AuthorizationDetailsJSONRepresentation authDetailJson : authDetails) {
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java]: It will be nice if `AuthorizationEndpointChecker` does not have any direct dependencies on OID4VCI specific logic.

Is it possible to add new callback method to `AuthorizationDetailsProcessorManager` and `AuthorizationDetailsProcessor`, which will move this logic (lines 251-266) to the OID4VC specific processor? That can possibly help that we would be easily able to re-use same/similar validation like already done for token-endpoint? (As discussed in the other comment).

**Review by mposolda — COMMENTED** [review]
@tdiesler Thanks! Added comment inline (related also to other comment by @forkimenjeckayang ).

Also one question: As mentioned here in this comment https://github.com/keycloak/keycloak/issues/47386#issuecomment-4125164610 , we do not need to support `credential_configuration_id` parameter in the credential-request. However in this PR it is still supported. Any issues with removing support for `credential_configuration_id` in this PR? Or do you rather want to do as a follow-up?

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java
Comment (mposolda) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java:1]: +1

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java (hunk 2 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java]: yes, that's how it should be (done)

**Comment by tdiesler** [comment]
> Any issues with removing support for `credential_configuration_id` in this PR? Or do you rather want to do as a follow-up

It is infact not supported, because of ...

```
        // Verify that the requested credential_configuration_id in the request matches one in the authorization_details
        //
        if (!Strings.isEmpty(requestedCredentialConfigurationId)) {

            if (!authorizedCredentialConfigurationId.equals(requestedCredentialConfigurationId)) {
                var errorMessage = "Credential configuration '" + requestedCredentialConfigurationId + "' not found in authorization_details";
                LOGGER.debug(errorMessage);
                eventBuilder.detail(Details.REASON, errorMessage).error(ErrorType.UNKNOWN_CREDENTIAL_CONFIGURATION.getValue());
                throw new BadRequestException(getErrorResponse(ErrorType.UNKNOWN_CREDENTIAL_CONFIGURATION, errorMessage));
            }

            if (!authorizedCredentialIdentifiers.isEmpty()) {
                var errorMessage = "Credential must be requested by credential identifier from authorization_details: " + authorizedCredentialIdentifiers;
                LOGGER.debug(errorMessage);
                eventBuilder.detail(Details.REASON, errorMessage).error(ErrorType.INVALID_CREDENTIAL_REQUEST.getValue());
                throw new BadRequestException(getErrorResponse(ErrorType.INVALID_CREDENTIAL_REQUEST, errorMessage));
            }
        }
```

The conformance suite suite wants to see an UNKNOWN_CREDENTIAL_CONFIGURATION error, so we can't simply fail on any credential_configuration_id. 

In our case, it always fails because we always return `authorization_details` from the token endpoint which MUST contain a credential_identifier. Remember, we decided to do it that way even for scope only requests that have no credential_identifiers configured on the scope - (in which case we generate the credential_identifier <=  credential_configuration_id_0000).

This code would stay valid even if we decide to no longer return redundant `authorization_details` from the token endpoint

**Review by mposolda — APPROVED** [review]
@tdiesler Thanks for the clarifications.

Leaving PR open for one more day in case @forkimenjeckayang has any additional feedback.

**Comment by tdiesler** [comment]
@mposolda FYI, this PR introduces a considerable amount of ugliness related to #47649. Invalid authorization requests are now caught early and will timeout with that Selenium exception - the root cause is lost. In case you prefer that this does not enter the code base, have a look at PR #47850. If that gets merged first, our tests could also be restored to handle their invalid auth requests properly.

```
git grep 'TODO #47649' 

tests/base/src/test/java/org/keycloak/tests/oid4vc/issuance/OID4VCAuthorizationCodeFlowTestBase.java:        // [TODO #47649] OAuthClient cannot handle invalid authorization requests
tests/base/src/test/java/org/keycloak/tests/oid4vc/issuance/OID4VCAuthorizationCodeFlowTestBase.java:        // [TODO #47649] OAuthClient cannot handle invalid authorization requests
tests/base/src/test/java/org/keycloak/tests/oid4vc/issuance/signing/OID4VCAuthorizationDetailsFlowTestBase.java:        // [TODO #47649] OAuthClient cannot handle invalid authorization requests
testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java:        // [TODO #47649] OAuthClient cannot handle i
```

In `LoginUrlBuilder` the relevant change is this ...

```
    public AuthorizationEndpointResponse doLogin(String username, String password) {
        open();

        // Login page may not get displayed (e.g. in case of an invalid AuthorizationRequest)
        String currUrl = client.driver.getCurrentUrl();
        if (currUrl != null && !currUrl.contains("error=") && !currUrl.contains("error_description=")) {
            client.fillLoginForm(username, password);
        }
        return client.parseLoginResponse();
    }
```

**Review by forkimenjeckayang — APPROVED** [review]
No further concerns, approach LGTM

**Comment by mposolda** [comment]
@tdiesler @forkimenjeckayang Thanks!
