### PR TITLE
CreatedResponseUtil.getCreatedId should expose server error message (#34343)

### LINKED ISSUE #34343: CreatedResponseUtil.getCreatedId should expose the actual error message from the server
### Description

Currently, if org.keycloak.admin.client.CreatedResponseUtil#getCreatedId fails, an error message like:
```
Create method returned status Bad Request (Code: 400); expected status: Created (201).
```

However the server actually sends helpful an errorMessages when when an ErrorResponse is created via `org.keycloak.services.ErrorResponse#error(java.lang.String, java.lang.Object[], jakarta.ws.rs.core.Response.Status)`.

We should check if the error response is readable and contains an errorMessage, and if present add it to the exception message.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
We now expose the actual error message found in the response if present.

Fixes #34343

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>
(cherry picked from commit d94e388047418549d7228280782e804087b2586e)

### CODE REVIEW

**Review by graziang — APPROVED** [review]

File: integration/admin-client/src/main/java/org/keycloak/admin/client/CreatedResponseUtil.java [hunk 1]
```diff
@@ -39,9 +42,24 @@ public static String getCreatedId(Response response) throws WebApplicationExcept
...
         if (!response.getStatusInfo().equals(Response.Status.CREATED)) {
             Response.StatusType statusInfo = response.getStatusInfo();
-            throw new WebApplicationException("Create method returned status " +
-                    statusInfo.getReasonPhrase() + " (Code: " + statusInfo.getStatusCode() + "); " +
-                    "expected status: Created (201)", response);
+            String contentType = response.getHeaderString(HttpHeaders.CONTENT_TYPE);
+            String errorMessage = "Create method returned status " +
+                                  statusInfo.getReasonPhrase() + " (Code: " + statusInfo.getStatusCode() + "); " +
+                                  "expected status: Created (201).";
+            if (MediaType.APPLICATION_JSON.equals(contentType)) {
```
Comment (jonkoops) [inline integration/admin-client/src/main/java/org/keycloak/admin/client/CreatedResponseUtil.java:49]: This could also potentially be something other than `application/json`, e.g. could include a charset as well `application/json; charset=utf-8`. There is also a `APPLICATION_JSON_TYPE` constant, perhaps the `MediaType` class has a way to compare these as well, without comparing the attributes in the string.

Comment (mposolda) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/CreatedResponseUtil.java:49]: @jonkoops Good point

This is backport of already merged community PR. So I've created another PR into `main` : https://github.com/keycloak/keycloak/pull/36558 . Can you review that one please?

Among your point, I've also figured that in some cases, we are returning `error` JSON claim instead of `errorMessage` (admin console is able to handle both though, so we can support both here as well).

Also added some automated testing for this.

Comment (mposolda) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/CreatedResponseUtil.java:49]: If we go with #36558 , I can include that one into this PR as well to have it backported both.

Comment (jonkoops) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/CreatedResponseUtil.java:49]: Agreed, let's merge that together, also an individual backport would be fine

Comment (mposolda) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/CreatedResponseUtil.java]: @jonkoops Thanks! Merged the original PR into main and added the commit to this PR, so we have the change on single place.

**Review by jonkoops — APPROVED** [review]

**Comment by mposolda** [comment]
@jonkoops Thanks!
