### PR TITLE
Fixed a11y violations for clients

### LINKED ISSUE #17711: Accessibility/Clients List: Minor Issues
### Describe the bug

The following minor issues were found as per the [attached](https://docs.google.com/spreadsheets/d/1KtZJbDHKosSJBQm--1iJKQMwGIOtoohXIdfwMH3rPns/edit?usp=sharing).

### Version

21.0.0

### Environment

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Use Deque Browser Extension

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/17711

### CODE REVIEW

File: js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx [hunk 1]
```diff
@@ -286,6 +286,7 @@ export default function PermissionDetails() {
                   {...register("resourceType", {
                     required: permissionType === "scope",
                   })}
+                  aria-label={t("resourceType")}
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx:289]: We should not be adding an `aria-label` attribute here, as there is already a label in the `FormGroup`. It looks like the `fieldId` prop is set to the wrong input, which is why it creates accessibility issues.

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by jonkoops — APPROVED** [review]
LGTM
