### PR TITLE
Call JPA code in blocking thread

### LINKED ISSUE #32153: Remote Infinispan code must not call JPA code in non-blocking thread
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When showing the list of sessions, the data for the users maybe loaded from the database inside the HotRod client async pool. 

This is problematic in at least two ways: 
* JPA access is blocking, and shouldn't be called from the event loop
* The JTA transaction manager doesn't know about the transaction, as that is only bound to the main thread 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Users should be loaded from the database when showing the session list

### Actual behavior

An exception is thrown. 

```
2024-08-15 09:12:56,598 INFO  [org.hibernate.event.internal.DefaultLoadEventListener] (HotRod-client-async-pool-1-3) HHH000327: Error performing load command: org.hibernate.exception.GenericJDBCException: could not prepare statement [Enlisted connection used without active transaction] [select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from USER_ENTITY ue1_0 where ue1_0.ID=?]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:194)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:155)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.lambda$list$0(JdbcSelectExecutor.java:85)
        at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:231)
        at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:167)
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:218)
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:98)
        at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
        at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:180)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:209)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)
        at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:145)
        at org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.load(SingleIdEntityLoaderStandardImpl.java:90)
        at org.hibernate.loader.ast.internal.AbstractEntityBatchLoader.load(AbstractEntityBatchLoader.java:94)
        at org.hibernate.loader.ast.internal.AbstractEntityBatchLoader.load(AbstractEntityBatchLoader.java:55)
        at org.hibernate.loader.ast.internal.EntityBatchLoaderArrayParam.load(EntityBatchLoaderArrayParam.java:161)
        at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:3738)
        at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3727)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:604)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromCacheOrDatasource(DefaultLoadEventListener.java:590)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:560)
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:544)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:207)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:246)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:111)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:68)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1226)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1214)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:209)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.doLoad(IdentifierLoadAccessImpl.java:160)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$load$1(IdentifierLoadAccessImpl.java:149)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:112)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:149)
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2434)
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2400)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:66)
        at jdk.proxy2/jdk.proxy2.$Proxy69.find(Unknown Source)
        at org.keycloak.models.jpa.JpaUserProvider.getUserById(JpaUserProvider.java:517)
        at org.keycloak.storage.UserStorageManager.getUserById(UserStorageManager.java:390)
        at org.keycloak.models.cache.infinispan.UserCacheSession.getUserById(UserCacheSession.java:222)
        at org.keycloak.models.sessions.infinispan.remote.RemoteUserSessionProvider.initUserSessionFromQuery(RemoteUserSessionProvider.java:381)
        at org.keycloak.models.sessions.infinispan.remote.RemoteUserSessionProvider.maybeInitUserSessionFromQuery(RemoteUserSessionProvider.java:387)
        at org.keycloak.models.sessions.infinispan.remote.RemoteUserSessionProvider.lambda$streamUserSessionByClientId$8(RemoteUserSessionProvider.java:465)
        at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:219)
        at io.reactivex.rxjava3.internal.operators.mixed.ConcatMapXMainSubscriber.onNext(ConcatMapXMainSubscriber.java:106)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.innerSuccess(FlowableFlatMapMaybe.java:173)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber$InnerObserver.onSuccess(FlowableFlatMapMaybe.java:374)
        at io.reactivex.rxjava3.internal.jdk8.MaybeFromCompletionStage$CompletionStageHandler.accept(MaybeFromCompletionStage.java:66)
        at io.reactivex.rxjava3.internal.jdk8.MaybeFromCompletionStage$CompletionStageHandler.accept(MaybeFromCompletionStage.java:48)
        at io.reactivex.rxjava3.internal.jdk8.FlowableFromCompletionStage$BiConsumerAtomicReference.accept(FlowableFromCompletionStage.java:91)
        at io.reactivex.rxjava3.internal.jdk8.FlowableFromCompletionStage$BiConsumerAtomicReference.accept(FlowableFromCompletionStage.java:82)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at org.infinispan.client.hotrod.impl.operations.HotRodOperation.complete(HotRodOperation.java:158)
        at org.infinispan.client.hotrod.impl.operations.GetWithMetadataOperation.acceptResponse(GetWithMetadataOperation.java:77)
        at org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.decode(HeaderDecoder.java:153)
        at org.infinispan.client.hotrod.impl.transport.netty.HintedReplayingDecoder.callDecode(HintedReplayingDecoder.java:94)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:801)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Enlisted connection used without active transaction
        at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:381)
        at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:646)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:153)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183)
        ... 85 more
```

### How to Reproduce?

* Start Keycloak with remote-cache enabled, so user sessions are stored and retrieved from the remote Infinispan
* Create an admin and a regular user
* Create log in with both users concurrently (possibly and incognito window for the second user)
* Restart Keycloak to clear the caches, so the session list will need to load the user from the database
* Login as admin
* Show the realm's session list -> exception will be thrown on the session that is not the current session / user. 

(it is a bit simpler to reproduce if you inject a code change that a user is no longer found with `updater.getValue().getUserId() + "x"` ... but beware, if the user is not found it, the user session will be removed from the remote store) 

### Anything else?

I'll create a draft PR. I don't have an overview on the reactive code used in the remote store, so I'll need additional help to ensure that there aren't any other places.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #32153

### CODE REVIEW

**Comment by ahus1** [comment]
@pruivo - I'm a bit unsure if this is the elegant way to fix this, and if other places might be affected. Not urgent though - please have a look when you have the time.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java [hunk 1]
```diff
@@ -462,9 +461,10 @@ private Stream<UserSessionModel> streamUserSessionByClientId(RealmModel realm, S
         var userSessionTx = getUserSessionTransaction(offline);
         return Flowable.fromIterable(QueryHelper.toCollection(userSessionIdQuery, QueryHelper.SINGLE_PROJECTION_TO_STRING))
                 .flatMapMaybe(userSessionTx::maybeGet, false, MAX_CONCURRENT_REQUESTS)
-                .concatMapMaybe(session -> maybeInitUserSessionFromQuery(session, realm, offline))
+                .blockingStream()
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java:464]: missing the batch size
```suggestion
                .blockingStream(batchSize)
```

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java [hunk 2]
```diff
@@ -462,9 +461,10 @@ private Stream<UserSessionModel> streamUserSessionByClientId(RealmModel realm, S
...
+                .flatMap(session -> maybeInitUserSessionFromQuery(session, realm, offline))
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java:465]: RxJava pipelines do not allow `null` but the Java `Stream` does. You can use the `initUserSessionFromQuery` and filter by non null. 
The method `maybeInitUserSessionFromQuery` can be removed. 
```suggestion
                .map(session -> initUserSessionFromQuery(session, realm, null, offline))
                .filter(Objects::nonNull)
```

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java [hunk 3]
```diff
@@ -462,9 +461,10 @@ private Stream<UserSessionModel> streamUserSessionByClientId(RealmModel realm, S
...
                 .map(UserSessionModel.class::cast)
-                .blockingStream(batchSize);
+                .limit(batchSize);
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java:467]: This doesn't look right. The query is limited by `maxResults`; we don't need to limit the stream.

**Review by pruivo — CHANGES_REQUESTED** [review]
Thanks @ahus1. The use of `limit` seems wrong to me and I suggested a couple of changes. 
Here is the only place where it is used.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java (hunk 3 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java]: Thanks, I think I mis-read the original code. 

Thinking about doing a query with a limit, and then removing entries that are null will lead to fewer than the maxresult entries, which will be surprising for the caller. We're doing this for entries which we retrieve and then consider them expired, as well as for those where we don't find the user. This would be a follow-up issue: #936

**Review by pruivo — APPROVED** [review]

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java (hunk 3 above)
Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java]: I see what you mean. And, it explains why `PersistentUserSessionProvider` is fetching everything in the query. I would have to remove the limits in the Ickle query and fetch everything too :cry:  It would be a nasty piece of code :rofl: 
The link to the issue in your comment seems incorrect. 
I'll fix the implementation after my holidays.

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java]: Link fixed. I would assume your approach is a lot more efficient - let's discuss and don't rush to an implementation. With that other issue implemented, it shouldn't happen so often.

**Review by mhajas — APPROVED** [review]
Approving based on the review from @pruivo
