### PR TITLE
Invalidating offline token is not working from client sessions tab

### LINKED ISSUE #27275: Invalidating offline token is not working from client sessions tab
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have configured an user and public client with direct access grant. 
Then used offline token scope to retrieve access_token and refresh_token through "*/protocol/openid-connect/token" endpoint.
Now i want to invalidate/revoke offline_token using Keycloak ui , 
I tried to logout the offline session from Client details --> Sessions tab. 
Screenshot 2024-02-26 at 11 11 20 am

But Offline token is not invalidated, iam able to get new access_token using the offline token received earlier.

### Version

keycloak-23.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Offline token should be invalidated and should not allow to retrieve access token using the offline token

### Actual behavior

 Able to get new access_token using the offline token  which was logged out through UI

### How to Reproduce?

1. Configured an user and public client with direct access grant. 
2. Get access_token and refresh_token through "*/protocol/openid-connect/token" endpoint , using offline token scope 
3.  Logout the offline session from Keycloak UI by going to Client details --> Sessions tab. 
4.  Now  get new access token using the offline token "*/protocol/openid-connect/token" endpoint
     Able to retrieve access token using the offline token 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes #27275

### CODE REVIEW

File: js/apps/admin-ui/src/sessions/SessionsTable.tsx [hunk 1]
```diff
@@ -185,8 +204,16 @@ export default function SessionsTable({
         }
         columns={columns}
         actionResolver={(rowData: IRowData) => {
-          if (rowData.data.type === "OFFLINE") {
-            return [];
+          if (
+            rowData.data.type === "Offline" ||
+            rowData.data.type === "OFFLINE"
```
Comment (jonkoops) [inline js/apps/admin-ui/src/sessions/SessionsTable.tsx:209]: Why do we have two similar types here? This seems like an issue with the data provided, can it not be normalized in the REST API, or even the database?

Comment (martin-kanis) [reply js/apps/admin-ui/src/sessions/SessionsTable.tsx:209]: There is an inconsistency how sessions are obtained on `sessions` page and on `clients/{clientid}/sessions` page. As a result there are different sessions types. Created https://github.com/keycloak/keycloak/issues/28124
For this PR, I had to work with what we have at place ATM as this needs to be ready for 24 backport ASAP.

**Review by jonkoops — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]
I'm not sure if we need to differentiate in-memory and offline sessions when deleting sessions but not a blocker.
