### PR TITLE
Remove the timeout in authChecker when page is unloaded

### LINKED ISSUE #30334: RESTART_AUTHENTICATION_ERROR when login in in private browser window after 25.0.0 update
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Today I updated from 24.0.5 to 25.0.0 on out test system. Update using the upgrade guide worked smoothly, thanks for that.
But now I see a RESTART_AUTHENTICATION_ERROR event every time I try to login in a private browser window (Edge, Firefox, Chrome) directly after login. The client gets an error response afterwards.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Login without event and with success response to client.

### Actual behavior

Event RESTART_AUTHENTICATION_ERROR directly after login and error response to client.

### How to Reproduce?

- Close all browser windows
- Start a new private browser window
- Navigate to client
- Client redirects to Keycloak
- Login using username/password
- Event RESTART_AUTHENTICATION_ERROR will be logged, Keycloak redirects to client with error response

### Anything else?

Issue occurs on all major browsers (Edge, Chrome, Firefox). If no private browser window is used, it will work without any issue.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #30334

Just removing the timeout if the page is unloaded. It avoids the execution of the timer after the login page has been submitted. There are other some minor changes done by lint at commit.

### CODE REVIEW

**Comment by anatolinicolae** [comment]
LGTM, nice! 👍

**Review by mposolda — DISMISSED** [review]
@rmartinc Thanks!

File: themes/src/main/resources/theme/base/login/resources/js/authChecker.js [hunk 1]
```diff
@@ -1,6 +1,15 @@
 const CHECK_INTERVAL_MILLISECS = 2000;
 const initialSession = getSession();
 
+let timeout;
+
+addEventListener("beforeunload", () => {
```
Comment (jonkoops) [inline themes/src/main/resources/theme/base/login/resources/js/authChecker.js:6]: Let's add a comment here describing why we need this code, so that future devs be able to understand it at a glance.

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: themes/src/main/resources/theme/base/login/resources/js/authChecker.js (hunk 1 above)
Comment (rmartinc) [reply themes/src/main/resources/theme/base/login/resources/js/authChecker.js:8]: :+1:  Done!

**Review by jonkoops — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving on @jonkoops' and @mposolda's previous review. Thanks!
