### PR TITLE
fixed search on only one resource

### LINKED ISSUE #38458: [FGAP] [UI] Permission search doesn't execute correct consequent search request
When searching for permissions following behavior occurs:

Steps:
* create `user-1` and `user-2` users
* create user permission to `view` specific user and select `user-1`
* create user permission to `view` specific user and select `user-1` and `user-2`
* in `Search permission` choose `Users` type and select `user-2`
* click `Search`
* there is request sent, similar to 
```GET | http://localhost:8080/admin/realms/master/clients/7eb7ecaa-a65f-4918-a7ae-4a37c54181e5/authz/resource-server/permission/scope?first=0&max=11&resourceType=Users&resource=6f1155c0-e518-4301-9cb1-476aeeba53ef```
* one permission is returned and visible in the list
* click `Search permission` again in `Users` field add `user-1`, now there are two user present
* but request sent is exactly the same: ```GET | http://localhost:8080/admin/realms/master/clients/7eb7ecaa-a65f-4918-a7ae-4a37c54181e5/authz/resource-server/permission/scope?first=0&max=11&resourceType=Users&resource=6f1155c0-e518-4301-9cb1-476aeeba53ef```
* and therefore the returned permissions is also the same

It seems that second user who was added was omitted from the request.

It request should look like ```GET | http://localhost:8080/admin/realms/master/clients/7eb7ecaa-a65f-4918-a7ae-4a37c54181e5/authz/resource-server/permission/scope?first=0&max=11&resourceType=Users&resource=6f1155c0-e518-4301-9cb1-476aeeba53ef&${user-1.id}```

### PR DESCRIPTION
**Pull request by edewit**
fixes: #38458
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

File: js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx [hunk 1]
```diff
@@ -95,7 +95,9 @@ export const ResourceType = ({
             resourceType: normalizedResourceType,
           })}
           defaultValue={[]}
-          variant="typeaheadMulti"
+          variant={withEnforceAccessTo ? "typeaheadMultiple" : "typeahead"}
```
Comment (ssilvert) [inline js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx:98]: Did you mean `typeaheadMulti` instead of `typeaheadMultiple`?

**Review by ssilvert — CHANGES_REQUESTED** [review]

**Review by vramik — APPROVED** [review]

File: js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx (hunk 1 above)
Comment (edewit) [reply js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx]: yes, good catch

**Review by ssilvert — APPROVED** [review]
