### PR TITLE
fix: making the deadline override applicable to all remote tests

### LINKED ISSUE #37392: [Jenkins Operator CI] - UpgradeTest#testImageChange
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

https://keycloak-jenkins.com/view/OpenShift/job/rhbk-operator-test-pipeline/1163/testReport/org.keycloak.operator.testsuite.integration/UpgradeTest/testImageChange_UpdateStrategy__3_/

```
2025-02-16 21:44:07  [ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 441.238 s <<< FAILURE! - in org.keycloak.operator.testsuite.integration.UpgradeTest
2025-02-16 21:44:07  [ERROR] org.keycloak.operator.testsuite.integration.UpgradeTest.testImageChange(UpdateStrategy)[3]  Time elapsed: 161.572 s  <<< FAILURE!
2025-02-16 21:44:07  java.lang.AssertionError: java.util.concurrent.TimeoutException
2025-02-16 21:44:07  	at org.keycloak.operator.testsuite.integration.UpgradeTest.await(UpgradeTest.java:215)
2025-02-16 21:44:07  	at org.keycloak.operator.testsuite.integration.UpgradeTest.testImageChange(UpgradeTest.java:71)
2025-02-16 21:44:07  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)

```

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #37392

### CODE REVIEW

**Review by pruivo — APPROVED** [review]

**Review by vmuzikar — DISMISSED** [review]

**Comment by shawkins** [comment]
Needed to update this - that modification mechanism is not transitive, so it needs to start at the Deployment.

**Comment by shawkins** [comment]
> I think there is a typo in the test file. As per the existing property which was passed in ci.yml naming convention for env variable should be `KC_OPERATOR_KEYCLOAK_UPDATE_POD_DEADLINE_SECONDS` instead of `KC_OPERATOR_KEYCLOAK_UPDATED_POD_DEADLINE_SECONDS`.

Quite right, updated again. If we encouter needing another common test property like this, I'll definitely want to drive it from a single place - so that we don't have to worry about copy paste.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java [hunk 1]
```diff
@@ -175,6 +174,9 @@ private static void createRBACresourcesAndOperatorDeployment() throws FileNotFou
             ((ClusterRoleBinding)obj).getSubjects().forEach(s -> s.setNamespace(namespace));
         } else if (obj instanceof RoleBinding && "keycloak-operator-view".equals(((RoleBinding)obj).getMetadata().getName())) {
             return null; // exclude this role since it's not present in olm
+        } else if (obj instanceof Deployment) {
+            // set values useful for testing - TODO: could drive this in some way from the test/resource/application.properties
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:178]: Now that you mention application.properties. It might be quite easy to get it, no? SmallRye Config is available in the test context, isn't it?

This is not a blocker, though. Approving regardless.

**Review by vmuzikar — APPROVED** [review]

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java (hunk 1 above)
Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:178]: > It might be quite easy to get it, no? SmallRye Config is available in the test context, isn't it?

Easy to get to the config or even the properties file - not so easy to determine what should be set on the operator as we put other stuff in there for unit testing.
