### PR TITLE
fix: adds back reporting of non-ip client addresses

### LINKED ISSUE #36843: Login with x-forwarded-for: IP address in user login event is null
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

Since Keycloak version 26.0.6, the user login events do no longer show an IP address if the user logged in with x-forwarded-for.

### Version

26.1.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Login event shows the IP address from the x-forwarded-for header.

Image

### Actual behavior

IP address in the login event is null.

Image

### How to Reproduce?

Requires a keycloak instance with https enabled.

1.) Build docker image: `docker build . -t my_keycloak_image:26.1.0`

Dockerfile:
```
FROM quay.io/keycloak/keycloak:26.1.0  as builder

ENV KC_HEALTH_ENABLED=false
ENV KC_METRICS_ENABLED=false
ENV KC_FEATURES=token-exchange

FROM quay.io/keycloak/keycloak:26.1.0
COPY --from=builder --chown=1000:1000 /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=<my_server>" -alias <my_server_alias> -ext "SAN:c=DNS:<my_server>,IP:<my_server_ip>" -keystore conf/server.keystore

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

2.) Run docker image

`docker run -d -p 8443:8443 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin -e KC_PROXY_HEADERS=xforwarded -e KC_PROXY_ADDRESS_FORWARDING=true -e KC_HOSTNAME=<my_server> my_keycloak_image:26.1.0`

3.) Login at https://<my_server>:8443 and enable user events in the realm settings

4.) Use Postman or the like to obtain an access token:

POST https://<my_server>:8443/realms/master/protocol/openid-connect/token
Body (x-www-form-urlencoded): grant_type=password, username=admin, password=admin, client_id=admin-cli
Header: x-forwarded-for=xxx.xxx.xxx.1234

5.) Make a request with the obtained access token:

GET https://<my_server>:8443/admin/realms
Authorization: Bearer, token

6.) Check the user events in the admin console

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #36843

For an initial proposal:
- where we are simply capturing what is called the client ip (which was most places like DeviceRepresentation, SessionRepresentation, etc.) those have been changed to use the remote host instead. I can update the javadocs of the relevant getIpAddress or similar methods to indicate that they aren't always ip addresses if that seems warranted. As mentioned in the issue the only alternative is to put in a more obviously invalid form of the host - such as \:host - so that any attempt to use a basic InetAddress forName will fail without a dns lookup.
- in places where we were differentiating, no changes were made, but I did update the policy evaluation api docs
- the additional places where we were might resolve an InetAddress, they were updated to better handle the null case to avoid any processing - see the TrustedHost logic
- in remote apis where we were sending a client ip, those will now do a null check - this was done for the google identity provider and registration recapta

@mabartos @vmuzikar @pedroigor WDYT?

### CODE REVIEW

File: services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java [hunk 1]
```diff
@@ -855,25 +872,33 @@ public Response handleBrowserException(Exception failure) {
...
+                    return e.getResponse();
+                }
                 return ErrorPage.error(session, authenticationSession, Response.Status.BAD_REQUEST, e.getUserErrorMessage());
             } else {
                 ServicesLogger.LOGGER.failedAuthentication(e);
                 event.error(Errors.INVALID_USER_CREDENTIALS);
-                if (e.getResponse() != null) return e.getResponse();
+                if (e.getResponse() != null) {
+                    return e.getResponse();
+                }
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java:901]: I'm sorry, I haven't yet fully reviewed the PR but I wonder if we could limit unrelated changes like this (splitting conditions to multiple lines) in the PR. It adds some additional noise and makes it a bit harder to review. We could do some refactor like  that as a follow-up. Thanks.

Comment (shawkins) [reply services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java:901]: Sure, it's just happening because of an automatic setting in the IDE. Do you want me to remove them?

Comment (vmuzikar) [reply services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java:901]: Yes please, if you don't mind.

Comment (shawkins) [reply services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java]: Removed and the additional javadocs added.

File: services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java [hunk 2]
```diff
@@ -80,7 +80,9 @@ protected boolean validate(ValidationContext context, String captcha, Map<String
         List<NameValuePair> formparams = new LinkedList<>();
         formparams.add(new BasicNameValuePair("secret", config.get(SECRET_KEY)));
         formparams.add(new BasicNameValuePair("response", captcha));
-        formparams.add(new BasicNameValuePair("remoteip", context.getConnection().getRemoteAddr()));
+        if (context.getConnection().getRemoteAddr() != null) {
+            formparams.add(new BasicNameValuePair("remoteip", context.getConnection().getRemoteAddr()));
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java:84]: Do we know the implications on the form if the IP is missing?

File: services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientUpdaterSourceHostsCondition.java [hunk 3]
```diff
@@ -85,7 +85,11 @@ public ClientPolicyVote applyPolicy(ClientPolicyContext context) throws ClientPo
     private boolean isHostMatched() {
         String hostAddress = session.getContext().getConnection().getRemoteAddr();
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientUpdaterSourceHostsCondition.java:86]: Should we use `getRemoteHost` here instead? Or if we're really validating the IP, why are we using `getRemoteHost` there?

File: services/src/main/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicy.java [hunk 4]
```diff
@@ -97,29 +97,34 @@ protected void verifyHost() throws ClientRegistrationPolicyException {
 
         String hostAddress = session.getContext().getConnection().getRemoteAddr();
 
-        verifyHost(hostAddress);
-    }
+        logger.debugf("Verifying remote host : %s", session.getContext().getConnection().getRemoteHost());
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicy.java:100]: Similar question as above. Why to log host if what we're really checking is the IP?

**Review by vmuzikar — COMMENTED** [review]
Thanks for the PR.

Looks good in general. Added some comments/questions.

We'd also need a review from a core team. CC @pedroigor @mposolda

The way I understand it is that it's basically a regression caused by https://github.com/keycloak/keycloak/pull/35247. I wonder if we should've originally consider this as a breaking change for the upgrading guide as some extension can be using it as well.

**Comment by shawkins** [comment]
> The way I understand it is that it's basically a regression caused by https://github.com/keycloak/keycloak/pull/35247. I wonder if we should've originally consider this as a breaking change for the upgrading guide as some extension can be using it as well.

We did note it as a breaking change.

File: services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientUpdaterSourceHostsCondition.java (hunk 3 above)
Comment (shawkins) [reply services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientUpdaterSourceHostsCondition.java:86]: For display / logging purposes we're using the host.

File: services/src/main/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicy.java (hunk 4 above)
Comment (shawkins) [reply services/src/main/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicy.java:100]: For display / logging purposes we're using the host.

File: services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java (hunk 2 above)
Comment (shawkins) [reply services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java:84]: For both of these scnenarios the ip is an optional parameter. It seems to be used as an anti-fraud mechanism. If it's missing my guess is that you're more likely to see throttling.

Comment (vmuzikar) [reply services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java:84]: Ok, makes sense. Thanks.

**Review by vmuzikar — DISMISSED** [review]
LGTM, thanks!

> We did note it as a breaking change.

Ah, I forgot it was part of a micro release.

Before merge, it'd be good to get an approval from core.

**Comment by vmuzikar** [comment]
@shawkins Can you also please rebase to resolve the conflict?

**Comment by shawkins** [comment]
> @shawkins Can you also please rebase to resolve the conflict?

Should be good now.

**Review by mabartos — DISMISSED** [review]
LGTM.

btw. where are exactly these upgrading notes? Users should be probably notified about this change even for the upcoming release?

**Review by vmuzikar — DISMISSED** [review]

**Comment by mabartos** [comment]
@mposolda @pedroigor Guys, would you find a little of your time to check this PR? Thanks!

**Review by pedroigor — DISMISSED** [review]

**Review by mposolda — DISMISSED** [review]
I am fine with the idea. I did not reviewed very deeply as I am leaving to cloud-native team members for doing that. But you can consider approved from me.

Looks ok, but will need rebase as already mentioned by @vmuzikar .

**Review by pedroigor — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]
