### PR TITLE
Use SessionExpirationUtils for validate user and client sessions. Check client session is valid in TokenManager.

### LINKED ISSUE #24936: Negative token expiration when changing client session max lifetime
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When adding a client session max limit, Keycloak will generate refresh and access tokens with negative token lifetime.

### Version

22.0.5, nightly

### Expected behavior

Keycloak creates a new client session and a new token with positive token expiration based on the client session settings.

### Actual behavior

Keycloak uses the original start date of the first client session and calculates the expiry date based on the now reduced client session max.

### How to Reproduce?

1. Do an authcode flow to retrieve an access+refresh token.
2. Enter a client session max of 1 minute in the realm settings.
3. Wait at least one minute.
4. Do another authcode flow to retrieve an access+refresh token, both tokens will have expiration date in the past and expires_in is negative in the response.

### Anything else?

This is really a corner case, probably not that critical.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #24936

This PR checks the client session in the token manager to not manage a expired client session that generates negative values. Besides I have also unified the `AuthenticationManager.isSessionValid` to also use `SessionExpirationUtils` calculations. I'm sending a draft because of the last change. This is modifying some tests because previously the `isSessionValid` used just the remember-me values when the session was remember-me. Now it uses teh max value between the remember-me value and the normal sso value (as `SessionExpirationUtils` does). I think we should add a little upgrade note if we decide to continue this way. There are other two options: continue doing the calculation like before; change calculation in `SessionExpirationUtils` to use one or the other value. I prefer this way.

@mposolda @douglaspalmer Can you please test and review if you see something wrong?

### CODE REVIEW

**Review by douglaspalmer — APPROVED** [review]
LGTM

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java [hunk 1]
```diff
@@ -1356,6 +1349,168 @@ public void refreshTokenUserClientMaxLifespanGreaterThanSession() throws Excepti
         }
     }
 
+    @Test
+    public void refreshTokenUserSessionMaxLifespanModifiedAfterTokenExchange() throws Exception {
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java:1353]:
```suggestion
    public void refreshTokenUserSessionMaxLifespanModifiedAfterTokenRefresh() throws Exception {
```

Minor nitpick to rename this method as it does not have anything to do with "token exchange" and hence is a little bit misleading.

Few other places in this class of similar naming.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java [hunk 2]
```diff
@@ -1356,6 +1349,168 @@ public void refreshTokenUserClientMaxLifespanGreaterThanSession() throws Excepti
...
+            assertEquals(0, checkIfUserAndClientSessionExist(sessionId, loginEvent.getClientId(), clientSessionId));
+        } finally {
+            getTestingClient().testing().revertTestingInfinispanTimeService();
+            events.clear();
+            resetTimeOffset();
+        }
+    }
+
+    @Test
+    public void refreshTokenClientSessionMaxLifespanModifiedAfterTokenExchange() throws Exception {
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java:1396]:
```suggestion
    public void refreshTokenClientSessionMaxLifespanModifiedAfterTokenRefresh() throws Exception {
```

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java [hunk 3]
```diff
@@ -1356,6 +1349,168 @@ public void refreshTokenUserClientMaxLifespanGreaterThanSession() throws Excepti
...
+            assertEquals(0, checkIfUserAndClientSessionExist(sessionId, loginEvent.getClientId(), clientSessionId));
+        } finally {
+            getTestingClient().testing().revertTestingInfinispanTimeService();
+            events.clear();
+            resetTimeOffset();
+        }
+    }
+
+    @Test
+    public void silentLoginClientSessionMaxLifespanModifiedAfterTokenExchange() throws Exception {
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java:1459]:
```suggestion
    public void silentLoginClientSessionMaxLifespanModifiedAfterTokenRefresh() throws Exception {
```

File: services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java [hunk 4]
```diff
@@ -199,6 +199,12 @@ public TokenValidation validateToken(KeycloakSession session, UriInfo uriInfo, C
             }
         }
 
+        if (!AuthenticationManager.isClientSessionValid(realm, client, userSession, clientSession)) {
+            logger.debug("Client session is disabled");
+            userSession.removeAuthenticatedClientSessions(Collections.singletonList(client.getId()));
+            throw new OAuthErrorException(OAuthErrorException.INVALID_GRANT, "Client session disabled");
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java:205]: Nitpick: Isn't it "Client session expired" more accurate than "Client session disabled" ? If yes, similar probably applies also for debug message above.

**Review by mposolda — COMMENTED** [review]
@rmartinc @douglaspalmer Thanks for the fix and review!

I've added some nitpick comments, which can be easily fixed (if you think they make sense) as the rebase in fixing conflict is needed anyway.

+1 for adding some migration documentation

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java (hunk 1 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java]: Done! I have changed all the methods...

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java (hunk 2 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java]: Done!

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java (hunk 3 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java]: Done!

File: services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java (hunk 4 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java]: Yep, you are right, I have changed it to `Client session not active` to be consistent with the user session message.

**Comment by rmartinc** [comment]
@mposolda Moving from draft as we all agreed to change the calculation like in the other parts. Requested changes added and rebased because there was a conflict.

**Comment by rmartinc** [comment]
The new Persistent Session IT tests were failing. The reason seems to be that if the client session is removed and added in the same transaction the old session remains. I have changed to (instead of remove/add) do a restart similar to what we do in the user session. I'm adding @ahus1 to review because maybe I'm doing something wrong. :smile: 
All tests pass now in my branch.

**Comment by ahus1** [comment]
@rmartinc - can you please point me to where you did this change?

**Comment by rmartinc** [comment]
> @rmartinc - can you please point me to where you did this change?

Yes, [here](https://github.com/keycloak/keycloak/pull/29013/files#diff-fd8b1c47da5ec7ee42d5450d3f7b73cdeef9c08af26b825c9245e3e6052c5cdfR578). In the previous version of the PR there was a remove/create of the client session. Now I created a `restartClientSession` that just cleans/adds the default client session values again. For that I added that method in [AuthenticatedClientSessionModel](https://github.com/keycloak/keycloak/pull/29013/files#diff-b4014a5e9c73d54dc98153e6fa64803e21ab0646a75566cf74ca9a02abbb18dbR77) and [AuthenticatedClientSessionAdapter](https://github.com/keycloak/keycloak/pull/29013/files#diff-c185363ae3c4ea873fe04e5057cd15688da7764fc306ca33157442ffa381c4d9R324)

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks for the updates!

@ahus1 Could you please review or delegate to someone from the cross-dc team for the review?

**Review by ahus1 — APPROVED** [review]
Thank you for the PR, looks good to me.
