### PR TITLE
Loading message bundles using the flat-classpath theme provider

### LINKED ISSUE #11186: Theme resources are not loaded correctlyusing quarking when having multiple providers
### Describe the bug

When having multiple providers delivering themes resources containing messages only the first 'seen' provider get its messages loaded, all other providers are ignored. This seems to be related to the quarkus build configuration where only a single message bundle gets processed. 

### Version

17.0.1

### Expected behavior

Load message bundles from all providers

### Actual behavior

Only a single message bundle gets loaded (the first provider seen by the quarkus build)

### How to Reproduce?

Create 2 e.g. authentication providers each containing a theme-resources folder
First provider: 
Add template folder and add template-1.ftl
Add message folder and add messages_en.properties
Implement authentication provider and factory running a form challenge rendering template-1
Build and copy jar to keycloak providers  directory

Second provider:
Add template folder and add template-2.ftl 
Add message folder and add messages_en.properties
Implement authentication provider and factory running a form challenge rendering template-2
Build and copy jar to keycloak providers directory 

Start keycloak  (./kc.[bat|sh] start-dev)
Configure the browser flow authentication flow containing an execution on provider 1
Try login
Messages from the message bundle may be shown properly or the message key is visible (issue triggered, stop here)
Change the browser flow authentication removing provider 1 and adding provider 2
Try login
Messages from the message bundle are shown by their message key.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #11186

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/themes/FlatClasspathThemeResourceProviderFactory.java [hunk 1]
```diff
@@ -19,9 +19,15 @@
...
 import java.io.InputStream;
+import java.io.InputStreamReader;
+import java.io.Reader;
 import java.net.URL;
+import java.nio.charset.Charset;
 import java.util.Enumeration;
+import java.util.Locale;
+import java.util.Properties;
 import org.keycloak.theme.ClasspathThemeResourceProviderFactory;
+import org.keycloak.theme.PropertiesUtil;
```
Comment (DGuhr) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/themes/FlatClasspathThemeResourceProviderFactory.java:30]: could you please remove the unused imports here? The code that used these seems to be in [ClasspathThemeResourceProviderFactory.java](https://github.com/keycloak/keycloak/pull/11711/files#diff-7e5492140ee2d42c1e7456d9bed8ce8d61598d76410118b5eeb50510921c7874) now.

**Review by stianst — DISMISSED** [review]

**Review by DGuhr — DISMISSED** [review]

**Review by stianst — APPROVED** [review]
