### PR TITLE
fix: allow the keycloak instances to stop gracefully on deletion

### LINKED ISSUE #28244: Pick up operator sdk fix to prevent invalid cache state with intervening deletions
### Description

There is a narrow timing issue with the operator sdk temporary cache related to deletions that happen during an add / update opertation, we need the [upstream fix](https://github.com/operator-framework/java-operator-sdk/issues/2314) to address this.

Once we pickup the fix we can simplify the changes made by #27904

### LINKED ISSUE #34868: [Jenkins Operator CI] - Test remote - ClusteringTest on OpenShift
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

The following tests are failing constantly when running on OpenShift:

```
2024-11-10 21:55:13  [ERROR] Errors: 
2024-11-10 21:55:13  [ERROR]   ClusteringTest.testKeycloakCacheIsConnected:243 » ConditionTimeout Assertion condition defined as a Lambda expression in org.keycloak.operator.testsuite.integration.ClusteringTest 
2024-11-10 21:55:13  Expecting any elements of:
2024-11-10 21:55:13    [KeycloakRealmImportStatusCondition{type='Done', status=False, message=''},
2024-11-10 21:55:13      KeycloakRealmImportStatusCondition{type='Started', status=False, message=''},
2024-11-10 21:55:13      KeycloakRealmImportStatusCondition{type='HasErrors', status=True, message='Deployment not yet ready, waiting for it to be ready'}]
2024-11-10 21:55:13  to match given predicate but none did within 10 minutes.
2024-11-10 21:55:13  [ERROR]   ClusteringTest.testKeycloakScaleAsExpected:146 » ConditionTimeout Assertion condition defined as a Lambda expression in org.keycloak.operator.testsuite.utils.K8sUtils found status KeycloakStatusCondition{type='Ready', status=False, message='Waiting for more replicas'} and expected status true within 5 minutes.
2024-11-10 21:55:13  [INFO] 
2024-11-10 21:55:13  [ERROR] Tests run: 125, Failures: 0, Errors: 2, Skipped: 5
```
https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/893/execution/node/69/log/

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
also reusing curl pods when there is no label

closes: #34868
closes: #28244

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
LGTM, still I understand only half of what is happening here and why there was the old code. Giving others the chance to review this one as well.

**Review by pruivo — APPROVED** [review]

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java [hunk 1]
```diff
@@ -298,37 +297,21 @@ private static void setDefaultAwaitilityTimings() {
...
+                  .statefulSets()
+                  .inNamespace(namespace)
+                  .withLabels(Constants.DEFAULT_LABELS).informOnCondition(List::isEmpty).get(20, TimeUnit.SECONDS);
       } catch (Exception e) {
-          // delete event should have arrived quickly because this is a background delete
-          throw new RuntimeException(e);
+          throw KubernetesClientException.launderThrowable(e);
       }
-      dependents.stream().map(c -> k8sclient.resources(c).withLabels(Constants.DEFAULT_LABELS))
-              .forEach(r -> r.withGracePeriod(10).delete());
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:319]: Are we sure this PR fixes #34868? We were already killing resources with a grace period here. The forcible killing doesn't happen with these changes as  hinted [here](https://github.com/keycloak/keycloak/issues/34868#issuecomment-2604772007)?

In any case, let's give it a try and we'll see if this pops up again.

**Review by vmuzikar — APPROVED** [review]
LGTM, let's give this a try. Thanks for the changes, @shawkins!

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java (hunk 1 above)
Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:319]: > We were already killing resources with a grace period here.

The following lines could supercede that with a termination without a grace period.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:319]: Wouldn't that happen only if the 10 seconds grace period would be passed?

Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:319]: No, those aren't blocking calls.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:319]: Ah, right. We proceed immediately to the forced killiling. Ok, that makes sense, thanks for the context. 👍

Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:319]: Still unsure of why this failure only started to happen more recently and seemingly only on openshift.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:319]: Our OCP env is a bit specific and different from what we run here in minikube. Let's see if this fix helps.
