### PR TITLE
Stabilize testCreateUserSessionsParallel model test

### LINKED ISSUE #13281: Model test `UserSessionProviderModelTest#testCreateUserSessionsParallel` is unstable
### Describe the bug

The test is unstable, see for example: https://github.com/keycloak/keycloak/actions/runs/2715531851

### Version

main

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by martin-kanis**
Fixes #13281

### CODE REVIEW

**Comment by martin-kanis** [comment]
10 parallel model test runs https://github.com/martin-kanis/keycloak/runs/7563800584?check_suite_focus=true

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java [hunk 1]
```diff
@@ -296,20 +297,50 @@ public void testCreateUserSessionsParallel() throws InterruptedException {
...
+            try {
+                Thread.sleep(1000);
+            } catch (InterruptedException e) {
+                throw new RuntimeException(e);
+            }
+
+            withRealm(realmId, (session, realm) -> {
+                userSessionIds.forEach(id -> Assert.assertNotNull(session.sessions().getUserSession(realm, id)));
+
+                latchEnd.countDown();
```
Comment (mhajas) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java:333]: Is this second latch necessary?

**Review by mhajas — COMMENTED** [review]
Thanks @martin-kanis, the fix looks good, I added one question though.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java (hunk 1 above)
Comment (martin-kanis) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java:333]: My reasoning was to prevent deletion of sessions in the cluster when nodes are destroyed. Maybe I'm too careful here. I can try to remove it and let it test by GHA.

Comment (martin-kanis) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java:333]: https://github.com/martin-kanis/keycloak/actions/runs/2774186250 It looks also good without ending latch. I'll remove it.

Comment (mhajas) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java]: Sessions should not be removed when nodes are destroyed, if it is the case we have to fix it. I believe the sessions are removed only in the `cleanEnvironment` method. 

Btw. there seems to be some collision with Dominik's commit around the DB fix. Could you have a look at the commit message?

Comment (martin-kanis) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java]: Fixed

**Review by mhajas — APPROVED** [review]
Thanks @martin-kanis, LGTM

**Review by hmlnarik — APPROVED** [review]
