### PR TITLE
Fix String comparison

### LINKED ISSUE #21773: Invalide objects comparison in Java
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

The code contains an invalid comparison where the "==" is used to compare two strings instead of the equals() method.

### Version

22.0.0

### Expected behavior

For example in `services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java` the method `validatePolicy()` contains a comparison based on the `==` line 520.

`        if (policyCheckMode == CERTIFICATE_POLICY_MODE_ANY)
`

### Actual behavior

The comparison should be based on the `equals()` method.

`        if (policyCheckMode.equals(CERTIFICATE_POLICY_MODE_ANY))
`

### How to Reproduce?

The validating certificate policies associated with X.509 certificates always fail.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by alidandach**
Closes #21773

Fix the comparison logic by replacing the usage of the "==" operator with the "equals()" method.

### CODE REVIEW

**Comment by alidandach** [comment]
If this PR will be merged, then we can close this draft PR https://github.com/keycloak/keycloak/pull/21717

**Comment by ahus1** [comment]
@alidandach - thank you for contributing this. As stated in the previous PR and as stated in `CONTRIBUTING.md`, this is missing: 

* A GitHub issue describing the problem
* A commit message following this template: 

```
A brief descriptive summary

Optionally, more details around how it was implemented

Closes #1234
```

Until this is present, I'm switching this PR to a draft PR.

**Comment by alidandach** [comment]
@ahus1 shall I create a new PR

**Comment by ahus1** [comment]
@alidandach - there is no need to create a new PR. Create a GitHub issue, and then update this PR's commit and force-push the changes. 

Maybe ask a friend to walk you though this or ask for a mentor on a Keycloak mailing list, as this is out-of-scope for a PR discussion.

File: adapters/oidc/tomcat/tomcat-core/src/main/java/org/keycloak/adapters/tomcat/AbstractKeycloakAuthenticatorValve.java [hunk 1]
```diff
@@ -68,7 +68,7 @@ public void lifecycleEvent(LifecycleEvent event) {
             cache = false;
         } else if (Lifecycle.AFTER_START_EVENT.equals(event.getType())) {
         	keycloakInit();
-        } else if (event.getType() == Lifecycle.BEFORE_STOP_EVENT) {
+        } else if (event.getType().equals(Lifecycle.BEFORE_STOP_EVENT)) {
```
Comment (ahus1) [inline adapters/oidc/tomcat/tomcat-core/src/main/java/org/keycloak/adapters/tomcat/AbstractKeycloakAuthenticatorValve.java:71]: Please swap the two sides of the `equals` operation so that they are similar to the statement above. The new order has the advantage that the first part can never be null, so I consider it a best practice.

File: core/src/main/java/org/keycloak/representations/docker/DockerError.java [hunk 2]
```diff
@@ -60,7 +60,7 @@ public boolean equals(final Object o) {
 
         final DockerError that = (DockerError) o;
 
-        if (errorCode != that.errorCode) return false;
+        if (!errorCode.equals(that.errorCode)) return false;
```
Comment (ahus1) [inline core/src/main/java/org/keycloak/representations/docker/DockerError.java:63]: Consider a null safe operation here:

```suggestion
        if (!Objects.equals(errorCode, that.errorCode)) return false;
```

File: model/jpa/src/main/java/org/keycloak/storage/jpa/entity/FederatedUserRequiredActionEntity.java [hunk 3]
```diff
@@ -120,7 +120,7 @@ public boolean equals(Object o) {
 
             Key key = (Key) o;
 
-            if (action != key.action) return false;
+            if (!action.equals(key.action)) return false;
```
Comment (ahus1) [inline model/jpa/src/main/java/org/keycloak/storage/jpa/entity/FederatedUserRequiredActionEntity.java:123]: As above, please use `Objects.equals()`

File: services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java [hunk 4]
```diff
@@ -517,7 +517,7 @@ private static void validatePolicy(X509Certificate[] certs, List<String> expecte
 
         logger.debugf("Certificate policies found: %s", String.join(",", policyList));
 
-        if (policyCheckMode == CERTIFICATE_POLICY_MODE_ANY)
+        if (policyCheckMode.equals(CERTIFICATE_POLICY_MODE_ANY))
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java:520]: Please switch the two sides of the `.equals()` to make it null-safe.

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for the PR. Please see some comments below which need to be resolved before it can be merged. Thanks!

**Review by ahus1 — APPROVED** [review]
Thank you for contributing these changes, LGTM.
