### PR TITLE
Testsuite must rely on IDs from keycloak

### LINKED ISSUE #19814: Testsuite must rely on IDs from Keycloak
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

The testsuite often creates a new object and assumes its ID. However Keycloak may introduce a different ID for the object than requested originally e.g. because of the ID format does not conform the underlying store.

Update the testsuite to determine IDs rather than expect it created as expected.

### Version

21

### Expected behavior

IDs are determined after creation from Keycloak

### Actual behavior

IDs are suggested in the REST call and then assumed their existence

### How to Reproduce?

Run any of the affected tests with a file store (`map-storage-file` testsuite profile), e.g. `AdminClientTest`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hmlnarik**
Closes: #19814

### CODE REVIEW

**Comment by hmlnarik** [comment]
Flaky text fixed with the last update.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java [hunk 1]
```diff
@@ -133,25 +133,20 @@ public void addTestRealms(List<RealmRepresentation> testRealms) {
                 .password("password");
         realm.user(defaultUser);
 
-        userId = KeycloakModelUtils.generateId();
         UserRepresentation user = UserBuilder.create()
-                .id(userId)
```
Comment (lhanusov) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java:138]: @hmlnarik In this line you are removing user id, is it generated automatically?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AudienceTest.java [hunk 2]
```diff
@@ -74,7 +74,7 @@ public void configureTestRealm(RealmRepresentation testRealm) {
 
         // Create sample user
         UserRepresentation user = UserBuilder.create()
-                .id(userId)
+                .id(KeycloakModelUtils.generateId())
```
Comment (lhanusov) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AudienceTest.java:77]: @hmlnarik Does this line differ then in the class: ResourceOwnerPasswordCredentialsGrantTest.java that id is not deleted but rather generated?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCDynamicScopeTest.java [hunk 3]
```diff
@@ -55,13 +55,13 @@
...
 
-    private static String userId = KeycloakModelUtils.generateId();
+    private static String userId;
 
     @Override
     public void configureTestRealm(RealmRepresentation testRealm) {
         super.configureTestRealm(testRealm);
         UserRepresentation user = UserBuilder.create()
-                .id(userId)
+                .id(KeycloakModelUtils.generateId())
```
Comment (lhanusov) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCDynamicScopeTest.java:64]: @hmlnarik Does this line differ then in the class: ResourceOwnerPasswordCredentialsGrantTest.java that id is not deleted but rather generated?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCScopeTest.java [hunk 4]
```diff
@@ -68,12 +68,12 @@
...
 public class OIDCScopeTest extends AbstractOIDCScopeTest {
 
-    private static String userId = KeycloakModelUtils.generateId();
+    private static String userId;
 
     @Override
     public void configureTestRealm(RealmRepresentation testRealm) {
         UserRepresentation user = UserBuilder.create()
-                .id(userId)
+                .id(KeycloakModelUtils.generateId())
```
Comment (lhanusov) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCScopeTest.java:76]: Does this line differ then in the class: ResourceOwnerPasswordCredentialsGrantTest.java that id is not deleted but rather generated?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UserManagedAccessTest.java
Comment (lhanusov) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UserManagedAccessTest.java:1]: @hmlnarik 7 out of 8 tests are failing: "Caused by: java.lang.IllegalStateException: Could not find ScriptEngine for script: Script{id='null', realmId='c6650ad2-a8d1-4f8d-b618-85d67cc5786f', name='Only Owner Policy', type='text/javascript', code='var permission = $evaluation.getPermission();"

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ScriptAuthenticatorTest.java
Comment (lhanusov) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ScriptAuthenticatorTest.java:1]: @hmlnarik all 3 tests are failing: "type=LOGIN_ERROR, realmId=test, clientId=test-app, userId=null, ipAddress=127.0.0.1, error=invalid_user_credentials"

**Review by lhanusov — COMMENTED** [review]
@hmlnarik Thank you Hynku for your PR, it is a large refactoring on multiple places, except 2 classes all tests are passing. I am fine with commenting the non relevant tests. Please can you please address my comments?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java (hunk 1 above)
Comment (hmlnarik) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java:138]: Yes

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AudienceTest.java (hunk 2 above)
Comment (hmlnarik) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AudienceTest.java:77]: No, they are the same in essence

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ScriptAuthenticatorTest.java
Comment (lhanusov) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ScriptAuthenticatorTest.java:1]: it works with JDK 11, but not with JDK 17 (@hmlnarik good assumption in case of Nashhorn)

**Review by lhanusov — APPROVED** [review]
@hmlnarik LGTM -> approve

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ScriptAuthenticatorTest.java
Comment (lhanusov) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ScriptAuthenticatorTest.java:1]: @kami619 will fix is as part of the jdk 17 compatibility update

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UserManagedAccessTest.java
Comment (lhanusov) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UserManagedAccessTest.java:1]: @kami619 will fix is as part of the jdk 17 compatibility update

**Comment by hmlnarik** [comment]
Thanks for review @lhanusov!

Re Nashorn (unrelated to this PR): I recall I had some more failures due to Nashorn in authz tests specifically when running the full testsuite with file store. Perhaps would be good to run the full arq testsuite as part of the exercise you mentioned.
