### PR TITLE
Fix flaky OfflineServletsAdapterTest test

### LINKED ISSUE #20013: Flaky test: org.keycloak.testsuite.adapter.servlet.OfflineServletsAdapterTest#testServlet
## org.keycloak.testsuite.adapter.servlet.OfflineServletsAdapterTest#testServlet
[Keycloak CI - Base IT (2)](https://github.com/keycloak/keycloak/actions/runs/4823932445/jobs/8593363010)

```
java.lang.AssertionError: 

Expected: not null
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
...
```

### PR DESCRIPTION
**Pull request by mabartos**
Fixes #20013

Possible fix for the flaky test OfflineServletsAdapterTest#testServlet.

As for this test, there were always some instabilities with the time handling, such as setting offsets for auth and app servers, which live in different JVMs. The additional time needed for app/auth interoperability could help.

Moreover, there's no need for another deserialization of obtained refresh token.

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OfflineServletsAdapterTest.java [hunk 1]
```diff
@@ -129,8 +129,10 @@ public void testServlet() {
             assertCurrentUrlStartsWith(offlineTokenPage);
 
             // assert successful refresh
-            assertThat(offlineTokenPage.getRefreshToken().getId(), not(refreshTokenId));
-            assertThat(offlineTokenPage.getAccessToken().getId(), not(accessTokenId));
+            refreshToken = offlineTokenPage.getRefreshToken();
+            assertThat(refreshToken, notNullValue());
+            assertThat(refreshToken.getId(), not(refreshTokenId));
+            assertThat(refreshToken.getId(), not(accessTokenId));
```
Comment (vmuzikar) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OfflineServletsAdapterTest.java:135]: I think the last assert should be for accessToken to match the previous behaviour?

**Review by vmuzikar — CHANGES_REQUESTED** [review]

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OfflineServletsAdapterTest.java (hunk 1 above)
Comment (mabartos) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OfflineServletsAdapterTest.java:135]: Oh, nice catch

**Review by vmuzikar — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review
