### PR TITLE
fix: adding the discovery servicename to the statefulset

### LINKED ISSUE #38757: Keycloak statefulset is not mapped to any headless service if installed via operator
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

I have installed keycloak operator 26.1.4 and also used the keycloak manifest to get the keycloak statefulset up and running. But I can see that there is no service name associated with statefulset even if there exists two headless services for keycloak (one created implicitly by keycloak manifest and one created via helm chart by myself).
Image

These are all the service associated with keycloak in my deployments:
Image

### Version

quay.io/keycloak/keycloak:26.1.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The **Service Name** field for keycloak statefulset should be mapped to one of the headless services created (implicitly or explicitly) for keycloak.

### Actual behavior

The **Service Name** field for keycloak statefulset in not bound/mapped to any one of the headless services created (implicitly or explicitly) for keycloak.

### How to Reproduce?

1. Install keycloak operator 26.1.4 on any kubernetes cluster using the following: 
`
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.1.4/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.1.4/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.1.4/kubernetes/kubernetes.yml
`
2. Install keycloak manifest using the below yaml file:
`
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: your-namespace
spec:
  instances: 1
  db:
    vendor: postgres
    host: your_db_host
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
    database: your_db_name
    port: 5432
  http:
    httpEnabled: true
  hostname:
    strict: false
`
3. Check the service name in keycloak stateful set, it must not be unbound to any headless service (created implicitly by the name **keycloak-discovery**).

### Anything else?

This issue pertains to keycloak statefulset not being associated with any service name which is a must for the statefulset to be scalable and for kubernetes internal DNS to work. There is no way to set this mapping in the existing keycloak CRD (v26.1.4).

### PR DESCRIPTION
**Pull request by shawkins**
closes: #38757

### CODE REVIEW

**Comment by shawkins** [comment]
Double checked locally that it doesn't matter what order the statefulset and service are created in - kube / minikube will create the statefulset just fine without the service in existence, and it won't cause a restart to create it after the fact.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java [hunk 1]
```diff
@@ -287,6 +287,7 @@ private StatefulSet createBaseDeployment(Keycloak keycloakCR, Context<Keycloak>
                         .editOrNewSpec().withImagePullSecrets(keycloakCR.getSpec().getImagePullSecrets()).endSpec()
                     .endTemplate()
                     .withReplicas(keycloakCR.getSpec().getInstances())
+                    .withServiceName(KeycloakDiscoveryServiceDependentResource.getName(keycloakCR))
```
Comment (vmuzikar) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:290]: Should it rather use the main service?
```suggestion
                    .withServiceName(KeycloakServiceDependentResource.getServiceName(keycloakCR))
```

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:290]: No, it's supposed to be a headless service.

Comment (vmuzikar) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:290]: From the [docs|https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/#StatefulSetSpec] it does not seem so?

Additionally it says:
> This service must exist before the StatefulSet

Despite it now works with StS created before the Service, can we really rely on it as that behaviour might change to align with the spec?

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:290]: > From the [docs](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/#StatefulSetSpec) it does not seem so?

I'm referencing https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id 

I suppose the language there does say "can", not "must" be headless.

> Despite it now works with StS created before the Service, can we really rely on it as that behaviour might change to align with the spec?

This behavior / validation has been poorly defined for quite some time. https://github.com/kubernetes/kubernetes/issues/69608 was logged years ago.

Even if it doesn't "work" at some point in the furture, the worst case behavior would be the statefulset not working until scaling up until the service is created - since these are peer dependent resources, that would be a narrow window. 

I'm leary of adding any kind of reconciliation condition for this kind of behavior - instead if you are worried about not eventually seeing some kind of ephemeral error, then I'd opt instead for Dependent.dependsOn

Comment (vmuzikar) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:290]: > Even if it doesn't "work" at some point in the furture, the worst case behavior would be the statefulset not scaling up until the service is created - since these are peer dependent resources, that would be a narrow window.

Makes sense 👍

**Review by vmuzikar — APPROVED** [review]
LGTM as I don't have a better solution in mind. Thanks @shawkins.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java (hunk 1 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:290]: > We might create a dedicated headlessService just for this purpose but that seems like an overkill at this point.

I think we'd just leave the discovery service in place. There's not much harm / risk and users may have already adopted using it for their own purposes as well.
