### PR TITLE
fix: replaces aesh with picocli

### LINKED ISSUE #28275: Migrate kcreg from aesh to picocli
### Description

Similar to #27388 for consistency and a better user experience we should migrate off of aesh. This will also help with issues like https://github.com/keycloak/keycloak/issues/27322

### PR DESCRIPTION
**Pull request by shawkins**
closes: #28275

@vmuzikar @mabartos to cut down on some duplication kcreg now depends on kcadm. In yet another pr I'd like to remove some more of the code overlap.

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

File: integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/util/IoUtil.java [hunk 1]
```diff
@@ -81,43 +73,14 @@ public static void waitFor(long millis) {
...
+        char[] passwd;
+        if ((cons = System.console()) != null &&
+            (passwd = cons.readPassword("%s", prompt)) != null) {
+            return new String(passwd);
         }
-         */
-        // Windows hack - get rid of any \n
-        result = result.replaceAll("\\n", "");
-        return result;
+        throw new RuntimeException("Console is not active, or no password provided");
```
Comment (mabartos) [inline integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/util/IoUtil.java:83]: nit - We discussed this in the PR for kcadm as it's not very user-friendly, but nothing that might block this PR.

**Review by mabartos — DISMISSED** [review]
@shawkins Nice job! I haven't spotted any issue in this PR.

**Comment by mabartos** [comment]
The failures for the Docs external links should not be related to this PR. It seems there's some "special" GitHub policy around GH accounts.

```
Broken links (6) in guide 'release_notes': 
		- https://github.com/nngo (invalid status code 429)
		- https://github.com/dasniko (invalid status code 429)
		- https://github.com/rradillen (invalid status code 429)
		- https://github.com/jonkoops (invalid status code 429)
		- https://github.com/fredbi (invalid status code 429)
		- https://github.com/daniel-ac-martin (invalid status code 429)
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
```

File: integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/util/IoUtil.java (hunk 1 above)
Comment (shawkins) [reply integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/util/IoUtil.java:83]: I should have mentioned this will be addressed by the follow-on pr that removes code duplication between the clients.

Comment (mabartos) [reply integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/util/IoUtil.java:83]: Ahh, I see; works for me.

**Comment by mabartos** [comment]
@shawkins Could you please rebase? There should already be changes for the doc test failures.

@vmuzikar PTAL, once you have some time for it.

**Review by vmuzikar — DISMISSED** [review]
LGTM, very nice work! Thank you @shawkins!

One last thing – can you please rebase?

**Comment by shawkins** [comment]
> One last thing – can you please rebase?

@vmuzikar done

**Comment by shawkins** [comment]
No failing due to the follow-on issue related to the cache configmap test.

**Comment by shawkins** [comment]
@vmuzikar should be good now

File: docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc [hunk 2]
```diff
@@ -69,9 +69,7 @@ Options `cache`, `cache-stack`, and `cache-config-file` are no longer build opti
 This eliminates the need to execute the build phase and rebuild your image due to them.
 Be aware that they will not be recognized during the `build` phase, so you need to remove them.
 
-= kcadm Changes
-
-How kcadm parses and handles options and parameters has changed. Error messages from usage errors, the wrong option or parameter, may be slightly different than previous versions. Also usage errors will have an exit code of 2 instead of 1.
+How kcadm and kcreg parse and handle options and parameters has changed. Error messages from usage errors, the wrong option or parameter, may be slightly different than previous versions. Also usage errors will have an exit code of 2 instead of 1.
```
Comment (vmuzikar) [inline docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc:72]: @shawkins Can you please (re-)add a heading here?

Comment (shawkins) [reply docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc]: Sorry, added it back.

**Review by mabartos — APPROVED** [review]
@shawkins LGTM

**Review by vmuzikar — APPROVED** [review]
