### PR TITLE
Brute Force Detection is disabled when updating frontenUrl via admin client

### LINKED ISSUE #21409: Brute Force Detection is disabled when updating frontenUrl via admin client
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/node

### Describe the bug

When the frontenUrl is updated through the admin client e.g.: 
```     
 await this.client.realms.update(
        {realm},
        {
          attributes: {
            frontendUrl: `${frontendUrl}/auth`,
          },
        },
      );
 ```

the brute force detection mechanism is unexpectedly disabled.

### Version

21.1.1

### Expected behavior

Changing the frontenUrl attribute should not affect brute force settings

### Actual behavior

Brute force detection is disabled when changing frontenUrl

### How to Reproduce?

1. Enable brute force detection for a realm using the Keycloak admin UI.
2. Set a new frontendUrl for this realm using the Keycloak admin client.
3. Inspect the brute force settings for this realm using the Keycloak admin UI.

### Anything else?

Same behaviour with security header settings. They are also deleted when the frontendUrl is updated. Seems to affect all security defence settings of the realm

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #21409

### CODE REVIEW

**Review by mposolda — COMMENTED** [review]
Is it possible to run UI tests with this change as well?

They are not executed automatically by GH actions on this PR due the fact that nothing is changed in the UI. But it is possible to test them by creating another branch with your changes, then doing some "dummy" change in the UI files (just to enforce UI build) and then push this new branch. Perhaps something like:
```
git checkout 21409
git checkout -b 21409-with-dummy-ui-change
// Change something in the UI files
git add -A
git commit -s -m "Commit of dmmy UI change"
git push origin 21409-with-dummy-ui-change
# Now see if UI tests are OK in your repo ...
```

For the possible "Dummy" change, which triggers UI tests - this one can be good to go for the inspiration: https://github.com/keycloak/keycloak/pull/26561#discussion_r1469973403 .

Separate branch is good just so that you don't need to push dummy change to the original PR .

Another note: There is also PR from Stian, which is a different fix, but maybe bit related: https://github.com/keycloak/keycloak/pull/26729 . Can be probably good to rebase your fix on top of that one. I guess it would be ready in main in next few hours, so likely when you're reading this, it is already in Keycloak main :-)

File: model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java [hunk 1]
```diff
@@ -813,11 +815,15 @@ public void updateRealm(RealmRepresentation rep, RealmModel realm) {
             realm.setPasswordPolicy(PasswordPolicy.parse(session, rep.getPasswordPolicy()));
         if (rep.getOtpPolicyType() != null) realm.setOTPPolicy(toPolicy(rep));
 
-        WebAuthnPolicy webAuthnPolicy = getWebAuthnPolicyTwoFactor(rep);
-        realm.setWebAuthnPolicy(webAuthnPolicy);
+        if (rep.getWebAuthnPolicyRpEntityName() != null && !rep.getWebAuthnPolicyRpEntityName().isEmpty()) {
```
Comment (pedroigor) [inline model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java:818]: This is why I'm afraid of fixing this globally. I guess you added this because for this one it behaves differently, right?

Comment (douglaspalmer) [reply model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java:818]: This is slightly orthogonal to the attribute fix. The WebAuthn policy is regenerated regardless of whether or not the attributes have changed. If the new RealmRepresentation has no WebAuthn attributes then the current WebAuthn policy is replaced by the defaults.

**Review by pedroigor — APPROVED** [review]
