### PR TITLE
reset error on new fetch it could be resolved

### LINKED ISSUE #31638: Error when non-admin user accesses admin console
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

My installation has multiple users who have access to the admin console for specific realms, not including the master realm. For example, a user has permissions to manage other users in a different realm. Previously when that user would log in, they would view the Keycloak homepage and be able to select the necessary page in a different realm. Now, those users are able to successfully log in still, but receive an error on the homepage. While they are able to navigate to other pages (including ones that should work), the error doesn't go away.

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Users who have admin access to specific realms should be able to access those realms in the admin ui without error.

### Actual behavior

Users who do not have the master realm's `view-realm` role receive an error when logging in, and the refresh button in the error does not help. Additionally, navigating to other pages they should have access to still gives the same error.

### How to Reproduce?

1. Create a new user in the master realm.
2. Give that user non-master realm permissions without any master realm permissions.
3. Log in to the admin console as that user.

### Anything else?

Previously, the master realm users were able to see Keycloak statistics, such as version and memory allocation. I agree that users who do not have access to the master realm should not be able to see that information, but they should not get an error just by logging in.

### LINKED ISSUE #32847: Admin UI defaults to master realm even without permissions to it
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When logging into the admin UI (`/admin/master/console/`) with a user that has no permissions to view the `master` realm, the user is greeted with a "Network response was not OK." message because `whoami?currentRealm=master` returns a 403 Forbidden.

When then selecting the correct realm in the drop down the UI does not reload/change, while the URL does (`/admin/master/console/#/test`) and clicking "Press here to refresh and continue" the default URL (`/admin/master/console/`) is refreshed, not the one of the just selected realm.

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that the UI redirects to the first valid realm and does not fallback/stop to the default `master` realm, when the user does not have access to it.

At least I would expect, that selecting a valid realm in the drop down, refreshes the UI and actually loads the content of the requested realm (not just the navigation bar on the left).

### Actual behavior

See "Describe the bug" ☝🏻 

### How to Reproduce?

1. Create a user that has no access to the `master` realm. For example with a group like this:

```yml
groups:
  - name: user-manager
    clientRoles:
      test-realm:
        - view-users
        - query-users
        - manage-users
        - query-groups
```

2. Log in with that user on `<url>/admin/master/console/`
3. You are greeted with
image
4. Selecting "test" in the realm drop down and only updates the navigation bar on the left, not the content itself.
5. Clicking "Press here to refresh and continue" redirects back to `<url>/admin/master/console/` which results in 3.

### Anything else?

When directly calling the UI for a valid realm (`/admin/master/console/#/test`), then it works as expected. So as a workaround the users need to bookmark the "correct" URL, instead of the base URL.

### PR DESCRIPTION
**Pull request by edewit**
reset error so when doing a new request, error could be gone

fixes: #32847
fixes: #31638

### CODE REVIEW

File: js/libs/ui-shared/src/utils/useFetch.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ export function useFetch<T>(
   useEffect(() => {
     const controller = new AbortController();
     const { signal } = controller;
+    showBoundary(undefined);
```
Comment (jonkoops) [inline js/libs/ui-shared/src/utils/useFetch.ts:29]:
```suggestion
    showBoundary();
```

**Review by pedroigor — APPROVED** [review]

**Review by sguilhen — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]
