### PR TITLE
Fixing incorrectly cached role after update/rename

### LINKED ISSUE #37320: Cannot fetch realm role that was renamed
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When updating the name of a realm role using admin REST API, the server responds with 404 when requested to fetch recently renamed role.

### Version

26.1.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The newly created role should be renamed and fetched when requested.

### Actual behavior

While the role is created and renamed as expected, it cannot be fetched after being renamed. Surprisingly, if you skip step 2 (as described in `How to Reproduce?` section), everything works as expected.

### How to Reproduce?

Steps to reproduce:
0) Get token
```
curl --location '{keycloakUrl}/realms/{realm}/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id={clientId}' \
--data-urlencode 'client_secret={clientSecret}' \
--data-urlencode 'grant_type=client_credentials'
```
1) Create role realm
```
curl --location '{keycloakUrl}/admin/realms/{realm}/roles' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
    "name": {originalName}
}'
```
2) Fetch role with the new name - check for unique name (before updating role)
```
curl --location '{keycloakUrl}/admin/realms/{realm}/roles/{newName}' \
--header 'Authorization: ••••••'
```
3) Update/rename role
```
curl --location --request PUT '{keycloakUrl}/admin/realms/{realm}/roles/{originalName}' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
    "name": {newName}
}'
```
4) Fetch role with new name
```
curl --location '{keycloakUrl}/admin/realms/{realm}/roles/{newName}' \
--header 'Authorization: ••••••'
```

### Anything else?

While everything else works as expected in keycloak UI, when you click the tab `Users in role` that is available on relevant realm role details page, the application crashes and the following attached error message is displayed

Image

### PR DESCRIPTION
**Pull request by GMalliaris**
Closes #37320

### CODE REVIEW

**Comment by ahus1** [comment]
@GMalliaris - thank you for the PR. I updated the code slightly to avoid a situation where a the delegate is first fetched, and then a new name is set when the delegate was already fetched. The new code should work in both cases.

**Comment by ahus1** [comment]
@pruivo - can you please review this PR as you already reviewed the PR that introduced this regression: https://github.com/keycloak/keycloak/pull/36930? 

@mhajas - can you please merge this PR once it is reviewed, so I can prepare a backport?

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RoleAdapter.java [hunk 1]
```diff
@@ -61,6 +61,15 @@ protected void getDelegateForUpdate() {
         }
     }
 
+    protected void getDelegateForRename(String newName) {
+        if (!Objects.equals(newName, cached.getName())) {
+            // New role name might have been cached as non-existent
+            String containerId = getContainerId();
+            cacheSession.registerRoleInvalidation(cached.getId(), newName, containerId);
+        }
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RoleAdapter.java:69]: AFAIK, `newName` is always different. 

https://github.com/keycloak/keycloak/blob/7cff8572387e6bbfca160aa60e9a8191d22e5c85/services/src/main/java/org/keycloak/services/resources/admin/RoleResource.java#L65-L66

I suggest removing the if block. 
```suggestion
        cacheSession.registerRoleInvalidation(cached.getId(), newName, getContainerId());
```

Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RoleAdapter.java:69]: OK, it is your call. No objection from me.

**Review by pruivo — APPROVED** [review]

**Review by mhajas — APPROVED** [review]
Thanks for the fix @GMalliaris and reviews @ahus1 and @pruivo! LGTM
