### PR TITLE
Define a max expiration window for Signed JWT client authentication

### LINKED ISSUE #38576: Define a max expiration window for Signed JWT client authentication
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Currently when the clients are configured to authenticate using a JWT token (**Signed JWT**  or **Signed JWT with Client Secret**) the token can only be used once (it is not reusable) but in all the valid period defined in the token itself (`iat`, `nbf` and `exp` claims are used to detect the token is valid).  The client can use a very long period of expiration (for example hours or even days) and this can be problematic for keycloak because it's outside the server control. For example someone can generate a token stealthily and the token is valid for a very long time. Besides long expiration periods also stress keycloak in the single use cache (the token should be stored there for a very long time).

Better enforce a small expiration for tokens. This way although the token can have any expiration defined inside it, keycloak will only allow the authentication if the token is sent just after being issued (a little window of 1 minute, for example). After that time the token will be rejected.

### Version

26.1.4

### Regression

- [ ] The issue is a regression

### Expected behavior

JWT tokens for client authentication will only be allowed to be used in a small window after being issued.

### Actual behavior

The expiration inside the token is trusted.

### How to Reproduce?

See description.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #38576

The PR adds a maximum expiration for JWT client authentication. This means that the JWT tokens are only valid for a short period of time (60s by default). The only problem that I see is if someone are using tokens with `exp` but no `iat` because in that case probably the token will be discarded (it is just valid if the token is in that 60s window before expiring). The expiration can be modified in the client configuration using a new property. Tests added.

Setting the notes for new version 26.2, I the version is released before this is merged I will just move to 26.2.1.

### CODE REVIEW

File: services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java [hunk 1]
```diff
@@ -192,12 +194,50 @@ public void validateToken() {
...
     }
 
+    private long calculateLifespanInSeconds()  {
+        if ((token.getExp() == null || token.getExp() <= 0) && (token.getIat() == null || token.getIat() <= 0)) {
+            throw new RuntimeException("Token cannot be validated. Neither the exp nor the iat claim are present.");
+        }
+
+        if (token.getExp() == null || token.getExp() <= 0) {
+            // exp not present but iat present, just allow a short period of time from iat (10s)
+            // The JWT MUST contain an "exp" by spec??? https://datatracker.ietf.org/doc/html/draft-jones-oauth-jwt-bearer-03#section-3
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java:204]: The spec says that `exp` is compulsory, but null is allowed as it was accepted before.

**Review by jonkoops — DISMISSED** [review]

**Comment by rmartinc** [comment]
I modified the comment to link the correct RFC. It seems that both `iat` and `exp` claims are required in [rfc9068](https://datatracker.ietf.org/doc/html/rfc9068#section-2.2).

File: services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java (hunk 1 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java]: In the last RFC both `iat` and `exp` are marked as required. So I have changed this comment and linked the last RFC.

File: services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java [hunk 2]
```diff
@@ -192,12 +194,50 @@ public void validateToken() {
         }
     }
 
+    private long calculateLifespanInSeconds()  {
+        if ((token.getExp() == null || token.getExp() <= 0) && (token.getIat() == null || token.getIat() <= 0)) {
+            throw new RuntimeException("Token cannot be validated. Neither the exp nor the iat claim are present.");
+        }
+
+        // rfc-9068 marks exp and iat claims are required: https://datatracker.ietf.org/doc/html/rfc9068#section-2.2
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java:202]: This comment is a little bit confusing IMO as it references RFC9068. But RFC9068 is related to "JWT access tokens", but the JWT used for client authentication may not necessarily be an "access token" per my understanding and hence it should rather rely on the other specs https://datatracker.ietf.org/doc/html/rfc7523#section-3 , which mentions `iat` as optional. WDYT?

The code actually allows `iat` as optional and you even have test for it. So the behaviour of this PR is OK IMO . Just this single comment may need some update, but this is not a blocker for this PR IMO.

**Review by mposolda — DISMISSED** [review]
@rmartinc Approving this PR, Thanks! I've adde only single comment inline, but it is not a blocker for the PR.

File: services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java (hunk 2 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java:202]: @mposolda That section says:

> In order to issue an access token response as described in OAuth 2.0
   RFC6749 or to rely on a JWT for client authentication, the
   authorization server MUST validate the JWT according to the criteria
   below.

So the part that says `or to rely on a JWT for client authentication` applies here... Or am I missing something?

Comment (rmartinc) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java:202]: Ah! I copied the other RFC, right I understand, doing the change now.

Comment (rmartinc) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java]: Done!

**Review by mposolda — APPROVED** [review]

File: services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java (hunk 2 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java]: @rmartinc Thanks! I hope to merge the PR once tests are OK

**Review by jonkoops — APPROVED** [review]
