### PR TITLE
fix: adds more validation of proxy-headers

### LINKED ISSUE #38091: Add more validation for proxy-headers
### Description

Add more validation for proxy-headers

### Discussion

_No response_

### Motivation

Users are quite often creating discussions and issues around things like 403 responses from CORS checks (see [#37132](https://github.com/keycloak/keycloak/issues/37132)) or non-secure context warnings that are typically resolved by setting the proxy-headers setting.

We should make it as clear as possible in the docs, and the code, when they should be set.

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
cc @vmuzikar @mabartos this is a rough in of code changes to add more validation around proxy-headers. Without re-introducing something like the proxy setting, we cannot directly infer the user's intention in several cases.

In particular we still don't have a good handle on what some users were doing using Keycloak over http but not through a proxy, so the message just says something vague about reviewing the usage: "Please review whether this direct http usage of keycloak is expected." @vmuzikar I believe you mentioned something about this case being problematic with Docker usage - keycloak ends up not actually being accessed over localhost, so it's not a secure context.

It would also make more sense to put this validation (and that of the legacy property usage) in the v2 provider, but that would require broader access to the whole configuration. If we want to pursue that we could either consider adding something like Config.Scope.getDescoped(String key)  - which breaks the config encapsulation a little bit, or we'll have to map everything of interest to an spi property.

The other place where users are commonly getting tripped up is here 
https://github.com/keycloak/keycloak/blob/edd67c6ca4af1bac5c1cc883720f580c0db4c917/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java#L88 - I previously updated the debug log to reference proxy-headers, but it could be expanded upon and/or logged at a higher level.

I haven't done it yet, but some additional doc changes will be added as well.

WDYT?

closes: #38091

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 1]
```diff
@@ -35,13 +40,50 @@ public static PropertyMapper<?>[] getHostnamePropertyMappers() {
...
+            }
+            String path = url.getPath();
+            String configuredPath = Configuration.getConfigValue(HttpOptions.HTTP_RELATIVE_PATH).getValue();
+            // TODO: normalize paths
+            if (!Objects.equals(path, configuredPath)) {
+                // WARNING
+                // cors check won't work as expected
+            }
+        } catch (MalformedURLException e) {
+        }
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:86]: IMHO it is fine-ish to keep this validation here (instead of having it in the provider). The providers are encapsulated, they should not have access to config in general, only to their narrow scope.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 2]
```diff
@@ -35,13 +40,50 @@ public static PropertyMapper<?>[] getHostnamePropertyMappers() {
...
+                // cors check, nor secure context detection will work as expected
+            }
+            String port = String.valueOf(url.getPort() == -1 ? 80 : url.getPort());
+            String configuredPort = Configuration.getConfigValue(HttpOptions.HTTP_PORT).getValue();
+            if (!port.equals(configuredPort)) {
+                // WARNING
+                // cors check won't work as expected
+            }
+            String path = url.getPath();
+            String configuredPath = Configuration.getConfigValue(HttpOptions.HTTP_RELATIVE_PATH).getValue();
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:79]: I'm not sure if we can do this check. To be more precise, AFAIK the cases when this would be useful are limited. It would only work if someone explicitly set `http-relative-path` to something else than the default `/`.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 3]
```diff
@@ -35,13 +40,50 @@ public static PropertyMapper<?>[] getHostnamePropertyMappers() {
...
+            return;
+        }
+        if (HttpPropertyMappers.isHttpsEnabled()) {
+            // must be tls passthrough, but there's no way of knowing the intention
+            return;
+        }
+        // if https is not enabled, and any part of the host does not match the rest of the system, then there's likely a problem
+        try {
+            URL url = new URL(host);
+            if ("https".equalsIgnoreCase(url.getProtocol())) {
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:68]: What if someone is using edge TLS termination but doesn't use proxy headers, and sets hardcoded hostname incl. the protocol (`https://`)? This would trigger the warn/error, which I believe it should not.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 4]
```diff
@@ -35,13 +40,50 @@ public static PropertyMapper<?>[] getHostnamePropertyMappers() {
...
+                // WARNING, or even ERROR
+                // cors check, nor secure context detection will work as expected
+            }
+            String port = String.valueOf(url.getPort() == -1 ? 80 : url.getPort());
+            String configuredPort = Configuration.getConfigValue(HttpOptions.HTTP_PORT).getValue();
+            if (!port.equals(configuredPort)) {
+                // WARNING
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:75]: When this case could happen? We know proxy headers are not used. So the port needs to be the real port the server listens on.

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thanks for the PR. Added some comments/questions.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java (hunk 3 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:68]: > This would trigger the warn/error, which I believe it should not.

It absolutely should - that's the main thrust of this issue. We are consistently getting discusssions / issues precisely because people are not setting the proxy-headers in this case. I guess the alternative would be to have secure context detection consider the server's configured host, instead of just what is coming from the request.

Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:68]: Could you elaborate why it should trigger error when the `hostname` is specified as a full URL? In that case we don't need proxy headers.

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java]: Oh right, sorry I wasn't thinking clearly - simplified this to just a specific case.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java]: Removed.

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thanks for the update.

Just to summarize offline discussion we had. The validation should fail if (pseudo code):
```
!tlsConfigured && proxyHeaders == null && (!hostname.startsWith("https://") || hostname.isLocalContext())
```
The validation should be just a warning not to be breaking change (for some folks even the misconfigured scenario might sort of work).

We should also document that Admin Console loads only in secure context, incl. what secure context mean (TLS from the browser's perspective, or localhost).

**Comment by shawkins** [comment]
I'll circle back to this after https://github.com/keycloak/keycloak/pull/38536 is merged because it touches the same logic.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:1]: A generic note. In addition to cross-site cookies, should we also mention the Secure Context is required for the JS Adapter? Maybe we could word in more broadly, something like "Certain Keycloak features might not work properly due to Secure Context violation.".

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 5]
```diff
@@ -41,6 +46,50 @@ public static void validateConfig(Picocli picocli) {
...
+        if (proxyHeaders != null) {
+            // must not be tls passthrough, but there's no way of knowing the intention
+            return;
+        }
+        if (isProd) {
+            if (host == null) {
+                picocli.warn("With HTTPS not enabled and hostname-strict=false, cross-origin cookies will not be allowed.");
+            } else if (!SecureContextResolver.isLocal(host)) {
+                picocli.warn("HTTPS is not enabled on the server, either the `hostname` should be set to a full URL or `proxy-headers` should be used. This is likely a misconfiguration.");
+            } // else warn on prod
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:69]: Why `// else warn on prod`? The warning si already there, no?

**Review by vmuzikar — CHANGES_REQUESTED** [review]
In general looks good.

Could you please also update the docs to incorporate some notes around these new validations?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java (hunk 5 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:69]: The else case here is something like hostname=http://localhost - doesn't seem like that would be used in production, but I wasn't sure if it warrented a warning.

**Comment by shawkins** [comment]
> In general looks good.
> 
> Could you please also update the docs to incorporate some notes around these new validations?

Yes, once we have a handle on all the cases / verbiage, I'll update the docs.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:1]: Ok, I'll also mention CORS specifically where applicable.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 6]
```diff
@@ -2,17 +2,23 @@
...
 import org.keycloak.config.HostnameV2Options;
+import org.keycloak.quarkus.runtime.Environment;
 import org.keycloak.quarkus.runtime.cli.Picocli;
+import org.keycloak.config.ProxyOptions;
 import org.keycloak.quarkus.runtime.configuration.Configuration;
+import org.keycloak.utils.SecureContextResolver;
 
 public final class HostnameV2PropertyMappers {
 
+    private static final String CONTEXT_WARNING = "the server running in an insecure context. Secure contexts are required for full functionality, including cross-origin cookies.";
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:21]:
```suggestion
    private static final String CONTEXT_WARNING = "the server is running in an insecure context. Secure contexts are required for full functionality, including cross-origin cookies.";
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 7]
```diff
@@ -41,6 +47,51 @@ public static void validateConfig(Picocli picocli) {
...
+        }
+    }
+
+    static boolean validateFullHostname(boolean httpsEnabled, boolean isProd, String host, Picocli picocli) {
+        try {
+            URL url = new URL(host);
+
+            if (!url.getProtocol().toUpperCase().equals("HTTPS") && isProd) {
+                if (!SecureContextResolver.isLocal(url.getHost())) {
+                    picocli.warn("Likely misconfiguration detected. `hostname` is configured to use HTTP instead of HTTPS " + CONTEXT_WARNING);
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:81]:
```suggestion
                    picocli.warn("Likely misconfiguration detected. `hostname` is configured to use HTTP instead of HTTPS, " + CONTEXT_WARNING);
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java [hunk 8]
```diff
@@ -41,6 +47,51 @@ public static void validateConfig(Picocli picocli) {
...
+            // must be tls passthrough, but there's no way of knowing the intention
+            return;
+        }
+        String proxyHeaders = Configuration.getConfigValue(ProxyOptions.PROXY_HEADERS).getValue();
+        if (proxyHeaders != null) {
+            // must not be tls passthrough, but there's no way of knowing the intention
+            return;
+        }
+        if (isProd) {
+            String warning = CONTEXT_WARNING + " Also if you are using a proxy, requests from the proxy to the server will fail CORS checks with 403s because the wrong origin will be determined.";
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java:66]:
```suggestion
            String warning = CONTEXT_WARNING + " Also if you are using a proxy, requests from the proxy to the server will fail CORS checks with 403s because the wrong origin will be determined. Make sure `proxy-headers` are configured properly.";
```

**Review by vmuzikar — COMMENTED** [review]
IMHO it is good enough for now, it's a good start and we'll see if that helps the users.

Added some minor comments, mostly typos.

I think we can update the docs and we're ready for merge. It'd be good to get it to 26.2.

**Comment by shawkins** [comment]
Finally circling back to this. It now incorporates the config warnings into the hostname-debug output along with a more precise test of misconfiguration of the frontend URL.

There are two ways that could be done - either do it under the main hostname-debug endpoint logic, or the endpoint test logic. I opted for the latter. 

The only thing I'd like to additionally check for is if tls passthrough is being used and proxy headers have been set - but this will take a bit more logic to determine. Does it seem worth it?

cc @vmuzikar

**Comment by shawkins** [comment]
@vmuzikar reviewed again for consistency across the docs, startup warnings, and hostname-debug page. The only thing that needed adjusted was recommending that someone use a full url hostname when behind a proxy as a remedy for failing CORs checks. As far as I can tell, this does not work. 

In LoginStatusIframeEndpoint logic https://github.com/keycloak/keycloak/blob/f58a998426b3d3bfea5c4a5af72943e0c2d2aa79/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java#L83 and in the previous admin redirect check https://github.com/keycloak/keycloak/pull/39095/files#diff-3b717e96493408412377f67ab2a8acac4a1c84b6746a3d7b61b56512fcf44d0aL97 the usage of session.getContext().getUri().getRequestUri() when there are no proxy headers set returns the actual details of the actual request sent from the proxy server to keycloak. It is unaffected by a full hostname url.

So the only time you can get away with setting the full hostname url, but not the proxy-headers, is when you are not behind a proxy.

**Comment by shawkins** [comment]
> Yes, as discussed offline, let's update the PR to reflect that.

Should already be up-to-date. This proxy related warning no longer mentions a full hostname url - https://github.com/keycloak/keycloak/pull/38092/files#diff-7c377d926388e6270afeeb19a6c85191ac26a0b4916bd4ed37ddaffa1f05446fR70

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java [hunk 9]
```diff
@@ -117,10 +130,45 @@ public String debug(final @PathParam("realmName") String realmName) throws IOExc
...
+        String text = "OK";
+        String corsOrigin = keycloakSession.getContext().getRequestHeaders().getHeaderString(Cors.ORIGIN_HEADER);
+        URI requestUri = keycloakSession.getContext().getUri().getRequestUri();
+        String requestOrigin = UriUtils.getOrigin(requestUri);
+        URI frontendUri = keycloakSession.getContext().getUri(UrlType.FRONTEND).getBaseUri();
+
+        if (frontEnd) {
+            boolean originMatches = requestOrigin.equals(UriUtils.getOrigin(frontendUri));
+            HttpHeaders requestHeaders = keycloakSession.getContext().getRequestHeaders();
+            boolean proxied = requestHeaders.getHeaderString("Forwarded") != null || requestHeaders.getHeaderString("X-Forwarded-For") != null;
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:143]: Should we check for other `X-Forwarded-*` headers too, or at least change it to `X-Forwarded-Host` as it's most relevant for this case?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java [hunk 10]
```diff
@@ -117,10 +130,45 @@ public String debug(final @PathParam("realmName") String realmName) throws IOExc
...
+
+            if (!originMatches) { // might fail CORs checks
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:145]:
```suggestion
            if (!originMatches) { // might fail CORS checks
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java [hunk 11]
```diff
@@ -117,10 +130,45 @@ public String debug(final @PathParam("realmName") String realmName) throws IOExc
...
+                try {
+                    new URL(Configuration.getKcConfigValue(HostnameV2Options.HOSTNAME.getKey()).getValue());
+                    // a full url is ok
+                } catch (MalformedURLException e) {
+                    text = "Default origin check failing. Please check you proxy settings.";
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:150]: I'd be maybe more explicit.
```suggestion
                    text = "Default origin check failing, request hostname does not match frontend hostname. Please check you proxy settings.";
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java [hunk 12]
```diff
@@ -117,10 +130,45 @@ public String debug(final @PathParam("realmName") String realmName) throws IOExc
...
+            }
+
+            boolean https = requestUri.getScheme().equals("https");
+            if (https) {
+                // if reencrypt, then proxy headers may need set
+                // if passthrough, then proxy headers should not be set
+
+                // TODO: not sure if there is great way to do this. Would likely need to check that a connection to the frontend uses the same
+                // cert as what is coming in on this request
+            }
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:167]: This would rather be a security config issue, no? It's not really a hostname issue. Perhaps it doesn't belong to the hostname debug tool? It's a generic misconfig issue.

**Review by vmuzikar — COMMENTED** [review]
> Should already be up-to-date.

Right, I missed it, thanks.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java (hunk 12 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:167]: > This would rather be a security config issue, no? 

Yes, but it relates to proxy-headers, so ideally it could be checked here as well.

**Comment by shawkins** [comment]
> Alternative would be to revisit the code base to make it uses the Hostname provider (with explicit URL type) instead of raw requests but it might not be possible everywhere, and we'd risk regressions.

It could be the issue here is some inconsistency or missing guidance over the HOST header. The full hostname URL could work without proxy-headers when using re-encrypt - as long as the proxy sets the HOST header to be what was used to access the proxy. This does not appear to be the default behavior for nginx, as it will set the host to what is used to access the backend. I don't think this won't work in edge mode because the scheme is not part of the HOST header.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java (hunk 9 above)
Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java]: > do you want to consolidate those and switch to X-Forwarded-Host instead?

That'd probably make sense.

Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java]: But it's not a blocker, approving regardless, feel free to merge.

**Comment by vmuzikar** [comment]
Actually, there seems to be something wrong with the commits. Can you please check it?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java (hunk 9 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java]: Refined to use the headers we have defined in the constants.

**Comment by shawkins** [comment]
> Actually, there seems to be something wrong with the commits. Can you please check it?

Should be better now. Added one more validation about setting proxy-headers in edge mode.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java [hunk 13]
```diff
@@ -117,10 +130,44 @@ public String debug(final @PathParam("realmName") String realmName) throws IOExc
...
     @Path("/{realmName}/" + DEFAULT_PATH_SUFFIX + "/" + PATH_FOR_TEST_CORS_IN_HEADERS)
     @Produces(MediaType.TEXT_PLAIN)
-    public Response test(final @PathParam("realmName") String realmName) {
-        Response.ResponseBuilder builder = Response.ok(PATH_FOR_TEST_CORS_IN_HEADERS + "-OK");
-        String origin = keycloakSession.getContext().getRequestHeaders().getHeaderString(Cors.ORIGIN_HEADER);
-        builder.header(Cors.ACCESS_CONTROL_ALLOW_ORIGIN, origin);
+    public Response test(final @PathParam("realmName") String realmName, @DefaultValue("false") @QueryParam("frontEnd") boolean frontEnd) {
+        String text = "OK";
+        String corsOrigin = keycloakSession.getContext().getRequestHeaders().getHeaderString(Cors.ORIGIN_HEADER);
+        URI requestUri = keycloakSession.getContext().getUri().getRequestUri();
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:136]: I did some testing and this actually does get us the "raw" request but one enriched by the Hostname provider, see:
https://github.com/keycloak/keycloak/blob/8d9439913cffe5aef10ac14eb2876daca3336e5e/server-spi/src/main/java/org/keycloak/models/KeycloakUriInfo.java#L52

@shawkins Could you please check it?

**Review by vmuzikar — CHANGES_REQUESTED** [review]

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java (hunk 13 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:136]: I have. You only get the enrichment if you call getBaseUri. If you call getRequestUri, you get the underlying request: https://github.com/keycloak/keycloak/blob/8d9439913cffe5aef10ac14eb2876daca3336e5e/server-spi/src/main/java/org/keycloak/models/KeycloakUriInfo.java#L72

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:136]: If you have hostname=example.com the urls tested by hostname-debug will be to example.com, not localhost.

Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:136]: > If you have hostname=example.com the urls tested by hostname-debug will be to example.com, not localhost.

Right, sorry, I was stupid and also forgot I have `example.com` in my `/etc/hosts`. :D

LGTM, thanks. Let's get this merged finally.

**Review by vmuzikar — APPROVED** [review]

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java (hunk 13 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:136]: Just to double check - do you think we need to review our usage of getRequestUri and the other methods on KeycloakUriInfo that expose the underlying delegate? I see several code paths using that, which makes using the full hostname url without proxy-headers problematic - or are we good with just requiring the proxy-headers to be be set?

Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java:136]: > or are we good with just requiring the proxy-headers to be be set

IMHO we're good for now - we say in docs proxy headers are required anyway for edge and reencrypt. If we did a refactor of `getRequestUri`, I would do that in a separate PR. But I wouldn't do that for now not to risk regressions.
