### PR TITLE
Fixes #9482: A user could be assigned to a parent group if he is already assigned to a subgroup.

### LINKED ISSUE #9482: Can't add user to "parent group" if member of a subgroup
### Describe the bug

Trying to add a user to a parent group when the user already is a member of a subgroup don't work. No errors, just not added to the group.

### Version

16.1.0

### Expected behavior

User gets added to the group or a error is thrown.

### Actual behavior

User is not added to the group and no visible errors.

### How to Reproduce?

1. Create a new group.
2. Create a group under the newly created group.
3. Add a user to the subgroup created in step 2.
4. Try to add the user to the parent group created in step 1.

You will get `Success! Added group membership`, but the user is not added to the group. The same is true from the API.

The reverse order (add to the root group first) works as excepted.

### Anything else?

If this is working as expected the API should return a error, and doing it in reverse should not work.

image

### PR DESCRIPTION
**Pull request by leischt**
Closes #9482 
Changed precondition for joining a group from is not a member to has group not directly assigned.

### CODE REVIEW

**Comment by ahus1** [comment]
Thanks for contributing to this project with this pull request!

Please add `Closes #9482` to the description of this pull request. 

This will help collaboration on GitHub in two ways:

1. It populates the right-hand column on both the issue and the PR with a reference to the issue you're about to fix.
2. It will close the issue once the PR has been merged automatically.

Thanks!

**Comment by sschu** [comment]
@mposolda @hmlnarik Could any of you please have a look? Would be great to have this in KC19.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thank you for the test.
Sadly, the fix is not valid. The `isMemberOf` accounts for recursive walk of group hierarchy. This is not the case with the code proposed in this PR which only checks the direct assignment of a user to groups.

**Comment by hmlnarik** [comment]
@leischt @sschu Please refer to the original issue #9482 for further discussion

**Comment by sschu** [comment]
@hmlnarik In the light of https://github.com/keycloak/keycloak/discussions/12726#discussioncomment-3221122, do you think this could be merged? Also tests need to be rerun I guess...

File: model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java [hunk 1]
```diff
@@ -392,7 +392,7 @@ public long getGroupsCountByNameContaining(String search) {
 
     @Override
     public void joinGroup(GroupModel group) {
-        if (isMemberOf(group)) return;
+        if (getGroupsStream().anyMatch(g -> group.getId().equals(g.getId()))) return;
```
Comment (hmlnarik) [inline model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java:395]: This change should also be propagated to https://github.com/keycloak/keycloak/blob/fd5a423b551b9836bda44d47b38d7cd34f8d27c4/model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java#L266-L269

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java [hunk 2]
```diff
@@ -2958,4 +2972,69 @@ public void testCreateUserDoNotGrantRole() {
...
+        String parentGroupName = "parent-group";
+        String subGroupName = "sub-group";
+
+        GroupRepresentation parentGroup = createGroup(realm, GroupBuilder.create().name(parentGroupName).build());
+        GroupRepresentation subGroup = createSubGroup(realm, parentGroup.getId(), GroupBuilder.create().name(subGroupName).build());
+
+        UserRepresentation build = UserBuilder.create()
+                .username(username)
+                .build();
+        String userId = createUser(build);
```
Comment (hmlnarik) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java:2991]: Could you leverage `Creator.create(RealmResource, GroupRepresentation)` and `Creator.create(RealmResource, UserRepresentation)` instead in both tests to clean after the test completes?

Example:
https://github.com/keycloak/keycloak/blob/fd5a423b551b9836bda44d47b38d7cd34f8d27c4/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java#L2883-L2894

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thank you for the PR. Could you please rebase, it has conflicts, and also please see inline

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java (hunk 2 above)
Comment (sschu) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java]: @hmlnarik Since @leischt is on leave, I will step in. I adapted the tests as you requested.

File: model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java (hunk 1 above)
Comment (sschu) [reply model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java]: Actually, this one is a bit tricky. In `UserAdapter.java` this method was not adapted, it is still checking for transitive group membership. It is only not used anymore when joining a group. However, in `MapUserAdapter.java`I can see there is actually no check at all when joining a group: https://github.com/keycloak/keycloak/blob/52488150917c5c7dd68e7eef7eab7c66275f0e49/model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java#L257

I am not sure this is really intended.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java (hunk 2 above)
Comment (hmlnarik) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java]: Thank you.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java [hunk 3]
```diff
@@ -3003,6 +3003,20 @@ private GroupRepresentation createGroup(RealmResource realm, GroupRepresentation
...
+        }
+
+        assertAdminEvents.assertEvent(realmId, OperationType.CREATE, AdminEventPaths.groupSubgroupsPath(parentGroupId), group, ResourceType.GROUP);
+
+        // Set ID to the original rep
+        group.setId(groupId);
+        return group;
+    }
+
     @Test
```
Comment (hmlnarik) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java:3020]: This is not used anymore, could you please remove this method?

File: model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java (hunk 1 above)
Comment (hmlnarik) [reply model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java]: My bad, apologies. I marked wrong lines in the `MapUserAdapter` and you have correctly spotted that.
I meant propagating it to the `MapUserAdapter.joinGroup()` method that you have referenced.

File: services/src/main/java/org/keycloak/services/resources/admin/UserResource.java [hunk 4]
```diff
@@ -933,7 +933,7 @@ public void joinGroup(@PathParam("groupId") String groupId) {
             throw new NotFoundException("Group not found");
         }
         auth.groups().requireManageMembership(group);
-        if (!user.isMemberOf(group)){
+        if (user.getGroupsStream().noneMatch(g -> group.getId().equals(g.getId()))){
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/services/resources/admin/UserResource.java:936]: Could you please for the sake of readability leverage the newly introduced `RoleUtils.isDirectMember` method here as well?

**Review by hmlnarik — COMMENTED** [review]
Thank you for the changes, looks better now. Could you please see the comments inline?

Nit: For the sake of better readability, leveraging the newly introduced method `RoleUtils.isDirectMember` in the changed lines which currently use `getGroupsStream().{none,any}Match` would be preferred.

File: services/src/main/java/org/keycloak/services/resources/admin/UserResource.java (hunk 4 above)
Comment (sschu) [reply services/src/main/java/org/keycloak/services/resources/admin/UserResource.java]: Done.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java (hunk 3 above)
Comment (sschu) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java]: Done.

File: model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java (hunk 1 above)
Comment (sschu) [reply model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java]: I added the check to `MapUserAdapter.java`.

**Review by hmlnarik — APPROVED** [review]
Thank you for the PR!
