### PR TITLE
TestLdapConnectionResource: give usefull feedback in UI on what faile…

### LINKED ISSUE #15434: Customize log messages for user storage LDAP configuration in KC shown in admin UI
### Description

Hi team,

I have setup of LDAP active directory configured with KC and as a end user perspective, I want to make sure whenever this configuration is wrongly configured, I get clear and specific message in admin console UI to help in troubleshooting.

What is currently happening is that Keycloak is throwing generic error messages in UI although application (deployed as docker container) itself shows some logs which are helpful but those are all in backend and doesn't helps end-users who are exposed only to admin UI.

Is it possible somehow to modify those log messages in the UI and get specific messages as per the exact mis-configuration ?

Note: Even the API response is generic message "unknown_error", "LDAP test error" etc... not indicating the exact issue.

I will attach one such scenario for better understanding here.
Ex. below, It would be nice for the end user if it shows the unknown host/wrong host configured issue instead of showing generic messages.

[keycloak LDAP configuration]
paint

[keycloak container logs]
keycloak-backend

[keycloak UI]
keycloak-admin

### Discussion

https://github.com/keycloak/keycloak/discussions/15416

### Motivation

It helps to the end user while troubleshooting the exact issue while doing configuration who are only exposed to keycloak admin UI and doesn't have access to server logs.

### Details

_No response_

### PR DESCRIPTION
**Pull request by dinutine**
…d in LDAP connection/authentication/sync users

Currently, for all errors, a meaningless message "LDAP test error" or "unknown_error" is returned by the API.
To give some usefull feedback to the user, by creating an error message based on the exception being thrown

Closes: #15434

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
Can't say anything about the Java code, but the changes on the font-end look good to me.

File: services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java [hunk 1]
```diff
@@ -117,12 +123,53 @@ private static int getStatusCode(Throwable throwable) {
...
     }
 
-    private static String getErrorCode(Throwable throwable) {
+    public static String getErrorCode(Throwable throwable) {
         if (throwable instanceof WebApplicationException && throwable.getMessage() != null) {
             return throwable.getMessage();
         }
 
-        return "unknown_error";
+        String errorMsg = "UnknownError";
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java:131]: This change needs reverting. The `unknown_error` is a constant which must not be changed.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thank you for the PR. It is a useful PR but the Java code needs polishing.

Due to a change in `KeycloakErrorHandler`, it can now leak internals of server-side information even to unauthorized users, as this handler can be used for all requests. For example, instead of `unknown_error`, in the login screen it could happen that `CommunicationError` would be displayed which can be seen as CWE-1230 (Exposure of Sensitive Information Through Metadata). The lack of verbosity there is intentional.

Translating the exception to error should thus be done in the testing endpoint which is only available in the admin UI.

File: model/legacy-services/src/main/java/org/keycloak/services/resources/admin/UserStorageProviderResource.java [hunk 2]
```diff
@@ -74,6 +77,20 @@ public UserStorageProviderResource(KeycloakSession session, AdminPermissionEvalu
...
+    public static String getErrorCode(Throwable throwable) {
+        if (throwable instanceof org.keycloak.models.ModelException) {
+           if (throwable.getCause() != null) {
+                throwable = throwable.getCause();
+                if (throwable instanceof org.keycloak.models.ModelException) {
+                   if (throwable.getCause() != null) {
+                        throwable = throwable.getCause();
+                    }
+                }
+            }
```
Comment (hmlnarik) [inline model/legacy-services/src/main/java/org/keycloak/services/resources/admin/UserStorageProviderResource.java:89]:
```suggestion
                return getErrorCode(throwable.getCause());
```

**Review by hmlnarik — COMMENTED** [review]
LGTM, just one minor nit and the Java part is good to go.

**Review by hmlnarik — DISMISSED** [review]

**Comment by hmlnarik** [comment]
The java code LGTM, thank you!
There are test failures in the Admin UI test, could you please check?

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
@hmlnarik if everything looks good, can you re-approve the PR? I think we can get this merged in.

**Review by hmlnarik — APPROVED** [review]
