### PR TITLE
Show details for error messages where they were missing

### LINKED ISSUE #32533: Admin UI messages sometimes miss details, and sometimes refer to details in the logs which are missing
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

There are sometimes error messages without details, and sometimes they refer to the logs for details which are unaccessible to a pure web-UI user.

 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

All details should be provided in the UI

### Actual behavior

Details are missing, and a not-helpful message pointing to the logs:

When managing a user's groups:
image

When changing events:
image

When changing passwords:
image

### How to Reproduce?

Various situations: 

* Try to join a group which has been deleted in a second window
* Try to send out an email with a credential reset
* Trying to set a password which is just a space character

### Anything else?

This has partly been resolved in #30710.

I'll provide a PR to do some fixes

### PR DESCRIPTION
**Pull request by ahus1**
Closes #32533

Possible follow-ups: 
* FlowTest#testRemoveUsedFlow - catch all ModelExceptions and wrap them as client exceptions. Cleanup existing code.

### CODE REVIEW

File: js/apps/admin-ui/src/client-scopes/ClientScopesSection.tsx [hunk 1]
```diff
@@ -180,7 +180,7 @@ export default function ClientScopesSection() {
           addError("deleteErrorClientScope", error);
         }
       } else {
-        addError(t("notAllowedToDeleteAllClientScopes"), "error");
+        addError("notAllowedToDeleteAllClientScopes", "error");
```
Comment (jonkoops) [inline js/apps/admin-ui/src/client-scopes/ClientScopesSection.tsx:183]: This is wrong, there is a value being passed as `error` which is just a string literal that will be omitted as the label does not format an error.

Not sure why this was done, likely to quickly work around the function signature requirements. This should be refactored to a plain call to `addAlert()`, for example:

```ts
addAlert(t("notAllowedToDeleteAllClientScopes"), AlertVariant.danger);
```

File: js/apps/admin-ui/src/realm-settings/NewClientPolicy.tsx [hunk 2]
```diff
@@ -262,7 +262,7 @@ export default function NewClientPolicy() {
               toEditClientPolicy({ realm, policyName: formValues.name! }),
             );
           } catch (error) {
-            addError(t("deleteConditionError"), error);
+            addError("deleteConditionError", error);
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/NewClientPolicy.tsx:265]: It seems that this label is actually missing, I cannot find it in any of the locales.

File: services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java [hunk 3]
```diff
@@ -63,7 +63,11 @@ public DefaultEmailSenderProvider(KeycloakSession session) {
 
     @Override
     public void send(Map<String, String> config, UserModel user, String subject, String textBody, String htmlBody) throws EmailException {
-        send(config, retrieveEmailAddress(user), subject, textBody, htmlBody);
+        String address = retrieveEmailAddress(user);
+        if (address == null) {
+            throw new EmailException("No email address configured for the user", null);
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java:68]: Looks like the second argument could be omitted here?

```suggestion
            throw new EmailException("No email address configured for the user");
```

File: services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java [hunk 4]
```diff
@@ -107,6 +111,10 @@ public void send(Map<String, String> config, String address, String subject, Str
             props.setProperty("mail.smtp.connectiontimeout", "10000");
 
             String from = config.get("from");
+            if (from == null) {
+                throw new EmailException("No sender address configured in the realm settings for emails", null);
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java:115]:
```suggestion
                throw new EmailException("No sender address configured in the realm settings for emails");
```

File: services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java [hunk 5]
```diff
@@ -89,7 +89,9 @@ public static Response getResponse(KeycloakSession session, Throwable throwable)
             OAuth2ErrorRepresentation error = new OAuth2ErrorRepresentation();
 
             error.setError(getErrorCode(throwable));
-            error.setErrorDescription("For more on this error consult the server log at the debug level.");
+            if (statusCode >= 500 && statusCode <= 599) {
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java:92]: Not sure why we ever decided to use the raw status code and not a `Response.Status`, this could be 'simplified' to:

```suggestion
            Response.Status status = Response.Status.fromStatusCode(statusCode);
            
            if (status.getFamily().equals(Response.Status.Family.SERVER_ERROR)) {
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Comment by ahus1** [comment]
@jonkoops - I found that all the error messages put an `{{error}}` in the message template which will show the untranslated text from the backend. All of them put it at the end of the message.

I wonder if we can simplify that: Instead, we can update `addError()` to append the text retrieved via `getErrorMessage(error)`. 

This would prevent missing the {{error}} in the message pattern.

WDYT?

**Comment by ahus1** [comment]
As discussed in chat with @jonkoops, we're keeping the ``{{error}}`` in the messages to allow for a better localization.

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by edewit — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]
