### PR TITLE
Fix NPE on mixed-case email domain in Keycloak Organization

### LINKED ISSUE #46969: Authentication Failure with Mixed-Case Email Domain in Organizations
### Before reporting an issue[/+]
- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.[/+]

### Area

organizations

## Describe The Bug
Users attempting to log in to Keycloak Organizations with an email containing mixed-case domain characters (e.g., `User@MixedCase.com`) intermittently receive an error page. Checking the logs reveals a `NullPointerException` (NPE) in `InfinispanOrganizationProvider.getByDomainName`.

The issue starts working after organizational changes (like deleting and recreating an organization).

## Why?
The root cause is a mismatch between administrative operations and the authentication cache:
1. **Case-Sensitive Cache**: The Infinispan cache uses the raw domain string as a key. A login with `MixedCase.com` creates a cache entry distinct from `mixedcase.com`.
2. When an organization is updated or deleted, Keycloak only invalidates the *lowercase* version of the domain in the cache.
3. **Stale Cache Entry**: If a mixed-case entry exists (`MixedCase.com`), it remains in the cache even if the organization is deleted.
4. When a subsequent login uses the mixed-case domain, Keycloak hits the stale cache entry, finds an organization ID that no longer exists in the DB, and throws an NPE when trying to process that null result.

### Version

26.5.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Logging in with a mixed-case email domain (e.g., `user@Domain.Com`) should work identical to lowercase. 
If an organization is deleted or updated, all related cache entries should be cleared immediately. 
If a cache entry is stale, Keycloak should gracefully fall back to the database instead of crashing.

### Actual behavior

Logging in with a mixed-case domain creates a separate, case-sensitive cache key. 
When an organization is deleted, Keycloak only invalidates the lowercase version of the domain. Subsequent logins using the mixed-case domain hit a stale cache entry, attempt to map a deleted organization ID, and throw a NullPointerException, resulting in an authentication failure page for the user.

### How to Reproduce?

1. Create an organization with domain `test.com`.
2. Log in with `user@Test.Com` (creates a mixed-case cache entry).
3. Delete and recreate the organization (invalidates `test.com`, but leaves `Test.Com` in cache).
4. Attempt to log in again with `user@Test.Com` -> NPE / Auth failure.

### PR DESCRIPTION
**Pull request by Asafima**
This PR addresses the authentication failure caused by case-sensitivity issues in the Organization Infinispan cache.

### Key Changes
- **Cache Key Normalization**: Updated `InfinispanOrganizationProvider` to always lowercase domain names when generating cache keys. This ensures cache entries are consistent with the JPA layer and are correctly invalidated during organization updates.
- **Defensive Null Handling**: Added a null check when resolving organizations from the cache. This prevents `NullPointerException` if a stale or corrupted cache entry points to a non-existent organization ID.
- **Integration Test**: Added a new test case `testStaleCacheEntryDoesNotThrowNPE` in `OrganizationCacheTest.java` that specifically validates the fix by simulating a stale cache scenario.

Closes #46969

### CODE REVIEW

**Review by martin-kanis — CHANGES_REQUESTED** [review]
@Asafima Thanks for the PR. Please avoid any unnecessary changes like formatting changes, breaking lines, etc in the PR.

**Comment by Asafima** [comment]
@martin-kanis 
Done, sorry for the hassle, should have noticed.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java [hunk 1]
```diff
@@ -469,7 +469,7 @@ private Stream<OrganizationModel> getCacheDelegates(Stream<OrganizationModel> ba
     }
 
     private String cacheKeyByDomain(String domainName) {
-        return getRealm().getId() + ".org.domain.name." + domainName;
+        return getRealm().getId() + ".org.domain.name." + (domainName == null ? "null" : domainName.toLowerCase());
```
Comment (pedroigor) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java]: We should not expect a `null` domain name at this point. If so, it should throw an illegal argument exception. Callers should not call this method if the domain is null.

Comment (Asafima) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java]: @pedroigor Fixed.
Just to point out this changes the previous behavior - if `domainName` was passed as `null`, the `cacheKeyByDomain` method would return `{{realmId}}.org.domain.name.null`

**Review by martin-kanis — CHANGES_REQUESTED** [review]
@Asafima Thanks for the update. I checked the test and it is not failing without the fix. Here is my update that reproduces NPE https://github.com/martin-kanis/keycloak/commit/12df4dc3f27e0d0287f16aebf1fae89e687d1caf. Can you incorporate it please? 
Also, please don't you the the fully qualified types in the code but rather import it as I did. 
Other than that it looks good.

Thanks!

**Comment by Asafima** [comment]
@martin-kanis Done.
Incorporated your changes to the test as-is (including the comments with the detailed explanation), hope that's ok.
Please LMK if we need anything else.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java (hunk 1 above)
Comment (pedroigor) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java]: Thanks, @Asafima.

**Comment by martin-kanis** [comment]
@Asafima Thanks for the changes. The new tests revealed incorrect cleanup for some existing tests, so we got some failures. Can you also add https://github.com/martin-kanis/keycloak/commit/0013e5d0eac4ba4493f7fb16524be2194f75a342 so the CI is green? Then the PR should be ready for merge. Thank you!

**Comment by Asafima** [comment]
Thanks @martin-kanis! Incorporated your commit changes.

**Review by martin-kanis — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
Thanks, @Asafima !
