### PR TITLE
Account console backend should redirect to login on missing auth

### LINKED ISSUE #31469: Show account page before login
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

I intend to describe the bug very briefly and precisely. I am using version 25.0.2. When I try to access the account page, the account page, including menus and header, is displayed for a few moments and then the login page is shown.

This is not very pleasant! Thank you.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Well, it's natural that the login page should be shown to the user immediately and quickly.

### Actual behavior

The point is that the account page is shown first, then it checks whether the user is logged in or not. After realizing that no one is logged in, the user is redirected to the login page.

### How to Reproduce?

You can easily reproduce the bug. Just try to access the account page. That's it.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thomasdarimont**
Adapted the login redirect logic from the old account console.

Fixes #31469

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java [hunk 1]
```diff
@@ -92,10 +96,31 @@ public Object getResource() {
...
     @GET
     @NoCache
-    @Path("{any:.*}")
-    public Response getMainPage() throws IOException, FreeMarkerException {
+    @Path("{path:.*}")
+    public Response getMainPage(@PathParam("path") String path) throws IOException, FreeMarkerException {
+
+        if (auth == null) {
+            return redirectToLogin(path);
+        }
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java:122]: Could we add a test for this redirect logic?

File: services/src/main/java/org/keycloak/services/resources/AbstractSecuredLocalService.java
Comment (jonkoops) [inline services/src/main/java/org/keycloak/services/resources/AbstractSecuredLocalService.java:1]: This entire file was orphaned code before changes were introduced in this PR to add some public code. This leads me to suspect that there is likely another way to do the redirect required to authenticate the user, although I am not aware of where this code resides. Perhaps someone else on the team is aware of this. Was this code previously used anywhere?

Comment (thomasdarimont) [reply services/src/main/java/org/keycloak/services/resources/AbstractSecuredLocalService.java:1]: Perhaps @mposolda has an Idea what the "new " way to redirect the user to the login is.

File: services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java (hunk 1 above)
Comment (thomasdarimont) [reply services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java:106]: I just added a test for this.

**Comment by mposolda** [comment]
@jonkoops @thomasdarimont AFAIK at some point, the "home page" of the account console allowed anonymous mode (the initial page was displayed even if user was not logged-in) and user needed explicitly to click "Sign in" to being redirected to login. But it looks that this behaviour changed and users are now always required to authenticate to access account console. Is it correct? The new behaviour makes sense to me, just wanted to confirm that this was changed on purpose :-)

@jonkoops AFAIK the code, which redirects user to the account-console is done by keycloak.js adapter. Not exactly sure where (in which file) the keycloak.js adapter is bootstrapped for account console. If possible, it will makes sense to me to handle the redirect just on the client side and not handle this at server-side in classes like `AbstractSecuredLocalService` or `AccountConsole` due the login options being configured on single place (EG. `scope` parameter if we ever want to add supporting it in account-console). But not sure how feasible it is?

I guess it will require to do some slight update and make sure that keycloak.js is bootstrapped earlier before the initial account pages are rendered. I suppose there is a way to do this as admin-console does not render any stuff before being redirected to login page?

**Comment by thomasdarimont** [comment]
Since the Account Console is hosted by the Keycloak Server directly, we could just use the Keycloak Server as a Backend For Frontend (BFF).  By using this the account console frontend would not need to use an access / refresh token at all, but would rely on a cookie that can be read by the Keycloak server.

**Comment by jonkoops** [comment]
> By using this the account console frontend would not need to use an access / refresh token at all, but would rely on a cookie that can be read by the Keycloak server.

This would also mean that we'd have to use this cookie as a way to call the Admin REST API in an authenticated manner. Not advocating for or against it, just something to take into account.

**Comment by thomasdarimont** [comment]
> This would also mean that we'd have to use this cookie as a way to call the Admin REST API in an authenticated manner. Not advocating for or against it, just something to take into account.

Yes, that would be one option. Another option would be to create a dedicated account "backend" for the Account Console (similar to the admin console endpoints) that accepts requests authenticated via cookie. The account backend could then resolve the current user (session) from the cookie, and call the internal APIs.

**Comment by pedroigor** [comment]
@jonkoops @thomasdarimont The changes seem to be enough to solve the original problem. Is there anything else missing to merge this one or are you still considering alternatives?

For me, we can go with this one first and evaluate the BFF later. Do we really need this now?

File: services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java [hunk 2]
```diff
@@ -193,6 +202,20 @@ public Response getMainPage() throws IOException, FreeMarkerException {
...
 
+    private Response redirectToLogin(String path) {
+        UriBuilder consoleUriBuilder = Urls.accountBase(session.getContext().getUri().getBaseUri());
+        if (!StringUtil.isNullOrEmpty(path)) {
+            consoleUriBuilder.path(path);
+        }
+        URI targetUri = consoleUriBuilder.build(realm.getName());
+
+        var oauthRedirect = new AbstractSecuredLocalService.OAuthRedirect();
+        oauthRedirect.setAuthUrl(OIDCLoginProtocolService.authUrl(session.getContext().getUri()).build(realm.getName()).toString());
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java:213]: To avoid multiple sources for the client config, can we use a public endpoint to fetch the config? IIRC, we had this before, don't we?

**Comment by ahus1** [comment]
I know I'm late for the party, still some thought here: Some years ago I wrote a Vue.js app and the way do do things was to first call keycloak.init(), and then on success or failure initialize Vue. Not sure if this pattern still apply, and if it is suitable for React as well. This could avoid duplicating the frontend and backend logic.

**Comment by pedroigor** [comment]
@ahus1 As mentioned by @jonkoops, it seems we can't do that in React, at least without deep changes to how we bootstrap the adapter.

**Comment by jonkoops** [comment]
> I know I'm late for the party, still some thought here: Some years ago I wrote a Vue.js app and the way do do things was to first call keycloak.init(), and then on success or failure initialize Vue. Not sure if this pattern still apply, and if it is suitable for React as well. This could avoid duplicating the frontend and backend logic.

This is the way it used to be, but when the Keycloak instance got pulled into `ui-shared` it became a service, which requires React to be bootstrapped. But even if it was the way it was before this still saves users time waiting for loading states, so a nice enhancement.

**Comment by pedroigor** [comment]
@ahus1 @jonkoops @thomasdarimont Let's then continue with the proposal in this PR. Sounds good to you?

The missing points are:

* Make sure the account adapter config is resolved from a single place
* Fix tests as the failures are related.

**Comment by jonkoops** [comment]
Sounds good!

**Review by jonkoops — DISMISSED** [review]

**Comment by thomasdarimont** [comment]
@pedroigor I think this works now as discussed and the account e2e test are passing now. The test failures in the admin ui seems to unreleated.

**Comment by thomasdarimont** [comment]
Yay all tests are passing now :)

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
Thanks, @thomasdarimont. 

@jonkoops @mposolda Would you mind re-reviewing it?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java [hunk 3]
```diff
@@ -299,7 +299,7 @@ private void registerUser(OrganizationResource organization, String expectedEmai
     }
 
     private void acceptInvitation(OrganizationResource organization, UserRepresentation user) throws MessagingException, IOException {
-        acceptInvitation(organization, user, "Account Management");
+        acceptInvitation(organization, user, "Sign in to");
```
Comment (jonkoops) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java:302]: Does this test still work as expected? Seems like this now ends up on the login page instead.

**Review by jonkoops — APPROVED** [review]

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java (hunk 3 above)
Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java:302]: That was the page title when rendering-first the account console even though you have a redirect to the login page.

Comment (jonkoops) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java:302]: Sounds good then, consider this resolved.

**Comment by jonkoops** [comment]
Thanks for working on this @thomasdarimont. This is a really nice little UX boost.
