### PR TITLE
fix: adds a test and permissions for cache configmap

### LINKED ISSUE #28638: Missing permission to read configmaps in `keycloak-operator-role`
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Using a custom infinispan config:
```
spec:
  cache:
    configMapFile:
        name: kcb-infinispan-cache-config
        key: ....
```

I get a permission error when the operator's service account is trying to access it:
```
Failure executing: GET at: [https://172.30.0.1:443/api/v1/namespaces/tkyjovsk-keycloak/configmaps/kcb-infinispan-cache-config](https://172.30.0.1/api/v1/namespaces/tkyjovsk-keycloak/configmaps/kcb-infinispan-cache-config). Message: configmaps \"kcb-infinispan-cache-config\" is forbidden: User \"system:serviceaccount:tkyjovsk-keycloak:keycloak-operator\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"tkyjovsk-keycloak\". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=configmaps, name=kcb-infinispan-cache-config, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps \"kcb-infinispan-cache-config\" is forbidden: User \"system:serviceaccount:tkyjovsk-keycloak:keycloak-operator\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"tkyjovsk-keycloak\", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
```

Manually adding the permission to read configmaps into the `keycloak-operator-role` and restarting the operator pod seems to resolve the problem.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Permission issue not present.

### Actual behavior

See bug description.

### How to Reproduce?

See bug description.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #28638

To match olm we need to remove the auto-generated view role from the remote tests. From there rbac on minikube is sufficient to catch this situation.

Added the permissions that will allow for using a watch/informer or polling.

### CODE REVIEW

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+        });
+
+        createCacheConfigMap();
+
+        Awaitility.await().ignoreExceptions().atMost(2, TimeUnit.MINUTES).untilAsserted(() -> {
+            assertThat(stsResource.get()).isNotNull();
+            Keycloak keycloak = keycloakResource.get();
+            CRAssert.assertKeycloakStatusCondition(keycloak, KeycloakStatusCondition.HAS_ERRORS, false);
+            CRAssert.assertKeycloakStatusCondition(keycloak, KeycloakStatusCondition.READY, false);
+        });
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java:77]: I'm not sure if we should be testing like that. No errors and not ready basically happens immediately, doesn't tell us anything about cache config file. If there were errors, they might happen a bit later, not immediately.

Shouldn't we rather wait for Keycloak to be truly ready and also check if the volume mount exists and KC_CACHE_CONFIG_FILE points to it?

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+
+        Resource<StatefulSet> stsResource = k8sclient.resources(StatefulSet.class).withName(deploymentName);
+        Resource<Keycloak> keycloakResource = k8sclient.resources(Keycloak.class).withName(deploymentName);
+
+        Awaitility.await().ignoreExceptions().atMost(2, TimeUnit.MINUTES).untilAsserted(() -> {
+            assertThat(stsResource.get()).isNotNull();
+            Keycloak keycloak = keycloakResource.get();
+            CRAssert.assertKeycloakStatusCondition(keycloak, KeycloakStatusCondition.HAS_ERRORS, false);
+            CRAssert.assertKeycloakStatusCondition(keycloak, KeycloakStatusCondition.READY, false);
+        });
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java:97]: Same comment as above.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@shawkins Thank you for the quick fix!

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java (hunk 2 above)
Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java]: Corrected, just a copy and paste error.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java (hunk 1 above)
Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java]: > I'm not sure if we should be testing like that. No errors and not ready basically happens immediately, doesn't tell us anything about cache config file. If there were errors, they might happen a bit later, not immediately.

It's the same weak check that we're doing in the testKeycloakDeploymentBeforeSecret test. Essentially it's the existence check of the statefulset that we're wanting to see here - that we progressed in resolving enough for that to be created. If there were a RBAC issue, this it won't exist. There is a narrow possibility that the statefulset status may not yet exist, but since we've disabled probes as long as the pods are created successfully that would cause the rollout to be successful. It would be more propper to check that the statefulset is blocked by the configmap, which could be done in the testKeycloakDeploymentBeforeSecret test as well.

> Shouldn't we rather wait for Keycloak to be truly ready and also check if the volume mount exists and KC_CACHE_CONFIG_FILE points to it?

Sorry, yes that was supposed to check for full readiness. I'm not checking the volume mount here because that is covered by a PodTemplate test. We can of course do other things like initially specify an invalid config to make sure that it's being picked up appropriately.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java]: Makes sense, thanks.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+
+        createCacheConfigMap();
+
+        K8sUtils.waitForKeycloakToBeReady(k8sclient, kc);
+    }
+
+    @Test
+    public void testCacheConfigMapFile() {
+        var kc = getTestKeycloakDeployment(true);
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java:78]: Would it make sense to run with probes enabled in this test?
```suggestion
        var kc = getTestKeycloakDeployment(false);
```

Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java:78]: Not necessarily - the tests here are really just to exercise the operator's handling of configmaps. We could add a polling test as well here. All of the other considerations - how the file is mounted, if it's valid - are either covered by other tests or aren't really the concern of this feature.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java:78]: Makes sense, thanks. Let's not hold this PR any longer. LGTM.

**Review by vmuzikar — APPROVED** [review]
