### PR TITLE
Execution config not duplicated when duplicating flows

### LINKED ISSUE #12012: KEYCLOAK-17116 Copy of Browser Flow overrides an original one
### Describe the bug

I was trying to create a custom authentication flow in order to use a new default Idp. To do that I copied Browser flow and edited `Identity Provider Redirector` on a copy. This change was applied to the original one. It can lead to a big issue if you try to change it on prod.

### Version

11.0.2, 12.0.2

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Configure "Identity Provider Redirector" for Browser flow with Default Identity Provider=1111
Copy Browser flow
Change "Default Identity Provider" on the copy to 2222
Check Browser flow -> Identity Provider Redirector -> Default Identity Provider. It equals "2222" instead of "1111"

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #12012

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java [hunk 1]
```diff
@@ -392,6 +392,26 @@ public static void copy(RealmModel realm, String newName, AuthenticationFlowMode
...
+
+            if (execution.getAuthenticatorConfig() != null) {
+                AuthenticatorConfigModel config = realm.getAuthenticatorConfigById(execution.getAuthenticatorConfig());
+
+                if (config == null) {
+                    logger.debugf("Authentication execution with id [%s] not found", config.getId());
+                    throw new IllegalStateException("Authentication execution configuration not found");
+                }
+
+                config.setId(null);
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java:404]: It is not very nice to duplicate objects like that but changing it would introduce more changes to this PR. Looks like this pattern is being used alot.

File: services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java [hunk 2]
```diff
@@ -392,6 +392,26 @@ public static void copy(RealmModel realm, String newName, AuthenticationFlowMode
...
+
+                if (config.getAlias() != null) {
+                    config.setAlias(newName + " " + config.getAlias());
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java:407]: If the alias is kept the same it will break `RealmModel.getAuthenticatorConfigByAlias`. This is not well-tested and sages of `alias` across the code base are not very clear.

**Comment by mposolda** [comment]
@pedroigor LGTM. Thanks for this fix! The only remaining thing from my point of view is fix the `InitialFlowsTest` (seems to be also causing store related issues).

**Review by mposolda — APPROVED** [review]
