### PR TITLE
fix: corrects cli arg stringification

### LINKED ISSUE #34155: cli options starting or ending with ; or containing ;; mangle the cli handling
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

cli options starting or ending with ; or containing ;; mangle the cli handling

### Version

all

### Regression

- [ ] The issue is a regression

### Expected behavior

Arguments should be preserved

### Actual behavior

The logic is using ;; as a separator, but performs no escaping so naturally occurring usage of ; becomes problematic.

### How to Reproduce?

Using a command that includes: --db-url=...; --something

Will mangle the --something to become "; --something"

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #34155

I would have liked to just use a new static variable on ConfigArgsConfigSource, but that doesn't seem to work because a different classload is used for building.

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java [hunk 1]
```diff
@@ -53,7 +53,7 @@ public final class ShowConfig extends AbstractCommand implements Runnable {
 
     public static final String NAME = "show-config";
     private static final List<String> ignoredPropertyKeys = List.of(
-            "kc.config.args", "kc.show.config", "kc.profile", "kc.quarkus-properties-enabled", "kc.home.dir");
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java:56]: Just out of curiosity. We're still setting the `kc.config.args` sys prop as before. Why we don't need to ignore it any longer? It might still be recognized as a config option, no?

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks @shawkins

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java:56]: We must have at some point seen system properties as config properties. This and the check for build time properties seem to indicate that - however system properties are no longer picked up as config properties, so we don't need this.
