### PR TITLE
Make sure user-defined user profile config is set if provided

### LINKED ISSUE #48008: User-defined user profile configuration not set when starting the server
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

It is a behavior that changed in Quarkus and broke our (wrong) assumption about the order of the execution of build steps.

The default user profile configuration is set before calling the user profile factory `init`, therefore preventing from setting the user-defined configuration

### Version

26.6.0

### Regression

- [x] The issue is a regression

### Expected behavior

User-defined user profile configuration is set as the default

### Actual behavior

User-defined user profile configuration is not set as the default

### How to Reproduce?

Start the server using the `spi-user-profile--declarative-user-profile--config-file` SPI option and see the config is not loaded but the default.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #48008

### CODE REVIEW

File: services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java [hunk 1]
```diff
@@ -560,17 +557,18 @@ private void initDefaultConfiguration(Scope config) {
...
-                .map(UPConfigUtils::parseConfig)
-                .orElse(PARSED_DEFAULT_RAW_CONFIG);
-
-        // As fallback parse the system default config
-        if (parsedConfig == null) {
-            parsedConfig = UPConfigUtils.parseSystemDefaultConfig();
+        String configFile = config.get("configFile");
+
+        if (configFile == null) {
+            // the default config is already parsed and will be set by Quarkus
```
Comment (shawkins) [inline services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java]: Does this mean that this factory will no longer work as expected with undertow? Or are there no longer arquillian tests of this functionality?

Comment (pedroigor) [reply services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java]: I changed the approach, but I'm not sure if the best.

Looking at other build steps, some use `PropertyMappingInterceptor#disable` to temporarily allow fetching configuration from config sources within a try/finally block.

I'm also looking for the two formats of SPI options.

**Review by shawkins — APPROVED** [review]
LGTM
