### PR TITLE
A11y fixes for Account UI

### LINKED ISSUE #17597: Accessibility/Account management: Minor Issues
### Describe the bug

Minor issues were found as per the [attached](https://docs.google.com/spreadsheets/d/1KtZJbDHKosSJBQm--1iJKQMwGIOtoohXIdfwMH3rPns/edit?usp=sharing).

### Version

21.0.0

### Environment

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Use Deque Browser Extension.

### Anything else?

_No response_

### LINKED ISSUE #17598: Accessibility/Account management: Moderate Issues
### Describe the bug

The following issues were found as per the [attached](https://docs.google.com/spreadsheets/d/1KtZJbDHKosSJBQm--1iJKQMwGIOtoohXIdfwMH3rPns/edit?usp=sharing).

### Version

21.0.0

### Environment

_No response_

### Expected behavior

Reported issues are fixed.

### Actual behavior

Reported issues are not fixed.

### How to Reproduce?

Use Deque Browser Extension,

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/17597 and closes https://github.com/keycloak/keycloak/issues/17598

### CODE REVIEW

File: js/apps/account-ui/src/groups/Groups.tsx [hunk 1]
```diff
@@ -69,7 +69,10 @@ const Groups = () => {
             />
           </DataListItemRow>
         </DataListItem>
-        <DataListItem id="groups-list-header" aria-labelledby="Columns names">
+        <DataListItem
+          id="groups-columns-header"
+          aria-labelledby="Columns names"
```
Comment (jonkoops) [inline js/apps/account-ui/src/groups/Groups.tsx:74]: The `aria-labelledby` attribute should reference an `id` of the element that labels this one. Otherwise an `aria-label` attribute should be used with a human readable string.

File: js/apps/account-ui/src/resources/ResourcesTab.tsx [hunk 2]
```diff
@@ -154,7 +154,9 @@ export const ResourcesTab = ({ isShared = false }: ResourcesTabProps) => {
             <Th aria-hidden="true" />
             <Th>{t("resourceName")}</Th>
             <Th>{t("application")}</Th>
-            <Th>{!isShared ? t("permissionRequests") : ""}</Th>
+            <Th aria-hidden={isShared ?? true}>
```
Comment (jonkoops) [inline js/apps/account-ui/src/resources/ResourcesTab.tsx:157]: Since `isShared` is always defined there should be no need to fall back to another value.

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/account-ui/src/groups/Groups.tsx (hunk 1 above)
Comment (agagancarczyk) [reply js/apps/account-ui/src/groups/Groups.tsx]: Thanks @jonkoops I've just pushed a fix. Please let me know if that's better now.

Comment (jonkoops) [reply js/apps/account-ui/src/groups/Groups.tsx]: @agagancarczyk it still contains a human readable string in an attribute that is expected to be the ID of an element that describes it instead. See https://tink.uk/the-difference-between-aria-label-and-aria-labelledby/

Comment (agagancarczyk) [reply js/apps/account-ui/src/groups/Groups.tsx]: Thanks, I changed `aria-labelledby` to `aria-label` as it makes more sense in this case.

**Review by jonkoops — APPROVED** [review]

**Comment by ahus1** [comment]
I see this has been tagged for 22.0.3, but AFAIK it hasn't been backported to the Release 22 branch. I'm updating the tag for 22.0.4, and adding it to the backport project.
