### PR TITLE
fix: creating a cleaner module for use by java clients

### LINKED ISSUE #48114: Restructor the client admin api v2 logic
### Description

In order to have a clean api we should put the rest interfaces and the representations in a single module (api), with everything else in another (services)

### PR DESCRIPTION
**Pull request by shawkins**
close: #48114

Rather than relying on dependency exclusion, we can refactor to have a cleaner layer for clients to use. Basically the representations, validation annotations, and rest interfaces are now in the "api" module, with everything else in "services".

### CODE REVIEW

**Review by michalvavrik — COMMENTED** [review]
+1 for extracting API. It feels like I shouldn't be the making this call as I am not yet familiar with all customs here, so I'll skip this one.

**Comment by shawkins** [comment]
> Everything else was moved to the api module as I didn't yet want to introduce a third module.

With two modules the ValidationContext is used to isolate the "rest" module from keycloak-server-spi.

Alternatives:

- If we added a third module we can have things even more factored:
  - "api or rest" - just rest interfaces and representations, has a provided dependencies on "validations" and hibernate validator. This would be the only module needed by the admin client.
  - "validations" - May directly use keycloak-server-spi, so the ValidationContext can go back to directly referencing the session and realm.
  - "services" - everything else.

- Allow a provided dependency to keycloak-server-spi, but ensure we only use those classes in the validation logic. If it inadvertantly makes it into the representations, or rest interfaces we risk either pulling in unintended dependencies or making the creation of the admin client more complicated.

- Just rely on https://github.com/keycloak/keycloak/pull/47902 and let the admin client creation logic look across multiple modules, selectively copy classes, etc.

**Comment by vmuzikar** [comment]
> If we added a third module we can have things even more factored

As discussed offline, let's try the 3 module structure: `api`, `validations`, `services`.

**Comment by shawkins** [comment]
@vmuzikar here's another pass at doing the two module split. The key was finding that validators can be service loaded, so we can keep the annotations along with the representions, but have the implementations in the "services" module.

TODO:
- this probably needs associated with a new issue
- rename api to services
  - should rest be renamed to api?
- replace jsonnode with inputstream - #47913 
- we could mark all the annotation dependencies of the rest/api module as provided, but that currently doesn't seem necessary
- see if we can change the source compatibility to align with the admin client

**Comment by shawkins** [comment]
@vmuzikar @Pepo48 updated based upon the direction from our meeting. Should be ready for more review.

File: rest/admin-v2/services/src/main/java/org/keycloak/representations/admin/v2/validators/UuidUnmodifiedValidator.java [hunk 1]
```diff
@@ -23,10 +25,11 @@ public class UuidUnmodifiedValidator implements ConstraintValidator<UuidUnmodifi
...
     public void initialize(UuidUnmodified constraintAnnotation) {
-        try {
-            uuidProvider = constraintAnnotation.uuidProvider().getDeclaredConstructor().newInstance();
-        } catch (ReflectiveOperationException e) {
-            throw new RuntimeException("Failed to instantiate UUID provider: " + constraintAnnotation.uuidProvider().getName(), e);
+        Class<?> type = constraintAnnotation.type();
+        if (type == BaseClientRepresentation.class) {
+            uuidProvider = new ClientUuidProvider();
+        } else {
+            throw new AssertionError("Not Uuid Provider defined for " + type);
```
Comment (michalvavrik) [inline rest/admin-v2/services/src/main/java/org/keycloak/representations/admin/v2/validators/UuidUnmodifiedValidator.java]:
```suggestion
            throw new AssertionError("No Uuid Provider defined for " + type);
```

File: quarkus/runtime/pom.xml [hunk 2]
```diff
@@ -424,15 +424,15 @@
...
+            <artifactId>keycloak-admin-v2-services</artifactId>
             <exclusions>
                 <exclusion>
                     <groupId>*</groupId>
                     <artifactId>*</artifactId>
                 </exclusion>
             </exclusions>
         </dependency>
-
+
```
Comment (michalvavrik) [inline quarkus/runtime/pom.xml]: let's drop the trailing white space (in case it was intentional, I'd like to learn about it so that I understand in the future as well)

File: rest/admin-v2/services/pom.xml [hunk 3]
```diff
@@ -52,9 +69,18 @@
             <optional>true</optional>
         </dependency>
     </dependencies>
-
+
```
Comment (michalvavrik) [inline rest/admin-v2/services/pom.xml]:
```suggestion

```

(trailing white space, the new line is fine)

File: rest/admin-v2/services/src/main/java/org/keycloak/representations/admin/v2/validators/UuidUnmodifiedValidator.java [hunk 4]
```diff
@@ -23,10 +25,11 @@ public class UuidUnmodifiedValidator implements ConstraintValidator<UuidUnmodifi
 
     @Override
     public void initialize(UuidUnmodified constraintAnnotation) {
-        try {
-            uuidProvider = constraintAnnotation.uuidProvider().getDeclaredConstructor().newInstance();
-        } catch (ReflectiveOperationException e) {
-            throw new RuntimeException("Failed to instantiate UUID provider: " + constraintAnnotation.uuidProvider().getName(), e);
+        Class<?> type = constraintAnnotation.type();
```
Comment (michalvavrik) [inline rest/admin-v2/services/src/main/java/org/keycloak/representations/admin/v2/validators/UuidUnmodifiedValidator.java]: This requires no changes if you want to make it explicit. I just meant to note you could avoid `type` (drop the annotation attribute) as you already know the type in `isValid` anyway, so you could initialize `uuidProvider` there lazily into `volatile` prop. It is just matter of preference and yours is fine with me.

File: quarkus/runtime/pom.xml (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/pom.xml]: It's not intentional, just my ide seems to not be set to remove trailing from all file types.

File: rest/admin-v2/services/src/main/java/org/keycloak/representations/admin/v2/validators/UuidUnmodifiedValidator.java (hunk 4 above)
Comment (shawkins) [reply rest/admin-v2/services/src/main/java/org/keycloak/representations/admin/v2/validators/UuidUnmodifiedValidator.java]: Thank you for this simplification. Updated to remove the type attribute and addressed the other review comments.

File: rest/admin-v2/services/src/main/java/org/keycloak/representations/admin/v2/validators/UuidUnmodifiedValidator.java [hunk 5]
```diff
@@ -19,19 +21,16 @@
...
-
     @Override
     public boolean isValid(RepresentationWithUuid representation, ConstraintValidatorContext context) {
+        Class<?> type = representation.getClass();
+        UuidProvider uuidProvider = null;
+        if (BaseClientRepresentation.class.isAssignableFrom(type)) {
+            uuidProvider = new ClientUuidProvider();
+        } else {
+            throw new AssertionError("No UuidProvider defined for " + type);
+        }
```
Comment (vmuzikar) [inline rest/admin-v2/services/src/main/java/org/keycloak/representations/admin/v2/validators/UuidUnmodifiedValidator.java:32]: This is not ideal, it's shifting the dependency for providing the UUID from the representation to the validator that should not be concerned with representation specific details like how to get the UUID. That said, it's ok from my perspective for now and we will revisit later in #44162 and #47451.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

**Comment by vmuzikar** [comment]
Build seems to be failing, though.

**Comment by shawkins** [comment]
> Build seems to be failing, though.

Should just be some npm flakiness.

**Review by michalvavrik — APPROVED** [review]
LGTM
