### PR TITLE
[quick-theme] Show login page and change basic attributes

### LINKED ISSUE #45581: [quick-theme] The default logo and background is not applied when not overridden for login
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

At this moment, when you use the `quick-theme` feature and you don't specify the logo or background, the default should be used. 

At this moment, there's no logo present and empty background applied. 

### Version

999

### Regression

- [ ] The issue is a regression

### Expected behavior

Default logo and background is used

### Actual behavior

Cannot find the undefined logo and background

### How to Reproduce?

Create a custom theme without overriden logo and background and use it for login theme. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #45524
- Closes https://github.com/keycloak/keycloak/issues/45581

## :tada: How to extend your theme with the Quick theme? 

- You can directly see the login screen when customizing
- You can see the background change
- You can edit the width and height of the logo
- Inspired by Keycloakify (they also directly uses the HTML tags inside the React files)
- WiP - needs polishing (no hardcoded theme.properties, no hardcoded CSS files,...)

### 1. Create the custom theme with custom logo, background and colors
 
https://github.com/user-attachments/assets/5cf986e8-592f-4d62-83ed-ae3b2ba8d9d8

### 2. Add the created JAR to the `/providers` folder
And change the login theme to your new theme:

https://github.com/user-attachments/assets/2cd31217-4234-4399-972f-6db7d7251350

@edewit @ssilvert @stianst Let me know if you like the way it goes or not :)

### CODE REVIEW

**Comment by edewit** [comment]
:+1: I like this

**Comment by edewit** [comment]
what also would be cool, maybe outside of this PR, but to be able to set other things like rounded corners, see this link for some more ideas https://keycloak-theme-editor.tpvk7sed8.workers.dev/

**Comment by mabartos** [comment]
> what also would be cool, maybe outside of this PR, but to be able to set other things like rounded corners

@edewit Yes, that's true. We could provide some basic attributes by default that are frequently changed - rounder corners, background properties,...

And if it's not sufficient, there might be also a custom text input box for custom CSS (with all these validations of course).

There should be also a capability to change the name of the theme.

**Comment by mabartos** [comment]
@ssilvert @edewit Could you please check it? Thanks!

Other improvements can be done in follow-up tasks.

Some of them already identified in the milestone:
- https://github.com/keycloak/keycloak/issues/45523

**Comment by ssilvert** [comment]
@mabartos I like this too.  

However, at first it wasn't clear to me that I would need to scroll down to see the original WYSIWYG that was more based on admin console.  Maybe this is more clear if I was looking at it live rather than in the video?

Any ideas?

**Comment by mabartos** [comment]
@ssilvert Thanks for the comment. 

This is the initial form and it still needs some improvements. At this moment, the login preview is on top and the admin preview is under that. However, I thought that we could provide some Init page when users want to customize themes. That they could choose what component they want to customize (login, account, admin, or all) and the specific preview would be shown. Captured here: https://github.com/keycloak/keycloak/issues/45531

Or there might be some 3 way "switch" at the top of the preview "Login | Account | Admin", and only one could be choosen and then shown. And admins could just switch to other preview to see how it looks like for other previews. 

But we can discuss more :)

**Comment by mabartos** [comment]
@edewit As we discussed, this initiative will be more targeted to 26.7, but if you have some spare time, you could check it and potentially add whatever suits to the TS changes.

**Comment by edewit** [comment]
@ssilvert it moves down when there isn't enough room if you make your screen a bit wider then if fits. What we could do is collapse the sidebar on this screen so that the user has more room to edit. Right now when you "design" a theme it creates a theme that can be applied to all "apps", you can then opt to only use it for the login once installed, so I don't think we need to ask a user here what they want to theme. So I rather have a tab control so they can see what the changes look like for the different "apps".

**Review by edewit — APPROVED** [review]
I have a small fix https://github.com/mabartos/keycloak/pull/1138

**Comment by mabartos** [comment]
@edewit LGTM.

image

**Comment by vmuzikar** [comment]
@mabartos @edewit Is this ready to be merged?

**Comment by mabartos** [comment]
@vmuzikar Yes :)

**Comment by thomasdarimont** [comment]
@mabartos I just gave your branch quick-theme-login, but on my machine it still looks like this:
Screenshot 2026-02-04 at 21 19 21

Additionally, MacOS reports the generated quick-theme.jar as potentially mallicios - I needed to extract it via the terminal to view it's contents.

Some additional feedback:
- Add some additional structure (Colors, Fonts, Borders, Logo)
This would help to make tge growing list of config options less daunting. 
- Make it easier to match the customization with the target element
Right now it is hard to see beforehand which element is affacted by a particlar style. For example if I inspect the generated `<button class="pf-v5-c-button pf-m-primary pf-m-block" name="login" id="kc-login" type="submit">Sign In</button>` with dev tools I don't see immediately which style option is affecting this element.
I dev tools I see `background-color: var(--pf-v5-c-button--m-primary--Color)` - which Style option do I need to modify to change the color? Perhaps it would help to show a (?) next to the style option that mentions the actual css class / css-variable.
Another option would be to briefly highlight the respective target element in the preview when clicking in a styling option.
- Logo Position and Visibility
It would be helpfil if we could control the logo alignment (left, center, right)
- Logo location (URL instead of upload)
Some customers prefer to use a logo from a predefined URI that they control. 
- Identity Provider Button Location
Some customer want to show the identity provider icons first and offer the username/password as a secondary option.
- Page State Toggles:
It would be helpful to toggle different page states (status: error/success, focussed, hover) to quickly preview the effect of the styling.
- Support for customizing font sizes (Title, Subtitle, Body, Buttons, Labels, Links)
This would make the styling capabilities more complete.
- Support more use-case pages (Registration, Required Action, Profile validation, Consent, 2FA screens, Error)
This would help to view the styling in action directly.
- Add support to import/export a style preset as json
This can be exchanged easier than sending a jar around (e.g. some companies might block .jar attachments in emails).
- Add support to select locale for preview
This would make it easier to see issues with too long texts etc.

I'm looking forward to this feature finally being implemented!

**Comment by mabartos** [comment]
@thomasdarimont Oops, that's weird... I'll check it tomorrow. Thanks!

Nice list of possible improvements though!

File: js/apps/admin-ui/src/realm-settings/themes/LoginPreviewWindow.tsx [hunk 1]
```diff
@@ -0,0 +1,222 @@
...
+  const contextLogo = usePreviewLogo();
+  const contextBackground = usePreviewBackground();
+
+  // Resources
+  const resourceUrlRoot = `/resources/${environment.resourceVersion}`;
+  const loginResourceUrl = `${resourceUrlRoot}/login/keycloak.v2`;
+
+  // Default login theme resources from local files
+  const defaultBgImage = `${loginResourceUrl}/img/keycloak-bg-darken.svg`;
+  const defaultLogo = `${loginResourceUrl}/img/keycloak-logo-text.svg`;
```
Comment (mabartos) [inline js/apps/admin-ui/src/realm-settings/themes/LoginPreviewWindow.tsx:22]: Getting the default background image, and logo from the login resources on the server.

File: js/apps/admin-ui/src/realm-settings/themes/LoginPreviewWindow.tsx [hunk 2]
```diff
@@ -0,0 +1,222 @@
...
+
+  const logoWidth = cssVars["logoWidth"];
+  const logoHeight = cssVars["logoHeight"];
+
+  // CSS files
+  const pf5CssRootPath = `${resourceUrlRoot}/common/keycloak/vendor/patternfly-v5`;
+  const pf5Css = `${pf5CssRootPath}/patternfly.min.css`;
+  const pf5AddonsCss = `${pf5CssRootPath}/patternfly-addons.css`;
+
+  const stylesThemeCssUrl = `${loginResourceUrl}/css/styles.css`;
```
Comment (mabartos) [inline js/apps/admin-ui/src/realm-settings/themes/LoginPreviewWindow.tsx:37]: Getting the PF5 CSSs from the resources on the server.

File: js/apps/admin-ui/src/realm-settings/themes/ThemesTab.tsx [hunk 3]
```diff
@@ -117,18 +120,20 @@ styles=css/login.css css/theme-styles.css
         .map(([key, value]) => `--pf-v5-global--${key}: ${value};`)
         .join("\n");
 
-    const logoCss = (
-      await fetch(joinPath(environment.resourceUrl, "/theme/login.css"))
+    const loginCss = (
+      await fetch(
+        `/resources/${environment.resourceVersion}/login/keycloak.v2/css/styles.css`,
```
Comment (mabartos) [inline js/apps/admin-ui/src/realm-settings/themes/ThemesTab.tsx:124]: Didn't really work before. 

Now, it uses the login v2 CSS file.

**Review by mabartos — COMMENTED** [review]
@thomasdarimont I was able to reproduce the issue and now it should work - trying it with Vite introduced an illusion that all resources (CSS) are present. 

@edewit I just fetch the default background and logo from the keycloak.v2 theme resources, so we don't need to duplicate it anywhere. The same with the default styles.css

@edewit Can you review it again? Thanks!

**Review by edewit — APPROVED** [review]

**Comment by mabartos** [comment]
Resolved conflict and rebased. 

I can confirm it works even with the new light/dark switch:


https://github.com/user-attachments/assets/1b9aa2cd-44e9-408d-be2d-ef32e19aac42

**Comment by mabartos** [comment]
@edewit Fixed lint error.

**Review by edewit — APPROVED** [review]

**Comment by mabartos** [comment]
@edewit Thanks for the review!

@vmuzikar We should be ready to go with this one :) Thanks!

**Review by vmuzikar — APPROVED** [review]
Approving based on other reviews.
