### PR TITLE
Using a valid URI when deleting cookies before/after running tests

### LINKED ISSUE #22691: Flaky test: org.keycloak.testsuite.forms.RecoveryAuthnCodesAuthenticatorTest#test03AuthenticateRecoveryAuthnCodes
## org.keycloak.testsuite.forms.RecoveryAuthnCodesAuthenticatorTest#test03AuthenticateRecoveryAuthnCodes
[Keycloak CI - Forms IT (firefox)](https://github.com/keycloak/keycloak/actions/runs/5963149836/job/16176167764) / [Pull Request #22463](https://github.com/keycloak/keycloak/pull/22463)

```
org.openqa.selenium.TimeoutException: 
Navigation timed out after 10000 ms
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'fv-az408-563', ip: '10.1.0.185', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1041-azure', java.version: '17.0.8'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
...
```

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #22691

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java [hunk 1]
```diff
@@ -285,7 +285,7 @@ public void deleteAllCookiesForMasterRealm() {
     protected void deleteAllCookiesForRealm(String realmName) {
         // we can't use /auth/realms/{realmName} because some browsers (e.g. Chrome) apparently don't send cookies
         // to JSON pages and therefore can't delete realms cookies there; a non existing page will do just fine
```
Comment (ahus1) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java:287]: Please update the comment to explain which browsers require an existing page

```suggestion
        // to JSON pages and therefore can't delete realms cookies there. Apparently it needs to be an existing page because ...
```

**Review by ahus1 — CHANGES_REQUESTED** [review]

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java (hunk 1 above)
Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java:287]: Thanks, but I prefer waiting for @mposolda for a proper review and checking if that comment still makes sense.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java [hunk 2]
```diff
@@ -285,7 +285,7 @@ public void deleteAllCookiesForMasterRealm() {
...
-        navigateToUri(oauth.SERVER_ROOT + "/auth/realms/" + realmName + "/super-random-page");
+        navigateToUri(oauth.SERVER_ROOT + "/auth/realms/" + realmName + "/protocol/openid-connect/3p-cookies/step1.html");
```
Comment (jonkoops) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java:288]: You likely don't want to use this URL as this iframe sets cookies and does redirects.

Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java:288]: What cookies are set there?

Comment (jonkoops) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java:288]: It sets the `KEYCLOAK_3P_COOKIE_SAMESITE` and `KEYCLOAK_3P_COOKIE` (see [source code](https://github.com/keycloak/keycloak/blob/904e688400cbb4470b15d88ef9f65f03ee1e7c71/services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html#L49-L56)), and then redirects to `step2.html`, which then attempts to [read and clear](https://github.com/keycloak/keycloak/blob/904e688400cbb4470b15d88ef9f65f03ee1e7c71/services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step2.html#L12-L15) those cookies.

> The main idea here is to actually reach out the server and a realm to make sure the driver can delete all cookies bound to a domain/path. 

Aren't we just testing WebDriver at that point? Seems rather redundant.

Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java:288]: Not sure if redundant because that method is called before, and sometimes after, a test is run. So it seems all about making sure the webdriver is not referencing cookies from previous runs. And by cookies, the main ones are those related to the user session. But again, that is what I would like to check with Marek.

I can choose some other HTML-facing endpoint if we want to. But those cookies you mentioned should not interfere with tests as they are expiring.

I was able to run the test I'm fixing in this PR multiple times without any failure. Without the change, it fails very often. We can always evaluate a better approach if this one proves to be not enough.

Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java:286]: @jonkoops I tried to change the endpoint locally to `step2.html` and it works fine too. Not sure if makes any difference to change the PR but if you have a suggestion to use some other endpoint, I can see how it goes.

Comment (mposolda) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java:286]: @jonkoops Is it ok with you to use `step2.html` url or will it also create cookies like `KEYCLOAK_3P_COOKIE_SAMESITE` ?

Other option is to create some "dummy" endpoint (maybe in `TestingResourceProvider` or somewhere where our other "test endpoints" are), but would be nice to avoid that, so we don't create endpoint just for this purpose?

**Review by mposolda — DISMISSED** [review]

**Comment by pedroigor** [comment]
FTR, looks like the failure is related to:

```
1704414581685	addons.xpi	ERROR	System addon update list error SyntaxError: XMLHttpRequest.open: 'http://%(server)s/dummy-system-addons.xml' is not a valid URL.
BrowserFlowTest ++ console.log: "RemoteSettingsWorker error: DataError: IndexedDB: records, timestamps execute() Data provided to an operation does not meet requirements."
BrowserFlowTest ++ console.error: (new RemoteSettingsWorkerError("DataError: IndexedDB: records, timestamps execute() Data provided to an operation does not meet requirements.", 
```

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java (hunk 2 above)
Comment (jonkoops) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java]: Yeah using `step2.html` is an option, but in general I would not recommend testing against these endpoints. If it is ever changed this test will fall over.

In general I think we 'abuse' random endpoints to much. For example, I have to refactor a bunch of unrelated tests every-time I change a front-end, as other tests do stupid things like use it as a crutch to make assertions on page contents that are likely to change.

If there is a page that can be used from `TestingResourceProvider` that seems more appropriate.

**Review by ahus1 — APPROVED** [review]
My initial comments have been resolved.

**Review by mposolda — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]
