### PR TITLE
fix: removing unknown field validation parameter

### LINKED ISSUE #43728: Make unknown fields handling a server side option
### Description

* Remove the `FieldValidation` option.
* Make it a server config option.

See https://github.com/keycloak/keycloak/pull/43395#discussion_r2447106122

### PR DESCRIPTION
**Pull request by shawkins**
closes: #43728

### CODE REVIEW

File: rest/admin-v2/rest/src/main/java/org/keycloak/admin/api/client/DefaultClientApi.java [hunk 1]
```diff
@@ -105,12 +108,12 @@ public ClientRepresentation patchClient(JsonNode patch, FieldValidation fieldVal
         }
     }
 
-    static void validateUnknownFields(FieldValidation fieldValidation, ClientRepresentation rep, HttpResponse response) {
+    static void validateUnknownFields(ClientRepresentation rep, HttpResponse response) {
         if (!rep.getAdditionalFields().isEmpty()) {
-            if (fieldValidation == null || fieldValidation == FieldValidation.Strict) {
+            if (DEFAULT_FIELD_VALIDATION == null || DEFAULT_FIELD_VALIDATION == FieldValidation.Strict) {
```
Comment (vmuzikar) [inline rest/admin-v2/rest/src/main/java/org/keycloak/admin/api/client/DefaultClientApi.java]: I'd rather prefer we removed also the `FieldValidation` enum. We do not know if we'll even make it configurable (that depends on the result of #44161). We do not need it for now (just like the SPIs we removed in the previous PR).

Comment (shawkins) [reply rest/admin-v2/rest/src/main/java/org/keycloak/admin/api/client/DefaultClientApi.java]: Ok, we'll add it back later.

**Review by vmuzikar — APPROVED** [review]
@shawkins Thank you, LGTM.
