### PR TITLE
fix: allow the cli to accept negative values

### LINKED ISSUE #33068: cli does not accept negative integer arguments
### Description

The cli parsing logic will not allow something like:

```
--option=-1
```

You get an erroneous error:

```
Missing required value. Option '--option' (port) expects a single value.
```

### PR DESCRIPTION
**Pull request by shawkins**
also adding a unit testable picocli

closes: #33068

cc @mabartos @vmuzikar if necessary the changes can be cut back for 26 if we want to deffer on adding a more testable Picocli. We alluded to doing something like this at the ConfigurationTest level a few prs ago, but obviously there would be more follow up here to rewrite any of the integration tests that don't fully launch the server. We can also do some additional tweaks to get the non-AbstractStartCommand running this way as well (mostly just capturing sys out).

### CODE REVIEW

**Comment by vmuzikar** [comment]
I'd rather hold this until after 26. Does it work for you @shawkins @mabartos?

Also, does it mean the docs
https://github.com/keycloak/keycloak/blob/6855ef3d7c919e5fda841b588032b8a30fb6dd55/docs/guides/server/enabletls.adoc?plain=1#L91
are now incorrect with the `-1` support?

**Comment by shawkins** [comment]
> I'd rather hold this until after 26. Does it work for you @shawkins @mabartos?
 
Most of the changes here are testing related. The core of the fix is the removal of the PropertyMapperParameterConsumer. If even that scoped to a smaller pr seems like too much, then yes we can hold off.

> are now incorrect with the `-1` support?

From the cli it won't work, but it will from the other config sources. So if someone really wants to disable it before this fix goes in there are workarounds.

File: quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 1]
```diff
@@ -0,0 +1,209 @@
...
+        assertEquals(CommandLine.ExitCode.USAGE, nonRunningPicocli.exitCode);
+        assertThat(nonRunningPicocli.getErrString(), containsString("Unknown option: 'postgres'"));
+    }
+
+    @Test
+    public void failMultipleMultiOptionValue() {
+        NonRunningPicocli nonRunningPicocli = pseudoLaunch("build", "--features", "linkedin-oauth", "account3");
+        assertEquals(CommandLine.ExitCode.USAGE, nonRunningPicocli.exitCode);
+        assertThat(nonRunningPicocli.getErrString(), containsString("Unknown option: 'account3'"));
+    }
```
Comment (vmuzikar) [inline quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:148]: Just wanted to highlight this. It is essentially a step back that we no longer provide a user friendly message (like `Option '--db' (vendor) expects a single value. Expected values are: ...` or `Option '--features' (feature) expects one or more comma separated values without whitespace. Expected values are: ...`) in these cases any more. However, I still do believe it's a step in the right direction as we're aligning with Picocli default behaviour and it allows us to remove custom code (`PropertyMapperParameterConsumer`).

**Review by vmuzikar — APPROVED** [review]
I believe this is a good enhancement that we can now test Picocli independently of the server which provides faster test times but more importantly it allows us to access config directly from the test so we can assert it directly.

@shawkins Thank you, LGTM.

**Comment by vmuzikar** [comment]
Not merging yet to allow @mabartos to take a look as well.

File: quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 2]
```diff
@@ -0,0 +1,209 @@
...
+import org.keycloak.quarkus.runtime.configuration.test.AbstractConfigurationTest;
+
+import io.smallrye.config.SmallRyeConfig;
+import picocli.CommandLine;
+import picocli.CommandLine.Help;
+
+public class PicocliTest extends AbstractConfigurationTest {
+
+    // TODO: could utilize CLIResult
+    private class NonRunningPicocli extends Picocli {
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:43]: Follow-up: It should be separated from the specific test cases + polished. Might be good also provide some annotations(`@NonRunningServer`) + leverage @Launch annotation for it. @shawkins WDYT?

**Review by mabartos — APPROVED** [review]
@shawkins Nice work! I don't see any spot that might break the distribution execution; LGTM.

File: quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:43]: Yes, it can be refined as needed. As for mixing with the Launch annotation, it's possible, but there can be mismatches (such as capturing the console coloring) where it's not transparently the same. The goal would be to keep it runnable directly from the runtime module.
