### PR TITLE
fix: refining v2 hostname validation

### LINKED ISSUE #32643: Dots are not allowed in the path in Hostname v2
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Setting `hostname`/`KC_HOSTNAME` with the new Hostname v2 to an URL containing a dot in the path will crash keycloak at startup with the following message:

```
ERROR: Unexpected error when starting the server in (production) mode
Error details:
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:139)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:35)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:119)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:99)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.lang.IllegalArgumentException: Provided hostname is neither a plain hostname or a valid URL
	at org.keycloak.url.HostnameV2ProviderFactory.validateAndCreateUri(HostnameV2ProviderFactory.java:84)
	at org.keycloak.url.HostnameV2ProviderFactory.init(HostnameV2ProviderFactory.java:64)
	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.<init>(QuarkusKeycloakSessionFactory.java:83)
	at org.keycloak.quarkus.runtime.KeycloakRecorder.configSessionFactory(KeycloakRecorder.java:116)
	at io.quarkus.deployment.steps.KeycloakProcessor$configureKeycloakSessionFactory343981823.deploy_4(Unknown Source)
	at io.quarkus.deployment.steps.KeycloakProcessor$configureKeycloakSessionFactory343981823.deploy(Unknown Source)
	... 26 more
```

With Keycloak 24, the setting `hostname-url`/`KC_HOSTNAME_URL` has worked in this scenario.

### Version

25.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak 25 with Hostname v2 can work with a sub path that contains dots, like Keycloak 24 did.

### Actual behavior

Keycloak crashes at startup.

### How to Reproduce?

Set `hostname`/`KC_HOSTNAME` to `https://my-example.com/auth.this/crashes`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #32643

### CODE REVIEW

File: services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java [hunk 1]
```diff
@@ -78,17 +73,36 @@ public void init(Config.Scope config) {
...
+            result = URI.create("http://"+hostname);
+        }
+        catch (IllegalArgumentException e) {
+            throw new IllegalArgumentException(INVALID_HOSTNAME, e);
+        }
+        if (result.getHost() == null || !result.getHost().equals(hostname)) {
+            throw new IllegalArgumentException(INVALID_HOSTNAME);
+        }
+        this.hostname = hostname;
+    }
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java:89]: I believe, something like `foobar.com/path` would also pass for a plain hostname and it would be evaluated as `hostname=foobar.com`. I believe the validation should fail in cases like this.

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thank you for this fix!

File: services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java (hunk 1 above)
Comment (shawkins) [reply services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java:89]: This case is covered: https://github.com/keycloak/keycloak/pull/32659/files#diff-173c36cf91b186489908e31566b3d2fb199c41bb4b898f6787796ae194fb083fR42

The check for getHost equality with the hostname makes sure that nothing else can appear.

Comment (vmuzikar) [reply services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java:89]: Ah, right, sorry for the noise.

**Review by vmuzikar — APPROVED** [review]
