### PR TITLE
use array instead of first

### LINKED ISSUE #19638: Custom User Storage Provider doesn't look up users after saving changes
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

When using a custom user provider and configuring it, everything works as expected.
I am able to log in with users from this federation and I can see them in the 'Users' tab.

After trying to edit the provider (User federation -> Provider details) and saving changes, the provider no longer works as expected. (It is enough to 'fake' the changes - delete a single letter and revert - then save)

- I can still see the logs from the UserStorageProviderFactory `getConfigProperties()` and `validateConfiguration()` methods implementations
- I can no longer see the logs from the factory `create()` method (which was visible and invoked before the changes)

This problem started occurring after upgrading from 18 to 21

Current workaround:

- delete the provider and configure it again
- disable and re-enable the provider (yes, this is enough for it to start working again)

I tried running KC with debug logs but can't see anything meaningful.
I do not see any problem with the plugin implementation (I was trying to check with the reference implementation: https://github.com/dasniko/keycloak-extensions-demo/tree/main/peanuts-userprovider)

### Version

21.0.1

### Expected behavior

Custom user provider still works as expected after saving changes.

### Actual behavior

The provider is fetching its configuration but is not invoked for searching the users.

### How to Reproduce?

- Keycloak extension for custom user provider
- configure a working example
- make changes to the configuration (or just fake changes) and save
- the keycloak doesn't invoke the implementation of the storage provider's `UserStorageProviderFactory` `create()` method
- after disabling and enabling the provider, everything should work again

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #19638

### CODE REVIEW

File: js/apps/admin-ui/src/user-federation/shared/Header.tsx [hunk 1]
```diff
@@ -99,7 +99,7 @@ export const Header = ({
                 if (!value) {
                   toggleDisableDialog();
                 } else {
-                  field.onChange(value.toString());
+                  field.onChange(`${value}`);
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user-federation/shared/Header.tsx:102]: Why can't we use `toString()` here?

**Review by jonkoops — DISMISSED** [review]

File: js/apps/admin-ui/src/user-federation/shared/Header.tsx (hunk 1 above)
Comment (edewit) [reply js/apps/admin-ui/src/user-federation/shared/Header.tsx:102]: we can, this is just shorter and `undefined / null ` proof

**Review by jonkoops — APPROVED** [review]
LGTM
