### PR TITLE
fix: refactor LightweightUserAdapter instantiation for DefaultTokenEx…

### LINKED ISSUE #28241: NPE on External OIDC to Internal Token Exchange when Transient Users feature is enabled
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Keycloak is unable to perform an External to Internal Token Exchange when the Identity Provider is configured not to store the users

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak was expected to return a new internal token after verifying the token with the external identity provider

### Actual behavior

NPE:

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-13) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.sessions.AuthenticationSessionModel.getParentSession()" because the return value of "org.keycloak.broker.provider.BrokeredIdentityContext.getAuthenticationSession()" is null
	at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.importUserFromExternalIdentity(DefaultTokenExchangeProvider.java:608)
	at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.exchangeExternalToken(DefaultTokenExchangeProvider.java:541)
	at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.tokenExchange(DefaultTokenExchangeProvider.java:165)
	at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.exchange(DefaultTokenExchangeProvider.java:131)
	at org.keycloak.protocol.oidc.grants.TokenExchangeGrantType.process(TokenExchangeGrantType.java:62)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:139)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### How to Reproduce?

* Start keycloak with `--features=preview,transient-users`
* Add a new OIDC Identity Provider 
** Configure Token Exchange permission
** Enable "Do not store users" on the Identity Provider's Advanced Settings
* Create a new Client with Token Exchange Permission

Execute the token exchange call:
```
curl --location 'http://localhost:8080/realms/master/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=SOME_CLIENT' \
--data-urlencode 'client_secret=some_password' \
--data-urlencode 'subject_token=this is my secret' \
--data-urlencode 'subject_issuer=identityProviderAliasHere' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:token-exchange' \
--data-urlencode 'subject_token_type=urn:ietf:params:oauth:token-type:access_token'
```

### Anything else?

This is related to pull request https://github.com/keycloak/keycloak/pull/24542

### PR DESCRIPTION
**Pull request by nbaiocco**
Avoid NullPointerException during external to internal token-exchange iff transient user is enabled. Modified LightweightUserAdapter instantiation to include the realm parameter to avoid NullPointerException in org.keycloak.storage.adapter.AbstractInMemoryUserAdapter#getGroupsStream.

Closes #28241

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java [hunk 1]
```diff
@@ -630,7 +630,7 @@ protected UserModel importUserFromExternalIdentity(BrokeredIdentityContext conte
             }
 
             if (context.getIdpConfig().isTransientUsers()) {
-                user = new LightweightUserAdapter(session, context.getAuthenticationSession().getParentSession().getId());
+                user = new LightweightUserAdapter(session, realm);
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java:633]:
```suggestion
                user = new LightweightUserAdapter(session, realm, context.getAuthenticationSession().getParentSession().getId());
```

Is it possible to use that one above instead of generated ID? Or any particular reason why ID needs to be changed to be generated?

If you change this way, you can also remove constructor with signature `public LightweightUserAdapter(KeycloakSession session, RealmModel realm)` as it would not used.

**Review by mposolda — COMMENTED** [review]
@nbaiocco Thanks for the PR, one small suggestion added

File: services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java (hunk 1 above)
Comment (nbaiocco) [reply services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java:633]: As mentioned in #28241, the NullPointerException is caused by context.getAuthenticationSession() == null, for this reason, I removed that part. 
If you believe this removal is incorrect, I can investigate further to understand why context.getAuthenticationSession() of BrokeredIdentityContext is null.

In my tests, both context.getAuthenticationSession() and context.getBrokerSessionId() (of BrokeredIdentityContext) consistently return null.

Comment (nbaiocco) [reply services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java]: Ok, I applied your suggestions in the second commit. 
It is slightly different, but it ensures the NullPointerException is avoided in cases where the parent session is empty.

**Review by mposolda — APPROVED** [review]
@nbaiocco Thanks!

**Review by mposolda — APPROVED** [review]
