### PR TITLE
fix: updating export option text

### LINKED ISSUE #42011: users-per-file option should no longer mention exponential runtime increases
### Description

users-per-file option still have the legacy text

### PR DESCRIPTION
**Pull request by shawkins**
closes: #42011

### CODE REVIEW

File: quarkus/config-api/src/main/java/org/keycloak/config/ExportOptions.java [hunk 1]
```diff
@@ -21,7 +21,7 @@ public class ExportOptions {
 
     public static final Option<String> FILE = new OptionBuilder<>("file", String.class)
             .category(OptionCategory.EXPORT)
-            .description("Set the path to a file that will be created with the exported data. To export more than 500 users, export to a directory with different files instead.")
+            .description("Set the path to a file that will be created with the exported data. To export more than 50000 users, export to a directory with different files instead.")
```
Comment (mabartos) [inline quarkus/config-api/src/main/java/org/keycloak/config/ExportOptions.java:24]: Are we confident to claim/recommend the 50k users?

**Review by mabartos — APPROVED** [review]
@shawkins Thanks. LGTM, just one question.

File: quarkus/config-api/src/main/java/org/keycloak/config/ExportOptions.java (hunk 1 above)
Comment (shawkins) [reply quarkus/config-api/src/main/java/org/keycloak/config/ExportOptions.java:24]: That matches a change made to the main docs.

Comment (mabartos) [reply quarkus/config-api/src/main/java/org/keycloak/config/ExportOptions.java:24]: ok, thanks
