### PR TITLE
fix: limiting what fields are hashed to identify compatible update jobs

### LINKED ISSUE #41014: Operator auto update hash
We can remove anything that doesn't contribute to the Keycloak configuration.

The following fields can be ignored: 
* `instances`
* `startOptimized` - 90% sure it is fine to ignore it in the hash
* `imagePullSecrets`
* `ingressSpec`
* `truststores` - they are automatically mounted in the containers, so they have no use for the update job
* `resourceRequirements`
* `schedulingSpec`
* `bootstrapAdminSpec` - nothing happens if changed in a running cluster, right?
* `networkPolicySpec`
* `updateSpec`
* `readinessProbeSpec`
* `livenessProbeSpec`
* `startupProbeSpec`

_Originally posted by @pruivo in https://github.com/keycloak/keycloak/issues/40985#issuecomment-3047998542_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #41014

### CODE REVIEW

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java [hunk 1]
```diff
@@ -218,8 +219,14 @@ private static List<String> replaceStartWithUpdateCommand(List<String> currentAr
...
-    private static String keycloakHash(Keycloak keycloak) {
-        return Utils.hash(List.of(keycloak.getSpec()));
+    static String keycloakHash(Keycloak keycloak) {
+        return Utils.hash(
+                List.of(new KeycloakSpecBuilder(keycloak.getSpec()).withInstances(null).withLivenessProbeSpec(null)
+                        .withHostnameSpec(null).withStartOptimized(null).withTracingSpec(null).withTruststores(null)
+                        .withHttpManagementSpec(null).withProxySpec(null).withStartupProbeSpec(null)
+                        .withReadinessProbeSpec(null).withResourceRequirements(null).withSchedulingSpec(null)
+                        .withBootstrapAdminSpec(null).withNetworkPolicySpec(null).withIngressSpec(null)
+                        .withImagePullSecrets().withImportSpec(null).withUpdateSpec(null).build()));
```
Comment (pruivo) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java]: The following spec may be ignored too:
* TransactionSpec
* ProxySpec

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java]: ProxySpec was already covered. Added TransactionSpec.

**Review by pruivo — DISMISSED** [review]
LGTM! Thank you.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceMonitorDependentResource.java [hunk 2]
```diff
@@ -46,6 +47,7 @@ protected ServiceMonitor desired(Keycloak primary, Context<Keycloak> context) {
               .withNewMetadata()
                 .withName(meta.getName())
                 .withNamespace(meta.getNamespace())
+                .withLabels(Utils.allInstanceLabels(primary))
```
Comment (shawkins) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceMonitorDependentResource.java:50]: @ryanemerson this appears to be missing from the original servicemonitor pr. It showed up in some test failure here that creating the servicemonitor was failing because it already existed.

Let me know if you want this in a different pr.

Comment (ryanemerson) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceMonitorDependentResource.java:50]: Happy for it to be fixed in this PR, thanks.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java [hunk 3]
```diff
@@ -218,8 +219,15 @@ private static List<String> replaceStartWithUpdateCommand(List<String> currentAr
...
-    private static String keycloakHash(Keycloak keycloak) {
-        return Utils.hash(List.of(keycloak.getSpec()));
+    static String keycloakHash(Keycloak keycloak) {
+        return Utils.hash(
+                List.of(new KeycloakSpecBuilder(keycloak.getSpec()).withInstances(null).withLivenessProbeSpec(null)
+                        .withHostnameSpec(null).withStartOptimized(null).withTracingSpec(null).withTruststores(null)
+                        .withHttpManagementSpec(null).withProxySpec(null).withStartupProbeSpec(null)
+                        .withReadinessProbeSpec(null).withResourceRequirements(null).withSchedulingSpec(null)
+                        .withBootstrapAdminSpec(null).withNetworkPolicySpec(null).withIngressSpec(null)
+                        .withImagePullSecrets().withImportSpec(null).withUpdateSpec(null).withTransactionsSpec(null)
```
Comment (ryanemerson) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java]: I think we can also exclude the ServiceMonitor spec here

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java]: Thanks @ryanemerson, updated.

**Review by ryanemerson — DISMISSED** [review]

**Comment by ryanemerson** [comment]
LGTM, thanks @shawkins

**Review by pruivo — DISMISSED** [review]

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java (hunk 3 above)
Comment (vmuzikar) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java]: Are we sure to exclude some server affecting specs Hostname, Proxy, ...? What if, at some point, it requires the update decision logic? This will be hard to track and maintain.

File: .github/workflows/ci.yml [hunk 4]
```diff
@@ -104,7 +104,9 @@ jobs:
           SEP=""
           PROJECTS=""
           for i in `find -name '*Test.java' -type f | egrep -v './(testsuite|quarkus|docs|tests|test-framework)/' | sed 's|/src/test/java/.*||' | sort | uniq | sed 's|./||'`; do
-            PROJECTS="$PROJECTS$SEP$i"
+            if [ $i != "operator" ]; then
```
Comment (vmuzikar) [inline .github/workflows/ci.yml]: Shouldn't we handle this exclusion in the `egrep`?

**Comment by shawkins** [comment]
> Are we sure to exclude some server affecting specs Hostname, Proxy, ...? What if, at some point, it requires the update decision logic? This will be hard to track and maintain.

There are really two different levels of update consideration here. update-compatibility is focused on things like keycloak version, database, infinispan, and feature compability - all build time / image concerns.

There are however obviously things you can do to runtime options that will not mesh well with other running instances - but we've always simply rolled in those changes. Are you suggesting that we'll expand the update-compatibility logic to consider changes in runtime options, or are you thinking that we'll eventually have build time options in some of these specs that the update compatibility logic will be interested in?

File: .github/workflows/ci.yml (hunk 4 above)
Comment (shawkins) [reply .github/workflows/ci.yml]: Ok, moved it there.

**Comment by vmuzikar** [comment]
> Are you suggesting that we'll expand the update-compatibility logic to consider changes in runtime options, or are you thinking that we'll eventually have build time options in some of these specs that the update compatibility logic will be interested in?

Both, actually. My point was, we shouldn't have any "filtering logic" on the Operator level deciding what server options should be considered for the update logic, that needs to be exclusively in the server as the single source of truth.

**Comment by shawkins** [comment]
> Both, actually. My point was, we shouldn't have any "filtering logic" on the Operator level deciding what server options should be considered for the update logic, that needs to be exclusively in the server as the single source of truth.

The initial motivation for the change was to remove the most likely operator side modification - which is instances because that could be due to hpa - from this hash. I can change it to be just operator related fields, but in general what you are concerned with wrt to the update-compatibility logic would be quite an undertaking.

And just to clarify this isn't filtering - this is just for computing a hash to confirm if the current update job is associated with the given Keycloak instance.

**Comment by pruivo** [comment]
Honestly, I'm a bit torn. @vmuzikar has a point; changing the HTTPS port, for example, should invalidate the update job. But there are attributes in there that make no sense to be hashed, like annotations and labels. 
I don't think the `update-compatibility` cares abort ports at all. And we definitely aren't going to bring a cluster down to change the port; we will do a rolling update. 

I think it is safe to ignore the HttpSpec from the hashing.

**Comment by shawkins** [comment]
> Honestly, I'm a bit torn. @vmuzikar has a point; changing the HTTPS port, for example, should invalidate the update job.

Just to make sure we're all on the same page, the sequence of events here is:
- an initial change comes into the Keycloak CR and triggers the update job logic to run.
- before the update job finishes, there are additional reconciliations. 
 
If there have been additional changes to the Keycloak CR we either need to:
- determine if it's something we can ignore and let the current job complete (this pr).
- kill the job and start another reconciliation based upon the new Keycloak CR state.

Either way the additional changes are effective blocked from rolling in until either the job completes or we've determined that an update job isn't needed.

I know there's only a limited window of when it matters, but I would like to at least exclude changes in the instance count from restarting the job as that may not be something the admin is even directly changing. Any spec that touches the runtime has been removed from the PR.

**Comment by shawkins** [comment]
@vmuzikar if you still have misgivings about this pr after the latest change, I'll check the label changes in under a different issue so that can move forward.

**Review by pruivo — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks
