### PR TITLE
Fix realm import failure when OID4VCI credential-offer-create role exists

### LINKED ISSUE #44637: Fail to import the realm with OID4VCI enabled
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

- Export the realm `test` from the test `OID4VCSdJwtAuthorizationDetailsFlowTest` (After realm initialized, client scopes created etc)
- Try to import this realm into fresh Keycloak instance. It fails with the exception below (Caused by the role `credential-offer-create` ). We should doublecheck the related code to avoid similar issues... The built-in role `credential-offer-create` is probably created in the different stage than other built-in roles during realm import, which likely cause this issue:

```
2025-12-03 15:49:42,698 ERROR [org.keycloak.services.resources.admin.RealmsAdminResource] (executor-thread-11) Conflict detected: org.keycloak.models.ModelDuplicateException
	at org.keycloak.models.jpa.JpaRealmProvider.addRealmRole(JpaRealmProvider.java:252)
	at org.keycloak.storage.RoleStorageManager.addRealmRole(RoleStorageManager.java:128)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.addRealmRole(RealmCacheSession.java:716)
	at org.keycloak.models.jpa.RealmAdapter.addRole(RealmAdapter.java:902)
	at org.keycloak.models.utils.RepresentationToModel.createRole(RepresentationToModel.java:286)
	at org.keycloak.models.utils.RepresentationToModel.importRoles(RepresentationToModel.java:157)
	at org.keycloak.storage.datastore.DefaultExportImportManager.importRealm(DefaultExportImportManager.java:405)
	at org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:148)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:646)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:550)
	at org.keycloak.services.managers.RealmManagerProviderFactory.lambda$postInit$0(RealmManagerProviderFactory.java:54)
	at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:88)
	at org.keycloak.storage.ImportRealmFromRepresentationEvent.fire(ImportRealmFromRepresentationEvent.java:50)
	at org.keycloak.storage.datastore.DefaultExportImportManager.importRealm(DefaultExportImportManager.java:195)
	at org.keycloak.services.resources.admin.RealmsAdminResource.importRealm(RealmsAdminResource.java:162)
	at org.keycloak.services.resources.admin.RealmsAdminResource$quarkusrestinvoker$importRealm_37a293e60e353619b43f3749caba299f4851581f.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:183)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:645)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Version

nightly (from 2025-12-03)

### Regression

- [ ] The issue is a regression

### Expected behavior

Realm export/import works fine

### Actual behavior

Realm export/import fails

### How to Reproduce?

See the description

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Awambeng**
This PR modifies setupRealmDefaults() to check for credential-offer-create role in the realm representation before creating it during import. This prevents ModelDuplicateException when importing a realm that already contains the built-in OID4VCI role.

The fix follows the same pattern used for offline_access role handling:
- Added overloaded setupRealmDefaults() method that accepts optional RealmRepresentation parameter
- Check hasRealmRole() before creating credential-offer-create role
- Updated importRealm() to pass realm representation to setupRealmDefaults()
- Preserves backward compatibility for fresh realm creation

Added testRealmImportWithOID4VCICredentialOfferCreateRole() to verify that realm import succeeds when the role is present in exported JSON.

Closes #44637

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java [hunk 1]
```diff
@@ -320,6 +324,62 @@ public void testExportUserProfileConfig() throws IOException {
...
+        TestingExportImportResource exportImport = testingClient.testing().exportImport();
+        exportImport.setProvider(SingleFileExportProviderFactory.PROVIDER_ID);
+        exportImport.setAction(ExportImportConfig.ACTION_EXPORT);
+        exportImport.setRealmName(testRealmName);
+        String targetFilePath = exportImport.getExportImportTestDirectory() + File.separator + "oid4vci-realm-export.json";
+        exportImport.setFile(targetFilePath);
+        exportImport.runExport();
+        
+        // Verify the exported file contains the role
+        Map<String, RealmRepresentation> exportedRealms = ImportUtils.getRealmsFromStream(JsonSerialization.mapper, new FileInputStream(targetFilePath));
```
Comment (Captain-P-Goldfish) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java]: The FileInputStream is not getting closed by the method `ImportUtils.getRealmsFromStream`. You need to close it manually.

**Review by Captain-P-Goldfish — CHANGES_REQUESTED** [review]

**Comment by Awambeng** [comment]
@Captain-P-Goldfish Could you please check again?

**Review by Captain-P-Goldfish — APPROVED** [review]
LGTM

**Comment by mposolda** [comment]
@Awambeng @Captain-P-Goldfish Thanks for the PR and review! LGTM as well.

Is it please just possible to rebase with latest main just to doublecheck tests still work? I am not 100% sure if realm `oid4vci` switch is not needed as well now to be enabled (I think probably not needed, but rather want to be on safe side before merging PR with broken test :-) ).

**Comment by Awambeng** [comment]
> @Awambeng @Captain-P-Goldfish Thanks for the PR and review! LGTM as well.
> 
> Is it please just possible to rebase with latest main just to doublecheck tests still work? I am not 100% sure if realm `oid4vci` switch is not needed as well now to be enabled (I think probably not needed, but rather want to be on safe side before merging PR with broken test :-) ).

@mposolda Done.

**Comment by mposolda** [comment]
@Awambeng Thanks!

**Review by mposolda — APPROVED** [review]
