### PR TITLE
Make sure the customized Ingress resource isn't deleted when the Keycloak deployed by Operator is killed.

### LINKED ISSUE #14433: customized ingress resource is deleted as soon as a Keycloak pod is killed
### Describe the bug

As I've already seen in some discussions here in GitHub, it seems that it is not possible to customize the default ingress resource when deploying over the keycloak operator and e.g. pass a host with it.

For this reason I set "disableDefaultIngress: true" as described in the instructions and started my own Ingress.

So far so good and everything works as I imagined.
Unfortunately now the problem occurs that the ingress resource I created is automatically deleted as soon as a keycloak pod is killed.

Does anyone else have this problem and know how to solve it?

### Version

19.0.2

### Expected behavior

The ingress resource I created manually remains, regardless of whether a keycloak pod is deleted or not.

### Actual behavior

The ingress is delete

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andre-nascimento6791**
This change ensures that If the User set one customized Ingress resource, it won't be deleted when the Keycloak deployed by Operator is killed.

Closes #14433

### CODE REVIEW

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java [hunk 1]
```diff
@@ -188,4 +192,108 @@ public void testMainIngressDurability() {
                     assertThat(k8sclient.network().v1().ingresses().inNamespace(namespace).list().getItems().size()).isEqualTo(0);
                 });
     }
+
+    @Test
+    public void testCustomIngressDeletion() {
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:197]: I think this test can be significantly simplified. Something like:
1. Deploy custom ingress (without the owner reference but with the same name as if it was created by the Operator leveraging `Constants.KEYCLOAK_INGRESS_SUFFIX`).
2. Deploy Keycloak with ingress disabled.
3. Check if the custom ingress is not deleted.

File: operator/src/test/resources/custom-ingress-installed-manually.yml [hunk 2]
```diff
@@ -0,0 +1,41 @@
+apiVersion: networking.k8s.io/v1
```
Comment (vmuzikar) [inline operator/src/test/resources/custom-ingress-installed-manually.yml:1]: I think we don't need anything as complex as this. A new ingress could be created programatically, maybe even as simple as this:
```java
new IngressBuilder().withNewMetadata().withName("example-kc-ingress").endMetadata().build();
```

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@andre-nascimento-rh Thanks for the fix, added a few comments.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java (hunk 1 above)
Comment (andre-nascimento-rh) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:198]: Done!

Thanks.

File: operator/src/test/resources/custom-ingress-installed-manually.yml (hunk 2 above)
Comment (andre-nascimento-rh) [reply operator/src/test/resources/custom-ingress-installed-manually.yml]: Done!

Thanks.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java [hunk 3]
```diff
@@ -188,4 +193,87 @@ public void testMainIngressDurability() {
...
+                Log.info("Make sure the Custom Ingress still remains");
+                assertThat(k8sclient.network().v1().ingresses().inNamespace(namespace).list().getItems().size()).isEqualTo(1);
+            });
+
+            Log.info("Destroying the Custom Ingress created manually to avoid errors in others Tests methods");
+            assertThat(customIngressDeployedManuallySelector.delete()).isTrue();
+
+            Awaitility.await().untilAsserted(() -> {
+                assertThat(k8sclient.network().v1().ingresses().inNamespace(namespace).list().getItems().size()).isEqualTo(0);
+            });
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:243]: This should be in `finally` block in case something fails in this test.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java [hunk 4]
```diff
@@ -188,4 +193,87 @@ public void testMainIngressDurability() {
...
+                    .ingresses()
+                    .inNamespace(namespace)
+                    .withName(customIngressCreatedManually.getMetadata().getName());
+
+            Awaitility.await().atMost(1, MINUTES).untilAsserted(() -> {
+                assertThat(k8sclient.network().v1().ingresses().inNamespace(namespace).list().getItems().size()).isEqualTo(1);
+            });
+
+            // Delete Keycloak CR
+            Log.info("Deleting Keycloak CR and watching cleanup");
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:225]: We're not deleting any Keycloak CR here.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java [hunk 5]
```diff
@@ -188,4 +193,87 @@ public void testMainIngressDurability() {
                     assertThat(k8sclient.network().v1().ingresses().inNamespace(namespace).list().getItems().size()).isEqualTo(0);
                 });
     }
+
+    @Test
+    public void testCustomIngressDeletion() {
+
+        Keycloak defaultKeycloakDeployment;
+        Ingress customIngressCreatedManually;
+        String kcDeploymentName = "example-kc";
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:202]:
```suggestion
        Keycloak defaultKeycloakDeployment = K8sUtils.getDefaultKeycloakDeployment();
        Ingress customIngressCreatedManually;
        String kcDeploymentName = defaultKeycloakDeployment.getMetadata().getName();
```

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@andre-nascimento-rh Thanks for the update! Added a few more comments, we're getting there. 🙂

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java [hunk 6]
```diff
@@ -188,4 +193,87 @@ public void testMainIngressDurability() {
...
+            });
+
+            // Delete Keycloak CR
+            Log.info("Deleting Keycloak CR and watching cleanup");
+            defaultKeycloakDeployment = K8sUtils.getDefaultKeycloakDeployment();
+            defaultKeycloakDeployment.getSpec().setIngressSpec(new IngressSpec());
+            defaultKeycloakDeployment.getSpec().getIngressSpec().setIngressEnabled(false);
+
+            K8sUtils.deployKeycloak(k8sclient, defaultKeycloakDeployment, true);
+            K8sUtils.waitForKeycloakToBeReady(k8sclient, defaultKeycloakDeployment); // wait for reconciler to calm down to avoid race condititon
```
[the remark this answers is not in the document]
Comment (andre-nascimento-rh) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:231]: OK. Removed.

Done!

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java (hunk 3 above)
Comment (andre-nascimento-rh) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:243]: OK. Moved to ```finally``` block.

Done!

Thanks!

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java (hunk 5 above)
Comment (andre-nascimento-rh) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:202]: Nice suggestion. Accepted!

Thanks!

Done.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java [hunk 7]
```diff
@@ -188,4 +193,87 @@ public void testMainIngressDurability() {
...
+        Keycloak defaultKeycloakDeployment;
+        Ingress customIngressCreatedManually;
+        String kcDeploymentName = "example-kc";
+
+        try {
+
+            Awaitility.await().atMost(1, MINUTES).untilAsserted(() -> {
+                assertThat(k8sclient.apps().statefulSets().inNamespace(namespace).withName(kcDeploymentName).get()).isNull();
+                assertThat(k8sclient.network().v1().ingresses().inNamespace(namespace).list().getItems().size()).isEqualTo(0);
+            });
```
[the remark this answers is not in the document]
Comment (andre-nascimento-rh) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:209]: To make sure there isn't any remaining Ingress. But we assume there's nothing created before each method, right?

Then I removed those checkings.

Thanks.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java [hunk 8]
```diff
@@ -114,6 +115,22 @@ protected void deleteExistingIngress() {
         client.network().v1().ingresses().inNamespace(getNamespace()).delete(existingIngress);
     }
 
+    private boolean isExistingIngressFromSameOwnerReference() {
+
+        if ((Objects.nonNull(this.keycloak) && Objects.nonNull(this.keycloak.getMetadata().getUid())) &&
+            (Objects.nonNull(this.existingIngress) && Objects.nonNull(this.existingIngress.getMetadata().getOwnerReferences()))) {
```
[the remark this answers is not in the document]
Comment (andre-nascimento-rh) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java:121]: I only added this ```If``` because the error below happens in this other test:

`
org.opentest4j.AssertionFailedError: 
Expected :true
Actual   :false
<Click to see difference>
        ...
	at org.keycloak.operator.testsuite.unit.IngressLogicTest.testIngressDisabledExisting(IngressLogicTest.java:99)
        ...
`

The `deleteExistingIngress()` method must run for that the `IngressLogicTest.testIngressDisabledExisting()` can perform successfully.

When running the `IngressLogicTest.testIngressDisabledExisting()`, it is created a Mocked Ingress with its `Metadata` as `null`. And yet still the `deleteExistingIngress()` method must be run.

So I'm gonna keep that `If` to have all tests passing OK.

WDYT, @vmuzikar ?

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java [hunk 9]
```diff
@@ -114,6 +115,22 @@ protected void deleteExistingIngress() {
...
+
+            return existingIngress
+                    .getMetadata()
+                    .getOwnerReferences()
+                    .stream()
+                    .anyMatch(oneOwnerRef -> oneOwnerRef.getUid().equalsIgnoreCase(keycloak.getMetadata().getUid()));
+
+        }
+
+        return true;
```
[the remark this answers is not in the document]
Comment (andre-nascimento-rh) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java:131]: See the comment above.
Thanks.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (andre-nascimento-rh) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java:121]: I only added this ```If``` because the error below happens in this other test:

`
org.opentest4j.AssertionFailedError: 
Expected :true
Actual   :false
<Click to see difference>
        ...
	at org.keycloak.operator.testsuite.unit.IngressLogicTest.testIngressDisabledExisting(IngressLogicTest.java:99)
        ...
`

The `deleteExistingIngress()` method must run for that the `IngressLogicTest.testIngressDisabledExisting()` can perform successfully.

When running the `IngressLogicTest.testIngressDisabledExisting()`, it is created a Mocked Ingress with its `Metadata` as `null`. And yet still the `deleteExistingIngress()` method must be run.

So I'm gonna keep that `If` to have all tests passing OK.

WDYT, @vmuzikar ?

[the remark this answers is not in the document]
Comment (vmuzikar) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java:121]: I would fix the `testIngressDisabledExisting` to add (empty) metadata. In real-life scenarios, we can expect the metadata for existing Ingress are there. Otherwise, something's wrong and the reconciliation should fail.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java [hunk 10]
```diff
@@ -188,4 +193,81 @@ public void testMainIngressDurability() {
...
+                    .ingresses()
+                    .inNamespace(namespace)
+                    .withName(customIngressCreatedManually.getMetadata().getName());
+
+            Awaitility.await().atMost(1, MINUTES).untilAsserted(() -> {
+                assertThat(k8sclient.network().v1().ingresses().inNamespace(namespace).list().getItems().size()).isEqualTo(1);
+            });
+
+            Log.info("Redeploying the Keycloak CR with default Ingress disabled");
+            defaultKeycloakDeployment = K8sUtils.getDefaultKeycloakDeployment();
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:221]: Just a non-blocking nitpick. We don't need it as this variable is already assigned here:
https://github.com/keycloak/keycloak/blob/89586ebaf4b6ace35d3b9f376975f67095ee5bc2/operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java#L200

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java [hunk 11]
```diff
@@ -188,4 +193,81 @@ public void testMainIngressDurability() {
...
+                Log.info("Make sure the Custom Ingress still remains");
+                assertThat(k8sclient.network().v1().ingresses().inNamespace(namespace).list().getItems().size()).isEqualTo(1);
+            });
+
+        } catch (Exception e) {
+            savePodLogs();
+            throw e;
+        } finally {
+            Log.info("Destroying the Custom Ingress created manually to avoid errors in others Tests methods");
+            assertThat(customIngressDeployedManuallySelector).isNotNull();
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:237]: Did you mean this?
```suggestion
            assertThat(customIngressDeployedManuallySelector.get()).isNotNull();
```

**Review by vmuzikar — CHANGES_REQUESTED** [review]

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java (hunk 11 above)
Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java:237]: Actually, nevermind. There an `if` for null-check instead. Otherwise the following line will fail if `customIngressDeployedManuallySelector == null`.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java (hunk 10 above)
Comment (andre-nascimento-rh) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java]: Removed.

Thanks.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java (hunk 11 above)
Comment (andre-nascimento-rh) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java]: Done!

Thanks.

**Comment by andre-nascimento-rh** [comment]
The recommended changes were done.

Thanks, @vmuzikar.

**Review by vmuzikar — APPROVED** [review]
@andre-nascimento-rh Thanks for the update, LGTM!
