### PR TITLE
Correct unique constraints for UserConsent entity

### LINKED ISSUE #13045: Duplicated user consents
### Describe the bug

In some cases the consent of users for SAML clients is duplicated in the database, which throws the following exception when users try to log in:
```
2022-07-11 22:28:07,534 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1570) Uncaught server error: org.keycloak.models.ModelException: More results found for user [789ee841-0966-4d9d-aabb-d513133b138a] and client [2847d11d-7dcb-4697-a4fe-232e089c3bb7]
	at org.keycloak.models.jpa.JpaUserProvider.getGrantedConsentEntity(JpaUserProvider.java:280)
	at org.keycloak.models.jpa.JpaUserProvider.updateConsent(JpaUserProvider.java:248)
	at org.keycloak.storage.UserStorageManager.updateConsent(UserStorageManager.java:594)
	at org.keycloak.models.cache.infinispan.UserCacheSession.updateConsent(UserCacheSession.java:653)
	at org.keycloak.services.resources.LoginActionsService.processConsent(LoginActionsService.java:918)
	at jdk.internal.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The database entry then looks like this:
```
keycloak=# SELECT * FROM user_consent WHERE user_id='e052733f-3106-4030-a833-029a0666e784';
                  id                  |              client_id               |               user_id                | created_date  | last_updated_date | client_storage_provider | external_client_id 
--------------------------------------+--------------------------------------+--------------------------------------+---------------+-------------------+-------------------------+--------------------
[...]
 73c06e73-8bb2-4d81-acaf-397dac52916e | 2847d11d-7dcb-4697-a4fe-232e089c3bb7 | 789ee841-0966-4d9d-aabb-d513133b138a | 1657267613443 |     1657267613455 |                         | 
 6a63b4c2-4968-4ff0-8864-e9b021d58aec | 2847d11d-7dcb-4697-a4fe-232e089c3bb7 | 789ee841-0966-4d9d-aabb-d513133b138a | 1657267610788 |     1657267610790 |                         | 
```

I usually remove both entries from the database (tables user_consent and user_consent_client_scope) and the users are then able to successfully log in.

### Version

18.0.2

### Expected behavior

There should be no redundant database entries for the same consent.

### Actual behavior

In some cases (not sure how to reproduce) the entries are doubled.

### How to Reproduce?

_No response_

### Anything else?

I think the table user_consent should get a uniqe constraint for the tuple (client_id, user_id).

### PR DESCRIPTION
**Pull request by cgeorgilakis**
Closes #13045

As we see in the following code (class`JpaUserProvider` , method `addConsent`) : 

```
 if (clientStorageId.isLocal()) {
            consentEntity.setClientId(clientId);
        } else {
            consentEntity.setClientStorageProvider(clientStorageId.getProviderId());
            consentEntity.setExternalClientId(clientStorageId.getExternalId());
        }

```
Unique constraint in a database is not working if one - or more - field is null. So we propose to delete old one and create two appropriate unique constraints.
I also propose to delete the check in the  method `addConsent` of class `JpaUserProvider`. This check must be done in database, no need for twice check.

### CODE REVIEW

**Comment by cgeorgilakis** [comment]
Adding unique indexes will be failed for Keycloak instances with already duplicate entries.
We have two possible solution for adding in liquibase before changing unique constraints:

- Delete all duplicate consents
- Delete newer consent for duplicate consents

What Keycloak team believe that we should do?

**Comment by svenseeberg** [comment]
What would happen during a migration if duplicate keys are present? Keycloak would fail to start?

**Comment by cgeorgilakis** [comment]
> What would happen during a migration if duplicate keys are present? Keycloak would fail to start?

That's why I am asking Keycloak team for the way to solve possible duplicate entries problem: 

> We have two possible solution for adding in liquibase before changing unique constraints:
>- Delete all duplicate consents
>- Delete newer consent for duplicate consents

I believe the second is the ideal.

**Comment by sguilhen** [comment]
@hmlnarik I've requested your review for this - the current constraint is not enough to prevent duplicate consents (see associated issue). The problem is that reworking the constraint as proposed here will cause migration failures for those who already have duplicate records in their DBs, so some previous action must be taken to eliminate duplicates before attempting to change the constraints.

**Comment by cgeorgilakis** [comment]
I have rebased in current main.

Moreover based on our discussion in [github issue](https://github.com/keycloak/keycloak/issues/13045), during migration Keycloak will delete newer consent for duplicate consents.
MySQL is different database. So SQL script need to create temporary table and delete it after.
Oracle seems to work with current unique constraints. If I am not wrong, it is the only SQL database that checks null values in unique contraint. If you add new two unique constraints, tests will be failed in Oracle.
The code has been chacked with postegreSQL database with duplicate instances.
Could you review it now? @sguilhen?

File: model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java [hunk 1]
```diff
@@ -208,15 +208,10 @@ public void preRemove(RealmModel realm, IdentityProviderModel provider) {
     @Override
     public void addConsent(RealmModel realm, String userId, UserConsentModel consent) {
         String clientId = consent.getClient().getId();
-
-        UserConsentEntity consentEntity = getGrantedConsentEntity(userId, clientId, LockModeType.NONE);
-        if (consentEntity != null) {
-            throw new ModelDuplicateException("Consent already exists for client [" + clientId + "] and user [" + userId + "]");
-        }
-
```
Comment (sguilhen) [inline model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java:216]: I am personally not in favor to remove this check, and the reason is that we have similar checks in many other providers. If we decide to go down this route of relying solely on the DB constraints it would call for a broader change in all the providers.

File: model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml [hunk 2]
```diff
@@ -50,4 +50,149 @@
...
+            DELETE FROM USER_CONSENT
+            WHERE ID IN (SELECT ID FROM TEMP_USER_CONSENT_IDS2);
+
+            DROP TEMPORARY TABLE IF EXISTS TEMP_USER_CONSENT_IDS2;
+        </sql>
+        <dropUniqueConstraint tableName="USER_CONSENT" constraintName="UK_JKUWUVD56ONTGSUHOGM8UEWRT"/>
+        <addUniqueConstraint columnNames="CLIENT_ID, USER_ID" constraintName="UK_LOCAL_CONSENT" tableName="USER_CONSENT"/>
+        <addUniqueConstraint columnNames="CLIENT_STORAGE_PROVIDER, EXTERNAL_CLIENT_ID, USER_ID" constraintName="UK_EXTERNAL_CONSENT" tableName="USER_CONSENT"/>
+    </changeSet>
+
```
Comment (sguilhen) [inline model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml:197]: In Keycloak we have avoided the explicit SQL statements in the changesets, and instead we use custom changes like the one in [this PR](https://github.com/keycloak/keycloak/commit/e49dfe534e979db7f401021b7e2bb7d8c4c7cd73#diff-79a74c9de3a029d446c502274e5709f364a0787cc507183cfeed84d86b466cf6) -  for consistency I would use the same approach here.

**Review by sguilhen — CHANGES_REQUESTED** [review]
Hi @cgeorgilakis. I've added a couple of points I think are worth revisiting. In addition, we need to ensure this change also works for Microsoft SQL Server.

I've also requested a review from @vramik to see if I'm not missing anything.

File: model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java (hunk 1 above)
Comment (cgeorgilakis) [reply model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java:216]: > I am personally not in favor to remove this check, and the reason is that we have similar checks in many other providers. If we decide to go down this route of relying solely on the DB constraints it would call for a broader change in all the providers.

I do not like double checks for the same thing. If you think that it is not a performance problem, I will add it back.

File: model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml (hunk 2 above)
Comment (cgeorgilakis) [reply model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml:197]: > In Keycloak we have avoided the explicit SQL statements in the changesets, and instead we use custom changes like the one in [this PR](https://github.com/keycloak/keycloak/commit/e49dfe534e979db7f401021b7e2bb7d8c4c7cd73#diff-79a74c9de3a029d446c502274e5709f364a0787cc507183cfeed84d86b466cf6) - for consistency I would use the same approach here.

Ok, I will check it and will make appropriate changes if possible.

Comment (cgeorgilakis) [reply model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml]: I have migrate SQL statements to Java class extends CustomKeycloakTask.

**Comment by cgeorgilakis** [comment]
> Hi @cgeorgilakis. I've added a couple of points I think are worth revisiting. In addition, we need to ensure this change also works for Microsoft SQL Server.
> 
> I've also requested a review from @vramik to see if I'm not missing anything.

Microsoft SQL Server seems to work as Oracle database supporting NULL values in unique constraints.
One the other hand, unique constraints in PostgreSQL, MariaDB, MySQL take into account only entries with not NULL values.

**Review by vramik — COMMENTED** [review]
@cgeorgilakis thank you for preparing the PR. 

@sguilhen I went through it and the code seems good to me. I didn't test the solution locally with different databases. 

I've spotted only a minor thing. New classes `JpaUpdate25*` don't contain copyright message.

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis thank you for preparing the PR.
> 
> @sguilhen I went through it and the code seems good to me. I didn't test the solution locally with different databases.
> 
> I've spotted only a minor thing. New classes `JpaUpdate25*` don't contain copyright message.

I have added them.

**Comment by sguilhen** [comment]
@cgeorgilakis one final comment that might simplify the whole thing a little bit for your consideration. Instead of two separate custom changes, you can combine them in a single change and use the `database` from `CustomKeycloakTask` to differentiate the sql statements that have to be generated. Something like

```java
    protected void generateStatementsImpl() throws CustomChangeException {
        if (super.database instanceof MariaDBDatabase || super.database instanceof PostgresDatabase) {
            generateStatementsPGMariaDB();
        } else if (super.database instanceof MySQLDatabase) {
            generateStatementsMySQL();
        }
    }
    
    protected void generateStatementsPGMariaDB() throws CustomChangeException {
        // PG / MariaDB statements go here
    }
    
    protected void generateStatementsMySQL() throws CustomChangeException {
        // MySQL statements go here
    }
```

Then the changeset can be adjusted to no longer have pre conditions that check the DB type, and instead simply call the custom change and then adjusts the index (drop current and add the two new indexes). WDYT?

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis one final comment that might simplify the whole thing a little bit for your consideration. Instead of two separate custom changes, you can combine them in a single change and use the `database` from `CustomKeycloakTask` to differentiate the sql statements that have to be generated. Something like
> 
> ```java
>     protected void generateStatementsImpl() throws CustomChangeException {
>         if (super.database instanceof MariaDBDatabase || super.database instanceof PostgresDatabase) {
>             generateStatementsPGMariaDB();
>         } else if (super.database instanceof MySQLDatabase) {
>             generateStatementsMySQL();
>         }
>     }
>     
>     protected void generateStatementsPGMariaDB() throws CustomChangeException {
>         // PG / MariaDB statements go here
>     }
>     
>     protected void generateStatementsMySQL() throws CustomChangeException {
>         // MySQL statements go here
>     }
> ```
> 
> Then the changeset can be adjusted to no longer have pre conditions that check the DB type, and instead simply call the custom change and then adjusts the index (drop current and add the two new indexes). WDYT?

The problem with this is that no changes are needed for Microsoft SQL Server and Oracle. So, add/ drop unique Constraint need to be in JpaUpdate25_0_0_ConsentConstraints . Is this change needed?

**Comment by sguilhen** [comment]
> The problem with this is that no changes are needed for Microsoft SQL Server and Oracle. So, add/ drop unique Constraint need to be in JpaUpdate25_0_0_ConsentConstraints . Is this change needed?

Good point. Lets leave it as is then.

@ahus1 The PR looks good to me, @vramik also reviewed. If you could take one final look/merge it would be great.

**Review by sguilhen — APPROVED** [review]

**Comment by ahus1** [comment]
Unfortunately there are now conflicts for the JPA changelog, please resolve them.

 Something I worry about a bit: when creating the SQL statements, I am not sure if they contain a schema name, which might be used for MySQL databases. Please double-check. If you think we are fine, I'm ok to go ahead and merge.

**Comment by vramik** [comment]
@ahus1 thank you for looking into it. As far as I'm aware there is schema correctly handled within https://github.com/keycloak/keycloak/blob/d61b1ddb09c5d1396633504c7dbb0ccdc91b3f8a/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java#L313-L315

which is called from https://github.com/keycloak/keycloak/blob/d61b1ddb09c5d1396633504c7dbb0ccdc91b3f8a/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomKeycloakTask.java#L132

Does that address your concern?

**Comment by ahus1** [comment]
@vramik - thank you, yes, this resolves it for me.

**Review by ahus1 — APPROVED** [review]
Approving based on @sguilhen's previous review. Thanks!
