### PR TITLE
[FGAP] Refactor permission evaluation code for V2

### LINKED ISSUE #38086: [FGAP] Refactor permission evaluation code for V2
Something like following class might be one option
```java
class PermissionEvaluator {

    private final KeycloakSession session;
    private final MgmtPermissions root;
    private final ResourceStore resourceStore;
    private final PolicyStore policyStore;

    PermissionEvaluator(KeycloakSession session, MgmtPermissions root, ResourceStore resourceStore, PolicyStore policyStore) {
        this.session = session;
        this.resourceStore = resourceStore;
        this.root = root;
        this.policyStore = policyStore;
    }
    
    <T> boolean hasPermission(T model, String resourceType, EvaluationContext context, String... scopes) {
        if (!root.isAdminSameRealm()) {
            return false;
        }

        ResourceServer server = root.realmResourceServer();

        if (server == null) {
            return false;
        }

        String modelId = getModelId(model);
        Resource resource = modelId == null ? null : resourceStore.findByName(server, modelId);

        if (resource == null) {
            resource = AdminPermissionsSchema.SCHEMA.getResourceTypeResource(session, server, resourceType);

            // check if there is a permission for "all-resources". If so, proceed with the evaluation to check scopes
            if (policyStore.findByResource(server, resource).isEmpty()) {
                return false;
            }
        }

        Collection<Permission> permissions = root.evaluatePermission(new ResourcePermission(resource, resource.getScopes(), server), server);

        List<String> expectedScopes = Arrays.asList(scopes);

        for (Permission permission : permissions) {
            for (String scope : permission.getScopes()) {
                if (expectedScopes.contains(scope)) {
                    return true;
                }
            }
        }

        return false;
    }

    private String getModelId(Object model) {
        if (model == null) return null;
        if (model instanceof UserModel user) {
            return user.getId();
        } else if (model instanceof GroupModel group) {
            return group.getId();
        } else if (model instanceof Resource resource) {
            return resource.getId();
        }
        throw new IllegalArgumentException("Unsupported model type: " + model.getClass().getName());
    }
}
```

### PR DESCRIPTION
**Pull request by vramik**
Closes #38086

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissionsV2.java [hunk 1]
```diff
@@ -109,78 +100,16 @@ public boolean canManageMembership(GroupModel group) {
             return true;
         }
 
-        return hasPermission(group.getId(), AdminPermissionsSchema.MANAGE_MEMBERSHIP);
+        return eval.hasPermission(new GroupModelRecord(group), null, AdminPermissionsSchema.MANAGE_MEMBERSHIP);
     }
 
     @Override
     public Set<String> getGroupIdsWithViewPermission() {
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissionsV2.java:107]: We can just make this a no-op method, given that it is not used at all when using FGAP v2?

File: services/src/main/java/org/keycloak/services/resources/admin/permissions/ModelRecord.java [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+ */
+package org.keycloak.services.resources.admin.permissions;
+
+import org.keycloak.authorization.AdminPermissionsSchema;
+import org.keycloak.models.ClientModel;
+import org.keycloak.models.GroupModel;
+import org.keycloak.models.RoleModel;
+import org.keycloak.models.UserModel;
+
+sealed interface ModelRecord {
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/permissions/ModelRecord.java:25]: I would vote for having separate implementations of a `ResourceType` interface and better encapsulating the specific behaviors/state of each resource type.

Let's sync about this one, and depending on what we decide, we can do it as a follow-up.

Comment (vramik) [reply services/src/main/java/org/keycloak/services/resources/admin/permissions/ModelRecord.java:25]: Will be done as follow-up

**Review by pedroigor — APPROVED** [review]
