### PR TITLE
fix: removal of resteasy-core

### LINKED ISSUE #26315: Fully remove reasteasy-core
### Description

With upgrading to 3.6/3.7 #26150, continued usage of resteasy-core is becoming more problematic. In particular we need to rewrite  logic dealing with the ResteasyContext.

### PR DESCRIPTION
**Pull request by shawkins**
Removes resteasy-core from usage in the quarkus distribution. Allows for the dual stack workaround to be removed. In some places we still do need a dependency on resteasy-core-spi. The context logic seems like it can be replaced by our own usage of a threadlocal.

There is still usage of resteasy-core in the tests. It's also mentioned in the admin-cli shading - which seems like it could also be removed either now or later (it may mean that we'll have to add things that were covered transitively that are not covered by resteasy-client)

closes #26315

cc @vmuzikar @mabartos @geoand

### CODE REVIEW

**Comment by geoand** [comment]
🥳

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/ResteasyVertxProvider.java [hunk 1]
```diff
@@ -20,16 +20,24 @@
...
 
 public class ResteasyVertxProvider implements ResteasyProvider {
 
+    private static final ThreadLocal<Map<Class<?>, Object>> contextualData = new ThreadLocal<Map<Class<?>, Object>>() {
+        @Override
+        protected Map<Class<?>, Object> initialValue() {
+            return new HashMap<>();
+        };
+    };
+
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/ResteasyVertxProvider.java:37]: I see that's the almost identical impl as provided by ResteasyContext, instead of the ThreadLocalStack, but it's not necessary. LGTM

**Review by mabartos — APPROVED** [review]
@shawkins Nice work! LGTM

**Review by vmuzikar — APPROVED** [review]
@shawkins LGTM. Nice job, thanks.
