### PR TITLE
fix: adds a way to expose health endpoints on the main interface

### LINKED ISSUE #41303: Allow for health check on main interface
### Description

The previous draft pr that added just a local health check on the main interface does not satisfy https://github.com/keycloak/keycloak/discussions/37287

We have two options:
- undeprecate the legacy management interface option: https://github.com/shawkins/keycloak/tree/legacy_observe
- narrowly, and optionally, add a readiness check to the main interface: https://github.com/shawkins/keycloak/tree/iss39506 - still just a draft
  - In it's current state the branch would also need to document the same percaution as undeprecating the legacy management interface about blocking access to /health. The only way to build in a restriction of traffic here seems to be to require non-proxied http access. We cannot restrict to localhost as that will not work for https://github.com/keycloak/keycloak/discussions/37287

@mabartos @vmuzikar It's a smaller change to just undeprecate the legacy option, are you good with doing something like that? Or do you want to explore more adding limited health checks on the main interface - the additional advantage here is that it leaves rest of the management access as is.

### Discussion

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #41303

Reopening the previous pull request as a new one since there was a lot of now out-dated content on the pr.

This adds an option for /health/ready on main - we can easily add all the /health endpoints though.

### CODE REVIEW

File: quarkus/config-api/src/main/java/org/keycloak/config/HealthOptions.java [hunk 1]
```diff
@@ -4,7 +4,14 @@ public class HealthOptions {
...
             .category(OptionCategory.HEALTH)
-            .description("If the server should expose health check endpoints. If enabled, health checks are available at the '/health', '/health/ready' and '/health/live' endpoints.")
+            .description("If the server should expose health check endpoints. If enabled, health checks are available at the '/health', '/health/ready', '/health/live', and '/health/started' endpoints.")
+            .defaultValue(Boolean.FALSE)
+            .buildTime(true)
+            .build();
+
+    public static final Option<Boolean> HEALTH_ON_MAIN = new OptionBuilder<>("health-on-main", Boolean.class)
+            .category(OptionCategory.HEALTH)
+            .description("If the server should expose health checks om amain. If enabled, health checks are available at the '/health/ready' endpoint on the main interface.")
```
Comment (vit-zikmund) [inline quarkus/config-api/src/main/java/org/keycloak/config/HealthOptions.java]: Hello @shawkins, just cruising by, watching this heroic effort unfold, I dare to leave with a question:
Why export only the `/health/ready` endpoint and not the usual `/health/*` bunch? I see `/ready` has been primarily requested by some users, but wouldn't it make sense to stay consistent both on main and the management port? I'd vote for consistency here.

Although, if there's yet another security concern (not already tackled by the "proxy warning") about adding the rest of the `/health` sub-routes (I fail to see it :thinking:), the option name should perhaps better reflect that (e.g. `health-ready-on-main`).

OT, there's also a typo in the description :wink:

Comment (shawkins) [reply quarkus/config-api/src/main/java/org/keycloak/config/HealthOptions.java]: > Why export only the /health/ready endpoint and not the usual /health/* bunch? I see /ready has been primarily requested by some users, but wouldn't it make sense to stay consistent both on main and the management port? I'd vote for consistency here.

I don't have a strong opinion. The draft is to cover the minimum. As mentioned in the initial pr comment we can easily add everything. The only concern with doing that is we'll be on the hook for maintaining consistency - if new health endpoints should be added later, we'll need to add those on our side as well.

> Although, if there's yet another security concern (not already tackled by the "proxy warning") about adding the rest of the /health sub-routes (I fail to see it 🤔)

Something brought up elsewhere is that we can use start using a single prefix for anything added to the main interface - like /insecure/health... so that it would be even easier to block traffic.

> the option name should perhaps better reflect that (e.g. health-ready-on-main).

That is also possible, we'll just need more feedback on the direction first.

> OT, there's also a typo in the description 

Thanks, I'll clean this up before it gets out of draft.

**Review by vmuzikar — COMMENTED** [review]
See https://github.com/keycloak/keycloak/pull/41733#issuecomment-3189500584

**Comment by shawkins** [comment]
Took another pass at this and noticed there is already a quakus option to control putting the entire set of health checks on main. So rather than trying to duplicate the endpoints on both interfaces, we'll just expose this option.

Not mentioned in the doc changes is that you cannot disable this option when using the operator - as the probes will no longer work. I believe we probably need another issue under #39506 to address this (could be a doc change or we can add logic for scanning the additional options). There are other lingering operator considerations, such as if you use passthrough or reencrypt and require mTLS then the probes may not work either.

**Review by ryanemerson — DISMISSED** [review]
> Not mentioned in the doc changes is that you cannot disable this option when using the operator - as the probes will no longer work. I believe we probably need another issue under https://github.com/keycloak/keycloak/issues/39506 to address this

+1 to at least documenting this limitation as it could cause confusion otherwise. We could maybe even add this to the CLI option description?

**Comment by vmuzikar** [comment]
I'd like to review later this week.

**Review by vmuzikar — COMMENTED** [review]
@shawkins Do you want to update this PR with the Operator changes and the doc change (how to use HTTP health endpoint without curl), or do you want to do it as a follow-up?

**Comment by shawkins** [comment]
> @shawkins Do you want to update this PR with the Operator changes and the doc change (how to use HTTP health endpoint without curl), or do you want to do it as a follow-up?

I'll add that based upon our off-line conversation.

**Comment by shawkins** [comment]
@vmuzikar should be good now.

**Review by vmuzikar — APPROVED** [review]
@shawkins Thanks for the update. LGTM.

I reckon we'll do the docs update for the container guide as a follow-up in a separate PR.
