### PR TITLE
Close the session within resteasy boundaries

### LINKED ISSUE #15192: Close the session within resteasy boundaries
### Area

dist/quarkus

### Describe the bug

As a follow-up on https://github.com/keycloak/keycloak/issues/15152.

In order to avoid potential deadlocks in the event loop thread (even though we always dispatch requests to a worker thread) we should close the session within rest easy boundaries.

This basically means closing the session before the response is written to the underlying HTTP connection.

### Version

19.0.3

### Expected behavior

Close session before the response is written to the underlying HTTP connection.

### Actual behavior

The session is closed when the response is still being written to the underlying HTTP connection.

### How to Reproduce?

See https://github.com/keycloak/keycloak/issues/15152

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #15192

* Changes to `QuarkusRequestFilter` to avoid using Vert.x callbacks (e.g.: addHeadersEndHandler) to avoid closing sessions when the response is not yet done. We are still keeping this filter as it provides a very important hook for us to manage the entire request lifecycle and how it is dispatched for processing.
* Changes to `KeycloakSession` to make sure we can't close it more than once. I see improvements in this area in the future so that we can track the leaking of sessions (and underlying resources) and be more proactive about it.
* Introduced a `TransactionalSessionHandler` (right now basically a marker interface with some default methods) so that we can track the components responsible for managing the request/session lifecycle.
* The fact we are closing the session in multiple places is because we lack a proper hook from Quarkus. Another reason is that due to how Resteasy works on Quarkus we need to make sure the session is only closed after processing streamed responses (e.g: streams returned from endpoints).
* Also note that Vert.x/Quarkus developers assume everything is async. Because of that, we need to consider that closing sessions should not be done after the response is complete, otherwise, sub-sequent requests might see stale state. Now we have a lot of control over this and we are able to handle/control async/reactive responses. Right now everything is blocking though.

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/TransactionalResponseFilter.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+public class TransactionalResponseFilter implements ContainerResponseFilter, TransactionalSessionHandler {
+
+    @Override
+    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext)
+            throws IOException {
+        Object entity = responseContext.getEntity();
+
+        if (shouldDelaySessionClose(entity)) {
+            return;
+        }
```
Comment (ahus1) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/TransactionalResponseFilter.java:45]: I agree that streaming is the most common scenario when the session should be kept open. Still I could see other options when JSON serialization would pull some data from lazily loaded properties and would need to access the database. 

Therefore I wonder: could we always delay this to be consistent and safe?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java [hunk 2]
```diff
@@ -68,89 +67,43 @@ public void handle(RoutingContext context) {
         }
         // our code should always be run as blocking until we don't provide a better support for running non-blocking code
         // in the event loop
-        context.vertx().executeBlocking(createBlockingHandler(context), false, EMPTY_RESULT);
+        executor.execute(createBlockingHandler(context));
```
Comment (ahus1) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:70]: I see that this now changes to the executor thread pool. What were the reasons for that, and how would I configure the thread pool boundaries? 

If the execution throws an exception, where would it be logged? The old code just swallowed it, what would make analysis of problems difficult.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java [hunk 3]
```diff
@@ -68,89 +67,43 @@ public void handle(RoutingContext context) {
...
+    private Runnable createBlockingHandler(RoutingContext context) {
+        return () -> {
+            KeycloakSession session = configureContextualData(context);
 
             try {
-                tx.begin();
                 context.next();
-                promise.tryComplete();
             } catch (Throwable cause) {
-                promise.fail(cause);
```
Comment (ahus1) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:93]: When I debugged the old code, there was a similar catch block in the caller, so it would be ok to remove the catch here.

**Review by ahus1 — COMMENTED** [review]
Thanks for preparing this PR, I like the way it approaches things in a pure JAX-RS way. Please see below for some questions.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/TransactionalResponseFilter.java (hunk 1 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/TransactionalResponseFilter.java:45]: `WriteInterpetor` is not always called and it depends on the media type and if a JAX Response is returned from endpoints.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java (hunk 2 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:70]: The executor is the same. We are basically using it directly instead of dispatching using `RoutingContext`. This is basically a cosmetic change as it makes the code much simpler, with the possibility of managing the request lifecycle a lot better as we can deal with completable|futures to add very nice non-functional aspects. For instance, better exception handling.

I'm not doing it now as I want to just rely on the Vert.X/Quarkus/Resteasy error handing for now.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java (hunk 3 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:93]: I would rather keep it as now we have the possibility to better handle exceptions from dispatched threads.

**Comment by pedroigor** [comment]
@ahus1 Thanks for you comments. I would like more input to see what we can be improving. Please, look at my last changes to the `KeycloakSession`.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java (hunk 2 above)
Comment (ahus1) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:70]: I'd be happy if you could verify with a manual test how those exceptions in the future are handled in the Vert.X/Quarkus/Resteasy error handing. I'd hope they would be logged.

**Comment by ahus1** [comment]
Hi @pedroigor - +1 for closing the session only once. Not sure though if the`isClosed()` should be exposed. 

I saw that an earlier version threw exceptions whenever some method was called on an already closed session. I like that fail-safe design. I assume you removed it as it broke too many places? I'd be happy if we could have this in another PR, or maybe to start logging some warnings first.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java (hunk 2 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:70]: We have a test covering this. The FlowTest expects a response error during commit. Or do you mean something else?

**Comment by pedroigor** [comment]
@ahus1 I agree we should look at tracking session usage after closing it. We are really missing it.

However, I did not want to include the previous changes that you are referring to because they require a bit more time to get it right. For instance, need to consider async responses and delay closing sessions.

I do not see as a blocker but definitely something to improve. I have the changes almost ready and will create an issue and PR for your review.

**Comment by ahus1** [comment]
> I believe the close method should be part of the public contract. Are you concerned about people calling this method directly? Ifo wouldn't help the checks we are discussed around reusing a closed session?

I agree with you that having this method would help with the transition. Still I think that any use of the method indicates that we're not sure if the code involved has either closed or not closed the session, which is a code smell indicating that we're not 100% sure what the code is doing. 

So +1 to have it in the public interface for the transition.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java (hunk 2 above)
Comment (ahus1) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:70]: I've tested what happens when an exception would happen after `context.next()`. I now see that the executor pool logs that information: 

```
2022-10-31 10:54:58,128 ERROR [org.jboss.threads.errors] (executor-thread-1) Thread Thread[executor-thread-1,5,main] threw an uncaught exception: java.lang.RuntimeException: java.lang.RuntimeException: oops
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:88)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: oops
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:84)
	... 7 more
```

So this is resolved for me.

**Review by ahus1 — DISMISSED** [review]
I reviewed the changes and tested them to my best knowledge and they look good to me. The failing model tests are due to a know unstable test.

I noticed one change that should go in the release notes:

* previously the REST calls have been dispatched to a Vert.x worker thread
* now they are dispatched to the executor pool

The new behavior is better, as I saw the RESTEasy stack sometimes dispatching the finishing response to the executor pool (didn't figure out the full scenario, but was probably a streaming response). 

This requires uses to change their configuration on the thread pool: 

* the old setting https://quarkus.io/guides/all-config#quarkus-vertx_quarkus.vertx.worker-pool-size which defaults to 20

* new setting https://quarkus.io/guides/all-config#quarkus-core_quarkus.thread-pool.max-threads that is at minimum 200 threads, but might be a lot more depending on the cores of the machine

IMHO that change is worth a text snippet in the release notes.

File: server-spi/src/main/java/org/keycloak/models/KeycloakSession.java [hunk 4]
```diff
@@ -202,6 +202,8 @@ default <T> T getAttributeOrDefault(String attribute, T defaultValue) {
 
     void close();
 
+    boolean isClosed();
```
Comment (hmlnarik) [inline server-spi/src/main/java/org/keycloak/models/KeycloakSession.java:205]: I am not keen on extending the `KeycloakSession` with this method.

Prevention of throwing an exception is the sole reason for this method. The use of this method exposes `KeycloakSession` internal state. If `KeycloakSession.close` was idempotent and for active transactions handled the transaction commit / rollback itself, this could be completely omitted, and `KeycloakSession`.

**Review by hmlnarik — COMMENTED** [review]
Thank you @pedroigor for the PR!

While I like the overall direction a lot, I have to object adding a new method into `KeycloakSession` as it would expose internal state rather than keeping encapsulation principle. Please see inline for more details.

File: server-spi/src/main/java/org/keycloak/models/KeycloakSession.java (hunk 4 above)
Comment (pedroigor) [reply server-spi/src/main/java/org/keycloak/models/KeycloakSession.java:205]: Sorry, but I'm not following what you mean exposing state. Why exposing if the session is closed so bad?

We are really missing this as well as proper checks to enable a safer usage of the session.

**Comment by pedroigor** [comment]
@ahus1 +1. I'm going to prepare the changes to the upgrade guide. In fact, we need to create specific options in our side to configure those tread pools.

Btw, created:

* https://github.com/keycloak/keycloak/issues/15223
* https://github.com/keycloak/keycloak/issues/15223

**Comment by pedroigor** [comment]
@ahus1 By using the quarkus thread pool we are also losing the capability from Vert.x to warn when a worker thread is blocking.

I think that is OK because it aligns better with what Resteasy extension does as it also dispatches to the same thread pool we are using.

File: server-spi/src/main/java/org/keycloak/models/KeycloakSession.java (hunk 4 above)
Comment (hmlnarik) [reply server-spi/src/main/java/org/keycloak/models/KeycloakSession.java:205]: The code which handles the transaction is this and is found at many places across the codebase:
```java
        KeycloakTransactionManager tx = session.getTransactionManager();

        try {
            if (tx.isActive()) {
                if (tx.getRollbackOnly()) {
                    tx.rollback();
                } else {
                    tx.commit();
                }
            }
        } finally {
            session.close();
        }
```
There is no place in codebase which closes the session has does not have the transaction commit handling code before itself in try-finally block.

This follows from the fact that closing session without committing the to-be-committed transaction is illegal: The changes in session would be lost, so the session should not exist in the first place.

Hence this code could and should be enclosed in `KeycloakSession.close()` instead of repeating it at many times differently, e.g. [here](https://github.com/keycloak/keycloak/blob/17117820cc14f87f5990ddce80ef38a0e2e7f314/server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java#L255-L277) or [here](https://github.com/keycloak/keycloak/blob/17117820cc14f87f5990ddce80ef38a0e2e7f314/services/src/main/java/org/keycloak/services/filters/AbstractRequestFilter.java#L59-L68). This enclosing also makes `isClosed` method redundant. One of the consequences is that e.g. rollback-only transactions are not handled at all e.g. in [ScheduledTaskRunner](https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/services/scheduled/ScheduledTaskRunner.java)

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+
+    /**
+     * Closes a transactional {@link KeycloakSession}.
+     *
+     * @param session a transactional session
+     */
+    default void close(KeycloakSession session) {
+        if (session.isClosed()) {
+            return;
+        }
```
Comment (stianst) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:54]: Do we actually call this multiple times?

I think I also agree that it shouldn't be required to expose `isClosed` on a session, and honestly maybe would rather see the session throw exceptions if trying to use a closed session.

File: server-spi/src/main/java/org/keycloak/models/KeycloakSession.java (hunk 4 above)
Comment (stianst) [reply server-spi/src/main/java/org/keycloak/models/KeycloakSession.java:205]: I agree with @hmlnarik here. 

It would be much nicer if DefaultKeycloakSession#close handles the closing of the tx itself, so this boilerplate code isn't needed elsewhere.

DefaultKeycloakSession#close could just be a no-op if the session is already closed, or maybe it would be better to throw an exception? Strictly speaking a session that is closed should throw an exception if someone tries to use it.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java (hunk 5 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:54]: Under some circumstances, yes. One of them is when using RESTEasy async responses. In Quarkus we dispatch requests differently so we need to make sure the session is always closed after running RESTeasy. I know it looks redundant, but it is much safer.

As mentioned by @ahus1, I did test some changes to throw exceptions when trying to use a closed session. But to properly implement it we need a bit more investigation to make sure we are covering all cases.

IMO, exposing `isClosed` is just natural because it is a state that should be exposed. Not really different than what you see from other frameworks like Hibernate or even requests/responses from Vert.X. As mentioned before, this should be done as a follow-up as per https://github.com/keycloak/keycloak/issues/15224.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+        return session;
+    }
+
+    /**
+     * Closes a transactional {@link KeycloakSession}.
+     *
+     * @param session a transactional session
+     */
+    default void close(KeycloakSession session) {
+        if (DefaultKeycloakSession.class.cast(session).isClosed()) {
```
Comment (pedroigor) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:53]: @ahus1 @hmlnarik @stianst I'm removing from the interface for now so that we can discuss the changes to `KeycloakSession` and its lifecycle on this issue https://github.com/keycloak/keycloak/issues/15223.

I'm pretty convinced we need this method as in the contract but it is not a blocker to moving forward and fixing the original issue.

**Review by ahus1 — APPROVED** [review]
Thanks for preparing this PR and answering all my questions around it. Looking forward to the future issues, especially #15223

File: server-spi/src/main/java/org/keycloak/models/KeycloakSession.java (hunk 4 above)
Comment (hmlnarik) [reply server-spi/src/main/java/org/keycloak/models/KeycloakSession.java]: Calling a session `close` twice is illegal operation, so an exception perhaps makes more sense.

> Regarding encapsulating the close/commit, that is the reason why I've added the `TransactionalSessionHandler` to remove boilerplate code between components related to creating/closing _transactional_ sessions within the distribution codebase, without introducing more changes to the core codebase.

I like the way of its separation from the rest of code, so +1 for this.

> Still, I think we should expose whether or not a session is closed. We do have places where a session is only created to obtain providers without any transaction. For instance, setting up background tasks.

Controlling the "any transactions" part by the code is not possible as there is always transaction manager instantiated in a session which is never cleared: https://github.com/keycloak/keycloak/blob/17117820cc14f87f5990ddce80ef38a0e2e7f314/services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java#L94
Furthermore the code which uses the session has no access to actual transactions registered inside TM, so the `commit` / `rollback` operation is performed on TM and never on individual transactions directly, as shown e.g. here: https://github.com/keycloak/keycloak/blob/17117820cc14f87f5990ddce80ef38a0e2e7f314/services/src/main/java/org/keycloak/services/filters/AbstractRequestFilter.java#L64

> IMO, closing a session is purely about releasing providers/resources and not necessarily ending transactions. Keeping these two concepts separate is far more flexible than assuming a session is always transactional.

Should a provider be retrieved on an already closed session, it cannot read or write any data since the data transaction is committed, and - as also proposed in this PR - commit is never performed on an already closed session. Already closed session also contains potentially dirty transaction manager instance since that is never cleared (rightfully so). Thus I don't think that assumption of _closing a session is purely about releasing providers/resources_ is correct. Supporting concept of reusing keycloak session as declared in the current codebase would thus be prone to errors.

Comment (pedroigor) [reply server-spi/src/main/java/org/keycloak/models/KeycloakSession.java]: I see.

I'm not talking about reusing closing sessions, that is what we are discussing avoiding, right? 

My point is more about not assuming all usages of sessions are transactional. And we have this type of usage too.

**Review by hmlnarik — APPROVED** [review]
Thank you @pedroigor for removing the `isClosed` from `KeycloakSession`.
I'm fine to have this in to unblock the release as long as the #15243 is also included soon.
