### PR TITLE
[OID4VCI-HAIP] Pass oid4vci-1_0-issuer-metadata_test

### LINKED ISSUE #47150: [OID4VCI-HAIP] Fix oid4vci-1_0-issuer-metadata-test
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

`token_endpoint_auth_methods_supported` does not include `attest_jwt_client_auth`

```
[
  "private_key_jwt",
  "client_secret_basic",
  "client_secret_post",
  "tls_client_auth",
  "client_secret_jwt"
]
```

### PR DESCRIPTION
**Pull request by tdiesler**
closes #47150

The Client Attester is supposed to be an external component that the AS can trust and that the Wallet accesses to get an "Client Attestation JWT". As such, it should really be provided by the OpenID Foundation Conformance Suite, so that their mock Wallet can connect to some mock Client Attester - this however is not the case.

Instead, this PR provides a basic Client Attester to unblock HAIP conformance testing.
The PR also adds an `AttestationBasedClientAuthenticator` which currently does nothing but inform the OpenID Metadata Provider that `attest_jwt_client_auth` is (going to be) supported.

This is enough to pass the `oid4vci-1_0-issuer-metadata-test` and simply the first PR in a long series of HAIP conformance test related changes.

depends on 

1. #47313

### CODE REVIEW

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+ * @author <a href="mailto:tdiesler@proton.me">Thomas Diesler</a>
+ */
+public class AttestationBasedClientAuthenticator extends AbstractClientAuthenticator {
+
+    public static final String PROVIDER_ID = "client-attestation";
+
+    @Override
+    public void authenticateClient(ClientAuthenticationFlowContext context) {
+        logger.warnf("Attestation-Based Client Authentication not (yet) fully supported");
+    }
```
Comment (forkimenjeckayang) [inline services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java:61]: `authenticateClient`  only logs a warning and does nothing else. It doesn't call `context.success()` or `context.failure(...)`. This means any client attempting to actually use `attest_jwt_client_auth` will fail with a confusing generic error. While the PR description acknowledges this could the method atleast fail gracefully?

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+
+    @Override
+    public String getHelpText() {
+        return "Validates client based on a Client Attestation JWT and a PoP JWT which proves possession of the private key";
+    }
+
+    @Override
+    public List<ProviderConfigProperty> getConfigProperties() {
+        return new LinkedList<>();
+    }
```
Comment (forkimenjeckayang) [inline services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java:86]: Could we return `Collections.emptyList()` same as `getConfigPropertiesPerClient()` to have some consistency?

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+    public List<ProviderConfigProperty> getConfigPropertiesPerClient() {
+        return Collections.emptyList();
+    }
+
+    @Override
+    public Map<String, Object> getAdapterConfiguration(KeycloakSession session, ClientModel client) {
+        Map<String, Object> config = new HashMap<>();
+        return config;
+    }
+
```
Comment (forkimenjeckayang) [inline services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java:97]: `getAdapterConfiguration` creates an empty HashMap and returns it. Could simply return `Collections.emptyMap()`.

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+    @Override
+    public Set<String> getProtocolAuthenticatorMethods(String loginProtocol) {
+        boolean abcaEnabled = Profile.isFeatureEnabled(Profile.Feature.OID4VC_VCI_ABCA);
+        if (loginProtocol.equals(OIDCLoginProtocol.LOGIN_PROTOCOL) && abcaEnabled) {
+            return Set.of(OIDCLoginProtocol.ATTEST_JWT_CLIENT_AUTH);
+        } else {
+            return Collections.emptySet();
+        }
+    }
+}
```
Comment (forkimenjeckayang) [inline services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java:111]: `getProtocolAuthenticatorMethods` checks `Profile.Feature.OID4VC_VCI_ABCA`, while `OIDCWellKnownProvider.getClientAuthMethodsSupported()` additionally checks `realm.isVerifiableCredentialsEnabled()`. This means `attest_jwt_client_auth` requires BOTH the feature flag AND the realm-level toggle to be enabled. This is correct but could be  worth documenting explicitly.  WDYT?

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractClientAuthenticator.java
Comment (forkimenjeckayang) [inline services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractClientAuthenticator.java:1]: Adding logger to this abstract base class affects ALL existing subclasses. If any subclass already declares a logger field, this will shadow it. Ideally the existing subclass loggers should eventually be removed in favor of the inherited one ,but that cleanup can be a separate PR ?

File: common/src/main/java/org/keycloak/common/Profile.java [hunk 5]
```diff
@@ -129,6 +129,7 @@ public enum Feature {
         PERSISTENT_USER_SESSIONS("Persistent online user sessions across restarts and upgrades", Type.DEFAULT, FeatureUpdatePolicy.SHUTDOWN),
 
         OID4VC_VCI("Support for the OID4VCI protocol as part of OID4VC.", Type.EXPERIMENTAL),
+        OID4VC_VCI_ABCA("Support for Attestation-Based Client Authorization", Type.EXPERIMENTAL, OID4VC_VCI),
```
Comment (forkimenjeckayang) [inline common/src/main/java/org/keycloak/common/Profile.java]:
```suggestion
        OID4VC_VCI_ABCA("Support for Attestation-Based Client Authentication", Type.EXPERIMENTAL, OID4VC_VCI),
```

File: core/src/main/java/org/keycloak/protocol/oidc/representations/OIDCConfigurationRepresentation.java
Comment (forkimenjeckayang) [inline core/src/main/java/org/keycloak/protocol/oidc/representations/OIDCConfigurationRepresentation.java:1]: Could the new fields have getter methods like the others? While Jackson can still read the fields via `@JsonProperty` annotations for serialization, the missing getters break the class's API contract and prevent tests from easily verifying the values. WDYT ?

File: services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java [hunk 6]
```diff
@@ -153,10 +155,18 @@ public Object getConfig() {
...
+
+        config.setTokenEndpointAuthMethodsSupported(clientAuthMethodsSupported);
+        config.setTokenEndpointAuthSigningAlgValuesSupported(supportedClientSigningAlgorithms);
+        config.setIntrospectionEndpointAuthMethodsSupported(clientAuthMethodsSupported);
+        config.setIntrospectionEndpointAuthSigningAlgValuesSupported(supportedClientSigningAlgorithms);
+
+        if (clientAuthMethodsSupported.contains(ATTEST_JWT_CLIENT_AUTH)) {
+            config.setClientAttestationSigningAlgValuesSupported(List.of(Algorithm.RS256.name()));
+            config.setClientAttestationPopSigningAlgValuesSupported(List.of(Algorithm.RS256.name()));
+        }
```
Comment (forkimenjeckayang) [inline services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java:169]: Should we restrict to `RS256` only or we include all supported algorithms ?

File: tests/base/src/test/java/org/keycloak/tests/oid4vc/abca/OIDCAuthorizationMetadataABCATest.java
Comment (forkimenjeckayang) [inline tests/base/src/test/java/org/keycloak/tests/oid4vc/abca/OIDCAuthorizationMetadataABCATest.java:1]: A negative test verifying that `attest_jwt_client_auth` is NOT present when the feature/realm is disabled could be good?

**Review by forkimenjeckayang — CHANGES_REQUESTED** [review]
A few concerns to check when you're chanced @tdiesler

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java (hunk 1 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java:61]: done

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java (hunk 2 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java:86]: done

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java (hunk 3 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java:97]: done

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java (hunk 4 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/AttestationBasedClientAuthenticator.java:111]: Now implementing EnvironmentDependentProviderFactory

File: services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractClientAuthenticator.java
Comment (tdiesler) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractClientAuthenticator.java:1]: I checked all sub-classes

File: core/src/main/java/org/keycloak/protocol/oidc/representations/OIDCConfigurationRepresentation.java
Comment (tdiesler) [reply core/src/main/java/org/keycloak/protocol/oidc/representations/OIDCConfigurationRepresentation.java:1]: good catch - thanks

File: services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java (hunk 6 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java:169]: good catch, lets do this for now ...

```
        if (clientAuthMethodsSupported.contains(ATTEST_JWT_CLIENT_AUTH)) {
            config.setClientAttestationSigningAlgValuesSupported(getSupportedSigningAlgorithms(false));
            config.setClientAttestationPopSigningAlgValuesSupported(getSupportedSigningAlgorithms(false));
        }
```

File: tests/base/src/test/java/org/keycloak/tests/oid4vc/abca/OIDCAuthorizationMetadataABCATest.java
Comment (tdiesler) [reply tests/base/src/test/java/org/keycloak/tests/oid4vc/abca/OIDCAuthorizationMetadataABCATest.java:1]: done

**Review by forkimenjeckayang — APPROVED** [review]
Thank you for considering my comments. I have no further concerns

**Comment by tdiesler** [comment]
Is this waiting on anything?

File: common/src/main/java/org/keycloak/common/Profile.java [hunk 7]
```diff
@@ -129,6 +129,7 @@ public enum Feature {
         PERSISTENT_USER_SESSIONS("Persistent online user sessions across restarts and upgrades", Type.DEFAULT, FeatureUpdatePolicy.SHUTDOWN),
 
         OID4VC_VCI("Support for the OID4VCI protocol as part of OID4VC.", Type.EXPERIMENTAL),
+        OID4VC_VCI_ABCA("Support for Attestation-Based Client Authentication", Type.EXPERIMENTAL, OID4VC_VCI),
```
Comment (mposolda) [inline common/src/main/java/org/keycloak/common/Profile.java]: Minor: This feature is not specific to OID4VCI as attestation based client authentication does not have direct dependency on `OID4VCI` . Is it perhaps possible to rename to something like `CLIENT_AUTH_ABCA` ? (As we already have feature `CLIENT_AUTH_FEDERATED`, which adds client authenticator and this feature is a bit similar to that).

**Review by mposolda — COMMENTED** [review]
@tdiesler Thanks for the PR and sorry for the late review :-/ 

LGTM, just added one minor comment regarding the feature name. Is it ok with you to rename the feature?

It is not ideal to add the "non working" client authenticator just because of the metadata, but understand the reason to unblock the other tests etc... So should be OK considering that it is experimental feature and the proper implementation would be added later.

**Comment by mposolda** [comment]
@tdiesler @forkimenjeckayang FYI. commented on the discussion here regarding ABCA https://github.com/keycloak/keycloak/discussions/40413#discussioncomment-16505794 (This is not related to this PR, but not sure where is the best place to discuss this, so just commenting here for your info :-) ).

File: common/src/main/java/org/keycloak/common/Profile.java (hunk 7 above)
Comment (tdiesler) [reply common/src/main/java/org/keycloak/common/Profile.java]: sure - done

**Review by mposolda — APPROVED** [review]
@tdiesler Thanks!
