### PR TITLE
fix: reusing the apache builder to retain retry config

### LINKED ISSUE #47379: RetryConfig is ignored
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Any configuration properties defined in RetryConfig (https://www.keycloak.org/server/outgoinghttp#_configuring_retry_behavior_for_outgoing_http_requests) like `spi-connections-http-client-default-max-retries` or `spi-connections-http-client-default-initial-backoff-millis` are ignored.

The reason is because the retry handler built in `DefaultHttpClientFactory.configureRetries` is attached to a Apache HttpClientBuilder that is returned by `getApacheHttpClientBuilder()`.
This is done before keycloak's `HttpClientBuilder.build()` is called.
Afterwards in keycloak's HttpClientBuilder.build() a new Apache HttpClientBuilder is created by calling `getApacheHttpClientBuilder()` again. In this instance no retry handler is attached.
Therefore the default Apache `DefaultHttpRequestRetryHandler` is used.

### Version

26.5.6

### Regression

- [ ] The issue is a regression

### Expected behavior

The retry configuration properties should be used to control http retry behavior.

### Actual behavior

The retry configuration properties are not used.

### How to Reproduce?

Configure retry e.g. by setting KC_SPI_CONNECTIONS_HTTP_CLIENT_DEFAULT_MAX_RETRIES and check in the debugger if the correct retry handler is set before `builder.build()` is called in `HttpClientBuilder` (line 297).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #47379

### CODE REVIEW

File: services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java [hunk 1]
```diff
@@ -301,7 +302,7 @@ public CloseableHttpClient build() {
     }
 
     protected org.apache.http.impl.client.HttpClientBuilder getApacheHttpClientBuilder() {
-        return HttpClients.custom();
+        return apacheBuilder;
```
Comment (rhandsch) [inline services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java:309]: This method is overwritten by `OTelHttpClientBuilder`, that again re-creates the Apache HttpClientBuilder.

I'd suggest to: 
- rename this method ti indicate that it is supposed to create a new instance of the Apache HttpClientBuilder (e.g. `createApacheHttpClientBuilder`)
- add a new internal method that caches the returned instance and calls createApacheHttpClientBuilder only once

Comment (shawkins) [reply services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java:309]: Updated with the create method.

Comment (rhandsch) [reply services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java:309]: That looks good. Now I'd suggest to make this method `final`, so that it cannot be overwritten.
Would it make sense to make the method public?

Comment (shawkins) [reply services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java:309]: > Now I'd suggest to make this method final, so that it cannot be overwritten.

You mean make the getter final? Since none of the other methods are final, I'll just leave it as non-final as well.

> Would it make sense to make the method public?

That would need to be an enhancement request. @mabartos likely wanted to keep this as not broadly exposed.

Comment (rhandsch) [reply services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java:309]: Would it be an option to make the getter `private`? It is all about to avoid overwriting it and thus breaking the logic.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.
