### PR TITLE
Use monospaced font for workflow editor.

### LINKED ISSUE #47454: Workflows editor uses proportional font instead of monospace
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

[Complaint ](https://github.com/keycloak/keycloak/issues/39888#issuecomment-4126664571)from @dasniko.

Why the (workflows) editor uses a proportional font and not monospace?
IMHO monospace would make more sense when dealing (fighting) with YAML.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Use monospace font.

### Actual behavior

proportional font

### How to Reproduce?

Use the workflows editor.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ssilvert**
Fixes #47454

Monospaced font is nicer for editing YAML.

ui-monospace → SF Mono on macOS/iOS (Safari)
SFMono-Regular → SF Mono on macOS (Chrome/Firefox)
Menlo → macOS fallback
Consolas → Windows
Liberation Mono → Linux
monospace → final fallback

### CODE REVIEW

File: js/apps/admin-ui/src/components/form/CodeEditor.tsx [hunk 1]
```diff
@@ -26,7 +26,9 @@ const CodeEditor = ({
         padding={15}
         minHeight={height}
         style={{
-          font: "var(--pf-global--FontFamily--monospace)",
+          fontFamily:
+            'ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace',
+          fontSize: "16px",
```
Comment (dasniko) [inline js/apps/admin-ui/src/components/form/CodeEditor.tsx:31]: IMHO font-size could only be 14px, but this is less important

**Review by dasniko — CHANGES_REQUESTED** [review]
LGTM

File: js/apps/admin-ui/src/components/form/CodeEditor.tsx (hunk 1 above)
Comment (ssilvert) [reply js/apps/admin-ui/src/components/form/CodeEditor.tsx:31]: Hard to say what this should be.  Looked too small on my monitor.  I could make it adjustable, but that might be overkill.

**Review by sguilhen — APPROVED** [review]

File: js/apps/admin-ui/src/components/form/CodeEditor.tsx (hunk 1 above)
Comment (dasniko) [reply js/apps/admin-ui/src/components/form/CodeEditor.tsx:31]: Then keep it as is, it's not that important.

**Review by pedroigor — APPROVED** [review]
