### PR TITLE
fix: Adding client to logout event. Should fix #21236 

### LINKED ISSUE #21236: Keycloak Event clientId is null when ever a logout event is fired.
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

We are implementing the `EventListenerProvider` interface in order to catch some Keycloak events, we are using the event.clientId to get the clientId which is related to this event.

For the events of type `LOGIN`, we are able to see the correct clientId on which the user or admin is using to authenticate using `event.clientId` , however for `LOGOUT` event, the `event.clientId` is null. (we are using Kotlin)

I tested this with both 20.0.5 and 21.1.1.

### Version

21.1.1

### Expected behavior

I expect that the `event.clientId` should return the correct clientId instead of null, same behaviour as the login event.

### Actual behavior

`event.clientId` is null for the `LOGOUT` event.

### How to Reproduce?

```
class MyEventListenerClass : EventListenerProvider {

  override fun onEvent(event: Event) {

    when (event.type) {
      EventType.LOGIN -> {
             printtln(event.clientId). <----- correct
      }
      EventType.LOGOUT -> {
             printtln(event.clientId) <----- null
      }
}
}}
```

### Anything else?

I am not sure if it is a problem just for the `LOGOUT` event.

### PR DESCRIPTION
**Pull request by Delawen**
Should fix #21236 

Previously, `LOGOUT` events didn't contain any client id information:
image

After this fix, `LOGOUT` events contain the client information as the rest of the events:
image

This PR contains also a test that checks the client id after a logout is made.

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java [hunk 1]
```diff
@@ -1293,7 +1293,11 @@ private void resetPasswordTwiceInNewTab(UserRepresentation user, String clientId
             logoutConfirmPage.assertCurrent();
             logoutConfirmPage.confirmLogout();
 
-            events.expectLogout(sessionId).user(user.getId()).removeDetail(Details.REDIRECT_URI).assertEvent();
+            events.expectLogout(sessionId)
```
Comment (Delawen) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java:1296]: Removing the `null` client in `AssertEvents` forced me to add a real `.client` here to not fail the check.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java [hunk 2]
```diff
@@ -175,7 +175,7 @@ public ExpectedEvent expectRefresh(String refreshTokenId, String sessionId) {
     }
 
     public ExpectedEvent expectLogout(String sessionId) {
-        return expect(EventType.LOGOUT).client((String) null)
```
Comment (Delawen) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java:178]: Now there's many tests that fail (like on `ResetPasswordTest`) because we return an actual client.

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Comment by Delawen** [comment]
I believe those flaky tests are not my fault, are they?

**Comment by Delawen** [comment]
@keycloak/core @mposolda can you take a look at this, please, and tell me if something is missing?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LogoutTest.java [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+import org.keycloak.testsuite.AssertEvents;
+import org.keycloak.testsuite.pages.AppPage;
+import org.keycloak.testsuite.pages.LoginPage;
+import org.keycloak.testsuite.util.RealmBuilder;
+import org.keycloak.testsuite.util.UserBuilder;
+
+/**
+ * @author <a href="mailto:ariasdereyna@redhat.com">María Arias de Reyna</a>
+ */
+public class LogoutTest extends AbstractTestRealmKeycloakTest {
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LogoutTest.java:37]: Thanks for adding this test class. But I actually vote for remove it from this PR.

As you pointed in the other comment (in `AssertEvents` class), you already needed to update events on multiple places in other tests due the fact that client is included in the logout event with your changes. So additional class for this, which already tests the same scenario as some other places is pretty redundant IMO.

Besides that, we already have 2 classes in the codebase named `LogoutTest`. They are in different packages, but still it can cause confusions in theory to have test classes of same name.

**Review by mposolda — COMMENTED** [review]
@Delawen Thanks! Your PR looks quite good. Added just one minor inline comment regarding new test class.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java [hunk 4]
```diff
@@ -293,7 +293,7 @@ public void successfulKLogoutAfterEmptyBackChannelUrl() throws Exception {
         }
 
         // Assert logout event triggered for backchannel logout
-        events.expectLogout(sessionId).detail(Details.REDIRECT_URI, oauth.APP_AUTH_ROOT).assertEvent();
+        events.expectLogout(sessionId).client((String) null).detail(Details.REDIRECT_URI, oauth.APP_AUTH_ROOT).assertEvent();
```
Comment (pedroigor) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java:296]: I think we are missing a similar change (set client to event) when going through the logout endpoint. This assertion indicates we are missing the client there too when the `client_id` or `id_token_hint` is passed.

Looking at the `LogoutEndpoint#logout` (GET) method, it seems we are only setting the client when there is a mismatch between `client_id` and id_token `azp`. See https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java.

File: services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java [hunk 5]
```diff
@@ -384,6 +384,9 @@ public Response frontchannelLogout(UserSessionModel userSession, AuthenticatedCl
     @Override
     public Response finishBrowserLogout(UserSessionModel userSession, AuthenticationSessionModel logoutSession) {
         event.event(EventType.LOGOUT);
+        if (event.getEvent().getClientId() == null) {
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java:387]: Not sure if we need the check but just set the client from the authentication session?

**Review by pedroigor — COMMENTED** [review]
@Delawen Thanks. In general, LGTM. Only a few comments.

File: services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java (hunk 5 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java:387]: This is minor, but yes, I think `if` can be removed.

Comment (Delawen) [reply services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java:387]: I didn't want to overwrite anything that came from somewhere else. But if you think this is not needed, I will remove it.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java (hunk 4 above)
Comment (Delawen) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java:296]: Looking for a better place/another place to setup the client id.

File: services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java (hunk 5 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java]: @Delawen The way you did is safer but I can't see why a client other than the one associated with the authentication session should be set there. Not hard on it as we can figure it out later.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LogoutTest.java (hunk 3 above)
Comment (Delawen) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LogoutTest.java]: Class removed.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java (hunk 4 above)
Comment (Delawen) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java]: Added the client to the event on the same place where the client gets added to the session context. Now there's even a logout error event test that reports a client id, so I it looks like a good place to set the client.

**Review by mposolda — APPROVED** [review]
@Delawen Thanks for the updates!
@pedroigor Do you have anything more to this PR?

**Review by pedroigor — APPROVED** [review]

File: services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java (hunk 5 above)
Comment (pedroigor) [reply services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java]: Thanks @Delawen !

**Comment by mposolda** [comment]
@Delawen Thanks again and Congratulations for your 1st Keycloak contribution :-)
