### PR TITLE
fix: remove the use of regex for determining local addresses

### LINKED ISSUE #36227: Local IPv6 check still not correct
Hi @shawkins , hope you're well

I'm having the same issue even after the fix #35737  
After debugging i noted that variable  `address` didn't start with "[", instead had value `0:0:0:0:0:0:0:1`, reason why it didn't pass to regex check, hence giving the same error. 

ipv6-issue

_Originally posted by @Eddyhanderson in https://github.com/keycloak/keycloak/issues/35675#issuecomment-2558700903_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #36227

### CODE REVIEW

File: services/src/test/java/org/keycloak/utils/SecureContextResolverTest.java
Comment (jonkoops) [inline services/src/test/java/org/keycloak/utils/SecureContextResolverTest.java:1]: Should these test cases not be added to `testIsLocalhost()` instead?

Comment (shawkins) [reply services/src/test/java/org/keycloak/utils/SecureContextResolverTest.java:1]: Good point, moved them over.

**Review by mabartos — APPROVED** [review]
@shawkins Much better! Thanks!

File: services/src/main/java/org/keycloak/utils/SecureContextResolver.java [hunk 1]
```diff
@@ -79,16 +78,15 @@ public static boolean isLocalAddress(String address) {
...
-        if (address.startsWith("[")) {
-            return LOCALHOST_IPV6.matcher(address).matches();
-        }
 
-        // The host matches a CIDR notation of 127.0.0.0/8
-        if (LOCALHOST_IPV4.matcher(address).matches()) {
-            return true;
+        if (NetUtil.isValidIpV4Address(address) || NetUtil.isValidIpV6Address(address)) {
+            try {
+                return InetAddress.getByName(address).isLoopbackAddress();
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/utils/SecureContextResolver.java:84]: I wonder if this might yield some false positives, does this match the full CIDR range of  `::1/128` and `127.0.0.0/8`, and nothing else? User agents are [rather strict](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy) about what is allowed here, and might not set cookies properly if some other address is matched.

Comment (vmuzikar) [reply services/src/main/java/org/keycloak/utils/SecureContextResolver.java:84]: > does this match the full CIDR range of `::1/128` and `127.0.0.0/8`, and nothing else?

Looking at the OpenJDK implementations for [v4](https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/java.base/share/classes/java/net/Inet4Address.java#L189-L193) and [v6](https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/java.base/share/classes/java/net/Inet6Address.java#L321-L327) addresses, it looks it matches exactly that. Question is if we can rely on it as the contract (the java doc) doesn't seem to say that and theoretically other JDK impls could have a different logic for that.

Comment (vmuzikar) [inline services/src/main/java/org/keycloak/utils/SecureContextResolver.java:84]: `InetAddress#getByName` is doing a DNS request, no? At least when it's called from [`isSecureContext`](https://github.com/keycloak/keycloak/blob/63a87155478b0df8ce2a9e0eb45715d2373b0090/services/src/main/java/org/keycloak/utils/SecureContextResolver.java#L61). Not sure we should do it as it might be partially a regression of #35216, no?

Comment (jonkoops) [reply services/src/main/java/org/keycloak/utils/SecureContextResolver.java:84]: Thanks for following up on that, I think we can consider the OpenJDK implementation sound enough in this regard. But yeah, the JavaDoc is rather limiting, not sure if there are other specifications we could reference.

Comment (shawkins) [reply services/src/main/java/org/keycloak/utils/SecureContextResolver.java:84]: > InetAddress#getByName is doing a DNS request, no?

Only for non-IP values.

**Review by jonkoops — APPROVED** [review]
LGTM

File: services/src/main/java/org/keycloak/utils/SecureContextResolver.java (hunk 1 above)
Comment (vmuzikar) [reply services/src/main/java/org/keycloak/utils/SecureContextResolver.java:84]: Yes, and that was the issue with #35216 as well, right?

Comment (vmuzikar) [reply services/src/main/java/org/keycloak/utils/SecureContextResolver.java:84]: Right, the `isValidIp...` method. I guess my brain is still booting up in the 2025, sorry. :)

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks
