### PR TITLE
Remove hardcoded references to jakarta package from JEE admin client

### LINKED ISSUE #27609: Mixed use of javax and jakarta in org.keycloak.admin.client
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/jee

### Describe the bug

Hi, we recently upgraded our java application from using Keycloak 21 to 22 and we started to have runtime exceptions related to jakarta. The package we use is `org.keycloak:keycloak-admin-client:22.0.5`

After some searching, I eventually came to this [file](https://github.com/keycloak/keycloak/blob/release/22.0/integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UserProfileResource.java), where there is inconsistent reference of `APPLICATION_JSON`:

In L42

```@Consumes(jakarta.ws.rs.core.MediaType.APPLICATION_JSON)```

But in L46, simply
```@Produces(MediaType.APPLICATION_JSON)```

And there is no import of jakarta in the admin-client.

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

No build issues or runtime issues when having `import org.keycloak.admin.client.Keycloak;`  

### Actual behavior

We see build error: `class file for jakarta.ws.rs.core.Response not found`.

### How to Reproduce?

(I'm not able to provide the code as it is private. But I hope I already found the root cause.)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
closes #27609

### CODE REVIEW

File: integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/GroupResource.java [hunk 1]
```diff
@@ -90,12 +90,12 @@ public interface GroupResource {
      *
      * @param first
      * @param max
-     * @param full
+     * @param briefRepresentation
```
Comment (jonkoops) [inline integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/GroupResource.java:93]: Might as well remove these comments since they don't add any additional information.

**Review by jonkoops — APPROVED** [review]

File: integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/GroupResource.java (hunk 1 above)
Comment (mposolda) [reply integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/GroupResource.java:93]: Thanks! I consider it possibly as a follow-up if we want to review javadoc of the admin-client in general as there are lots of the methods, which use empty parameters. I've just changed this to remove warning from Intellij Idea due to incorrect parameter name.
