### PR TITLE
Use a different API method to move groups

### LINKED ISSUE #20615: Moving a group to root loses all its members
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In the Admin UI, when a group "ChildGroup" that is a child of another group "ParentGroup" is moved to the root, all members associated with  "ChildGroup" group are lost because the group is deleted and then recreated with a new ID.

### Version

21.0.1

### Expected behavior

Any members of ChildGroup prior to the move would still be members after the move. The group ID of ChildGroup should not change.

### Actual behavior

ChildGroup has no members after the move. The group ID for ChildGroup changed to a different value.

### How to Reproduce?

1. Set up a Keycloak realm with two groups:
	ParentGroup - as a root-level group
	ChildGroup - as a child of ParentGroup
2. Add one or more members to ChildGroup
3. Either from the group hierarchy view, or on the "Child groups" tab of the ParentGroup, click the ellipsis on the row for ChildGroup, and select "Move to" from the popup menu.
4. In the move dialog, don't select a new parent (leave as "Move ChildGroup to root"), and click "Move here"
5. After ChildGroup is moved to be a root-level group, check its list of members.

### Anything else?

Research findings:
The admin UI is performing the following requests to the Keycloak API during the move operation:

`GET /admin/realms/MYREALM/groups?first=0&max=11`
Returns the set of groups, including the nested child group with an ID of 4201f8c9-73a4-4071-bbc3-20583c3d0235
`DELETE /admin/realms/MYREALM/groups/4201f8c9-73a4-4071-bbc3-20583c3d0235`
Deletes the nested child group and all of its members
`POST /admin/realms/MYREALM/groups`
Creates a new group with an ID of feb1fdb8-9cc8-494f-b496-c8389acdadfb
`GET /admin/realms/MYREALM/groups/4201f8c9-73a4-4071-bbc3-20583c3d0235/role-mappings`
Returns 404 since that group was deleted
`GET /admin/realms/MYREALM/groups/4201f8c9-73a4-4071-bbc3-20583c3d0235/members?first=0&max=11`
Returns 404 since that group was deleted
`GET /admin/realms/MYREALM/groups/4201f8c9-73a4-4071-bbc3-20583c3d0235`
Returns 404 since that group was deleted
`GET /admin/realms/MYREALM/ui-ext/groups?first=0&max=21&exact=false`
Returns the set of groups, including a root-level group with an ID of feb1fdb8-9cc8-494f-b496-c8389acdadfb, but no group with an ID of 4201f8c9-73a4-4071-bbc3-20583c3d0235
`GET /admin/realms/MYREALM/ui-ext/groups?first=0&max=21&exact=false`
Same result as the previous request

Examining the admin-ui client code in js/apps/admin-ui/src/groups/components/MoveDialog.tsx, the function "moveToRoot" begins with the following lines, which appear to be responsible for the DELETE and POST requests above:
```
  await adminClient.groups.del({ id: source.id! });
  const { id } = await adminClient.groups.create({
    ...source,
    id: undefined,
  });
```

In contrast, the "moveToGroup" function, which is used for all other group moves, performs the following operation:
`    await adminClient.groups.setOrCreateChild({ id: dest.id! }, source);`
This results in the following API request:
`POST /admin/realms/MYREALM/groups/{parent-group-id}/children`
Which makes the posted group object a child of the specified parent group. This operation works correctly without losing the members associated with the group. However, it won't work for moving to the root-level, since there is no parent group to specify.

After some research, I found a solution, which involves performing the following API request:
`POST /admin/realms/MYREALM/groups`
With a JSON object payload containing at least two properties, the "id" and "name" from the group to be moved to the root-level.

I have verified that this method works correctly for moving a group from a child position to the root-level without loss of members. It appears that this is the intended way for groups to be moved to root, since the addTopLevelGroup method in the services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java file contains code specifically for this purpose as follows:

```
        String groupName = rep.getName();

        if (ObjectUtil.isBlank(groupName)) {
            throw ErrorResponse.error("Group name is missing", Response.Status.BAD_REQUEST);
        }

        try {
            if (rep.getId() != null) {
                child = realm.getGroupById(rep.getId());
                if (child == null) {
                    throw new NotFoundException("Could not find child by id");
                }
                realm.moveGroup(child, null);
                adminEvent.operation(OperationType.UPDATE).resourcePath(session.getContext().getUri());

```

Based on this, I believe the change that would correct the move behavior is to replace the first few lines in the "moveToRoot" function referenced previously with the following code.

```
  const { id } = source;
  await adminClient.groups.create(source);

```

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #20615, supersedes #20624

### CODE REVIEW

File: js/apps/admin-ui/src/groups/components/MoveDialog.tsx [hunk 1]
```diff
@@ -11,39 +11,13 @@ type MoveDialogProps = {
...
-) => {
-  try {
-    await adminClient.groups.setOrCreateChild({ id: dest.id! }, source);
-  } catch (error: any) {
-    if (error.response) {
-      throw error;
-    }
-  }
-};
+) => adminClient.groups.setOrCreateChild({ id: dest.id! }, source);
```
Comment (daniel-brannon) [inline js/apps/admin-ui/src/groups/components/MoveDialog.tsx:20]: Removing the try catch here will cause the exception to be caught on line 31 below, which "handles" all exceptions by displaying an error in the UI. This is not desirable, since the operation actually succeeds. The problem originates in the file js/libs/keycloak-admin-client/src/resources/agent.ts, requestWithParams function. If the returnResourceIdInLocationHeader is set in that function, it expects the HTTP response to include a Location header, from which it can extract the generated resource Id. The adminClient.groups.create(...) and adminClient.groups.setOrCreateChild(...) methods, which are implemented in js/libs/keycloak-admin-client/src/resources/groups.ts, both set the returnResourceIdInLocationHeader parameter, because a new resource is created in some cases, and thus the Id needs to be retrieved. If you want to avoid an exception being thrown in the case where a new resource is not to be created, such as when an existing resource is passed in to these methods to be updated, then the code in the requestWithParams method should be modified to check for this condition. Unless that change is made, the original try-catch in this file should be kept to avoid displaying an error when there is none.

**Review by edewit — CHANGES_REQUESTED** [review]
Yes this no longer works it always gives an error:
image

**Comment by daniel-brannon** [comment]
@jonkoops I appreciate your effort to improve the error handling in the codebase. However, I still think that my original pull request  #20624 is a better solution for this bug than your pull request #20820. Here are my reasons:

- My pull request fixes the bug without showing an error to the user, while your pull request shows an error even though the operation succeeds. This is confusing and misleading for the user.
- My pull request maintains the consistency of the error handling in the file, while your pull request removes a try-catch block that is necessary to handle a specific exception thrown by the adminClient.groups.create() function call. This exception is thrown because the function expects a Location header in the response, which is not present when an existing group is updated. This exception should be ignored, as it does not indicate a failure of the operation.
- My pull request follows the same pattern of error handling as the moveToGroup function, which also calls the adminClient.groups.setOrCreateChild() function and catches and ignores the same exception. This makes the code easier to understand and maintain.

Given these reasons, I respectfully ask you to consider reopening and merging my pull request #20624, and closing your pull request #20820. I believe this would be the best way to fix this bug quickly and effectively, while also preserving the quality and consistency of the codebase. In any case, I'm sure the users of Keycloak, myself included, would appreciate a fix for this serious data loss issue as soon as possible. Thank you for your time and attention.

**Comment by jonkoops** [comment]
I have to disagree, this should be fixed properly. From what I am seeing here, the Admin Client should not be throwing an error in this case, so let's fix that first.

**Comment by jonkoops** [comment]
I've split the combined create/update methods into separate calls. It now checks if there is an `id` defined on a group in order to make the correct call. This prevents instances where an ID might be expected in a header, but is not returned.

**Review by edewit — APPROVED** [review]
works, I like it...
