### PR TITLE
trigger IDENTITY_PROVIDER_FIRST_LOGIN (and UPDATE_PROFILE ) event when identity provider flow succeeds

### LINKED ISSUE #15098: IDENTITY_PROVIDER_FIRST_LOGIN is never triggered
### Describe the bug

The event `IDENTITY_PROVIDER_FIRST_LOGIN` can be useful, if one would like to trigger some action whenever there is one (by creating a custom EventListenerProvider), or simply for auditing purposes by storing it. 

It seems like the event is used  here: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L759

However, it seems like the event is never triggered because the `.success()` method is never called. 

### Version

19.0.2

### Expected behavior

The `IDENTITY_PROVIDER_FIRST_LOGIN` should be triggered

### Actual behavior

The `IDENTITY_PROVIDER_FIRST_LOGIN` is not triggered

### How to Reproduce?

* create a demo realm
* add an identity provider of your choice (I tested using Google)
* activate event auditing, by going to Realm settings -> Events -> User events settings -> and then activate save events and hit save. 
* navigate to the account console from a different browser session (e.g private window): http://localhost:8081/auth/realms/YOUR_TEST_REALM_NAME/account/#/
* try logging in using the identity provider you configured
* Go back to the admin console -> and check the events that got triggered. 

You will find the following events:
* CODE_TO_TOKEN
* LOGIN
* REGISTER

but not the IDENTITY_PROVIDER_FIRST_LOGIN

### Anything else?

This can be fixed simply by adding `event.success()` (checkout the PR for more details)
The only thing to note is that the user is not created yet at this point, so the user field in the event will be null / empty. Here is an example entry:
localhost_8081_auth_admin_master_console_

### PR DESCRIPTION
**Pull request by zak905**
fixes #15098

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/LoginActionsService.java [hunk 1]
```diff
@@ -815,6 +815,7 @@ public Response authenticateOnly() throws AuthenticationFlowException {
             protected Response authenticationComplete() {
                 if (firstBrokerLogin) {
                     authSession.setAuthNote(AbstractIdpAuthenticator.FIRST_BROKER_LOGIN_SUCCESS, identityProviderAlias);
+                    event.success();
```
Comment (nicolasiannarilli) [inline services/src/main/java/org/keycloak/services/resources/LoginActionsService.java:818]: Why not send the event "IDENTITY_PROVIDER_POST_LOGIN" at the same time ?

Comment (zak905) [reply services/src/main/java/org/keycloak/services/resources/LoginActionsService.java:818]: I think only one of the two should be triggered, not both, as you can see here:  https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L755

however, thanks for drawing my attention to that. Now I need to slightly change the `event.success()` call to be outside of the if.

**Review by pedroigor — COMMENTED** [review]
@zak905 Thanks.

We should also call `error` when the flow did not completed successfully to keep consistency with other events.

**Comment by zak905** [comment]
Hi @pedroigor, thanks. I have added the `error` call when an exception is thrown or checks fail. It seems like this change set causes the Base IT (2) tests to fail: https://github.com/keycloak/keycloak/actions/runs/4174238327/jobs/7227727357, any hints on how I can run those tests locally so that I can debug ?

File: services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java [hunk 2]
```diff
@@ -107,7 +107,6 @@ protected boolean requiresUpdateProfilePage(AuthenticationFlowContext context, S
     @Override
     protected void actionImpl(AuthenticationFlowContext context, SerializedBrokeredIdentityContext userCtx, BrokeredIdentityContext brokerContext) {
         EventBuilder event = context.getEvent();
-        //velias: looks like UPDATE_PROFILE event is not fired. IMHO it should not be fired here as user record in keycloak is not changed, user doesn't exist yet
```
Comment (zak905) [inline services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java:110]: this comment is not revlevant anymore, because now `UPDATE_PROFILE` is triggered

**Comment by zak905** [comment]
I was able to run the tests locally and fix following the guides in https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md. I also noticed that in addition to `IDENTITY_PROVIDER_FIRST_LOGIN`, the `UPDATE_PROFILE` is also triggered properly.

**Review by mposolda — APPROVED** [review]
@zak905 Thanks! The change looks good. Hopefully tests will be OK.

I've updated your branch to make sure that tests are executed against latest Keycloak main.

**Comment by zak905** [comment]
Great thanks!
