### PR TITLE
Don't update the client session's timestamp when loading it from the database

### LINKED ISSUE #38591: Persistent User Sessions doesn't track staleness of client sessions
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I came across a situation where all client sessions are kept alive when any of the client sessions of the user session was refreshed when persistent sessions are enabled. 

Still, If the user session times out, the client sessions are timed out as well.

Reason: This snippet of code which was probably true with offline sessions (only one offline client session per offline user sessions):

https://github.com/keycloak/keycloak/blob/9861acc2aaa6b8d588ef1155563c1f652ec08d28/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java#L749-L750

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

If the expiry time of a client session has been reached, it shouldn't be allowed to refresh its token

### Actual behavior

The client session staleness is calculated from the user session's last updated

### How to Reproduce?

Manual setting the `timestamp` in the client session table to 0, and then restarting Keycloak to clear the caches.

### Anything else?

I'll create a PR

### PR DESCRIPTION
**Pull request by ahus1**
(at least for online sessions)

Closes #38591

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java [hunk 1]
```diff
@@ -1743,8 +1747,104 @@ public void refreshTokenClientSessionMaxLifespan() throws Exception {
...
+            assertThat(sessionId, Matchers.equalTo(tokenResponse2.getSessionState()));
+
+            setTimeOffset(100);
+
+            tokenResponse2 = oauth.doRefreshTokenRequest(tokenResponse2.getRefreshToken());
+            assertEquals(200, tokenResponse2.getStatusCode());
+            assertTrue("Invalid RefreshExpiresIn: " + tokenResponse2.getRefreshExpiresIn(), 0 < tokenResponse2.getRefreshExpiresIn() && tokenResponse2.getRefreshExpiresIn() <= 500);
+
+            // Clear all entries from the cache to enforce re-loading the data from the database
+            testingClient.server("test").run(session -> {
```
Comment (mhajas) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java:1807]: So if I understand correctly this issue is not reproducible if we use caches because if we have a cache hit we are not loading from the database, therefore not updating timestamp of client sessions and therefore correctly refusing to refresh token for the client. Is it correct?

Couple more questions:
1. I am confused about how it is possible the test is failing in the current state. I would expect this cleaning of caches needs to be done before line 1802. I would expect that in the current version line 1802 finds the client session for `test-app2` in cache and therefore the codepaths you changed (that are changing timestamp for all client sessions for the user session) are not called. Am I thinking about this incorrectly? Do we not cache client sessions when we create it on line 1793?  
2. Should we run some tests in CI without session caches as this is default for multi-site?

**Review by mhajas — COMMENTED** [review]
Thanks for the fix. Could you have a look at my comments?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java (hunk 1 above)
Comment (ahus1) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java:1807]: ad 1: There are three situations when you read an entry from the database: (a) if there are more sessions than the size of the cache allows - currently 10_000 entries in both the user sessions and client sessions cache (b) if you restart the KC cluster, and the cache is empty (c) in the multi-site setup, and I haven't thought about it before you mentioned it.

ad 2: we could in a follow-up issue, still I think it wouldn't have found this issue as a lot of things would need to come together. We have some tests in OfflineSessionPersistenceTest in the model tests that it simulate a restart and load sessions from the database again.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java [hunk 2]
```diff
@@ -1743,8 +1747,104 @@ public void refreshTokenClientSessionMaxLifespan() throws Exception {
...
+                if (Profile.Feature.PERSISTENT_USER_SESSIONS.isAvailable()) {
```
[the remark this answers is not in the document]
Comment (ahus1) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java]: Agreed, it is now removed.

**Review by mhajas — APPROVED** [review]
Thanks for the fix @ahus1
