### PR TITLE
Fix compilation error with ServerInfoAdminResource

### LINKED ISSUE #24962: ServerInfoAdminResource fails to compile on Eclipse compiler
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

There is small incompatibility in the code that prevents me to use JDT / Eclipse Java Compier to compile Keycloak in vscode.

### Version

main

### Expected behavior

It should be possible to run/debug Keycloak under vscode / Eclipse.

### Actual behavior

Admin console does not open correctly, instead it prints error "Network response was not OK." and following exception is visible in logs

```
2023-11-23 12:21:18,820 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.Error: Unresolved compilation problems: 
	Type mismatch: cannot convert from Map<Boolean,Object> to Map<Boolean,List<String>>
	The method listCombiner(List<T>, List<T>) in the type ServerInfoAdminResource is not applicable for the arguments (Object, Object)

	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.<init>(ServerInfoAdminResource.java:111)
ServerInfoAdminResource.java:111
	at org.keycloak.services.resources.admin.AdminRoot.getServerInfo(AdminRoot.java:275)
AdminRoot.java:275
	at org.keycloak.services.resources.admin.AdminRoot$quarkusrestinvoker$getServerInfo_af58ef46002deb1ad4721c04a79203aeec92de8e.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
InvocationHandler.java:29
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
QuarkusResteasyReactiveRequestContext.java:141
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
AbstractResteasyReactiveContext.java:145
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
VertxCoreRecorder.java:576
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
EnhancedQueueExecutor.java:2513
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
EnhancedQueueExecutor.java:1538
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
DelegatingRunnable.java:29
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
ThreadLocalResettingRunnable.java:29
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
FastThreadLocalRunnable.java:30
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

1. Compile code initially with maven on command line `mvn clean install -DskipTests`
2. Open vscode, wait for it to compile the code again again
3. Run Keycloak in vscode debugger
4. Load the admin console in browser and observe the failure

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tsaarni**
This change fixes following type inference error when compiling the code with Eclipse JDT compiler:

* Type mismatch: cannot convert from Map<Boolean,Object> to Map<Boolean,List<String>>

The fix allows developers to use vscode or Eclipse to work on Keycloak code. 

Fixes #24962

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java [hunk 1]
```diff
@@ -113,7 +113,7 @@ public ServerInfoRepresentation getInfo() {
                                 Collectors.toMap(
                                         ClientSignatureVerifierProvider::isAsymmetricAlgorithm,
                                         clientSignatureVerifier -> Collections.singletonList(clientSignatureVerifier.getAlgorithm()),
-                                        (l1, l2) -> listCombiner(l1, l2)
+                                        (l1, l2) -> ServerInfoAdminResource.<String>listCombiner(l1, l2)
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java:116]: Sorry about the nitpick. It works too. 

However, we introduce a warning because the type can be inferred too. What if we just expand this lambda to an anonymous class? By removing the warning it also helps to avoid accidentaly removing the type because of the warning.

**Review by pedroigor — CHANGES_REQUESTED** [review]

File: services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java (hunk 1 above)
Comment (tsaarni) [reply services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java:116]: Thanks @pedroigor no problem! though I wonder would following alternative work without warning?

```diff
diff --git a/services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java b/services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
index 9b66c7f8be..a23bf90c0c 100755
--- a/services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
+++ b/services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
@@ -113,10 +113,12 @@ public class ServerInfoAdminResource {
                                 Collectors.toMap(
                                         ClientSignatureVerifierProvider::isAsymmetricAlgorithm,
                                         clientSignatureVerifier -> Collections.singletonList(clientSignatureVerifier.getAlgorithm()),
-                                        (l1, l2) -> listCombiner(l1, l2)
-                                                .stream()
-                                                .sorted()
-                                                .collect(Collectors.toList()),
+                                        (l1, l2) -> {
+                                            List<String> result = listCombiner(l1, l2);
+                                            return result.stream()
+                                                    .sorted()
+                                                    .collect(Collectors.toList());
+                                        },
                                         HashMap::new
                                 )
                         );
```

BTW how / where could I see the warning? I did not find it while compiling on command line. I've also got sonarlint and checkstyle but I did not seem to get the warning that it could be inferred.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java]: I see the warning in my InteliJ not really when running a java compiler. The syntax above also works for me ...

I hope you see my point ... Just want to avoid someone reverting your change because the type `<String>` is marked as unnecessary (at least in IntelliJ which a lot of people are using here). Refactoring the code to a lambda is a more drastic change ....

A nitpick, otherwise we can just merge it as is.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
If someone reverts we fix again :)

**Comment by pedroigor** [comment]
Btw, I was able to reproduce when changing compiler in InteliJ to use Eclipse compiler. There are other tweaks that I had to do too, like removing generated classes for logging classes, to get a successful compilation. But it works ...
