### PR TITLE
12653 check if fine-grained permissions are enabled before retrieving…

### LINKED ISSUE #12653: Brief representation user retrieval on Admin API: only check group memberships when fine-grained permissions are enabled
### Describe the bug

Keycloak checks for permissions to manage users via group membership of users even if fine-grained permissions are not enabled.

### Version

18.0.1

### Expected behavior

Group memberships of users are only checked when retrieving brief representations of users when fine-grained permissions are actually enabled.

### Actual behavior

Group memberships are retrieved for every user  when retrieving brief representations of users even though fine-grained permissions are actually disabled.

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sschu**
… group memberships of users

Fixes https://github.com/keycloak/keycloak/issues/12653

### CODE REVIEW

**Comment by sschu** [comment]
@hmlnarik I isolated this one out of [the other PR.](https://github.com/keycloak/keycloak/pull/12168).  I will continue with the rest tomorrow...

File: services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java [hunk 1]
```diff
@@ -262,7 +262,7 @@ public void requireManage() {
      */
     @Override
     public boolean canManage(UserModel user) {
-        return canManage() || canManageByGroup(user);
+        return canManage() || (Profile.isFeatureEnabled(Profile.Feature.AUTHORIZATION) && canManageByGroup(user));
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java:265]: Shouldn't we check `org.keycloak.common.Profile.Feature#ADMIN_FINE_GRAINED_AUTHZ` instead?

Comment (sschu) [reply services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java:265]: @pedroigor Could be possible, but I basically just copied how it is done elsewhere like here: https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java#L254
Its basically like that all over the place. ;)

Comment (sschu) [reply services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java:265]: @pedroigor Any feedback from your side?

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java:265]: Sorry. My last comment is because `AUTHORIZATION` should always be enabled. But not the `ADMIN_FINE_GRAINED_AUTHZ` feature.

So I'm wondering what difference that condition makes if you remove it or at least change it to `ADMIN_FINE_GRAINED_AUTHZ` if there is a difference.

Comment (sschu) [reply services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java:265]: @pedroigor If `AUTHORIZATION`is always enabled but the `ADMIN_FINE_GRAINED_AUTHZ` is the correct one to use, it is probably used wrong all over the place. There is only one place where `ADMIN_FINE_GRAINED_AUTHZ` is used: https://github.com/keycloak/keycloak/blob/820ab52dce148eae0d51ba194ba9248bf83a69c6/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L191

`AUTHORIZATION` is used much more often and I assume it's used wrong in these places:
https://github.com/keycloak/keycloak/blob/cdef39f76c50506681227b627e678bdbf15779a4/services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java#L86

https://github.com/keycloak/keycloak/blob/cdef39f76c50506681227b627e678bdbf15779a4/services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissions.java#L64

https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java#L76

https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java#L254

https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java#L265

I especially find https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java#L254

dangerous, as the decision that fine-grained permissions are not used is essentially taken by searching for a resource server for the realm-management client and not finding it in:

https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java#L259

This would mean that if fine-grained permissions were enabled before and a resource server was created for the realm management client, they would still be used even after the profile was changed to not support fine-grained permissions.

WDYT?

**Comment by sschu** [comment]
@pedroigor Any feedback?

**Comment by pedroigor** [comment]
@sschu You are right, I think those checks are outdated and referring to the time when authorization services was still tech preview.

The reason it works, partially, is that there is a check for resource servers and policies. So if you don't have them created fine-frained admin permissions won't be evaluated. Otherwise, if you enable, setup permissions, and disabled, they will be still running.

From a security perspective, I think this is not so bad because fine-grained permissions should be more restrictive. But definetly not the behavior we want.

So yeah, I think we should update everything to use fine-grained feature instead.

**Comment by sschu** [comment]
@pedroigor I updated this PR to use the correct profile feature name. I will file a bug and send a PR to change all the other places where the feature name was not used correctly.

**Comment by sschu** [comment]
@pedroigor If you like my updates to the other PR, I would probably change this to not check explicitly for the feature flag but for `authz!=null` and move it into `can(View|Manage)ByGroup`.

**Comment by sschu** [comment]
@pedroigor I changed the implementation to be in line with the changes in https://github.com/keycloak/keycloak/pull/13648.
The test failures seem to be unrelated...

**Review by pedroigor — APPROVED** [review]
