### PR TITLE
Move transaction processing into session close

### LINKED ISSUE #15223: Make sure the KeycloakSession is not closed more than once
### Description

Currently, the `KeycloakSession` does not have any mechanism to control whether the client code is performing operation after the session has been closed.

We need to make sure a closed session is not used after being closed otherwise it might cause unexpected behavior and indicate its usage is not correct. It should also indicate whether or not we are properly handling the request lifecycle.

### Discussion

https://github.com/keycloak/keycloak/issues/15192

### Motivation

Properly handle closed sessions.

### Details

_No response_

### PR DESCRIPTION
**Pull request by hmlnarik**
Fixes: #15223

### CODE REVIEW

**Comment by hmlnarik** [comment]
I have kept calls `session.getTransactionManager().begin();` mandatory in this version, but am inclined to make this call implicit upon any call to `KeycloakTransactionManager.enlist*` methods, which would simplify it even more. OTOH, this PR provides minimal solution to the transaction management encapsulation which could be then leveraged in #15193.

**Comment by pedroigor** [comment]
@hmlnarik Can you please rebase?

It is indeed a great step towards removing boilerplate code. As a follow-up, I would like to discuss more how we can actually improve the API to make the intention clear for the different use cases where a session is used.

**Comment by hmlnarik** [comment]
@pedroigor Could you re-review please?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java [hunk 1]
```diff
@@ -49,22 +49,20 @@ default KeycloakSession create() {
      *
      * @param session a transactional session
      */
-    default void close(KeycloakSession session) {
-        if (DefaultKeycloakSession.class.cast(session).isClosed()) {
-            return;
-        }
+    default void close() {
+        RoutingContext context = ResteasyContext.getContextData(RoutingContext.class);
```
Comment (pedroigor) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:53]: Can we just get the session as an argument? I don't think we need to resolve contextual data if the expected instance can be easily passed to the method.

Comment (hmlnarik) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:53]: Sadly, no: the session could be attempted to be closed twice that way. This led to duplicate closing of the same session.

Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:53]: I see.

I do not think we should be adding more method calls if we can just avoid it by checking if the session is closed. As I've proposed before. Looks like a nitpick but I'm really trying to avoid unnecessary logic when processing the request lifecycle.

I know we have some divergences about adding the  `isClosed` method. So I would leave it to others to comment here.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java [hunk 2]
```diff
@@ -159,24 +159,20 @@ private void createAdminUser() {
...
-            session.getTransactionManager().rollback();
-            ServicesLogger.LOGGER.addUserFailed(t, adminUserName, Config.getAdminRealm());
-        } finally {
-            session.close();
+            try {
+                new ApplianceBootstrap(session).createMasterRealmUser(adminUserName, adminPassword);
+                ServicesLogger.LOGGER.addUserSuccess(adminUserName, Config.getAdminRealm());
+            } catch (IllegalStateException e) {
+                session.getTransactionManager().setRollbackOnly();
+                ServicesLogger.LOGGER.addUserFailedUserExists(adminUserName, Config.getAdminRealm());
```
Comment (stianst) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java:171]: Since the transaction is not closed until after this is executed I don't see how it will get the exception if the user already exists.

File: model/legacy-private/src/main/java/org/keycloak/services/scheduled/ClusterAwareScheduledTaskRunner.java [hunk 3]
```diff
@@ -44,8 +44,6 @@ public ClusterAwareScheduledTaskRunner(KeycloakSessionFactory sessionFactory, Sc
 
     @Override
     protected void runTask(final KeycloakSession session) {
-        session.getTransactionManager().begin();
```
Comment (stianst) [inline model/legacy-private/src/main/java/org/keycloak/services/scheduled/ClusterAwareScheduledTaskRunner.java:47]: How is the transaction started in this case?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java (hunk 1 above)
Comment (stianst) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:53]: I don't like relying on the context-data to be cleared as a way to "check if the session has been closed". I think what @pedroigor is suggesting would be nicer, and having a `isClosed` method on the session makes sense to me.

File: server-spi-private/src/main/java/org/keycloak/services/scheduled/ScheduledTaskRunner.java [hunk 4]
```diff
@@ -46,32 +46,23 @@ public ScheduledTaskRunner(KeycloakSessionFactory sessionFactory, ScheduledTask
...
+        try (KeycloakSession session = sessionFactory.create()) {
+            session.getTransactionManager().begin();
             if (transactionLimit != 0) {
                 KeycloakModelUtils.setTransactionLimit(sessionFactory, transactionLimit);
             }
             runTask(session);
         } catch (Throwable t) {
             logger.errorf(t, "Failed to run scheduled task %s", task.getClass().getSimpleName());
-
-            session.getTransactionManager().rollback();
```
Comment (stianst) [inline server-spi-private/src/main/java/org/keycloak/services/scheduled/ScheduledTaskRunner.java:58]: If there is an error how is the transaction now rolled-back?

File: services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java [hunk 5]
```diff
@@ -452,28 +454,68 @@ public ClientPolicyManager clientPolicy() {
...
+              getTransactionManager().isActive() ? " (transaction active" + (getTransactionManager().getRollbackOnly() ? ", ROLLBACK-ONLY" : "") + ")" : "",
+              StackUtil.getShortStackTrace());
+        }
+
         if (closed) {
-            throw new IllegalStateException("Illegal call to #close() on already closed KeycloakSession");
+            throw new IllegalStateException("Illegal call to #close() on already closed " + this);
+        }
+
+        RuntimeException re = closeTransactionManager();
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java:471]: Did we use to commit the transaction prior to closing the session (and providers) or the other way around?

File: services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java [hunk 6]
```diff
@@ -452,28 +454,68 @@ public ClientPolicyManager clientPolicy() {
...
+
+        try {
+            if (this.transactionManager.getRollbackOnly()) {
+                this.transactionManager.rollback();
+            } else {
+                this.transactionManager.commit();
+            }
+        } catch (RuntimeException re) {
+            if (this.transactionManager.isActive()) {
+                this.transactionManager.rollback();
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java:508]: Seems this can call rollback twice, if it fails above?

File: services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java [hunk 7]
```diff
@@ -346,37 +344,34 @@ public void importAddUser() {
...
+                                }
+                            } catch (Exception e) {
+                                session.getTransactionManager().setRollbackOnly();
+                                throw e;
                             }
-
-                            session.getTransactionManager().commit();
                         } catch (ModelDuplicateException e) {
-                            session.getTransactionManager().rollback();
                             ServicesLogger.LOGGER.addUserFailedUserExists(userRep.getUsername(), realmRep.getRealm());
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java:372]: This is not going to be triggered since the session/tx is closed later

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java [hunk 8]
```diff
@@ -258,6 +258,9 @@ private ProcessBuilder getProcessBuilder() {
         }
 
         addStorageOptions(storeProvider, commands);
+        if (System.getProperty("auth.server.quarkus.log-level") != null) {
+            commands.add("--log-level=" + System.getProperty("auth.server.quarkus.log-level"));
+        }
```
Comment (stianst) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java:263]: Why is this being added? We have built-in support for configuring logging for the Quarkus dist

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java [hunk 9]
```diff
@@ -474,7 +474,7 @@ public boolean test(AuthenticationFlowRepresentation rep) {
         } catch (InternalServerErrorException isee) {
             try (Response response = isee.getResponse()) {
                 assertEquals(500, response.getStatus());
-                assertFalse(StreamUtil.readString((InputStream) response.getEntity(), Charset.forName("UTF-8")).toLowerCase().contains("exception"));
+                assertEquals(0, response.getLength());
```
Comment (stianst) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java:477]: Why is this changed?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java [hunk 10]
```diff
@@ -76,18 +76,29 @@ private boolean ignoreContext(RoutingContext context) {
 
     private Runnable createBlockingHandler(RoutingContext context) {
```
Comment (stianst) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:77]: I'm completely lost in the number of filters/interceptors/etc, so got no clue what's going on here and can't review this stuff properly

**Review by stianst — COMMENTED** [review]
See inline comments

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java (hunk 2 above)
Comment (hmlnarik) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java:171]: Good catch. Changed to `runJobInTransaction`.

File: model/legacy-private/src/main/java/org/keycloak/services/scheduled/ClusterAwareScheduledTaskRunner.java (hunk 3 above)
Comment (hmlnarik) [reply model/legacy-private/src/main/java/org/keycloak/services/scheduled/ClusterAwareScheduledTaskRunner.java:47]: It is started in the parent: `ScheduledTaskRunner.run` which calls `runTask`

File: server-spi-private/src/main/java/org/keycloak/services/scheduled/ScheduledTaskRunner.java (hunk 4 above)
Comment (hmlnarik) [reply server-spi-private/src/main/java/org/keycloak/services/scheduled/ScheduledTaskRunner.java:58]: This is done in `close` method invoked at the end of the try-with-resources block, specifically in `DefaultKeycloakSession.closeTransactionManager`

File: services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java (hunk 5 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java:471]: First the transaction manager was closed, then session was closed, see https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/filters/AbstractRequestFilter.java#L58-L69

File: services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java (hunk 6 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java:508]: Upon rollback, TM will turn into inactive mode. Thus this line will not be reached. But you are right that this applies to commit too, so this condition is redundant and will be removed.

File: services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java (hunk 7 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java:372]: Will be resolved by using standard `KeycloakModelUtils.runJobInTransaction` mechanism.

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java (hunk 8 above)
Comment (hmlnarik) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java:263]: To have this support available in integration auth-server-quarkus. Without this addition, it is not possible to pass in the logging parameter into the tested server.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java (hunk 9 above)
Comment (hmlnarik) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java:477]: It's revert from the https://github.com/keycloak/keycloak/pull/15193/files#diff-40281afe608b4070873d6915e1e4070f0f091611294e6450fbd50863a6154e86L468.

File: server-spi-private/src/main/java/org/keycloak/services/scheduled/ScheduledTaskRunner.java (hunk 4 above)
Comment (stianst) [reply server-spi-private/src/main/java/org/keycloak/services/scheduled/ScheduledTaskRunner.java:58]: That looks like it's committing the TX, not rolling it back?

File: services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java (hunk 7 above)
Comment (stianst) [reply services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java:368]: Relying on KeycloakModelUtils (which is beyond messy and an anti pattern IMO) is not great here. I'd honestly rather then have some method on the session factory or something that does this.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java [hunk 11]
```diff
@@ -76,18 +76,29 @@ private boolean ignoreContext(RoutingContext context) {
...
         return () -> {
-            KeycloakSession session = configureContextualData(context);
+            configureContextualData(context);
 
             try {
-                context.next();
+                context.addBodyEndHandler(event -> close(context));
```
Comment (pedroigor) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java:82]: You are introducing some of the issues fixed here https://github.com/keycloak/keycloak/pull/15193.

Also, this method is not supposed to be used for resource cleanup.

FYI, most of the time the session is closed from the response filter/interceptors as they run within the same worker thread and right after the response is created from JAX-RS resource methods.

Closing the session here in this top-level filter is to make sure the session is actually closed (we can easily check for "session leaks" here as well plus avoid dispatching requests if they can be served directly from an event loop thread) as well as make sure the session is closed when Resteasy handlers are not executed.

Differently from Resteasy Reactive, Resteasy Classic does not provide a single point to hook all the logic to manage the request lifecycle. That is about to change once we move to Resteasy Reactive.

**Review by pedroigor — CHANGES_REQUESTED** [review]

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java (hunk 1 above)
Comment (hmlnarik) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:53]: The session is created by the filter/interceptor/handler chain and should be closed in there.
Thus it is the handler chain which owns the session, an it maintains its state in the context data.
The session itself is not aware of when it should be closed.
Hence it seems to me that it should be the handler chain which should hold the state of the session, and to precisely define when it should be closed, and call `close` accordingly.
Relying on the active/closed state in the session to determine whether it should be closed object seems like violation of the encapsulation to me.

If this should be changed to a `isClosed` method regardless, I can do that. Let me know your thoughts.

Comment (hmlnarik) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java]: This part will be removed in the next round

**Review by pedroigor — DISMISSED** [review]

File: server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java [hunk 12]
```diff
@@ -263,27 +262,17 @@ public static void runJobInTransaction(KeycloakSessionFactory factory, KeycloakS
...
+                result = callable.run(session);
+            } catch (Throwable t) {
+                session.getTransactionManager().setRollbackOnly();
+                throw t;
             }
-            throw re;
-        } finally {
-            session.close();
+        } catch (RuntimeException e) {
+            throw e;
```
Comment (stianst) [inline server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java:275]: Is this needed?

File: services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java [hunk 13]
```diff
@@ -88,13 +88,15 @@ public class DefaultKeycloakSession implements KeycloakSession {
...
     private ClientPolicyManager clientPolicyManager;
-
-    private boolean closed;
+    private boolean closed = false;
 
     public DefaultKeycloakSession(DefaultKeycloakSessionFactory factory) {
         this.factory = factory;
         this.transactionManager = new DefaultKeycloakTransactionManager(this);
         context = createKeycloakContext(this);
+        if (LOG.isDebugEnabled()) {
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java:97]: Perhaps this really should be trace level?

File: services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java [hunk 14]
```diff
@@ -452,31 +454,72 @@ public ClientPolicyManager clientPolicy() {
         return clientPolicyManager;
     }
 
+    private static final Logger LOG = Logger.getLogger(DefaultKeycloakSession.class);
+
     @Override
     public void close() {
+        if (LOG.isDebugEnabled()) {
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java:461]: Perhaps this really should be trace level?

File: services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java [hunk 15]
```diff
@@ -316,15 +315,14 @@ public void importRealm(RealmRepresentation rep, String from) {
...
-                if (!exists) {
-                    ServicesLogger.LOGGER.unableToImportRealm(t, rep.getRealm(), from);
-                }
+                session.getTransactionManager().setRollbackOnly();
+                throw t;
+            }
+        } catch (Throwable t) {
+            if (!exists) {
+                ServicesLogger.LOGGER.unableToImportRealm(t, rep.getRealm(), from);
             }
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java:325]: Does this really always work? Previously the commit was done prior to this catch, but now it's done by auto close, which happens after this catch doesn't it?

**Review by stianst — APPROVED** [review]
