### PR TITLE
Intermediate page(to confirmExecutionOfActions) after an ExecuteActionsEmail is not localized based on the user's locale

### LINKED ISSUE #17233: the InfoPage after an ExecuteActionsEmail is not localized based on the user's locale
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

In my case an execute-actions-email is sent to a user for them to update their password. After the user clicks on the link in the execute-action-email they will visit an infopage listing the actions to execute followed by the update-password-page. The infopage is translated according to the locale accepted by the browser-request but update-password-page is translated according to the locale set in the user's profile.

If these two locales are not equal the translation changes during the workflow.

### Version

20.0.5

### Expected behavior

The first page should be translated by the user's locale aswell.

### Actual behavior

The first page and the second page are translated differently if the browser-requested locale and the user-profile's locale are not equal. 

### How to Reproduce?

precondition:
- a realm with a working smtp config and two supported languages (for example: german and english)
- a browser without a cookie specifying a locale for keycloak that is set to one of the supported languages (for example: german)

1. create a user with a specific locale (for example: english)
2. trigger an execute-actions-email for the UPDATE_PASSWORD action
3. the email is in english
4. open the link send by mail in the browser
5. the infopage will open in german, the language accepted by the browser
6. the following update-password-page will open in englisch, the use-profile's locale

### Anything else?

I might have already identified the underlying issue: the authenticed user is not loaded into the loginformsprovider in ExecuteActionsActionTokenHandler::handleToken.

I plan to provide a pull-request shortly.

### PR DESCRIPTION
**Pull request by rishabhsvats**
Closes #17233

Checks if the UserModel is null before executing resolveLocale, and if indeed UserModel is null then performs resolveLocale using AuthenticationSessionModel.getAuthenticatedUser

### CODE REVIEW

**Comment by ahus1** [comment]
Pinging @mposolda as this references a core-client issue that has been closed due to a timeout.

File: services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java [hunk 1]
```diff
@@ -217,14 +217,20 @@ public Response createResponse(UserModel.RequiredAction action) {
...
         } catch (IOException e) {
             logger.error("Failed to create theme", e);
             return Response.serverError().build();
         }
+        if (user == null && this.authenticationSession != null) {
+            locale = session.getContext().resolveLocale(this.authenticationSession.getAuthenticatedUser());
+        }
+        else{
+            locale = session.getContext().resolveLocale(user);
+        }
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java:232]: @rishabhsvats There is `setUser` method in this class  to set the user and, checking other handlers, it is called (for example here in [VerifyEmailActionTokenHandler](https://github.com/keycloak/keycloak/blob/26.0.6/services/src/main/java/org/keycloak/authentication/actiontoken/verifyemail/VerifyEmailActionTokenHandler.java#L85). So better if, instead of adding this change, you just call this method in the `ExecuteActionsActionTokenHandler`:

```diff
diff --git a/services/src/main/java/org/keycloak/authentication/actiontoken/execactions/ExecuteActionsActionTokenHandler.java b/services/src/main/java/org/keycloak/authentication/actiontoken/execactions/ExecuteActionsActionTokenHandler.java
index 17bb665acc..d8b4b4bb26 100644
--- a/services/src/main/java/org/keycloak/authentication/actiontoken/execactions/ExecuteActionsActionTokenHandler.java
+++ b/services/src/main/java/org/keycloak/authentication/actiontoken/execactions/ExecuteActionsActionTokenHandler.java
@@ -90,6 +90,7 @@ public class ExecuteActionsActionTokenHandler extends AbstractActionTokenHandler

             return session.getProvider(LoginFormsProvider.class)
                     .setAuthenticationSession(authSession)
+                    .setUser(authSession.getAuthenticatedUser())
                     .setSuccess(Messages.CONFIRM_EXECUTION_OF_ACTIONS)
                     .setAttribute(Constants.TEMPLATE_ATTR_ACTION_URI, confirmUri)
                     .setAttribute(Constants.TEMPLATE_ATTR_REQUIRED_ACTIONS, token.getRequiredActions())
```

I see there are no tests for this, so just adding this line would be OK.

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @rishabhsvats! I added a comment with another way of fixing this. I prefer my sugestion as it's qwhat other handlers are doing. WDYT?

~~Besides he issue you are attaching #17233 is closed. So please create a new issue, it can be not internationalized page for the  ExecuteActionsActionTokenHandler for example. And then update the commit with the new issue number.~~

I saw the issue was just closed by inactivity, I though initially it was closed because it was another problem. Just consider calling the `setUser` method.

**Comment by rmartinc** [comment]
@rishabhsvats  Forget about the issue. I saw it was closed by inactivity I have just reopened it.

**Review by jonkoops — APPROVED** [review]

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @rishabhsvats! It's OK to me but please sign the commit `git commit --amend --signoff`.

**Comment by rishabhsvats** [comment]
@rmartinc thanks a lot for the feedback. I agree this will be cleaner way to resolve this issue. I have updated the PR with the change to setUser in ExecuteActionsActionTokenHandler#handleToken.

**Review by mposolda — APPROVED** [review]

**Review by rmartinc — APPROVED** [review]
Thanks @rishabhsvats!
