### PR TITLE
fixes navigation when searching for groups

### LINKED ISSUE #25927: UI crash after using breadcrumb group navigation during an active group search
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After searching for a nested group in the groups section, the usage of the breadcrumb navigation (above the group title) ends in a UI crash.

### Version

23.0.3

### Expected behavior

I'd expect the same behaviour during the `search mode` as it would behave, if I manually navigate to the nested group only using the tree navigation.

### Actual behavior

As soon I use the breadcrumb navigation (after I searched, and selected a child group), the UI crashes and needs to be hard-refreshed.

Before the UI crashes, I see a 404 HTTP error from the API, which is not there, if I manually select the groups from the three view.

I have two groups:

* top-level group (`a997ad23-605e-4b77-927e-c3a0daeb4c11`)
* second-level group (`5a12534d-48fe-4042-804b-9a12e1cde4f9`)

If i select the top-level group from the breadcrumb, the following api call ends in a 404.

```http
GET /admin/realms/Github-Issue/groups/5a12534d-48fe-/children
```
instead of:
```http
GET /admin/realms/Github-Issue/groups/a997ad23-605e-4b77-927e-c3a0daeb4c11/children
```

> It seems, the generated links for the breadcrumb are broken (in search mode). The group id in the path parameter looks like the first part of the second-level group, instead of the group id of the parent. 

As result of the broken links, the UI has problems to handle this.

```javascript
TypeError: b is null
    Fe KeycloakDataTable.tsx:240
    is KeycloakDataTable.tsx:341
    uc useFetch.ts:33
    promise callback*uc/< useFetch.ts:31
    React 10
    a SubGroupsContext.tsx:24
    onClick GroupBreadCrumbs.tsx:38
    O index.js:746
    React 16
    <anonymous> main.tsx:20
react-dom.production.min.js:10:71285
```

ui-crash

### How to Reproduce?

1. Create a top-level group in the Groups section
2. Create second-level group as child of the top-level group
3. Search for the second-level group via the search bar
4. Select the second-level group from the tree view
5. Try to navigate now via the breadcrumb navigation to the top-level group

### Anything else?

_No response_

### LINKED ISSUE #26036: subgroups clickopen not working
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In the group-tree, when clicking a group, the tree is refreshed and therefore collapsed. This also makes it impossible to see subgroups in the tree.

### Version

23.0.4

### Expected behavior

The tree should not refresh

### Actual behavior

The tree refreshes

### How to Reproduce?

Create a group, with a subgroup, try to go to the subgroup from the tree.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #25927
closes #26036
also supersedes #26036 

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

File: js/apps/admin-ui/src/groups/components/GroupTree.tsx [hunk 1]
```diff
@@ -314,14 +312,18 @@ export const GroupTree = ({
...
-            const id = item.id?.substring(item.id.lastIndexOf("/") + 1);
-            const subGroups: GroupRepresentation[] = [];
-            findGroup(groups, id!, [], subGroups);
-            setSubGroups(subGroups);
+
+            const path = findGroup(data, item.id!, []);
+            if (!subGroups.every(({ id }) => path.find((t) => t.id === id)))
+              clear();
 
             if (canViewDetails || subGroups.at(-1)?.access?.view) {
```
Comment (pkeuter) [inline js/apps/admin-ui/src/groups/components/GroupTree.tsx:320]: Not specifically related to this fix, but when fine grained permissions are enabled, this check is not sufficient because it will not check access to the selected item and therefore will always show the `noViewRights`

Comment (edewit) [reply js/apps/admin-ui/src/groups/components/GroupTree.tsx:320]: @pkeuter could you make a separate issue for that?

Comment (pkeuter) [reply js/apps/admin-ui/src/groups/components/GroupTree.tsx:320]: Done. See https://github.com/keycloak/keycloak/pull/26230
