### PR TITLE
fix: adding type validation and lazily adding cli options

### LINKED ISSUE #42960: KC_VERBOSE is not honored for a fast start
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Support for KC_VERBOSE works only if picocli fully runs - it's handled as a side effect in the Main command,

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

KC_VERBOSE should still work.

### Actual behavior

KC_VERBOSE does not work.

### How to Reproduce?

KC_VERBOSE=true ./kc.sh ...

### Anything else?

_No response_

### LINKED ISSUE #43466: Picocli refinements
### Description

Picocli logic only performs type validation when using the cli, this means that putting invalid values in the ENV or keycloak.conf will have different, and potentially quarkus specific messages.

Also to increase the performance of picocli we should defer adding all of the options until they are needed.

### Discussion

_No response_

### Motivation

To increase consistency and performance.

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #43466

I realize that I tied two things that don't necessary need to go together into this pr. If you want they can be separated.

There's at least one more optimization I could do on top of this, but I think that the performance between using picocli and using fast-start is close enough that I can next resolve https://github.com/keycloak/keycloak/issues/42960 and https://github.com/keycloak/keycloak/issues/38790 by just eliminating fast start. @mabartos @vmuzikar what would be an acceptable delta between "start --optimized --verbose" and "start --optimized"?

### CODE REVIEW

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 1]
```diff
@@ -187,7 +187,24 @@ public void testInvalidArgumentType() {
         NonRunningPicocli nonRunningPicocli = pseudoLaunch("start-dev", "--http-port=a");
         assertEquals(CommandLine.ExitCode.USAGE, nonRunningPicocli.exitCode);
         assertThat(nonRunningPicocli.getErrString(),
-                containsString("Invalid value for option '--http-port': 'a' is not an int"));
+                containsString("Invalid value for option '--http-port': SRCFG00029: Expected an integer value, got \"a\""));
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java]: It'd be nice to get rid of the converting status: "SRCFG00029"

**Review by mabartos — DISMISSED** [review]
@shawkins Nice work! LGTM as a base for the following work.

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java]: It does look a little odd, but it matches the message you see if you currently put http-port=a in your keycloak.conf.

Unfortunately I don't think we have a great way other than string manipulation to eliminate this.

Comment (mabartos) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java]: As we (probably) know, the converter always includes the code when the converting fails, right? I would not object to remove everything until the first colon. We have quite a comprehensive testsuite, so we could test if everything works as expected. 

WDYT?

Comment (shawkins) [reply quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java]: Added logic to strip the code.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java [hunk 2]
```diff
@@ -577,6 +580,24 @@ public void validateValues(ConfigValue configValue, BiConsumer<ConfigValue, Stri
...
+                if (option.getComponentType() != String.class && option.getExpectedValues().isEmpty()) {
+                    if (v.isEmpty()) {
+                        throw new PropertyException("Invalid empty value for option %s".formatted(getOptionAndSourceMessage(configValue)));
+                    }
+                    try {
+                        Configuration.getConfig().convert(v, option.getComponentType());
+                    } catch (Exception e) {
+                        // strip the smallrye code if possible
+                        String message = e.getMessage();
+                        Pattern p = Pattern.compile("SRCFG\\d+: (.*)$");
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:592]:
```suggestion
                        Pattern p = Pattern.compile("^SRCFG\\d+: (.+)$");
```

nitpick

**Review by mabartos — APPROVED** [review]
@shawkins Looks good! Just one nitpick, but it's up to you if it will be used or not - I do not insist on that :)

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:592]: As I'm not sure that we're guarenteed that message will start with the code, my assumption is that we just wanted what appeared after the colon. 

Would you prefer this hard expectation?

Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:592]: If we're not sure, let's keep it as is :)
