### PR TITLE
use filtered times instead of all

### LINKED ISSUE #28748: Webauthn Policy timeout accepts values > 8 hours
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The tooltip for the Timeout field in Authentication states that the value needs to be between 0 and 8 hours. You are able to type a values in seconds that is over the 28800 second limit (tried 28801-31299) and the error notification does not appear. 

If you enter enough values, the value will actually appear in the Seconds/Minutes/Hours dropdown, which is odd.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Timeout field should show an error message if you to enter a value that exceeds the maximum allowed timeout value. Timeout values should never appear in the Seconds/Minutes/Hours dropdown.

### Actual behavior

Timeout field allows you to enter a value that exceeds the maximum allowed timeout value. Timeout values eventually appear in the Seconds/Minutes/Hours dropdown.

### How to Reproduce?

Enter a value between 28800-31299 seconds in the timeout field.

### Anything else?

Screen caps:
timeout-1
timeout-2
timeout-3

### PR DESCRIPTION
**Pull request by edewit**
fixes: #28748
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

File: js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx [hunk 1]
```diff
@@ -35,17 +35,17 @@ export type TimeSelectorProps = Omit<
     className?: string;
   };
 
-export const getTimeUnit = (value: number | undefined = 0) =>
-  allTimes.reduce(
+const getTimeUnit = (units: TimeUnit[], value: number | undefined = 0) =>
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx:38]: This can be shortened to the following code by using inferrence:
```suggestion
const getTimeUnit = (units: TimeUnit[], value = 0) =>
```

File: js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx [hunk 2]
```diff
@@ -35,17 +35,17 @@ export type TimeSelectorProps = Omit<
...
+  units.reduce(
     (v, time) =>
       value % time.multiplier === 0 && v.multiplier < time.multiplier
         ? time
         : v,
-    allTimes[0],
-  );
+    units[0],
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx:44]: Are we sure this is correct? It looks like the reduce starts with `units[0]`, but then on the first entry of the reduce `v` will also be the same value as `units[0]`. It also seems that as long the modulo `multiplier` is reached `v` is returned, so perhaps this could be accomplished with `for` loop and `return` as well? Avoiding additional iteration the proccess.

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx (hunk 2 above)
Comment (edewit) [reply js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx]: `units[0]` is the default it only iterates once, you could do it with a for loop of course:
```js
let largestUnit = units[0];
for (let i = 1; i < units.length; i++) {
  const unit = units[i];
  if (value % unit.multiplier === 0 && largestUnit.multiplier < unit.multiplier) {
    largestUnit = unit;
  }
}
```
But this is just a lot longer

Comment (jonkoops) [reply js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx]: Ahh yeah, the default makes sense

**Review by jonkoops — APPROVED** [review]
