### PR TITLE
Prevent thread concurrency and not-locked database problems

### LINKED ISSUE #13130: JPA Map storage concurrent execution of liquibase updates
### Describe the bug

There are currently two synchronization problems: 

The following code will add the current model to the list of `validatedModels`. A second request would not wait here while the Liquibase upgrade is performed, and would instead overtake the first request and would fail due to missing tables. 

https://github.com/keycloak/keycloak/blob/f6a2b334d1e0652dcaba76cf8fccdc464a3171cd/model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java#L377-L398

A second problem arises as the databasechangelog table is not locked with Quarkus. With undertow, as long as the legacy store is in the classpath, the [CustomLockService](https://github.com/keycloak/keycloak/blob/7c1d6eae431be5bcea976e67e099c8fe4391118d/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/lock/CustomLockService.java) will take care of this. 

To untangle the old JPA legacy store from the new JPA map store, this needs to be duplicated / adjusted to the needs to JPA map storage.

### Version

999-SNAPSHOT

### Expected behavior

When one thread migrates the database, all other threads should wait for that to complete. 

### Actual behavior

Threads might overtake each other, and even try to do parallel deployments.

### How to Reproduce?

Debugging with the Quarkus distribution.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
First commit: Assure that a second thread waits for the first thread to process the database changes. This prevents the "relation "kc_group" does not exist" exception we've been seeing when clicking on "groups" in the UI for the first time with a new database.

Second commit: Fall back to standard Liquibase locking, as DBLockProvider is "none" for the Map storage providers; at least until the map storage will provide its own lock provider.

Liquibase's classic lock provider has issues that need to be tackled in a follow-up issue, see https://github.com/liquibase/liquibase/issues/1311

This also removes the thread-local elements from the `MapJpaLiquibaseUpdaterProvider` that are not used in the new map storage. 

Closes #13130

### CODE REVIEW

**Comment by ahus1** [comment]
@sguilhen / @hmlnarik: This tries to bridge the biggest gaps with the current solution. While the first commit is more straight-forward, the solution attempt of the second commit might raise more of a debate. 

Still I don't see many other options until there is a new implementation of a DBLock provider which is compatible with the map storage approach. Happy to hear your thoughts.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java [hunk 1]
```diff
@@ -374,24 +374,30 @@ public void validateAndUpdateSchema(KeycloakSession session, Class<?> modelType)
...
-                MapJpaUpdaterProvider updater = session.getProvider(MapJpaUpdaterProvider.class);
-                MapJpaUpdaterProvider.Status status = updater.validate(modelType, connection, config.get("schema"));
-
-                if (!status.equals(VALID)) {
-                    update(modelType, connection, session);
-                }
-            } finally {
-                if (connection != null) {
+        if (!this.validatedModels.contains(modelType)) {
+            if (!this.validatedModels.contains(modelType)) {
```
Comment (sguilhen) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java:374]: This line should be after the synchronized block, shouldn't it?

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/updater/MapJpaLiquibaseUpdaterProvider.java [hunk 2]
```diff
@@ -42,23 +42,6 @@
...
-    
-        public static void setCurrentSession(KeycloakSession session) {
-            currentSession.set(session);
-        }
-    
-        public static void removeCurrentSession() {
-            currentSession.remove();
-        }
-    }
-
```
Comment (sguilhen) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/updater/MapJpaLiquibaseUpdaterProvider.java:61]: +1 to remove this - this thread local context was copied over from the legacy provider and was used to supply the session to the custom changes and was never really needed in the new store.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java [hunk 3]
```diff
@@ -374,24 +374,30 @@ public void validateAndUpdateSchema(KeycloakSession session, Class<?> modelType)
...
+                //noinspection SynchronizationOnLocalVariableOrMethodParameter
+                synchronized (modelType) {
```
Comment (hmlnarik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java:376]: Sync should be on an object owned by this `JpaMapStorageProviderFactory.java` instance. How about declaring a `private final ConcurrentHashMap<Class<?>, Object> SYNC_MODELS = new ConcurrentHashMap()` and using it here?

```suggestion
                synchronized (SYNC_MODELS.computeIfAbsent(modelClass, mc -> new Object())) {
```

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java [hunk 4]
```diff
@@ -438,14 +434,7 @@ private void printOperationalInfo(Connection connection) {
...
     private void update(Class<?> modelType, Connection connection, KeycloakSession session) {
         KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(), (KeycloakSession lockSession) -> {
-            // TODO locking tables based on modelType: https://github.com/keycloak/keycloak/issues/9388
-            DBLockProvider dbLock = session.getProvider(DBLockProvider.class);
-            dbLock.waitForLock(DBLockProvider.Namespace.DATABASE);
-            try {
-                session.getProvider(MapJpaUpdaterProvider.class).update(modelType, connection, config.get("schema"));
-            } finally {
-                dbLock.releaseLock();
-            }
```
Comment (hmlnarik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java:442]: What is the purpose of removing these lines? AFAICS, these are no-op in `none` lock. Wouldn't these be used once the proper locking is implemented in #9388?

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java [hunk 5]
```diff
@@ -91,18 +96,46 @@ private void exitLiquibaseScope(String scopeId) {
         } catch (Exception e) {
             throw new RuntimeException("Failed to exist scope: " + e.getMessage(), e);
         }
+        // To avoid cached instances from the just closed scope.
+        // Must be called only after exiting the scope.
+        SqlGeneratorFactory.reset();
```
Comment (hmlnarik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java:101]: Should this be in `finally` clause?

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java [hunk 6]
```diff
@@ -91,18 +96,46 @@ private void exitLiquibaseScope(String scopeId) {
...
+        });
         try {
             scopeId = Scope.enter(scopeValues);
         } catch (Exception e) {
             throw new RuntimeException("Failed to initialize Liquibase: " + e.getMessage(), e);
         }
+
+        // To avoid cached instances from another scope.
+        // Must be called only after entering the scope.
+        SqlGeneratorFactory.reset();
```
Comment (hmlnarik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java:137]: Should this be in a `finally` clause?

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java [hunk 7]
```diff
@@ -91,18 +96,46 @@ private void exitLiquibaseScope(String scopeId) {
...
+            @Override
+            public int getPriority() {
+                return serviceLocator.getPriority();
+            }
+
+            @Override
+            public <T> List<T> findInstances(Class<T> interfaceType) throws ServiceNotFoundException {
+                List<T> instances = serviceLocator.findInstances(interfaceType);
+                // prevent any class from the legacy JPA store to leak into the service discovery
+                instances = instances.stream().filter(t -> !t.getClass().getPackage().getName().startsWith("org.keycloak.connections.jpa")).collect(Collectors.toList());
```
Comment (hmlnarik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java:125]: Please use a constant for the package name.

Also a nit:
```suggestion
                instances = instances.stream().filter(t -> !t.getClass().getPackageName().startsWith("org.keycloak.connections.jpa")).collect(Collectors.toList());
```

**Comment by hmlnarik** [comment]
Quarkus test failure seems related

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java (hunk 1 above)
Comment (ahus1) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java:374]: true, will be fixed in next iteration.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java (hunk 3 above)
Comment (ahus1) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java:376]: My IDE had a similar suggestion, therefore the "noinspection SynchronizationOnLocalVariableOrMethodParameter" comment. 

This could be debatable, as `modelType` is a class, and classes are singletons inside a classloader context. That's why I kept it as is.

Comment (hmlnarik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java:376]: I'd prefer to have it done so that the lock is done locally within the instance, if only to allow for concurrent initialization for say `UserModel` schema from several realms concurrently.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java (hunk 7 above)
Comment (ahus1) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java:125]: The `getPackageName()` is only available as of JDK9, therefore not used here (and Maven/IDE will complain), as code aligns with JDK8.

Constant will be added.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java (hunk 5 above)
Comment (ahus1) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/liquibase/connection/DefaultLiquibaseConnectionProvider.java:101]: done in next commit

**Comment by ahus1** [comment]
All changes have been addressed, and the failing Quarkus test was fixed by updating LiquibaseProcessor.java. The builds are still running, still it should now be ready for another round of tests.

Thanks!

**Review by hmlnarik — APPROVED** [review]
Thank you for the PR!
