### PR TITLE
fix: refining https file type detection

### LINKED ISSUE #33649: Validation of http truststore or keystore file masks if the file exists
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

The validation message for keystore / truststores is misleading when the file does not exist.

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

A message that the file can't be found.

### Actual behavior

You see:

Unable to determine 'https-trust-store-type' automatically. Adjust the file extension or specify the property.

Even if you have the type option set.

### How to Reproduce?

./kc.sh start --https-key-store-file=not-there.ks --https-trust-store-file=also-not-there.ks --hostname-strict=false --https-key-store-type=JKS --https-trust-store-type=JKS

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
also making common trustore logic align

closes: #33649

cc @Pepo48 @vmuzikar tried to further mimic the logic in quarkus and specifically check for not being able to determine the type

### CODE REVIEW

**Review by Pepo48 — CHANGES_REQUESTED** [review]
@shawkins thanks for the improvements. Overall the proposed looks fine to me.

I added a comment down bellow - just a small thing.

I also rerun the CI - from the logs it wasn't clear whether the failures are related on just an instability.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java [hunk 1]
```diff
@@ -130,68 +141,61 @@ public static PropertyMapper<?>[] getHttpPropertyMappers() {
...
+        Optional<String> certFile = Configuration.getOptionalKcValue(HttpOptions.HTTPS_CERTIFICATE_FILE.getKey());
+        Optional<String> keystoreFile = Configuration.getOptionalKcValue(HttpOptions.HTTPS_KEY_STORE_FILE.getKey());
+        if (!enabled && (certFile.isEmpty() && keystoreFile.isEmpty())) {
+            throw new PropertyException(Messages.httpsConfigurationNotSet());
+        }
+
+        CertificateConfig config = new CertificateConfig();
+
+        config.trustStoreFile = Configuration.getOptionalKcValue(HttpOptions.HTTPS_TRUST_STORE_FILE.getKey()).map(Paths::get);
+        config.trustStoreFile = Configuration.getOptionalKcValue(HttpOptions.HTTPS_TRUST_STORE_FILE.getKey()).map(Paths::get);
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java]: Thank you, I messed that up in the merge. Corrected now.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java [hunk 2]
```diff
@@ -130,68 +141,60 @@ public static PropertyMapper<?>[] getHttpPropertyMappers() {
...
-            if (value.isEmpty()) {
-                throw new PropertyException(Messages.httpsConfigurationNotSet());
-            }
+            throw new PropertyException(e.getMessage(), e);
         }
     }
 
-    private static BiFunction<String, ConfigSourceInterceptorContext, String> validatePath(String key) {
-        return (value, context) -> Environment.isWindows() && value != null && value.equals(context.proceed(key).getValue()) ? value.replace("\\", "/") : value;
+    private static BiFunction<String, ConfigSourceInterceptorContext, String> transformPath(String key) {
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:196]: Providing the 'key' param seems confusing when it's not even used.

```suggestion
    private static BiFunction<String, ConfigSourceInterceptorContext, String> transformPath() {
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java [hunk 3]
```diff
@@ -130,68 +141,60 @@ public static PropertyMapper<?>[] getHttpPropertyMappers() {
...
+        config.trustStoreFiles = Optional.empty();
+
+        config.keyStoreFile = keystoreFile.map(Paths::get);
+        config.keyStorePassword = Configuration.getOptionalKcValue(HttpOptions.HTTPS_KEY_STORE_PASSWORD.getKey());
+        config.keyStoreFileType = Configuration.getOptionalKcValue(HttpOptions.HTTPS_KEY_STORE_TYPE.getKey());
+        config.keyStoreProvider = Configuration.getOptionalValue("quarkus.http.ssl.certificate.key-store-provider");
+        config.keyStoreAlias = Configuration.getOptionalValue("quarkus.http.ssl.certificate.key-store-alias");
+        config.keyStoreAliasPassword = Configuration.getOptionalValue("quarkus.http.ssl.certificate.key-store-alias-password");
+        config.keyStoreAliasPasswordKey = Configuration.getOptionalValue("quarkus.http.ssl.certificate.key-store-alias-password-key");
+        config.keyStoreKeyAlias = Configuration.getOptionalValue("quarkus.http.ssl.certificate.key-store-key-alias");
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:166]: nit: Why obtain the keystore config, when there's a problem with truststore? I mean, the fail-fast makes more sense to me as the keystone config should not influence the `computeTrustOptions` at all, right?.

File: services/src/main/java/org/keycloak/truststore/TruststoreBuilder.java [hunk 4]
```diff
@@ -101,7 +101,8 @@ private static void mergeFiles(String[] truststores, KeyStore truststore, boolea
             if (f.isDirectory()) {
                 mergeFiles(Stream.of(f.listFiles()).map(File::getAbsolutePath).toArray(String[]::new), truststore, false, discoveredFiles);
             } else {
-                if (file.endsWith(".p12") || file.endsWith(".pfx")) {
+                String lowerName = file.toLowerCase();
+                if (KeystoreUtil.KeystoreFormat.PKCS12.getFileExtensions().stream().anyMatch(s -> lowerName.endsWith(s))) {
```
Comment (mabartos) [inline services/src/main/java/org/keycloak/truststore/TruststoreBuilder.java:105]: It means this condition will be evaluated even in cases like:

- some**p12**
- wrongfile**pfx**
- hello**pkcs12**

Is that correct? As these extensions are set without the dot.

**Review by mabartos — COMMENTED** [review]
@shawkins Thanks; just some considerations.

**Review by mabartos — CHANGES_REQUESTED** [review]
The CI failures should be related to this PR with the NPE in the Http PM.

```
AccountLinkTest ++ INFO: HHH10001005: Database info:
AccountLinkTest ++ 	Database JDBC URL [undefined/unknown]
AccountLinkTest ++ 	Database driver: undefined/unknown
AccountLinkTest ++ 	Database version: 2.3.230
AccountLinkTest ++ 	Autocommit mode: undefined/unknown
AccountLinkTest ++ 	Isolation level: <unknown>
AccountLinkTest ++ 	Minimum pool size: undefined/unknown
AccountLinkTest ++ 	Maximum pool size: undefined/unknown
AccountLinkTest ++ ERROR: Failed to start server in (production) mode
AccountLinkTest ++ Error details:
AccountLinkTest ++ java.lang.NullPointerException
AccountLinkTest ++ 	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
AccountLinkTest ++ 	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:296)
AccountLinkTest ++ 	at java.base/java.nio.file.Path.of(Path.java:148)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.configuration.mappers.HttpPropertyMappers.lambda$transformPath$5(HttpPropertyMappers.java:197)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.transformValue(PropertyMapper.java:240)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.getConfigValue(PropertyMapper.java:136)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers.getValue(PropertyMappers.java:76)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.configuration.PropertyMappingInterceptor.getValue(PropertyMappingInterceptor.java:85)
AccountLinkTest ++ 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:27)
AccountLinkTest ++ 	at io.quarkus.opentelemetry.runtime.config.MpTelemetryRelocateConfigSourceInterceptor$1.getValue(MpTelemetryRelocateConfigSourceInterceptor.java:26)
AccountLinkTest ++ 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:27)
AccountLinkTest ++ 	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:449)
AccountLinkTest ++ 	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:369)
AccountLinkTest ++ 	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$vertx$http$runtime$CertificateConfig(Unknown Source)
AccountLinkTest ++ 	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$vertx$http$runtime$ServerSslConfig(Unknown Source)
AccountLinkTest ++ 	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$vertx$http$runtime$HttpConfiguration(Unknown Source)
AccountLinkTest ++ 	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
AccountLinkTest ++ 	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
AccountLinkTest ++ 	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
AccountLinkTest ++ 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
AccountLinkTest ++ 	at io.quarkus.runtime.Application.start(Application.java:101)
AccountLinkTest ++ 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
AccountLinkTest ++ 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:146)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:57)
AccountLinkTest ++ 	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
AccountLinkTest ++ 	at picocli.CommandLine.access$1500(CommandLine.java:148)
AccountLinkTest ++ 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
AccountLinkTest ++ 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
AccountLinkTest ++ 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
AccountLinkTest ++ 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
AccountLinkTest ++ 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
AccountLinkTest ++ 	at picocli.CommandLine.execute(CommandLine.java:2174)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:147)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:135)
AccountLinkTest ++ 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:106)
AccountLinkTest ++ 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
AccountLinkTest ++ 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
AccountLinkTest ++ 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
AccountLinkTest ++ 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java (hunk 3 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:166]: This logic is just setting up the config, the cost is minimal - no disk reads are happening. Then there's a serial checking of the trust, then key material.

File: services/src/main/java/org/keycloak/truststore/TruststoreBuilder.java (hunk 4 above)
Comment (shawkins) [reply services/src/main/java/org/keycloak/truststore/TruststoreBuilder.java:105]: Right, this was not intentional with the refactoring. I'll update this to use the new utility method.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java]: Simplified to just be a function, rather than returning a function. As far as I can tell the check of the context.forward value when the value isn't null isn't necessary - that would imply the usage of quarkus.properties, but that usage would be overriden by the value coming PropertyMappingInterceptor.

File: common/src/main/java/org/keycloak/common/util/KeystoreUtil.java [hunk 5]
```diff
@@ -38,8 +39,8 @@
 public class KeystoreUtil {
 
     public enum KeystoreFormat {
-        JKS("jks"),
-        PKCS12("p12", "pfx"),
+        JKS("jks", "truststore"),
+        PKCS12("p12", "pfx", "pkcs12"),
         BCFKS("bcfks");
```
Comment (mabartos) [inline common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:44]: It'd be great to mention the mapping of extensions to specific KS formats somewhere in the documentation. 

I see it's only in [Upgrading guide for KC 26.0.0](https://www.keycloak.org/docs/latest/upgrading/index.html#keystore-and-trust-store-default-format-change):

_If the file extension is .p12, .pkcs12 or .pfx, the format is PKCS12. If the file extension is .jks, .keystore or .truststore, the format is JKS. If the file extension is .pem, .crt or .key, the format is PEM._

IMO it makes sense to mention it. @shawkins WDYT? Could you please potentially handle it in a follow-up?

**Review by mabartos — DISMISSED** [review]
@shawkins LGTM, just one suggestion for follow-up task.

File: common/src/main/java/org/keycloak/common/util/KeystoreUtil.java (hunk 5 above)
Comment (shawkins) [reply common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:44]: Sure, this can be moved to the regular docs. It could also mention .ca is accepted as a pem trust file.

**Review by Pepo48 — DISMISSED** [review]
LGTM now, thanks!

**Comment by mabartos** [comment]
@vmuzikar Changes LGT-us, could you please check it as it also requires maintainers approval? Thanks

File: common/src/main/java/org/keycloak/common/util/KeystoreUtil.java (hunk 5 above)
Comment (shawkins) [reply common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:44]: Added

File: common/src/main/java/org/keycloak/common/util/KeystoreUtil.java [hunk 6]
```diff
@@ -38,8 +39,8 @@
 public class KeystoreUtil {
 
     public enum KeystoreFormat {
-        JKS("jks"),
-        PKCS12("p12", "pfx"),
+        JKS("jks", "truststore"),
```
Comment (mabartos) [inline common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:42]: We should be more explicit and include here also the `.keystore`, right?
```suggestion
        JKS("jks", "truststore", "keystore"),
```

File: common/src/main/java/org/keycloak/common/util/KeystoreUtil.java [hunk 7]
```diff
@@ -105,6 +106,17 @@ public static KeyPair loadKeyPairFromKeystore(String keystoreFile, String storeP
             throw new RuntimeException("Failed to load private key: " + e.getMessage(), e);
         }
     }
+    
+    public static Optional<KeystoreFormat> getKeystoreFormat(String path) {
```
Comment (mabartos) [inline common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:110]: It'd be great to have at least some test cases for this method when they are made public.

**Review by mabartos — COMMENTED** [review]
@shawkins Thanks for the update. Just last small things.

File: common/src/main/java/org/keycloak/common/util/KeystoreUtil.java (hunk 6 above)
Comment (shawkins) [reply common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:42]: > We should be more explicit and include here also the .keystore, right?

I didn't include it because there's some potential confusion there. We already use .keystore for the default server keystore. That is in pkcs12 format, not jks. However it still works as pkcs12 even when quarkus detects the type as jks because the jdk will try both formats when you specify jks. Since we don't rely on the KeystoreUtil to define keystores, I just left that out for now.

Comment (shawkins) [reply common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:42]: Actually we could have the same concern with .truststore - because that's what we're using for the generated keycloak.truststore.

Comment (mabartos) [reply common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:42]: > Actually we could have the same concern with .truststore

@shawkins yes, that's exactly what I wanted to point out as well xD 

Like, even when the `KeystoreFormat` is barely used right now, we could move it out of the util class and have its own lifecycle with a proper setting. 

Just right now, we state in docs that `.keystore` and `.truststore` extensions are considered JKS, but it's not reflected here. 

As it is an inner enum of the util class, I would not consider it as a big deal to have it "complete", as the source code should not depend on it in a big manner (IMHO).

So, I'll leave it up to you what to include there.

Comment (shawkins) [reply common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:42]: I primarly wanted to align the pkcs12 extensions, so I'll just leave out the .truststore and .keystore conventions for now.

Comment (mabartos) [reply common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:42]: Agree

File: common/src/main/java/org/keycloak/common/util/KeystoreUtil.java (hunk 7 above)
Comment (shawkins) [reply common/src/main/java/org/keycloak/common/util/KeystoreUtil.java:110]: Added a couple of tests.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java [hunk 8]
```diff
@@ -130,68 +139,60 @@ public static PropertyMapper<?>[] getHttpPropertyMappers() {
...
+        
+        config.keyFiles = Configuration.getOptionalKcValue(HttpOptions.HTTPS_CERTIFICATE_KEY_FILE.getKey()).map(Paths::get).map(List::of);
+        config.files = certFile.map(Paths::get).map(List::of);
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:167]: Just out of curiosity, it seems like [we were setting](https://github.com/keycloak/keycloak/blob/6d525207308c8442678d8a68edac1e6e448471d8/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java#L167-L168) both here to `Optional.empty()`?

**Comment by vmuzikar** [comment]
@mabartos Do you want to give it another look?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java (hunk 8 above)
Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:167]: Ok, thanks for elaborating.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

**Review by mabartos — APPROVED** [review]
LGTM
