### PR TITLE
Fixed searchClientRegistration message text

### LINKED ISSUE #28514: Message for searchClientRegistration is missing
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Go to clients --> Client registration -> Notice that "searchClientRegistration" text is present in the search box.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Correct message should display

### Actual behavior

Message is missing

### How to Reproduce?

Go to clients --> Client registration -> Notice that "searchClientRegistration" text is present in the search box.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/28514

### CODE REVIEW

File: js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx [hunk 1]
```diff
@@ -104,7 +104,9 @@ export const ClientRegistrationList = ({
       <DeleteConfirm />
       <KeycloakDataTable
         ariaLabelKey="clientRegistration"
-        searchPlaceholderKey="searchClientRegistration"
+        searchPlaceholderKey={t("searchClientRegistration", {
+          policyType: subTab || "anonymous",
```
Comment (jonkoops) [inline js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx:108]: We'll have to localize `subTab` and `"anonymous"` as well if they are to be displayed in different languages.

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx (hunk 1 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx:108]: I see, I'll keep it simple then.

**Review by jonkoops — APPROVED** [review]
