### PR TITLE
fix: ensuring placeholders can be used with --import-realm

### LINKED ISSUE #33578: In imported realms, the ability to use environment variables has disappeared
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

In imported realms, the ability to use environment variables has disappeared

Works on the Keycloak 25.0.6 and crashes on the Keycloak: 26.0.0

Running as container in the docker compose. Startup options: `start-dev --import-realm`

Realm JSON:
```json
{
  "id": "${KC_REALM_NAME}",
  "realm": "${KC_REALM_NAME}",
  "sslRequired": "none",
  "enabled": true,
  "eventsEnabled": true,
  "eventsExpiration": 900,
  "adminEventsEnabled": true,
  "adminEventsDetailsEnabled": true,
  "attributes": {
    "adminEventsExpiration": "900"
  },
  "clients": [
    {
      "id": "grafana",
      "clientId": "grafana",
      "name": "grafana",
      "enabled": true,
      "publicClient": true,
      "rootUrl": "${GF_URL}",
      "adminUrl": "${GF_URL}",
      "baseUrl": "${GF_URL}",
      "redirectUris": [
        "${GF_URL}/*"
      ],
      "webOrigins": [
        "${GF_URL}"
      ]
    }
  ],
  "users": [
    {
      "id": "admin",
      "email": "${GF_ADMIN_USERNAME}@admin",
      "username": "${GF_ADMIN_USERNAME}",
      "firstName": "DevOps",
      "lastName": "SRE",
      "enabled": true,
      "emailVerified": true,
      "credentials": [
        {
          "temporary": false,
          "type": "password",
          "value": "${GF_ADMIN_PASSWORD}"
        }
      ]
    }
  ]
}
```

### Version

26.0.0

### Regression

- [x] The issue is a regression

### Expected behavior

The Realm was imported with the substitution of environment variables

### Actual behavior

Keycloak crashes with message: 
```
keycloak-1    | 2024-10-04 10:17:16,990 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /opt/keycloak/bin/../data/import/realm.json
keycloak-1    | 2024-10-04 10:17:16,993 WARN  [org.keycloak.utils.ReservedCharValidator] (main) Character '$' not allowed.
keycloak-1    | 2024-10-04 10:17:17,019 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 3 ResultSet(s) and 0 Statement(s)
keycloak-1    | 2024-10-04 10:17:17,053 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
keycloak-1    | 2024-10-04 10:17:17,071 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
keycloak-1    | 2024-10-04 10:17:17,071 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Character '$' not allowed.
keycloak-1    | 2024-10-04 10:17:17,071 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
keycloak-1 exited with code 1
```

### How to Reproduce?

Run the current version of the project: https://github.com/eabykov/keycloak-compose/tree/26.0.0 

The main branch works with version 25.0.6

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #33578

### CODE REVIEW

File: services/src/main/java/org/keycloak/exportimport/ExportImportManager.java [hunk 1]
```diff
@@ -95,6 +95,7 @@ public boolean isImportMasterIncludedAtStartup(String dir) {
         if (dir == null) {
             throw new IllegalStateException("Import not enabled");
         }
+        ExportImportConfig.setReplacePlaceholders(true);
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/exportimport/ExportImportManager.java:98]: This looks like an odd place to set configuration. Can't this be moved somewhere else (maybe the `ExportImportManager`)?

Comment (shawkins) [reply services/src/main/java/org/keycloak/exportimport/ExportImportManager.java:98]: Another alternative is to default to always replacing placeholders. I think we didn't do that before just to limit the scope of the changes, but as long as the core folks agree then we can remove both of these calls.

Comment (vmuzikar) [reply services/src/main/java/org/keycloak/exportimport/ExportImportManager.java:98]: > Do you mean you want to get rid of the ExportImportConfig class? That has the responsibility currently of handling all of these system properties.

No, I meant that I don't think we should be calling `ExportImportConfig.setReplacePlaceholders(true);` from `isImportMasterIncludedAtStartup` which is essentially just a getter/checker, it should not modify the configuration IMHO.

> Another alternative is to default to always replacing placeholders. I think we didn't do that before just to limit the scope of the changes, but as long as the core folks agree then we can remove both of these calls.

That might be a bit out of scope for now.

Comment (shawkins) [reply services/src/main/java/org/keycloak/exportimport/ExportImportManager.java:98]: > No, I meant that I don't think we should be calling ExportImportConfig.setReplacePlaceholders(true); from isImportMasterIncludedAtStartup which is essentially just a getter/checker, it should not modify the configuration IMHO.

No, it's not great. It's similar to the issues raised in the TODO about undoing the static state changes. We can move it up, but it's not great in KeycloakApplication either.

Comment (vmuzikar) [reply services/src/main/java/org/keycloak/exportimport/ExportImportManager.java:98]: TBH, it makes more sense to me if it was in `KeycloakApplication` than in `isImportMasterIncludedAtStartup`. Feels cleaner.

Comment (shawkins) [reply services/src/main/java/org/keycloak/exportimport/ExportImportManager.java:98]: Let's just resolve this in a follow-up: #33596 - ideally we should be encapsulating as much as possible the usage of static ExportImportConfig logic.

File: quarkus/tests/integration/src/test/resources/quickstart-realm.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
     "realm": "quickstart-realm",
-    "enabled": true,
+    "enabled": ${TEST_REALM_ENABLED:true},
```
Comment (vmuzikar) [inline quarkus/tests/integration/src/test/resources/quickstart-realm.json:3]: We're not explicitly testing if the realm is enabled in the [`ImportAtStartupDistTest`](https://github.com/keycloak/keycloak/blob/e7ad9ff2d6a3ccb7e3e11a0ce8fc864b02bf04c4/quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportAtStartupDistTest.java) but it should be fine as the import would fail if placeholders were disabled.

File: services/src/main/java/org/keycloak/exportimport/ExportImportManager.java (hunk 1 above)
Comment (vmuzikar) [reply services/src/main/java/org/keycloak/exportimport/ExportImportManager.java:98]: Ok, let's do it as a follow-up.

**Review by vmuzikar — APPROVED** [review]
@shawkins LGTM, thanks.

Can you please create a backport?
