### PR TITLE
Refresh token for an OAuth2 based IDP when retrieving the IDP token

### LINKED ISSUE #14644: External IDP tokens are not refreshed automatically for OAuth2 & OIDC IDPs when retrieving the external token
### Describe the bug

We're using Github (specifically a Github app) as an external IDP. We have configured Github to use expiring access tokens (good for 8 hours). When we want to get data from Github on behalf of the user, such as a list of repositories where the Github app is installed, we need a Github [user-to-server access token](https://docs.github.com/en/rest/apps/installations#list-app-installations-accessible-to-the-user-access-token).

We can retrieve these external IDP tokens from keycloak via [this endpoint](https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens).

Unfortunately, if it has been more than 8 hours, then the access token is expired and the request to Github will fail. If I use the refresh token (which is also returned from the endpoint above), to get new tokens from Github, this works _once_. I get a new access and refresh token, and I can make a request to Github with the access token. However, this _expires_ the refresh token that Keycloak has. And there doesn't seem to be a way for me to give Keycloak the new access/refresh tokens that I've retrieved on behalf of the user.

Is this just an oversight? Is there any way to use Github as an external IDP with expiring access tokens?

### Version

19.0.2

### Expected behavior

1. Keycloak refreshes tokens _before_ returning them from `GET /realms/{realm}/broker/{provider_alias}/token` (provided the current `refresh_token` has not expired).

### Actual behavior

Keycloak appears to just return the exact response that it originally receives from Github, which is most likely an expired access token. If the refresh token is still good, it is worthless because using it will expire the one held in Keycloak.

### How to Reproduce?

Use Github as an external IDP with expiring tokens and try to use the endpoint as described above.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #14644

Follow-ups: 
* `minValidityToken` (minimum seconds a token is valid before it is refreshed) can't be configured via the UI, so it is unlikely people will discover this functionality. By default it is 5 seconds.

### CODE REVIEW

**Comment by ahus1** [comment]
@mposolda  / @rmartinc - looking for a reviewer for this PR. Thanks!

**Comment by ahus1** [comment]
I would assume it shouldn't break existing consumers that fetch the token once and refresh it themselves, so it should be backwards compatible. I still doubt that we'll backport it, as it might still surprise people. Comments welcome.

File: tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java [hunk 1]
```diff
@@ -209,6 +218,39 @@ public AccessTokenResponse doTokenExchange(String subjectToken) {
         return tokenExchangeRequest(subjectToken).send();
     }
 
+    public AccessTokenResponse doFetchExternalIdpToken(String providerAlias, String accessToken) {
```
Comment (mposolda) [inline tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java:221]: I am not sure if `AbstractOAuthClient` is supposed to directly have methods like these on itself.

It seems the idea behind the recent refactoring of OAuthClient done by @stianst was, that `AbstractOAuthClient` just provides the methods for retrieve the "request" objects where the actual requests are invoked.

Could you please make this consistent with the existing stuff?

File: services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java [hunk 2]
```diff
@@ -304,6 +306,48 @@ protected SimpleHttp getRefreshTokenRequest(KeycloakSession session, String refr
         return authenticateTokenRequest(refreshTokenRequest);
     }
 
+    @Override
+    public Response retrieveToken(KeycloakSession session, FederatedIdentityModel identity) {
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java:310]: The `Automatic refresh of external IDP token` is actually already supported for the internal-external token exchange. It is implemented in the method `OIDCIdentityProvider.exchangeStoredToken` . Could we possibly make sure that both places are using same logic (and maybe re-using same code if possible) ?

For example `exchangeStoredToken` takes into consideration `getConfig().getMinValidityToken()` while it seems that this one does not.

**Review by mposolda — COMMENTED** [review]
@ahus1 Thanks!

Added few comments inline.

**Comment by mposolda** [comment]
@ahus1 Another point I've noticed: The issue https://github.com/keycloak/keycloak/issues/14644 talks about github provider. This PR solves the issue for `OIDCIDentityProvider` , but `GithubIdentityProvider` is actually not subclass of `OIDCIDentityProvider`. Hence I guess that for github, the issue will not be solved?

At the same time, this probably applies for internal-external token exchange as well...

Related note: There is PR opened for adding "Generic OAuth2 provider" : https://github.com/keycloak/keycloak/pull/39417 . Not sure whether wait for this one though. 

At the same time, I am not 100% sure if we save refresh-tokens for github and generic OAuth2 providers. If not, maybe we can maybe make sure to have this.

File: tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java (hunk 1 above)
Comment (ahus1) [reply tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java]: Thanks, I reworked the code.

File: services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java (hunk 2 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java:310]: I aligned the logic, and extracted two methods. 

I didn't use them with the existing code yet, I would like to keep it in a separate PR as it would lead to too many changes. And I would like to merge #31275 first which fixes another bug and adds more tests.

**Comment by ahus1** [comment]
Tests are green!

**Comment by ahus1** [comment]
I did some manual testing today with GitHub, and found that additional changes were necessary to make it work:

* Not all providers will return JSON, and the refreshing should only be attempted if it is a JSON format
* Option to switch the GitHub provider to JSON
* Store the expiry of the token when it is retrieve (similar to the OIDCIdentityProvider)

In-scope: Retrieving the external IDP tokens as described in the original request. 

Out of scope: exchangeSessionToken and exchangeStoredToken (as those would need the functionality today available in OIDCIdentityProvider. This should probably go along with some refactoring to of the OIDC provider.

Let me hear your thoughts. Thanks!

**Comment by kevinwright** [comment]
I'm curious, why has this been made about just GitHub?

The underlying need, as I see it, is:

> For **any** OAuth2 provider that returns an access and refresh token— When requesting that provider's access token via keycloak, the service first needs to check if the access token has expired and refresh it if necessary to ensure that it returns a valid non-expired token to the client

This is definitely a must-have for GitHub. But the same can also be said of GitLab and other providers. It's a generic need for almost all OAuth2

**Comment by ahus1** [comment]
@kevinwright - TL;DR: This PR touches several parts - and in the end it should work with OIDC and OAuth2 providers. 

Some background: 

* There was a simpler version of the PR that implemented it for OIDC providers that built on top of the token refresh logic already present for OIDC providers, but GitHub is only an OAuth2 provider. 
* GitHub provides an OAuth2 API, but it is a bit special as it responds with JSON only when you set a special header which is not part of the OAuth2 spec. So to retrieve JSON like for all other OAuth2 providers - this is why this PR touches GitHub specific code.  
* GitHub provides two flavors: "GitHub App" (which provides refresh tokens) and "OAuth Apps" (which do not provide refresh tokens). 

I would love to get feedback on this implementation if someone could try it out if it works for them good enough.

**Review by mposolda — DISMISSED** [review]
@ahus1 Thanks for the updates! I am approving.

Note: Some logic for refreshing the external token is already implemented for internal-external token exchange for the OIDC provider (See `OIDCIdentityProvider.exchangeStoredToken` ). It can be possibly good to make sure that refreshing external token is implemented on the single place and both those methods are re-using as there is some duplicated logic (For example around `minValidityToken` etc). But this could be done as a follow-up though. So approving this PR.

Another note: It can be good if this PR is also reviewed by @keycloak/core-iam team as we discussed in private as identity-brokering is the area owned mainly by the core-iam team.

File: docs/documentation/server_admin/topics/identity-broker/social/github.adoc [hunk 3]
```diff
@@ -13,10 +13,12 @@ To log in with GitHub, perform the following procedure.
 image:images/github-add-identity-provider.png[Add Identity Provider]
 +
 . Copy the value of *Redirect URI* to your clipboard.
-. In a separate browser tab, https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app[create an OAUTH app].
+. In a separate browser tab, https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app[create an OAuth app] or https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps[create an GitHub app]. Note that only GitHub apps can refresh tokens, while OAuth apps cannot refresh tokens.
```
Comment (sguilhen) [inline docs/documentation/server_admin/topics/identity-broker/social/github.adoc:16]: Overall this looks good to me. I'm just wondering if the sentence above is still valid as the code was moved to the base OAuth2 provider and thus should allow Oauth apps to refresh tokens, no?

Comment (ahus1) [reply docs/documentation/server_admin/topics/identity-broker/social/github.adoc:16]: @sguilhen - this is still valid, and only talks about how to set up things in the GitHub UI, as there are both "GitHub apps" and "OAuth Apps" with different capabilities, and only one allows refreshing of the tokens.

**Comment by ahus1** [comment]
@sguilhen - added a note the upgrading guide; please re-review and approve if you think this is good to be merged. Thanks!

File: docs/documentation/server_admin/topics/identity-broker/social/github.adoc (hunk 3 above)
Comment (sguilhen) [reply docs/documentation/server_admin/topics/identity-broker/social/github.adoc:16]: Ah got it. Thanks for the clarification!

**Review by sguilhen — APPROVED** [review]

**Comment by sguilhen** [comment]
Thanks @ahus1 ! Approved!

**Review by mposolda — APPROVED** [review]

**Comment by eperdeme** [comment]
I don't see this json format tick box in the MR pictures when using the nightly keycloak.

**Comment by Splitframe** [comment]
This doesn't seem to work for me. We have a customer with their own KeyCloak that our KeyCloak uses as an IDP.
So `KeyCloak WE` and `KeyCloak THEM` both are KeyCloak v26.4.0

`KeyCloak WE` Session length: 14 days
`KeyCloak WE` Access Token length: 10 Minutes

`KeyCloak THEM` Session length: 30 days
`KeyCloak THEM` Access Token length: 5 Minutes

User logs in on `KeyCloak WE` with the Button "Use `KeyCloak THEM` to Login, then logs in with the customer credentials.
This returns a Token Set from `KeyCloak WE`.

Call Broker or Token Exchange API so either
[Broker](https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens):
```
GET /realms/<realm_WE>/broker/<idp_alias_THEM>/token HTTP/1.1
Authorization: Bearer <Access Token WE>
```
or [Exchange](https://www.keycloak.org/securing-apps/token-exchange#_internal_token_to_external_token_exchange)
```
POST /realms/<realm_WE>/protocol/openid-connect/token HTTP/1.1
Body:
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:token-exchange' \
--data-urlencode 'subject_token=<Access Token WE>' \
--data-urlencode 'requested_issuer=<idp_alias_THEM>' \
--data-urlencode 'client_id=app' \
--data-urlencode 'requested_token_type=urn:ietf:params:oauth:token-type:access_token'
```

Both work and give me an Access Token for `KeyCloak THEM`.
But when the 5 Minutes are over and the Access Token of `KeyCloak THEM` is expired both endpoints return an Error:

Broker:
```
{
  "errorMessage": "Invalid token."
}
```

Exchange:
```
{"error_description":"linked token is expired","account-link-url":"[<KeyCloakWE>/broker/<idp_alias_THEM>/link?nonce=8369ef63-0545-4d9a-8cc6-42403b5e2219&hash=hWUlKKhMt6ZyZV2Wjc1OnXUg6RQLsFO9tod2bqpxSvY&client_id=app","error":"token_expired"}](<KeyCloakWE>/broker/<idp_alias_THEM>/link?nonce=8369ef63-0545-4d9a-8cc6-42403b5e2219&hash=hWUlKKhMt6ZyZV2Wjc1OnXUg6RQLsFO9tod2bqpxSvY&client_id=app%22,%22error%22:%22token_expired%22})
```

Or did I misunderstand something? Originaly I found this pull requesty via these issues: https://github.com/keycloak/keycloak/pull/39508 https://github.com/keycloak/keycloak/issues/14644
