### PR TITLE
fix: narrow fix for creating single file import without a system prop

### LINKED ISSUE #34270: Move away from using system properties to configure import/export providers
> We should really get rid of configuring the import/export providers via sys props eventually.

We are configuring import / export providers via system properties as a workaround due to the provider methods not accepting configuration per run. 

This forces us to use a seperate session for each import provider for example.

An option would be to put config overrides on the KeycloakContext (and reference that in the provider, rather than System.getxxx) - when those are present, we'd also have to use them as part of the cache keys with further changes along the lines of https://github.com/keycloak/keycloak/pull/34220

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/issues/34210#issuecomment-2431989885_

### PR DESCRIPTION
**Pull request by shawkins**
This also addresses the concern about double parsing to determine if the master realm is present.

I also think the current usage of action by import at startup could be removed and we just alway emit the "imported realm ..." log.

There's probably no need to take the changes further until there is some interest in running the operations post-startup such that we want a clean configuration without having to utilize system properties.

An alternative, rather than a new interface, would be to add a method to KeycloakSession to get property overrides - but the contract there doesn't seem as clear.

The other alternative, of updating the provider caching logic, is possible as well - but that seemed more cumbersome than this approach.

closes: #34270

### CODE REVIEW

File: server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+package org.keycloak.provider;
+
+import java.util.Map;
+
+import org.keycloak.models.KeycloakSession;
+
+public interface OverridableProviderFactory<T> {
+
+    T create(KeycloakSession session, Map<String, String> overrides);
+
```
Comment (mabartos) [inline server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java:27]: @shawkins Could you please add a Javadoc describing the purpose of the interface? It'd be good to mention what exactly might be overridden.

Comment (shawkins) [reply server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java]: Sure, refined the interface and the method javadoc to be clearer.

File: server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+ * limitations under the License.
+ */
+
+package org.keycloak.provider;
+
+import java.util.Map;
+
+import org.keycloak.models.KeycloakSession;
+
+public interface OverridableProviderFactory<T extends Provider> extends ProviderFactory<T> {
```
Comment (vmuzikar) [inline server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java:24]: IMHO this might be an antipattern and a solution tailored for a bad design of Import providers.

If a provider needs dynamic input/config, it should be provided as arguments to its methods, not handled at the factory upon provider creation. The suggested approach here feels to me like it adds additional complexity to something we already have a solution for.

From my perspective, the factory should be passing to the provider only config that is applicable for the whole server and whole lifecycle of the provider as generally they are mostly supposed to be singletons managed by Keycloak Session. Whatever config/input needs to be provided at runtime should be provided to methods specific to given provider (e.g. `importModel` in case of Import Provider).

I would argue that the Import Providers are not designed well as they e.g. require specifying file names at instantiation time. However, I understand changing that would require larger refactor.

As a compromise, we might make `create(KeycloakSession session, Map<String, String> overrides);` specific just to `ImportProviderFactory`, instead of having a new `OverridableProviderFactory` interface. Or really moving it just to `SingleFileImportProviderFactory`.

WDYT?

File: server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+    /**
+     * Create the Provider instance using additional overrides.
+     * <br>
+     * Only needed in circumstances where the Provider instances are created with configuration
+     * that changes at runtime - such as when performing single file import over multiple single files
+     */
+    T create(KeycloakSession session, Map<String, String> overrides);
```
Comment (vmuzikar) [inline server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java:32]: If we kept the interface approach, we could probably move the default impl here.
```suggestion
    T create(KeycloakSession session, Map<String, String> overrides);

    @Override
    default T create(KeycloakSession session) {
        return create(session, Map.of());
    }
```

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@shawkins Thank you for the PR. Added some comments, happy to hear your feedback on them.

Additionally, I'd rather open a new issue for this PR. #34270 sounds more like completely getting rid of the sys props while this PR removes them only partially as a first step, if I understand correctly.

File: server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java (hunk 2 above)
Comment (shawkins) [reply server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java:24]: > The suggested approach here feels to me like it adds additional complexity to something we already have a solution for.

I'm aware, but wanted as targeted of a changes as possible without being overly specific to the ImportProviderFactory as this issue will keep coming up if we don't want to use system properties and don't want to rewrite the providers and/or their caching. 

If you instead want it targeted to the ImportProviderFactory that's fine with me.

> Or really moving it just to SingleFileImportProviderFactory.

That would require adding an additional dependency to keycloak-services.

**Comment by shawkins** [comment]
> Additionally, I'd rather open a new issue for this PR. #34270 sounds more like completely getting rid of the sys props while this PR removes them only partially as a first step, if I understand correctly.

I don't see that issue getting worked any time soon, the motivation for this change was so that it could be closed.

File: server-spi-private/src/main/java/org/keycloak/exportimport/ImportProviderFactory.java [hunk 4]
```diff
@@ -17,10 +17,18 @@
...
 import org.keycloak.provider.ProviderFactory;
 
 /**
  * @author <a href="mailto:mposolda@redhat.com">Marek Posolda</a>
  */
 public interface ImportProviderFactory extends ProviderFactory<ImportProvider> {
+
+    default ImportProvider create(KeycloakSession session, Map<String, String> overrides) {
+        return create(session);
+    }
```
Comment (vmuzikar) [inline server-spi-private/src/main/java/org/keycloak/exportimport/ImportProviderFactory.java:32]: Should we rather have the default impl for `create(KeycloakSession)` to avoid mistakenly ignoring the overrides? If it's part of the interface, IMHO the most specific method should require implementation, with the less specific one having a default.

However, it'll require changes to other import providers, so if we want to keep the changes here less involved, let's keep as is.

File: server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java (hunk 2 above)
Comment (vmuzikar) [reply server-spi/src/main/java/org/keycloak/provider/OverridableProviderFactory.java]: > If you instead want it targeted to the ImportProviderFactory that's fine with me.

Works for me.

**Review by vmuzikar — DISMISSED** [review]
Added a non-blocking comment, but LGTM as is already.

Thanks!

File: server-spi-private/src/main/java/org/keycloak/exportimport/ImportProviderFactory.java (hunk 4 above)
Comment (shawkins) [reply server-spi-private/src/main/java/org/keycloak/exportimport/ImportProviderFactory.java:32]: > However, it'll require changes to other import providers, so if we want to keep the changes here less involved, let's keep as is.

Yes, the main goal is to not be a breaking change. I realize that even using a default method is not guarenteed to be non-breaking as someone could already have create(KeycloakSession, Map<other bounds>) method - that was part of the reasoning of using a separate interface. But this is not likely and easy to fix, so it seems fine to keep it this way.

Comment (vmuzikar) [reply server-spi-private/src/main/java/org/keycloak/exportimport/ImportProviderFactory.java:32]: Import Provider is not a public SPI, we can do breaking changes as we like.

**Review by vmuzikar — APPROVED** [review]
LGTM now, thanks!

File: server-spi-private/src/main/java/org/keycloak/exportimport/ImportProviderFactory.java [hunk 5]
```diff
@@ -17,10 +17,21 @@
...
+
+import org.keycloak.models.KeycloakSession;
 import org.keycloak.provider.ProviderFactory;
 
 /**
  * @author <a href="mailto:mposolda@redhat.com">Marek Posolda</a>
  */
 public interface ImportProviderFactory extends ProviderFactory<ImportProvider> {
+
+    ImportProvider create(KeycloakSession session, Map<String, String> overrides);
```
Comment (mabartos) [inline server-spi-private/src/main/java/org/keycloak/exportimport/ImportProviderFactory.java:30]: As I've mentioned in a comment before, this should contain some Javadoc to describe the `overrides`. 

Can be done in a follow-up issue.

**Review by mabartos — APPROVED** [review]
@shawkins LGTM, just one minor thing.
