### PR TITLE
Disable cache store only if a remote store is used

### LINKED ISSUE #10803: Persist session in JDBC store without using external infinispan cluster
### Description

We need to store session in a JDBC store, but the flag `SKIP_CACHE_STORE` has been introduced in [commit KEYCLOAK-4187 Added UserSession support for cross-dc](https://github.com/keycloak/keycloak/commit/07e2136b3b29984252c974a3f11ba3ddb69abda3) prevents writing in the store.

Thomas Darimont has proposed a patch in a previous discussion (https://groups.google.com/g/keycloak-dev/c/sOBzG76f2FE) and @mposolda seemed to approve the idea to be able do disable this flag (https://lists.jboss.org/pipermail/keycloak-dev/2018-August/011089.html). There was no change since then (2018).

At the moment, we have not found any way to natively store sessions in a JDBC store. Because of this, we are considering to use in production ( :fearful: )  a workaround deploying a custom `keycloak-infinispan-models` jar. Moreover, we are wondering if this will be compatible with the future Quarkus new store.

**Should we propose a new PR allowing to enable the `SKIP_CACHE_STORE` flag only when a remote-store is present in configuration ?** Is there any chance that this PR will be approved ?

We were able to persist sessions with an external infinispan cluster with jdbc store, but this leads us to a new blocking issue : https://github.com/keycloak/keycloak/discussions/10577

### Discussion

https://groups.google.com/g/keycloak-dev/c/sOBzG76f2FE

### Motivation

Business needs to guarantee to never lose user sessions

### Details

We may detect if a remote-store is in used by reading the infinispan configuration. Only if this is the case, the SKIP_CACHE_STORE flag should be added on `CacheDecorators.skipCacheStore` and `CacheDecorators.skipCacheLoaders`.

### LINKED ISSUE #24766: non-functioning session persistence when using JDBC over Infinispan
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

Hello, I recently created a pull request regarding the issue of storing user sessions into the JDBC data layer through Infinispan. The PR also describes a use case.

PR link:

https://github.com/keycloak/keycloak/pull/24248

PR description:

The problem arises when the persistent jdbc layer is used to save the session. After logging in, the user session is only stored in memory and is not stored in the relational database as I would expect. However, in rare cases the saving works, but it was very accidental. After studying the integration code on infinispan, I discovered that the cache instance always returns with the SKIP_CACHE_STORE flag, which actually results in the avoidance of persistence. It complicates the use of keycloak for us, because after a restart, users are always logged out both on mobile devices and on websites. I have tested this fix and user sessions persist immediately after logging in. If you know another way to fix it, let me know, if there is no other way, it would be good to reconsider the purpose of the SKIP_CACHE_STORE flag. Well thank you.

I found the same problem on a forum as well. Also, there is a recorded response that describes the modification of CacheDecorators and a problematic flag. 

Here is link:
https://stackoverflow.com/questions/76661708/infinispan-doesnt-write-any-sessions-in-jdbc-persisted-cache-in-keycloak-21-0-2

Please try to look into it to see if it is correct behavior, thank you.

### Version

21.1.2

### Expected behavior

I expect that with each login, sessions will be saved to the database and will not be lost upon restarting KC.

### Actual behavior

Currently, the saving is random and in most cases, the session is not saved, resulting in users being logged out after a restart.

### How to Reproduce?

o simulate the problem, it is necessary to run KC with ISPN and JDBC configuration, for example on a Postgres DB, then perform a login and check the table where sessions are stored. I would perform the login multiple times with different users, as sometimes the session is recorded.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
**Disclaimer:** The primary purpose of this is to not stand in the way of people experimenting with persistence in Infinispan's XML. This hasn't been performance tested, and is not a recommended setup. More changes are necessary to make this fully tested and supported, and we might look into different options to make persistence of sessions fully supported which might be incompatible from this one. It is not ideal (and can be problematic) as it uses one additional connection pool per cache, where it should probably reuse Quarkus' connection pool.

The following change will disable the writethrough/readthrough only when a remote store is used. Using a persistence and a remote store at the same time is not supported.

Closes #10803
Closes #24766

### CODE REVIEW

**Comment by ahus1** [comment]
I've tested this with the following configuration. This is still experimental and not supported, as it uses for example a separate connection pool for each cache. Ideally it should re-use Quarkus' connection pool. Further changes will be necessary to support this in a better way.

```
<?xml version="1.0" encoding="UTF-8"?>

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.xsd urn:infinispan:config:store:jdbc:14.0 https://infinispan.org/schemas/infinispan-cachestore-jdbc-config-14.0.xsd"
        xmlns="urn:infinispan:config:14.0">

    <cache-container name="keycloak">
        <transport lock-timeout="60000" />
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration />
            <!-- TODO: Keycloak should ensure to use either remote store or a persistence -->
            <persistence passivation="false">
                <!-- consider preload to be true or false? customer decision -->
                <string-keyed-jdbc-store
                        xmlns="urn:infinispan:config:store:jdbc:14.0"
                        dialect="POSTGRES"
                        shared="true"
                        segmented="true"
                        purge="false"
                        preload="false">
                    <!-- TODO: inject the JDBC connection from Quarkus -->
                    <connection-pool
                            connection-url="jdbc:postgresql://localhost:5432/keycloak?ApplicationName=keycloak-ispn"
                            username="keycloak"
                            password="pass"
                            driver="org.postgresql.Driver"/>
                    <string-keyed-table create-on-start="true" fetch-size="10000" prefix="ispn">
                        <id-column name="id" type="VARCHAR(255)" />
                        <data-column name="datum" type="BYTEA" />
                        <timestamp-column name="timestamp" type="BIGINT" />
                        <segment-column name="segment" type="BIGINT" />
                    </string-keyed-table>
                </string-keyed-jdbc-store>
            </persistence>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration />
            <persistence passivation="false">
                <string-keyed-jdbc-store
                        xmlns="urn:infinispan:config:store:jdbc:14.0"
                        dialect="POSTGRES"
                        shared="true"
                        segmented="true"
                        purge="false"
                        preload="false">
                    <connection-pool
                            connection-url="jdbc:postgresql://localhost:5432/keycloak?ApplicationName=keycloak-ispn"
                            username="keycloak"
                            password="pass"
                            driver="org.postgresql.Driver"/>
                    <string-keyed-table create-on-start="true" fetch-size="10000" prefix="ispn">
                        <id-column name="id" type="VARCHAR(255)" />
                        <data-column name="datum" type="BYTEA" />
                        <timestamp-column name="timestamp" type="BIGINT" />
                        <segment-column name="segment" type="BIGINT" />
                    </string-keyed-table>
                </string-keyed-jdbc-store>
            </persistence>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>
```

Two additional JARs are needed:

```
curl -f https://repo1.maven.org/maven2/org/infinispan/infinispan-cachestore-jdbc/14.0.19.Final/infinispan-cachestore-jdbc-14.0.19.Final.jar -o providers/infinispan-cachestore-jdbc-14.0.19.Final.jar
curl -f https://repo1.maven.org/maven2/org/infinispan/infinispan-cachestore-jdbc-common-jakarta/14.0.19.Final/infinispan-cachestore-jdbc-common-jakarta-14.0.19.Final.jar -o providers/infinispan-cachestore-jdbc-common-jakarta-14.0.19.Final.jar
```

This can then be started as follows: 

```
bin/kc.sh --verbose start --http-enabled true --hostname-strict false --db postgres --db-password pass --db-username keycloak --cache-config-file cache-ispn-db.xml
```

Smoketests I performed: The user session of a logged in user survives a Keycloak restart. Listing of user sessions in the Keycloak UI works as well.

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by martin-kanis — APPROVED** [review]
@ahus1 Thanks for the improvement. Looks good to me.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java [hunk 1]
```diff
@@ -40,17 +42,31 @@ public static <K, V> AdvancedCache<K, V> localCache(Cache<K, V> cache) {
...
-    public static <K, V> AdvancedCache<K, V> skipCacheLoaders(Cache<K, V> cache) {
-        return cache.getAdvancedCache().withFlags(Flag.SKIP_CACHE_LOAD, Flag.SKIP_CACHE_STORE);
+    public static <K, V> AdvancedCache<K, V> skipCacheLoadersIfRemoteStoreIsEnabled(Cache<K, V> cache) {
+        if (!getRemoteStores(cache).isEmpty()) {
+            // Disabling of the cache load and cache store is only needed when a remote store is used and handled separately.
+            return cache.getAdvancedCache().withFlags(Flag.SKIP_CACHE_LOAD, Flag.SKIP_CACHE_STORE);
+        } else {
+            // If there is no remote store, use write through/read through for all stores of the cache.
+            // Mixing remote and non-remote caches is not supported.
+            return cache.getAdvancedCache();
```
Comment (daviddelannoy) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java:52]: Hi @ahus1 ,

Thanks for starting this PR, even if as you said it is not a recommended setup, several projects/people use it.

I understand the effect of removing `SKIP_CACHE_STORE` here, but I don't get all impacts of removing the `SKIP_CACHE_LOAD` too if no remote store is used. 

I already noticed performance issues while removing `SKIP_CACHE_LOAD` here. With hundred of thousands of user/client sessions, user API will become very slow : more than 30 seconds or timeout when searching a user in the admin console, several seconds to delete one by API ... 

It was making too many SQL queries to ISPN sessions/clientSessions tables, always fetching from database : 
`SELECT datum, id FROM "ispn_sessions" WHERE (timestamp > $1 OR timestamp < 0) AND segment IN ($2) `

It is just a hint on my past observations on that, I know that it is working fine without performance issues with this code and around ~ 2 millions user sessions : 

```suggestion
            return cache.getAdvancedCache(Flag.SKIP_CACHE_LOAD);
```

Regarding your comment about `preload` in ISPN XML config file, I also can confirm that it works fine without any performance or functional issue with the default `preload=false`, combined with an : 
`<state-transfer enabled="true" await-initial-transfer="false" />`

In a 3-node cluster with 2 owners for distributed-cache, it makes the node available quite quickly (a few seconds) and prevent timeout issues during initial state transfer which `240000`  default value is too short for a huge number of sessions, even when increasing the state-transfer `chunk-size`. Of course state-transfer timeout can also be increased in case of sync startup.

Comment (martin-kanis) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java]: How does `Flag.SKIP_CACHE_LOAD` effects this when there is no remote store to skip?

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java]: Thank you for the update, I accepted the change. 

I agree that regular user handling will work (login, logout, refresh), but I doubt that listing all the sessions of for example a user will work as expected as from looking at the code I assume all sessions need to be in the internal Infinispan store. Therefore the preloading and state transfer enabled. Deferring the initial transfer will deliver wrong results until the transfer is complete, but that might be a trade off for some deployments.

Let's go with this version as an improvement, and possibly have future PR to enhance it even more.

**Comment by ahus1** [comment]
@mkanis - I've updated the PR after the comment of @daviddelannoy - could you please re-approve the change?

**Comment by ahus1** [comment]
@martin-kanis  - I've updated the PR after the comment of @daviddelannoy - could you please re-approve the change?

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java (hunk 1 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java]: @martin-kanis - the "skip load" will prevent the "string-keyed-jdbc-store" to be searched when listing, therefore I think it is a good idea and actually makes this change smaller.

**Comment by daviddelannoy** [comment]
> I've updated my Infinispan XML above to ensure that sessions are preloaded. This is required for listing sessions of a user / broker.

@ahus1 you have updated to `preload=true` for the `sessions` cache only, but not for `clientSessions` cache. Is it on purpose ? Is it enough to preload user `sessions` to be able to list them ?

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java (hunk 1 above)
Comment (martin-kanis) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java]: Then I find name of the method confusing. It skips cache load every time, not just if remote store is enabled.

Comment (daviddelannoy) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java]: yes exactly @martin-kanis that's why I was telling that for me the role of `skipCacheLoad` was really confusing, contrary to `skipCacheStore`  which is clearer.

You are right about consistency @ahus1 on startup, until user sessions have been loaded in internal cache. For example in admin console they won't be visible immediatly. 
But for some customers it can be an acceptable trade-off as you said.

**Review by mhajas — APPROVED** [review]
Thank you @ahus1, I like this change. I agree we should not limit users that want to use `persistence`.

**Comment by mhajas** [comment]
> > I've updated my Infinispan XML above to ensure that sessions are preloaded. This is required for listing sessions of a user / broker.
> 
> @ahus1 you have updated to `preload=true` for the `sessions` cache only, but not for `clientSessions` cache. Is it on purpose ? Is it enough to preload user `sessions` to be able to list them ?

Thanks for bringing it up @daviddelannoy! I checked the code and if the reason for preloading entries is only listing entities it should be ok to preload user sessions only as we are not listing client sessions anywhere. We usually load client sessions only for a specific user session that contains references to the client sessions. @ahus1 Was not preloading client sessions intended or it was only a mistake?

**Comment by ahus1** [comment]
> @ahus1 Was not preloading client sessions intended or it was only a mistake?

This was only by mistake and lack of knowledge. Good to see you fixing this.

**Comment by ahus1** [comment]
Thank you to everyone who participated in this. I'm now merging this. To change the docs and the behavior of Keycloak, please consider creating pull requests. Thank you for @miroRucka for creating the first PR here.

At the same time, the the store team at Keycloak might be focusing on other issues like performance, bugs and new features, so our time might be limited. FYI: PRs usually get more attention than feature requests.

**Comment by miroRucka** [comment]
Thank you @ahus1 for promptly addressing the issue, we will test it with the recommended setting.

**Comment by ahus1** [comment]
As this has been merged yesterday, it is part of tonights nightly Keycloak build for everyone to try. 

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by daviddelannoy** [comment]
@ahus1 it works fine for me with nightly build !

**Comment by ahus1** [comment]
@daviddelannoy - thank you for testing this, this is always appreciated!
