### PR TITLE
Management Interface is turned on even though nothing is exposed on it

### LINKED ISSUE #29601: Disable management port for non-server commands
### Description

import / export and any additional commands that don't start the server, should not start the management port.

### LINKED ISSUE #31818: Management Interface is turned on even though nothing is exposed on it
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I'm not sure if this is a bug or feature suggestion. It seems like a bug based on the [Management Interface Docs](https://www.keycloak.org/server/management-interface).

> The management interface is automatically turned off when nothing is exposed on it. Currently, only health checks and metrics are exposed on the management interface regardless.

When the health and metrics endpoints are disabled (which is the default), then it seems the management interface should be turned off because nothing is exposed on it. However, the management interface is still turned on for me - it is accessible via the base management URI and the log shows `Management interface listening on https://0.0.0.0:9000.`. If the above documentation is the intended behavior, the this is a bug.

If the intended behavior is for the management interface to always be on, even when nothing is exposed on it, then this is a feature suggestion to turn it off when nothing is exposed on it. I do not want to expose another port. Because of this bug/behavior, I'm using `legacy-observability-interface` for now, but it is deprecated.

----
As an alternative solution to using `legacy-observability-interface`, I tried setting the `http-management-port` to the same port as Keycloak, `https-port`, (I also set `http-management-relative-path=/management`), but I'm getting intermittent "Resource not found" errors 6% of the time accessing the admin console and making API calls (130 errors out of 1933 calls). This is causing failures in automation I've done for configuring our realm. Also, I'm aware this is documented as not a security best practice, but since I am not enabling the health and metrics endpoints, I thought this would be a viable solution. If the management interface can be turned off, then I would have no need to set the management port to the same as the Keycloak port.

Examples of the API calls getting "Resource not found":
* GET https://kc-fqdn:kc-port
* GET https://kc-fqdn:kc-port/admin/realms/master
* POST https://kc-fqdn:kc-port/realms/master/protocol/openid-connect/token
* GET https://kc-fqdn:kc-port/admin/realms/<my-realm>/client-scopes
* POST https://kc-fqdn:kc-port/admin/realms/<my-realm>/roles

Below is a screenshot of the error in the admin console and the network tab (again only occurring about 6% of the time):
image

image

image

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The management interface is automatically turned off when nothing is exposed on it.

### Actual behavior

The management interface is still turned on - it is accessible via the base management URI and the log shows `Management interface listening on https://0.0.0.0:9000.`.

### How to Reproduce?

My config file:
hostname= https://kc-fqdn:kc-port/
https-port=kc-port
https-key-store-file=kc-keystore
https-key-store-password=kc-keystorePw

Note: I'm excluding database and log parameters. I have no other parameters set. kc-* are replaced with my actual values.

Steps to reproduce:
kc.bat build --db=kc-db
kc.bat start --optimized
The management interface is still turned on - it is accessible via https://kc-fqdn:9000/ and the log shows `Management interface listening on https://0.0.0.0:9000.`.

----
Just in case, here is the configuration for my alt. solution that is giving me errors:
hostname= https://kc-fqdn:kc-port/
https-port=kc-port
http-management-port=kc-port
http-management-relative-path=/management
https-key-store-file=kc-keystore
https-key-store-password=kc-keystorePw

kc.bat build --db=kc-db
kc.bat start --optimized
Getting "Resource not found" 6% of the time via any admin console UI pages and any API calls. Some API examples getting the error:
* GET https://kc-fqdn:kc-port
* GET https://kc-fqdn:kc-port/admin/realms/master
* POST https://kc-fqdn:kc-port/realms/master/protocol/openid-connect/token
* GET https://kc-fqdn:kc-port/admin/realms/<my-realm>/client-scopes
* POST https://kc-fqdn:kc-port/admin/realms/<my-realm>/roles

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Fixes #31818

### CODE REVIEW

**Comment by mabartos** [comment]
I am still thinking about the validity of the issue, as it might be a little bit confusing for users to know when it is turned on or off.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ManagementPropertyMappers.java [hunk 1]
```diff
@@ -117,7 +120,13 @@ public static PropertyMapper<?>[] getManagementPropertyMappers() {
     }
 
     public static boolean isManagementEnabled() {
-        return isTrue("quarkus.management.enabled");
+        if (isNonServerMode()) return false;
+        var isManagementOccupied = isTrue(HealthOptions.HEALTH_ENABLED) || isTrue(MetricsOptions.METRICS_ENABLED);
+        return isManagementOccupied && !isTrue(ManagementOptions.LEGACY_OBSERVABILITY_INTERFACE);
```
Comment (shawkins) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ManagementPropertyMappers.java:125]:
```suggestion
        if (isNonServerMode() || isTrue(ManagementOptions.LEGACY_OBSERVABILITY_INTERFACE)) {
            return false;
        }
        return isTrue(HealthOptions.HEALTH_ENABLED) || isTrue(MetricsOptions.METRICS_ENABLED);
```

Might be simplier to put the false conditions together.

Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ManagementPropertyMappers.java]: Thanks, I've updated it. But I left the named var there to emphasize when the mgmt interface is enabled. @shawkins Is it ok?

**Comment by mabartos** [comment]
Dropped commit with the changes for https://github.com/keycloak/keycloak/issues/29601

**Review by shawkins — DISMISSED** [review]
LGTM

File: quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
Comment (vmuzikar) [inline quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt:1]: I wonder if the dynamically hidden management port options won't be confusing to the user. I know it's logical to enable the options conditionally and we leverage that for other options too (like Hostname versions). But here I feel it might be a bit different case as it might not be fully clear to the user when and why the options "disappear".

Maybe it'd provide a better UX not to conditionally enable the options?

WDYT @mabartos?

Comment (mabartos) [reply quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt:1]: @vmuzikar Agree the UX would be better, and it solves the minor concern I had above. Nice point!

**Review by vmuzikar — DISMISSED** [review]
LGTM, thanks @mabartos!

@shawkins Do you want to give it another look too?

**Comment by shawkins** [comment]
> But here I feel it might be a bit different case as it might not be fully clear to the user when and why the options "disappear".

That is probably more of an issue with the enabled message - it could say "Available only when Management interface is in use, e.g. metrics is enabled". 

If we remove the isEnabled condition from the PropertyMappers, I'd vote for the affected property descriptions to include text like that instead. I'd also be fine with keeping the use of the isEnabled condition.

**Comment by vmuzikar** [comment]
> That is probably more of an issue with the enabled message

My concern is that users don't see the enabled message as the disabled options are not visible (unless user uses `help-all`). And it's a quite a lot of options in case of the management interface, which are disabled just because seemingly unrelated options (health, metrics) are turned off. This feels a bit confusing to me from the user perspective.

> I'd vote for the affected property descriptions to include text like that instead

That works for me too.

**Comment by mabartos** [comment]
@shawkins @vmuzikar After some more thoughts, IMHO, the most suitable and reasonable approach for it would be proposed by @shawkins. 

If these options are always visible, it might provide additional confusion such as it is possible to specify these options, but actually, nothing happens, and users do not know what's going on at all.

When options are conditionally enabled, and the message is sth like "Available when Mgmt interface is enabled", users explicitly do not know when it is enabled, and it introduces another confusion.

I'm leaning towards the approach, as we edit only the message in the `isEnabled` that is more straightforward ('when mgmt is in use, e.g ....'), and if users specify these options, they immediately know what happened, and we prevent any confusion (hopefully :)).

@vmuzikar Does it work for you?

**Comment by vmuzikar** [comment]
From my perspective, the fact whether the management interface is enabled or disabled, is a bit hidden from the user as it's "dynamic". Now the condition is quite simple: is health or metrics enabled? But it might get more complicated in the future when there are more things that can be exposed on the management interface. And therefore confusing to the user why and when the management options are hidden and when not. As a user I care about when the management interface is enabled I want to configure it this end that way. I don't want to care when exactly the management interface is enabled – that's an implementation detail carried out by Keycloak.

Therefore, I would go with the way of adding a note to the description itself. Something like "Relevant only if something is exposed on the Management Interface. See the guide for details on what can use the Management Interface.".

**Comment by mabartos** [comment]
> Therefore, I would go with the way of adding a note to the description itself. Something like "Relevant only if something is exposed on the Management Interface. See the guide for details on what can use the Management Interface.".

@vmuzikar Ok, it's not a big deal to do it this way, and it works for me. The conditional enablement has also its own caveats and does not have to be the ultimate approach for all cases :)

**Review by vmuzikar — APPROVED** [review]
@mabartos Thanks for the update. LGTM.

@shawkins WDYT?

**Comment by mabartos** [comment]
@shawkins Are you ok with these changes?

**Review by shawkins — APPROVED** [review]
LGTM, thanks @mabartos
