### PR TITLE
[quarkus-next] Tests fail due to missing build step ordering constrai…

### LINKED ISSUE #46075: [quarkus-next] Tests fail due to missing build step ordering constraint on disableHealthCheckBean
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

This is a follow-up to [#45993](https://github.com/keycloak/keycloak/issues/45993), which added the annotation to three other methods that stabilized the build. In order to stabilize the CI test workflows, it is needed to add the annotation to the `disableHealthCheckBean` method as well.

https://github.com/keycloak/keycloak/actions/runs/21733796080

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests run.

### Actual behavior

https://github.com/keycloak/keycloak/actions/runs/21733796080

### How to Reproduce?

Run tests from the `quarkus-next` branch.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Pepo48**
…nt on disableHealthCheckBean

Closes: #46075

### CODE REVIEW

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 1]
```diff
@@ -831,6 +831,7 @@ void indexJpaStore(BuildProducer<IndexDependencyBuildItem> indexDependencyBuildI
     }
 
     @BuildStep
+    @Consume(ProfileBuildItem.class)
```
Comment (vmuzikar) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:834]: @Pepo48 Could you elaborate why profile is needed here? It seems we don't require profile in this build step?

Comment (Pepo48) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:834]: @vmuzikar we do, see `isRemoteInfinispan()` method on the line # 845:
image

Comment (vmuzikar) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:834]: Sorry, missed that.

**Review by vmuzikar — APPROVED** [review]
