### PR TITLE
fix: considering source ordinality with spi options

### LINKED ISSUE #43793: import does not seem to run db migration
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

We are using keycloak container, and what we do is to always run import to initalise master realm with some settings.

`opt/keycloak/bin/kc.sh import --override=false`

Then we do start using the start command

With latest version, we encountered this : 

```
2025-10-28 18:29:10,327 INFO  [org.keycloak.url.HostnameV2ProviderFactory] (main) If hostname is specified, hostname-strict is effectively ignored
2025-10-28 18:29:35,018 INFO  [org.hibernate.orm.jdbc.batch] (JPA Startup Thread) HHH100501: Automatic JDBC statement batching enabled (maximum batch size 32)
2025-10-28 18:29:46,299 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2025-10-28 18:29:46,620 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (nonserver) mode
2025-10-28 18:29:46,620 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Database not up-to-date, please enable database migration
2025-10-28 18:29:46,624 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

26.4.2

### Regression

- [x] The issue is a regression

### Expected behavior

I would expect the import command to run database migration before doing the import.

### Actual behavior

Database migration is not done when launching import, even with ` --spi-connections-jpa-quarkus-migration-strategy=update`

### How to Reproduce?

1- Setup keycloak on a previous version
2- Keep the database
3- Change the version and run import, before starting the server

### Anything else?

I'm pretty sure this was working before, we are using keycloak since version 24.0.5, and I don't think we ever had any issues with db upgrade.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #43793

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java [hunk 1]
```diff
@@ -137,8 +137,18 @@ private <T> T getValue(String key, Class<T> clazz, T defaultValue) {
...
+            ConfigValue newValue = config.getConfigValue(name);
+            if (newValue.getValue() == null) {
+                name = oldName;
+            } else {
+                ConfigValue oldValue = config.getConfigValue(oldName);
+                if (oldValue.getValue() != null && oldValue.getSourceOrdinal() > newValue.getSourceOrdinal()) {
+                    name = oldName;
+                }
+            }
+            return config.getOptionalValue(name, clazz).orElse(defaultValue);
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java]:
```suggestion
            Converter<T> converter = config.getConverter(clazz).orElseThrow();
            ConfigValue newValue = config.getConfigValue(separatorPrefix.concat(dashCase));
            ConfigValue oldValue = config.getConfigValue(prefix.concat(dashCase));

            String selectedValue = newValue.getValue();
            if (selectedValue == null || (oldValue.getValue() != null && oldValue.getSourceOrdinal() > newValue.getSourceOrdinal())) {
                selectedValue = oldValue.getValue();
            }

            return Optional.ofNullable(selectedValue).map(converter::convert).orElse(defaultValue);
```

IMHO, we could do this improvement to not call the `getConfigValue` and `getOptionalValue` twice for old and new value. @shawkins WDYT?

**Review by mabartos — COMMENTED** [review]
@shawkins LGTM, just one suggestion for improvement. Thanks!

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java]: My initial reasoning for not doing something like this is that getOptionalValue handles the conversion of indexed properties - should we ever add support for that, it would then simply work here.

If we want to ignore that for now, then I would just use SmallryeConfig.convert, rather than dealing with the converter directly.

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java]: @mabartos updated the logic

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java [hunk 2]
```diff
@@ -20,14 +20,16 @@
...
 import java.util.stream.StreamSupport;
-import org.eclipse.microprofile.config.ConfigProvider;
-
+import org.eclipse.microprofile.config.ConfigValue;
 import org.keycloak.Config;
 import org.keycloak.Config.Scope;
 
+import io.smallrye.config.SmallRyeConfig;
+
 public class MicroProfileConfigProvider implements Config.ConfigProvider {
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java:33]:
```suggestion
public class SmallRyeConfigProvider implements Config.ConfigProvider {
```

So, shouldn't be it SmallRye config provider? :P

**Review by mabartos — APPROVED** [review]
@shawkins LGTM, just one small improvement suggestion.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java:33]: > So, shouldn't be it SmallRye config provider? :P

It could be, but I don't think we need to update the class, factory, and other references, as there's no practical difference to us between MP and SmallRye.
