### PR TITLE
Requested grant_types inconsistent with created grant_types for OpenI…

### LINKED ISSUE #32801: Requested `grant_types` inconsistent with created `grant_types` for OpenID Connect Dynamic Client Registration
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When specifying `grant_types` in a OpenID Connect Dynamic Client Registration the requested and returned `grant_types` do not match. 

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Requested and returned `grant_types` are the same

### Actual behavior

Requested `grant_types` results in different created `grant-types`:

* `authorization_code` --> `authorization_code` [OK]
* `client_credentials` --> `[authorization_code, client_credentials]` [NOT OK]
* `password` --> `authorization_code` [NOT OK]
* `urn:ietf:params:oauth:grant-type:device_code` --> `authorization_code` [NOT OK]

### How to Reproduce?

Use `kct` to dynamically create clients for different flows, using the following command replacing flows with browser, client, password, and device, to try the different grant types:

```
kct config context create --iss myissuer -c mycontext --create-client --flow <FLOW> -X
```

Before running the above you need to create an issuer in `kct`, and context with a flow that uses boostrap admin user or client, and register that context with the issuer as the `client-registration-context`.

Using `-X` option you will see the request sent to Keycloak, and the responses.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
…D Connect Dynamic Client Registration

closes #32801

The issue is a bit tricky as both parameters `response_types` and `grant_types` are optional in the OIDC dynamic registration specification https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata .

PR tries to provide some "Best judge" according to the fact if:
- None of them is provided
- Only `response_types` is provided
- Only `grant_types` is provided
- Both are provided

Also PR fixes some nitpick issues and tries to preserve backwards compatibility and not reject request if incompatible values are provided.

### Details

For the case (1), PR preserves backwards compatibility, which was before this PR (Browser flow enabled with refresh token enabled)

For the case (2), the behaviour is unchanged in this PR.

For the case (3) we always assumed `code` to be used in case that `response_types` parameter was not provided. Now we're instead using `grant_Types` parameter to figure which flows should be enabled. So for example browser flow is enabled just if `grant_types` contains `authorization_code`. This is the case from the description of the issue (as `kct` currently use only `grant_types`, but not `response_types` parameter)

For the case (4), it is pretty much backwards compatible with the previous behaviour. The issue is, that there could be the case when provided `grant_types` are not aligned with `response_types`. For example when using `response_types=code` and `grant_types` without `authorization_code` . If provided response_types are not 100% aligned with provided grant_types, we can in theory reject the request based on https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata and the note "The following table lists the correspondence between response_type values that the Client will use and grant_type values that MUST be included in the registered grant_types list" . But from the specs, it s not 100% clear to me if authorization server is supposed to reject the request or adjust the grant_types to be compatible with response_types (EG. assume grant type `authorization_code` included if `response_types` contains `code`). I am doing the 2nd and not rejecting the request (also for backwards compatibility).

Besides that:

- Added the automated test `OIDCClientRegistrationResponseTypesAndGrantsTest` for various combinations (Also added the excell table here for the reference https://docs.google.com/spreadsheets/d/1YdtnigYNnVMDAl5hEUzrM6j_IUpYBNwoeCH9HDWC-sc/edit?usp=sharing ). Besides added some combinations in the test, I moved some existing test from `OIDCClientRegistrationTest` to it.

- Added support for enabling `device flow` from OIDC client registration (We did not have it before this PR)

- When `password` grant type was used, we enabled Direct-grant (correct behaviour), but we did not returned `password` grant type in the registration response (incorrect behaviour). It was correctly returned just in the subsequent OIDC GET requests. Fixed it in this PR.

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationResponseTypesAndGrantsTest.java [hunk 1]
```diff
@@ -0,0 +1,243 @@
...
+        } catch (ClientRegistrationException cre) {
+            throw new AssertionError(cre);
+        }
+    }
+
+    private void assertOIDCResponseImpl(OIDCClientRepresentation response, List<String> expectedResponseTypes, List<String> expectedGrantTypes) {
+        Assert.assertTrue("Incompatible response_types. Expected response types: " + expectedResponseTypes + ", Received response types: " + response.getResponseTypes(),
+                expectedResponseTypes.size() == response.getResponseTypes().size() && expectedResponseTypes.containsAll(response.getResponseTypes()));
+        Assert.assertTrue("Incompatible grant_Types. Expected grant types: " + expectedGrantTypes + ", Received grant types: " + response.getGrantTypes(),
+                expectedGrantTypes.size() == response.getGrantTypes().size() && expectedGrantTypes.containsAll(response.getGrantTypes()));
```
Comment (rmartinc) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationResponseTypesAndGrantsTest.java:222]: Just a minor but I prefer use the hamcrest matchers:

```java
MatcherAssert.assertThat("Incompatible response_types", response.getResponseTypes(), Matchers.containsInAnyOrder(expectedResponseTypes.toArray()));
MatcherAssert.assertThat("Incompatible grant_Types", response.getGrantTypes(), Matchers.containsInAnyOrder(expectedGrantTypes.toArray()));
```

**Review by rmartinc — APPROVED** [review]
I did a minor suggestion but it's OK to me. Thanks @mposolda!

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationResponseTypesAndGrantsTest.java (hunk 1 above)
Comment (mposolda) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationResponseTypesAndGrantsTest.java]: @rmartinc Updated, Thanks!
