### PR TITLE
Resolve first the user by username and fallback to the email during the identity-first login flow

### LINKED ISSUE #38852: [Organization] Failed authentication (ModelDuplicateException) when e-mail duplicates are allowed on the realm
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

I am opening this issue because we recently started getting these exceptions in our development environment, and we need to find a solution before we go to production. More context about our specific situation will be at the very end of the post.

The quick summary of the problem is that when an account's username is the e-mail address of 2+ accounts, then that account cannot log in if the browser flow uses the organization features and the flow goes through the `OrganizationAuthenticator`. This line of code is where the problem occurs (from `OrganizationAuthenticator.resolveUser()`):

`UserModel user = Optional.ofNullable(users.getUserByEmail(realm, username)).orElseGet(() -> users.getUserByUsername(realm, username));`

Here we have a username, not an e-mail, and yet we try to retrieve users by e-mail, using a username value. I understand this may have something to do with features like "e-mail as username", and/or "login with e-mail", but still, the attribute that is available in this method is the username (unless the variable name incorrect?). And this method can be called in situations where "login with e-mail" and "e-mail as username" are both disabled on the realm, so at the very least, it seems like a strange retrieve to do without checking for realm settings.

This issue was already reported in October of last year, here: https://github.com/keycloak/keycloak/issues/34266. This issue was closed without explanation, even though the discussion seemed to reach an agreement between the people involved. If there is good reason not to apply the proposed changes from the previous issue, I would appreciate at least an explanation, so that it can spark new ideas and maybe lead to a pull request, where everybody wins.

This other closed issue also touches on somewhat related topics and is an interesting read: https://github.com/keycloak/keycloak/issues/15024. I'm pasting this here for context in case it is helpful to the discussion.

### Version

26.1.4

### Regression

- [ ] The issue is a regression

### Expected behavior

If duplicate e-mails are allowed on the realm, a user for which the username is the same as the e-mail address should be able to log in, even if that e-mail address is used by other accounts.

If there is a security implication why this shouldn't be allowed, I do not see it, so I don't understand why this isn't allowed, seems unintentional. But the way I see it, if I create an account for myself and set my username as my e-mail address, everything is fine. If I then create another account for myself, and the realm allows duplicate e-mails, why shouldn't I be able to use the same e-mail address and receive all communications at the same place. I will need a unique username for that other account, and that's ok.

If a user with bad intentions creates a third account with my e-mail, they will need a unique username and will only be able to log in to that third account, and I will receive the communications destined to their account, which is fine because it will let me know that something fishy is going on.

On the other hand, if I create my own account with username = e-mail, and somebody with bad intentions creates another account with my e-mail, in the current implementation, I can no longer log in to the applications (if using `OrganizationAuthenticator`), which allows others to block me out of my account (because the `OrganizationAuthenticator` will find 2 accounts with the e-mail and will throw an exception when I try to log in). What's more, the second account will be able to log in just fine, because their username is not my e-mail address.

### Actual behavior

Trying to log in with a username that is the e-mail address of 2+ accounts fails, with a `ModelDuplicateException`. Note that this is only if the authentication flow goes through the `OrganizationAuthenticator`.

Stack trace:

`2025-04-10 17:17:20,655 WARN  [org.keycloak.services] (executor-thread-1225) KC-SERVICES0013: Failed authentication: org.keycloak.models.ModelDuplicateException: Multiple users with email 'the.user.email@domain.com' exist in Keycloak.
	at org.keycloak.models.jpa.JpaUserProvider.ensureEmailConstraint(JpaUserProvider.java:916)
	at org.keycloak.models.jpa.JpaUserProvider.getUserByEmail(JpaUserProvider.java:540)
	at org.keycloak.storage.UserStorageManager.getUserByEmail(UserStorageManager.java:427)
	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByEmail(UserCacheSession.java:402)
	at org.keycloak.organization.authentication.authenticators.browser.OrganizationAuthenticator.resolveUser(OrganizationAuthenticator.java:273)
	at org.keycloak.organization.authentication.authenticators.browser.OrganizationAuthenticator.action(OrganizationAuthenticator.java:98)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:149)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1039)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:378)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:349)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:341)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:407)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_13d428b70e62601585246c086a52f40868a3208e.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

### How to Reproduce?

1. Enable the organizations feature on the realm
2. Enable duplicate e-mails on the realm
3. Disable the "login with e-mail" and "username as e-mail" features on the realm.
4. Create an account with e-mail `test@test.com` and username `test@test.com`
5. Create a second account with e-mail `test@test.com` and username `testUser`
6. Try to log in with the first account, on a browser flow that uses organizations (identity first, `OrganizationAuthenticator`). The default browser flow on an organization enabled realm works for this.
7. Type in the username for the account, `test@test.com` and click Next.
8. Error message: `Unexpected error when handling authentication request to identity provider.`

Note that neither account even need to be associated to an organization to reproduce this.

### Anything else?

Here's more context about our specific situation, in case it is helpful. We have a fairly large user base (in the six figures) logging in to multiple applications, some old, some recent. We are on a quest to make e-mail addresses unique across the user base, for several reasons that are not relevant to this discussion. Duplicate e-mails have been allowed on the realm since the beginning, many years ago, so we have several cases of users with multiple accounts on the same e-mail address. We are providing tools in our applications to merge accounts so that users in these situations will be able to work with a single account, using a single e-mail address.

The end goal is to have a unique e-mail address on each account, no usernames (e-mail as username) and allow log in via e-mail and disallow duplicate e-mail addresses on the realm, when all duplicates are gone. But this is going to take time, and as a first step, we started copying the e-mail address to the username for newly created accounts in our applications, so that new users are already "clean". This also prevents the problem from growing, while we work on resolving existing duplicates. But now, what happens is we are starting to have some new users for which the username (an e-mail address) is the e-mail address of other existing accounts, that may or may not belong to the same user. The issue described here is a blocker for this, as the new account is unable to log in and may be a legitimate account.

For now, as a workaround, we have disabled the organization feature from the authentication flows, as we are not yet using it in production, but we would very much like to use it and have started integrating it into our applications already. But we cannot go to production yet, until we find a solution to this. We are happy to discuss this further and would like to find a solution that works for everybody.

I have not opened a PR yet, because the change I was going to propose is the same one that was discussed in the closed issue: https://github.com/keycloak/keycloak/issues/34266. If that change is not suitable, I would like to continue the discussion and hopefully find common ground.

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #38852

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java [hunk 1]
```diff
@@ -209,6 +213,61 @@ public void testLoginHint() {
...
+
+        // a different account with the same email can also authenticate using a unique username
+        oauth.loginForm().open();
+        loginPage.loginUsername(duplicatedUser.getUsername());
+        loginPage.clickSignIn();
+        loginPage.login(duplicatedUser.getUsername());
+        appPage.assertCurrent();
+        testRealm().users().get(duplicatedUser.getId()).logout();
+
+        // trying to authenticate with the duplicated user using the email will fail because the username is the email of a different account
```
Comment (WMartel) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java:256]: Change looks great, the test looks solid. Since the "stopper" for the second account is hitting an Invalid password error when they try to log-in by e-mail, I was wondering what would happen if both accounts have the same password (because let's be honest, users creating multiple accounts are likely to use the same password...).

But after thinking through the scenarios, everything seems to work out fine.

If both accounts have a different password, these are the possible scenarios:
- Account 1 tries to log in by username, the correct account is retrieved (by username), login succeeds
- Account 1 tries to log in by e-mail, the correct account is retrieved (by username), login succeeds
- Account 2 tries to log in by username, the correct account is retrieved (by username), login succeeds
- Account 2 tries to log in by e-mail, account 1 is retrieved (by username), login fails du to wrong password. This is ok because Account 2 should log in by username.

If both accounts have the same password, these are the possible scenarios:
- Account 1 tries to log in by username, the correct account is retrieved (by username), login succeeds
- Account 1 tries to log in by e-mail, the correct account is retrieved (by username), login succeeds
- Account 2 tries to log in by username, the correct account is retrieved (by username), login succeeds
- Account 2 tries to log in by e-mail, account 1 is retrieved (by username), login succeeds, bot for Account 1, not Account 2. This seems fine, because the user typed an e-mail address that is the username of Account 1, and login with e-mail is not enabled on the realm.

This could be a problem if users could log in with e-mail instead of username, but enabling the "login with e-mail" feature on the realm automatically disallows duplicate e-mails, so this doesn't seem like a problem. By the time we enable this feature, all the users will have a unique e-mail address. Apologies for the lengthy comment, writing this down helped me to reason through the scenarios!

**Review by WMartel — APPROVED** [review]

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java [hunk 2]
```diff
@@ -209,6 +213,61 @@ public void testLoginHint() {
...
+
+        realm.setDuplicateEmailsAllowed(true);
+        realm.setLoginWithEmailAllowed(false);
+        realm.setRegistrationEmailAsUsername(false);
+
+        testRealm().update(realm);
+
+        OrganizationRepresentation organization = createOrganization();
+        OrganizationResource organizationResource = testRealm().organizations().get(organization.getId());
+        UserRepresentation member = addMember(organizationResource);
```
[the remark this answers is not in the document]
Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java:228]: Yeah, the username is the email. See https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java#L188

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java (hunk 1 above)
Comment (WMartel) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java:256]: To be honest, I don't understand why in the organization authenticator the way to retrieve the user should be different than in the regular authentication flow if Organizations are not enabled on the realm. I have searched around a bit but I don't know which Authenticator class is used in that case, I'm not very familiar with the code base. But in that other flow, is there a verification of whether `Login with email` is enabled to determine if the user should be retrieved by username or by e-mail?

It sounds a bit more robust, to retrieve by e-mail only if `Login with email` is enabled and to retrieve by username if it's disabled. But I'm wondering about a scenario like this:
Account 1: Username: test@test.com, e-mail: user@outlook.com
Account 2: Username: otherUser, e-mail: test@test.com

In this situation, if `Login with email` is disabled on the realm, it seems clear that if someone tries to log in with test@test.com, the first account should be retrieved. But if `Login with email` is enabled, which account should be retrieved? I honestly don't know the answer to this one.

I was trying to find other authentication flows where the user is retrieved by either username or e-mail, I found this method:

```
public static UserModel findUserByNameOrEmail(KeycloakSession session, RealmModel realm, String username) {
    if (realm.isLoginWithEmailAllowed() && username.indexOf('@') != -1) {
        UserModel user = session.users().getUserByEmail(realm, username);
        if (user != null) {
            return user;
        }
    }

    return session.users().getUserByUsername(realm, username);
}
```

It seems to be used in a few places, maybe that's how it's done for authentication flows. That being said, with the scenario I described above, there is still possible ambiguity on which account should be retrieved. With this method, Account 2 would be retrieved. We could argue that it makes more sense, as the owner of Account 2 controls that e-mail address, not the owner of account 1.

Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java:256]: The method you mentioned above is the one I would like to reuse in the authenticator. It would be more aligned with other authenticators and yeah, in case login with email is enabled it will resolve the owner of the email.

In case you have duplicate email enabled, the call on `getUserByEmail` will throw an exception if there are multiple accounts with a same e-mail. Therefore, preventing the user to login using the e-mail.

I'll update the PR.

**Review by sguilhen — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving as of @sguilhen's review.
