### PR TITLE
Fix IllegalState InjectionManagerFactory not found on springboot tests

### LINKED ISSUE #24061: Adapter tests failing
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/spring

### Describe the bug

Some adapters tests failing with:
IllegalState InjectionManagerFactory not found

### Version

999-SNAPSHOT

### Expected behavior

Tests pass

### Actual behavior

Tests fail

### How to Reproduce?

Run the adapter tests

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Aboullos**
Fixes #24061

### CODE REVIEW

File: adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/BearerTokenRequestAuthenticator.java [hunk 1]
```diff
@@ -31,6 +31,7 @@
 
 import java.util.List;
 import javax.security.cert.X509Certificate;
+
```
Comment (miquelsi) [inline adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/BearerTokenRequestAuthenticator.java:34]: New line not needed

File: testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml [hunk 2]
```diff
@@ -192,7 +192,7 @@
             <dependency>
                 <groupId>org.springframework.boot</groupId>
                 <artifactId>spring-boot-starter-parent</artifactId>
-                <version>${spring-boot.version}</version>
+                <version>2.6.15</version>
```
Comment (miquelsi) [inline testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml:195]: It's better to use a property instead of a hardcoded value. If you need Spring Boot 2.6.x version, use `spring-boot26.version` property from parent pom. There you can upgrade it to 2.6.15 if needed.

Comment (mhajas) [reply testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml:195]: I did this just for testing purposes, we need to remove this change completely

**Review by miquelsi — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Comment by ahus1** [comment]
Merging as of @miquelsi's review. For a future iteration, I'd like to avoid a pause in the tests, but instead wait for a UI element to appear: Pauses usually lead to brittle tests, and it is unclear what they are waiting for if it is blunt pause like in this example.
