### PR TITLE
Fixed a11y violations

### LINKED ISSUE #26058: Fix Admin UI Accessibility Violations
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Review serious and critical violations recorded in the cypress dashboard and provide fixes.

### Version

22.0.5

### Expected behavior

Cypress dashboard should not show any serious and critical a11y violations.

### Actual behavior

Cypress dashboard shows a couple of serious and critical a11y violations.

### How to Reproduce?

Take a look at the cypress dashboard/ accessibility section.Cypress

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/26058

### CODE REVIEW

File: js/apps/admin-ui/src/components/key-value-form/ValueSelect.tsx [hunk 1]
```diff
@@ -41,6 +41,11 @@ export const ValueSelect = ({
       ))}
     </Select>
   ) : (
-    <KeycloakTextInput id="customValue" data-testid={rest.name} {...field} />
+    <KeycloakTextInput
+      id={t("customValue")}
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/key-value-form/ValueSelect.tsx:45]: The `id` should not be translated, perhaps we can just remove this?
```suggestion
```

File: js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx [hunk 2]
```diff
@@ -135,6 +135,7 @@ export const AttributeGeneralSettings = () => {
           render={({ field }) => (
             <Select
               toggleId="kc-attributeGroup"
+              aria-label={t("selectAttributeGroup")}
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx:138]: This select is already inside of a `FormGroup` with a label, so it should be associated with that element rather than adding an aria-label attribute.

File: js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx [hunk 3]
```diff
@@ -308,7 +309,7 @@ export default function LdapMapperDetails() {
                     variant={SelectVariant.typeahead}
                   >
                     {components.map((c) => (
-                      <SelectOption key={c.id} value={c.id} />
+                      <SelectOption id={c.id} key={c.id} value={c.id} />
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx:312]: Why does this element need an `id`?

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/components/key-value-form/ValueSelect.tsx (hunk 1 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/components/key-value-form/ValueSelect.tsx:45]: yeah, I think we can remove it

File: js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx (hunk 3 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx:312]: Yes, I don't think we need it. I'm going to remove it.

File: js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx [hunk 4]
```diff
@@ -135,6 +135,7 @@ export const AttributeGeneralSettings = () => {
           render={({ field }) => (
             <Select
               toggleId="kc-attributeGroup"
+              aria-label={t("attributeGroup")}
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx:138]: Looks like this one is redundant, as there is already a labelled `FormGroup`.  It seems the `id` is [just mismatched](https://github.com/keycloak/keycloak/blob/160299d3c64e3543c08470d01fa5186025bfd010/js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx#L129).

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx (hunk 4 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx:138]: Thanks @jonkoops This is a strange one. I have now both fieldId and toggleId the same, but if I remove the aria-label I get the violation. It seems that the aria-label is needed here.

Comment (jonkoops) [reply js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx:138]: Very strange, perhaps the ID is not being applied correctly?

Comment (jonkoops) [reply js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx:138]: Upon further inspection, this is a bug in PatternFly, looks like passing the `aria-label` attribute is the only way [this functions](https://github.com/patternfly/patternfly-react/blob/db0cdde6e3e6ae61348129b73bb43c97a98b4617/packages/react-core/src/components/Select/SelectMenu.tsx#L202).

**Review by jonkoops — APPROVED** [review]
