### PR TITLE
Fix race condition while updating Secrets labels in Operator

### LINKED ISSUE #12942: KC Operator Test WatchedSecretsTest.testSecretsAreWatched is unstable
### Describe the bug

When doing an unrelated change, the test listed above failed. 

https://github.com/keycloak/keycloak/runs/7203118955?check_suite_focus=true

Unfortunately it failed without logging enough information on the console to find out why it failed.

A PR should change this as the first step.

### Version

999-SNAPSHOT

### Expected behavior

Information to show the reason of the failure in the console.

### Actual behavior

Current status from the Keycloak CR is not logged.

### How to Reproduce?

Randomly failing on GitHub action.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #12942

There was occasionally a race condition in the Operator on watched Secrets when Operator overwrote a Secret that user (or test) just modified. That was due to incorrect handling of Secrets editing.

I did not add a new test for this as it is a bit hard to reliably reproduce. But the change is pretty simple as it is basically just alignment with [best practices](https://github.com/fabric8io/kubernetes-client/blob/f3e776b1557aa54c02b078f2b75382d932489e10/doc/CHEATSHEET.md#secret) in Fabric8.

I also sneaked in a log improvement for tests.

### CODE REVIEW

**Comment by vmuzikar** [comment]
10 test runs (which were unstable previously): https://github.com/vmuzikar/keycloak/actions/runs/3396274587

**Review by andre-nascimento6791 — APPROVED** [review]
LGTM.
Good Job!

File: operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java [hunk 1]
```diff
@@ -111,13 +111,12 @@ public void addLabelsToWatchedSecrets() {
...
                 Log.infof("Adding label to Secret \"%s\"", secret.getMetadata().getName());
 
-                secret = new SecretBuilder(secret)
-                        .editMetadata()
-                        .addToLabels(Constants.KEYCLOAK_COMPONENT_LABEL, WATCHED_SECRETS_LABEL_VALUE)
-                        .endMetadata()
-                        .build();
-
-                client.secrets().inNamespace(secret.getMetadata().getNamespace()).withName(secret.getMetadata().getName()).patch(secret);
+                client.secrets().inNamespace(secret.getMetadata().getNamespace()).withName(secret.getMetadata().getName())
```
Comment (mabartos) [inline operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java:114]: I'm afraid the `secret.getMetadata().getNamespace()` can throw NPE. As the code is executed even when the metadata are null for the secret.

**Review by mabartos — CHANGES_REQUESTED** [review]
@vmuzikar Thanks for the PR! Could you please check the comment below? Thanks!

File: operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java (hunk 1 above)
Comment (mabartos) [reply operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java:114]: Yep, you're right. I've been thinking about it in a more fault-tolerant way as after some invalid secret creation in a cluster, the whole process could be canceled. I was thinking about some warning dump and ignoring the secret, but it's probably better not to continue and solve the issue with that. Moreover, without a name, the secret wouldn't even be fetched, so the metadata are always there.

IMHO, the PR is ready to go. Thanks!

**Review by pedroigor — APPROVED** [review]
