### PR TITLE
SecureRedirectUrisEnforcerExecutor fixes

### LINKED ISSUE #27344: Secure Redirect URI executor issues
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

- The OIDC dynamic client registration does not work at all when secure-redirect-uris-executor is used in some client policy. This is due this condition is broken as authenticatedClient is null during OIDC dynamic client registration: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRedirectUrisEnforcerExecutor.java#L171

- When creating/updating client with some rootUrl, the redirect uris are incorrectly resolved based on the URL of authenticated client. For example when administrator updates the client `foo` in the admin console, the `authenticatedClient` would be `security-admin-console`. So redirect-uris will be resolved based on the rootUrl of `security-admin-console` instead of rootUrl of client `foo`. This is not correct as they should use rootUrl of the "target client", not the rootUrl of "authenticating client". See:
  - https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRedirectUrisEnforcerExecutor.java#L174
  - https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRedirectUrisEnforcerExecutor.java#L185

- The `secure-redirect-uri-executor` covers client redirect uris, but does not cover post-logout redirect uris. Those will be also good to cover to avoid cases when administrator has `secure-redirect-uri-executor` but someone is still able to register client with `post-logout-redirect-uri` like `*`, which means they can be used as open redirector.

### Version

nightly (from 2024-02-28)

### Regression

- [ ] The issue is a regression

### Expected behavior

Post-logout-redirect-uris are also verified when creating/updating client. And possibly also during logout.

### Actual behavior

Post-logout-redirect-uris are not verified

### How to Reproduce?

See above

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
closes #27344

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java [hunk 1]
```diff
@@ -180,7 +182,7 @@ public void testSecureRedirectUrisEnforcerExecutor_IPv6LoopbackAddress() throws
 
         // register - fail
         // IPv4 loopback address not allowed
-        testSecureRedirectUrisEnforcerExecutor_failRegisterDynamically(Arrays.asList("https://[::1]/", "https://localhost/auth/admin"));
+        testSecureRedirectUrisEnforcerExecutor_failRegisterDynamically(Arrays.asList("https://[::1]/", "https://127.0.0.1/auth/admin"));
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:185]: Question 1: Request does not fail when `localhost` is used (request was not failing before my changes as well, but test did not correctly tested that request fails).

In other words, it means that redirect-uri like `http://localhost/foo` is allowed even if configuration has `Allow IPv4 loopback` and `Allow IPv6 loopback` switched to false. This does not look like correct behaviour? WDYT?

I figured the issue is in guava code:

```
            try {
                addr = InetAddresses.forUriString(uri.getHost());
            } catch (IllegalArgumentException e) {
                return false;
            }
```
In case of `uri.getHost()` is `localhost`, there is IllegalArgumentException thrown and method returns false considering `localhost` as not being loopback address.

I wonder if we can use `InetAddress.getByName(uri.getHost())` instead of `InetAddresses.forUriString(uri.getHost())` ? This is the same, which is used for instance by `SslRequired` checks in Keycloak. Does it work for you?

**Review by mposolda — COMMENTED** [review]
@tnorimat @rmartinc I fixed the things mentioned in the description of the issue #27344 .

In addition to that, I fixed also the test methods `testSecureRedirectUrisEnforcerExecutor_failUpdateByAdmin` and `testSecureRedirectUrisEnforcerExecutor_failRegisterDynamically` as those did not really tested that client register/update request failed (There was missing `fail` after calling request, so method returned successfully even if expected failure did not happen). Some tests started to fail because some client CRUD requests, which were supposed to fail in the test, were passing. I have added 2 comments inline regarding the particular tests.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java (hunk 1 above)
Comment (tnorimat) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:185]: @mposolda 

> I wonder if we can use InetAddress.getByName(uri.getHost()) instead of InetAddresses.forUriString(uri.getHost()) ?

In the discussion in [the original PR](https://github.com/keycloak/keycloak/pull/25647), `InetAddresses.forUriString(uri.getHost())` instead of `InetAddress.getByName(uri.getHost()) ` to avoid a DNS lookup .

Comment (tnorimat) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:185]: @mposolda 

> In other words, it means that redirect-uri like http://localhost/foo is allowed even if configuration has Allow IPv4 loopback and Allow IPv6 loopback switched to false. This does not look like correct behaviour? WDYT?

+1 if `localhost` is not allowed if `oauth-2-1-compliant` is ON because OAuth 2.1 does not allow using `localhost`.

Comment (tnorimat) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:185]: @mposolda  I expect that registering a client dynamically with  redirect urls ("https://[::1]/", "https://127.0.0.1/auth/admin") fails because "Allow IPv4 loopback address" is OFF. Is that right?

**Review by tnorimat — COMMENTED** [review]
@mposolda I added some review comments. Could you check them?
Also, codes for post-logout uris check looks good to me.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java (hunk 1 above)
Comment (mposolda) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:185]: @tnorimat Yes, exactly. Registration of ("https://127.0.0.1/auth/admin") fails because `Allow IPv4 loopback address` is OFF. So when `127.0.0.1` is used in the address, it works as expected IMO as it is supposed to fail and it really fails.

But my point here is the other case when you try to register with use `localhost` instead of `127.0.0.1`. I think that registering of ("https://localhost/auth/admin") should fail in case of `Allow IPv4 loopback address` is `OFF`. But it currently does not fail. The client is successfully registered, which does not look like correct behaviour.

My observation is that `InetAddresses.forUriString(uri.getHost())` does not work well as in case when you call `InetAddresses.forUriString("localhost")` it throws `IllegalArgumentException`. This causes `SecureRedirectUrisEnforcerExecutor.isLoopbackAddressRedirectUri` to incorrectly return `false` even if `localhost` is loopback address.

ATM my vote is to add back `InetAddress.getByName` instead of `InetAddresses.forUriString` . I understand the concern with DNS lookup, but I am not sure if this is really big concern? For instance, Keycloak uses this already in `SslRequired.isLocal(String remoteAddress)` , which is called almost at every HTTP request to Keycloak?

Comment (tnorimat) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:185]: @mposolda Thank you for the clarification.

> I think that registering of ("https://localhost/auth/admin") should fail in case of Allow IPv4 loopback address is OFF. But it currently does not fail. The client is successfully registered, which does not look like correct behaviour.

Yes, I agree with you. We need to modify the executor to do so.

> ATM my vote is to add back InetAddress.getByName instead of InetAddresses.forUriString . I understand the concern with DNS lookup, but I am not sure if this is really big concern? For instance, Keycloak uses this already in SslRequired.isLocal(String remoteAddress) , which is called almost at every HTTP request to Keycloak?

@rmartinc suggested using `InetAddresses.forUriString`. I am OK to use `InetAddress.getByName`, but it might be better to ask @rmartinc for the point.

Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:185]: @mposolda @tnorimat I recommended to avoid the DNS lookup because I saw the tests were OK. I indeed thought that localhost was not considered like loopback access because it is not recommended by the spec. If you thin it's OK just change for getByName again.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java [hunk 2]
```diff
@@ -481,11 +565,13 @@ private void testSecureRedirectUrisEnforcerExecutor_failRegisterDynamically(List
         try {
             createClientDynamically(generateSuffixedName(CLIENT_NAME), (OIDCClientRepresentation clientRep) ->
                 clientRep.setRedirectUris(redirectUrisList));
+            fail("Expected to fail with redirectUris: " +redirectUrisList);
```
Comment (tnorimat) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:568]: `+redirectUrisList` might be `+ redirectUrisList`
But not necessarily fix it.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java [hunk 3]
```diff
@@ -503,12 +589,25 @@ private List<String> testSecureRedirectUrisEnforcerExecutor_successRegisterByAdm
...
+        }
+    }
+
     private void testSecureRedirectUrisEnforcerExecutor_failUpdateByAdmin(String cId, List<String> redirectUrisList) {
         try {
             updateClientByAdmin(cId, (ClientRepresentation clientRep) -> {
                 clientRep.setAttributes(new HashMap<>());
                 clientRep.setRedirectUris(redirectUrisList);
             });
+            fail("Expected to failwhen updating clientId " + cId + " with redirectUris: " +redirectUrisList);
```
Comment (tnorimat) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java:610]: `+redirectUrisList` might be `+ redirectUrisList`
But not necessarily fix it.

**Review by tnorimat — APPROVED** [review]
@mposolda LGTM, but I added comments that are not necessarily fixed them.

**Review by rmartinc — APPROVED** [review]
Apart from the typos detected by @tnorimat LGTM!

**Comment by mposolda** [comment]
@tnorimat @rmartinc Thanks!
