### PR TITLE
Incompatible method of admin-client in Keycloak 26.1 and missing javadoc

### LINKED ISSUE #36090: Incompatible method of admin-client in Keycloak 26.1 and missing javadoc
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

The method `ClientResource.getInstallationProvider(@PathParam("providerId") String providerId)` changed the return type from `String` to `Response` . This is incompatible change for the java admin-client.

This was introduced by https://github.com/keycloak/keycloak/commit/80bbb0be (My bad to not catching this)

Also it will be useful to add the javadoc to some newly added parameters of admin-client to mention since which server version those are available.

### Version

nightly (from 2024-12-20)

### Regression

- [X] The issue is a regression

### Expected behavior

Existing methods still have the same signature, so backwards compatibility is preserved. Javadoc available to indicate from which Keycloak server version particular methods work.

### Actual behavior

Changed signature on the method `ClientResource.getInstallationProvider`. Javadoc missing.

### How to Reproduce?

See the description

### Anything else?

Not strictly a blocker for Keycloak 26.1.0 release, but then we will need to wait with syncing of Keycloak client for the Keycloak 26.1.1 release to not break backwards compatibility.

### PR DESCRIPTION
**Pull request by mposolda**
closes #36090

### CODE REVIEW

File: integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java [hunk 1]
```diff
@@ -108,8 +108,9 @@ List<OrganizationRepresentation> search(
      *              the method returns all organizations whose name or (domains) partially match the {@code search} param.
      * @param first the position of the first result to be processed (pagination offset). Ignored if negative or {@code null}.
      * @param max the maximum number of results to be returned. Ignored if negative or {@code null}.
-     * @param briefRepresentation if {@code true} the full representation is to be returned. Otherwise, only the basic fields are returned.
+     * @param briefRepresentation if {@code true} the full representation is to be returned. Otherwise, only the basic fields are returned. The parameter is supported since Keycloak 26.1
      * @return a list containing the matched organizations.
+     * @since Keycloak 26.1. Use method {@link #search(String, Boolean, Integer, Integer)} for the older versions of the Keycloak server
```
Comment (pskopek) [inline integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java:113]: Shouldn't `@since` tag contain just version number?

File: integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java [hunk 2]
```diff
@@ -91,10 +91,11 @@ List<MemberRepresentation> search(
      * @param exact if {@code true}, the members will be searched using exact match for the {@code search} param - i.e.
      *              at least one of the username main attributes must match exactly the {@code search} param. If false,
      *              the method returns all members with at least one main attribute partially matching the {@code search} param.
-     * @param membershipType The {@link org.keycloak.representations.idm.MembershipType}.
+     * @param membershipType The {@link org.keycloak.representations.idm.MembershipType}. The parameter is supported since Keycloak 26.1
      * @param first index of the first element (pagination offset).
      * @param max the maximum number of results.
      * @return a list containing the matched organization members.
+     * @since Keycloak 26.1. Use method {@link #search(String, Boolean, Integer, Integer)} for the older versions of the Keycloak server
```
Comment (pskopek) [inline integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java:98]: Shouldn't `@since` tag contain just version number?

**Comment by pskopek** [comment]
Otherwise PR looks fine to me.

File: integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java (hunk 1 above)
Comment (mposolda) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java:113]: That's good point. We had same conversation about this with
@jonkoops 
few months ago . Found it on GH here: https://github.com/keycloak/keycloak/pull/32980#discussion_r1762608227 .

We decided to go with `@since` also for indicating the server version as it seems the definition of the `@since` tag is not so strict to enforce the specific format.

I've originaly added some simple text like `since` , but Jon proposed to used `@since` . Basically, we need to specify from which server version the particular endpoint (or parameter) is supported rather than version of the client itself where this endpoint was introduced.

**Review by pskopek — APPROVED** [review]
My earlier question was resolved with @mposolda . We will leave the change as is and start a discussion for proper usage of the tag.

**Comment by mposolda** [comment]
@pskopek Thanks!
