### PR TITLE
Fix cases when user is forced to re-authenticate

### LINKED ISSUE #9498: Username editable when user is forced to re-authenticate
### Describe the bug

See https://issues.redhat.com/browse/KEYCLOAK-18905

### Version

15.0.2

### Expected behavior

- During user re-authentication, the username field should not be editable. And it may not even be visible due the fact that username is shown at the top of the login screen

- There should be notification that user is re-authenticating (not authenticating from the scratch)

- In case that realm has registration enabled, there should not be "Registration" link available during re-authentication (Currently it is)

- Same applies for remember-me link

- During re-authentication, only the IDPs, which are already linked to the user account, should be shown on the login screen. Currently all realm IDPs are shown, which is not correct

- In case of identity-first (Separate username authenticator shown first), the Username authenticator can be entirely skipped and the password authenticator may be shown as first screen. This is possible just in case that user is not linked to any IDPs (There is limitation that IDPs are currently shown on the username form authenticator, but not on the passwordForm authenticator, which is hopefully something we can improve with authentication policies)

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
-    During user re-authentication, the username field should not be visible due the fact that username is shown at the top of the login screen and user should not be allowed to use username of different user during re-authentication

-    There should be notification that user is re-authenticating, so he knows why login screen is shown even if he is already authenticated

-    In case that realm has registration enabled, there should not be "Registration" link available during re-authentication (Currently it is in latest main)

-    Same applies for remember-me link

-    During re-authentication, only the IDPs, which are already linked to the user account, should be shown on the login screen. Current main has all realm IDPs shown, which is not correct

-    In case of identity-first (Separate username authenticator shown first), the Username authenticator can be entirely skipped and the password authenticator may be shown as first screen. This is possible just in case that user is not linked to any IDPs (There is limitation that IDPs are currently shown on the username form authenticator, but not on the passwordForm authenticator, which is hopefully something we can improve with authentication policies)

Closes #9498

### CODE REVIEW

**Comment by mposolda** [comment]
@stianst @pedroigor Does anyone of you has a chance to review this please? See description for more details

**Comment by stianst** [comment]
Tested this out with the admin console and Chrome developer console by running `auth.authz.login({maxAge: 1})`. It's now not letting me change the username which is nice, but spotted another issue. 

There's the action to `Restart login`, which should let me switch to a different user, but it doesn't as I just get taken straight back to the same screen asking me to re-authenticate.

image

Clicking on the `Restart login` just takes me back to the same page and doesn't let me actually restart the login to switch to a different user.

File: services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java [hunk 1]
```diff
@@ -54,6 +54,9 @@
     public static final String REGISTRATION_FORM_ACTION = "registration_form";
     public static final String ATTEMPTED_USERNAME = "ATTEMPTED_USERNAME";
 
+    // Flag is true if user was already set in the authContext before this authenticator was triggered. In this case we skip clearing of the user after unsuccessful password authentication
+    protected static final String USER_SET_BEFORE_USERNAME_PASSWORD_AUTH = "USER_SET_BEFORE_USERNAME_PASSWORD_AUTH";
```
Comment (stianst) [inline services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java:58]: Maybe rename to `USER_ALREADY_SET`?

**Review by stianst — CHANGES_REQUESTED** [review]
Looks pretty good, two things perhaps:

* Not able to restart the login to switch to a different user
* Tests don't seem to cover where there are multiple identity providers, and user has link to only one or a few of the registered providers, and only the linked idps are shown when re-auth

**Comment by mposolda** [comment]
> Looks pretty good, two things perhaps:
> 
>     * Not able to restart the login to switch to a different user

Yes, so far I've did it in a way that click the link will _Restart RE-authentication_ rather than _Restart authentication_ . So user re-authentication starts from the beginning (EG. When he is on the 2nd-factor authentication screen, he will be switched back to the initial screen with 1st-level authentication, but his username is still the same).

Changing it in the way you proposed will likely mean SSO session logout. As we currently does not have support for something like single SSO session for 2 different users. Is it ok to do SSO logout?

One addition to this is, that when user press "Restart link" during re-authentication, there can be another confirmation screen shown like _Restart of the login will logout your current session and you will authenticate from the beginning. Do you really want to logout?_ And SSO logout will be performed just when user confirms this.

> 
>     * Tests don't seem to cover where there are multiple identity providers, and user has link to only one or a few of the registered providers, and only the linked idps are shown when re-auth

I've added the scenario for this in the ReAuthenticationTest. There is added link for github IDP with the admin REST API and then checking that only "github" link is available on the login screen during re-authentication: https://github.com/keycloak/keycloak/blob/ee45e9f47ba3bf303558c1ecdf7b630c0ac16e9a/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ReAuthenticationTest.java#L252 .

There is similar scenario tested also for identity-first. Isn't this ok as coverage?

**Comment by stianst** [comment]
If user clicks on "re-auth" option I would simply go ahead and invalidate the current session and start from scratch. Don't think a confirmation is strictly needed?

**Comment by stianst** [comment]
For checking only idps that should be shown are, it seems that's okay then.

**Comment by mposolda** [comment]
> If user clicks on "re-auth" option I would simply go ahead and invalidate the current session and start from scratch. Don't think a confirmation is strictly needed?

Yeah, ok. It is easier without confirmation. Eventually we can add it as a follow-up (if someone asks for it). I will update PR for this.

**Comment by mposolda** [comment]
@stianst I've updated PR as we discussed, so the "Restart flow" will allow to login from the scratch with different username/password. Do you have a chance to re-review please?

**Review by stianst — APPROVED** [review]

**Comment by aghArdeshir** [comment]
Hello. I know this is not a Q&A, but I ended up here after a lot of investigation. Hoping for an answer.

In my application, sometimes users end up in this page, when their email/username is already filled up in the header (kc-attempted-username) and they are only prompted for password. With a reset-login-link active here.

But, if they try opening my app on another tab, they will be already logged in and everything works; so the re-authentication is actually unnecessary.

I couldn't find anything in the docs, now I'm wondering if there is a way to prevent this page from happening at all. I kinda find the essence of this state happening at all questionable:
image
