### PR TITLE
Certificate reloading does not work for the management interface

### LINKED ISSUE #37039: Certificate reloading dosen't work for management interface related certificate
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

We run a Keycloak server in k8s environment as a statefulset. 

We set the following env variables to point to the certificate and the key for Keycloak server and management interface 

1. KC_HTTPS_CERTIFICATE_FILE and KC_HTTPS_CERTIFICATE_KEY_FILE for Keycloak server
2. KC_HTTPS_MANAGEMENT_CERTIFICATE_FILE and KC_HTTPS_MANAGEMENT_CERTIFICATE_KEY_FILE for the management interface 
3. KC_HTTPS_CERTIFICATES_RELOAD_PERIOD is set to "5m"

Same set of certificate-key pair is passed for keycloak server and management interface

Our management interface exposes  the metrics and health endpoints.

- When certificate and key is changed, after the specified interval reload happens for the Keycloak server's own keystore certificate and file. This can be verified by running "curl -kv <keycloak-url>" command is run for its service endpoint. 

- Ideal behavior according to the statement present in https://www.keycloak.org/server/enabletls#_certificate_and_key_reloading " is Keycloak will reload the certificates, keys, and keystores specified in https-* options" the same should have happened for the management interface. 
   Do a "curl -kv <keycloak-url>/health" command for its health endpoint. We can see that reloading has not happened and it still points to the initial one used.

### Version

26.1.0

### Regression

- [ ] The issue is a regression

### Expected behavior

As described in the documentation  https://www.keycloak.org/server/enabletls#_certificate_and_key_reloading , Keycloak will reload the certificates, keys, and keystores specified in https-* options  based on the value we have configured for KC_HTTPS_CERTIFICATES_RELOAD_PERIOD

The reload of certificate related to management interface should have happened  and we should have been able to see this change post the KC_HTTPS_CERTIFICATES_RELOAD_PERIOD value configured.

### Actual behavior

Reloading of certificates related to management interface is not done and it still points to the initial one used.  

### How to Reproduce?

1. Bring up Keycloak server with same certificate-key pair for Keycloak's keystore and for management interface. Set the environment variables for the same along with the KC_HTTPS_CERTIFICATES_RELOAD_PERIOD=5m .

2. Do a curl to keycloak server endpoint and for health endpoint, you will see your certificate being used. 
3. Edit the certificate-key pair used. Wait for the reload interval to pass by.

4. Do a curl to the keycloak-service endpoint, you will be able to see that the certificate has been reloaded. Do a curl to the health endpoint exposed via management interface, you will notice that the certificate still points the initial one that was given 
 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Fixes #37039

### CODE REVIEW

File: quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public enum ClientAuth {
 
     public static final Option<String> HTTPS_CERTIFICATES_RELOAD_PERIOD = new OptionBuilder<>("https-certificates-reload-period", String.class)
             .category(OptionCategory.HTTP)
-            .description("Interval on which to reload key store, trust store, and certificate files referenced by https-* options. May be a java.time.Duration value, an integer number of seconds, or an integer followed by one of [ms, h, m, s, d]. Must be greater than 30 seconds. Use -1 to disable.")
+            .description("Interval on which to reload key store, trust store, and certificate files referenced by https-* options for the main server. May be a java.time.Duration value, an integer number of seconds, or an integer followed by one of [ms, h, m, s, d]. Must be greater than 30 seconds. Use -1 to disable.")
```
Comment (shawkins) [inline quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java:68]: This change by itself might be confusing. The other properties that serve as a default for the corresponding management property aren't similarly qualified.

Comment (mabartos) [reply quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java:68]: Yep - probably does not have to be there anyway.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

**Review by shawkins — APPROVED** [review]
LGTM
