### PR TITLE
[OID4VCI] Fix OID4VC wallet interoperability issues 

### LINKED ISSUE #44736: Fix OID4VCI Wallet Interoperability Issues (Draft 15 Compatibility & Metadata Compliance)
## Summary

Several interoperability issues were discovered during testing with multiple OID4VC wallets (Ubique, Valera, Heidi, etc.).
These issues were caused by differences between older Draft 15 behavior and the current OID4VCI specification.
This enhancement introduces backward-compatible handling and spec-aligned metadata serialization to ensure smooth interactions across wallets.

### 1. Support legacy single proof format (Draft 15 compatibility)

Some wallets still send a single proof object instead of the current proofs[] array structure.

### 2. Accept deprecated keyattestation+jwt typ header

Older wallet implementations use the deprecated `keyattestation+jwt` `typ` value (missing hyphen).

### 3. Correct metadata for optional key attestation

When key attestation is not required, the `key_attestations_required` parameter must be omitted from the issuer metadata according to the OID4VCI specification. This ensures that the issuer does not unintentionally signal that key attestation is needed and avoids unnecessary wallet-side validation or misinterpretation.

## Benefits

* Ensures full interoperability with commonly used OID4VC wallets, including those still following Draft 15 conventions.
* Reduces integration friction for implementers by gracefully handling legacy formats.
* Produces spec-compliant metadata, preventing wallet-side parsing issues.
* Improves overall stability and reliability of the OID4VCI credential issuance flow in Keycloak.

### Goals

* Provide seamless interoperability with both modern OID4VCI-compliant wallets and older Draft-15-based implementations.
* Normalize incoming proof structures so that Keycloak can consistently process both single-object and array-based proof formats.
* Accept both the current and deprecated `typ` header values for key attestation JWTs to avoid unnecessary validation failures in older wallets.
* Ensure the metadata correctly reflects whether key attestation is required by omitting the `key_attestations_required` field entirely when it is not needed.

### Non-Goals

* This enhancement does not introduce new proof types, cryptographic binding methods, or credential format profiles beyond those already supported.
* It does not modify the core OID4VCI authorization flow, issuance flow, or token endpoint behavior.
* It does not enforce or introduce new key attestation policies; it only ensures correct metadata representation and validation of existing ones.
* It does not provide full compatibility for arbitrary non-standard wallet implementations—only the Draft 15–compatible behaviors explicitly addressed.
* It does not alter existing administrative UI functionality or introduce new configuration options.

### Discussion

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by forkimenjeckayang**
## Summary

Fixes compatibility issues discovered during wallet interop testing with Ubique, Valera and other wallets, ensuring backward compatibility with Draft 15 format and proper handling of optional key attestation requirements.

### Changes

**1. Legacy proof payload format (Draft 15 compatibility)**

- Added backward compatibility in `normalizeProofFields()` to automatically convert single `proof` objects to the `proofs` array structure

- Ensures Draft 15 wallets using the single proof object format continue to work

**2. Legacy attestation JWT typ header (Draft 15 compatibility)**

- Updated `AttestationValidatorUtil.validateJwsHeader()` to accept deprecated `keyattestation+jwt` typ (without hyphen) for backward compatibility

- Logs deprecation warning while accepting both `key-attestation+jwt` and `keyattestation+jwt` formats

**3. Empty key_attestations_required in metadata**

- Empty `key_attestations_required` is excluded from metadata by setting the field to `null`

- The `@JsonInclude(JsonInclude.Include.NON_NULL)` annotation on `SupportedProofTypeData` ensures null values are automatically excluded from JSON serialization per OID4VCI spec requirement

- Ensures empty `key_attestations_required` is not present in metadata when attestation is not required

closes #44736

### CODE REVIEW

**Comment by mposolda** [comment]
@forkimenjeckayang Thanks! Could you please create issue with the description of what this fixes (if it doesn't exist yet) and add to the first line of the description of this issue. Something like `closes #123456` . See description of other Keycloak PRs for the details (BTW. The message about `closes #xyz` is automatically added to the issue description if you include it in the commit message).

**Comment by forkimenjeckayang** [comment]
> @forkimenjeckayang Thanks! Could you please create issue with the description of what this fixes (if it doesn't exist yet) and add to the first line of the description of this issue. Something like `closes #123456` . See description of other Keycloak PRs for the details (BTW. The message about `closes #xyz` is automatically added to the issue description if you include it in the commit message).

Hello @mposolda , I have created an issue and linked this PR to it. Due to Pascal's code that was recently , merged https://github.com/keycloak/keycloak/pull/44471, the current code now omits `key_attestations_required` only when `vc.key_attestations_required` is false/absent.

**Comment by forkimenjeckayang** [comment]
Hello @mposolda , this PR is ready for review now
Please check when you have time..

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/keybinding/AttestationValidatorUtil.java [hunk 1]
```diff
@@ -291,8 +296,16 @@ private static void validateJwsHeader(JWSHeader header) {
...
 
-        if (!ATTESTATION_JWT_TYP.equals(header.getType())) {
-            throw new VCIssuerException("Invalid JWT typ: expected " + ATTESTATION_JWT_TYP);
+        String typ = Optional.ofNullable(header.getType())
+                .map(Object::toString)
+                .orElseThrow(() -> new VCIssuerException("Missing typ in JWS header"));
+
+        if (!ATTESTATION_JWT_TYP.equals(typ)) {
+            if (LEGACY_ATTESTATION_JWT_TYP.equals(typ)) {
+                LOGGER.debugf("Accepting deprecated attestation JWT typ '%s' for backward compatibility", typ);
```
Comment (wistefan) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/keybinding/AttestationValidatorUtil.java:305]: I think this should be on a higher log-level to actually become visible.

**Review by wistefan — APPROVED** [review]
LGTM

**Review by mposolda — APPROVED** [review]
@forkimenjeckayang @wistefan Thanks for the PR and review!
