### PR TITLE
Group count and PartialExport permission fixes

### LINKED ISSUE #12171: Inconsistent authorization behavior when exporting data from a realm
### Describe the bug

_Originally reported by_ **Muhammad Uwais**

## Scenario 1

An authenticated user with "View Realm" role enabled would be able to export all the information about the realm and disclose all "Client scopes" name and information.

Export and Client Scope feature is only available to the the users which have the role mapping as "Realm Admin" or "Manage-Realm/Manage-Client" enabled.  

### Steps to reproduce

1- Log into keycloak as a non-admin user with "view-realm" role mapping.  
2- Browser to [http://localhost:8080/admin/PentestRealm/console/#/realms/PentestRealm/partial-export](http://localhost:8080/admin/PentestRealm/console/#/realms/PentestRealm/partial-export)
3- Click "Export" and you will be able to export the realm information in json format.

## Scenario 2

An authenticated user with role mapping set to "View-Realm" would be able to determine the number of Groups for the realm.
Groups count is only available to the users with role mapping set as "Realm-Admin" or "Manage-Groups".

### Steps to reproduce

1- Log into the keycloak with the "View-Realm" role mapping.  
2- Make any request and intercept it to get the authentication bearer token. (use any proxy tool such as burp). Copy the Bearer token for the account.
3- Make the following curl request and change the <token> from step 2.
```
curl [http://localhost:8080/admin/realms/PentestRealm/groups/count?top=true](http://localhost:8080/admin/realms/PentestRealm/groups/count?top=true) -H "Authorization: Bearer <token>"
```

**Recommendation/Fix:** Validate the permission on the mentioned request in POC.

### Version

18.0.0

### Expected behavior

Users with `View Realm` role should not be enabled to export all the information about the realm and all "Client scopes" name and information, or determine the number of groups.

### Actual behavior

Users with `View Realm` role can export all the information about the realm and all "Client scopes" name and information, or determine the number of groups.

### Anything else?

Potential fixes suggested by @JoshuaMulliken:
1. Add documentation or help text that explains that the view-only role allows users to export ALL realm data including the client scope info through the API (I would also recommend showing the export button to the user).
2. Restrict the API endpoint for those with the view-only role to force it to match the UI

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/12171

* Scenario 1: This is a change in permissions, previously it was `view-realm` and with this PR the export requires `manage-realm`. There were tests checking the old behavior. As the issue is directly requesting this permission I have just changed it. To include groups/clients in the export the same permissions as before are requested (list/view respectively). If anyone has any concern or we need some documentation, just let me know. @keycloak/ui I have modified the realm header to mark enable/disable toggle and the action options as read-only if the admin doesn't  have `manage-realm` permission. Lint is OK, let's see the tests.

* Scenario 2 was fixed yesterday by [#22700 ](https://github.com/keycloak/keycloak/pull/22700/files#diff-cdba8763b4828809135e80a085d9b697f88fe999a9d76ad06988037a5403c84eR146-R147) :smile: . I needed to rebase because of the conflict. So it's fixed now.

`PermissionsTest` class modified to add tests for both modifications.

### CODE REVIEW

**Comment by rmartinc** [comment]
That test works for me locally so maybe it's spureous:

```
CYPRESS_BASE_URL=http://localhost:8080/admin/ CYPRESS_KEYCLOAK_SERVER=http://localhost:8080 /home/rmartinc/.local/share/pnpm/pnpm run cy:run --browser chromium --spec ./cypress/e2e/realm_settings_general_tab_test.spec.ts

> admin-ui@ cy:run /home/rmartinc/keycloak/js/apps/admin-ui
> cypress run --browser chrome "--browser" "chromium" "--spec" "./cypress/e2e/realm_settings_general_tab_test.spec.ts"

  (Run Starting)
  ...                                                                                                 
  Running:  realm_settings_general_tab_test.spec.ts                                         (1 of 1)


  Realm settings general tab tests
    ✓ Test all general tab switches (9365ms)
    ✓ Modify Display name (2227ms)
    ✓ Check Display name value (1579ms)
    ✓ Modify front end URL (2211ms)
    ✓ Select SSL all requests (1851ms)
    ✓ Verify SSL all requests displays (1544ms)
    ✓ Select SSL external requests (1887ms)
    ✓ Verify SSL external requests displays (1671ms)
    ✓ Select SSL None (2021ms)
    ✓ Verify SSL None displays (1557ms)
    ✓ Check Access Endpoints OpenID Endpoint Configuration link (1563ms)
    ✓ Access Endpoints OpenID Endpoint Configuration link (1527ms)
    ✓ Check if Access Endpoints SAML 2.0 Identity Provider Metadata link exists (1568ms)
    ✓ Access Endpoints SAML 2.0 Identity Provider Metadata link (1661ms)
    ✓ Verify 'Revert' button works (2170ms)


  15 passing (35s)
```

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx [hunk 1]
```diff
@@ -71,6 +72,9 @@ const RealmSettingsHeader = ({
   const [partialImportOpen, setPartialImportOpen] = useState(false);
   const [partialExportOpen, setPartialExportOpen] = useState(false);
 
+  const { hasAccess } = useAccess();
+  const isManageRealm = hasAccess("manage-realm");
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx:76]: Perhaps this would be more appropriately named `canManageRealm`?

```suggestion
  const canManageRealm = hasAccess("manage-realm");
```

**Review by jonkoops — DISMISSED** [review]
Aside from a small nit this code looks good to me.

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx (hunk 1 above)
Comment (rmartinc) [reply js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx]: Done! :wink:

**Review by pedroigor — COMMENTED** [review]
@rmartinc We probably need release notes for this one.

**Review by pedroigor — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by jonkoops — APPROVED** [review]
