### PR TITLE
[OID4VCI] Revisit and fix OAuthClient.credentialOfferRequest()

### LINKED ISSUE #46001: [OID4VCI] Revisit and fix OAuthClient.credentialOfferRequest()
### Description

Currently we send a CredentialOffer request like this ...

```
        CredentialOfferResponse credentialOfferResponse = oauth.oid4vc()
                .credentialOfferRequest()
                .endpoint(offerUri)
                .send();
        int statusCode = credentialOfferResponse.getStatusCode();
        if (HttpStatus.SC_OK != statusCode) {
            throw new IllegalStateException(credentialOfferResponse.getErrorDescription() != null
                    ? credentialOfferResponse.getErrorDescription()
                    : "Request failed with status " + statusCode);
        }
        CredentialsOffer credOffer = credentialOfferResponse.getCredentialsOffer();
```

or 

```
        CredentialOfferResponse credentialOfferResponse = oauth.oid4vc()
                .credentialOfferRequest()
                .nonce(credOfferUri.getNonce())
                .send();
        int statusCode = credentialOfferResponse.getStatusCode();
        if (HttpStatus.SC_OK != statusCode) {
            throw new IllegalStateException(credentialOfferResponse.getErrorDescription() != null
                    ? credentialOfferResponse.getErrorDescription()
                    : "Request failed with status " + statusCode);
        }

```

This code has several issues ...

* It (again often) relies on constructing the endpoint Url externally
* From a Wallet perspective - it has the complete offerUrl (nonce is a Keycloak proprietary thing)
* From our test API perspective we have the CredentialOfferURI, which can be used directly
* error handling should not have to be duplicated for every request

### Value Proposition

* use credential offer url or CredentialOfferURI directly
* error handling by CredentialOfferResponse

### Goals

Cleaner and more reliable code

### Non-Goals

--

### Discussion

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by tdiesler**
closes #46001

### CODE REVIEW

**Comment by tdiesler** [comment]
Consider merging #46014 instead

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCCredentialOfferCorsTest.java [hunk 1]
```diff
@@ -339,12 +335,12 @@ public void testCredentialOfferUriWithInvalidCredentialConfig() throws Exception
     }
 
     @Test
+    @Ignore // [TODO] Replace nonceHolder with other mechanism that does not rely on a shared ClassLoader
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCCredentialOfferCorsTest.java]: Is it possible to avoid introducing this `Ignore` ?

There is method `testingClient.server(TEST_REALM_NAME).fetchString` . Maybe this one can be used instead of `testingClient.server(TEST_REALM_NAME).run` and can directly return nonce? This should allow to remove `nonceHolder` variable as well.

**Review by mposolda — COMMENTED** [review]
@tdiesler Thanks! I hope we can apply this PR.

Added small comment inline regarding "ignored" test. Can you please check?

**Comment by mposolda** [comment]
> Consider merging #46014 instead

In general, it is preferred in Keycloak to have more smaller PRs rather than one huge PR. Simplifies review a lot and allows to divide the needed work into multiple chunks, which can be discussed and applied gradually.

Sometimes it may not be easily possible (for example when some method, which is used in many places, needs to be renamed or refactored), but in generally, it is preferred whenever possible.

**Comment by tdiesler** [comment]
We can do this either way. If you prefer to merge individually, it's best to do it the natural order as #46014 suggests - merge conflicts will have to be resolved as we go along.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCCredentialOfferCorsTest.java (hunk 1 above)
Comment (tdiesler) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCCredentialOfferCorsTest.java]: Yes, that is what I was looking for - thanks a lot

**Review by mposolda — DISMISSED** [review]
@tdiesler Thanks! I hope to merge if tests are OK (hope re-run helps as it seems the UI tests failures are not related to your changes).

**Review by mposolda — APPROVED** [review]
