### PR TITLE
Fix for Network error attempting to view events without permissions

### LINKED ISSUE #31918: Network error attempting to view events without permissions
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If a user has view-event or manage-event permission they can see events under realm settings else they get 403 forbidden error as per the below screenshot 
Screenshot 2024-08-06 at 9 25 49 AM

### Version

quay.io/keycloak/keycloak:latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Permissions error should not be shown

### Actual behavior

403 forbidden error and admin console unresponsive.

### How to Reproduce?

1. Create a realm
2. Create a user in the realm with view-realm permissions
3. Log in as that user
4. Go to Realm Settings 
5. Click on Events tab

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaustubh-rh**
Closes #31918

### CODE REVIEW

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx [hunk 1]
```diff
@@ -361,13 +364,15 @@ export const RealmSettingsTabs = () => {
...
-          </Tab>
+          {canViewOrManageEvents ? (
+            <Tab
+              title={<TabTitleText>{t("events")}</TabTitleText>}
+              data-testid="rs-realm-events-tab"
+              {...eventsTab}
+            >
+              <EventsTab realm={realm!} />
+            </Tab>
+          ) : null}
```
Comment (ssilvert) [inline js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx:375]: This should be a cleaner way to do it.  Give this a try:
```suggestion
          {canViewOrManageEvents && (
            <Tab
              title={<TabTitleText>{t("events")}</TabTitleText>}
              data-testid="rs-realm-events-tab"
              {...eventsTab}
            >
              <EventsTab realm={realm!} />
            </Tab>
          )}
```

**Review by ssilvert — DISMISSED** [review]

**Review by ssilvert — APPROVED** [review]
