### PR TITLE
fix: separating api server tests, and splitting the operator tests

### LINKED ISSUE #37853: Operator test runs are taking too long in github
### Description

We've had several iterations of performance improvements to decrease operator test runs, but were still routinely over 40 minutes for the remote test pre-update strategy. After that we're getting close to 50 minute remote runs.

We should determine is there is any more low hanging fruit for optimization, and if not then split the test suite.

cc @vmuzikar @ahus1 @pruivo

### PR DESCRIPTION
**Pull request by shawkins**
closes: #37853

### CODE REVIEW

File: operator/src/test/java/org/keycloak/operator/testsuite/apiserver/CRDTest.java [hunk 1]
```diff
@@ -33,12 +33,13 @@
...
 import com.fasterxml.jackson.databind.ObjectMapper;
 import org.keycloak.operator.crds.v2alpha1.realmimport.KeycloakRealmImportBuilder;
+import org.keycloak.operator.testsuite.integration.BaseOperatorTest;
 import org.keycloak.operator.testsuite.utils.K8sUtils;
 
 import static org.assertj.core.api.Assertions.assertThat;
 import static org.junit.jupiter.api.Assertions.assertThrows;
 
-@KubernetesTest
+@EnableKubeAPIServer
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/apiserver/CRDTest.java:42]: I wonder if this really saves so much time. We're not starting the Operator in this test, K8s is running already for other tests. Do we know what difference does it make in comparison to interacting with the real K8s API server?

**Review by vmuzikar — DISMISSED** [review]
Thanks for the PR! Added one question but LGTM so approving regardless.

File: operator/src/test/java/org/keycloak/operator/testsuite/apiserver/CRDTest.java (hunk 1 above)
Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/apiserver/CRDTest.java:42]: This isn't about saving time - yet. While k8s is currently running for the other tests currently, this style of test in the future provides not only a better dev experience - no minikube or kubernetes setup - but it forces us to focus on testing without resorting to the full server with a better "mock" experience that using the built-in fabric8 mock logic.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/apiserver/CRDTest.java:42]: Ok, thanks for clarifying. In this specific case it's IMHO ok to take the "mocking" approach but we'll need to carefully decide each test that should use this approach.

**Comment by vmuzikar** [comment]
Can you please rebase, so we could merge?

**Comment by shawkins** [comment]
> Can you please rebase, so we could merge?

@vmuzikar should be good now.

**Review by vmuzikar — APPROVED** [review]
