### PR TITLE
Fix for Email settings erased after any change on realm settings

### LINKED ISSUE #19746: Email settings erased after any change on realm settings
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Email settings keep reverting to blank after any other realm settings update. Only way to go around it for now is to setup everything and do email settings at the end. 

### Version

21.0.2

### Expected behavior

Email Settings remain as were saved before other realm changes

### Actual behavior

Email Settings completely wiped after change. 

### How to Reproduce?

Steps to reproduce: 

1. Setup email on admin user
2. Create new realm
3. Setup email for realm
4. Change any other realm settings (in my case disable https requirements for incoming requests) 
5. go back to email settings

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by btirth**
Modified the save function in RealmSettingsTabs.tsx to save the email settings and removed the custom save function from EmailTab.tsx.

Closes #19746

### CODE REVIEW

**Review by edewit — DISMISSED** [review]

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx [hunk 1]
```diff
@@ -199,14 +199,15 @@ export const RealmSettingsTabs = ({
...
     try {
-      await adminClient.realms.update(
-        { realm: realmName },
-        {
-          ...realm,
-          ...r,
-          id: r.realm,
-        }
-      );
+      const savedRealm = {
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx:202]: I think we should add a type annotation here, the inferred type is very dynamic.

```suggestion
      const savedRealm: RealmRepresentation = {
```

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx [hunk 2]
```diff
@@ -199,14 +199,15 @@ export const RealmSettingsTabs = ({
...
+        ...realm,
+        ...r,
+        id: r.realm,
+      };
+
+      // For default value, back end is expecting null instead of empty string
+      if (savedRealm.smtpServer?.port === "") savedRealm.smtpServer.port = null;
```
Comment (jonkoops) [inline js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx:209]: Note that even though a new object is created before, it still contains a reference to the original realm since `realm.smtpServer` is nested and spreading an object using the spread operator (`...`) only creates a shallow clone.

If we want to accomplish this without mutating the original reference we can do the following:
```suggestion
      // For the default value, null is expected instead of an empty string.
      if (savedRealm.smtpServer?.port === "") {
        savedRealm.smtpServer = { ...savedRealm.smtpServer, port: null };
      }

```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx (hunk 2 above)
Comment (tirth1) [reply js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx]: @jonkoops thank you for pointing out.

**Review by jonkoops — APPROVED** [review]
LGTM, thanks for helping us land this @tirth1!

**Comment by tirth1** [comment]
@jonkoops can you please help here? Some of the checks are failing.

**Comment by jonkoops** [comment]
Did a quick rebase, hopefully it will pass after this.
