### PR TITLE
fix: ensuring exit codes are handled consistently

### LINKED ISSUE #38161: RawKeycloakDistribution exit code is always 0
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

When making a distribution run with non-zero exit in the testsuite the `RawKeycloakDistribution`  does not provide correct exit code.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

When running this distribution run: https://github.com/keycloak/keycloak/blob/3c0fc83842a43b358a350722b3b2b92b9dc91d2f/quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java#L96 

the expected call to `result.exitCode()` should return non-zero exit code.

### Actual behavior

The run return 0.

### How to Reproduce?

Run the following test in debug mode: https://github.com/keycloak/keycloak/blob/3c0fc83842a43b358a350722b3b2b92b9dc91d2f/quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java#L87-L107

The result on line 96 should have non-zero exit code, however, the exit code is 0.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #38161

### CODE REVIEW

**Comment by shawkins** [comment]
We were making the test launch mode pull double duty. It was both causing an early exit, and preventing System.exit calls. Rather than removing the launch mode from the raw dist, I'm using it only for the early exit. Now we attempt to detect what type of launch were using by the classloader and adjust our exit handling accordingly. @pedroigor does this work for you / embedded usage?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java [hunk 1]
```diff
@@ -140,45 +153,38 @@ private static boolean isFastStart(List<String> cliArgs) {
...
             // in test mode we exit immediately
             // we should be managing this behavior more dynamically depending on the tests requirements (short/long lived)
-            Quarkus.asyncExit(exitCode);
+            Quarkus.asyncExit(ApplicationLifecycleManager.getExitCode());
         } else {
             Quarkus.waitForExit();
         }
 
-        return exitCode;
+        return ApplicationLifecycleManager.getExitCode();
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java:187]: Jus out of curiosity, why is this change needed? Why can't we store the exit code in a var?

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

I tested the embedded server and it seems fine – even better  than before as it nows properly exits the process on error instead of just hanging.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java:187]: That's a potential bug, we don't want to store it because it could change while the waiting for exit.
