### PR TITLE
Fix for Issue #26937

### LINKED ISSUE #26937: Once all default client scopes are deleted from the realm we can't create a new custom role.
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I've deleted all default roles from the 'Client Scopes' and i'm not able to create a new one.
The button **Create a client scope** is missing.
image

### Version

23.0.6

### Expected behavior

To have the ability to create a custom client scopes.

### Actual behavior

The button for creating client scopes is missing.

### How to Reproduce?

Delete all client scopes.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaustubh-rh**
Made it not possible to remove all the client scopes .Issue https://github.com/keycloak/keycloak/issues/26937

Closes #26937

### CODE REVIEW

**Comment by edewit** [comment]
There should also be a check on the backend, because now I can still do it with the rest endpoint

**Comment by kaustubh-rh** [comment]
Hi @edewit , thank you for the update. Added the check on the backend.

File: services/src/main/java/org/keycloak/services/resources/admin/ClientScopeResource.java [hunk 1]
```diff
@@ -148,14 +149,19 @@ public ClientScopeRepresentation getClientScope() {
...
 
-        try {
-            realm.removeClientScope(clientScope.getId());
-            adminEvent.operation(OperationType.DELETE).resourcePath(session.getContext().getUri()).success();
-            return Response.noContent().build();
-        } catch (ModelException me) {
-            throw ErrorResponse.error(me.getMessage(), Response.Status.BAD_REQUEST);
+        auth.clients().requireManage(clientScope);
+        long ClientScopesCount =  Arrays.stream(realm.getClientScopesStream().toArray()).count();
+        if(ClientScopesCount>1) {
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/resources/admin/ClientScopeResource.java:155]: Minor: formatting. Could you please use spaces? So something like `if (clientScopesCount > 1) {` . This applies for some other places in this PR (Like for example `} else }` etc. Also can be good to rename variable `ClientScopesCount` with lower case at the beginning (java convention to use lowercased variables).

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java [hunk 2]
```diff
@@ -320,6 +320,10 @@ public void deleteClientScopeTest(KeycloakSession session) {
 
             ClientScopeModel fooScope = KeycloakModelUtils.getClientScopeByName(realm, "foo");
             realm.removeClientScope(fooScope.getId());
+            ClientScopeModel barScope = KeycloakModelUtils.getClientScopeByName(realm, "bar");
+            try {
+                realm.removeClientScope(barScope.getId());
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java:325]: If it is expected that clientScope cannot be removed, then it can be good to add `fail` into the `try` block. As otherwise it is not tested that removing of client scope failed. So something like:
```
try {
    realm.removeClientScope(barScope.getId());
    Assert.fail("It is not expected to successfully remove client scope bar");
} catch (Exception expected) {}
```
```

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentWithUserStorageModelTest.java [hunk 3]
```diff
@@ -330,6 +330,10 @@ public void deleteClientScopeTest(KeycloakSession session) {
             ClientModel fooClient = realm.getClientByClientId("foo-client");
             ClientScopeModel fooScope = KeycloakModelUtils.getClientScopeByName(realm, "foo");
             realm.removeClientScope(fooScope.getId());
+            ClientScopeModel barScope = KeycloakModelUtils.getClientScopeByName(realm, "bar");
+            try {
+                realm.removeClientScope(barScope.getId());
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentWithUserStorageModelTest.java:335]: Same comment as above.

**Review by mposolda — COMMENTED** [review]
@kaustubh-rh Thanks! Added few comments inline, but only minor things. I did not review UI part (leaving for UI team to review that).

**Comment by kaustubh-rh** [comment]
Hi @mposolda , thanks for the update .I have updated the same

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java (hunk 2 above)
Comment (kaustubh-rh) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java]: I replaced it with `Assert.assertTrue(realm.removeClientScope(barScope.getId()));`

as `removeClientScope` returns a boolean

Comment (mposolda) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java]: @kaustubh-rh Thanks, but if I understand correctly, since removing of the client scope is still OK and returns true, it means that you are not testing at all the new functionality, which you added to `ClientScopeResource` ? The test changes in `UserConsentModelTest.java` were passing even before your changes if I understand correctly.

To test that it is not possible to remove all realm client scopes, I suggest to add a new test method to `ClientScopeTest`, which tests admin REST API. You can probably inspire from some of the tests in this class.

Comment (kaustubh-rh) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java]: Hi @mposolda , thanks, I did the required changes.

File: js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties [hunk 4]
```diff
@@ -282,6 +282,7 @@ samlKeysExportError=无法导出密钥，因为：{{error}}
 webAuthnPolicyCreateTimeout=超时
 comparison=对比
 deletedSuccessClientScope=客户端作用域已删除
+notAllowedToDeleteAllClientScopes=您不能删除所有客户端范围
```
Comment (jonkoops) [inline js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties:285]: @xianli123 could you verify this translation is accurate?

**Review by jonkoops — DISMISSED** [review]
Changes to the front-end look good to me.

File: js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties (hunk 4 above)
Comment (xianli123) [inline js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties:285]:
```suggestion
notAllowedToDeleteAllClientScopes=您不能删除所有客户端作用域
```

**Review by xianli123 — CHANGES_REQUESTED** [review]
I would change the line 285 from `notAllowedToDeleteAllClientScopes=您不能删除所有客户端范围` to `notAllowedToDeleteAllClientScopes=您不能删除所有客户端作用域`. In this way, we can keep the wording consistent.

File: js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties (hunk 4 above)
Comment (xianli123) [reply js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties:285]: Yes. I made a suggestion for the line #285. @jonkoops

**Review by jonkoops — APPROVED** [review]

**Review by mposolda — APPROVED** [review]
@kaustubh-rh @jonkoops Thanks for the updates and review! I hope to merge if tests are OK (saw the failure in UI test, but looks it might be rather some instability not related to this PR. So tried to re-run UI tests).

**Comment by jonkoops** [comment]
@mposolda Yeah, we've been having some test stability issues recently. I think this is good to go, thanks again @kaustubh-rh!
