### PR TITLE
Show the original exception when shutdown of Keycloak failed

### LINKED ISSUE #25424: Improve logging of Quarkus process when it failed to stop it
### Description

When analyzing #23786, I found that the original exception is missing.

The logs about an unresolved host name in the hosts file where already resolved in #22035.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #25424

It also adds bits of redirection to ensure STDERR is captured as well by the trimmer.

### CODE REVIEW

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java [hunk 1]
```diff
@@ -98,6 +107,39 @@ public RawKeycloakDistribution(boolean debug, boolean manualStop, boolean enable
...
+
+                // now the resolving of the hostname should work as expected
+                try {
+                    //noinspection ResultOfMethodCallIgnored
+                    InetAddress.getLocalHost();
+                } catch (UnknownHostException e) {
+                    throw new RuntimeException("unable to resolve host name even after adding it to the host_name file", e);
+                }
+            }
+        }
```
Comment (mabartos) [inline quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java:142]: @ahus1 I'm not sure if we can override the 'jdk.net.hosts.file' hosts file without any fallback. For GHA CI it's probably acceptable, but not sure if we can do it when a user execute these tests on a local machine/server. 

Moreover, can you point me to some job, where the `Unable to resolve host` warnings are printed? AFAIK, for the FipsDistTest, there are not such msgs and I haven't spotted it for a long time. AFAIK, these warnings should be already gone after merging this PR: https://github.com/keycloak/keycloak/pull/22035.

Nitpick: Potentially, I'd separate it into a new self-descriptive method as it might be a little bit confusing to have written such a functionality in the constructor, right?

Comment (ahus1) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]: You're right, this was already fixed. I think I was mislead by the login the original issue. 

I saw in this run that those exceptions are no longer there: https://github.com/keycloak/keycloak/actions/runs/7139549047/job/19451789357

I removed that part, and only kept the bit that shows the original exception.

**Review by mabartos — APPROVED** [review]
Thanks @ahus1. LGTM!

**Review by stianst — APPROVED** [review]
