### PR TITLE
Fix NPE when importing SAML EntityDescriptor without SPSSODescriptor

### LINKED ISSUE #44430: NPE when importing SAML EntityDescriptor without SPSSODescriptor
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When importing a SAML EntityDescriptor via the SAML Entity Descriptor Client Registration endpoint, Keycloak throws a NullPointerException if the uploaded metadata does not contain an SPSSODescriptor.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Error handling

### Actual behavior

Keycloak returns server error:
```
Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.dom.saml.v2.metadata.SPSSODescriptorType.isWantAssertionsSigned()" because "spDescriptorType" is null
        at org.keycloak.protocol.saml.EntityDescriptorDescriptionConverter.loadEntityDescriptors(EntityDescriptorDescriptionConverter.java:193)
        at org.keycloak.protocol.saml.EntityDescriptorDescriptionConverter.convertToInternal(EntityDescriptorDescriptionConverter.java:73)
        at org.keycloak.protocol.saml.clientregistration.EntityDescriptorClientRegistrationProvider.createSaml(EntityDescriptorClientRegistrationProvider.java:47)
        at org.keycloak.protocol.saml.clientregistration.EntityDescriptorClientRegistrationProvider$quarkusrestinvoker$createSaml_7b43b364c4f60a385ea6d147f84361448f568d5a.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:183)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:645)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### How to Reproduce?

 1. Build and run Keycloak:
```
./mvnw -pl quarkus/dist -am clean install
./kc.sh start-dev
```
 2. POST SAML metadata without an SPSSODescriptor:
```
curl -X POST \
  -H "Content-Type: application/xml" \
  --data-binary @keycloak/saml-core/src/test/resources/org/keycloak/saml/processing/core/parsers/saml/KEYCLOAK-4809-IdPMetadata_test.xml \
  http://localhost:8080/realms/master/clients-registrations/saml2-entity-descriptor
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PavlNekrasov**
resolves #44430

### CODE REVIEW

**Comment by mposolda** [comment]
@rmartinc Do you please have a chance to review this PR?

File: services/src/main/java/org/keycloak/protocol/saml/EntityDescriptorDescriptionConverter.java [hunk 1]
```diff
@@ -187,6 +187,7 @@ private static ClientRepresentation loadEntityDescriptors(InputStream is) {
         attributes.put(SamlConfigAttributes.SAML_SIGNATURE_ALGORITHM, SignatureAlgorithm.RSA_SHA256.toString());
         attributes.put(SamlConfigAttributes.SAML_AUTHNSTATEMENT, SamlProtocol.ATTRIBUTE_TRUE_VALUE);
         SPSSODescriptorType spDescriptorType = getSPDescriptor(entity);
+        if (spDescriptorType == null) return app;
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/protocol/saml/EntityDescriptorDescriptionConverter.java]: This method is to create a SAML client via the  `SPSSODescriptor`. So, if the descriptor is not for an SP, maybe it's better to throw an exception. Because it makes no sense returning something that will be completely empty or filled with default values. Similar to the case when there is no entity descriptor a few lines before. Something like:

```java
if (spDescriptorType == null) {
    throw new RuntimeException("No SPSSODescriptorType defined in the entity descriptor file");
}
```

If you prefer you can return a `BadRequestException`. Because, just curiosity, what are you trying to import here? A IDPSSODescriptor or another thing?

**Review by rmartinc — CHANGES_REQUESTED** [review]
I think that throwing an exception would be better than returning an empty client. WDYT?

**Comment by PavlNekrasov** [comment]
I was fuzzing `convertToInternal()`.
I’d suggest using a **BadRequestException** in `loadEntityDescriptors` everywhere, because `RuntimeException` isn’t handled in `createSaml`, making `BadRequestException` a controlled exception.

**Review by rmartinc — APPROVED** [review]
Thanks @PavlNekrasov!

**Review by mposolda — APPROVED** [review]
@PavlNekrasov @rmartinc Thanks for the PR and review!
