### PR TITLE
Fix flaky JS test

### LINKED ISSUE #15761: Flaky test: JavascriptAdapterTest.implicitFlowOnTokenExpireTest
### Area

testsuite

### Describe the bug

```
JavascriptAdapterTest.implicitFlowOnTokenExpireTest:399 » Timeout Expected condition failed: waiting for text ('Access token expired') to be present in text ('November 22, 2022 11:56:23 PM GMT Access token expired.
```

### Version

main

### Expected behavior

Test passes always

### Actual behavior

Test fails randomly, with 2 failures in GA last 14 days

### How to Reproduce?

```
============================================================================================================================================
Finding details for JavascriptAdapterTest.implicitFlowOnTokenExpireTest
============================================================================================================================================
https://github.com/keycloak/keycloak/actions/runs/3527776900

Base testsuite (quarkus-map-jpa, group3)	Run base tests	2022-11-23T00:16:28.2720405Z -- [ERROR]   JavascriptAdapterTest.implicitFlowOnTokenExpireTest:399 » Timeout Expected condition failed: waiting for text ('Access token expired') to be present in text ('November 22, 2022 11:56:23 PM GMT Access token expired.
--------------------------------------------------------------------------------------------------------------------------------------------
https://github.com/keycloak/keycloak/actions/runs/3504959452

Base testsuite (quarkus-map-jpa, group3)	Run base tests	2022-11-19T21:15:50.2397645Z -- [ERROR]   JavascriptAdapterTest.implicitFlowOnTokenExpireTest:399 » Timeout Expected condition failed: waiting for text ('Access token expired') to be present in text ('November 19, 2022 8:52:43 PM GMT Access token expired.
--------------------------------------------------------------------------------------------------------------------------------------------
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mhajas**
Closes #15761

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java [hunk 1]
```diff
@@ -386,21 +389,23 @@ public void implicitFlowRefreshTokenTest() {
...
-            testExecutor.logInAndInit(defaultArguments().implicitFlow(), testUser, this::assertInitAuth)
-                  .addTimeSkew(-5); // Move in time instead of wait
-
-            waitUntilElement(eventsArea).text().contains("Access token expired");
-        } finally {
-            // Get to origin state
-            realm.setAccessTokenLifespanForImplicitFlow(storeAccesTokenLifespan);
-            adminClient.realms().realm(REALM_NAME).update(realm);
+        try (RealmAttributeUpdater rau = new RealmAttributeUpdater(adminClient.realms().realm(REALM_NAME))
+                .setAccessTokenLifespanForImplicitFlow(3)
```
Comment (stianst) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java:393]: Should we consider setting that even lower? Since we're only testing expiration in this test, maybe even 1 second?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java [hunk 2]
```diff
@@ -386,21 +389,23 @@ public void implicitFlowRefreshTokenTest() {
...
+        ) {
+                setImplicitFlowForClient();
+                testExecutor.init(defaultArguments().implicitFlow());
+
+                testExecutor.logInAndInit(defaultArguments().implicitFlow(), testUser, this::assertInitAuth);
+                assertThat(driver.getPageSource(), not(containsString("Access token expired")));
+
+                // Here we can't move in time because we are waiting for onTokenExpired execution which is already
+                //   scheduled by setTimeout method, so we can't make it execute sooner
+                pause(1000);
```
Comment (stianst) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java:404]: Rather than a straightforward pause can't we just wait for the "Access token expired" update?

**Review by stianst — APPROVED** [review]
