### PR TITLE
Fix clientRole warning

### LINKED ISSUE #16857: Fix `Overwriting value of clientRole field` log message
This is a followup to fix a warning message that stems from MapRoleEntity implementation of `clientRole` field

### PR DESCRIPTION
**Pull request by hmlnarik**
Fixes: #16857

### CODE REVIEW

File: model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/IckleQueryWhereClauses.java [hunk 1]
```diff
@@ -167,6 +170,30 @@ private static String whereClauseForConsentClientFederationLink(String modelFiel
...
+    private static String whereClauseForClientRole(String modelFieldName, ModelCriteriaBuilder.Operator op, Object[] values, Map<String, Object> parameters) {
+        if (op != ModelCriteriaBuilder.Operator.EQ && op != ModelCriteriaBuilder.Operator.NE) {
+            throw new CriterionNotSupportedException(RoleModel.SearchableFields.IS_CLIENT_ROLE, op);
+        }
+        if (values == null || values.length != 1) {
+            throw new CriterionNotSupportedException(RoleModel.SearchableFields.IS_CLIENT_ROLE, op, "Invalid arguments, expected (boolean), got: " + Arrays.toString(values));
+        }
+
+        Boolean b = (Boolean) values[0];
+        if (op == Operator.EQ) {
```
Comment (mhajas) [inline model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/IckleQueryWhereClauses.java:182]: This can be simplified to something like this:
```java
Boolean b = (Boolean) values[0];
        Operator operatorToUse = (op == Operator.EQ && b == Boolean.TRUE) || (op == Operator.NE && b == Boolean.FALSE) ? Operator.EXISTS : Operator.NOT_EXISTS;
        return IckleQueryWhereClauses.produceWhereClause(RoleModel.SearchableFields.CLIENT_ID, operatorToUse, new Object[] {}, parameters);
```

however, I am not sure about readability. Your version is probably better.

**Review by mhajas — COMMENTED** [review]
If we need a no-downtime upgrade (20-21) we need to create an issue with milestone KC 22 for removing [this](https://github.com/keycloak/keycloak/blob/main/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/role/HotRodRoleEntity.java#L106-L108), otherwise, we can remove it in this PR.

**Comment by hmlnarik** [comment]
> If we need a no-downtime upgrade (20-21) we need to create an issue with milestone KC 22 for removing [this](https://github.com/keycloak/keycloak/blob/main/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/role/HotRodRoleEntity.java#L106-L108), otherwise, we can remove it in this PR.

Created #17086

**Review by vramik — APPROVED** [review]
JPA part lgtm, thank you @hmlnarik

**Review by mhajas — APPROVED** [review]
Thanks @hmlnarik, LGTM
