### PR TITLE
Use browser router for Account Console

### LINKED ISSUE #27442: Use browser router for Account Console
The router for the Account Console uses the [hash based](https://reactrouter.com/en/main/routers/create-hash-router) router, but should be changed to the [browser based](https://reactrouter.com/en/main/routers/create-browser-router) one, which is the recommended router for React Router projects. This will allow the usage of real paths for URLs rather than 'fake' paths that use a hash (`#`).

The main motivation, aside from the React Router recommendation, is that this will allow us to use the same paths for local development, as well as in production. This reduces the surface for bugs, and also makes easier to do end-to-end testing without adding exceptions.

### PR DESCRIPTION
**Pull request by jonkoops**
Changes the router for the Account Console from a [hash based](https://reactrouter.com/en/main/routers/create-hash-router) router to a [browser based](https://reactrouter.com/en/main/routers/create-browser-router) one, which is the recommended router for React Router projects. This will allow the usage of real paths for URLs rather than 'fake' paths that use a hash (`#`).

The main motivation, aside from the React Router recommendation, is that this will allow us to use the same paths for local development, as well as in production. This reduces the surface for bugs, and also makes easier to do end-to-end testing without adding exceptions.

Closes #27442

### CODE REVIEW

**Comment by jonkoops** [comment]
@keycloak/core @keycloak/ui  I am in need of some assistance on the Java side of things here. Is there anyone willing to peer up with me for a couple of hours?

**Comment by jonkoops** [comment]
> Browser routing is not supported on old browsers.

It's been supported since Internet Explorer 10, so I don't think this will be an issue. We're using much more modern JavaScript features that have a lesser support target than this API.

**Comment by ssilvert** [comment]
> > Browser routing is not supported on old browsers.
> 
> It's been supported since Internet Explorer 10, so I don't think this will be an issue. We're using much more modern JavaScript features that have a lesser support target than this API.

Jon and I discussed this off line.  I agree we're good to go for browser routing.

**Review by edewit — DISMISSED** [review]
This is cool

File: services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java [hunk 1]
```diff
@@ -87,71 +87,66 @@ public Response getMainPage() throws IOException, FreeMarkerException {
         URI accountBaseUrl = uriInfo.getBaseUriBuilder().path(RealmsResource.class).path(realm.getName())
                 .path(Constants.ACCOUNT_MANAGEMENT_CLIENT_ID).path("/").build(realm);
 
-        if (!session.getContext().getUri().getRequestUri().getPath().endsWith("/")) {
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java:90]: @pedroigor @ssilvert I've had to revert the work done under #7794 and #7818 for [KEYCLOAK-17174](https://issues.redhat.com/browse/KEYCLOAK-17174), as the browser router does not add a trailing slash, causing redirects back to the base URL if this code remains.

I don't quite understand the original issue, but it looks like this would no longer affect us. Could I ask you to take a look at the changes in this PR and let me know if it all makes sense?

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Comment by jonkoops** [comment]
The routing issue has been fixed, but we still need to figure out if this introduces the aforementioned regression (https://github.com/keycloak/keycloak/pull/22192#discussion_r1283024125).

File: services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java (hunk 1 above)
Comment (ssilvert) [reply services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java:90]: I think the logic to redirect when the path ends with `/` pre-dates that JIRA.

Maybe @pedroigor or @stianst knows why that is done.

If not, I guess we should go ahead as long as the tests are passing.

Comment (jonkoops) [reply services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java:90]: Yeah, looks like you are right. The only thing that I can imagine is that it exists to allow concatenating paths without adding an extra slash (e.g. `accountBaseUrl + "foo/bar"`). But it would be hard to tell where this is being done, or at all.

Comment (pedroigor) [reply services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java:90]: IIRC, the issues you linked are about making sure the URL is built based on the hostname settings. I'll check if we have this covered.

I'm not sure why you had to make all those changes to achieve your goal. Will check it out.

Comment (jonkoops) [reply services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java:90]: I think the white-space formatting is giving the impression that more code has changed. You can change the view of the diff, so that it no longer[ shows these changes](https://github.blog/2018-05-01-ignore-white-space-in-code-review/). The only thing that was removed is the `if` statement and redirect.

**Review by edewit — DISMISSED** [review]
works great I'm :+1: on this, but would it be possible to keep `referrer` and `referrer_uri` query parameters in the url?

**Comment by jonkoops** [comment]
> but would it be possible to keep `referrer` and `referrer_uri` query parameters in the url?

We're not excluding those in this PR right? Under what circumstances are these parameters added?

**Review by pedroigor — DISMISSED** [review]

**Review by ssilvert — DISMISSED** [review]
LGTM

**Review by ssilvert — DISMISSED** [review]

**Review by edewit — DISMISSED** [review]

**Review by agagancarczyk — DISMISSED** [review]

File: js/apps/account-ui/test/applications.spec.ts [hunk 2]
```diff
@@ -62,15 +64,15 @@ test.describe("Applications test", () => {
...
     await page.goto("/");
-    await expect(page).toHaveURL("http://localhost:8080/admin/master/console/");
-    await page.waitForURL("http://localhost:8080/admin/master/console/");
+    await expect(page).toHaveURL(`${getBaseUrl()}/admin/master/console/`);
+    await page.waitForURL(`${getBaseUrl()}/admin/master/console/`);
 
-    await page.goto("/realms/master/account");
-    await page.waitForURL("http://localhost:8080/realms/master/account/");
+    await page.goto(getRootPath());
+    await page.waitForURL(getBaseUrl() + getRootPath());
```
Comment (hmlnarik) [inline js/apps/account-ui/test/applications.spec.ts:75]: Nit: if instead of `getRootPath()` there was a function `getAccountPath()` in `utils.ts`, and there was a similar `getAdminPath()` function, this could be rewritten to:

```suggestion
    await expect(page).toHaveURL(getBaseUrl() + getAdminPath());
    await page.waitForURL(getBaseUrl() + getAdminPath());

    await page.goto(getRootPath());
    await page.waitForURL(getBaseUrl() + getAccountPath());
```

or even simpler with additional functions `getAccountUrl`/`getAdminUrl` which would concatenate base url with the respective path.

```suggestion
    await expect(page).toHaveURL(getAdminUrl());
    await page.waitForURL(getAdminUrl());

    await page.goto(getRootPath());
    await page.waitForURL(getAccountUrl());
```

**Review by hmlnarik — DISMISSED** [review]
LGTM, thanks! One nit left inline.

**Review by pedroigor — DISMISSED** [review]

**Review by pedroigor — DISMISSED** [review]

**Review by agagancarczyk — DISMISSED** [review]
LGTM!

**Review by edewit — DISMISSED** [review]

File: js/apps/account-ui/test/applications.spec.ts (hunk 2 above)
Comment (jonkoops) [reply js/apps/account-ui/test/applications.spec.ts]: Yeah, this could be pulled into the `utils` a little more, I've pushed some changes, let me know what you think.

**Review by hmlnarik — DISMISSED** [review]
Thanks!

**Review by agagancarczyk — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]

**Review by edewit — APPROVED** [review]
