### PR TITLE
fix: detecting when we can set the serviceName

### LINKED ISSUE #40890: Keycloak Operator 26.3.0 fails to update to 26.3.0
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

When upgrading the Keycloak Operator to 26.3.0 on an existing Keycloak instance the Keycloak StatefulSet is not updated to the new version. The operator logs the following error:

```
2025-07-03 11:16:25,467 ERROR [io.jav.ope.pro.eve.EventProcessor] (ReconcilerExecutor-keycloakcontroller-96) Error during event processing ExecutionScope{ resource id: ResourceID{name='keycloak', namespace='keycloak'}, version: 1543606041}: io.javaoperatorsdk.operator.AggregatedOperatorException: Exception(s) during workflow execution. Details:
keycloak-operator-5c854d47ff-xzk42 keycloak-operator  - org.keycloak.operator.controllers.KeycloakDeploymentDependentResource -> io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://.../apis/apps/v1/namespaces/keycloak/statefulsets/keycloak?fieldManager=keycloakcontroller&force=true. Message: StatefulSet.apps "keycloak" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec, message=Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden, reason=FieldValueForbidden, additionalProperties={})], group=apps, kind=StatefulSet, name=keycloak, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=StatefulSet.apps "keycloak" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

### Version

26.3.0

### Regression

- [x] The issue is a regression

### Expected behavior

The StatefulSet is updated to the new image or automatically recreated.

### Actual behavior

The update does not happen.

### How to Reproduce?

Install Keycloak Operator 26.2.5, create Keycloak, update to 26.3.0.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #40890

### CODE REVIEW

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecretDependentResource.java [hunk 1]
```diff
@@ -38,7 +38,7 @@ public KeycloakAdminSecretDependentResource() {
     }
 
     @Override
-    protected Secret desired(Keycloak primary, Context<Keycloak> context) {
+    public Secret desired(Keycloak primary, Context<Keycloak> context) {
```
Comment (vmuzikar) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecretDependentResource.java]: Can you elaborate what is the purpose of this change? Alignment with the other dependent resources?

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java [hunk 2]
```diff
@@ -213,6 +212,7 @@ public void testConfigInCRTakesPrecedence() {
     @Test
     public void testDeploymentDurability() {
         var kc = getTestKeycloakDeployment(true);
+        KeycloakDeploymentTest.initCustomBootstrapAdminUser(kc);
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java:215]: Do we need it for this test?

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java [hunk 3]
```diff
@@ -229,4 +235,30 @@ public void testPodTemplateIncorrectImagePullSecretsConfig() {
                 });
     }
 
+    @Test
+    public void testDeploymentUpgrade() {
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java:239]: This will work for now. But still, I'm wondering if we shouldn't have a fully fledged upgrade test, ideally using OLM to see if it complains about some breaking changes in the CRDs.

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thanks for the quick fix!

**Review by vmuzikar — DISMISSED** [review]
Over all, LGTM. The comments around tests are not blocking.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java (hunk 2 above)
Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java:215]: Yes, otherwise it's a timing issue whether the operator sdk will delete the existing statefulset.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecretDependentResource.java (hunk 1 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecretDependentResource.java]: It's no longer needed once I switch to initCustomBootstrapAdminUser, I'll remove it.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java (hunk 3 above)
Comment (shawkins) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java:239]: There's an existing issue on the olm upgrades.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java:239]: Right, just for reference: https://github.com/keycloak/keycloak/issues/25431

**Review by vmuzikar — DISMISSED** [review]
LGTM, thanks.

**Comment by shawkins** [comment]
Had to update the timeout - the test is run both as local_apiserver, and remote, so the remote test needs more time.

**Review by vmuzikar — APPROVED** [review]

**Comment by vmuzikar** [comment]
@shawkins Can you please create the backport?

**Comment by shawkins** [comment]
> @shawkins Can you please create the backport?

https://github.com/keycloak/keycloak/pull/40943
