### PR TITLE
NoSuchFileException with ${kc.home.dir} on Windows

### LINKED ISSUE #23217: NoSuchFileException with ${kc.home.dir} on Windows
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

Under Windows, I use `keycloak.config` with 

```
https-certificate-file=${kc.home.dir}/../../cert/cert.pem
```

This works in v21 but no longer in v22.
When with `kc.bat --verbose start` I get sth like

```
java.nio.file.NoSuchFileException: D:Dir1Dir2Dir3keyCloakbin..\..\..\cert\cert.pem
```

When I replace the config path with an absolute path containing only / then it works.
E.g. `D:/Dir1/Dir2/Dir3/cert/cert.pem`.

### Version

22.0.3

### Expected behavior

The old configuration should work as it did till v21.

### Actual behavior

I get a _NoSuchFileException_ instead. Except when I use the workaround: absolute paths with \ replaced by /.

I think, `${kc.home.dir}` may return `\` separators and this doesn't seem to work with the file load logic.
Either that logic has changed or the `${kc.home.dir}` did use `/` in the past instead of `\`.

### How to Reproduce?

Use Windows and try a https-certificate-file configuration similar to mine, containing `${kc.home.dir}`.

### Anything else?

It may be similar like #17413.

### PR DESCRIPTION
**Pull request by Pepo48**
* added a path validation for https cert and key files in HttpPropertyMappers

Closes #23217

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java [hunk 1]
```diff
@@ -105,6 +109,20 @@ public static PropertyMapper[] getHttpPropertyMappers() {
         };
     }
 
+    private static Optional<String> validatePath(Optional<String> value, ConfigSourceInterceptorContext context) {
```
Comment (shawkins) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:112]: Just a minor though, it might be more direct to express this as:

```
    private static BiFunction<Optional<String>, ConfigSourceInterceptorContext, Optional<String>> validatePath(String key) {
        return (value, context) -> value.filter(v -> v.equals(context.proceed(key).getValue())).map(p -> p.replace("\\", "/"));
    }
```

**Review by vmuzikar — COMMENTED** [review]
@Pepo48 Thanks for the PR. +1 to @shawkins comment, otherwise LGTM.

I just wonder, isn't this rather a bug on Quarkus side then? I'd like to avoid introducing more workarounds for Quarkus bugs on our end.

**Comment by Pepo48** [comment]
> @Pepo48 Thanks for the PR. +1 to @shawkins comment, otherwise LGTM.
> 
> I just wonder, isn't this rather a bug on Quarkus side then? I'd like to avoid introducing more workarounds for Quarkus bugs on our end.

@vmuzikar as I already mentioned [here](https://github.com/keycloak/keycloak/issues/23217#issuecomment-1768223569), I also believe that this is rather a bug on Quarkus/SmallRye side. Therefore, I tried to initiate a discussion first (as you may see at the end of my comment). This PR was prepared rather proactively, in order to not to waste more time if we decide to workaround it on our end.

**Comment by vmuzikar** [comment]
@Pepo48 Can you please open a GH Issue on the Quarkus side? We might even consider contributing a fix if it's simple enough. :)

**Comment by Pepo48** [comment]
> @Pepo48 Can you please open a GH Issue on the Quarkus side? We might even consider contributing a fix if it's simple enough. :)

Just for the record, here's the summary of my further investigation of Quarkus and SmallRye-config later on:
https://github.com/smallrye/smallrye-config/issues/1033

**Comment by Pepo48** [comment]
@vmuzikar the last advice was to use a [custom converter](https://smallrye.io/smallrye-config/Main/converters/custom/), which is, afaict, a similar approach to what I we already have in this PR. One way or another, It definitely requires an implementation on our end. 

From what I understood for them this is an edge case they are willing to fix once they find some time. But at this moment it has no visible priority.

**Comment by vmuzikar** [comment]
@Pepo48 Ok, let's go with the workaround then. Can you please rebase?

**Comment by Pepo48** [comment]
@vmuzikar I rebased it, made some cosmetic changes and tested it again - everything seems to work as expected:
image

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java (hunk 1 above)
Comment (Pepo48) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java]: @shawkins addressed, thanks!

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@Pepo48 Thanks. Only thing that's missing from my perspective is a test.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java [hunk 2]
```diff
@@ -109,6 +114,10 @@ public static PropertyMapper[] getHttpPropertyMappers() {
         };
     }
 
+    private static BiFunction<Optional<String>, ConfigSourceInterceptorContext, Optional<String>> validatePath(String key) {
+        return (value, context) -> value.filter(v -> v.equals(context.proceed(key).getValue())).map(p -> p.replace("\\", "/"));
```
Comment (shawkins) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java:118]: It's valid, but unlikely, for unix files and directories to contain the \ character.  This probably needs to be done only for windows.  Or generally require uses to be consistent - and error out with mixed file separators.

Comment (Pepo48) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java]: I can think of one edge case on Unix platform and that's when a space in a directory/file name is escaped.

So I proceeded with the backslash replacement just for the windows platform and with no transformation for Unix. I also added a separate test case for each platform.

Comment (Pepo48) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java]: I also retested it on Windows, just to be on a safe side.

**Review by shawkins — DISMISSED** [review]
LGTM, thanks @Pepo48

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java [hunk 3]
```diff
@@ -153,14 +155,38 @@ void testInvalidSmallRyeKeyStorePathProperty(LaunchResult result) {
...
+    @Order(12)
     void testSmallRyeKeyStoreConfigSource(LaunchResult result) {
         // keytool -importpass -alias kc.log-level -keystore keystore -storepass secret -storetype PKCS12 -v (with "debug" as the stored password)
         CLIResult cliResult = (CLIResult) result;
         assertTrue(cliResult.getOutput().contains("DEBUG"));
         cliResult.assertBuild();
     }
 
+    @Test
+    @BeforeStartDistribution(ForceRebuild.class)
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java:167]: @Pepo48 does this mean that a build from one test is capturing a non-build time property, which then gets used by default in another test if that property isn't set explicitly?

cc @pedroigor

[the remark this answers is not in the document]
Comment (Pepo48) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java:167]: @shawkins correct. I also remember that you a week or two ago mentioned that running multiple tests at once caused an issue while separately they passed. The same thing happened to here and it can be easily reproduced if you remove the @BeforeStartDistribution annotation.

I assume that this happens because of how the server configuration is currently persisted among individual test executions (afaict, there is no manual rebuild nor a properties cleanup in this specific case).

[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java:167]: @Pepo48 yes, I had attributed that to some error with config change I was trying to make.  

Just to make sure, let's use config-keystore, a runtime option, as an example for this behavior.  If it's set as an env variable, I do see that it is incidentially validated if you run kc.sh build - because Picocli.hasConfigChanges triggers the resolution of all properties.  That seems like a bug.  

If the build is successful, then I unset KC_CONFIG_KEYSTORE, it looks like both start and start --optimized will fail - hopefully this should mean we aren't leaking over the previous setting as a default.

**Review by shawkins — APPROVED** [review]
LGTM, captured #25166 as the first follow-up.  Will try to see if there is another lurking issue about missing an auto-build.

**Comment by shawkins** [comment]
@vmuzikar can you approve this?

**Review by vmuzikar — APPROVED** [review]
Approving based on @shawkins review.
