### PR TITLE
Registration with email verification - corner case scenario for pre-a…

### LINKED ISSUE #48206: Registration with email verification - corner case scenario for pre-account takeover
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

This issue is a follow-up after #45568 . That issue is partially fixed, but still there can be a corner case allowing pre-account take-over as a variant of what is described in #45568 :

1. an attacker creates an account using someone else's email address (classic pre-account takeover attack)
2. an email verification message is sent to the victim
3. the attacker waits at the screen which tells that a confirmation email was sent - if this authentication session expire, attack is not possible. But assume that attacker is refreshing the screen periodically for a long time until victim came to her browser (and continue with step 4 and further below)
4. the victim gets the emails
5. the victim doesn't confirm the email, but goes directly to the application
6. tries to log in, but can't and also can't register (as account already registered)
7. the victim clicks forgot password
8. password reset email is sent and the victim completes the action
9. victim sees the email verification and gets another confirmation mail
10. the victim now verifies the email and sets the password
11. victim logs in
12. attacker (who is waiting all this time) refreshes the login page and gets logged in too

### Version

main (after PR for 45568 merged)

### Regression

- [ ] The issue is a regression

### Expected behavior

When email is verified after user's registration, but email verification happened in a different browser, the original browser (where user registration was triggered) should not continue with other actions. Authentication session should be either expired or should not be able to continue with next steps after "Verify email" .

### Actual behavior

See description

### How to Reproduce?

See description

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
…ccount takeover

closes #48206

PR adds new authentication session note `NEW_USER_REGISTERED` in case that user self-registration happens in this authentication session (EG. `authSession1`) . When verify-email is done in the meantime for the user in different browser (by some different authentication session like `authSession2` ), then `authSession1` is not able to continue after verify-email.

### CODE REVIEW

File: services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java [hunk 1]
```diff
@@ -92,10 +97,15 @@ public void requiredActionChallenge(RequiredActionContext context) {
     private void process(RequiredActionContext context, boolean isChallenge) {
         AuthenticationSessionModel authSession = context.getAuthenticationSession();
 
-        if (context.getUser().isEmailVerified()) {
-            context.success();
-            authSession.removeAuthNote(Constants.VERIFY_EMAIL_KEY);
-            return;
+        // When triggered during registration, make sure to add requiredAction also to the authSession. If email is later verified in different authSession, this authSession should not continue
+        if ("true".equals(context.getAuthenticationSession().getAuthNote(NEW_USER_REGISTERED))) {
+            context.getAuthenticationSession().addRequiredAction(UserModel.RequiredAction.VERIFY_EMAIL);
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java]: Nitpick. Maybe just deleting auth session and force to restart the login was better. But this is enough to fix the issue.

**Review by rmartinc — APPROVED** [review]
Thanks a lot @mposolda!

Approved, maybe deleting the auth session was better. Asking to verify again is a bit weird. But, as it's a corner case, it's OK to me.

File: services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java (hunk 1 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java]: Yes, that is another variant I've considered and agree that it is likely better. I've updated PR for restart current authentication session in case that email was verified in other authSession in the meantime. Used separate commit, so it is possible to easily see the changes. Could you re-review?

**Review by rmartinc — APPROVED** [review]
Thanks @mposolda! LGTM!

**Comment by mposolda** [comment]
@rmartinc Thanks!
