### PR TITLE
Use RESOURCE_LOCAL transactions for JPA map storage

### LINKED ISSUE #15248: JPA Map store JDBC transactions not rolled back on Hibernate transaction rollback when running in Quarkus
### Area

storage

### Describe the bug

Given a setup with Quarkus and JPA map storage, a transaction is not rolled back. Instead, the changes are written to the database.

### Version

19.0.2

### Expected behavior

When a transaction is marked for rollback, it should be rolled back.

### Actual behavior

When the rollback is triggered to the Hibernate transaction, that is not propagated to the underlying PostgreSQL DB connection. 
Instead, when the DB connection is returned, it is being committed.

### How to Reproduce?

* Start Quarkus as described in discussion #9596 with JPA map storage
* Login and select a client
* Change the “Valid redirect URIs” to contain a “#text” (an anchor) at the end
* Press “Save” -> an error message appears
* Press reload in the browser to load the changes from the database -> the changes have been persisted to the database

### Anything else?

Part of the cause might be that Hibernate is still using JTA for transactions, but the JDBC connection is not bound to the JTA transaction; instead it needs to be handled manually.

Possible remedies: 
* Manually commit/rollback the JDBC transaction in JpaTransactionWrapper with something like: 
em.unwrap(SessionImpl.class).doWork(Connection::rollback);
* Use JTA all the way for JPA Map storage in Quarkus 
* Use RESOURCE_LOCAL transaction type

### PR DESCRIPTION
**Pull request by ahus1**
Closes #15248

### CODE REVIEW

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 1]
```diff
@@ -272,7 +273,18 @@ private void configureDefaultPersistenceUnitProperties(ParsedPersistenceXmlDescr
         Properties unitProperties = descriptor.getProperties();
 
         unitProperties.setProperty(AvailableSettings.DIALECT, config.defaultPersistenceUnit.dialect.dialect.orElse(null));
-        unitProperties.setProperty(AvailableSettings.JPA_TRANSACTION_TYPE, PersistenceUnitTransactionType.JTA.name());
+        String storage = Configuration.getRawValue(
```
Comment (pedroigor) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:276]: We can use this option to choose between `JTA` and `RESOURCE_LOCAL`. See https://github.com/keycloak/keycloak/blob/a76b597b35a4d9ce9015016db6f02793e4d03ea5/quarkus/config-api/src/main/java/org/keycloak/config/TransactionOptions.java#L12.

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 2]
```diff
@@ -272,7 +273,18 @@ private void configureDefaultPersistenceUnitProperties(ParsedPersistenceXmlDescr
...
+                MicroProfileConfigProvider.NS_KEYCLOAK_PREFIX.concat(StorageOptions.STORAGE.getKey()));
+        if (storage == null) {
+            // legacy store
+            unitProperties.setProperty(AvailableSettings.JPA_TRANSACTION_TYPE, PersistenceUnitTransactionType.JTA.name());
+        } else {
+            // JPA map store; avoid JTA and use a direct (resource local) approach
+            unitProperties.setProperty(AvailableSettings.JPA_TRANSACTION_TYPE, PersistenceUnitTransactionType.RESOURCE_LOCAL.name());
+            // needed to change the connection handling to avoid Hibernate returning the connection too early,
+            // which then interfered with the auto-commit reset that's done at the end of the transaction and PgConnection throwing a "Cannot commit when autoCommit is enabled."
+            unitProperties.setProperty(AvailableSettings.CONNECTION_HANDLING, PhysicalConnectionHandlingMode.DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION.name());
```
Comment (pedroigor) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:286]: See https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/FastBootMetadataBuilder.java#L287.

In the past, we had some discussions with Quarkus team about it. We can involve them again to see the implications of doing this. At that time, the discussions were around JTA, perhaps using resource local it can work well.

Comment (ahus1) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java]: As agreed in today's call, I'll reach out to experts in Quarkus/Hibernate/Agroal to discuss this. Still, this PR will be merged to fix the problems we currently experience.

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java (hunk 1 above)
Comment (ahus1) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java]: Included in the latest commit

**Comment by ahus1** [comment]
@vramik - after the builds are finally green this is now ready for review.

**Review by pedroigor — APPROVED** [review]
