### PR TITLE
fix: allows for schedulings to be defined for operator jobs

### LINKED ISSUE #42057: [Operator] Update job incorrectly inherits podTemplate configuration from unsupported.podTemplate
## Issue Summary

When using the `unsupported.podTemplate` configuration for the main Keycloak pods, the update job incorrectly inherits the same `nodeSelector` and `tolerations` configuration, preventing separate control over update job scheduling.

## Current Behavior
1. Main Keycloak pods use `unsupported.podTemplate` configuration ✅
2. Update job automatically inherits the same `nodeSelector` and `tolerations` ❌
3. No way to configure update job scheduling separately ❌

## Expected Behavior
The Keycloak operator appears to be applying the `unsupported.podTemplate` configuration to both the main StatefulSet and the update job, instead of allowing separate configuration for each.

## Impact
- Update jobs cannot be scheduled on **different nodes** than the main Keycloak pods
- Cannot use different tolerations for update jobs vs. main pods
- Limits flexibility in cluster resource management
- May cause update job failures if the inherited configuration is inappropriate

## Environment
- Keycloak Operator Version: 26.3.3
- Kubernetes Version: 1.33.0
- Use Case: Multi-node cluster with dedicated nodes for different workloads

## Steps to Reproduce
1. Deploy Keycloak with unsupported.podTemplate configuration:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  # ... other configuration ...
  unsupported:
    podTemplate:
      spec:
        nodeSelector:
          node-role: "keycloak-dedicated"
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "keycloak"
            effect: "NoSchedule"
```
2. Trigger an update (e.g., change image tag, configuration)
3. Observe that the update job uses the same nodeSelector and tolerations
4. The update job cannot be scheduled because this node group have more than 3 nodes (keycloak used 3 nodes)

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #42057

It's probably worth discussing, but we actually have several options here:

- this pr - keep the current behavior that defaults the job scheduling to that of the server, and allow that to be overriden by specific scheduling fields. 

- An alternative to putting the import scheduling on the import cr is to instead put that on the keycloak cr - it's highly likely that users would want the same scheduling for all imports.

- Add a declarative field on or beside the scheduling spec to state whether the scheduling should be inherited - it would default to true as to not be a breaking change, but we could later default it false.

### CODE REVIEW

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java [hunk 1]
```diff
@@ -162,4 +166,13 @@ private void buildKeycloakJobContainer(Container keycloakContainer, KeycloakReal
 
         addResources(keycloakRealmImport.getSpec().getResourceRequirements(), config, keycloakContainer);
     }
+
+    static void handleJobScheduling(SchedulingSpec schedulingSpec, PodSpec spec) {
```
Comment (pruivo) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java]: nitpicking; wouldn't make more sense for this method to be in `CRDUtils`?

**Comment by pruivo** [comment]
> It's probably worth discussing, but we actually have several options here:
> 
> * this pr - keep the current behavior that defaults the job scheduling to that of the server, and allow that to be overriden by specific scheduling fields.
> * An alternative to putting the import scheduling on the import cr is to instead put that on the keycloak cr - it's highly likely that users would want the same scheduling for all imports.
> * Add a declarative field on or beside the scheduling spec to state whether the scheduling should be inherited - it would default to true as to not be a breaking change, but we could later default it false.

I don't have a strong preference, but this pr/first option seems to be the simplest of all.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java (hunk 1 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java]: Those utility methods seem to be more about finding things on a cr, not applying changes to kubernetes objects.

**Comment by ryanemerson** [comment]
I like the separation of scheduling definitions on the two CRs, I think it is the most flexible solution, so +1 to the current approach to the specs.

I am not convinced it makes sense for the import and upgrade jobs to default to the Keycloak scheduling rules though.

Currently the default `TopologySpreadConstraints` prefer that pods are scheduled on distinct zones and nodes. Imagine a K8s cluster with multiple zones, but a single Keycloak instance. I don't think it makes sense that the upgrade/import jobs be provisioned in a separate zone as this will cause additional latency and cost.

I can think of two solutions to prevent ^:

1. Don't define scheduling defaults for these jobs. Simple, but jobs may still be scheduled across zones.

2. Define default scheduling for import and upgrade jobs that prefers co-location via an affinity rule.

I think 2. is the more robust solution. 

Is there any scenario where wouldn't prefer the jobs to be co-located?

**Comment by shawkins** [comment]
> Is there any scenario where wouldn't prefer the jobs to be co-located?

I don't think so. At least in terms of zones that was effectively the old default behavior - which means we can go back to that without any concerns about breaking.

> I think 2. is the more robust solution.

What about when the user has put explicit scheduling on the Keycloak CR - do we just break the old behavior of inheriting, or add another flag to control that?

**Comment by ryanemerson** [comment]
> What about when the user has put explicit scheduling on the Keycloak CR - do we just break the old behavior of inheriting, or add another flag to control that?

Personally I don't like adding additional flags unless absolutely necessary, as it's one more thing for the user to consider.

Can we add this to notable changes and document that by default import/upgrade jobs will be co-located unless explicitly configured otherwise?

**Comment by shawkins** [comment]
> Can we add this to notable changes and document that by default import/upgrade jobs will be co-located unless explicitly configured otherwise?

@vmuzikar we didn't explicitly document the that Jobs inherit scheduling from the Keycloak CR, so do you see this as a notable change - or a breaking change that would necessitate a flag in a minor release?

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java (hunk 1 above)
Comment (vmuzikar) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java]: @pruivo +1
Was about to write the same comment. :)

> Those utility methods seem to be more about finding things on a cr, not applying changes to kubernetes objects.

It's utils, I don't see a reason why it shouldn't modify stuff. Though it's not blocking.

**Review by vmuzikar — DISMISSED** [review]
@shawkins Thanks, LGTM.

**Comment by vmuzikar** [comment]
> @vmuzikar we didn't explicitly document the that Jobs inherit scheduling from the Keycloak CR, so do you see this as a notable change - or a breaking change that would necessitate a flag in a minor release?

We're not changing existing behaviour, just adding new fields to override it, no? If anything, it should be included in the Release Notes.

I'd keep the current behaviour as the default (that it inherits scheduling from main deployment).

**Comment by vmuzikar** [comment]
> but a single Keycloak instance

This would not seem production ready – a single KC pod. :) I doubt that would be too common.

**Comment by shawkins** [comment]
> We're not changing existing behaviour, just adding new fields to override it, no? 

What @ryanemerson is proposing not in this pr and would change existing behavior - but it is not explicitly documented.

> I'd keep the current behaviour as the default (that it inherits scheduling from main deployment).

That is the current state of the pr. However with the recent changes to the main default scheduling it is not likely the behavior users want by default for the jobs.

**Comment by vmuzikar** [comment]
> However with the recent changes to the main default scheduling it is not likely the behavior users want by default for the jobs.

That's what I'm not entirely sure about. If the user expects some scheduling policy, it might be counter intuitive if it's not reflected by all KC pods (for the user, it might be low level tech details if it's a Job or main KC deployment). Even worse if the user explicitly set the scheduling spec for the main deployment.

**Comment by vmuzikar** [comment]
> Is there any scenario where wouldn't prefer the jobs to be co-located?

In strictly resourced envs where the user doesn't expect more than 1 KC pod on a node.

**Comment by ryanemerson** [comment]
> This would not seem production ready – a single KC pod. :) I doubt that would be too common.

True! I said a single pod for simplicity, but the scenario I describe is also applicable if a Kubernetes cluster is deployed across 3 availability-zones and the user provisions Keycloak with `spec.instances: 2`. If we inherit the default topologyPodConstraints in the jobs, this will result in the following distribution:

- `keycloak-0`: AZ1
- `keycloak-1`: AZ2
- job: AZ3

**Comment by vmuzikar** [comment]
@ryanemerson Right. So the user is expecting to have a single KC pod per zone (for whatever reasons) which can be either default or explicitly set behaviour. Now, won't it be confusing to the user that suddenly a new "KC pod" appeared in the same AZ when some other AZ has 0 pods? Additionally, what would be the disadvantage of scheduling the Jobs in a different AZ? Neither the Import Job, nor the Update Job need to communicate with the other KC Pods, no? One reason might be the DB latency but that shouldn't be an issue if the scheduling actually allows the KC Pods to be scheduled in various AZs.

**Comment by ryanemerson** [comment]
> Now, won't it be confusing to the user that suddenly a new "KC pod" appeared in the same AZ when some other AZ has 0 pods?

Presumably the pods have a different naming convention as they're not part of the StatefulSet, so I think that would make the difference clear.

> Additionally, what would be the disadvantage of scheduling the Jobs in a different AZ? Neither the Import Job, nor the Update Job need to communicate with the other KC Pods, no?

That's a good point about the pod communication. When I wrote https://github.com/keycloak/keycloak/pull/42310#issuecomment-3252831668, I had made some incorrect assumptions about how the import job worked. So you're right, network cost for cross-zone traffic is not a concern here.

It's minor, but one disadvantage I can think of is resource allocation. Inheriting the default policies means that more weight will be attached to scheduling the job pod to a distinct AZ/node then a node that has more available resources.

Very much an edge-case, but job execution and simultaneous scaling of Keycloak `spec.instances` could also lead to a scenario where a keycloak server pod is not provisioned on a distinct az. Consider the scenario described in https://github.com/keycloak/keycloak/pull/42310#issuecomment-3265148434 again, if the job is on AZ3, it could be that `keycloak-2` then gets provisioned on AZ1 or AZ2.

> One reason might be the DB latency but that shouldn't be an issue if the scheduling actually allows the KC Pods to be scheduled in various AZs.

+1. If the user wants to co-locate an import job with the DB writer instance, they will now have the flexibility in `keycloakrealmimports` to do that. That will be deployment dependent though, so I don't think we can further improve this in a generic way.

**Comment by vmuzikar** [comment]
@ryanemerson Considering the past few points in the discussion, do you still see the co-location as the preferred/correct scheduling strategy for the Jobs?

I'd still see it as a bit counter intuitive, especially in case the user explicitly specifies the scheduling for the main deployment in the CR – as a user, I'd probably expect it to be reflected by the Jobs too, and took the Job specific scheduling as an override for the main one. I guess I'm more taking it from the UX perspective rather than the nuanced performance one.

**Comment by ryanemerson** [comment]
> Considering the past few points in the discussion, do you still see the co-location as the preferred/correct scheduling strategy for the Jobs?

No, I don't think explicit co-location brings any real benefit.

Given the edge-case that I described above regarding scheduling and our default topologyPodConstraints policy, I'm still not convinced that it makes sense for jobs to inherit the Keycloak CR scheduling configuration.

That being said, as users can now override the configuration, I don't have strong views on this and I'm happy to go with cloud-native team's preference.

**Comment by vmuzikar** [comment]
> I'm happy to go with cloud-native team's preference.

@shawkins Are you ok with this as is, too?

**Comment by shawkins** [comment]
Talked about this in our meeting. It seems like the most straight-forward UX is to make our best effort to make things work as much as expected by default and be done in only a single place, so we should not inherit the default scheduling and we'll move the scheduling of import jobs to the keycloak cr.

@vmuzikar @ryanemerson @pruivo we also wanted to confirm there's no chance the switch from non-stretch to stretch clusters could be a breaking change for any existing users?

**Comment by ryanemerson** [comment]
> @vmuzikar @ryanemerson @pruivo we also wanted to confirm there's no chance the switch from non-stretch to stretch clusters could be a breaking change for any existing users?

You mean the new default `podTopologySpreadConstraints` vs the old anti-affinity rules? It shouldn't impact functionality in the sense that everything will work as before, but if the user is running a multi-az k8s cluster then pods will now be scheduled on distinct zones opposed to being co-located within the same az.

The changes doc is outdated, as it still talks about anti-affinity rules. If you're happy with above change in behaviour, then I will create a PR to fix it.

**Comment by shawkins** [comment]
Updated the pr based upon my last comment.

> You mean the new default podTopologySpreadConstraints vs the old anti-affinity rules? It shouldn't impact functionality in the sense that everything will work as before, but if the user is running a multi-az k8s cluster then pods will now be scheduled on distinct zones opposed to being co-located within the same az.

Just wanted to make sure there wasn't a case to be made for this being a breaking change - this could even be if someone experiences unexpected cross-az data shipment charges that weren't happening before.

> The changes doc is outdated, as it still talks about anti-affinity rules. If you're happy with above change in behaviour, then I will create a PR to fix it.

I had fixed one occurrance of that in this pr, went ahead and addressed the other as well. If need be it can be separated to a different issue / pr.

File: docs/guides/operator/advanced-configuration.adoc [hunk 2]
```diff
@@ -294,8 +294,8 @@ If you do not specify a custom topology spread constraint, your Pods will have a
 
 ==== Job Scheduling
 
-Realm import and update Jobs inherit the scheduling of the server Pods. If your server Pod scheduling is highly restrictive this may result in the 
-Job Pods being unschedulable. In this situation you may override the Job scheduling using the KeycloakRealmImport CR `spec.scheduling` and Keycloak CR `spec.update.scheduling` fields.
+Realm import and update Jobs inherit the scheduling of the server Pods if it is specified the Keycloak CR `spec.shceduling` field. If your server Pod scheduling is highly restrictive this may result in the
```
Comment (ryanemerson) [inline docs/guides/operator/advanced-configuration.adoc]: `s/shceduling/scheduling`

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java [hunk 3]
```diff
@@ -360,4 +365,12 @@ public void setReadinessProbeSpec(ProbeSpec readinessProbeSpec) {
     public void setStartupProbeSpec(ProbeSpec startupProbeSpec) {
         this.startupProbeSpec = startupProbeSpec;
     }
+
+    public SchedulingSpec getImportSchedulingSpec() {
```
Comment (ryanemerson) [inline operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java]: Does it make sense for us to take this opportunity to nest the import scheduling so we have `spec.import.scheduling`?

The benefits would be:

1. Consistent with `spec.update.scheduling`
2. Allows for future global import configuration that maybe required e.g. `spec.update.<tbdElement>`. I don't have a concrete example, but you never know what the future might bring.

**Review by ryanemerson — COMMENTED** [review]
> I had fixed one occurrance of that in this pr, went ahead and addressed the other as well. If need be it can be separated to a different issue / pr.

Thanks! It makes sense for it to be addressed here :+1:

File: operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java (hunk 3 above)
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java]: > Does it make sense for us to take this opportunity to nest the import scheduling so we have spec.import.scheduling?

It does, we talked about this a little in our team meeting, but I didn't reflect it in this pr. It's possible that users will eventually want to tweak the resource allocation for the update and import jobs as well, so having a separate stanza is good.

**Comment by shawkins** [comment]
@ryanemerson should be good now.

File: docs/guides/operator/advanced-configuration.adoc [hunk 4]
```diff
@@ -290,7 +290,26 @@ spec:
 
 Please see https://kubernetes.io/docs/concepts/scheduling-eviction[the kubernetes docs] for more on scheduling concepts.
 
-If you do not specify a custom affinity, your Pods will have an anti-affinity for the same zone and node to improve availability.
+If you do not specify a custom topology spread constraint, your Pods will have a spread constraint across zones and nodes to improve availability.
+
+==== Job Scheduling
+
+Realm import and update Jobs inherit the scheduling of the server Pods if it is specified the Keycloak CR `spec.scheduling` field. If your server Pod scheduling is highly restrictive this may result in the
```
Comment (ryanemerson) [inline docs/guides/operator/advanced-configuration.adoc]: "...specified in the Keycloak..."

**Review by ryanemerson — COMMENTED** [review]
Thanks @shawkins, other than a minor docs fix LGTM assuming CI is :green_circle:

File: docs/guides/operator/advanced-configuration.adoc [hunk 5]
```diff
@@ -290,7 +290,26 @@ spec:
 
 Please see https://kubernetes.io/docs/concepts/scheduling-eviction[the kubernetes docs] for more on scheduling concepts.
 
-If you do not specify a custom affinity, your Pods will have an anti-affinity for the same zone and node to improve availability.
+If you do not specify a custom topology spread constraint, your Pods will have a spread constraint across zones and nodes to improve availability.
```
Comment (vmuzikar) [inline docs/guides/operator/advanced-configuration.adoc]:
```suggestion
If you do not specify a custom topology spread constraint, your Pods will have a spread constraint across zones and nodes to improve availability. These defaults do not affect import and update Jobs, only server Pods.
```

File: docs/guides/operator/advanced-configuration.adoc (hunk 4 above)
Comment (shawkins) [reply docs/guides/operator/advanced-configuration.adoc]: Corrected, thanks @ryanemerson

**Review by vmuzikar — APPROVED** [review]
LGTM, thank you @shawkins!

**Review by ryanemerson — APPROVED** [review]
