### PR TITLE
OTEL: Fix #podNamePropagation test for Operator

### LINKED ISSUE #32490: Failing operator test - KeycloakDeploymentTest.testPodNamePropagation
### Description

In several job runs, inluding https://github.com/keycloak/keycloak/actions/runs/10594540860/job/29358667097, KeycloakDeploymentTest.testPodNamePropagation is failing due to an underlying exception of

Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class io.quarkus.opentelemetry.runtime.tracing.DelayedAttributes] and qualifiers [[@jakarta.enterprise.inject.Any()]]

This is not consistently occurring nor has it been reproducable locally. Locally I consistenly observe TracerProducer providing the DelayedAttributes regardless of where other breakpoints are set in attempts to alter the startup.

cc @geoand @mabartos

### PR DESCRIPTION
**Pull request by mabartos**
- Fixes #32490

As the custom Keycloak image is used when testing the Operator, it should be unmarked as optimized to be properly set up.

Draft PR for now as some tweaks to the main will be added. This should be ready for backport.

### CODE REVIEW

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import static org.keycloak.operator.controllers.KeycloakDeploymentDependentResource.KC_TRACING_RESOURCE_ATTRIBUTES;
+import static org.keycloak.operator.controllers.KeycloakDeploymentDependentResource.KC_TRACING_SERVICE_NAME;
+import static org.keycloak.operator.testsuite.utils.K8sUtils.deployKeycloak;
+
+@QuarkusTest
+public class TracingDeploymentTest extends BaseOperatorTest {
+
+    public static Keycloak getTestKeycloakDeployment(boolean disableProbes) {
+        var kc = BaseOperatorTest.getTestKeycloakDeployment(disableProbes);
+        kc.getSpec().setStartOptimized(false);
```
Comment (shawkins) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:41]: Looks good. This may have gotten disabled prior to recent change to make it a hard error to start optimized with a changed build time option - that would have made it in the pod log what was happening.

However I'm wondering why it ever worked. There should have been a warning that tracing-enabled was ignored.

Comment (mabartos) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:41]: I think we should handle pod logs better if some issue occurs - still space for improvements. As sometimes it's really hard to understand what exactly happened and why the test failed. 

> However I'm wondering why it ever worked.

The thing is in the test case, we're just checking the env vars propagated to the pod. And when we have disabled probes for the test deployment, the test does not even wait to properly start the server up. 

I'll enable these probes to verify the pod started correctly.

**Comment by mabartos** [comment]
## Problem Summary

As we use optimized custom Keycloak image when testing Operator, some problems occurred due to the build time options manner. In order to properly start distribution with Tracing enabled, we need to have enabled `opentelemetry` feature, and set `tracing-enabled=true`. Associated Keycloak options `features-enabled`, and `tracing-enabled` are build time, so they need reaugmentation to be properly propagated.

However, as the Operator uses an optimized image, no augmentation was done and we faced quite weird behavior due to it. It was a series of unhappy coincidences:

1.  The focus of the test case was propagating proper env vars to the pod and nothing more. We did not even wait for the proper server startup - we disabled probes for the test case.
2. The DelayedAttributes handling on the Quarkus side
3. Not sure how good was our mechanism for property propagation to Quarkus that time (maybe the `quarkus.otel.traces.enabled`, or `quarkus.otel.enabled` was propagated to Quarkus without running augmentation and that might have caused some issues)

In this PR, probes are enabled and we will wait for the proper server startup with the tracing capabilities to verify everything works as expected. We unmarked the image as optimized, so the reaugmentation is happening. It should solve the problem and the issue should not occur again. We can keep an eye on it for some time, but I believe it's gonna be ok.

@shawkins @vmuzikar Are you ok with these changes?

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+        kc.getSpec().getAdditionalOptions().add(new ValueOrSecret("tracing-enabled", "true"));
+
+        var featureSpec = new FeatureSpec();
+        featureSpec.setEnabledFeatures(List.of("opentelemetry"));
+        kc.getSpec().setFeatureSpec(featureSpec);
+        return kc;
+    }
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:48]: Just a nitpick. I think we don't need this extra method.

We don't need to enable the feature any more, it effectively just sets `tracing-enabled` and it's called only one.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+
+    @Test
+    public void podNamePropagation() {
```
Comment (vmuzikar) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:51]: Possibly we don't even need to move it to a separate test class, WDYT?

Comment (mabartos) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:51]: I'd like to move here also the test case for Keycloak Tracing CR to have it separated. Does it work for you?

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:38]: Sure, if we move the other tracing test here, that seems good. Point is to keep them in a single place.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:38]: Do you want move the other test here as well?

Comment (mabartos) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:38]: I think it should be done in a separate PR to keep some sort of atomicity.

Comment (vmuzikar) [reply operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java:38]: Ok, works for me either way, don't want to block this PR on this.

My reasoning to suggest moving the other OTEL test (`testTracingSpec`) in this PR was that we're also moving `podNamePropagation` to a new test class here, so felt natural to me to move both at the same time. But it's not a blocker for me.

**Review by vmuzikar — APPROVED** [review]
