### PR TITLE
Fix custom userFed that doesn't implement CredentialInputUpdater

### LINKED ISSUE #19491: Cannot set initial password for new users when using a custom UserFederation
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I have a custom User Federation in my realm. When I create a user in the admin UI I can not set a password for that user.
I suspect the problem is the new "FederatedCredentials.tsx" used in "UserCredentials.tsx". From what I see it misses the behavior for an empty List of credentials.
This worked fine before updating to 21.0.1

### Version

21.0.1

### Expected behavior

The "Credentials" tab shows the big plus sign and the button to set a password.

### Actual behavior

The "Credentials" tab shows an empty list of credenitals.

### How to Reproduce?

Add a user federation to a realm, create a user and go to the "Credentials" tab of that user.

### Anything else?

It is possible that we are missing something in our User Federation, but it worked fine until I updated.
I suspect this commit: https://github.com/keycloak/keycloak/commit/2ae520fb8a578ac2a44bed55e5c89f147d16a13f#diff-a1e2da5a441004308e9f0a28ff989d02e123ec30a1c9a63e347a11fcac490137

### PR DESCRIPTION
**Pull request by ssilvert**
Fixes #19491

Fixing this required pulling a lot of things from `FederatedCredentials.tsx` into the parent, `UserCredentials.tsx`.  There wasn't much left except the markup, so I just moved the rest and removed `FederatedCredentials.tsx`.

### CODE REVIEW

File: js/apps/admin-ui/src/user/UserCredentials.tsx [hunk 1]
```diff
@@ -35,9 +35,11 @@ import { InlineLabelEdit } from "./user-credentials/InlineLabelEdit";
 import styles from "@patternfly/react-styles/css/components/Table/table";
 import { CredentialRow } from "./user-credentials/CredentialRow";
 import { toUpperCase } from "../util";
+import { KeycloakSpinner } from "../components/keycloak-spinner/KeycloakSpinner";
+import { FederatedUserLink } from "./FederatedUserLink";
 
 import "./user-credentials.css";
-import { FederatedCredentials } from "./user-credentials/FederatedCredentials";
+//import { FederatedCredentials } from "./user-credentials/FederatedCredentials";
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserCredentials.tsx:42]: Can we remove this commented out code?
```suggestion
```

File: js/apps/admin-ui/src/user/UserCredentials.tsx [hunk 2]
```diff
@@ -329,6 +331,28 @@ export const UserCredentials = ({ user }: UserCredentialsProps) => {
     }
   };
 
+  const useFederatedCredentials = user.federationLink || user.origin;
+  const [credentialTypes, setCredentialTypes] = useState<string[]>([]);
+
+  if (useFederatedCredentials) {
+    useFetch(
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserCredentials.tsx:338]: Hook functions are [not allowed](https://react.dev/warnings/invalid-hook-call-warning#breaking-rules-of-hooks) to be called conditionally.

File: js/apps/admin-ui/src/user/UserCredentials.tsx [hunk 3]
```diff
@@ -485,30 +509,58 @@ export const UserCredentials = ({ user }: UserCredentialsProps) => {
           </TableComposable>
         </PageSection>
       )}
-      {(user.federationLink || user.origin) && (
-        <FederatedCredentials user={user} onSetPassword={toggleModal} />
+      {useFederatedCredentials && hasCredentialTypes && (
+        <PageSection variant={PageSectionVariants.light}>
+          <TableComposable variant={"compact"}>
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserCredentials.tsx:514]:
```suggestion
          <TableComposable variant="compact">
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/user/UserCredentials.tsx [hunk 4]
```diff
@@ -329,6 +330,26 @@ export const UserCredentials = ({ user }: UserCredentialsProps) => {
     }
   };
 
+  const useFederatedCredentials = user.federationLink || user.origin;
+  const [credentialTypes, setCredentialTypes] = useState<string[]>([]);
+
+  useFetch(
+    () => adminClient.users.getUserStorageCredentialTypes({ id: user.id! }),
+    setCredentialTypes,
+    []
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserCredentials.tsx:339]: It's not likely to change, but since this fetch passes the user's id it should be a dependency here.
```suggestion
    [user.id]
```

**Review by jonkoops — DISMISSED** [review]
Small nit, but otherwise LGTM

File: js/apps/admin-ui/src/user/UserCredentials.tsx (hunk 4 above)
Comment (ssilvert) [reply js/apps/admin-ui/src/user/UserCredentials.tsx]: @jonkoops Done.

**Review by jonkoops — DISMISSED** [review]
LGTM!

**Review by jonkoops — APPROVED** [review]
