### PR TITLE
OID4VCI credentials have invalid subject id value

### LINKED ISSUE #43854: OID4VCI credentials have invalid subject id value
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

With oid4vc_natural_person  we get credentials like this 

```
{
    "_sd": [
        "57fy_JHyzJS5gt3QrHqnzeq18HVM3NzA1jv2Gz-0DgY",
        "6noKmxXkD9wtoVQq6w6Yy0ldWe6cIgPHrqKzRInh7zA",
        "7qVtLDYk8l5EMxAd8m4q99QzlCqc0ACGThr8-JYzXBY",
        "Ceogod-Tn_vtM_dFWRZsQlqvmZAvcy6UERKI3tAq5Kg",
        "OlwZJoSFht0zVn2--0g5NAoQ0sih7lAl0wgkBV55R2c",
        "OuqThn6OhslgAFYTSxNpY6EZIF0-K4q9YEY4jlx0Ssw",
        "VvgcR5g21HPAi_CzGwuiFR3OqSrK2DNtB9I1rYiwOSM",
        "hY0GlYSCrsOGb63q2h4xLqx4UGjhFHzZI1WGwhilnzk",
        "mUqL3x6r4WJ45D5L8GRoA8pS09M9I_yg4WTbZFl6-68",
        "nH9-5FU1Qzqk8qlBDtPwphUs3tNiidkQJFXXv0yH6MY",
        "siK_io9IWrisfoxs2tNn0ACAR1FKG-YpecGM0j8AmRQ",
        "uJ4bCl6Yu4hr_fVmc5kyQ8oR_BA7Ufs0UFQ6OG7NmbI",
        "v1zy1vJbEvPO3O7xUY1hPe5SD4OQKGl8IdthZLiBPY8"
    ],
    "_sd_alg": "SHA-256",
    "vct": "oid4vc_natural_person",
    "iss": "did:key:z4oJ8dcwF8oDcPcSYbAeioXtoq6vmJZ7o9fAEbPkYncQFnGb71ZaAoSrG1azKQnVawjcJiCgxjEECnpcTYPVHQGEqNoQx",
    "id": "id",
    "cnf": {
        "jwk": {
            "kid": "uBHnFK3vKHYpl6yeaHRH-9eG8zRhpkqbbB-HIMhfyQM",
            "kty": "EC",
            "alg": "ES256",
            "use": "sig",
            "crv": "P-256",
            "x": "H4B9ZHQISPRy7JE39KBKKtccLt3NxkuwUvHJxHtwDK8",
            "y": "QXpXqW_bkVRMBNeFl0E2KsVmGvSc1l7KsUBamkcKaMA"
        }
    }
}
```

The `"id": "id"` is not a valid dc+sd-jwt claim according to [oid4vci-1.0](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#I-D.ietf-oauth-sd-jwt-vc)

The code suggests that this is supposed to be a subject id (OID4VCSubjectIdMapper), which however should be a did and part of the subject claims (instead of a top level jwt claim).

The comment reads _Sets an ID for the credential, either randomly generated or statically configured_, but such a credential id is not to be found in the spec AFAICS.

I suggest to ...

1. Rename that mapper to `OID4VCCredentialIdMapper`
2. Make it work such that it actually creates a random id for every vc of that type
3. Remove it from oid4vc_natural_person for spec alignment

Note, when a credential is issued as a JWT, the credential id should be different from JWT id (jti)

### PR DESCRIPTION
**Pull request by tdiesler**
closes #43854

This is the second attempt to fix the subject id issue. Unlike the previous attempt it is not concerned with SD JWT claim visibility nor does it introduce an additional 'did' user attribute.

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCSubjectIdMapper.java [hunk 1]
```diff
@@ -48,45 +51,57 @@ public class OID4VCSubjectIdMapper extends OID4VCMapper {
         ProviderConfigProperty idPropertyNameConfig = new ProviderConfigProperty();
         idPropertyNameConfig.setName(CLAIM_NAME);
         idPropertyNameConfig.setLabel("ID Property Name");
-        idPropertyNameConfig.setHelpText("Name of the property to contain the id.");
-        idPropertyNameConfig.setDefaultValue("id");
+        idPropertyNameConfig.setHelpText("Name of the property to contain the subject id.");
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCSubjectIdMapper.java]: AFAIK This configuration property refers to the name of the claim, which will be in the OID4VC credential. IMO the label "ID Property Name" is confusing and tooltip is confusing as well and also it is not consistent with the naming used by "User Attribute Mapper". So I wonder if for consistency it should just simply use something like:
```
idPropertyNameConfig.setLabel(OIDCAttributeMapperHelper.TOKEN_CLAIM_NAME_LABEL);
idPropertyNameConfig.setHelpText("Name of the claim to insert into the token. This can be a fully qualified name such as 'address.street'. In case that 'id' is used as a value of this configuration property, it would be mapped into sd-jwt credential as claim 'sub'.");
```
in same way like "User Attribute Mapper" is using? Note that I've used also slightly different note for help-text to inform that "id" is mapped into "sub" in case of sd-jwt credential (if I understand correctly the code snippet you added in `SdJwtCredentialBuilder`).

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCSubjectIdMapper.java [hunk 2]
```diff
@@ -48,45 +51,57 @@ public class OID4VCSubjectIdMapper extends OID4VCMapper {
...
-        return CONFIG_PROPERTIES;
-    }
 
-    @Override
-    public List<String> getMetadataAttributePath() {
-        return ListUtils.union(getAttributePrefix(), List.of("id"));
+        ProviderConfigProperty userAttributeConfig = new ProviderConfigProperty();
+        userAttributeConfig.setName(USER_ATTRIBUTE_KEY);
+        userAttributeConfig.setLabel("User attribute");
+        userAttributeConfig.setHelpText("The user attribute that maps to the subject id.");
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCSubjectIdMapper.java]:
```suggestion
        userAttributeConfig.setHelpText("The name of the user attribute that maps to the subject id.");
```
Just a nitpick to make this tooltip a little bit cleaner.

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCSubjectIdMapper.java [hunk 3]
```diff
@@ -21,20 +21,23 @@
...
 import org.keycloak.protocol.oid4vc.OID4VCLoginProtocolFactory;
 import org.keycloak.protocol.oid4vc.model.VerifiableCredential;
 import org.keycloak.provider.ProviderConfigProperty;
 
-import org.apache.commons.collections4.ListUtils;
+import static org.keycloak.OID4VCConstants.CLAIM_NAME_SUBJECT_ID;
 
 /**
- * Sets an ID for the credential, either randomly generated or statically configured
+ * Sets an ID for the credential subject, either by attribute mapping or statically configured
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCSubjectIdMapper.java]:
```suggestion
 * Sets an ID for the credential subject, either from User ID or by attribute mapping
```
Small nitpick to this javadoc as AFAIK the "statically configured" is not supported anymore with your changes.

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCSubjectIdMapper.java [hunk 4]
```diff
@@ -96,7 +111,7 @@ public String getDisplayType() {
 
     @Override
     public String getHelpText() {
-        return "Assigns a subject ID to the credentials subject. If no specific id is configured, a randomly generated one is used.";
+        return "Assigns a subject ID to the credentials subject. The default is the user's id, others can be selected.";
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCSubjectIdMapper.java]:
```suggestion
        return "Sets an ID for the credential subject, either from User ID or by attribute mapping.";
```
Another small nitpick: I like a bite more the formulation used in the javadoc and hence proposed here to update "help text" to use the same text. It sounds a little bit more clear what this mapper is doing. But I am not strong on this to be used as help text.

**Review by mposolda — COMMENTED** [review]
@tdiesler Thanks for the PR! I've added few review comments in the PR. Can you check them please?

@Captain-P-Goldfish @IngridPuppet @Awambeng @forkimenjeckayang @Ogenbertrand Do someone of you prefer to review as well?

**Review by mposolda — APPROVED** [review]
@tdiesler Thanks! I am merging since this PR blocks the other PR.

If someone else wants to review, feel free to create follow-up issues / PRs.
