### PR TITLE
fix: adds affinity and other scheduling to the operator

### LINKED ISSUE #29258: Support pod affinity settings in the Keycloak Operator
### Description

Kubernetes allows to specify affinity settings for Pods. 

This would allow: 
* avoiding to run multiple Keycloak instances on one node, avoiding data loss on a node failure (
* additional resilience strategies related to a Kubernetes topology (like avoid all Keycloak instances to be on servers on a specific rack, or a specific availability zone) 
* specifying Keycloak to run on ARM based nodes (similar to https://www.scaleway.com/en/docs/containers/kubernetes/how-to/deploy-x86-arm-images/)

### Motivation

* Better resilience against failures
* Cost-saving when using ARM

### PR DESCRIPTION
**Pull request by shawkins**
closes: #29258

Draft of a scheduling spec with the options that are most likely to be requested - affinity, topologyspread, priorityclass, and tolerations.

The handling is similar to other constructs - if the user has populated the field in the unsupported spec, that takes presedence.

A new label, app.kubernetes.io/component, is added to distinguish the server pods.

The default node anti-affinity is added if no other affinity has been specified. This mechanism may not have great usability. It could be better to have a withDefaults field on the scheduling spec.

Similarly I'm proposing to go a step further and handle the default affinity or spread - depending upon whether an external cache is in use. Issues with doing this:
- cache configuration is currently done though additional properties. However we do have a cache spec where we could have first-class properties.
- the cache configuration could be baked into the image, which we currently don't know how to account for. At worst the user would need to supply their own spread constraint(s).

@ahus1 @vmuzikar @abelmatos WDYT?

### CODE REVIEW

**Comment by shawkins** [comment]
@ahus1 I'm fine with removing the defaults around spread constraints and moving that to a topic for the scaling guide.

**Comment by ahus1** [comment]
> I'm fine with removing the defaults around spread constraints and moving that to a topic for the scaling guide.

No, please add a default best-effort spread. I'm just against making the default settings dependent on the cache configuration.

**Comment by shawkins** [comment]
> No, please add a default best-effort spread. I'm just against making the default settings dependent on the cache configuration.

The default spread is just an affinity for the same zone. The pr has been updated with that.

Should just need some docs.

@vmuzikar WDYT?

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thank you for the changes!

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java [hunk 1]
```diff
@@ -224,6 +227,8 @@ static Optional<PodTemplateSpec> getPodTemplateSpec(Keycloak keycloakCR) {
 
     private StatefulSet createBaseDeployment(Keycloak keycloakCR, Context<Keycloak> context) {
         Map<String, String> labels = Utils.allInstanceLabels(keycloakCR);
+        labels.put("app.kubernetes.io/component", "server");
```
[the remark this answers is not in the document]
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:230]: @vmuzikar we could, but I think the intent here is to have a general component name - to make it easy for example to find all databases regardless of what they are being used with. The component in combination with the other labels certainly is unique enough.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java [hunk 2]
```diff
@@ -350,6 +356,40 @@ private StatefulSet createBaseDeployment(Keycloak keycloakCR, Context<Keycloak>
...
+            }
+            if (!specBuilder.hasTolerations()) {
+                specBuilder.withTolerations(schedulingSpec.getTolerations());
+            }
+            if (!specBuilder.hasTopologySpreadConstraints()) {
+                specBuilder.withTopologySpreadConstraints(schedulingSpec.getTopologySpreadConstraints());
+            }
+        }
+
+        // set defaults if nothing was specified by the user
```
[the remark this answers is not in the document]
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:376]: Will do

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java [hunk 3]
```diff
@@ -350,6 +356,40 @@ private StatefulSet createBaseDeployment(Keycloak keycloakCR, Context<Keycloak>
...
+
+        if (!specBuilder.hasAffinity()) {
+            specBuilder.editOrNewAffinity().withNewPodAffinity().addNewPreferredDuringSchedulingIgnoredDuringExecution()
+                    .withWeight(1).withNewPodAffinityTerm().withNewLabelSelector().withMatchLabels(labels)
```
Comment (ryanemerson) [inline operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:380]: Shouldn't we be setting a greater weight here? The default policy should encourage pods to be distributed to Nodes in the same AZ as much as possible.

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:380]: From what we've talked about for default support this is sufficient. If we also add the ability to retain the default affinities, then we can make this greater to allow for users to choose weights that are less. 

In the worst case if there's just a single node in each AZ my expectation is that we'll still prefer separate nodes over keeping things in the same AZ - do you want it the other way around?

Comment (ryanemerson) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:380]: It's a trade-off between performance and protecting against data loss. As this is the default policy, I think you're right that in the worst-case we should favour distributing pods across AZs in  order to prevent data loss on node failure.

However with a weight of 1 for the ZONE_KEY, what would happen in this scenario: K8s is deployed across 3 AZs, each of which has 2 nodes. Keycloak is then deployed with 3 replicas? Does having a lower weight assigned to the ZONE_KEY affinity strategy mean it's more likely that the 3rd pod will be deployed in a different AZ to the first 2?

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:380]: > Does having a lower weight assigned to the ZONE_KEY affinity strategy mean it's more likely that the 3rd pod will be deployed in a different AZ to the first 2 that are hosted on distinct nodes in the same AZ?

Let's assume that the first instance is placed in AZ 1. The next instance has 6 nodes to consider, kubernetes will create a sum of the weights for each of the targets. The same node will have a weight of 50, the other node in the same AZ will have a weight of 0. All of the other nodes will have a weight of 0. The scheduler will choose the one with the lowest weight, which will be the other node in the same AZ.

Comment (ryanemerson) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:380]: Not meaning to nitpick, just want to clarify for my own understanding.

> The same node will have a weight of 50, the other node in the same AZ will have a weight of 0.

Won't the other node have a weight of 1 as it satisfies the zone affinity rule?


> The scheduler will choose the one with the lowest weight, which will be the other node in the same AZ.

I thought the scheduler chose the node with the largest value?


```qoute
The final sum is added to the score of other priority functions for the node. Nodes with the highest total score are prioritized when the scheduler makes a scheduling decision for the Pod.
```

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:380]: @ryanemerson yes sorry I was thinking of it the other way around for some reason. So what we actually have is:

node 1 zone 1 with an existing keycloak, score 1
node 2 zone 1 with score 51
node 3 zone 2 with score 50
node 4 zone 2 with score 50
node 5 zone 3 with score 50
node 6 zone 3 with score 50

Which should prefer the placemtn on node 2.

The more constrained scenario of just a single node per zone:

node 1 zone 1 with an existing keycloak, score 1
node 2 zone 2 with score 50
node 3 zone 3 with score 50

The scheduler will prefer node 2 / 3 over node 1.

Comment (ryanemerson) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:380]: Thanks for the explanation @shawkins, it makes it clear to me now that a larger weight isn't required. The defaults LGTM :+1:

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java]: In case we do move forward with an option to preserve the default affinities, I updated the PR to use 10 instead of 1 as the weight so that there is room for even smaller weights.

**Comment by shawkins** [comment]
@vmuzikar added the docs, should be fully ready for review now.

**Review by ryanemerson — APPROVED** [review]

**Review by mabartos — DISMISSED** [review]
@shawkins Great work! I've just put a little brain dump below. And there's also some changes conflict.

nit: I also like when we have test-covered the CR serialization as they're running a few ms and may bring additional test coverage - but in this case the PodTemplate test should be sufficient enough.

File: operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java [hunk 4]
```diff
@@ -350,6 +356,42 @@ private StatefulSet createBaseDeployment(Keycloak keycloakCR, Context<Keycloak>
...
+                specBuilder.withTopologySpreadConstraints(schedulingSpec.getTopologySpreadConstraints());
+            }
+        }
+
+        // set defaults if nothing was specified by the user
+        // - server pods will have an affinity for the same zone as to avoid stretch clusters
+        // - server pods will have a stronger anti-affinity for the same node
+
+        if (!specBuilder.hasAffinity()) {
+            specBuilder.editOrNewAffinity().withNewPodAffinity().addNewPreferredDuringSchedulingIgnoredDuringExecution()
```
[the remark this answers is not in the document]
Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:381]: That was to keep the code portable - those invocations can be moved around, without causing an issue. I can refactor to use an affinity builder if that will read better.

[the remark this answers is not in the document]
Comment (mabartos) [reply operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java:381]: No worries, it's only a nitpick. There are no comprehensive evaluations of the existing affinity under the hood, so just leave it as is, as it can additionally prevent some possible issues in the future.

File: docs/guides/operator/advanced-configuration.adoc [hunk 5]
```diff
@@ -204,6 +204,25 @@ It is achieved by providing certain JVM options.
...
+----
+apiVersion: k8s.keycloak.org/v2alpha1
+kind: Keycloak
+metadata:
+  name: example-kc
+spec:
+  scheduling:
+    priortyClassName: custom-high
+  ...
+----
```
[the remark this answers is not in the document]
Comment (mabartos) [reply docs/guides/operator/advanced-configuration.adoc:223]: As discussed, it'd be really good to include some references to the k8s guides for the settings - as links. Hope it will not decrease the docs CI stability for the external links tests. But the UX will be improved, so I'm in favor to do it :) And after the private discussion, I agree that these examples might not be directly included in the KC guide.

@shawkins WDYT?

**Comment by shawkins** [comment]
@ryanemerson @ahus1 @vmuzikar in the docs should we call out specifically recommending an affinity for the same zone as the database?

File: docs/guides/operator/advanced-configuration.adoc [hunk 6]
```diff
@@ -204,6 +204,25 @@ It is achieved by providing certain JVM options.
 
 For more details, see <@links.server id="containers" />.
 
+=== Scheduling
+
+You may control several aspects of the server Pod scheduling via the Keycloak CR. The scheduling stanza exposes the standard Kubernetes affinity, tolerations, topology spread constraints, and the priority class name to fine tune the scheduling and placement of your server Pods. By default if you do not specify a custom affinity your Pods will have an affinity for the same zone to prevent stretch clusters and an anti-affinity for the same node to improve availability.
```
[the remark this answers is not in the document]
Comment (shawkins) [reply docs/guides/operator/advanced-configuration.adoc]: Added a little more on this. I'd defer to @ryanemerson if we want a more detailed explanation.

File: docs/guides/operator/advanced-configuration.adoc (hunk 5 above)
[the remark this answers is not in the document]
Comment (shawkins) [reply docs/guides/operator/advanced-configuration.adoc:243]: Added a snippet showing all fields used and a link to the kubernetes scheduling docs.

**Comment by ahus1** [comment]
@shawkins 

> should we call out specifically recommending an affinity for the same zone as the database?

The good thing about pod affinity is that it is now (1) supported by the Operator and no longer part of the unsupported pod template and (2) we have a reasonable default. 

Deploying Keycloak on the same region as the database seems to be a good idea, still I didn't tested this how much it actually impacts Keycloak. And if the database is running outside of Kubernetes, you would start coding the zone manually in the affinity rules, and not use the "try to run all pods in the same zone but I don't care which". 

So I'd say it is probably good enough for now. 

Once we work with this a bit more, I could see that we provide some predefined scheduling templates to hide the complexity and to promote some well-tested and well-understood scheduling methods. This would then be a follow-up PR.

**Comment by ryanemerson** [comment]
+1 to Alexander's comment. I think that more advanced/opinionated setting examples should exist as part of the Keycloak HA guide or similar, where we explain in detail the trade-offs of different architectures and how they apply to specific use-cases.

File: docs/guides/operator/advanced-configuration.adoc (hunk 6 above)
[the remark this answers is not in the document]
Comment (ryanemerson) [reply docs/guides/operator/advanced-configuration.adoc]: I think what we have for now is fine. I think we need a dedicated guide explaining different architectures, stretch vs non-stretch etc, as it's a complex topic.

File: docs/guides/operator/advanced-configuration.adoc [hunk 7]
```diff
@@ -204,6 +204,48 @@ It is achieved by providing certain JVM options.
...
+              matchLabels:
+                app: keycloak
+                app.kubernetes.io/managed-by: keycloak-operator
+                app.kubernetes.io/component: server
+                topologyKey: topology.kubernetes.io/zone
+              weight: 10
+    tolerations:
+      - key: "some-taint"
+  		operator: "Exists"
+		effect: "NoSchedule"
```
Comment (mabartos) [inline docs/guides/operator/advanced-configuration.adoc:236]:
```suggestion
    tolerations:
    - key: "some-taint"
      operator: "Exists"
      effect: "NoSchedule"
```
It'd be good to have unified formatting for this

**Review by mabartos — COMMENTED** [review]
@shawkins Just last minor thing about the example formatting, otherwise LGTM

**Comment by shawkins** [comment]
> @shawkins Just last minor thing about the example formatting, otherwise LGTM

Should be good now.

File: docs/guides/operator/advanced-configuration.adoc (hunk 7 above)
Comment (vmuzikar) [reply docs/guides/operator/advanced-configuration.adoc:236]: Looks like @mabartos' comment is still valid?

**Review by vmuzikar — COMMENTED** [review]
Added one minor comment. LGTM otherwise.

File: docs/guides/operator/advanced-configuration.adoc (hunk 7 above)
Comment (shawkins) [reply docs/guides/operator/advanced-configuration.adoc:236]: Not sure, what happened there. Applying again.

**Review by vmuzikar — APPROVED** [review]
@shawkins LGTM, thank you.

**Comment by vmuzikar** [comment]
@mabartos I believe your comments has been resolved. I'm overriding your review request so we can merge. Let me know if you have any further concerns, we can address them as a follow-up.
