### PR TITLE
KEYCLOAK-19866 Fix user-defined-/anyType parsing and introduce XPathAttributeMapper

### LINKED ISSUE #11644: Crash when parsing user-defined or anyType SAML attributes
### Describe the bug

Keycloak crashes whenever you try to parse a SAML response with user-defined types or anyTypes. More information is given in [KEYCLOAK-19866](https://issues.redhat.com/browse/KEYCLOAK-19866). The workaround in #8156 only works for simple user-defined types and does not mitigate the issue.

A fix is already proposed in #10650

### Version

18.0.0

### Expected behavior

- Keycloak should not crash
- Attributes of user-defined and anyType should be available in attribute mapping

### Actual behavior

- The application crashes

### How to Reproduce?

Let keycloak process a saml response with user-defined types e.g.

`<saml2:Attribute xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
  <saml2:AttributeValue xmlns:myCustomType="http://www.whatever.de/schema/myCustomType/saml/extensions"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="myCustomType:AddressType">
    <myCustomType:Street>Zillestraße</myCustomType:Street>
    <myCustomType:HouseNumber>17</myCustomType:HouseNumber>
    <myCustomType:ZipCode>10585</myCustomType:ZipCode>
    <myCustomType:City>Berlin</myCustomType:City>
    <myCustomType:Country>DE</myCustomType:Country>
  </saml2:AttributeValue>
</saml2:Attribute>`

SAMLAttributeValueParser#parse recognizes an user-defined type. StaxParserUtil#bypassElementBlock skips only the next tag (e. g. <myCustomType:Street>Zillestraße</myCustomType:Street>). The next element of xmlEventReader is <myCustomType:HouseNumber> which fails in SAMLAttributeParser#processSubElement and/or SAMLAttributeValueParser#parse as this element is no ATTRIBUTE_VALUE.

### Anything else?

The pull requests #10650 has a proposed solution including tests for problematic payloads

### LINKED ISSUE #13502: Add XPath processing of SAML custom attributes
### Description

Add a mapper to SAML broker capable of maniulating XML contents of SAML attributes via XPath.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by KnauerSecunet**
@hmlnarik following my email from end of january here is my proposed solution for KEYCLOAK-19866 which also renders KEYCLOAK-19608 unnecessary.

It fixes parsing user-defined types and anyType saml attributes. And lets you later processthem  via a xpath attribute mapper.

Please let me know what you think about it and which parts need improving/changes. Concerning the tests for the xpath mapper I plan to add one similar to AbstractUserAttributeMapperTest? Is there a documentation that needs to be expanded (with examples)?

### CODE REVIEW

**Comment by dpulrichth** [comment]
I cannot comment on whether this fits in with the guidelines and conventions within the code base but from a purely functional point of view this looks promising. It allows us to work with complex XML types with relative ease and removes the need for a customized keycloak. I got it up and running and can confirm that this works as expected.

A bit of documentation or examples might be helpful. I figured out how to use the included Mapper but had to refer to the source code to realize that the XPath must be relative to the SAML Attribute, not the SAML Assertion.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 1]
```diff
@@ -0,0 +1,305 @@
...
+        return "Attribute Importer";
+    }
+
+    @Override
+    public String getDisplayType() {
+        return "XPath Attribute Importer";
+    }
+
+    @Override
+    public void preprocessFederatedIdentity(KeycloakSession session, RealmModel realm, IdentityProviderMapperModel mapperModel, BrokeredIdentityContext context) {
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:125]: Although this method gets passed session and realm, it doesn't use them, and the other objects are quite plain. This makes it a good candidate for a unit test.

Therefore, I'd like to see a unit test at least for this method and a happy path. This would allow me to explore the code a lot more simpler.

A starting point could be the following snippet of code. Please update accordingly, and add 1-2 cases to provide the code coverage you would like to see.

```
public class XPathAttributeMapperTest extends TestCase {

    @Test
    public void test() {
        IdentityProviderMapperModel mapperModel = new IdentityProviderMapperModel();
        Map<String, String> config = new HashMap<>();
        mapperModel.setConfig(config);
        config.put(XPathAttributeMapper.USER_ATTRIBUTE, "email");
        config.put(XPathAttributeMapper.ATTRIBUTE_NAME, "email");
        config.put(XPathAttributeMapper.ATTRIBUTE_XPATH, "email");
        BrokeredIdentityContext context = new BrokeredIdentityContext("xzy");
        AssertionType assertion = AssertionUtil.createAssertion("xzy", NameIDType.deserializeFromString("xzy"));
        AttributeStatementType statement = new AttributeStatementType();
        assertion.getAttributeStatements().add(statement);
        context.getContextData().put(SAMLEndpoint.SAML_ASSERTION, assertion);
        new XPathAttributeMapper().preprocessFederatedIdentity(null, null, mapperModel, context);
        assertNotNull(context.getEmail());
    }
}
```

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 2]
```diff
@@ -0,0 +1,305 @@
...
+    private static final String FIRST_NAME = "firstName";
+    private static final String LAST_NAME = "lastName";
+    private static final Set<IdentityProviderSyncMode> IDENTITY_PROVIDER_SYNC_MODES = new HashSet<>(Arrays.asList(IdentityProviderSyncMode.values()));
+
+    static {
+        ProviderConfigProperty property;
+        property = new ProviderConfigProperty();
+        property.setName(ATTRIBUTE_XPATH);
+        property.setLabel("Attribute XPath");
+        property.setHelpText("XPath to search for in attribute.");
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:69]: As a user commented in the PR with: 

> [I] had to refer to the source code to realize that the XPath must be relative to the SAML Attribute, not the SAML Assertion.

please consider adding half a sentence or a full sentence here.

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for creating this pull request. I can see that this offers a very flexible way to extract information from SAML and that it will be useful to a lot of users. 

@hmlnarik asked me to review it, please find my comments below. 

Please let me know if any of my comments leaves open questions, or if you think any of the suggestions doesn't fit the context of this pull quest. 

I'm looking forward to you replies or an updated pull request.

**Comment by KnauerSecunet** [comment]
@ahus1: I agree to and basically implemented all of your suggestions in 5dec051. Comments:

- parseAnyTypeAsString was lacking the handling of the top element and namespace, but has different handlings for basic elements compared to parseCustomTypeAsString. But there was an error anyway (xmls have to have a single root element) so I needed to add a root for anyType and decided to use AttributeValue (as it seems more intuitive, see @dpulrichth comment) and both method are now similar enough to be merged together.
- I used a warning log when the xpath expression is bad (because that's something that shouldn't suddenly happen in a production environment). And error log for parsing problems (as we could parse the xml before that shouldn't happen).
- Good catch on the XXE!

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java [hunk 3]
```diff
@@ -141,4 +144,38 @@ public static String parseAnyTypeAsString(XMLEventReader xmlEventReader) throws
...
+                event = (XMLEvent) xmlEventReader.next();
+                if (event.isStartElement()) {
+                    tagLevel++;
+                }
+                if (event.isEndElement()) {
+                    tagLevel--;
+                }
+            } while (xmlEventReader.hasNext() && tagLevel >= 0);
+            writer.add(xmlEventFactory.createEndElement(tagName.getPrefix(), tagName.getNamespaceURI(), typeValueSplitted[1]));
+            writer.flush();
```
[the remark this answers is not in the document]
Comment (ahus1) [reply saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java]: Thanks for changing this. You can now resolve this thread.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 4]
```diff
@@ -0,0 +1,305 @@
...
+                        if (prefixes.containsKey(namespaceURI)) {
+                            list.add(prefixes.get(namespaceURI));
+                        }
+
+                        return list.iterator();
+                    }
+                });
+                return xPath.compile(attributeXPath).evaluate(new InputSource(new StringReader(xml)), XPathConstants.STRING);
+            } catch (XPathExpressionException e) {
+                // Ignore unparsable elements
```
[the remark this answers is not in the document]
Comment (ahus1) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: Thanks for changing this. You can now resolve this thread.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 5]
```diff
@@ -0,0 +1,305 @@
...
+                    public Iterator<String> getPrefixes(String namespaceURI) {
+                        List<String> list = new ArrayList<>();
+                        if (prefixes.containsKey(namespaceURI)) {
+                            list.add(prefixes.get(namespaceURI));
+                        }
+
+                        return list.iterator();
+                    }
+                });
+                return xPath.compile(attributeXPath).evaluate(new InputSource(new StringReader(xml)), XPathConstants.STRING);
```
[the remark this answers is not in the document]
Comment (ahus1) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: Thanks for changing this. You can now resolve this thread.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 6]
```diff
@@ -0,0 +1,305 @@
...
+        property = new ProviderConfigProperty();
+        property.setName(ATTRIBUTE_XPATH);
+        property.setLabel("Attribute XPath");
+        property.setHelpText("XPath to search for in attribute.");
+        property.setType(ProviderConfigProperty.STRING_TYPE);
+        configProperties.add(property);
+        property = new ProviderConfigProperty();
+        property.setName(ATTRIBUTE_NAME);
+        property.setLabel("Attribute Name");
+        property.setHelpText("Name of attribute to search for in assertion and apply xpath. You can leave this blank to try to apply xpath to all attributes or specify a friendly name instead.");
```
[the remark this answers is not in the document]
Comment (ahus1) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: Thanks for changing this. You can now resolve this thread.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 1 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:131]: Thanks for adding this test. Please now mark this thread to be resolved.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 7]
```diff
@@ -0,0 +1,314 @@
...
+    private static final Set<IdentityProviderSyncMode> IDENTITY_PROVIDER_SYNC_MODES = new HashSet<>(Arrays.asList(IdentityProviderSyncMode.values()));
+
+    static {
+        ProviderConfigProperty property;
+        property = new ProviderConfigProperty();
+        property.setName(ATTRIBUTE_XPATH);
+        property.setLabel("Attribute XPath");
+        property.setHelpText("XPath expression to search for. It has to be defined relative to the AttributeValue root element. Given prefixes and namespace are preserved. "
+                + "Example: <saml2:AttributeValue xmlns:myCustomType=\"http://myCustomType.extension\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"myCustomType:AddressType\">"
+                + "<myCustomType:Street>Zillestraße</myCustomType:Street>...</saml2:AttributeValue>");
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:75]: I see that you're using a character that is common in Germany, but might be confusing for other countries. In addition to this, this street does exist in Berlin. Please try to use a generic street name here, with an English name that would be preferred to match the English UI.
I tested the Admin UI and it shows the "<" and ">" correctly, so it is find to use XML here.

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thanks for updating this PR, looking at the new functionality this looks now good to me. 

As this is your first PR to the Keycloak project, the GitHub actions don't run automatically to provide feedback. They will require a manual approval by a maintainer.

I ran some unit tests on the SAML module using 

```
mvn clean install -am -pl saml-core
```

and I see that there are two failing tests:

```
[ERROR] Failures: 
[ERROR]   SAMLParserTest.testSaml20AssertionExample:1007 expected:<[<saml:AttributeValue xsi:type="xs:anyType" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">060D00000000SHZ
            </saml:AttributeValue>]> but was:<[060D00000000SHZ]>
[ERROR]   SAMLParserTest.testSaml20AssertionsAdviceTag:1137 
Expected: iterable containing [is "060D00000000SHZ"]
     but: item 0: was "<saml:AttributeValue xsi:type=\"xs:anyType\" xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\">060D00000000SHZ\n            </saml:AttributeValue>"
[INFO] 
[ERROR] Tests run: 85, Failures: 2, Errors: 0, Skipped: 0
```

Maybe something broke during refactoring, please have a look.

In addition to that, I'd prefer if you could rebase your PR with the lastest changes onto main. This will ensure that your changes work well with the latest changes in the main branch, even when there are no code conflicts.

Please some additional small review comments below.

**Comment by KnauerSecunet** [comment]
Sorry for closing it ... rebased to main, changed the help text (two better examples) and added some trace logging to help getting the right xpath. Now checking the unit tests.

**Comment by ahus1** [comment]
@KnauerSecunet - good to see it the PR back open and no worries! 

Please let me know when you got any questions or code I should look into!

**Comment by KnauerSecunet** [comment]
@ahus1 Yeah the test gave me some more insight what's possible already and what let to exceptions:
```
<saml:Attribute Name="xyzAnyA">
    <saml:AttributeValue xsi:type="xs:anyType"><A><B>b</B><C>c</C></A></saml:AttributeValue>
</saml:Attribute> <!-- case 1a: returns String "<A><B>b</B><C>c</C></A>" -->
<saml:Attribute Name="xyzAnyB">
    <saml:AttributeValue xsi:type="xs:anyType">Foo</saml:AttributeValue>
</saml:Attribute> <!-- case 1b: returns String "Foo" -->

<saml:Attribute Name="xyzCustom">
    <saml:AttributeValue xmlns:myCustomType="http://www.whatever.de/schema/myCustomType/saml/extensions" xsi:type="myCustomType:AddressType"><myCustomType:A><myCustomType:B>b</myCustomType:B><myCustomType:C>c</myCustomType:C></myCustomType:A></saml:AttributeValue>
</saml:Attribute> <!-- case 2: currently skipped -->

<saml:Attribute Name="xyzAny2">
    <saml:AttributeValue xsi:type="xs:anyType"><B>b</B><C>c</C></saml:AttributeValue>
</saml:Attribute> <!-- case 3: valid xml as far as I know? But leads to a "continuation" exception due to an error in SAMLAttributeValueParser#parseAnyTypeAsString -->

<saml:Attribute Name="xyzCustom2">
    <saml:AttributeValue  xmlns:myCustomType="http://www.whatever.de/schema/myCustomType/saml/extensions" xsi:type="myCustomType:AddressType"><myCustomType:B>b</myCustomType:B><myCustomType:C>c</myCustomType:C></saml:AttributeValue>
</saml:Attribute> <!-- case 4: also valid but same situation as case 3 with StaxParserUtil.bypassElementBlock -->
```
I guess my change should not change the result for case 1a/b (or anything in `saml20-assertion-example.xml`)? So I suggest I revert the parser to an earlier version and return:

- case 1a/b and `saml20-assertion-example.xml`: No changes
- case 2: `<myCustomType:A xmlns:myCustomType="..."><myCustomType:B>b</myCustomType:B><myCustomType:C>c</myCustomType:C></myCustomType:A>`
- case 3: `<anyType><B>b</B><C>c</C></anyType>` (hard coded root tag "anyType")
- case 4: `<myCustomType:AddressType xmlns:myCustomType="..." xsi:type="myCustomType:AddressType"><myCustomType:A><myCustomType:B>b</myCustomType:B><myCustomType:C>c</myCustomType:C></myCustomType:A></myCustomType:AddressType>`

Then case 2 would behave similar to an anyType of case 1, but I lose the AddressType type (any better ideas?). case 3 and case 4 also return similar results (and no longer throw exceptions).

**Comment by ahus1** [comment]
I had a look at the code an tried different variants. Yes, the existing parsing should remain the same. On the other hand I see that there is some inconsistency how values are returned. 

Here's some variants, I probably need to discuss with @hmlnarik what's best here, and if we could afford to break the existing behavior: 

* On top you your latest change 1c0a304df15ec8510992be5abc725540663f02f7, I pushed a commit here that makes all old tests pass, but not one of your new tests: 7591453aa0a5086975a844d9aa035a1bae69a01f

* Still, I'm not happy as there are so many variants for an XML snippet to end up as a string. The following would always include the `<saml:AttributeValue ...`, and would break two old test cases: 3d62b3d1ada82faa6a6e77b0af2315b51e8ec11f
```
Expected: is "<status><code><status>XYZ</status></code></status>"
     but: was "<saml:AttributeValue xsi:type=\"xs:anyType\" xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\"><status><code><status>XYZ</status></code></status></saml:AttributeValue>"

Expected: iterable containing [is "<n1:elem2 xmlns:n1=\"http://example.net\" xml:lang=\"en\"><n3:stuff xmlns:n3=\"ftp://example.org\">00DD0000000F7L5</n3:stuff></n1:elem2>"]
     but: item 0: was "<saml:AttributeValue xsi:type=\"xs:anyType\" xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\"><n1:elem2 xmlns:n1=\"http://example.net\" xml:lang=\"en\"><n3:stuff xmlns:n3=\"ftp://example.org\">00DD0000000F7L5</n3:stuff></n1:elem2></saml:AttributeValue>"
```

**Comment by ahus1** [comment]
Thinking a bit more, a consistent way with the existing logic would be to return an XML fragment, and to never return the `saml:AttributeValue` as a wrapper. Only XPathAttributeMapper would then add a dummy `<root>...</root>` around it to make the fragment a valid XML (there might be a better way to parse fragments, I'm not familiar with fragment parsing)

**Comment by ahus1** [comment]
Reading yesterday's comments, they sound rather draft and exploring. After a night's sleep, I suggest the following: 

* SAMLAttributeValueParser: Responsibility to return everything inside an attribute - mostly as a String, with the exception of a  XMLGregorianCalendar for dates
  * Old behavior: ignored some unknown types, and for multiple XML children returns only the first (Note: There are no existing tests for multiple children in the old code)
  * New behavior: ignoring fewer unknown types, returning all children within an attribute
* XPathAttributeMapper: Treat attribute contents as an XML fragment and apply an XPath
  * A simple (maybe too simple approach): Wrap the contents extracted by SAMLAttributeValueParser in a new root tag, then apply the XPath

With regards to namespace handling in SAMLAttributeValueParser: While my namespace handling is rusty, I suppose any namespace on the attribute that would be relevant for its children might as well be declared on the children, so they can be preserved even if the attribute tag is not part of the fragment. 

@KnauerSecunet, @hmlnarik - what do you think about this suggestion? I know this different from the original suggestion, still I see that it matches the behavior in the existing tests.

**Comment by ahus1** [comment]
Reading yesterday's comments, they sound rather draft and exploring. After a night's sleep, I suggest the following: 

* SAMLAttributeValueParser: Responsibility to return everything inside an attributeValue - mostly as a String, with the exception of a  XMLGregorianCalendar for dates
  * Old behavior: ignored some unknown types, and for multiple XML children returns only the first (Note: There are no existing tests for multiple children in the old code)
  * New behavior: ignoring fewer unknown types, returning all children within an attribute
* XPathAttributeMapper: Treat attributeValue contents as an XML fragment and apply an XPath
  * A simple (maybe too simple approach): Wrap the contents extracted by SAMLAttributeValueParser in a new root tag, then apply the XPath

With regards to namespace handling in SAMLAttributeValueParser: While my namespace handling is rusty, I suppose any namespace on the attributeValue that would be relevant for its children might as well be declared on the children, so they can be preserved even if the attributeValue tag is not part of the fragment. 

@KnauerSecunet, @hmlnarik - what do you think about this suggestion? I know this different from the original suggestion, still I see that it matches the behavior in the existing tests. This drops the information in `xsi:type`, I don't know what downsides that might have, still I assume most XPath evaluations would still work.

**Comment by KnauerSecunet** [comment]
> Thinking a bit more, a consistent way with the existing logic would be to return an XML fragment, and to never return the `saml:AttributeValue` as a wrapper. Only XPathAttributeMapper would then add a dummy `<root>...</root>` around it to make the fragment a valid XML (there might be a better way to parse fragments, I'm not familiar with fragment parsing)

> Reading yesterday's comments, they sound rather draft and exploring. After a night's sleep, I suggest the following: ...

As I understand it your draft and the proposed solution are the same: Both return the xml string (fragmet) including namespace and the mapper handles the missing root tag? It won't be that easy for the mapper to recognize a missing root element but basically I like that idea very much and think it would be feasible.

The missing xml-type also came to my mind, but I actually think it should be possible to rely on the attribute name (which can be configured/filtered in the xpath mapper).

@ahus1 Works for me, just waiting for your go when you get the projects feedback ...

**Comment by ahus1** [comment]
@KnauerSecunet - thanks for the feedback. Regarding the root tag: I'd suggest that the mapper will always wrap the string it receives within the root tag. That will make it simpler to implement, and it would not depend on the number of siblings in the string. Any user who would use an XPath with "//" wouldn't notice it, anyway IMHO.

I'll update this issue once I get feedback from the project.

**Comment by hmlnarik** [comment]
> A simple (maybe too simple approach): Wrap the contents extracted by SAMLAttributeValueParser in a new root tag, then apply the XPath

I agree with this approach, and agree also with the proposal to propagate namespaces to the first-level tags of the value as suggested here:

> While my namespace handling is rusty, I suppose any namespace on the attributeValue that would be relevant for its children might as well be declared on the children, so they can be preserved even if the attributeValue tag is not part of the fragment.

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java [hunk 8]
```diff
@@ -105,40 +108,50 @@ public Object parse(XMLEventReader xmlEventReader) throws ParsingException {
...
-        // KEYCLOAK-18417: Simply ignore unknown types
-        logger.debug("Skipping attribute value of unsupported type " + typeValue);
-        StaxParserUtil.bypassElementBlock(xmlEventReader);
-        return null;
+        if (typeValue.contains(":")) {
+            return parseAsString(xmlEventReader, element);
+        } else {
+            // KEYCLOAK-18417: Simply ignore unknown types
+            logger.debug("Skipping attribute value of unsupported type " + typeValue);
+            return null;
```
Comment (ahus1) [inline saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java:116]: While the old code called `StaxParserUtil.bypassElementBlock(xmlEventReader);` whenever there was something unknown, the new code doesn't call it any more. I suspect this could lead to a wrong result. Please have a look.

**Review by ahus1 — CHANGES_REQUESTED** [review]
@KnauerSecunet - after talking to @hmlnarik today, the suggested approach is now generally approved (thank you, @hmlnarik!).

While the new code uses the safe XXE methods, he also asked for a test to show that it is safe. This shouldn't affect the implementation, and I'll have more information on that, soon. 

If you have additional questions, I'm happy to get the answers for them.

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java (hunk 8 above)
Comment (KnauerSecunet) [reply saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java]: As we can now parse anything (even without a prefix separator) I removed the else-branch

**Comment by KnauerSecunet** [comment]
Changed the code as discussed (parsing without root-tag and type; adding a root tag in mapping). Changed the help texts and tests accordingly. Added some new tests in SAMLParserTest#testInvalidEndElement.

> While the new code uses the safe XXE methods, he also asked for a test to show that it is safe. This shouldn't affect the implementation, and I'll have more information on that, soon.

I was not able to add a XXE test for the mapper. XXE via DOCTYPE should no longer be possible as we add a root tag on top level. If I change the input to `new InputSource(new StringReader(xml))`, use the payload `<foo xmlns:xi="http://www.w3.org/2001/XInclude"><xi:include parse="text" href="file:///etc/passwd"/></foo>` and the xpath `/` I just get `null` and nothing from passwd. I am not sure whether InputSource is subsceptible to xinclude injection.

@ahus1 Any ideas for the XXE test (or comments for the other changes)?

**Review by ahus1 — CHANGES_REQUESTED** [review]
Hi, this now works great, I did a review for the code changes and they work in the unit test. I asked a maintainer to give the GitHub actions a run, and that showed one failing test as the list of attribute mappers now contained a new entry. The other failing tests were unstable, and can be disregarded. 

With some help from @mhajas I was able to create an integration test for the new XPathAttribute mapper: it shows that some additional XML with a string can be parsed by the XPathMapper and that it will be stored as a user attribute. 

I also changed one log statement for efficiency. 

My changes are available here: https://github.com/KnauerSecunet/keycloak/pull/9 ... please review them, merge them, and squash them with your changes. Then this PR is good to be merged from my perspective.

**Comment by ahus1** [comment]
@hmlnarik - I reviewed this PR today, and it looks fine to me. With some help from @mhajas I prepared an integration test in a separate branch (until this is merged, these changes are available here: https://github.com/KnauerSecunet/keycloak/pull/9).

As the XPathAttributeMapper uses the XXE safe methods, and as the fragment is wrapped inside a `<root></root>` element, I don't see a way to exploit this via a SAML Attribute Value, so no additional tests similar to https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/SamlXMLAttacksTest.java would be necessary. Please comment here if you think differently about this.

I'd trigger you again once the integration tests have been merged here.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 9]
```diff
@@ -0,0 +1,316 @@
...
+        property = new ProviderConfigProperty();
+        property.setName(ATTRIBUTE_FRIENDLY_NAME);
+        property.setLabel("Friendly Name");
+        property.setHelpText("Friendly name of attribute to search for in assertion. You can leave this blank to try to apply XPath to all attributes or specify a name instead.");
+        property.setType(ProviderConfigProperty.STRING_TYPE);
+        configProperties.add(property);
+        property = new ProviderConfigProperty();
+        property.setName(USER_ATTRIBUTE);
+        property.setLabel("User Attribute Name");
+        property.setHelpText("User attribute name to store XPath value.  Use email, lastName, and firstName to map to those predefined user properties.");
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:93]: Since https://issues.redhat.com/browse/KEYCLOAK-14536, the email, lastName and firstName are treated (from the perspective of mapper) as attributes, and not as properties anymore, and do not need special handling below
```suggestion
        property.setHelpText("User attribute name to store XPath value. Use " + UserModel.EMAIL + ", " + UserModel.FIRST_NAME + ", and " + UserModel.LAST_NAME + " for e-mail, first and last name, respectively.");
```

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 10]
```diff
@@ -0,0 +1,316 @@
...
+        if (!attributeValuesInContext.isEmpty()) {
+            if (attribute.equalsIgnoreCase(EMAIL)) {
+                setIfNotEmpty(context::setEmail, attributeValuesInContext);
+            } else if (attribute.equalsIgnoreCase(FIRST_NAME)) {
+                setIfNotEmpty(context::setFirstName, attributeValuesInContext);
+            } else if (attribute.equalsIgnoreCase(LAST_NAME)) {
+                setIfNotEmpty(context::setLastName, attributeValuesInContext);
+            } else {
+                context.setUserAttribute(attribute, attributeValuesInContext);
+            }
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:149]: Due to the same argument as above (https://issues.redhat.com/browse/KEYCLOAK-14536), can be replaced with 
```suggestion
            context.setUserAttribute(attribute, attributeValuesInContext);
```

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 11]
```diff
@@ -0,0 +1,316 @@
...
+
+                Matcher namespaceMatcher = Pattern.compile("xmlns:(\\w+)=\"(.+?)\"").matcher(xml);
+                Map<String, String> namespaces = new HashMap<>();
+                Map<String, String> prefixes = new HashMap<>();
+                while (namespaceMatcher.find()) {
+                    namespaces.put(namespaceMatcher.group(1), namespaceMatcher.group(2));
+                    prefixes.put(namespaceMatcher.group(2), namespaceMatcher.group(1));
+                }
+
+                XPath xPath = XPathFactory.newInstance().newXPath();
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:195]: This is a costly operation. Please introduce a method `getXPathFactory` similar to `getXMLInputFactory` (below for reference) and use it instead. Consider also introducing setting dummy `XPathVariableResolver` in that method as described in https://cheatsheetseries.owasp.org/cheatsheets/Injection_Prevention_in_Java_Cheat_Sheet.html#xml-xpath-injection.
https://github.com/keycloak/keycloak/blob/9b43e62f2b6279ba0da9cedcf4b790ccd9b5edaa/saml-core/src/main/java/org/keycloak/saml/common/util/StaxParserUtil.java#L905-L933

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 12]
```diff
@@ -0,0 +1,316 @@
...
+        };
+    }
+
+    private List<String> findAttributeValuesInContext(String attributeName, String attributeXPath, BrokeredIdentityContext context) {
+        AssertionType assertion = (AssertionType) context.getContextData().get(SAMLEndpoint.SAML_ASSERTION);
+
+        return assertion.getAttributeStatements().stream()
+                .flatMap(statement -> statement.getAttributes().stream())
+                .filter(elementWith(attributeName))
+                .flatMap(attributeType -> attributeType.getAttribute().getAttributeValue().stream())
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:242]: Consider leveraging method references rather than introducing new methods. https://softwareengineering.stackexchange.com/a/285311 can give more insight why:

```suggestion
                .map(AttributeStatementType::getAttributes)
                .flatMap(Collection::stream)
                .map(List::getAttributes)
                .filter(elementWith(attributeName))
                .map(AttributeStatementType.ASTChoiceType::getAttribute)
                .filter(Objects::nonNull) // note that the attribute could be encrypted, thus resulting to null
                .map(AttributeType::getAttributeValue)
                .flatMap(Collection::stream)
```

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java [hunk 13]
```diff
@@ -0,0 +1,316 @@
...
+                // attribute no longer sent by brokered idp, remove it
+                user.removeAttribute(attribute);
+            } else if (currentAttributeValues == null) {
+                // new attribute sent by brokered idp, add it
+                user.setAttribute(attribute, attributeValuesInContext);
+            } else if (!CollectionUtil.collectionEquals(attributeValuesInContext, currentAttributeValues)) {
+                // attribute sent by brokered idp has different values as before, update it
+                user.setAttribute(attribute, attributeValuesInContext);
+            }
+            // attribute already set
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:280]: Please replace with solely attribute manipulation

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java [hunk 14]
```diff
@@ -141,4 +143,27 @@ public static String parseAnyTypeAsString(XMLEventReader xmlEventReader) throws
         }
     }
 
+    private static String addNamespaceWhenMissing(Deque<String> definedPrefixes, XMLEventWriter writer, StartElement startElement)
```
Comment (hmlnarik) [inline saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java:146]: Does this account for other namespaces used by e.g. attributes? For example would both `a` and `b` namespaces be preserved for the following tag?
```xml
<a:x b:lang="en" xmlns:a="uri:a" xmlns:b="uri:b"/>
```

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java [hunk 15]
```diff
@@ -141,4 +143,27 @@ public static String parseAnyTypeAsString(XMLEventReader xmlEventReader) throws
...
+            boolean hasNamespace = false;
+            while (namespaces.hasNext()) {
+                Namespace namespace = namespaces.next();
+                if (namespace.getNamespaceURI().equals(startElement.getName().getNamespaceURI())) {
+                    hasNamespace = true;
+                    break;
+                }
+            }
+            if (!hasNamespace) {
+                XMLEventFactory xmlEventFactory = XMLEventFactory.newInstance();
```
Comment (hmlnarik) [inline saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java:162]: This is a costly operation. Please introduce a method `getXMLEventFactory` similar to `getXMLInputFactory` (below for reference) and use it instead. 
https://github.com/keycloak/keycloak/blob/9b43e62f2b6279ba0da9cedcf4b790ccd9b5edaa/saml-core/src/main/java/org/keycloak/saml/common/util/StaxParserUtil.java#L905-L933

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java [hunk 16]
```diff
@@ -141,4 +143,27 @@ public static String parseAnyTypeAsString(XMLEventReader xmlEventReader) throws
...
+                writer.add(xmlEventFactory.createNamespace(startElement.getName().getPrefix(), startElement.getName().getNamespaceURI()));
+                return startElement.getName().getPrefix();
```
Comment (hmlnarik) [inline saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java:164]: FTR: I agree that we need not consider extreme cases where the same prefix would (per context) map to two different namespaces like in here:
```xml
<a:a xmlns:a="uri:1">
   <a:b xmlns:a="uri:2"/>
</a:a>
```
Still I'm wondering whether to cover this case:
```xml
<a xmlns="uri:1">
  <b xmlns="uri:2"/>
</a>
```
But I guess we can leave this only if the need arises too.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thanks for the PR! The overall direction looks good. I left a few comments inline, could you please have a look?

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 13 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:280]: @hmlnarik - I assume that you're referring to the following logic in the Keycloak model to map attributes to fields, like for example here: https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java#L161-L183

With this approach, the cases for EMAIL, FIRST_NAME, and LAST_NAME can be removed, and only the else-branch is necessary. I gave it a try with the new SAML test cases, and it works as expected. 

At the same time [BrokeredIdentityContext](https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/broker/provider/BrokeredIdentityContext.java) doesn't implement this logic, and for example the email stored in an attribute might be hidden from those calling getEmail().

WDYT?

**Comment by KnauerSecunet** [comment]
> Thanks for the PR! The overall direction looks good. I left a few comments inline, could you please have a look?

All comments make sense. @hmlnarik Could please answer ahus1 [open question](https://github.com/keycloak/keycloak/pull/10650#discussion_r873397233) whether attributes can be used / whether that was your intention?

Once that is done I can implement all changes / answer the namespace questions ... I think sometime next week

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 13 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java:280]: > I assume that you're referring to the following logic in the Keycloak model to map attributes to fields, like for example here: https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java#L161-L183
>
> At the same time [BrokeredIdentityContext](https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/broker/provider/BrokeredIdentityContext.java) doesn't implement this logic, and for example the email stored in an attribute might be hidden from those calling getEmail().

You are correct, `BrokeredIdentityContext` has been forgotten in the #7080 PR. Thank you for checking this. Let's keep it as is for now, and address it in the newly introduced #12307.

**Comment by KnauerSecunet** [comment]
I will continue working on the issue around June 20th ...

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 10 above)
Comment (KnauerSecunet) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: I think its correct to only call `setUserAttribute` when I find a value / the list is not empty

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 11 above)
Comment (KnauerSecunet) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: I now reuse the XPathFactory but I don't think its possible to use a XPathVariableResolver: It would be used to replace parameters in the expression (e.g. $bookId) with a value (e.g. bk102) that will be fully escaped. But in our case we are supplying the whole expression not just the parameters and the expression must not be escaped. Furthermore the injection is only possible with the expression (not the saml attributes) thus only admins could carry out the attack.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 13 above)
Comment (KnauerSecunet) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: If I understood you correctly I should nevertheless change it already in my code? I replaced it including the else path (@ahus1) with a call to `setUserAttribute` which should be working as expected as far as I understand the code. Let me know if that was wrong / is not the desired change. I also had to change the unittest ... so this changed some behaviour.

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java (hunk 14 above)
Comment (KnauerSecunet) [reply saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java]: Namespaces for attributes was not implemented correctly. I fixed it and now all necessary namespaces are added and your example is working. I added a test for it as well.

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java (hunk 16 above)
Comment (KnauerSecunet) [reply saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java]: I agree different namespaces with the same prefixes don't make sense. Missing prefixes are working (and are tested now).

**Comment by KnauerSecunet** [comment]
> My changes are available here: [KnauerSecunet#9](https://github.com/KnauerSecunet/keycloak/pull/9) ... please review them, merge them, and squash them with your changes. Then this PR is good to be merged from my perspective.

[Your changes](https://github.com/KnauerSecunet/keycloak/pull/9) and @hmlnarik comments are now included in my pull request. I either resolved the comment above or added some reasoning for my change.

I made a separate branch in my clone [keycloak_pull_10650](https://github.com/KnauerSecunet/keycloak/tree/keycloak_pull_10650) which contains a commit [71244a61](https://github.com/keycloak/keycloak/commit/71244a617ef2e7ca6f00047f45b7ef7bb3d91f4c) for my recent changes only.

**Comment by hmlnarik** [comment]
@KnauerSecunet Thank you for updates. Could you please rebase the PR?

**Comment by KnauerSecunet** [comment]
> @KnauerSecunet Thank you for updates. Could you please rebase the PR?

@hmlnarik Rebased on current main

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 10 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: That's right, and it it is on par with existing code (which alas contains still the specific methods for email / first name / lastname) https://github.com/keycloak/keycloak/blob/7e925bfbff5410d27675f10d596b752fa794a4ab/services/src/main/java/org/keycloak/broker/saml/mappers/UserAttributeMapper.java#L145-L155

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 13 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: > If I understood you correctly I should nevertheless change it already in my code?

Yes, that's correct, thank you.

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 11 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: I agree with the reasoning and with the attack surface being small. Still, Keycloak as a security product prefers reducing attack surface and this change is tiny. Could you please introduce a (singleton)
```java
    private static XPathVariableResolver XPATH_VARIABLE_RESOLVER = new XPathVariableResolver() {
        @Override
        Object resolveVariable(QName variableName) { 
            return null;
        }
    }
```
and set it to all newly created `XPath` objects?

**Review by hmlnarik — COMMENTED** [review]
@KnauerSecunet Thank you for the work, this is very nice piece of code! Once you address the one last comment regarding XPath, this PR is ready for merging.

File: saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java (hunk 14 above)
Comment (hmlnarik) [reply saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java]: Perfect!

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 11 above)
Comment (KnauerSecunet) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: I added a XPathVariableResolver and XPathFunctionResolver in ddd7575 that throw exceptions whenever they are called (including an unit-test). Which is basically the same behaviour as returning null.

But what I wanted to say: Even before the change it would not have been possible to exploit an xpath injection because we don't concat user parameters to the xpath expression. Moreover it was not possible to replace a variable (or function) because no values are given. What's better now: Maybe (!) a bug will be discovered for the default resolvers that can no longer be exploited.

**Comment by KnauerSecunet** [comment]
@hmlnarik Done and rebased on current main

File: services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java (hunk 11 above)
Comment (hmlnarik) [reply services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java]: Thank you for the update! It is exactly about this replacement of default resolvers that makes it safer. XML processing is well known for surprising vulnerabilities, and the aim is not to allow even a malicious realm admin (ie. not a system admin) to reveal deployment details available say via system properties (e.g. `java.version`) or calling a XPath function even if such a vulnerability would be found in XPath processing implementation.

**Review by hmlnarik — APPROVED** [review]
Approved on the condition that the tests pass

**Comment by svenhartmann** [comment]
@ahus1 @hmlnarik  Is there a expected date when the XPathAttributeMapper will be available in a release?

**Comment by ahus1** [comment]
@svenhartmann - it will be part of Keycloak 20. You can watch the progress on KC20 by looking at the milestone https://github.com/keycloak/keycloak/milestone/22 ... the last open issues are actively being worked on, at the same time it will be released when it is ready.

To give this feature a try, please use the Keycloak nightly builds. Given the small number of open issue for the milestone it should be quite close.
