### PR TITLE
Exposing user profile metadata from the User Profile API

### LINKED ISSUE #23434: Can not view or update user profile attribute in user details
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Since upgrading to KC 22.0.3 I am not able to see the user profile attribute values on the user details page even though they are returned by the API: 

image

image

When I try to update the value this is not updated in the request payload and the old value is send again:
image
image

Looks like this is a Frontend issue. The mapping between the form and the model seem to be broken.

### Version

22.0.3

### Expected behavior

Form for user profile attributes is filled with old values on opening the user details screen.
When updating user profile attributes and pressing the save button the updated values are send.

### Actual behavior

Form for user profile attributes is **NOT** filled with old values on opening the user details screen. Its just empty.
When updating user profile attributes and pressing the save button the updated values are **NOT** send. Instead the old ones are send.

### How to Reproduce?

1. Enable user profile feature, add a custom user profile attribute: e.g. birthdate - validator not necessary. Do not set it to required as otherwise you are at the moment not able to create a user (there is a separate story for that one).
2. Create a user
3. On the details screen of the user update the birthdate and press save.
4. Reload the page: The birthdate is empty.

### Anything else?

_No response_

### LINKED ISSUE #23507: User cannot be created via Admin UI if custom user attribute is required
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When having the user-profile feature enabled and having a custom user attribute marked as required, admin cannot create user via the Admin UI because the attribute is not displayed in the user creation screen, therefore cannot be provided. The field is only shown when editing user and can be set there (have to make the attribute optional)...

### Version

nightly

### Expected behavior

Admin is able to create user via Admin UI when having custom user attributes marked as required.

### Actual behavior

Admin is not able to create user via Admin UI when having custom user attributes marked as required.

### How to Reproduce?

- Enable the user-profile and add new custom user attribute (for e.g locale) and mark it as required
- Try to create user as an admin

### Anything else?

For implementing this a new endpoint for accessing the user profile metadata would become necessary, as the user details API can not be used. It would make sense to afterwards also use that API on the user details screen and decommission the old way.

On the create user screen no inputs for user profile attributes are rendered - if one is required the user can not be created of course. The issue seems to be that for the UserForm to render the UserProfileFields also a user has to be present at the moment:
https://github.com/keycloak/keycloak/blob/d8ff73e34f4cbaae18b9926a42d22a0aeda74854/js/apps/admin-ui/src/user/UserForm.tsx#L226-L228
The user is undefined in case of create user.

imho this is a general flaw of the user screens gathering the user profile metadata through the user details api. Instead maybe a dedicated endpoint in the ui-ext extension should be added, allowing for users with view-users or manage-users permissions to gather the user profile metadata for admin ui (create and edit user - no user entity necessary). When this would be refactored, it could also be addressed, that there is a [discrepancy between what the frontend thinks it gets and what the backend actually returns](https://github.com/keycloak/keycloak/issues/23443) for user profile metadata, resulting in user profile attribute validators to not work in the admin ui.

Afterwards the additional parameter and response data can be removed from the users api ...

### LINKED ISSUE #23584: Return attribute group metadata from Admin and Account APIs
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

Attribute group metadata is not returned from the Admin and Account APIs when fetching user profile metadata.

We need this information in order to allow their corresponding UIs to properly render attributes when they are associated with a group.

The behavior should be similar to what we have today when rendering the registration, update, and very profile pages.

### Version

22.0.3

### Expected behavior

Attribute group metadata is returned from the Admin and Account APIs when fetching user profile metadata.

### Actual behavior

Attribute group metadata is not returned from the Admin and Account APIs when fetching user profile metadata.

### How to Reproduce?

* Create a realm
* Enable user profile
* Create an attribute group
* Associate any attribute with the newly created group
* Query the User API or Account Rest API and see the group metadata is not there.

### Anything else?

This is basically about exposing the `org.keycloak.userprofile.AttributeGroupMetadata` from the `org.keycloak.userprofile.AttributeMetadata`.

### LINKED ISSUE #23740: Admin Console doesn't show user when user attribute has annotation inputType
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When user profile is activated and an attribute has annotation with key "inputType" (e.g. inputType=select) then the user view just shows error message "undefined has no properties".

image

### Version

22.0.4

### Expected behavior

User view is rendered

### Actual behavior

Error is shown
Browser console shows at [react-dom.production.min.js:189:29](http://localhost:8080/resources/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.production.min.js)

`TypeError: undefined has no properties
    D SelectComponent.tsx:16
    React 9
    Ot EditUser.tsx:121
    useFetch useFetch.ts:33
    promise callback*useFetch/< useFetch.ts:31
    React 6
    Xr EditUser.tsx:81
    useFetch useFetch.ts:33
    promise callback*useFetch/< useFetch.ts:31
    React 3
    ct scheduler.production.min.js:13
    At scheduler.production.min.js:14
    EventHandlerNonNull* scheduler.production.min.js:14
    <anonymous> scheduler.production.min.js:19
react-dom.production.min.js:189:29
    React 12
    Ot EditUser.tsx:121
    useFetch useFetch.ts:33
    (Async: promise callback)
    useFetch useFetch.ts:31
    React 6
    Xr EditUser.tsx:81
    useFetch useFetch.ts:33
    (Async: promise callback)
    useFetch useFetch.ts:31
    React 3
    ct scheduler.production.min.js:13
    At scheduler.production.min.js:14
    (Async: EventHandlerNonNull)
    <anonymous> scheduler.production.min.js:14
    <anonymous> scheduler.production.min.js:19
`

### How to Reproduce?

- Activate user profile
- Create a new attribute and set it as viewable and writable for Admin
- Add annotation inputType=select
- Open a user (e.g. admin)

### Anything else?

Could reproduce with 22.0.4 but not with latest nightly release.

### LINKED ISSUE #23774: User can't be updated in admin console when user profile is used
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When user profile is enabled and an attribute defined which is visible for the Admin, isn't updated when save is clicked.

### Version

22.0.4 and nightly

### Expected behavior

The user can be updated e.g. name, firstname or the value of the declared attribute can be changed and saved.

### Actual behavior

Error in browser JS console
`
Uncaught (in promise) TypeError: e.responseData is undefined
    ea UserProfileFields.tsx:29
    z EditUser.tsx:132
    re index.esm.mjs:2147
    React 16
    <anonymous> main.tsx:20
`

### How to Reproduce?

- Activate user profile
- Create a new attribute and set it as viewable for Admin
- Open a user (e.g. admin)
- Enter a Last Name.
- Click Save

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #23507
Closes #23584
Closes #23740
Closes #23774
Closes #23434

### CODE REVIEW

**Review by edewit — DISMISSED** [review]

File: js/apps/admin-ui/src/user/CreateUser.tsx [hunk 1]
```diff
@@ -66,15 +94,15 @@ export default function CreateUser() {
       />
       <PageSection variant="light" className="pf-u-p-0">
         <UserProfileProvider>
```
Comment (edewit) [inline js/apps/admin-ui/src/user/CreateUser.tsx:96]: guess we don't need this `UserProfileProvider` here anymore

File: js/apps/admin-ui/src/user/CreateUser.tsx [hunk 2]
```diff
@@ -66,15 +94,15 @@ export default function CreateUser() {
...
-              <UserForm
-                realm={realmRepresentation}
-                onGroupsUpdate={setAddedGroups}
-                save={save}
-              />
-            </PageSection>
-          </FormProvider>
+          <PageSection variant="light">
+            <UserForm
+              form={form}
```
Comment (edewit) [inline js/apps/admin-ui/src/user/CreateUser.tsx:99]: Why did you pass in the form instead?

File: js/apps/admin-ui/src/user/EditUser.tsx [hunk 3]
```diff
@@ -87,35 +87,35 @@ export default function EditUser() {
...
+    async () =>
+      Promise.all([
+        adminClient.realms.findOne({ realm: realmName }),
         adminClient.users.findOne({ id: id!, userProfileMetadata: true }),
-        adminClient.realms.findOne({ realm }),
         adminClient.attackDetection.findOne({ id: id! }),
-      ]);
-
-      if (!user || !currentRealm || !attackDetection) {
+        adminClient.users.getProfileMetadata({ realm: realmName }),
```
Comment (edewit) [inline js/apps/admin-ui/src/user/EditUser.tsx:95]: For edit user we don't need to query this as it's already on the use object

File: js/apps/admin-ui/src/user/EditUser.tsx [hunk 4]
```diff
@@ -203,14 +203,17 @@ export default function EditUser() {
...
+            enabled: value,
+          })
         }
         isEnabled={user.enabled}
       />
 
       <PageSection variant="light" className="pf-u-p-0">
         <UserProfileProvider>
-          <FormProvider {...userForm}>
+          <FormProvider {...form}>
```
Comment (edewit) [inline js/apps/admin-ui/src/user/EditUser.tsx:216]: Either we use the form as a parameter or we pass it in as an argument, here you do both. IMO using the `FormProvider` is a bit nicer

**Review by edewit — CHANGES_REQUESTED** [review]

File: js/apps/admin-ui/src/user/CreateUser.tsx (hunk 2 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/CreateUser.tsx:99]: Type safety, this way we can be sure that the form we are dealing with is in fact provided and of the correct type.

File: js/apps/admin-ui/src/user/CreateUser.tsx (hunk 1 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/CreateUser.tsx:96]: Yeah, good catch. I'll remove it.

File: js/apps/admin-ui/src/user/EditUser.tsx (hunk 3 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/EditUser.tsx:95]: Would that contain the exact same data? @pedroigor

Comment (jonkoops) [reply js/apps/admin-ui/src/user/EditUser.tsx:95]: I'll add a commit for this now, let me know if this is wrong and I will revert it.

Comment (pedroigor) [reply js/apps/admin-ui/src/user/EditUser.tsx:95]: @jonkoops The metadata is the same.

File: js/apps/admin-ui/src/user/EditUser.tsx (hunk 4 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/EditUser.tsx:216]: > Either we use the form as a parameter or we pass it in as an argument

Agreed, but I did not want to refactor all the forms under this provider in this PR as that would create significantly more code to review.

 > IMO using the `FormProvider` is a bit nicer

I agree with you from a convenience perspective, it is a lot less verbose to use a context. However I disagree from a type-safety and maintenance perspective. The reason for that is when you use a context the form and it's value becomes loosely coupled from the form controls.

For example, I can do the following that is perfectly valid:


```tsx
type ParentForm = {
  attributes: Record<string, string[]>;
}

const ParentWithForm =  () => {
  const form = useForm();
  return <FormProvider {...form}><ChildWithContext /></FormProvider>
}


type ChildForm = {
  attributes: { key: string; value: string; }[];
}

const ChildWithContext =  {
  const form = useFormContext();
  // This will not give an error, even thought it is wrong.
  // The parent form is expecting a different type.
  form.setValue("attributes", [{ key: "foo", value: "bar" }]);
}
```

If we pass the form down as a strongly typed prop instead, then it will suddenly not be possible to assign it to anything but the type that was specified at the root. Also it will prevent possible nested `FormProvider`s, which can cause conflicts with each other.

So yeah, it  is more cumbersome, but it is also more maintainable long term, and I think that is more important than the DX in the shot term.

File: js/apps/admin-ui/src/user/CreateUser.tsx (hunk 1 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/CreateUser.tsx]: Done

File: js/apps/admin-ui/src/user/EditUser.tsx (hunk 3 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/EditUser.tsx]: Ok, I've changed this to use the data from the user instead :+1:

File: js/apps/admin-ui/src/user/CreateUser.tsx [hunk 5]
```diff
@@ -58,24 +81,26 @@ export default function CreateUser() {
...
-            <PageSection variant="light">
-              <UserForm
-                realm={realmRepresentation}
-                onGroupsUpdate={setAddedGroups}
-                save={save}
-              />
-            </PageSection>
-          </FormProvider>
-        </UserProfileProvider>
+        <PageSection variant="light">
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/CreateUser.tsx:95]: Just noticed we have a nested `PageSection` here, I wonder if we really need it.

**Review by edewit — DISMISSED** [review]

File: js/apps/admin-ui/src/user/EditUser.tsx (hunk 4 above)
Comment (edewit) [reply js/apps/admin-ui/src/user/EditUser.tsx:215]: that's why you should use `useFormContext<ParentForm>();`, but yes you can remove the types, but that is true everywhere because in the end there are no types.

**Comment by jonkoops** [comment]
I am converting this to a draft as we still have a couple of issues that need to be resolved:
- If email as username is disabled it's not possible to create a user.
- If a field is readOnly it should be hidden during create.
- When creating a user with a custom attribute, it is not displayed in the form.

**Comment by pedroigor** [comment]
> * If email as username is disabled it's not possible to create a user.

OK

> * If a field is readOnly it should be hidden during create.

OK

> * When creating a user with a custom attribute, it is not displayed in the form.

OK

Still missing:

* Properly handle the required marker in the UI when the attribute is required
* Allow setting multiple values to a field

File: js/apps/admin-ui/src/user/EditUser.tsx (hunk 4 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/EditUser.tsx:215]: This has been resolved as we now pass the form in as a typed prop everywhere for User Profile.

**Comment by jonkoops** [comment]
> Properly handle the required marker in the UI when the attribute is required

Fixed in 6e24dbfc4ac4d5dc7b70623c754f0c126a531494

> Allow setting multiple values to a field

Fixed in b21381b48190797628b47c7652c6c9afd71111ca

File: js/apps/admin-ui/src/user/CreateUser.tsx (hunk 5 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/CreateUser.tsx]: This was redundant, so I've removed it.

File: js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts [hunk 6]
```diff
@@ -10,7 +10,7 @@ export interface UserProfileAttribute {
   validations?: Record<string, unknown>;
   validators?: Record<string, unknown>;
   annotations?: Record<string, unknown>;
-  required?: UserProfileAttributeRequired;
+  required?: boolean | UserProfileAttributeRequired;
```
Comment (jonkoops) [inline js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts:13]: @pedroigor could tell me whether the `UserProfileAttributeRequired` type is ever returned anywhere in the REST API? I get the feeling we made a mistake here, and this is actually always a boolean.

**Review by jonkoops — DISMISSED** [review]

File: js/apps/admin-ui/src/user/EditUser.tsx (hunk 4 above)
Comment (edewit) [reply js/apps/admin-ui/src/user/EditUser.tsx:215]: If that is the case why do you still have this `<FormProvider>` tag here

File: js/apps/admin-ui/src/user/UserAttributes.tsx [hunk 7]
```diff
@@ -16,13 +19,13 @@ export const UserAttributes = ({ user, save }: UserAttributesProps) => {
   return (
     <PageSection variant={PageSectionVariants.light}>
       <AttributesForm
-        form={form}
+        form={form as UseFormReturn<AttributeForm>}
```
Comment (edewit) [inline js/apps/admin-ui/src/user/UserAttributes.tsx:22]: this isn't very typesafe

**Review by edewit — DISMISSED** [review]

File: js/apps/admin-ui/src/user/UserAttributes.tsx (hunk 7 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/UserAttributes.tsx:22]: True, if you have a suggestion on how to handle this better let me know.

File: js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts (hunk 6 above)
Comment (pedroigor) [reply js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts:13]: You're right, it is a boolean.

It is probably there because the interface was generated from a user profile configuration. The type exists on the server side to represent the configuration for mandatory/optional attributes and it is not exposed when querying the metadata. What you get is a calculated value based (true|false) at the end.

Comment (jonkoops) [reply js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts]: Peered up with Pedro to fix the types here, so we are good to go on this front.

File: js/apps/admin-ui/src/user/EditUser.tsx (hunk 4 above)
Comment (jonkoops) [reply js/apps/admin-ui/src/user/EditUser.tsx:215]: Ah yes, my bad. I meant for the user profile fields. Doing all the other fields for the user would be a massive refactor that I don't want to get into right now.

File: js/apps/admin-ui/src/user/utils/user-profile.ts [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+    return false;
+  }
+
+  // If the 'required' is a boolean, we can use it directly.
+  if (typeof required === "boolean") {
+    // Check if required is true or if the validators include a validation that would make the attribute implicitly required.
+    return required || hasRequiredValidators(validators);
+  }
+
+  // If the 'required' attribute is not a boolean, it will be an object with required roles and scopes.
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/utils/user-profile.ts:18]: TODO This can now be removed.

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
@antikalk @jbman if you have the time to do so, please test the code in this PR and let us know if you are still experiencing issues.

**Review by edewit — APPROVED** [review]

**Review by agagancarczyk — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]
I reviewed the java part of this and it looks good.  Personally, I wouldn't have moved the `getAttributeMetadata()` method from a test class to a production class.  But it's not a blocker for me.  Approved.

**Review by mposolda — APPROVED** [review]

**Comment by antikalk** [comment]
> @antikalk @jbman if you have the time to do so, please test the code in this PR and let us know if you are still experiencing issues.

@jonkoops Just tried the main branch and it now looks good to me. I am able to create a user with required user profile attributes, they are also rendered on the user details and I am able to update them. Many thanks to the whole Keycloak team for working on those fixes! :)

**Comment by jonkoops** [comment]
Awesome, thanks so much for the sanity check!
