### PR TITLE
Better handling for SAML signatures in POST and REDIRECT bindings

### LINKED ISSUE #17456: Bug in SAML Redirect Binding with 2 validating certificates
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

saml

### Describe the bug

If I configure a SAML-IdentityProvider under Menu -> IdentityProvider and use 2 "Validating X509 Certificates" separated with comma (",") and use Redirect-Binding for IDP Responses I get an error:
Caused by: org.keycloak.common.VerificationException: Invalid key locator for signature verification
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:183)

So we have two certificates with MIIH1DCCBbygAwIBAgITbQASIUmhHRspDof1LAACABI...,MIIHxjCCBa6gAwIBAgITbQAU15owiFXb0lHXUgACABTXmj... 
Note the comma in the middle. This is possible to support signing certificate change of the IDP.
So the assumption is that both certificates are checked for signature validation. This works in the case of POST-Binding, but not in the case of REDIRECT-Binding.
I inspected the code in this area and I found the bug in this case. The verify signature method is a different implementation in case of POST-Binding and Redirect-Binding.
Redirect-Binding uses this Method:
org/keycloak/protocol/saml/SamlProtocolUtils.java:178
There is org.keycloak.rotation.HardcodedKeyLocator#getKey Method used, which implements this method:

public Key getKey(String kid) {
    if (this.keys.size() == 1) {
        return this.keys.iterator().next();
    } else {
        return null;
    }
}

So only in the case we have only one key the implementation works. In the case we have two separated keys it won't work.
The correct implementation is to iterate over the HardcodedKeyLocator like it does the POST-Binding Implementation in this area:
org/keycloak/saml/processing/core/util/XMLSignatureUtil.java:498

### Version

21.0.1

### Expected behavior

No Exception when using 2 certifiactes

### Actual behavior

If I configure a SAML-IdentityProvider under Menu -> IdentityProvider and use 2 "Validating X509 Certificates" separated with comma (",") and use Redirect-Binding for IDP Responses I get an error:
Caused by: org.keycloak.common.VerificationException: Invalid key locator for signature verification
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:183)

### How to Reproduce?

If I configure a SAML-IdentityProvider under Menu -> IdentityProvider and use 2 "Validating X509 Certificates" separated with comma (",") and use Redirect-Binding for IDP Responses I get an error:
Caused by: org.keycloak.common.VerificationException: Invalid key locator for signature verification
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:183)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/17456

Two main changes in the PR:

* The code to test all the keys in the locator for REDIRECT binding was moved from the adapter sub-project to the core-saml one. This way the same code is reused by adapters and broker. Previously broker didn't iterate at all.
* I have extended the `KeyLocator` interface to also look for keys directly using the KeyInfo. The KeyInfo can have the key name, the X509Certificate or the Key itself, so in POST binding is always better to check if the locator has that specific key (not only check by name). Trying to verify the signature with all the keys is just the last chance.

For the second point I have modified the `KeyLocator` to extends `Iterable<Key>`. It's a change in the API but REDIRECT binding does not send any KeyInfo by spec so it's compulsory to test with all the keys. Only if keycloak is used as the server a special indication to locate the key via name is added in the SAML response.

### CODE REVIEW

**Comment by rmartinc** [comment]
@pedroigor Can you please take a look to this? Thanks!

**Review by pedroigor — APPROVED** [review]

File: saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java [hunk 1]
```diff
@@ -494,20 +490,16 @@ public static boolean validateSingleNode(Node signatureNode, final KeyLocator lo
...
-                try {
-                    if (validateUsingKeySelector(signatureNode, new KeySelectorPresetKey(key))) {
-                        return true;
-                    }
-                } catch (XMLSignatureException ex) { // pass through MarshalException
-                    logger.debug("Verification failed: " + ex);
-                    logger.trace(ex);
+        for (Key key : locator) {
+            try {
+                if (validateUsingKeySelector(signatureNode, new KeySelectorPresetKey(key))) {
```
Comment (pedroigor) [inline saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java:497]: Not a blocker but do we need `KeySelectorPresetKey` or we can just use `javax.xml.crypto.KeySelector#singletonKeySelector`?

**Review by pedroigor — DISMISSED** [review]

File: saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java (hunk 1 above)
Comment (rmartinc) [reply saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java:497]: No, not needed I think, I just used the same code that was before. The `KeySelectorPresetKey` is the same than the `KeySelector.singletonKeySelector`. Let me replace it.

Comment (rmartinc) [reply saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java]: Done!

**Review by pedroigor — APPROVED** [review]
