### PR TITLE
Generate translations for locales via built-in Java functionality

### LINKED ISSUE #28201: Locale label missing on login page for Brazilian Portuguese, Greek and Persian
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

In `themes/src/main/resources/theme/base/login/messages/messages_en.properties` the messages for el, fa and pt-BR do not show up.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The language picker shows the name of the language.
(Like in the admin panel)

### Actual behavior

The language picker shows the language code.
grafik

### How to Reproduce?

1. Create new realm
2. Enable internationalization
3. Select Greek, Brazilian Portuguese and Persion

### Anything else?

_No response_

### LINKED ISSUE #29124: Use Java locale translations instead of manually edited translations
### Description

Leverage Java's language names to display them in the front end.

### Discussion

https://github.com/keycloak/keycloak/pull/29103

### Motivation

Remove the need for manual translations, while allowing to override them where necessary.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #29124
Closes #28201

### CODE REVIEW

**Comment by MoeidHeidari** [comment]
dfsxgdfg

File: js/apps/admin-ui/src/util.ts [hunk 1]
```diff
@@ -173,7 +173,7 @@ export const generateId = () => Math.floor(Math.random() * 1000);
 export const localeToDisplayName = (locale: string, displayLocale: string) => {
   try {
     return new Intl.DisplayNames([displayLocale], { type: "language" }).of(
-      locale,
+      locale === "zh-CN" ? "zh-HANS" : locale === "zh-TW" ? "zh-HANT" : locale,
```
Comment (jonkoops) [inline js/apps/admin-ui/src/util.ts:176]: Perhaps we could add a comment here with some explainer why this is needed for future reference.

File: js/libs/ui-shared/src/user-profile/LocaleSelector.tsx [hunk 2]
```diff
@@ -20,9 +20,10 @@ export const LocaleSelector = ({
   supportedLocales,
 }: LocaleSelectorProps) => {
   const locales = supportedLocales.map((locale) => ({
-    key: locale,
-    value: localeToDisplayName(locale) || "",
-  }));
+      key: locale,
+      value: t("locale_" + locale, localeToDisplayName(locale) || locale),
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/LocaleSelector.tsx:24]: We can use some more modern JS syntax here.
```suggestion
      value: t(`locale_ ${locale}`, localeToDisplayName(locale) ?? locale),
```

File: js/libs/ui-shared/src/user-profile/LocaleSelector.tsx [hunk 3]
```diff
@@ -20,9 +20,10 @@ export const LocaleSelector = ({
...
+    }))
+    .sort((a, b) => a.value.localeCompare(b.value));
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/LocaleSelector.tsx:26]: Since this all depends on the locale configured by the user we have a special hook called [`useLocaleSort()`](https://github.com/keycloak/keycloak/blob/02e2ebf25829508945be6d5be12630935903d031/js/apps/admin-ui/src/utils/useLocaleSort.ts) that should be used instead.

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java [hunk 4]
```diff
@@ -276,6 +277,32 @@ private Map<Locale, Properties> getMessagesByLocale(String baseBundlename, Local
...
+                l = l.trim();
+                String key = "locale_" + l;
+                String label = m.getProperty(key);
+                if (label == null) {
+                    String rl = l;
+                    if (l.equals("zh-CN")) {
+                        rl = "zh-HANS";
+                    } else if (l.equals("zh-TW")) {
+                        rl = "zh-HANT";
+                    }
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:291]: Let's also add a comment here explaining why this is needed, as well as perhaps logging an issue to remove this in the future.

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java [hunk 5]
```diff
@@ -276,6 +277,32 @@ private Map<Locale, Properties> getMessagesByLocale(String baseBundlename, Local
...
+                    if (!Objects.equals(loc, locale)) {
+                        label += " (" + capitalize(loc.getDisplayName(loc), loc) + ")";
+                    }
+                    m.put(key, label);
+                }
+            }
+        }
+
+        private String capitalize(String name, Locale locale) {
+            return name.substring(0, 1).toUpperCase(locale) + name.substring(1);
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:303]: Not sure if this logic is sound when dealing with different locales, e.g. left-to-right languages, or languages that have Han characters like Kanji.

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java [hunk 6]
```diff
@@ -276,6 +277,32 @@ private Map<Locale, Properties> getMessagesByLocale(String baseBundlename, Local
...
+                    String rl = l;
+                    if (l.equals("zh-CN")) {
+                        rl = "zh-HANS";
+                    } else if (l.equals("zh-TW")) {
+                        rl = "zh-HANT";
+                    }
+                    Locale loc = Locale.forLanguageTag(rl);
+                    label = capitalize(loc.getDisplayName(locale), locale);
+                    if (!Objects.equals(loc, locale)) {
+                        label += " (" + capitalize(loc.getDisplayName(loc), loc) + ")";
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:295]: This kind of source order also seems something that could be very locale dependent. E.g. in Arabic you might want to reverse the order here. Perhaps we should add a label for the format of this? E.g. `locale_choice={0} ({1})`.

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java [hunk 7]
```diff
@@ -276,6 +277,32 @@ private Map<Locale, Properties> getMessagesByLocale(String baseBundlename, Local
             }
         }
 
+        protected void addlocaleTranslations(Locale locale, Properties m) throws IOException {
+            for (String l : getProperties().getProperty("locales", "").split(",")) {
+                l = l.trim();
+                String key = "locale_" + l;
+                String label = m.getProperty(key);
+                if (label == null) {
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:285]: Alternatively this could be inversed to reduce nesting, but more of a code-style thing:

```java
if (label != null) {
  continue;
}
```

File: themes/src/main/resources/theme/base/account/messages/messages_en.properties
Comment (jonkoops) [inline themes/src/main/resources/theme/base/account/messages/messages_en.properties:1]: If we are removing all `locale_` entries from the English locale, this can likely be done for the other languages as well. Or are you counting on Weblate to make a PR after this is merged to fix this up?

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Comment by jonkoops** [comment]
Looks really nice @ahus1!

File: js/apps/admin-ui/src/util.ts (hunk 1 above)
Comment (ahus1) [reply js/apps/admin-ui/src/util.ts:176]: will be part of next commit

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 4 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:291]: will be part of next commit

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 6 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:295]: Even in RTL languages, isn't the string just printed RTL? For now, I'd like to keep it as is, as it is an improvement to the current way IMHO

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 7 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:285]: part of next commit

File: js/libs/ui-shared/src/user-profile/LocaleSelector.tsx (hunk 3 above)
Comment (ahus1) [reply js/libs/ui-shared/src/user-profile/LocaleSelector.tsx:26]: The hook is in the admin-ui, while this LocaleSelector is in the ui-shared. I assume it needs to be moved first, which seems to be out of reach for my JavaScript skills. Could this be part of a follow-up issue?

File: themes/src/main/resources/theme/base/account/messages/messages_en.properties
Comment (ahus1) [reply themes/src/main/resources/theme/base/account/messages/messages_en.properties:1]: I was thinking that Weblate would clean them up. But as we don't have all the translations in there, the latest commit removes them.

**Comment by ahus1** [comment]
@jonkoops - please re-review my latest changes. 

I see some unstable tests reported here which I want to take a look at in the upcoming days.

File: js/libs/ui-shared/src/user-profile/LocaleSelector.tsx (hunk 3 above)
Comment (jonkoops) [reply js/libs/ui-shared/src/user-profile/LocaleSelector.tsx:26]: This actually seems like something that makes sense to put in `ui-shared`, let me whip up a PR to do that for you.

Comment (jonkoops) [reply js/libs/ui-shared/src/user-profile/LocaleSelector.tsx:26]: Hmm. On closer inspection, this will mean moving the `WhoAmI` context as well, which brings in a lot more work, let's save that for another time. What we can do is pass the current locale into `LocaleSelector` as a prop, that should be manageable.

Comment (jonkoops) [reply js/libs/ui-shared/src/user-profile/LocaleSelector.tsx]: This has been resolved in 7802ed3f153c10e8d973a128ed48aa8bd2218bdb

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 6 above)
Comment (jonkoops) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java]: Ok, let's file this as a possible enhancement as I don't want to hold up what is already a good improvement, let's log a follow up issue for this.

@Eng-Fouad @sharifrezvani since you maintain some of the RTL languages, I'd like to know what you think about this.

File: js/libs/ui-shared/src/user-profile/LocaleSelector.tsx [hunk 8]
```diff
@@ -12,17 +12,21 @@ const localeToDisplayName = (locale: string) => {
...
-  const locales = supportedLocales.map((locale) => ({
-    key: locale,
-    value: localeToDisplayName(locale) || "",
-  }));
+  const locales = supportedLocales
+    .map((locale) => ({
+      key: locale,
+      value: t(`locale_${locale}`, localeToDisplayName(locale) ?? locale),
+    }))
+    .sort((a, b) => a.value.localeCompare(b.value, currentLocale));
```
Comment (jonkoops) [inline js/libs/ui-shared/src/user-profile/LocaleSelector.tsx:29]: I am thinking, since this is likely an expensive operation to do on each render, we might want to memoize this.
```suggestion
  const locales = useMemo(
    () =>
      supportedLocales
        .map((locale) => ({
          key: locale,
          value: t(`locale_${locale}`, localeToDisplayName(locale) ?? locale),
        }))
        .sort((a, b) => a.value.localeCompare(b.value, currentLocale)),
    [supportedLocales, currentLocale, t],
  );

```

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java [hunk 9]
```diff
@@ -276,6 +280,53 @@ private Map<Locale, Properties> getMessagesByLocale(String baseBundlename, Local
...
+                p = Pattern.compile("(\\p{L1}|\\p{InLATIN_EXTENDED_A}|\\p{InLATIN_EXTENDED_B}|\\p{InLATIN_EXTENDED_C}|\\p{InLATIN_EXTENDED_D}|\\p{InLATIN_EXTENDED_E}).*");
+            } catch (PatternSyntaxException ex) {
+                log.warn("unable to create regex for latin characters", ex);
+                // just in case the JVM doesn't recognize the language patterns used above
+                p = Pattern.compile("[a-zA-Z]");
+            }
+            LATIN_CHARACTERS = p;
+        }
+
+        private String capitalize(String name, Locale locale) {
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:322]: I was thinking, we already include Apache Commons right? It seems that it offers a [`StringUtils.capitalize()`](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#capitalize-java.lang.String-), is that something that could be used here? Note that I am not sure if it handles the edge cases correctly that were handling here.

File: themes/src/main/resources-community/theme/base/account/theme.properties [hunk 10]
```diff
@@ -1 +1 @@
-locales=ar,ca,cs,da,de,el,en,es,fa,fr,fi,hu,it,ja,lt,nl,no,pl,pt,pt-BR,ru,sk,sv,th,tr,uk,zh-CN,zh-TW
+locales=ar,ca,cs,da,de,el,en,es,fa,fr,fi,hu,it,ja,lt,lv,nl,no,pl,pt,pt-BR,ru,sk,sv,th,tr,uk,zh-CN,zh-TW
```
Comment (jonkoops) [inline themes/src/main/resources-community/theme/base/account/theme.properties:1]: Interesting, we were not including Latvian before?

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 9 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:322]: Done - the dependencies is used in some parts of Keycloak, but not here. So I now added it here as well.

Comment (ahus1) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:322]: Hm, reverted it as that method doesn't allow passing in a locale, and making things uppercase is locale dependent. This might need more investigation.

File: themes/src/main/resources-community/theme/base/account/theme.properties (hunk 10 above)
Comment (ahus1) [reply themes/src/main/resources-community/theme/base/account/theme.properties:1]: It was present in the login locales list, but not on the account locales list. I double checked and the files `messages_lv.properties` contains data, so I added it. And without it, the dropdown list in the locales for the Account UI was only showing the fallback, not the message properties entry.

**Comment by ahus1** [comment]
Hi @jonkoops - I updated the PR to address your comments. It is now ready for (final?) review. Thanks!

**Review by jonkoops — APPROVED** [review]
LGTM, let's get this merged.

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 6 above)
Comment (Eng-Fouad) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java]: Here is how it would look when printing locales in Arabic:

using LTR UI (notice how RTL locale is printed):

ltr

using RTL UI:

rtl

**Review by mhajas — APPROVED** [review]
Approving based on the review from @jonkoops

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 6 above)
Comment (jonkoops) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java]: Sounds good, thanks for the feedback @Eng-Fouad
