### PR TITLE
fix: consolidating logic dealing with persisted property handling

### LINKED ISSUE #34258: Simplify how Keycloak deals with persisted properties
### Description

There is currently an asymmetry in how persisted properties are created and checked. We should make it consistent to avoid problems with auto-builds and invalid warnings / errors related to build properties.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #34258

This splits out logic that was initially part of https://github.com/keycloak/keycloak/pull/33760

Issues covered here:

- The change detection and property persisting now use the same method to build the properties set. We still have special handling, but only for the optimized and profile properties.
- We will only deal with fully resolved property names, so routines dealing with the profile aren't needed, but this also requires initializing the profile in Picocli sooner than we were doing before.
- Previously we were persisting all quarkus.properties (including things like passwords), but checking for build time changes in only quarkus datasource related properties - I've been hit by it before with some testing where I was setting some other quarkus build time property, but the autobuild was not happening. The changes here embrace that we don't know which of the properties are build time (quarkus only provides limited facilities for this), so we'll just rebuild whenever any of these change.
- Some of our checks around dev profile behavior were specific to start, but any of the commands that can trigger autobuilds are affected as well. So this required moving around where those checks were performed and adding a couple of new tests
- Refined some of the ConfigValue ordinal handling with additional comments to make our expectations explicit.
  - Differentiated between the quarkus.properties in the classpath and the filesystem
  - Make the PropertyMapper transformValue explcitly set the ordinal to 0
  - Add a constant for our lowest level of options that should be set by the user. Obviously they can unintentionally include a provider jar that shadows the classpath location for one of our built-in files, but we call this out in the docs as something they shouldn't do.

### CODE REVIEW

**Comment by pedroigor** [comment]
@shawkins @vmuzikar LGTM, log of changes. If tests pass and you are good with it, works for me.

Do we want to backport it? I'm afraid if not, we'll live with a very different codebase than what we'll have here in upstream?

**Comment by shawkins** [comment]
It's worth mentioning that these changes also address a subtle issue with build properties referencing other properties. The prior logic stored the raw values, so later auto-build / validation checks are based potentially on the wrong value.

**Comment by shawkins** [comment]
Converting back to draft to make sure I didn't miss anything wrt system properties.

**Comment by shawkins** [comment]
Added a comment about what is considered user modifiable - it will currently ignore system properties.

**Comment by shawkins** [comment]
@mabartos @vmuzikar it would be great to see if this could get merged before tackling a different direction for https://github.com/keycloak/keycloak/issues/34058

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 1]
```diff
@@ -558,124 +551,62 @@ private static void outputDisabledProperties(Set<String> properties, boolean bui
...
-                    continue;
+                name = mapper.getFrom();
+                if (properties.containsKey(name)) {
+                    return;
                 }
-
-                // probably because it was unset
-                return true;
+            } else if (name.startsWith(MicroProfileConfigProvider.NS_QUARKUS)) {
+                // TODO: this is not correct - we are including runtime properties here, but at least they
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:569]: Quarkus needs to have some mechanism for testing whether it's buildtime option, or not, right?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 2]
```diff
@@ -558,124 +551,62 @@ private static void outputDisabledProperties(Set<String> properties, boolean bui
...
-                                return true;
-                            }
-                        }
-
-                        //if it contains the key, check if the value actually changed from the persisted one.
-                        return hasAtLeastOneChangedBuildProperty(foundQuarkusBuildProperties, persistedConfigSource.get().getProperties().entrySet());
-                    }
-                }
+            // since we're presisting all quarkus values, this may leak some runtime information - we don't want
+            // to capture expanded expressions that may be referencing environment variables
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:582]: +1

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 3]
```diff
@@ -558,124 +551,62 @@ private static void outputDisabledProperties(Set<String> properties, boolean bui
...
+        // the following should be ignored when output the optimized check message
+        // they are either not set by the user, or not properly initialized
 
-    private static boolean hasAtLeastOneChangedBuildProperty(Map<String, String> foundQuarkusBuildProperties, Set<Map.Entry<String, String>> persistedEntries) {
-        for(Map.Entry<String, String> persistedEntry : persistedEntries) {
-            if (foundQuarkusBuildProperties.containsKey(persistedEntry.getKey())) {
-                return isChangedValue(foundQuarkusBuildProperties, persistedEntry);
-            }
+        for (File jar : getProviderFiles().values()) {
+            properties.put(String.format(KC_PROVIDER_FILE_PREFIX + "%s.last-modified", jar.getName()), String.valueOf(jar.lastModified()));
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:594]: How do we check change for custom providers that need a rebuild? From reading new changes, it seems to me that whenever the provider is changed, the explicit build is required without any changes detection. Is it correct?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java [hunk 4]
```diff
@@ -111,8 +110,13 @@ public List<OptionCategory> getOptionCategories() {
     }
 
     private void exitWithErrorIfDevProfileIsSetAndNotStartDev() {
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java:112]:
```suggestion
    private void exitWithErrorIfDevProfileIsSet() {
```
nitpick: not related to start-dev anymore

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java [hunk 5]
```diff
@@ -232,24 +236,27 @@ public Optional<DeprecatedMetadata> getDeprecatedMetadata() {
...
+            return configValue;
+        }
 
-        return ConfigValue.builder()
-                .withName(name)
-                .withValue(mappedValue)
-                .withRawValue(value)
-                .withConfigSourceName(configSourceName)
-                .build();
+        // by unsetting the ordinal this will not be seen as directly modified by the user
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java:258]: +1

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java [hunk 6]
```diff
@@ -52,6 +54,7 @@ void reAugOnFirstRun(LaunchResult result) {
     @BeforeStartDistribution(EnableAdditionalConsoleHandler.class)
     @Launch({ "start" })
     @Order(2)
+    @Disabled(value = "We don't properly differentiate between quarkus runtime and build time properties")
```
Comment (mabartos) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java:57]: Instead of disabling all of them, it'd be good to have some test, that the reaug really happening, when the quarkus prop is changed. @shawkins WDYT?

**Review by mabartos — COMMENTED** [review]
@shawkins Great work! Changes LGTM and I agree with your claims in the PR description.

I added some comments there - the most serious question is related to the custom providers. 

Could you please also check the TODO comments? Are they gonna be addressed even in this PR, or is it something that we should follow up on?

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java (hunk 6 above)
Comment (shawkins) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java:57]: We do have that for the build-time quarkus properties, the disabled tests should be for runtime only.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 7]
```diff
@@ -236,34 +230,51 @@ protected int runReAugmentationIfNeeded(List<String> cliArgs, CommandLine cmd, C
...
+
     private static boolean shouldSkipRebuild(List<String> cliArgs, String currentCommandName) {
         return cliArgs.contains("--help")
                 || cliArgs.contains("-h")
                 || cliArgs.contains("--help-all")
                 || currentCommandName.equals(Build.NAME)
                 || currentCommandName.equals(ShowConfig.NAME)
-                || currentCommandName.equals(BootstrapAdmin.NAME)
-                || currentCommandName.equals(Tools.NAME);
+                || currentCommandName.equals(Completion.NAME);
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:257]: > So, as Tools command contains only the Completion subcommand, it will never be set as the current command - always the Completion is used. I understand it.

Yes, that is correct. Checking for the parent command here is ineffective.

> But what is the case for the bootstrap admin?

Similar - checking for the parent command here isn't doing anything.

> AFAIK, the NonServer commands never run augmentation, is it correct?

Unfortunately no. import, export, bootstrap-admin are all allowed to auto-build.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:569]: Yes, for most of the configuration in quarkus it is able to determine if something is build time vs. runtime and tries to capture in the respective bucket - runtime defaults, build time values, etc. If we worked with the quarkus team more we could probably come up with a way to just rely on their internal stuff, rather than needing our own persisted properties.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 3 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:594]: > How do we check change for custom providers that need a rebuild?

The current entry in the properties will have a different timestamp than the persisted entry.

> it seems to me that whenever the provider is changed, the explicit build is required without any changes detection. Is it correct?

If using --optimized you will continue to use the current build - and will not see any log related to the provider change. That matches the behavior today. We certainly could add a check, just like we do for regular configuration values, and log a warning or error in this situation instead. 

If not using --optimized, it will see that an auto-build is needed.

**Comment by shawkins** [comment]
One more change - more comprehensively dealt with the setting / comparison of the profile. We were effectively omitting setting it to prod for some builds.

**Review by vmuzikar — DISMISSED** [review]
Thanks for the PR, @shawkins! I think it's a very nice refactor and overall simplification, preventing issues like we had recently.

Added some nitpics but they are not blocking from my perspective.

> Do we want to backport it? I'm afraid if not, we'll live with a very different codebase than what we'll have here in upstream?

@pedroigor I'm not comfortable with backporting this, despite the implications of maintaining 2 codebases for this. The changes here are quite extensive and I would not risk introducing regressions in a micro.

**Comment by vmuzikar** [comment]
@shawkins Can you please also rebase?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 8]
```diff
@@ -236,34 +229,44 @@ protected int runReAugmentationIfNeeded(List<String> cliArgs, CommandLine cmd, C
...
-            return true;
-        }
-
-        return hasProviderChanges();
+        var current = getNonPersistedBuildTimeOptions();
+        
+        // everything but the optimized option must match
+        Stream.of(Configuration.KC_OPTIMIZED)
+                .forEach(key -> Optional.ofNullable(rawPersistedProperties.get(key))
+                        .ifPresentOrElse(value -> current.put(key, value), () -> current.remove(key)));
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:268]: Right I just left it the way it was in case we added other properties back.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 9]
```diff
@@ -236,34 +229,44 @@ protected int runReAugmentationIfNeeded(List<String> cliArgs, CommandLine cmd, C
         return exitCode;
     }
 
+    protected void initProfile(List<String> cliArgs, String currentCommandName) {
+        if (currentCommandName.equals(StartDev.NAME)) {
+            // force the server image to be set with the dev profile
+            Environment.forceDevProfile();
+        } else {
+            String profile = Optional.ofNullable(org.keycloak.common.util.Environment.getProfile()).orElse(Environment.PROD_PROFILE_VALUE);
+            Environment.setProfile(profile);
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:238]: Unfortunately no, we don't want to use the persisted profile at this point.

**Comment by shawkins** [comment]
> @shawkins Can you please also rebase?

Updated now.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (vmuzikar) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:238]: > Would you prefer adding a parameter to updateProfile?

That's sounds like a good idea to have the logic in a single place.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 3 above)
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:586]: @shawkins right, thanks for the explanation. 

> We certainly could add a check, just like we do for regular configuration values, and log a warning or error in this situation instead.

@shawkins It might be nice to have some check for detecting changed provider. Could you please create a follow-up task? Thanks!

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:583]: @mabartos added https://github.com/keycloak/keycloak/issues/34665

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java]: Ok, merged the logic in several more places.

File: quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 10]
```diff
@@ -255,4 +260,112 @@ public void spiRuntimeWarnWithBuild() {
...
+        NonRunningPicocli nonRunningPicocli = pseudoLaunch("export", "--file=file");
+        assertEquals(CommandLine.ExitCode.OK, nonRunningPicocli.exitCode);
+        assertFalse(nonRunningPicocli.reaug);
+    }
+    
+    @Test
+    public void testReaugFromDevToProd() {
+        build("start-dev");
+        
+        Environment.setRebuildCheck(); // will be reset by the system properties logic
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:333]: The `Environment.setRebuildCheck()` might be part of the `build(..)` method, right? Maybe considering it for further follow-ups.

**Review by mabartos — APPROVED** [review]
@shawkins Nice stuff! Nothing serious came to my eyes and changes LGTM. Thanks!

File: quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 10 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:333]: It could be, but it probably should be an option. We have three distinct test paths:
build + rebuildCheck = reaug test
build + w/o rebuildCheck = auto start test
build + w/o rebuildCheck + --optimized = optimized start test

I'm not sure if it's worth the effort, but we could change the rebuild check logic - rather than requiring 2 separate java commands we could just always do the rebuild check if --optimized is not supplied, then return a non-zero exit code when rebuilt to let the script no that another launch is needed.

Comment (mabartos) [reply quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:333]: I see. Let's discuss some improvements around PicocliTest in follow-up tasks, how we could improve devEx.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.
