### PR TITLE
NPE when using HttpClient and enabled tracing

### LINKED ISSUE #47379: RetryConfig is ignored
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Any configuration properties defined in RetryConfig (https://www.keycloak.org/server/outgoinghttp#_configuring_retry_behavior_for_outgoing_http_requests) like `spi-connections-http-client-default-max-retries` or `spi-connections-http-client-default-initial-backoff-millis` are ignored.

The reason is because the retry handler built in `DefaultHttpClientFactory.configureRetries` is attached to a Apache HttpClientBuilder that is returned by `getApacheHttpClientBuilder()`.
This is done before keycloak's `HttpClientBuilder.build()` is called.
Afterwards in keycloak's HttpClientBuilder.build() a new Apache HttpClientBuilder is created by calling `getApacheHttpClientBuilder()` again. In this instance no retry handler is attached.
Therefore the default Apache `DefaultHttpRequestRetryHandler` is used.

### Version

26.5.6

### Regression

- [ ] The issue is a regression

### Expected behavior

The retry configuration properties should be used to control http retry behavior.

### Actual behavior

The retry configuration properties are not used.

### How to Reproduce?

Configure retry e.g. by setting KC_SPI_CONNECTIONS_HTTP_CLIENT_DEFAULT_MAX_RETRIES and check in the debugger if the correct retry handler is set before `builder.build()` is called in `HttpClientBuilder` (line 297).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #47379

@shawkins Could you please check it? Thanks!

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/tracing/OTelHttpClientFactory.java [hunk 1]
```diff
@@ -38,24 +38,14 @@
...
-            BUILDER_SINGLETON = new OTelHttpClientBuilder((OTelTracingProvider) session.getProvider(TracingProvider.class));
-        }
-        return super.create(session);
-    }
-
-    @Override
-    protected HttpClientBuilder newHttpClientBuilder() {
-        return BUILDER_SINGLETON;
+    protected HttpClientBuilder newHttpClientBuilder(KeycloakSession session) {
+        return new OTelHttpClientBuilder((OTelTracingProvider) session.getProvider(TracingProvider.class));
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/tracing/OTelHttpClientFactory.java]: FYI - No need to have the singleton builder - rather be more consistent and safe in this initialization.

File: services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java [hunk 2]
```diff
@@ -306,6 +306,10 @@ protected HttpClientBuilder newHttpClientBuilder() {
         return new HttpClientBuilder();
     }
 
+    protected HttpClientBuilder newHttpClientBuilder(KeycloakSession session) {
```
Comment (mabartos) [inline services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java:313]: FYI - method overload to avoid any potential breaking change.

File: services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java [hunk 3]
```diff
@@ -306,6 +306,9 @@ public CloseableHttpClient build() {
     }
 
     protected org.apache.http.impl.client.HttpClientBuilder getApacheHttpClientBuilder() {
+        if (apacheBuilder == null) {
+            apacheBuilder = createApacheHttpClientBuilder();
```
Comment (mabartos) [inline services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java]: FYI - Lazy init

Comment (shawkins) [reply services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java]: Lazy init is not needed, getApacheHttpClientBuilder is always called when build is called.

Unless you think there will be situations where a builder is created and build is not called.

Comment (mabartos) [reply services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java]: @shawkins Updated based on the offline discussion.

**Review by shawkins — DISMISSED** [review]
LGTM, thanks @mabartos

**Comment by shawkins** [comment]
Retargeted to #47379 for better tracking

**Review by vmuzikar — APPROVED** [review]
