### PR TITLE
Forward LOGIN_HINT of authentication session with identity-provider-r…

### LINKED ISSUE #36396: "identity-provider-redirector" does not forward LOGIN_HINT of authentication session
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Using the `identity-provider-redirector` the LOGIN_HINT on the session is not forwarded to the IDP.

Having a look at the code it seems like the redirect function is always called with the loginHint being null: https://github.com/keycloak/keycloak/blob/40f39f3f0953b70f8f6d012d25cfb2980e9c1041/services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java#L77-L79

Instead of always using null here, the value should be taken from the AuthenticationSession, maybe like this:

```java
protected void redirect(AuthenticationFlowContext context, String providerId) {
    String loginHint = context.getAuthenticationSession().getClientNote(OIDCLoginProtocol.LOGIN_HINT_PARAM);
    redirect(context, providerId, loginHint);
}
```

I stumbled upon this issue when having a look at: https://github.com/sventorben/keycloak-home-idp-discovery/discussions/396#discussioncomment-10066716 

### Version

25.0.5 (but latest should also be affected)

### Regression

- [ ] The issue is a regression

### Expected behavior

If there is a LOGIN_HINT set on the LoginSession this should be forwarded.

### Actual behavior

None is forwarded.

### How to Reproduce?

Setup flow like mentioned here: https://github.com/sventorben/keycloak-home-idp-discovery/discussions/396#discussioncomment-10066716  

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by antikalk**
…edirector

Fixes keycloak#36396

### CODE REVIEW

**Comment by ahus1** [comment]
Pinging @douglaspalmer as you have triaged the parent issue.

**Review by douglaspalmer — CHANGES_REQUESTED** [review]
Can you please add a test to for this behaviour? I think AbstractSamlLoginHintTest would be the right place to test this.

**Comment by antikalk** [comment]
@douglaspalmer Actually I don't think that the `AbstractSamlLoginHintTest` class is the right place for these tests. As far as I understand the class, here it is only tested whether the loginHint is forwarded when using the social login buttons, there is no interaction with the `identity-provider-redirector` authenticator from what I can see.

**Review by douglaspalmer — CHANGES_REQUESTED** [review]
I don't know where identity-provider-redirector is tested.

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @antikalk for the PR!

But we need a test for this. I think that you can check the [AbstractDefaultIdpTest](https://github.com/keycloak/keycloak/blob/26.2.5/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractDefaultIdpTest.java#L96), it would be doing something similar, passing the login hint parameter and check the parameter is forwarded.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractDefaultIdpTest.java [hunk 1]
```diff
@@ -93,6 +93,27 @@ public void testDefaultIdpSet() {
                 driver.getCurrentUrl().contains("/auth/realms/" + bc.providerRealmName() + "/"));
     }
 
+    @Test
```
Comment (antikalk) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractDefaultIdpTest.java]: @douglaspalmer @rmartinc I have added the corresponding test here. Signing in with the consumer realm, we expect to be forwarded to the provider realm with the login_hint still being present in the login page on the provider realm.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerConfiguration.java [hunk 2]
```diff
@@ -201,6 +201,7 @@ protected void applyDefaultConfiguration(final Map<String, String> config, Ident
         config.put("clientId", CLIENT_ID);
         config.put("clientSecret", CLIENT_SECRET);
         config.put("prompt", "login");
+        config.put("loginHint", "true");
```
Comment (antikalk) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerConfiguration.java:204]: Additionally I had to add this parameter, because only when this is set on the IDP the loginHint is forwarded when provided anyway.

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @antikalk!

I have been testing your branch and it's almost OK. The test works as expected but fails with `KcSamlDefaultIdpTest` (which is normal). The reason is that both classes extends the modified `AbstractDefaultIdpTest`. Just move your test from `AbstractDefaultIdpTest` to `KcOidcDefaultIdpTest` and it would be OK.

Thanks again!

**Comment by antikalk** [comment]
Makes sense! I have updated the branch accordingly.

**Review by rmartinc — APPROVED** [review]
Thanks @antikalk! LGTM!

**Review by mposolda — APPROVED** [review]
@antikalk @rmartinc Thanks for the work and review of this.
