### PR TITLE
Efficient row-count on PostgreSQL for indexes

### LINKED ISSUE #42704: SELECT COUNT(*) FROM called multiple times for an index creation
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

While upgrading Keycloak we saw multiple `SELECT count(*) FROM` on the database logs for the same table and multiple `Following index should be created:` for the same index. 

In `CustomCreateIndexChange` there is a `SELECT count(*) FROM` to check for table size and skip a index creation if a table is too big: 

https://github.com/keycloak/keycloak/blob/aa8321b8373f9ce443eb2851fb37f41a1101e55e/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java#L82

But, this is called inside `SqlStatement[] generateStatements(Database database)` where the javadoc says that this method maybe called multiple times:

>  NOTE: This method may be called multiple times throughout the changelog execution process and may be called in documentation generation and other integration points as well. 
> If this method reads from the current database state or uses any other logic that will be affected by whether previous changeSets have ran or not, you must return true from [generateStatementsVolatile(liquibase.database.Database)](https://javadoc.io/static/org.liquibase/liquibase-core/4.33.0/liquibase/change/Change.html#generateStatementsVolatile(liquibase.database.Database)).

https://javadoc.io/doc/org.liquibase/liquibase-core/latest/liquibase/change/Change.html#generateStatements(liquibase.database.Database)

### Version

26.2.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect Keycloak to only perform a single `SELECT count(*) FROM` for each index. 

Ideally, if multiple indexes are created against the same table, it could re-use already computed counts. 

Even more ideally, it could use existing statistics provided by the database (like `n_live_tup` in `pg_stat_user_tables` for postgres), but this may be database specific. 

### Actual behavior

It performs the same `SELECT count(*) FROM` for each index 3 times at least. 

### How to Reproduce?

1. Enable logs for all queries in the database
2. Upgrade between version, where a index is to be created on a table with too many rows (default above 300000 rows)
3. Check the database logs to see multiple `SELECT count(*) FROM`  

### Anything else?

_No response_

### LINKED ISSUE #44057: Retrieving row count to evaluate index creation takes a long time on PostgreSQL and big tables
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When trying to update a Keycloak instance from 26.3.5 to 26.4.4, `CustomCreateIndexChange` froze the Keycloak boot because of the following SQL query:
```sql
SELECT COUNT(*) FROM public.EVENT_ENTITY
```

The jstack pinpointed https://github.com/keycloak/keycloak/blob/39c4c1ed942a4bdcc0a3c4d68a9b853a082ea9a2/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java#L82-L82 .

In this instance, table `EVENT_ENTITY` is huge with many records. The count request is very slow.
I guess that, ironically, `CustomCreateIndexChange` performs this count to avoid triggering an index creation that would take too much time.

### Version

26.4.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak automatic database update should take a reasonable amount of time.

### Actual behavior

Keycloak automatic database update hangs forever.

### How to Reproduce?

Make sure to have  a huge `EVENT_ENTITY` table on version 26.3.5 then update Keycloak to 26.4.4

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #44057
Closes #42704

I tested this manually as follows when testing: 

* Test with PostgreSQL
* In the `migration_model` table, create an entry for 26.4.0 in addition to the 999.0.0 entry
* In the `databasechangelog`, remove `26.5.0-index-offline-css-by-client` and `26.5.0-index-offline-css-by-client-storage-provider`
* Drop the index `idx_offline_css_by_client` and `idx_offline_css_by_client_storage_provider` on `offline_client_session`
* Start Keycloak with `--spi-datastore-legacy-allow-migrate-existing-database-to-snapshot=true` and see that Keycloak performs the migration and adds the indexes

### CODE REVIEW

**Comment by ahus1** [comment]
@keycloak/cloud-native - looking for a reviewer for this database related change. 

I would like to backport this change, we had some index changes for KC 26.4 / RHBK 26.4, and I those who haven't upgraded yet to benefit from it. 

The build was green once, the latest changes were only about the documentation.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java [hunk 1]
```diff
@@ -55,6 +56,8 @@
 public class CustomCreateIndexChange extends CreateIndexChange {
     private static final Logger logger = Logger.getLogger(CustomCreateIndexChange.class);
     private int indexCreationThreshold;
```
Comment (pruivo) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: It looks like this needs to be a long too.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java [hunk 2]
```diff
@@ -55,6 +56,8 @@
...
+    private Long entriesInTable = null;
+    private boolean logged;
```
Comment (pruivo) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java:61]: Are the `CustomCreateIndexChange` instances shared for this to be a field!?

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java [hunk 3]
```diff
@@ -95,6 +101,38 @@ public SqlStatement[] generateStatements(Database database) {
...
 
+    private Long computeEntriesInTable(Database database) throws DatabaseException {
+        if (entriesInTable != null) {
+            return entriesInTable;
+        }
+
+        if (database instanceof PostgresDatabase) {
+            try {
+                // This avoids locking all rows in the database table to get an exact count and instead takes an estimate
+                entriesInTable = Scope.getCurrentScope().getSingleton(ExecutorService.class).getExecutor(LiquibaseConstants.JDBC_EXECUTOR, database)
```
Comment (pruivo) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: It would be easier to read if `Scope.getCurrentScope().getSingleton(ExecutorService.class).getExecutor(LiquibaseConstants.JDBC_EXECUTOR, database)` is in a method.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java [hunk 4]
```diff
@@ -95,6 +101,38 @@ public SqlStatement[] generateStatements(Database database) {
...
+                        .queryForLong(new RawParameterizedSqlStatement("SELECT reltuples::bigint AS estimate FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = current_schema AND UPPER(c.relname) = UPPER(?)", getTableName()));
+                if (entriesInTable == -1L) {
```
Comment (pruivo) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: Shouldn't it be `if entriesInTable >= 0; then return`? The method will continue and use the "count with limit" query.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java [hunk 5]
```diff
@@ -95,6 +101,38 @@ public SqlStatement[] generateStatements(Database database) {
...
+                    // no statistics exist for this table, try next approach
+                    entriesInTable = null;
+                }
+            } catch (UnexpectedLiquibaseException e) {
+                logger.warn("No permissions to run SELECT on the pg_class and pg_namespace tables, therefore can't estimate row count. Falling back to slower method to count entries with SELECT COUNT(*).", e);
+            }
+        }
+
+        if (database instanceof PostgresDatabase) {
```
Comment (pruivo) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: Don't need to do `instanceof` again, just move the code inside the if above.

**Review by pruivo — CHANGES_REQUESTED** [review]

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 5 above)
Comment (sguilhen) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: Shouldn't this test for `entriesInTable == null` instead?

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 2 above)
Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java:61]: Each entry in a changeset item gets its own instance of this class. So when there are two indexes to be created, there are two instances of this class. Due to that, this should is fine - including the caching of the row number.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 1 above)
Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: It seems that I was too lazy here, added in next commit.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 3 above)
Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: done in next commit.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 4 above)
Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: If no-one has created statistics for the table we do not have any information on how many entries there are in the table. I thought it would be better to use he count-with-limit to get a better estimate.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 5 above)
Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: sure, will do that in the next PR.

Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: thanks for spotting this. Changed in next commit.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 1 above)
Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: Implemented in next commit. It seems I was too lazy to do that.

File: docs/documentation/upgrading/topics/migrate_db.adoc [hunk 6]
```diff
@@ -28,6 +28,13 @@ To change the threshold, set the `index-creation-threshold` property, value for
 kc.[sh|bat] start --spi-connections-liquibase--quarkus--index-creation-threshold=300000
 ----
 
+You can disable this feature by setting it to a negative number:
+
+[source,bash]
+----
+kc.[sh|bat] start --spi-connections-liquibase--quarkus--index-creation-threshold=-1
```
Comment (pedroigor) [inline docs/documentation/upgrading/topics/migrate_db.adoc]: It is not clear why I should disable this setting (perhaps not calling it a feature). Would it make sense to add more information about disabling it in case the database is PostgreSQL, that it will ignore the number of rows, the risk of disabling it to other vendors, and have a link to the guide for more details?

Perhaps it makes sense to prevent disabling this setting if the database is other than PostgreSQL? IMO, I think it is a nice thing to allow admins to disable it for any vendor, as they should know what they are doing.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 4 above)
Comment (pruivo) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: It is what I said :rofl:

File: docs/documentation/upgrading/topics/migrate_db.adoc (hunk 6 above)
Comment (ahus1) [reply docs/documentation/upgrading/topics/migrate_db.adoc]: @pedroigor - this sounds like a follow-up discussion to me about this feature in general. I will not consider it for this issue.

**Comment by ahus1** [comment]
@pruivo - can you please re-review my latest changes? Thanks!

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java (hunk 4 above)
Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java]: Hm, maybe it was too late. Adapted as you suggested here and in the other relevant places in this method.

**Review by pruivo — DISMISSED** [review]
LGTM, but someone with more expertise should review it too.

**Review by pedroigor — APPROVED** [review]
Nice improvement!
