### PR TITLE
Do not store RealmModel in cache entries

### LINKED ISSUE #33439: Avoid caching `RealmModel` in `CachedOrganization`
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

A `RealmModel` is created per Keycloak transaction and it is associated with the transaction, making it unusable. Also, it is a large object graph taking almost 30MB per instance.

https://github.com/keycloak/keycloak/blob/a0ad680346934980adb33c320352d0b29a007d77/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganization.java#L35

We observed a performance penalty, see https://github.com/keycloak/keycloak/issues/33331, due to the same reason. I believe the number of organizations won't be as large as the number of users but it can be a problem in the future. 

Other models are also cached but I'm not sure how large they can be

https://github.com/keycloak/keycloak/blob/5218af1e79a8e2e88d732d26fc88c3c363ff1208/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganization.java#L41-L42

Please review. 

### Version

Main branch

### Regression

- [x] The issue is a regression

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #33439

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganization.java [hunk 1]
```diff
@@ -55,10 +55,10 @@ public CachedOrganization(Long revision, RealmModel realm, OrganizationModel org
 
     @Override
     public String getRealm() {
-        return realm.getId();
+        return realm;
     }
 
-    public RealmModel getRealmModel() {
+    public String getRealmModel() {
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganization.java:61]: can it be removed? Invokers can use `getRealm()` method above.

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganization.java:61]: +1

Comment (pedroigor) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/CachedOrganization.java]: Done

**Review by ahus1 — APPROVED** [review]
