### PR TITLE
Treat unencrypted local origins as insecure context in Safari

### LINKED ISSUE #33557: Unable to submit forms in Safari
When building Keycloak from source and navigating to `http://localhost:8080` every form submission ends in an error. For example, when creating the initial admin user in the welcome page, or when submitting the form to sign-in on the login. This was tested on the recently released Safari 18.0, I am not sure if this problem occurs in earlier versions.

## Steps to reproduce
- Download the Keycloak 26 release (https://www.keycloak.org/downloads)
- Extract the archive and run Keycloak with `./bin/kc.sh start-dev`.
- Navigate to http://localhost:8080 and fill in the admin user form on the welcome page
- Submit the form and observe a server error on the page (see below)

Screenshot 2024-10-04 at 12 12 10

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #33557

### CODE REVIEW

**Review by douglaspalmer — APPROVED** [review]
This isn't compiling right now; I guess you missed some usages of isSecureContext() when you refactored. Looks good otherwise though.

**Review by douglaspalmer — CHANGES_REQUESTED** [review]
Upon reflection I think there is a simpler way to do this. Instead of refactoring isSecureContext() and parsing the User Agent string it would be simpler and more efficient to simply use: 

String userAgent = context.getRequestHeaders().getHeaderString(HttpHeaders.USER_AGENT);
if(userAgent != null && userAgent.toLowerCase().contains("safari")) {
    return true;
}

File: services/src/main/java/org/keycloak/utils/SecureContextResolver.java [hunk 1]
```diff
@@ -1,4 +1,7 @@
-package org.keycloak.common.util;
```
Comment (shawkins) [inline services/src/main/java/org/keycloak/utils/SecureContextResolver.java:1]: Just want to double check on how public are keycloak common apis? Do we have to give any consideration to backwards compatibility / deprecation in general?

Comment (stianst) [reply services/src/main/java/org/keycloak/utils/SecureContextResolver.java:1]: This file was moved here by mistake previously, and should not be part of common.

**Review by stianst — CHANGES_REQUESTED** [review]
Needs testing, see https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java. Should be relatively easy to send a http request with the Safari user-agent set. See some of the existing tests on how to do that.

One additional issue here is that this can lead to parsing the user-agent header multiple times for a single request. That can easily be fixed by updating https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/device/DeviceRepresentationProviderImpl.java to introduce a field `private DeviceRepresentation deviceRepresentation`, and only parse the header if this is not set.

**Comment by stianst** [comment]
> Upon reflection I think there is a simpler way to do this. Instead of refactoring isSecureContext() and parsing the User Agent string it would be simpler and more efficient to simply use:
> 
> String userAgent = context.getRequestHeaders().getHeaderString(HttpHeaders.USER_AGENT); if(userAgent != null && userAgent.toLowerCase().contains("safari")) { return true; }

Makes more sense to me to do this properly and use the `DeviceRepresentationProvider` as we shouldn't introduce multiple places that parses user-agent headers.

File: services/src/main/java/org/keycloak/utils/SecureContextResolver.java (hunk 1 above)
Comment (jonkoops) [reply services/src/main/java/org/keycloak/utils/SecureContextResolver.java:1]: Also considering this work will be in the upcoming patch release I don't think it will be too much of an issue.

**Comment by jonkoops** [comment]
> `userAgent.toLowerCase().contains("safari")`

The issue with this code is that all browsers provide various user-agents other than their own in their user-agent string for backwards compatibility. This might lead to a browser being incorrectly identified, for example Google Chrome has the following user-agent:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`

As you can see it advertises itself as `Mozilla`, `AppleWebkit`, `Chrome` and `Safari`. So using a simple `contains("safari")` would lead to a false positive here.

**Comment by jonkoops** [comment]
I've added unit and integration tests for the Safari quirks. I've also changed the implementation of the `SecureContextResolver` to take a `Supplier` so that the user agent can be evaluated lazily and properly unit tested without having to deal with mocking an implementation of `KeycloakSession`. This enures that on a production deployment (HTTPS) the user agent is never evaluated, so it should incur no performance hits.

**Review by stianst — APPROVED** [review]

**Review by stianst — DISMISSED** [review]

**Review by shawkins — APPROVED** [review]
LGTM, I'll adjust #33530 as necessary if it moves forward.

**Review by pedroigor — APPROVED** [review]

**Review by douglaspalmer — APPROVED** [review]
LGTM
