### PR TITLE
Imposing certain constraints to files when importing at start-up

### LINKED ISSUE #11861: Keycloak v18.0.0 fails to import realm when directories are present in data/import location
### Describe the bug

Keycloak fails to startup when it finds a directory in the data/import location, we triggered this by mounting the realm json definition from a configmap in OpenShift/Kubernetes at data/import dir, kubernetes adds directories and symlinks in addition to the file contents and we are unable to use the kc.sh start-up realm import (--import-realm) feature because of this. 

### Version

18.0.0

### Expected behavior

Keycloak startup data import should actually ignore (perhaps report) but continue processing files in data/import , should never fail because there are symlinks or other directories present.

### Actual behavior

Keycloak/kc.sh fails to startup with --import-realm because it finds directories in the data/import location

### How to Reproduce?

Drop some sample realms to import in data/import , also create directories , try to startup with kc.sh start --import-realm , watch it fail.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #11861

### CODE REVIEW

**Comment by andreaTP** [comment]
Would it be possible to easily support symlinks? Looks like a legit use-case 🙂

**Review by DGuhr — DISMISSED** [review]
PR LGTM, even when i'd prefer to have automated tests for this case. 

@andreaTP I'd say move your suggestion to another issue? It's pretty valid imo, and the [Files](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html) api has everything in it to [check](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#isSymbolicLink(java.nio.file.Path)) and [read](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#readSymbolicLink(java.nio.file.Path)) symlinks, but in the end it's a new requirement, adding complexity, has to be maintained, and should be handled as such, right?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java [hunk 1]
```diff
@@ -25,6 +25,8 @@
 import java.io.FileInputStream;
 import java.io.IOException;
 import java.nio.file.Files;
+import java.nio.file.LinkOption;
```
Comment (andreaTP) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java:28]: don't hate me @pedroigor , but this is an unused import 😢

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportAtStartupDistTest.java [hunk 2]
```diff
@@ -45,6 +46,23 @@ void testImport(LaunchResult result) {
         cliResult.assertMessage("Imported realm quickstart-realm from file");
     }
 
+    @Test
+    @BeforeStartDistribution(CreateRealmConfigurationFileAndDir.class)
+    @Launch({"start-dev", "--import-realm", "--log-level=org.keycloak.quarkus.runtime.storage.database.jpa:debug"})
+    void testImportAndIgnoreDirectory(LaunchResult result) {
```
Comment (andreaTP) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportAtStartupDistTest.java:52]: would you mind adding a test checking the functionality with symlinks?

**Review by andreaTP — COMMENTED** [review]
a couple of notes, but is totally going in the right direction! 👍

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportAtStartupDistTest.java (hunk 2 above)
Comment (pedroigor) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportAtStartupDistTest.java:52]: If not explicitly disabled why check for symlinks if we already have tests for files? For me, it is unnecessary. Or am I missing something?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java (hunk 1 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java]: You missed a few others :) Also updated the test herein changed.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java [hunk 3]
```diff
@@ -322,8 +327,15 @@ private void importRealms() {
                 String file = tokenizer.nextToken().trim();
                 RealmRepresentation rep;
                 try {
+                    Path filePath = Paths.get(file);
```
Comment (DGuhr) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java:330]: Giving this PR another look, one question around this line and the following check for "json":

In case of a symlink, does `filePath` contain the symlinkspath/name/ending or the actual files path and name/extension? 

Maybe wrong here, but when that one contains just the symlink, it would be theoretically possible to do a symlink from "import.json" pointing to "myBadHackingScript.java" right? So just want to make sure we check the ending of the actual file that's linked to here, not the one of the symlink.

i mean with the above that I am not sure we should use Paths.toRealPath instead of Paths.get before checking the file ending, because it may (or may not when I understand it wrong) be that we're just checking the symlink extension instead of the file extension and thus opening attack vectors where there's no need to. 

ref: https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toRealPath-java.nio.file.LinkOption...-

Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java:330]: For me, it makes not much difference but if you really think this is needed perhaps you can elaborate more about the attack vectors?

Comment (DGuhr) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java:330]: I don't have concrete attack vectors in mind, that's why its a general question. 

_if my assumption is true_, it just seemed a bit weird for me that we are checking only that the symlink is ending with `json` without checking that the actual file the symlink links to is a json file. 

Afterwards we try to serialize it, so if there's any bug in the serialization, when you add a specifically crafted sh/exe file or sth, we would be open for it. But as said, I don't have an exact CVE in mind. Perhaps @abstractj knows more? 

I am not hard on this, question is just why not add it as the change looks like it is simple to do and will definitely avoid the scenario i outline above?

Comment (DGuhr) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java:330]: works for me for now, approved.

**Review by DGuhr — APPROVED** [review]

**Comment by abstractj** [comment]
@DGuhr I understand your point, and it is a valid exercise to do. At the same time, let's think abit about the scenario described.

(If I understood it correctly) Scenario: A malicious attacker introduces a symlink "import.json" pointing to "myBadHackingScript.java" adding a specifically crafted sh/exe

Requirements for the attacker to be successful from my understanding:
- Access to the system console to create the symlink, or send a malicious script to create this symlink locally to any user with access to the system. 
- Credentials to import the script
- Trick the JSON parser, or benefit from some bug in the serialization process

If understood it correctly and the requirements are somewhat valid, it is a very unlikely scenario to happen. Although, I agree that if it is an easy change it would be better to use `Paths.toRealPath`, but at the same time, not a dealbreaker for me.

**Review by abstractj — APPROVED** [review]
@pedroigor approving it. But I will wait for @andreaTP and @DGuhr approvals before we merge.

**Comment by andreaTP** [comment]
@pedroigor have we tested those changes with K8s configmaps?
