### PR TITLE
fix: ensures that cli and env messages are the same

### LINKED ISSUE #13608: Improve error handling when configuration env vars
### Description

This requires a little bit more investigation to properly set the scope of it.

One concrete example of confusing error message:
```
docker run --rm -e KC_DB=postgresdb -e KC_DB_USERNAME=test -e KC_DB_PASSWORD=test quay.io/keycloak/keycloak:19.0.0 start

Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.

...

ERROR: Failed to run 'build' command.
ERROR: java.util.NoSuchElementException: No value present
ERROR: No value present
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

Compare to CLI arguments:
```
docker run --rm quay.io/keycloak/keycloak:19.0.0 start --db postgredb --db-username test --db-password test


Changes detected in configuration. Updating the server image.
Invalid value for option '--db': postgredb. Expected values are: dev-file, dev-mem, mariadb, mssql, mysql, oracle, postgres
Try 'kc.sh build --help' for more information on the available options.
```

We should be consistent with the  error messages regardless if env vars or CLI args are used for configuration.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
Fix for inconsistency between cli and env usage.  This seems to be the simplest way to handle this - pulling the relevant env as cli options.  There is of course some messiness to doing this, and it's adding an extra parsing of the command line options, but I didn't see another way to quickly determine the target command.

closes #13608

### CODE REVIEW

**Comment by shawkins** [comment]
@vmuzikar @mabartos is there a better way to do this?

**Review by vmuzikar — CHANGES_REQUESTED** [review]
I think this approach doesn't fully fix it as we need to account for [fast start](https://github.com/keycloak/keycloak/blob/c9d93019c2e13de2037543a9ab40912612f46bc3/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java#L90-L93) that [skips](https://github.com/keycloak/keycloak/blob/c9d93019c2e13de2037543a9ab40912612f46bc3/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java#L71) CLI args parsing.

**Comment by shawkins** [comment]
> For 3 we could possibly find some way to unify the logic for CLI and env vars. 

As far as I can tell what the cli is primary giving us is expected value validation.  Let me see what things look like if that is added separately.

> I wonder if config file (and potentially any config source) is affected too.

My focus here was strickly on the env because of the issue, but yes if all checks are moved post-cli, then they would be against the full Config, including any config file.

**Comment by vmuzikar** [comment]
> IMO, we should create some sort of abstraction about the configuration. We might just gather the configuration from SmallRye(don't care about the source) and create some sort of representation of the Keycloak configuration.

I agree but we [have it already](https://github.com/keycloak/keycloak/tree/main/quarkus/config-api/src/main/java/org/keycloak/config), kinda... I think we just need to unify validation.

**Comment by shawkins** [comment]
> I think we just need to unify validation.

@vmuzikar the next stab at this creates a utility method for validating the non-cli properties.  It is a much larger change, but it does have specific handling for the optimized start case.

If the overall approach seems fine, some additional questions / thoughts:
- The config source name could be mentioned in the non-cli case to make it more clear where the property is defined
- validateNonCliConfig was based on hasConfigChanges, which scans over all config.  It may be better to scan based upon the applicable PropertyMappers instead - as we have seen with the method too large issue raised recently some environments will have thousands of env variables.  In particular for the "fast start" case this doing quite a bit more work just to validate a handful of runtime properties that have expected values (like --log)
- https://github.com/keycloak/keycloak/pull/23797/files#diff-5e7526010bd1f3d3c2735d6b5d600aaf3457a83eb1699ef7e10c91e2257ae6d2R145 - could be moved to a separate pr.  It's to better cover the case where a user mistaken does something like "./kc.sh --something" where there's no command present.
- Similarly it seems like we should be setting the exit code here https://github.com/keycloak/keycloak/pull/23797/files#diff-c1907932c84285e376fbc3a66277c655f30b91476db47834c3f5a81a7a45b319R80

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 1]
```diff
@@ -225,6 +234,59 @@ private static boolean hasProviderChanges() {
...
+                if (mapper.isRunTime() && !options.includeRuntime) {
+                    // TODO for cli this is treated as unknown
+                    continue;
+                }
+
+                if (!PropertyMapperParameterConsumer.isExpectedValue(mapper.getExpectedValues(), value)) {
+                    throw new NonCliPropertyException(PropertyMapperParameterConsumer.getErrorMessage(mapper.getFrom(),
+                            value, mapper.getExpectedValues(), mapper.getExpectedValues()) + ". From ConfigSource " + configSource.getName());
+                }
+            }
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:286]: I'm not 100 % happy that we need to access config sources directly but I guess there's no other way if we want to get "unprocessed" value skipping the whole interceptor chain.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java [hunk 2]
```diff
@@ -20,12 +29,28 @@ public int handleParseException(ParameterException ex, String[] args) {
...
+                if (!command.getOptionCategories().contains(mapper.getCategory())) {
+                    errorMessage = "Option: '" + cliKey + "' not valid for command " + cmd.getCommandName();
+                } else {
+                    if (Stream.of(args).anyMatch(OPTIMIZED_BUILD_OPTION_LONG::equals) && mapper.isBuildTime() && Start.NAME.equals(cmd.getCommandName())) {
+                        errorMessage = "Build time option: '" + cliKey + "' not usable with pre-built image and --optimized";
+                    } else {
+                        errorMessage = (mapper.isRunTime()?"Run time":"Build time") + " option: '" + cliKey + "' not usable with " + cmd.getCommandName();
+                    }
+                }
+            }
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java:53]: This is a very nice UX adjustment! 👍

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thank you, I like it. It's a very nice UX improvement.

That said, it feels to me a bit "messy" and I wonder if we could maybe somehow decouple the validation from Pico CLI. But not sure about it, nor do I have a specific idea how it should look like. So current approach works for me.

Could you perhaps add a new test to check if config sources get correct error messages?

@pedroigor @mabartos Do you want to review as well?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java [hunk 3]
```diff
@@ -20,12 +29,28 @@ public int handleParseException(ParameterException ex, String[] args) {
 
             String[] unmatched = getUnmatchedPartsByOptionSeparator(uae,"=");
             String original = uae.getUnmatched().get(0);
+            String cliKey = unmatched[0];
 
             if (unmatched[0].equals(original)) {
                 unmatched = getUnmatchedPartsByOptionSeparator(uae," ");
             }
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java:36]: Yes it should be, will correct.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:286]: Right the PropertyMappingInterceptor introduces a lot of considerations - especially with the build command.  It seems best to side-step that.  Otherwise there are some corrections that could / should be made to the PropertyMapper transformation / validation logic which is assuming that a valid db type is being used, or that a value exists (quite a few places are doing optional.get(), but optional could be empty).

**Comment by shawkins** [comment]
> That said, it feels to me a bit "messy" and I wonder if we could maybe somehow decouple the validation from Pico CLI. But not sure about it, nor do I have a specific idea how it should look like. So current approach works for me.

It's a light coupling with Pico cli in that we need the AbstractCommand classes, but not the CommandLine.  I didn't see anywhere else that had the option category mapping to command or the property validation message logic, so it seems best for now if this lives close to Picocli - I could move not a different class if you want.

Another small bit of messiness is at what ConfigSource to stop looking - we just want to consider the "user configurable" config sources.  I've hardcoded that at 300, which matches the built-in EnvConfigSource - which shouldn't even get used because it should be fully eclipsed by the KC env config source.  We may want to put more thought into that.

> Could you perhaps add a new test to check if config sources get correct error messages?

Yes, env and conf/keycloak.conf definitely are covered.  I haven't expressly tried --config-file, but I believe that should already have been initialized by the cli by the time we're running the validation logic.

Expectations for env or other user configurable sources:

1. export KC_DB=invalid
./kc.sh start | build
should complain about kc.db

2. export KC_LOG=invalid
./kc.sh start
should complain about kc.log

TBD:

1. export KC_DB=invalid
./kc.sh start --optimized
currently marked as a TODO - we may at least want a log indicating which build-time properties were ignored.  If we don't want to add further validation to the operator, then something is needed here to address the original operator issue - log scaping or even a flag that would cause a failure to start with incorrect usage of build-time properties.

1. export KC_LOG=invalid
./kc.sh build
Similar to the above - we could at least log what runtime values are not used.

**Comment by vmuzikar** [comment]
> TBD:
> 
> 1. export KC_DB=invalid
>    ./kc.sh start --optimized
>    currently marked as a TODO - we may at least want a log indicating which build-time properties were ignored.  If we don't want to add further validation to the operator, then something is needed here to address the original operator issue - log scaping or even a flag that would cause a failure to start with incorrect usage of build-time properties.
> 2. export KC_LOG=invalid
>    ./kc.sh build
>    Similar to the above - we could at least log what runtime values are not used.

+1 for just logging that with info level. Anything more than (failure) that might be a bit complicated and confusing. Would we consider env vars? Config file? What if the env var remain set after the previous `kc.sh build`? Etc., etc. But in any case, I'd address that as a follow-up.

**Comment by shawkins** [comment]
> +1 for just logging that with info level. Anything more than (failure) that might be a bit complicated and confusing. 

I've added something for this already: Picocli.outputIgnoredProperties - it is directly to the stdout because the quarkus deferred logger will swallow it sometimes otherwise.

> Would we consider env vars? Config file? What if the env var remain set after the previous kc.sh build? Etc., etc. 

It's all the same "configurable" sources that we're already checking.  The message just says they are being ignored - it's not trying to compare to the existing value, if any.  

> But in any case, I'd address that as a follow-up.

It can be done in a separate pr if you want.

**Comment by vmuzikar** [comment]
@mabartos @pedroigor I'd like to merge this soon. Let me know if you want to review. :)

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 4]
```diff
@@ -225,6 +249,74 @@ private static boolean hasProviderChanges() {
...
+                    continue;
+                }
+                if (mapper.isRunTime() && !options.includeRuntime) {
+                    ignoredRunTime.add(mapper.getFrom());
+                    continue;
+                }
+
+                if (!PropertyMapperParameterConsumer.isExpectedValue(mapper.getExpectedValues(), value)) {
+                    throw new NonCliPropertyException(PropertyMapperParameterConsumer.getErrorMessage(mapper.getFrom(),
+                            value, mapper.getExpectedValues(), mapper.getExpectedValues()) + ". From ConfigSource " + configSource.getName());
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:301]: Agreed, mentioned this as well in https://github.com/keycloak/keycloak/pull/23797#issuecomment-1755557548 - so we'll capture that as a follow-up.

**Review by mabartos — APPROVED** [review]
@shawkins @vmuzikar As we don't have any better solution for it ATM, and it quite remarkably improves the UX, I'm ok to proceed in this form.

**Review by Pepo48 — APPROVED** [review]
I went through the changes yesterday, I just forgot about the approve. I'm fine with the proposed, it's actually a huge improvement from my perspective. 

Thanks @shawkins 👍

**Comment by shawkins** [comment]
There errors seem to be from an unrelated issue with liquibase - there's a sql related exception in the failed pod logs.  I'll rebase to see if we can get this pr clean.

**Review by vmuzikar — APPROVED** [review]
LGTM. Are we ready to merge this yet? :)

**Comment by shawkins** [comment]
> LGTM. Are we ready to merge this yet? :)

I think once it tests cleanly yes - see above that there some liqiubase errors in the previous run.
