### PR TITLE
use the backend and fixed grouping

### LINKED ISSUE #19673: Sessions displayed multiple times
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The "Sessions" page at `/admin/master/console/#/master/sessions` has multiple entries for the same session when multiple clients have been visited by a user.

### Version

21.0.2

### Expected behavior

The "Sessions" page has a "Clients" column. If a user visits multiple clients, there should be a single row with multiple entries in the "Clients" column. Just like in Users - Sessions:

image

### Actual behavior

For each visited client, a separate row is displayed in the "Sessions" page. All rows list all clients in their "Clients" column:

image

The above image should only have a single row.

### How to Reproduce?

* Login to Security Admin Console as `admin`
* Visit the account console as `admin`
* Open the "Sessions" page

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #19673

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
Can't say much about the Java code, but all the UI changes look good to me.

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/SessionRepresentation.java [hunk 1]
```diff
@@ -79,5 +80,18 @@ public Map<String, String> getClients() {
     public void setClients(Map<String, String> clients) {
         this.clients = clients;
     }
+
+    @Override
+    public boolean equals(Object o) {
+        if (this == o) return true;
+        if (o == null || getClass() != o.getClass()) return false;
```
Comment (ssilvert) [inline rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/SessionRepresentation.java:87]: Joshua Bloch recommends to use `instanceof` instead of `getClass()` here.  That way, this method will still work if the class hierarchy changes.  (I always pull out my copy of Effective Java whenever I have to do this).

**Review by ssilvert — CHANGES_REQUESTED** [review]

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/SessionRepresentation.java (hunk 1 above)
Comment (edewit) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/SessionRepresentation.java:87]: Well if it's not the same class it's not the same imo

Comment (ssilvert) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/SessionRepresentation.java:87]: A distinct session is one that has the same start, userId, and type.  Let's say someone decides we need FooSessionRepresentation and BarSessionRepresentation that both extend SessionRepresentation:

```
FooSessionRepresentation extends SessionRepresentation {
}

BarSessionRepresentation extends SessionRepresentation {
}
```

Now we would be back to having the same problem as in the issue.  There would be a possibility of duplicates with the same start, userId, and type.  They would differ only by class instance, but are really two representations of the same session. So how do you fix this problem?  Just override and call super();

```
FooSessionRepresentation extends SessionRepresentation {
   @Override
    public boolean equals(Object o) {
         return super.equals(o);
    }

   @Override
    public int hashCode() {
        return super.hashCode();
    }
}
```

But with `getClass()`, `super.equals(o)` doesn't work.  `FooSessionRepresentation` and `BarSessionRepresentation` would not be considered equal, even though they are just two representations of the same session.  Nobody would notice the problem and we've just reintroduced the original bug.  With `instanceof`, it does work because both are an instance of `SessionRepresentation`.

It's a pretty esoteric point.  But this is why Bloch recommends `instanceof`.  I think `instanceof` is slightly more correct.

**Review by ssilvert — DISMISSED** [review]

**Review by jonkoops — APPROVED** [review]
