### PR TITLE
Better management of the CSP header

### LINKED ISSUE #24568: iframe for frontend logout gets blocked if a custom CSP header is used
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When Front channel logout is configured for a oidc client the logout is performed using an `iframe` to call the client front-channel URL. For example in my sample client:

```html
<li>
  sample-rhsso
  <iframe src="http://localhost:8081/sample-rhsso/logout?sid=310d5fbf-7df7-4d75-957d-46208cdb77c2&amp;iss=http%3A%2F%2Flocalhost%3A8080%2Frealms%2Fmaster" style="display:none;"></iframe>
</li>
```

The CSP header by default is modified to allow client URL in the `iframe` adding the hostname of the client backchannel URL to the `frame-src` poclicy. In my sample:

```
Content-Security-Policy: frame-src localhost:8081 ; object-src 'none';
```

If a custom CSP header is configured in the realm the `frame-src` is not modified and therefore the iframe is not called because it's not allowed. For example is I change my realm `Realm Settings -> Security Defenses -> Content-Security-Policy` to `frame-src 'self'; frame-ancestors 'self'; object-src 'none'; style-src 'self';`.

I'm just adding the `style-src` directive to the default CSP value but now the CSP received by the browser is:

```
Content-Security-Policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none'; style-src 'self';
```

And the backchannel URL is not called because it's not allowed by the CSP. So the client is not logged out.

### Version

22.0.5

### Expected behavior

I think we need a more intelligent design of the CSP header. I would do the following:

* Manage `frame-src` and `frame-ancestors` independently of the other directives.
* For `frame-src` add the hostnames needed to the current value defined by the realm (by default would be `'self'` and transformed to `'self` hostname1 hostname2...`.
* For `frame-ancestors` remove the directive if and only if the default `'self'` is in place. This modification is needed for the login iframe used by the JS adapter. If the administrator has modified the `frame-ancestors` it will be respected and not modified.

### Actual behavior

If the CSP header is customized at realm level the modifications for `frame-src` and `frame-ancestors` are just not done. The logout or the iframe for login won't work.

### How to Reproduce?

1. Create an OIDC client with Front channel logout to ON and Front-channel logout URL configured.
2. Test that by default the CSP and iframe is OK and the frontchannel URL is called.
3. Modify the realm setting CSP to `frame-src 'self'; frame-ancestors 'self'; object-src 'none'; style-src 'self';`.
4. Check the CSP is just sent as configured in the realm and the iframe URL is not called.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/24568

With this PR the CSP modifications are performed independently to the `frame-src`  (front-channel logout handler) and `frame-ancestors` (getting the iframe from resources)  directives. In the `frame-src`  case, the different hostnames are added to the configured directive (for example if the realm defines `'self' keycloak.org` the final directive sent after adding the clients values is `'self' keycloak.org client1 client2`). In the case of `frame-ancestors` the directive is removed for iframe inclusion only if the default `'self'` value is configured (if the admin changed it to any other value, the directive is not modified). Added a test in `forms` to use firefox and chrome (the test needs a real browser to check the CSP header).

Parsing just manages spaces as separator to read the current CSP defined in the realm. The spec allows other things  as separator (like tabs, new lines,...) but I didn't want to complicate it more. If you think it's necessary just let me know.

@mposolda @stianst Take a look when you have time.

### CODE REVIEW

File: services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java [hunk 1]
```diff
@@ -106,22 +106,24 @@ private void addHtmlHeaders(MultivaluedMap<String, Object> headers) {
...
-            ContentSecurityPolicyBuilder csp = ContentSecurityPolicyBuilder.create();
+            ContentSecurityPolicyBuilder csp = ContentSecurityPolicyBuilder.create(
+                    headers.getFirst(CONTENT_SECURITY_POLICY.getHeaderName()).toString());
 
             if (options.isAllowAnyFrameAncestor()) {
                 headers.remove(BrowserSecurityHeaders.X_FRAME_OPTIONS.getHeaderName());
 
-                csp.frameAncestors(null);
+                if (csp.isDefaultFrameAncestors()) {
+                    // only remove frame ancestors if defined to default 'self'
```
Comment (jichen-amplify) [inline services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java:116]: @rmartinc Can you elaborate on why this is the case? Isn't the intention of `options.isAllowAnyFrameAncestor()` so that we can allow some resources to be loaded under any third-party domains? If that is the case, then we should remove frame ancestors regardless whether it is defined to be default or not, right?

Comment (rmartinc) [reply services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java:116]: The intention of this part is to just force the frame-ancestors if it's not modified by the admins. If admins are setting some default ancestors for example `self https://*.example.com` I suppose the admins know what they are doing and limiting to those ancestors on purpose (because they know the clients are always from those URLs or similar). But not writing in stone, if you have a better idea just let me know. This part is only used to get the IFrame for login.

Comment (jichen-amplify) [reply services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java:116]: I see that currently there are three resources that are using the `options.isAllowAnyFrameAncestor()` feature to remove frame ancestors, so that they can be loaded in any iFrames:

* [login-status-iframe.html](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java#L51)
* [3p-cookies-step1.html](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/ThirdPartyCookiesIframeEndpoint.java#L46)
* [3p-cookies-step2.html](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/ThirdPartyCookiesIframeEndpoint.java#L53)

It seems to me that it is safe to allow these resources to be hosted in any iFrames all the time. That is why I am thinking we should continue to treat these resources differently as the other pages (such as the actual login pages), even when the admins specifically are limiting the frame ancestors on purpose.

Comment (rmartinc) [reply services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java:116]: Yes, all those resources are used by the keycloak-js client when the checkLoginIframe is default true. So, just used for the keycloak-js client login. I'm OK to always remove ancestors but then we should take in mind that this cannot be overridden.

**Review by mposolda — COMMENTED** [review]
@rmartinc I've added only minor comments. Hopefully moving the test to different class (and maybe constants) and we should be fine. Is it ok to you?

File: server-spi-private/src/main/java/org/keycloak/models/ContentSecurityPolicyBuilder.java [hunk 2]
```diff
@@ -1,48 +1,120 @@
...
+public class ContentSecurityPolicyBuilder {
 
-    private boolean first;
-    private StringBuilder sb;
+    private final Map<String, String> directives = new LinkedHashMap<>();
 
     public static ContentSecurityPolicyBuilder create() {
-        return new ContentSecurityPolicyBuilder();
+        return new ContentSecurityPolicyBuilder()
+                .add("frame-src", "'self'")
```
[the remark this answers is not in the document]
Comment (rmartinc) [reply server-spi-private/src/main/java/org/keycloak/models/ContentSecurityPolicyBuilder.java:28]: Done!

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java [hunk 3]
```diff
@@ -1029,4 +1033,35 @@ public void testExecuteActionIfSessionExists() {
         }
 
     }
+
+    @Test
+    public void testFrontChannelLogoutCustomCSP() throws Exception {
```
[the remark this answers is not in the document]
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java:1038]: No, it's not possible. For this test I need the chrome/firefox driver to correctly follow the CSP directives. If the test uses default browser it is always OK because the CSP directives are not taken into account. So I need the forms or the wenauthn CI run (the ones that uses `-Dbrowser=chrome`). I remember I initially added the test in another class to realize that it was not tested in CI. If you want I can add it in a complete new class nut in forms folder (something like `CSPLoginTest` for example).

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks!
