### PR TITLE
fix: change from operator. to kc-operator. properties

### LINKED ISSUE #12352: Align Operator config naming with Quarkus distribution
This is a follow-up from https://github.com/keycloak/keycloak/issues/10738#issuecomment-1142189716.

Change `Config` to be more aligned with Quarkus distribution (e.g. similar to `kc-operator.operand.image`, `kc-operator.operand.image-pull-policy` etc. etc.)

### PR DESCRIPTION
**Pull request by shawkins**
closes #12352

### CODE REVIEW

File: operator/src/main/java/org/keycloak/operator/Config.java [hunk 1]
```diff
@@ -24,7 +24,7 @@
 /**
  * @author Vaclav Muzikar <vmuzikar@redhat.com>
  */
-@ConfigMapping(prefix = "operator")
+@ConfigMapping(prefix = "kc-operator")
 public interface Config {
     Keycloak keycloak();
```
Comment (mabartos) [inline operator/src/main/java/org/keycloak/operator/Config.java:29]: @shawkins 
What is the purpose of having the inner Keycloak interface included in the parent Config interface? Do we expect some other config props unrelated to Keycloak in this case? 

The thing is that when we put the `kc-` prefix to the config mapping, we explicitly reference the Keycloak Operator. What about merging these interfaces and thus simplify the configuration?

The breaking changes are inevitable anyway, right?

So, instead of:
```
-Doperator.keycloak.pod-labels."xxx"=
```

We would have:
```
-Dkc-operator.pod-labels."xxx"=
```

But that's my initial thought and I'm not aware of any issues it could bring, or violates certain k8s conventions, etc.

Comment (shawkins) [reply operator/src/main/java/org/keycloak/operator/Config.java:29]: In managed kafka for example we ended up with two deployments in our bundle - the operator and a sync component. Presumably the usage of the keycloak interface will allow for this possiblity as well:

kc-operator.sidecar.key=value

Comment (mabartos) [reply operator/src/main/java/org/keycloak/operator/Config.java:29]: > Presumably the usage of the keycloak interface will allow for this possiblity as well

+1. I think it worths the discussion about it as we're introducing breaking changes anyway, so we could polish it a little bit. @shawkins @vmuzikar WDYT?

Comment (vmuzikar) [reply operator/src/main/java/org/keycloak/operator/Config.java:29]: As @shawkins mentioned, the inner `Keycloak` interface is meant just for the Keycloak deployment just in case we have more deployments in the future.

**Comment by vmuzikar** [comment]
@shawkins @mabartos Was wondering if instead of `kc-operator` we should use `kc.operator` to also align with Keycloak (use its `kc` "namespace")? WDYT?

**Comment by shawkins** [comment]
> @shawkins @mabartos Was wondering if instead of `kc-operator` we should use `kc.operator` to also align with Keycloak (use its `kc` "namespace")? WDYT?

So long as there won't be a case where we need to pass regular kc options via the operator env there won't be a conflict - or we can agree to reserve the usage of the operator term.

**Comment by vmuzikar** [comment]
Now that #26203 was resolved, I'd like to resurrect this PR. For me, most sense makes `kc.operator` to align with Keycloak. I think conflicts are not likely as Keycloak Quarkus context and Operator Quarkus context are completely separated. But I don't have a strong opinion, either `kc.operator` or `kc-operator` work for me.

AFAIK, the options are used in the following places which will need updating:
* Tests in GHA both [local](https://github.com/keycloak/keycloak/blob/ac6f16df70cd33d6ee1910c092d49ebaf552c335/.github/workflows/operator-ci.yml#L90-L97) and [remote](https://github.com/keycloak/keycloak/blob/ac6f16df70cd33d6ee1910c092d49ebaf552c335/.github/workflows/operator-ci.yml#L135-L145)
* Tests in QE pipelines
* [Release process on GH](https://github.com/keycloak-rel/keycloak-rel/blob/028c7f7a18dd749dbc1f13d124e8334da676cb91/.github/workflows/x-keycloak-operator.yml#L115)
* Release process downstream(?)
   CC @ASzc

**Comment by shawkins** [comment]
@mabartos what are your thoughts - kc.operator or kcop?

**Comment by mabartos** [comment]
> @mabartos what are your thoughts - kc.operator or kcop?

@shawkins I like `kc.operator` more; as it's also close to the conventions we have in distro config with the `kc.` prefix :)

**Comment by shawkins** [comment]
Ok updated to kc.operator - we won't worry about any potential overlap between the server and the operator. 

This will need some kind of doc in the upgrade guide. 

Another thought is that we could try to maintain backwards compatibility by adding application properties like:

```
kc.operator.keycloak.image=${operator.keycloak.image}
```

That would allow for deprecation, rather than forced updates. @vmuzikar @mabartos wdyt?

File: .github/workflows/operator-ci.yml [hunk 2]
```diff
@@ -138,11 +138,11 @@ jobs:
           ./mvnw install -Poperator -pl :keycloak-operator -am \
               -Dquarkus.container-image.build=true \
               -Dquarkus.kubernetes.image-pull-policy=IfNotPresent \
-              -Doperator.keycloak.image=keycloak:${{ env.version_remote }} \
-              -Dquarkus.kubernetes.env.vars.operator-keycloak-image-pull-policy=Never \
-              -Dtest.operator.custom.image=custom-keycloak:${{ env.version_remote }} \
+              -Dkc-operator.keycloak.image=keycloak:${{ env.version_remote }} \
+              -Dquarkus.kubernetes.env.vars.kc-operator-keycloak-image-pull-policy=Never \
+              -Dtest.kc-operator.custom.image=custom-keycloak:${{ env.version_remote }} \
```
Comment (vmuzikar) [inline .github/workflows/operator-ci.yml:143]:
```suggestion
              -Dkc.operator.keycloak.image=keycloak:${{ env.version_remote }} \
              -Dquarkus.kubernetes.env.vars.kc-operator-keycloak-image-pull-policy=Never \
              -Dtest.kc.operator.custom.image=custom-keycloak:${{ env.version_remote }} \
```

File: .github/workflows/operator-ci.yml [hunk 3]
```diff
@@ -138,11 +138,11 @@ jobs:
...
               --no-transfer-progress -Dtest.operator.deployment=remote \
-              -Dtest.operator.kubernetes.ip=$(minikube ip)
+              -Dtest.kc-operator.kubernetes.ip=$(minikube ip)
```
Comment (vmuzikar) [inline .github/workflows/operator-ci.yml:145]:
```suggestion
              -Dtest.kc.operator.kubernetes.ip=$(minikube ip)
```

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thanks!

We'll also need to update:
https://github.com/keycloak/keycloak/blob/ac6f16df70cd33d6ee1910c092d49ebaf552c335/operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java#L92-L93

> This will need some kind of doc in the upgrade guide.

Yeah, just a brief mention. But I woulnd't worry too much about it as it's not supported.

> Another thought is that we could try to maintain backwards compatibility by adding application properties

No need for this, operator config options are neither supported nor documented.

**Comment by vmuzikar** [comment]
@ASzc Ah, you're not using the `operator.keycloak.image` config option as you are setting it via `RELATED_IMAGE_KEYCLOAK` env var.

File: .github/workflows/operator-ci.yml (hunk 3 above)
Comment (shawkins) [reply .github/workflows/operator-ci.yml]: On the test properties - test.operator.kubernetes.ip is no longer needed, and I meant to leave test.operator.custom.image alone as it (and test.operator.deployment) are specifically test properties.

File: .github/workflows/operator-ci.yml [hunk 4]
```diff
@@ -91,10 +91,10 @@ jobs:
...
           ./mvnw install -Poperator -pl :keycloak-operator -am \
               -Dquarkus.kubernetes.image-pull-policy=IfNotPresent \
-              -Doperator.keycloak.image=keycloak:${{ env.version_local }} \
-              -Dtest.operator.custom.image=custom-keycloak:${{ env.version_local }} \
-              -Doperator.keycloak.image-pull-policy=Never \
-              -Dtest.operator.kubernetes.ip=$(minikube ip)
+              -Dkc.operator.keycloak.image=keycloak:${{ env.version_local }} \
+              -Dtest.kc.operator.custom.image=custom-keycloak:${{ env.version_local }} \
+              -Dkc.operator.keycloak.image-pull-policy=Never \
+              -Dtest.kc.operator.kubernetes.ip=$(minikube ip)
```
[the remark this answers is not in the document]
Comment (shawkins) [reply .github/workflows/operator-ci.yml]: Removed - and also added back the logic around the ip. I had forgotten that the docs explicitly call out its usage with mac and minikube tunnel.

**Review by vmuzikar — APPROVED** [review]
@shawkins Thanks!

**Comment by vmuzikar** [comment]
@mabartos Do you want to give it a look as well?

**Review by mabartos — APPROVED** [review]
LGTM
