### PR TITLE
Fix DB tests for Quarkus

### LINKED ISSUE #13642: Fix DB tests for Quarkus
### Describe the bug

Related issue: [CIAM-3417](https://issues.redhat.com/browse/CIAM-3417)

At this moment, it's not possible to execute DB tests with the Quarkus distribution. It seems that only the default H2 database is used when executing these tests with the Quarkus auth server. 

### Version

999

### Expected behavior

Tests are executed with a particular DBs.

### Actual behavior

Tests are executed with the default H2 DB.

### How to Reproduce?

For instance, execute some test with Postgres DB as follows:

`mvn -f /testsuite/integration-arquillian/pom.xml -Dtest=UserTests -Pauth-server-quarkus,db-postgres`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Fixes #13642

Local execution of tests is working for:

1. Default H2 DB
2. Legacy Store
3. JPA Map Store
4. CHM Store

Supported DBs ATM for the pipeline: PostgreSQL, MariaDB, MySQL

With this PR, we can execute any test with a particular DB in our testsuite with `auth-server-quarkus`.
F.e. 
```
mvn -f /testsuite/integration-arquillian/pom.xml -Dtest=UserTests -Pauth-server-quarkus,db-postgres
```
It will fetch the docker image of Postgres DB and execute the particular test with it.

JPA Map store: 
```
mvn -f /testsuite/integration-arquillian/pom.xml -Dtest=UserTests -Pauth-server-quarkus,map-storage,map-storage-jpa,db-postgres
```

Note: Needs to be properly tested and polished. I'll add more information later.

------------------------------------------
@nehachopra27 @hmlnarik @DGuhr @pedroigor Could you please take a look at it, once you have a chance? :) Thank you!

MR to the pipeline: https://keycloak-pipeline.com/keycloak/keycloak-pipeline/-/merge_requests/170

### CODE REVIEW

**Comment by pedroigor** [comment]
@mabartos Somes tests are failing. I'm not 100% sure what might be causing but I suspect it is related to how re-augmentation is happening after your changes. Or how the `data` directory is removed between test runs.

**Comment by mabartos** [comment]
@pedroigor Yep, there are a few failures. I need to investigate it a little bit; there are also some failures for the DB Allocator.

**Comment by mabartos** [comment]
Added Michal's commit from PR #13724 which resolves the map-storage failures.

It'd be good to optimize the execution of those tests as currently, after each restart, the 'build' process is executed and the re-augmentation is done. Only the first start of the server with the default H2 DB is optimized. However, we don't have a chance to determine, when it's possible to start the server without the 'build' phase. We'd need to trace features state changes, providers deployment,... It's out of this PR scope.

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/MapStoreProvider.java [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+        }
+
+        @Override
+        public Optional<String> getDbPassword() {
+            return Optional.ofNullable(System.getProperty("keycloak.map.storage.connectionsJpa.password"));
+        }
+    },
+    HOTROD("hotrod") {
+        @Override
+        public Optional<String> getDbUrl() {
```
Comment (mhajas) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/MapStoreProvider.java:63]: @mabartos HotRod has different configuration options as DB in Quarkus dist, see https://github.com/keycloak/keycloak/blob/main/quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartDevHelpAll.unix.approved.txt#L82-L89

Comment (mabartos) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/MapStoreProvider.java:63]: @mhajas Thanks for your comment! I think the support for HotRod can be done in some follow-up task, WDYT? :)) 

Perhaps, included in this #13697 task?

Comment (mhajas) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/MapStoreProvider.java:63]: Sure we will make HotRod with Quarkus work with that issue. However, the changes done in this PR will need quite a significant refactoring to add the possibility of setting different options for HotRod. Maybe it would make sense to introduce a way of setting the option that already supports this. For example,  within the `MapStoreProvider` enum, we could have a method that takes `List<String> commands and it would do something like [this](https://github.com/keycloak/keycloak/pull/13643/files#diff-80935a251925bed2db7292d60c81a7546ceb14dcb4565e82cd5582e34705cc4cL250-L263) but each case would be a different enum. WDYT? If you think it makes sense to solve this later and this PR needs to be merged asap, we can leave this as is.

Comment (mabartos) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/MapStoreProvider.java:63]: Yep, it makes sense, at least, to prepare the codebase for the HotRod changes :)) I'll do it in this PR

**Comment by mhajas** [comment]
> It'd be good to optimize the execution of those tests as currently, after each restart, the 'build' process is executed and the re-augmentation is done.

@mabartos AFAIK, the re-augmentation is done only when it is necessary (only if some meaningful change to config was done before restart). See [this method](https://github.com/keycloak/keycloak/blob/e3af0610e21961c1e8d074a223f9fffee0e56dde/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java#L125).

**Comment by mabartos** [comment]
@mhajas Slightly modified code in order to be compatible with the HotRod. I think it's not necessary having the possibility to specify those parameters in the arquillian.xml (KeycloakQuarkusConfiguration).

**Comment by mabartos** [comment]
@mhajas @DGuhr @nehachopra27 Could you please check this PR? Everything works as expected. 

@pedroigor Could you please re-run the Base testsuite (quarkus, group3) check? There's an error, which is not related to this PR (RefreshTokenTest).

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java [hunk 2]
```diff
@@ -22,7 +22,7 @@ public class KeycloakQuarkusConfiguration implements ContainerConfiguration {
     private int bindHttpPortOffset = 100;
     private int bindHttpPort = 8080;
     private int bindHttpsPortOffset = 0;
-    private int bindHttpsPort = Integer.valueOf(System.getProperty("auth.server.https.port", "8543"));
+    private int bindHttpsPort = Integer.parseInt(System.getProperty("auth.server.https.port", "8543"));
```
Comment (pedroigor) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java:25]: A nitpick and optional suggestion.

As you are changing here, perhaps we can just use `java.lang.Integer#getInteger(java.lang.String, java.lang.Integer)`.

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java [hunk 3]
```diff
@@ -47,20 +48,20 @@
...
 
     private static final int DEFAULT_SHUTDOWN_TIMEOUT_SECONDS = 10;
-    private static final String AUTH_SERVER_QUARKUS_MAP_STORAGE_PROFILE = "auth.server.quarkus.mapStorage.profile.config";
 
     private static final Logger log = Logger.getLogger(KeycloakQuarkusServerDeployableContainer.class);
 
     private KeycloakQuarkusConfiguration configuration;
     private Process container;
-    private static AtomicBoolean restart = new AtomicBoolean();
+    private static AtomicBoolean firstExecution = new AtomicBoolean(true);
```
Comment (pedroigor) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java:64]: I'm not 100% sure if the best here is to change the logic around this flag.

The main idea around that flag is to only run re-augmentation (implicit `build`) when the server is restarting. This eventually happens during test execution due to changes to features, deploying providers, or changing anything else that requires a  `build` prior to starting the server. Also, note that the logic around this flag also makes sure the same build options are set as when running the Ant plugin to pre-configure the distribution (auth-server-quarkus).

Instead, I would change the Ant script (`configure.xml` in auth-server-quarkus module) to pre-configure the distribution with the choosen database vendor and then make sure the Arquillian container includes the database vendor when doing restarts.

Comment (mabartos) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java:64]: @pedroigor Thank you very much for your comment!

I've only renamed the flag as I think it makes more sense in the current context of determining whether the build phase should be executed, or not. To be more specific, it emphasizes the fact that's necessary to execute the build phase only for the first time when some particular DB or store is required; not for the default H2 DB. 
However, if you think it makes more sense to keep the var name `restart`, I can revert it (it's just "negated" logic for better readability).

Regarding the ant script, I wouldn't say it's a better approach. The old approach is suitable only for the default H2 DB, where it's not necessary to execute the build phase after the first initialization of the Quarkus server; even for this new approach, there's no build phase, when the H2 should be used. Each store (Legacy, CHM, Map-JPA, HotRod) requires different arguments to run, in order to properly execute tests with it, and IMHO, setting the configuration in the codebase is better than having it set up by some Maven properties. 

Moreover, from the dev perspective, as it's kinda important to execute tests with ease, it'd bring some additional effort and complications, when the DB vendor should be set up already in the ant script. It'd mean when a developer would try to execute some tests with different DB vendors (f.e PostgreSQL and then MariaDB), he/her would have to always build the whole Quarkus auth server (/servers/auth-server/...). ATM, a developer can just execute the base module with the specified DB profile - f.e `mvn clean install -f /testsuite/integration-arquillian/tests/base/pom.xml -Dtest=UsersTest -Pauth-server-quarkus,db-postgres`.

Comment (mabartos) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java]: Reverted `restart` logic.

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java (hunk 2 above)
Comment (mabartos) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java]: Fixed, thanks.

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java (hunk 3 above)
Comment (pedroigor) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java]: Yeah, that is true. By pre-configuring the distribution with a database (default to H2/no-vendor) we add an additional step where the `auth-server-quarkus` module should be built prior to executing tests.

However, my argument is all about reducing test execution time. I understand that for H2 tests it should not make a difference but when running DB tests the time will increase significantly.

For now, we can focus on enabling the DB tests for Quarkus. And then evaluate later improvements to execution time. Not hard on fixing this now.

Comment (mabartos) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java]: @pedroigor I understand your concerns, but IMO, the proper execution of tests with various DBs is more important ATM than the execution time. And as you've mentioned, we can improve the execution time of those tests in some follow-up tasks :) Thank you!

**Review by pedroigor — APPROVED** [review]
