### PR TITLE
11198 added event information to consent granting and revocation via …

### LINKED ISSUE #11198: Granting or revoking consent using account rest service does not fully populate event information
### Describe the bug

Event information when granting or revoking consent using the account rest api only contain IP address as information but nothing else (client, user, granted/revoked client, granted scopes).

### Version

17.0.1

### Expected behavior

- Revoking consent using the account rest API shows IP address, user, calling client in event + revoked client in event details
- Granting consent using the account rest API shows IP address, user, calling client in event + granted client and granted scopes in event details

### Actual behavior

- Revoking consent using the account rest API only shows IP address in events (see screenshot)
- Granting consent using the account rest API only shows IP address in event
Screenshot 2022-04-08 at 17 58 21

### How to Reproduce?

Grant and revoke consents using the account REST API.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sschu**
…REST API

Fixes https://github.com/keycloak/keycloak/issues/11198

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java [hunk 1]
```diff
@@ -391,6 +393,8 @@ public Response grantConsent(final @PathParam("clientId") String clientId,
     @Produces(MediaType.APPLICATION_JSON)
     public Response updateConsent(final @PathParam("clientId") String clientId,
                                   final ConsentRepresentation consent) {
+        //Default assumption: PUT means UPDATE_CONSENT
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java:396]:
```suggestion
```

Same as above

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java [hunk 2]
```diff
@@ -1004,257 +1004,281 @@ public void getNotExistingApplication() throws IOException {
...
+                .detail(Details.GRANTED_CLIENT,appId)
+                .detail(Details.SCOPE,requestedScopes.get(0).getName())
+                .assertEvent();
+        events.assertEmpty();
+
+        //Cleanup
+        SimpleHttp.doDelete(getAccountUrl("applications/" + appId + "/consent"), httpClient)
+                .header("Accept", "application/json")
+                .auth(tokenUtil.getToken())
+                .asResponse();
```
Comment (stianst) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java:1099]: Would it not be better to use the admin-client here instead of SimpleHttp?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java [hunk 3]
```diff
@@ -1004,257 +1004,281 @@ public void getNotExistingApplication() throws IOException {
...
+        events.poll();
+        events.expectAccount(EventType.UPDATE_CONSENT)
+                .user(getUser().getId())
+                .detail(Details.GRANTED_CLIENT,appId)
+                .detail(Details.SCOPE,requestedScopes.get(0).getName())
+                .assertEvent();
+        events.assertEmpty();
+
+        //Cleanup
+        SimpleHttp.doDelete(getAccountUrl("applications/" + appId + "/consent"), httpClient)
```
Comment (stianst) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java:1217]: Same as above

**Comment by stianst** [comment]
LGTM, only minor comments is perhaps the comments are not needed, but doesn't really matter

File: services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java [hunk 4]
```diff
@@ -375,6 +375,8 @@ public Response revokeConsent(final @PathParam("clientId") String clientId) {
     @Produces(MediaType.APPLICATION_JSON)
     public Response grantConsent(final @PathParam("clientId") String clientId,
                                  final ConsentRepresentation consent) {
+        //Default assumption: POST means GRANT_CONSENT
```
[the remark this answers is not in the document]
Comment (sschu) [reply services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java]: Removed comment.

File: services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java (hunk 1 above)
Comment (sschu) [reply services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java]: Removed comment.

**Review by stianst — APPROVED** [review]

**Comment by ahus1** [comment]
A short "heads up" for those involved in this PR: This PR updated the test AccountRestService with the assumption that the granted scopes in the consentRepresentation are in the same order as requestedConsent. 

AFAIK this is not not necessary, and as the test fails with the upcoming map stores, I prepared another PR to allow for any order. Even though ConsentRepresentation is contains a list, those are retrieved from the store as a set which is unordered.

See #12396 for the code changes.

**Comment by ahus1** [comment]
@sschu - no worries, this was just passing on the information as feedback for future changes, and to make sure that my fix wasn't removing some that was supposed to be there.

Randomly failing tests are always hard to spot by humans and machines. Happy to see future PRs from you!
