### PR TITLE
Use sendKeys instead of click for the webauthn tests

### LINKED ISSUE #32548: Flaky test: org.keycloak.testsuite.webauthn.registration.UserVerificationRegisterTest#required
## org.keycloak.testsuite.webauthn.registration.UserVerificationRegisterTest#required
[Keycloak CI - WebAuthn IT (chrome)](https://github.com/keycloak/keycloak/actions/runs/10649338021/job/29519522930)

```
java.lang.AssertionError: Expected RegisterPage but was Sign in to test (https://localhost:8543/auth/realms/test/protocol/openid-connect/auth?response_type=code&client_id=test-app&redirect_uri=https%3A%2F%2Flocalhost%3A8543%2Fauth%2Frealms%2Fmaster%2Fapp%2Fauth&state=596fbc2b-9911-4d1f-a10c-396dde82a634&scope=openid)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
...
```

### LINKED ISSUE #33037: Flaky test: org.keycloak.testsuite.webauthn.registration.UserVerificationRegisterTest#discouraged
## org.keycloak.testsuite.webauthn.registration.UserVerificationRegisterTest#discouraged
[Keycloak CI - WebAuthn IT (chrome)](https://github.com/keycloak/keycloak/actions/runs/10913160374/job/30289331978)

```
java.lang.AssertionError: Expected RegisterPage but was Sign in to test (https://localhost:8543/auth/realms/test/protocol/openid-connect/auth?response_type=code&client_id=test-app&redirect_uri=https%3A%2F%2Flocalhost%3A8543%2Fauth%2Frealms%2Fmaster%2Fapp%2Fauth&state=2e6f2977-ad28-4903-ac35-0cb3cced0c57&scope=openid)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
...
```

### LINKED ISSUE #33362: Flaky test: org.keycloak.testsuite.webauthn.registration.UserVerificationRegisterTest#preferredVerificationWrong
## org.keycloak.testsuite.webauthn.registration.UserVerificationRegisterTest#preferredVerificationWrong
[Keycloak CI - WebAuthn IT (chrome)](https://github.com/keycloak/keycloak/actions/runs/11079372807/job/30788496263)

```
java.lang.AssertionError: Expected RegisterPage but was Sign in to test (https://localhost:8543/auth/realms/test/protocol/openid-connect/auth?response_type=code&client_id=test-app&redirect_uri=https%3A%2F%2Flocalhost%3A8543%2Fauth%2Frealms%2Fmaster%2Fapp%2Fauth&state=cfe8e66a-4121-4c95-8608-6f6e1d909ea1&scope=openid)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
...
```

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #33362
Closes #33037
Closes #32548

Draft for this because it's a bit strange. I have detected that the issue in `UserVerificationRegisterTest` is that `click` method sometimes does not work for the chrome driver. It's not a matter of waiting, you have to `click` again. I have detected that the method `sendKeys` works always. So I'm modifying the `clickLink` method to use the `sendKeys` for chrome. That is valid for links and buttons but not for selects, so another method `click` is created for selects (only used a few times in the CI). Maybe I'm too drastic so just asking what do you think about this.

I have executed 5x10 executions of the `UserVerificationRegisterTest` and with `click` it fails ([here](https://github.com/rmartinc/keycloak/actions/runs/11141588474), not even a single 10 run is achieved completely) and with `sendKeys` it never fails ([here](https://github.com/rmartinc/keycloak/actions/runs/11141821891/job/30963724174)). I don't know, as commented this is very weird, and related to CI infrastructure.

Other alternatives I see:

1. Just creating the new method for the `clickRegister` that is failing (although I suppose it can happen in more places).
2. Do not use the `sendKeys` but try to re-click if doesn't work. I have not tried this but I suppose it's possible, but I fear it would be again a solution only for the `clickRegister` (we have to call the new method one by one when we detect the issue).

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java [hunk 1]
```diff
@@ -74,6 +74,13 @@ public static void clickLink(WebElement element) {
 
         waitUntilElement(element).is().clickable();
 
+        performOperationWithPageReload(BrowserDriverUtil.isDriverChrome(driver)
+                ? () -> element.sendKeys(Keys.ENTER)
+                : element::click);
+    }
+
+    public static void click(WebElement element) {
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java:82]: Is it possible to add javadoc for this method (EG. mention that is useful for selects etc)? It can be good to do the same for `clickLink` and mention when this one might be useful.

**Review by mposolda — COMMENTED** [review]
@rmartinc Thanks for the PR!

IMO the way you did it works and I vote for adding it.
@pedroigor @miquelsi What do you think?

I saw exactly same issue few weeks ago and figured that it happens after upgrade to Chrome 128. I've fixed it only for one single link, which caused huge amount of test failures - https://github.com/keycloak/keycloak/commit/e1d5f0c8715ed66088db2fadba820642b819da6e as I was not aware that it happens for other links as well (was surprised why this one is the only one affected). So maybe in your PR, you can also revert this change from `LoginPage.resetPassword` since you did more generic update in `clickLink` ?

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java (hunk 1 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java:82]: Yep, no problem if @miquelsi and @pedroigor agree this is the way to go I will add the javadoc.

**Review by miquelsi — APPROVED** [review]

**Review by sguilhen — APPROVED** [review]

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java (hunk 1 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java:98]: javadocs added for the two methods.

**Review by mposolda — APPROVED** [review]

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java [hunk 2]
```diff
@@ -69,11 +68,35 @@ public static void refreshPageAndWaitForLoad() {
         performOperationWithPageReload(() -> getCurrentDriver().navigate().refresh());
     }
 
+    /**
+     * The method executes click or sendKeys(Keys.ENTER) in the element.
```
Comment (jonkoops) [inline testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java:72]: Is there a bug report for this behaviour in Chrome? If so, can we link it here for future reference?

**Review by jonkoops — APPROVED** [review]
LGTM. Very nice job on finding this edge case.

File: testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java (hunk 2 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java:72]: I didn't find a bug, although I didn't search a lot. Maybe is something between chrome, selenium, arquillian,... We can test later and just changing back the clickLink method would be enough.
