### PR TITLE
Wrong query when fetching last model version

### LINKED ISSUE #9250: Wrong query when fetching last model version
After migrating from previous versions, the last model version is not properly fetched and forces Liquibase validations even though the database was already migrated.

This causes a degradation in startup time.

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #9250

### CODE REVIEW

**Review by DGuhr — DISMISSED** [review]

**Review by DGuhr — APPROVED** [review]

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java [hunk 1]
```diff
@@ -81,7 +81,7 @@
 
     public static final String QUERY_PROPERTY_PREFIX = "kc.query.";
     private static final Logger logger = Logger.getLogger(QuarkusJpaConnectionProviderFactory.class);
-    private static final String SQL_GET_LATEST_VERSION = "SELECT VERSION FROM %sMIGRATION_MODEL";
+    private static final String SQL_GET_LATEST_VERSION = "SELECT VERSION FROM %sMIGRATION_MODEL ORDER BY UPDATE_TIME DESC";
```
Comment (stianst) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java:84]: Shouldn't this use:
 https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/entities/MigrationModelEntity.java#L37

Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java:84]: It is basically the same query but we run it natively instead of through Hibernate. It is one of the optimizations we have to startup.

**Review by stianst — APPROVED** [review]
