### PR TITLE
Fix duplicate parameter check for UserInfo endpoint.

### LINKED ISSUE #14016: Missing a duplicated parameter check in UserInfo endpoint.
### Describe the bug

Related to the reported bug in [JIRA](https://issues.redhat.com/browse/KEYCLOAK-16009), UserInfo endpoint should check duplicated parameters of requests but does not check.

### Version

19.0.0

### Expected behavior

When the below request which contains duplicated scope parameters is comming, Keycloak should respond 400 Bad Request.
```
curl -s -v \
    -H "application/x-www-form-urlencoded" \
    -d "access_token=<ACCSESS_TOKEN>" \
    -d "access_token=<ACCSESS_TOKEN>" \
    http://<YOUR_HOST>/realms/test/protocol/openid-connect/userinfo
```

### Actual behavior

The duplicated access tokens are not checked, then a client get userinfo response with a status code 200.

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by m-takai**
Similar to past PR (https://github.com/keycloak/keycloak/pull/11295).
The error response of UserInfo endpoint follows RFC6750.
Thus, the checking process of duplicated parameters is added to UserInfo endpoint.

Closes https://github.com/keycloak/keycloak/issues/14016

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java [hunk 1]
```diff
@@ -136,7 +137,9 @@ public Response issueUserInfoPost() {
 
         // Fallback to form parameter
         if (accessToken == null) {
-            accessToken = request.getDecodedFormParameters().getFirst("access_token");
+            MultivaluedMap<String, String> formParams = request.getDecodedFormParameters();
+            checkParameterDuplicated(formParams);
+            accessToken = formParams.getFirst("access_token");
```
Comment (tnorimat) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java:142]: The existing UserInfoEndpoint only checks "access_token" and igores other unknown parameters.

This PR checks duplication of "access_token" and other unknows parameters.

Another option is to check only duplication of "access_token" and ignores unknow parameters.

@m-takai 
Which option do you prefer?

If checking duplication of unknown parameters, it should be checked regardless of "acess_token" being null or not.

**Review by tnorimat — COMMENTED** [review]
@m-takai I have added a few comment. Could you check them?

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java (hunk 1 above)
Comment (m-takai) [reply services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java]: Thank you for you review and a valuable comment.
Although OIDC specification does not specify how treat unknown parameters in UserInfo endpoint, the other endpoints such as authorization endpoint ignore unknown parameters followed by RFC6749. Thus, I fix the PR code to check only duplication of "access_token".

**Review by tnorimat — DISMISSED** [review]

**Comment by tnorimat** [comment]
@m-takai Could you rebase this PR on the latest main branc?

**Comment by m-takai** [comment]
@tnorimat OK, I just rebased my PR.

**Comment by mposolda** [comment]
@m-takai Thanks for the PR!

@tnorimat Are you ok with this PR? If yes, please approve. I can merge it afterwards.

**Review by tnorimat — APPROVED** [review]
LGTM

**Comment by tnorimat** [comment]
@mposolda I have approved this PR.

**Review by mposolda — APPROVED** [review]
@tnorimat @m-takai Thanks
