### PR TITLE
Reduce logging of errors during shutdown

### LINKED ISSUE #10588: Reduce log size for the model tests
### Description

Logs for model tests are too big due to Infinispan related stacktraces. Verbosity level should be reduced so logs can be rendered in a browser. 
Related to the following issue https://github.com/keycloak/keycloak/issues/10016 and PR https://github.com/keycloak/keycloak/pull/10288.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #10588

### CODE REVIEW

**Comment by ahus1** [comment]
@martin-kanis - I took an attempt and now the logs are down from 110 MB to 13 MB. 

The change contains to commits while it is in draft mode: 

1. the first commit makes sure not to enqueue threads to already closed executors
2. the second commit restructures ClientListenerExecutorDecorator.java so that it will work without error logs and problems even if the number of queued tasks exceeds the executors queue size of the default 1024. It actually implements an unlimited in-memory queue for changes. 

The second change is a change to the default behavior, at the same time I wonder when one would discard events here in the first place; I would assume people want to get and process all these event instead of filling the log.

I'd love to hear a first comment. Depending on your comment we could ask more people for feedback here.

// cc: @mhajas, @hmlnarik

**Comment by ahus1** [comment]
@martin-kanis - after yesterdays's call I looked a bit deeper also into DefaultExecutorsProviderFactory and the change you pointed me at.

This is the code in the main branch:
```
        if (min == max) {
            return Executors.newFixedThreadPool(min, threadFactory);
        } else {
            // Same like Executors.newCachedThreadPool. Besides that "min" and "max" are configurable
            return new ThreadPoolExecutor(min, max,
                    60L, TimeUnit.SECONDS,
                    new ArrayBlockingQueue<>(1024),
                    threadFactory);
        }
```

Previously this was a `SynchronousQueue`, then your change in 30b3caee9f6bea580f5b916f5eea3fe437268750 changed it to a `ArrayBlockingQueue`. Looking at the comment it should be "Same like Executors.newCachedThreadPool", and looking at that code of `Executors.newFixedThreadPool()` the JDK uses is a `LinkedBlockingQueue`. 

The behaviors of the different classes: 
* `SynchronousQueue`: queue size of 0, accept tasks only if there is an idle thread
* `ArrayBlockingQueue` with 1024 as the parameter: queue size of 1024, accept tasks only if there is an idle thread or if the queue size is less than 1024
* `LinkedBlockingQueue`: accept all tasks independent of the queue size

This indicates that when it is configured as `min == max`, it will accept all tasks as it will use the `LinkedBlockingQueue`.

I now changed the code to match the comment, it now uses a `LinkedBlockingQueue` that will never reject a task. This will ensure that all events are published for example to the remote caches, and no task is lost. I prefer this solution over the my initial work as it doesn't touch that much code. 

Now the behavior to never reject a task is the same if one would configure min/max to the same size. The downside is that it could queue up a lot of tasks, and I will reach out to Marek in another comment to hear his thoughts. 

For now, I'd like you to have a look/review and give me your thoughts on this. Thanks!

// cc: @mhajas, @hmlnarik

**Comment by ahus1** [comment]
Hi @mposolda - we've seen lots of exception as such as the following during the model tests when we create lots of offline sessions to test. They are rejected due to the setup of the executors in `DefaultExecutorsProviderFactory`.

> ERROR [org.keycloak.models.sessions.infinispan.remotestore.ClientListenerExecutorDecorator] (Thread-0) Rejected execution of task for the event 'ClientEvent [ type=CLIENT_CACHE_ENTRY_REMOVED, key=e64b14ae-c978-414d-8656-3084d3580643, version=-1 ]' . Try to increase the pool size. Pool is 'java.util.concurrent.ThreadPoolExecutor@e9bc730[Running, pool size = 64, active threads = 64, queued tasks = 1024, completed tasks = 345]'
 13:40:52,179 ERROR [org.infinispan.HOTROD] (Thread-0) ISPN004038: Unexpected error consuming event RemovedEventImpl(key=e64b14ae-c978-414d-8656-3084d3580643)
 org.infinispan.commons.CacheListenerException: ISPN004035: Caught exception [java.lang.reflect.InvocationTargetException] while invoking method [public void org.keycloak.models.sessions.infinispan.remotestore.RemoteCacheSessionListener.removed(org.infinispan.client.hotrod.event.ClientCacheEntryRemovedEvent)] on listener instance: org.keycloak.models.sessions.infinispan.remotestore.RemoteCacheSessionListener@7337e84

I wonder if you could remember a reason when an executor should actually reject the task that Keycloak wants to execute, for example when it is about to send something to a remote cache. I would think that I'd rather queue the task than discard it.

Looking at the code I found that when min=max size of the pool, it constructs a thread pool that has a `LinkedBlockingQueue` of an unlimited size; I'd rather use that setup to never discard an event.

Please let me know what you think about this change in DefaultExecutorsProviderFactory https://github.com/keycloak/keycloak/pull/10589/files#diff-afccac3c0d30862d947ddc23b9670f7e26dbbf26a4687e7b266fc7f8b538df90

Thanks!

**Comment by ahus1** [comment]
@martin-kanis, updated `testPersistenceMultipleNodesClientSessionsAtRandomNode` a bit so that it can cope with error messages when a cache is shutting down. Do you have more information on the Cross-DC tests failing?

**Comment by martin-kanis** [comment]
> @martin-kanis, updated `testPersistenceMultipleNodesClientSessionsAtRandomNode` a bit so that it can cope with error messages when a cache is shutting down. Do you have more information on the Cross-DC tests failing?

I don't know yet why Cross-DC tests are failing. Tests use `auth-server-wildfly` so there should the Wildfly managed thread pool used instead of embedded one, but I'm not sure that is relevant.

**Review by mhajas — COMMENTED** [review]
Thank you for the PR @ahus1, I think I found another place that should be guarded with `isShutdown` check, could you please have a look?

The changes in the tests look good.

File: model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java [hunk 1]
```diff
@@ -196,6 +195,12 @@ public String getId() {
 
         @ViewChanged
         public void viewChanged(ViewChangedEvent event) {
+            if (localExecutor.isShutdown()) {
```
[the remark this answers is not in the document]
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java:198]: I had a look at that piece of code. I see that this is only called from the test suite. Look at the Exception handling in these places it looks weird to me, and I would need some help to do an analysis here. 

I don't see that this creates unnecessary warnings and error messages for the model tests, therefore I'd see this as unrelated to the ticket. 

If you want to keep it as part of this ticket as a refactoring, I'd be happy to team up with you to have a look at the code what should be returned here if the localExecutor has already been shut down.

Please let me know what you think.

**Comment by martin-kanis** [comment]
@ahus1 Failures in Cross-DC tests are maybe related to this https://developer.jboss.org/thread/239373

File: model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (mhajas) [reply model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java:198]: Sorry for the late response. Yes, I think you are right. I didn't realize this is called only from the testsuite.

**Review by martin-kanis — DISMISSED** [review]
Thanks @ahus1! Log size reduced from ~108MB to ~18MB.

**Comment by ahus1** [comment]
Hi @hmlnarik - this PR is ready to be merged. 

The biggest change is in [DefaultExecutorsProviderFactory.java](https://github.com/keycloak/keycloak/pull/10589/files#diff-afccac3c0d30862d947ddc23b9670f7e26dbbf26a4687e7b266fc7f8b538df90) that changes a bounded queue to an unbounded queue; changing a previous commit here https://github.com/keycloak/keycloak/commit/30b3caee9f6bea580f5b916f5eea3fe437268750#diff-afccac3c0d30862d947ddc23b9670f7e26dbbf26a4687e7b266fc7f8b538df90.

Thanks!

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java [hunk 2]
```diff
@@ -189,7 +218,27 @@ public void testPersistenceMultipleNodesClientSessionsAtRandomNode() throws Inte
...
+                while (true) {
+                    try {
+                        clientSessionId = createOfflineClientSession(offlineSessionId, clientIds.get(cid));
+                        break;
+                    } catch (RuntimeException ex) {
+                        // invocation can fail when remote cache is stopping, this is actually part of this test:
+                        // "ISPN000217: Received exception from node-8, see cause for remote stack trace
+                        // IllegalLifecycleStateException: ISPN000324: Cache 'clientSessions' is in 'STOPPING' state and this is an invocation not belonging to an
+                        // on-going transaction, so it does not accept new invocations."
+                        if (ex.getMessage().contains("ISPN000217")) {
```
Comment (hmlnarik) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java:231]: Should this target `ISPN000324` rather than `ISPN000217`? It seems that the current code could mask even valid exceptions.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java [hunk 3]
```diff
@@ -160,6 +163,32 @@ public void testPersistenceMultipleNodesClientSessionAtSameNode() throws Interru
...
+            try {
+                intermediate.await();
+            } catch (InterruptedException e) {
+                Thread.currentThread().interrupt();
+                throw new RuntimeException(e);
+            }
+
+            // defer the shutdown and check if all sessions exist to ensure that they replicate across the different nodes
+            // this should avoid an "org.infinispan.remoting.transport.jgroups.SuspectException: ISPN000400: Node node-XX was suspected"
+            while (true) {
```
Comment (hmlnarik) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java:178]: Rather than indefinite `while`, there should be some timeout / maximum iteration count

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java [hunk 4]
```diff
@@ -160,6 +163,32 @@ public void testPersistenceMultipleNodesClientSessionAtSameNode() throws Interru
...
+                    assertOfflineSessionsExist(realmId, clientSessionIds);
+                    break;
+                } catch (AssertionError e) {
+                    log.warn("assertion failed, retrying to see if all sessions exist.");
+                    try {
+                        Thread.sleep(1000);
+                    } catch (InterruptedException ex) {
+                        Thread.currentThread().interrupt();
+                        throw new RuntimeException(e);
+                    }
```
Comment (hmlnarik) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java:189]: This occurs in several places. Could this be extracted into a method, e.g. `interruptibleSleep(int timeMs)`

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java (hunk 2 above)
Comment (ahus1) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java]: I changed the code to look in the nested exception with the `ISPN000324`. Please re-review.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java (hunk 3 above)
Comment (ahus1) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java:178]: This is already wrapped in a timeout for the `inIndependentFactories`. I'd rather let this timeout catch this, so that the result shows in the stacktrace where it timed out. This allows me to keep the code simpler. Please confirm.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java (hunk 4 above)
Comment (ahus1) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java]: Done. I named it "sleep" as there is no other sleep around to make it more specific. Please re-review.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java (hunk 3 above)
Comment (hmlnarik) [reply testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java:178]: That makes sense, thanks for explanation

**Comment by ahus1** [comment]
@hmlnarik - all review comments are now implemented. The current build failed for model tests and quickstarts as the version number changed to "999-SNAPSHOT", therefore this is not relevant here. Thanks.

**Review by hmlnarik — APPROVED** [review]
Thanks for the changes!
