### PR TITLE
Avoiding nip.io for stability

### LINKED ISSUE #38104: Temporary failure in name resolution with nip.io
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
Error: Errors: 
Error:  SamlReverseProxyTest » Runtime java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: Temporary failure in name resolution
```
```
Error: Errors: 
Error: org.keycloak.testsuite.cookies.DefaultCookieProviderTest.testCookieDefaultsWithInsecureContext
Error:  Run 1: DefaultCookieProviderTest.testCookieDefaultsWithInsecureContext:70 » Processing RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: 127.0.0.1.nip.io: Temporary failure in name resolution
Error:  Run 2: DefaultCookieProviderTest.testCookieDefaultsWithInsecureContext:70 » Processing RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: 127.0.0.1.nip.io
Error:   Run 3: DefaultCookieProviderTest.testCookieDefaultsWithInsecureContext:70 » Processing RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: 127.0.0.1.nip.io
```

https://github.com/keycloak/keycloak/actions/runs/13836394668/job/38715546968
https://github.com/keycloak/keycloak/actions/runs/13836394668/job/38715544781

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #38104

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/AbstractSamlTest.java [hunk 1]
```diff
@@ -73,6 +74,7 @@ public abstract class AbstractSamlTest extends AbstractAuthTest {
 
     static {
         try {
+            CryptoIntegration.init(Thread.currentThread().getContextClassLoader());
```
Comment (ahus1) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/AbstractSamlTest.java:77]: In case you are wondering: This was necessary to run `SamlReverseProxyTest` isolated from the CLI, as then the crypto integration wasn't initialized yet. This call doesn't do any harm if it isn't initialized yet.

**Review by mhajas — COMMENTED** [review]
I am not sure we can do this. The purpose of nip.io usage is to simulate usage of a real domain in browser. Cookies for `0.0.0.0` may be handled differently, like it is possible secure cookies are sent also to insecure context when 0.0.0.0 is used.

**Comment by ahus1** [comment]
For the cookie provider test, `0.0.0.0` is not considered a secure context as long as no https is used, so IMHO it is equivalent to `.nip.io` and it is not considered a localhost address. I see this regularly when opening that URL in the browse locally and the APIs to copy to the clipboard are regularly not working. 

For the reverse proxy it doesn't matter as there are both http and https test. And using `0.0.0.0` didn't work here, as the client will be connecting via the public address, and then the tests will fail.

**Comment by ahus1** [comment]
@jonkoops - AFAIK you have been involved in the discussion about secure vs. non-secure contexts. Maybe you can help to assess this change.

**Comment by jonkoops** [comment]
`0.0.0.0` is not considered a secure context ([see specification](https://w3c.github.io/webappsec-secure-contexts/)), so I agree with @ahus1's assessment that this is likely equivalent. We only need to be careful with tests that might do cross-origin requests (need to be on different domains), as those might result in a different result for setting cookies, but I see no such changes here at this time.

Note that `127.0.0.1` (previously `proxy.kc.127.0.0.1.nip.io`) is considered a secure context, but I am not quite sure if the context for the reverse proxy was ever used in a secure manner anywhere that impacts user-agents.

**Review by mhajas — APPROVED** [review]
Thanks for the fix!
