### PR TITLE
fixed pagination on the sessions tab

### LINKED ISSUE #20835: There is no server side pagination for sessions
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

There are 2 query strings (first, max) for pagination session api: `/auth/admin/realms/bbl/ui-ext/sessions?first=0&max=11&type=ALL&search=`, but the api returns session count is greater than max value. We have huge sessions, and the session api returns over 50M data.

CleanShot 2023-06-07 at 14 57 51

### Version

21.1.1

### Expected behavior

Sessions should be paged on server side.

### Actual behavior

see the bug description

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #20835

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]

File: rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java [hunk 1]
```diff
@@ -75,8 +73,7 @@ public Stream<SessionRepresentation> realmSessions(@QueryParam("type") @DefaultV
                     .keySet().stream().map(i -> new SessionId(i, OFFLINE)));
         }
 
-
-        final List<SessionId> sessionIds = clientIds.skip(first).limit(max).collect(Collectors.toList());
+        final List<SessionId> sessionIds = clientIds.collect(Collectors.toList());
```
Comment (sschu) [inline rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java:76]: Is this transformation into a List<> really necessary here? As far as I can see, it is just iterated over so it could just be used as a stream...

Comment (edewit) [reply rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java]: you are right, changed that

**Review by sschu — APPROVED** [review]
The java changes look good to me.

**Review by jonkoops — APPROVED** [review]
