### PR TITLE
Make user attribute option for SAML mappers required

### LINKED ISSUE #37648: User Attribute option of SAML "User Attribute Mapper for NameID" should be required
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

For this SAML mapper, User Attribute should be a required field.

Image

It doesn't make sense for this mapper to have a null User Attribute.  And according to reports, it leads to a NullPointerException on the server:

```
2025-02-20 15:06:41,209 WARN  [org.keycloak.services] (executor-thread-116) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.keycloak.storage.ldap.mappers.UserAttributeLDAPStorageMapper$3.getFirstAttribute(UserAttributeLDAPStorageMapper.java:366)
```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

User Attribute required

### Actual behavior

User Attribute not required

### How to Reproduce?

1. Create a client scope with protocal SAML
2. Go to the Mappers tab
3. Add mapper by configuration
4. Select "User Attribute Mapper For NameID"
5. Observe `User Attribute` field that should be mandatory

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #37648

The PR just adds the `required` attribute and the user profile list type to the user attribute in the three SAML mappers. But I detected that the `⚠ Required field` error message was not displayed in the UI because the `errors` variable has an intermediate `config` key and it's not detected in the array `errors[convertedName!]`. I just fixed that doing a quick fix, please @keycloak/ui check if you see something better for this.

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]
Approving, but will require from UI team.

File: js/apps/admin-ui/src/components/dynamic/UserProfileAttributeListComponent.tsx [hunk 1]
```diff
@@ -46,6 +46,10 @@ export const UserProfileAttributeListComponent = ({
 
   if (!config) return null;
 
+  const getError = (record: any, path: string) => {
+    return path.split(".").reduce((record, item) => record?.[item], record);
+  };
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/dynamic/UserProfileAttributeListComponent.tsx:51]: This can probably be typed a bit stronger:

```suggestion
  const getError = (record: FieldErrors<FieldValues>, path: string) => {
    return path.split(".").reduce((record, item) => record?.[item], record);
  };
```

However, since the `errors` variable is already in the scope of this function, there is no need to pass it as an argument:

```suggestion
  const getError = (path: string) => {
    return path.split(".").reduce((errors, item) => record?.[item], errors);
  };
```

If this runs into some type errors, it is best to cast it at the last moment, so the type is preserved as much as possible.

Comment (rmartinc) [reply js/apps/admin-ui/src/components/dynamic/UserProfileAttributeListComponent.tsx]: Done! Both arguments are defined so I have just removed them. The argument is transformed into `any` in the reduce.

**Review by jonkoops — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving based on previous reviews
