### PR TITLE
Fix test IdentityProviderTest#testSamlImportWithAnyEncryptionMethod

### LINKED ISSUE #28575: Flaky test: org.keycloak.testsuite.admin.IdentityProviderTest#testSamlImportWithAnyEncryptionMethod
## org.keycloak.testsuite.admin.IdentityProviderTest#testSamlImportWithAnyEncryptionMethod
[Keycloak CI - Base IT (1)](https://github.com/keycloak/keycloak/actions/runs/8623959055/job/23638302720)

```
java.lang.AssertionError: identityProviders instance count expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.keycloak.testsuite.admin.IdentityProviderTest.testSamlImport(IdentityProviderTest.java:761)
...
```

NOTE: Probably same issue (or same cause) like https://github.com/keycloak/keycloak/issues/28577

### LINKED ISSUE #28576: Flaky test: org.keycloak.testsuite.admin.IdentityProviderTest#testSamlImportWithAnyEncryptionMethod
## org.keycloak.testsuite.admin.IdentityProviderTest#testSamlImportWithAnyEncryptionMethod
[Keycloak CI - Store IT (aurora-postgres)](https://github.com/keycloak/keycloak/actions/runs/8623959055/job/23638308017)

```
java.lang.AssertionError: identityProviders instance count expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.keycloak.testsuite.admin.IdentityProviderTest.testSamlImport(IdentityProviderTest.java:761)
...
```

NOTE: Probably same issue (or same cause) like #28577

### LINKED ISSUE #28577: Flaky test: org.keycloak.testsuite.admin.IdentityProviderTest#testSamlImportWithAnyEncryptionMethod
## org.keycloak.testsuite.admin.IdentityProviderTest#testSamlImportWithAnyEncryptionMethod
[Keycloak CI - Store IT (mariadb)](https://github.com/keycloak/keycloak/actions/runs/8623959055/job/23638307642)

```
java.lang.AssertionError: identityProviders instance count expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.keycloak.testsuite.admin.IdentityProviderTest.testSamlImport(IdentityProviderTest.java:761)
...
```

# Details

This is very likely caused by https://github.com/keycloak/keycloak/commit/a40a9536444ecdc8ce8ff86a1c7e36df99517beb . Hence adding to Keycloak 25 as important and moving to `core-clients`.

Fixing this one will probably also fix #28576 and #28575 , which look like duplicate issues.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #28577
Closes #28576
Closes #28575

The addition of the new test showed an issue with an older one that was not removing the created identity provider. I suppose the order of executions is meaningful to work or not. Just adding the provider for cleanup in the other test.

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java [hunk 1]
```diff
@@ -458,6 +458,7 @@ public void failUpdateInvalidUrl() throws Exception {
 
             try (Response response = realm.identityProviders().create(representation)) {
                 assertEquals(Response.Status.CREATED.getStatusCode(), response.getStatus());
+                getCleanup().addIdentityProviderAlias(representation.getAlias());
```
Comment (hmlnarik) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java:461]: You could perhaps leverage [`Creator.create`](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/Creator.java#L115) in the outer `try` instead.

Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java]: I used the private `create` method in the same class as it's what all the other methods are doing. If you prefer the `Creator.create` let me know.

Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java]: I waiter the test to finish to check that the `IdentityProviderTest` test didn't fail in the initial run.

**Review by mposolda — APPROVED** [review]
@rmartinc @hmlnarik Thanks for the update and review! I am merging in order to have flaky test fixed asap as it is failing in lots of PRs and the approach of using `create` methods used by all other tests is ok as it is also checking the event.
