### PR TITLE
Use back keycloak-js instead of initiate login in the backend for account

### LINKED ISSUE #40463: Login to Account Console produces two consecutive LOGIN events
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When an unauthenticated user logins in to the account console Keycloak will generate two separate consecutive LOGIN events.

### Version

26.2.5

### Regression

- [x] The issue is a regression

### Expected behavior

Keycloak should only generate one LOGIN event when an unauthenticated user performs a login for the account-console client.

### Actual behavior

Keycloak generates two LOGIN events when an unauthenticated user performs a login for the account-console client.

### How to Reproduce?

0) Enable event storage
1) Login to account-console
2) Observe two LOGIN events created for the account-console.

### Anything else?

Keycloak Versions before v26.1.0 only one LOGIN event was produces for the account-console.

This was caused by my change in this PR: https://github.com/keycloak/keycloak/pull/32686
This only affects the account-console, other clients produce only one LOGIN event.

The Problem is that if we detect an unauthenticated user accessing the /account endpoint, we redirect the user to a generated authorize URL to spare the bootstrappung of the "heavy" react JS app which would then redirect the user.
The user now sees the login page and can authenticate. After successful authentication the user is sent back to the account console. This produces the first LOGIN event.
This time, we can detect the existing user session and this start to bootstrap the react JS app. The react JS app then performs the "real" auth code flow in the context of the already authenticated user session, which is then immediately redirected back to the account-console. This produces the second LOGIN event.

The following shows an example event sequence for different OIDC client:
Image 1:
Image
.. and here is an event sequence for the account-console:
Image 2:
Image

This leads to double counting of LOGIN events if users login to the account-console client.

I see the following options:
1) somehow suppress the second "Event 2" shown in Image 2 for the account-console client
2) handle the code-flow / token-management for the account-console on the account backend
3) add additional event_details metadata about the LOGIN TYPE (e.g. interactive, session)

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #40463

After checking this I think the only way of doing this OK without changing things a lot is going back and use `keycloak-js` normally again. If I understood this correctly, the initial issue #31469 was reported because the console was displayed empty, and the login was requested later when the login was required for the first request (401). This PR does the following:

* The backend does not initiate the login. This part is removed because it's a mess. This is the first login and then the account console uses `keycloak-js` to login again (automatically now because cookies are in place), but it was a second round-trip in events. The JS part cannot use the state or code verifier generated by the backend. It makes no sense.
* The applications now in `ui-shared` always initiates the login if not already authenticated. This way nothing is displayed (just the `spinner`) and if the redirect is needed, from the spinner you go to the login page. Nothing is shown except the spinner if you are not logged in. The shared part is used for both consoles (admin and account).
* The problem is that there are a lot tests that thinks that there will be an automatic redirect for the account console. As `keycloak-js` is used we need a real browse (firefox or chrome) to execute the JS needed to login. I have changed those tests to use other thing instead of the account console.
* The `AccountConsoleTest` is the only test that really checks the account functionality This one is moved to the `forms` package to be used with firefox and chrome. The scopes are correctly respected. The only little difference is that the `keycloak-js` always adds `openid`, but I think that this is OK.
* I have also changed the error representation. The current setup shows anything in the `error_description` returned. The only error accepted now is a JS `Error` or the `error` generated bye `keycloak-js`. As the `error` is standard I have provided the translations for it, and only the standard errors are displayed. Other unknown error uses always the same message.

It's a draft for now. Because maybe you see another approach (but I really don't see anything better than this).

### CODE REVIEW

File: js/libs/ui-shared/src/context/KeycloakContext.tsx [hunk 1]
```diff
@@ -74,20 +74,23 @@ export const KeycloakProvider = <T extends BaseEnvironment>({
       });
 
     init()
```
Comment (jonkoops) [inline js/libs/ui-shared/src/context/KeycloakContext.tsx]: Instead of ensuring the user is authenticated by doing so manually, it is possible to set `onLoad` to `"login-required"`. This will ensure that if the user is not authenticated, they will be redirected to the login page.

Comment (rmartinc) [reply js/libs/ui-shared/src/context/KeycloakContext.tsx]: Done!

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
@rmartinc I am moving this out of draft in your absence, I agree with the approach here. I'll have some other reviewers check this out as well.

**Review by pedroigor — APPROVED** [review]
I agree about the mess. The discussions at that time were basically changing UIs vs backend, whereas the UI was, in theory, too hard to change in order to avoid rendering the React app when users are not yet authenticated.

If we are still handling errors properly and the spinner is shown instead of initing the React app, LGTM.
