### PR TITLE
Determine root distribution directory properly from ZIP file itself.

### LINKED ISSUE #43356: Keycloak tests framework - issue to identify distribution directory inside ZIP file when version string uses suffix
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

Class RawKeycloakDistribution using version string in filename of the `zip` distribution to construct distribution home directory.
This is not correct when version with suffix is used. 
It prevents tests run at all.

### Version

26.2.9

### Regression

- [ ] The issue is a regression

### Expected behavior

Test framework should determine the home directory automatically from the zip file and not based on zip's filename.

### Actual behavior

It fails to start Keycloak Server from described distribution zip file.

### How to Reproduce?

Set version of keycloak sources to `26.2.9-custom-2` and run build and tests.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pskopek**
Closes #43356

### CODE REVIEW

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java [hunk 1]
```diff
@@ -494,22 +498,38 @@ private void reset() {
...
+            Optional<? extends ZipEntry> e = zipFile.stream().filter(ZipEntry::isDirectory).findFirst();
+            if (e.isPresent()) {
+                String dirName = e.get().getName();
+                if (dirName.contains("..")) {
+                    throw new RuntimeException("inside zip distribution directory cannot contain relative paths: " + dirName);
+                }
+                return Path.of(dirName);
+            }
+        };
+        throw noDirectories.get();
```
Comment (mabartos) [inline quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]:
```suggestion
        throw new RuntimeException(String.format("ZIP file '%s' doesn't contain any directories", distPath));
```

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java [hunk 2]
```diff
@@ -494,22 +498,38 @@ private void reset() {
         keycloak = null;
     }
 
+    private Path inDistZipDirectory(File distFile) throws Exception{
+        Supplier<RuntimeException> noDirectories = () -> new RuntimeException(String.format("ZIP file %s doesn't contain any directories", distPath));
```
Comment (mabartos) [inline quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java]:
```suggestion
      
```

nitpick: I don't think we need the supplier here.

**Review by mabartos — COMMENTED** [review]
@pskopek Thanks for the PR! I just added a small nitpick - no blocker.

**Review by mabartos — APPROVED** [review]
