### PR TITLE
Detect and handle KC split brain clusters

### LINKED ISSUE #41561: Detect and handle KC split brain clusters
### Description

If there is a network split between KC nodes while the KC nodes can still talk to the database, their caches will get out-of-sync, and they might deliver possibly wrong results based on outdated caches. 

### Discussion

_No response_

### Motivation

Make it safe to run Keycloak even in split brain environments. 

### Details

If an isolated node can't talk to the database, it will already mark itself not-ready, and will then no longer serve traffic.

### PR DESCRIPTION
**Pull request by pruivo**
Closes #41561

- [x] docs?

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/health/KeycloakClusterReadyHealthCheck.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+            failingSince.set(null);
+        } else {
+            builder.down();
+            Instant failingTime = failingSince.updateAndGet(KeycloakReadyHealthCheck::createInstanceIfNeeded);
+            builder.withData(FAILING_SINCE, DATE_FORMATTER.format(failingTime));
+        }
+        return Uni.createFrom().item(builder.build());
+    }
+
+
```
Comment (ryanemerson) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/health/KeycloakClusterReadyHealthCheck.java]: Nitpick: Redundant whitespace.

File: model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/ClusterHealthFactory.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+import org.keycloak.infinispan.health.impl.ClusterHealthImpl;
+
+@DefaultFactoryFor(classes = ClusterHealth.class)
+public class ClusterHealthFactory extends AbstractComponentFactory implements AutoInstantiableFactory {
+
+    @Override
+    public Object construct(String componentName) {
+        return new ClusterHealthImpl();
+    }
+
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/ClusterHealthFactory.java]: Nitpick: Redundant whitespace.

File: model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/ClusterHealthFactory.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+package org.keycloak.infinispan.module.factory;
+
+import org.infinispan.factories.AbstractComponentFactory;
+import org.infinispan.factories.AutoInstantiableFactory;
+import org.infinispan.factories.annotations.DefaultFactoryFor;
+import org.keycloak.infinispan.health.ClusterHealth;
+import org.keycloak.infinispan.health.impl.ClusterHealthImpl;
+
+@DefaultFactoryFor(classes = ClusterHealth.class)
+public class ClusterHealthFactory extends AbstractComponentFactory implements AutoInstantiableFactory {
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/ClusterHealthFactory.java:27]: We should add `@SuppressWarnings("unused")`.

File: model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+            logger.debug("Cluster health check disabled. Local mode");
+            return;
+        }
+        if (!(transport instanceof JGroupsTransport jgrp)) {
+            logger.debug("JGroups Transport not found. Unable to check cluster health.");
+            return;
+        }
+        KEYCLOAK_JDBC_PING2 ping = jgrp.getChannel().getProtocolStack().findProtocol(KEYCLOAK_JDBC_PING2.class);
+        if (ping == null) {
+            logger.debug("Stack 'jdbc-ping' not used. Unable to check cluster health.");
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: Should we add this is as a warning log? It might encourage users to migrate to `jdbc-ping` as they get additional capabilities.

File: model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java [hunk 5]
```diff
@@ -0,0 +1,137 @@
...
+            r.trigger();
+        }
+    }
+
+    private record HealthRunner(KEYCLOAK_JDBC_PING2 discovery, Executor executor, Consumer<KEYCLOAK_JDBC_PING2> check) {
+
+        HealthRunner {
+            Objects.requireNonNull(discovery);
+            Objects.requireNonNull(executor);
+        }
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: Do we need these checks given that it's only used internally? Could we just use `assert` in `#inject` or just not check as a NPE will be thrown eventually anyway.

File: model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java [hunk 6]
```diff
@@ -242,4 +242,58 @@ protected Connection getConnection() {
...
+     *     <li>If multiple coordinators are found, it compares them and uses the coordinator with the lowest {@link UUID}</li>
+     *     <li>Finally, it compares if the coordinator is the same as the current view coordinator. If so, it returns {@link HealthStatus#HEALTHY}, otherwise {@link HealthStatus#UNHEALTHY}</li>
+     * </ul>
+     *
+     * @return The {@link HealthStatus}.
+     * @see HealthStatus
+     */
+    public HealthStatus isHealthy() {
+        try {
+            // maybe create an index, and a query to return coordinators only?
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java:265]: I think this makes sense in theory, but is it overkill in reality given that Keycloak apparently struggles to scale well past several nodes?

I guess adding the index now means that's one less problem we need to solve if/when we try to improve horizontal scaling.

File: model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java [hunk 7]
```diff
@@ -242,4 +242,58 @@ protected Connection getConnection() {
...
+                    .stream()
+                    .filter(PingData::isCoord)
+                    .map(PingData::getAddress)
+                    .sorted()
+                    .findFirst()
+                    .map(view.getCoord()::equals)
+                    .map(isCoordinatorInView -> isCoordinatorInView ? HealthStatus.HEALTHY : HealthStatus.UNHEALTHY)
+                    .orElse(HealthStatus.NO_COORDINATOR);
+        } catch (Exception e) {
+            // database failed?
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java:276]: Debug log?

File: model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java [hunk 8]
```diff
@@ -242,4 +242,58 @@ protected Connection getConnection() {
...
+     *     <li>Filters out non coordinator members</li>
+     *     <li>If no coordinator is found, it return {@link HealthStatus#NO_COORDINATOR}</li>
+     *     <li>If multiple coordinators are found, it compares them and uses the coordinator with the lowest {@link UUID}</li>
+     *     <li>Finally, it compares if the coordinator is the same as the current view coordinator. If so, it returns {@link HealthStatus#HEALTHY}, otherwise {@link HealthStatus#UNHEALTHY}</li>
+     * </ul>
+     *
+     * @return The {@link HealthStatus}.
+     * @see HealthStatus
+     */
+    public HealthStatus isHealthy() {
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java]: As this doesn't return a boolean, I would rename to something like `healthStatus()` or `status()`.

File: model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java [hunk 9]
```diff
@@ -0,0 +1,137 @@
...
+                    break;
+                case NO_COORDINATOR:
+                    logger.warn("Unable to check the cluster health because no coordinator has been found.");
+                    // fallthrough
+                case UNHEALTHY:
+                    logger.debug("Set cluster health status to unhealthy");
+                    healthy = false;
+                    break;
+                case ERROR:
+                    // do not change the state
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: Redundant comment given the log below?

File: model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java [hunk 10]
```diff
@@ -0,0 +1,137 @@
...
+        }
+    }
+
+    @Override
+    public boolean isHealthy() {
+        return healthy;
+    }
+
+    @Override
+    public void triggerClusterHealCheck() {
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: `s/triggerClusterHealCheck/triggerClusterHealthCheck`

File: model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java [hunk 11]
```diff
@@ -0,0 +1,137 @@
...
+        HealthRunner r;
+        if ((r = runner) != null) {
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: Why do we need the assignment here, can't we just do:

```java
if (runner != null) runner.trigger();
```

File: model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java [hunk 12]
```diff
@@ -290,10 +291,16 @@ public Map<String, String> getOperationalInfo() {
         return info;
     }
 
+    @Override
+    public boolean isClusterHealthy() {
+        clusterHealth.triggerClusterHealCheck();
+        return clusterHealth.isHealthy();
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:310]: The default operator configuration for the StatefulSet uses a timeout of 10 seconds, so in this case it will be 20 seconds until the split-brain is detected by the readiness probe as the first call to this method will result in `true` being returned?

File: model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java [hunk 13]
```diff
@@ -0,0 +1,137 @@
...
+ * <p>
+ * The method {@link KEYCLOAK_JDBC_PING2#isHealthy()} contains the algorithm description. If it returns
+ * {@link HealthStatus#ERROR}, the healthy state does not change and relies on the Quarkus/Agroal readiness health
+ * check. But, if {@link HealthStatus#NO_COORDINATOR} is returned, the state will be changed to unhealthy. The should be
+ * a temporary situation as at least one coordinator must be present in the database table.
+ *
+ * @see KEYCLOAK_JDBC_PING2#isHealthy()
+ */
+@Scope(Scopes.GLOBAL)
+public class ClusterHealthImpl implements ClusterHealth {
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: As this is tightly coupled with JDBC_PING2, how about `JdbcPingClusterHealthImpl`?

**Review by ryanemerson — CHANGES_REQUESTED** [review]
We need to update `docs/guides/observability/health.adoc#available-checks` to document the health check.

File: model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/ClusterHealthFactory.java (hunk 3 above)
Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/ClusterHealthFactory.java:27]: I don't have any warning in mine.

File: model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java (hunk 5 above)
Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: The `assert` is disabled in production and, without this, the NPE will be thrown by a blocking thread, which will have no useful stack traces.

File: model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java (hunk 6 above)
Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java:265]: Just some idea that crossed my mind, but I don't think it is worth it. I don't think a database would have problems querying a table with a single-digit number of rows (famous last words).

File: model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/ClusterHealthFactory.java (hunk 3 above)
Comment (ryanemerson) [reply model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/ClusterHealthFactory.java:27]: It's because I hadn't compiled the branch. Once compiled it goes away as we have the generated code using it.

File: model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java (hunk 12 above)
Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java:310]: It depends on the failure threshold. What you describe is the minimum time to mark it not ready.

File: model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java (hunk 5 above)
Comment (ryanemerson) [reply model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: Understood about `assert`, I just meant so we had this check in our repo. I don't think that's necessary tbh, as in the production code it's us that passes the inputs, so we know they're not `null`:

```java
        if (ping == null) {
            logger.debug("Stack 'jdbc-ping' not used. Unable to check cluster health.");
            return;
        }

        logger.debug("Cluster Health check available");
        init(ping, blockingManager.asExecutor("cluster-health"));
```

Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: The method is public, and users may do all kinds of crazy stuff.

Comment (ryanemerson) [reply model/infinispan/src/main/java/org/keycloak/infinispan/health/impl/ClusterHealthImpl.java]: On a class in an `impl` package ... anyway, no harm leaving the check if you prefer. I just thought it was adding verbosity for little benefit.

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 14]
```diff
@@ -790,16 +790,23 @@ void disableHealthCheckBean(BuildProducer<BuildTimeConditionBuildItem> removeBea
             ClassInfo disabledBean = index.getIndex()
                     .getClassByName(DotName.createSimple(KeycloakReadyHealthCheck.class.getName()));
             removeBeans.produce(new BuildTimeConditionBuildItem(disabledBean.asClass(), false));
-            ClassInfo clusterHealth = index.getIndex().getClassByName(DotName.createSimple(KeycloakClusterReadyHealthCheck.class));
-            removeBeans.produce(new BuildTimeConditionBuildItem(clusterHealth.asClass(), false));
+        } else if (!isHealthEnabled()) {
+            // health enabled / metrics disabled
```
Comment (ryanemerson) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java]: Is this possible, won't we always go into the first if branch as we're using `||` not `&&` ?

As we always invert these methods, I think we can make this easier to read by changing the methods to `isHealthDisabled` and `isMetricsDisabled`.

Comment (pruivo) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java]: done

File: model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java [hunk 15]
```diff
@@ -242,4 +242,59 @@ protected Connection getConnection() {
...
+                    .filter(PingData::isCoord)
+                    .map(PingData::getAddress)
+                    .sorted()
+                    .findFirst()
+                    .map(view.getCoord()::equals)
+                    .map(isCoordinatorInView -> isCoordinatorInView ? HealthStatus.HEALTHY : HealthStatus.UNHEALTHY)
+                    .orElse(HealthStatus.NO_COORDINATOR);
+        } catch (Exception e) {
+            // database failed?
+            log.debug("Failed to fetch the cluster members fromm the database.", e);
```
Comment (ahus1) [inline model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java]:
```suggestion
            log.warn("Failed to fetch the cluster members from the database.", e);
```

File: model/infinispan/src/test/java/org/keycloak/jgroups/protocol/ControlledJdbcPing.java [hunk 16]
```diff
@@ -0,0 +1,56 @@
...
+
+package org.keycloak.jgroups.protocol;
+
+import java.util.List;
+
+import org.jgroups.Address;
+import org.jgroups.View;
+import org.jgroups.protocols.PingData;
+
+/*
```
Comment (ahus1) [inline model/infinispan/src/test/java/org/keycloak/jgroups/protocol/ControlledJdbcPing.java]:
```suggestion
/**
```

File: docs/guides/observability/health.adoc [hunk 17]
```diff
@@ -40,7 +40,11 @@ These endpoints respond with HTTP status `200 OK` on success or `503 Service Una
     "status": "UP",
     "checks": [
         {
-            "name": "Keycloak database connections health check",
+            "name": "Keycloak cluster health check",
```
Comment (ahus1) [inline docs/guides/observability/health.adoc:43]: The cluster check should only be present if JDBC_PING is enabled, otherwise it would trick people into a false confidence. Maybe CDI can help you here to produce this bean only when the right configuration is present. 

This should also be reflected in the docs both here in the health check, as well as in the single cluster HA guide where we would state that people should use JDBC_PING to detect such splitbrains.

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for this pull request, it looks great for those running JDBC_PING. See below to polish the behavior and the docs for those who are not using it.

File: docs/guides/observability/health.adoc (hunk 17 above)
Comment (pruivo) [reply docs/guides/observability/health.adoc:43]: Infinispan configuration is a runtime option and not a build-time option. I don't want to go through that path.

**Review by ryanemerson — DISMISSED** [review]

File: docs/guides/observability/health.adoc (hunk 17 above)
Comment (ahus1) [reply docs/guides/observability/health.adoc:43]: I found a way to allow a runtime configuration via CDI means. I pushed one more commit, please have a look.

Comment (pruivo) [reply docs/guides/observability/health.adoc:43]: @ahus1 pushed a small change + javadoc, otherwise it looks good to me.

**Review by ryanemerson — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
