### PR TITLE
OIDC Protocol Mappers with same claim

### LINKED ISSUE #25774: OIDC Protocol Mappers with same claim
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

If you have configured two(or more) _OIDC protocol mappers_ with the same _Token Claim Name_, claim will contain only one mapper value!
Claim value must be unique (not allowed duplication values) combination of both mappers value. From this behaviour we need to exclude primary claims ("name", "given_name", "family_name", "preferred_username", "email").

This works for attribute value in _SAML protocol mapper_.

### Version

22.0.5

### Expected behavior

If you have configured two(or more) _OIDC protocol mappers_ with the same _Token Claim Name_, claim value will be combination of both mappers value.

### Actual behavior

If you have configured two(or more) _OIDC protocol mappers_ with the same _Token Claim Name_, claim will contain only one mapper value!

### How to Reproduce?

Create two _OIDC protocol mappers_ with same _Token Claim Name_ and _Add to access token_ equal to true.
Get access token and see claim value.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
Closes #25774

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java [hunk 1]
```diff
@@ -309,8 +311,24 @@ private static void mapClaim(List<String> split, Object attributeValue, Map<Stri
         int i = 0;
         for (String component : split) {
             i++;
-            if (i == length) {
+            if (i == length && length == 1 && primaryClaims.contains(split.get(0))) {
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java:314]: Instead of using the hard-coded `primaryClaims` list maybe we can better rely on the multi-valued configuration option. Those primary claims will never be defined as multi (and if they are they are probably wrong defined). You can pass the model to the method because it's private without problems.

@cgeorgilakis WDYT? Do you see any problem with that approach?

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @cgeorgilakis for the PR!

I have just added one comment because I don't like the hard-coded `primaryClaims` list. My proposal is using the `isMultivalued` from the config option. Let me know if you see any problem with that idea.

**Comment by cgeorgilakis** [comment]
> Thanks @cgeorgilakis for the PR!
> 
> I have just added one comment because I don't like the hard-coded `primaryClaims` list. My proposal is using the `isMultivalued` from the config option. Let me know if you see any problem with that idea.

I agree and I have changed it. Tests are ok.

File: services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java [hunk 2]
```diff
@@ -307,16 +308,32 @@ private static <T> void mapClaim(T token, ProtocolMapperModel mappingModel, Obje
...
     }
 
-    private static void mapClaim(List<String> split, Object attributeValue, Map<String, Object> jsonObject) {
+    private static void mapClaim(List<String> split, Object attributeValue, Map<String, Object> jsonObject, boolean isMultivalued) {
         final int length = split.size();
         int i = 0;
         for (String component : split) {
             i++;
-            if (i == length) {
+            if (i == length && length == 1 && !isMultivalued) {
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java:319]: I don't understand the `length == 1` here, is it needed? The attribute should be appended if multi-valued no matter if the claim is `claim` or `complex.claim` (length of the split), am I right?

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @cgeorgilakis! I have just one more doubt about the PR...

File: services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java (hunk 2 above)
Comment (cgeorgilakis) [reply services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java]: You are right. I have been removed  it.

**Review by rmartinc — APPROVED** [review]
Thanks @cgeorgilakis! LGTM now...

**Review by pedroigor — APPROVED** [review]
