### PR TITLE
fix: limit the use of Resteasy to the KeycloakSession

### LINKED ISSUE #28152: Limit the use of Resteasy static methods to the KeycloakSession
### Description

To clarify the responsibilities of the Resteay static methods we should look to limit what is coming from the provider and what is potentially available via the threadlocal. I propose we shoot for making just the KeycloakSession available via this logic.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #28152

contextualizes other state to the KeycloakSession

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]
LGTM

**Comment by pedroigor** [comment]
It is a nice improve towards the goal of decoupling our code base from the underlying JAX-RS implementation ...

**Comment by shawkins** [comment]
@pedroigor added some javadocs to indicate what's now expected of the Resteasy static methods - we can of course consider an alternative to this class and just deprecate the whole thing.

Also carried over some of the minor changes from the other pr like eliminating the TransactionalSessionHandler.

Also added some cleanup of the state retained by the KeycloakSession on close.

**Comment by shawkins** [comment]
@pedroigor another option to consider is just casting the KeycloakContext to DefaultKeycloakContext (or adding setters) and setting the members like request and response directly - we may not even need to expose / use a general context map.

**Comment by pedroigor** [comment]
>Also carried over some of the minor changes from the other pr like eliminating the TransactionalSessionHandler.
>Also added some cleanup of the state retained by the KeycloakSession on close.

You are already making big changes, we can certainly discuss those in a separate issue/PR, I would say ..

**Comment by shawkins** [comment]
> You are already making big changes, we can certainly discuss those in a separate issue/PR, I would say ..

Sorry, I was pulling in what seemed to be benign changes (to localize the session create / close), but they can be backed out if needed.

Based upon your concern with clearning the KeycloakContext I've updated things to instead be based upon directly setting the member variables that would come from the context - this means that KeycloakContext.getContextObject is no longer used internally and KeycloakContext.putContextObject no longer needs added.

Long story short:
- Via Resteasy we provide access to the KeycloakSession via the RoutingContext because it could be used over multiple threads. However if it is used this way, then access is lost to the thread bound transaction.
- Via Resteasy we can also maniplute a threadlocal for the KeycloakSession - this is primarily needed when we switch from one thread to another via some task.
- We don't need any other providers because the threadlocal suffices as the general implemenation. If we instead assume the KeycloakSession to be threadbound even in the vertx case, then we don't need the vertx provider either.
- Any other manipulation of the context is directly on the KeycloakContext associated with the KeycloakSession.
- The changes stop short of trying to have the logic generalize the context propogation used in the ArtifactResolutionRunnable. If this becomes more prevelant (it looks to only also exist now in EmailEventListenerProvider), we could consider pulling that logic further up into ScheduledTaskRunner / KeycloakModelUtils so this happens automatically.

File: server-spi/src/main/java/org/keycloak/models/KeycloakContext.java [hunk 1]
```diff
@@ -55,6 +55,12 @@ public interface KeycloakContext {
 
     HttpHeaders getRequestHeaders();
 
+    /**
+     * Will always return null
+     *
+     * @deprecated
+     */
+    @Deprecated
```
Comment (mabartos) [inline server-spi/src/main/java/org/keycloak/models/KeycloakContext.java:63]:
```suggestion
    /**
     * Will always return null
     *
     * @deprecated obtaining contextual data is limited and you should refer to a current context provider (f.e. Resteasy.getContextData)
     */
    @Deprecated(forRemoval = true)
```

We should possibly explain more current status, right? I find marking `forRemoval=true` more visible in the deprecation process. @shawkins WDYT?

**Review by mabartos — COMMENTED** [review]
@shawkins In general, LGTM and dealing only with KeycloakSession for the ResteasyProvider context makes sense to me. I've just added a few minor comments. 

However, as we're storing the RestEASY context as `ThreadLocal`, we should also explicitly clear the context data at the end of request processing, right? 

AFAIK, it has a particular impact using ThreadLocal vars with thread pools (present even on the lower levels) as it can still be part of the platform thread (OS thread) memory. Is it correct?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/CloseSessionHandler.java [hunk 2]
```diff
@@ -66,6 +66,9 @@ public void write(OutputStream output) throws IOException, WebApplicationExcepti
     }
 
     private void closeSession() {
-        close(Resteasy.getContextData(KeycloakSession.class));
+        KeycloakSession session = Resteasy.getContextData(KeycloakSession.class);
+        if (session != null && !DefaultKeycloakSession.class.cast(session).isClosed()) {
+            session.close();
+        }
```
[the remark this answers is not in the document]
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/CloseSessionHandler.java:72]: I'll just leave it as is for now, since that's what it has always been. The only reason to change it to an instanceof would be if we introduce some form of mock testing such that the instance isn't actually a DefaultKeyCloakSession.

**Comment by shawkins** [comment]
> However, as we're storing the RestEASY context as ThreadLocal, we should also explicitly clear the context data at the end of request processing, right?

We are by setting it back to the original value. I'm now creating the Map with a capacity of 1 so that any residual memory footprint is minimal - we can of course go further than that if we want to fully eliminate any state.

> AFAIK, it has a particular impact using ThreadLocal vars with thread pools (present even on the lower levels) as it can still be part of the platform thread (OS thread) memory. Is it correct?

The usage of a threadlocal for this purpose is not new. It was part of the ReseasyContext, which until recently was still being used as part of the vertx provider.

File: server-spi/src/main/java/org/keycloak/models/KeycloakContext.java (hunk 1 above)
Comment (shawkins) [reply server-spi/src/main/java/org/keycloak/models/KeycloakContext.java]: Ok, updated with more text. In this method we don't even want to refer them to Resteasy.getContextData as that is only for obtaining the KeycloakSession, which they should already have for this KeycloakContext.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java [hunk 3]
```diff
@@ -1,57 +0,0 @@
...
-import org.keycloak.models.KeycloakTransactionManager;
-import org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory;
-import org.keycloak.services.DefaultKeycloakSession;
-
-/**
- * <p>A {@link TransactionalSessionHandler} is responsible for managing transaction sessions and its lifecycle. Its subtypes
- * are usually related to components available from the underlying stack that runs on top of the request processing chain
- * as well as at the end in order to create transaction sessions and close them accordingly, respectively.
- */
-public interface TransactionalSessionHandler {
```
Comment (pedroigor) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java:31]: I was more talking about why removing this interface as it has a purpose and does not seem related to all the nice changes you are introducing here.

I would keep it for now and have a better discussion in a separate issue/PR if we really want to do so. I know what you are doing with this interface but it was there to help identify the components involved in the transaction lifecycle.

That is the kinda of discussion I would like to avoid now and focus on the key bits you are delivering here.

**Comment by pedroigor** [comment]
> We are by setting it back to the original value. I'm now creating the Map with a capacity of 1 so that any residual memory > footprint is minimal - we can of course go further than that if we want to fully eliminate any state.

@mabartos @shawkins +1 to make sure any state is cleared at the end of the request lifecycle.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/CloseSessionHandler.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/CloseSessionHandler.java:72]: Works for me.

File: server-spi/src/main/java/org/keycloak/models/KeycloakContext.java (hunk 1 above)
Comment (mabartos) [reply server-spi/src/main/java/org/keycloak/models/KeycloakContext.java]: Nice. Yep, I know, the intention behind that was to point users somewhere for more info, but it is better in this form.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java (hunk 3 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/transaction/TransactionalSessionHandler.java]: > I was more talking about why removing this interface as it has a purpose and does not seem related to all the nice changes you are introducing here.

It's just to move the logic closer together as those are the only places those methods are used.

> That is the kinda of discussion I would like to avoid now and focus on the key bits you are delivering here.

No problem, I've put back TransactionalSessionHandler.

**Comment by shawkins** [comment]
There were also a few more changes needed to make the undertow server work again, looks good now.

**Review by mabartos — APPROVED** [review]
@shawkins Thanks! LGTM now. AFAIU, we will not produce any breaking changes. Is it correct?

@pedroigor Could you please make another round of review, once you have a chance?

**Comment by shawkins** [comment]
@mposolda do you want to review as well?

**Comment by shawkins** [comment]
> Thanks! LGTM now. AFAIU, we will not produce any breaking changes. Is it correct?

@mabartos that is correct. Confirmed with @pedroigor that users are not expected to use Resteasy static methods directly anymore, in particular they should not be putting anything of their own into the context.

**Review by pedroigor — APPROVED** [review]
