### PR TITLE
Calculating the correct Expected Destination Path for SAML IDP-initiated SSO flow.

### LINKED ISSUE #32622: InvalidDestination Error for IDP-initiated SSO with Keycloak behind a Reverse Proxy
👍
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

I have been playing with Keycloak behind an Nginx proxy which terminates TLS. I use Okta as my IDP and have tried both SP-initiated and IDP-initiated modes. I have read some blogs around this, but none talk about this specific setup and error - except for one person who did not provide any solution.

I see that the SP-initiated flow works fine with my setup and the [getExpectedDestination](https://github.com/keycloak/keycloak/blob/d63c0fbd138ab0a27f3bb0833ae92e3211146c5c/services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java#L815) function returns the expected Destination properly with Scheme, host, and port similar to the original URL (before TLS termination - what Okta reaches out to).

However, the for IDP-initiated flow, the same function [getExpectedDestination](https://github.com/keycloak/keycloak/blob/d63c0fbd138ab0a27f3bb0833ae92e3211146c5c/services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java#L815) returns the Destination that is "After" the termination (http - not https).

After some tracing of code, I see that the difference between SP and IDP-initiated flows is that the clientId is `null` for SP-initiated flow and therefore the destination is computed with this line of code
```Urls.identityProviderAuthnResponse(session.getContext().getUri().getBaseUri(), providerAlias, realm.getName()).toString();```
However, for IDP-initiated flow, I have a client that I go thru and therefore the clientId is NOT `null` and the destination is computed with the following line of code
```session.getContext().getUri().getAbsolutePath().toString();```

I see that SP-initiated flow works because it is relying on the BaseUri part of the context which is correctly set to the external https URI However, getAbsolutePath() part of the evaluation for IDP-initiated flow returns the 'http' URI.

I think it is a bug in the following line
```session.getContext().getUri().getAbsolutePath().toString();```

The destination is supposed to be built similar to how it is done when `clientId == null`

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

The `getExpectedDestination` function should return the URI that is before the proxy (just like it does when clientID is null).
In this case, the URI with HTTPS and port number used before the reverse proxy. 

### Actual behavior

The returned URI uses the scheme and port AFTER the reverse proxy. In my case, it uses HTTP and 80 as the port.

### How to Reproduce?

Put a TLS-terminating reverse proxy (like NGINX) in front of Keycloak and then set up an IDP-initiated SAML flow with a client defined. Then used an external IDP like Okta to connect directly. The destination URI will not match as the external IDP will put the public-facing address (example - https://auth.example.com:8443/realms/myrealm/protocol/saml/clients/myapp-saml) in the SAML assertion as the destination.
During the handling of the SAML response, the code under function `getExpectedDestination` will compute the expected destination URI as `http://auth.example.com/realms/myrealm/protocol/saml/clients/myapp-saml` if you have forwarded the host in NGINX using 
`proxy_set_header HOST            $host;`

You can see some setup steps for IDP-initiated flow in this blog: https://www.lisenet.com/2020/keycloak-with-okta-idp-initiated-sso-login/

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ManishMehta**
fixes https://github.com/keycloak/keycloak/issues/32622

The expected Destination Path needs to properly point to the client that is created for IDP-initiated SSO flow. This is especially an issue when Keycloak is behind a reverse proxy that terminates TLS.

No Tests are impacted with this change.

### CODE REVIEW

**Comment by jonkoops** [comment]
Could you please add a logical title for your commit and PR that does not include the issue number? If you want to link a PR to an issue you can do so [by using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by ManishMehta** [comment]
> Could you please add a logical title for your commit and PR that does not include the issue number? If you want to link a PR to an issue you can do so [by using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

Thanks @jonkoops 
I have edited the Title and also used "fixes" keyword in the description.

**Comment by jonkoops** [comment]
Thanks, appreciate it :)

**Comment by jonkoops** [comment]
Please do not merge `main` into this PR unless there are conflicts, this just wastes time on CI and keeps spamming notifications. Your PR does not have to be in sync with `main` to be merged.

**Comment by ahus1** [comment]
@mposolda / @rmartinc - this handles a core clients issue that has already been triaged. Please have a look when you have the time.

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
Comment (jonkoops) [inline services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:1]: Could you add some tests to verify this fix?

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java [hunk 1]
```diff
@@ -814,7 +814,7 @@ protected Response handleLogoutResponse(SAMLDocumentHolder holder, StatusRespons
 
         private String getExpectedDestination(String providerAlias, String clientId) {
             if(clientId != null) {
-                return session.getContext().getUri().getAbsolutePath().toString();
+                return Urls.identityProviderAuthnResponse(session.getContext().getUri().getBaseUri(), providerAlias, realm.getName()).toString()+"/clients/"+clientId;
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:817]: Rather than building the path here manually I'd say let's add an overload to the `Urls.identityProviderAuthnResponse()` that accepts a client so that the `URIBuilder` can be re-used.

**Review by jonkoops — CHANGES_REQUESTED** [review]
Can we add some test for this

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java (hunk 1 above)
Comment (ManishMehta) [reply services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java]: I have updated the PR with this change

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
Comment (ManishMehta) [reply services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:1]: There are no existing test that I could find on this. I am not sure what tests will help here. I am not a regular contributor to this project. If one of the regulars can provide any assistance here, that would be great.

**Review by jonkoops — APPROVED** [review]
This fix looks good to me, but I would love a sanity check from someone else on the @keycloak/core-clients team.

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
Comment (rmartinc) [reply services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:1]: @jonkoops I think we don't need a test for this. The `getExpectedDestination` is used in any broker test about saml (all KcSaml* tests in this [package](https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker)). So the method is tested with the new implementation a lot. To test the original issue, IIUIC we would need some proxy in front or similar so I think it's OK like it is now. The new way of obtaining the destination is tested in normal testing.

**Review by rmartinc — APPROVED** [review]
Thanks @ManishMehta! LGTM!

**Comment by rmartinc** [comment]
Yep, @ManishMehta please signoff your commit to pass the DCO test (git commit -s)

File: services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
Comment (jonkoops) [reply services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java:1]: Perfect, thanks for confirming that @rmartinc!

**Comment by ManishMehta** [comment]
@jonkoops @rmartinc Thanks for your review and help.
I squashed and signed-off. DCO test is happy now.

BTW, I tested the fix locally with a proxy.

**Review by mposolda — APPROVED** [review]
@ManishMehta Thank for the PR!
@jonkoops @rmartinc Thanks for the reviews!
