### PR TITLE
Avoid lookup of existing workflow instances when not needed

### LINKED ISSUE #44791: Workflows look up entries from the database on each event
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

_No response_

### Describe the bug

In `DefaultWorkflowProvider#processEvent()`, each event will call `stateProvider.getScheduledStepsByResource` which touches the database and is therefore slow.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Only touch the database when there are workflow, and a relevant entity is at hand.

### Actual behavior

It touches the database even when there is no workflow for the realm configured.

### How to Reproduce?

Enable SQL logging

### Anything else?

I'll create a PR

### PR DESCRIPTION
**Pull request by ahus1**
Closes #44791

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

File: model/jpa/src/main/java/org/keycloak/models/workflow/DefaultWorkflowProvider.java [hunk 1]
```diff
@@ -247,9 +246,20 @@ private void processEvent(Stream<Workflow> workflows, WorkflowEvent event) {
             EventBasedWorkflow provider = new EventBasedWorkflow(session, getWorkflowComponent(workflow.getId()));
 
             try {
-                ScheduledStep scheduledStep = scheduledSteps.get(workflow.getId());
                 DefaultWorkflowExecutionContext context = new DefaultWorkflowExecutionContext(session, workflow, event);
 
+                if (!provider.supports(event.getResourceType())) {
```
Comment (pruivo) [inline model/jpa/src/main/java/org/keycloak/models/workflow/DefaultWorkflowProvider.java:249]: The `DefaultWorkflowExecutionContext` constructor invokes `realm.getComponentsStream(getId(), WorkflowStepProvider.class.getName())` in one code path. You may want to move this check above line 249.

**Review by pruivo — APPROVED** [review]

**Review by sguilhen — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]
