### PR TITLE
Make fileChooser platform independent.

### LINKED ISSUE #41474: File choosing tests fail on Windows
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Admin console tests that need to choose a file, such as partial import tests, are failing on Windows.  The reason is because the chooseFile utility is not written in a platform-independent way.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests using chooseFile() pass on Windows.

### Actual behavior

Tests using chooseFile() fail on Windows.

### How to Reproduce?

Run admin Playwright tests on Windows.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ssilvert**
Fixes #41474

### CODE REVIEW

File: js/apps/admin-ui/test/utils/file-chooser.ts [hunk 1]
```diff
@@ -1,11 +1,15 @@
 import { Page } from "@playwright/test";
 import path from "path";
+import { fileURLToPath } from "url";
```
Comment (jonkoops) [inline js/apps/admin-ui/test/utils/file-chooser.ts]: Nit: We should use the `node:` prefix for imports that come from Node's standard library. e.g. also `path` should be `node:path`.
```suggestion
import { fileURLToPath } from "node:url";
```

**Review by jonkoops — DISMISSED** [review]
LGTM

**Review by jonkoops — APPROVED** [review]
