### PR TITLE
fix cli output token without return token

### LINKED ISSUE #20215: Cannot retrieve initial access token if created with kcadm
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/cli

### Describe the bug

calling `./kcadm.sh create clients-initial-access -r master -s count=5  -s expiration=60 -o` will create an initial access token but kcamd does not print the token

This issues was also mentioned [here](https://lists.jboss.org/pipermail/keycloak-user/2019-January/016977.html) and curl was suggested as a workaround.

The issue arises because `-o` triggers an additional get, but the token can only be retrieved from the initial json response:

https://github.com/keycloak/keycloak/blob/1d2a98d747372f909e330edc3e85e32de92fbfc9/integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java#L385:L400 

### Version

21.1.1

### Expected behavior

return the json object like

`{"id":"4913c63e-6ed4-48cd-b1af-cd9091685494","token":"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmNmI3ODhmMi0yNDNiLTQ3NGQtYjY3OC00NGFlM2Y5OTExZTkifQ.eyJleHAiOjE2ODM1NTQ3MzMsImlhdCI6MTY4MzU1NDY3MywianRpIjoiNDkxM2M2M2UtNmVkNC00OGNkLWIxYWYtY2Q5MDkxNjg1NDk0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21hc3RlciIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.KOnnjyy1EBa6T2HUOeG_FudrNnr8iXX2WsjKWloBDGo","timestamp":1683554673,"expiration":60,"count":1,"remainingCount":1}`

### Actual behavior

The token id gets returned

`Created new clients-initial-acces with id '4913c63e-6ed4-48cd-b1af-cd9091685494'`

### How to Reproduce?

1. `kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password $PASSWORD`
2. `kcadm.sh create clients-initial-access -r master -s count=5 -s expiration=60 -c -o`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rokkiter**
clients-initial-access without method of get by id, so i skip get detail by id when get output

Closes #20215

### CODE REVIEW

**Comment by rokkiter** [comment]
@pedroigor hello, Please review this pr, if you can give some suggestions, it will be even better.  
thanks a lot

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java [hunk 1]
```diff
@@ -440,4 +439,14 @@ private boolean isUpdate() {
     private boolean isCreateOrUpdate() {
         return "post".equals(httpVerb) || "put".equals(httpVerb);
     }
+
+    private boolean unGetByID(String url) {
```
Comment (shawkins) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java:443]: This would read better as isGetByID.  

Also is it possible to add a test for this?

Comment (rokkiter) [reply integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java]: Sorry, I can't add UT for this.

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java [hunk 2]
```diff
@@ -440,4 +439,14 @@ private boolean isUpdate() {
     private boolean isCreateOrUpdate() {
         return "post".equals(httpVerb) || "put".equals(httpVerb);
     }
+
+    private boolean isGetByID(String url) {
+        String[]  unGetByIDUrls = {"clients-initial-access"};
```
Comment (shawkins) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java:444]: This may be even clearer if you just did 

return !Arrays.asList("clients-initial-access").contains(url);

Or, if there are no other known urls of this type for now, just do:

return !"clients-initial-access".equals(url);

And let the next person decide how to account for multiple urls.

Comment (rokkiter) [reply integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java]: This looks great. I'm sorry for not seeing the reply in time due to some things.

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java [hunk 3]
```diff
@@ -42,12 +42,7 @@
 import java.io.IOException;
 import java.io.InputStream;
 import java.nio.charset.StandardCharsets;
-import java.util.HashMap;
-import java.util.Iterator;
-import java.util.LinkedHashMap;
-import java.util.LinkedList;
-import java.util.List;
-import java.util.Map;
+import java.util.*;
```
Comment (mabartos) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java:45]: @rokkiter Please don't use the star imports.

Comment (rokkiter) [reply integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java]: Thanks for pointing this out,It has been modified

**Comment by vmuzikar** [comment]
@mabartos Do you want to give this another look? :)

**Review by mabartos — APPROVED** [review]
@rokkiter Thanks for the PR. Works as expected.

The  `ClientInitialAccessPresentation` JSON with the token is only retrieved when the `-o` option is explicitly specified. IMO, it's a correct approach as we want to have unified ways for other sub-components. To be more specific, we don't show the JSON for the `clients-initial-access` implicitly during the creation; it needs to be required.

Otherwise, we'd need to make workarounds only for the `clients-initial-access`, which does not seem a proper approach. Users who works with the Admin CLI already know that they need to specify the `-o` option to get the additional output. 

LGTM in this form.

@pedroigor Do you wanna take a look at it, as you have assigned this PR?

**Review by pedroigor — APPROVED** [review]
