### PR TITLE
[client-v2] Require 'clientId' in the payload

### LINKED ISSUE #47524: Require 'clientId' field in the payload
### Description

As discussed, we should always require presence of the `clientId` in the requests. The payload `clientId` is very often used as the main reference to the client, and it's better than dealing with the path parameter. It'll also help to create a new Jakarta/Hibernate validator to rely mainly on the payload clientId.

### LINKED ISSUE #47574: Client API v2 CLI Client: Jakarta validation errors are not handled
### Description

When there are some validation errors on the Jakarta Validator level, the response contains the "violations" set of strings. You can check it in the `ValidationExceptionHandler` class. 

The CLI output does not contain the violations:
Error:  Failures: 
Error:    KcAdmV2ClientCLITest.testUpdateWithoutClientIdFails:534 
Expected: a string containing "clientId: must not be blank"
     but: was "null [Provided data is invalid]

### LINKED ISSUE #47579: Require 'protocol' field in the payload
### Description

`protocol`should be required because it is a discriminator field.

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #47524
- Closes https://github.com/keycloak/keycloak/issues/47574
- Closes #47579
- In most cases, before Hibernate validation, we have the check of whether the payload and path `clientId` are the same - if it's missing, it fails - but it's still good to mark it as required for OpenAPI spec + be more defensive for some possible cases like [this](https://github.com/keycloak/keycloak/compare/main...mabartos:KC-47524?expand=1#diff-6c00855e2a8dcb4913c2b9a4f34360421beaf24d927382e759fe16474e27f883R170)

### CODE REVIEW

**Comment by michalvavrik** [comment]
While I didn't know about https://github.com/keycloak/keycloak/issues/47574, I already handled it in my PR opened before this one. Let's go with your version as you have linked actual opened issue.

**Comment by mabartos** [comment]
@michalvavrik Ahh, didn't know about that. Whatever you prefer.

**Review by michalvavrik — APPROVED** [review]
I think the CLI portion is fine (I handled it by simply detecting the violations, but making it explicit is better for backwards compatibility), thanks for fixing it.

As for https://github.com/keycloak/keycloak/issues/47524 (requiring `clientId`) I think this is architectural decision. It is bit suprising for the `PUT` as then you have it twice (in path and in the object). I remember that we used to use different DTO for `PUT` when I used to write CRUD microservices, which would avoid this problem, but that is just a preference.

However, it is aligned with what Steven keeps repeating (that `PUT` should require the full resource). I'll leave decision on that part to other reviewers.

**Comment by sschu** [comment]
@mabartos As discussed today during the WG meeting, can you please also make `protocol` required?

**Comment by mabartos** [comment]
@sschu Makes sense. Added.

**Review by michalvavrik — APPROVED** [review]

File: rest/admin-v2/api/src/main/java/org/keycloak/representations/admin/v2/BaseClientRepresentation.java [hunk 1]
```diff
@@ -20,7 +19,10 @@
 import org.eclipse.microprofile.openapi.annotations.media.Schema;
 import org.hibernate.validator.constraints.URL;
 
-@Schema(description = "Base client representation with common properties for all client types")
+@Schema(
+        description = "Base client representation with common properties for all client types",
+        requiredProperties = {"protocol", "clientId"}
```
Comment (sschu) [inline rest/admin-v2/api/src/main/java/org/keycloak/representations/admin/v2/BaseClientRepresentation.java]: Is this necessary? I thought your "NotBlank" annotation essentially does the same thing?

Comment (mabartos) [reply rest/admin-v2/api/src/main/java/org/keycloak/representations/admin/v2/BaseClientRepresentation.java]: @sschu You're right. It's not needed, as once the NotBlank annotation is present, the OpenAPI contains the required fields automatically :) Thanks!

Updated

**Review by sschu — APPROVED** [review]
LGTM!

File: rest/admin-v2/tests/src/test/java/org/keycloak/tests/admin/client/v2/validation/AbstractClientValidationTest.java [hunk 2]
```diff
@@ -169,6 +163,42 @@ public void clientWithBlankClientIdFails(String protocol) throws Exception {
...
+                yield r;
+            }
+            case HttpPut.METHOD_NAME -> {
+                var r = new HttpPut(getClientApiUrl("%20"));
+                r.setHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON);
+                yield r;
+            }
+            default -> throw new IllegalStateException("Unexpected value: " + getHttpMethod());
+        };
+        setAuthHeader(request);
```
Comment (vmuzikar) [inline rest/admin-v2/tests/src/test/java/org/keycloak/tests/admin/client/v2/validation/AbstractClientValidationTest.java:180]: Why not to use `getRequest`?

Comment (mabartos) [reply rest/admin-v2/tests/src/test/java/org/keycloak/tests/admin/client/v2/validation/AbstractClientValidationTest.java:180]: @vmuzikar For the POST it is doable, but not for PUT, as we check this special case as having the '%20' as clientId in the path.

Comment (mabartos) [reply rest/admin-v2/tests/src/test/java/org/keycloak/tests/admin/client/v2/validation/AbstractClientValidationTest.java:180]: @vmuzikar Updated for the POST: https://github.com/keycloak/keycloak/pull/47533/changes/33a85bb6c8f2e140b378c3b2f16c6b0c2939854a

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.
