### PR TITLE
Realms Map JPA implementation

### LINKED ISSUE #9661: JPA map storage: Realm no-downtime store
### Description

Create a JPA map storage implementation for Realm area

### LINKED ISSUE #11070: Testsuite failures when JPA Map Storage is used for realms
### Describe the bug

The following tests fail when the base testsuite is run with the JPA Map Storage for realms is enabled:

- org.keycloak.testsuite.admin.ComponentsTest.txt (2 test failures)
- org.keycloak.testsuite.federation.ldap.LDAPRoleMappingsTest.txt  (1 test failure)

The root issue is the same:
```
org.keycloak.models.ModelException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.keycloak.models.map.storage.jpa.realm.entity.JpaRealmEntity#c248659e-825e-4b3e-b8b9-110ed4235a6f]
```

### Version

Unreleased

### Expected behavior

Testsuite must run without errors when the JPA Map Storage is enabled for all areas

### Actual behavior

Tests in the description fail with `OptimisticLockException`

### How to Reproduce?

1- Setup PostgreSQL according to instruction in https://github.com/keycloak/keycloak/discussions/9596
2- Run the tests enabling the JPA map storage for realms using the correct parameters:

```
mvn clean install -Dkeycloak.profile.feature.map_storage=enabled -Dkeycloak.realm.provider=map \
-Dkeycloak.realm.map.storage.provider=jpa-map-storage -Dkeycloak.map.storage.connectionsJpa.url=jdbc:postgresql://localhost:5432/keycloak \
-Dkeycloak.map.storage.connectionsJpa.user=keycloak -Dkeycloak.map.storage.connectionsJpa.password=pass \
-Dtest=ComponentsTest
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
Closes #9661
Closes #11070

### CODE REVIEW

**Comment by sguilhen** [comment]
Opening as draft because I'm still testing locally

**Review by vramik — COMMENTED** [review]
Thank you @sguilhen for the PR. Looks great! I have just one question, please see inline.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java [hunk 1]
```diff
@@ -0,0 +1,978 @@
...
+    /**
+     * Used by hibernate when calling cb.construct from read(QueryParameters) method.
+     * It is used to select realm without metadata(json) field.
+     */
+    public JpaRealmEntity(final UUID id, final int version, final Integer entityVersion, final String name) {
+        this.id = id;
+        this.version = version;
+        this.entityVersion = entityVersion;
+        this.name = name;
+        this.metadata = null;
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java:115]: Yeah, I've noticed that after I sent the PR. I'm about to push some other changes and this fix is included.

File: model/map-jpa/src/main/resources/META-INF/realms/jpa-realms-changelog-1.xml [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+            <column name="version" type="INTEGER" defaultValueNumeric="0">
+                <constraints nullable="false"/>
+            </column>
+            <column name="metadata" type="json"/>
+        </createTable>
+        <ext:addGeneratedColumn tableName="kc_realm">
+            <ext:column name="entityversion" type="INTEGER" jsonColumn="metadata" jsonProperty="entityVersion"/>
+            <ext:column name="name" type="VARCHAR(255)" jsonColumn="metadata" jsonProperty="fName"/>
+            <ext:column name="displayName" type="VARCHAR(255)" jsonColumn="metadata" jsonProperty="fDisplayName"/>
+            <ext:column name="displayNameHtml" type="VARCHAR(255)" jsonColumn="metadata" jsonProperty="fDisplayNameHtml"/>
```
Comment (sguilhen) [inline model/map-jpa/src/main/resources/META-INF/realms/jpa-realms-changelog-1.xml:41]: I'm still looking for the proper size for these columns, need to check the legacy DB schema

Comment (sguilhen) [reply model/map-jpa/src/main/resources/META-INF/realms/jpa-realms-changelog-1.xml]: Done

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/JpaRealmModelCriteriaBuilder.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    @Override
+    public JpaRealmModelCriteriaBuilder compare(SearchableModelField<? super RealmModel> modelField, Operator op, Object... value) {
+        switch(op) {
+            case EQ:
+                if (modelField.equals(RealmModel.SearchableFields.NAME)) {
+                    validateValue(value, modelField, op, String.class);
+                    return new JpaRealmModelCriteriaBuilder((cb, root) ->
+                            cb.equal(root.get(modelField.getName()), value[0])
+                    );
+                } else if (modelField.equals(RealmModel.SearchableFields.COMPONENT_PROVIDER_TYPE)) {
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/JpaRealmModelCriteriaBuilder.java:60]: Yes, inverted index was added for the components

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/JpaRealmModelCriteriaBuilder.java [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+                            cb.isTrue(cb.function("@>",
+                                    Boolean.TYPE,
+                                    cb.function("->", JsonbType.class, root.get("metadata"), cb.literal("fComponents")),
+                                    cb.literal(convertToJson(new MapComponentEntity[]{component}))))
+                    );
+                } else {
+                    throw new CriterionNotSupportedException(modelField, op);
+                }
+            case EXISTS:
+                if (modelField.equals(RealmModel.SearchableFields.CLIENT_INITIAL_ACCESS)) {
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/JpaRealmModelCriteriaBuilder.java:74]: Yes, inverted index was added for client initial accesses

File: services/src/main/java/org/keycloak/services/managers/RealmManager.java [hunk 5]
```diff
@@ -93,11 +93,17 @@ public RealmModel getRealmByName(String name) {
...
     }
 
     public RealmModel createRealm(String id, String name) {
-        if (id == null) {
+        // map storage requires UUIDs
+        if (Profile.isFeatureEnabled(Profile.Feature.MAP_STORAGE)) {
+            if (!KeycloakModelUtils.isValidUUID(id)) {
+                id = KeycloakModelUtils.generateId();
+            }
+        }
```
[the remark this answers is not in the document]
Comment (vramik) [reply services/src/main/java/org/keycloak/services/managers/RealmManager.java:105]: I think the configuration option would be nice. I agree with the proposed solution to have it by default set to false and throw an exception when set to true. On top of that I think we should add a warning which would alert a user that the id of realm is going to be changed.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/BadRealmTest.java [hunk 6]
```diff
@@ -33,6 +35,10 @@ public void testBadRealmName(KeycloakSession session) {
     @Test
     @ModelTest
     public void testBadRealmId(KeycloakSession session) {
+        if (Profile.isFeatureEnabled(Profile.Feature.MAP_STORAGE)) {
+            // when map storage is enabled, the id is always converted into a valid UUID.
+            return;
+        }
```
Comment (vramik) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/BadRealmTest.java:41]:
```suggestion
        Assume.assumeFalse("When map storage is enabled, the id is always converted into a valid UUID.",  Profile.isFeatureEnabled(Profile.Feature.MAP_STORAGE));
```

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (vramik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java]: thanks, resolved

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/BadRealmTest.java (hunk 6 above)
Comment (sguilhen) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/BadRealmTest.java:41]: I've tried this suggestion and the test fails when the assumptions turns out to be false. With newer versions of Junit we have stuff like `@DisabledIf` annotations that can be used to disable the test under some circumstances, but the version we have in Keycloak is too old for that.

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java [hunk 7]
```diff
@@ -1101,6 +1103,8 @@ public ComponentModel importComponentModel(ComponentModel model) {
             }
         }
 
+        model.setId(UuidValidator.validateAndConvert(model.getId(), "component",
+                Boolean.valueOf(Config.scope(MapStorageSpi.NAME).get("rejectInvalidIds"))));
```
Comment (ahus1) [inline model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java:1107]: nitpick: my IDE notified me that "parseBoolean" would be sufficient here and would avoid boxing the boolean.

```suggestion
                Boolean.parseBoolean(Config.scope(MapStorageSpi.NAME).get("rejectInvalidIds"))));
```

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java [hunk 8]
```diff
@@ -68,7 +76,9 @@ public RealmModel createRealm(String id, String name) {
             throw new ModelDuplicateException("Realm with given name exists: " + name);
         }
 
-        if (id != null && tx.read(id) != null) {
+        id = UuidValidator.validateAndConvert(id, "realm", Boolean.valueOf(
```
Comment (ahus1) [inline model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java:79]: The JavaDoc states "Internal ID of the realm or null if one is to be created by the underlying store" for the id attribute. Please consider changing the JavaDoc to indicate that the storage might overwrite/change the ID at its own discretion.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaComponentEntity.java [hunk 9]
```diff
@@ -0,0 +1,198 @@
...
+import org.keycloak.models.map.storage.jpa.JpaRootVersionedEntity;
+import org.keycloak.models.map.storage.jpa.hibernate.jsonb.JsonbType;
+
+import static org.keycloak.models.map.storage.jpa.Constants.CURRENT_SCHEMA_VERSION_REALM;
+
+/**
+ * JPA {@link MapComponentEntity} implementation. Some fields are annotated with {@code @Column(insertable = false, updatable = false)}
+ * to indicate that they are automatically generated from json fields. As such, these fields are non-insertable and non-updatable.
+ *
+ * @author <a href="mailto:sguilhen@redhat.com">Stefan Guilhen</a>
```
Comment (ahus1) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaComponentEntity.java:49]: Please add some comments to the JavaDoc to explain the reasons why there was the decision to have this as a JpaRootVersionedEntity with pros/cons.

Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaComponentEntity.java:59]: Added!

File: services/src/main/java/org/keycloak/services/managers/RealmManager.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (sguilhen) [reply services/src/main/java/org/keycloak/services/managers/RealmManager.java]: Incorporated all these suggestions. For now I'm using a config property from the map storage, but it can be switched into something else, like a system property.

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java (hunk 7 above)
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java]: Ah nice catch. Changed, thanks!

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java (hunk 8 above)
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java]: Updated the javadoc.

File: model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+     * @param id the {@code id} to be validated.
+     * @param component the name of the component (e.g. realm, component) whose id is being validated.
+     * @return the {@code id} itself if it is a valid {@code UUID}, or a new generated {@code UUID}.
+     * @throws {@code InvalidUuidException} if the {@code id} is invalid and the {@code mapStorage} has been configured to
+     * reject invalid ids.
+     */
+    public static String validateAndConvert(final String id, final String component) {
+        boolean rejectInvalid = Boolean.parseBoolean(Config.scope(MapStorageSpi.NAME).get("rejectInvalidIds"));
+        return validateAndConvert(id, component, rejectInvalid);
+    }
```
Comment (sguilhen) [inline model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java:65]: Just thinking a bit more about this validation/conversion of ids into UUIDs for the JPA storage.. using a config property from the `mapStorage` does feel a bit misplaced as other storage impls might not have this hard requirement of ids being UUIDs.

Perhaps we should have this `rejectInvalidIds` config in the `jpa-map-storage` instead and inject its value into the created transactions. The transaction's `create` method can then run the `validateAndConvert` method using the flag that signals if an exception should be thrown or if the invalid id should be simply converted into an UUID.

Thoughts?

Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java:65]: If the UUIDs are a requirement for the map storage in general, then maybe the approach of using a config in `mapStorage` directly is not displaced at all.

File: services/src/main/java/org/keycloak/services/managers/RealmManager.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (ahus1) [reply services/src/main/java/org/keycloak/services/managers/RealmManager.java]: Sorry that I'm late for this discussion: For the LDAP store, all IDs are determined by the LDAP server as GUIDs, so all ids passed in by Keycloak will be replaced in the returned entity with a GUID. 

The automatic conversion is therefore correct IMHO. Thinking about configuration, there having an automatic conversion is what is expected from a map store as it is allowed to treat any passed in ID as a mere suggestion. 

I would even go so far to make it non-configurable and also to not log a warning unless you have a scenario in mind where the conversion could break an existing behavior.

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java (hunk 7 above)
Comment (ahus1) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java]: reviewed, please mark this one as resolved.

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java (hunk 8 above)
Comment (ahus1) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java]: +1 for the javadoc. Actually I don't agree with the throwing an exception, it should always create a new one.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaComponentEntity.java (hunk 9 above)
Comment (ahus1) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaComponentEntity.java:59]: +1, consider it to be resolved.

File: model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java (hunk 10 above)
Comment (ahus1) [reply model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java:65]: Given the example of LDAP, the UUIDs are no requirement across all map storages. A store might decide to create IDs differently, and as long as they are a String they are fine to do so. Having a UUID might be default for Keycloak, and the only supported way for JPA, but this won't hold true for all map storages.

Comment (hmlnarik) [reply model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java:65]: +1 to what @ahus1 wrote.

Also: can `rejectInvalidIds` ever be false? Wouldn't passing in an invalid ID result in an exception from the store later upon saving the object?

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java (hunk 8 above)
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java]: Based on the other comments I'll remove the exception part.

File: model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java (hunk 10 above)
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java:65]: @ahus1 @hmlnarik  Ok, so based on the discussion the conclusion is that the store has the freedom to convert ids at its own discretion, treating any supplied id as a suggestion. In that case, I should remove the id validation/conversion from the `MapRealmProvider` and `MapRealmAdapter` and move it to the JPA transaction `create` method. The reason being that converting at the logical layer is meaningless if other store, like LDAP, will have to convert it again.

In JPA, once the store is invoked to create an entity it can validate if the incoming id is a UUID and convert if needed. I'll also remove the exception and log message. Can I proceed this way?

Comment (ahus1) [reply model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java:65]: +1

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/BadRealmTest.java (hunk 6 above)
Comment (sguilhen) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/BadRealmTest.java:41]: Leaving this piece as is - assumeFalse is throwing exception and failing the test instead of skipping it.

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java (hunk 8 above)
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java]: Done, javadoc updated.

File: model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java (hunk 10 above)
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java]: Done! All changes pushed based on the reviews

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/delegate/JpaRealmDelegateProvider.java [hunk 11]
```diff
@@ -0,0 +1,81 @@
...
+            if (field instanceof MapRealmEntityFields) {
+                switch ((MapRealmEntityFields) field) {
+                    case ID:
+                    case NAME:
+                    case DISPLAY_NAME:
+                    case DISPLAY_NAME_HTML:
+                    case ENABLED:
+                        return getDelegate();
+
+                    case ATTRIBUTES:
```
Comment (vramik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/delegate/JpaRealmDelegateProvider.java:61]: Shoudn't we also handle `case COMPONENTS` to avoid unnecessary additional query?

**Review by vramik — COMMENTED** [review]
Thank you @sguilhen. It's huge amount of work! Great job, please see my comments inline.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapKeycloakTransaction.java [hunk 12]
```diff
@@ -90,6 +89,7 @@ public E read(String key) {
         CriteriaQuery<RE> query = cb.createQuery(entityType);
         Root<RE> root = query.from(entityType);
         query.select(selectCbConstruct(cb, root));
+        if (mcb.isDistinct()) query.distinct(true);
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapKeycloakTransaction.java:93]: Yes. The query that looks for realms that have a component of a type returns the same realm multiple times if the realm has multiple components of the same type. Then code [like this](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/UserStorageSyncManager.java#L62) might end up processing the realms directly from the stream multiple times.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/delegate/JpaRealmDelegateProvider.java [hunk 13]
```diff
@@ -0,0 +1,81 @@
...
+                    default:
+                        setDelegate(em.find(JpaRealmEntity.class, UUID.fromString(getDelegate().getId())));
+                }
+            } else {
+                throw new IllegalStateException("Not a valid realm field: " + field);
+            }
+        } else {
+            setDelegate(em.find(JpaRealmEntity.class, UUID.fromString(getDelegate().getId())));
+        }
+        return getDelegate();    }
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/delegate/JpaRealmDelegateProvider.java:80]: Thanks!

File: model/map/src/main/java/org/keycloak/models/map/realm/entity/MapAuthenticatorConfigEntity.java [hunk 14]
```diff
@@ -45,7 +45,9 @@ static AuthenticatorConfigModel toModel(MapAuthenticatorConfigEntity entity) {
         AuthenticatorConfigModel model = new AuthenticatorConfigModel();
         model.setId(entity.getId());
         model.setAlias(entity.getAlias());
-        model.setConfig(entity.getConfig());
+        Map<String, String> config = new HashMap<>();
+        if (entity.getConfig() != null) config.putAll(entity.getConfig());
+        model.setConfig(config);
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/realm/entity/MapAuthenticatorConfigEntity.java:50]: Ok, without this change this [test fails](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/OwnerReplacementTest.java#L293) because the config is "live", meaning that changes to the config, like adding or removing properties end up being persisted.

This change makes this entity consistent with other entities that also have a config map. (See the [MapComponentEntity](https://github.com/keycloak/keycloak/blob/main/model/map/src/main/java/org/keycloak/models/map/realm/entity/MapComponentEntity.java#L55))

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java [hunk 15]
```diff
@@ -1105,6 +1106,7 @@ public ComponentModel importComponentModel(ComponentModel model) {
             throw new ModelDuplicateException("A Component with given id already exists");
         }
 
+        model.setId(UuidValidator.validateAndConvert(model.getId()));
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java:1109]: Yeah, I had a few issues moving this into the JPA storage but I seem to have found a way to do it correctly. Once I finish testing I'll update.

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java [hunk 16]
```diff
@@ -72,6 +73,7 @@ public RealmModel createRealm(String id, String name) {
             throw new ModelDuplicateException("Realm exists: " + id);
         }
 
+        id = UuidValidator.validateAndConvert(id);
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java:76]: same thing, currently testing a different approach to put this into the JPA storage.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java [hunk 17]
```diff
@@ -255,6 +256,7 @@ public void createRealmCheckDefaultPasswordPolicy() {
     @Test
     public void createRealmFromJson() {
         RealmRepresentation rep = loadJson(getClass().getResourceAsStream("/admin-test/testrealm.json"), RealmRepresentation.class);
+        rep.setId(KeycloakModelUtils.generateId());
```
[the remark this answers is not in the document]
Comment (sguilhen) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java:259]: We don't - prob the first test I've ran and I think I set it here to see if the failure would be fixed with a proper id set. Now that invalid ids are converted this is not needed, so I'll remove. Thanks for spotting this.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/delegate/JpaRealmDelegateProvider.java (hunk 11 above)
Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/delegate/JpaRealmDelegateProvider.java:61]: I think so, and the impl would very very similar to the attributes. I'll add it.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapKeycloakTransaction.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (vramik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapKeycloakTransaction.java:93]: Thank you for the explanation, now I understand. Makes sense.

File: model/map/src/main/java/org/keycloak/models/map/realm/entity/MapAuthenticatorConfigEntity.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (vramik) [reply model/map/src/main/java/org/keycloak/models/map/realm/entity/MapAuthenticatorConfigEntity.java:50]: I see, thank you!

File: model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java (hunk 10 above)
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/common/UuidValidator.java]: This approach worked, got a clean testsuite run using this approach instead of adding things in the logical layer.

File: model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (sguilhen) [reply model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java]: Done

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java [hunk 18]
```diff
@@ -289,6 +290,7 @@ public void createRealmWithPasswordPolicyFromJsonWithInvalidPasswords() {
     @Test
     public void createRealmWithPasswordPolicyFromJsonWithValidPasswords() {
         RealmRepresentation rep = loadJson(getClass().getResourceAsStream("/import/testrealm-keycloak-6146.json"), RealmRepresentation.class);
+        rep.setId(KeycloakModelUtils.generateId());
```
Comment (vramik) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java:293]: Tthis shoudn't be necessary as well, right? Sorry for not spotting it earlier.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java [hunk 19]
```diff
@@ -0,0 +1,1023 @@
...
+    }
+
+    @Override
+    public String getId() {
+        return id == null ? null : id.toString();
+    }
+
+    @Override
+    public void setId(String id) {
+        String validatedId = UuidValidator.validateAndConvert(id);
```
Comment (vramik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java:178]: wondering if it should also be implemented for other areas as well ... if so perhaps we could move it into `JpaMapKeycloakTransaction.create` method, wdyt?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java (hunk 18 above)
Comment (sguilhen) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java:293]: Yes, it definitely needs changing. Thanks!

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java (hunk 19 above)
Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java:178]: create wouldn't work for entities such as the ComponentEntity because its creation happens when it is added to the components relationship - i.e. components are not created via `tx.create`. I would indeed put this check in every entity's `setId(String id)` because this is always called, whether from the `tx.create` or when creating an entity by adding it to a relationship (such as components or auth sessions that are added to the root auth session).

Comment (sguilhen) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaRealmEntity.java:179]: Added the validation on `setId` to all other entities that have non-generated ids. For generated ids this method should never be called.

**Review by vramik — APPROVED** [review]
Thanks @sguilhen

**Review by hmlnarik — APPROVED** [review]
Approving per @vramik and @ahus1 approvals. Thanks for the PR!
