### PR TITLE
Avoid having N+1 database calls when fetching composite roles

### LINKED ISSUE #46605: 26.5.4 startup regression with many realms: RealmCacheSession.prepareCachedRealm() scans master admin role composites per realm (O(N²))
### Description

**Keycloak version(s)**
- 26.5.3: OK
- 26.5.4: startup much slower

**Tested Environment**
DB: MariaDB

**Topology:** 
3-node Keycloak cluster
JGroups: JDBC_PING

**Realms: 732**

**Description**
After upgrading from 26.5.3 to 26.5.4, Keycloak startup is significantly slower in an installation with 732 realms. During startup, a very large number of queries are executed against COMPOSITE_ROLE/KEYCLOAK_ROLE (composite role expansion), and startup time increases substantially.

We traced the slowdown to the following new logic introduced in 26.5.4 (comment: “to accommodate imports of new realms, check to see if the master admin role is up-to-date”) in RealmCacheSession.prepareCachedRealm():

```
// to accommodate imports of new realms, check to see if the master admin role is up-to-date
if (!model.getName().equals(Config.getAdminRealm())) {
    RealmModel adminRealm = session.realms().getRealmByName(Config.getAdminRealm());
    if (adminRealm != null) {
        ClientModel clientModel = session.clients().getClientByClientId(adminRealm, model.getName() + "-realm");
        if (clientModel != null) {
            RoleModel adminRole = adminRealm.getRole(AdminRoles.ADMIN);
            if (adminRole.getCompositesStream().noneMatch(r -> (r.isClientRole() && r.getContainerId().equals(clientModel.getId())))) {
                registerRoleInvalidation(adminRole.getId(), adminRole.getName(), adminRole.getContainerId());
            }
        }
    }
}
```

With hundreds of realms, this results in repeated scanning of master realm admin role composites for each realm, which appears to be O(number_of_realms × number_of_admin_composites) and becomes very expensive at scale.

Observed SQL pattern
Repeated queries like:

```
select re1_0.ID, ...
from KEYCLOAK_ROLE re1_0
join COMPOSITE_ROLE cre1_0 on re1_0.ID=cre1_0.CHILD_ROLE
where cre1_0.COMPOSITE=?
```

**Expected behavior**
Startup time should be comparable to 26.5.3 for large realm counts.

**Actual behavior**
Startup time is much slower on 26.5.4; large volume of role/composite lookups during startup.

**Impact**
Large multi-tenant installations (hundreds of realms) see a significant regression.

**Suggestion**
This could likely be optimized by avoiding per-realm scans of adminRole.getCompositesStream():

precompute a set/map of composite client container IDs once (per boot / per admin role load) and do O(1) membership checks, or

query existence directly (single indexed query) rather than streaming all composites per realm, or

cache adminRealm/adminRole and/or memoize the composite check.

Reproduction

Install with hundreds of realms (in our case 732).

Upgrade 26.5.3 → 26.5.4.

Observe startup time regression and DB query volume during startup.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #46605

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java [hunk 1]
```diff
@@ -500,7 +502,10 @@ private RealmAdapter prepareCachedRealm(String id, KeycloakSession session) {
                     ClientModel clientModel = session.clients().getClientByClientId(adminRealm, model.getName() + "-realm");
                     if (clientModel != null) {
                         RoleModel adminRole = adminRealm.getRole(AdminRoles.ADMIN);
-                        if (adminRole.getCompositesStream().noneMatch(r -> (r.isClientRole() && r.getContainerId().equals(clientModel.getId())))) {
+                        if (containers == null) {
```
Comment (shawkins) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java]: This should limit the potential reloading of admin composite roles due to newly cached realms to just once per session.

Newly cached realms are caused either by a realm being added, or because an existing realm was evicted from cache. If I'm understanding correctly all resources in the realm cache are being treated equally - that is loading a lot of entries, such as composite roles, will cause the eviction of realms and the admin role. Other than adjusting the realm cache size, do we have some additional controls over cache tiers or weighting for eviction by type (it seems realms are substancially more heavy-weight than most entries)?

Without adjustments to what is being evicted, the other approach of simply invalidating the admin role when a newly cached realm is created may be better than this in practice (at least for non-admin heavy workloads) because if realms are routinely being evicted, then so is the master admin role.

Alternatively is there any way to create a cache entry for the admin role that cannot be evicted? That would address the performance issue here and reduce the overhead with frequent admin requests once the cache is thrashing.

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java]: Infinispan will cache evict the "least frequently used" item, so this should help a bit. 

Still, I'll rewrite the code to always invalidate the admin role.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java [hunk 2]
```diff
@@ -483,6 +483,12 @@ public RealmModel getRealm(String id) {
         return adapter;
     }
 
+    /**
+     * Cache that we've triggere an admin role invalidation in this session already.
```
Comment (shawkins) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java]:
```suggestion
     * Cache that we've triggered an admin role invalidation in this session already.
```

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java (hunk 1 above)
Comment (shawkins) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java]: > Infinispan will cache evict the "least frequently used" item, so this should help a bit.

Is it worth a follow-up about tuning this further?

Another possible followup - even with light-weight tokens it seems like creating the server side identity for someone with the master admin role is expensive (at least in terms of cache entires) when there are a lot of realms. Should we consider partitioning the load of composites by realm, rather than materializing all of them for light-weight tokens? Or do we already caution against using someone with the master admin role to perform admin operations in this scenario?

**Review by shawkins — DISMISSED** [review]
Looks good, just one nit and some questions about follow-ups.

**Review by shawkins — APPROVED** [review]

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java (hunk 1 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java]: > Is it worth a follow-up about tuning this further?

IMHO no. 

> For light-weight tokens it seems like creating the server side identity for someone with the master admin role is expensive

It is very expensive as it will evaluate all roles by iterating through them recursively. There were some ideas to maybe implement a recursive query in the past, but we did never implement that. 

See https://vladmihalcea.com/hibernate-with-recursive-query/ for more information, and #46653 for a follow-up issue.
