### PR TITLE
Missing client_id validation match when authenticating client with JW…

### LINKED ISSUE #22177: Missing client_id validation match when authenticating client with JWT
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

According to JWT client authentication specification for client_id parameter https://www.rfc-editor.org/rfc/rfc7521.html#section-4.2 :
```
client_id
      OPTIONAL.  The client identifier as described in [Section 2.2](https://www.rfc-editor.org/rfc/rfc7521.html#section-2.2) of
      OAuth 2.0 [[RFC6749](https://www.rfc-editor.org/rfc/rfc6749)].  The "client_id" is unnecessary for client
      assertion authentication because the client is identified by the
      subject of the assertion.  If present, the value of the
      "client_id" parameter MUST identify the same client as is
      identified by the client assertion.
```

Right now, Keycloak doesn't check that if client_id is present, it matches the client from client assertion. This shouldn't have any side-effect (as the most important is client from JWT), but still should be validated

### Version

22.0.1

### Expected behavior

Validation for client_id is done as per specification

### Actual behavior

When using parameter `client_id=some-nonexistent-or-nonmatching-client`, client authentication works 

### How to Reproduce?

See above

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
…T. Refactoring JWTClientAuthenticator and JWTClientSecretAuthenticator to share the common validations

Closes #22177

This adds the missing validation as described in #22177. Also I took the opportunity for some cleanup and finally refactored `JWTClientAuthenticator` and `JWTClientSecretAuthenticator` to re-use as much validations as possible as lots of the validations (maybe 80%) are same for both and makes sense to re-use them to avoid fragility (EG. when some validation is added only to one place when it should be added to both etc).

### CODE REVIEW

**Comment by mposolda** [comment]
@tnorimat Can I please ask you to review this PR?

**Comment by tnorimat** [comment]
@mposolda Yes, I will review the PR.

File: services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java [hunk 1]
```diff
@@ -0,0 +1,213 @@
...
+        return true;
+    }
+
+    public void readJws() throws JWSInputException {
+        jws = new JWSInput(clientAssertion);
+        token = jws.readJsonContent(JsonWebToken.class);
+    }
+
+    public boolean validateClient() {
+        String clientId = token.getSubject();
```
Comment (tnorimat) [inline services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java:105]: It assumes that `validateClient()` is called after `readJws()` was called. If not, L105 cause NPE.
Mayby the current L105 is OK, but null check might be added.

**Review by tnorimat — COMMENTED** [review]
@mposolda I added one review comment. Could you check it?

File: services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java (hunk 1 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java:109]: I've added the null check and also added few more null checks on more places. I've used separate commit, so you can easily review changes, but I am planning to squash before merge.

In theory, with correct usage of the JWTClientValidator as is used from the authenticators, this should not happen. But it is indeed good to add null checks (for instance for the case when someone wants to override default authenticators and use the validators in his code etc).

Comment (tnorimat) [reply services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java:109]: Thank you.

**Review by tnorimat — APPROVED** [review]

**Comment by mposolda** [comment]
@tnorimat Thanks!
