### PR TITLE
Missing comment generated by Liquibase executor in the custom script

### LINKED ISSUE #41299: [quarkus-next] Missing comment generated by Liquibase executor in the custom script
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Related to all DB vendors.

After upgrade to Liquibase 4.33.0 the `Create Database Change Log Table` message is missing from the custom-generated script as seen here: https://github.com/liquibase/liquibase/blob/v4.33.0/liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java#L262

However, the log message should be present in the log, so we should be sure the branch is executed.

Not sure if it worth the effort to analyze what has changed since the Liquibase 4.29.1 -> 4.33.0 as the comment is not propagated to the executor and not written to the file. I think it should be only necessary to check if the log message i there.

EDIT: The DATABASECHANGELOG is always created in the database and outside of the custom Liquibase executor, so it seems user's executions are done separately than the default one done by Liquibase.

```
--------- org.keycloak.it.storage.database.dist.PostgreSQLDistTest output end  ---------
Error:  Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 141.591 s <<< FAILURE! - in org.keycloak.it.storage.database.dist.PostgreSQLDistTest
Error: OR] org.keycloak.it.storage.database.dist.PostgreSQLDistTest.testKeycloakDbUpdateScript(CLIResult,RawDistRootPath)  Time elapsed: 18.304 s  <<< FAILURE!
-- java.lang.AssertionError: 
-- 
-- Expected: a string containing "Create Database Change Log Table"
--      but: was "-- *********************************************************************
-- -- * Keycloak database creation script - apply this script to empty DB *
-- -- *********************************************************************
-- 
-- -- *********************************************************************
-- -- Update Database Script
-- -- *********************************************************************
-- -- Change Log: META-INF/jpa-changelog-master.xml
-- -- Ran at: 7/21/25, 12:36 AM
-- -- Against: keycloak@jdbc:postgresql://localhost:32781/keycloak?loggerLevel=OFF
-- -- Liquibase version: 4.33.0
-- -- *********************************************************************
-- 
-- -- Changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com
-- CREATE TABLE public.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL);
-- 
-- CREATE TABLE public.CLIENT (DTYPE VARCHAR(31) NOT NULL, ID VARCHAR(36) NOT NULL, ALLOWED_CLAIMS_MASK BIGINT, ENABLED BOOLEAN DEFAULT FALSE NOT NULL, FULL_SCOPE_ALLOWED BOOLEAN DEFAULT FALSE NOT NULL, NAME VARCHAR(255), NOT_BEFORE INTEGER, PUBLIC_CLIENT BOOLEAN DEFAULT FALSE NOT NULL, SECRET VARCHAR(255), BASE_URL VARCHAR(255), BEARER_ONLY BOOLEAN DEFAULT FALSE NOT NULL, MANAGEMENT_URL VARCHAR(255), SURROGATE_AUTH_REQUIRED BOOLEAN DEFAULT FALSE NOT NULL, DIRECT_GRANTS_ONLY BOOLEAN DEFAULT FALSE NOT NULL, REALM_ID VARCHAR(36));
-- 
-- CREATE TABLE public.CLIENT_SESSION (ID VARCHAR(36) NOT NULL, ACTION INTEGER, CLIENT_ID VARCHAR(36), REDIRECT_URI VARCHAR(255), STATE VARCHAR(255), TIMESTAMP INTEGER, SESSION_ID VARCHAR(36));
-- 
-- CREATE TABLE public.CLIENT_SESSION_ROLE (ROLE_ID VARCHAR(255) NOT NULL, CLIENT_SESSION VARCHAR(36) NOT NULL);
-- 
-- CREATE TABLE public.COMPOSITE_ROLE (COMPOSITE VARCHAR(36) NOT NULL, CHILD_ROLE VARCHAR(36) NOT NULL);
-- 
-- CREATE TABLE public.CREDENTIAL (ID VARCHAR(36) NOT NULL, DEVICE VARCHAR(255), HASH_ITERATIONS INTEGER, SALT BYTEA, TYPE VARCHAR(255), VALUE VARCHAR(255), USER_ID VARCHAR(36));
-- 
-- CREATE TABLE public.EVENT_ENTITY (ID VARCHAR(36) NOT NULL, CLIENT_ID VARCHAR(255), DETAILS_JSON VARCHAR(2550), ERROR VARCHAR(255), IP_ADDRESS VARCHAR(255), REALM_ID VARCHAR(255), SESSION_ID VARCHAR(255), TIME BIGINT, TYPE VARCHAR(255), USER_ID VARCHAR(255));
-- 
-- CREATE TABLE public.FED_PROVIDERS (REALM_ID VARCHAR(36) NOT NULL, USERFEDERATIONPROVIDERS_ID VARCHAR(36) NOT NULL);
```

### Version

quarkus-next (Liquibase 4.33)

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests pass

### Actual behavior

Tests do not pass

### How to Reproduce?

Execute the DB tests

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #41299

For Liquibase 4.33.0 the `databasechangelog` table is always created in the database - not part of the custom user's script anymore. More details in the parent issue.

CI for `quarkus-next` :ok: :
- https://github.com/keycloak/keycloak/pull/41492

### CODE REVIEW

File: quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java [hunk 1]
```diff
@@ -92,7 +93,8 @@ public void assertManualDbInitialization(CLIResult cliResult, RawDistRootPath ra
         var output = readKeycloakDbUpdateScript(rawDistRootPath);
 
         assertThat(output, notNullValue());
-        assertThat(output, containsString("Create Database Change Log Table"));
+        // after upgrade to >= Liquibase 4.33.0, we can remove the check with the 'history' table
+        assertThat(output, CoreMatchers.anyOf(containsString("Creating database history table with name"), containsString("Creating database changelog table with name")));
```
Comment (mabartos) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java]: Changes related to:
1. checked [statement](https://github.com/liquibase/liquibase/blob/v4.33.0/liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java#L262)
2. [Log message](https://github.com/liquibase/liquibase/blob/v4.33.0/liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java#L272)

File: quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java [hunk 2]
```diff
@@ -92,11 +93,9 @@ public void assertManualDbInitialization(CLIResult cliResult, RawDistRootPath ra
...
 
         assertThat(output, notNullValue());
-        assertThat(output, containsString("Create Database Change Log Table"));
-
-        var outputLowerCase = output.toLowerCase();
-        var count = countMatches(outputLowerCase, "create table public.databasechangelog") + countMatches(outputLowerCase, "create table keycloak.databasechangelog");
-        assertThat(count, is(1));
+        assertThat(output,containsString("Keycloak database creation script - apply this script to empty DB"));
+        // after upgrade to >= Liquibase 4.33.0, we can remove the check with the 'history' table
+        assertThat(cliResult.getOutput(), CoreMatchers.anyOf(containsString("Creating database history table with name"), containsString("Creating database changelog table with name")));
```
Comment (mabartos) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java]: Changes related to:
1. checked [statement](https://github.com/liquibase/liquibase/blob/v4.33.0/liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java#L262)
2. [Log message](https://github.com/liquibase/liquibase/blob/v4.33.0/liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java#L272)

**Comment by mabartos** [comment]
Still some failures - need to take a look at it.

**Comment by mabartos** [comment]
@keycloak/cloud-native @keycloak/core Should be ready for review. Thanks!

Works with the `quarkus-next` branch: https://github.com/keycloak/keycloak/pull/41492

**Review by sguilhen — APPROVED** [review]

**Review by Pepo48 — APPROVED** [review]
