### PR TITLE
fix: adds a check for duplicate users/clients to simplify cmd errors

### LINKED ISSUE #31160: Failed admin bootstrap behavior
If a user / service account fails to be created we should cause the creation of the master realm to fail. Otherwise the behavior is that the master realm will be created and the user must then use the cli to perform the bootstrap admin operation.

### PR DESCRIPTION
**Pull request by shawkins**
also changes temp-admin-service to temp-admin

closes: #31160

A duplicate user check was requested by @pedroigor - to consolidate exception handling / logging the ApplianceBootstrap methods now return booleans.

~~It was also brought up in a change that the client and user can have the same name - this is a very small change just tacked on to this PR, but it can be separated if needed - cc @Pepo48 that will need documentation changes as well.~~

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/ServicesLogger.java [hunk 1]
```diff
@@ -465,10 +465,15 @@ public interface ServicesLogger extends BasicLogger {
     void scriptEngineCreated(String engineName, String engineVersion, String mimeType);
 
     @LogMessage(level = DEBUG)
-    @Message(id=107, value="Skipping create admin user. Admin already exists in realm '%s'.")
+    @Message(id=107, value="Skipping create admin user. Users already exists in realm '%s'.")
     void addAdminUserFailedAdminExists(String realm);
```
Comment (mabartos) [inline services/src/main/java/org/keycloak/services/ServicesLogger.java:469]:
```suggestion
    @Message(id=107, value="Skipping create admin user. Users already exist in realm '%s'.")
    void addAdminUserFailedUsersExist(String realm);
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java [hunk 2]
```diff
@@ -85,23 +80,23 @@ protected void createTemporaryAdmin(KeycloakSession session) {
 
         try {
             //Integer expiration = Configuration.getOptionalKcValue(BootstrapAdminOptions.EXPIRATION.getKey()).map(Integer::valueOf).orElse(null);
-            if (StringUtil.isNotBlank(adminPassword)) {
-                createTemporaryMasterRealmAdminUser(adminUsername, adminPassword, /*expiration,*/ session);
+            if (StringUtil.isNotBlank(adminPassword) && !createTemporaryMasterRealmAdminUser(adminUsername, adminPassword, /*expiration,*/ session)) {
+                throw new RuntimeException("Aborting startup and the creation of the master realm, because the temp admin user account could not be created.");
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:84]:
```suggestion
                throw new RuntimeException("Aborting startup and the creation of the master realm, because the temporary admin user account could not be created.");
```
might be better, right?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java [hunk 3]
```diff
@@ -85,23 +80,23 @@ protected void createTemporaryAdmin(KeycloakSession session) {
...
             }
-            if (StringUtil.isNotBlank(clientSecret)) {
-                createTemporaryMasterRealmAdminService(clientId, clientSecret, /*expiration,*/ session);
+            if (StringUtil.isNotBlank(clientSecret) && !createTemporaryMasterRealmAdminService(clientId, clientSecret, /*expiration,*/ session)) {
+                throw new RuntimeException("Aborting startup and the creation of the master realm, because the temp admin service account could not be created.");
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java:87]: same as above

**Review by mabartos — COMMENTED** [review]
@shawkins LGTM, just few nitpicks

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java (hunk 2 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java]: Ok, applied.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java (hunk 3 above)
Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java]: Ok, applied.

File: services/src/main/java/org/keycloak/services/ServicesLogger.java (hunk 1 above)
Comment (shawkins) [reply services/src/main/java/org/keycloak/services/ServicesLogger.java]: Yes, the method name can change too.

**Review by mabartos — APPROVED** [review]
@shawkins Thanks! LGTM

**Review by abstractj — APPROVED** [review]
