### PR TITLE
Make Locale updater generate an event and use the user profile

### LINKED ISSUE #24369: UpdateUserLocaleAction does not trigger EventType.UPDATE_PROFILE event
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

When "Update User Locale" required action is active, it does not fire "EventType.UPDATE_PROFILE" event, although user profile is updated.

### Version

21.1.1

### Expected behavior

After successful update of "locale" attribute, there should be fired "EventType.UPDATE_PROFILE" event. Then it is possible to catch this profile change in custom SPI.

### Actual behavior

When "locale" is changed, no event is fired.

### How to Reproduce?

Active "Update User Locale" required action and try to catch "EventType.UPDATE_PROFILE" event in custom SPI.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #24369

With this PR the `DefaultLocaleUpdaterProvider` now:

* Uses UP to modify the locale in the user.
* An event is created to notify the UPDATE_PROFILE  modification.

A i18n test is modified to check the event is triggered.

### CODE REVIEW

File: services/src/main/java/org/keycloak/locale/DefaultLocaleUpdaterProvider.java [hunk 1]
```diff
@@ -16,32 +16,51 @@
...
     public void updateUsersLocale(UserModel user, String locale) {
-        if (!locale.equals(user.getFirstAttribute("locale"))) {
+        final String previousLocale = user.getFirstAttribute("locale");
+        if (!locale.equals(previousLocale)) {
             try {
+                EventBuilder event = new EventBuilder(session.getContext().getRealm(), session, session.getContext().getConnection())
+                        .event(EventType.UPDATE_PROFILE)
+                        .user(user)
+                        .client(session.getContext().getClient())
+                        .detail(Details.PREF_PREVIOUS + UserModel.LOCALE, previousLocale)
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/locale/DefaultLocaleUpdaterProvider.java:54]: I wonder about why we cannot rely on `EventAuditingAttributeChangeListener` to set those details automatically like other places calling `profile.update` method? Also about why we still need to manually call `user.setSingleAttribute` from `DefaultLocaleUpdaterProvider` instead of relying on profile to set it automatically.

Is it because of "locale" attribute is not automatically available in the `UPDATE_PROFILE` context? I wonder if we should have some dedicated context like `UPDATE_PROFILE_LOCALE`, which can be created manually and support only "locale" attribute? Or is it too "heavy" just for this purpose?
@pedroigor WDYT?

Comment (pedroigor) [reply services/src/main/java/org/keycloak/locale/DefaultLocaleUpdaterProvider.java:54]: Yeah, I think it does not make much sense to set the attribute directly if also using the user profile provider to update the user.

I'm not sure about creating a dedicated context but perhaps add locale to the update profile context, if possible.

Comment (rmartinc) [reply services/src/main/java/org/keycloak/locale/DefaultLocaleUpdaterProvider.java:54]: @mposolda @pedroigor But if I add locale to the UPDATE_PROFILE it would appear in the update profile page, right? Do we want that?

And thinking about this, if there is some invalid data in the user the locale update is going to fail (for example if a required attribute is not filled in the user). Maybe I was wrong and better don't use the user profile, just update the "locale" as before and trigger the event.

Comment (mposolda) [reply services/src/main/java/org/keycloak/locale/DefaultLocaleUpdaterProvider.java:54]: +1 to avoid using user profile. As you pointed, it can be a risk of "required" attribute not being filled, which would cause that it won't be possible to update locale.

We have follow-up tasks to better handling various related situations. Perhaps we can have some more "dynamicity" in the user profile context to being able to say "Please validate just `locale` attribute now and ignore all other attributes or required attributes" etc...

So I would say just ignore userProfile for now and "hardcode" the details in the event like you did. Is it ok to update PR in this way?

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks!
