### PR TITLE
Fix: Stabilize PlainTextVaultProviderTest by enhancing validation logging

### LINKED ISSUE #39660: Failed shouldPreventPathFileSeparatorInVaultSecretId test on Windows
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

Test case `shouldPreventPathFileSeparatorInVaultSecretId` fails on Windows.

### Version

latest commit from main

### Regression

- [ ] The issue is a regression

### Expected behavior

The aforementioned test case succeeds

### Actual behavior

The test case fails, the following assertion evaluates to false: https://github.com/keycloak/keycloak/blob/a035b904ff3f867f8a8ce9e78fed060e61258471/services/src/test/java/org/keycloak/vault/PlainTextVaultProviderTest.java#L224

I think the problem is, that the separator character is `\` on windows and `/` on unix systems. The test case uses the unix-style separator hard-coded, while the validator method uses a platform based constant.

See:
https://github.com/keycloak/keycloak/blob/a035b904ff3f867f8a8ce9e78fed060e61258471/services/src/main/java/org/keycloak/vault/AbstractVaultProvider.java#L102

Image

### How to Reproduce?

Execute `shouldPreventPathFileSeparatorInVaultSecretId` test case on a windows machine.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Pepo48**
Closes #39660

### CODE REVIEW

**Comment by mabartos** [comment]
@Pepo48 What's the status of this PR?

**Comment by Pepo48** [comment]
@mabartos waiting to be reviwed and merged. I'll then create the backports.

@vmuzikar knows about this, we also discussed the way the backports are going to be created.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
We would need to look into the tests – why they didn't fail before without this fix, or if there's no test covering this.

**Comment by Pepo48** [comment]
> We would need to look into the tests – why they didn't fail before without this fix, or if there's no test covering this.

@vmuzikar the test in question `PlainTextVaultProviderTest` is part of the base unit tests, which we only execute on Ubuntu runners.

**Comment by vmuzikar** [comment]
> @vmuzikar the test in question `PlainTextVaultProviderTest` is part of the base unit tests, which we only execute on Ubuntu runners.

Would be probably good to run on Windows as well. Can you try it?

**Comment by Pepo48** [comment]
> Would be probably good to run on Windows as well. Can you try it?

Of course, I would do it this way:
https://github.com/keycloak/keycloak/compare/main...Pepo48:keycloak:win-base-ut

Which adds `Base UT (windows-latest) stage` to our CI:
https://github.com/Pepo48/keycloak/actions/runs/17885496692/job/50858783770

And as you can see `PlainTextVaultProviderTest` failed this time even in the GH CI.

I will cherrypick the commit and add it to this PR in order to also see the results with the fix applied.

**Comment by Pepo48** [comment]
The vault tests passed. The UT stage failure is caused by two other unrelated tests. I can analyze and fix them in a separate PRs.

**Comment by Pepo48** [comment]
I split it into separate issues: https://github.com/keycloak/keycloak/issues/42796.

Corresponding PRs are also in place.

File: services/src/main/java/org/keycloak/vault/AbstractVaultProvider.java [hunk 1]
```diff
@@ -99,7 +99,7 @@ private void checkForLegacyKey(VaultKeyResolver resolver, String vaultSecretId,
      * @return a boolean indicating whether the validation passed.
      */
     protected boolean validate(VaultKeyResolver resolver, String key, String resolvedKey) {
-        if (key.contains(File.separator)) {
+        if (key.indexOf('/') >= 0 || key.indexOf(File.separatorChar) >= 0) {
```
Comment (vmuzikar) [inline services/src/main/java/org/keycloak/vault/AbstractVaultProvider.java]: This way on Unix-like systems, `\` will be accepted (though it won't matter as it's not a path separator there). But if someone e.g. moves their KC instance to Windows, then it starts failing which might be confusing.

I'd suggest making it consistent and check for both `/` and `\`, on top of `File.separator` just in case...

**Review by vmuzikar — CHANGES_REQUESTED** [review]

File: services/src/main/java/org/keycloak/vault/AbstractVaultProvider.java (hunk 1 above)
Comment (shawkins) [reply services/src/main/java/org/keycloak/vault/AbstractVaultProvider.java]: Checking for \ on linux can be seen as a notable or breaking change.

Comment (vmuzikar) [reply services/src/main/java/org/keycloak/vault/AbstractVaultProvider.java]: @shawkins Good point. This is still a CVE fix which would justify a reasonable breaking change. I would prefer it over platform inconsistency as that might be very confusing to users.

Comment (Pepo48) [reply services/src/main/java/org/keycloak/vault/AbstractVaultProvider.java]: I addressed the suggestion and added a release note as well.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
As agreed offline, we will rather adjust the test in the end.

**Review by vmuzikar — APPROVED** [review]

**Review by shawkins — APPROVED** [review]
LGTM, thanks @Pepo48
