### PR TITLE
Limit the number of clientSessionIds in the test

### LINKED ISSUE #12264: Unstable test model test OfflineSessionPersistenceTest.testPersistenceMultipleNodesClientSessionAtSameNode
### Describe the bug

The the following test in the model testsuite is now and then unstable:  org.keycloak.testsuite.model.session.OfflineSessionPersistenceTest.testPersistenceMultipleNodesClientSessionAtSameNode

Unstable model tests have also been reported by @DGuhr. It looks like this test ran into a timeout. 

Log of a previous run: [16-3.txt](https://github.com/keycloak/keycloak/files/8802922/16-3.txt)

### Version

999-SNAPSHOT

### Expected behavior

Test should be stable.

### Actual behavior

While the test runs stable most of the times, there seems to be times of day where it fails, probably due to load.

### How to Reproduce?

Difficult, reason needs to be extracted from the logs.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Before it was 1500 client sessions, now its only 150 client sessions. This should help to keep the test within its time constraint of 60 + 30 seconds.

Local run before: 35 seconds
Local run after: 20 seconds

Closes #12264

### CODE REVIEW

**Comment by ahus1** [comment]
The model tests completed green, so I assume this is good enough to be reviewed and merged. The failed test in the Base testuide on undertow seems unrelated.

File: testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java [hunk 1]
```diff
@@ -136,8 +136,9 @@ public void testPersistenceSingleNode() {
     @RequireProvider(UserSessionPersisterProvider.class)
     @RequireProvider(value = UserSessionProvider.class, only = InfinispanUserSessionProviderFactory.PROVIDER_ID)
     public void testPersistenceMultipleNodesClientSessionAtSameNode() throws InterruptedException {
+        int NUM_CLIENTS = 2;
```
Comment (hmlnarik) [inline testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java:139]: Could you please introduce a constant or rename the variable in camel case?

**Review by hmlnarik — APPROVED** [review]
Thanks @ahus1 !
