### PR TITLE
Fix oid4vc mappers

### LINKED ISSUE #29805: Supported Credential Type is not evaluated when applying the Protocol Mapper in OID4VCI
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

The "supportedCredentialTypes" configuration of an OID4VCMapper should allow to control the application of a protocol-mapper to a concrete requested Credential inside of a client. However, the configuration is currently not evaluated and therefor all mappers of a client are applied for all credential types.

### Version

not yet released

### Regression

- [ ] The issue is a regression

### Expected behavior

Only Protocol Mappers that supported the requested credential type should be applied.

### Actual behavior

All configured Protocol Mappers are applied.

### How to Reproduce?

Configure an OID4VC client, with at least two protocol mappers. The mappers should be configured to support different credential types. Request one of the credentials and see that both mappers are applied to them.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wistefan**
Evaluates the supportedTypes of the OID4VC mapper config.
Fixes #29805

### CODE REVIEW

**Comment by mposolda** [comment]
@francis-pouatcha @tnorimat @pskopek Anyone of you available to review this please?

**Comment by tnorimat** [comment]
@mposolda Hello, I will review the PR.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java [hunk 1]
```diff
@@ -335,6 +335,7 @@ public void testRequestCredentialUnsupportedCredential() throws Throwable {
     @Test
     public void testRequestCredential() {
```
Comment (tnorimat) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java:336]: How about add these additional check in `requestOffer` ?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
Comment (tnorimat) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java:1]: L79 import is not used.

**Review by tnorimat — CHANGES_REQUESTED** [review]
@wistefan Thank you. Could you check review comments I added?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java (hunk 1 above)
Comment (wistefan) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java:335]: I agree, thank you:) Fixed in [bf62374](https://github.com/keycloak/keycloak/pull/29806/commits/bf6237402e5039bc326c730eba6d4c7fcf1967b9)

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
Comment (wistefan) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java:1]: Fixed in [bf62374](https://github.com/keycloak/keycloak/pull/29806/commits/bf6237402e5039bc326c730eba6d4c7fcf1967b9)

Comment (tnorimat) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java:1]: I confirmed the fix. Thank you.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java (hunk 1 above)
Comment (tnorimat) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java:335]: I confirmed the fix. Thank you.

**Review by tnorimat — APPROVED** [review]
@wistefan Thank you very much.
@mposolda I approved the PR.

**Review by ahus1 — APPROVED** [review]
Approving based on @tnorimat's review.
