### PR TITLE
Show username of selected users during search in user selector

### LINKED ISSUE #36789: Seaching users in the user selector will not show the username for users already selected
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In pages using the `UserSelect` component to allow selecting users based on a search, there is a bug when you search for an user already selected and select it from the result list.

The current behavior of the component is to empty the username of the selected user once you search for the same user and select it.

In addition to that,  the component should not show in the search results the users already selected.

### Version

26.0.8

### Regression

- [ ] The issue is a regression

### Expected behavior

Searching for users when using the `UserSelect` component should keep the existing users and their usernames and do not allow selecting the same user again.

### Actual behavior

Searching for users when using the `UserSelect` component removes the username for  existing users after selecting the same user and the search result does not filter the selected users.

### How to Reproduce?

* Create a client and enable authorization
* Navigate to the `Authorization` and then the `Policies` tab
* Create a `User Policy` by adding a user to it
* Go back to the policies listing page and click on the policy previously created
* In the `Users` field, type the username of the user already associated with the policy

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #36789

### CODE REVIEW

File: js/apps/admin-ui/src/components/users/UserSelect.tsx [hunk 1]
```diff
@@ -53,46 +52,66 @@ export const UserSelect = ({
...
+    setSelectedUsers,
+    [values],
+  );
 
-      if (search) {
-        params.username = search;
+  useFetch(
+    async () => {
+      if (!search) {
+        return [];
```
Comment (edewit) [inline js/apps/admin-ui/src/components/users/UserSelect.tsx:82]: If your not searching shouldn't it show the first couple of users? Seems a bit odd when you only click it to see an empty box:
image

File: js/apps/admin-ui/src/components/users/UserSelect.tsx [hunk 2]
```diff
@@ -53,46 +52,66 @@ export const UserSelect = ({
...
+        username: search,
+        max: 20,
+      });
+
+      if (!values) {
+        return foundUsers;
       }
-      return adminClient.users.find(params);
+
+      return foundUsers.filter((user) => !values.includes(user.id!));
```
Comment (edewit) [inline js/apps/admin-ui/src/components/users/UserSelect.tsx:94]: It shouldn't remove selected users from the list, but rather show them as selected with a little blue tick:
image

File: js/apps/admin-ui/src/components/users/UserSelect.tsx [hunk 3]
```diff
@@ -53,46 +52,66 @@ export const UserSelect = ({
...
 
   const [open, toggleOpen, setOpen] = useToggle();
-  const [users, setUsers] = useState<(UserRepresentation | undefined)[]>([]);
+  const [selectedUsers, setSelectedUsers] = useState<UserRepresentation[]>([]);
+  const [searchedUsers, setSearchedUsers] = useState<UserRepresentation[]>([]);
   const [inputValue, setInputValue] = useState("");
   const [search, setSearch] = useState("");
   const textInputRef = useRef<HTMLInputElement>();
 
   const debounceFn = useCallback(debounce(setSearch, 1000), []);
```
Comment (edewit) [inline js/apps/admin-ui/src/components/users/UserSelect.tsx:61]: this has always been a second, but that is a bit slow

**Review by edewit — CHANGES_REQUESTED** [review]
I'll add my changes to this PR

**Review by edewit — APPROVED** [review]

**Review by agagancarczyk — APPROVED** [review]
