### PR TITLE
[OID4VCI] Fix creation of clientScopes with protocol oid4vc

### LINKED ISSUE #39527: [OID4VCI] protocol-type `oid4vc` in ClientScopes
### Description

The UI allows to select protocol-type `OpenID for Verifiable Credentials` in the client-scopes view. Saving it with this protocol selected causes a BadRequest. ClientScopes that should be used for OpenId for Verifiable Credentials should get this protocol type assigned. 

Fixing this bug will make it easier to read out details for the `/openid-credential-issuer` endpoint that must display the configured credential-types under the attribute `credential_configurations_supported`

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
fixes #39527

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+                                                                           .build();
+        realm.client(enabledAppWithSkipRefreshToken);
+
+        UserBuilder defaultUser = UserBuilder.create()
+                                             .id(KeycloakModelUtils.generateId())
+                                             .username("test-user@localhost")
+                                             .password("password")
+                                             .role(Constants.REALM_MANAGEMENT_CLIENT_ID, AdminRoles.REALM_ADMIN)
+                                             .addRoles(OAuth2Constants.OFFLINE_ACCESS);
+        realm.user(defaultUser);
```
Comment (IngridPuppet) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:84]: Is configuring a client and adding a default user really necessary for this testsuite? My concern is making the testsuite more straightforward for human processing.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java [hunk 2]
```diff
@@ -0,0 +1,170 @@
...
+        testRealms.add(realm.build());
+    }
+
+    @Override
+    public void importRealm(RealmRepresentation realm) {
+        super.importRealm(realm);
+        if (Objects.equals(realm.getRealm(), realmName)) {
+            clientUUID = adminClient.realm(realmName).clients().findByClientId(clientId).get(0).getId();
+        }
+    }
```
Comment (IngridPuppet) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:95]: `clientUUID` is set, but not used. Do we need this code?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+import java.io.IOException;
+import java.util.List;
+import java.util.Map;
+import java.util.Objects;
+
+/**
+ * @author Pascal Knüppel
+ */
+public class ClientScopeTests extends AbstractKeycloakTest {
+
```
Comment (IngridPuppet) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:48]: I found this pre-existing test: `org.keycloak.tests.admin.client.ClientScopeTest`. Isn't this new class somewhat a duplicate?

**Review by IngridPuppet — COMMENTED** [review]
To fix the bug reported by the linked issue, I believe the main action of this PR is to add `OID4VCLoginProtocolFactory.PROTOCOL_ID` to the list of allowed protocols in an existing validation rule. I checked the implementation and have a few comments about the test added. Hello @Captain-P-Goldfish - Please could you check them?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java (hunk 3 above)
Comment (Captain-P-Goldfish) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:48]: The pre-existing Test is found in the base-module. The core-difference is that this is an integration-test making sure, that the creation works using the REST-API

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java [hunk 4]
```diff
@@ -0,0 +1,170 @@
...
+    private static String clientId;
+    private static String clientSecret;
+
+    @Rule
+    public AssertEvents events = new AssertEvents(this);
+
+    @Override
+    public void beforeAbstractKeycloakTest() throws Exception {
+        super.beforeAbstractKeycloakTest();
+    }
```
[the remark this answers is not in the document]
Comment (Captain-P-Goldfish) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:61]: fixed

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java (hunk 1 above)
Comment (Captain-P-Goldfish) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:84]: you are absollutely right. I did copy paste and forgot to clean up...

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java (hunk 2 above)
Comment (Captain-P-Goldfish) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:95]: fixed

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java [hunk 5]
```diff
@@ -0,0 +1,170 @@
...
+        final RealmResource testRealm = adminClient.realm(realmName);
+
+        String clientScopeId = null;
+        try {
+            clientScopeId = createClientScope(realmName, clientScope);
+        } finally {
+            // cleanup
+            testRealm.clientScopes().get(clientScopeId).remove();
+        }
+    }
```
[the remark this answers is not in the document]
Comment (Captain-P-Goldfish) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:168]: fixed

**Comment by Captain-P-Goldfish** [comment]
Thanks for your great review @IngridPuppet . Fixed all your comments.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+    @Test
+    public void createClientScopeWithOpenId4VCIProtocol() {
+        createClientScope("oid4vc");
+    }
+
+    private void createClientScope(String oid4vc) {
+        ClientScopeRepresentation clientScope = new ClientScopeRepresentation();
+        clientScope.setName("test-client-scope");
+        clientScope.setDescription("test-client-scope-description");
+        clientScope.setProtocol(oid4vc);
```
Comment (IngridPuppet) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java:89]: You likely meant to use a generic naming.
```suggestion
    private void createClientScope(String protocol) {
        ClientScopeRepresentation clientScope = new ClientScopeRepresentation();
        clientScope.setName("test-client-scope");
        clientScope.setDescription("test-client-scope-description");
        clientScope.setProtocol(protocol);
```

**Review by IngridPuppet — APPROVED** [review]
Thank you for addressing my concerns and considering my suggestions.

**Review by mposolda — COMMENTED** [review]
@Captain-P-Goldfish Thanks! Added few comments inline. Could you please check them?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java (hunk 3 above)
Comment (Captain-P-Goldfish) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientScopeTests.java]: fixed

**Review by mposolda — APPROVED** [review]
@Captain-P-Goldfish Thanks!
