### PR TITLE
Recognize email verification during brokering from a separate auth session

### LINKED ISSUE #37559: Linking user in different browser doesn't work if original window/tab is closed
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

When a user links a 3rd party IdP account to an existing account, they are prompted to click on a link in an email to verify their email address. After clicking the link, the user is eventually asked to return to the original browser window/tab and click ‘Continue’ (next to ‘Verified in another browser?’) If they already closed the tab/window they were in, they’re unable to link their account unless they restart the process from scratch.

### Version

26.1.2

### Regression

- [ ] The issue is a regression

### Expected behavior

IDP link should be added after the user is confirmed to proceed by email.
When the user tries to log in with iDP that was just linked to account, it should proceed with iDP login, instead of linking the account again.

### Actual behavior

The user does not have added an iDP link in the Admin console.
The user is prompted about the existing account and has to restart the linking process from scratch.

### How to Reproduce?

1. Prepare an IdP account which already has an existing account.
2. Navigate to the Keycloak login page.
3. Click on the IdP provider link of your choice and login with your IdP account.
5. When prompted about the existing account, select ‘Add to existing account'.

Image

6.. When prompted to verify your email, close the tab you’re in and open your email in a different browser.
7. Click on the link in the email.
8. Confirm you want to link your IdP account.

Image

Image

9. Reopen your previous browser, navigate to the Keycloak login page, and try to login with your IdP account.

Image

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #37559

### CODE REVIEW

File: services/src/main/java/org/keycloak/authentication/actiontoken/idpverifyemail/IdpVerifyAccountLinkActionTokenHandler.java [hunk 1]
```diff
@@ -133,6 +139,37 @@ public Response handleToken(IdpVerifyAccountLinkActionToken token, ActionTokenCo
...
+            } finally {
+                singleObjects.remove(singleObjectKey);
+            }
+        }
+
+        return isEmailVerified;
+    }
+
+    private static String getEmailVerifiedSingleObjectKey(String userId, String idpAlias) {
+        return "emailVerified" + userId + idpAlias;
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/authentication/actiontoken/idpverifyemail/IdpVerifyAccountLinkActionTokenHandler.java:170]:
```suggestion
        return "verified" + userId + idpAlias;
```

Maybe if it is removed to `verified`, it can be better as the "signal" that user verified his account may not be specific to email, but could be used by other use-cases in theory. Similarly the methods could be renamed to `isUserVerified` instead of `isEmailVerified` .

But this is possibly just a detail considering that we do not have more OOTB use-cases besides email verification right now.

**Review by mposolda — DISMISSED** [review]
@pedroigor Added single inline comment, but not a blocker IMO. So approving

**Review by mposolda — APPROVED** [review]
@pedroigor Thanks for the updates! Approving again.

For the CI: The FIPS tests should be already solved in latest main. Rebase should help. Not 100% sure about operator issues.
