### PR TITLE
Remove random redirect after password reset

### LINKED ISSUE #20867: Control redirect after password reset
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

After a user has reset their password, they are sent to a "random" redirect.
This happens if the user is sent directly to the reset-credentials endpoint (skipping the KC login page).
The "random" redirect is the first "Valid redirect URI", which are sorted by their hash value. Hence the quoted random.

### Version

18 (RH-SSO 7.6)

### Expected behavior

I should be able to control the redirect somewhat.

**Here are several suggested solutions**
1. Redirect to "Base URL". Base is described in the documentation as "Default URL to use when the auth server needs to redirect or link back to the client". This sounds as it should be the fallback if no redirect is found.
2. Being able to change sort order of "Valid Redirect URIs"
3. Sort "Valid Redirect URIs" alphabetically.
4. Support "redirect_uri" query-param for reset-credentials endpoint. Also requested in #15279 

### Actual behavior

The user is redirected to the first "valid redirect uri", which can't be controlled.

When "Valid Redirect URIs" are loaded they are put into a HashSet
See org.keycloak.models.utils.RepresentationToModel line 571
`resource.setRedirectUris(new HashSet<>(redirectUris));`

When loading the redirectUri, the first (with the lowest hash value) is set.
See org.keycloak.services.resources.LoginActionsService line 422
`redirectUri = RedirectUtils.getFirstValidRedirectUri(session, client.getRootUrl(), client.getRedirectUris());`

### How to Reproduce?

1. have a client with multiple "Valid Redirect URIs" and Base URL set
2. Go to {KEYCLOAK}/auth/realms/{REALM}/login-actions/reset-credentials?client_id={CLIENT_ID}
3. Enter email and receive a “reset password”-email with a link
4. Click link
5. Enter new password twice and submit
6. Get redirect to first "Valid Redirect URIs"

### Anything else?

The "Valid Redirect URIs" should only be used for validation and never for fallback.
They can contains wildcards (*) and therefore can be invalid URLs.
"Base URL" is a much better candidate for this.

### PR DESCRIPTION
**Pull request by mposolda**
closes #20867

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/LoginActionsService.java [hunk 1]
```diff
@@ -412,17 +410,20 @@ public Response resetCredentialsPOST(@QueryParam(AUTH_SESSION_ID) String authSes
...
      */
     @Path(RESET_CREDENTIALS_PATH)
     @GET
+    @Deprecated
     public Response resetCredentialsGET(@QueryParam(AUTH_SESSION_ID) String authSessionId, // optional, can get from cookie instead
                                         @QueryParam(SESSION_CODE) String code,
                                         @QueryParam(Constants.EXECUTION) String execution,
                                         @QueryParam(Constants.CLIENT_ID) String clientId,
                                         @QueryParam(Constants.TAB_ID) String tabId) {
+        logger.warn("This endpoint is deprecated. Please use endpoint '/realms/{realm_name}/protocol/openid-connect/forgot-credentials' with parameters like OIDC for directly reset credentials from your client application");
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/services/resources/LoginActionsService.java:426]: @mposolda This endpoint is the one that the `Forgot password` login option uses right now when it's shown in the login page. I think it cannot be changed to the OIDC one (the client initiating can be SAML for example). So I think we cannot deprecate it, we can say that it's only for internal use in the doc and move the warning when the auth session needs to be created (but I think that deprecation is not OK).

**Review by rmartinc — CHANGES_REQUESTED** [review]
@mposolda I think that the endpoint is used for the forgot password login link, and I think it's OK (we cannot change it). So I see two options:

1. Remove the deprecation, change doc to say that the endpoint is for internal use (not to call it directly by users), move the warning to the point when the auth session is missing and should be created.
2. Add a new `redirect_uri` parameter to the endpoint to be used when the auth session is missing (check client is ok and redirect_uri is ok, moving to error page if necessary if no redirect uri or not valid one).

With option 2 you can initiate a reset-credentials even with a SAMl client (which I think it's not possible in any other way). But option 1 is also valid if you really the effort the effort is not needed.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java [hunk 2]
```diff
@@ -185,19 +209,71 @@ public void resetPasswordLink() throws IOException, MessagingException {
...
+            event.detail(Details.REDIRECT_URI,  expectedRedirectUri);
+        } else {
+            event.removeDetail(Details.REDIRECT_URI);
+        }
+        event.assertEvent();
+    }
 
-        AccountHelper.logout(testRealm(), username);
+    @Test
+    public void resetPasswordLinkTestAppWithourRedirectUriParam() throws IOException {
```
Comment (rmartinc) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java:224]: Typo:
```suggestion
    public void resetPasswordLinkTestAppWithoutRedirectUriParam() throws IOException {
```

**Review by rmartinc — APPROVED** [review]
LGTM! There is a little typo but I'm approving it (just fix it and it's OK to me!).
