### PR TITLE
fix: refining the usage of distribution tests

### LINKED ISSUE #34058: Refine usage of distribution tests
### Description

Distribution tests that don't need a running server should be converted into Quarkus or unit tests (see PicocliTest). This is especially true for tests that are either expect a server to fail to start, or are simply checking the hand off of configuration to quarkus.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #34058

Our longest running quarkus tests seem to be:
StartCommandDistTest
Fips"
Logging"
Metrics"
Health"

We have several options:
- split the zip tests into two parts roughly 30 minutes each
- move tests that don't actually need a running server to unit tests
  - I'm showing that here with the first three tests from StartCommandDistTest. With StartCommandDistTest it appears that just the shear number of tests / augmentations is causing the excessive times on github. I can continue to work my way through these classes to pull out anything that doesn't test the running server - obviously augmentation / build does still need to have integration coverage to some degree - but it doesn't need to be extensive. With https://github.com/keycloak/keycloak/pull/34260 nearly all of the autobuilding logic is easily testable.
  - We can of course also structure the Picocli tests more logically. My goal is that in just a couple of packages we can get an extreme amount of coverage of everything in front of quarkus in just a couple of seconds.
- An alternative to moving tests as @mabartos suggested, is to use the existing set of annotations to hide the details of whether we're launching a running server or not. The possible benefit here is to use a system property to drive whether a distribution test is run in some long running launch.

And of course these options are not mutually exclusive.

@vmuzikar @Pepo48 @vmuzikar @pedroigor  what are some opinions on the directions we should head in?

### CODE REVIEW

File: quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 1]
```diff
@@ -244,4 +240,85 @@ public void spiRuntimeWarnWithBuild() {
         assertThat(nonRunningPicocli.getOutString(), containsString("The following run time options were found, but will be ignored during build time: kc.spi-something-pass"));
     }
     
+    @Test
+    public void failIfOptimizedUsedForFirstStartupExport() {
+        NonRunningPicocli nonRunningPicocli = pseudoLaunch("export", "--optimized", "--dir=data");
+        assertEquals(CommandLine.ExitCode.USAGE, nonRunningPicocli.exitCode);
+        assertThat(nonRunningPicocli.getErrString(), containsString("The '--optimized' flag was used for first ever server start."));
+    }
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:248]:
```suggestion
    @Test
    @NonRunningServer
    @Launch({"export", "--optimized", "--dir=data"})
    public void failIfOptimizedUsedForFirstStartupExport(CLIResult cliResult) {
        cliResult.assertExitCode(CommandLine.ExitCode.USAGE);
        cliResult.assertError("The '--optimized' flag was used for first ever server start.");
    }
```

I would like some sort of this ^^ approach. Not introducing any other `pseudoLaunch` and these kind of constructs on developer side, but rather have it hidden.

-  The `NonRunningPicocli` might be some kind of `KeycloakDistribution` type that would not start the server
- We could leverage the `@Launch` annotation
- We could leverage the `KeycloakDistribution` parameter injection
- The `@NonRunningServer` (or diff name) annotation would mark the test to not start server itself
- In that case, we would not have to rewrite tests so much.

@shawkins WDYT?

**Review by mabartos — COMMENTED** [review]
@shawkins I think it makes perfect sense to split the ZIP tests as they're already quite extensive. I added also a suggestion below.

File: quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java (hunk 1 above)
Comment (shawkins) [reply quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java:248]: My concerns with going this approach are:
- not as good at localizing the tests - they will be in the test module, not in the quarkus-server module
- additional / alternative setup is required to test scenarios dependent up augmented state
- devs will have to be very careful to not hit the subtle differences, such as:
  - the error/out contain console characters
  - the execution is not via the shell scripts, which contains a lot of manipulation
  - the KeycloakDistribution would be mostly not implemented
  
I'd probably be more comfortable with adding support for a option that would cause the distribution to act more like a non-running server. That is if -Dkc.test.non-running or something is specified then we'll inhibit reaug and skip full exection of the command.

**Comment by shawkins** [comment]
@vmuzikar @Pepo48 @mabartos Added a dryrun annotation / option to a number of StartCommandDistTest - locally this saves only about 15 seconds of total exection time because there are just a handful of the tests are incidentally triggering an augmentation. Most of the failing tests that use start and runtime options won't end up causing a reaugmentation unless interviening tests mess with build options or the profile.

So it looks like we need the pseudo-rearg logic (which is easily enabled by https://github.com/keycloak/keycloak/pull/34260) to prevent most of the reaugmentations. Tests that have prior invocations of build or start-dev can put the persisted properties into that state and skip the full reaugmentation.

The only other thing I can think to do is somehow create a repository of optimized images / persisted properties such that when we are supposed to run build or reaug we could see if anything matches the current state and copy that over - however we'd really want to be able to do this across test classes as well, which would be even more work with docker distributions.

**Comment by shawkins** [comment]
@mabartos @vmuzikar @pedroigor @Pepo48 here's the next refinements based upon the persistent property logic refactoring.

The good:
- There's a significant reduction in the runtime of the StartCommandDistTest - only 2 tests are actually augmenting / starting the server.
- With only slight modifications the tests will run with the DryRun annotation. We can of course use an enviornment variable to turn off the affect of the dry run annotation and let the tests run fully, even in raw mode.
- further tried to encapsulate logic, such as the fast start
- --dryRun is marked as hidden, but we can choose to expose it as a general option

The bad:
- FipsDistTest, and LoggingDistTest are not as easy to convert as they mostly verify logic after quarkus starts, or don't rely on reaugmentation (most of the tests that should not start the server in LoggingDistTest). So more than likely we'll still need to split this test suite. I'm not sure yet about the other log running test classes.

The ugly:
- The unit testing of Picocli and the distribution testing are using competing mechanisms. We need some test specific logic in PersistedConfigSource and a couple of other places beyond the dry run handling to deal with the capturing / use of the build properties. We could go to the extent of introducing a provider jar into the distribution to separate some of this out of the main code. Alternatively we can consider just doing the initial proposal of moving the relevant tests out of the distribution tests and into unit tests instead.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java [hunk 2]
```diff
@@ -63,4 +66,16 @@ public boolean includeRuntime() {
...
+        try {
+            Start start = new Start();
+            start.optimizedMixin.optimized = true;
+            start.dryRunMixin.dryRun = dryRun;
+            start.setPicocli(picocli);
+            start.run();
+        } catch (PropertyException | ProfileException e) {
+            picocli.usageException(e.getMessage(), e.getCause());
+        }
+    }
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java:80]: 👍  to this. We won't have to have a special fast start logic which caused e.g. https://github.com/keycloak/keycloak/issues/30380.

**Review by vmuzikar — COMMENTED** [review]
> There's a significant reduction in the runtime of the StartCommandDistTest - only 2 tests are actually augmenting / starting the server.

If I'm looking correctly, seems like it shaved off about 4 minutes from the whole Quarkus CI. That's actually not that much.

> We can of course use an enviornment variable to turn off the affect of the dry run annotation and let the tests run fully, even in raw mode.

That doesn't seem yet implemented, right?

> --dryRun is marked as hidden, but we can choose to expose it as a general option

+1 to keep it hidden for now

> The unit testing of Picocli and the distribution testing are using competing mechanisms. We need some test specific logic in PersistedConfigSource and a couple of other places beyond the dry run handling to deal with the capturing / use of the build properties. We could go to the extent of introducing a provider jar into the distribution to separate some of this out of the main code. Alternatively we can consider just doing the initial proposal of moving the relevant tests out of the distribution tests and into unit tests instead.

I'd keep as is for now.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
[the remark this answers is not in the document]
Comment (shawkins) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java:1]: Removed

**Review by vmuzikar — DISMISSED** [review]
@mabartos @Pepo48 Do you want to review as well?

**Comment by shawkins** [comment]
> If I'm looking correctly, seems like it shaved off about 4 minutes from the whole Quarkus CI. That's actually not that much.

Correct, and that's just from StartCommandDistTest. About half the savings are just from one test method.

The top 10 longest running test classes currently account for about half the runtime of the zip test suite. 

I don't see a great savings coming from the Fips or Logging test classes based upon these changes. So a rought guess is that we could probably save another 5-10 minutes off the entire test suite run if I agressively apply dryRun everwhere else. Ultimately we're still looking at splitting the zip test into 2 test runs to get it under 30 minutes.

There is a further saving of a few seconds per test to move it from a distribution test to a unit test - but at best we'd be looking at shaving off a couple of minutes by doing that.

> 
> > We can of course use an enviornment variable to turn off the affect of the dry run annotation and let the tests run fully, even in raw mode.
> 
> That doesn't seem yet implemented, right?

Correct, it's not in there. I did restrict the DryRun annotation to be only for the raw distribution though. So any of the container smoke tests are still running fully - but I do see some unexpected error output that way.

**Comment by vmuzikar** [comment]
> Ultimately we're still looking at splitting the zip test into 2 test runs to get it under 30 minutes.

Yeah, I think that will be the way to go.

> There is a further saving of a few seconds per test to move it from a distribution test to a unit test - but at best we'd be looking at shaving off a couple of minutes by doing that.

Nah, that seems like not really a good trade off.

> So any of the container smoke tests are still running fully

Yeah, that is enough if we don't use dry-run there.

**Comment by shawkins** [comment]
@vmuzikar I think this is about as broadly as I can apply DryRun. It cut about 10 minutes from the zip runtime. 

The last bit of messiness is the usage of assertStarted - I've replaced that with dry runs asserting that the error log is blank as that will work either way[*]. Other options:
- encapsulate the detection of what started means under the assertStarted method.
- add and look for a general "started in production mode" log

[*] Looking for a blank error output is currently failing for one of the container tests because one of the non-keycloak containers is emitting "/bin/sh: line 1: nc: command not found" and some other error output.

**Review by vmuzikar — COMMENTED** [review]
The current approach looks good but we need to tackle the failing container test.

**Comment by shawkins** [comment]
> The current approach looks good but we need to tackle the failing container test.

As far as I can tell that's an existing issue that we were unaware of because we're not generally looking for clean error logs. The only downside is that this may keep happening - even after we address this, we could have future failures completely unrelated to the testing that we're trying to do.

**Comment by shawkins** [comment]
Should be good now. Needed to refine stdout / stderr collection for the docker distribution.

File: quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java [hunk 3]
```diff
@@ -23,10 +24,26 @@
...
+
+        @Override
+        public void accept(OutputFrame t) {
+            if (t.getType() == OutputType.STDERR) {
+                stdErr.accept(t);
+            } else if (t.getType() == OutputType.STDOUT) {
+                stdOut.accept(t);
+            }
+        }
+    }
```
Comment (vmuzikar) [inline quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java:45]: This is quite similar to https://github.com/keycloak/keycloak/pull/34956/files#diff-6b0c5824a800a0027bae134fa2edbeb32a6575a5bbe3addd033a9c1a5c48787a. Maybe we can try and align it even though it's not merged yet.

Comment (shawkins) [reply quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java:45]: > Maybe we can try and align it even though it's not merged yet.

We shouldn't try to do that proactively. It should be straight-forward later to have this implement OutputConsumer if the docker dist needs the same abstraction.

**Review by vmuzikar — APPROVED** [review]
@shawkins Ok, LGTM. Nice work, thanks!

@mabartos Do you want to give it a look too?

**Comment by mabartos** [comment]
@vmuzikar feel free to merge it. I'm not able to fully review it right now, but some additional work can be done in follow ups. So I would not prolong it.
