### PR TITLE
Fix session type of access token in offline access refresh token flow

### LINKED ISSUE #47776: False session type of access token in offline_access refresh token flow with scope parameter without offline_access scope
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

[Issue 37694](https://github.com/keycloak/keycloak/issues/37694) correct session type of access token of other oidc/oauth flows.

However, this way could produce wrong session type of access token in offline_access refresh token flow and accordingly problems using returned access token.
Fe In offline_access refresh token flow with scope parameter without offline_access including in scope, return on session type instead of off. This access token could not be used in other flows if online session does not exist or will expired based on online sessionif it exists.

In refresh token flow, session type must be based on user session type.

### Version

26.5.6

### Regression

- [x] The issue is a regression

### Expected behavior

1. Log into a client with `Use refresh tokens` enabled and without `offline_access` scope
2. Log into the same window in the same client with `offline_access` scope. An offline refresh token is returned.
3. Execute refresh token flow with the offline refresh token with scope parameter without `offline_access` scope.
4. Access token (token A) with session type off returned
5. Wait until online session expired or logout the client
6. Execute UserInfo with token A --> return userinfo successfully

### Actual behavior

1. Log into a client with `Use refresh tokens` enabled and without `offline_access` scope
2. Log into the same window in the same client with `offline_access` scope. An offline refresh token is returned.
3. Execute refresh token flow with the offline refresh token with scope parameter without `offline_access` scope.
4. Access token (token A) with session type on returned
5. Wait until online session expired or logout the client
6. Execute UserInfo with token A --> 401 (expired access token)

### How to Reproduce?

See actual behavior

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
Closes #47776

### CODE REVIEW

File: services/src/main/java/org/keycloak/authorization/admin/PolicyEvaluationService.java [hunk 1]
```diff
@@ -342,8 +345,9 @@ private CloseableKeycloakIdentity createIdentity(PolicyEvaluationRequest represe
 
                     AuthenticationManager.setClientScopesInSession(keycloakSession, authSession);
                     ClientSessionContext clientSessionCtx = TokenManager.attachAuthenticationSession(keycloakSession, userSession, authSession);
-
-                    accessToken = new TokenManager().createClientAccessToken(keycloakSession, realm, clientModel, userModel, userSession, clientSessionCtx);
+                    TokenContextEncoderProvider encoder = keycloakSession.getProvider(TokenContextEncoderProvider.class);
+                    AccessTokenContext tokenCtx = encoder.getTokenContextFromClientSessionContext(clientSessionCtx, SecretGenerator.getInstance().generateSecureID());
+                    accessToken = new TokenManager().createClientAccessToken(keycloakSession, realm, clientModel, userModel, userSession, clientSessionCtx, encoder.encodeTokenId(tokenCtx));
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/authorization/admin/PolicyEvaluationService.java]: The method `createClientAccessToken` is called from multiple places and in this PR, you added those lines to all the places, which call this method:
```
TokenContextEncoderProvider encoder = keycloakSession.getProvider(TokenContextEncoderProvider.class);
AccessTokenContext tokenCtx = encoder.getTokenContextFromClientSessionContext(clientSessionCtx, SecretGenerator.getInstance().generateSecureID());
```

I wonder that instead of updating all the places, the method `createClientAccessToken` could be updated directly?

File: services/src/main/java/org/keycloak/protocol/oidc/encode/DefaultTokenContextEncoderProvider.java [hunk 2]
```diff
@@ -67,6 +67,32 @@ public AccessTokenContext getTokenContextFromClientSessionContext(ClientSessionC
         return new AccessTokenContext(sessionType, tokenType, grantType, rawTokenId);
     }
 
+    @Override
+    public AccessTokenContext getTokenContextFromClientSessionContextForRefresh(ClientSessionContext clientSessionContext, String rawTokenId) {
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/protocol/oidc/encode/DefaultTokenContextEncoderProvider.java]: Instead of copy/paste almost whole method from `getTokenContextFromClientSessionContext` with just a minor difference, is it possible to re-use the same code? For example something like:
```
@Override
public AccessTokenContext getTokenContextFromClientSessionContext(ClientSessionContext clientSessionContext, String rawTokenId) {
    return getTokenContextFromClientSessionContext(clientSessionContext, rawTokenId, clientSessionContext.isOfflineTokenRequested());
}

@Override
public AccessTokenContext getTokenContextFromClientSessionContextForRefresh(ClientSessionContext clientSessionContext, String rawTokenId) {
    UserSessionModel userSession = clientSessionContext.getClientSession().getUserSession();
    return getTokenContextFromClientSessionContext(clientSessionContext, rawTokenId, userSession.isOffline());
}

private AccessTokenContext getTokenContextFromClientSessionContext(ClientSessionContext clientSessionContext, String rawTokenId, boolean isOffline) {
    // IMPL here...
}
```

**Review by mposolda — COMMENTED** [review]
@cgeorgilakis Thanks for the PR. Behavior looks good. Few minor inline comments added.

File: services/src/main/java/org/keycloak/protocol/oidc/encode/DefaultTokenContextEncoderProvider.java [hunk 3]
```diff
@@ -67,6 +67,32 @@ public AccessTokenContext getTokenContextFromClientSessionContext(ClientSessionC
...
+        UserSessionModel userSession = clientSessionContext.getClientSession().getUserSession();
+        if (userSession.getPersistenceState() == UserSessionModel.SessionPersistenceState.TRANSIENT) {
+            String createdFromPersistent = userSession.getNote(Constants.CREATED_FROM_PERSISTENT);
+            if (createdFromPersistent != null) {
+                sessionType = Constants.CREATED_FROM_PERSISTENT_OFFLINE.equals(createdFromPersistent) ? AccessTokenContext.SessionType.OFFLINE_TRANSIENT_CLIENT : AccessTokenContext.SessionType.ONLINE_TRANSIENT_CLIENT;
+            } else {
+                sessionType = AccessTokenContext.SessionType.TRANSIENT;
+            }
+        } else {
+            sessionType = userSession.isOffline() ? AccessTokenContext.SessionType.OFFLINE : AccessTokenContext.SessionType.ONLINE;
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/protocol/oidc/encode/DefaultTokenContextEncoderProvider.java]: Is it needed to create a new method? Maybe it's enough just changing the `sessionType` using a or in the previous method, something like:

```suggestion
            sessionType = clientSessionContext.isOfflineTokenRequested() || userSession.isOffline() ? AccessTokenContext.SessionType.OFFLINE : AccessTokenContext.SessionType.ONLINE;
```

**Review by rmartinc — CHANGES_REQUESTED** [review]
Just a minor comment, which is more or less the same @mposolda is commenting. I think that you can use the same method, and if not, follow what Marek is suggesting to not repeat all the code.

**Comment by cgeorgilakis** [comment]
I have made changes based on @mposolda proposal keeping one method with adding _parameter boolean isOffline_

**Review by mposolda — APPROVED** [review]
@cgeorgilakis Thanks!
