### PR TITLE
[fix: #9213] Bump Quarkus to 2.5.4.Final

### LINKED ISSUE #9213: Spurious logs are spilling in Quarkus Distribution.X integration tests
### Describe the bug

As a direct consequence of: https://github.com/quarkusio/quarkus/issues/22302
Sometimes JVMs tests are spuriously failing (e.g. in CI) intercepting unrelated log messages (e.g. from other test run).

The problem is more evident when running tests in a different order (e.g. from an IDE), the problem got reduced for Keycloak here:
https://github.com/andreaTP/keycloak/tree/repro-spilling-out

### Version

main

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**

### CODE REVIEW

**Comment by DGuhr** [comment]
We looked at the workaround in our pairing session, so imo when the CI tests run green (locally they did for me, but not tested all docker tests for now) than this LGTM. Nevertheless the underlying problem is still weird (we got no log output, bc. the redirects of the streams seem to happen _after_ we actually log something, but this looks even more weird bc. we're relying on quarkusmaintestextension internals, which are starting the application _after_ installing redirects). @andreaTP may be worth discussing it on the quarkus-dev mailing list?

**Review by DGuhr — APPROVED** [review]
approved, as the concerned tests are already green. have a good end of year, y'all ;)

File: quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java [hunk 1]
```diff
@@ -72,6 +73,8 @@ public void beforeEach(ExtensionContext context) throws Exception {
             }
         } else {
             configureProfile(context);
+            // WORKAROUND: this intercepts the output when actually starting the server.
+            QuarkusConsole.installRedirects();
```
Comment (andreaTP) [inline quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java:77]: This workaround is fixed here:

https://github.com/quarkusio/quarkus/pull/22455

Comment (pedroigor) [reply quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java:77]: Looks like we are in the same situation. Do we really need this workaround to make tests stable? I understand it might help when running tests locally out of order, etc.

But I would say we can just wait for the fix from Quarkus.

Comment (pedroigor) [reply quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java:77]: I have no issue in merging with this, but I would prefer to introduce this change only if needed.

Comment (andreaTP) [reply quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java:77]: > Do we really need this workaround to make tests stable?

We do need this workaround for the JVM tests to pass at all ...

Comment (pedroigor) [reply quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java:77]: We do not, at least I can't see any failure looking at the last runs. Neither locally.

**Review by pedroigor — APPROVED** [review]
