### PR TITLE
AuthZEN lookup subject.type=user based upon username not UUID

### LINKED ISSUE #48287: AuthZEN lookup subject.type=user based upon username not UUID
### Description

#47632 implemented user lookups, so that a `subject.id` is expected to be the UUID used by Keycloak to internally identify a user. This is problematic for several reasons:

- It does not work with AuthZen interop and compatibility scenarios, as the id is represented as a Base64 string not a UUID
- It will not work with pairwise subject identifiers, or other scenarios where the returned `sub` claim is modified, as the Keycloak UUID will not be present

Instead we should make it so that the following request results in users being looked up via their username:

```json
"subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
}
```

### PR DESCRIPTION
**Pull request by ryanemerson**
- Remove interop Base64 mapping as now redundant
- Ensure that interop JSON requests are sent exactly as defined to the
  server
- Remove "_note" element from interop scenario as that is removed in the
  next interop scenarios, to be added in a future commit. Keeping this
  element prevents strict request checking on the server-side.

Closes #48287

### CODE REVIEW

File: authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZenResource.java [hunk 1]
```diff
@@ -143,7 +143,7 @@ private Identity resolveSubjectIdentity(RealmModel realm, AuthZen.EvaluationRequ
         AuthZen.Subject subject = request.subject();
         Identity identity = switch (subject.type()) {
             case USER -> {
-                UserModel user = session.users().getUserById(realm, subject.id());
```
Comment (pedroigor) [inline authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZenResource.java:146]: We can resolve from `username`  and fallback to UUID. Even though there is an additional cache hit/miss, it makes the lives of clients easier ...

By looking at the specs around subject (https://openid.net/specs/authorization-api-1_0.html#name-subject) it seems we can also leverage the `properties` claim for additional properties about the subject. For instance, resolving by username by default, but allowing the use of additional properties to identify the subject.

**Review by pedroigor — APPROVED** [review]

File: authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZenResource.java (hunk 1 above)
Comment (pedroigor) [reply authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZenResource.java:146]: As discussed, let us run some follow-ups to explore how to properly support resolving subjects with different identifiers.
