### PR TITLE
Properties mapped in our property mappers are overridden

### LINKED ISSUE #36927: MeterFilter is configured after a Meter has been registered
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When starting the latest Keycloak docker container (`26.1.0-0`) with the parameter `--metrics-enabled=true`, the following warning is shown 5 times:
```
WARN  [io.micrometer.core.instrument.composite.CompositeMeterRegistry] (main) A MeterFilter is being configured after a Meter has been registered to this registry. All MeterFilters should be configured before any Meters are registered. If that is not possible or you have a use case where it should be allowed, let the Micrometer maintainers know at https://github.com/micrometer-metrics/micrometer/issues/4920. Enable DEBUG level logging on this logger to see a stack trace of the call configuring this MeterFilter.
```

Enabling DEBUG (which BTW only works when it's enabled globally) shows this:
[micrometer-debug.txt](https://github.com/user-attachments/files/18590249/micrometer-debug.txt)

### Version

26.1.0

### Regression

- [ ] The issue is a regression

### Expected behavior

No warning messages from Micrometer.

### Actual behavior

Warning message from micrometer is shown.

### How to Reproduce?

Run `docker run -m 1G keycloak/keycloak:26.1.0-0 start-dev --metrics-enabled=true` and look for the warning message in the log

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Fixes #36927

The issue is when the log category is specified in the `application.properties` file as the quarkus property `quarkus.log.category."<category>".level`, it does not take any effect. It started to behave like that after providing changes to https://github.com/keycloak/keycloak/pull/35138.

Basically, when the property mapper has the `.to()` builder method defined, the property is always obtained through the specific property mapper. However, it does not take into account the case when the property is specified in `application.properties`, `quarkus.properties` files, or set in Quarkus - [here](https://github.com/quarkusio/quarkus/pull/46120/files#diff-f6bc4d87c5e57cae3839c0a5b116e6f269bc0622b7526bb0a2b226b5dff1218aR206) and [here](https://github.com/quarkusio/quarkus/blob/4703297f9465b3273eafd419c12c1028816b3300/extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java#L248).

I thought I could provide some general solution, but then I decided it might be better to address this special use case for log categories as the priority of config "sources" differs and we need a different values visualized as:

LoggingPropertyMappers:

```
        .from()                           .mapFrom()                    .mapFrom()
+----------------------+        +--------------------------+        +-----------------+
| log-level-<category> | -----> | log-level=category:level | -----> | log-level=level | -----> default
+----------------------+        +--------------------------+   ^    +-----------------+
                                                               |                 
                                               .to()         | (add)                   
                                           +---------------------------------------+       
                                           | quarkus.log.category.<category>.level | 
                                           +---------------------------------------+

```

### Problem with build

When the augmentation is executed, properties for `quarkus.log` are not considered, but it might be a follow-up issue.

### Diff of logs:
```
INFO  [io.quarkus.hibernate.orm.deployment.HibernateOrmProces <
INFO  [io.quarkus.hibernate.orm.deployment.HibernateOrmProces <
Running the server in development mode. DO NOT use this confi <
INFO  [io.agroal.pool] (JPA Startup Thread) Datasource '<defa	INFO  [io.agroal.pool] (JPA Startup Thread) Datasource '<defa
WARN  [io.micrometer.core.instrument.composite.CompositeMeter <
WARN  [io.micrometer.core.instrument.composite.CompositeMeter <
WARN  [io.micrometer.core.instrument.composite.CompositeMeter <
WARN  [io.micrometer.core.instrument.composite.CompositeMeter <
WARN  [io.micrometer.core.instrument.composite.CompositeMeter <
INFO  [org.keycloak.quarkus.runtime.storage.database.liquibas	INFO  [org.keycloak.quarkus.runtime.storage.database.liquibas
INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheM	INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheM
INFO  [org.infinispan.CONTAINER] (Quarkus Main Thread) Virtua	INFO  [org.infinispan.CONTAINER] (Quarkus Main Thread) Virtua
INFO  [org.infinispan.CONTAINER] (Quarkus Main Thread) ISPN00	INFO  [org.infinispan.CONTAINER] (Quarkus Main Thread) ISPN00
INFO  [org.infinispan.CLUSTER] (Quarkus Main Thread) ISPN0000	INFO  [org.infinispan.CLUSTER] (Quarkus Main Thread) ISPN0000
INFO  [org.infinispan.CLUSTER] (Quarkus Main Thread) ISPN0000 |	INFO  [org.infinispan.CLUSTER] (Quarkus Main Thread) ISPN0000
INFO  [org.infinispan.CLUSTER] (Quarkus Main Thread) ISPN0000 |	INFO  [org.infinispan.CLUSTER] (Quarkus Main Thread) ISPN0000
INFO  [org.keycloak.connections.infinispan.DefaultInfinispanC |	INFO  [org.keycloak.connections.infinispan.DefaultInfinispanC
INFO  [org.keycloak.broker.provider.AbstractIdentityProviderM	INFO  [org.keycloak.broker.provider.AbstractIdentityProviderM
INFO  [org.keycloak.services] (Quarkus Main Thread) KC-SERVIC	INFO  [org.keycloak.services] (Quarkus Main Thread) KC-SERVIC
INFO  [io.quarkus] (Quarkus Main Thread) Keycloak 1 on JVM (p |	INFO  [io.quarkus] (Quarkus Main Thread) Keycloak 1 on JVM (p
INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activate	INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activate
INFO  [io.quarkus] (Quarkus Main Thread) Installed features: 	INFO  [io.quarkus] (Quarkus Main Thread) Installed features:
```

### Suggestion

It would be good to gather more requirements for the wildcard mappers before we make some general approach. We will use the wildcard mappers for additional datasources (https://github.com/keycloak/keycloak/issues/29116), so we can follow-up on this after that.

@vmuzikar @shawkins Could you please check it? Thanks!

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java [hunk 1]
```diff
@@ -288,7 +291,13 @@ private static String resolveCategoryLogLevelFromParentLogLevelOption(String cat
                 rootLevel = categoryLevel.levelName;
             }
         }
-        return rootLevel;
+
+        // If KC property is not set and the 'log-level' does not override the specific category, use value from Quarkus or properties files
+        return Optional.ofNullable(context.proceed("quarkus.log.category.\"" + category + "\".level"))
+                .filter(f -> f.getValue() != null)
```
[the remark this answers is not in the document]
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java]: > It should also work to return a null rootLevel when nothing matches - the PropertyMapper logic will automatically then proceed to the quarkus property.

You're right, it can be like this.

> And not specific to this pr, but is there any concern here for the performance characteristics of wildcardMapFrom, because it's at least n^2 - here for each category it asks about we have to reparse the parent list.

It is true, that the parsing of the parent log-level is executed multiple times. I cache the parsed categories for the parent list and there's a slight improvement in num of samples in terms of CPU and profiling. Thanks for spotting this :)

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java [hunk 2]
```diff
@@ -29,6 +31,8 @@ public final class LoggingPropertyMappers {
     private static final String SYSLOG_ENABLED_MSG = "Syslog is activated";
     private static final String DEFAULT_ROOT_LOG_LEVEL = toLevel(LoggingOptions.LOG_LEVEL.getDefaultValue().orElseThrow().get(0)).getName();
 
+    private static List<CategoryLevel> rootLogLevels;
```
Comment (shawkins) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java:34]: Just to be future proof for testing, can this be reset by AbstractConfigurationTest.resetConfiguration?

Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java:34]: @shawkins Thanks for spotting that.

I rather have it isolated and reset in the prop mappers class below. Should be ok now. 

https://github.com/keycloak/keycloak/pull/37265/files#diff-78e1ea4992f437dbda8637131776d9f1e448a2cf4f6ba2dd986e07ec0d1eb298R40

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java:34]: Sure, that's fine too as it's called by a reset method already. 

Maybe someday we'll have some additional context for static state, rather than having it spread about :)

**Review by shawkins — APPROVED** [review]
Thanks @mabartos this looks good.

The only additional thought would be to expand the comment about using context.proceed - why this shouldn't rely on the PropertyMapping logic (the handling of inherit?)

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

I'll just try and rebase the PR so we test it with the Quarkus 3.18 upgrade that just got merged.
