### PR TITLE
Fix CRL verification failing due to client cert not being in chain

### LINKED ISSUE #19853: CRL Verification failing due to client certificate not being in a chain
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Behavior:

When we Enable X509 Browser certificate authentication and turn CRL checking on with the CRL file option, the user always fails to authenticate. This seems to be due to Keycloak expecting a chain of certificates from the Client cert rather than just the client cert. As far as I can tell, it is not standard for the client cert to contain the CA Chain, so Keycloak always end up with this error:

```20T21:27:46.901Z","sequence":8562,"loggerClassName":"org.jboss.logging.DelegatingBasicLogger","loggerName":"org.keycloak.services","level":"ERROR","message":"Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it","threadName":"executor-thread-3","threadId":118,"mdc":{},"ndc":"","hostName":"ip-10-38-1-109.us-gov-west-1.compute.internal","processName":"QuarkusEntryPoint","processId":77,"exception":{"refId":1,"exceptionType":"java.security.GeneralSecurityException","message":"Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it","frames":[{"class":"org.keycloak.utils.CRLUtils","method":"check","line":55},{"class":"org.keycloak.authentication.authenticators.x509.CertificateValidator","method":"checkRevocationStatusUsingCRL","line":737},{"class":"org.keycloak.authentication.authenticators.x509.CertificateValidator","method":"checkRevocationStatusUsingCRLDistributionPoints","line":760},```

Can this be fixed to accept the child client cert and get its issuer from there? Rather than forcing a minimum length of two certificates?

```
    public static void check(X509Certificate[] certs, X509CRL crl, KeycloakSession session) throws GeneralSecurityException {
        if (certs.length < 1) {
            throw new GeneralSecurityException("Not possible to verify signature on CRL. X509 certificate doesn't exist");
        }

        X500Principal crlIssuerPrincipal = crl.getIssuerX500Principal();
        X509Certificate crlSignatureCertificate = null;

        // Try to find the certificate in the CA chain, which was used to sign the CRL
        for (int i=0 ; i<certs.length ; i++) {
            X509Certificate currentCert = certs[i];
            if (crlIssuerPrincipal.equals(currentCert.getIssuerX500Principal())) {
                crlSignatureCertificate = currentCert;

                log.tracef("Found certificate used to sign CRL in the CA chain of the certificate. CRL issuer: %s", crlIssuerPrincipal);
                break;
            }
        }
```

### Version

21.1.0

### Expected behavior

Users be able to login with x509 Certificate and CRL checking to be working.

### Actual behavior

When CRL checking is turned on in the browser auth flow, and a CRL file is specified.  Users gets rejected due to failed CRL verification.

```20T21:27:46.901Z","sequence":8562,"loggerClassName":"org.jboss.logging.DelegatingBasicLogger","loggerName":"org.keycloak.services","level":"ERROR","message":"Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it","threadName":"executor-thread-3","threadId":118,"mdc":{},"ndc":"","hostName":"ip-10-38-1-109.us-gov-west-1.compute.internal","processName":"QuarkusEntryPoint","processId":77,"exception":{"refId":1,"exceptionType":"java.security.GeneralSecurityException","message":"Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it","frames":[{"class":"org.keycloak.utils.CRLUtils","method":"check","line":55},{"class":"org.keycloak.authentication.authenticators.x509.CertificateValidator","method":"checkRevocationStatusUsingCRL","line":737},{"class":"org.keycloak.authentication.authenticators.x509.CertificateValidator","method":"checkRevocationStatusUsingCRLDistributionPoints","line":760},```

Can this be fixed to accept the child client cert and get its issuer from there? Rather than forcing a minimum length of two certificates?

```
    public static void check(X509Certificate[] certs, X509CRL crl, KeycloakSession session) throws GeneralSecurityException {
        if (certs.length < 1) {
            throw new GeneralSecurityException("Not possible to verify signature on CRL. X509 certificate doesn't exist");
        }

        X500Principal crlIssuerPrincipal = crl.getIssuerX500Principal();
        X509Certificate crlSignatureCertificate = null;

        // Try to find the certificate in the CA chain, which was used to sign the CRL
        for (int i=0 ; i<certs.length ; i++) {
            X509Certificate currentCert = certs[i];
            if (crlIssuerPrincipal.equals(currentCert.getIssuerX500Principal())) {
                crlSignatureCertificate = currentCert;

                log.tracef("Found certificate used to sign CRL in the CA chain of the certificate. CRL issuer: %s", crlIssuerPrincipal);
                break;
            }
        }
```

### How to Reproduce?

1. Create a login Browser flow using x509 certificate check
2. Turn on CRL checking and specify a CRL file
3. Login with a certificate that is signed by a single root CA

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #19853

Just superseding PR #24760 to include a test with a single certificate with no CA trust anchor in the chain.

### CODE REVIEW

File: services/src/main/java/org/keycloak/utils/CRLUtils.java [hunk 1]
```diff
@@ -51,15 +51,15 @@ public final class CRLUtils {
      * @throws GeneralSecurityException if some error in validation happens. Typically certificate not valid, or CRL signature not valid
      */
     public static void check(X509Certificate[] certs, X509CRL crl, KeycloakSession session) throws GeneralSecurityException {
-        if (certs.length < 2) {
-            throw new GeneralSecurityException("Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it");
+        if (certs == null || certs.length < 1) {
+            throw new GeneralSecurityException("Not possible to verify signature on CRL because no certificate chain passed.");
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/utils/CRLUtils.java:55]:
```suggestion
            throw new GeneralSecurityException("Not possible to verify signature on CRL because no certificate chain was passed.");
```

File: services/src/main/java/org/keycloak/utils/CRLUtils.java [hunk 2]
```diff
@@ -51,15 +51,15 @@ public final class CRLUtils {
...
         }
 
         X500Principal crlIssuerPrincipal = crl.getIssuerX500Principal();
         X509Certificate crlSignatureCertificate = null;
 
         // Try to find the certificate in the CA chain, which was used to sign the CRL
-        for (int i=1 ; i<certs.length ; i++) {
+        for (int i=0 ; i<certs.length ; i++) {
             X509Certificate currentCACert = certs[i];
```
Comment (jonkoops) [inline services/src/main/java/org/keycloak/utils/CRLUtils.java:63]: If the index starts at `0`, and the value is never used this might as well be a regular for loop.

```suggestion
        for (X509Certificate currentCACert: certs) {
```

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509SingleCertificateBrowserCRLTest.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+ * @author rmartinc
+ */
+public class X509SingleCertificateBrowserCRLTest extends AbstractX509AuthenticationTest {
+
+    @ClassRule
+    public static CRLRule crlRule = new CRLRule();
+
+    @Drone
+    @PhantomJSBrowser
+    private WebDriver phantomJS;
```
Comment (jonkoops) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509SingleCertificateBrowserCRLTest.java:41]: Ideally we'd try to avoid introducing more PhantomJS (see #9979), but since `AbstractX509AuthenticationTest` is heavily based on it there is very little we can do.

**Review by jonkoops — DISMISSED** [review]

File: services/src/main/java/org/keycloak/utils/CRLUtils.java (hunk 1 above)
Comment (rmartinc) [reply services/src/main/java/org/keycloak/utils/CRLUtils.java]: Done!

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509SingleCertificateBrowserCRLTest.java (hunk 3 above)
Comment (rmartinc) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509SingleCertificateBrowserCRLTest.java:41]: All x509 tests use the phantom, so I just followed the same idea. So when the x509 tests were changed to use another thing this one will be just one more test to change. Not doing anything here.

Comment (jonkoops) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509SingleCertificateBrowserCRLTest.java:41]: Indeed, nothing that can be done about it until the testing team gets to it :)

**Review by jonkoops — APPROVED** [review]
LGTM!

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509SingleCertificateBrowserCRLTest.java (hunk 3 above)
Comment (mposolda) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509SingleCertificateBrowserCRLTest.java:41]: +1 , FYI. There is WiP by @Aboullos from QA team for refactoring of X.509 tests to make them get rid of PhantomJS

**Review by mposolda — APPROVED** [review]
@rmartinc @jonkoops Thanks for the fix and review!
