### PR TITLE
KEYCLOAK-18334 Fix null pointer exception when viewing flow executions

### LINKED ISSUE #10371: NPE when viewing flow executions and authentication provider not deployed
### Describe the bug

See https://issues.redhat.com/browse/KEYCLOAK-18334

### Version

17.0.0-SNAPSHOT

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java [hunk 1]
```diff
@@ -566,6 +566,9 @@ public void recurseExecutions(AuthenticationFlowModel flow, List<AuthenticationE
             } else {
                 String providerId = execution.getAuthenticator();
                 ConfigurableAuthenticatorFactory factory = CredentialHelper.getConfigurableAuthenticatorFactory(session, providerId);
+                if (factory == null) {
+                    throw new NotFoundException("Could not find authenticator provider");
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java:570]: Minor: will it be possible to add `logger.warnf("Cannot find authentication provider implementation with provider ID '%s'", providerId);`

So that user is aware of what the missing authenticator is?

**Review by mposolda — CHANGES_REQUESTED** [review]
@treydock Thanks for the PR and sorry for late response. Will be nice to have this. I've added one minor comment to this.

Also it will be nice to have automated test for this. For example creating simple authentication flow with some non-existing provider and check that admin REST API returns NotFound response as expected. Is it fine for you to create new test method for example to the `ExecutionTest` class for this?

File: services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java (hunk 1 above)
Comment (treydock) [reply services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java:571]: I made this change.

Comment (mposolda) [reply services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java:571]: Thanks!

**Comment by mposolda** [comment]
> > Also it will be nice to have automated test for this. For example creating simple authentication flow with some non-existing provider and check that admin REST API returns NotFound response as expected. Is it fine for you to create new test method for example to the `ExecutionTest` class for this?
> 
> My Java is extremely basic, I can sometimes patch bugs but that usually involves lots of trial/error and Google searches. I'm not sure I have the Java know-how to add any kind of testing unfortunately.

I understand. This is very basic change and doesn't have any side-effects, so accepting your PR. Thanks!
