### PR TITLE
MapUserProvider in KC20 needs to store username compatible with KC19 …

### LINKED ISSUE #14678: MapUserProvider in KC20 needs to store username compatible with KC19 to be no-downtime-upgradable
### Describe the bug

PR #13183 introduced a new searchable field USERNAME_CASE_INSENSITIVE that stores for the JPA store the username in lower case, and preserves the case for the USERNAME field.

To be no-downtime-upgradable, the two versions KC19 and KC20 would need to do same things: 

KC19: 
* Writes USERNAME with always Java's lowercase to the database for new entities
* When searching for a user, applies case-insensitive search to USERNAME field using ILIKE
* When reading a version 2 entity, will write the entity in version 1 

KC20: 
* Has REALM_ATTR_USERNAME_CASE_SENSITIVE_DEFAULT set to "false"
* Writes USERNAME always with the original case
* When searching for a user, applies Java's lowercase to the search string and compares that to the USERNAME_CASE_INSENSITIVE for version 2 entities, and to  USERNAME for version 1 entities.
  :warning: so this requires all USERNAMEs to be lowercase on version 1 entities :warning:

Scenario that is problematic (tested with JPA store): 
* Create a new user with KC20 with a mixed-case-username (creating a V2 entity)
* Updating the user with KC19 - this will preserve the mixed case username, and write the entity as a V1 entity
* Login on KC20 fails, as it would search for a username that is all lowercase in the field USERNAME in the database.
  :musical_note: this will be "healed" once the user is changed on KC20, writing the entity as a V2 to the database :musical_note:

### Version

20.0.0-SNAPSHOT

### Expected behavior

When using the new store, two versions of KC should be allowed to run in parallel and should provider meaningful results, in this case users can be created in both versions and then log in or modify their user with both instances.

### Actual behavior

As described above, this could lead to a user not logging in in the new version of Keycloak.

### Anything else?

Once an existing field is filled with different data, this can lead to unexpected results.

Could be fixed by a KC19 patch release that always ensure that the username is lowercase (especially on downgrades), or in KC20 if that would use ILIKE on usernames as the old version did.

Returning a username in mixed case in the user list is also a change in behavior, yet I wasn't able to create a failing scenario from this.

### PR DESCRIPTION
**Pull request by vramik**
…to be no-downtime-upgradable

Closes #14678

### CODE REVIEW

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java [hunk 1]
```diff
@@ -62,11 +62,7 @@
  * @author <a href="mailto:sguilhen@redhat.com">Stefan Guilhen</a>
  */
 @Entity
-@Table(name = "kc_user",
-        uniqueConstraints = {
-                @UniqueConstraint(columnNames = {"realmId", "username"}),
-                @UniqueConstraint(columnNames = {"realmId", "emailConstraint"})
-        })
```
Comment (vramik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:69]: I've noticed there are no constraints in the db, therefore this is removed from here. I was wondering whether we should add the constrains instead of removing it from here.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java [hunk 2]
```diff
@@ -232,16 +230,19 @@ public void setRealmId(String realmId) {
...
     }
 
+    /**
+     * @return User's username with respecting letter case.
+     */
     @Override
     public String getUsername() {
-        if (this.isMetadataInitialized()) return this.metadata.getUsername();
-        return this.username;
+        if (this.isMetadataInitialized()) return this.metadata.getUsernameWithCase();
```
Comment (hmlnarik) [inline model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:238]: Will this work with entityversion 1?

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java (hunk 1 above)
Comment (hmlnarik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:69]: I this we should add the constraints for
`@UniqueConstraint(columnNames = {"realmId", "username", "usernameWithCase"})` - `username` is present always, and if the same, it could only be due to difference in `usernameWithCase`. WDYT?

Comment (vramik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:69]: It makes sense to me. Would you prefer do it within this issue or should I create a new one to deal with the constraints?

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java (hunk 2 above)
Comment (vramik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:238]: It should work now when the migration of the entity was fixed in the last force-push. Each entity loaded from the database should have the usernameWithCase field filled. Or am I missing something?

Comment (hmlnarik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:238]: The migration fixed the functional part when the username is loaded from JSON, thank you.
Will the V1 have the `this.usenameWithCase` field filled when loading the value from column directly in the next line?

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java (hunk 1 above)
Comment (hmlnarik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:69]: I would prefer a new issue.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java [hunk 3]
```diff
@@ -804,8 +804,7 @@ public void salesPostTestCompositeRoleForUser() {
         UserRepresentation topGroupUser = createUserRepresentation("topGroupUser", "top@redhat.com", "", "", true);
         setPasswordFor(topGroupUser, PASSWORD);
 
-        String expectedString = StoreProvider.getCurrentProvider().isMapStore() ? "principal=topGroupUser" : "principal=topgroupuser";
```
Comment (ahus1) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java:807]: I'd like to see a code comment describing the reason for having this switch, for example "map storage preserves the case of users" - otherwise it would be hard for future readers to understand why the statement is there. Alternatively, you could have a case-insensitive comparison for the suffix (everything after "principal=").

Looking at it again, and with the changes in the mapper, this isn't something that depends on the map store, but on the realm setting in a map store. With the default being false (as now implemented in the mapper), it should be lower case.

File: model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java [hunk 4]
```diff
@@ -49,7 +51,8 @@ public String getId() {
 
     @Override
     public String getUsername() {
-        return entity.getUsername();
+        Boolean usernameCaseSensitiveAttribute = realm.getAttribute(REALM_ATTR_USERNAME_CASE_SENSITIVE, REALM_ATTR_USERNAME_CASE_SENSITIVE_DEFAULT);
+        return usernameCaseSensitiveAttribute ? entity.getUsername() : entity.getUsername().toLowerCase();
```
Comment (ahus1) [inline model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java:55]: I like the new behavior that when the realm attribute is set to false, the username is returned in a case-insensitive format. This is something that wasn't in the change before, and I believe of the changes to the tests need to be reverted to their original state. 

I'm was actually expecting this conversion to happen on the physical layer (JPA implementation). Maybe @hmlnarik could comment on this.

**Review by ahus1 — CHANGES_REQUESTED** [review]
I like the new behavior that when the realm attribute is set to false, the username is returned in a case-insensitive format. I believe some of the tests need to be reverted to reflect that. Please see more comments below.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java (hunk 2 above)
Comment (vramik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:238]: I see, it won't. I'll add fallback to `username` filed in case of `usernameWithCase` is null.

File: model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java (hunk 1 above)
Comment (vramik) [reply model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java:69]: https://github.com/keycloak/keycloak/issues/14797

File: model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java (hunk 4 above)
Comment (vramik) [reply model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java:55]: > This is something that wasn't in the change before, and I believe of the changes to the tests need to be reverted to their original state.

Do you mean reverting test changes from https://github.com/keycloak/keycloak/pull/13183?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java (hunk 3 above)
Comment (vramik) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java:807]: So do I get it right there is no need to add the comment there?

Comment (ahus1) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java:807]: Yes - when the change is reverted, no comment is needed.

File: model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java (hunk 4 above)
Comment (ahus1) [reply model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java:55]: > Do you mean reverting test changes from https://github.com/keycloak/keycloak/pull/13183?

Yes - I assume those will fail anyway due to the username being returned in lowercase as long as the setting is false.

Comment (vramik) [reply model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java:55]: I can revert those, np with that. Just a note the tests there were updated mostly to lowered case username so it should pass regardless of the setting.

Comment (ahus1) [reply model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java]: You were write, the changed tests would pass. Still I think was good to reverted the ignore-case tests as you did, as checking the case in the tests instead of ignoring it looks better to me. 

This is now resolved for me.

**Review by ahus1 — APPROVED** [review]
I have reviewed the changes and tests them with Keycloak 19.0.3 and this version running against the same database using JPA map storage. I tested it with different scenarios where both write their entity version to the DB, and it works fine. Thank you for preparing this change!

**Review by hmlnarik — APPROVED** [review]
Thank you for the PR!
