### PR TITLE
Validate realm name for uniqueness before creating a new realm in the DB

### LINKED ISSUE #38426: New realm creation should validate the name uniqueness before hitting the DB
### Description

When creating  a new realm, if a realm with the same name already exists Keycloak actually attempts to create this realm in the DB, failing due to unique constraint violation. As a result, the logs display a DB error message along with stack traces and the admin console shows a generic message instructing the admin to check the logs.

Keycloak should simply validate no other realm exists with the same name before attempting to create the realm in the DB, like we do for users that we check for unique usernames or e-mails before storing the users. The endpoint should return a CONFLICT with a descriptive message that clearly indicates the name is already in use. 

### Discussion

_No response_

### Motivation

The main motivation for enhancing the validation is to prevent unnecessary DB error messages being displayed in the logs when a simple validation should suffice.

### Details

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
Closes #38426

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

File: services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java [hunk 1]
```diff
@@ -174,9 +174,8 @@ public Response importRealm(InputStream requestBody) {
 
             return Response.created(location).build();
         } catch (ModelDuplicateException e) {
-            logger.error("Conflict detected", e);
             if (session.getTransactionManager().isActive()) session.getTransactionManager().setRollbackOnly();
-            throw ErrorResponse.exists("Conflict detected. See logs for details");
+            throw ErrorResponse.exists("Realm with same name already exists");
```
Comment (ahus1) [inline services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java:178]: There is `KeycloakErrorHandler.getResponse()` that should already handle any `ModelException`. 

So I suggest to remove the code of catching `ModelDuplicateException`, `ModelIllegalStateException` and `ModelException` altogether. Looking at the code, I am a bit worried that sometimes the transaction is rolled back, and sometimes not. 

If you feel in the mood, it might be good to deprecate the `ModelDuplicateException` with a no-arg constructor so we enfore that we always set an error message that can be shown to the user.

**Review by ahus1 — CHANGES_REQUESTED** [review]
In general I am in favor of this change. See below for a possibly simplification.

File: services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java (hunk 1 above)
Comment (sguilhen) [reply services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java]: Thanks for the feedback, @ahus1 ! I've applied all your suggestions

**Review by ssilvert — DISMISSED** [review]

**Comment by sguilhen** [comment]
I'll look into the test failures later today

File: services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java (hunk 1 above)
Comment (ahus1) [reply services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java]: It seems that my previous comment was only partially correct: While the KeycloakErrorHandler recognizes at least some of the exceptions, it maps a plain `ModelException` to a server error and not to a client error.  

So it might be necessary to bring back 

```
} catch (ModelException e) {
       throw ErrorResponse.error(e.getMessage(), Response.Status.BAD_REQUEST);
}
```

to avoid regressions. Treating all `ModelException`s as bad requests is likely beyond this PR, and would be a breaking change in a minor release to consumers. Possibly something for KC 27

Comment (sguilhen) [reply services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java]: Yeah, I came to the same conclusion. I was spending some time trying to find out a way to fix how the model exceptions are handled. But as you said, it is well beyond the scope of this PR.

Comment (sguilhen) [reply services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java]: Not related to this PR, but indicates we seem to have a broader issue handling exceptions

**Comment by sguilhen** [comment]
@pedroigor or @ahus1 could you re-run the failed operator tests, please?

**Comment by sguilhen** [comment]
Not sure the UI tests are related - they passed before I rebased @ahus1 @pedroigor

**Review by pedroigor — APPROVED** [review]

**Comment by sguilhen** [comment]
@ahus1 can you re-review this one?

**Review by ahus1 — APPROVED** [review]
Thank you for the change. I see that the error code for `ModelIllegalStateException` might now differ from before, still I think the "bad request" is more accurate here.

**Comment by ahus1** [comment]
@ssilvert - can you please re-approve, as a UI team review is needed?

**Comment by sguilhen** [comment]
> Thank you for the change. I see that the error code for `ModelIllegalStateException` might now differ from before, still I think the "bad request" is more accurate here.

I think KeycloakErrorHandler still sets the code to INTERNAL_SERVER_ERROR when handling this particular exception. So unless I'm missing something there should not be a difference there.

**Review by ssilvert — APPROVED** [review]
