### PR TITLE
Admin UI: User Profile always render multi valued inputs for multi valued input types.

### LINKED ISSUE #24311: User Profile input type mulitselect-checkboxes not rendered correctly when values selected
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Input type "mulitselect-checkboxes" is rendered as generic multi-value input type after selecting a second value.

screen-record

### Version

22.0.5

### Expected behavior

Checkboxes remain visible.

### Actual behavior

Checkboxes are replaced with text input elements.

### How to Reproduce?

Create an attribute with input-type "mulitselect-checkboxes" and validation options. Permission: Admin can edit.
image

Edit a user and select two checkboxes.

### Anything else?

The bug also occurs with inputType "multiselect"

### LINKED ISSUE #24318: User attribute array data gets stored as comma-separated value if no specific input type annotation present
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When a user attribute value contains multiple values and no annotation is set to render it as multi-value field, it is rendered as text field with comma-separated string. Editing this string causes the comma separated string value to be stored.
The original array of values is replaced with a single value.

screen-record

### Version

22.0.5

### Expected behavior

The attribute with multipe-values should not get lost.

### Actual behavior

A comma separated string is stored.

### How to Reproduce?

1) Store multiple values in an attribute of a user, e.g. by 

 - configuring input type 'multiselect'
 - update a user and add two values
 - remove input type annotation

2) Update the user. The input is rendered as simple text field.

image

3) Add an entry as if you would believe it should be done (",newentry") and save the user

### Anything else?

This bug may cause accidental data corruption by Admins.

Thought that this bug was already reported and fixed in #20837. 
Maybe it was re-introduced with #23911?

### PR DESCRIPTION
**Pull request by antikalk**
Always render multi valued inputs for multi valued input types.

Closes #24311
Closes #24318

### CODE REVIEW

File: js/apps/admin-ui/src/user/UserProfileFields.tsx [hunk 1]
```diff
@@ -200,8 +206,12 @@ function determineInputType(
     return DEFAULT_INPUT_TYPE;
   }
 
-  // An attribute with multiple values is always multi-valued, even if an input type is provided.
-  if (Array.isArray(value) && value.length > 1) {
+  // For a non-multi value allowed input type, check if multiple values are provided, if so fall back to multi-input.
+  if (
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/UserProfileFields.tsx:210]: I think we should improve the `determineInputType()` function a little, so that there is a bit more explanation behind the choices being made here:

```ts
function determineInputType(
  attribute: UserProfileAttributeMetadata,
  value: string | string[],
): InputType {
  // Always treat the root attributes as a text field.
  if (isRootAttribute(attribute.name)) {
    return "text";
  }

  const inputType = attribute.annotations?.inputType;

  // If the attribute has no valid input type, fall back to a default input type.
  // Depending on the length of the value, we either use a 'multi-input' or a 'text' input type so all values are always visible.
  if (!isValidInputType(inputType)) {
    return value.length > 1 ? "multi-input" : "text";
  }

  // If the input type is multi-valued, we don't have to do any further checks, as we know all values will always show up.
  if (MULTI_VALUED_INPUT_TYPES.includes(inputType)) {
    return inputType;
  }

  // An attribute with multiple values is always as a 'multi-input', even if a singular input type is provided.
  // This is done so that the user can edit the attribute without accidentally truncating the other values that would otherwise be hidden.
  if (Array.isArray(value) && value.length > 1) {
    return "multi-input";
  }

  return inputType;
}
```

WDYT?

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by jonkoops — CHANGES_REQUESTED** [review]
The code looks good, but it is causing some of the tests to fail. Could you take a look at those @antikalk?

**Review by jonkoops — APPROVED** [review]
LGTM

**Comment by jonkoops** [comment]
@antikalk it seems that @edewit opened up [a PR](https://github.com/keycloak/keycloak/pull/24382) that touches this code as well to fix [this issue](https://github.com/keycloak/keycloak/issues/24318). However, I think your PR also fixes this issue, could you confirm this is the case? If so, I will link that issue to this PR as well.

**Comment by antikalk** [comment]
> @antikalk it seems that @edewit opened up [a PR](https://github.com/keycloak/keycloak/pull/24382) that touches this code as well to fix [this issue](https://github.com/keycloak/keycloak/issues/24318). However, I think your PR also fixes this issue, could you confirm this is the case? If so, I will link that issue to this PR as well.

Yes the PR also fixes this issue (thanks to your suggested change for the invalid input type return). What I did: 

1. Created a new realm
2. Created a new user "tester"
3. Added multiple values for attribute "test"
4. Enabled user profile and configured attribute test without input type
5. Went to the details of the user "tester"
6. "test" attribute was rendered in multiline, as multi value input :)

**Comment by jonkoops** [comment]
Thanks a bunch for validating this @antikalk. I will go ahead and link the issue.

**Review by edewit — APPROVED** [review]
I think the logic can be a bit more simplified, but it works like this
