### PR TITLE
Ensure org group membership checks the org the user is member of

### LINKED ISSUE #47137: Ensure org group membership checks the org the user is member of
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

The `groupMemberships` endpoint in `OrganizationMemberResource` use `getUser(memberId)` which only checks that the user exists in the realm — we should verify that the user is actually a member of the organization in the URL path. 

`GET /organizations/{orgA}/members/{userId}/groups` with a user who belongs to orgB (but not orgA) and it would return their group memberships from orgB, leaking cross-organization data. 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

see desc

### Actual behavior

see desc

### How to Reproduce?

see desc

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vramik**
Closes #47137

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/group/OrganizationGroupMembershipTest.java [hunk 1]
```diff
@@ -535,4 +535,38 @@ public void testGetMemberGroupMembershipsWithSearch() {
...
+        List<GroupRepresentation> orgBGroups = orgB.members().member(memberB.getId()).groups(null, null, true);
+        assertThat(orgBGroups, hasSize(1));
+
+        // Try to get memberB's group memberships via orgA - should return 404
+        try {
+            orgA.members().member(memberB.getId()).groups(null, null, true);
+            fail("Should not be able to get group memberships for a non-member of the organization");
+        } catch (jakarta.ws.rs.NotFoundException expected) {
+            // expected - memberB is not a member of orgA
+        }
```
Comment (sguilhen) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/group/OrganizationGroupMembershipTest.java:570]: Just a small thing - not a blocker for this but maybe something for the next PRs. I've recently realized there's an `assertThrows` that helps a lot when handling these "exception is expected here" cases. If you want, check the SCIM `FilterTest` for some examples.

**Review by sguilhen — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]
