### PR TITLE
fix user profile form saving

### LINKED ISSUE #22982: User attributes can't be saved when user profile is enabled
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

User attributes can't be saved

### Version

main

### Expected behavior

Attributes are saved

### Actual behavior

not

### How to Reproduce?

Enable the user profile on the realm
Add a custom attribute
Open the user details
Fill the field you just created
Press save
Reload the page and see the field go blank

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #22982

### CODE REVIEW

File: js/apps/admin-ui/src/user/EditUser.tsx [hunk 1]
```diff
@@ -58,80 +57,21 @@ export default function EditUser() {
...
-  );
-}
-
-type EditUserFormProps = {
-  user: UserRepresentation;
-  bruteForced: BruteForced;
-  refresh: () => void;
-};
-
-const EditUserForm = ({ user, bruteForced, refresh }: EditUserFormProps) => {
```
Comment (jonkoops) [inline js/apps/admin-ui/src/user/EditUser.tsx:101]: Why get rid of the separate component for the form?

Comment (edewit) [reply js/apps/admin-ui/src/user/EditUser.tsx:101]: because it didn't update the user with this `useUpdateEffect`

**Comment by jonkoops** [comment]
@edewit looks like the CI is failing and there are some conflicts, could you take a look at it?

**Review by jonkoops — APPROVED** [review]
