### PR TITLE
Use admin console correctly in KeycloakIdentity

### LINKED ISSUE #29688: client_authorization_test fails
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

client_authorization_test fails consistently

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Test passes

### Actual behavior

Test fails

### How to Reproduce?

At least since [May 16](https://github.com/keycloak/keycloak/actions/runs/9104361542), the client_authorization_test fails in `main`
Last known date when this test ran successfully was [May 13](https://github.com/keycloak/keycloak/actions/runs/9055245281)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hmlnarik**
Fixes: #29688
Relates to: #29640

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java [hunk 1]
```diff
@@ -97,12 +97,17 @@ class MgmtPermissions implements AdminPermissionEvaluator, AdminPermissionManage
...
-                || Constants.ADMIN_CONSOLE_CLIENT_ID.equals(auth.getToken().getIssuedFor())) {
-            this.identity = new UserModelIdentity(auth.getRealm(), auth.getUser());
+        final String issuedFor = auth.getToken().getIssuedFor();
 
+        if (Constants.ADMIN_CLI_CLIENT_ID.equals(issuedFor) || Constants.ADMIN_CONSOLE_CLIENT_ID.equals(issuedFor)) {
+            this.identity = new UserModelIdentity(auth.getRealm(), auth.getUser());
         } else {
-            this.identity = new KeycloakIdentity(auth.getToken(), session);
+            ClientModel client  = session.clients().getClientByClientId(auth.getRealm(), issuedFor);
+            if (client != null && Boolean.parseBoolean(client.getAttribute(Constants.SECURITY_ADMIN_CONSOLE_ATTR))) {
```
Comment (hmlnarik) [inline services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java:106]: This is a condition similar to the one added in the #29646

**Review by rmartinc — APPROVED** [review]
Thanks @hmlnarik! LGTM!

**Review by mposolda — APPROVED** [review]
Approving as well based on @rmartinc review

**Review by ssilvert — APPROVED** [review]
