### PR TITLE
Change supported criteria for Google Authenticator

### LINKED ISSUE #27349: Google Authenticator now supports SHA256 and SHA512
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Google Authenticator provider is not included in the list of supported authenticators if algorithm is not SHA1 and if number of digits is not 6

https://github.com/keycloak/keycloak/blob/e2ed9791efb3039692e18133151d473a69c0ef32/services/src/main/java/org/keycloak/authentication/otp/GoogleAuthenticatorProvider.java#L25-L31

This information seems outdated since the app now works with other hash algorithms too and can generate 8 digit numbers.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Google Authenticator should be listed in supported authenticator apps even if 
* OTP policy sets hash algorithm to SHA256 or SHA512.
* OTP policy sets number of digits to 8.

### Actual behavior

Google Authenticator is not included in list of supported OTP authenticators if OTP policy sets hash algorithm SHA256 or  SHA512  or if digits is set to 8.

### How to Reproduce?

Configure SHA256 or SHA512 or number of digits 8 and see that Google Authenticator disappears from the list of supported authenticators. The list is displayed when user is setting up an authenticator app in the account console or when administrator configures OTP policy.

To validate that Google Authenticator still works even if it is not in the list:

1. Download latest Google Authenticator (Android app, updated in Play Store on 2023-05-18). 
2. Change Keycloak's OTP policy to SHA256 and SHA512, and number of digits to 8.
3. Setup authenticator app for user in account console, double check that hash algorithm was changed (click "Unable to scan?" to see parameters)
5. Check that OTP code can be validated successfully even when SHA256 or SHA512 is set as hash algorithm.
6. Check that OTP code can be validated successfully even when number of digits is set to 8.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tsaarni**
This change adds Google Authenticator to the list of supported authenticator apps, also when OTP policy sets any combination of:

- hash algorithm: SHA256 or SHA512
- number of digits:  8
- OTP type: HOTP 

The list of supported authenticators is visible in admin console in OTP policy page, and in account console when user adds authenticator. Before this PR, Google Authenticator was not listed as supported, even though the latest version of the app works under these OTP parameters.

Fixes #27349

### CODE REVIEW

**Comment by tsaarni** [comment]
I've tested also Microsoft Authenticator, but it still has the old limitations so no changes needed there.

File: services/src/main/java/org/keycloak/authentication/otp/GoogleAuthenticatorProvider.java [hunk 1]
```diff
@@ -22,14 +22,6 @@ public String getName() {
...
     public boolean supports(OTPPolicy policy) {
-        if (policy.getDigits() != 6) {
-            return false;
-        }
-
-        if (!policy.getAlgorithm().equals("HmacSHA1")) {
-            return false;
-        }
-
         return policy.getType().equals("totp") && policy.getPeriod() == 30;
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/authentication/otp/GoogleAuthenticatorProvider.java:25]: I think google authenticator also supports `hotp` now. Can you please test?
If that the case  then the only limitation is that it just supports 30s for totp.

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks a lot @tsaarni for the PR!
I think that google authenticator also supports hotp in all the formats. If I'm right please update the method to also add hotp. You can also add one more test for that if you want.

File: services/src/main/java/org/keycloak/authentication/otp/GoogleAuthenticatorProvider.java (hunk 1 above)
Comment (tsaarni) [reply services/src/main/java/org/keycloak/authentication/otp/GoogleAuthenticatorProvider.java]: Oh, that is true! hotp also worked now!  Updated accordingly.

**Review by rmartinc — APPROVED** [review]
Thanks a lot @tsaarni! LGTM!

**Review by mposolda — APPROVED** [review]
@tsaarni @rmartinc Thanks for the fix and review!
