### PR TITLE
Fix deny unsupported FGAPv2 token-exchange audience checks

### LINKED ISSUE #46718: UnsupportedOperationException in V1 Token Exchange Audience Validation (FGAPv2 Incompatibility)
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

Thank you for binreaper for submitting this to our bug bounty program in YWH-PGM40475-143

## Summary

Keycloak 26.5.3 crashes with `UnsupportedOperationException` when performing a V1 token exchange with an `audience` parameter targeting a different client. The `V1TokenExchangeProvider.validateAudience()` calls `AdminPermissions.management().clients().canExchangeTo()`, which dispatches to `ClientPermissionsV2` when FGAPv2 is enabled (default in 26.5.3). `ClientPermissionsV2.canExchangeTo()` throws `UnsupportedOperationException("Not supported in V2")` instead of performing the authorization check, resulting in an HTTP 500 error.

## Vulnerability Type

Denial of Service / Improper Error Handling (CWE-754: Improper Check for Unusual or Exceptional Conditions)

## Affected Component(s)

- `services/src/main/java/org/keycloak/services/resources/admin/fgap/ClientPermissionsV2.java` — line 142-143
- Called from: `V1TokenExchangeProvider.validateAudience()` — line 254

## Keycloak Configuration Context

- TOKEN_EXCHANGE feature enabled (`--features=preview` or `--features=token-exchange`)
- FGAPv2 (Fine-Grained Admin Permissions V2) enabled — this is `Type.DEFAULT` in 26.5.3, so it applies to ALL default installations
- Any realm with at least two clients

### Version

26.5.3 

### Regression

- [ ] The issue is a regression

### Expected behavior

Do not log exceptions in the server log. 

Suggestions from the hunter: 

**Option 1** (preferred): Implement `canExchangeTo()` in `ClientPermissionsV2` using the V2 permission evaluation framework.

**Option 2**: Graceful fallback — return `false` (deny) instead of throwing:
```java
@Override
public boolean canExchangeTo(ClientModel authorizedClient, ClientModel to, AccessToken token) {
    return false; // V2 does not yet support client exchange permissions
}
```

**Option 3**: Guard in `V1TokenExchangeProvider` with try-catch around the `canExchangeTo()` call, returning HTTP 403 on `UnsupportedOperationException`.

### Actual behavior

500 response code, and an exception in the server log. 

## Steps to Reproduce (PoC)

1. Start Keycloak 26.5.3 with token exchange enabled:
```
docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin \
  quay.io/keycloak/keycloak:26.5.3 start-dev --features=preview
```

2. Create a realm "test" with a user "alice" (password: alice123) and ensure at least two clients exist (admin-cli and broker are present by default).

3. Get a user token:
```bash
TOKEN=$(curl -s -X POST http://localhost:8080/realms/test/protocol/openid-connect/token \
  -d "grant_type=password&client_id=admin-cli&username=alice&password=alice123" \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])")
```

4. Attempt token exchange with a different audience:
```bash
curl -v -X POST http://localhost:8080/realms/test/protocol/openid-connect/token \
  -d "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
  -d "client_id=admin-cli" \
  -d "subject_token=$TOKEN" \
  -d "subject_token_type=urn:ietf:params:oauth:token-type:access_token" \
  -d "audience=broker"
```

5. **Expected**: HTTP 403 (exchange not permitted) or HTTP 200 (exchange succeeded)
   **Actual**: HTTP 500 Internal Server Error:
```json
{"error":"unknown_error","error_description":"For more on this error consult the server log."}
```

6. Server logs show unhandled exception:
```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1)
Uncaught server error: java.lang.UnsupportedOperationException: Not supported in V2
    at org.keycloak.services.resources.admin.fgap.ClientPermissionsV2.canExchangeTo(ClientPermissionsV2.java:143)
    at org.keycloak.protocol.oidc.tokenexchange.V1TokenExchangeProvider.validateAudience(V1TokenExchangeProvider.java:254)
    at org.keycloak.protocol.oidc.tokenexchange.AbstractTokenExchangeProvider.exchangeClientToClient(AbstractTokenExchangeProvider.java:227)
```

## Detailed Description

Three classes interact to cause the crash:

1. **`AdminPermissions.management()`** (line 57-62): When `ADMIN_FINE_GRAINED_AUTHZ_V2` is enabled (which is `Type.DEFAULT` in 26.5.3), returns `MgmtPermissionsV2`.

2. **`MgmtPermissionsV2.clients()`** (line 87-91): Returns `ClientPermissionsV2`.

3. **`ClientPermissionsV2.canExchangeTo()`** (line 142-143): Throws `UnsupportedOperationException("Not supported in V2")` — the V2 implementation was never completed for this method.

The V1 token exchange code at `V1TokenExchangeProvider.validateAudience()` line 254 calls:
```java
AdminPermissions.management(session, realm).clients().canExchangeTo(client, targetClient, token)
```

This chain resolves to `ClientPermissionsV2.canExchangeTo()` which unconditionally throws.

Note: Self-exchange (audience = same client) works because the code short-circuits before reaching `canExchangeTo()`. Only cross-client audience exchange triggers the crash.

Also affects `exchangeToPermission()` and `mapRolesPermission()` in the same class — same `throw new UnsupportedOperationException("Not supported in V2")` in three methods (lines 142-148, 152-153).

## Impact

1. **Broken OAuth feature**: V1 token exchange with `audience` parameter is completely non-functional on any default Keycloak 26.5.3 installation with token exchange enabled. This is a documented OAuth feature (RFC 8693) that applications may depend on for service-to-service token delegation.

2. **Authorization check bypassed by crash**: The `canExchangeTo()` method is supposed to perform an authorization check (allow/deny). Instead of returning true/false, it crashes. The permission system fails before making any decision.

3. **Server-side log pollution**: Each request generates a full Java stack trace, which can be used for log flooding.

### PR DESCRIPTION
**Pull request by Oluwatobi-Mustapha**
Fixes #46718

`ClientPermissionsV2.canExchangeTo()` currently throws `UnsupportedOperationException`, which causes `V1TokenExchangeProvider.validateAudience()` to fail with HTTP 500 when FGAPv2 is enabled and a cross-client `audience` is requested.

This change makes `canExchangeTo()` deny gracefully by returning `false`, so unsupported checks produce an authorization denial instead of an uncaught server error.

A focused unit test (`ClientPermissionsV2Test`) was added to verify the method returns `false` and no longer throws.

### CODE REVIEW

**Comment by ahus1** [comment]
Please avoid merging the main branch into the PR or rebasing the PR unless there are merge conflicts reported by GitHub or a reviewer asks you for a rebase. This prevents spamming reviewers with notifications and saves minutes on the GitHub actions CI. Thanks!

**Comment by ahus1** [comment]
@rmartinc - can you please have a look if this is sane and safe to do? Thanks!

File: services/src/main/java/org/keycloak/services/resources/admin/fgap/ClientPermissionsV2.java [hunk 1]
```diff
@@ -140,7 +140,9 @@ public Set<String> getClientIdsByScope(String scope) {
 
     @Override
     public boolean canExchangeTo(ClientModel authorizedClient, ClientModel to, AccessToken token) {
-        throw new UnsupportedOperationException("Not supported in V2");
+        // V2 does not support configuring token-exchange permissions yet.
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/services/resources/admin/fgap/ClientPermissionsV2.java]: Better remove this line, I don't think that TE V2 will ever use fgap. So probably this methods are not needed anymore when TE V1 is gone.

**Review by rmartinc — COMMENTED** [review]
IMHO this makes sense but better if @vramik also take a look to this one.

File: services/src/main/java/org/keycloak/services/resources/admin/fgap/ClientPermissionsV2.java (hunk 1 above)
Comment (vramik) [reply services/src/main/java/org/keycloak/services/resources/admin/fgap/ClientPermissionsV2.java]: +1, I'd just remove the word `yet` from that sentence. 

Also another thing to consider would be, whether or not we want to log anything in case this method is called.

**Review by vramik — COMMENTED** [review]
LGTM, please consider updating the java comment, FGAP V2 won't support token exchange.

**Review by ahus1 — APPROVED** [review]
Thank you for reviews!
