### PR TITLE
fix: corrects the db property handling and null mapped values

### LINKED ISSUE #25010: Bug: KC_DB_USERNAME environment variable is causing a crash in latest version
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

When I build the following Dockerfile

```
FROM quay.io/keycloak/keycloak:latest

ENV KEYCLOAK_ADMIN=admin
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://localhost:5432/
ENV KC_DB_USERNAME=postgres

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

And run it with the following command

`docker run -p 8080:8080 --network="host" -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_DB_PASSWORD=password my-image`

I get a crash.

```
2023-11-24 14:11:36,335 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation

2023-11-24 14:11:36,582 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@6af9fcb2

2023-11-24 14:11:36,582 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@6af9fcb2

ERROR: Failed to run 'build' command.
ERROR: Cannot invoke "io.smallrye.config.ConfigValue.withConfigSourceName(String)" because the return value of "org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.transformValue(String, java.util.Optional, io.smallrye.config.ConfigSourceInterceptorContext)" is null
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

I used this Dockerfile throughout version 22 without issue, and when I specify 22.0 as the version, it works as expected.

When I comment out the KC_DB_USERNAME, I get an expected crash about user authentication failing for Postgres. If I add the variable in my run command instead of the Dockerfile, the same crash happens. Therefore I believe it's KC_DB_USERNAME causing the issue.

I checked the migration guide and release notes for 23 and could not find anything referring to why KC_DB_USERNAME is failing now, which is why I'm reporting this as a bug. The closest I found was the "[kc.sh and shell metacharacters](https://www.keycloak.org/docs/latest/upgrading/index.html#migration-changes)" changes, but I believe that does not affect this environment variable.

### Version

23

### Expected behavior

The Dockerfile should successfully build and run.

### Actual behavior

The Docker image crashes when ran.

### How to Reproduce?

Use the following Dockerfile and connect it using your Postgres database

```
FROM quay.io/keycloak/keycloak:latest

ENV KEYCLOAK_ADMIN=admin
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://localhost:5432/
ENV KC_DB_USERNAME=postgres

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

`docker build -t your-image .`

`docker run -p 8080:8080 --network="host" -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_DB_PASSWORD=your-password keycloak`

Of course change `--network="host"` and `localhost` in the `KC_DB_URL` string depending on your platform. [https://docs.docker.com/desktop/networking/#use-cases-and-workarounds-for-all-platforms](https://docs.docker.com/desktop/networking/#use-cases-and-workarounds-for-all-platforms)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
The issue seems to be triggered by having the db username match one of the database kinds - that will cause the mapper to return null, and we'll get the NPE in the calling logic.  The two changes here are to prevent the npe, and the other is to remove the  logic checking for a db kind from the username and password mappers.

@vmuzikar this will need to be backported as well

cc @pedroigor 

closes #25010

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java [hunk 1]
```diff
@@ -137,15 +137,15 @@ private static Optional<String> resolveUsername(Optional<String> value, ConfigSo
             return of("sa");
         }
 
-        return Database.getDatabaseKind(value.get()).isEmpty() ? value : null;
```
Comment (vmuzikar) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java:140]: I wonder what was the original intention for returning `null` if a username or password matches a DB kind. @pedroigor?

**Review by vmuzikar — COMMENTED** [review]
LGTM, thanks @shawkins

**Review by vmuzikar — DISMISSED** [review]

**Comment by mabartos** [comment]
Config test failed: https://github.com/keycloak/keycloak/actions/runs/7019688279/job/19098429038?pr=25088

jfyi; The Operator jobs will fail until the issue with UBI9 repositories is solved.

**Comment by shawkins** [comment]
> Config test failed: https://github.com/keycloak/keycloak/actions/runs/7019688279/job/19098429038?pr=25088

That should explain the original intent - at times the username property is computed from the parent value, in which case the mapping to the database kind does not make sense.  There are too many ways for properties to be calculated...  I'll refine things to account for this.

**Comment by shawkins** [comment]
@mabartos @pedroigor @vmuzikar As far as I can tell it's not necessary to have the username and password properties as mapped from db - their mappers will use the context to lookup that value.  So the additional change here is to remove the from("db") for each of them.

A concern would be that this same ambiguity affects some of the other mapping logic.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java (hunk 1 above)
Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java:140]: It should be an empty optional. The reason why it should not resolve the username is because some databases might not have a default value for this option.

**Review by pedroigor — APPROVED** [review]

**Review by mabartos — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]
LGTM, I don't think we ever had default username/password based on DB vendor (if that was the intention here). At least I was not able to make it working with 22. So should be safe to remove.
