### PR TITLE
22352 kerberos fallback

### LINKED ISSUE #9422: Support kerberos realm filter on LDAP provider
TL;DR: Support a configuration on LDAP provider which would specify which Kerberos realm(s) are handled by given LDAP provider.

_Original description follows_

### [KEYCLOAK-7009](https://issues.redhat.com/browse/KEYCLOAK-7009)
```
Keycloak supported multiple kerberos realms with [KEYCLOAK-3842](https://issues.redhat.com/browse/KEYCLOAK-3842), but it does not work with the following situations.
```

### Closing reason
```
Closing as duplicate of [KEYCLOAK-6225](https://issues.redhat.com/browse/KEYCLOAK-6225) . Although the "Steps to reproduce" are really nice and will help when we start work on [KEYCLOAK-6225](https://issues.redhat.com/browse/KEYCLOAK-6225) (which is not clear when it will be).
```

### [KEYCLOAK-6225](https://issues.redhat.com/browse/KEYCLOAK-6225)
```
In a scenario where multiple User Storage providers are configured, and you have 2 LDAP providers configured against Kerberos realm (assuming both use same keytab file). Keycloak ideally should look up after the user being authenticated in each one (following priority order) until find it.

For example, in a scenario where we have two providers: LDAP A and LDAP B, if the user couldn't be found in the first one, Keycloak would look up in LDAP B.

Today, if the user couldn't be found in the first one, the authentication flow stops and return an authentication error to the client.
```

### Closing reason
```
Issue is being closed as out of date due to lack of work on this issue.
```

I made a PR a while ago after asking on the mailing list, I can update it if you want.

### Version

15.1.1

### Expected behavior

User should be logged in on the correct ldap

Improvement plan:
-----------------

I think Keycloak should search the ldap which is extracted from the user principal.\
(I think active directory has a lot of configuration such as global catalog, so the inprovement plan should be discussed much here.)

### Actual behavior

(1)\
I found user002 and user003 can not do the desktop single sign on.\
Keycloak judges error when "Kerberos authenticatin is succeded" and "Keycloak cannot find the user information from the ldap provider".

server.log

2018-03-16 17:39:47,233 WARN  [org.keycloak.storage.ldap.LDAPStorageProvider] (default task-13) Kerberos/SPNEGO authentication succeeded with username [user002], but couldn't find or create user with federation provider [aaa.com]

(2)\
When the ccc.com\user001 logged in to the windows domain, desktop sso succeed but the Keycloak get the wrong user information ( aaa.com\user001 ).\
Keycloak got the user principal ( user001@ccc.com ) but Keycloak extract just "user001" and search the user information without using "ccc.com".

### How to Reproduce?

Situation:
----------

-   I have the multiple kerberos realms active directory environment attached.
-   I want to implemet a desktop single sign on using "ldap provider".

Active Directory setting:
-------------------------

-   Domain Controller : AAA.COM

    ktpass -out keycloak.HTTP.keytab.aaa -princ HTTP/keycloak.example.com@AAA.COM -ptype KRB5_NT_PRINCIPAL -mapuser keycloak -pass P@ssw0rd

-   Domain Controller : CCC.COM

    ktpass -out keycloak.HTTP.keytab.ccc -princ HTTP/keycloak.example.com@CCC.COM -ptype KRB5_NT_PRINCIPAL -mapuser keycloak -pass P@ssw0rd

Keycloak setting:
-----------------

#### 1\. aaa.com (priority:0)

| key | value |
|---|---|
| Username LDAP attribute | sAMAccountName |
| Connection URL | ldap://aaa.com |
| Allow Kerberos authentication | ON |
| Kerberos Realm | AAA.COM |
| Server Principal | HTTP/keycloak.example.com@AAA.COM |
| KeyTab | /opt/keytab/keycloak.HTTP.keytab.aaa |

#### 2\. bbb.com (priority:10)

| key | value |
|---|---|
| Username LDAP attribute | sAMAccountName |
| Connection URL | ldap://bbb.com |
| Allow Kerberos authentication | ON |
| Kerberos Realm | BBB.COM |
| Server Principal | HTTP/keycloak.example.com@AAA.COM |
| KeyTab | /opt/keytab/keycloak.HTTP.keytab.aaa |

#### 3\. ccc.com (priority:20)

| key | value |
|---|---|
| Username LDAP attribute | sAMAccountName |
| Connection URL | ldap://ccc.com |
| Allow Kerberos authentication | ON |
| Kerberos Realm | CCC.COM |
| Server Principal | HTTP/keycloak.example.com@CCC.COM |
| KeyTab | /opt/keytab/keycloak.HTTP.keytab.ccc |

_thumb_12433272

### Anything else?

_No response_

### LINKED ISSUE #14665: map a kerberos provider to one or more ldap provider stores
### Description

Scenario One:
- single keycloak realm
- two ldap providers configured each of a different OU containing user accounts in the same Active Directory Domani/KDC realm:
        - provider L1 has userA,  priority=10  - OU=finance
        -provider L2 has userB, priority=20  - OU=technology
- both ldap providers configured for Keberos SSO - this tested independently and working
- userA connects to a resource - OIDC flows and SSO occurs in the authentication. All good
- userB connects to same resource - OIDC flow begins, SSO doesn't happen and form-based login form presented.  Error:   "User with username userB already exists, but is not linked to provider [L1]"

So it appears that only one provider store is checked - the one with the highest priority that has also successfully decrypted the SPNEGO ticket.

If the ldap providers  are both set to the same priority, the SSO working becomes random.

N.B. Also tried to create a kerberos provider (K1) and disablde the kerberos on both ldap providers.  However SSO fails for all users:  "User with username userA already exists, but is not linked to provider [K1]" and there appears no mechanism to tell it to use one or more ldap provider stores.

Ran out of configuration options to try after this.

Solution proposal:
I think it would work best if a single kerberos provider configuration can be explicitly mapped to multiple ldap provider stores for our scenario so that each can be tried in succession in order of priority to find a match for the kerberos user principal found in the SPNEGO ticket after decrypting/verifying with the keytab file.

### Discussion

I have seen a similar discussion (but different) where each ldap provider is a separate KDC realm. Again apparently it tries the highest priority provider and then gives up rather than trying the next. I would also like this addressed at the same time.

### Motivation

You generally have no control over how a legacy AD domain has been managed/mismanaged.  In our case they kept dead accounts in multiple subtrees under "Managed Users" along with multiple live account subtrees (for multiple organisations).   So we had a poor choice of syncing all user accounts at the "Managed Users" level and subtrees with a single ldap provider but putting up with all the dead accounts being synced (which caused some email conflict sync errors)  or create multiple ldap providers to target the Live account subtree under each organisation OU.  
You might suggest that we could use the ldap filter to filter out the subtree OUs that we don't want - but AD ldap doesn't support the extension that is needed to achieve that - (distinguishedName=\*Dead\*)

### Details

Add a mapping capability to map a kerberos provider to one or more ldap provider stores so that it searches for the kerberos user principal in each of the mapped ldap provider stores until it finds it.

btw, the testing was done on v18 and v19

### LINKED ISSUE #22352: Only first kerberos provider is checked
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

When two or more Kerberos providers are added to the same realm the client provided token is only validated towards the first kerberos provider.. If the client provides a token issued by the second Kerberos provider they are not able to login.

The problem seems to be in `org.keycloak.storage.UserStorageManager#getUserByCredential` that fails completely on the first failure. It should instead continue to authenticate towards the next storage provider, if there are any.

### Version

22.0.1

### Expected behavior

Each Kerberos storage provider should be checked in the order specified by priority until one is successful or there are no more providers are available.

### Actual behavior

Only the first Kerberos provider is actually checked.

### How to Reproduce?

Setup a keycloak realm with two kerberos providers, test to login to the "Account Manager" with a token issued by the kerberos kdc defined in the provider with the least priority.

A demo using "docker compose" to setup a test environment together with a detailed guide on how to  reproduce this bug can be found here https://github.com/ullgren/keycloak-with-two-kdc

### Anything else?

Proposed patch will be submitted as a PR shortly.

### PR DESCRIPTION
**Pull request by mposolda**
Closes #22352 #9422 #14665 .

Summary of changes:
- It adds new state `FALLBACK` to `CredentialValidationOutput.Status`. This means that federation provider was not able to finish authentication, and wants to fallback to other providers.
The status `FAILED` means that user storage provider wants to finish authentication with failure without fallback to other providers (current behaviour from Keycloak main). Status `CONTINUE` means that federation provider does not want to finish, but doesn't want fallback as another challenge response might need to be sent to the user (current behaviour from Keycloak main). Added also javadoc to what those status should mean.
@ahus1 This should raise your concern from the https://github.com/keycloak/keycloak/pull/22353#issuecomment-1674989476 as it should be possible to acknowledge fallback as well as fail authentication right away.

- There are 2 scenarios when there are multiple LDAP providers and fallback to next federation provider might be needed. Added automated tests to both of them in this PR:

1) Scenario when `ldap-provider-1` (which is 1st in the chain) is not able to do SPNEGO authentication at all. For instance because token contains completely different kerberos realm. In this case SPNEGO authentication did not success, so fallback to another provider might be needed

2) Scenario when `ldap-provider-1` (which is 1st in the chain) is able to do SPNEGO authentication, but that provider is not able to lookup the user. This is common scenario with various "forest trust" scenarios. For this case, I've introduced note `KerberosConstants.AUTHENTICATED_SPNEGO_CONTEXT` when the authenticated Spnego from 1st provider can be saved and then next provider in the chain (like `ldap-provider-2`) can lookup user.

It can be better if same provider always does both SPNEGO authentication and lookup the user, but repeating SPNEGO authentication with same token is not possible as this would replay error (Something like `Caused by: KrbException: Request is a replay (34)`) and authentication would not be possible to happen.

At the same time, I don't see much issues with provider1 doing SPNEGO authentication and provider2 doing eventual lookup the user. Assumption is that administrator has control over the user-storage providers configured in the realm and hence automatically doing fallback does not seem to me as an issue. We can eventually add an option to LDAP/Kerberos providers like `Supports fallback for Kerberos authentication`, which will allow both save spnego context for next providers as well as consume spnego context from previous providers. But so far, I did not messed with another option due I don't see issues with doing fallback automatically and the amount of options on LDAP-provider is already quite big.

I've updated only `UserStorageManager` in this PR, but did not updated `MapUserProvider`. I am not sure if it is needed to deal with the map storage and also wanted to first ask for the feedback in this PR. I can possibly update `MapUserProvider` as well if you think it is necessary and we're ok with those changes.

@ahus1 To your question from  about detecting realm from spnego token - This is not easily possible. Spnego token is Base64 encoded token in ASN1 format with complicated structure. It might be possible to parse it with some 3rd party library or with BouncyCastle. Some hints are here https://stackoverflow.com/questions/4508555/decrypt-kerberos-ticket-using-spnego . I've tried to parse it with BouncyCastle (just for fun) in this branch https://github.com/mposolda/keycloak/blob/22352-spnego-parsing/crypto/default/src/test/java/org/keycloak/crypto/def/test/SPNEGOParseExample.java, but figured it is not trivial... At the same time, even if we figure parsing, announce which kerberos realms the LDAP provider supports won't be very useful as it is possible that realm `MYREALM.ORG` is supported by 2 LDAP providers `ldap-provider-1` and `ldap-provider-2` and hence fallback might be still needed as user authenticated by `ldap-provider-1` might be available in the LDAP subtree of `ldap-provider-2`. Also requirement to announce realms might not be very useful in the scenarios with MSAD forest trust with many realms when realms are added to the forest ad-hoc and hence the change in the configuration of LDAP providers would be needed always when adding new realm. However it can help with the scenario 1 I've described above as the provider1 would not try to authenticate SPNEGO token, which is clearly for different realm.

### CODE REVIEW

**Comment by ullgren** [comment]
@mposolda Thanks so much for looking in to this. Initial tests using our reproducer show that this PR does solve our issue, as reported in #22352

**Review by ahus1 — COMMENTED** [review]
@mposolda - thank you for the changes, they look good to me. 

It might be worth adding this to the release notes, I assume some people have been waiting for this quite some time, and they'll be happy to find it there.

For the map storage, feel free to update the `MapUserProvider` or open a new ticket to add that support. It might be difficult (impossible) to write a test for the `MapUserProvider` yet, as the PR to add LDAP/Kerberos support for the map storage is still pending, see #10700.

Let me know how you decide, and then re-request a review and I'll approve it.

**Comment by ullgren** [comment]
@mposolda Done some more testing with our test environment and it confirmed that this PR solves our problem. Again thanks so much for the work.

File: server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java [hunk 1]
```diff
@@ -63,6 +67,26 @@ public CredentialValidationOutput merge(CredentialValidationOutput that) {
     }
 
     public enum Status {
-        AUTHENTICATED, FAILED, CONTINUE
```
Comment (pedroigor) [inline server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java:66]: Not a blocker as it is related to naming. I think we can make the statues a bit more clear if:

* `VALID` (AUTHENTICATED)
* `INVALID` (FAILED)
* `VALID_USER` (FALLBACK)
* `CHALLENGE`

My point is:

*  `AUTHENTICATED`: Credentials are validated and authentication happens on the upper layer where the authentication logic is in
* `FAILED`, the validator is actually returning that the credential is invalid
* `VALID_USER`, the validator is actually returning if the user is valid but not the credential. The decision to try other providers to authenticate the user depends on the upper layer.
* `CONTINUE`, this name indicates for me that validation should continue and not necessarily the authentication (somewhat related to the `FALLBACK` which indicates moving forward with the provider chain.

Comment (mposolda) [reply server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java:66]: Thanks Pedro for the suggestions. Your naming is probably better, but there is also concern with backwards compatibility as `CredentialValidationOutput` class is part of the `server-spi` module, which is part of user-storage SPI and hence backwards compatibility might be a concern...

@ahus1 What do you think? Can we rename things or is it better to keep as it is?

I see options like:
1) Rename as @pedroigor  suggested
2) Rename only `FALLBACK` to `VALID_USER` . This is fine for backwards compatibility though as `FALLBACK` is new thing added in this PR
3) Keep as it is

I vote for 2. I can do 1 if @ahus1 agrees that backwards compatibility is not an issue.

**Comment by mposolda** [comment]
> @mposolda Done some more testing with our test environment and it confirmed that this PR solves our problem. Again thanks so much for the work.

@ullgren Thanks for testing and confirming this!

**Comment by mposolda** [comment]
@ahus1 @pedroigor I've added another commit with the release notes and with some small clarification in the javadoc of `CredentialValidationOutput` class. In the end, I did not updated any names on `CredentialValidationOutput.Status` enum. Can you please check it?

I've created https://github.com/keycloak/keycloak/issues/22780 as a follow-up task for the new store.

I've used separate commit, so you can review the changes, but I plan to squash it before merge.

File: server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java (hunk 1 above)
Comment (mposolda) [reply server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java:66]: Update: In the end I've kept `FALLBACK` instead of `VALID_USER`. The `VALID_USER` is not accurate as it is used even for the cases when the user-storage provider is not able to recognize the credential nor the user and hence it just needs to fallback to next provider.

I see options like:
1) Rename statuses to `VALID`, `INVALID`, `FALLBACK`, `CHALLENGE`
2) Keep statuses as is in this PR 

My vote is 2 just due the backwards compatibility. If we can break backwards compatibility, I am fine with (1).

@pedroigor @ahus1 What do you think?

File: docs/documentation/release_notes/topics/22_0_2.adoc [hunk 2]
```diff
@@ -0,0 +1,4 @@
+= Improvements in LDAP and Kerberos integration
+
+It is possible to have multiple LDAP providers in the realm, which support Kerberos integration with same Kerberos realm. When LDAP provider is not able to find user, which was authenticated through
+Kerberos/SPNEGO, there will be attempt to fallback to next LDAP provider.
```
Comment (ahus1) [inline docs/documentation/release_notes/topics/22_0_2.adoc:4]: I added some articles, and avoided the passive: 

```suggestion
Keycloak now supports multiple LDAP providers in a realm, which support Kerberos integration with the same Kerberos realm. When an LDAP provider is not able to find the user which was authenticated through
Kerberos/SPNEGO, Keycloak ties to fallback to the next LDAP provider.
```

Looking at the added tests, I wonder if we now support even more than is described here, like multiple Kerberos providers, but I'm not so much into this.  

I'm about to approve it anyway, and the docs could be further improved in a separate PR, as KC 22.0.2 might be just around the corner.

File: server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java (hunk 1 above)
Comment (ahus1) [reply server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java:66]: Looking at the docs, I see that this change is targeted for KC22, so it should be backward compatible. Therefore I vote to not rename the options.

**Review by ahus1 — DISMISSED** [review]
LGTM - one small nit-pick around the docs.

**Comment by mposolda** [comment]
@ahus1 Thanks for another review! I've applied your comments regarding docs. Also Thanks for the clarification for backwards compatibility.

**Review by ahus1 — APPROVED** [review]

File: server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java (hunk 1 above)
Comment (pedroigor) [reply server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java:66]: Not a blocker for me.

**Review by pedroigor — APPROVED** [review]

**Comment by mposolda** [comment]
@ahus1 @pedroigor Thanks for the review!
