### PR TITLE
fix: use distance measure for unknown options

### LINKED ISSUE #48115: Refine KcUnmatchedArgumentException option filtering
### Description

The filtering for disabled options can be removed as these completions are coming from picocli and the options have been constructed with only enabled options.

We can also see about doing a better job of limiting the completions shown as suggested here https://github.com/keycloak/keycloak/pull/48055#discussion_r3084102696 - that may be difficult in general unless we apply a simple heuristic. For example if the unknown option has two parts (db-paswd), then show only completions with two parts?

cc @mabartos

### PR DESCRIPTION
**Pull request by shawkins**
After thinking more about the part matching it seems better to use a general notion of similarity. While it doesn't completely understand the wildcard convention it seems to be close enough based upon the prefix.

The change here will return the closest 7 options, rather than all options that start with same prefix.

This reuses the picocli cosine distance as I don't see another text distance utility in our code base.

However this is via reflection. The next best options would be to copy that or some code that implements levenshtein - rather than introducing a dependency on commons text.

closes: #48115

### CODE REVIEW

**Comment by shawkins** [comment]
Another option is to always perform the sorting.

**Comment by Pepo48** [comment]
> However this is via reflection. The next best options would be to copy that or some code that implements levenshtein - rather than introducing a dependency on commons text.

+1 for using our own method. I think relying on a private inner method obtained via reflection is a ticking bomb.

I looked at their [code](https://github.com/remkop/picocli/blob/121646e408bfee65f70875a6ddb94e16e83d958c/src/main/java/picocli/CommandLine.java#L18540-L18572) just out of curiosity (I happened to play with Levenshtein in the past, when I needed to parse out a specific sport event from a huge IPTV list 😄 - many team name variants) - they seem to use Bigram cosine similarity, which behaves differently as I searched and read through materials.

I did some primitive testing with KC options and I think we can stick with Bigram cosine similarity. I tried 8 scenarios - BCS won in 5, for the rest it was a tie. Levenshtein favours short strings, it ranked `--db-url` above `--db-tls-trust-store-password` even when I provided `--db-pasword` (with one s) as the input.

On top of that, our own impl can give us some advantage - more modern syntax (Picocli uses Java 5 style still) and more importantly better results. Picocli's `CosineSimilarity.mostSimilar()` uses `TreeMap<Double, String>`- when two options score identically, one is silently dropped. This turned out to be a real issue as I was losing completely relevant suggestions.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcUnmatchedArgumentException.java [hunk 1]
```diff
@@ -36,6 +38,20 @@ public KcUnmatchedArgumentException(CommandLine.UnmatchedArgumentException ex) {
...
+        if (result.size() > 7) {
+            try {
+                Class<?> clazz = Class.forName(CommandLine.class.getName() + "$CosineSimilarity");
+                Method m = clazz.getDeclaredMethod("mostSimilar", String.class, Iterable.class);
+                m.setAccessible(true);
+                result = (List<String>) m.invoke(null, this.getUnmatched().get(0), result);
+                result = result.subList(0, Math.min(7, result.size()));
+            } catch (ClassNotFoundException | NoSuchMethodException | SecurityException | IllegalAccessException
+                    | InvocationTargetException e) {
+                // do nothing
```
Comment (Pepo48) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcUnmatchedArgumentException.java]:
```suggestion
        List<String> suggestions = super.getSuggestions();
        if (suggestions.size() <= MAX_SUGGESTIONS) {
            return suggestions;
        }
        String unmatched = this.getUnmatched().get(0).toLowerCase();
        List<String> sorted = new ArrayList<>(suggestions);
        sorted.sort(Comparator.comparingDouble(s -> -cosineSimilarity(unmatched, s.toLowerCase())));
        return sorted.subList(0, Math.min(MAX_SUGGESTIONS, sorted.size()));
    }

    static double cosineSimilarity(String a, String b) {
        Map<String, Integer> aFreq = bigramFrequency(a);
        Map<String, Integer> bFreq = bigramFrequency(b);
        double dot = dotProduct(aFreq, bFreq);
        double normA = dotProduct(aFreq, aFreq);
        double normB = dotProduct(bFreq, bFreq);
        double denominator = Math.sqrt(normA * normB);
        return denominator == 0 ? 0 : dot / denominator;
    }

    private static Map<String, Integer> bigramFrequency(String s) {
        Map<String, Integer> freq = new HashMap<>();
        for (int i = 0; i < s.length() - 1; i++) {
            freq.merge(s.substring(i, i + 2), 1, Integer::sum);
        }
        return freq;
    }

    private static double dotProduct(Map<String, Integer> a, Map<String, Integer> b) {
        double result = 0;
        for (Map.Entry<String, Integer> entry : a.entrySet()) {
            Integer bVal = b.get(entry.getKey());
            if (bVal != null) {
                result += entry.getValue() * bVal;
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcUnmatchedArgumentException.java [hunk 2]
```diff
@@ -17,6 +17,8 @@
 
 package org.keycloak.quarkus.runtime.configuration;
 
+import java.lang.reflect.InvocationTargetException;
+import java.lang.reflect.Method;
 import java.util.List;
```
Comment (Pepo48) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcUnmatchedArgumentException.java]:
```suggestion
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
```

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcUnmatchedArgumentException.java
Comment (Pepo48) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcUnmatchedArgumentException.java:34]:
```suggestion

    private static final int MAX_SUGGESTIONS = 7;

```

**Review by Pepo48 — COMMENTED** [review]
Just for the reference what I was playing with - hugely inspired by Picocli, the math is identical:

**Comment by shawkins** [comment]
> +1 for using our own method. I think relying on a private inner method obtained via reflection is a ticking bomb.

I wouldn't necessarily say bomb :) - if there were a problem, then we'd just return the full list as we do currently. We'd also catch this in testing. However it could slow down an upgrade eventually.

> On top of that, our own impl can give us some advantage - more modern syntax (Picocli uses Java 5 style still) and more importantly better results. Picocli's CosineSimilarity.mostSimilar() uses TreeMap<Double, String>- when two options score identically, one is silently dropped. This turned out to be a real issue as I was losing completely relevant suggestions.

Thank you for looking at their code (which is currently used for command suggestions). That sounds like multiple upstream issues are needed then - one for using similarity on options, and another on not dropping things with the same score.

**Comment by shawkins** [comment]
@Pepo48 I adapted your proposal to include our own cosine similarity to be more general - mostly replacing any usage of PicoCli's function. I'll still create upstream issues as well.

File: quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java [hunk 3]
```diff
@@ -297,7 +297,7 @@ private void assertUnknownOption(NonRunningPicocli nonRunningPicocli) {
...
+                "--db-password, --db-password-<datasource>, --db-mtls-key-store-password, --db-tls-trust-store-password, --db-mtls-key-store-password-<datasource>, --db-tls-trust-store-password-<datasource>, --db"));
```
Comment (mabartos) [inline quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java:300]: Yes! 🚀

**Comment by shawkins** [comment]
Upstream issue: https://github.com/remkop/picocli/issues/2510

**Comment by shawkins** [comment]
Updated based upon the reviews.

**Review by Pepo48 — DISMISSED** [review]
I tested it once again with my initial test:
```
Input: --db-usr
Candidates: 24

Top 7:
  1. --db-url
  2. --db-username
  3. --db
  4. --db-url-port
  5. --db-url-host
  6. --db-driver
  7. --db-url-database
```
 (`--db,` `--db-url-host`, `--db-driver` were previously dropped)

Thus, LGTM now. Thank you very much, Steve!

**Comment by shawkins** [comment]
One more refinement - since the command suggestions are prefixed, they should retain the default limit of 3.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.
