### PR TITLE
Fix remaining failing tests with BCFIPS approved mode

### LINKED ISSUE #16698: Fix remaining failing tests with BCFIPS approved mode
There are still few failing tests with BCFIPS approved mode. Those are:
- Few tests failing because of using 1024 long RSA key (not allowed in BCFIPS approved mode)
- Few tests dependent on Kerberos/SPNEGO available (ResetPasswordTest, JsonFileImport198MigrationTest), which is not true with FIPS where Kerberos feature is disabled by default
- Few tests failing because of `keystore.type.compat` security feature was explicitly set to `false`, which makes it impossible to read default java truststore from cacerts file

### PR DESCRIPTION
**Pull request by mposolda**
Closes #16698

### CODE REVIEW

File: common/src/main/java/org/keycloak/common/util/ObjectUtil.java [hunk 1]
```diff
@@ -76,4 +79,28 @@ public static boolean isBlank(final CharSequence cs) {
...
+    /**
+     * Calling:
+     * <pre>joinValuesWithLogicalCondition("or", Arrays.asList("foo", "bar", "baz", "caz" ))</pre>
+     * will return "foo, bar, baz or caz"
+     *
+     * @param conditionText condition
+     * @param values values to be joined with the condition at the end
+     * @return see above
+     */
+    public static String joinValuesWithLogicalCondition(String conditionText, Collection<String> values) {
```
Comment (pedroigor) [inline common/src/main/java/org/keycloak/common/util/ObjectUtil.java:92]: More like a string utility, no? See org.keycloak.utils.StringUtil. Perhaps we should move this class to core too.

**Review by pedroigor — DISMISSED** [review]

**Comment by pedroigor** [comment]
@mposolda Only a comment, feel free to ignore it.

File: common/src/main/java/org/keycloak/common/util/ObjectUtil.java (hunk 1 above)
Comment (mposolda) [reply common/src/main/java/org/keycloak/common/util/ObjectUtil.java]: @pedroigor Good point, I've moved from `ObjectUtil` to `StringUtil` . I've used separate commit, so you can re-review just this simple change.

**Review by pedroigor — APPROVED** [review]
