### PR TITLE
Can not set a jgroups stack other than the defaults from Infinispan

### LINKED ISSUE #10052: Can not set a jgroups stack other than the defaults from Infinispan
### Describe the bug

It is not possible to configure a custom JGroups stack to the cache container but use only those provided OOTB.

Because of that, it is not possible to configure a JGroups stack with additional protocols such as ASYM_ENCRYPT.

The issue does not happen in `16.1.1` but is in upstream/main. It is related to the ISPN upgrade from 13.0.0 to 13.0.5. 

### Version

17.0.0-SNAPSHOT

### Expected behavior

The server must allow user-defined jgroups stacks.

### Actual behavior

The `udp` stack is always set as the JGroups stack, ignoring any custom stack configured in the cache configuration file. The reason is that it is set as a default option value.

### How to Reproduce?

Create a custom JGroups stack by creating a `jgroups-asym-enc.xml` with the following content:

```
<config xmlns="urn:org:jgroups"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups-4.2.xsd">
   <!-- jgroups.udp.address is deprecated and will be removed, see ISPN-11867 -->
   <UDP bind_addr="${jgroups.bind.address,jgroups.udp.address:SITE_LOCAL}"
        bind_port="${jgroups.bind.port,jgroups.udp.port:0}"
        mcast_addr="${jgroups.mcast_addr:228.6.7.8}"
        mcast_port="${jgroups.mcast_port:46655}"
        tos="0"
        ucast_send_buf_size="1m"
        mcast_send_buf_size="1m"
        ucast_recv_buf_size="20m"
        mcast_recv_buf_size="25m"
        ip_ttl="${jgroups.ip_ttl:2}"
        thread_naming_pattern="pl"
        enable_diagnostics="false"
        bundler_type="transfer-queue"
        max_bundle_size="8500"

        thread_pool.min_threads="${jgroups.thread_pool.min_threads:0}"
        thread_pool.max_threads="${jgroups.thread_pool.max_threads:200}"
        thread_pool.keep_alive_time="60000"

        thread_dumps_threshold="${jgroups.thread_dumps_threshold:10000}"
   />
   <PING num_discovery_runs="3"/>
   <MERGE3 min_interval="10000"
           max_interval="30000"
   />
   <FD_SOCK/>
   <!-- Suspect node `timeout` to `timeout + timeout_check_interval` millis after the last heartbeat -->
   <FD_ALL timeout="10000"
           interval="2000"
           timeout_check_interval="1000"
   />
   <VERIFY_SUSPECT timeout="1000"/>
   <SSL_KEY_EXCHANGE keystore_name="server.jks"
                        keystore_password="password"/>
<ASYM_ENCRYPT asym_keylength="2048"
                    asym_algorithm="RSA"
                    change_key_on_coord_leave = "false"
                    change_key_on_leave = "false"
                    use_external_key_exchange = "true"
                    />

   <pbcast.NAKACK2 xmit_interval="100"
                   xmit_table_num_rows="50"
                   xmit_table_msgs_per_row="1024"
                   xmit_table_max_compaction_time="30000"
                   resend_last_seqno="true"
   />
   <UNICAST3 xmit_interval="100"
             xmit_table_num_rows="50"
             xmit_table_msgs_per_row="1024"
             xmit_table_max_compaction_time="30000"
   />
   <pbcast.STABLE desired_avg_gossip="5000"
                  max_bytes="1M"
   />
   <pbcast.GMS print_local_addr="false"
               join_timeout="${jgroups.join_timeout:2000}"
   />
   <UFC max_credits="4m"
        min_threshold="0.40"
   />
   <MFC max_credits="4m"
        min_threshold="0.40"
   />
   <FRAG3 frag_size="8000"/>
</config>
```

Create a cache configuration file `conf/cache-ispn-secure.xml`:

```
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

<jgroups>
    <stack name="encrypt-udp" extends="udp">
      <SSL_KEY_EXCHANGE keystore_name="server1.jks"
                        keystore_password="password"
                        stack.combine="INSERT_AFTER"
                        stack.position="VERIFY_SUSPECT"/>
      <ASYM_ENCRYPT asym_keylength="2048"
                    asym_algorithm="RSA"
                    change_key_on_coord_leave = "false"
                    change_key_on_leave = "false"
                    use_external_key_exchange = "true"
                    stack.combine="INSERT_BEFORE"
                    stack.position="pbcast.NAKACK2"/>
    </stack>
  </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="encrypt-udp"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>            
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>
```

Build the server as follows:

```
kc.sh build --cache-config-file cache-ispn-secure.xml
```

Then try to start two server instances where one of them does not have the proper key material to join the cluster.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Basically:

* Removing the default value for `cache-stack` so that we can decide whether we should solely rely on the config from a the configuration file. By default, ISPN is going to use UDP anyways, and removing the value keeps the same behavior.
* I would like to improve our configuration layer later so that we are able to distinguish whether it was provided or not. Right now we can not infer that easily. For instance, based on the config source name of a `ConfigValue`.

Closes #10052

### CODE REVIEW

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java [hunk 1]
```diff
@@ -17,19 +17,22 @@
...
 import org.keycloak.it.junit5.extension.CLIResult;
 import org.keycloak.it.junit5.extension.DistributionTest;
+import org.keycloak.it.junit5.extension.RawDistOnly;
+import org.keycloak.it.utils.KeycloakDistribution;
 
 import io.quarkus.test.junit.main.Launch;
 import io.quarkus.test.junit.main.LaunchResult;
 
 @DistributionTest
+@RawDistOnly(reason = "Not possible to mount files using docker.")
```
Comment (DGuhr) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java:35]: this would be possible in general with a few changes, btw, but don't know if it brings much benefit now to touch the dockerdist for that. :)

**Review by DGuhr — APPROVED** [review]
approved, with a minor suggestion that does not block the pr :)

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java [hunk 2]
```diff
@@ -66,11 +69,12 @@ void testExplicitCacheConfigFile(LaunchResult result) {
     }
 
     @Test
-    @Launch({ "start", "--http-enabled=true", "--hostname-strict false" })
+    @Launch({ "start", "--auto-build", "--http-enabled=true", "--hostname-strict false" })
```
[the remark this answers is not in the document]
Comment (pedroigor) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java:72]: Because we need to auto-build to fallback to the default cluster config. See the name of the method.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java (hunk 1 above)
Comment (pedroigor) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java:35]: Sure, you can mount files in docker. But not in our impl.

**Review by stianst — APPROVED** [review]

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java (hunk 1 above)
Comment (Mezzenine) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java:35]: Hi @pedroigor, @DGuhr 
did this comment mean it is impossible to mount ispn-config.xml on the docker run command?
