### PR TITLE
KEYCLOAK-17252 'Aggregate attribute values' mapper option is now applied to group hierarchy

### LINKED ISSUE #11255: 'Aggregate attribute values' mapper option not applied to group hierarchy
### Describe the bug

In a group hierarchy Multivalued attributes (with 'Aggregate attribute values' option set) are not properly aggregated into the Generated Access Token.

### Version

12.0.4

### Expected behavior

For a 'User Attribute' token claim that is Multivalued and has the 'Aggregate attribute values' option set, values found for a user's group should be combined with attribute values found for any ancestor of that group.

### Actual behavior

A parent group's attribute values are ignored instead of aggregated (even though inheritance works fine when the child group contains no values for the attribute).

### How to Reproduce?

1. Create a group, named A with attribute 'x' with value `A##1`
2. Create a group B, that is a child group of A, with attribute 'x' with value `B##2`
3. Create a user C that is a member of group B.
4. Make a User Attribute mapper for a User Attribute 'x' and Token Claim Name 'x' with the 'Multivalued' and 'Aggregate attribute values' options set.
5. Include the mapper in a Client Scope that is included to a client's "Assigned Default Client Scopes" and evaluate for user C.

The evaluation result ('Generated Access Token') includes claim 'x' with values ["B", "2"] (instead of the desired ["A", "1", "B", "2"]).

### Anything else?

This is [KEYCLOAK-17252](https://issues.redhat.com/browse/KEYCLOAK-17252) re-entered. 
It was closed as if outdated, but for us it still is and has always been a very relevant current issue (running with the provided PR in production).

The PR that fixes this issue: https://github.com/keycloak/keycloak/pull/7871
(after all this time only the added unit test causes a git conflict right now; we will address this).

### PR DESCRIPTION
**Pull request by jurjanpaul**
Hopefully https://issues.redhat.com/browse/KEYCLOAK-17252 (reentered as https://github.com/keycloak/keycloak/issues/11255) describes clearly enough the lacking attribute value aggregation in group hierarchies that this PR tackles.

To elaborate a bit on the functional context: for a number of separate projects (top-level groups) we manage users in different organizations (subgroups of these projects) in Keycloak. Group attributes at the 'project' level indicate which parts/configurations of an application users in these projects have access to (by means of the generated JWT). These attributes are multi-valued and aggregated. We want to take this a step further by providing specific organizations within projects with additional access grants (using the same attribute key(s), so as not to have to bother the application(s) with having to take into account at what 'level' the access was granted, in the same way it does not matter whether the attributes were set on a user, role or group). 

Without this PR the attribute values on the organization level would always take precedence over the attributes on the project level, even with 'Aggregate attribute values' turned on, unexpectedly taking away intended access from the users involved. 

We believe this PR fixes this inconsistent 'Aggregate attribute values' behavior for attributes in group hierarchies.

Apart from a new test that verifies the new behavior, some tests were added to verify that the existing 'inheritance' behavior for subgroups still works for attributes that are not multi-valued or not 'aggregated'.

### CODE REVIEW

**Comment by jurjanpaul** [comment]
Somehow the (unrelated?) HardcodedUserAttributeMapperTest failed with a Timeout. 

Locally I have not been able to reproduce this, as it consistently succeeds when run either separately or after OIDCProtocolMappersTest that this PR extends.

**Comment by lhanusov** [comment]
@jurjanpaul Hello Jurjan, first of all thank you for this PR and the issue #11255, I apologize that it has been such a long time without any response. I think the issue is very well described and covered. I will try few more things, and if there are fine, I will contact one of the maintainers and ask him to merge it.

Thank you,
Lukas

**Comment by lhanusov** [comment]
@jurjanpaul Please, can you rebase it to the latest main branch commit. Thank you

**Comment by jurjanpaul** [comment]
@lhanusov Thank you for your messages! Great to hear that this PR might be of interest after all. :-) 
I will need to find some time to swap this back in, rebase and resolve the merge conflict. I will let you know when that's done.

**Comment by lhanusov** [comment]
@mposolda Please, can you take a look on this PR? It looks good to me and it makes sense, because the current method doesn't evaluate the aggregate option for groups, in this case OIDC. I've triggered local tests against this class and it passes, I will wait for the rebase and gh actions quarkus tests.

**Comment by jurjanpaul** [comment]
Rebased (resolving minor conflicts); awaiting test results.

**Comment by jurjanpaul** [comment]
At least this looks quite good: https://github.com/jurjanpaul/keycloak/actions/runs/3010007623
(1 failing test that doesn't seem to have anything to do with this PR: `DefaultHostnameTest.fixedFrontendUrlOldAdminPage:120->assertOldAdminPageJsPathSetCorrectly:301`)

**Comment by jurjanpaul** [comment]
Locally I end up with:
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AccountRestServiceCorsTest.testErrorResponse:113->doXhr:164 Cors request failed: Browser doesn't support fetching logs
[ERROR]   AccountRestServiceCorsTest.testGetProfile:85->doXhr:164 Cors request failed: Browser doesn't support fetching logs
[ERROR]   AccountRestServiceCorsTest.testGetVersionedApi:129->doXhr:164 Cors request failed: Browser doesn't support fetching logs
[ERROR]   AccountRestServiceCorsTest.testUpdateProfile:99->doXhr:164 Cors request failed: Browser doesn't support fetching logs
[ERROR]   DefaultHostnameTest.fixedFrontendUrlOldAdminPage:120->assertOldAdminPageJsPathSetCorrectly:301
[ERROR] Errors: 
[ERROR]   LifespanAdapterTest.testPathConfigInvalidation » PageObjectInitialization Can not instantiate Page Object 
class org.keycloak.testsuite.adapter.page.PhotozClientAuthzTestApp
 declared in: 
org.keycloak.testsuite.adapter.example.authorization.LifespanAdapterTest

[ERROR]   KcOidcBrokerFrontendUrlTest.testLogInAsUserInIDP » Runtime java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: No address associated with hostname
[ERROR]   KcSamlBrokerFrontendUrlTest.testFrontendUrlInDestinationExpected » Runtime java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: No address associated with hostname
[ERROR]   KcSamlBrokerFrontendUrlTest.testKeycloakRejectsRealUrlWhenFrontendUrlConfigured » Runtime java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io
[ERROR]   KcSamlBrokerFrontendUrlTest.testLogInAsUserInIDP » Runtime java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io
[ERROR]   TokenEndpointCorsTest.accessTokenCorsRequest » Runtime java.net.UnknownHostException: localtest.me: No address associated with hostname
[ERROR]   ParTest.testParCorsRequestWithInvalidUrlShouldFail » Runtime java.net.UnknownHostException: localtest.me: No address associated with hostname
[ERROR]   ParTest.testParCorsRequestWithValidUrl » Runtime java.net.UnknownHostException: localtest.me
[ERROR]   SamlReverseProxyTest » Runtime java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: No address associated with hostname
[ERROR]   DefaultHostnameTest.fixedFrontendUrl:94->assertBackendForcedToFrontendWithMatchingHostname:263 » Runtime java.net.UnknownHostException: keycloak.127.0.0.1.nip.io: No address associated with hostname
[INFO] 
[ERROR] Tests run: 4509, Failures: 5, Errors: 10, Skipped: 189
```
None of these failures and errors seem related to this PR.

**Comment by jurjanpaul** [comment]
@lhanusov and @mposolda I hope this PR is now ready for your approval!
But please let me know if there is something I still need to do.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
 import org.junit.Test;
 import org.keycloak.admin.client.resource.ClientResource;
 import org.keycloak.admin.client.resource.ClientScopeResource;
+import org.keycloak.admin.client.resource.GroupResource;
```
Comment (lhanusov) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java:26]: @jurjanpaul please, can you remove this unused import, besides that tests are clearly described and pass without any issue.

Comment (jurjanpaul) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java]: @lhanusov Removed. Thanks for noticing!

**Review by lhanusov — APPROVED** [review]
LGTM

**Review by mposolda — APPROVED** [review]
@jurjanpaul Thanks for the PR! And Thanks @lhanusov for the additional review and testing.

I am approving as well. I can merge it once tests are OK.

**Comment by jurjanpaul** [comment]
@lhanusov @mposolda This is great! Thank you so much!
