### PR TITLE
Inconsistency in User enabled status in Rest query results.

### LINKED ISSUE #39549: Inconsistency in User enabled status in Rest query results.
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

With Brute Force Protection enabled and a temporarily locked out user the following calls will give different results for the "enabled" attribute. The first call modifies the enabled status with when the user is temporarily locked out. The second call does not modify the enabled status.

http://localhost:8080/admin/realms/<REALM>/users/<USERID>
http://localhost:8080/admin/realms/<REALM>/users?username=<USERNAME>

We should return the modified status from both endpoints.

### Version

26.2.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Both endpoints should return the same value for User.Enabled.

### Actual behavior

The first endpoints correctly returns false. The second endpoint incorrectly returns true.

### How to Reproduce?

Steps to Reproduce:
Create a realm
Create a client with Credential
Create a user for this realm
Configure in RealmSetting > Security Defenses > Brute Force Detection: use 'Enable' in (RHSSO) so that RHBK uses the "temporary lockout model".
As a model, use few lockout attempts, for example 3 attempts for this user.
Now, perform 3 attempts for this user and after blocking the user, execute
the shellToBlock.sh file with userCredentialsNOK.json to get the result.
Content file shellToBlock.sh :
~~~
#!/bin/sh
set -e
HOST=`cat $1 | jq -r .host`
REALM=`cat $1 | jq -r .realm`
USERNAME=`cat $1 | jq -r .username`
PASSWORD=`cat $1 | jq -r .password`
CLIENTID=`cat $1 | jq -r .clientid`
CLIENTSECRET=`cat $1 | jq -r .client_secret`
curl -X POST -k \
https://$host/realms/$REALM/protocol/openid-connect/token \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d username=$USERNAME \
-d password=$PASSWORD \
-d grant_type=password \
-d client_id=$CLIENTID \
-d client_secret=$CLIENTSECRET
~~~
Content file userCredentialsNOK.json:
~~~
{ "host": "keycloak_host", "realm": "testcase", "username": "test-user", "password": "passwordTestIncorrect", "clientid": "test-case", "client_secret": "8lQejN2BjnwYgKE4Cl74QaUf2lrxzd7A" }
~~~
 - Execute as watch:
~~~ 
$ ./shellToBlock.sh userCredentialsNOK.json
~~~
Now, to get details from result:
  - Create a file "getResultCallAB.sh" with API REST
  - Content file getResultCallAB.sh:
~~~
#!/bin/sh
set -e
AUTHENTICATION=`curl -k -s \
  -d "client_id=admin-cli" \
  -d "username=<user-admin>" \
  -d "password=<pwd-admin>" \
  -d "grant_type=password" \
  "http://<hostsso>:<port>/realms/master/protocol/openid-connect/token"`
ACCESS_TOKEN=`echo $AUTHENTICATION | jq -r .access_token`
CALL_A=`curl -k -s http://localhost:8080/admin/realms/<REALM>/users/<USERID> -H "Authorization: bearer $ACCESS_TOKEN"`
CALL_B=`curl -k -s http://localhost:8080/admin/realms/<REALM>/users?username=<USERNAME> -H "Authorization: bearer $ACCESS_TOKEN"`
echo $CALL_A | jq
echo $CALL_B | jq

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #39549

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java [hunk 1]
```diff
@@ -539,6 +547,26 @@ public void testEmail() throws Exception {
...
+        String urlA = suiteContext.getAuthServerInfo().getContextRoot().toString() + "/auth/admin/realms/test/users/" + userId;
+        SimpleHttp a = SimpleHttpDefault.doGet(urlA, httpClient).auth(getAdminToken());
+
+        String urlB = suiteContext.getAuthServerInfo().getContextRoot().toString() + "/auth/admin/realms/test/users?username=test-user@localhost";
+        SimpleHttp b = SimpleHttpDefault.doGet(urlB, httpClient).auth(getAdminToken());
+
+        UserRepresentation user = a.asJson(UserRepresentation.class);
+        assertFalse(user.isEnabled());
+        user = b.asJson(new TypeReference<List<UserRepresentation>>() {}).get(0);
+        assertFalse(user.isEnabled());
```
Comment (rmartinc) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java:568]: @douglaspalmer You don't need a `httpClient` here, you can use directly the `adminClient`:

```java
        assertFalse(testRealm().users().get(userId).toRepresentation().isEnabled());
        assertFalse(testRealm().users().search("test-user@localhost", true).get(0).isEnabled());
```

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @douglaspalmer! Just two little requests.

**Comment by mposolda** [comment]
@douglaspalmer LGTM. It will be good to document the change in the "Release notes" and "upgrading guide" .

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java [hunk 2]
```diff
@@ -539,6 +543,18 @@ public void testEmail() throws Exception {
...
+    @Test
+    public void testUserDisabledTemporaryLockout() throws Exception {
+        String userId = adminClient.realm("test").users().search("test-user@localhost", null, null, null, 0, 1).get(0).getId();
+
+        loginInvalidPassword();
+        loginInvalidPassword();
+        expectTemporarilyDisabled();
+
+        assertTrue(testRealm().users().get(userId).toRepresentation().isEnabled());
+        assertTrue(testRealm().users().search("test-user@localhost", true).get(0).isEnabled());
```
Comment (rmartinc) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java:556]: Maybe add the test for the other endpoint:

```java
assertEquals(true, testRealm().attackDetection().bruteForceUserStatus(userId).get("disabled"));
```

File: docs/documentation/release_notes/topics/26_3_0.adoc [hunk 3]
```diff
@@ -26,6 +26,10 @@ In this release, the Instagram Identity Broker is deprecated for removal and is
 If you are using this broker, it is recommended to use the Facebook Identity Broker instead. For more
 details, see link:{upgradingguide_link}[{upgradingguide_name}].
 
+= Inconsistent user endpoints harmonized
+
+In previous releases there was an inconsistency in the REST endpoint result of getting a user and searching for a user. When BruteForce is enabled and a user was temporarily locked out one endpoint would return enabled=false while the other would return enabled=true. If the user was updated and enabled was false due to temporary lockout then the user would be disabled permanently. Both endpoints now return enabled=true when a user is temporarily locked out. To check whether a user is temporarily locked out the BruteForeUserResource endpoint should be utilised.
```
Comment (rmartinc) [inline docs/documentation/release_notes/topics/26_3_0.adoc:31]: I would remove this and just set the comment in the upgrading notes. If not we are adding all upgrading notes to the release notes. But this is just my opinion, so no strong opinion here.

File: docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc [hunk 4]
```diff
@@ -22,6 +22,10 @@ It has been a while since discussions started about any activity around the Inst
 and any objection from the community about deprecating it for removal. For more details, see
 https://github.com/keycloak/keycloak/issues/37967[Deprecate for removal the Instagram social broker].
 
+=== Inconsistent user endpoints harmonized
+
+In previous releases there was an inconsistency in the REST endpoint result of getting a user and searching for a user. When BruteForce is enabled and a user was temporarily locked out one endpoint would return enabled=false while the other would return enabled=true. If the user was updated and enabled was false due to temporary lockout then the user would be disabled permanently. Both endpoints now return enabled=true when a user is temporarily locked out. To check whether a user is temporarily locked out the BruteForeUserResource endpoint should be utilised.
```
Comment (rmartinc) [inline docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc:27]: What about adding the url in each call?

```suggestion
In previous releases there was an inconsistency in the REST endpoint result of getting a user (`GET /admin/realms/{realm}/users/{user-id}`) and searching for a user (`GET /admin/realms/{realm}/users`). When BruteForce is enabled and a user was temporarily locked out the former endpoint would return enabled=false while the latter would return enabled=true. If the user was updated and enabled was false due to temporary lockout then the user would be disabled permanently. Both endpoints now return enabled=true when a user is temporarily locked out. To check whether a user is temporarily locked out the BruteForeUserResource endpoint should be utilised (`GET /admin/realms/{realm}/attack-detection/brute-force/users/{userId}`).
```

**Review by rmartinc — APPROVED** [review]
Just some suggestions for your consideration, but none is really critical. So I'm approving.

**Review by mposolda — COMMENTED** [review]
+1 to the comments by @rmartinc . Also added some additional comment with small typo. Once it is done, the PR is good IMO.

**Review by rmartinc — APPROVED** [review]
Thanks for the changes @douglaspalmer! LGTM!

**Review by mposolda — APPROVED** [review]
@douglaspalmer @rmartinc Thanks for the updates and review!
