### PR TITLE
fix: adds handling for a KC_CLI_PASSWORD env variable

### LINKED ISSUE #21961: Allow to provider password to kcadm (keycloak-admin-cli) via environment variable
### Description

Please allow us to provide the user password for `kcadm` also via the environment variable, not just `--password` option or interactively.

### Discussion

_No response_

### Motivation

Simplify using `kcadm` in scripts in a more secure way.

### Details

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #21961

Went the route of picocli defaults for this. We could consider adding a general default handler, but option keys for the "secrets" don't seem consistent.

The other possible "secret" env variables (not addressed in this pr) include:
- the truststore password (although we are trying to move away from truststores that require a password)
- the initial token
- the registration token

### CODE REVIEW

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseAuthOptionsCmd.java [hunk 1]
```diff
@@ -62,7 +62,7 @@ public abstract class BaseAuthOptionsCmd extends BaseGlobalOptionsCmd {
     @Option(names = "--user", description = "Username to login with")
     protected String user;
 
-    @Option(names = "--password", description = "Password to login with (prompted for if not specified and --user is used)")
+    @Option(names = "--password", description = "Password to login with (prompted for if --user is used and the env variable KC_CLI_PASSWORD is not defined)", defaultValue = "${env:KC_CLI_PASSWORD}")
```
Comment (vmuzikar) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseAuthOptionsCmd.java:65]:
```suggestion
    @Option(names = "--password", description = "Password to login with (prompted for if not specified, --user is used and the env variable KC_CLI_PASSWORD is not defined)", defaultValue = "${env:KC_CLI_PASSWORD}")
```

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseConfigCredentialsCmd.java [hunk 2]
```diff
@@ -202,7 +202,7 @@ public String help() {
         out.println("    --server SERVER_URL     Server endpoint url (e.g. 'http://localhost:8080')");
         out.println("    --realm REALM           Realm name to use");
         out.println("    --user USER             Username to login with");
-        out.println("    --password PASSWORD     Password to login with (prompted for if not specified and --user is used)");
+        out.println("    --password PASSWORD     Password to login with (prompted for if not specified --user is used and the env variable KC_CLI_PASSWORD is not defined)");
```
Comment (vmuzikar) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseConfigCredentialsCmd.java:205]:
```suggestion
        out.println("    --password PASSWORD     Password to login with (prompted for if not specified, --user is used and the env variable KC_CLI_PASSWORD is not defined)");
```

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thanks for this enhancement.

I think it might be good to also document it that it now accepts env var? Possibly [here](https://github.com/keycloak/keycloak/blob/c5ada9639e9b8cc39f0e09bc4f47c74027030226/docs/documentation/server_admin/topics/admin-cli.adoc?plain=1#L90)?

File: integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseAuthOptionsCmd.java [hunk 3]
```diff
@@ -62,7 +62,7 @@ public abstract class BaseAuthOptionsCmd extends BaseGlobalOptionsCmd {
     @Option(names = "--user", description = "Username to login with")
     protected String user;
 
-    @Option(names = "--password", description = "Password to login with (prompted for if not specified and --user is used)")
+    @Option(names = "--password", description = "Password to login with (prompted for if not specified, --user is usedm, the env variable KC_CLI_PASSWORD is not defined)", defaultValue = "${env:KC_CLI_PASSWORD}")
```
Comment (vmuzikar) [inline integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseAuthOptionsCmd.java:65]: Just a nitpick, small typo.
```suggestion
    @Option(names = "--password", description = "Password to login with (prompted for if not specified, --user is used, the env variable KC_CLI_PASSWORD is not defined)", defaultValue = "${env:KC_CLI_PASSWORD}")
```

**Comment by shawkins** [comment]
@vmuzikar updated the punctuation / typo. I'm now thinking this is probably too narrow in scope. Users would expect the same behavior for the client secret, store pass, etc. Does it seem ok to expend the effort for all of these?

**Comment by vmuzikar** [comment]
> Does it seem ok to expend the effort for all of these?

Works for me.

**Review by vmuzikar — APPROVED** [review]
LGTM, thank you @shawkins.
