### PR TITLE
Resolve disabled options even at fast startup

### LINKED ISSUE #30380: Incorrect warning log about deprecated options hostname, hostname-debug
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After updating to 25.0.0 and changing the configuration to the new hostname v2 options, a warning is logged on startup:
```
2024-06-12 12:21:17,077 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
        - hostname-debug
        - hostname
Consult the Release Notes for details.
```

The feature hostname v2 is enabled (by default) and hostname v1 is disabled:

image

The new configuration also works as expected:

image

It just seems like the new options are incorrectly marked as deprecated.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

No warnings about deprecated options are logged when using hostname v2 options.

### Actual behavior

A warning about deprecated options is logged on startup.

### How to Reproduce?

1. Use [hostname v2 configuration options](https://www.keycloak.org/server/hostname), e.g. with
    ```env
    KC_HOSTNAME=https://my.keycloak.hostname
    KC_HOSTNAME_DEBUG=true
    ```
2. Start Keycloak and observe the first log line

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #30380

Disabled mappers were not resolved (sanitized in terms of our code wording) on fast startup (`--optimized` flag + no CLI args). I assume the removed condition was there just for optimization. @mabartos Can you please confirm as you are the author of this code?

Unfortunately, there is no good way to test that. If we don't want to rely on Hostname v1 ([which is going away very soon](https://github.com/keycloak/keycloak/issues/27731)) as reported in the original issue, we have no other options that take some effect when value is provided even though the option is supposed to be disabled. For instance, any of the disabled logging options don't take any effect (no validations are performed) when their respective log handler is disabled.

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java [hunk 1]
```diff
@@ -257,8 +257,6 @@ private void remove(String key, PropertyMapper<?> mapper) {
         }
 
         public void sanitizeDisabledMappers() {
-            if (Environment.getParsedCommand().isEmpty()) return; // do not sanitize when no command is present
```
Comment (mabartos) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java:260]: @vmuzikar AFAIR, it was used for cases when no command is provided and help msg should be shown. I don't think it's gonna work. The parsed command should be set even for the fast startup (`kc.sh start --optimized`) - the `start` is the parsed command. And even for the startup, the sanitization should normally work - https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java#L83.

There might be some more deeply hidden issue - I can take a look at it tomorrow :)

**Comment by vmuzikar** [comment]
@mabartos Tests looks good now. Ready for another review round. :)

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java (hunk 1 above)
Comment (mabartos) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java]: > It was not as we initialize the commands only when Picocli is initialized too. I added an explicit command set for the fast startup. Let's see if the tests pass.

Yes, you're definitely right.

**Review by mabartos — APPROVED** [review]
@vmuzikar LGTM, thanks! 

Changes are so straighforward wrt the sanitizing disabled mappers that do not require additional test case.

I was able to reproduce it via setting the hostname env vars and do the fast startup with and without these changes, and I can confirm the log is not present anymore.
