### PR TITLE
fix for issue #31595

### LINKED ISSUE #31595: Misconfiguration of login settings causes login to not be possible
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If a user sets Login timeout to 0 as well as Login action timeout to 0, a "Login timeout." timeout appears instead of the login display (username/password/etc.).  This could cause the admin login experience to be locked out and require database manipulation to get back into the Keycloak admin experience.

### Version

latest as of 7/25/2024

### Regression

- [ ] The issue is a regression

### Expected behavior

Login experience is still usable.

Possibly, trying to put in zero values would be blocked by the UI as well.

### Actual behavior

Zero values are accepted and then login experience is replaced by "Login timeout" error message and no username/password prompts.

### How to Reproduce?

In Realm Settings -> Sessions,
Set Login timeout to "0" minutes.
Set Login action timeout to "0" minutes.

Then sign out and attempt to sign back in.

### Anything else?

downloaded using latest tag: docker run quay.io/keycloak/keycloak start-dev

I selected admin/ui as the area since it is where the input entry error took place.

### PR DESCRIPTION
**Pull request by himanshi1099**
closes #31595

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java [hunk 1]
```diff
@@ -692,6 +692,15 @@ public void updateRealm() {
         assertEquals(Boolean.FALSE, rep.isRegistrationEmailAsUsername());
         assertEquals(Boolean.FALSE, rep.isEditUsernameAllowed());
         assertEquals(Boolean.FALSE, rep.isUserManagedAccessAllowed());
+
+        rep.setAccessCodeLifespanLogin(0);
+        rep.setAccessCodeLifespanUserAction(0);
+        try {
+            realm.update(rep);
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java:699]: Can you please add something like `Assert.fail("Not expected to successfully update the realm");` after the `realm.update(rep)` ?

If the line with "Assert.fail" is not added, then it is not tested if realm update really failed as expected due the incorrect validation. See some other places for the inspiration (For example method `deleteSession()` of the `RealmTest`).

File: services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java [hunk 2]
```diff
@@ -389,6 +389,12 @@ public RealmRepresentation getRealm() {
                 rep.setRegistrationEmailAsUsername(realm.isRegistrationEmailAsUsername());
             }
 
+            if (auth.realm().canViewIdentityProviders()) {
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java:392]: Can you please remove this snippet of the code from your PR? As it looks that #31595 does not have anything to do with identity providers.

**Review by mposolda — COMMENTED** [review]
@himanshi1099 Thanks! Added 2 review comments

File: services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java [hunk 3]
```diff
@@ -457,8 +469,9 @@ public Response updateRealm(final RealmRepresentation rep) {
             throw ErrorResponse.error(e.getMessage(), Status.INTERNAL_SERVER_ERROR);
         } catch (ModelException e) {
             throw ErrorResponse.error(e.getMessage(), Status.BAD_REQUEST);
+        } catch (org.keycloak.services.ErrorResponseException e) {
+            throw ErrorResponse.error("AccessCodeLifespanLogin or AccessCodeLifespanUserAction cannot be 0", Status.BAD_REQUEST);
         } catch (Exception e) {
-            logger.error(e.getMessage(), e);
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java:461]: Could you please keep this line?

File: services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java [hunk 4]
```diff
@@ -457,8 +469,9 @@ public Response updateRealm(final RealmRepresentation rep) {
             throw ErrorResponse.error(e.getMessage(), Status.INTERNAL_SERVER_ERROR);
         } catch (ModelException e) {
             throw ErrorResponse.error(e.getMessage(), Status.BAD_REQUEST);
+        } catch (org.keycloak.services.ErrorResponseException e) {
+            throw ErrorResponse.error("AccessCodeLifespanLogin or AccessCodeLifespanUserAction cannot be 0", Status.BAD_REQUEST);
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java:473]: Can you please update this line just to:
```
throw e
```
so that the original exception is just re-thrown?

As for example when some other `ErrorResponse` was thrown (like the `Can't rename realm`), then it would be incorrectly re-thrown with the error `AccessCodeLifespanLogin or AccessCodeLifespanUserAction cannot be 0`, which would be very confusing.

**Review by mposolda — APPROVED** [review]
@himanshi1099 Thanks!
