### PR TITLE
Skip required runtime properties during build stage

### LINKED ISSUE #45415: cache-remote-host becomes mandatory at build time when using clusterless feature
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

In Keycloak 26.5.0 (the current `latest` version), the `cache-remote-host` option has become mandatory at build time when using the `clusterless` feature, causing a regression from version 26.4.x. This breaks environment-specific configuration patterns where the remote cache host differs between environments (dev, staging, production).

### Version

26.5.0

### Regression

- [x] The issue is a regression

### Expected behavior

The `cache-remote-host` option should:
1. Not be mandatory at build time when using `clusterless` feature
2. Allow configuration at runtime via environment variables or runtime parameters
3. Maintain backward compatibility with 26.4.x behavior

### Actual behavior

Build fails with the following error when `cache-remote-host` is not specified:
```
=> ERROR [2/2] RUN /opt/keycloak/bin/kc.sh build --features=clusterless --features-disabled="persistent-user-sessions"                                                                          0.5s
------
 > [2/2] RUN /opt/keycloak/bin/kc.sh build --features=clusterless --features-disabled="persistent-user-sessions":
0.453 WARNING: Usage of the default value for the db option in the production profile is deprecated. Please explicitly set the db instead.
0.457 The following options are required:
0.457 	- cache-remote-host: Required when feature 'multi-site' or 'clusterless' is set.
------
Dockerfile:4
--------------------
  2 |
  3 |   # Build with clusterless feature
  4 | >>> RUN /opt/keycloak/bin/kc.sh build --features=clusterless --features-disabled="persistent-user-sessions"
  5 |
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c /opt/keycloak/bin/kc.sh build --features=clusterless --features-disabled=\"persistent-user-sessions\"" did not complete successfully: exit code: 2  5 |
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c /opt/keycloak/bin/kc.sh build --features=clusterless --features-disabled=\"persistent-user-sessions\"" did not complete successfully: exit code: 2
```

### How to Reproduce?

```
cat > Dockerfile <<'EOF'
FROM [quay.io/keycloak/keycloak:26.5.0](http://quay.io/keycloak/keycloak:26.5.0)
# Build with clusterless feature
RUN /opt/keycloak/bin/kc.sh build --features=clusterless --features-disabled="persistent-user-sessions"
EOF
# 2. Build custom image
docker build -t keycloak-clusterless:26.5.0 .
# 3. Run with the environment-specific cache host
docker run -d \
 --name keycloak-26.5.0 \
 -p 8080:8080 \
 -e KEYCLOAK_ADMIN=admin \
 -e KEYCLOAK_ADMIN_PASSWORD=admin \
 -e KC_CACHE_REMOTE_HOST=infinispan.local\
 -e KC_CACHE_REMOTE_PORT=11222 \
 -e KC_CACHE_REMOTE_USERNAME=keycloak \
 -e KC_CACHE_REMOTE_PASSWORD=secret \
 -e KC_HOSTNAME=keycloak.local\
 -e KC_HTTP_ENABLED=true \
 keycloak-clusterless:26.5.0 \
 start-dev
```

### Anything else?

Here is what happens with 26.4.7 (expected):

```
cat > Dockerfile <<'EOF'
FROM quay.io/keycloak/keycloak:26.4.7

# Build with clusterless feature
RUN /opt/keycloak/bin/kc.sh build --features="clusterless" --features-disabled="persistent-user-sessions"
EOF

# 2. Build custom image
docker build -t keycloak-clusterless:26.4.7 .

# 3. Run with the environment-specific cache host
docker run -d \
  --name keycloak-26.4.7 \
  -p 8080:8080 \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  -e KC_CACHE_REMOTE_HOST=infinispan.local\
  -e KC_CACHE_REMOTE_PORT=11222 \
  -e KC_CACHE_REMOTE_USERNAME=keycloak \
  -e KC_CACHE_REMOTE_PASSWORD=secret \
  -e KC_HOSTNAME=keycloak.local\
  -e KC_HTTP_ENABLED=true \
  keycloak-clusterless:26.4.7 \
  start-dev
[+] Building 0.7s (6/6) FINISHED                                                                                                                                                                                                                           docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                       0.0s
 => => transferring dockerfile: 217B                                                                                                                                                                                                                                       0.0s
 => [internal] load metadata for quay.io/keycloak/keycloak:26.4.7                                                                                                                                                                                                          0.6s
 => [internal] load .dockerignore                                                                                                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                            0.0s
 => [1/2] FROM quay.io/keycloak/keycloak:26.4.7@sha256:9409c59bdfb65dbffa20b11e6f18b8abb9281d480c7ca402f51ed3d5977e6007                                                                                                                                                    0.0s
 => CACHED [2/2] RUN /opt/keycloak/bin/kc.sh build --features="clusterless" --features-disabled="persistent-user-sessions"                                                                                                                                                 0.0s
 => exporting to image                                                                                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                                                                                    0.0s
 => => writing image sha256:c98e458078e567ee06d3dd8c9e10a4b6e1f03aa23c3720965de925b56274d00c                                                                                                                                                                               0.0s
 => => naming to docker.io/library/keycloak-clusterless:26.4.7                                                                                                                                                                                                             0.0s

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/tj4ykfd73xhlfzf3h3jhngw0q
```

### PR DESCRIPTION
**Pull request by pruivo**
Fixes #45415

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 1]
```diff
@@ -398,12 +398,13 @@ private void validateProperty(AbstractCommand abstractCommand, IncludeOptions op
         if (mapper.isBuildTime() && !options.includeBuildTime) {
             return; // no need to validate as we've already checked for changes in the build time state
         }
+        boolean ignoreRuntime = mapper.isRunTime() && !options.includeRuntime;
```
Comment (shawkins) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:401]: It makes sense to move this up.

**Review by shawkins — APPROVED** [review]
LGTM, thanks @pruivo

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 1 above)
Comment (pruivo) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:401]: @shawkins, I'm sorry, do you mean before line 398?

Comment (shawkins) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:401]: No, I mean I agree with this change.
