### PR TITLE
Keycloak server fails to start when using different named schema

### LINKED ISSUE #10235: ERROR: relation "migration_model" does not exist
### Describe the bug

I'm not 100% sure if this is a bug or a missing configuration from my side. I can't get the latest Docker image `quay.io/keycloak/keycloak:17.0.0` up and running. The start always fails with the follwoing log messages:

```
2022-02-15 19:54:42,453 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 42P01
2022-02-15 19:54:42,453 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) ERROR: relation "migration_model" does not exist
  Position: 121
2022-02-15 19:54:42,500 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-02-15 19:54:42,555 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-02-15 19:54:42,555 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
2022-02-15 19:54:42,555 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: could not extract ResultSet
2022-02-15 19:54:42,556 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: relation "migration_model" does not exist
  Position: 121
```
Anyone experiencing the same issue?  The configuration was working with the `jboss/keycloak:16.1.0` image. I also tried to delete and re-create an empty database schema. But no luck either.

### Version

17.0.0

### Expected behavior

successfull start.

### Actual behavior

`ERROR: ERROR: relation "migration_model" does not exist`

### How to Reproduce?

```yaml
# docker-compose.yml
version: "3.6"
services:
  ## Keycloak IAM Authentication Provider
  authentication-provider:
    image: quay.io/keycloak/keycloak:17.0.0
    command: "start --auto-build"
    ports:
      - "9001:8080"
    restart: unless-stopped
    environment:
      ## Host settings
      KC_HOSTNAME: keycloak
      ## Database settings
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DB}
      KC_DB_SCHEMA: ${KEYCLOAK_SCHEMA}
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASSWORD}
      ## Admin User settings
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      ## Proxy settings
      KC_PROXY: edge

### Anything else?

_No response_

### LINKED ISSUE #12219: Keycloak server fails to start when using different named schema
### Describe the bug

Keycloak fails to start with the following error when using a different schema than default 'public' when running postgres 

`2022-05-27 12:55:27,356 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-05-27 12:55:27,357 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
2022-05-27 12:55:27,359 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: could not extract ResultSet
2022-05-27 12:55:27,359 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: relation "migration_model" does not exist
  Position: 121`

Looks like it is searching for table migration_model in the public default schema. The tables exist on the named schema

### Version

18.0.0

### Expected behavior

Keycloak server to start successfully

### Actual behavior

keycloak fails to start with error relation "migration_model" does not exist

### How to Reproduce?

Use the following config specifying DB schema and start keycloak bat/sh

# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
db=postgres

# The username of the database user.
db-username=postgres

# The password of the database user.
db-password=postgres

db-schema=kc

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
db-url=jdbc:postgresql://localhost:5432/kcnew?ssl=false

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #12219
Closes #10235

* The `quarkus.hibernate-orm.database.default-schema` is not forcing a default schema to Hibernate. Something changes that makes the extension to mark the default PU as not coming from an XML file causing the property to not be set https://github.com/quarkusio/quarkus/blob/a71f7f0b4360494157bcf18f0eb3df6f5b2e13a5/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/FastBootHibernatePersistenceProvider.java#L186.
* To force a schema a new PU listener is created to set the default schema to Hibernate directly, pretty much what HHH extension should be doing.

Right now, only `db-schema` is impacted because it is among the runtime properties we are exposing from Quarkus that rely on the PU coming from an XML file.

### CODE REVIEW

File: quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java [hunk 1]
```diff
@@ -17,22 +17,12 @@
...
-import org.keycloak.it.junit5.extension.CLIResult;
 import org.keycloak.it.junit5.extension.CLITest;
 import org.keycloak.it.junit5.extension.WithDatabase;
-import org.keycloak.it.storage.database.BasicDatabaseTest;
+import org.keycloak.it.storage.database.MariaDBTest;
 
 @CLITest
 @WithDatabase(alias = "mariadb")
-public class MariaDBDistTest extends BasicDatabaseTest {
+public class MariaDBDistTest extends MariaDBTest {
```
Comment (vmuzikar) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java:26]: Just out of curiosity, what is the difference between `MariaDBDistTest` and `MariaDBTest`. They seem identical now (incl. annotations).

**Review by vmuzikar — APPROVED** [review]
As far as I can tell, LGTM (although it's now area of my expertise).

File: quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java (hunk 1 above)
Comment (pedroigor) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java:26]: One runs in the same JVM as tests, the other is running the dist.

JVM tests are easier to develop/test/debug. And dist tests are more a E2E test.

We should have more dist tests.

Comment (DGuhr) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java:26]: tbh i am more into having more CLITests, as they are whiteboxed (as you say, easily debuggable etc). but that's sadly most of the time not possible bc. they are not playing well when a `build` is invoked and thus another java process spawns, so we rely on blackbox tests for that one.

File: quarkus/tests/integration/src/main/resources/database/scripts/init-postgres.sql [hunk 2]
```diff
@@ -0,0 +1,18 @@
+/*
+ * Copyright 2021 Red Hat, Inc. and/or its affiliates
```
Comment (DGuhr) [inline quarkus/tests/integration/src/main/resources/database/scripts/init-postgres.sql:2]: nitpick, not blocking: we have 2022 now ;)

**Review by DGuhr — APPROVED** [review]
LGTM, thanks :) Couldn't reproduce the migration problem locally anymore.

**Review by abstractj — APPROVED** [review]
