### PR TITLE
Fowarding scopes when initializing the JS adapter

### LINKED ISSUE #35060: Cannot request additional scopes when using the account console
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

Trying to request additional scopes when authenticating to the account console does not grant the requested scopes. This is a regression introduced by https://github.com/keycloak/keycloak/pull/32686.

After the user is successfully authenticated and redirected back to the account console for the very first time, the user is redirected back to the server because it is the first time accessing the account console. At this point, the authorization request does not contain any `scope` parameter, and the scopes previously requested are ignored.

[1] https://github.com/keycloak/keycloak/pull/32686

### Version

999-SNAPSHOT

### Regression

- [ ] The issue is a regression

### Expected behavior

Any scope requested when changing the `scope` parameter when at the login page needs to be granted.

### Actual behavior

Any scope requested when changing the `scope` parameter at the login page is not granted.

### How to Reproduce?

* Reach the account console at `http://localhost:8180/realms/{realm}/account/`
* At the login page, add/set the `scope` parameter to  `phone` to request this scope
* Authenticate
* Check if the token issued by the server holds the `phone` scope

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #35060

### CODE REVIEW

File: js/libs/ui-shared/src/context/environment.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export type BaseEnvironment = {
   logo: string;
   /** The URL to be followed when the logo is clicked. */
   logoUrl: string;
+  scope?: string;
```
Comment (jonkoops) [inline js/libs/ui-shared/src/context/environment.ts:22]: If this is only used in the [account environment](https://github.com/keycloak/keycloak/blob/ced8e643c9c80ccd549439d0db9d03088748b464/js/apps/account-ui/src/environment.ts#L6). Ideally this field is also commented so folks know what it does.

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by ssilvert — APPROVED** [review]
