### PR TITLE
[OID4VCI] Ensure authorization_details from PAR requests are properly returned in token responses

### LINKED ISSUE #43214: [OID4VC] Ensure authorization_details from PAR requests are properly returned in token responses for conformace tests
#### Problem
- When `authorization_details` is passed in a PAR request, the system was not properly ensuring it gets returned in the token response
- The OID4VC specification requirement for mandatory `authorization_details` in token responses when used in authorization requests was not being enforced

#### Solution
1. **Extended AuthorizationDetailsProcessor SPI**: Added `processStoredAuthorizationDetails()` method to handle `authorization_details` from stored authorization requests (PAR)
2. **Enhanced OID4VC Processor**: Updated `OID4VCAuthorizationDetailsProcessor` to process stored `authorization_details` and throw `OAuthErrorException` when processing fails
3. **Improved Error Handling**: Modified `OAuth2GrantTypeBase` to catch `OAuthErrorException` and wrap it in `CorsErrorResponseException` for proper HTTP 400 responses
4. **Updated Authorization Code Flow**: Enhanced `AuthorizationCodeGrantType` to process stored `authorization_details` with proper error handling
5. **Comprehensive Testing**: Added dedicated test suite covering success, failure, and no-details scenarios

#### Authorization Code flow with no `authorization_details`

Image

#### Authorization Code flow with `authorization_details`

Image

### PR DESCRIPTION
**Pull request by forkimenjeckayang**
## Summary
This PR implements proper handling of `authorization_details` parameter in OID4VC authorization code flow when used with Pushed Authorization Requests (PAR). According to the OID4VC specification, when `authorization_details` is used in the authorization request (e.g., via PAR), it is **required** to be returned in the token response. If processing fails for this specific scenario, it should result to an error response.

## Problem
- When `authorization_details` is passed in a PAR request, the system was not properly ensuring it gets returned in the token response
- The OID4VC specification requirement for mandatory `authorization_details` in token responses when used in authorization requests was not being enforced

## Solution
1. **Extended AuthorizationDetailsProcessor SPI**: Added `processStoredAuthorizationDetails()` method to handle `authorization_details` from stored authorization requests (PAR)
2. **Enhanced OID4VC Processor**: Updated `OID4VCAuthorizationDetailsProcessor` to process stored `authorization_details` and throw `OAuthErrorException` when processing fails
3. **Improved Error Handling**: Modified `OAuth2GrantTypeBase` to catch `OAuthErrorException` and wrap it in `CorsErrorResponseException` for proper error responses
4. **Updated Authorization Code Flow**: Enhanced `AuthorizationCodeGrantType` to process stored `authorization_details` with proper error handling
5. **Comprehensive Testing**: Added dedicated test suite covering success, failure, and no-details scenarios

## Authorization Code flow with no `authorization_details`

Image

## Authorization Code flow with `authorization_details`

Image

Closes #43214

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java [hunk 1]
```diff
@@ -384,6 +384,14 @@ private void updateAuthenticationSession() {
                 authenticationSession.setClientNote(LOGIN_SESSION_NOTE_ADDITIONAL_REQ_PARAMS_PREFIX + paramName, request.getAdditionalReqParams().get(paramName));
             }
         }
+
+        // Store authorization_details from authorization/PAR request for later processing
+        if (request.getAdditionalReqParams() != null) {
+            String authorizationDetails = request.getAdditionalReqParams().get(OAuth2Constants.AUTHORIZATION_DETAILS_PARAM);
+            if (authorizationDetails != null) {
+                authenticationSession.setClientNote(OAuth2Constants.AUTHORIZATION_DETAILS_PARAM, authorizationDetails);
```
Comment (tnorimat) [inline services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java:390]: Line 382 and Line 389 do the same thing.
To remove this duplication, how about moving Line 390-392 after Line 385?

File: services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java [hunk 2]
```diff
@@ -225,7 +225,20 @@ public Response process(Context context) {
...
+            try {
+                authorizationDetailsResponse = processStoredAuthorizationDetails(userSession, clientSessionCtx);
+                if (authorizationDetailsResponse != null && !authorizationDetailsResponse.isEmpty()) {
+                    clientSessionCtx.setAttribute(AUTHORIZATION_DETAILS_RESPONSE, authorizationDetailsResponse);
+                }
+            } catch (CorsErrorResponseException e) {
+                // Re-throw CorsErrorResponseException as it's already properly formatted for HTTP response
+                throw e;
+            }
+        }
```
Comment (tnorimat) [inline services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java:244]: It seems that negating  Line 229 `authorizationDetailsResponse != null && !authorizationDetailsResponse.isEmpty()` equals Line 242 `authorizationDetailsResponse == null || authorizationDetailsResponse.isEmpty()`.

How about the following?
```
        // If no authorization_details were processed from the request, try to process stored authorization_details
        if (authorizationDetailsResponse == null || authorizationDetailsResponse.isEmpty()) {
            try {
                authorizationDetailsResponse = processStoredAuthorizationDetails(userSession, clientSessionCtx);
                if (authorizationDetailsResponse != null && !authorizationDetailsResponse.isEmpty()) {
                    clientSessionCtx.setAttribute(AUTHORIZATION_DETAILS_RESPONSE, authorizationDetailsResponse);
                } else {
                    authorizationDetailsResponse = handleMissingAuthorizationDetails(clientSession.getUserSession(), clientSessionCtx);
                    if (authorizationDetailsResponse != null && !authorizationDetailsResponse.isEmpty()) {
                        clientSessionCtx.setAttribute(AUTHORIZATION_DETAILS_RESPONSE, authorizationDetailsResponse);
                    } 
                }
            } catch (CorsErrorResponseException e) {
                // Re-throw CorsErrorResponseException as it's already properly formatted for HTTP response
                throw e;
            }
        }
```

**Review by tnorimat — COMMENTED** [review]
Hello, I added two review comments. Could you check them?

**Comment by Captain-P-Goldfish** [comment]
I know you have tested it with the testsuite but not adding a unit test tends to a broken result in a future version if the test-suit was not used to test-the new extensions. Therefore, I would recommend to also add a unit-test

**Comment by forkimenjeckayang** [comment]
> I know you have tested it with the testsuite but not adding a unit test tends to a broken result in a future version if the test-suit was not used to test-the new extensions. Therefore, I would recommend to also add a unit-test

Thank you for the feedback! @Captain-P-Goldfish 
 I've addressed your concern about unit test coverage for the OID4VCAuthorizationDetailsProcessor.

**Comment by forkimenjeckayang** [comment]
> Hello, I added two review comments. Could you check them?

Thnak you @tnorimat  for the suggestions.
Changes applied. Please have another look

File: services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java
Comment (tnorimat) [inline services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java]: How about removing the comment (L296)?

I think that we can implement RAR processing by implementing `AuthorizationDetailsProcessor` other than for OID4VCI.

Considering this point, this method is not for OID4VC specific. It can be used for other purpose.

What do you think about that?

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 3]
```diff
@@ -0,0 +1,459 @@
...
+public class OID4VCAuthorizationDetailsProcessorTest {
+
+    /**
+     * Creates a valid AuthorizationDetail for testing
+     */
+    private AuthorizationDetail createValidAuthorizationDetail() {
+        AuthorizationDetail authDetail = new AuthorizationDetail();
+        authDetail.setType("openid_credential");
+        authDetail.setCredentialConfigurationId("test-config-id");
+        authDetail.setLocations(Arrays.asList("https://test-issuer.com"));
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 4]
```diff
@@ -0,0 +1,459 @@
...
+        ClaimsDescription claim = createInvalidClaimsDescription();
+        assertNull("Path should be null", claim.getPath());
+        assertTrue("Mandatory should be true", claim.isMandatory());
+    }
+
+    @Test
+    public void testClaimsDescriptionWithEmptyPath() {
+        // Test claims description with empty path
+        ClaimsDescription claim = new ClaimsDescription();
+        claim.setPath(Arrays.asList());
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 5]
```diff
@@ -0,0 +1,459 @@
...
+        assertEquals("Fourth path element should be correct", "number", claim.getPath().get(3));
+        assertFalse("Claim should not be mandatory", claim.isMandatory());
+    }
+
+    @Test
+    public void testParseAuthorizationDetailsLogic() {
+        // Test valid authorization details structure that would be parsed
+        AuthorizationDetail authDetail = createValidAuthorizationDetail();
+        ClaimsDescription claim = createValidClaimsDescription();
+        authDetail.setClaims(Arrays.asList(claim));
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 6]
```diff
@@ -0,0 +1,459 @@
...
+
+        List<AuthorizationDetail> authDetails = Arrays.asList(authDetail);
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 7]
```diff
@@ -0,0 +1,459 @@
...
+    public void testValidateClaimsLogic() {
+        // Test valid claims that would pass validation
+        AuthorizationDetail authDetailWithClaims = createValidAuthorizationDetailWithClaims();
+        List<ClaimsDescription> validClaims = authDetailWithClaims.getClaims();
+        assertValidClaims(validClaims);
+
+        for (ClaimsDescription claim : validClaims) {
+            assertNotNull("Each claim path should not be null", claim.getPath());
+            assertFalse("Each claim path should not be empty", claim.getPath().isEmpty());
+            assertTrue("Each claim path should start with credentialSubject",
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: It can be  `            assertEquals("Each claim path should start with credentialSubject", "credentialSubject", claim.getPath().get(0));
`

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 8]
```diff
@@ -0,0 +1,459 @@
...
+                    claim.getPath().get(0).equals("credentialSubject"));
+        }
+
+        // Test invalid claims that would fail validation
+        ClaimsDescription invalidClaim = createInvalidClaimsDescription();
+        assertNull("Invalid claim path should be null", invalidClaim.getPath());
+
+        ClaimsDescription emptyPathClaim = new ClaimsDescription();
+        emptyPathClaim.setPath(Arrays.asList()); // Empty path
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 9]
```diff
@@ -0,0 +1,459 @@
...
+        assertNotNull("Empty path claim should not be null", emptyPathClaim.getPath());
+        assertTrue("Empty path should be empty", emptyPathClaim.getPath().isEmpty());
+    }
+
+    @Test
+    public void testBuildAuthorizationDetailResponseLogic() {
+        // Test authorization detail that would be used to build response
+        AuthorizationDetail authDetail = createValidAuthorizationDetail();
+        ClaimsDescription claim = createValidClaimsDescription();
+        authDetail.setClaims(Arrays.asList(claim));
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 10]
```diff
@@ -0,0 +1,459 @@
...
+
+        // Verify the data structure that buildAuthorizationDetailResponse() would process
+        assertValidAuthorizationDetail(authDetail);
+        assertNotNull("Claims should not be null", authDetail.getClaims());
+        assertEquals("Should have exactly one claim", 1, authDetail.getClaims().size());
+
+        // Test the response structure that would be built
+        String expectedType = "openid_credential";
+        String expectedCredentialConfigurationId = "test-config-id";
+        List<String> expectedCredentialIdentifiers = Arrays.asList("test-identifier-123");
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 11]
```diff
@@ -0,0 +1,459 @@
...
+        List<ClaimsDescription> expectedClaims = Arrays.asList(claim);
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 12]
```diff
@@ -0,0 +1,459 @@
...
+        assertNotNull("Response claims should not be null", expectedClaims);
+        assertEquals("Response should have exactly one claim", 1, expectedClaims.size());
+    }
+
+    @Test
+    public void testProcessStoredAuthorizationDetailsLogic() {
+        // Test valid stored authorization details
+        AuthorizationDetail storedDetail = createValidAuthorizationDetail();
+        ClaimsDescription claim = createValidClaimsDescription();
+        storedDetail.setClaims(Arrays.asList(claim));
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 13]
```diff
@@ -0,0 +1,459 @@
...
+
+        List<AuthorizationDetail> storedDetails = Arrays.asList(storedDetail);
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 14]
```diff
@@ -0,0 +1,459 @@
...
+        // Test the authorization details that would be generated
+        for (String configId : credentialConfigurationIds) {
+            // Verify each configuration ID would generate proper authorization detail
+            assertNotNull("Configuration ID should not be null", configId);
+            assertFalse("Configuration ID should not be empty", configId.isEmpty());
+            assertTrue("Configuration ID should start with 'config'", configId.startsWith("config"));
+        }
+
+        // Test empty credential configuration IDs
+        List<String> emptyConfigIds = Arrays.asList();
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java [hunk 15]
```diff
@@ -0,0 +1,459 @@
...
+        AuthorizationDetail missingIdDetail = createMissingCredentialIdAuthorizationDetail();
+        assertMissingCredentialIdAuthorizationDetail(missingIdDetail);
+
+        // Test invalid claims error handling
+        ClaimsDescription invalidClaim = createInvalidClaimsDescription();
+        assertNull("Invalid claim path should be null", invalidClaim.getPath());
+
+        // Test empty claims error handling
+        ClaimsDescription emptyPathClaim = new ClaimsDescription();
+        emptyPathClaim.setPath(Arrays.asList());
```
Comment (tnorimat) [inline services/src/test/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessorTest.java]: `Arrays.asList` can be `List.of` .

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java [hunk 16]
```diff
@@ -0,0 +1,422 @@
...
+        // Create authorization details with claims
+        ClaimsDescription claim = new ClaimsDescription();
+        List<Object> claimPath = Arrays.asList("credentialSubject", getExpectedClaimPath());
+        claim.setPath(claimPath);
+        claim.setMandatory(true);
+
+        AuthorizationDetail authDetail = new AuthorizationDetail();
+        authDetail.setType(OPENID_CREDENTIAL_TYPE);
+        authDetail.setCredentialConfigurationId(credentialConfigurationId);
+        authDetail.setClaims(Arrays.asList(claim));
```
Comment (tnorimat) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java]: `Arrays.asList` can be `List.of` .

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java [hunk 17]
```diff
@@ -0,0 +1,422 @@
...
+     */
+    protected static class Oid4vcTestContext {
+        public CredentialIssuer credentialIssuer;
+        public OIDCConfigurationRepresentation openidConfig;
+    }
+
+    /**
+     * Get the credential format (jwt_vc or sd_jwt_vc)
+     */
+    protected String getCredentialFormat() {
```
Comment (tnorimat) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java]: This method is never called. Is it intentional?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java [hunk 18]
```diff
@@ -0,0 +1,422 @@
...
+            verifyCredentialStructure(credentialObj);
+        }
+    }
+
+    @Test
+    public void testAuthorizationCodeFlowWithPARAndAuthorizationDetailsFailure() throws Exception {
+        Oid4vcTestContext ctx = prepareOid4vcTestContext();
+
+        // Step 1: Create PAR request with INVALID authorization_details
+        String credentialConfigurationId = getCredentialClientScope().getAttributes().get(CredentialScopeModel.CONFIGURATION_ID);
```
Comment (tnorimat) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java]: It seems that `credentialConfigurationId ` is never used. Is it intentional?

**Review by tnorimat — COMMENTED** [review]
Hello, I added some review comment. Could you check them?

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java (hunk 18 above)
Comment (Captain-P-Goldfish) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java]: I think it is set in the authDetail object in line 139

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java (hunk 17 above)
Comment (Captain-P-Goldfish) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowWithPARTest.java]: +1 - method should be removed if not needed

File: services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java
Comment (Captain-P-Goldfish) [reply services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java]: +1

**Comment by Awambeng** [comment]
@tnorimat @Captain-P-Goldfish thank you for the reviews! I’ve addressed the comments you added on behalf of @forkimenjeckayang, who’s currently on vacation. Could please check again?

**Review by tnorimat — APPROVED** [review]
LGTM

**Review by Captain-P-Goldfish — APPROVED** [review]
looks also good to me

**Comment by Awambeng** [comment]
Thank you @Captain-P-Goldfish @tnorimat for the reviews

**Review by mposolda — APPROVED** [review]
@forkimenjeckayang @Awambeng @tnorimat @Captain-P-Goldfish Thanks for the updates and review!
