### PR TITLE
KEYCLOAK-19148 correct getGroupsCountByNameContaining of MapGroupProv…

### LINKED ISSUE #9585: Different method getGroupsCountByNameContaining in MapGroupProvider and JpaRealmProvider
### Describe the bug

See https://issues.redhat.com/browse/KEYCLOAK-19148

### Version

16.0.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**

### CODE REVIEW

**Comment by mposolda** [comment]
@hmlnarik Since this is related to map storage, do you please have a chance to review this or assign to someone for review? Thanks

**Review by martin-kanis — CHANGES_REQUESTED** [review]
@cgeorgilakis Thank you for the fix! It looks good. Only think I would improve is Javadoc in `GroupProvider.getGroupsCountByNameContaining` so it's clear that the method counts only top level groups.

File: model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java [hunk 1]
```diff
@@ -129,11 +129,7 @@ public Long getGroupsCount(RealmModel realm, Boolean onlyTopGroups) {
 
     @Override
     public Long getGroupsCountByNameContaining(RealmModel realm, String search) {
-        ModelCriteriaBuilder<GroupModel> mcb = groupStore.createCriteriaBuilder()
-          .compare(SearchableFields.REALM_ID, Operator.EQ, realm.getId())
-          .compare(SearchableFields.NAME, Operator.ILIKE, "%" + search + "%");
-
-        return tx.getCount(withCriteria(mcb));
+        return searchForGroupByNameStream(realm, search, null, null).count();
```
Comment (hmlnarik) [inline model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java:132]: Please keep use of `getCount`, for performance reason.

**Review by hmlnarik — CHANGES_REQUESTED** [review]

File: model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java (hunk 1 above)
Comment (martin-kanis) [reply model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java:132]: @hmlnarik Not sure that is possible. We need this part
```
tx.read(withCriteria(mcb).pagination(firstResult, maxResults, SearchableFields.NAME))
            .map(MapGroupEntity::getId)
            .map(id -> {
                GroupModel groupById = session.groups().getGroupById(realm, id);
                while (Objects.nonNull(groupById.getParentId())) {
                    groupById = session.groups().getGroupById(realm, groupById.getParentId());
                }
                return groupById;
            }).sorted(GroupModel.COMPARE_BY_NAME).distinct();
``` 
from `searchForGroupByNameStream`.

Comment (hmlnarik) [reply model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java:132]: You are right, thanks @martin-kanis . That only stresses the need to improve Javadoc.

**Comment by hmlnarik** [comment]
@cgeorgilakis Please rebase to `main` branch which is the new name of the main Keycloak branch, and also add a test.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java [hunk 2]
```diff
@@ -1117,6 +1117,14 @@ public void searchAndCountGroups() throws Exception {
 
         assertEquals(new Long(allGroups.size()), realm.groups().count(true).get("count"));
         assertEquals(new Long(allGroups.size() + 1), realm.groups().count(false).get("count"));
+        //search and count for group with string group11 -> return 2 top level group, group11 and group0 having subgroup group1111
```
Comment (martin-kanis) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java:1120]: @cgeorgilakis  Thank you for the Javadoc and test. It would be also good to cover a scenario which fails without your change. 
```suggestion
        //add another subgroup
        GroupRepresentation level2Group2 = new GroupRepresentation();
        level2Group2.setName("group111111");
        realm.groups().group(firstGroupId).subGroup(level2Group2);

        //search and count for group with string group11 -> return 2 top level group, group11 and group0 having subgroup group1111
        search = realm.groups().groups("group11",0,10);
        assertEquals(2, search.size());
        GroupRepresentation group0 = search.stream().filter(group -> "group0".equals(group.getName())).findAny().orElseGet(null);
        assertNotNull(group0);
        assertEquals(2,group0.getSubGroups().size());
        assertThat(group0.getSubGroups().stream().map(GroupRepresentation::getName).collect(Collectors.toList()), Matchers.containsInAnyOrder("group1111", "group111111"));
        assertEquals(new Long(search.size()), realm.groups().count("group11").get("count"));
```

**Review by martin-kanis — CHANGES_REQUESTED** [review]

**Comment by cgeorgilakis** [comment]
I have rebased to main branch, I have changed javadoc and I have enhanced test method searchAndCountGroups of GroupTest

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java (hunk 2 above)
Comment (cgeorgilakis) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java:1120]: How will we test scenario that fails without my change? 
Fe the corrected test will fail in Keycloak main. realm.groups().count("group11").get("count") will return 3 instead of 2.

Comment (martin-kanis) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java]: If you run the test with ConcurrentHashMap group provider `mvn clean install -nsu -B -Pauth-server-undertow -Pmap-storage -f testsuite/integration-arquillian/tests/base/pom.xml -Dtest=GroupTest#searchAndCountGroups` the test will pass if you revert the change in `MapGroupProvider`. The key part is add another subgroup to make it fail without your change.

**Comment by martin-kanis** [comment]
@cgeorgilakis Thanks! Can you please squash the commits and once the checks are green this is ready to go from my point of view.

**Comment by cgeorgilakis** [comment]
I have squashed to one commit. Sorry, I have misunderstand your previous comment.

**Review by martin-kanis — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]
Thanks for the contribution!
Approving per @martin-kanis 's approval
