### PR TITLE
Login-page a11y improvements

### LINKED ISSUE #27190: a11y improvements on login page
### Description

Some a11y improvements on the login page:
* Tab index seems incorrect (jumping between elements instead of a logical DOM order
* `h4` is used instead of a `h2` for `or sign in with`-header content. See https://www.w3.org/WAI/tutorials/page-structure/headings/
  > Skipping heading ranks can be confusing and should be avoided where possible
* The language selector is not accessible with keyboard

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by pkeuter**
Closes #27190

Changes:
* Improved order of tabindexes to avoid jumping
* Set autocomplete to `username` and `current-password` for the respective fields
* Switched `h4` to `h2` to conform to spec (see #27190)
* Added `h2` styling to keycloak theme to let the `h2` visually stay the same as the `h4`
* Made the language selector keyboard-accessible by using the specification from https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-links/ (the script from [here](https://www.w3.org/WAI/content-assets/wai-aria-practices/patterns/menu-button/examples/js/menu-button-links.js) is licensed by the [W3C license](https://www.w3.org/copyright/software-license-2023/). The file is not modified, and placed as-is with copyright notice.

### CODE REVIEW

File: themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js [hunk 1]
```diff
@@ -0,0 +1,308 @@
...
+function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
+function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
+function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == typeof i ? i : String(i); }
+function _toPrimitive(t, r) { if ("object" != typeof t || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != typeof i) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
+var MenuButtonLinks = /*#__PURE__*/function () {
```
Comment (jonkoops) [inline themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js:17]: This code looks downcompiled to ES5 from some kind of source, I'd rather not check this in. If you need modern JS syntax you can use the latest features available in evergreen browsers.

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js (hunk 1 above)
Comment (pkeuter) [reply themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js:17]: For context see the `Base IT` action that had a problem with the defined `const`: https://github.com/keycloak/keycloak/actions/runs/7986432593/job/21807156724#step:4:52140
``` 
Run 1: RealmTest.deleteSession » WebDriver com.gargoylesoftware.htmlunit.ScriptException: missing ; before statement (https://localhost:8543/auth/resources/em9ks/login/keycloak/js/menu-button-links.js#12)
```
I would (very) gladly use more modern JS, but `HtmlUnitDriver` used in the Keycloak integration tests don't support this (yet).

Comment (jonkoops) [reply themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js:17]: Yeah, this is a problem we're working on. The test suite will be modernized in the near future to address this. For now you can load your script using `type="module"`, which the test suite will ignore.

Comment (pkeuter) [reply themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js:17]: Ah, that is a nice thing to know. I will update to the ES6 version in that case! Thanks

File: themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js [hunk 2]
```diff
@@ -0,0 +1,328 @@
...
+    this.lastMenuitem = false;
+    this.firstChars = [];
+
+    this.buttonNode.addEventListener(
+      'keydown',
+      this.onButtonKeydown.bind(this)
+    );
+    this.buttonNode.addEventListener('click', this.onButtonClick.bind(this));
+
+    var nodes = domNode.querySelectorAll('[role="menuitem"]');
```
Comment (jonkoops) [inline themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js:28]: If you have a variable then declare it with `const` if it doesn't get re-assigned, otherwise use `let`.

File: themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js [hunk 3]
```diff
@@ -0,0 +1,328 @@
...
+
+    for (var i = 0; i < nodes.length; i++) {
```
Comment (jonkoops) [inline themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js:30]: Let's not use indexes if it can be avoided for iteration, a `NodeList` implements an iterator so `for...of` should be possible here.

File: themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js [hunk 4]
```diff
@@ -0,0 +1,328 @@
...
+
+    window.addEventListener(
+      'mousedown',
+      this.onBackgroundMousedown.bind(this),
+      true
+    );
+  }
+
+  setFocusToMenuitem(newMenuitem) {
+    this.menuitemNodes.forEach(function (item) {
```
Comment (jonkoops) [inline themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js:60]: Let's use arrow functions for anonymous functions.

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Comment by pkeuter** [comment]
Thanks for the review @jonkoops. Like I said in the PR-description, this is a script from W3C, which is now placed in this repo without any modifications. If you want all these changes, I think it is better to rewrite from scratch. But to be honest, treating this as a library-file is not so bad, is it?

It's your choice obviously but I am not sure if I have the time currently to rewrite this file. Is there another way to incorporate this as a library file?

**Comment by jonkoops** [comment]
If we are going to check something in it will have to be up to our code standards. If it is a library available on NPM it can be included as a 'common' package, which can be [installed here](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/keycloak/common/resources/package.json).

**Comment by pkeuter** [comment]
Thanks for your reply @jonkoops. Other scripts, like https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/resources/js/base64url.js are also committed using functions that do not use the standards of Keycloak since they are just used as a library (I assume):

[// for embedded scripts, quoted and modified from https://github.com/swansontec/rfc4648.js by William Swanson](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/resources/js/base64url.js#L1C1-L1C110).

Can't we commit this file in the same fashion?

**Comment by jonkoops** [comment]
> Other scripts, like [`base64url.js`](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/resources/js/base64url.js) are also committed using functions that do not use the standards of Keycloak since they are just used as a library.

Yes, this is true as in this case this is being refactored in another PR (#27239) to match our code conventions. The convention generally is:

- If it is on NPM, and distributed in the [ECMAScript module format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), install it through NPM and include it on the page.
- If it does not meet these conditions, relevant parts may be included as files in source, refactored to meet Keycloak standards.

**Comment by pkeuter** [comment]
Thanks, I will try to find a moment to refactor then. I think this PR brings some useful accessibility fixes to the login-page.

**Comment by jonkoops** [comment]
> I think this PR brings some useful accessibility fixes to the login-page.

For sure, would love to land this!

**Comment by pkeuter** [comment]
@jonkoops I think I have now implemented all your suggested changes. Please let me know if everything is okay now.

File: themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js [hunk 5]
```diff
@@ -0,0 +1,319 @@
...
+        this.closePopup();
+        this.buttonNode.focus();
+      }
+    }
+  }
+}
+
+// Initialize menu buttons
+
+window.addEventListener("load", () => {
```
Comment (jonkoops) [inline themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js:314]: There should be no need for this in a module script, as these are [deferred by default](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts).

**Review by jonkoops — CHANGES_REQUESTED** [review]
One small nit, otherwise LGTM

**Comment by jonkoops** [comment]
@pkeuter Just FYI, we're [developing a new login theme](https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources/theme/keycloak.v2/login) based on PatternFly 5, you might want to backport your efforts there as well.

**Comment by pkeuter** [comment]
> @pkeuter Just FYI, we're [developing a new login theme](https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources/theme/keycloak.v2/login) based on PatternFly 5, you might want to backport your efforts there as well.

That's good to know. I'll look into that later.

File: themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js (hunk 5 above)
Comment (pkeuter) [reply themes/src/main/resources/theme/base/login/resources/js/menu-button-links.js]: Good one. Fixed.

**Review by jonkoops — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
approving as of @jonkoops's review.

**Comment by jonkoops** [comment]
The FIPS test failures are unrelated, we'll have to a rebase after those have been fixed under #27346
