### PR TITLE
Hibernate Validator is enabled by default when not used

### LINKED ISSUE #45677: Hibernate Validator is enabled by default when not used
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

The Hibernate Validator is enabled by default, even when it's not used currently. The Hibernate Validator is only used for the new Client API v2 right now. Enabling Hibernate Validator is quite resource-consuming for startup due to expensive initialization. That's also a difference between 26.4.x and 26.5.x, so it's considered as regression. 

Startup time:

Image

Startup memory allocations (against 26.4.x) (~10MB with other related procedures):
 
Image

### Version

26.5.1

### Regression

- [x] The issue is a regression

### Expected behavior

Hibernate Validator is not enabled when not needed

### Actual behavior

Hibernate Validator is always enabled

### How to Reproduce?

Start the server and see enabled Quarkus extensions

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #45677
- Do not enable expensive Hibernate Validator when it's not needed
- Extension does not do any execution + no Quarkus extension is listed in the log
- Might contribute to https://github.com/keycloak/keycloak/issues/45662

Screenshot From 2026-01-22 13-10-29

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java [hunk 1]
```diff
@@ -102,8 +101,6 @@ public static Response getResponse(KeycloakSession session, Throwable throwable)
                 error.setErrorDescription("Cannot parse the JSON");
             } else if (isServerError) {
                 error.setErrorDescription("For more on this error consult the server log.");
-            } else if (throwable instanceof ValidationException) {
```
Comment (mabartos) [inline services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java:105]: Not needed as we have the ValidationExceptionHandler.

**Review by vmuzikar — DISMISSED** [review]
Looks good, thanks @mabartos.

**Comment by mabartos** [comment]
@vmuzikar Thanks! I've just added one small change to fix Quarkus UT tests (embedded).

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 2]
```diff
@@ -860,6 +862,16 @@ private static void disableReadyHealthCheck(BuildProducer<BuildTimeConditionBuil
         removeBeans.produce(new BuildTimeConditionBuildItem(disabledBean.asClass(), false));
     }
 
+    @BuildStep(onlyIfNot = IsTest.class) // needed for embedded Keycloak
```
Comment (vmuzikar) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:865]: @mabartos Could you please share more context why this is needed?

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java [hunk 3]
```diff
@@ -860,6 +862,16 @@ private static void disableReadyHealthCheck(BuildProducer<BuildTimeConditionBuil
...
+    void disableHibernateValidatorCustomizer(BuildProducer<BuildTimeConditionBuildItem> removeBeans, CombinedIndexBuildItem index) {
+        if (!Profile.isFeatureEnabled(Profile.Feature.CLIENT_ADMIN_API_V2)) {
```
Comment (shawkins) [inline quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:867]: Not specific to this pr, but just wanted to highlight that moving forward this type of check is going to get messy. There will be a set of features and versions where hibernate validation might be used.

**Review by shawkins — APPROVED** [review]
LGTM

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java (hunk 3 above)
Comment (mabartos) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:867]: @shawkins Once we adapt the Hibernate Validator keycloak-codebase-wide, we remove all these checks and the Hibernate Validator will be enabled by default. Right now, as it's not needed (only for experimental feature), we should not have it enabled by default as it's causing perf regressions for 26.5.x.

File: quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java (hunk 2 above)
Comment (mabartos) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:865]: For the Quarkus embedded server, we don't have a really nice approach on how to disable specific artifacts. At this moment, we just don't care about the ignored artifacts for the embedded server and we just have them enabled all by default (except for explicit FIPS handling). We could improve it for sure, but not sure if it worth the effort. 

That means that the Hibernate validator is enabled by default for embedded server (as other features), and in order to have it initialized, we need the validator factory customizer that do not include the Expression Language (EL) functionality that needs the expressly dependency (that we don't have in project). It means, that for UT tests, we just say that we don't want the EL. 

It's ok, because integration tests are executed with a distribution server - the officially created distribution that excludes the bean for the validator customizer (this step is executed).

So I think we're safe to do this :) 

@vmuzikar Is it ok to you, or should I explain more?

Comment (vmuzikar) [reply quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java:865]: Thank you, works for me.

**Review by vmuzikar — APPROVED** [review]
