### PR TITLE
Avoid inefficient SQL when deleting a role

### LINKED ISSUE #39237: Deletion of a role is slow when when there are a lot of roles in the database
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When there are a lot of roles in the DB (in this case 400_000), the deletion of a role takes several seconds. 

Due to that, deletion of a realm times out, even if that realm has only very few roles.

### Version

26.2.1

### Regression

- [x] The issue is a regression

### Expected behavior

The deletion should be fast, as all data in the database is indexed.

### Actual behavior

It takes several seconds. 

fetching via a "member of" in JPA with

```
            select role from RoleEntity role where :compositeRole member of role.compositeRoles

```

lead to a query

```
            select re1_0.ID,re1_0.CLIENT,re1_0.CLIENT_REALM_CONSTRAINT,re1_0.CLIENT_ROLE,re1_0.DESCRIPTION,re1_0.NAME,re1_0.REALM_ID from KEYCLOAK_ROLE re1_0 where ? in (select cr1_0.CHILD_ROLE from COMPOSITE_ROLE cr1_0 where re1_0.ID=cr1_0.COMPOSITE)
```

which was awfully slow with 400_000 KEYCLOAK_ROLE entries and 316 entries in COMPOSITE_ROLE on Aurora PostgreSQL 16.6:

```
             Limit  (cost=0.00..903683.68 rows=100000 width=167)
               ->  Seq Scan on keycloak_role re1_0  (cost=0.00..1827365.87 rows=202213 width=167)
                     Filter: (SubPlan 1)
                     SubPlan 1
                       ->  Seq Scan on composite_role cr1_0  (cost=0.00..8.95 rows=6 width=37)
                             Filter: ((re1_0.id)::text = (composite)::text)
``` 

What I actually want is:

```
             select * from KEYCLOAK_ROLE re1_0 where ID in (select cr1_0.CHILD_ROLE from COMPOSITE_ROLE cr1_0 where cr1_0.CHILD_ROLE = '5e0c1a84-2708-4876-b620-cb7a60eddbe8')
```

which is fast:

```
              Nested Loop Semi Join  (cost=0.70..16.74 rows=1 width=167)
               ->  Index Scan using constraint_a on keycloak_role re1_0  (cost=0.42..8.44 rows=1 width=167)
                     Index Cond: ((id)::text = '5e0c1a84-2708-4876-b620-cb7a60eddbe8'::text)
               ->  Index Only Scan using idx_composite_child on composite_role cr1_0  (cost=0.27..8.29 rows=1 width=37)
                     Index Cond: (child_role = '5e0c1a84-2708-4876-b620-cb7a60eddbe8'::text)
```

### How to Reproduce?

Occurred in out nightly performance runs on KCB.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #39237

This is now a lot more efficient as it allows PostgreSQL to use the existing keys

```
select pr1_0.CHILD_ROLE,pr1_1.ID,pr1_1.CLIENT,pr1_1.CLIENT_REALM_CONSTRAINT,pr1_1.CLIENT_ROLE,pr1_1.DESCRIPTION,pr1_1.NAME,pr1_1.REALM_ID 
from COMPOSITE_ROLE pr1_0 join KEYCLOAK_ROLE pr1_1 on pr1_1.ID=pr1_0.COMPOSITE where pr1_0.CHILD_ROLE=?
```

### CODE REVIEW

**Comment by ahus1** [comment]
@mhajas - please at your earliest convenience. Fixing this one should help our nightly performance builds.

It should also be backported to 26.2 / 26.0 in time for the next patch release. Thanks!

File: model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java [hunk 1]
```diff
@@ -99,6 +98,9 @@ public class RoleEntity {
     @JoinTable(name = "COMPOSITE_ROLE", joinColumns = @JoinColumn(name = "COMPOSITE"), inverseJoinColumns = @JoinColumn(name = "CHILD_ROLE"))
     private Set<RoleEntity> compositeRoles;
 
+    @ManyToMany(mappedBy = "compositeRoles", cascade = {})
```
Comment (mhajas) [inline model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java:101]: Should we set `fetch = FetchType.LAZY` to this relationship? We usually don't need to fetch this when using roles.

**Review by mhajas — COMMENTED** [review]
Nice catch @ahus1! I added one comment.

File: model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java (hunk 1 above)
Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java]: At least when debugging it, it seems that it was lazy already that is fetching those items when accessing them. 

Added this in the next commit to enforce it. Thank you for spotting this.

**Comment by ahus1** [comment]
@mhajas - please re-review, changes are in (build is still running)

**Review by mhajas — APPROVED** [review]
Thanks for the addition

File: model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java [hunk 2]
```diff
@@ -99,6 +98,9 @@ public class RoleEntity {
     @JoinTable(name = "COMPOSITE_ROLE", joinColumns = @JoinColumn(name = "COMPOSITE"), inverseJoinColumns = @JoinColumn(name = "CHILD_ROLE"))
     private Set<RoleEntity> compositeRoles;
 
+    @ManyToMany(mappedBy = "compositeRoles", fetch = FetchType.LAZY, cascade = {})
```
Comment (mabartos) [inline model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java:101]: @ahus1 Just out of curiosity - We do not need to update liquibase changelog for ManyToMany relationship, do we?

Comment (ahus1) [reply model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java:101]: @mabartos - this ManyToMany annotation points to the relation above. It is the same table, and the same data (no new data is added). It only adds the necessary Java code to navigate it from child to parent, while the one above allows to navigate from parent to child.

Comment (mabartos) [reply model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java:101]: @ahus1 Ahhh, nice. Thanks for the explanation.
