### PR TITLE
Fix cache option defaults in help

### LINKED ISSUE #22707: `start-dev` by default starts with cache `local`, but docs state otherwise
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

The CLI documentation (and guide) state the default value for `cache` is `ispn`. However, with `start-dev` it seems it is actually using `cache=local` by default:

https://github.com/keycloak/keycloak/blob/e9accaf387471d4baf227cb3a138ffdcc4a8474f/quarkus/runtime/src/main/resources/META-INF/keycloak.conf#L8

### Version

22.0.1

### Expected behavior

Documentation states `local` is used by default in `start-dev`, while `ispn` is the default in `start`.

### Actual behavior

Documentation states default is `ispn` for both

### How to Reproduce?

See https://www.keycloak.org/server/all-config#category-cache

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
We could change the description based on the profile used but this approach would be problematic with the generated docs. So kept it simple for now and added just a text note there.

Closes #22707

### CODE REVIEW

File: quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java [hunk 1]
```diff
@@ -13,7 +13,8 @@ public enum Mechanism {
             .category(OptionCategory.CACHE)
             .description("Defines the cache mechanism for high-availability. "
                     + "By default, a 'ispn' cache is used to create a cluster between multiple server nodes. "
```
Comment (stianst) [inline quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java:15]: A bit lengthy and strange to add the extra `Note` at the end.

I'd suggest something along the lines of:

By default in production mode, a 'ispn' cache is used to create a cluster between multiple server nodes. By default in development mode, a `local` cache disables clustering and is intended for development and testing purposes.

Looking at the docs:

image

It's says `ispn` is the default, but not sure how we can easily change that since there's two different defaults, maybe we just live with it as is for now

Comment (vmuzikar) [reply quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java]: Changed per your suggestion.

> It's says `ispn` is the default, but not sure how we can easily change that since there's two different defaults, maybe we just live with it as is for now

Yeah, doesn't seem simple enough to do. We could probably do it as a follow-up as it concerns more than just cache option.

**Review by stianst — APPROVED** [review]
