### PR TITLE
fixes incorrect JWK thumprint computation

### LINKED ISSUE #38394: JWKSUtils.computeThumbprint(..) broken for ECPublicKeys
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

_No response_

### Describe the bug

The [JWKSUtils.computeThumbprint(..)](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/util/JWKSUtils.java#L153) does not account for [ECPublicJWK](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/jose/jwk/ECPublicJWK.java#L28) keys.

Keys generated or directly parsed as a `ECPublicJWK` will return incorrect thumbprints.

### Version

26.1.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Calculating the thumbprint of a JWK does not depend on the type of its instance.

### Actual behavior

The thumbprint depends on whether the same JWK is a `JWK` or a `ECPublicJWK` were the latter one is incorrect.

### How to Reproduce?

```java
        String keyA = "{" +
                          "   \"kty\": \"EC\"," +
                          "   \"use\": \"sig\"," +
                          "   \"crv\": \"P-384\"," +
                          "   \"kid\": \"key-a\"," +
                          "   \"x\": \"KVZ5h_W0-8fXmUrxmyRpO_9vwwI7urXfyxGdxm1hpEuhPj2hhDxivnb2BhNvtC6O\"," +
                          "   \"y\": \"1J3JVw_zR3uB3biAE7fs3V_4tJy2M1JinzWj9a4je5GSoW6zgGV4bk85OcuyUAhj\"," +
                          "   \"alg\": \"ES384\"" +
                          "  }";

        ECPublicJWK ecPublicKey = JsonSerialization.readValue(keyA, ECPublicJWK.class);
        JWK publicKey = JsonSerialization.readValue(keyA, JWK.class);

        assertEquals(JWKSUtils.computeThumbprint(publicKey), JWKSUtils.computeThumbprint(ecPublicKey));
```

### Anything else?

Pretty sure other subclasses have similar issues.
It would also be worthwile to check if all required members for the thumbprint are present while computing it.
This would prevent similar issues for new subtypes.

### PR DESCRIPTION
**Pull request by thomasrichner-oviva**
Closes #38394

### CODE REVIEW

File: core/src/main/java/org/keycloak/util/JWKSUtils.java [hunk 1]
```diff
@@ -153,6 +154,13 @@ public static String computeThumbprint(JWK key, String hashAlg)  {
             members.put(member, (String) key.getOtherClaims().get(member));
         }
 
+        if(key instanceof ECPublicJWK) {
+            ECPublicJWK ecJwk = (ECPublicJWK) key;
+            members.put(ECPublicJWK.CRV, ecJwk.getCrv());
+            members.put(ECPublicJWK.X, ecJwk.getX());
+            members.put(ECPublicJWK.Y, ecJwk.getY());
+        }
+
```
Comment (rmartinc) [inline core/src/main/java/org/keycloak/util/JWKSUtils.java:163]: @thomasrichner-oviva I prefer to make this more generic, as there are more types of keys that could be affected in the feature. What do you think about doing something like the following?

```java
        Map<String, String> members = new TreeMap<>();
        members.put(JWK.KEY_TYPE, key.getKeyType());

        try {
            JsonNode node = JsonSerialization.writeValueAsNode(key);
            for (String member : JWK_THUMBPRINT_REQUIRED_MEMBERS.get(key.getKeyType())) {
                members.put(member, (String) node.get(member).asText());
            }

            byte[] bytes = JsonSerialization.writeValueAsBytes(members);
            byte[] hash = HashUtils.hash(hashAlg, bytes);
            return Base64Url.encode(hash);
        } catch (IOException ex) {
            return null;
        }
```

The `JsonSerialization.writeValueAsNode` should be something like:

```java
    public static JsonNode writeValueAsNode(Object obj) throws IOException {
        return mapper.valueToTree(obj);
    }
```

Do you see it OK?

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @thomasrichner-oviva for the PR! Yep, you are right the `ECPublicJWK` has the members as properties while the `JWK` saves them in the other claims map. But I prefer to make it more generic for other keys. WDYT about the proposed change?

And one little thing, taking avdantage you are modifying this file, can you fix the RFC in this [line](https://github.com/keycloak/keycloak/blob/26.1.4/core/src/main/java/org/keycloak/util/JWKSUtils.java#L147)? The correct RFC is rfc7638.

Thanks!

File: core/src/main/java/org/keycloak/util/JWKSUtils.java (hunk 1 above)
Comment (thomasrichner-oviva) [reply core/src/main/java/org/keycloak/util/JWKSUtils.java]: Great suggestion! Done :D

**Review by rmartinc — APPROVED** [review]
Thanks @thomasrichner-oviva! LGTM! Let's see if we have not broken anything in the CI. :smile:
@mposolda Please launch the CI for this PR.

**Review by mposolda — APPROVED** [review]
Approving on behalf of @rmartinc .
