### PR TITLE
fix: correctly handle duplicate values in setAttribute()

### LINKED ISSUE #38526: Duplicate user attribute values cannot be removed
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

If a user account has a custom attribute with the same value multiple times, it is not possible to remove some of the duplicate values. However, it is possible to remove **all** the duplicate values together.
In fact it's also not possible to add the same value once more to same attribute.

### Version

26.1.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Via admin console duplicate values of a user attribute can be removed persistently.

### Actual behavior

Removing duplicate values of a user attribute via admin console will actually not be removed from storage when saving.

### How to Reproduce?

1. In admin console create a new custom user attribute with 3 times the value "A"
2. Save -> the attribute will be shown 3 times with value "A"
3. Remove one of the values by clicking on the minus button -> the entry disappears from the UI
4. Save
5. The attribute will be shown shown again 3 times with value "A"

### Anything else?

The Problem is in `org.keycloak.models.jpa.UserAdapter#setAttribute()`. There the new values and old values are compared as ``Set`` and not as ``List``.

```
...
        Set<String> oldEntries = getAttributeStream(name).collect(Collectors.toSet());
        Set<String> newEntries;
        if (values == null) {
            newEntries = new HashSet<>();
        } else {
            newEntries = new HashSet<>(values);
        }
        if (CollectionUtil.collectionEquals(oldEntries, newEntries)) {
            return;
        }
...
```
The same applies to 'infinispan.UserAdapter.
`RoleAdapter` and `GroupAdapter` don't have the same problem. Actually, `GroupAdapter` seems to be the best implementation which should probably be taken over to the other adapters.

### PR DESCRIPTION
**Pull request by dasniko**
When an user attribute holds duplicate values (e.g. ["bar", "bar"]) and the caller reduces the count (e.g. to ["bar"]), the change was silently dropped. Both the infinispan cache adapter and the JPA adapter compared old and new values as Sets, so ["bar", "bar"] and ["bar"] both collapsed to {"bar"} and the equality check returned true, causing an early return without persisting any change.

The infinispan adapter's check is the primary failure point in real deployments: it guards the call to getDelegateForUpdate(), so the JPA layer was never reached at all.

Fix: replace Set-based comparison with List-based comparison in both adapters. CollectionUtil.collectionEquals already counts duplicates correctly when given Lists, so ["bar", "bar"] vs. ["bar"] correctly evaluates to not-equal and the update proceeds.

Includes a regression test that verifies duplicate-value reduction is persisted correctly across transaction boundaries.

closes #38526

🤖 AI disclosure: The analysis of the issue and the proposed changes were done with the help of Claude Code. The implementations, especially the new test method, was done myself. Claude also wrote the commit message.

### CODE REVIEW

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java [hunk 1]
```diff
@@ -215,13 +215,8 @@ public void setAttribute(String name, List<String> values) {
...
         if (updated == null) {
-            Set<String> oldEntries = getAttributeStream(name).collect(Collectors.toSet());
-            Set<String> newEntries;
-            if (values == null) {
-                newEntries = new HashSet<>();
-            } else {
-                newEntries = new HashSet<>(values);
-            }
+            List<String> oldEntries = getAttributeStream(name).collect(Collectors.toList());
+            List<String> newEntries = values == null ? Collections.emptyList() : values;
```
Comment (ryanemerson) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java]: You use `Collections.emptyList()` here, but `List.of()` in the JPA adapter. It would be better to be consistent and make use of `List.of()` here as well.

**Comment by ryanemerson** [comment]
I see there's https://github.com/keycloak/keycloak/pull/41432, which you have contributed to, but it appears to be abandoned. Let's proceed here and we can close that PR once this has been merged.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java (hunk 1 above)
Comment (dasniko) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java]: yes, makes sense, I will fix it.

**Comment by dasniko** [comment]
Yes, #41432 is much more complex and does also not work. So I started a completely new approach. And it turns out that it is quite easy to fix.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java (hunk 1 above)
Comment (dasniko) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java]: done.

**Review by ryanemerson — DISMISSED** [review]
LGTM, thanks @dasniko

**Comment by ahus1** [comment]
Thank you for this PR @dasniko  and thank you for the first review @ryanemerson.

I've reviewed it and found a similar log in the `setSingleAttribute()` method. I've pushed one more change and a test case that accompanies it. 

The database stores the value as a "bag", which is unordered. Unfortunately there is no native Java type for that, so I chose to sort the list and then compare. Please have a look. 

Once one of you has reviewed this change, I'll merge it and prepare the backports.

**Review by ryanemerson — APPROVED** [review]
Thanks for the second pair of eyes @ahus1, good catch!

**Comment by dasniko** [comment]
Thanks @ahus1! LGTM

**Review by ahus1 — APPROVED** [review]

**Comment by ryanemerson** [comment]
Re-running the Store model tests as `UserSessionInitializerTest` passes for me locally.
