### PR TITLE
[Operator] Make UpgradeTest stable

### LINKED ISSUE #37690: [Operator] Test UpgradeTest is unstable
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

The test seems to be unstable, see 

```
Error:    UpgradeTest.testCacheMaxCount:111->assertUnknownUpdateTypeStatus:237 found status KeycloakStatusCondition{type='RecreateUpdateUsed', status=True, message='Unexpected update-compatibility command exit code (137). Check update job for details.'} and expected status null
```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Test should be stable

### Actual behavior

Sometimes it fails

### How to Reproduce?

https://github.com/keycloak/keycloak/actions/runs/13546778519/job/37860558399?pr=37556
https://github.com/keycloak/keycloak/actions/runs/13561805423/job/37906467158?pr=37664

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pruivo**
Fixes #37690

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
LGTM, thank you for implementing an testing this. Not merging this yet to give Steven the chance to review it as well you are listed as a reviewer.

File: operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java [hunk 1]
```diff
@@ -314,6 +314,8 @@ public void afterEach(QuarkusTestMethodContext context) {
           savePodLogs();
           // provide some helpful entries in the main log as well
           logFailedKeycloaks();
+          k8sclient.resources(Keycloak.class).list().getItems()
```
Comment (shawkins) [inline operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java:317]: logFailedKeycloaks could just become logKeycloaks to handle this.

**Review by shawkins — APPROVED** [review]
Looks good. Just one small change could be made to the additional logging.

Also has an issue been logged on the performance degredation for the Operator local / remote runs? We'll need to get them back to 30 minutes.

**Comment by ahus1** [comment]
I'm merging this one based on Steven's approval. I assume the comment about the logging could be added to the follow-up issue about the performance of the test. I would like to have this test activated again so that it runs on the other enhancements about the upgrade feature. 

I looked at the logs, I see that takes currently ~7 miutes to complete the 7 tests. 

> [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 425.982 s - in org.keycloak.operator.testsuite.integration.UpgradeTest

While the current tests are 43 min and 49 min, optimizing this test won't bring the overall time below 30 minutes.

**Comment by shawkins** [comment]
> I'm merging this one based on Steven's approval. I assume the comment about the logging could be added to the follow-up issue about the performance of the test. I would like to have this test activated again so that it runs on the other enhancements about the upgrade feature.
> 
> I looked at the logs, I see that takes currently ~7 miutes to complete the 7 tests.
> 
> > [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 425.982 s - in org.keycloak.operator.testsuite.integration.UpgradeTest
> 
> While the current tests are 43 min and 49 min, optimizing this test won't bring the overall time below 30 minutes.

I brought this up because I recalled @stianst mentioning the operator test runtimes creeping up, but hadn't looked deeply at it. 

Looking at the last couple of runs on 26.1 I see roughly 40 minutes for local and 43 minutes for remote. 

It is correct that we weren't at 30 before, but my understanding is that is the goal which motivated the splitting of the quarkus integration tests. Captured #37853 so we can follow up on this.
