### PR TITLE
Do not return empty scope field in token introspection response

### LINKED ISSUE #16526: Token introspection response does not follow RFC6479 "scope" parameter format
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Currently, the introspection response include a scope parameter even if no scope is granted. It will be empty, e.g. `"scope": ""`.

Token introspection spec in [RFC6479 section 3.3](https://www.rfc-editor.org/rfc/rfc6749#section-3.3) specifies the format of this field is:

     scope       = scope-token *( SP scope-token )
     scope-token = 1*( %x21 / %x23-5B / %x5D-7E )

My understanding is that means "at least one scope-token" and scope-token must include "at least one character" (in those ranges).

### Version

20.0.3

### Expected behavior

If no scope is granted, then the "scope" field should not be present.

### Actual behavior

An empty value of `"scope": ""` is included.

### How to Reproduce?

Request a grant with no scopes, and call the token introspection endpoint.

### Anything else?

This behavior is the same as in access tokens per #16523 , however I consider that a separate issue because Keycloak defines its own format of JWTs for access tokens, and this is not specified by OAuth. So  16523 is more of a "nice to have" to be consistent with token introspection (as well as RFC9068).

This can be worked around by requesting at least one scope.

### PR DESCRIPTION
**Pull request by Mobe91**
Closes #16526

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java [hunk 1]
```diff
@@ -322,7 +349,26 @@ public void testIntrospectAccessToken() throws Exception {
         AbstractOIDCScopeTest.assertScopes("openid email profile", rep.getScope());
     }
 
+    @Test
+    public void testIntrospectAccessTokenWithoutScope() throws Exception {
+        oauth.realm("realmWithoutScopes").clientId("no-scope").openid(false).doLogin("test-user@localhost", "password");
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java:354]: Just a small detail, but is it possible to avoid creation of new realm, but instead just update existing "test" realm and possibly create some new client without scopes in it (and then cleanup this client afterwards etc)? Creation of new realm has some overhead and makes a test a bit longer to execute than necessary.

**Review by mposolda — COMMENTED** [review]
@Mobe91 Thanks for the PR! Added only one small detail regarding test.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java (hunk 1 above)
Comment (Mobe91) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java:354]: I actually asked about this in the [Keycloak Slack channel](https://cloud-native.slack.com/archives/C056HC17KK9/p1696537271544279) and the answer was that creating a new realm is the simplest approach.

The problem is that if I apply this modification before importing the test realm it would apply to all tests and this would fail other tests (I tried this). So I would have to somehow conditionally apply this modification for only this test case or extract this one testcase into a new test class. Not so nice I think...

Alternatively, I could try to update the already imported realm as part of the test case using the adminClient - I have not explored this option yet. Is this what you mean?

Comment (mposolda) [reply testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java:354]: Yes, exactly. That is what I meant. The ideal is, that if some test needs something, it can be set at the beginning of the test method and then reverted at the end (to not affect other test methods, which rely on the "default" behaviour). We use this approach on many places. For instance this method: https://github.com/keycloak/keycloak/blob/22.0.4/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java#L181-L202

This is usually sufficient and more effective than always creating new realm, which is a bit time consuming.

**Review by mposolda — APPROVED** [review]
@Mobe91 Thanks!
