### PR TITLE
use id instead of name

### LINKED ISSUE #20694: Selecting one mapper and switch page select them all
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

If you select a client dedictated scope setting and try to select one new mapper "From predefined mappers" and do a page-click in this mappers-view the result is that all predefined mappers get selected.

### Version

21.1.1

### Expected behavior

Only the selected mapper get's selected after page change

### Actual behavior

All mappers get's selected after page change

### How to Reproduce?

Select a client, go to client scope, the client-dedictated and then add a predefined mapper, do a page-click in the mapper view.
capture_005_31052023_154554
capture_006_31052023_154603
capture_007_31052023_154611

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #20694

### CODE REVIEW

File: js/apps/admin-ui/src/client-scopes/add/MapperDialog.tsx [hunk 1]
```diff
@@ -61,7 +61,7 @@ export const AddMapperDialog = (props: AddMapperDialogProps) => {
         )[0];
         return {
           item: mapper,
-          name: mapper.name!,
+          id: mapper.name!,
```
Comment (jonkoops) [inline js/apps/admin-ui/src/client-scopes/add/MapperDialog.tsx:64]: Should this not also be `mapper.id`?

**Review by jonkoops — APPROVED** [review]

File: js/apps/admin-ui/src/client-scopes/add/MapperDialog.tsx (hunk 1 above)
Comment (edewit) [reply js/apps/admin-ui/src/client-scopes/add/MapperDialog.tsx:64]: no
