### PR TITLE
Fix SSSDTest

### LINKED ISSUE #19397: Fix SSSDTest
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

SSSDTest wasn't updated when AccountPasswordPage was removed and doesn't currently compile.

### Version

21.0.1

### Expected behavior

SSSDTest should compile

### Actual behavior

SSSDTest does not compile

### How to Reproduce?

mvn test -DskipTests -f testsuite/integration-arquillian/tests/other/sssd/pom.xml

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by douglaspalmer**
closes #19397

### CODE REVIEW

File: testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/SSSDTest.java [hunk 1]
```diff
@@ -10,11 +10,7 @@
 import org.apache.commons.configuration.PropertiesConfiguration;
 import org.jboss.arquillian.graphene.page.Page;
 import org.jboss.logging.Logger;
-import org.junit.Assume;
-import org.junit.Before;
-import org.junit.BeforeClass;
-import org.junit.Rule;
-import org.junit.Test;
+import org.junit.*;
```
Comment (mposolda) [inline testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/SSSDTest.java:13]: A small detail: Can you remove star imports (and update your IDE to avoid using star imports and star static imports?)

AFAIK we discussed this in the team a long time ago to avoid star imports (although I think it is not formally documented anywhere)

**Review by mposolda — CHANGES_REQUESTED** [review]
@douglaspalmer LGTM, just one minor comment inline regarding imports

**Review by mposolda — APPROVED** [review]
