### PR TITLE
[OID4VCI] QR Code Unbounded Dimensions DoS

### LINKED ISSUE #48044: OID4VC QR Code Unbounded Dimensions DoS
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

File: OID4VCIssuerEndpoint.java lines 435-436, 536-539
 
width and height query parameters have no upper bound:

``` 
    @QueryParam("width") https://github.com/DefaultValue("200") int width,
    @QueryParam("height") https://github.com/DefaultValue("200") int height
``` 
 

### Acknowledgement

This was shared with the Keycloak security team by @Medoedus. This is handled as a public issue as this OID4VC is still an experimental feature.

### Version

26.6

### Regression

- [ ] The issue is a regression

### Expected behavior

System should not OOM / should validate the parameters

### Actual behavior

Passed directly to ZXing QRCodeWriter which allocates BitMatrix of width*height bits. Request with width=50000&height=50000 allocates ~2.5GB.

### How to Reproduce?

 Reachability: `GET /realms/{realm}/protocol/oid4vc/create-credential-offer?type=qr&width=50000&height=50000` with valid bearer token.

### Anything else?

Fix: Add MAX_QR_DIMENSION constant (e.g. 2000) and validate before generation.

### PR DESCRIPTION
**Pull request by tdiesler**
closes #48044

allowing 800x800 max

### CODE REVIEW

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java [hunk 1]
```diff
@@ -463,6 +463,17 @@ public Response createCredentialOffer(
                     ErrorType.INVALID_CREDENTIAL_OFFER_REQUEST.getValue(), errorMessage, Response.Status.BAD_REQUEST);
         }
 
+        // Verify image dimensions
+        //
+        if (List.of(OfferResponseType.QR, OfferResponseType.URI_QR).contains(responseType)) {
+            if (width > 800 || height > 800) {
+                var errorMessage = "Requested QR Code too large, allowed maximum is 800x800";
```
Comment (utafrali) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java]: The literal `800` appears both in the condition (`width > 800 || height > 800`) and inside the error string (`"allowed maximum is 800x800"`). If the limit is adjusted later, one of the two will silently fall out of sync. Extract a named constant:

```java
private static final int MAX_QR_DIMENSION = 800;
```

Then reference `MAX_QR_DIMENSION` in both the guard and the message.

Comment (utafrali) [inline services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java]: The check only rejects values above the maximum, but `width=0`, `height=0`, or negative values will pass the guard and likely trigger an unhandled exception inside the QR generation library, surfacing as a 500 error. For a security-motivated validation, the lower bound should be explicit:

```java
if (width < 1 || height < 1 || width > MAX_QR_DIMENSION || height > MAX_QR_DIMENSION) {
    var errorMessage = "Requested QR Code dimensions must be between 1 and " + MAX_QR_DIMENSION;
    ...
}
```

File: tests/base/src/test/java/org/keycloak/tests/oid4vc/OID4VCredentialOfferAuthCodeTest.java [hunk 2]
```diff
@@ -252,6 +254,34 @@ public void testAuthCodeOffer_Targeted() throws Exception {
...
+    }
+
+    @Test
+    public void testAuthCodeOffer_QRCode_InvalidDimensions() {
+
+        var ctx = new OID4VCTestContext(client, jwtTypeCredentialScope);
+
+        var ex = assertThrows(IllegalStateException.class, () -> wallet.createCredentialOffer(ctx, req -> {
+            req.responseType(OfferResponseType.URI_QR);
+            req.width(1000).height(1000);
```
Comment (utafrali) [inline tests/base/src/test/java/org/keycloak/tests/oid4vc/OID4VCredentialOfferAuthCodeTest.java:298]: The test asserts an `IllegalStateException` and then string-matches its message. This couples the assertion to the internal wrapping behavior of the HTTP test client rather than the actual HTTP contract (status 400, error body). If the client changes how it wraps 4xx responses, the test could fail for unrelated reasons, or a different 4xx could silently satisfy the check. Consider asserting the HTTP status code and the structured error response body directly, which is how most other Keycloak endpoint error tests are written.

**Review by utafrali — COMMENTED** [review]
The fix correctly closes the DoS vector by capping QR dimensions, but the maximum value (800) is hardcoded in two places that can drift apart, there is no lower-bound check for zero or negative dimensions that would reach the QR library as unhandled exceptions, and the error-path test verifies exception message text rather than HTTP status and response body.

**Comment by ahus1** [comment]
@utafrali - I see you added a review only shortly after the PR was created. This leaves me to suspect that you had AI to help in creating the review. If this is the case, I wonder if you would want to share mechanisms of automating pull requests reviews with the Keycloak team. If the review was done manually, then I apologize for my suspicion.

File: tests/base/src/test/java/org/keycloak/tests/oid4vc/OID4VCredentialOfferAuthCodeTest.java (hunk 2 above)
Comment (tdiesler) [reply tests/base/src/test/java/org/keycloak/tests/oid4vc/OID4VCredentialOfferAuthCodeTest.java:298]: Like this ... ?

```
        CredentialOfferUriResponse res = wallet.createCredentialOfferUri(ctx, req -> {
            req.responseType(OfferResponseType.URI_QR);
            req.width(1000).height(1000);
        });
        String errorDescription = res.getErrorDescription();
        assertEquals(HttpStatus.SC_BAD_REQUEST, res.getStatusCode());
        assertNotNull(errorDescription, "No ErrorDescription");
        assertTrue(errorDescription.contains("Requested QR Code too large, allowed maximum is 800x800"), errorDescription);
```

File: services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java (hunk 1 above)
Comment (tdiesler) [reply services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java]: done

Comment (tdiesler) [reply services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java]: done

**Review by mposolda — APPROVED** [review]
@tdiesler Thanks!
@utafrali Thanks for the review!
