### PR TITLE
Quarkus props at runtime

### LINKED ISSUE #10968: Usage of raw quarkus runtime properties without a build
### Description

At the moment, all quarkus properties are handled as "build" options in keycloak. This leads to a few corner cases:

1) Quarkus has capabilities we don't wrap / maintain (e.g. using syslog logging). In this case, e.g. a syslog server property is environment dependant (think: dev/stage/prod/whatever). At the moment this would always require a rebuild, though the actual quarkus property is a runtime property. 

2) Same applies for the runtime datasource properties for additional datasources, as we use (or will use) e.g. [here](https://github.com/keycloak/keycloak-quickstarts/pull/302):  JDBC-URL, Username, Password are runtime properties in quarkus, so we want to have them runtime config in keycloak, too.

This issue should provide the following capabilities:
- when a quarkus property is a runtime property, _but not included in our configuration_, it should still be handled as if it is a runtime configuration, so without a rebuild needed. (e.g. syslog properties)
- when a quarkus property is a buildtime property, _but not included in our configuration_, a build has to be run before starting keycloak for the build property to apply. If no build is done beforehand, the standard quarkus build/runtime mismatch warning is shown. (e.g. `quarkus.hibernate.metrics-enabled` at the time of writing is not used by us but available as buildtime property in quarkus)
- Auto-build would not trigger a build automatically on quarkus build properties _not used in keycloak_, because at the time of writing there is no possibility for us to check the general quarkus config if a property there is build- or runtime. (auto-build is a concept that is keycloak-specific, and does not exist in quarkus). I raised [this discussion in quarkus](https://github.com/quarkusio/quarkus/discussions/24555 ) for this issue, so it may be changed in quarkus in the future.
- an exception for auto-build compatibility is made for raw quarkus buildtime properties we use for the new UserStorageProvider implementation to add additional datasources (see [here](https://github.com/keycloak/keycloak-quickstarts/pull/302)), namely `quarkus.datasource.<pattern>.db-kind`, `quarkus.jdbc.<pattern>.jdbc.driver`, `quarkus.jdbc.<pattern>.jdbc.transactions`, `quarkus.jdbc.<pattern>.jdbc.enable-metrics` (comp. https://quarkus.io/guides/datasource#jdbc-configuration ). When these properties are available in the `quarkus.properties` file, a build is automatically triggered by our ruleengine. For all other properties, point 2 applies and the standard quarkus warning for the mismatch is shown. The environment-dependant runtime properties for additional datasources like `jdbc-url`, `db-username`, `db-password` etc. would not require a build.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by DGuhr**
Closes #10968

### CODE REVIEW

**Comment by DGuhr** [comment]
Opened as draft, as it's not quite discussed if we really want to make the exception or jump back to "as it was in the past", so just let people use quarkus properties as build/runtime properties, and auto-build would not work for all of them. Would reduce the amount of added code for sure. 

cc @pedroigor @stianst let's talk about this when you have the time.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 1]
```diff
@@ -269,9 +274,65 @@ private static boolean hasConfigChanges() {
             }
         }
 
+        //check for defined quarkus raw build properties for UserStorageProvider extensions
+        if (QuarkusPropertiesConfigSource.getConfigurationFile() != null) {
```
Comment (pedroigor) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:278]: IMO, we should not worry about dealing with this situation at this momment.

As we discussed, ideally we should be able to query Quarkus if a property is a build time property. 

Including here a whitelist of build properties deserves a bit more discussion because. For instance, the possibility to add data sources is a capability we should support in order to deploy custom user providers. In this case, we should think about wrapping the data source config.

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/util/SetKeepAliveTrueForTest.java [hunk 2]
```diff
@@ -0,0 +1,13 @@
+package org.keycloak.it.cli.dist.util;
+
+import org.keycloak.it.utils.KeycloakDistribution;
+
+import java.util.function.Consumer;
+
+public class SetKeepAliveTrueForTest implements Consumer<KeycloakDistribution> {
```
Comment (pedroigor) [inline quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/util/SetKeepAliveTrueForTest.java:7]: Isn't better to create a `@KeepServerAlive` annotation?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 1 above)
Comment (DGuhr) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:278]: I have to disagree. I still think the behaviour we have here with the whitelist is better for testing purposes _for now_, as long as we don't have first-class configuration options. 

First-class options would open up the "dependant options" space again, so not trivial. "Only allow/show options when the named additional datasource is there" is something we can't do as of now. A possible starting point to look at: we could have e.g. a build option `db-external-names=foo,bar,...` and only show and map the right way options like e.g. `kc-db-foo=mysql`, `kc-db-bar=postgres" and so on... so this is not trivial to achieve imo. at least not if we want to support the CLI with these and not have a ux issue on that matter. And for me definitely nothing for this ticket.

So, without first class support, I consider a dev who runs start --auto-build often to try things out before creating an optimized image for prod (and this is done often it seems from various other issues). 

The devex while doing this without the whitelist would be "start it, run the build bc. it detects quarkus.properties everytime even if only the username / url changed for the external datasource" and thus not good IMO. So at least until we support first class config for additional datasources, i think the whitelist approach is **good for now** and I am happy to change it when we either 

a) get sth from quarkus to check more fine-grained for build/runtime, or 
b) have first class support for additional datasources config on our side. 

Both approaches are some time down the road i guess, and it's not that hard to change the impl later on, so as a stop-gap solution I'd prefer keeping it that way.

Comment (DGuhr) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:278]: would be nice to get a third opinion, as ours seem to not go together here ;) cc @vmuzikar @andreaTP @stianst

Comment (pedroigor) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:278]: I'm not hard on that if others are OK. Looks like the extension story keeps knocking on the door :)

If we can avoid temporary code, better.

Comment (andreaTP) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:278]: We discussed about a possible more generic and structural fix that might come in a future iteration.

For the time being this already enables some use-cases and improve the code-base, I'm happy to go with it!

File: quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/util/SetKeepAliveTrueForTest.java (hunk 2 above)
Comment (DGuhr) [reply quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/util/SetKeepAliveTrueForTest.java]: done

**Comment by DGuhr** [comment]
rebased and squashed commits, added @KeepServerAlive annotation to testsuite based on the PR discussions. Put out of draft state.

**Comment by pedroigor** [comment]
@DGuhr Does it make sense to set `quarkus.configuration.build-time-mismatch-at-runtime=fail` when using quarkus properties?

**Review by pedroigor — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]
