### PR TITLE
Validate single quotes in themes

### LINKED ISSUE #37930: Inconsistent use of single quotes in message resources
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

In several places (especially in the login theme and the email themes, everywhere there are Freemarker templates, Keycloak uses Java MessageFormat. 

This will remove single quotes, and treat everything within single quotes as escaped. 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

We shouldn't use single quotes in the message resources, only double quotes. 

### Actual behavior

Single quotes disappear, pleaceholders are escaped.

### How to Reproduce?

Try out MessageFormat

### Anything else?

I'll provide a pull request.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #37930

### CODE REVIEW

**Comment by ahus1** [comment]
@jonkoops: can you please comment on my change in the frontend that would prevent showing double quotes?

Thanks!

cc: @robson90

File: js/apps/account-ui/src/i18n.ts
Comment (jonkoops) [inline js/apps/account-ui/src/i18n.ts:1]: I think rather than solving this here on the front-end the API should normalize these values. This will avoid other consumers from having to do the same.

Comment (ahus1) [reply js/apps/account-ui/src/i18n.ts:1]: I was thinking the same first, but then wasn't sure if someone might want to use the original Java Messageformat to do a replacement. WDYT - should I still do it only in the backend?

Comment (jonkoops) [reply js/apps/account-ui/src/i18n.ts:1]: My vote is to do it on the backend. Unless I am somehow misunderstanding the formatting here. What is the purpose of the double `''`? I thought it was properties file specific trait, and not related to MessageFormat.

Comment (ahus1) [reply js/apps/account-ui/src/i18n.ts:1]: The `''` is related to MessageFormat only, that is when you have placeholders in the string. Not all strings in the property file are then processed by a MessageFormat. 

The logic of MessageFormat in a nutshell: If you want to escape a something that would normally be a placeholder, put it in single quotes. It will then be printed without the single quotes. If you then want to print one single quote, have two single quotes in the original string. 

I assume no-one is consume this strings except the original admin UI and account UI, so it doesn't really matter. I'll move it to the backend in the next commit.

Comment (jonkoops) [reply js/apps/account-ui/src/i18n.ts:1]: Yeah, sounds like it can be handled in the API then. At some point we should really look to unify these messages. There is a standard [MessageFormat API proposal](https://github.com/tc39/proposal-intl-messageformat) in the works for JavaScript that will implement the [MessageFormat 2 standard](https://messageformat.dev/).

**Comment by ahus1** [comment]
@jonkoops - I gave it a thought to convert the message resources on the backend, but then it would affect all resource themes, not only those used in the React UI. 

So I chose to update the docs that in Admin/Account UI theme you MUST NOT use `''`, while you MUST use `''` in the base themes. 

WDYT? I think it is a step in the right direction, but there is a lot more to clean up around translations...

File: misc/theme-verifier/src/test/resources/doubleSingleQuotes_en.properties [hunk 1]
```diff
@@ -0,0 +1,17 @@
+#
```
Comment (jonkoops) [inline misc/theme-verifier/src/test/resources/doubleSingleQuotes_en.properties:1]: As per the mailing list, we no longer need to include copyright notices in every file.

**Review by jonkoops — DISMISSED** [review]
I agree with the approach of using the MessageFormat syntax only for the Java related messages and adding some instructions. Long-term, we need to reach an agreement on a unified format for translations.

**Comment by ahus1** [comment]
Thank you for the approval of this next step in the journey. There are some conflicts that I need to resolve. As this one is touching a lot of files, I've now locked the Weblate translations. Once the last Weblate changes are merged, I'll rebase this one.

Once this PR is merged, I'll unlock Weblate.

**Review by jonkoops — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Comment by ahus1** [comment]
@jmallach / @Ecron / @EdoardoTona / @GioviQ:

With this change in place, you now need to check where you add quotes: While typographic quotes are preferred, it is `'` in the Admin UI and Account UI, and `''` in the basic themes. Let me know if you have questions around that. 
I hope we can in the future have a more aligned process around that.

**Comment by jmallach** [comment]
Thanks for this specific clarification: people were saying all around that '' was always needed, but it was clearly not the case.

We should try to search&replace all apostrophe's in our Catalan translations to use ‘ instead, and use ' only where it is really needed.

**Comment by ahus1** [comment]
@jmallach - we are learning and are untangling this bit by bit. Sometimes we might take a detour, or correct previous assumptions. We try to keep the `translation.md` file up-to-date as we go.

To do the search-and-replace, you can choose to create a pull request for the files if you don't want to use the UI for that.
