### PR TITLE
Prevent stampede after realm cache invalidation

### LINKED ISSUE #22988: Cache stampede after realm cache invalidation
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

### Describe the bug

Any code paths that include `RealmAdapter.getRealmForUpdate()` thus invalidate the cache for a given Realm.

https://github.com/keycloak/keycloak/blob/6830735ed9692a275208183e14c7af32c661826c/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java#L55

Subsequent to this, any threads servicing a request that needs to read through the realm cache and identify it is empty/invalidated will try to populate it from the database.  Under request load, this means multiple threads will concurrently try to read from the database to populate the same in-memory cache.  This creates unnecessary database load and has negative performance implications (e.g., excessive object creation/heap consumption/garbage collection).

### Version

19.0.3

### Expected behavior

Ideally, realm invalidation would be more surgical.  For example, during a DELETE scope operation just the deleted scope should be invalidated from the in-memory cache instead of the entire realm.  This is likely a significant design change and implementation effort.

Alternatively, I think it would be acceptable to implement a locking mechanism such that only 1 thread can populate the realm cache after invalidation event.  This solution is much less invasive to implement and _roughly_ follows the pattern in used https://github.com/keycloak/keycloak/pull/21522 .  I have drafted an implementation of this and will open a pull request shortly.

### Actual behavior

Following realm cache invalidation, any thread servicing a request that tries to read through the realm cache will try to populate the realm cache from database.  Under load, this means several threads will concurrently try to do the same work and increase load on the DB and application.

### How to Reproduce?

1. Bring up keycloak with a realm
2. Make sure realm is populated with some clients and some scopes.  Larger numbers of clients and scopes (or other realm objects for that matter) will exacerbate the problem, but any number will do.
3. Put keycloak under request load (I used 5 threads in JMeter - any concurrent load is sufficient)
4. Delete a scope
5. Observe that `RealmCacheSession.getRealmByName(String name)` is called multiple times concurrently 
 https://github.com/keycloak/keycloak/blob/6830735ed9692a275208183e14c7af32c661826c/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java#L460

### Anything else?

I will open a pull request with a fix proposal shortly.

### PR DESCRIPTION
**Pull request by JesseEstum**
Closes #22988

### CODE REVIEW

**Comment by sschu** [comment]
@JesseEstum Thanks for the PR! Wasn't this already solved with the PR from @ahus1 (https://github.com/keycloak/keycloak/pull/21522)?

**Comment by JesseEstum** [comment]
> @JesseEstum Thanks for the PR! Wasn't this already solved with the PR from @ahus1 (#21522)?

@sschu I had hoped so, but no - @ahus1 (#21522) did not quite do it.

Some evidence to support my claim:

(A) Here is a graph of a test run without my PR and without #21522.  You can see a certain base level of activity because I'm pounding the token endpoint with requests via JMeter.  The two huge spikes are when I run 10 iterations of separate test battery calling administrative endpoints that cause realm cache invalidation.  **Note the two huge spikes go up to ~110k and ~85k**
image

(B) Here is a graph of a test run without my PR but with #21522.  Again, you see the same base level of activity with some large spikes.  The three large spikes are when I run 10 iterations of the same test battery calling administrative endpoints that cause realm cache invalidation.  **Note the three huge spikes go up to ~56k, ~60k, and ~60k**
image

(C) And this is a test run with my PR but without #21522.  **Note the large spikes reach ~45k and ~45k.**
image

**Comment by JesseEstum** [comment]
Also, for what it's worth, I've done some analysis on the lock acquisition time.  It's typically quite low with a median somewhere around ~225 nanoseconds.  Note that we'd expect a longer lock acquisition time for cases where a thread is repopulating the in-memory cache from DB.  Also please carefully note on the X axis that my bucketing size is bracketed/progressively larger.

image

**Comment by sschu** [comment]
@ahus1 Since you worked in that area, can you maybe have a look?

**Comment by ahus1** [comment]
@JesseEstum - thank you for suggesting this change. I updated it a bit to be more in line with the previous change. While it is a bit more complex, the code is now aligned with the two ways to retrieve a realm. Also loading a realm by name doesn't block any other requests on other realms. 

I tested it manually by starting Keycloak, creating a new realm `test` and then renaming it. When testing this locally, this loaded the realm once, and then two other concurrent requests picked up the change from the cache. 

Please give it a try and see if it works for you. Note that once this is solved, there is another cache stampede on the clients of the as well - but let's keep that for another PR once we are sure this works as expected.

**Comment by JesseEstum** [comment]
> @JesseEstum - I can't go into too much details as I don't know about your test setup, and I'm afraid it would go beyondthe time I have available to devote to this PR.

Fair.  I've spent way more time on this than I care to admit so I know where you're coming from.

> If you suspect a bug, consider creating a thread dump when about to fetch something from the database. Those thread dump should show what the other threads of the Keycloak instance are currently doing.

Capturing the thread dump at the right time will be difficult if not impossible.

> Talking about PostgreSQL DB connections, I recommend to have initial DB connection = max DB connections, as creating a new DB connection is expensive, as it needs to warm up with (server side) prepared statements before it is efficient.

I'm also not a fan of elastically sized DB connection pools.  My min and max DB connections value are already set equal and  I have good telemetry to confirm I'm nowhere near DB connection pool exhaustion.

@ahus1 I believe I've found the bug with your additional commit and the concurrency approach in general.  Will comment on that separately.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java [hunk 1]
```diff
@@ -459,25 +459,32 @@ public KeycloakSession getKeycloakSession() {
     @Override
     public RealmModel getRealmByName(String name) {
         String cacheKey = getRealmByNameCacheKey(name);
+        if (invalidations.contains(cacheKey)) {
+            return getRealmDelegate().getRealmByName(name);
+        }
```
Comment (JesseEstum) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java:464]: @ahus1 here we will have multiple threads pounding the database, even before we get to the `synchronized` part.

Suppose the following conditions:
1. Realm `myRealm` has just been invalidated and thus `invalidations.contains(cacheKey)` is `true`

Now suppose _n_ threads service requests that come in at the same time.
This means line 462 will be evaluated _n_ times to `true` concurrently.  Subsequently line 463 will be invoked _n_ times concurrently.  

`getRealmDelegate().getRealmByName(name)` on 463 will invoke DB I/O.  This will be done _n_ times concurrently and thus cause the stampede phenomena.

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java:464]: @JesseEstum - some background on `KeycloakSession`: It captures the transaction context of a single request, and starts together with the request and ends when the request ends. It can be nested to support nested transactions, but most of the time it is not. 

The `RealmCacheSession` is instantiated during a request and bound to an instance of `KeycloakSession`, so it has the same lifetime (usually even shorter). 

The  attributes `invalidations` and `listInvalidations` are attributes local to `RealmCacheSession`, and only contain information from the current request. Once there are local changes to a realm, they are filled with the invalidations which will be published once the current request completes. 

Due to this, there can't be a cache stampede due to them, as there are no concurrent requests on them.

**Comment by ahus1** [comment]
@JesseEstum - I've been looking at the diagrams, and the colored spikes are named: 

* client_scope
* client_scope_attributes
* protocol_mapper
* protocol_mapper_config

So I assume those show the amount of SQL selects you see for those tables.

Those selects are called AFAIK by `getClientById()`, `getClientScopeById()`, `getClientByClientId()` and `getClientScopes()` in the `RealmCacheSession` and those are not yet protected from the cache stampede, and I'd classify this as a known issue. 

The anomaly where you see lower activity is IMHO only a timing issue, and my latest changes wouldn't have cause that. 

I assume we have at least two ways to proceed here: 

* Verify that this PR is good to be merged as it covers realms, and tackle client related cache stampede in another PR

* Identify which of the `getClient*()` methods is called in your setup and add the cache stampede protection for that one(s) as part of this PR. Eventually all need that protection, but we might start with some. The methods needing protection possibly depend on the kind of changes you do to the realm, and the kind of activities you are performing.

Please let me know how you want to proceed.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java (hunk 1 above)
Comment (JesseEstum) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java:464]: @ahus1 Thanks for the background/context.  I am admittedly not familiar with the overall request/response and object model in Keycloack so this is useful to understand.  With this understanding now in hand, I agree my [previous comment](https://github.com/keycloak/keycloak/pull/22989#discussion_r1322018201) is not correct.

**Comment by ahus1** [comment]
@pedroigor - I wonder if you could review this PR if it can be merged as is, and clients could be handled in a follow-up PR. Thanks!

**Comment by ahus1** [comment]
Thank you @JesseEstum for re-testing this. I appreciate the time and effort you're putting into this.

I'll wait for another review from either @pedroigor or another Keycloak team member before merging it.

**Comment by ahus1** [comment]
@sguilhen - maybe you have the time instead to have a look? Thanks!

**Review by sguilhen — APPROVED** [review]
Thanks @JesseEstum and @ahus1 . This is IMO  aligned with the solution we already have in place for `getRealm(String id)`, so +1 from me.

I'd only raise an issue (if one doesn't exist yet) to track the client issues that require the same solution.

**Comment by ahus1** [comment]
Thank you @sguilhen - follow-up issue created: #24202

**Review by ahus1 — APPROVED** [review]
Approving as of @sguilhen's review.

**Comment by ahus1** [comment]
@JesseEstum - thank you for the code, the tests, and the patience to get this ready to be merged. This will be part of the KC23 release.
