### PR TITLE
join title and expand section together

### LINKED ISSUE #20329: Additional Provider Info only shows at end of list not below provider
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When opening the Provider info page, `Operationalnfo` provided by `ServerInfoAwareProviderFactory` implementations is not shown near the provider but at the end of the list.

image

### Version

21.1.1

### Expected behavior

As with the old admin console, provider specific infomation should be displayed right below the provider.

### Actual behavior

Provider specific infomation is displayed at the end of the list.

### How to Reproduce?

Check with the `connectionsJpa` provider `legacy` or install the [Home IdP Discovery extension](https://github.com/sventorben/keycloak-home-idp-discovery) and open the provider info page.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #20329

### CODE REVIEW

File: js/apps/admin-ui/src/dashboard/ProviderInfo.tsx [hunk 1]
```diff
@@ -56,37 +55,39 @@ export const ProviderInfo = () => {
...
                 <Td>
                   <ul>
-                    {Object.entries(providers).map(([key]) => (
-                      <li key={key}>{key}</li>
-                    ))}
+                    {Object.entries(providers).map(
+                      ([key, { operationalInfo }]) => (
+                        <>
+                          <li key={key}>{key}</li>
+                          {operationalInfo ? (
```
Comment (jonkoops) [inline js/apps/admin-ui/src/dashboard/ProviderInfo.tsx:62]: Semantically a `ul` is only allowed to have `li` as children, no other elements are allowed.

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by jonkoops — APPROVED** [review]
