### PR TITLE
"Allowed Protocol Mapper Types" prevents clients from self-updating via client registration api

### LINKED ISSUE #27558: Client registration policy "Allowed Protocol Mapper Types" prevents clients from self-updating via the client registration api
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

`Allowed Protocol Mapper Types` fails client self-update when the client tries to push an already assigned protocol mapper having a non whitelisted type.

`Allowed Protocol Mapper Types` should be smarter and only deny *addition* of non whitelisted protocol mapper type. Already assigned protocol mappers should be allowed even if they are not part of the whitelist.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Performing `PUT /realms/master/clients-registrations/default/foo` with the exact same representation retrieved from `GET /realms/master/clients-registrations/default/foo` should succeed.

### Actual behavior

`PUT /realms/master/clients-registrations/default/foo` fails with an http status 403 and response body `{"error":"insufficient_scope","error_description":"Policy 'Allowed Protocol Mapper Types' rejected request to client-registration service. Details: ProtocolMapper type not allowed"}`.

Looking at the Keycloak log, we can see that `Allowed Protocol Mapper Types` rejected protocol mapper `Client Host` because its type `oidc-usersessionmodel-note-mapper` is not whitelisted.

### How to Reproduce?

1. Create an OIDC client with `Client authentication` enabled, `Service account` enabled and client id `foo`
1. Notice that the client `dedicated` scope has at least the following protocol mappers of type `oidc-usersessionmodel-note-mapper`: `Client IP Address`, `Client Host` and `Client ID`
1. Generate a registration access token for this client
1. Using the registration access token, update the client *without any modification* . Submit the response body of `GET /realms/master/clients-registrations/default/foo` to `PUT /realms/master/clients-registrations/default/foo`.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix #27558

### CODE REVIEW

File: services/src/main/java/org/keycloak/services/clientregistration/policy/impl/ProtocolMappersClientRegistrationPolicy.java [hunk 1]
```diff
@@ -48,27 +51,51 @@ public ProtocolMappersClientRegistrationPolicy(KeycloakSession session, Componen
...
+			if (allowedMapperProviders.contains(mapperType)) {
+				continue;
+			}
+			if (clientModel == null) {
+				failWithProtocolMapperTypeNotAllowedError(mapperRepresentation);
+				return;
+			}
+			String mapperRepresentationId = mapperRepresentation.getId();
+			if (mapperRepresentationId == null) {
+				failWithProtocolMapperTypeNotAllowedError(mapperRepresentation);
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/clientregistration/policy/impl/ProtocolMappersClientRegistrationPolicy.java:77]: We can probably respond with a more explicit message that the mapper id is missing and later that it can not be found?

Instead of just returning `ProtocolMapper type not allowed`?

**Review by pedroigor — COMMENTED** [review]
@reda-alaoui Thanks a lot. Only a minor comment about messages. Other than that, LGTM.

**Review by pedroigor — APPROVED** [review]
@mposolda LGTM.
