### PR TITLE
Convert database errors to 500 HTTP status response  instead of 400.

### LINKED ISSUE #25993: PostgreSQL deadlock causes 400 client error instead of 500 server error
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

If two clients happen to update realm attributes exactly at the same time, it may cause a [deadlock](https://www.cybertec-postgresql.com/en/postgresql-understanding-deadlocks/) at SQL server (PostgreSQL in our case).  In this scenario, Keycloak may return unexpected error response and also "leak" the SQL query details in error response body.

### Version

23.0.3

### Expected behavior

In this error scenario:

1. Keycloak should preferably return `500 Internal Server Error` to indicate that client may retry the operation. 
2. The error response from Keycloak should not contain SQL query details.

### Actual behavior

Keycloak returns `400 Bad Request` with following response body:

```json
{"errorMessage":"jakarta.persistence.OptimisticLockException: org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 182 waits for ShareLock on transaction 2310; blocked by process 176.\nProcess 176 waits for ShareLock on transaction 2309; blocked by process 182.\n  Hint: See server log for query details.\n  Where: while deleting tuple (3,71) in relation \"realm_attribute\"] [delete from REALM_ATTRIBUTE where NAME=? and REALM_ID=?]"}
```

Luckily, Hibernate uses prepared statements here, so no sensitive data is leaked.

### How to Reproduce?

Note that following steps are not a realistic use case, but it provides easy way to reproduce the fault just in a few seconds.

I've used following short Python scripts below to update the realm attributes concurrently in two separate processes. This is eventually likely to cause a deadlock at the database server.

<details>

This first script fetches token and full realm data, and then it updates whole realm by PUTting the fetched realm data back in a busy loop:

```python
import requests

TOKEN = requests.post(
    'http://keycloak/realms/master/protocol/openid-connect/token',
    data={'username': 'admin', 'password': 'admin', 'grant_type': 'password', 'client_id': 'admin-cli'}
).json()['access_token']

REALM_DATA = requests.get(
    'http://keycloak/admin/realms/master',
    headers={'Authorization': 'bearer ' + TOKEN}).text

num_requests = 1
while True:
    res = requests.put(
        'http://keycloak/admin/realms/master',
        headers={'Authorization': 'bearer ' + TOKEN,
                 'Content-Type': 'application/json'},
        data=REALM_DATA)
    if res.status_code == 204:
        print(f'Attempt {num_requests} successful')
    else:
        print(f'Error at attempt {num_requests}: {res.status_code} {res.reason}: {res.text}')
    num_requests += 1
```

The above script alone will not cause errors, it will always succeed (well, until token expires). One client triggers only one SQL transaction which cannot cause deadloc. But if running another client concurrently that updates couple of other independent attributes in the same table, then database deadlock happens in a few seconds:

```python
import requests

TOKEN = requests.post(
    'http://keycloak/realms/master/protocol/openid-connect/token',
    data={'username': 'admin', 'password': 'admin', 'grant_type': 'password', 'client_id': 'admin-cli'}
).json()['access_token']

num_requests = 1
while True:
    res = requests.put(
        'http://keycloak/admin/realms/master',
        headers={'Authorization': 'bearer ' + TOKEN},
        json={'bruteForceProtected': True, 'defaultSignatureAlgorithm': 'ES384'}
    )
    if res.status_code == 204:
        print(f'Attempt {num_requests} successful')
    else:
        print(f'Error at attempt {num_requests}: {res.status_code} {res.reason}: {res.text}')
    num_requests += 1
```

Output Example

```
Error at attempt 188: 400 Bad Request: {"errorMessage":"jakarta.persistence.OptimisticLockException: org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 239 waits for ShareLock on transaction 2567; blocked by process 245.\nProcess 245 waits for ShareLock on transaction 2566; blocked by process 239.\n  Hint: See server log for query details.\n  Where: while deleting tuple (94,36) in relation \"realm_attribute\"] [delete from REALM_ATTRIBUTE where NAME=? and REALM_ID=?]"}
```

</details>

### Anything else?

While running the reproduction steps above, it can be seen that the second python script that updates individual attributes will get error code `500 Internal Server Error` with response body `{"error":"unknown_error"}` which seems better, compared to the first python script that gets `400 Bad Request`. 

When enabling the SQL statement debug on PostgreSQL side, it can be observed that the first script (update of full realm) will generate SQL transaction with `DELETE` and `INSERT` for `REALM_ATTRIBUTE` i.e. it seems to delete and re-import the whole realm. The second script that updates just two individual attributes will generate smaller SQL transaction with only `UPDATE` statements in it.

I guess DB deadlock might happen with other types of scenarios too, but in our case we bumped into this via realm attribute updates.

I attach two example backtraces from Keycloak when the SQL deadlock happens

a) PostgreSQL exception: org.postgresql.util.PSQLException: ERROR: deadlock detected

```
2024-01-08 12:23:11,074 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: org.keycloak.models.ModelException: org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected
  Detail: Process 239 waits for ShareLock on transaction 2587; blocked by process 245.
Process 245 waits for ShareLock on transaction 2588; blocked by process 239.
  Hint: See server log for query details.
  Where: while updating tuple (100,26) in relation "realm_attribute"] [update REALM_ATTRIBUTE set VALUE=? where NAME=? and REALM_ID=?]
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:99)
        at org.keycloak.connections.jpa.JpaExceptionConverter.convert(JpaExceptionConverter.java:33)
        at org.keycloak.transaction.JtaTransactionWrapper.lambda$handleException$0(JtaTransactionWrapper.java:65)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.keycloak.transaction.JtaTransactionWrapper.handleException(JtaTransactionWrapper.java:67)
        at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:92)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
        at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
        at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
        at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:55)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.closeSession(CloseSessionHandler.java:69)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.filter(CloseSessionHandler.java:65)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected
  Detail: Process 239 waits for ShareLock on transaction 2587; blocked by process 245.
Process 245 waits for ShareLock on transaction 2588; blocked by process 239.
  Hint: See server log for query details.
  Where: while updating tuple (100,26) in relation "realm_attribute"] [update REALM_ATTRIBUTE set VALUE=? where NAME=? and REALM_ID=?]
        at org.hibernate.dialect.PostgreSQLDialect.lambda$buildSQLExceptionConversionDelegate$1(PostgreSQLDialect.java:944)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:278)
        at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:107)
        at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:40)
        at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:52)
        at org.hibernate.persister.entity.mutation.UpdateCoordinatorStandard.doStaticUpdate(UpdateCoordinatorStandard.java:771)
        at org.hibernate.persister.entity.mutation.UpdateCoordinatorStandard.performUpdate(UpdateCoordinatorStandard.java:327)
        at org.hibernate.persister.entity.mutation.UpdateCoordinatorStandard.coordinateUpdate(UpdateCoordinatorStandard.java:244)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2749)
        at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:166)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:635)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:502)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:364)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1412)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:485)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2301)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1966)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:336)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
        at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:76)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:360)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:91)
        at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
        at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
        at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:90)
        ... 16 more
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 239 waits for ShareLock on transaction 2587; blocked by process 245.
Process 245 waits for ShareLock on transaction 2588; blocked by process 239.
  Hint: See server log for query details.
  Where: while updating tuple (100,26) in relation "realm_attribute"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
        at jdk.internal.reflect.GeneratedMethodAccessor196.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
        at jdk.proxy2/jdk.proxy2.$Proxy87.executeUpdate(Unknown Source)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:275)
        ... 45 more
```

b) Hibernate exception: Row was updated or deleted by another transaction

```
2024-01-08 12:23:11,139 WARN  [com.arjuna.ats.arjuna] (executor-thread-5) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff0af4010b:aaed:659bce15:2de7, org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@1650a81d >: jakarta.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.keycloak.models.jpa.entities.RealmAttributeEntity#org.keycloak.models.jpa.entities.RealmAttributeEntity$Key@b67afc34]
        at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:204)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:93)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:162)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:168)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1416)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:485)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2301)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1966)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:336)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
        at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:76)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:360)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:91)
        at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
        at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
        at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:90)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
        at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
        at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
        at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:55)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.closeSession(CloseSessionHandler.java:69)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.filter(CloseSessionHandler.java:65)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.keycloak.models.jpa.entities.RealmAttributeEntity#org.keycloak.models.jpa.entities.RealmAttributeEntity$Key@b67afc34]
        at org.hibernate.engine.jdbc.mutation.internal.ModelMutationHelper.identifiedResultsCheck(ModelMutationHelper.java:75)
        at org.hibernate.persister.entity.mutation.UpdateCoordinatorStandard.lambda$doStaticUpdate$8(UpdateCoordinatorStandard.java:775)
        at org.hibernate.engine.jdbc.mutation.internal.ModelMutationHelper.checkResults(ModelMutationHelper.java:50)
        at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:114)
        at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:40)
        at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:52)
        at org.hibernate.persister.entity.mutation.UpdateCoordinatorStandard.doStaticUpdate(UpdateCoordinatorStandard.java:771)
        at org.hibernate.persister.entity.mutation.UpdateCoordinatorStandard.performUpdate(UpdateCoordinatorStandard.java:327)
        at org.hibernate.persister.entity.mutation.UpdateCoordinatorStandard.coordinateUpdate(UpdateCoordinatorStandard.java:244)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2749)
        at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:166)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:635)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:502)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:364)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1412)
        ... 31 more
```

### PR DESCRIPTION
**Pull request by tsaarni**
Closes #25993

This PR fixes #25993 where PostgreSQL deadlock caused Keycloak to respond with `400` error and leak SQL statement details in response body.

**Background**

Currently database errors are converted into `ModelException` ([link](https://github.com/keycloak/keycloak/blob/0f48027ffb14d8147a87c9b36b5ae5aeae87db4a/model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java#L99)). The exception is handled as client error in places like `RealmAdminResource` ([link](https://github.com/keycloak/keycloak/blob/0f47071a299c0084ea4247deca06fc06500bf8af/services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java#L470-L471)) and `400 Bad Request` response is sent to the client. Sometimes also `500 Internal Server Error` is returned (see [exception mapper](https://github.com/keycloak/keycloak/blob/42f0488d76c15ea83beb235d144f1de2076908e1/services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java#L117)) when `ModelException` is not specifically catched. Which one is sent, depends on how/when the original exception happens.

The current approach is problematic because:

1. The `400` response implies that client sent bad request. Client should not retry bad request. However, database error can very well be temporary and client should retry in this case. Therefore sending `500` response would be more appropriate.
2. The [`PersistenceExceptionConverter`](https://github.com/keycloak/keycloak/blob/0f48027ffb14d8147a87c9b36b5ae5aeae87db4a/model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java#L99) includes the original database exception as cause, and as an example, [`RealmAdminResource`](https://github.com/keycloak/keycloak/blob/0f47071a299c0084ea4247deca06fc06500bf8af/services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java#L471) includes the exception message as response body sent to the client. This leaks database details to client, which is not desirable. Nothing too sensitive is sent since hibernate uses prepared statements, so this is not a security issue.

Fixes #25993

### CODE REVIEW

**Comment by tsaarni** [comment]
I've analyzed the test case failure:

There is actually existing handling for deadlocks in one very specific case (at least): [`UserStorageManager.deleteInvalidUser()`](https://github.com/keycloak/keycloak/blob/47f7e3e8f162d1638f74a86263ecee3d870e2749/model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L192-L196) expects for locking problems to happen and since it knows `ModelException` was thrown, it catches that, ingores it, and prints

```
15:16:59,502 DEBUG [org.keycloak.storage.UserStorageManager] ModelException thrown during deleteInvalidUser with username 'test-user-188'
org.keycloak.models.ModelException: jakarta.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.keycloak.models.jpa.entities.UserEntity#19666d6e-bfc2-4575-b3b3-41c500a6823b]
```

Now when in this PR the database errors throw `RuntimeException`, the above catch was not effective anymore. Associated test case failed:

```
[ERROR]   UserStorageDirtyDeletionUnsyncedImportTest>AbstractUserStorageDirtyDeletionTest.testMembersWhenCachedUsersRemovedFromBackend:126 » BadRequest HTTP 400 Bad Request
```

Curiously the failure reason is `HTTP 400 Bad Request` which I wanted to avoid in the first place. This is because during test case, the server throws `JsonMappingException` (see full stack [here](https://gist.github.com/tsaarni/cbd8e8d45809d298c847ec62c170b669)) which is explicitly catched by [`KeycloakErrorHandler`](https://github.com/keycloak/keycloak/blob/2ee49fe5e958d112852998bedfe1b27628a66a76/services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java#L126-L128`) and converted to `400`. Not sure why during test case there is `JsonMappingException` but it might be related to running undertow.

I'd appreciate guidance on how to proceed! 🙏

File: model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java [hunk 1]
```diff
@@ -95,6 +98,8 @@ public static ModelException convert(Throwable t) {
             throw new ModelDuplicateException(t.getCause());
         } else if (throwModelDuplicateEx.test(t)) {
             throw new ModelDuplicateException(t);
+        } else if (t instanceof HibernateException || t instanceof OptimisticLockException) {
+            throw new RuntimeException("Database operation failed", t);
```
Comment (ahus1) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java:102]: I had a look at the existing exceptions, and `ModelIllegalStateException` might be a better fit than a `RuntimeException`. It might even fix the other problem you're seeing with the failing test (I didn't try it though).

Catching the `HibernateException` here seems to be a bit broad here, I'd like to restrict it to the `OptimisticLockException`. 

Looking at the original issue that the message of a ModelException is passed to the caller without modification, it seems that it is a bad idea to pass on the exception to the constructor without providing a message. So I'd suggest to remove that constructor and only use the one which explicitly provides a message. WDYT?

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for this PR. See my comments below for some ideas.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java (hunk 1 above)
Comment (tsaarni) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java]: > I had a look at the existing exceptions, and ModelIllegalStateException might be a better fit than a RuntimeException. 


`ModelIllegalStateException` seems better to me as well.
I was previouly thinking this (from issue description) "_There is existing exception ModelIllegalStateException that could in theory be used, but it is subclass of ModelException and therefore as of today it is already mapped to 400. Changing that would mean we should add specific catch for ModelIllegalStateException to all relevant places to return 500 which does not seem right._" but maybe this is the right approach.

> It might even fix the other problem you're seeing with the failing test (I didn't try it though).
  
I needed to add catches to places that already catched the parent class `ModelException` and mapped it to `400`.

Now I have explicit catch `ModelIllegalStateException` and return `500`

> Catching the HibernateException here seems to be a bit broad here, I'd like to restrict it to the OptimisticLockException.

Done!


> Looking at the original issue that the message of a ModelException is passed to the caller without modification, it seems that it is a bad idea to pass on the exception to the constructor without providing a message. So I'd suggest to remove that constructor and only use the one which explicitly provides a message. WDYT? 

I removed the constructor and changed all accordingly.

**Comment by ahus1** [comment]
@tsaarni - thank you for the changes, and sorry it took me so long to review them. 

They look good now and should be ready to be merged. Unfortunately, this PR acquired a merge conflict in the meantime. Please resolve the conflict, and I'll then review it.

**Comment by tsaarni** [comment]
Thank you @ahus1! I've now resolved the merge conflict.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java [hunk 2]
```diff
@@ -92,11 +96,13 @@ public static ModelException convert(Throwable t) {
         throwModelDuplicateEx = throwModelDuplicateEx.or(checkDuplicationMessage);
 
         if (t.getCause() != null && throwModelDuplicateEx.test(t.getCause())) {
-            throw new ModelDuplicateException(t.getCause());
+            throw new ModelDuplicateException("Duplicate resource error", t.getCause());
         } else if (throwModelDuplicateEx.test(t)) {
-            throw new ModelDuplicateException(t);
+            throw new ModelDuplicateException("Duplicate resource error", t);
+        } else if (t instanceof OptimisticLockException) {
```
Comment (pedroigor) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java:102]: Does it make sense to have a single `else` branch to throw ` ModelIllegalStateException("Database operation failed", t);` ?

I would say that any other unhandled exception should be thrown as `ModelIllegalStateException`, no?

File: services/src/main/java/org/keycloak/services/resources/admin/ClientRoleMappingsResource.java [hunk 3]
```diff
@@ -173,6 +175,9 @@ public void addClientRoleMapping(List<RoleRepresentation> roles) {
                 auth.roles().requireMapRole(roleModel);
                 user.grantRole(roleModel);
             }
+        } catch (ModelIllegalStateException e) {
+            logger.error(e.getMessage(), e);
+            throw ErrorResponse.error(e.getMessage(), Response.Status.INTERNAL_SERVER_ERROR);
```
Comment (pedroigor) [inline services/src/main/java/org/keycloak/services/resources/admin/ClientRoleMappingsResource.java:180]: Created https://github.com/keycloak/keycloak/issues/28587 to improve how we are handling exceptions in our JAX-RS layer.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java (hunk 2 above)
Comment (tsaarni) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java]: I've now changed that. Now from client perspective they will result in `500` error. Thank you @pedroigor for review!

Comment (tsaarni) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java]: That [last change](https://github.com/keycloak/keycloak/compare/487321bd7c6258e8efc33d38fccf86d7eb566b5c..3930be5d9a67c96d608a500e1801a806bdf98e48) caused failures with mysql and mssql https://github.com/keycloak/keycloak/actions/runs/8634930577/job/23671780092?pr=26096. It seems to me that Keycloak logs are not enabled on those jobs and arranging local test seems bit challenging, so I'm reverting the change for now, unless you'd like me to try going deeper.

**Review by pedroigor — DISMISSED** [review]
@tsaarni Thanks.

@ahus1 It seems the only thing missing from your side was the merge conflict so I'm only approving from my side.

**Review by ahus1 — DISMISSED** [review]

**Comment by ahus1** [comment]
@tsaarni - unfortunately GitHub now tells me again that there are conflicts, although the UI doesn't show them to me. Please again rebase he PR. Sorry for this.

**Comment by tsaarni** [comment]
> @tsaarni - unfortunately GitHub now tells me again that there are conflicts, although the UI doesn't show them to me. Please again rebase he PR. Sorry for this.

No problem! PR is now rebased.

**Review by pedroigor — APPROVED** [review]
