### PR TITLE
Persisting revoked access tokens

### LINKED ISSUE #31296: Revoke access tokens for persistent user sessions
### Area

authentication

### Describe the bug

When using persistent user sessions, user sessions will survive the restart of Keycloak. 
As revoked access tokens will be stored in-memory only, those entries will be gone, and the access tokens will be valid again. 

### Version

25.0.0

### Expected behavior

When using persistent sessions a revoked access token should still be revoked after a full Keycloak restart.

### Actual behavior

The access token is usable again after the Keycloak restart, as the user session is stored in the database, but the revoked access token is not.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #31296

General idea:
* Write each revoked token to the database when it is revoked, plus also write it to the cache.
* On Keycloak restart, check if the cache contents have been lost, and then read them again from the database.
* The rest of the revocation logic is untouched.
* This table should be filled all the time, or only when persistent sessions are enabled

Discarded approach: 
* Storing revoked access tokens in the client session, as not all tokens have a client sessions (for example if they are light-weight, exchanged, or from a session-less token from a client).

A future PR: Apply a similar logic to RemoteInfinispanSingleUseObjectProvider

### CODE REVIEW

**Comment by ahus1** [comment]
@pedroigor / @mposolda - please let me know if this is a valid approach to solve the issue.

cc: @stianst

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentSessionsSingleUseObjectProviderFactory.java [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+        initialize(session);
+        return new PersistentSessionsSingleUseObjectProvider(session, singleUseObjectCache);
+    }
+
+    private void initialize(KeycloakSession session) {
+        if (!initialized) {
+            synchronized (this) {
+                if (!initialized) {
+                    RevokedTokenPersisterProvider provider = session.getProvider(RevokedTokenPersisterProvider.class);
+                    BasicCache<String, SingleUseObjectValueEntity> cache = singleUseObjectCache.get();
```
Comment (stianst) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentSessionsSingleUseObjectProviderFactory.java:63]: Maybe add a `provider != null` check here, because then it would be possible to disable this by simply disabling the JpaRevokedTokensPersister provider?

**Review by stianst — COMMENTED** [review]
LGTM, have not done a deep deep review though.

One potential idea is to maybe make this into something that can be enabled/disabled separately from persisted user sessions. Essentially even without persisted user sessions there's still the issue of revoked tokens being lost for service accounts. Also, someone might want persisted sessions, but don't revoke individual tokens, or don't care about them being lost after an upgrade (i.e. they always have short timeout on tokens anyways).

For the above I was thinking perhaps just make InfinispanSingleUseObjectProvider do the job if there is a persisted single sessions provider, then it's just a matter of enabling/disabling the JpaRevokedTokensPersister provider (which could also be wrapped in a feature if you wanted to make it nicer to enable/disable).

File: model/jpa/src/main/resources/META-INF/jpa-changelog-26.0.0.xml [hunk 2]
```diff
@@ -45,4 +45,14 @@
         </createIndex>
     </changeSet>
 
+    <changeSet author="keycloak" id="31296-persist-revoked-access-tokens">
+        <createTable tableName="REVOKED_TOKEN">
+            <column name="ID" type="VARCHAR(255)">
+                <constraints nullable="false" />
+            </column>
+            <column name="EXPIRE" type="INT"/>
```
Comment (mhajas) [inline model/jpa/src/main/resources/META-INF/jpa-changelog-26.0.0.xml:53]: If I understand correctly this uses 4 bytes integer. Should we use bigint instead to avoid the year 2038 problem?

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProvider.java [hunk 3]
```diff
@@ -61,9 +67,14 @@ public void put(String key, long lifespanSeconds, Map<String, String> notes) {
             if (logger.isDebugEnabled()) {
                 logger.debugf(re, "Failed when adding code %s", key);
             }
-
             throw re;
         }
+        if (persistRevokedTokens && key.endsWith(REVOKED_KEY)) {
+            if (!notes.isEmpty()) {
+                throw new ModelException("notes are not supported for revoked tokens");
```
Comment (mhajas) [inline model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProvider.java:74]: Should we also throw an exception in all other methods in this class? For example, when `remove` method is called with the `REVOKED_KEY` suffix the operation is not propagated to the database and entries can be reintroduced after a restart.

**Review by mhajas — COMMENTED** [review]
Thank you @ahus1, the change looks good to me. I added a few comments to the code.

File: model/jpa/src/main/resources/META-INF/jpa-changelog-26.0.0.xml (hunk 2 above)
Comment (ahus1) [reply model/jpa/src/main/resources/META-INF/jpa-changelog-26.0.0.xml]: There are a lot of other places where INT is used for time in seconds. Still, we can move to 8 bytes here. Part of the next change.

File: model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProvider.java (hunk 3 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProvider.java]: Done. I think this API is due for a redesign. I combined the check with the `persistRevokedTokens` for now to make it possible for people to opt-out on this.

**Review by mhajas — APPROVED** [review]
Thank you @ahus1, the changes LGTM.

**Review by mposolda — COMMENTED** [review]
Adding 2 minor comments (can be addressed either as a follow-up or not addressed as both are relatively minor)...


My another concern is about possibly adding index to `EXPIRE` field in the database or have some more optimizations to make sure the performance is not a concern?

Just to add some context: There are customers, who still have issues with expiring the events, which were saved by the `JpaEventStoreProvider` . This is due it can be very huge amount of events. Then the DB transaction, which tries to remove expired, basically time-outs and does not remove anything. It is also problematic to add this index later (when DB is already filled with huge amount of objects).

For access-tokens, it is hopefully not so huge issue like for the events as they are usually relatively short-lived and should be expired more often and hence likely a lower chance with having millions of revoked access tokens in the DB. Still, some customers can have strange setups etc... So can be always good to have better performance of the expiration thread OOTB. Just my 2 cents :-)
