### PR TITLE
Fixed tabbing issues in dropdown forms

### LINKED ISSUE #24464: Tabbing is not working in forms inside dropdown
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Tabbing is not working in the following forms inside dropdown:
1. User attribute search form in Users
2. Effective message bundles search form in Realm-settings/Localization/Effective message bundles tab
3. User & Admin event search forms in Events

### Version

22.0.5

### Expected behavior

Tabbing is working as expected.

### Actual behavior

Tabbing is not working.

### How to Reproduce?

1. Go to users, select attribute search/select attributes, click `enter`, and try to tab to go to the first form field. Observe that tabbing is not possible. 
2. Go to realm settings > localization > effective message bundles tab and use tab to open and navigate through fields. Observe that tabbing is not possible. 
3. Go to events > user events tab to open the user events search form and navigate through fields. Observe that tabbing is not possible. This is also true for the admin events search form.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/24464

### CODE REVIEW

File: js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx [hunk 1]
```diff
@@ -60,12 +47,13 @@ const DropdownPanel: React.FC<DropdownPanelProps> = ({
   }, [setSearchDropdownOpen]);
 
   return (
-    <div ref={dropdownRef}>
+    <span ref={dropdownRef}>
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx:50]: Why make this a span?

**Review by jonkoops — APPROVED** [review]

File: js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx (hunk 1 above)
Comment (agagancarczyk) [reply js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx:50]: yeah, thanks @jonkoops , I'm using <span> here because <div> was moving the refresh button to the next line, which was wrong.
