### PR TITLE
Use org.keycloak.common.util.Base64Url to encode/decode clientID

### LINKED ISSUE #15734: clientID are base64 encoded in state uri param with non URI friendly base64
### Area

identity-brokering

### Describe the bug

Hi,

Since #10227 some clientID (in "state") are Base64 encoded but not in URI friendly form despite the warning in the pull request.

New code in IdentityBrokerState.

This new code use java.util.Base64 and can produce non URL safe parameter.
It produce url paramater "state" with + or /.
Sample : c5ac1ea7-6c28-4be1-b7cd-d63a1ba57f78 >  xawep2woS+G3zdY6G6V/eA

The "+" seems well encoded in url with %2B but some js adapter decode the complete uri and remplace %2B with "+".

"+" in URI is a "space".

The callback url is then like this with "+" instead of "%2B"

https://{host}/auth/realms/{realmName}/broker/{broker-name}/endpoint?state=EeW2DGPPk6sdZG6jgymATsRqZeNpj3iy6lP1QAMATnc.uJpIOdQ89-w.xawep2woS+G3zdY6G6V%2FeA&session_state={session}&code={code}

When state is decoded, the "+" is interpreted as "space" and the session is not found.

DEBUG [org.keycloak.protocol.RestartLoginCookie] (executor-thread-3) Skip restarting from the KC_RESTART. Clients doesn't match: Cookie client: cityzen.app.crm_frontend, Requested client: xawep2woS G3zdY6G6V/eA

In the original PR #10231 @ahus1 as already warn about : 
> The alphabet used by Base64 is not URL safe

@mposolda say 
>We have Base64Url class inside the codebase, which effectively does this. So hopefully using that class should be ok
..
>Please use org.keycloak.common.util.Base64Url to encode/decode to avoid reinventing the wheel for convert into URL friendly format.

But the code merged use :
(java.util.)Base64.getEncoder()
(java.util.)Base64.getDecoder()

The original PR was about to reduce the length of RelayState.
Using BASE64Url don't increase length

https://en.wikipedia.org/wiki/Base64#URL_applications
>using [URL encoders/decoders](https://en.wikipedia.org/wiki/Percent-encoding) is no longer necessary and **has no effect on the length of the encoded value**

I propose to use standard java.util.Base64.getUrlDecoder() and Base64.getUrlEncoder() instead or the internal
org.keycloak.common.util.Base64Url

Thanks

### Version

20.0.1

### Expected behavior

Don't encode clientID with "+" ou "/" in URI

Encode c5ac1ea7-6c28-4be1-b7cd-d63a1ba57f78 as Base64URI Friendly : "xawep2woS-G3zdY6G6V_eA"

### Actual behavior

c5ac1ea7-6c28-4be1-b7cd-d63a1ba57f78 is encoded as "xawep2woS+G3zdY6G6V/eA" in URI

### How to Reproduce?

Uuid wich is encoded with "+"  : c5ac1ea7-6c28-4be1-b7cd-d63a1ba57f78

### Anything else?

#10231
#10227

### PR DESCRIPTION
**Pull request by douph1**
fix #15734
related #10227 #10231

### CODE REVIEW

File: server-spi-private/src/main/java/org/keycloak/broker/provider/util/IdentityBrokerState.java [hunk 1]
```diff
@@ -51,8 +51,8 @@ public static IdentityBrokerState decoded(String state, String clientId, String
                 bb.putLong(clientDbUuid.getMostSignificantBits());
                 bb.putLong(clientDbUuid.getLeastSignificantBits());
                 byte[] clientUuidBytes = bb.array();
-                clientIdEncoded = Base64.getEncoder().encodeToString(clientUuidBytes).replace("=", "");
-            } catch (IllegalArgumentException e) {
+                clientIdEncoded = Base64Url.encode(clientUuidBytes);
```
Comment (sschu) [inline server-spi-private/src/main/java/org/keycloak/broker/provider/util/IdentityBrokerState.java:54]: Istn't the `.replace("=", "");`missing here?

Comment (douph1) [reply server-spi-private/src/main/java/org/keycloak/broker/provider/util/IdentityBrokerState.java:54]: no, as the the method already take the part before the first "="
(see comment)

    public static String encodeBase64ToBase64Url(String base64) {
        String s = base64.split("=")[0]; // Remove any trailing '='s
        s = s.replace('+', '-'); // 62nd char of encoding
        s = s.replace('/', '_'); // 63rd char of encoding
        return s;
    }

Comment (sschu) [reply server-spi-private/src/main/java/org/keycloak/broker/provider/util/IdentityBrokerState.java:54]: You are right, I haven't checked that. I just compared it to https://github.com/keycloak/keycloak/pull/15735/files but apparently standard Java does not remove trailing `=`?

**Comment by ahus1** [comment]
Pinging @hmlnarik - I'm starting to review this.

File: server-spi-private/src/main/java/org/keycloak/broker/provider/util/IdentityBrokerState.java (hunk 1 above)
Comment (douph1) [reply server-spi-private/src/main/java/org/keycloak/broker/provider/util/IdentityBrokerState.java:54]: true, standard java doesn't, but since we know the boundaries from the base64, we don't need to keep the `=` for padding

Java 17 always use padding by default :
padding

but provide a way to disable it 

java_no_padding

**Review by ahus1 — APPROVED** [review]
I reviewed the change and it looks good to me. Thanks for adding another unit test for me. All builds are green, approving it.

**Comment by ahus1** [comment]
Hi @hmlnarik - this IMHO ready to be merged. As you've been involved in the original issue, I'd ask you to merge this. Thanks!

**Review by hmlnarik — APPROVED** [review]
Thanks for the fix!
