### PR TITLE
Fix NotContainsUsernamePasswordPolicyProvider: reversed check

### LINKED ISSUE #28389: New username-password policy check is reversed
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

The `NotContainsUsernamePasswordPolicyProvider` class that implements the new password policy incorrectly checks whether the password contains the username or not. [This comment](https://github.com/keycloak/keycloak/commit/757c524cc508a662289284b85223a2e3c9a08fa9#r140532594) describes the issue inline.

If not relevant, please ignore this.

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

A `PolicyError` should be raised if the user's password contains their username.

### Actual behavior

An error is raised only when the user's username contains their password.

### How to Reproduce?

I did not try reproducing the bug, the error seems clear from the code, although it should be reproducible by enabling the password policy in question, then creating a user named _Bob_ and setting its password to _Bob123_. The error would not be raised.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gilvansfilho**
Fix the validation order
closes #28389

### CODE REVIEW

File: server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java [hunk 1]
```diff
@@ -36,7 +36,7 @@ public PolicyError validate(String username, String password) {
         if (username == null) {
```
Comment (csakyzsolt) [inline server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java:36]: Could in any cases `password` be null? If so, a similar null check would be a good idea to prevent unexpected `NullPointerException`s from being raised when `password.contains(username)` is called.

**Review by csakyzsolt — COMMENTED** [review]
Thank you for the quick response and fix! I have made a comment with a small suggestion, otherwise, everything looks good!

File: server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java (hunk 1 above)
Comment (gilvansfilho) [reply server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java:36]: In fact, I think even this check is unnecessary once no other provider does that. Others providers uses username and password without any check.  I think is better just remove that.

@pedroigor wdty?

Comment (sguilhen) [reply server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java:36]: Actually other providers, such as `NotUsernamePasswordPolicyProvider` checks for the `null` username, but none check for a `null` password. In this case, it should be irrelevant if username is `null` or not because `equals` will be `false` if it is, so the check can be skipped completely, IMO.

**Review by sguilhen — APPROVED** [review]

File: server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java (hunk 1 above)
Comment (pedroigor) [reply server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java:36]: @csakyzsolt It makes sense to me. We can do it as a follow-up. If you want to send a contribution to fix this, I'm happy to review/approve it.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@gilvansfilho Thanks again :)
