### PR TITLE
9945 java17 nashorn

### LINKED ISSUE #9945: Script providers not working on OpenJDK 17 due to Nashorn being deprecated
### Describe the bug

Hitting this below exception when I run the `org.keycloak.testsuite.authz.*` module tests 

and here is the reference for the deprecation notice in openjdk - https://openjdk.java.net/jeps/372

I was able to confirm the same runs just fine with JDK11 runtime for the authserver. This would be a blocker for the Java 17 certification tests.

```Caused by: java.lang.IllegalStateException: Could not find ScriptEngine for script: Script{id='null', realmId='0cfba609-5d40-404f-a3eb-769cf46dcff8', name='Grant Policy', type='text/javascript', code='$evaluation.grant();', description='null'}```

This is also was previously discussed in [KEYCLOAK-12755](https://issues.redhat.com/browse/KEYCLOAK-12755)

### Version

17.0.0-SNAPSHOT, OpenJDK17

### Expected behavior

We would like the javascript engine to initialize and not fail on the authorization work flows

### Actual behavior

The suspicion is that because of the deprecated Nashorn js engine in jdk17, we are getting a `Could not find ScriptEngine for script` IllegalStateExceptions.

I think we also want a proper exception to bubble up the stack trace, as currently we get a generic exception which is 
`Unexpected error while evaluating permissions: java.lang.RuntimeException: Failed to evaluate permissions` even though we get the actual problem the stack trace down the line.

### How to Reproduce?

run the authz module testsuite using the below mvn command

set the right binary path for the JDK17_HOME and MVN_SETTINGS_PATH before you run it.

```
mvn -f testsuite/integration-arquillian/tests/base/pom.xml clean install -Dauth.server.java.home=${JDK17_HOME} -Dauth.server.memory.settings="-Xms128m -Xmx512m -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=256m" -Dapp.server.memory.settings="-Xms128m -Xmx512m -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=256m" -B -s ${MVN_SETTINGS_PATH} -Dsettings.path=${MVN_SETTINGS_PATH} -Dsurefire.memory.Xms=512m -Dsurefire.memory.Xmx=1536m -Dinsecure.repositories=WARN -Pauth-server-wildfly -Pjava11-auth-server -Dtest=org.keycloak.testsuite.authz.AuthorizationTest

```

### Anything else?

Issue full stack trace:

```
2022-02-01 20:07:38,427 ERROR [org.keycloak.authorization.authorization.AuthorizationTokenService] (default task-1) Unexpected error while evaluating permissions: java.lang.RuntimeException: Failed to evaluate permissions
        at org.keycloak.keycloak-server-spi-private@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.evaluation.DecisionPermissionCollector.onError(DecisionPermissionCollector.java:182)
        at org.keycloak.keycloak-server-spi-private@17.0.0-SNAPSHOT//org.keycloak.authorization.permission.evaluator.IterablePermissionEvaluator.evaluate(IterablePermissionEvaluator.java:71)
        at org.keycloak.keycloak-server-spi-private@17.0.0-SNAPSHOT//org.keycloak.authorization.permission.evaluator.IterablePermissionEvaluator.evaluate(IterablePermissionEvaluator.java:87)
        at org.keycloak.keycloak-services@17.0.0-SNAPSHOT//org.keycloak.authorization.authorization.AuthorizationTokenService.evaluatePermissions(AuthorizationTokenService.java:285)
        at org.keycloak.keycloak-services@17.0.0-SNAPSHOT//org.keycloak.authorization.authorization.AuthorizationTokenService.authorize(AuthorizationTokenService.java:222)
.
.
.
.
Caused by: java.lang.IllegalStateException: Could not find ScriptEngine for script: Script{id='null', realmId='0cfba609-5d40-404f-a3eb-769cf46dcff8', name='Grant Policy', type='text/javascript', code='$evaluation.grant();', description='null'}
        at org.keycloak.keycloak-services@17.0.0-SNAPSHOT//org.keycloak.scripting.DefaultScriptingProvider.createPreparedScriptEngine(DefaultScriptingProvider.java:106)
        at org.keycloak.keycloak-services@17.0.0-SNAPSHOT//org.keycloak.scripting.DefaultScriptingProvider.prepareEvaluatableScript(DefaultScriptingProvider.java:72)
        at org.keycloak.keycloak-services@17.0.0-SNAPSHOT//org.keycloak.scripting.DefaultScriptingProvider.prepareEvaluatableScript(DefaultScriptingProvider.java:33)
        at org.keycloak.keycloak-authz-policy-common@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.lambda$getEvaluatableScript$0(JSPolicyProviderFactory.java:109)
        at org.keycloak.keycloak-authz-policy-common@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.provider.js.ScriptCache.lambda$computeIfAbsent$0(ScriptCache.java:80)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at org.keycloak.keycloak-authz-policy-common@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.provider.js.ScriptCache.computeIfAbsent(ScriptCache.java:80)
        at org.keycloak.keycloak-authz-policy-common@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.getEvaluatableScript(JSPolicyProviderFactory.java:106)
        at org.keycloak.keycloak-authz-policy-common@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.provider.js.JSPolicyProvider.evaluate(JSPolicyProvider.java:46)
        at org.keycloak.keycloak-authz-policy-common@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.provider.permission.AbstractPermissionProvider.evaluate(AbstractPermissionProvider.java:56)
        at org.keycloak.keycloak-authz-policy-common@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.provider.permission.ResourcePolicyProvider.evaluate(ResourcePolicyProvider.java:47)
        at org.keycloak.keycloak-server-spi-private@17.0.0-SNAPSHOT//org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.lambda$createPolicyEvaluator$0(DefaultPolicyEvaluator.java:116)

```

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

File: common/src/main/java/org/keycloak/common/util/Environment.java [hunk 1]
```diff
@@ -26,6 +26,21 @@ public class Environment {
 
     public static final int DEFAULT_JBOSS_AS_STARTUP_TIMEOUT = 300;
 
+    /*
+     * @return major version of java runtime like 8, 11 or 17
+     */
+    public static int getJavaVersion() {
```
Comment (DGuhr) [inline common/src/main/java/org/keycloak/common/util/Environment.java:32]: when this is targeted to the time we won't have support for wildfly/java8 anymore, I suggest to use `Runtime.version().major()` instead. way less verbose and gives what you want in one line of code. Available since java9.

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/QuarkusPlatform.java [hunk 2]
```diff
@@ -159,4 +166,48 @@ public File getTmpDirectory() {
     private void reset() {
         deferredExceptions.clear();
     }
+
+    @Override
+    public ClassLoader getScriptEngineClassLoader(Config.Scope scriptProviderConfig) {
```
Comment (pedroigor) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/QuarkusPlatform.java:171]: In Quarkus we have a flat classpath so I'm unsure if we need to create a classloader?

Comment (mposolda) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/QuarkusPlatform.java:171]: @pedroigor You're right, Thanks for this point! After some digging, I figured that it is completely sufficient to just include the nashorn jar and it's dependencies directly inside "providers" directory. They are simply picked from there by the default flat classloader. So I changed the Quarkus part to just return null, which is simply using the same default (flat) classloader.

File: common/src/main/java/org/keycloak/common/util/Environment.java (hunk 1 above)
Comment (mposolda) [reply common/src/main/java/org/keycloak/common/util/Environment.java]: I've changed the quarkus part per the suggestion of @pedroigor so it doesn't use this anymore. Hence I removed the stuff from the `Environment` class of keycloak-common module and moved it to the Wildfly module.

However Wildfly module still needs to use that instead of `Runtime.version().major()` as it still needs to use Java 8. This stuff is target for the RHSSO 7.6.X and hence Wildfly and Java8 support still needs to be kept. But since this is in the Wildfly module, it will be auto-removed once we are able to remove Wildfly distribution entirely.

**Review by pedroigor — DISMISSED** [review]
@mposolda Looking forward to have these changes in :)

**Comment by mposolda** [comment]
@pedroigor @DGuhr Thanks guys! Will move forward with the testsuite update for this PR and then will "undraft" it and ask you for re-review. So there will be some additional changes, but possibly just in the testsuite part.

**Comment by mposolda** [comment]
@pedroigor @DGuhr @kami619 I've removed the "draft" flag from this PR and I've updated testsuite part. Now the script tests should be working on JDK 17 on both Wildfly and Quarkus. Do you please have a chance to re-review this PR?

I've added testsuite changes in the latest commit for the easier re-review, but I am planning to squash the commits before merge. I am also planning to follow with the PRs for the quickstarts and documentation.

@kami619 In order to have tests passing on JDK 17, there is also need to prepare the servers with JDK 17 to have the necessary nashorn bits available on the servers. I've used this for my testing on local machine with Java 17:
```
cd testsuite/integration-arquillian/servers
mvn clean install -Pauth-server-wildfly
cd ../tests/base
mvn clean install -Pauth-server-wildfly -Dtest=ScriptAuthenticatorTest
```
Same should work also for `auth-server-quarkus` . And also it should hopefully work for all the other tests, which use javascript engine (protocol mappers, authorization), however I did not test other besides ScriptAuthenticatorTest.

**Review by pedroigor — APPROVED** [review]

**Comment by kami619** [comment]
@mposolda thank you for the detailed instructions, I shall pick this up and test it on my local.

**Comment by mposolda** [comment]
@pedroigor Thanks Pedro!

@kami619 Ok, Thanks. I will wait for you to confirm if your tests are ok before merging this.

**Comment by mabartos** [comment]
@mposolda After some discussion with @kami619, I was trying to execute the `ScriptAuthenticatorTest` test with JDK11 and JDK17. For JDK11 everything works as expected, but for JDK17 there are some issues. It seems the Script authenticator doesn't work for me. I'll try to investigate it a little bit.

**Comment by mposolda** [comment]
@mabartos Hmm.... This is strange.

I've just checked again in this branch. I've rebuild it with Java 11 (from the top codebase directory):
```
mvn clean install -DskipTests=true -Pdistribution
```

And then executed this with Java 17:
```
cd testsuite/integration-arquillian/servers
mvn clean install -Pauth-server-wildfly
cd ../tests/base
mvn clean install -Pauth-server-wildfly -Dtest=ScriptAuthenticatorTest
```

Last command works fine also with `-Dtest=org.keycloak.testsuite.authz.AuthorizationTest` (The test which @kami619 pointed to me this morning).

Do you see different results with the command sequence like this? If not, can you check if in the ZIP file `testsuite/integration-arquillian/servers/auth-server/jboss/wildfly/integration-arquillian-servers-auth-server-wildfly-999-SNAPSHOT.zip` you see the nashorn module inside `auth-server-wildfly/modules/system/layers/keycloak/org/openjdk/nashorn/nashorn-core/main` ?

**Review by mabartos — APPROVED** [review]
@mposolda Oh, sorry, I tried to repeat those steps again and it seems everything's fine even for the WF. Sorry for the confusion. The module is present there.

Manually tested with Open JDK11 and Open JDK17 and everything works as expected.

**Comment by kami619** [comment]
@mabartos thanks for the confirmation. @mposolda lets merge it if its all good from your end as martin was able to verify it for us

**Comment by mposolda** [comment]
@mabartos @kami619 Thanks guys!

**Comment by BenjaminVettori** [comment]
I am uncertain if all dependencies of `nashorn-core.jar` are necessary, but when i looked them up at maven repository, i found those:

```
<dependencies>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
      <version>7.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-commons</artifactId>
      <version>7.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-tree</artifactId>
      <version>7.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-util</artifactId>
      <version>7.3.1</version>
    </dependency>
  </dependencies>
```

seems like `asm-tree` was not mentioned before.
I added nashorn-core.jar (15.4) and the four dependency jar files (7.3.1) and then the default javascript policy started to work.

Just a small side-note: A Default (javascript) policy is generated, when you enable fine grained permissions for a client, even if the javascript dependency is missing. If you try to evaluate permissions with the default policy, there happens just nothing in the gui (no error, just a 500 response from the server in the developer tools). You have to look up server logs to find the root cause.

However, once you add the missing jar files to the provider folder and run `kc.sh build`, everything seems to work.
