### PR TITLE
Fixed the types of Andreas original

### LINKED ISSUE #21261: Identity providers: Pagination in account console (and account REST API)
### Description

See https://issues.redhat.com/browse/KEYCLOAK-18061 and https://github.com/keycloak/keycloak/discussions/8609

### Discussion

https://github.com/keycloak/keycloak/discussions/8609

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by edewit**
in favour of: #32913
fixes: #21261

Co-authored-by: Andreas Kozadinos <koza-sparrow@hotmail.com>
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

File: js/apps/account-ui/src/api/methods.ts [hunk 1]
```diff
@@ -109,8 +109,14 @@ export async function getCredentials({ signal, context }: CallOptions) {
   return parseResponse<CredentialContainer[]>(response);
 }
 
-export async function getLinkedAccounts({ signal, context }: CallOptions) {
-  const response = await request("/linked-accounts", context, { signal });
+export async function getLinkedAccounts(
+  { signal, context }: CallOptions,
+  requestParams: Record<string, string>,
+) {
```
Comment (jonkoops) [inline js/apps/account-ui/src/api/methods.ts:115]: Let's add an explicit type here with the parameters that are allowed. Additionally, let's keep the primitive types here rather than using `string` everywhere. This avoids additional parsing using `parseInt()` or `Boolean()` in the React components.

```suggestion
export type GetLinkedAccountParams = PaginationParams & {
  linked: boolean;
};

export async function getLinkedAccounts(
  { signal, context }: CallOptions,
  requestParams: GetLinkedAccountParams,
) {
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: js/apps/account-ui/src/api/methods.ts [hunk 2]
```diff
@@ -109,8 +109,24 @@ export async function getCredentials({ signal, context }: CallOptions) {
...
 }
 
-export async function getLinkedAccounts({ signal, context }: CallOptions) {
-  const response = await request("/linked-accounts", context, { signal });
+export type LinkedAccountQueryParams = {
+  first: number;
+  max: number;
+  search?: string;
+  linked?: boolean;
+};
```
Comment (jonkoops) [inline js/apps/account-ui/src/api/methods.ts:117]: There is already a type for the pagination present that can be re-used here.

```suggestion
export type LinkedAccountQueryParams = PaginationParams & {
  search?: string;
  linked?: boolean;
};
```

**Review by jonkoops — DISMISSED** [review]

**Review by jonkoops — APPROVED** [review]

File: js/apps/account-ui/src/api/methods.ts [hunk 3]
```diff
@@ -109,8 +109,22 @@ export async function getCredentials({ signal, context }: CallOptions) {
...
+
+export async function getLinkedAccounts(
+  { signal, context }: CallOptions,
+  query: LinkedAccountQueryParams,
+) {
+  const response = await request("/linked-accounts", context, {
+    searchParams: Object.entries(query).reduce(
```
Comment (jonkoops) [inline js/apps/account-ui/src/api/methods.ts:122]: Instead of `.reduce()` you could also do:

```ts
Object.fromEntries(Object.entries(query).map(([key, value]) => ([key, value.toString()])))
````

I kinda expected that `request()` would do this to `searchParams` automatically.

Comment (edewit) [reply js/apps/account-ui/src/api/methods.ts:122]: atm this is the only request with parameters

**Comment by sguilhen** [comment]
@edewit Now that the CI issues were fixed we need to rebase this one

File: js/apps/account-ui/src/api/methods.ts (hunk 3 above)
Comment (jonkoops) [reply js/apps/account-ui/src/api/methods.ts:122]: Yeah, this is an improvement that could be done at a later point
