### PR TITLE
Avoid initing the profile multiple times during re-augmentation

### LINKED ISSUE #19324: Profile is created twice when resolving ignored artifacts
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Enabling FIPS ends up with the following output during the `build`.

```
2023-03-24 18:41:56,866 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: fips
2023-03-24 18:41:56,906 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: fips
2023-03-24 18:41:57,538 INFO  [org.keycloak.common.Profile] (build-5) Preview features enabled: fips
2023-03-24 18:41:57,546 INFO  [org.keycloak.common.Profile] (build-7) Preview features enabled: fips
```

It was introduced by https://github.com/keycloak/keycloak/pull/17228/files where the `Profile` is created a second time when resolving the artifacts to ignore.

### Version

21.0.1

### Expected behavior

`Profile` should not be created twice and no message duplicates in logs.

### Actual behavior

`Profile` is created twice and duplicated messages are in logs as per the description.

### How to Reproduce?

```
kc.sh start-dev --features fips
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #19324

### CODE REVIEW

**Comment by pedroigor** [comment]
@vmuzikar When fixing the corresponding issue, I noticed that option transformers might not be able to resolve enabled features during re-augmentation.

FIPS relies on dynamically [ignoring artifacts](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java#L26) from the runtime when the `fips` feature is set or not.

In this case, the build step where the feature profile is initialized is only executed after the above method is called. This only happens for this particular [property](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java#L20) because at that point Quarkus is still loading the build steps from the current classloader.

To make sure the feature profile instance is always initialized, regardless of the bootstrap stage, the profile is now lazily created during re-augmentation.

This change does not change anything to runtime code.

File: crypto/fips1402/src/main/java/org/keycloak/crypto/fips/KeycloakFipsSecurityProvider.java [hunk 1]
```diff
@@ -38,23 +36,4 @@ public synchronized final Service getService(String type, String algorithm) {
             return null;
         }
     }
-
-    public static String isSystemFipsEnabled() {
```
Comment (pedroigor) [inline crypto/fips1402/src/main/java/org/keycloak/crypto/fips/KeycloakFipsSecurityProvider.java:42]: @mposolda @rmartinc This code does not work in JDK 17 because `java.security.SystemConfigurator` is not there.  Looks like it makes more sense to remove it and move forward without checking if FIPS is enabled to the JVM.

I did not find any alternative in JDK 17. If you have an alternative, that would be nice.

**Review by vmuzikar — DISMISSED** [review]
Thanks @pedroigor. LGTM, but let's wait for a review from someone from the core team as well.

File: crypto/fips1402/src/main/java/org/keycloak/crypto/fips/KeycloakFipsSecurityProvider.java (hunk 1 above)
Comment (mposolda) [reply crypto/fips1402/src/main/java/org/keycloak/crypto/fips/KeycloakFipsSecurityProvider.java:42]: @pedroigor Some correction to this as I've already investigated something similar few months ago once you introduced this. That's also why I've slightly changed this code in this commit https://github.com/keycloak/keycloak/commit/4f068fcd  to return 3 statuses (`enabled`, `disabled`, `unknown` ) instead of 2 statuses (`enabled`, `disabled`), which you originally had.

This code actually works even on JDK 17. But strangely enough, it does not work on all JVM platforms. Few details:
- It does not work on my Ubuntu laptop at all. On both OpenJDK 11 and OpenJDK 17 I have `java.lang.ClassNotFoundException: java.security.SystemConfigurator`

- However on RHEL 9, it works fine with OpenJDK 17! When running Keycloak server on this OpenJDK 17 version:
```
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-3.el9_1) (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-3.el9_1) (build 17.0.6+10-LTS, mixed mode, sharing)
```
The code actually works and it is able to correctly detect status. See this, which I've tried this morning:
```
2023-03-27 09:35:48,159 TRACE [org.keycloak.common.crypto.CryptoIntegration] (main) Java security providers: [ 
 KC(BCFIPS version 1.000203, FIPS-JVM: enabled) version 1.0 - class org.keycloak.crypto.fips.KeycloakFipsSecurityProvider, 
 BCFIPS version 1.000203 - class org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider, 
 BCJSSE version 1.0014 - class org.bouncycastle.jsse.provider.BouncyCastleJsseProvider, 
 SunPKCS11-NSS-FIPS version 17 - class sun.security.pkcs11.SunPKCS11, 
 SUN version 17 - class sun.security.provider.Sun, 
 SunEC version 17 - class sun.security.ec.SunEC, 
 SunJSSE version 17 - class sun.security.ssl.SunJSSE, 
 SunJCE version 17 - class com.sun.crypto.provider.SunJCE, 
 SunRsaSign version 17 - class sun.security.rsa.SunRsaSign, 
 XMLDSig version 17 - class org.jcp.xml.dsig.internal.dom.XMLDSigRI, 
]
```

- One interesting aspect: This works when I execute the Keycloak with Quarkus distribution. Which can be done when I test manually on RHEL VM or when running tests as described here: https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md#integration-tests . However when I run the tests as unit tests with Java 17 as described here https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md#unit-tests, then I have also status `unknown`. But the reason is `java.lang.reflect.InaccessibleObjectException: Unable to make static boolean java.security.SystemConfigurator.isSystemFipsEnabled() accessible: module java.base does not "opens java.security" to unnamed module @22f71333` . So the reason is different than on Ubuntu when the class SystemConfigurator is not available at all. This can be good to investigate, but IMO it very low priority as it affects only unit tests.

- I am not sure about Fedora and not sure if it works there or not

So in shortcut: My vote is definitely to keep this code as it works on OpenJDK 17 at least on some platforms like RHEL 9 and UBI 9, which are most important platforms for us and for our customers. The fact that it doesn't work everywhere is OK as long as status `unknown` is reported.

**Review by mposolda — CHANGES_REQUESTED** [review]
Thanks for the PR!

I've added some details inline related to SystemConfiguratorCheck. My vote is to keep only profile related fixes in this PR, but revert all the changes related to FIPS status check from this PR (changes in class `KeycloakFipsSecurityProvider` and other related changes). See my comment inline. Marking as "Request changes" for now until we clarify this.

**Review by mposolda — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]
