### PR TITLE
Ensure OIDC prompt=login gets correctly mapped to SAML ForceAuthN during identity brokering

### LINKED ISSUE #25980: Force reauthentication is ignored during identity brokering when mapping between OIDC and SAML protocols
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Summary
Keycloak doesn't correctly map OIDC `prompt=login` to a SAML `ForceAuthN` during identity brokering.

### Detail
The OIDC specification states that when a server receives a `prompt=login` authentication request parameter the server:

> The Authorization Server SHOULD prompt the End-User for reauthentication.

Therefore, when a client initiates an OIDC authentication request with the protocol `prompt=login` parameter and the request results in a SAML identity broker redirection (for instance, using the Identity Provider Redirector), Keycloak should map the OIDC `prompt=login` to a SAML `ForceAuthN` XML attribute. This ensures that the external SAML provider also prompts the user for reauthentication regardless of session state. 

Currently, the `SAMLIdentityProvider` logic will ignore any dynamic state in the request context, such as the OIDC parameter, and instead reads from the Identity Provider configuration value to build the SAML request using `ForceAuthN`. Therefore, `ForceAuthN` will only be sent if the IdP has been permanently configured to do so, which makes it hard for clients to conditionally opt-in to the behaviour.

This is a common scenario for step-up authentication flows when an OIDC client needs to ensure that the user is reauthenticated regardless of their session state. 

### Fix
Refactor the logic in the `SAMLIdentityProvider#performLogin()` method to conditionally override the IdP `forceAuthN` value based on the authentication session state and whether `prompt=login` was passed.

### More detail
Code flow for the IdentityProviderAuthenticator, If an IdP is found, it does a redirect here:
https://github.com/keycloak/keycloak/blob/5c86abbc32a7425b7f465e6d51806fa8650a231a/services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java#L86

This creates a URL which is created to send the request to the RealmsResource-> IdentityBrokerService->`performLogin` method:
https://github.com/keycloak/keycloak/blob/5c86abbc32a7425b7f465e6d51806fa8650a231a/services/src/main/java/org/keycloak/services/Urls.java#L56

That service is responsible for loading the IdentityProvider (e.g. SAMLIdentityProvider) and calling the `performLogin` method to create the redirect:
https://github.com/keycloak/keycloak/blob/5c86abbc32a7425b7f465e6d51806fa8650a231a/services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java#L363

The SAMLIdentityProvider creates the SAML2 request, specifically the ability to use `ForceAuthn` based on the Config, which is associated with the identity provider, rather than a transient value which can be passed.
https://github.com/keycloak/keycloak/blob/5c86abbc32a7425b7f465e6d51806fa8650a231a/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java#L164

### Note
As this is a simple fix, I am raising this issue purely as a pointer to reference in the commit and PR and I will be submitting a Pr to fix shortly.

### Version

23.0.3

### Expected behavior

When a client sends requests an OIDC authentication request with the protocol `prompt=login` parameter and the request results in a SAML identity broker redirection, Keycloak should map the OIDC `prompt=login` to a SAML `ForceAuthN` attribute.

### Actual behavior

Keycloak ignores the `prompt=login` parameter and generates a SAML request without `ForceAuthN`.

### How to Reproduce?

- Configure a SAML IdP with `ForceAuthN` set to `false` and associate with a user
- Configure an authentication flow with the "Identity Provider Redirector"
- Configure an OIDC client and bind to authentication flow
- Send OIDC auth request with `prompt=login`
- Get redirected to external SAML IdP and note lack of `ForceAuthN` in the SAML request XML

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by phamann**
Closes #25980

---

### Summary 
Keycloak doesn't correctly map OIDC `prompt=login` to a SAML ForceAuthN during identity brokering.
Detail

The OIDC specification states that when a server receives a prompt=login authentication request parameter the server:

    The Authorization Server SHOULD prompt the End-User for reauthentication.

The SAML protocol has an equivilent behaviour in the form of `ForceAuthN`.

Therefore, when a client initiates an OIDC authentication request with the protocol `prompt=login` parameter and the request results in a SAML identity broker redirection (for instance, using the Identity Provider Redirector), Keycloak should map the OIDC `prompt=login` to a SAML ForceAuthN XML attribute. This ensures that the external SAML provider also prompts the user for reauthentication regardless of session state.

Currently, the SAMLIdentityProvider logic will ignore any dynamic state in the request context, such as the OIDC parameter, and instead reads from the Identity Provider configuration value to build the SAML request using `ForceAuthN`. Therefore, `ForceAuthN` will only be sent if the IdP has been permanently configured to do so, which makes it hard for clients to conditionally opt-in to the behaviour.

This is a common scenario for step-up authentication flows when an OIDC client needs to ensure that the user is reauthenticated regardless of their session state.

### Fix

Refactor the logic in the `SAMLIdentityProvider#performLogin()` method to conditionally override the IdP forceAuthN value based on the authentication session state and whether `prompt=login` was passed.

### CODE REVIEW

File: services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java [hunk 1]
```diff
@@ -157,11 +157,14 @@ public Response performLogin(AuthenticationRequest request) {
             Boolean allowCreate = null;
             if (getConfig().getConfig().get(SAMLIdentityProviderConfig.ALLOW_CREATE) == null || getConfig().isAllowCreate())
                 allowCreate = Boolean.TRUE;
+            Boolean forceAuthn = getConfig().isForceAuthn();
+            if ("login".equals(request.getAuthenticationSession().getClientNote(OIDCLoginProtocol.PROMPT_PARAM)))
```
Comment (rmartinc) [inline services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:161]: I would also check for the saml ForceAuthn note just in case keycloak is using SAML to login in the first place. It's the same but looking for [the note SamlProtocol.SAML_LOGIN_REQUEST_FORCEAUTHN](https://github.com/keycloak/keycloak/blob/23.0.4/services/src/main/java/org/keycloak/protocol/saml/SamlService.java#L494-L497). This way the identity provider forwards the re-login in both OIDC and SAML.

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @phamann for the PR!

The change looks good to me but I would also extend the change for SAML just in case. But we also need at least one test, you can try to add it using one of the [broker](https://github.com/keycloak/keycloak/tree/23.0.4/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker) test classes (KcSaml...Test ones for example).

**Comment by phamann** [comment]
👋🏻 @rmartinc Thanks for the speedy review and the feedback. 

I've added the check for the SAML case of `SamlProtocol.SAML_LOGIN_REQUEST_FORCEAUTHN`. However, I am struggling to find any tests covering this code path for brokering, so further pointers or examples would be greatly appreciated.

**Comment by phamann** [comment]
@rmartinc Ignore my previous comment RE tests, after getting more acquinted with the testsuite I was able to write a test covering the SAML path, the OIDC path seems harder to test. But I think the test I've supplied shoudl be sufficient as it exercises the same conditional logic. Let me know your thoughts.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlForceAuthnBrokerTest.java [hunk 2]
```diff
@@ -0,0 +1,104 @@
+package org.keycloak.testsuite.broker;
```
Comment (rmartinc) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlForceAuthnBrokerTest.java:1]: Please add the license comment copying from another file and changing to current year.

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlForceAuthnBrokerTest.java [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+    @Test
+    public void testForceAuthnNotSentInRequest() throws Exception {
+        // If no ForceAuthn is sent in SAML AuthnRequest the value should be
+        // read from the IdP configuration.
+        try (Closeable idpUpdater = new IdentityProviderAttributeUpdater(identityProviderResource)
+            .setAttribute(SAMLIdentityProviderConfig.FORCE_AUTHN, "false")
+            .update())
+        {
+            // Build the login request document
+            AuthnRequestType loginRep = SamlClient.createLoginRequestDocument(AbstractSamlTest.SAML_CLIENT_ID_SALES_POST + ".dot/ted", getConsumerRoot() + "/sales-post/saml", null);
```
Comment (rmartinc) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlForceAuthnBrokerTest.java:40]:
```suggestion
            AuthnRequestType loginRep = SamlClient.createLoginRequestDocument(AbstractSamlTest.SAML_CLIENT_ID_SALES_POST, getConsumerRoot() + "/sales-post/saml", null);
```

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlForceAuthnBrokerTest.java [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+    @Test
+    public void testForceAuthnSentInRequest() throws Exception {
+        // If ForceAuthn=true is sent in SAML AuthnRequest it should be
+        // forwarded to IdP regardless of the IdP ForceAuthn configuration.
+        try (Closeable idpUpdater = new IdentityProviderAttributeUpdater(identityProviderResource)
+            .setAttribute(SAMLIdentityProviderConfig.FORCE_AUTHN, "false")
+            .update())
+        {
+            // Build the login request document
+            AuthnRequestType loginRep = SamlClient.createLoginRequestDocument(AbstractSamlTest.SAML_CLIENT_ID_SALES_POST + ".dot/ted", getConsumerRoot() + "/sales-post/saml", null);
```
Comment (rmartinc) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlForceAuthnBrokerTest.java:77]:
```suggestion
            AuthnRequestType loginRep = SamlClient.createLoginRequestDocument(AbstractSamlTest.SAML_CLIENT_ID_SALES_POST, getConsumerRoot() + "/sales-post/saml", null);
```

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @phamann!

Yes, you are right, I think all the tests in broker are oidc->oidc and saml->saml, so the test oidc->saml is much more complicated. I also think that it's enough with the saml->saml test you are proposing.

For me the coding part is OK. Just adding three minor comments. Please add the license comment to the new test file with year 2024, and I asked you to remove the `+ ".dot/ted"` in the issuer (I suppose you copied this from another test and it's not needed, I'm just requesting this because the license file is needed, so you need to modify the PR anyway).

**Comment by phamann** [comment]
Thanks, @rmartinc. I have updated the test file with the license and amendments. 👍🏻

**Review by rmartinc — APPROVED** [review]
Thanks @phamann! Approved! I'm going to ask a maintainer to launch the tests.

File: services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java [hunk 5]
```diff
@@ -157,11 +157,15 @@ public Response performLogin(AuthenticationRequest request) {
             Boolean allowCreate = null;
             if (getConfig().getConfig().get(SAMLIdentityProviderConfig.ALLOW_CREATE) == null || getConfig().isAllowCreate())
                 allowCreate = Boolean.TRUE;
+            Boolean forceAuthn = getConfig().isForceAuthn();
+            if ("login".equals(request.getAuthenticationSession().getClientNote(OIDCLoginProtocol.PROMPT_PARAM)) ||
```
Comment (mposolda) [inline services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:161]: I would slightly prefer something like:
```
LoginProtocol protocol = context.getSession().getProvider(LoginProtocol.class, request.getAuthenticationSession.getProtocol());
if (protocol.requireReauthentication(null, request.getAuthenticationSession()) 
```
It might need some small updates to the `OIDCLoginProtocol.requireReauthentication` to allow null userSession to be passed as a parameter.

@rmartinc @phamann WDYT?

Comment (phamann) [reply services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:161]: That is certainly cleaner. I'm happy to give it a go 👍🏻

Comment (rmartinc) [reply services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java:161]: @mposolda It's more generic so I think that it's better too. @phamann As Marek comments you need to also modify the [OIDCLoginProtocol](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java#L414) to allow passing a null user session (return false in that case). The other protocols does not use the user session, so OIDC is the only one affected.

**Comment by phamann** [comment]
@mposolda @rmartinc I've now updated to use @mposolda's suggestion to use the generic protocol `requireReauthentication()` method.  

It also seems there was an unrelated test failure in the previous CI run.

**Review by rmartinc — APPROVED** [review]

**Review by mposolda — APPROVED** [review]
