### PR TITLE
Fix account console for usage with secure-session client-policy (#37447)

### LINKED ISSUE #37447: account-console no longer provides nonce/state parameter
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

With the update from Keycloak 26.0.8 to 26.1.0 I noticed that account-console gave a "Missing parameter: state" error. After some investigation I noticed that this is because we are using the secure-session client policy.

The reason for this seems to be that there has been a change to account-console where it no longer uses the state/nonce parameters and since the secure-session client policy requires these to be there it fails.

I can't find any information about this in the release notes and it feels like a breaking change but I guess it can be discussed. So far I see this as a bug but if not I would love to hear if there is a reason for this. It seems the security-console still uses state/nonce as it should.

Image

### Version

26.1.0

### Regression

- [x] The issue is a regression

### Expected behavior

I would expect that account-console works with secure-session client policy. This means that I would expect it to use state/nonce parameters in the OIDC flow.

Expected URL (Also how it looks in 26.0.8):
http://localhost:8080/realms/test/protocol/openid-connect/auth?client_id=account-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Frealms%2Ftest%2Faccount%2F&state=9263e110-9720-4ae5-adb7-3d56a7606524&response_mode=query&response_type=code&scope=openid&nonce=cf26e8e4-d51c-4748-9b32-72e556399fd1&code_challenge=fe-QrTtqOlyhbz9So1zSHKW6BpdaGjggE0GscpR5yQ4&code_challenge_method=S256

### Actual behavior

The current behavior is that account-console does not supply state/nonce parameters anymore in the OIDC flow.

Actual URL (How it looks from 26.1.0 and forward):
http://localhost:8080/realms/test/protocol/openid-connect/auth?client_id=account-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Frealms%2Ftest%2Faccount&response_type=code&code_challenge=5i6Psu8hD-AwOMkw7wSYnZOHeH5eSDIn_G8qImqOo0o&code_challenge_method=S256

### How to Reproduce?

Spin up a version of Keycloak later than 26.1.0 and enable secure-session client policy.
Realm Settings->Client Policies->Profile

Create a new Profile and add the secure-session executer.

Go back to Realm Settings->Client Policies->Policies

Create a new Policy and add client-any condition. Then add the client profile created and click save.

Logout from admin console, or use incognito mode and go to http://localhost:8080/realms/master/account/

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
Fixes #37447

(cherry picked from commit a4654167328842a4a5659468e2659c8478101b59)

This is an extension of the PR https://github.com/keycloak/keycloak/pull/38476 , which fixes `TermsAndConditionsTest` (as after the error after user rejects terms-and-conditions, there is another request sent automatically and hence login page is displayed) .

Also added the automated test in `ClientPoliciesExecutorTest` for the scenario from the report.

### CODE REVIEW

File: testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/TermsAndConditionsTest.java [hunk 1]
```diff
@@ -186,14 +186,8 @@ public void termsDeclinedAccount() {
             assertNull("expected null for terms acceptance user attribute " + TermsAndConditions.USER_ATTRIBUTE,
                     attributes.get(TermsAndConditions.USER_ATTRIBUTE));
         }
-        assertThat(DroneUtils.getCurrentDriver().getTitle(), equalTo("Account Management"));
```
Comment (pedroigor) [inline testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/TermsAndConditionsTest.java:189]: I did not get how the `state` param is now forcing us to remove these assertions. The flow is the same as when not setting the `state` parameter, and the `error` (and error_description) parameter should cause the account to be rendered with the expected user message?

**Review by thomasdarimont — APPROVED** [review]
LGTM, see remark regarding the terms and conditions test.

**Comment by mposolda** [comment]
@pedroigor @thomasdarimont It is the behaviour of keycloak.js integration of account console that when it sees the login URL with the unknown `state` parameter, it redirects directly to the login screen. When there is some other parameters (like `error`) together with `state`, the keycloak.js will try to lookup callback data by existing `state` (See method `parseCallback` in `keycloak.js`). When it does not find the data, it redirects to the login screen.

BTW. This happens during every successful login to the account console as well and it was the case before my changes as well. So during every login to account console (with or without `state` parameter), the account console will call another redirect to login (this 2nd redirect is done now by `keycloak.js` and hence it works as during 2nd redirect back, keycloak.js is able to find the callback when calling `parseCallback`)

In other words, with this PR, when user press "decline", Keycloak will redirect to the URL like this which contains `state` and this will automatically do the redirect to the login screen without displaying the `error` : https://localhost:8543/auth/realms/test/account?error=access_denied&error_description=termsAndConditionsDeclined&iss=https%3A%2F%2Flocalhost%3A8543%2Fauth%2Frealms%2Ftest&state=something

When you omit the `state` parameter (which is the case before this PR). The URL looks like this and keycloak.js will not try to redirect to login and just display the `error`: https://localhost:8543/auth/realms/test/account?error=access_denied&error_description=termsAndConditionsDeclined&iss=https%3A%2F%2Flocalhost%3A8543%2Fauth%2Frealms%2Ftest

To me, the options are:

1) Keep as it is in the current PR

2) Handle this as old behaviour and make sure that no changes in `TermsAndConditionsTest` are needed. This would be possible by doing some hacks somewhere here https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java#L276-L280 and make sure that when `state` is present, then ignore it and forward to account console UI without that `state`, which will make sure that keycloak.js will not try to lookup callback by unknown "state". This will make sure that `error` is displayed to the user.

TBH my preference is (1) as regarding usability, it is OK to redirect user directly to the login screen. When user rejected callback, he is aware that he is not able to login? So looks like the error page is just another splash screen displayed to the user? But if you prefer to do (2), please let me know and I can update the PR to not need to do any changes in `TermsAndConditionsTest` . 

Not sure if we can do something else? To me, it seems that this whole combination of redirecting to the login screen from Java (`AccountConsole.redirectToLogin`) and from keycloak.js is a hack. But that will require more changes if we want to get rid of this. For fixing this regression issue, I would prefer to do something simple (which can be backported to older branches without risk of other regressions) and then doing further bigger refactoring (if needed).

**Comment by mposolda** [comment]
@thomasdarimont When you want to test with latest chromedriver, you can download it manually https://googlechromelabs.github.io/chrome-for-testing/ and unpack somewhere in your laptop. Then you can run the test with something like:
```
-Dbrowser=chrome -Dwebdriver.chrome.driver=/home/mposolda/software/chromedriver-linux64-136/chromedriver
```

At least, that is what I am usually doing.

**Review by jonkoops — DISMISSED** [review]

**Comment by pedroigor** [comment]
> TBH my preference is (1) as regarding usability, it is OK to redirect user directly to the login screen. When user rejected callback, he is aware that he is not able to login. So looks like the error page would be just another "splash screen" displayed to the user? But if you prefer to do (2), please let me know and I can update the PR to not need to do any changes in TermsAndConditionsTest .

From a UX perspective, the user should be informed about any error returned by Keycloak to the application. In this case, inform that the term was declined.

I vote to keep the previous behavior.

> Not sure if we can do something else? To me, it seems that this whole combination of redirecting to the login screen from Java (AccountConsole.redirectToLogin) and from keycloak.js is a hack. But that will require more changes if we want to get rid of this. For fixing this regression issue, I would prefer to do something simple (which can be backported to older branches without risk of other regressions) and then doing further bigger refactoring (if needed).

Yer ... And we discussed a lot this approach when we introduced it. The decision was basically a tradeoff between making deep changes to the Account App - as discussed with @jonkoops at that time - and a simpler/hacky change to handle things from the backend. I'm also not happy with the current behavior but the old behavior where you have the Account App being loaded when the user is not even authenticated is worse, I think ....

**Comment by mposolda** [comment]
> > TBH my preference is (1) as regarding usability, it is OK to redirect user directly to the login screen. When user rejected callback, he is aware that he is not able to login. So looks like the error page would be just another "splash screen" displayed to the user? But if you prefer to do (2), please let me know and I can update the PR to not need to do any changes in TermsAndConditionsTest .
> 
> From a UX perspective, the user should be informed about any error returned by Keycloak to the application. In this case, inform that the term was declined.
> 
> I vote to keep the previous behavior.

@pedroigor Yeah, I see the point. For the UX, still not 100% sure as when user declined terms-and-conditions, it should be clear to him that login not possible and hence redirect to login screen might be OK. On the other hand, there could be some other errors (not caused by user himself), which may be clearer to display to the user...

So I've updated the PR, so no change needed in `TermsAndConditionsTest` . Can you re-review please?

**Review by pedroigor — APPROVED** [review]
