### PR TITLE
Fixes #9094: Remove other values for features command. Only preview al…

### LINKED ISSUE #9094: Start Keycloak.X with --features=experimental leads to exception
### Describe the bug

When running e.g. `kc.sh start-dev --features=experimental` I observed that the following exception occurs:

```
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureProviders threw an exception: java.lang.IllegalArgumentException: No enum constant org.keycloak.common.Profile.ProfileValue.EXPERIMENTAL
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.keycloak.common.Profile$ProfileValue.valueOf(Profile.java:109)
	at org.keycloak.common.Profile.<init>(Profile.java:133)
	at org.keycloak.quarkus.runtime.KeycloakRecorder.createProfile(KeycloakRecorder.java:86)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureProviders(KeycloakProcessor.java:240)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

It seems, there's no mapping found for "experimental" in ProductValue, which is true, bc. this only has 3 values, none of them experimental. Using e.g. `--features=preview` works as expected. 

### Version

15.1.0

### Expected behavior

Keycloak.X starts with experimental features enabled.

### Actual behavior

Exception is thrown. 

### How to Reproduce?

run kc.sh start-dev --features=experimental

### Anything else?

observed while trying to look into #9092

### PR DESCRIPTION
**Pull request by DGuhr**
…lowed for now.

Issue: https://github.com/keycloak/keycloak/issues/9094

### CODE REVIEW

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java [hunk 1]
```diff
@@ -305,12 +306,12 @@ private static void addFeatureOptions(CommandSpec commandSpec) {
...
 
-        Set<String> featuresExpectedValues = Arrays.stream(Profile.Type.values()).map(type -> type.name().toLowerCase()).collect(Collectors.toSet());
+        String previewName = Profile.Type.PREVIEW.name().toLowerCase();
 
         featureGroupBuilder.addArg(OptionSpec.builder(new String[] {"-ft", "--features"})
-                .description("Enables a group of features. Possible values are: " + String.join(",", featuresExpectedValues))
-                .paramLabel("feature")
-                .completionCandidates(featuresExpectedValues)
+                .description("Enables all tech preview features.")
+                .paramLabel(Profile.Type.PREVIEW.name().toLowerCase())
```
Comment (pedroigor) [inline quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:313]: A nitpick, but since you have the `previewName` local var perhaps you should just use it here too?

**Review by pedroigor — COMMENTED** [review]
I'm not sure if makes sense to have a option with a single value but have a specific one to enable preview features:

```
kc.sh --features-preview-enabled true
```

Or something similar. Does it make sense?

**Comment by DGuhr** [comment]
> I'm not sure if makes sense to have a option with a single value but have a specific one to enable preview features:
> 
> ```
> kc.sh --features-preview-enabled true
> ```
> 
> Or something similar. Does it make sense?

Might make sense. I was just not sure if we actually _want_ the possibility to have different categories of features like "preview", "experimental", ... so I left it like that. I suggest then to use `features-preview=enabled/disabled` to stay consistent with the others, wdyt?

File: quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java (hunk 1 above)
Comment (DGuhr) [reply quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java:313]: just to make sure: you mean also use it in the description? Can do for sure

**Review by pedroigor — APPROVED** [review]
