### PR TITLE
fix: expose bootstrap-admin-* options

### LINKED ISSUE #32176: Bootstrap options missing from help
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

The bootstrap options are not shown in help. This applies to CLI help (`kc.sh start|start-dev --help`) as well as in the `All configuration guide`.

This includes at least the following options:

* `bootstrap-admin-username`
* `bootstrap-admin-password`
* `bootstrap-admin-client-id`
* `bootstrap-admin-client-secret`

This makes it hard to use these options as the only place to discover them in the `Admin bootstrap and recovery` guide. As I can't seem to get these options quite right, or forget them, I need to then open the guide instead of just looking at the help for reference.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

`All configuration` guide has a `Bootstrap` section, which lists the options. 

`kc.sh start|start-dev --help` lists a `Bootstrap` section, which lists the options.

### Actual behavior

The bootstrap options are hidden from both the `All configuration` guide and CLI help

### How to Reproduce?

* Run `./kc.sh start-dev --help | grep bootstrap` 
* Observe no options are listed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #32176

@mabartos @vmuzikar not sure if it's necessary, but this introduces validators that are somewhat like the enabled logic - we could expand on that if it seems like a good idea with a new builder signature and ideally an automatic update to the description.

### CODE REVIEW

**Comment by mabartos** [comment]
@shawkins I'd prefer extending the builder signature for the `isEnabled`. Perhaps providing the third attribute there as like `boolean alwaysShowInHelp` ? Or do you have a better approach?

```
public Builder<T> isEnabled(BooleanSupplier isEnabled, String enabledWhen, boolean alwaysShowInHelp) {
```

**Comment by shawkins** [comment]
> Perhaps providing the third attribute there as like boolean alwaysShowInHelp ? Or do you have a better approach?

It's possible, but conflicts with the validator - it would require some additional javadocs to explain, or some additional logic .

File: quarkus/config-api/src/main/java/org/keycloak/config/BootstrapAdminOptions.java [hunk 1]
```diff
@@ -1,35 +1,39 @@
 package org.keycloak.config;
 
 public class BootstrapAdminOptions {
+    
+    public static final String DEFAULT_TEMP_ADMIN_USERNAME = "temp-admin";
+    public static final String DEFAULT_TEMP_ADMIN_SERVICE = DEFAULT_TEMP_ADMIN_USERNAME;
+    public static final int DEFAULT_TEMP_ADMIN_EXPIRATION = 120;
+    private static final String USED_ONLY_WHEN = " Used only when the master realm is created.";
+    private static final String NON_CLI = " Use a non-CLI configration option for this option if possible.";
```
Comment (mabartos) [inline quarkus/config-api/src/main/java/org/keycloak/config/BootstrapAdminOptions.java:9]:
```suggestion
    private static final String NON_CLI = " Use a non-CLI configuration option for this option if possible.";
```

File: quarkus/config-api/src/main/java/org/keycloak/config/BootstrapAdminOptions.java [hunk 2]
```diff
@@ -1,35 +1,39 @@
 package org.keycloak.config;
 
 public class BootstrapAdminOptions {
+    
+    public static final String DEFAULT_TEMP_ADMIN_USERNAME = "temp-admin";
+    public static final String DEFAULT_TEMP_ADMIN_SERVICE = DEFAULT_TEMP_ADMIN_USERNAME;
+    public static final int DEFAULT_TEMP_ADMIN_EXPIRATION = 120;
```
Comment (mabartos) [inline quarkus/config-api/src/main/java/org/keycloak/config/BootstrapAdminOptions.java:7]: Does it have to be exposed now? IMO, it might be just commented out. And for the future, it'd be also good to know the units of the expiration value - rather being more explicit.

**Review by mabartos — COMMENTED** [review]
@shawkins In general, LGTM. Even with the current validators for these mappers. It'd be good to create some follow-up issue for improving it as it's more like a workaround? Changing the builder signature, etc.

I've also added a few nitpicks. 

It'd also be good to have some simple test for the PropertyException as we would be sure the error message is properly propagated. But we should already test these exceptions in the validator block, so I'll leave it up to you - not necessary.

File: quarkus/config-api/src/main/java/org/keycloak/config/BootstrapAdminOptions.java (hunk 2 above)
Comment (shawkins) [reply quarkus/config-api/src/main/java/org/keycloak/config/BootstrapAdminOptions.java:7]: It is not exposed, it was just moved from the appliancebootstrap.

Comment (mabartos) [reply quarkus/config-api/src/main/java/org/keycloak/config/BootstrapAdminOptions.java:7]: yep, right, I thought more like it's visible even when we do not have any expiration yet :P 

But it's a nitpick. LGTM

**Comment by mabartos** [comment]
@shawkins Please also update the approval files to have the `HelpCommandDistTest` passed.

**Comment by shawkins** [comment]
> @shawkins Please also update the approval files to have the `HelpCommandDistTest` passed.

Ok, it's been updated.

File: services/pom.xml [hunk 3]
```diff
@@ -246,7 +246,10 @@
             <groupId>org.keycloak</groupId>
             <artifactId>keycloak-model-storage-private</artifactId>
         </dependency>
-
+        <dependency>
+        	<groupId>org.keycloak</groupId>
+        	<artifactId>keycloak-config-api</artifactId>
+        </dependency>
```
Comment (vmuzikar) [inline services/pom.xml:252]: This introduces a dependency on a Quarkus dist module in one of the key server modules. IMHO the generic server modules should remain independent of any dist-specific modules. That said, even though `keycloak-config-api` is currently in the Quarkus module, it's not really Quarkus-dependant. It's a generic server config API. Therefore it should be ok to keep as is.

**Review by vmuzikar — APPROVED** [review]

File: services/pom.xml (hunk 3 above)
Comment (shawkins) [reply services/pom.xml:252]: @vmuzikar right, this seemed to be the lesser of several evils:
- have services depend upon keycloak-config-api - at least in theory this seems conceptually correct, but as you point out config-api is under quarkus. Moving keycloak-config-api away from quarkus is possible. The dependency on infinispan-commons is unused. However the quarkus-opentelemetry dependency is used for one enum - so that would have to be moved to being defined directly in the PropertyMapper layer. Alternatively we just change the dependency scope for these to something like provided so that it doesn't introduce any transitive considerations.
- have keycloak-config-api depend upon services, this seems odd given how broad services is
- duplicate the default values
- introduce yet another module

**Review by mabartos — APPROVED** [review]
LGTM as is.

File: services/pom.xml (hunk 3 above)
Comment (vmuzikar) [reply services/pom.xml:252]: Works for me as is. If we see issues with that we can change the scope to provided, as you suggested.
