### PR TITLE
NPE on Theme after upgrade to 21 when parent or import theme not exists

### LINKED ISSUE #17313: When upgrading from v20.0.2 to v21.0.0 I get a NPE on Theme
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

After trying to start the application I got the error described on: https://github.com/keycloak/keycloak/issues/17248

So I executed following command on the db as suggested:
`update realm set admin_theme = 'keycloak' where admin_theme is null`

This worked and now my server starts, but when I log in on the admin section, I get an error:
2023-02-27 15:48:30,310 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-7) Uncaught server error: 
java.lang.NullPointerException: Cannot invoke "org.keycloak.theme.Theme.getImportName()" because "theme" is null
	at org.keycloak.theme.DefaultThemeManager.loadTheme(DefaultThemeManager.java:119)
	at org.keycloak.theme.DefaultThemeManager.getTheme(DefaultThemeManager.java:68)
	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.setThemes(ServerInfoAdminResource.java:182)
	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.getInfo(ServerInfoAdminResource.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Looking at the code I see that findTheme(parentName, type); can return null and there is no nullpointer check before theme.getImportName()

Can this also be corrected in v21.0.1?
 

### Version

21.0.0

### Expected behavior

After the upgrade you should be able to log into the admin console and manage your realms, clients, identity providers...

They are visible in the dropdown to the left, but on the right the error message is shown due to the theme not being found.

### Actual behavior

error-in-admin
Source_code

### How to Reproduce?

```
    private Theme findTheme(String name, Theme.Type type) {
        for (ThemeProvider p : getProviders()) {
            if (p.hasTheme(name, type)) {
                try {
                    return p.getTheme(name, type);
                } catch (IOException e) {
                    log.errorv(e, p.getClass() + " failed to load theme, type={0}, name={1}", type, name);
                }
            }
        }
        return null;
    }
```
So maybe getProviders() is empty or p.getTheme(name, type) returns null

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
closes #17313

### CODE REVIEW

**Comment by mposolda** [comment]
Docs PR with the note in the "Upgrading guide" that custom themes using `keycloak` admin theme won't work: https://github.com/keycloak/keycloak-documentation/pull/1788

File: services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java [hunk 1]
```diff
@@ -179,16 +179,18 @@ private void setThemes(ServerInfoRepresentation info) {
 
             for (String name : themeNames) {
                 try {
-                    Theme theme = session.theme().getTheme(name, type);
-                    ThemeInfoRepresentation ti = new ThemeInfoRepresentation();
-                    ti.setName(name);
+                    Theme theme = session.theme().getTheme(name, type, false);
+                    if (theme != null) {
```
Comment (stianst) [inline services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java:183]: What about doing something like this instead of adding the overloaded method to ThemeManager:

```suggestion
                    Theme theme = session.theme().getTheme(name, type);
                    if (theme != null && theme.getName().equals(name)) {
```

File: server-spi/src/main/java/org/keycloak/models/ThemeManager.java [hunk 2]
```diff
@@ -26,6 +26,17 @@ public interface ThemeManager {
...
+    /**
+     * Returns the specified theme for the specified type.
+     *
+     * @param name
+     * @param type
+     * @param fallbackToDefaultTheme if true (the default) and theme is not found, this method will return built-in default theme instead. If false and theme is not found, this method will return null
+     * @return
+     * @throws IOException
+     */
+    Theme getTheme(String name, Theme.Type type, boolean fallbackToDefaultTheme) throws IOException;
```
Comment (stianst) [inline server-spi/src/main/java/org/keycloak/models/ThemeManager.java:38]: See below, but thinking we could do without this overloaded method, especially since it's only used in a single place.

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java [hunk 3]
```diff
@@ -106,20 +115,19 @@ private Theme loadTheme(String name, Theme.Type type) {
         List<Theme> themes = new LinkedList<>();
         themes.add(theme);
 
-        if (theme.getImportName() != null) {
-            String[] s = theme.getImportName().split("/");
-            themes.add(findTheme(s[1], Theme.Type.valueOf(s[0].toUpperCase())));
-        }
+        if (!processImportedTheme(themes, theme, name, type)) return null;
```
Comment (stianst) [inline services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:118]: Shouldn't this return the default theme?

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java [hunk 4]
```diff
@@ -106,20 +115,19 @@ private Theme loadTheme(String name, Theme.Type type) {
...
 
         if (theme.getParentName() != null) {
             for (String parentName = theme.getParentName(); parentName != null; parentName = theme.getParentName()) {
+                String currentThemeName = theme.getName();
                 theme = findTheme(parentName, type);
+                if (theme == null) {
```
Comment (stianst) [inline services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:124]: Shouldn't this return the default theme?

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 3 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:109]: Actually not as `loadTheme` is private method, which is supposed to return the theme itself just if it exists and if it is OK. Even before this PR, the method returned null in case that theme itself is not found. So I've just extended this to return null also in case that "parent" is null or "import" is null (which means theme was found, but is incorrect).

The fallback to default theme is already done in the calling method https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/theme/DefaultThemeManager.java#L68-L72 .

File: services/src/main/java/org/keycloak/theme/DefaultThemeManager.java (hunk 4 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/theme/DefaultThemeManager.java:115]: See my comment https://github.com/keycloak/keycloak/pull/17350#discussion_r1121871082

File: services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java (hunk 1 above)
Comment (mposolda) [reply services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java]: Updated as you suggested

**Comment by mposolda** [comment]
@stianst Can you please re-review? I've used separate commit if you want to see just the latest changes since last review (can squash it during merge).

I've updated to your suggestions - removed new method in `ThemeManager` and handled the case in the `ServerInfoAdminResource` itself.

Replied to your other comments.

**Review by stianst — APPROVED** [review]
