### PR TITLE
Fix DB Migration Script to 13.0.0

### LINKED ISSUE #9138: DB Migration Script to 13.0.0 failed
### Describe the bug

DB update failed  when upgrading from 11.0.3 to 15.1.0.

Reason:
In file  JpaUpdate13_0_0_MigrateDefaultRoles.java, the commit 6b8890f 23 november introduces a bug.

In the code, "realmId" has been replaced by "entry.getValue()" that represents realm name and not realm id. It should be replaced by "entry.getKey()" to be used.

### Version

15.1.0

### Expected behavior

Migration db OK and server start.

### Actual behavior

Migration failed at startup with foreign key error when migrating db on insert role statement.

### How to Reproduce?

In version 11.0.3,  create a realm, and then rename it in order to have realm.id != realm.name in db, and then stop keycloak and   start the new server version (15.1.0).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vramik**
Closes #9138

### CODE REVIEW

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate13_0_0_MigrateDefaultRoles.java [hunk 1]
```diff
@@ -48,34 +48,34 @@ protected void generateStatementsImpl() throws CustomChangeException {
...
                     .addColumnValue("ID", id)
-                    .addColumnValue("CLIENT_REALM_CONSTRAINT", entry.getValue())
+                    .addColumnValue("CLIENT_REALM_CONSTRAINT", entry.getKey())
                     .addColumnValue("CLIENT_ROLE", Boolean.FALSE)
                     .addColumnValue("DESCRIPTION", "${role_" + roleName + "}")
                     .addColumnValue("NAME", roleName)
-                    .addColumnValue("REALM_ID", entry.getValue())
-                    .addColumnValue("REALM", entry.getValue())
+                    .addColumnValue("REALM_ID", entry.getKey())
+                    .addColumnValue("REALM", entry.getKey())
```
Comment (hmlnarik) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate13_0_0_MigrateDefaultRoles.java:56]: Why is this change here?

**Review by hmlnarik — APPROVED** [review]

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate13_0_0_MigrateDefaultRoles.java (hunk 1 above)
Comment (vramik) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate13_0_0_MigrateDefaultRoles.java:56]: The `REALM` column was removed in one of  previous releases in this [commit](https://github.com/keycloak/keycloak/commit/185075d37305463c4e8e82673bb5f2799e094346#diff-b8c40559721894bb6d1c59b1df39894b1f773f903582bf68e5163c0563195127L86-L89). It could then have any value, it doens't affect anything. We might consider dropping the column in the future.

Comment (vramik) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate13_0_0_MigrateDefaultRoles.java:56]: https://github.com/keycloak/keycloak/issues/9164
