### PR TITLE
Avoid adding post.logout.redirect.uris if already defined as client attributes

### LINKED ISSUE #16992: upgrading from v18.0.2 to 19.0.3 or 20.0.3 fails with ERROR duplicate key value violates unique constraint "constraint_3c"
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Dear keycloak team,

we have been using dockerised versions of keycloak for some time. At the moment, we are using version 16.1.1 across the board.
An update to version 18.0.2 was easily possible. When updating to version 19.0.3 or 20.0.3, we received the following error message on one of our instances.

`2023-02-XX HH:MM:SS.521 UTC [36] STATEMENT:  INSERT INTO public.client_attributes (CLIENT_ID, NAME, VALUE) VALUES ('xx40xxxx-3b12-4525-xxxx-xxxcabxxxx6a', 'post.logout.redirect.uris', '+')`

The analysis showed that this client had already set the value. This was due to the fact that the client was provided to us by a partner, which was already running on version 20.0.x. We checked the JSON for the import and it already contained this attribute and so it was transferred to the database. However, the value cannot be found in the graphical overview of version 16.1.1 and 18.0.2.

If an update to a version >18.0.2 is now carried out, it fails with the error mentioned above. To verify the error, we exported the client, deleted the line, imported it again and carried out another update. This was successful and the attribute was set.

### Version

16.1.1 > 18.0.2 > 20.0.3

### Expected behavior

- Importing clients from newer version into older versions should be without the attribute
- the GUI should show all attributes
- the update would recognise the already existing value and not try to set it again

### Actual behavior

- the update tries to set a already existing value again
- the GUI doesn't show all attributes
- Importing clients from newer version into older versions write attributes (ghostly) that can't be seen in the GUI

### How to Reproduce?

 - generating a client in a version > 18.0.2 with the attribute 'post.logout.redirect.uris'
 - exporting this client
 - importing in 16.1.1
 - try to update to an version > 18.0.2 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/16992

Just adding a `not in` to avoid adding the `post.logout.redirect.uris` if already defined in the client. Just the name is used to avoid issues searching using the CLOB value column.

### CODE REVIEW

**Comment by mposolda** [comment]
@hmlnarik Can you please review this or delegate to someone from store team?

My concerns are:

1) Performance - as Keycloak deployments can have thousands of clients in multiple realms. Can we update the statement in `JpaUpdate19_0_0_DefaultPostLogoutRedirectUri` to use 1 "insert" instead of using separate insert for each client? Basically something like https://www.w3schools.com/sql/sql_insert_into_select.asp ? I though it was already done this way originally, but apparently I was wrong and likely also overlooked this during the review of the original PR, which introduced this...:(

@rmartinc I know that performance was out of scope of this bug, but can you please update this to use that way when you're at it? AFAIK nobody yet reported performance issues, but it is possible that people may report them later once we use product (as it is higher chance that "product deployments" have higher number of clients than "community deployments")

@hmlnarik Do you agree with the above?
 
2) I am not 100% sure if we can update already existing changesets this way? AFAIR there are issues with updating old changelogs in case that something in some older file `jpa-changelog-*.xml` is updated, because in the case when some old changeset is updated, then the "liquibase checksum" would fail (for example for people, who are migrating from Keycloak 20.0.0 to Keycloak 22.0.0 as the changeset for version 19 was already triggered from them). However I think that changing custom java files triggered from changelogs is fine and should work? Anyone from the "store" team is aware if this would work?

**Comment by rmartinc** [comment]
@mposolda I think you are right in your two sentences.

1. I didn't think about that change and I just followed the same idea to fix teh issue. But you are roght, you can do a INSERT SELECT and it's done in previous releases for example [here](https://github.com/keycloak/keycloak/blob/21.0.2/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate13_0_0_MigrateDefaultRoles.java#L68-L71). I have updated the PR with the change.
2. I have tested my change doing just one step 17->999 and 17->19->999 (mariadb and postgresql). No issues for the moment. I'm not changing the xml, just the class executed. So if it was executed before there is no problem. For new updates the new INSERT is executed.

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks! I think it is correct and aI am approving. I would like also the opinion from the store team.

File: model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate19_0_0_DefaultPostLogoutRedirectUri.java [hunk 1]
```diff
@@ -17,32 +17,21 @@
...
-            }
-        } catch (Exception e) {
-            throw new CustomChangeException(getTaskId() + ": Exception when extracting data from previous version", e);
-        }
+        final String clientAttributesTable = getTableName("CLIENT_ATTRIBUTES");
+        final String redirectUrisTable = getTableName("REDIRECT_URIS");
+        statements.add(new RawSqlStatement(
+                "INSERT INTO " + clientAttributesTable + " (CLIENT_ID,NAME,VALUE) " +
+                "SELECT DISTINCT CLIENT_ID, '" + POST_LOGOUT_REDIRECT_URIS + "', '+' FROM " + redirectUrisTable + " WHERE CLIENT_ID NOT IN " +
+                "(SELECT CLIENT_ID FROM " + clientAttributesTable + " WHERE NAME = '" + POST_LOGOUT_REDIRECT_URIS + "')"
```
Comment (hmlnarik) [inline model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate19_0_0_DefaultPostLogoutRedirectUri.java:33]: The intention of this command is correct.

However the syntax may vary slightly per database vendor. Has this command been tried on all supported databases?

Comment (rmartinc) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate19_0_0_DefaultPostLogoutRedirectUri.java:33]: @hmlnarik Not in all (I personally tested in H2, mariadb/mysql and postgresql), but I have checked there similar SQLs in other upgrade classes like [here](https://github.com/keycloak/keycloak/blob/21.0.2/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate13_0_0_MigrateDefaultRoles.java#L68-L71). I can check in MSSQL too but I cannot test in Orcale (but I'm almost sure this is going to work in both of them).

Comment (rmartinc) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate19_0_0_DefaultPostLogoutRedirectUri.java:33]: Tested in MSSQL 2022 too, it works. So only oracle is missing. But I think that the syntax is OK with Oracle.

Comment (mposolda) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate19_0_0_DefaultPostLogoutRedirectUri.java:33]: @rmartinc I've sent you some notes (by email) how to test with Oracle docker image

In general, it will be better if we can rely on automated tests, and pipeline. However at the same time, I understand that sometimes it is safer to test things manually (also not sure about our pipeline state and if/how is possible to test migration here).

Comment (mposolda) [reply model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate19_0_0_DefaultPostLogoutRedirectUri.java:33]: Thanks!

I've already approved this PR and from my point of view, it is good to go.

@hmlnarik WDYT?

**Review by hmlnarik — APPROVED** [review]
Approving, thanks for checking the remaining databases.

**Comment by chethankumar4046** [comment]
@mposolda @hmlnarik @rmartinc 
Still i am getting same kind of error while migrating to 22.0.1 from 18.0.2-legacy 
```2023-08-16 13:03:04,154 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-19.0.0.xml::19.0.0-10135::keycloak:
     Reason: liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "constraint_3c"
  Detail: Key (client_id, name)=(5bca7e33-ad7b-4a99-a5b2-436f370041c6, post.logout.redirect.uris) already exists. [Failed SQL: (0) INSERT INTO public.client_attributes (CLIENT_ID, NAME, VALUE) VALUES ('5bca7e33-ad7b-4a99-a5b2-436f370041c6', 'post.logout.redirect.uris', '+')]
2023-08-16 13:03:04,154 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: duplicate key value violates unique constraint "constraint_3c"
  Detail: Key (client_id, name)=(5bca7e33-ad7b-4a99-a5b2-436f370041c6, post.logout.redirect.uris) already exists. [Failed SQL: (0) INSERT INTO public.client_attributes (CLIENT_ID, NAME, VALUE) VALUES ('5bca7e33-ad7b-4a99-a5b2-436f370041c6', 'post.logout.redirect.uris', '+')]
2023-08-16 13:03:04,154 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: duplicate key value violates unique constraint "constraint_3c"
  Detail: Key (client_id, name)=(5bca7e33-ad7b-4a99-a5b2-436f370041c6, post.logout.redirect.uris) already exists.
2023-08-16 13:03:04,154 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.```
