### PR TITLE
Issue with Handling Negative Values in Certain Fields of Brute Force Detection

### LINKED ISSUE #40353: Issue with Handling Negative Values in Certain Fields of Brute Force Detection
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When configuring and enabling **"Brute Force Detection"** within the authentication settings of any realm, it is possible to enter negative values for fields such as Max Login Failures and Max Wait. These negative values are then stored as-is in the Keycloak database. However, from a logical standpoint, such negative values are invalid and should not be allowed. 

The proper solution would be to validate these values within the realm adapter’s setters before they are assigned, ensuring that invalid (negative) inputs are rejected early on.

### Version

26.2.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that providing a negative value should trigger an exception, indicating that the value is invalid and not acceptable.

### Actual behavior

Currently, negative values entered in the mentioned fields are stored, but they behave the same way as if the value were set to 1.

### How to Reproduce?

Navigate to your desired realm, go to the Authentication section, then select Security Defenses and choose Brute Force Detection.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #40353

### CODE REVIEW

File: model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java [hunk 1]
```diff
@@ -326,7 +334,9 @@ public int getMinimumQuickLoginWaitSeconds() {
 
     @Override
     public void setMinimumQuickLoginWaitSeconds(int val) {
-        setAttribute("minimumQuickLoginWaitSeconds", val);
+        if(val >= 0) {
+            setAttribute("minimumQuickLoginWaitSeconds", val);
```
Comment (rmartinc) [inline model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java]: Would not be better to do this in the DefaultExportImportManager (updateRealm and importRealm methods). And I would prefer to throw an exception (ModelException or similar) that will return a 400 bad request for the endpoint. The same for all the properties.

**Review by rmartinc — CHANGES_REQUESTED** [review]
@douglaspalmer I think that it would better to check this when moving from rep to model in the `DefaultExportImportManager`. And I always prefer to return an error than doing nothing. WDYT?

And try with this commit https://github.com/rmartinc/keycloak/commit/2204992575ab93b019f485e3a75d0a5fd70482bb in the UI part. It's not perfect but much better.

File: model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java (hunk 1 above)
Comment (douglaspalmer) [reply model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java]: Done

**Review by rmartinc — CHANGES_REQUESTED** [review]
Don't you like the changes in the UI https://github.com/rmartinc/keycloak/commit/2204992575ab93b019f485e3a75d0a5fd70482bb ?

**Review by rmartinc — APPROVED** [review]
@douglaspalmer For me it's OK. But maybe adding a method to all the calls would more readable:

```java
public static int checkNonNegativeNumber(int value, String name) {
    if(value < 0) {
        throw new ModelException(name + " may not be a negative value");
    }
    return value;
}
```

And just call it something line:

```java
if (rep.getMaxTemporaryLockouts() != null) {
    newRealm.setMaxTemporaryLockouts(checkNonNegativeNumber(rep.getMaxTemporaryLockouts(), "Maximum temporary lockouts"));
}
```

Besides this way we execute the CI again to remove the failure. But the idea is OK, it's just an improvement.

**Review by rmartinc — APPROVED** [review]
Thanks @douglaspalmer! LGTM!

**Review by ssilvert — APPROVED** [review]
Approved the UI part.

**Review by edewit — APPROVED** [review]

**Review by abstractj — APPROVED** [review]
