### PR TITLE
Cache empty results for role-by-name lookup

### LINKED ISSUE #36919: Latency issue after Keycloak version upgrade
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

This was raised on the Keycloak user mailing list: https://groups.google.com/g/keycloak-user/c/6UwBBV8GcY0/m/wXfuxDoQDQAJ

We are currently utilizing Keycloak version 22.0.4 and are in the process of upgrading to version 25.0.6. During our performance testing following the upgrade, we are encountering latency issues, particularly during the authorization phase. We are using the same database as in the previous version.

I am wondering why the below query runs multiple times (20k) after the keycloak version upgrade to 25.0.6.

```
select re1_0.ID from KEYCLOAK_ROLE re1_0 where re1_0.CLIENT_ROLE=0 and re1_0.NAME=? and re1_0.REALM_ID=?
binding parameter (1:NVARCHAR) <- [8bee0f28-9795-4668-8ec8-602e82259aa5]
binding parameter (2:VARCHAR) <- [master]
```

I have conducted validation in Keycloak version 26.1; however, we continue to experience the same query being executed multiple times, and we are not utilizing any custom extensions.

Additionally, I would like to point out that with captured thread dumps, it appears this issue may be originating from here:
https://github.com/keycloak/keycloak/blob/d767c784c9e5bf60e5933162840d536baab8896a/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java#L221

Thanks,
Naresh Kumar

### Version

26.1.0

### Regression

- [x] The issue is a regression

### Expected behavior

With the fine grained authorizations enabled, Keycloak should still be fast. 

### Actual behavior

There are a lot of unnecessary SQL queries.

### How to Reproduce?

Use an authorization role policy with the ID of the role. 

### Anything else?

@ahus1 is looking into this.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #36919

### CODE REVIEW

**Comment by ahus1** [comment]
@pedroigor - this is the change we talked about earlier today. It implements both changes; let me know what you think of this change. Thanks!

**Comment by ahus1** [comment]
@pruivo - this is me changing the serialization and invalidation for the first time. Please let me know your thoughts on this. Thanks!

**Comment by pruivo** [comment]
> @pruivo - this is me changing the serialization and invalidation for the first time. Please let me know your thoughts on this. Thanks!

It looks fine to me.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java [hunk 1]
```diff
@@ -856,13 +857,21 @@ public RoleModel getRealmRole(RealmModel realm, String name) {
...
+                query = new RoleListQuery(loaded, cacheKey, realm, Set.of());
+            } else {
+                query = new RoleListQuery(loaded, cacheKey, realm, model.getId());
+            }
             logger.tracev("adding realm role cache miss: client {0} key {1}", realm.getName(), cacheKey);
             cache.addRevisioned(query, startupRevision);
             return model;
         }
-        RoleModel role = getRoleById(realm, query.getRoles().iterator().next());
+        Iterator<String> iterator = query.getRoles().iterator();
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java:870]: line 904 may need the same logic. 
I would probably add a method `getAny` to `RoleListQuery`.

File: authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java [hunk 2]
```diff
@@ -210,6 +211,8 @@ private Set<RoleDefinition> getRoles(String rawRoles, RealmModel realm) {
         return Collections.emptySet();
     }
 
+    public static final Pattern UUID_PATTERN = Pattern.compile("[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}");
+
     private RoleModel getRole(RolePolicyRepresentation.RoleDefinition definition, RealmModel realm) {
         String roleName = definition.getId();
```
Comment (pruivo) [inline authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java:217]: As an outside contributor, It is weird why `getId` returns `roleName` and we check for both id and name :shrug:

**Review by pruivo — CHANGES_REQUESTED** [review]

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java (hunk 1 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java:870]: I would be tempted to make it `getOneOrNoRole` and make it throw an exception when there is more than one. And then I am thinking this is overengineered. Now I'm undecided, so I am not sure if I should add it. 
Besides, also added the caching of no entry for client role by name.

File: authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java (hunk 2 above)
Comment (ahus1) [reply authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java:217]: It is a mess IMHO. I would hope that in a V2 version of the API we could get rid of it.

**Review by pruivo — APPROVED** [review]

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java (hunk 1 above)
Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java:870]: Creating a new class to cache the query by name would be better. 
The PR looks good to me.

**Comment by pruivo** [comment]
@ahus1 @pedroigor is the user going to test this patch? I have some concerns since the cache is bounded, and caching the empty results of the query will remove another cached key.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java (hunk 1 above)
Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java]: Picked up the suggestion for a new class in the latest commit to this PR. Please have a look. The `getRoles()` is still needed to comply with the interface.

**Comment by ahus1** [comment]
> is the user going to test this patch? I have some concerns since the cache is bounded, and caching the empty results of the query will remove another cached key.

I assume the user might test it in a nightly release, but not in this PR. Yes, this could lead to a higher cache turnover. Still I hope that Infinispan would adjust to keep more frequently used items in the cache. Even with a higher cache turnover, I think this one is still faster as the cache hits will outweight the DB activity, and ISPN will keep those entries in memory that are hot. 

For the case at hand, due to checking if the string is a UUID, I don't expect any additional entries to be in the cache anyway for this particular case. There might be other users who are affected by the earlier not-caching, and they will see an improvement.

**Comment by ahus1** [comment]
@pruivo - please re-review the latest change that reworks the code as suggested with a new class. Once that's in, IMHO it is the ready for merging.

File: model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/RoleByNameQuery.java [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+import java.util.Set;
+
+/**
+ * @author Alexander Schwartz
+ * @version $Revision: 1 $
+ */
+public class RoleByNameQuery extends AbstractRevisioned implements RoleQuery, InClient {
+    private final String role;
+    private final String realm;
+    private final String realmName;
```
Comment (pruivo) [inline model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/RoleByNameQuery.java:30]: `realmName` does not seem to be used. Same for `RoleListQuery`.

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/RoleByNameQuery.java:30]: It is implementing the `InRealm` interface which needs it. This is used to remove entries that belong to a realm, see for example 

https://github.com/keycloak/keycloak/blob/18a6c790113998bf039f46d6c71ffb668e961036/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/stream/InRealmPredicate.java#L41

Comment (pruivo) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/RoleByNameQuery.java:30]: Isn't that the realm ID?

Comment (ahus1) [reply model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/RoleByNameQuery.java:30]: Ok, I stand corrected. I'll create a follow-up PR on this one once @pedroigor approves the rest of the PR.

**Review by pedroigor — APPROVED** [review]
