### PR TITLE
remove status and use badge for special case

### LINKED ISSUE #24470: User status shows as "-" when user is enabled
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

User status is showing in the user data table as "-" when the user is enabled, leading to some confusion in the actual status of the user

### Version

Nightly

### Expected behavior

User status should show something more informative like "Enabled" 

### Actual behavior

Status shows as "-"

### How to Reproduce?

Navigate to user table in keycloak admin UI

### Anything else?

Appears to be an issue with this section of code in UserDataTable component: 

```
const StatusRow = (user: BruteUser) => {
    return (
      <>
        {!user.enabled && (
          <Label key={user.id} color="red" icon={<InfoCircleIcon />}>
            {t("disabled")}
          </Label>
        )}
        {user.bruteForceStatus?.disabled && (
          <Label key={user.id} color="orange" icon={<WarningTriangleIcon />}>
            {t("temporaryLocked")}
          </Label>
        )}
        {user.enabled && !user.bruteForceStatus?.disabled && "—"}
      </>
    );
  };
```

### PR DESCRIPTION
**Pull request by edewit**
removed status row and use badge

fixes: #24470

### CODE REVIEW

File: js/apps/admin-ui/src/components/users/UserDataTable.tsx [hunk 1]
```diff
@@ -49,6 +49,57 @@ export type UserAttribute = {
   value: string;
 };
 
+const UserDetailLink = (user: BruteUser) => {
+  const { realm } = useRealm();
+  return (
+    <Link
+      key={user.username}
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/users/UserDataTable.tsx:56]: No need to provide a `key` here.
```suggestion
```

File: js/apps/admin-ui/src/components/users/UserDataTable.tsx [hunk 2]
```diff
@@ -49,6 +49,57 @@ export type UserAttribute = {
...
+type StatusRowProps = {
+  user: BruteUser;
+};
+
+const StatusRow = ({ user }: StatusRowProps) => {
+  const { t } = useTranslation();
+  return (
+    <>
+      {!user.enabled && (
+        <Label key={user.id} color="red" icon={<InfoCircleIcon />}>
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/users/UserDataTable.tsx:73]:
```suggestion
        <Label color="red" icon={<InfoCircleIcon />}>
```

File: js/apps/admin-ui/src/components/users/UserDataTable.tsx [hunk 3]
```diff
@@ -49,6 +49,57 @@ export type UserAttribute = {
...
+          {t("disabled")}
+        </Label>
+      )}
+      {user.bruteForceStatus?.disabled && (
+        <Label key={user.id} color="orange" icon={<WarningTriangleIcon />}>
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/users/UserDataTable.tsx:78]:
```suggestion
        <Label color="orange" icon={<WarningTriangleIcon />}>
```

File: js/apps/admin-ui/src/components/users/UserDataTable.tsx [hunk 4]
```diff
@@ -49,6 +49,57 @@ export type UserAttribute = {
...
+  );
+};
+
+const ValidatedEmail = (user: UserRepresentation) => {
+  const { t } = useTranslation();
+  return (
+    <>
+      {!user.emailVerified && (
+        <Tooltip
+          key={`email-verified-${user.id}`}
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/users/UserDataTable.tsx:92]:
```suggestion
```

File: js/apps/admin-ui/src/components/users/UserDataTable.tsx [hunk 5]
```diff
@@ -49,6 +49,57 @@ export type UserAttribute = {
...
+          content={<>{t("notVerified")}</>}
```
Comment (jonkoops) [inline js/apps/admin-ui/src/components/users/UserDataTable.tsx:93]: Do we need a fragment here?
```suggestion
          content={t("notVerified")}
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by jonkoops — APPROVED** [review]
